# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de '1984' (George Orwell)."""

BOOK = {
 "title": "1984",
 "author": "George Orwell",
 "header_light": "GEORGE",
 "header_bold": "ORWELL",
 "subtitle": "VISÃO GERAL · O TOTALITARISMO E O FIM DA VERDADE",
 "intro": "Era um dia frio e claro de abril, e os relógios batiam treze horas. Em Oceania, o Partido não se contenta em mandar nos corpos: ele edita o passado, encolhe a língua e quer ser o dono do que se passa dentro do seu crânio. Winston Smith comete o único crime que importa — pensar por conta própria. Orwell não previu gadgets; ele dissecou o desejo eterno do poder de ter <em>tudo</em>, inclusive a sua certeza de que dois mais dois são quatro. A pergunta que ele deixa não envelhece: <em>o que sobra do humano quando a bota encontra o rosto — e o rosto aprende a amar a bota?</em>",
 "description": "Romance distópico de George Orwell (1949). Em Oceania, o Partido (INGSOC) governa pela inversão do sentido e pela vigilância da teletela; Winston Smith reescreve a história no Ministério da Verdade e ama Julia até ser quebrado por O'Brien. Grande Irmão, duplipensar, Novafala, crime de pensamento, o buraco da memória, '2+2=5', o Quarto 101 e o poder pelo poder — o vocabulário do totalitarismo moderno, lido como mapa do que o poder faz quando não há mais quem o impeça.",
 "tags": ["Distopia", "Política", "Totalitarismo"],
 "progress": "9 Capítulos",
 "cover": "assets/1984-cover.png",
 "overview_cards": [
   {"ic":"eye","t":"Vigilância como Ambiente","b":"A teletela vê, ouve e não desliga — mas o que de fato governa não é o olho: é a <strong>dúvida sobre quando o olho está aberto</strong>. Como você nunca sabe se há alguém do outro lado, passa a viver como se houvesse sempre. O Grande Irmão dispensa o carcereiro: ele instala um dentro da sua cabeça.","tip":"<strong>Modelo mental:</strong> o terror eficiente não precisa da câmera ligada — basta a câmera possível."},
   {"ic":"bubble","t":"Novafala: a Prisão da Língua","b":"Tire a palavra 'liberdade' e veja quanto tempo o desejo de ser livre sobrevive sem nome. A Novafala não proíbe o que se diz — <strong>amputa as palavras com que se pensaria a recusa</strong>. A cada dicionário mais fino, encolhe também o tamanho do mundo que cabe na sua mente.","tip":"<strong>Para refletir:</strong> quem define o léxico define a fronteira do pensável — e do desejável."},
   {"ic":"layers","t":"Os Três Lemas","b":"<strong>Guerra é Paz · Liberdade é Escravidão · Ignorância é Força.</strong> Não são slogans tolos: são o duplipensar feito governo — a arte de abraçar duas verdades opostas ao mesmo tempo sem sentir o atrito. Quando a mentira ocupa o lugar do óbvio sem ninguém piscar, a inversão já venceu.","tip":"<strong>Modelo mental:</strong> torcer o sentido das palavras é o primeiro decreto de todo regime total.","wide":True},
   {"ic":"sword","t":"Poder pelo Poder","b":"O Partido não oprime <em>para</em> chegar a lugar nenhum — a opressão é o destino. \"<strong>Imagine uma bota pisando um rosto humano — para sempre.</strong>\" O poder se prova rasgando carne e convertendo o inimigo, não matando: o cadáver não sente nada, e o que o regime quer é que você sinta tudo e ainda aplauda.","tip":"<strong>Para refletir:</strong> desconfie de toda causa que pede a sua alma, e não só a sua obediência.","warn":True},
 ],
}

CHAPTERS = [
 {"slug":"ch01-oceania-grande-irmao-ingsoc","sub":"CAPÍTULO 1: Oceania, o Grande Irmão e o INGSOC",
  "intro":"Antes de Winston mexer um dedo, Orwell ergue a verdadeira protagonista: a máquina. Um mundo lacrado de teletelas que nunca dormem, de palavras viradas do avesso e de uma guerra que não quer acabar — desenhado, parede por parede, para que não exista a porta dos fundos. Você entra em Oceania pelo cheiro de repolho cozido e pela cara do cartaz: o GRANDE IRMÃO ESTÁ VIGIANDO VOCÊ.",
  "cards":[
      {"ic":"eye","t":"A Vigilância que Vigia","emph":"Vigilância","b":"A teletela transmite e capta no mesmo instante; você nunca sabe se há um olho do outro lado da tela. <strong>A engenharia genial não é observar todo mundo — é fazer todo mundo viver como se estivesse sendo observado.</strong> Assim o medo se aloja na nuca, e o Grande Irmão deixa de ser cartaz na parede para virar magistrado dentro do seu crânio.","tip":"<strong>Modelo mental:</strong> o controle total não paga carcereiros — convence a vítima a vigiar a si mesma de graça."},
      {"ic":"layers","t":"A Inversão do Sentido","emph":"Inversão","b":"Guerra é Paz. Liberdade é Escravidão. Ignorância é Força. <strong>Quando o Estado ensina você a chamar a corrente de proteção, não há mais chão lógico onde firmar o pé.</strong> Repare nos quatro Ministérios: o do Amor tortura, o da Verdade fabrica mentira, o da Fartura administra a fome. O nome jura o contrário do que a coisa faz — e o espanto, com o tempo, vira hábito.","tip":"<strong>Sinal de alerta:</strong> o poder que entorta o vocabulário não quer só calar você — quer confiscar a ferramenta com que você pensaria a recusa."},
      {"ic":"target","t":"A Guerra que Não Quer Vencer","emph":"Guerra","b":"Oceania luta sem fim contra superestados que talvez nem existam — e o objetivo não é a vitória, é gastar. Queimar o excedente que, em paz, sobraria para o povo. <strong>A emergência permanente mantém todos pobres, com fome e gratos a quem promete defendê-los.</strong> A bomba não precisa atingir o inimigo: basta cair perto o bastante para renovar o medo de cada dia.","tip":"<strong>Prática:</strong> diante de qualquer crise sem prazo de validade, pergunte a quem serve que ela jamais termine."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["A vigilância apenas possível disciplina mais que a vigilância de fato constante.","Capturar a linguagem é capturar o pensamento — e isso vem antes de capturar os corpos.","A guerra perpétua é ferramenta de controle interno, não projeto de conquista externa."]},

 {"slug":"ch02-winston-diario-crime-de-pensamento","sub":"CAPÍTULO 2: Winston, o Diário e o Crime de Pensamento",
  "intro":"A rebelião não nasce com uma bomba — nasce com uma caneta. Winston abre um diário comprado às escondidas e escreve a primeira frase proibida; no segundo em que o pensamento vira tinta, ele se sabe um homem morto que ainda anda. É o que o regime mais teme: não o que você faz, mas o que você guarda lá dentro.",
  "cards":[
      {"ic":"book","t":"O Crime de Pensamento","emph":"Pensamento","b":"Não é preciso conspirar em voz alta nem empunhar arma alguma — duvidar em silêncio, sozinho, dentro do próprio crânio, já é a ofensa máxima. <strong>O totalitarismo acabado não persegue o seu gesto; ele invade e incrimina a sua intimidade.</strong> Por isso Winston abre o diário com a certeza serena de quem assina a própria sentença: o pensamento, ali, já é cadáver.","tip":"<strong>Modelo mental:</strong> o direito de pensar a sós é o último muro entre você e o abismo — e é exatamente esse muro que o poder vem derrubar."},
      {"ic":"mask","t":"Autocensura como Segunda Pele","emph":"Autocensura","b":"Você administra o olhar, congela os músculos do rosto, regula a respiração — porque uma careta errada diante da teletela é o <em>facecrime</em>, e basta. <strong>Quando até o seu próprio filho é treinado para denunciá-lo por um murmúrio no sono, a confiança entre as pessoas seca pela raiz.</strong> A Polícia do Pensamento já venceu antes de bater na porta: ela mora em você.","tip":"<strong>Armadilha:</strong> o pior cárcere é o que dispensa as grades, porque transformou o prisioneiro no carcereiro de si mesmo.","warn":True},
      {"ic":"spark","t":"A Memória que Acusa","emph":"Memória","b":"Um gosto antigo de chocolate de verdade, um pedaço de cantiga que ninguém mais sabe, a teima de que o passado era menos cinzento. <strong>O menor caco de lembrança verdadeira é flagrante de que o Partido mente.</strong> Num mundo onde a história é reescrita toda noite, lembrar com fidelidade é o gesto mais subversivo que existe.","tip":"<strong>Regra:</strong> proteger a própria memória é proteger a única lente capaz de desmentir a loucura oficial."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["O alvo do totalitarismo não é o comportamento, é a interioridade — pensar errado já basta.","A delação generalizada converte a sociedade inteira, família inclusive, em aparelho de vigilância.","A memória pessoal é a prova mais perigosa que existe contra a versão oficial da história."]},

 {"slug":"ch03-novafala-linguagem-como-prisao","sub":"CAPÍTULO 3: Novafala — a Linguagem como Prisão",
  "intro":"A Novafala não é mais um idioma — é a engenharia de tornar certos pensamentos impossíveis. Ano após ano, o Partido encolhe o dicionário de propósito, com orgulho, até o dia em que a palavra 'liberdade' não exista para ninguém formular o desejo dela. A finalidade da Novafala, dizem seus arquitetos, é estreitar o âmbito do pensamento. Matar a heresia antes que ela ache as palavras para nascer.",
  "cards":[
      {"ic":"bubble","t":"Sem a Palavra, Sem o Desejo","emph":"Sem a Palavra","b":"Tente querer ser livre sem dispor da palavra 'liberdade' — e sinta o desejo perder o contorno, virar um incômodo sem nome. <strong>A censura mais letal não queima livros: amputa o vocabulário pela raiz.</strong> Quando o dicionário encolhe, o seu mundo interior encolhe junto, até não restar espaço onde a rebeldia caiba.","tip":"<strong>Modelo mental:</strong> quem governa as palavras que você usa traça, sem você notar, a fronteira do que você é capaz de desejar."},
      {"ic":"lens","t":"Encolher é Política de Estado","emph":"Encolher","b":"Na Novafala, cada nova edição do dicionário é mais magra que a anterior — e isso se comemora, como quem comemora uma colheita. <strong>Menos palavras significam menos nuances, menos dúvidas e muito mais obediência sem ruído.</strong> A lucidez de quem enxerga a engrenagem girando é justamente o que não pode sobreviver.","tip":"<strong>Sinal de alerta:</strong> o discurso que achata a realidade até caber num slogan está, em silêncio, esvaziando a sua inteligência.","warn":True},
      {"ic":"key","t":"A Língua que Constrói o Mundo","emph":"Língua","b":"A linguagem deixa de ser espelho que descreve o que existe e vira cerca que define o que pode existir. <strong>O 'bompensar' já vem montado na própria gramática, de modo que a heresia se torne literalmente impronunciável.</strong> O controle definitivo não acontece na rua, com cassetetes — acontece na sua garganta, antes do gesto.","tip":"<strong>Prática:</strong> recuse o chavão e o slogan pronto; a língua empobrecida é a antessala mansa da servidão."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["A censura mais radical não proíbe o texto — apaga a palavra; sem palavra, não há pensamento.","Empobrecer deliberadamente a língua é projeto de Estado em todo regime total.","Quando a língua só descreve o mundo permitido, a resistência fica literalmente sem o que dizer."]},

 {"slug":"ch04-duplipensar-controle-do-passado","sub":"CAPÍTULO 4: Duplipensar e o Controle do Passado",
  "intro":"Dois mecanismos gêmeos sustentam Oceania de pé. O duplipensar permite crer ao mesmo tempo em duas verdades que se excluem, sem sentir o solavanco. O controle do passado reescreve a história todo dia para que o presente sempre confirme o Partido. Onde os dois operam juntos, a realidade deixa de ser firme — e até dizer que dois mais dois são quatro vira ato de fé proibido.",
  "cards":[
      {"ic":"spiral","t":"Crer nas Duas Verdades","emph":"Duas Verdades","b":"Você sabe que o Partido mente e, ao mesmo tempo, crê com devoção que ele jamais erra. <strong>O duplipensar é o músculo da mente que permite habitar o absurdo sem desabar na loucura.</strong> Não é hipocrisia, que ao menos sabe que finge — é a convicção sincera de que dois polos opostos são, os dois, inteiramente verdadeiros.","tip":"<strong>Armadilha:</strong> o autoengano treinado é o cárcere mais difícil de arrombar, porque é você quem gira a chave por dentro."},
      {"ic":"clock","t":"Quem Controla o Passado","emph":"Passado","b":"O ofício de Winston é reescrever jornais velhos para que a história de ontem obedeça ao decreto de hoje; o inconveniente desce pelo buraco da memória. <strong>Sem um passado sólido e conferível, some o chão — e com ele some a própria ideia de verdade objetiva.</strong> Quem controla o passado controla o futuro, e quem controla o presente controla o passado.","tip":"<strong>Sinal de alerta:</strong> apagar a memória histórica nunca é descuido; é a fundação sobre a qual se ergue o futuro inventado.","warn":True},
      {"ic":"target","t":"A Última Conta que Resta","emph":"A Conta","b":"A liberdade derradeira talvez seja esta: poder dizer que dois mais dois são quatro, e que daí decorre o resto. <strong>No instante em que a dor te obriga a enxergar cinco dedos onde há quatro, a fundação inteira da razão racha.</strong> Dobrar a percepção fria dos fatos é o xeque-mate mais cruel — porque depois dele você não tem mais de onde discordar.","tip":"<strong>Regra:</strong> defender a evidência mais boba e matemática é a trincheira final contra o delírio decretado."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["O duplipensar é o que torna o totalitarismo habitável por dentro — convicção genuína, não mera hipocrisia.","Destruir a memória é destruir a base sobre a qual a verdade objetiva poderia existir.","A razão (2+2=4) é a última trincheira da liberdade — e por isso é o alvo predileto do poder."]},

 {"slug":"ch05-julia-rebeliao-pelos-sentidos","sub":"CAPÍTULO 5: Julia e a Rebelião pelos Sentidos",
  "intro":"Contra um regime que coloniza a mente, sobra uma só arma: a carne e o que é seu. Winston e Julia se amam num quarto alugado, e cada beijo é um ato político — energia roubada do ódio que o Partido exigia. Mas há um detalhe terrível: o oásis foi armado de fora para dentro. O refúgio é a isca.",
  "cards":[
      {"ic":"person","t":"O Desejo como Sabotagem","emph":"Desejo","b":"O Estado quer a energia sexual canalizada para o ódio cívico, despejada nos Dois Minutos de Ódio e nas marchas — daí a Liga Anti-Sexo. <strong>Fazer amor pelo puro prazer, sem dever a ninguém, vira um motim silencioso contra a histeria coletiva.</strong> Onde a mente foi ocupada palmo a palmo, o corpo é o último território não anexado.","tip":"<strong>Modelo mental:</strong> num mundo que cobra sacrifício o tempo todo, a alegria privada e gratuita é, em si, um crime."},
      {"ic":"fork","t":"Duas Rebeldias pela Metade","emph":"Duas Rebeldias","b":"Julia burla o sistema de baixo para cima, para rir e gozar o agora; Winston quer derrubá-lo de cima para baixo, lendo teoria. <strong>Prática sem ideia e ideia sem prática são esmagadas exatamente do mesmo jeito pela engrenagem.</strong> Nenhuma das duas, sozinha, deixa um arranhão sequer na superfície do Partido.","tip":"<strong>Para refletir:</strong> fugir pelas beiradas ou apenas filosofar não basta — a resistência de verdade exigiria as duas coisas, e elas nunca se completam."},
      {"ic":"gap","t":"O Refúgio é a Ratoeira","emph":"Refúgio","b":"O quartinho sobre a loja do Sr. Charrington, com suas velharias doces, parecia um pedaço de mundo que o Estado tinha esquecido. <strong>A perversidade suprema é o poder fabricar ele mesmo o esconderijo, para atrair e abater a presa que ousou duvidar.</strong> O conforto de crer que você escapou é a isca mais letal da caçada inteira.","tip":"<strong>Sinal de alerta:</strong> quando um sistema total deixa uma porta convidativamente aberta, costuma haver um matadouro do outro lado.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Onde o poder reivindica toda a energia emocional, o desejo e a intimidade viram atos subversivos.","Rebeldia prática (Julia) e rebeldia teórica (Winston) só resistiriam unidas — e o regime as mantém separadas.","Regimes totais chegam a fabricar refúgios falsos para capturar justamente quem tenta escapar."]},

 {"slug":"ch06-livro-de-goldstein-teoria-do-poder","sub":"CAPÍTULO 6: O Livro de Goldstein e a Teoria do Poder",
  "intro":"No auge da ilusão de que resiste, Winston recebe das mãos de O'Brien o livro proibido de Goldstein — a teoria e prática do coletivismo oligárquico. As páginas explicam com frieza o COMO da máquina: a guerra perpétua, as três classes, a engrenagem que se trava. Só não explicam o porquê — e Winston vai descobrir que entender tudo não move uma só dobradiça da cela.",
  "cards":[
      {"ic":"layers","t":"A Roda que Pararam","emph":"A Roda","b":"A história sempre girou entre os de Cima, os do Meio que querem subir e os de Baixo que apenas suportam. <strong>O Partido foi o primeiro a decifrar a roda do poder e a inventar a trava para detê-la para sempre.</strong> Congelou a sociedade numa hierarquia eterna, onde a mobilidade não desacelera: ela morre.","tip":"<strong>Armadilha:</strong> o discurso que jura abolir as classes costuma instalar, no lugar, a elite mais impenetrável que já houve."},
      {"ic":"target","t":"A Oposição Fabricada","emph":"Fabricada","b":"A célebre Irmandade rebelde talvez não passe de peça encenada pelo próprio governo. <strong>O poder absoluto não se contenta em esmagar a dissidência: ele a inventa, para canalizar o ódio e pescar, um a um, os curiosos.</strong> Uma resistência caseira e controlada serve infinitamente mais ao regime do que o puro silêncio.","tip":"<strong>Sinal de alerta:</strong> desconfie fundo quando o suposto inimigo do sistema se encaixa perfeitinho na narrativa que o sistema precisava contar.","warn":True},
      {"ic":"bulb","t":"Entender Não Liberta","emph":"Entender","b":"Winston lê, compreende exatamente como a máquina mói gente e sente um alívio fugaz, quase eufórico. <strong>Mas o diagnóstico mais lúcido do universo não empurra um milímetro da porta de aço da cela.</strong> Saber a teoria sem ter força na mão não é meio caminho andado — é a forma mais nua do desamparo.","tip":"<strong>Regra:</strong> lucidez sem plano de ação não é salvação; é sofrer de olhos bem abertos, vendo a queda chegar."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["O poder total é racional e autoconsciente — a opressão é calculada, não tropeço acidental.","Regimes fabricam a própria oposição para controlá-la, canalizar o ódio e legitimar-se.","Compreender o sistema não é o mesmo que ter o poder de mudá-lo."]},

 {"slug":"ch07-prisao-tortura-2-mais-2","sub":"CAPÍTULO 7: A Prisão, a Tortura e '2+2=5'",
  "intro":"No Ministério do Amor — o que tortura — O'Brien diz a Winston a tese nua do regime, sem disfarce de utopia: o poder pelo poder, e nada além. A tortura ali não busca confissão, nem mesmo obediência: busca conversão. E o seu coroamento é trivial e medonho — fazer Winston ver, de verdade, cinco dedos onde há quatro.",
  "cards":[
      {"ic":"sword","t":"O Poder é o Fim","emph":"Poder","b":"Ninguém ergue uma ditadura sonhando em salvar o povo ou inaugurar um paraíso adiante; faz-se a revolução para instalar a ditadura. <strong>O objetivo do poder é o poder — e ele se prova na capacidade de infligir dor sem que dela saia bem nenhum.</strong> Não há idealismo escondido no fundo: governar, aqui, é a arte nua de fazer o outro sofrer.","tip":"<strong>Modelo mental:</strong> o regime não oprime para chegar à utopia prometida — a opressão já é, ela mesma, o projeto inteiro."},
      {"ic":"triangle","t":"Reeducação em Três Atos","emph":"Três Atos","b":"Primeiro quebram o corpo, para você aprender; depois quebram a mente e a realidade, para você entender; por fim, quebram o amor, para você aceitar. <strong>O regime não se contenta com submissão fingida: ele entra para limpar por dentro e reclamar a alma como propriedade.</strong> O carrasco só comemora quando o rebelde chora, convertido de coração.","tip":"<strong>Regra:</strong> o mal supremo não fuzila o prisioneiro de pé — molda-o em devoto, esvaziado, antes de descartá-lo."},
      {"ic":"eye","t":"A Última Trincheira","emph":"Última Trincheira","b":"Afirmar que dois mais dois são quatro, sob a dor, é o ato de resistência mais elementar que sobra — e o mais teimoso. <strong>A percepção crua dos fatos é o último solo firme em que a dignidade ainda consegue se fincar.</strong> Entregar a tabuada à tortura não é só ceder um número: é apagar o farol pelo qual você distinguia o real do delírio.","tip":"<strong>Sinal de alerta:</strong> relativizar fatos elementares e físicos é entregar de bandeja as chaves da própria mente.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["O poder pelo poder não persegue finalidade externa nenhuma — governa para se perpetuar.","A conversão íntima, e não a mera obediência, é a vitória total do totalitarismo.","A razão é a última defesa do eu — e exatamente por isso é o alvo final do poder."]},

 {"slug":"ch08-quarto-101-quebra-final","sub":"CAPÍTULO 8: O Quarto 101 e a Quebra Final",
  "intro":"A reeducação só termina quando o Partido toma a última cidadela do eu: o amor. No Quarto 101, diante da pior coisa do mundo — para Winston, os ratos —, ele grita que façam aquilo a Julia, não a ele. Trai o que mais amava. E o romance se fecha não em revolta, mas em rendição: Winston, vazio, ama o Grande Irmão.",
  "cards":[
      {"ic":"gap","t":"O Seu Terror, Só Seu","emph":"O Seu Terror","b":"A tortura comum dói no corpo de qualquer um; o Quarto 101 guarda o pesadelo inconfessável que só existe dentro de você. <strong>O regime descobre o medo mais particular de cada pessoa e o afia como lâmina contra o próprio dono.</strong> É o terror sob medida, cirúrgico — e por isso impossível de enganar com coragem genérica.","tip":"<strong>Armadilha:</strong> o totalitarismo mapeia as suas fobias por uma única razão: para manter o dedo pousado no seu botão de pânico.","warn":True},
      {"ic":"person","t":"Trair para Não Sentir","emph":"Trair","b":"Quando a gaiola de ratos se aproxima do rosto, o amor inteiro de Winston por Julia evapora num segundo, e ele berra: façam a ela, não a mim. <strong>A tortura cessa no exato instante em que você joga a pessoa amada no lugar do seu próprio sofrimento.</strong> O Partido não queria que Winston deixasse de amar Julia — queria que a entregasse, e por dentro.","tip":"<strong>Regra:</strong> sob o terror absoluto, o regime prova que nenhum laço humano é forte o bastante para não ser arrancado pela raiz."},
      {"ic":"mountain","t":"A Rendição da Alma","emph":"Rendição","b":"Winston não recebe a morte heroica do mártir, fuzilado de cara erguida com a rebeldia intacta. <strong>Ele continua vivo, esvaziado, bebe o gim morno e descobre que ama, de verdade, o Grande Irmão.</strong> A distopia se consuma justamente aí: não no corpo destruído, mas no homem oco que sorri para a corrente.","tip":"<strong>Modelo mental:</strong> o pesadelo orwelliano vence a guerra no dia em que o oprimido aprende a amar o pé que o esmaga."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["O medo mais íntimo de cada pessoa é a alavanca mais precisa que a tortura encontra.","O Partido destrói o amor porque ele é o último território do eu fora do alcance do controle.","A vitória total do poder é a conversão — a vítima que termina amando o próprio carrasco."]},

 {"slug":"ch09-simbolos-motivos-legado","sub":"CAPÍTULO 9: Símbolos, Motivos e o Legado Distópico",
  "intro":"'1984' não ficou na estante: virou vocabulário do mundo real. Dizemos 'orwelliano', 'Grande Irmão', 'duplipensar' sem precisar explicar. O romance legou à língua comum um conjunto de alertas permanentes — sobre a vigilância, a mentira de Estado e a fragilidade espantosa da verdade. Não é a história de um ano; é o retrato do que o poder faz quando ninguém o segura.",
  "cards":[
      {"ic":"lens","t":"Símbolos que Acusam","emph":"Símbolos","b":"O peso de vidro guarda um pedaço intacto de passado; a prole gorda que canta no quintal carrega, sem saber, a chama do humano. <strong>Cada objeto do romance é a radiografia de um mecanismo do regime — a vida que ainda resiste, ou o que o sistema já corroeu.</strong> São testemunhas mudas, e nenhuma testemunha muda é inocente.","tip":"<strong>Prática:</strong> olhe os objetos e hábitos do seu próprio tempo e pergunte que tipo de obediência eles, em silêncio, ensinam."},
      {"ic":"wave","t":"Espelho, Não Profecia","emph":"Espelho","b":"O ano de 1984 passou faz tempo, e nem por isso o livro envelheceu — porque ele nunca foi um calendário. <strong>Orwell não previu gadgets; ele descreveu o que o poder sempre quis fazer na sombra, com ou sem tela.</strong> O perigo que ele aponta não é a câmera nova: é a alienação mansa que aprende a chamar a coleira de conforto.","tip":"<strong>Modelo mental:</strong> leia '1984' não como almanaque do futuro, mas como espelho dos abusos do presente.","warn":True},
      {"ic":"person","t":"A Esperança Adormecida","emph":"Esperança","b":"'Se há esperança, ela está nos proles' — anota Winston. A massa que vive fora do alcance fino do Partido guarda os afetos brutos do humano e a força esmagadora dos números. <strong>Falta-lhe só uma coisa: a consciência de que está numa jaula.</strong> É um povo que poderia derrubar tudo num espirro — no dia em que acordasse.","tip":"<strong>Para refletir:</strong> nenhum poder é eterno enquanto sobrar gente capaz de, um dia, perceber a corrente e se recusar a usá-la."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["Os símbolos de Orwell são diagnósticos — leia-os como perguntas afiadas sobre o mundo de hoje.","'1984' é alerta, não profecia: vale menos como data marcada que como espelho de tendências.","A esperança existe, frágil, nos proles — mas exige consciência, não apenas peso de número."]},
]
