# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de '21 Lições para o Século 21' (Yuval Noah Harari)."""

BOOK = {
 "title": "21 Lições para o Século 21",
 "author": "Yuval Noah Harari",
 "header_light": "21 LIÇÕES",
 "header_bold": "PARA O SÉCULO 21",
 "subtitle": "VISÃO GERAL · O AGORA, ANTES QUE ELE NOS HACKEIE",
 "intro": "Sapiens contou de onde viemos; Homo Deus, para onde íamos. Este livro pergunta a coisa mais difícil de todas: o que fazer agora. Pela primeira vez, a humanidade tem poder de deuses e nenhuma história compartilhada para guiá-lo — as três grandes narrativas do século 20 ruíram e nada ocupou o vazio. Enquanto discutimos o passado, a IA e a biotecnologia aprendem a nos ler por dentro: quando uma máquina te conhecer melhor que você mesmo, a sua liberdade passa a ser dela. Não há fórmula para o século 21. Há uma única defesa, e ela é velha de 2.500 anos: conhece-te a ti mesmo — depressa, porque você tem concorrência.",
 "description": "Yuval Noah Harari larga o passado e o futuro e encara o presente, sem o conforto de uma grande resposta. Vinte e uma lições sobre um mundo em que a tecnologia corre mais rápido que a política: a classe que a automação torna não explorada, mas dispensável; a equação que permite hackear seres humanos quando sentimentos viram dados; a desigualdade que deixa de ser de bolso para virar de biologia; o terrorismo que é teatro e a guerra que virou mau negócio; a religião que dá coesão mas não conserta o clima; a espécie pós-verdade que sempre preferiu ficções úteis a fatos incômodos. No fim, nenhum guru, nenhum deus, nenhum algoritmo decide por você — só você conhecendo a própria mente antes que outro a conheça primeiro.",
 "tags": ["Política", "Tecnologia", "Filosofia"],
 "progress": "9 Capítulos",
 "cover": "assets/21-licoes-cover.png",
 "overview_cards": [
   {"ic":"gap","t":"A Equação do Hackeamento Humano","b":"<strong>Biologia × Poder Computacional × Dados = a capacidade de hackear um ser humano.</strong> Se o que você sente é apenas bioquímica, basta dados suficientes para que um sistema preveja seus desejos antes de você. No instante em que ele te conhece melhor que você, a autoridade muda de dono — e o seu coração vira o porta-voz de quem o programou.","tip":"<strong>O ponto:</strong> 'ouça seu coração' era um bom conselho enquanto ninguém mais o escutava."},
   {"ic":"triangle","t":"Os Três Perigos Sem Fronteira","b":"<strong>Nuclear, ecológico, tecnológico</strong> — os três que podem nos liquidar não respeitam aduana nem bandeira. Um vírus, uma nuvem radioativa e um algoritmo zombam de muros. Por isso o nacionalismo, ótimo para cuidar dos seus, é impotente aqui: não existe resposta nacional para um problema que é da espécie.","tip":"<strong>Teste rápido:</strong> esse problema tem fronteira? Se não tem, qualquer solução só nacional já nasce derrotada."},
   {"ic":"pivot","t":"O Vazio de Narrativa","b":"O século 20 ofereceu três grandes histórias — fascismo, comunismo, liberalismo. Duas morreram; a terceira sobreviveu até 2008, quando perdeu a fé até de quem a defendia. <strong>Sobramos sem enredo comum</strong> justo quando as maiores crises da história exigiriam um. O populismo não preenche o buraco: ele é o barulho que o buraco faz.","tip":"<strong>O ponto:</strong> a nostalgia não é um projeto de futuro — é a confissão de que ninguém mais sabe contar um."},
   {"ic":"leaf","t":"Conhece-te a Ti Mesmo","b":"Há séculos isto era conselho de filósofo. Hoje é segurança da informação. Num mundo de algoritmos pagos para te decifrar, <strong>conhecer a própria mente deixou de ser luxo espiritual e virou a única defesa que sobra</strong>. As ferramentas são modestas: os 4 Cs (pensamento crítico, comunicação, colaboração, criatividade), tratar o 'eu' como uma história em rascunho, e o silêncio da meditação laica.","tip":"<strong>Como aplicar:</strong> se você não tomar o volante da sua atenção, alguém com mais dados toma por você."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-desilusao","sub":"CAPÍTULO 1: Desilusão — o Fim das Grandes Narrativas",
  "intro":"O século 20 não nos legou só guerras: legou três histórias que disputavam o sentido do mundo — fascismo, comunismo e liberalismo. O fascismo morreu em 1945, o comunismo foi se apagando até 1989, e o liberalismo reinou sozinho até 2008 esfarelar a sua promessa. Ficamos com o que pode ser a primeira geração da história sem nenhuma grande narrativa em que acreditar — e ainda assim com problemas grandes demais para resolver sem uma.",
  "cards":[
      {"ic":"pivot","t":"O Vazio de Narrativa","emph":"Vazio","b":"Uma narrativa é o sistema operacional de uma sociedade: sem ela, nem os fatos sabemos interpretar. E é exatamente aí que estamos — encarando a IA e o colapso climático sem um enredo comum que explique o presente ou aponte o amanhã. <strong>O populismo não é uma narrativa nova: é o sintoma febril de que a antiga caiu e nada a substituiu.</strong>","tip":"<strong>O ponto:</strong> antes de discutir as respostas, repare que perdemos a pergunta compartilhada."},
      {"ic":"clock","t":"Nostalgia Não É Projeto","emph":"Nostalgia","b":"Quem promete devolver um passado dourado está, no fundo, confessando que não sabe desenhar futuro nenhum. O líder saudosista oferece a rejeição ruidosa do presente, não um plano. <strong>Quando um país inteiro vira o rosto para trás, o sintoma não é um político excêntrico — é uma desilusão estrutural.</strong>","tip":"<strong>Para refletir:</strong> a história que parecia eterna em 2007 já estava trincada em 2009. Nenhuma narrativa tem garantia vitalícia."},
      {"ic":"gap","t":"Buraco Não Fica Vazio","emph":"Buraco","b":"O perigo do vácuo é que ele nunca permanece vazio. <strong>O espaço deixado pela falta de sentido é depressa ocupado por fantasias regressivas e bodes expiatórios convenientes.</strong> Diagnosticar a ausência é o passo fácil; o trabalho duro — e ainda por fazer — é inventar um enredo à altura de problemas globais.","tip":"<strong>Regra:</strong> não se coordena bilhões de pessoas contra uma crise global sem uma história que todas comprem."},
    ],
  "lessons_title":"Por Que Ficamos Sem Enredo",
  "lessons":["As três grandes histórias do século 20 viraram uma — depois, nenhuma em que ainda se confie.","O populismo é o sintoma do vazio, não a cura: vende nostalgia porque não sabe contar futuro.","Sem história compartilhada, a IA e o clima viram crises que não conseguimos sequer enfrentar juntos."]},

 {"slug":"ch02-trabalho","sub":"CAPÍTULO 2: Trabalho — a IA e a 'Classe Inútil'",
  "intro":"Durante séculos, o medo do trabalhador foi ser explorado. O medo do século 21 é pior: ser dispensável. A IA e a biotecnologia não automatizam só os músculos — automatizam também o raciocínio e até a leitura de emoções, antes a última muralha humana. Pode nascer daí algo inédito na história: uma 'classe inútil' de milhões que não são oprimidos pelo sistema, apenas desnecessários a ele.",
  "cards":[
      {"ic":"person","t":"A Classe Inútil","emph":"Inútil","b":"O abismo não é o desemprego de sempre, é a obsolescência. <strong>Há algo pior do que ser explorado pelo sistema: ser irrelevante para ele.</strong> E a máquina nem precisa de consciência ou alma para te aposentar — basta superar o humano médio numa lista de tarefas. Ela não vai te odiar; vai apenas seguir em frente sem você.","tip":"<strong>Sinal de alerta:</strong> a IA não devora 'empregos' inteiros de uma vez — fatia tarefas, e a profissão se esvazia por dentro antes de cair.","warn":True},
      {"ic":"link","t":"Você Aprende Sozinho; Ela, em Rede","emph":"Rede","b":"A vantagem decisiva da máquina não é inteligência, é conectividade. <strong>Enquanto você aprende isolado com os seus erros, o algoritmo aprende com os erros de uma frota inteira e se atualiza no mesmo segundo, no mundo todo.</strong> Não é uma disputa de intuição contra fria lógica — é a sua biografia contra a memória somada de milhões.","tip":"<strong>Como aplicar:</strong> meça quanto do seu dia é reconhecimento de padrão repetível. Quanto mais for, mais perto você está da mira."},
      {"ic":"spiral","t":"Reinventar-se em Série","emph":"Reinventar","b":"A carreira em linha reta — aprende-se uma profissão aos vinte, exerce-se até a aposentadoria — morreu. O século 21 vai pedir que você se desmonte e se recrie aos quarenta, cinquenta, sessenta. <strong>E o custo mais alto disso não é técnico, é psicológico</strong>: reinventar a si mesmo dói mais do que aprender uma ferramenta nova.","tip":"<strong>Prática:</strong> a competência mais valiosa não é dominar algo, é a maleabilidade de largar o que você dominava e reaprender do zero."},
    ],
  "lessons_title":"O Medo Que Mudou de Nome",
  "lessons":["A ameaça do século não é a exploração, é a irrelevância — a classe que sobra, não a que apanha.","A IA vence por conectividade e atualização instantânea, não por imitar a alma humana.","O futuro do trabalho exige reinventar-se em série — um peso existencial, não só uma reciclagem técnica."]},

 {"slug":"ch03-liberdade","sub":"CAPÍTULO 3: Liberdade — Big Data e o Hackeamento Humano",
  "intro":"O liberalismo nos ensinou um mandamento: ouça seu coração, vote no seu sentimento, siga sua vontade. Esse conselho repousa numa aposta secreta — a de que ninguém conhece os seus sentimentos melhor que você. A aposta está prestes a perder. Se sentimentos são algoritmos bioquímicos, com dados e poder de processamento suficientes uma máquina os lê melhor do que o dono. E quando isso acontece, 'ouça seu coração' vira 'obedeça ao sistema que aprendeu a falar pelo seu coração'.",
  "cards":[
      {"ic":"gap","t":"A Equação do Hackeamento","emph":"Equação","b":"Junte biologia, poder de processamento e um oceano de dados e você terá <strong>a fórmula para hackear um ser humano.</strong> Quando o sistema conhece seus gatilhos melhor que você, o livre-arbítrio não some por decreto — some por irrelevância. A velha certeza de que o seu sentimento é a palavra final simplesmente deixa de valer.","tip":"<strong>O ponto:</strong> a pergunta do século deixou de ser 'quem está me vigiando?' e virou 'quem está decidindo por mim?'"},
      {"ic":"eye","t":"A Ditadura Que Sorri","emph":"Ditadura","b":"Esqueça o Big Brother que oprime de cima e à força. O perigo de agora é o oposto: <strong>o algoritmo gentil que te mapeia por dentro e satisfaz desejos que você ainda nem sabia que tinha.</strong> Esse controle não precisa de cassetete — ele vem embrulhado em conveniência, e a gente entrega a chave sorrindo.","tip":"<strong>Armadilha:</strong> quando uma recomendação parecer mágica de tão certeira, pergunte quem a encomendou e o que ela quer de você.","warn":True},
      {"ic":"key","t":"Duas Defesas: Regular e Conhecer","emph":"Defesas","b":"A resistência tem duas frentes. A coletiva é política: <strong>impedir que punhado de corporações monopolize os dados</strong>, porque quem é dono da informação será dono do futuro. A individual é íntima e intransferível: conhecer a própria mente antes que o software a conheça por você.","tip":"<strong>Como aplicar:</strong> entregar dados sem pensar é entregar a chave da sua autonomia. Trate cada 'aceito' com o peso de um contrato."},
    ],
  "lessons_title":"Quando a Máquina Te Conhece Melhor",
  "lessons":["A liberdade liberal aposta que seus sentimentos têm a palavra final — e o hackeamento desmonta a aposta.","Biologia × Computação × Dados pode te decifrar melhor do que você se decifra.","Há duas defesas: regular quem é dono dos dados (coletiva) e conhecer a própria mente (individual)."]},

 {"slug":"ch04-igualdade","sub":"CAPÍTULO 4: Igualdade — Quem Tem os Dados Tem o Futuro",
  "intro":"O século 20 foi, apesar de tudo, o mais igualitário da história — não por bondade, mas por necessidade. As elites precisavam de soldados nas trincheiras e operários nas fábricas, e gente útil precisa ser alimentada, educada e saudável. A tecnologia está cortando essa dependência. Quando as massas deixarem de ser necessárias, o velho motor da igualdade se desliga — e o pior cenário não é a desigualdade de bolso, é a de biologia: uma casta aprimorada por cima de uma classe que sobra.",
  "cards":[
      {"ic":"layers","t":"Da Carteira para o Corpo","emph":"Corpo","b":"Por enquanto, o rico e o pobre nascem com o mesmo corpo. Quando a elite puder comprar aprimoramento genético e cognitivo, isso acaba. <strong>Pela primeira vez na história, a desigualdade econômica pode se transformar em desigualdade biológica</strong> — uma fenda que não se mede em salários, mas em capacidades que se herdam.","tip":"<strong>Sinal de alerta:</strong> a igualdade do século passado foi efeito colateral do interesse. Tirado o interesse, some o efeito."},
      {"ic":"target","t":"O Dado É o Novo Ouro","emph":"Novo Ouro","b":"Cada era teve seu ativo supremo de poder: a <strong>terra</strong> no mundo agrário, a <strong>máquina</strong> no mundo industrial, e agora os <strong>dados</strong>. E há uma diferença cruel: terra e fábrica se repartem, dados se concentram. Empilhados em poucas mãos, eles desenham a tirania de amanhã.","tip":"<strong>Atalho:</strong> para achar onde mora o poder político hoje, não siga o dinheiro — siga quem guarda os dados."},
      {"ic":"scale","t":"O Fim da Redistribuição","emph":"Fim","b":"Estado de bem-estar, educação pública, saúde para todos: nada disso nasceu de generosidade. Nasceu da necessidade de soldados e operários fortes. <strong>Quando a automação dispensar esse exército, o incentivo histórico para repartir evapora.</strong> A igualdade deixará de cair de bandeja e passará a exigir luta política deliberada.","tip":"<strong>Para refletir:</strong> a generosidade de um sistema termina exatamente onde a sua utilidade para ele acaba.","warn":True},
    ],
  "lessons_title":"O Motor Secreto da Igualdade",
  "lessons":["A igualdade do século 20 vinha da utilidade das massas — e é justo isso que a tecnologia dispensa.","Dados são o ativo de poder da era; concentrados, geram a desigualdade que vem aí.","O risco extremo é a desigualdade virar biológica: castas humanas aprimoradas de forma desigual."]},

 {"slug":"ch05-comunidade-civilizacao","sub":"CAPÍTULO 5: Comunidade e Civilização",
  "intro":"Dois mitos confortáveis precisam cair. O primeiro: o de que estar conectado é o mesmo que pertencer — não é, e nunca foi o Facebook quem trouxe sopa para o seu velório. O segundo: o do 'choque de civilizações', como se o mundo fosse feito de blocos incompatíveis em rota de colisão. Na verdade, nunca houve um momento em que a humanidade compartilhasse tanto — uma só economia, uma só ciência, um só clima em apuros.",
  "cards":[
      {"ic":"link","t":"Conectar Não É Pertencer","emph":"Pertencer","b":"Bilhões de perfis ligados em rede, e mais solidão do que nunca. As redes sociais venceram a distância e esqueceram do essencial: <strong>pertencer pede corpo presente, intimidade desconfortável e responsabilidade pelo outro.</strong> Prometeram a aldeia global e entregaram ilhas polarizadas onde cada um grita sozinho.","tip":"<strong>Prática:</strong> uma rede que não te leva sopa quando você adoece é só uma agenda de contatos com fotos."},
      {"ic":"wave","t":"Uma Civilização, Não Muitas","emph":"Uma","b":"O 'choque de civilizações' é um mito sob medida para quem quer dividir. No fundo, todos jogamos <strong>no mesmo tabuleiro</strong>: o mesmo mercado, a mesma ciência, a mesma diplomacia, os mesmos vírus. Prova disso é que as guerras mais ferozes de hoje são internas — brigas de família dentro de uma só civilização global.","tip":"<strong>O ponto:</strong> por baixo de toda retórica de 'eles contra nós', os dois lados disputam o poder seguindo exatamente as mesmas regras."},
      {"ic":"mask","t":"Identidade É História, Não Essência","emph":"História","b":"Culturas nunca foram pedras: elas se misturam, racham e se reinventam o tempo todo. <strong>Tratar uma identidade como fôrma eterna e pura é uma ficção — e quase sempre uma ficção a serviço de quem quer separar e mandar.</strong> Você é feito de histórias em movimento, não de uma essência cravada nos genes.","tip":"<strong>Sinal de alerta:</strong> quando alguém invocar a 'pureza' de um passado, procure quem está lucrando com a divisão no presente."},
    ],
  "lessons_title":"O Mundo Que Já Dividimos",
  "lessons":["Conexão não é comunidade: pertencer é corpóreo e cobra responsabilidade mútua, não curtidas.","Já existe uma só civilização global; o 'choque de civilizações' é mito feito para dividir.","Identidades coletivas são histórias mutáveis — não essências fixas que se herdam no sangue."]},

 {"slug":"ch06-nacionalismo-religiao-imigracao","sub":"CAPÍTULO 6: Nacionalismo, Religião e Imigração",
  "intro":"Guerra nuclear, colapso ecológico, disrupção tecnológica: os três perigos capazes de acabar conosco têm uma coisa em comum — nenhum tem passaporte. Ironicamente, as forças que mais mobilizam paixão hoje — nacionalismo, religião, o atrito da imigração — fazem o oposto do que a hora exige: dividem a humanidade em times rivais bem na véspera em que ela precisaria jogar do mesmo lado.",
  "cards":[
      {"ic":"triangle","t":"Nacionalismo: Remédio e Veneno","emph":"Nacionalismo","b":"O patriotismo que financia hospitais, escolas e impostos é um pilar da civilização — cuidar dos seus é coisa boa. O veneno entra quando esse cuidado se torce em <strong>supremacia e ódio ao estrangeiro</strong>. O problema nunca foi amar o próprio país; foi achar que para isso é preciso desprezar os outros.","tip":"<strong>Teste:</strong> o seu orgulho nacional te empurra para a cooperação ou para a exclusão? A resposta diz se é remédio ou veneno."},
      {"ic":"scale","t":"Fé Dá Laço, Não Conserta o Clima","emph":"Laço","b":"A religião é insuperável para criar pertencimento e dar sentido — e inútil para resolver um problema técnico. <strong>Nenhuma reza calcula a órbita de um satélite nem reduz a emissão de carbono.</strong> Pedir engenharia climática à fé é tão equivocado quanto pedir consolo a uma planilha: cada esfera serve para o que sabe fazer.","tip":"<strong>O ponto:</strong> use a religião para tecer comunidade e a ciência para consertar máquinas e ecossistemas. Não troque as funções."},
      {"ic":"key","t":"Imigração: Um Acordo de Três Termos","emph":"Acordo","b":"O debate só parece insolúvel porque cada lado grita uma palavra e ignora as outras duas. Na verdade são três cláusulas de um mesmo contrato: o país <strong>acolhe</strong>, o recém-chegado <strong>assimila</strong> valores essenciais e, com o tempo, o Estado <strong>integra</strong>. Aceitar o tripô inteiro é o único jeito de baixar a fervura.","tip":"<strong>Como aplicar:</strong> quando a discussão sobre fronteiras ferver, identifique qual das três obrigações cada lado acusa o outro de quebrar."},
    ],
  "lessons_title":"O Que Não Tem Fronteira",
  "lessons":["Os três perigos do século são globais e cobram cooperação global — o nacionalismo sozinho é impotente.","Nacionalismo e religião dão coesão, não soluções técnicas; o tóxico é o orgulho que vira ódio.","Imigração é um contrato de três cláusulas — acolher, assimilar, integrar — em disputa; nomeá-las esfria o debate."]},

 {"slug":"ch07-terrorismo-guerra","sub":"CAPÍTULO 7: Terrorismo e Guerra",
  "intro":"O terrorista é fraco — fraquíssimo. Mata pouca gente e não conquista território algum. Sua arma não é a bomba, é a câmera: ele encena o medo e conta com a vítima para terminar o serviço. É a mosca que não derruba o touro, mas zumbe no ouvido até o touro, enlouquecido, demolir a própria loja de porcelana. Logo ao lado mora um perigo maior e mais antigo: a guerra, que num mundo onde a riqueza virou dado e conhecimento deixou de ser um bom negócio — sem que os generais tenham percebido.",
  "cards":[
      {"ic":"eye","t":"O Teatro do Medo","emph":"Teatro","b":"O estrago físico do terrorismo é minúsculo perto das mortes no trânsito de um único fim de semana. O poder dele é inteiramente <strong>psicológico e feito para a tela</strong>: ele sequestra a imaginação coletiva com a estética do horror. <strong>Se você responde com pânico espetacular, o ataque já cumpriu o objetivo.</strong>","tip":"<strong>O ponto:</strong> meça o risco pela estatística fria, não pela manchete em letra garrafal.","warn":True},
      {"ic":"pivot","t":"A Mosca e o Touro","emph":"A Mosca","b":"A mosca não tem força para derrubar o touro, mas tem zumbido para enfurecê-lo — e aí o próprio touro <strong>quebra a loja de porcelana sozinho</strong>. Guerras desastradas, vigilância de massa, liberdades suspensas: a sobre-reação do Estado é precisamente o troféu que o terrorista não conseguiria conquistar por conta própria.","tip":"<strong>Sinal de alerta:</strong> a provocação só funciona se você destruir seus próprios princípios para revidar. Não morda a isca."},
      {"ic":"mountain","t":"A Guerra Que Não Paga Mais","emph":"Não Paga","b":"Na era da informação, a riqueza de uma nação são algoritmos, talento e dados — ativos que tanque nenhum confisca, que se esvaem se você tenta tomá-los à força. <strong>A guerra de conquista deixou de ser um negócio lucrativo.</strong> Os generais, porém, ainda se embriagam com a velha fantasia da invasão rápida e limpa.","tip":"<strong>Armadilha:</strong> toda promessa de 'vitória rápida e cirúrgica' é propaganda. O caos da guerra nunca obedeceu a roteiro."},
    ],
  "lessons_title":"A Mosca, o Touro e o Butim",
  "lessons":["O terror é teatro: dano real ínfimo, efeito psicológico enorme — quem vence é a reação exagerada da vítima.","Não seja o touro da mosca: recuse a histeria e mantenha proporção e Estado de direito.","A guerra moderna é tentação fatal: o butim virou dado e talento, mas a ilusão da vitória fácil resiste."]},

 {"slug":"ch08-humildade-deus-secularismo","sub":"CAPÍTULO 8: Humildade, Deus e Secularismo",
  "intro":"Três lições que cabem numa palavra: modéstia. A primeira humilha os povos — nenhum deles é o centro da história nem inventou a moral. A segunda humilha as religiões — do mistério do cosmos não se deduz o que se pode comer ou amar no sábado à noite. E a terceira reabilita o secularismo, que não é o vazio de quem não crê em nada, mas um código de valores tão exigente quanto qualquer mandamento — talvez mais.",
  "cards":[
      {"ic":"person","t":"O Umbigo do Mundo","emph":"Umbigo","b":"Quase toda cultura se imagina, sozinha, como o eixo moral do universo e o motor da história. <strong>Esse provincianismo grandioso é um dos combustíveis mais antigos da guerra.</strong> Nenhuma tribo, por mais bela ou antiga, tem o monopólio da verdade — e desconfiar disso é o começo da paz.","tip":"<strong>Como aplicar:</strong> desconfie de toda narrativa que coloque a sua turma como a heroína ungida e o resto como figurante."},
      {"ic":"scale","t":"Do Mistério Não Sai Regra","emph":"Mistério","b":"Não dá para invocar o abismo insondável do cosmos para decretar o que se come ou quem se ama. <strong>Isso é contrabando: usar o infinito como carimbo de preconceitos bem locais.</strong> A moral secular não pergunta a um deus se algo é proibido — pergunta a outros humanos se aquilo causa sofrimento. A bússola é a dor real, não o decreto.","tip":"<strong>O ponto:</strong> reverenciar o indizível é uma coisa; obedecer a um manual escrito por mãos humanas em nome dele é outra bem diferente."},
      {"ic":"leaf","t":"O Código Secular","emph":"Código","b":"Secularismo não é o niilismo triste de quem não acredita em nada. É um pacto positivo e duro com <strong>a verdade dos fatos, a igualdade, a compaixão e a liberdade de questionar tudo</strong> — inclusive a si mesmo. É a coragem de dizer 'não sei' antes de apontar o dedo, e de assumir a responsabilidade sem terceirizá-la a um céu.","tip":"<strong>Para refletir:</strong> a virtude secular central não é a certeza, é admitir a própria ignorância e responder por ela mesmo assim."},
    ],
  "lessons_title":"Três Lições de Modéstia",
  "lessons":["Humildade: nenhum povo é o centro da história nem o inventor da moral.","Separe o Deus-mistério do Deus-legislador — do inefável não se deduz nenhuma regra concreta.","Secularismo é um código positivo — verdade, compaixão, igualdade e coragem de admitir o erro no centro."]},

 {"slug":"ch09-ignorancia-posverdade-meditacao","sub":"CAPÍTULO 9: Ignorância, Pós-verdade e Conhece-te a Ti Mesmo",
  "intro":"Você sabe muito menos do que acredita saber, e a culpa é boa: o conhecimento sempre foi propriedade da tribo, não do indivíduo — só que o ego confunde uma coisa com a outra. Pior: não há era das fake news inaugurando a mentira. O sapiens sempre foi uma espécie pós-verdade; foi crendo em ficções comuns que ele dominou o planeta. E é por isso que a defesa final deste livro é íntima: num mundo de algoritmos pagos para te hackear, conhecer a própria mente virou sobrevivência.",
  "cards":[
      {"ic":"lens","t":"A Ilusão do Conhecimento","emph":"Ilusão","b":"Você jura que entende como funciona uma vacina ou uma economia — até tentar explicar em voz alta e travar na segunda frase. <strong>O conhecimento real mora espalhado pela comunidade</strong>, mas o ego o confunde com sabedoria própria. Quanto menos sabemos do quanto não sabemos, mais alto falamos.","tip":"<strong>Regra:</strong> antes de bater o pé numa discussão, tente explicar o mecanismo do zero. Se você travar, é hora de ouvir."},
      {"ic":"bubble","t":"A Espécie Pós-Verdade","emph":"Pós-Verdade","b":"Conquistamos a Terra costurando redes em torno de ficções úteis: dinheiro, deuses, leis e nações não existem fora da nossa cabeça coletiva, e mesmo assim governam o mundo. O poder sempre se apoiou nelas. <strong>Por isso há um trade-off cruel: liderar pede flertar com a ilusão; insistir só na verdade costuma custar o poder.</strong>","tip":"<strong>O ponto:</strong> a manipulação não nasceu com a internet. Nossa espécie quase sempre preferiu a ordem confortável à verdade incômoda."},
      {"ic":"leaf","t":"Conheça a Própria Mente","emph":"Mente","b":"Para não ser devorado, mapeie seus pontos cegos antes que outro o faça. Meditação e autoconhecimento deixaram de ser luxo espiritual: viraram <strong>segurança da informação contra empresas que lucram hackeando a sua atenção</strong>. As falhas que você ignora são exatamente as que um algoritmo vai monetizar.","tip":"<strong>Prática:</strong> reserve silêncio sem tela. Se você não assumir o volante da sua atenção, alguém com mais dados assume — e cobra."},
    ],
  "lessons_title":"Conhece-te Antes Que Te Conheçam",
  "lessons":["Você sabe menos do que pensa: o conhecimento é da tribo, e a ilusão colapsa quando tenta explicar do zero.","O sapiens sempre foi pós-verdade: ficções coletivas são a base do poder e da cooperação em massa.","Conhecer a própria mente é a defesa decisiva — 'conhece-te a ti mesmo' deixou de ser conselho e virou sobrevivência."]},
]
