# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'As 48 Leis do Poder' (Robert Greene).
Agrupamento temático próprio das 48 leis, em chave DEFENSIVA (reconhecer para não ser peão).
Não reproduz o texto nem a lista integral — síntese atribuída a Greene."""

BOOK = {
 "title": "As 48 Leis do Poder",
 "author": "Robert Greene",
 "header_light": "AS 48 LEIS",
 "header_bold": "DO PODER",
 "subtitle": "VISÃO GERAL · A ANATOMIA FRIA DO PODER (LEITURA DEFENSIVA)",
 "intro": "O poder não tem moral — tem regras, e elas não mudam há três mil anos. Robert Greene dissecou a corte de Versalhes, os condottieri italianos e os trapaceiros de feira no mesmo bisturi, e o que sobrou foram 48 leis ditas em tom glacial: o poder como ele é, não como o púlpito gostaria que fosse. Por isso o livro escandaliza. Mas o mesmo mapa que arma o ambicioso protege quem só quer dormir tranquilo — e aqui ele serve a essa segunda mão. <em>A pergunta que governa cada página: quem está aplicando isto em mim?</em>",
 "description": "O tratado de Robert Greene sobre a mecânica do poder, destilado de três milênios de cortes, guerras e golpes — frio, histórico, sem indignação. Reorganizado por eixos e lido em chave defensiva: o cortesão que protege a reputação, o jogo das aparências e da atenção, a dependência que prende, a indireção que vence sem confronto, a sedução e o timing, a defesa contra o falso amigo e o falso presente, e a lei que fecha tudo — ser informe, fluir como água para não dar alvo.",
 "tags": ["Poder", "Estratégia", "Psicologia"],
 "progress": "8 Capítulos",
 "cover": "assets/48-leis-do-poder-cover.png",
 "overview_cards": [
   {"ic":"scale","t":"Os 7 Eixos das 48 Leis","b":"A síntese temática do livro:","list":[
     "<strong>Proteja o mestre e a reputação</strong> (1, 5, 2).",
     "<strong>Domine as aparências</strong> (3, 4, 6, 7).",
     "<strong>Controle e dependência</strong> (11, 8, 9).",
     "<strong>Tática e indireção</strong> (15, 33, 21, 13).",
     "<strong>Sedução, audácia e timing</strong> (32, 28, 35, 25).",
     "<strong>Defesa</strong> (10, 19, 20, 40) e <strong>a lei suprema</strong> (48, 34).",
   ],"tip":"<strong>Chave do acervo:</strong> leitura DEFENSIVA — decorar a tática para não ser vítima dela, jamais para virar quem a aplica.","wide":True},
   {"ic":"mask","t":"As Três Leis que Sustentam o Resto","b":"Tudo se apoia em três pilares. <strong>Reputação</strong> (Lei 5): é a sua fama que entra na sala antes de você, e um rival mira nela, nunca no seu trabalho. <strong>Dissimulação</strong> (Leis 3 e 4): o poder vive na incerteza — quem expõe a intenção entregou a arma. <strong>Ser informe</strong> (Lei 48): o padrão previsível é alvo, e a água, que não tem forma, vence a pedra.","tip":"<strong>Modelo mental:</strong> intenção anunciada é jogada perdida — o outro só precisa esperar você se mexer."},
   {"ic":"eye","t":"A Única Pergunta que Importa","b":"O livro inteiro cabe numa frase de defesa: diante de cada gesto, pergunte <strong>\"quem está aplicando isto em mim?\"</strong>. O elogio que vem grudado num pedido (a isca da Lei 8), o presente generoso e súbito (a amarra da Lei 40), o bajulador que te faz baixar a guarda — nenhum desses chega anunciando o nome.","tip":"<strong>Cuidado:</strong> achar que \"não jogar\" basta para se proteger é a porta dos fundos por onde o manipulador entra.","warn":True},
 ],
}

CHAPTERS = [
 {"slug":"ch01-natureza-do-poder","sub":"CAPÍTULO 1: A Natureza do Poder",
  "intro":"Esqueça o poder dos manuais de liderança. O poder de Greene é mais velho e mais frio: nasceu nas cortes, onde quem perdia não era demitido — era decapitado. Ali se aprendeu que a força bruta é a ferramenta dos amadores e que tudo se decide pela aparência, pela paciência e pelo cálculo. Recusar esse jogo não deixa ninguém puro. Deixa apenas desarmado.",
  "cards":[
      {"ic":"scale","t":"Versalhes Está em Toda Mesa","emph":"Versalhes","b":"O poder de Greene não foi destilado em palestras, e sim na corte de Luís XIV, onde um sorriso podia ser sentença e um deslize, o fim. Dali saiu a regra que atravessa séculos: o cortesão vence pela aparência e pela espera, nunca pelo confronto cru. <strong>A reunião de amanhã obedece à mesma física que Versalhes</strong> — só mudou a roupa. Quem não vê a camada de poder sob a conversa cordial já está perdendo sem saber que joga.","tip":"<strong>Modelo mental:</strong> antes de reagir, leia a jogada. Não há interação inocente — só interação cuja aposta você ainda não notou."},
      {"ic":"mask","t":"O Mapa Não é a Viagem","emph":"O Mapa","b":"Greene descreve o poder como ele <strong>é</strong>, não como o sermão exige que seja — e é esse frio de patologista que faz o livro parecer um manual de canalhice. Mas a anatomia que ensina o predador a atacar é a mesma que ensina a presa a se esquivar. O bisturi não tem moral; quem o segura tem. <strong>Aprender a tática não obriga a usá-la</strong> — obriga, sim, a reconhecê-la quando vier contra você.","tip":"<strong>Regra do acervo:</strong> leia como quem estuda o golpe para não cair nele, não como quem decora o golpe para aplicar."},
      {"ic":"eye","t":"A Ingenuidade Não é Inocência","emph":"Ingenuidade","b":"Quem se recusa a entender o jogo imagina que assim fica de mãos limpas. Fica apenas de mãos vazias: a tática que ignora não some — passa intacta para quem souber usá-la contra você. A pureza desarmada é o prato favorito do manipulador. A defesa começa numa só pergunta, diante de cada lance: <strong>\"quem está aplicando isto em mim?\"</strong> — o elogio que precede o pedido, o presente que chega cedo demais.","tip":"<strong>Sinal de alerta:</strong> a sensação de que \"basta não jogar para estar a salvo\" é o exato ponto cego que o jogador experiente procura.","warn":True},
    ],
  "lessons_title":"O Que Fundamenta Tudo",
  "lessons":["Poder é jogo social com regras antigas — leia a partida, não negue que ela existe.","As leis são raio-X: servem para reconhecer a manobra e se proteger dela.","O tom é amoral de propósito; a bússola ética não vem no livro — vem de você."]},

 {"slug":"ch02-mestre-reputacao","sub":"CAPÍTULO 2: Proteja o Mestre e a Reputação",
  "intro":"O poder não começa no que você faz, mas no que pensam que você é — e ninguém pensa mais alto sobre você do que quem está acima de você. Por isso as primeiras leis miram dois alvos que os ambiciosos costumam ignorar até ser tarde: o ego do superior e a fragilidade do próprio nome. Mais gente cai por ofuscar o chefe do que por incompetência.",
  "cards":[
      {"ic":"scale","t":"O Nome Entra na Sala Primeiro","emph":"O Nome","b":"A Lei 5 é a pedra angular: você é lido pela fama que chega antes da sua voz. Sólida, ela intimida sem você erguer um dedo; arranhada, vira convite ao ataque. É capital de construção lenta e ruína instantânea — e é justamente por isso que o rival hábil nunca contesta o seu trabalho, que dá discussão. <strong>Ele envenena o seu nome, que se defende muito pior.</strong>","tip":"<strong>Como aplicar:</strong> guarde a reputação como o ativo mais caro que você tem — e observe quem, à sua volta, anda mirando a dos outros."},
      {"ic":"mask","t":"Nunca Faça Sombra ao Sol","emph":"Sombra","b":"A Lei 1 derruba mais talento do que a burrice jamais derrubou: brilhar demais diante de quem está acima não desperta admiração, desperta inveja — e a inveja não promove, sabota. O subordinado que corrige o chefe na frente da sala ganha um inimigo, não um aumento. <strong>Faça quem manda sentir-se o mais inteligente do recinto</strong> e seu próprio mérito deixa de ser ameaça para virar enfeite da glória dele.","tip":"<strong>Regra:</strong> deixe o crédito subir a escada. Provar-se mais esperto que o superior é a vitória mais cara que existe.","warn":True},
      {"ic":"link","t":"Tema o Amigo, Recrute o Inimigo","emph":"o Inimigo","b":"A Lei 2 inverte o instinto, e a história lhe dá razão: o amigo que você favorece pode acabar invejando em surdina o que ganhou de graça, enquanto o antigo rival conquistado se torna o mais leal — teve de provar o valor para sobreviver. O afeto cega para o que está em jogo; a desconfiança calibrada enxerga. <strong>Pese quem te cerca pelo interesse, não só pelo carinho.</strong>","tip":"<strong>Cuidado:</strong> a confiança apoiada só no afeto ignora o que cada um tem a ganhar — e é exatamente por aí que a faca encontra as costas."},
    ],
  "lessons_title":"O Que Proteger Primeiro",
  "lessons":["A reputação é o ativo central: um rival ataca o seu nome muito antes do seu trabalho.","Valorize quem está acima — deixe o crédito subir em vez de competir com o chefe.","Meça os aliados pelo interesse em jogo, não apenas pela simpatia."]},

 {"slug":"ch03-aparencias-atencao","sub":"CAPÍTULO 3: Domine as Aparências e a Atenção",
  "intro":"O mundo julga pela superfície, e o poder sabe disso melhor que ninguém. Não vence quem tem mais razão, mas quem controla melhor duas coisas: o que os outros conseguem ver e para onde eles olham. A verdade nua é desajeitada; a aparência trabalhada é uma ferramenta. Quem desdenha as aparências entrega o tabuleiro a quem as domina.",
  "cards":[
      {"ic":"mask","t":"Plano Anunciado é Plano Morto","emph":"Anunciado","b":"As Leis 3 e 4 andam de braços dados: quem revela a estratégia dá ao rival o tempo exato de se armar, e quem fala demais por ansiedade entrega a mão antes da aposta. O poder respira na incerteza — mantenha o outro no escuro e ele só reage tarde. <strong>Numa mesa de negociação, o silêncio é o melhor advogado: o outro lado o preenche com concessões</strong> que nenhum argumento seu arrancaria.","tip":"<strong>Como aplicar:</strong> sirva intenções a conta-gotas e deixe a pausa trabalhar — quem fala menos comanda mais."},
      {"ic":"eye","t":"Ser Esquecido é Morrer Duas Vezes","emph":"Esquecido","b":"A Lei 6 é brutal na sua frieza: no jogo social, a invisibilidade é a morte. Ser notado e comentado pesa mais do que ter razão num canto calado, e até a controvérsia que faz falar vale mais que o elogio morno que ninguém repete. <strong>Quem ninguém vê, ninguém lembra; quem ninguém lembra não existe na partida.</strong> A presença se constrói, nunca se espera.","tip":"<strong>Modelo mental:</strong> atenção é moeda — gaste-a com intenção, não a torre em vaidade barata."},
      {"ic":"spark","t":"Mostre o Resultado, Esconda o Suor","emph":"o Suor","b":"A Lei 7 conhece a memória humana: ela guarda o efeito limpo, não o esforço escondido. Quem exibe o resultado sem mostrar o trabalho braçal parece talento; quem mostra o suor parece esforçado — e esforço impressiona menos que dom aparente. O lado predatório dessa lei é colher a glória alheia; aqui interessa o reverso: <strong>perceba quando estão colhendo a glória do que VOCÊ fez</strong> e cole o seu nome na obra.","tip":"<strong>Defesa:</strong> registre a própria contribuição — crédito não reclamado é crédito que evapora, calado, na conta de outro."},
    ],
  "lessons_title":"O Jogo da Superfície",
  "lessons":["Revele intenções a conta-gotas e deixe o silêncio arrancar as concessões.","Cultive presença: ser esquecido, no jogo social, equivale a não existir.","Gerencie atenção e crédito de propósito — o que não se reivindica, outro reivindica."]},

 {"slug":"ch04-controle-dependencia","sub":"CAPÍTULO 4: Controle e Dependência",
  "intro":"O poder que se exibe é frágil; o que se desgasta. O poder que dura é o de que os outros não conseguem prescindir — o que faz o jogo vir até você em vez de você correr atrás dele. Aqui se aprende a arte mais discreta: tornar-se necessário, atrair em vez de perseguir, e vencer pela obra em vez do berro.",
  "cards":[
      {"ic":"link","t":"Seja o Nó que, Solto, Derruba Tudo","emph":"o Nó","b":"A Lei 11 ensina a forma mais durável de poder: quando a sua ausência dói, a sua posição vira intocável. O favor isolado se esquece num dia; a necessidade permanece todo dia. <strong>Seja o nó que, removido, faz a estrutura cair</strong> — não por chantagem, mas por valor que ninguém substitui. E não se esvazie de uma vez: quem entrega o segredo inteiro entrega também a própria dispensabilidade.","tip":"<strong>Como aplicar:</strong> construa dependência por competência, não por dívida — e guarde sempre uma peça que só a sua mão encaixa."},
      {"ic":"target","t":"Quem Persegue, Cansa; Quem Atrai, Manda","emph":"Atrai","b":"A Lei 8 entrega o tabuleiro a quem força o outro a mexer primeiro: a paciência vira ataque, e a isca certa faz o adversário agir no terreno que VOCÊ escolheu. Quem corre atrás se desgasta e revela a urgência; quem atrai dita o ritmo. <strong>Mas a faca tem dois gumes — a mesma isca é jogada em você</strong>: o que parece bom demais para ser real costuma ser anzol vestido de oferta.","tip":"<strong>Defesa:</strong> quando algo chega fácil, vantajoso e no exato momento da sua necessidade, desconfie — sorte assim costuma ter linha presa."},
      {"ic":"spark","t":"Não Ganhe a Discussão e Perca a Pessoa","emph":"a Pessoa","b":"A Lei 9 desarma o impulso de convencer no grito: a discussão deixa rancor mesmo quando você está certo, porque ferir o ego do outro custa um inimigo permanente. O fato consumado, esse, convence sem deixar cicatriz — ninguém debate com o resultado já entregue. <strong>Ter razão e criar um adversário é derrota fantasiada de vitória.</strong>","tip":"<strong>Regra:</strong> prove com a obra, não com a retórica — o que se demonstra dispensa o que se argumenta, e não cobra o preço do orgulho ferido."},
    ],
  "lessons_title":"A Arte de Não Precisar Forçar",
  "lessons":["Torne-se indispensável por valor real — e nunca entregue tudo o que sabe de uma vez.","Atraia em vez de perseguir; quem faz o outro mover-se primeiro escolhe o terreno.","Convença pelo resultado entregue, não pela discussão — razão que cria inimigo é vitória cara."]},

 {"slug":"ch05-tatica-indirecao","sub":"CAPÍTULO 5: Tática e Indireção",
  "intro":"O ataque frontal é o recurso de quem não tem outro: caro, ruidoso, fácil de prever. O poder hábil entra pelo flanco — encontra a fraqueza secreta, veste a fantasia da tolice, fala a língua do interesse alheio. A linha reta é a rota mais longa até onde se quer chegar. A indireção é a curta.",
  "cards":[
      {"ic":"lens","t":"Cada Pessoa Tem um Polegar","emph":"Polegar","b":"A Lei 33 ensina que toda pessoa carrega uma fraqueza-mestra — uma insegurança escondida, uma vaidade incontida, uma carência antiga — e quem a localiza encontra a alavanca que move o resto. A vaidade, sobretudo, é a porta da frente do manipulador: elogie o que o outro mais quer ouvir e ele abre tudo. <strong>Por isso a defesa começa em casa: descubra o SEU polegar antes que alguém o aperte por você.</strong>","tip":"<strong>Defesa:</strong> mapeie a própria vaidade e a própria carência — aquilo que você mais nega ter é exatamente por onde te seguram.","warn":True},
      {"ic":"mask","t":"Quem Parece Inofensivo Passa por Tudo","emph":"Inofensivo","b":"As Leis 21 e 22 brincam com a percepção alheia. Fazer-se mais tolo que o alvo o desarma: o subestimado age à vontade porque ninguém o vigia. E ceder no momento exato — a tática da rendição — converte a fraqueza aparente em vantagem real, comprando tempo enquanto o outro relaxa a guarda, certo de que venceu. <strong>O cordeiro encenado entra onde o lobo declarado jamais entraria.</strong>","tip":"<strong>Modelo mental:</strong> humildade exibida pode ser camuflagem — não confunda quem se faz pequeno com quem é, de fato, pequeno."},
      {"ic":"key","t":"Fale do Ganho Dele, Nunca da Sua Falta","emph":"o Ganho","b":"A Lei 13 desmonta o pedido ingênuo: invocar favores passados ou apelar à gratidão soa como cobrança e fecha a porta na hora. O sim vem leve quando você mostra o que o OUTRO lucra — fale da vantagem de quem decide, jamais da sua necessidade. <strong>As pessoas não se movem pela sua carência; movem-se pelo próprio interesse.</strong> Vista o pedido com a roupa do aliado.","tip":"<strong>Como aplicar:</strong> antes de pedir, responda em silêncio \"o que isto resolve para ele?\" — e abra a conversa exatamente por essa resposta."},
    ],
  "lessons_title":"O Caminho Curto é Torto",
  "lessons":["Ao pedir, fale do interesse do outro — a sua necessidade não move ninguém.","Localize a fraqueza-mestra antes de agir; conheça a sua antes que a usem.","Não deixe a disputa pela metade (Lei 15) — inimigo ferido e vivo volta para cobrar."]},

 {"slug":"ch06-seducao-audacia-timing","sub":"CAPÍTULO 6: Sedução, Audácia e Timing",
  "intro":"Nem todo poder se impõe; muito se conquista. Atrai-se pela imaginação alheia — que prefere o sonho ao dado —, impõe-se respeito pela audácia que não hesita, e ganha-se ou perde-se tudo pelo senso do momento. A mesma jogada, cedo ou tarde demais, fracassa igual. O timing não é detalhe: é metade da arte.",
  "cards":[
      {"ic":"spark","t":"Venda o Sonho, Não o Número","emph":"O Sonho","b":"A Lei 32 é dura com a verdade nua: ela desaponta e afasta, enquanto quem oferece uma fantasia arrebanha multidões. O desejo move mais gente que a estatística jamais moveu, e a visão sedutora vende onde o dado frio trava. Por isso esta lei é faca de dois gumes: <strong>quem só promete o sonho e nunca o concreto é o primeiro nome da sua lista de auditoria</strong> — sedução em excesso quase sempre tapa um vazio.","tip":"<strong>Como aplicar:</strong> ofereça uma visão amarrada a dados reais — e desconfie de quem entrega só encantamento, sem lastro embaixo."},
      {"ic":"mountain","t":"Ouse Inteiro ou Não Ouse","emph":"Inteiro","b":"A Lei 28 não tolera o meio-termo: a hesitação contamina o ambiente e convida ao desrespeito, enquanto o gesto pleno convence pela própria convicção, antes de qualquer argumento. A meia-audácia é o pior dos mundos — chama atenção sem impor respeito, expõe sem blindar. <strong>E o relógio fecha a conta: o mesmo lance, prematuro ou atrasado, naufraga igual.</strong> Agir bem é, antes de tudo, agir na hora.","tip":"<strong>Regra:</strong> decida com firmeza total ou recue por inteiro — e dedique ao instante o mesmo cuidado que dedica à jogada."},
      {"ic":"clock","t":"Escreva o Seu Mito Antes que Escrevam por Você","emph":"o Seu Mito","b":"A Lei 25 manda recriar-se antes que o mundo te cole um rótulo: quem não conta a própria história recebe de presente a que inventarem. Casada com o timing da Lei 35 — saber esperar e saber atacar —, a imagem deixa de ser acaso e vira obra deliberada. <strong>Ou você forja como é lido, ou aceita a versão que despejaram em você.</strong>","tip":"<strong>Modelo mental:</strong> imponha cedo a sua narrativa — o vácuo de imagem nunca fica vazio, é sempre preenchido por terceiros."},
    ],
  "lessons_title":"Atrair, Ousar, Acertar a Hora",
  "lessons":["Mova as pessoas com uma visão, não só com dados — mas desconfie de quem só vende encantamento.","Aja com audácia plena ou não aja: a hesitação convida ao desrespeito.","Trabalhe o timing tanto quanto a tática — fora da hora, a melhor jogada falha."]},

 {"slug":"ch07-defesa","sub":"CAPÍTULO 7: O Lado Defensivo",
  "intro":"Aqui o livro se vira do avesso e mostra a sua melhor face. Boa parte das 48 leis não ensina a atacar — ensina a não ser atacado: a reconhecer o vício que contagia, o presente que prende, a facção que cobra. Esta é a chave deste acervo. Nomear a manobra que vem contra você já é metade da defesa.",
  "cards":[
      {"ic":"eye","t":"Você Vira a Média de Quem te Cerca","emph":"a Média","b":"A Lei 10 trata do contágio social, e é implacável: estados de espírito e padrões de fracasso grudam sem aviso — você absorve o jeito de quem convive tanto quanto respira o ar do quarto. O eterno azarado raramente é só vítima; costuma ser a causa do próprio caos, e arrasta junto quem fica por perto. <strong>A companhia que rebaixa contamina antes que você note o cheiro.</strong>","tip":"<strong>Cuidado:</strong> escolha o círculo com método — o padrão dominante à sua volta vira o seu sem jamais pedir licença.","warn":True},
      {"ic":"mask","t":"Todo Grátis Vem com Fatura","emph":"com Fatura","b":"A Lei 40 desconfia da dádiva, e tem motivo: a generosidade súbita quase sempre embrulha um preço, e o \"presente\" instala dívida e controle vestidos de gentileza. O brinde que chega antes da negociação não é cortesia — é amarra. <strong>Aceitar o grande favor sem ver a obrigação que ele costura é afivelar a coleira com a própria mão.</strong> A reciprocidade é a corrente mais educada de todas.","tip":"<strong>Defesa:</strong> agradeça sem virar refém — pague o que recebeu ou recuse cedo, antes que o favor vire alavanca contra você."},
      {"ic":"key","t":"Saiba com Quem Está Lidando — e Não Deva a Ninguém","emph":"a Ninguém","b":"As Leis 19 e 20 protegem a sua margem de manobra. Nem todos reagem igual: ofender a pessoa errada rende um inimigo que não esquece nunca — leia o alvo antes de provocar. E não se prenda cedo demais a lado nenhum: a independência preserva o seu valor e a sua liberdade de escolha. <strong>Quem não deve a ninguém não é dono nem refém de ninguém.</strong>","tip":"<strong>Regra:</strong> fique acima das facções o máximo de tempo possível — pressa alheia em te alistar costuma ser o aviso de uma armadilha."},
    ],
  "lessons_title":"A Armadura do Acervo",
  "lessons":["Escolha o círculo com cuidado — o padrão dominante é contagioso e silencioso.","Desconfie do grátis: toda dádiva súbita cobra, mais cedo ou mais tarde.","Preserve independência e opções — quem não deve, não obedece."]},

 {"slug":"ch08-lei-suprema","sub":"CAPÍTULO 8: A Lei Suprema — Seja Informe",
  "intro":"A última lei é a mais funda de todas, e quase um desmentido das anteriores: não confie cegamente em nenhuma delas. O que tem forma fixa é previsível, e o previsível é alvo. O poder que dura não é o mais duro — é o mais fluido. Vence como a água vence a pedra: cedendo, contornando, jamais se deixando agarrar.",
  "cards":[
      {"ic":"wave","t":"Tome a Forma da Água","emph":"da Água","b":"A Lei 48 fecha o livro com a sua verdade mais profunda: forma fixa é previsível, e o previsível é atacável. Não se acorrente a um único método nem a uma identidade rígida — mude com o terreno e ninguém consegue te encurralar. <strong>Quem reage sempre do mesmo jeito já foi lido, e quem foi lido já foi manipulado.</strong> A água não vence a pedra pela dureza; vence por não ter forma que a pedra possa quebrar.","tip":"<strong>Como aplicar:</strong> varie a resposta o suficiente para não ser decifrado — padrão fixo é mira pronta; adaptar-se é blindagem viva."},
      {"ic":"mountain","t":"Trate-se como Rei e o Mundo Concorda","emph":"como Rei","b":"A Lei 34 é uma profecia que se cumpre sozinha: a postura molda como o mundo te trata, e o porte vem sempre antes do reconhecimento. Quem se conduz com a dignidade que reivindica é tratado à altura dela; quem se encolhe convida a ser encolhido. <strong>Mas ser informe não é ser sem caráter</strong> — é flexibilidade tática assentada sobre valores firmes, não areia que o primeiro vento leva.","tip":"<strong>Cuidado:</strong> mudar de forma não é trair a essência — sem um núcleo de princípios, \"informe\" deixa de ser estratégia e vira só fraqueza."},
      {"ic":"scale","t":"A Última Lei é a Régua Ética","emph":"Régua Ética","b":"Greene entregou uma lente do jogo social, não um catecismo de canalhice — e quem a usa como catecismo paga caro: corrói a própria reputação (Lei 5) e fabrica inimigos que sobrevivem a ele. O poder íntegro pertence a quem decifra o jogo sem vender a alma nele. <strong>Nomear a manobra que aplicam em você já desarma o poder dela</strong> — como na ponerologia, o reconhecimento é a própria defesa.","tip":"<strong>Regra final:</strong> a pergunta que purifica todo o acervo — \"isto está sendo usado em mim?\" — é radar de defesa, nunca mira de ataque."},
    ],
  "lessons_title":"A Lei que Governa as Outras 47",
  "lessons":["Não se prenda a um método único; adapte a forma ao terreno e não dê alvo.","A postura projeta o status — trate-se à altura e o mundo segue.","Use as 48 leis como lente ética e radar de defesa, jamais como cartilha de vilania."]},
]
