# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Admirável Mundo Novo' (Aldous Huxley)."""

BOOK = {
 "title": "Admirável Mundo Novo",
 "author": "Aldous Huxley",
 "header_light": "ADMIRÁVEL",
 "header_bold": "MUNDO NOVO",
 "subtitle": "VISÃO GERAL · A SERVIDÃO QUE SE AMA",
 "intro": "Imagine uma tirania sem torturador, sem porão, sem censura — porque ninguém deseja ler o livro proibido. No ano 632 depois de Ford, o Estado Mundial não impõe a felicidade: ele a fabrica antes do nascimento, no frasco, junto com a casta e o gosto pela casta. Não há dor, não há velhice, não há perguntas; há sexo, consumo e um grama de soma para cada pontada de tristeza. A corrente que prende este mundo não pesa, não fere e não se vê — porque cada um a beija. Então chega John, criado fora do paraíso, e comete o único crime que sobrou: <em>quer sofrer</em>.",
 "description": "O romance de Huxley sobre a distopia que ninguém perceberia ser uma. Frascos, castas, hipnopedia e soma compõem uma engenharia da felicidade tão perfeita que dispensa o medo — e é justamente por isso que assusta mais. Onde Orwell temeu a bota que esmaga, Huxley temeu o abraço que adormece: o consumo permanente, o prazer obrigatório e o entretenimento como anestésico de massa. A profecia mais incômoda do século não é a do livro queimado, mas a do livro que ninguém quer mais abrir.",
 "hook": "Você já tomou um soma hoje. Só não sabia o nome.",
 "story_promise": "SOMA: A DROGA QUE SUBSTITUI A POLÍCIA",
 "story_lessons": [
   "O Estado não proíbe a liberdade — ele te faz não querer mais.",
   "Anestesiar toda dor anestesia também a profundidade da vida.",
   "Você não vê a jaula quando a jaula é o seu próprio prazer.",
 ],
 "tags": ["Distopia", "Filosofia", "Consumismo"],
 "progress": "8 Capítulos",
 "cover": "assets/admiravel-mundo-novo-cover.png",
 "overview_cards": [
   {"ic":"spark","t":"Controle pelo Prazer, Não pela Dor","b":"Orwell imaginou uma bota pisando um rosto humano; Huxley imaginou uma carícia. Aqui ninguém é preso, espancado ou silenciado — todos são <strong>saciados</strong> antes de sentirem falta de algo. O poder não censura o desejo: ele o atende com tanta pontualidade que a revolta morre de fome. <strong>A corrente perfeita é a que a vítima beija.</strong>","tip":"<strong>Modelo mental:</strong> desconfie da distopia que parece um anúncio — a mais difícil de derrubar é a que lhe dá tudo o que você pediu."},
   {"ic":"layers","t":"As Cinco Castas Pré-Fabricadas","b":"De Alfa a Épsilon, a desigualdade aqui não é uma falha a remediar — <strong>é o produto saindo da linha de montagem exatamente como projetado</strong>. Cada um foi otimizado no frasco para adorar o trabalho que lhe coube e ter pena de quem está acima e abaixo. Ninguém inveja, ninguém se revolta. A jaula mais segura é a que o prisioneiro confunde com lar.","tip":"<strong>Para refletir:</strong> a injustiça mais completa não é a que oprime a vítima — é a que a constrói feliz com a própria opressão.","list":["<strong>Alfa</strong> — líderes e pensadores.","<strong>Beta</strong> — técnicos e administração.","<strong>Gama</strong> — trabalho qualificado simples.","<strong>Delta</strong> — trabalho braçal.","<strong>Épsilon</strong> — trabalho mais bruto (privados de oxigênio no frasco)."],"wide":True},
   {"ic":"bulb","t":"O Direito de Ser Infeliz","b":"Oferecem a John o paraíso inteiro, de graça, e ele o devolve: <em>\"Reivindico o direito de ser infeliz\"</em> — e com ele Deus, a poesia, o perigo, o envelhecer, o pecado. Pede de volta tudo o que dói, porque intui que sem a dor não sobra ninguém para ser feliz. <strong>A pergunta que Huxley deixa sem resposta: uma felicidade que custa a alma ainda vale ser chamada de felicidade?</strong>","tip":"<strong>Para refletir:</strong> abolir todo sofrimento parece misericórdia — até se notar que ele é o avesso de tudo que dá peso a uma vida."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-estado-mundial-divisa","sub":"CAPÍTULO 1: O Estado Mundial e a Divisa",
  "intro":"Antes de qualquer personagem, o verdadeiro protagonista é o mundo. Em 632 depois de Ford, três palavras gravadas sobre a porta — 'Comunidade, Identidade, Estabilidade' — resumem um planeta que pagou a abolição do sofrimento com a abolição de tudo o que tornava o sofrimento suportável: a liberdade, a arte, o amor. O paraíso já está pronto. Falta só descobrir o que ele engoliu para existir.",
  "cards":[
      {"ic":"mountain","t":"Estabilidade Como Deus","emph":"Estabilidade","b":"Neste mundo, o pecado capital não é a crueldade — é a mudança. A <strong>estabilidade</strong> reina acima da verdade, da beleza e da liberdade, e tudo o que pudesse balançá-la foi cirurgicamente removido da vida: a paixão, a família, a velhice, o tédio, a dúvida. <strong>Uma máquina perfeitamente lubrificada cujo único propósito é nunca, jamais, parar.</strong>","tip":"<strong>Para refletir:</strong> não confunda estabilidade com paz. Um pântano também é estável — e nada de vivo cresce nele sem se mexer."},
      {"ic":"layers","t":"O Lema Invertido","emph":"Lema Invertido","b":"Leia o lema duas vezes e ele se desmancha: <em>Comunidade</em> que não admite indivíduos, <em>Identidade</em> carimbada de fora antes do nascimento, <em>Estabilidade</em> que é só estagnação com boa iluminação. <strong>Cada palavra foi mantida e teve a alma extraída</strong> — é a primeira pista de que aqui todo valor anda de cabeça para baixo.","tip":"<strong>Modelo mental:</strong> quando um mundo se gaba da própria felicidade, leia o elogio como acusação. Quanto mais perfeito o slogan, mais fundo o que ele esconde."},
      {"ic":"eye","t":"A Distopia ao Avesso","emph":"Avesso","b":"Procure o tirano e você não o encontra: não há campo de tortura, não há livro queimado, não há grito de revolta abafado. O controle chegou antes de você — no frasco, no berço, no sono. Ele não dobra a sua vontade; <strong>molda o seu desejo, para que você queira exatamente a coleira</strong>. O abraço que sufoca é mais perfeito que a bota na cara, porque ninguém luta contra um abraço.","tip":"<strong>Contraste com 1984:</strong> Orwell temia quem nos proibiria de ler. Huxley temia algo pior — que não restasse mais ninguém querendo ler."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["A ameaça de Huxley não usa botas: é o conforto total, oferecido com sorriso, virando cela.","Erguer a estabilidade acima de tudo mata exatamente o que torna humana a vida — a mudança, o risco, o crescimento.","Um lema pode ser a mais perfeita das mentiras: três palavras nobres, cada uma virada do avesso."]},

 {"slug":"ch02-fabricacao-castas","sub":"CAPÍTULO 2: A Fabricação de Gente e o Sistema de Castas",
  "intro":"Visite a maternidade deste mundo e você acha uma fábrica. Aqui ninguém nasce: as pessoas são decantadas de frascos numa esteira, sob luz vermelha. O Processo Bokanovsky pega um único óvulo e o obriga a render até 96 gêmeos idênticos — caixas e caixas de gente igual. E o mais frio: a desigualdade que sai dessa linha não é um defeito a corrigir. É a especificação do produto.",
  "cards":[
      {"ic":"steps","t":"A Fábrica de Seres Humanos","emph":"Fábrica","b":"O <strong>Processo Bokanovsky</strong> aplica o gênio de Ford ao nascimento: lotes de gêmeos idênticos, fabricados em série para servir à mesma máquina na mesma fábrica. Onde nós veríamos um milagre, o Estado vê um problema de qualidade — porque <strong>cada pessoa diferente é uma peça que não encaixa</strong>. A semelhança é estabilidade engarrafada; a individualidade, um defeito de fabricação.","tip":"<strong>Modelo mental:</strong> padronizar gente é o passo seguinte, e perfeitamente lógico, de uma civilização que já padronizou tudo o mais."},
      {"ic":"triangle","t":"A Desigualdade Desejada","emph":"Desejada","b":"Os Épsilons são embrutecidos de propósito — sufocados de oxigênio ainda no frasco — para que sejam genuinamente felizes em tarefas que enlouqueceriam um Alfa. Aqui não há explorado infeliz a resgatar: <strong>a vítima foi projetada para amar o seu próprio rebaixamento</strong>. O horror não está no que se faz a ela, mas em ela aplaudir.","tip":"<strong>Para refletir:</strong> 'eficiência' e 'estabilidade' são as duas palavras com que toda atrocidade pede licença para entrar — quando postas acima da dignidade de uma pessoa."},
      {"ic":"key","t":"Casta é Destino Sem Escolha","emph":"Destino Sem Escolha","b":"Não há escada social porque não houve acaso: ninguém poderia ter sido outra coisa. O futuro de cada um foi fixado antes do primeiro respiro, e por isso o Diretor chama o Bokanovsky, com orgulho, de <strong>'um dos maiores instrumentos da estabilidade social'</strong>. A frase é dita como elogio — e é a mais arrepiante do capítulo.","tip":"<strong>Modelo mental:</strong> aplicar a produção em massa ao ser humano não tira a liberdade depois; tira a possibilidade de ela ter existido."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["A linha de montagem não fabrica só objetos: fabrica pessoas — e sufoca a individualidade antes do primeiro respiro.","A desigualdade deste mundo é biológica, planejada e, pior, querida pela própria vítima.","Toda atrocidade entra de gravata quando 'eficiência' e 'estabilidade' valem mais que a dignidade humana."]},

 {"slug":"ch03-condicionamento-hipnopedia","sub":"CAPÍTULO 3: O Condicionamento — Hipnopedia e Pavlov",
  "intro":"O frasco entrega o corpo; falta domar a mente. E aqui está a obra-prima do Estado: ele não vigia o pensamento como faria um tirano — ele o jardina desde o berço, podando antes que cresça. A tirania que Orwell imaginou precisava esmagar o desejo de liberdade. A de Huxley é mais refinada: faz com que esse desejo nunca chegue a nascer.",
  "cards":[
      {"ic":"wave","t":"Condicionamento Neopavloviano","emph":"Neopavloviano","b":"Estendem livros e rosas diante de bebês Deltas e, no instante em que as mãozinhas se aproximam, disparam choques e alarmes. Repete-se até a lição grudar na carne: flores e leitura passam a doer. <strong>Quando esses bebês crescerem, odiarão a natureza e os livros sem jamais saber por quê</strong> — e acharão que a aversão é deles. O controle não vem depois da consciência; chega antes dela.","tip":"<strong>Para refletir:</strong> a liberdade impossível de defender é a que você foi treinado a não querer. Não se sente falta de uma porta cuja existência se desaprendeu.","wide":True},
      {"ic":"bubble","t":"Hipnopedia: o Slogan que Substitui o Pensamento","emph":"Slogan","b":"Enquanto dormem, sussurram nos seus ouvidos, milhares de vezes: 'todo mundo pertence a todo mundo', 'fora é melhor que conserto', 'um grama na hora certa'. De manhã, eles acordam donos de convicções que nunca examinaram. <strong>É pensamento terceirizado, moral pré-mastigada e servida quente</strong> — a reflexão substituída por uma frase de efeito que a pessoa toma por bom senso seu.","tip":"<strong>Modelo mental:</strong> repetir uma frase não é pensá-la. Pegue-se no flagrante de recitar um slogan onde devia estar raciocinando."},
      {"ic":"mask","t":"A Felicidade Implantada","emph":"Implantada","b":"E o pior é que funciona: estes cidadãos são, de fato, felizes. Não fingem, não disfarçam — sorriem de verdade. Daí o golpe que o livro desfere: <strong>uma felicidade que ninguém escolheu e que ninguém tem como pôr em dúvida ainda é felicidade?</strong> Ou é só a vitória definitiva sobre todos os que poderiam um dia ser infelizes?","tip":"<strong>Para refletir:</strong> a mesma mão educa e doutrina. A diferença mora num detalhe: ensinar a pensar, ou ensinar a obedecer sem perceber que obedece."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["A tirania mais perfeita não reprime o anseio de liberdade — faz com que ele jamais venha a nascer.","Um slogan repetido até virar convicção é o funeral da reflexão, com flores de senso comum.","Felicidade que não se escolheu nem se pode questionar tem outro nome: é servidão de bom humor."]},

 {"slug":"ch04-soma-felicidade-quimica","sub":"CAPÍTULO 4: Soma e a Felicidade Química",
  "intro":"Toda ditadura precisa de um porão para os inconformados. Esta tem um comprimido. O soma é a obra-prima farmacêutica do regime — 'todas as vantagens do cristianismo e do álcool, nenhum de seus defeitos': um feriado da realidade que não cobra ressaca. Com ele, a revolta deixa de ser proibida e passa a ser impensável. Quem está sempre contente nunca chega a perguntar por quê.",
  "cards":[
      {"ic":"leaf","t":"A Felicidade Como Algema","emph":"Algema","b":"Bateu uma tristeza, uma dúvida, um princípio de raiva? Um grama, e o desconforto evapora antes de virar pergunta. <strong>De um só gole, o soma faz o trabalho da polícia, da propaganda e do cassetete</strong> — e ainda agrada. É a algema mais elegante já inventada: o prisioneiro a engole sozinho, agradecido, e chama isso de bem-estar.","tip":"<strong>Modelo mental:</strong> num mundo assim, toda emoção difícil vira sintoma a ser medicado — nunca um sinal a ser escutado. E o que cala o sinal apaga também a notícia."},
      {"ic":"spark","t":"Anestesia, Não Plenitude","emph":"Anestesia","b":"Repare: o soma nunca resolve um conflito — apenas o adormece. E <strong>quem anestesia toda dor anestesia, no mesmo gesto, toda profundidade</strong>, porque é do desconforto que brotam a arte, a reflexão e a vontade de mudar. A felicidade aqui não é uma plenitude; é o silêncio de uma vida que parou de incomodar — e de sentir.","tip":"<strong>Para refletir:</strong> o soma é a metáfora afiada de toda distração que serve para uma coisa só: nos impedir de ficar a sós com a própria inquietação."},
      {"ic":"eye","t":"O Preço Político do Conforto","emph":"Preço Político","b":"Um povo permanentemente satisfeito é um povo que nunca pergunta 'por quê?'. Aí mora a genialidade política do soma: <strong>ele dissolve a indignação antes que ela encontre outra indignação e vire multidão</strong>. Não há protesto a reprimir porque não houve protesto. A calmaria fabricada é a forma mais eficiente — e mais invisível — de tirar um povo da política.","tip":"<strong>Sinal de alerta:</strong> diante de todo conforto bom demais, faça a única pergunta que o poder não quer: 'o que isto aqui está me ajudando a não notar?'","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["Uma sociedade pode ser dominada não pelo que a faz sofrer, mas pelo que a faz sentir-se bem — a felicidade vira algema.","Anestesiar toda dor anestesia a profundidade junto: sem desconforto não nascem reflexão, arte nem mudança.","O conforto fabricado é o mais silencioso dos golpes: despolitiza um povo sem que ele perceba ter sido roubado."]},

 {"slug":"ch05-consumismo-tabu-solidao","sub":"CAPÍTULO 5: Consumismo, Sexo e os Tabus",
  "intro":"Neste mundo, a virtude tem prateleira e o pecado tem cama. A máquina precisa girar sem parar, então comprar e descartar viram deveres patrióticos; e como o desejo represado é perigoso, o sexo é distribuído como recreação, livre e sem peso. O que sobra de proibido é o avesso de tudo isso: a solidão, o silêncio, a arte que dói, Deus. Tudo o que poderia levar alguém para dentro de si mesmo.",
  "cards":[
      {"ic":"target","t":"Consumir é um Dever Cívico","emph":"Dever Cívico","b":"'Fora é melhor que conserto', cantarolam desde o berço: jogar fora é mais nobre que remendar. Gastar mantém as fábricas girando, e fábricas girando é estabilidade. <strong>O consumo aqui não é escolha nem liberdade — é o ralo oficial por onde a energia que viraria revolta escorre, inofensiva, em compras</strong>.","tip":"<strong>Para refletir:</strong> quando comprar vira a sua identidade, o sistema que lucra com isso já dispensou a propaganda. Você faz o trabalho dele de graça."},
      {"ic":"person","t":"'Todo Mundo Pertence a Todo Mundo'","emph":"Todo Mundo Pertence a Todo Mundo","b":"O sexo virou esporte sem consequência; em troca, 'mãe' é palavra obscena, e o amor exclusivo, a fidelidade e a família foram banidos como vícios. <strong>Não por puritanismo — pelo contrário: porque o laço forte é o foco número um de instabilidade.</strong> O prazer farto e sem dono serve para gastar a tensão emocional antes que ela cometa o crime de virar amor.","tip":"<strong>Para refletir:</strong> trocar o amor pela recreação não liberta ninguém — apenas esvazia o vínculo mais profundo e o deixa leve o bastante para não prender em nada."},
      {"ic":"gap","t":"O Tabu da Interioridade","emph":"Interioridade","b":"A solidão, o silêncio, a arte que machuca e a religião foram proscritos por um motivo só: <strong>são portas para dentro — e lá dentro o Estado não tem jurisdição</strong>. Por isso o cidadão modelo nunca está só: está sempre no grupo, sempre ocupado, sempre distraído. A agenda lotada é uma cela sem grades.","tip":"<strong>Modelo mental:</strong> todo poder teme a interioridade, e com razão — é por dentro que a revolta começa, num minuto de silêncio que ninguém vigiou."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Não é só a escassez que escraviza: o excesso de prazer e de consumo prende com a mesma eficiência — e com aplauso.","Banir a solidão, a arte que dói e a religião é banir a interioridade; sem ela, não sobra indivíduo, só multidão.","Prazer dirigido é controle disfarçado de festa: gasta de antemão a energia que viraria amor, laço ou revolta."]},

 {"slug":"ch06-bernard-lenina-desajuste","sub":"CAPÍTULO 6: Bernard e Lenina — o Desajuste e o Desejo",
  "intro":"Toda fábrica produz defeitos, e até o paraíso tem os seus. Aqui as primeiras rachaduras têm nome: Bernard Marx, baixo demais para um Alfa e por isso inseguro de mais; Helmholtz Watson, inteligente e talentoso de mais para caber no molde. E há Lenina — sem nenhum defeito, perfeitamente ajustada, perfeitamente feliz. Ela é a peça impecável que sai da linha. E é, por isso mesmo, a tragédia mais silenciosa do livro.",
  "cards":[
      {"ic":"pivot","t":"Inadaptação Como Consciência","emph":"Inadaptação","b":"É exatamente por não encaixarem direito no molde que Bernard e Helmholtz conseguem espiar o sistema por uma fresta de fora. <strong>Num mundo feito de cópias, o que sobra de indivíduo se esconde no defeito de fabricação</strong> — e o Estado, claro, trata esse defeito como doença, com um diagnóstico e um frasco de soma à mão.","tip":"<strong>Para refletir:</strong> quem range no encaixe ainda consegue pensar; quem desliza perfeitamente para o lugar perdeu, sem saber, esse privilégio."},
      {"ic":"mask","t":"Duas Rebeldias, Dois Testes","emph":"Duas Rebeldias","b":"Cuidado em confundir os dois rebeldes. Bernard se revolta por <strong>ressentimento</strong> — quer mesmo é ser aceito; mal vira celebridade, abraça tudo o que jurava desprezar. Helmholtz se revolta por <strong>excesso</strong> — sente que tem algo a dizer e o mundo não tem onde caber — e aceita o exílio sem drama. <strong>A verdadeira prova de um rebelde não é a queixa: é o que ele faz quando o sistema enfim o recompensa.</strong>","tip":"<strong>Modelo mental:</strong> revolta por despeito e revolta por princípio usam as mesmas palavras de raiva, mas são feitas de matérias opostas. Espere a oferta de paz para distinguir as duas."},
      {"ic":"person","t":"Lenina: o Produto Perfeito","emph":"Produto Perfeito","b":"Bela, sempre alegre, promíscua por hábito e não por desejo, Lenina é incapaz de entender o amor que John vai lhe oferecer — porque nela a capacidade de amar foi desligada antes que houvesse um 'ela' para escolhê-la. <strong>Ela não é vilã; é vítima, e a mais comovente, justamente por ser o produto perfeito</strong>. Não lhe falta nada. Falta-lhe tudo, e ela não sente falta.","tip":"<strong>Para refletir:</strong> a obra-prima do condicionamento é uma pessoa incapaz de amar — e essa atrofia, indolor e sorridente, é o verdadeiro preço da estabilidade."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Num mundo todo padronizado, só quem desencaixa ainda consegue pensar — a inadaptação como último fiapo de humanidade.","Revolta por ressentimento e revolta por princípio são dois mundos: a recompensa é o reagente que revela qual é qual.","O produto perfeito do condicionamento não sabe amar — e é uma mutilação tão silenciosa que a própria vítima sorri."]},

 {"slug":"ch07-reserva-selvagem-john","sub":"CAPÍTULO 7: A Reserva Selvagem — Linda, John e Shakespeare",
  "intro":"Para se ver um mundo, é preciso alguém que venha de fora dele. Na Reserva dos Selvagens — um pedaço do planeta deixado intocado, com seus deuses, seus partos e suas dores —, Bernard reencontra Linda, sumida há vinte anos, e o filho que ela teve ali: John, o Selvagem, criado entre os índios e por Shakespeare, capaz de amar, crer e sofrer. Pelos olhos dele, o 'admirável mundo novo' deixa de ser paraíso e se revela monstro.",
  "cards":[
      {"ic":"lens","t":"O Olhar de Fora","emph":"Olhar de Fora","b":"John é o forasteiro de que a história precisava: <strong>o único par de olhos que enxerga a distopia sem ter sido condicionado a achá-la normal</strong>. O que para Londres é rotina civilizada, para ele é horror — e é esse espanto que nos serve de régua. Onde ele recua enojado, mede-se exatamente o quanto este mundo amputou de humano para ficar tão limpo.","tip":"<strong>Modelo mental:</strong> ninguém enxerga a própria jaula por dentro. É preciso o estranho — alguém que não foi treinado a não ver — para que ela, de repente, fique visível."},
      {"ic":"book","t":"Shakespeare Como Contramotivo","emph":"Contramotivo","b":"John pensa, ama e sofre em verso — Shakespeare é a língua da sua alma e, no fim, a causa da sua ruína. E é precisamente essa linguagem da paixão, da tragédia e da grandeza humana que o Estado riscou do mundo. <strong>A grande literatura é subversiva não por pregar revolta, mas por manter vivas a profundidade e a dor que tornam a revolta possível</strong>.","tip":"<strong>Para refletir:</strong> arte que machuca é perigosa para o poder porque dá sentido ao sofrimento — e dar sentido ao sofrimento é a primeira frase de toda resistência."},
      {"ic":"fork","t":"A Reserva Não é o Paraíso","emph":"Paraíso","b":"Não caia na armadilha: Huxley não pinta a Reserva como o éden perdido. Ela é suja, cruel, doente e supersticiosa. <strong>O livro recusa de propósito a falsa escolha entre 'tecnologia má' e 'natureza boa'</strong> — porque o humano se perde nos dois extremos. John sonha com Londres de longe e, ao chegar, descobre que o céu prometido é só outra forma de inferno.","tip":"<strong>Modelo mental:</strong> 'ó admirável mundo novo!', exclama John, deslumbrado — e a frase, roubada de Shakespeare, vira a ironia mais amarga do livro quando o deslumbramento desaba."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["Só um olhar de fora — não-condicionado — consegue revelar a distopia em que se vive como se fosse normal.","A arte trágica ameaça o poder porque conserva vivos a paixão e o sentido que ele trabalhou tanto para apagar.","O livro rejeita a dicotomia preguiçosa 'tecnologia má × natureza boa': o inimigo verdadeiro é a perda do humano, em qualquer margem."]},

 {"slug":"ch08-debate-mond-john-fim","sub":"CAPÍTULO 8: O Debate Mond × John e o Fim",
  "intro":"Agora o livro tira a máscara e vira debate de ideias. No gabinete de Mustafá Mond — o Controlador que conhece Shakespeare, Deus e a verdade, e mesmo assim escolheu este mundo — John exige de volta o direito de ser infeliz. Mond, sem fingir, confessa o preço que o paraíso pagou. Os dois têm razão, e é aí que dói. Sem lugar no Estado nem fora dele, John faz a única coisa que lhe resta. E a pergunta não se fecha.",
  "cards":[
      {"ic":"scale","t":"A Grande Troca","emph":"Grande Troca","b":"Mond não nega nada — admite tudo: <strong>trocaram a verdade, a beleza e a liberdade por conforto e estabilidade</strong>, e ponto. A arte, a ciência de verdade e Deus foram sacrificados não por maldade, mas porque ameaçavam a felicidade do rebanho. <strong>O defensor da distopia é o homem mais lúcido do livro</strong> — e é justamente a lucidez dele, não a estupidez, que torna o debate insuportável.","tip":"<strong>Modelo mental:</strong> Mond não é um vilão de papelão. Dê ao sistema os seus melhores argumentos, a sério e sem trapaça — só assim a recusa de John vale alguma coisa.","wide":True},
      {"ic":"mountain","t":"'O Direito de Ser Infeliz'","emph":"Direito de Ser Infeliz","b":"Oferecem a John o pacote completo da felicidade e ele recusa item por item, exigindo o oposto: Deus, poesia, perigo, liberdade, bondade, pecado — <strong>e o direito de envelhecer, adoecer, ter medo e sofrer</strong>. Uma felicidade sem nada disso, diz ele, não vale a pena ser vivida. É a reivindicação mais radical, e mais humana, de todo o romance.","tip":"<strong>Para refletir:</strong> o sofrimento e a dificuldade não são só males a varrer para longe — são a outra metade do que dá peso, sentido e dignidade a uma vida."},
      {"ic":"gap","t":"O Fim Trágico Como Tese","emph":"Fim Trágico","b":"John não cabe no Estado nem aguenta o que há fora dele; encurralado entre dois mundos, tira a própria vida. Mais que desfecho de personagem, é o veredito da obra: <strong>a civilização do prazer total e a alma humana não conseguem ocupar o mesmo espaço</strong>. O suicídio não é uma solução nem uma derrota dele — é o impasse virado aviso, deixado de pé para nós.","tip":"<strong>Para refletir:</strong> talvez a distopia mais perigosa não seja a que nos tira tudo à força, e sim a que nos dá tudo o que pedimos — e, em troca silenciosa, leva tudo o que somos."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["A grande troca está na mesa, e Mond a confessa: verdade, beleza e liberdade entregues em troca de conforto e estabilidade.","'Reivindico o direito de ser infeliz' — o sofrimento vem no mesmo pacote da humanidade, e é parte do que dá sentido à vida.","A distopia mais temível talvez seja a que atende a todos os nossos pedidos enquanto, sem alarde, nos rouba quem somos."]},
]
