# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'As Armas da Persuasão'
(Robert B. Cialdini). Frameworks: padrões fixos (clique-zumm), contraste, e os 6
princípios da influência (reciprocidade, compromisso/coerência, prova social,
afeição, autoridade, escassez) + a unidade como 7º. Para cada princípio: como
funciona e como se defender. Síntese atribuída — não reproduz o texto."""

BOOK = {
 "title": "As Armas da Persuasão",
 "author": "Robert B. Cialdini",
 "header_light": "AS ARMAS",
 "header_bold": "DA PERSUASÃO",
 "subtitle": "VISÃO GERAL · OS 6 PRINCÍPIOS DA INFLUÊNCIA",
 "intro": "Cialdini passou anos como 'otário' infiltrado: vendedores, arrecadadores, recrutadores — gente que vive de conseguir o 'sim'. Descobriu que todos exploram os mesmos seis atalhos que nosso cérebro usa para não ter de pensar em tudo. Os atalhos são bons; o problema é quem falsifica o gatilho para acionar a reação sem o conteúdo que a justificava. Este é o mapa das seis (mais uma) armas — e, em cada uma, onde fica o botão da defesa.",
 "description": "O estudo de campo de Robert Cialdini sobre por que dizemos 'sim'. Reagimos como animais com fitas gravadas — um único traço-gatilho (clique) dispara a reação inteira (zumm) —, e julgamos tudo por contraste com o que veio antes. Sobre essa mecânica trabalham os 6 princípios universais: reciprocidade, compromisso e coerência, prova social, afeição, autoridade e escassez (a unidade entra como 7º). Cada capítulo mostra o experimento, a tática que o explora e como recusar sem culpa.",
 "tags": ["Persuasão", "Influência", "Psicologia"],
 "progress": "8 Capítulos",
 "cover": "assets/armas-da-persuasao-cover.png",
 "overview_cards": [
   {"ic":"target","t":"Os 6 Princípios da Influência","b":"Toda persuasão eficaz aciona um destes gatilhos universais:","list":[
     "<strong>Reciprocidade</strong> — retribuímos o que recebemos.",
     "<strong>Compromisso e Coerência</strong> — agimos conforme o que já assumimos.",
     "<strong>Prova Social</strong> — fazemos o que os outros (parecidos) fazem.",
     "<strong>Afeição</strong> — dizemos sim a quem gostamos.",
     "<strong>Autoridade</strong> — obedecemos a (símbolos de) quem 'sabe'.",
     "<strong>Escassez</strong> — valorizamos o que é raro ou está acabando.",
   ],"tip":"<strong>Como usar:</strong> as edições novas somam a <strong>Unidade</strong> — o 'nós' de grupo — como 7º princípio, o mais difícil de farejar.","wide":True},
   {"ic":"spark","t":"Clique, Zumm: os atalhos mentais","b":"A perua aquece qualquer bola de penas que faça 'piu-piu' — e nós também rodamos fitas gravadas. <strong>Um traço-gatilho (preço alto = 'caro é bom') liga a reação inteira sem análise.</strong> O atalho poupa o esforço de pensar — e por isso é ouro nas mãos de quem aprende a imitar só o gatilho.","tip":"<strong>Modelo mental:</strong> a fita toca do começo ao fim com um clique — eficiente até ser falsificada."},
   {"ic":"key","t":"A chave é a defesa","b":"Desligar os atalhos é impossível: sem eles, decidir o supermercado paralisaria. A defesa é mais fina — <strong>flagrar o gatilho fabricado e voltar a artilharia contra o trapaceiro, não contra o atalho que costuma nos servir.</strong>","tip":"<strong>Regra-mãe:</strong> sentir-se ENGANADO — não só persuadido — é a deixa para recusar, sem dever satisfação a ninguém."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-armas-da-influencia","sub":"CAPÍTULO 1: As Armas da Influência",
  "intro":"Uma joalheria não vendia umas turquesas; na pressa, a dona mandou baixar o preço pela metade — e a vendedora, confusa, dobrou. Esgotaram em dias. 'Caro' tinha virado 'bom'. Vivemos de atalhos assim, disparados por um único traço — úteis, até alguém imitar o gatilho para acender a reação sem o conteúdo que a justificava.",
  "cards":[
      {"ic":"spark","t":"Clique, e a Fita Toca Inteira","emph":"a Fita Toca Inteira","b":"A perua aquece qualquer bola de penas que faça “piu-piu” — mesmo um furão empalhado, contanto que toque a fita. Nós também: um traço-gatilho (“caro é bom”, “todo mundo faz”) dispara a reação inteira sem análise, e o atalho nos poupa de pensar em tudo. <strong>O atalho nunca é o vilão; o vilão é quem reproduz só o gatilho e colhe a reação que não merecia.</strong>","tip":"<strong>Modelo mental:</strong> clique, e a fita toca até o fim — economia mental preciosa, e por isso mesmo falsificável."},
      {"ic":"scale","t":"O Contraste é Invisível","emph":"Invisível","b":"A mente não mede em absoluto: mede contra o que acabou de ver. Por isso a loja de roupa vende primeiro o terno e só depois o suéter — sobre o número grande, o caro vira detalhe. Depois da casa de um milhão, a de seiscentos mil parece pechincha. <strong>Quem mostra o item caro primeiro não está informando: está calibrando o seu juízo</strong> — e você jura que foi percepção, não manobra.","tip":"<strong>Como se defender:</strong> avalie cada preço sozinho, lavado da impressão do que apareceu um segundo antes.","wide":True},
      {"ic":"bulb","t":"Jiu-jítsu, Não Empurrão","emph":"Não Empurrão","b":"O persuasor hábil não empurra de fora: aciona uma força que já mora em você e deixa a gravidade trabalhar. Por isso a manobra não parece pressão — parece descoberta sua. <strong>Ele gasta pouca energia e sai de cena</strong>, enquanto o gatilho plantado segue te convencendo por dentro, no seu nome.","tip":"<strong>Sinal de alerta:</strong> reação rápida e forte a um sinal isolado — preço, jaleco, um “porque…” — é a fita rodando, não você decidindo.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Decidir por atalho é regra, não exceção; o perigo é o gatilho fabricado.","O preço, como tudo, é julgado por contraste — avalie-o isolado do que veio antes.","Guarde a análise lenta para o que é caro, raro ou irreversível."]},

 {"slug":"ch02-reciprocidade","sub":"CAPÍTULO 2: Reciprocidade",
  "intro":"Num experimento, um sujeito que comprava um refrigerante para o vizinho vendia depois o dobro de rifas a ele — e o vizinho nem precisava gostar dele para ceder. É a regra mais difundida da espécie: recebeu, deve. O favor, mesmo pequeno e não pedido, abre uma dívida que pagamos com juros.",
  "cards":[
      {"ic":"link","t":"Toda Dádiva Cria uma Dívida","emph":"uma Dívida","b":"Nenhuma sociedade humana dispensou a regra de retribuir — ela é tão funda que dispara até com o favor que ninguém pediu. A amostra grátis, o cafezinho, o brinde no envelope plantam um desconforto surdo de “estou devendo”. <strong>Para zerar a dívida aceitamos pagar mais do que recebemos</strong> — e é exatamente por isso que o “presente” chega antes do pedido.","tip":"<strong>Como se defender:</strong> aceite a gentileza genuína; mas, no instante em que ela se revela manobra, rebatize-a — a regra não manda retribuir um ardil.","wide":True},
      {"ic":"pivot","t":"A Porta na Cara","emph":"na Cara","b":"Peça um absurdo, colha o “não” previsto e recue para o pedido menor — o que você sempre quis. O recuo soa como concessão, e a regra cobra outra de volta. O escoteiro oferece o ingresso caro, leva o não, emenda “então umas barras de chocolate?” — e você sai com chocolate que nem queria. <strong>O segundo pedido só parece pequeno porque o primeiro era grande.</strong>","tip":"<strong>Sinal de alerta:</strong> pediram demais e “abriram mão” por um pedido menor? Não foi bondade, foi a alavanca da concessão.","warn":True},
      {"ic":"gap","t":"O Presente que Não é Presente","emph":"Não é Presente","b":"Quem dá primeiro escolhe o que se troca e quanto pesará a dívida — aí mora o poder da reciprocidade. O Hare Krishna crava a flor na sua mão antes de pedir o donativo, e nem aceita de volta: a flor custa centavos, a culpa custa caro. <strong>Quando o “mimo” chega cedo demais, raramente é cortesia — é um anzol jogado para fisgar o seu “sim”.</strong>","tip":"<strong>Modelo mental:</strong> antes de se sentir devedor, pergunte quem deu primeiro — e por que deu."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["O favor inicial é o que cria a dívida — repare sempre em quem deu primeiro.","Na porta na cara, o recuo é o “favor” forjado que puxa a sua concessão.","Defesa: não se deve retribuição a um truque disfarçado de gentileza."]},

 {"slug":"ch03-compromisso-coerencia","sub":"CAPÍTULO 3: Compromisso e Coerência",
  "intro":"Nos hipódromos, o apostador fica subitamente mais confiante no cavalo logo depois de apostar nele — nada mudou na pista, só que agora ele se comprometeu. Tomada uma posição, pressionamo-nos a ser coerentes com ela. Por isso um “sim” minúsculo no começo escancara a porta para os grandes.",
  "cards":[
      {"ic":"steps","t":"O Pé na Porta","emph":"na Porta","b":"Um “sim” trivial não custa nada — e é justamente por isso que é a alavanca. Aceitar o adesivo de “motorista cuidadoso” reescreve quem você acha que é; semanas depois você cede o jardim a um outdoor enorme e feio, porque já virou “o cidadão engajado”. <strong>O pedido cresce em degraus, e cada degrau parece coerente com o anterior</strong> — ninguém quer desmentir quem declarou ser.","tip":"<strong>Como aplicar:</strong> rastreie qual “sim” pequeno você assinou antes do grande — ali está a alavanca escondida."},
      {"ic":"key","t":"O que Faz o Compromisso Pegar","emph":"Pegar","b":"Nem todo “sim” gruda igual. O compromisso fixa quando é ativo, público, voluntário e trabalhoso — porque então a pessoa cria sozinha as próprias “pernas”, que seguram a decisão mesmo sem o motivo original. <strong>O que escrevemos de próprio punho e diante de testemunhas passa a nos governar</strong> — e o esforço que custou vira a prova de que valeu a pena.","tip":"<strong>Modelo mental:</strong> por escrito e em público, o compromisso vira âncora — e a âncora decide por você lá na frente.","wide":True},
      {"ic":"eye","t":"A Bola Baixa","emph":"Baixa","b":"Ofereça uma vantagem boa demais, deixe a decisão tomar corpo e então puxe a vantagem embaixo — a escolha continua de pé, já firmada nos apoios que ela criou. É o desconto que “acabou” depois do “sim”, o carro cujo preço sobe na hora de assinar. <strong>A decisão sobrevive ao incentivo que a gerou, escorada nas razões que você mesmo inventou.</strong>","tip":"<strong>Como se defender:</strong> consulte o estômago (“estou sendo coagido a isto?”) e o coração (“sabendo o que sei, escolheria assim de novo, agora?”).","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["Um “sim” pequeno, ativo e público já predispõe ao grande que virá.","Cuidado com a bola baixa: a vantagem evapora, a decisão fica de pé.","Defesa: pergunte ao estômago e ao coração antes de honrar o compromisso."]},

 {"slug":"ch04-aprovacao-social","sub":"CAPÍTULO 4: Aprovação Social",
  "intro":"As emissoras põem risadas gravadas em comédias sabendo que o público acha tudo menos engraçado — e ri mais assim mesmo. Decidimos o que é certo olhando o que os outros fazem. O atalho aperta mais sob incerteza (não sei agir, então copio) e diante de gente parecida comigo (são como eu, devem saber).",
  "cards":[
      {"ic":"constellation","t":"Incerteza e Semelhança","emph":"Semelhança","b":"Na dúvida, lemos o certo no comportamento alheio — e o atalho pesa mais sob incerteza (não sei o que fazer, então sigo) e diante de semelhantes (são como eu, devem saber). <strong>Daí a força do “mais vendido”, da fila na porta e do depoimento de alguém igual a você</strong>: provam pela quantidade, jamais pelo mérito.","tip":"<strong>Como se defender:</strong> um milhão de errados não fazem um certo — cheque os fatos, não o tamanho da manada.","wide":True},
      {"ic":"person","t":"Ninguém Ajuda Porque Ninguém Ajuda","emph":"Ninguém Ajuda","b":"Na emergência cheia de gente, cada um lê a calma do vizinho como “então não é grave” — e a multidão se enrijece na ignorância pluralística. Quanto mais testemunhas, menos socorro: a responsabilidade se reparte até evaporar. <strong>A fumaça invade a sala e quem está sozinho corre; cercado de indiferentes que fingem calma, o sujeito fica imóvel por minutos.</strong>","tip":"<strong>Como se defender:</strong> caído na rua, fure a dispersão — aponte UMA pessoa: “você, de camisa azul, chame a ambulância”."},
      {"ic":"wave","t":"O Efeito Werther","emph":"Werther","b":"A prova social no seu extremo trágico: depois da cobertura ampla de um suicídio, ondas de imitação sobem nos dias seguintes — a versão sombria de “se outros fizeram, talvez eu também”. É o mecanismo da fila, só que letal. <strong>A manada arrasta tanto para a compra quanto para o abismo</strong> — e o número que a infla nem sempre é verdadeiro.","tip":"<strong>Sinal de alerta:</strong> desconfie de prova social fabricada — avaliações compradas, plateia paga, números inflados.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["A prova social aperta mais sob incerteza e entre os que são parecidos comigo.","Multidão não é verdade: olhe os fatos, não a contagem da plateia.","Em emergência, recorte a multidão — peça ajuda a uma pessoa nomeada."]},

 {"slug":"ch05-afeicao","sub":"CAPÍTULO 5: Afeição",
  "intro":"O vendedor de carros campeão de vendas mandava milhares de cartões aos clientes, todo mês, com três palavras: “Gosto de você”. Funcionava. Dizemos sim a quem gostamos — e gostamos por gatilhos rápidos demais para notar. O perigo é deixar um afeto fabricado de propósito decidir por nós.",
  "cards":[
      {"ic":"bubble","t":"Cinco Atalhos para Gostar","emph":"Gostar","b":"Dizemos sim a quem gostamos, e gostamos por cinco gatilhos veloces demais para flagrar: a atratividade (o belo parece bom — efeito halo), a semelhança (“também sou de Minas!”), o elogio (até a bajulação escancarada cola), a familiaridade e a associação. <strong>O bom vendedor não precisa do melhor produto: precisa que você goste dele antes de decidir.</strong>","tip":"<strong>Como se defender:</strong> ao notar que gostou rápido e demais de quem vende, pare e pergunte “por quê?” — depois separe a pessoa da oferta.","wide":True},
      {"ic":"link","t":"Associação é Contágio","emph":"Contágio","b":"Transferimos sentimento por mera vizinhança: o produto ao lado da modelo bonita ou do atleta campeão herda o brilho do vizinho. Por isso o homem do tempo apanha pela chuva que apenas anunciou — grudamos o mensageiro na mensagem. <strong>O que fica perto da coisa “cola” nela, e a publicidade vive de escolher essa companhia.</strong>","tip":"<strong>Modelo mental:</strong> repare no que penduraram ao lado da oferta — beleza, fama, vitória — e desconte o brilho emprestado."},
      {"ic":"mask","t":"O Vendedor que é seu Amigo","emph":"seu Amigo","b":"Na festa Tupperware quem vende é uma amiga, na sua casa, entre conhecidas — e a oferta vem empilhada sobre reciprocidade e compromisso público. Recusar o produto soa como recusar a anfitriã. <strong>Quando afeto e negócio são fundidos de propósito, dizer “não” ao item parece dizer “não” à pessoa</strong> — e é desse atrito que a venda se alimenta.","tip":"<strong>Como se defender:</strong> aparte o sentimento pela pessoa da decisão sobre o negócio — “gosto dela; mas isto, em si, vale o preço?”.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Atratividade, semelhança, elogio, familiaridade e associação acendem o “sim”.","A associação contagia: vigie o que penduraram ao lado do produto.","Defesa: isole o mérito do negócio do afeto por quem o vende."]},

 {"slug":"ch06-autoridade","sub":"CAPÍTULO 6: Autoridade",
  "intro":"Enfermeiros experientes quase aplicaram uma dose absurda de remédio só porque a ordem, ao telefone, veio de uma voz que se disse “doutor” — sem conferir nada. Somos treinados desde cedo a obedecer a quem sabe. Útil — mas o atalho dispara diante dos meros símbolos do saber, sem checar a substância por trás.",
  "cards":[
      {"ic":"layers","t":"Três Símbolos Bastam","emph":"Símbolos","b":"Obedecemos a quem sabe — mas o gatilho responde a três sinais do saber, não ao saber em si: títulos (Dr., Professor), roupas (jaleco, uniforme) e adereços (o carro de luxo). <strong>Todos são fáceis de alegar e custosos de verificar</strong>, e por isso o impostor prefere a casca da autoridade ao seu miolo.","tip":"<strong>Como se defender:</strong> pergunte “esta autoridade é mesmo especialista NISTO?” — credencial só vale dentro da própria área.","wide":True},
      {"ic":"eye","t":"O Jaleco Não é o Médico","emph":"Não é o Médico","b":"O gatilho é o símbolo, não a competência real — e o símbolo se forja em minutos. O ator que avisa “não sou médico, mas faço um na TV” vende remédio com a credibilidade emprestada de um avental branco. <strong>Cedemos à aparência de saber muito antes de checar se há saber por baixo</strong> — e quase nunca paramos para conferir.","tip":"<strong>Como se defender:</strong> some uma segunda pergunta — “quão sincera ela está sendo aqui?”, isto é, qual é o interesse dela na minha decisão."},
      {"ic":"person","t":"Milgram e a Bota da Obediência","emph":"Milgram","b":"Pessoas comuns aplicaram o que criam ser choques cada vez mais fortes em um estranho só porque um “cientista” de jaleco dizia, calmo, “o experimento exige que continue” — e a maioria foi até o fim, contra o próprio horror. Não eram monstros: era obediência automática ao símbolo. <strong>A autoridade não precisa forçar; basta vestir-se dela para a vontade alheia se curvar.</strong>","tip":"<strong>Sinal de alerta:</strong> o risco mora em obedecer a quem só VESTE a autoridade — título alegado, uniforme, jaleco emprestado.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Reagimos a símbolos — título, roupa, adereço —, não à competência por trás deles.","A autoridade legítima só vale dentro da sua área específica.","Defesa: “é mesmo especialista nisto?” e “quão sincera está sendo aqui?”."]},

 {"slug":"ch07-escassez","sub":"CAPÍTULO 7: Escassez",
  "intro":"Quando uma loja avisava aos clientes que a carne ia faltar, eles compravam o triplo; quando dizia que a notícia era exclusiva, o triplo de novo. Damos mais valor ao que é raro ou está acabando — e a perda potencial pesa mais que o ganho equivalente. A oportunidade fugindo aciona o impulso de agarrar antes de pensar.",
  "cards":[
      {"ic":"clock","t":"Três Gatilhos do Raro","emph":"Raro","b":"Valorizamos mais o que escasseia, e o desejo acende por três alavancas: a quantidade limitada (“últimas unidades”), o prazo (“só hoje”, a contagem regressiva) e a censura (o proibido brilha mais). <strong>A raridade não muda o quanto a coisa serve — só o quanto a queremos</strong>, e confundir as duas já é metade do trabalho de quem vende.","tip":"<strong>Como se defender:</strong> rache “querer ter” de “servir para algo” — a raridade mexe no desejo, jamais no valor de uso.","wide":True},
      {"ic":"spiral","t":"O Proibido Seduz","emph":"Seduz","b":"Ameaçada a liberdade de ter ou escolher, desejamos ainda mais o que poderíamos perder — é a reatância de Brehm. Perder dói mais do que ganhar agrada, e a sombra de ficar sem distorce o juízo. <strong>Proibir um livro é o melhor anúncio que ele pode ter</strong>; cercear uma opção é o jeito mais limpo de torná-la irresistível.","tip":"<strong>Sinal de alerta:</strong> querer algo só porque foi restringido ou proibido é a reatância tomando o volante.","warn":True},
      {"ic":"target","t":"Escassez Mais Competição","emph":"Competição","b":"Junte “só resta uma” a “outro cliente já voltou para buscá-la” e o impulso de fechar agora salta ao pico. A raridade recém-criada vale mais que a antiga, e a disputa vira urgência física — o coração dispara, a posse parece escorrer dos dedos. <strong>Essa onda de excitação é o alarme, não a prova</strong> de que você precisa do item.","tip":"<strong>Como se defender:</strong> transforme a própria adrenalina em gatilho de pausa — pare e pergunte “útil, ou só raro?”."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["Raridade, prazo e proibição inflam o desejo — nunca o valor de uso.","Perder dói mais que ganhar: a ameaça de ficar sem distorce o juízo.","Defesa: use a própria excitação como sinal para parar, não para fechar."]},

 {"slug":"ch08-defesa-e-unidade","sub":"CAPÍTULO 8: Defesa e Unidade",
  "intro":"Quanto mais informação nos cerca, mais decidimos por gatilho único — não por preguiça, mas por sobrevivência: analisar tudo paralisaria. A defesa, então, não é abandonar os atalhos. É flagrar quando o gatilho foi falsificado e voltar a reação contra o explorador, nunca contra o atalho que costuma nos servir bem.",
  "cards":[
      {"ic":"lens","t":"Vigilância Seletiva","emph":"Seletiva","b":"No dilúvio de informação, decidir por um único gatilho deixou de ser preguiça e virou necessidade — examinar cada coisa nos travaria. A defesa não é desligar os atalhos: é reservar o pensamento lento para o que sai caro errar. <strong>Aceite o atalho quando o gatilho é autêntico; resista só quando ele foi fabricado para iludir você.</strong>","tip":"<strong>Regra-mãe:</strong> não tente conferir tudo — mire a análise profunda no que é caro, raro ou irreversível.","wide":True},
      {"ic":"constellation","t":"Unidade: o Sétimo Princípio","emph":"Unidade","b":"Mais fundo que gostar do parecido está o “nós” compartilhado: a família, o lugar, a identidade de grupo. Quando o outro é sentido como parte do seu eu coletivo, ele convence sem argumentar — persuadir vira falar consigo mesmo. <strong>O “um de nós” abaixa a guarda antes que qualquer razão entre em cena</strong>: é o gatilho mais difícil de farejar.","tip":"<strong>Como se defender:</strong> confirme se o “nós” é verdadeiro ou foi forjado de propósito para dissolver a sua resistência."},
      {"ic":"key","t":"A Bússola é o “Fui Usado”","emph":"Fui Usado","b":"Persuasão honesta e manipulação puxam os mesmos gatilhos; o que as separa é o gatilho ser genuíno ou plantado. Por isso a defesa final não é regra, é sensação: sentir-se enganado — não apenas persuadido — autoriza recusar e contra-atacar, sem dever desculpas. <strong>Não brigue com o atalho, que é bom; brigue com o trapaceiro que o falsificou.</strong>","tip":"<strong>Resumo 6+1:</strong> reciprocidade→não ao truque · coerência→estômago e coração · prova social→cheque os fatos · afeição→isole o negócio · autoridade→especialista e sincera? · escassez→a excitação é pausa · unidade→o “nós” é real?"},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["A defesa não é desligar os atalhos — é detectar o gatilho falsificado.","Vigilância seletiva: gaste a análise lenta onde o erro custa caro.","A Unidade (“um de nós”) é o 7º princípio — confirme sempre se é real."]},
]
