# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'A Arte da Sedução' (Robert Greene)."""

BOOK = {
  "title": "A Arte da Sedução",
  "author": "Robert Greene",
  "header_light": "ARTE DA",
  "header_bold": "SEDUÇÃO",
  "subtitle": "VISÃO GERAL · O PODER QUE NÃO PRECISA PEDIR",
  "intro": "A força encontra muros; a sedução encontra portas que se abrem por dentro. É o mais antigo e o mais delicado dos poderes — aquele que faz o outro caminhar até você jurando que a ideia foi dele. Greene não traça um manual de conquista: disseca o teatro. Nove tipos de sedutor, cada um vendendo a fantasia exata de um vazio; um Anti-Sedutor que afugenta sem saber por quê; vinte e quatro manobras encenadas em quatro atos. Leia-o como espelho, não como roteiro: a única defesa contra ser conduzido é enxergar a mão que conduz.",
  "description": "A Arte da Sedução de Robert Greene como mapa do poder mais suave que existe. Os 9 tipos de sedutor (Sereia, Libertino, Amante Ideal, Dândi, Natural, Coquete, Encantador, Carismático, Estrela) — cada um uma promessa moldada a uma carência; o Anti-Sedutor, retrato do que repele; os tipos de vítima; e as 24 manobras coreografadas em 4 fases (separar, penetrar, precipitar, o tombo). Aqui em chave analítica: não para enredar ninguém, mas para reconhecer o fio invisível — no flerte, no anúncio, no púlpito, no líder — e decidir, com os olhos abertos, se você cede.",
  "tags": ["Poder", "Influência", "Psicologia"],
  "progress": "9 Capítulos",
  "cover": "assets/arte-da-seducao-cover.png",
  "overview_cards": [
    {"ic":"spark","t":"Sedução é Poder Suave","b":"A força exige e cobra resistência; a sedução <strong>convida</strong> — e o outro se entrega convencido de que a vontade foi sua. Seu segredo é uma inversão: o sedutor cala o próprio ego para escutar o que <strong>falta</strong> na vida do alvo, e então se faz, sob medida, a resposta àquele vazio. Não se vence pela vaidade própria, mas pela fome alheia.","tip":"<strong>Chave analítica:</strong> diante de qualquer encanto, pergunte 'que carência minha isto explora?'. Nomear a fome devolve a você a escolha de saciá-la ou não."},
    {"ic":"person","t":"Os 9 Tipos + o Anti-Sedutor","b":"Cada tipo encanta por uma qualidade soberana e vende uma fantasia precisa — a Sereia oferece perigo, o Encantador oferece um espelho onde você brilha. Não são gavetas rígidas: são <strong>máscaras</strong> que se vestem ou se reconhecem no rosto alheio. O Anti-Sedutor é o avesso do catálogo — quem repele sem suspeitar do próprio cheiro.","tip":"<strong>Modelo mental:</strong> 'que promessa este rosto me faz?'. Cada tipo é uma fantasia diferente talhada para uma fome diferente — descubra qual fome é a sua.","wide":True},
    {"ic":"steps","t":"As 4 Fases (24 Manobras)","b":"Sedução não é um lance: é uma <strong>peça em quatro atos</strong>, com tensão crescente e clímax marcado. <strong>1</strong> Separar — afastar o alvo da rotina e plantar o desejo · <strong>2</strong> Penetrar — dar prazer e confundir até o juízo vacilar · <strong>3</strong> Precipitar — inflamar pela ausência e pela audácia · <strong>4</strong> O Tombo — consumar sem deixar a rotina matar o feitiço.","tip":"<strong>Como aplicar:</strong> a ordem é lei. Audácia no terceiro ato sem o vínculo dos dois primeiros não é sedução — é assédio, e o alvo sente a diferença na pele."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-seducao-como-poder",
    "sub": "CAPÍTULO 1: A Sedução como Poder",
    "intro": "Quem empurra desperta o instinto de empurrar de volta. O sedutor sabe disso e nunca empurra: ele cria um vazio e espera o outro correr para preenchê-lo. Paciente, oblíquo, teatral, age na sombra da intenção — e quando o alvo finalmente cede, sai jurando que a escolha nasceu nele. Eis o avesso da força: ela conquista corpos; a sedução conquista vontades.",
    "cards": [
      {"ic":"spark","t":"O Poder que Atrai","emph":"Atração","b":"A força arromba a porta e encontra trancas novas a cada visita. A sedução faz algo mais astuto: cava no outro um <strong>vazio que ardendo pede para ser preenchido</strong> — e se oferece, sem pressa, como a única coisa que cabe ali. O cálculo existe, frio e exato, mas se veste de acaso; e o acaso é o disfarce predileto de toda estratégia que funciona.","tip":"<strong>Modelo mental:</strong> pense menos como caçador e mais como dramaturgo. A presa que se sente caçada foge; a que se sente protagonista de um romance, fica."},
      {"ic":"eye","t":"A Fome do Outro","emph":"Carência","b":"O sedutor medíocre fala de si; o perigoso emudece e <strong>escuta o que falta na vida do outro</strong> — a ferida que não cicatriza, a fantasia que ninguém ouve, o tédio que pesa como chumbo. Esse vazio é a fechadura. Mapeada a fechadura, descobre-se qual máscara vestir para servir de chave.","tip":"<strong>Pista:</strong> ouça do que a pessoa reclama e o que ela idealiza — nas queixas e nos sonhos mora a fenda por onde se entra."},
      {"ic":"mask","t":"O Esforço Invisível","emph":"Naturalidade","b":"Toda a aritmética da sedução acontece nos bastidores; no palco, só fluidez. <strong>O encanto vive de parecer espontâneo</strong> — basta o alvo flagrar o suor da estratégia para que o escudo crítico se levante e a magia evapore. A graça é arte que esconde a arte: o esforço que aparece é esforço perdido.","tip":"<strong>Regra:</strong> nunca deixe ver a engrenagem. O dia em que o outro percebe o cálculo, deixa de ser seduzido e passa a se defender."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["Sedução é poder suave: atrai-se, não se força — o outro precisa crer que a escolha foi dele.", "Comece pela fome alheia, nunca pela própria intenção: o vazio do outro é o seu mapa.", "Encarne um personagem de promessa nítida e guarde o mistério — o cálculo que aparece é cálculo morto."],
  },
  {
    "slug": "ch02-tipos-sedutor-1",
    "sub": "CAPÍTULO 2: Os Tipos de Sedutor I",
    "intro": "Os quatro primeiros rostos da sedução prometem coisas distintas a fomes distintas: a Sereia promete perigo, o Libertino promete ser desejado sem freio, o Amante Ideal promete o sonho que ninguém escutou, o Dândi promete a liberdade de não caber em molde algum. Conhecer cada um é aprender a reconhecer qual fantasia está sendo vendida — e a quem.",
    "cards": [
      {"ic":"wave","t":"A Sereia e o Libertino","emph":"Sereia e Libertino","b":"Os dois apóstolos da intensidade. A <strong>Sereia</strong> envolve numa aura sensual com cheiro de perigo — promete a aventura que a rotina nega; foi a arma de Cleópatra. O <strong>Libertino</strong> arde de um desejo que parece incontrolável e faz o outro sentir-se o objeto absoluto desse fogo — ninguém resiste a ser, por um instante, o centro de uma obsessão.","tip":"<strong>Modelo mental:</strong> Sereia e Libertino vendem ardor. Seduzem quem cansou da morno e anseia ser desejado sem reservas e sem desculpas."},
      {"ic":"constellation","t":"O Amante Ideal e o Dândi","emph":"Amante Ideal e Dândi","b":"Os dois mestres do molde. O <strong>Amante Ideal</strong> estuda a fantasia secreta do outro e se esculpe nela — devolve à pessoa o romance que ela jurava existir só nos livros (proeza exaustiva de sustentar). O <strong>Dândi</strong> seduz pela ambiguidade: borra os papéis e os gêneros e promete o luxo perigoso de transgredir as convenções com elegância.","tip":"<strong>Como aplicar:</strong> Amante Ideal e Dândi vendem feitio sob medida. Seduzem quem deseja sentir-se enfim compreendido — ou enfim libertado da própria caixa."},
      {"ic":"mask","t":"Onde Cada Máscara Racha","emph":"Erro","b":"Toda máscara tem seu ponto de ruptura. <strong>Sereia</strong> sem mistério vira caricatura barata. <strong>Libertino</strong> sem aparência de sinceridade vira predador transparente. <strong>Amante Ideal</strong> que veste a <strong>própria</strong> fantasia, e não a do alvo, fracassa sempre. A regra é única: sem aura, a engrenagem aparece — e a engrenagem à vista é o fim do feitiço.","tip":"<strong>Sinal de alerta:</strong> o erro capital é projetar o próprio desejo em vez de ler o alheio. Esse anti-foco é a assinatura inconfundível do Anti-Sedutor.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["Reconheça o tipo pela promessa que ele faz — ela só prende quando casa com a fome do alvo.", "Sereia e Libertino vendem ardor; Amante Ideal e Dândi vendem o molde exato da fantasia.", "Nenhuma máscara funciona sem aura: à luz da transparência, a mecânica vira repelente."],
  },
  {
    "slug": "ch03-tipos-sedutor-2",
    "sub": "CAPÍTULO 3: Os Tipos de Sedutor II",
    "intro": "Os cinco rostos seguintes deixam o quarto e entram na praça pública. Seduzem pela espontaneidade que desarma, pela escassez que vicia, pelo agrado que envolve, pela convicção que arrebanha e pela distância que fascina. São os tipos que governam não só o flerte, mas a marca, o palanque e o púlpito — a sedução que age sobre multidões.",
    "cards": [
      {"ic":"leaf","t":"O Natural e a Coquete","emph":"Natural e Coquete","b":"Dois opostos perfeitos. O <strong>Natural</strong> seduz pela criança que não recalcou — espontaneidade e vulnerabilidade que desarmam num mundo couraçado de cinismo; ninguém ergue defesa contra quem parece incapaz de ferir. A <strong>Coquete</strong> faz o contrário: domina pelo dar-e-retirar, calor seguido de gelo calculado, a recompensa eternamente adiada que transforma a conquista num vício sem cura.","tip":"<strong>Modelo mental:</strong> um prende pela ausência de ameaça, o outro pela ausência da própria pessoa. Ternura desarma; escassez aprisiona."},
      {"ic":"person","t":"O Encantador e o Carismático","emph":"Encantador e Carismático","b":"O <strong>Encantador</strong> faz o mundo girar em torno do outro: foco total, zero confronto, e a sensação rara de ser, por inteiro, o centro das atenções de alguém. O <strong>Carismático</strong> opera em escala maior — uma aura de convicção e propósito que faz multidões marcharem atrás; não promete prazer, promete sentido, e a fome de sentido é a mais voraz de todas.","tip":"<strong>Como aplicar:</strong> o Encantador é a arma fina do convívio e do trabalho; Carismático e Estrela são a artilharia da influência em massa — marketing, política, liderança."},
      {"ic":"constellation","t":"A Estrela — Tela em Branco","emph":"Tela de Projeção","b":"A <strong>Estrela</strong> seduz por subtração: é uma tela em branco onde cada espectador pinta o próprio ideal. Presença que fascina somada à recusa de se definir — o vácuo onde cabe a fantasia de todos. Kennedy diante das câmeras, Marilyn no cinema, Warhol indecifrável: nenhum nasceu Estrela; cada um foi <strong>fabricado</strong> à força de calculado silêncio.","tip":"<strong>Sinal de alerta:</strong> Carismático sem substância degenera em demagogo. Estrela que se explica demais perde o poder — o mistério não é enfeite, é a estrutura.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["Natural e Encantador desarmam por não ameaçar; a Coquete prende pelo que recusa dar.", "Carismático e Estrela são os tipos da influência em escala — aura construída a frio, não herdada.", "Reconhecer o carisma e a 'tela Estrela' como fabricados já é resistir à projeção automática."],
  },
  {
    "slug": "ch04-anti-sedutor-vitimas",
    "sub": "CAPÍTULO 4: O Anti-Sedutor e as Vítimas",
    "intro": "Antes de aprender a atrair, convém aprender a não repelir — pois a sedução é subtração antes de adição. Este é o retrato do Anti-Sedutor, aquele que afasta sem suspeitar do próprio cheiro; e o diagnóstico do alvo, porque não existe vítima genérica: o tipo de fome dita a estratégia. A primeira jogada de toda sedução é, sempre, ler o outro em vez de exibir-se.",
    "cards": [
      {"ic":"triangle","t":"O Anti-Sedutor","emph":"Anti-Sedutor","b":"Quatro maneiras de matar o desejo antes que ele nasça: a <strong>insegurança</strong>, que suga a energia da sala e dissolve toda aura; o <strong>foco em si</strong>, de quem só fala e nunca escuta; a <strong>pressa</strong>, que força intimidade e desperta a defesa; e a <strong>transparência total</strong>, que entrega tudo e não deixa nada a imaginar. O Anti-Sedutor não tem técnica de menos — tem ruído de mais.","tip":"<strong>Regra:</strong> guarde o mistério; não diga nem mostre o todo. O desejo é planta que cresce no vácuo e morre no sufoco."},
      {"ic":"eye","t":"Ler a Fome do Alvo","emph":"Carência da Vítima","b":"Cada pessoa carrega um buraco de feitio único — a fantasia que reprime, o afeto que falta, o tédio que apodrece, o medo de envelhecer. Por isso <strong>não há vítima genérica</strong>: o gesto que arrebata um perfil é exatamente o que afugenta o outro. A leitura precede a manobra; quem não lê, atira no escuro.","tip":"<strong>Como aplicar:</strong> Casanova trocava de personagem conforme a mulher à frente — um só sedutor, fomes distintas, promessas talhadas para cada uma."},
      {"ic":"person","t":"O Seu Próprio Vazio","emph":"Próprio Perfil","b":"Aqui mora a chave analítica e a melhor defesa: <strong>conhecer a própria fome</strong>. Saber qual vazio o torna influenciável é blindagem; ignorá-lo é deixar a porta aberta. Repare — a resistência que você mais nega costuma ser o letreiro luminoso do desejo que alguém pode explorar.","tip":"<strong>Modelo mental:</strong> espelhe a fantasia do outro, jamais imponha a sua. O pecado do Anti-Sedutor é justo esse: projetar a própria necessidade em vez de ler a alheia."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["Primeiro remova os repelentes — insegurança, egocentrismo, pressa, previsibilidade —, só depois adicione encanto.", "Seduzir começa por ler a fome do outro, nunca por se exibir.", "Conhecer o próprio vazio é a defesa mais forte contra ser conduzido sem perceber."],
  },
  {
    "slug": "ch05-fase1-separar",
    "sub": "CAPÍTULO 5: Fase 1 — Separar / Criar Desejo",
    "intro": "O primeiro ato não conquista: prepara o terreno. Trata-se de afastar o alvo da rotina e do estado de guarda, semeando ao mesmo tempo desejo e uma leve inquietação. A meta é discreta e decisiva — fazer com que a pessoa passe a pensar em você sem desconfiar de que foi levada a isso.",
    "cards": [
      {"ic":"fork","t":"O Ataque Oblíquo","emph":"Indireta","b":"O avanço frontal é um aviso, e todo aviso arma a defesa. Por isso o sedutor entra de lado: como <strong>amigo, terceiro neutro, presença sem importância aparente</strong> — desarma a suspeita muito antes de acender o desejo. Conquista-se primeiro a confiança; o resto vem na esteira de uma porta já entreaberta.","tip":"<strong>Como aplicar:</strong> apareça como aliado de um interesse comum, fale de um terceiro assunto e, ao se despedir, deixe no ar um comentário ambíguo. A vontade de reaproximar tende a nascer no outro."},
      {"ic":"wave","t":"Quente e Frio","emph":"Quente e Frio","b":"O segredo não está no calor nem no gelo, mas na alternância entre os dois. Misture <strong>interesse e distância</strong> até instalar na cabeça do alvo a pergunta que não cala — 'ele gosta ou não de mim?'. Só calor sufoca; só frio é indiferença verdadeira. A dúvida entre ambos é o motor que mantém a atenção girando.","tip":"<strong>Modelo mental:</strong> tensão vale mais que declaração — o não-dito atrai mais do que a confissão. Ocupe a mente do outro, não a sua agenda."},
      {"ic":"gap","t":"Plantar a Falta","emph":"Carência","b":"Faça a pessoa sentir uma <strong>vaga insatisfação</strong> com a própria vida — um descontentamento ainda sem nome — e deixe que só você pareça caber naquele oco. Entre como objeto de desejo pela aura ou pela prova social: ser visto como cobiçado por outros faz o valor percebido subir sozinho. Queremos o que os outros querem.","tip":"<strong>Regra:</strong> confessar interesse cedo demais dissolve a tensão; escolher o alvo errado — alguém sem fenda aberta — deixa você sem porta de entrada."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["Comece pelo alvo certo e pela aproximação oblíqua — o ataque frontal arma a defesa.", "Use sinais ambíguos, quente e frio alternados, para gerar a dúvida que prende a atenção.", "Plante uma falta que só você pareça preencher — e deixe que o desejo cresça no vácuo."],
  },
  {
    "slug": "ch06-fase2-penetrar",
    "sub": "CAPÍTULO 6: Fase 2 — Penetrar / Prazer e Confusão",
    "intro": "Capturada a atenção, é hora de descer mais fundo. O segundo ato entra no mundo do alvo: dá prazer, espelha a alma alheia, afasta-a com mãos macias das referências que a protegiam e mistura doçura com dor até o juízo perder o pé. É aqui que a atração simples vira dependência.",
    "cards": [
      {"ic":"bubble","t":"Espelhar e Isolar","emph":"Espelhe e Isole","b":"<strong>Espelhar</strong>: adote o humor, os valores e o compasso do outro até ele sentir o raro prazer de se ver refletido — a semelhança percebida derrete a resistência. <strong>Isolar</strong>: afaste-o, sem alarde, de amigos, hábitos e senso crítico. Sozinho no 'mundo de vocês dois', sem outros espelhos para se conferir, ele depende cada vez mais do seu.","tip":"<strong>Sinal de alerta:</strong> isolamento ostensivo e controlador desperta a defesa — e, na vida real, é a assinatura da manipulação e do abuso. Aprenda a reconhecê-lo de fora.","warn":True},
      {"ic":"eye","t":"A Carta de Amor","emph":"Insinuação","b":"Fale por <strong>insinuação</strong>, nunca por decreto — bilhetes, alusões, referências que só os dois decifram. Fuja do literal ('eu te amo, namore comigo'): a mensagem implícita recruta a imaginação do outro, que vira <strong>coautor do próprio romance</strong>. E ninguém se apega tanto a uma história quanto àquela que ajudou a escrever.","tip":"<strong>Como aplicar:</strong> esboce uma cena, um sentimento vago, uma lembrança compartilhada e deixe o sujeito subentendido. O alvo preenche o branco com a própria fantasia — sempre mais sedutora que a sua."},
      {"ic":"wave","t":"Prazer e Dor","emph":"Prazer e Dor","b":"Alterne ternura com retração, ciúme leve, um desafio inesperado. A <strong>recompensa intermitente</strong> amarra mais que o carinho constante — o mesmo gatilho que prende o apostador à máquina, agora aplicado ao coração. O prazer garantido entedia; o prazer incerto vicia. Deseje sempre, conceda devagar.","tip":"<strong>Modelo mental:</strong> a antecipação supera a entrega. A imaginação do outro, acesa pela espera, é invariavelmente mais poderosa do que qualquer coisa que você possa dar."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["Espelhe para dissolver a resistência; isole com sutileza para aprofundar a dependência.", "Comunique por insinuação — torne o outro coautor do romance e o apego dispara.", "Alterne prazer e dor: a recompensa incerta cria o laço mais difícil de romper."],
  },
  {
    "slug": "ch07-fase3-precipitar",
    "sub": "CAPÍTULO 7: Fase 3 — Precipitar",
    "intro": "O vínculo já existe — e justamente aí mora o perigo: a familiaridade esfria o que a tensão acendeu, e a hesitação pode travar a queda. O terceiro ato existe para reanimar a chama. Quebra a rotina com o inesperado, inflama o desejo pela ausência e, no instante exato, força a decisão com um gesto que não admite recuo.",
    "cards": [
      {"ic":"spark","t":"A Surpresa Reacende","emph":"Inesperado","b":"O desejo construído com tanto esmero tem um único inimigo: a previsibilidade. Por isso, <strong>surpreenda</strong>. A mente prende-se ao inesperado e desliza sobre o repetido; uma reviravolta súbita reacende a tensão que a rotina já estava apagando. Onde tudo se torna esperado, o feitiço silenciosamente expira.","tip":"<strong>Como aplicar:</strong> quando a relação começar a mornar, mude o canal sem aviso — um gesto fora do roteiro, um plano imprevisto, um presente que ninguém pediria."},
      {"ic":"gap","t":"A Ausência que Inflama","emph":"Estratégica","b":"Afaste-se <strong>no auge do interesse</strong>, não na baixa. A falta é combustível: no vácuo deixado, o outro idealiza você muito além do que a presença permitiria. A presença constante satura; a ausência calculada acende. A Coquete fez disso ofício — transformou a ausência em personagem permanente e nunca completável.","tip":"<strong>Modelo mental:</strong> ausência estratégica não é sumiço. A primeira preserva o mistério e puxa de volta; o segundo apenas afasta e esfria."},
      {"ic":"sword","t":"Audácia no Tempo Certo","emph":"Cronometrada","b":"Chega o instante da hesitação — e nele a timidez é fatal. Um gesto <strong>ousado e resoluto</strong>, que não pede licença nem treme, rompe a indecisão e leva a relação ao patamar seguinte. Sem as fases anteriores por baixo, essa mesma audácia é invasão grosseira; com elas, é o desfecho que o outro secretamente esperava.","tip":"<strong>Regra:</strong> a hesitação contagia — e a audácia também. Quem assume a iniciativa com firmeza faz o outro segui-lo quase sem perceber."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["Quebre a rotina com o inesperado — a previsibilidade é o único veneno do desejo já construído.", "Recue no auge do interesse: a falta faz o desejo crescer mais que qualquer presença.", "No ponto de hesitação, seja audacioso e resoluto — a timidez aqui mata tudo."],
  },
  {
    "slug": "ch08-fase4-o-tombo",
    "sub": "CAPÍTULO 8: Fase 4 — O Tombo / Aprofundar",
    "intro": "Chega o desenlace, e com ele a tentação de relaxar — o erro mais comum dos amadores. O quarto ato consuma e aprofunda a entrega: induz a vulnerabilidade, mantém viva a ilusão, isola um pouco mais e desfere o golpe final. Tudo isso sem tropeçar no anticlímax, esse veneno que, num só descuido, dissolve toda a magia que custou quatro atos para erguer.",
    "cards": [
      {"ic":"leaf","t":"Regressão e Ilusão","emph":"Regressão","b":"Conduza o outro a um estado de <strong>entrega quase infantil</strong> — cuidado, ternura, nostalgia — em que as defesas adultas se afrouxam e ele se abandona ao vínculo sem mais o crivo da razão. E sustente a fantasia: não deixe a rotina nem a literalidade do dia a dia assassinarem o encanto. O desejo respira de idealização; sem ela, asfixia.","tip":"<strong>Sinal de alerta:</strong> regressão somada a isolamento e dependência é exatamente o desenho de uma relação manipuladora ou abusiva. Saiba reconhecê-lo — esse reconhecimento é a defesa.","warn":True},
      {"ic":"spark","t":"O Golpe Final","emph":"Golpe Final","b":"No ápice da entrega, o gesto que <strong>consuma</strong> a sedução e fecha o arco — a iniciativa firme, nunca a pergunta tímida. Nem cedo demais, antes que o vínculo amadureça, nem tarde, quando o interesse já arrefece. O instante do golpe final é tão arte quanto tudo o que veio antes; errar o tempo é perder a peça inteira no último gesto.","tip":"<strong>Como aplicar:</strong> o golpe final é ação, jamais declaração. Um gesto concreto que diz, sem palavras, tudo o que os quatro atos vinham construindo."},
      {"ic":"gap","t":"O Veneno do Anticlímax","emph":"Anticlímax","b":"Eis o erro fatal de quem já venceu: baixar a guarda e desabar na previsibilidade. A <strong>rotina desfaz, calada, tudo</strong> o que os atos anteriores ergueram. Os sedutores que conservaram o poder jamais se deixaram tornar inteiramente decifráveis — guardavam sempre uma reserva de mistério para reacender o desejo. O fim exige tanto cálculo quanto o começo.","tip":"<strong>Regra:</strong> a conquista não encerra o trabalho. O anticlímax ressuscita o Anti-Sedutor exatamente no instante em que você se julga seguro."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Aprofunde com regressão, ilusão e isolamento — e consuma com o golpe final no tempo exato.", "Tema o anticlímax: a previsibilidade do dia seguinte desfaz, em silêncio, todo o feitiço.", "Em chave defensiva: regressão somada a isolamento e dependência são sinais de alerta de manipulação."],
  },
  {
    "slug": "ch09-lente-analitica",
    "sub": "CAPÍTULO 9: A Lente Analítica — Reconhecer para Escolher",
    "intro": "Aqui se revela o porquê de tudo. O verdadeiro valor desta obra não é um receituário de conquista, mas uma lente — um modo de enxergar as forças da atração e da influência onde quer que operem: no flerte e no anúncio, no palanque e no púlpito. Quem aprende a ver a mão que conduz deixa de ser conduzido.",
    "cards": [
      {"ic":"eye","t":"Dê Nome à Manobra","emph":"Dinâmica","b":"A <strong>ausência estratégica</strong> de um pretendente, a <strong>prova social</strong> de uma marca-Estrela, o <strong>carisma</strong> de um líder, a <strong>Coquete</strong> que adia para prender — quando você batiza a dinâmica em voz alta, ela perde o feitiço. Nomear <strong>devolve a você a escolha</strong>: cessa de ser arrastado e passa a decidir se entra no jogo ou sai.","tip":"<strong>Modelo mental:</strong> o olhar analítico vale mais que o prescritivo. Entender como a influência funciona é poder maior do que executar qualquer roteiro de conquista."},
      {"ic":"mask","t":"No Palanque e na Vitrine","emph":"Marketing, Política e Liderança","b":"Os 9 tipos não vivem só na alcova. A <strong>marca-Estrela</strong> é a tela em branco onde o consumidor projeta o que deseja ser; o <strong>líder Carismático</strong> vende sentido e pertencimento; o <strong>Natural</strong> da política desarma pela autenticidade que aparenta. A sedução é a gramática silenciosa de toda influência em escala — quem a lê, lê o mundo.","tip":"<strong>Como aplicar:</strong> diante de um líder, uma marca ou um movimento, pergunte: qual dos 9 tipos está sendo encarnado? E qual fome do público está sendo explorada?"},
      {"ic":"scale","t":"A Linha Ética","emph":"Ético","b":"Esta leitura serve para <strong>entender e se defender</strong>, jamais para enredar. A fronteira entre influência legítima e manipulação é nítida: a honestidade quanto à própria intenção e o respeito pela autonomia alheia. Reconhecer a dinâmica é o que torna a escolha possível — e escolha consciente é o oposto exato de ser seduzido às cegas.","tip":"<strong>Regra:</strong> 'que fome minha isto explora?'. Essa pergunta é o antídoto. Quem nomeia o jogo recupera o controle do tabuleiro."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["Dê nome à manobra: batizar a dinâmica em voz alta lhe devolve a escolha.", "Os 9 tipos operam no marketing, na política e na liderança — a sedução é a gramática da influência.", "A lente analítica existe para entender e se defender, nunca para manipular."],
  },
]
