# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'A Arte da Guerra' (Sun Tzu)."""

BOOK = {
  "title": "A Arte da Guerra",
  "author": "Sun Tzu",
  "header_light": "A ARTE",
  "header_bold": "DA GUERRA",
  "subtitle": "VISÃO GERAL · A VITÓRIA DECIDIDA ANTES DA BATALHA",
  "intro": "Dois mil e quinhentos anos depois, ainda é o tratado mais frio já escrito sobre vencer. Sun Tzu não ensina a lutar melhor — ensina a tornar a luta desnecessária. A guerra é assunto de vida e morte para o Estado: por isso se decide no cálculo, longe do barulho, e quem mais conta no templo já venceu antes de sacar a espada. O cume da arte não é triunfar em cem batalhas — é dobrar o inimigo sem combater. <em>Quem domina o engano e conhece os dois lados não precisa da sorte.</em>",
  "description": "Os 13 capítulos de 'A Arte da Guerra' de Sun Tzu em cheat sheet: os 5 fatores do cálculo, vencer sem lutar, conhecer o inimigo e a si mesmo, a guerra como arte do engano, a vitória rápida, cheio e vazio, o momentum (shih), a flexibilidade da água, os tipos de terreno, não agir por raiva e o uso de espiões — a estratégia clássica chinesa para negócios, negociação e toda decisão sob conflito.",
  "hook": "Você lutou quando devia ter feito o inimigo desistir sozinho.",
  "story_promise": "A MAIOR VITÓRIA É SEM BATALHA",
  "story_lessons": [
    "Vencer cem batalhas não é genialidade — evitá-las é.",
    "Toda virtude levada ao extremo vira a sua pior fraqueza.",
    "Sun Tzu nunca age por ira: raiva destrói mais rápido que o inimigo.",
  ],
  "tags": ["Estratégia", "Liderança", "Filosofia"],
  "progress": "13 Capítulos",
  "cover": "assets/arte-da-guerra-capa.png",
  "overview_cards": [
    {"ic":"target","t":"Vencer sem Lutar","b":"Ganhar cem batalhas em cem combates não é o cume da arte: o cume é <strong>dobrar o inimigo sem combater</strong>. Há uma escada, e ela desce do barato ao caro: o melhor é atacar a estratégia dele; depois, romper suas alianças; depois, bater no exército; e só na pior das hipóteses, sitiar muralhas. Sangue derramado é a confissão de que o estrategista falhou antes.","tip":"<strong>Modelo mental:</strong> tomar o inimigo inteiro vale mais que destruí-lo em pedaços — preserve o todo, e o todo será seu.","wide":True},
    {"ic":"scale","t":"O Cálculo Antes do Campo","b":"A batalha é vencida no templo, antes de o tambor soar. Meça a si e ao adversário nos cinco fatores — Tao, Céu, Terra, Comando, Método — e responda às sete estimativas com frieza. <strong>Quem soma mais vantagens no cálculo já venceu; quem soma menos já perdeu.</strong> Entrar na luta para descobrir quem é mais forte é apostar com os olhos vendados.","tip":"<strong>Regra:</strong> decida pela soma dos fatores, nunca pela vontade de lutar."},
    {"ic":"eye","t":"Conhece o Inimigo e a Ti","b":"<strong>Conhece o inimigo e a ti mesmo, e em cem batalhas não correrás perigo.</strong> Conhece só a ti, e a cada vitória corresponderá uma derrota. Não conheces nem a um nem a outro, e sucumbirás em todas. O autoconhecimento não é virtude de monge: é metade exata do cálculo, e a metade que a maioria se recusa a fazer.","tip":"<strong>Como aplicar:</strong> antes de competir, faça o diagnóstico honesto dos dois lados — sem ele, há sorte, não estratégia."},
    {"ic":"wave","t":"Seja Água","b":"A tropa em forma suprema imita a água: foge do alto, corre para o baixo, não guarda forma fixa e toma o feitio do terreno que encontra. Assim o hábil evita o cheio, ataca o vazio e <strong>molda a vitória ao adversário</strong>, sem fórmula que se repita. Quem vence transformando-se conforme o inimigo, esse os antigos chamavam de divino.","tip":"<strong>Modelo mental:</strong> nenhuma regra é absoluta — o mérito está em saber a hora de quebrá-la."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-calculos-iniciais",
    "sub": "CAPÍTULO 1: Cálculos Iniciais",
    "intro": "A guerra é o grande assunto do Estado: o solo da vida e da morte, a estrada da sobrevivência ou da ruína. Coisa assim não se decide com pressa nem com sangue, e sim com a conta feita a frio: quem multiplica as estimativas no templo antes do choque vence; quem as escasseia, perde; quem não faz nenhuma, nem vale falar dele.",
    "cards": [
      {"ic":"scale","t":"Os Cinco Fatores","emph":"Cinco","b":"Antes que um soldado se mova, pese a si e ao inimigo em cinco medidas. <strong>Tao</strong>: o povo a uma só vontade com o líder, pronto a morrer sem hesitar. <strong>Céu</strong>: a estação, o frio, a hora — o que ninguém governa. <strong>Terra</strong>: a distância, o desfiladeiro, a saída. <strong>Comando</strong>: a têmpera do general. <strong>Método</strong>: a ordem que sustenta tudo. Quem domina os cinco prevalece; quem os ignora cai.","tip":"<strong>Como aplicar:</strong> pontue você e o adversário fator a fator — a vitória no templo precede a vitória no campo."},
      {"ic":"mask","t":"A Guerra é Engano","emph":"Engano","b":"Toda guerra repousa sobre o engano. Capaz, mostra-te inábil; pronto a agir, finge-te quieto; perto, faz crer que estás longe; longe, faz crer que estás perto. Acena com a isca ao ávido, semeia a desordem e o golpeia, evita-o onde é forte. <strong>A cada capacidade real, oponha a aparência contrária.</strong> Isto é a alma da arte, e não se transmite de antemão.","tip":"<strong>Modelo mental:</strong> ocultar a própria força e a própria intenção é o estado normal do estrategista, não o truque ocasional."},
      {"ic":"bulb","t":"As Sete Estimativas","emph":"Sete","b":"O cálculo se faz de perguntas, e estas são as sete: de que lado o soberano possui o Tao? Qual general é mais capaz? A quem servem Céu e Terra? Onde a disciplina é mais firme, a tropa mais forte, o soldado mais treinado, a recompensa e o castigo mais claros? <strong>Quem responde a isto com honestidade conhece o vencedor antes do primeiro grito.</strong>","tip":"<strong>Sinal de alerta:</strong> a recusa a fazer essas perguntas é medo da resposta — e entrar na luta cego é apostar sem ter contado as cartas.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["Decida pela soma dos 5 fatores, não pela vontade de lutar.", "Compare-se ao adversário ponto a ponto através das 7 estimativas.", "Trate o engano como o estado normal da guerra: oculte capacidade e intenção."],
  },
  {
    "slug": "ch02-conduzindo-a-guerra",
    "sub": "CAPÍTULO 2: Conduzindo a Guerra",
    "intro": "Toda campanha queima o tesouro: cada manhã de guerra é ouro que não volta. Daí a primeira lei da execução — a presteza. Houve quem vencesse com pressa tosca; jamais houve quem lucrasse com guerra arrastada. Nenhum país enriqueceu deixando a campanha apodrecer no tempo.",
    "cards": [
      {"ic":"clock","t":"A Duração é Inimiga","emph":"Duração","b":"A guerra que se estende cega as armas, gasta o ardor e seca o cofre — e, quando o reino está exausto, os abutres vizinhos aparecem. <strong>Vale mais uma vitória grosseira e veloz que uma campanha refinada e sem fim.</strong> O tempo aqui não é cenário neutro: é o adversário que sangra você a cada amanhecer, em silêncio.","tip":"<strong>Sinal de alerta:</strong> se a vitória tarda, o custo a anula — olhe o relógio do caixa, não só o placar.","warn":True},
      {"ic":"wrench","t":"Alimente-se do Inimigo","emph":"do Inimigo","b":"Um saco de grão tomado ao inimigo equivale a vinte tirados do próprio celeiro. Comer do depósito alheio <strong>fere duas vezes no mesmo gesto</strong>: enche a sua mão e esvazia a dele. Premeie quem captura, vista seus carros com as cores que o vento decidir e converta a força do rival em combustível da sua.","tip":"<strong>Como aplicar:</strong> antes de queimar seu próprio caixa, pergunte que recurso do rival pode virar força sua."},
      {"ic":"spark","t":"Some o Custo Diário","emph":"Custo Diário","b":"Mil carros de combate, provisões carregadas por mil li, ouro escorrendo por mãos no front e na retaguarda: a queima diária de uma campanha é colossal. Conte-a antes de partir, e meça quanto fôlego o cofre aguenta. <strong>Se o seu fôlego dá para seis meses e a vitória pede dois anos, a vitória já é derrota.</strong>","tip":"<strong>Regra:</strong> mire a vitória rápida — a duração é inimiga, não aliada."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["Mire a vitória rápida; a duração é inimiga, não aliada.", "Some o custo diário antes de comprometer-se com uma campanha.", "Alimente sua força com recursos tomados ao adversário."],
  },
  {
    "slug": "ch03-estrategia-ofensiva",
    "sub": "CAPÍTULO 3: Estratégia Ofensiva",
    "intro": "Render o exército inimigo sem partir uma lança: eis a flor da arte. Tomar o reino inteiro vale mais que arrasá-lo; tomar o batalhão intacto vale mais que dizimá-lo. Vencer cem combates em cem batalhas não é a excelência suprema — a excelência é quebrar a resistência do outro sem que o sangue corra.",
    "cards": [
      {"ic":"steps","t":"A Hierarquia da Vitória","emph":"Hierarquia","b":"Há uma escada do vencer, e o sábio sobe ao degrau mais alto. No topo: <strong>desmontar a estratégia do inimigo</strong> antes que ela ganhe corpo. Abaixo: cortar suas alianças e deixá-lo só. Mais abaixo: enfrentar seu exército no campo. No fundo, o pior de todos: sitiar muralhas — meses de cerco, máquinas, mortos, e a cidade reduzida a entulho. Sitiar é a derrota disfarçada de vitória.","tip":"<strong>Como aplicar:</strong> antes de bater de frente, pergunte se dá para derrubar a premissa em que o plano do outro se apoia."},
      {"ic":"eye","t":"Conhece os Dois Lados","emph":"os Dois Lados","b":"<strong>Conhece o inimigo e a ti mesmo, e cem batalhas não te darão susto.</strong> Conhece só a ti, e a cada vitória virá uma derrota colada. Não conheças nem um nem outro, e cairás sempre. O autoconhecimento aqui não é exame de consciência: é a metade da conta — e justo a metade que o orgulho costuma falsear primeiro.","tip":"<strong>Modelo mental:</strong> o diagnóstico honesto dos dois lados é a fronteira entre a segurança e a ruína."},
      {"ic":"link","t":"Não Algeme o General","emph":"Não Algeme","b":"O soberano aleija o próprio exército de três modos: mandando avançar ou recuar quem não pode; governando a tropa como se governa a corte; e metendo a mão na tática sem entendê-la. Daí nasce a dúvida nas fileiras, e a dúvida convida o inimigo. <strong>Onde há general capaz e soberano que não o algema, ali mora a vitória.</strong>","tip":"<strong>Sinal de alerta:</strong> quando a chefia distante dita a manobra local, a derrota está sendo semeada de cima.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["Suba a hierarquia: ataque a estratégia, depois as alianças, só então o exército.", "Ajuste a tática à razão de forças — inclusive a opção de evitar o combate.", "Conhecer o inimigo e a si mesmo é a fronteira entre a segurança e a ruína."],
  },
  {
    "slug": "ch04-disposicoes",
    "sub": "CAPÍTULO 4: Disposições / Forma",
    "intro": "Os antigos hábeis na guerra primeiro se tornavam impossíveis de derrotar, e depois esperavam a brecha para derrotar o inimigo. Não ser vencido depende de ti; vencer depende dele. Por isso o sábio garante o que está em sua mão e não jura sobre o que está na mão do outro.",
    "cards": [
      {"ic":"shield","t":"Primeiro, Não Perder","emph":"Não Perder","b":"<strong>Estar a salvo da derrota está em tuas mãos; a ocasião de vencer está nas do inimigo.</strong> A defesa tu governas; o ataque pende do erro alheio. Daí a ordem que não se inverte: torna-te primeiro intocável, depois espreita a abertura. Quem corre atrás do ganho sem ter blindado o que não pode perder está apostando a casa para ganhar o troco.","tip":"<strong>Regra:</strong> garanta a própria invencibilidade antes de atacar — a defesa precede a ofensiva."},
      {"ic":"mountain","t":"Vencer o Já Vencido","emph":"o Já Vencido","b":"O mestre só dá o golpe quando o golpe já está ganho: ele vence batalhas vencidas de antemão. Por isso seu triunfo não traz fama de astúcia nem glória de bravura — não houve risco para aplaudir. <strong>A vitória é consequência, não aposta:</strong> arrumadas as condições, ela despenca como água represada que se solta do alto da montanha.","tip":"<strong>Modelo mental:</strong> a vitória discreta e certa vale mais que a brilhante e arriscada."},
      {"ic":"steps","t":"Os Cinco Passos da Medida","emph":"Medida","b":"A vitória não cai do céu — sobe por uma cadeia de medidas, cada elo puxando o próximo: Medir o terreno → Estimar as quantidades → Calcular → Comparar → Vencer. <strong>Quem mede, estima, calcula e compara vence; quem confia na coragem crua perde.</strong> É a diferença entre lançar um grão de peso no prato leve e despejar uma tonelada sobre uma pluma.","tip":"<strong>Como aplicar:</strong> antes de agir, rode a cadeia — meça, estime, calcule, compare; a vitória é o último elo."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["Construa primeiro a invencibilidade (defesa), que está sob seu controle.", "Ataque só quando a vitória já está praticamente assegurada.", "A vitória nasce de medir, estimar, calcular e comparar — não de coragem cega."],
  },
  {
    "slug": "ch05-energia",
    "sub": "CAPÍTULO 5: Energia / Força",
    "intro": "Comandar muitos é como comandar poucos: tudo está em dividir os números. Fazer a multidão receber o inimigo sem se desfazer é questão de sinais e formação. E o que decide o choque não é a fúria de cada homem, mas a energia represada que se solta na hora exata.",
    "cards": [
      {"ic":"pivot","t":"O Momentum (Shih)","emph":"Momentum","b":"A vitória não brota do esforço de cada soldado, mas do impulso do conjunto — o <em>shih</em>. É a pedra redonda largada do alto de mil pés de montanha; é a torrente que rola pedregulhos. O guerreiro hábil <strong>busca a vitória no momento, não nos homens</strong>: arruma a posição até que vencer seja apenas deixar a pedra rolar. Pedir bravura a cada um é não ter entendido a inclinação do terreno.","tip":"<strong>Modelo mental:</strong> posição e momentum valem mais que o esforço individual — desenhe a vantagem em vez de forçá-la."},
      {"ic":"fork","t":"Ordinário e Extraordinário","emph":"Extraordinário","b":"Prende-se o inimigo com o direto, o <em>zheng</em>; abate-se com o indireto, o <em>qi</em>. Os dois andam de mãos dadas: o ordinário fixa o olhar do adversário enquanto o extraordinário entra pela porta que ninguém vigiava. <strong>As combinações de direto e indireto não têm fim</strong> — são cinco notas que geram mais melodias do que o ouvido consegue contar, cinco cores que pintam o mundo inteiro.","tip":"<strong>Como aplicar:</strong> fixe com o ordinário, vença com o extraordinário — nunca use só o ataque previsível."},
      {"ic":"spark","t":"O Golpe do Falcão","emph":"Falcão","b":"O ímpeto do hábil é a torrente que arrasta a rocha; sua decisão é o falcão que, no tempo exato, parte a espinha da presa num só bote. Não basta acumular energia — é preciso soltá-la no instante em que o alvo está descoberto. <strong>Concentre a força num ponto e libere-a no momento preciso</strong>, e o impacto será maior que a soma de tudo o que entrou nele.","tip":"<strong>Regra:</strong> energia dispersa não derruba nada — concentre num ponto e solte no tempo certo."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["A vitória vem do momentum (shih) bem posicionado, não da força isolada.", "Combine sempre o ordinário (zheng) e o extraordinário (qi).", "Concentre a energia num ponto e libere-a no instante exato."],
  },
  {
    "slug": "ch06-cheio-e-vazio",
    "sub": "CAPÍTULO 6: Pontos Fortes e Fracos",
    "intro": "Quem ocupa o campo primeiro e espera o inimigo chega fresco à luta; quem chega depois e corre para o choque chega exausto. Por isso o hábil traz o inimigo a si e não se deixa trazer por ele. Toda a arte deste capítulo cabe numa palavra: imponha a sua vontade, jamais sofra a dele.",
    "cards": [
      {"ic":"target","t":"Ataque o Vazio","emph":"o Vazio","b":"Evita o cheio — o que está forte e de guarda alta; despeja-te sobre o vazio — o que está frouxo e desatento. <strong>Avance por onde ele não pode resistir; recue por onde ele não pode alcançar.</strong> Bater de frente no ponto mais duro do inimigo é o erro mais caro da guerra. Entre pela fenda que ele esqueceu, e será você, não ele, quem escolhe onde a batalha acontece.","tip":"<strong>Regra:</strong> nunca bata no cheio; sempre ataque o vazio."},
      {"ic":"pivot","t":"Tome a Iniciativa","emph":"Iniciativa","b":"O hábil faz o inimigo vir até ele com o aceno de uma vantagem, ou o prende no lugar com a sombra de um dano. Quem dita o tempo dita a batalha. <strong>Faça o inimigo dançar conforme a sua música</strong> — nunca o contrário. No instante em que você se flagra correndo atrás do ritmo do outro, a iniciativa já mudou de mãos, e o resto da guerra será tentar retomá-la.","tip":"<strong>Sinal de alerta:</strong> reagir sempre ao tempo do outro é o sintoma de quem perdeu o comando do jogo.","warn":True},
      {"ic":"wave","t":"Seja Água, Sem Forma","emph":"Sem Forma","b":"Sê tão sutil que não tenhas forma, tão calado que não tenhas som — e o inimigo, sem saber onde cairás, terá de guardar tudo ao mesmo tempo. <strong>Quem se defende em toda parte é fraco em toda parte.</strong> Como a água sem feitio fixo, molda-te ao adversário: junta-te num só punho contra os pedaços que ele espalhou. Assim, dez se tornam um diante de ti.","tip":"<strong>Como aplicar:</strong> force o inimigo a se espalhar e concentre sua força no ponto único — seja um contra dez."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["Ataque sempre o vazio; evite o cheio.", "Tome a iniciativa — faça o inimigo dançar conforme a sua música.", "Seja sem forma e adaptável como a água, juntando sua força enquanto ele dispersa a dele."],
  },
  {
    "slug": "ch07-manobra",
    "sub": "CAPÍTULO 7: Manobra",
    "intro": "Nada na guerra é mais difícil que a manobra: a arte de fazer do caminho torto o atalho e da desvantagem um ganho. Quem parte depois e chega antes entendeu o segredo — calcular o desvio como se fosse a reta. Aí está, ao mesmo tempo, o que pode dar a vitória e o que pode custar tudo.",
    "cards": [
      {"ic":"fork","t":"O Desvio que Chega Antes","emph":"Desvio","b":"A manobra mestra é sair atrás e chegar na frente: você ilude o inimigo com a rota indireta, demora de propósito e ainda assim o ultrapassa. <strong>O caminho mais longo é o mais rápido quando é o menos disputado.</strong> Tomar o trajeto tortuoso por mais vantajoso — porque o reto está lotado e previsível — é dominar a distância que os olhos não medem.","tip":"<strong>Como aplicar:</strong> quando a rota óbvia está congestionada, procure a indireta que ninguém disputa."},
      {"ic":"wave","t":"Ataque o Moral","emph":"o Moral","b":"O ânimo de um exército tem suas horas: ao amanhecer arde, ao meio-dia afrouxa, ao anoitecer só pensa em voltar para casa. O comandante hábil poupa o próprio ardor e cai sobre o inimigo quando o dele já esfriou. <strong>Golpeie o espírito, não só os corpos:</strong> em ordem, espere a desordem dele; descansado, espere o exausto; saciado, espere o faminto.","tip":"<strong>Modelo mental:</strong> o ânimo é alvo legítimo — bata quando o do outro está em baixa e o seu, no alto."},
      {"ic":"arrow","t":"Deixe a Saída Aberta","emph":"Saída","b":"Não persiga quem finge fugir, não morda a tropa-isca de elite e, acima de tudo, deixe uma brecha ao inimigo cercado. <strong>Um adversário sem saída luta até a morte</strong> — e essa é a batalha mais cara e mais sangrenta de todas, travada sem necessidade. Encurralar o desesperado é comprar a resistência máxima; abrir-lhe uma fuga honrosa é comprar barato o fim da guerra.","tip":"<strong>Regra:</strong> nunca encurrale o desesperado — a rota de fuga é o que evita o combate mais sangrento.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["Faça do desvio o atalho: a rota indireta para chegar à frente.", "Ataque o inimigo quando o moral dele está em baixa.", "Deixe sempre uma rota de fuga ao adversário cercado."],
  },
  {
    "slug": "ch08-as-nove-variaveis",
    "sub": "CAPÍTULO 8: As Nove Variáveis",
    "intro": "Há estradas que não se tomam, exércitos que não se atacam, cidades que não se sitiam, terrenos que não se disputam — e há ordens do soberano que não se obedecem. Nenhuma regra é absoluta. A glória do general não está em conhecer a doutrina, e sim em saber a hora de contrariá-la.",
    "cards": [
      {"ic":"wave","t":"Toda Regra Tem Exceção","emph":"Exceção","b":"Quem entende o proveito de variar as táticas sabe comandar; quem conhece o terreno mas não sabe variar não extrai dele uma só vantagem. Saber o princípio é metade — a outra metade é dobrá-lo à realidade do campo. <strong>O mérito do general está justamente em saber quando não seguir a própria doutrina</strong>, e não em aplicá-la de olhos fechados como quem recita.","tip":"<strong>Como aplicar:</strong> quando a regra padrão colidir com a realidade, a realidade vence — varie."},
      {"ic":"scale","t":"Pese Ganho e Dano Juntos","emph":"Ganho e Dano","b":"O sábio mistura em cada plano a conta do ganho e a conta do dano. Vendo a vantagem escondida no perigo, age com firmeza; vendo o perigo escondido na vantagem, escapa da ruína. <strong>Nunca pese um sem o outro:</strong> toda chance traz um risco no forro e todo risco esconde uma chance no avesso, e o cálculo só é honesto quando vira os dois.","tip":"<strong>Regra:</strong> no mesmo cálculo, sempre o ganho E o dano — um sem o outro é meia verdade."},
      {"ic":"key","t":"Os Cinco Perigos do General","emph":"Cinco Perigos","b":"Cinco vícios perdem o general, e o inimigo os usa como alavancas. A temeridade leva à morte; a covardia, à captura; o gênio explosivo se deixa provocar; o brio ferido se deixa insultar; o excesso de compaixão se afoga em aflição. <strong>Conheça e guarde seus pontos fracos — são as portas pelas quais o adversário entra sem arrombar.</strong>","tip":"<strong>Sinal de alerta:</strong> quando um insulto te faz reagir na hora, o inimigo achou a alça para te mover — não morda a isca.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Domine a adaptação: nenhuma tática é regra fixa.", "Pese sempre vantagem e desvantagem no mesmo cálculo.", "Conheça e proteja seus 5 perigos — são portas para o inimigo.", "Não conte com o erro alheio; conte com o seu próprio preparo."],
  },
  {
    "slug": "ch09-o-exercito-em-marcha",
    "sub": "CAPÍTULO 9: O Exército em Marcha",
    "intro": "O general é antes de tudo um leitor de sinais. Move o exército conforme o terreno e lê na natureza e no inimigo o que eles não dizem. Cada folha que treme, cada pássaro que voa, cada palavra macia ou dura traz escrita uma intenção — a quem souber ler.",
    "cards": [
      {"ic":"eye","t":"Leia os Sinais","emph":"Sinais","b":"O gesto trai o que a língua esconde. Árvores que balançam: o inimigo avança. Pássaros que disparam ao alto: emboscada à espreita. Palavras humildes enquanto ele reforça as fileiras: prepara o bote. Fala arrogante e avanço fingido: vai recuar. <strong>Repare no que o outro faz, não no que ele diz</strong> — o ato confessa o que a retórica veste.","tip":"<strong>Como aplicar:</strong> diante de qualquer discurso, procure o sinal concreto que o confirma ou o desmente."},
      {"ic":"link","t":"Laço e Lei, Nessa Ordem","emph":"Nessa Ordem","b":"Trate o soldado com humanidade para ganhar-lhe o coração; mantenha a disciplina firme para ganhar-lhe o respeito. E a ordem é sagrada: <strong>punir antes de conquistar a lealdade gera revolta; afagar sem disciplina cria um exército mimado e inútil.</strong> Primeiro o afeto, depois a regra. Comandados como filhos amados, eles te seguem até o vale mais fundo.","tip":"<strong>Modelo mental:</strong> primeiro o coração, depois a regra — afeto sem disciplina, ou disciplina sem afeto, falham igual."},
      {"ic":"mountain","t":"O Alto e o Seco","emph":"Alto e o Seco","b":"Conquiste a vantagem antes do contato. Na montanha, fique no alto; ao cruzar o rio, afaste-se das margens; no pântano, atravesse depressa e não acampe. A regra que costura tudo é uma só: <strong>prefira sempre o terreno alto e seco ao baixo e úmido</strong>. Quem toma a posição superior antes do choque já chega ao combate com meio caminho vencido.","tip":"<strong>Regra:</strong> garanta a posição alta e seca antes de mover — vantagem se conquista antes do choque, não no meio dele."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["Posicione-se em terreno alto e seco; adapte a marcha ao terreno.", "Leia os sinais — eles revelam a intenção que a fala oculta.", "Comande com afeto E disciplina, conquistando o coração antes de impor a regra."],
  },
  {
    "slug": "ch10-o-terreno",
    "sub": "CAPÍTULO 10: O Terreno",
    "intro": "O terreno é o auxiliar do exército: avaliá-lo, medir suas distâncias e perigos, é meio caminho da vitória. Quem briga conhecendo o terreno vence; quem o ignora perde. E quando a derrota vem, raramente é o céu que a manda — é o general que a fabricou.",
    "cards": [
      {"ic":"layers","t":"Classifique o Terreno","emph":"Classifique","b":"São seis os terrenos, cada um com sua lei. No acessível, ocupe o alto e o sol antes do outro. No enredante — onde se entra fácil e se sai caro — só avance se o inimigo estiver desprevenido. No estreito e no escarpado já ocupados por ele, não ataque: dê meia-volta. <strong>Aplicar a mesma tática a todo terreno é o erro de raiz</strong> — a regra muda com o chão sob os pés.","tip":"<strong>Como aplicar:</strong> antes de mover, nomeie o tipo de terreno em que está; a tática certa nasce daí."},
      {"ic":"triangle","t":"A Derrota Tem Dono","emph":"Tem Dono","b":"As seis calamidades — a fuga, a insubordinação, o colapso, a ruína, a desordem, a debandada — não vêm do céu: vêm do general. Lançar um contra dez; oficiais frouxos sobre soldados bravos; comando sem autoridade. <strong>A derrota é diagnóstico de comando, não azar.</strong> Culpar o céu, o mercado ou a sorte é só a recusa elegante de encarar a própria falha.","tip":"<strong>Sinal de alerta:</strong> quando você credita uma perda a fatores externos, desconfie — a calamidade quase sempre teve assinatura de comando.","warn":True},
      {"ic":"shield","t":"Proteja o Todo, Não o Ego","emph":"o Todo","b":"O general digno avança sem cobiçar fama e recua sem temer desonra, com um só pensamento: proteger o povo e servir ao soberano. Esse é a joia do reino. Trate os soldados como filhos amados — mas sem o mimo que os torna inúteis na hora do perigo. <strong>Decidir pelo bem comum, nunca pela vaidade</strong>, é o que separa o líder maduro do que caça aplausos.","tip":"<strong>Regra:</strong> decida sempre pelo bem do todo — a glória pessoal é péssima bússola estratégica."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 10",
    "lessons": ["Classifique o terreno em seus 6 tipos e siga a regra própria de cada um.", "A maioria das derrotas é culpa do general — reconheça as 6 calamidades.", "Lidere para proteger o todo, não para colher glória."],
  },
  {
    "slug": "ch11-as-nove-situacoes",
    "sub": "CAPÍTULO 11: As Nove Situações",
    "intro": "Cada situação pede a sua tática, do terreno leve ao desesperado. E há aqui um paradoxo que o estrategista raso não suspeita: quanto mais fundo no perigo, mais firme e unido fica o exército. Lance a tropa onde não há salvação, e ela sobreviverá; jogue-a no chão da morte, e ela viverá.",
    "cards": [
      {"ic":"spark","t":"O Terreno Mortal","emph":"Mortal","b":"Sem rota de fuga, o soldado perde o medo e luta com a força que só o desespero acende: <strong>coloque-o onde não há saída e ele preferirá a morte à rendição</strong>. Às vezes é tirar o plano B que faz a tropa vencer — a necessidade vira combustível de coragem. É o avesso exato da brecha que se deixa ao inimigo cercado: a saída que você nega a si mesmo, negue ao outro jamais.","tip":"<strong>Como aplicar:</strong> quando o momento exige tudo, queimar o “plano B” pode transformar a acomodação em coragem total.","warn":True},
      {"ic":"spiral","t":"A Serpente Shuai-jan","emph":"Serpente","b":"Há nas montanhas uma serpente: bata-lhe a cabeça e a cauda ataca; bata-lhe a cauda e a cabeça morde; bata-lhe o meio e cabeça e cauda vêm juntas. Assim deve ser o exército — partes que se socorrem sozinhas, sem ordem que venha de cima. <strong>Una os muitos para que ajam como um só corpo:</strong> isso se forja na organização e na situação, não na bravura natural de cada um.","tip":"<strong>Modelo mental:</strong> projete os times para se socorrerem sozinhos, como a serpente que reage inteira a qualquer golpe."},
      {"ic":"arrow","t":"Rapidez é a Essência","emph":"Rapidez","b":"A velocidade é a alma da guerra: monte sobre o despreparo do inimigo, vá por onde ele não te espera, caia sobre o ponto que ele esqueceu de guardar antes que se reorganize. <strong>Conduza a multidão como quem leva um só homem pela mão</strong> — unidade e rapidez, juntas, decidem a campanha. Cada uma das nove situações tem seu modo de agir; tratá-las por igual é o erro.","tip":"<strong>Regra:</strong> identifique em qual das 9 situações você está e aja antes que o inimigo se prepare."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 11",
    "lessons": ["Identifique em qual das 9 situações está e use a tática própria de cada uma.", "Em terreno mortal, a falta de saída multiplica a coragem.", "Rapidez e unidade total — como a serpente Shuai-jan — ganham a campanha."],
  },
  {
    "slug": "ch12-ataque-pelo-fogo",
    "sub": "CAPÍTULO 12: Ataque pelo Fogo",
    "intro": "O fogo amplia a força como nenhuma outra arma — e por isso mesmo queima as duas mãos. Pede estação seca, vento a favor, material a postos e nervos frios. Mas a maior lição deste capítulo ultrapassa o fogo: nunca pegue em armas por raiva, pois o que o fogo consome não renasce.",
    "cards": [
      {"ic":"spark","t":"A Arma de Dois Gumes","emph":"Dois Gumes","b":"O fogo multiplica o efeito de um ataque, mas só nos meios e na hora certos: há estações próprias, dias secos, e jamais se ateia fogo com o vento soprando contra a própria face. <strong>Toda arma extrema cobra preparo e disciplina — e se vira contra quem a empunha sem cuidado.</strong> Some-a ao plano: se o caos pegar lá dentro, ataque por fora; se não pegar, espere. Nunca a solte para ver no que dá.","tip":"<strong>Como aplicar:</strong> reserve as medidas extremas para quando as condições, e não a sua vontade, as justificam."},
      {"ic":"layers","t":"Os Cinco Alvos","emph":"Cinco Alvos","b":"Cinco são os alvos do fogo: os homens no acampamento, os depósitos de provisão, os comboios de bagagem, os arsenais e as linhas que abastecem o front. Não é incêndio ao acaso — <strong>é força amplificada cravada no ponto exato e no instante exato</strong>. Sem inteligência para escolher o alvo, sem material a postos e sem a hora certa, o fogo falha ou volta para casa.","tip":"<strong>Regra:</strong> a medida destrutiva só vale no ponto e no instante certos — fora deles, é desperdício ou autodano."},
      {"ic":"mask","t":"Nunca Aja por Raiva","emph":"por Raiva","b":"O soberano não mova o exército por cólera, nem o general dê batalha por despeito. A ira de hoje vira alegria amanhã, o rancor cede ao contentamento — mas <strong>um reino destruído não se reergue, e os mortos não voltam à vida</strong>. A raiva é a pior das estrategistas, porque suas decisões não têm volta. Avance onde há ganho real; pare onde não há. O lucro decide, nunca o ego.","tip":"<strong>Sinal de alerta:</strong> se a vontade de agir nasce do despeito e não do ganho, espere — a ira passa, o estrago fica.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 12",
    "lessons": ["Armas extremas exigem condições, timing e disciplina.", "Coordene a medida destrutiva com o plano — nunca a solte sem controle.", "Jamais aja por raiva: o destruído não se recupera; decida pelo ganho real."],
  },
  {
    "slug": "ch13-uso-de-espioes",
    "sub": "CAPÍTULO 13: O Uso de Espiões",
    "intro": "O que permite ao sábio bater antes e vencer sempre é o conhecimento prévio — e este não se arranca dos deuses, dos espíritos, das estrelas nem da analogia. Só se obtém de homens que conhecem o estado do inimigo. Manter um exército por anos e poupar moedas com a espionagem que o salva é o cúmulo da insensatez.",
    "cards": [
      {"ic":"key","t":"O Conhecimento Prévio","emph":"Conhecimento Prévio","b":"A vantagem que tudo decide — saber antes do outro — não vem da intuição, da sorte nem do oráculo: vem de informação humana, verificada. <strong>Sangrar o tesouro na guerra e economizar na inteligência que a vence é a loucura levada ao ápice.</strong> A informação é, ao mesmo tempo, o gasto mais barato e o mais determinante de toda a campanha — quem a despreza compra a derrota com desconto.","tip":"<strong>Como aplicar:</strong> antes de adivinhar a posição do outro lado, invista em saber — informação custa pouco e decide tudo."},
      {"ic":"masks","t":"As Cinco Classes","emph":"Cinco Classes","b":"Cinco são os espiões. O <strong>local</strong>: gente da terra inimiga. O <strong>interno</strong>: oficiais do outro lado, virados. O <strong>convertido</strong>: o espião dele que passa a servir você — o agente duplo. O <strong>descartável</strong>: aquele a quem se entrega mentira para vazar. O <strong>sobrevivente</strong>: o que vai ao campo e volta com o relato. Operados juntos, sem que ninguém enxergue a teia inteira, são o tesouro mais secreto do soberano.","tip":"<strong>Modelo mental:</strong> nenhuma fonte isolada basta — a vantagem mora na rede que cruza várias fontes."},
      {"ic":"person","t":"O Agente Duplo é o Eixo","emph":"o Eixo","b":"O espião do inimigo capturado e seduzido para o seu lado é o mais precioso de todos: é por ele que se recrutam o local e o interno, e por ele que a mentira chega ao descartável. Por isso, trate-o com a maior das generosidades. <strong>E nada pede mais sigilo: vazado o segredo antes da hora, morrem o espião e todos os ouvidos que escutaram.</strong>","tip":"<strong>Sinal de alerta:</strong> quebra de sigilo é fatal — a operação de inteligência vive ou morre pela discrição absoluta.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 13",
    "lessons": ["A vantagem decisiva vem de informação humana — invista nela sem economia.", "Domine as 5 classes de espiões e opere-as como uma rede integrada.", "O agente duplo é o eixo — e o sigilo absoluto é inegociável."],
  },
]
