# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Assim Falou Zaratustra' (Friedrich Nietzsche)."""

BOOK = {
  "title": "Assim Falou Zaratustra",
  "author": "Friedrich Nietzsche",
  "header_light": "ASSIM FALOU",
  "header_bold": "ZARATUSTRA",
  "subtitle": "VISÃO GERAL · DEUS MORREU — E O CÉU FICOU VAZIO PARA QUE NELE PENDURES UM SOL TEU",
  "intro": "Dez anos no alto da montanha, a sós com a águia e a serpente — e Zaratustra desce de novo aos homens, farto da própria luz como abelha farta de mel. Traz uma só nova, a mais terrível e a mais festiva: <em>Deus morreu</em> — e fomos nós, vós e eu, os seus assassinos. Não é grito de ateu satisfeito; é o sino que toca para um morto que ainda não enterramos. O prego que sustentava todos os valores soltou-se do céu, e quem não pendurar ali um sol próprio há de congelar no azul vazio. Por isso este não é livro que prova: é livro que <strong>canta</strong> — em parábolas, salmos virados do avesso e bichos que falam. E te atira à cara o peso mais pesado já sonhado: viver de tal sorte que queiras viver tudo isto outra vez, e inúmeras vezes, igual, eternamente.",
  "description": "Análise de 'Assim Falou Zaratustra' de Nietzsche (1883–1885), o poema-profecia que derruba os ídolos a marteladas e gargalhadas. A morte de Deus como céu vago a ser pintado, não como bandeira a se hastear; o além-do-homem como o sentido da Terra; as três metamorfoses do espírito (camelo→leão→criança); a vontade de potência como a fome de toda vida que vive; o eterno retorno como a pedra que esmaga ou liberta; o amor fati; o último homem que 'inventou a felicidade' e pisca; o ressentimento que veste a própria impotência de virtude; e a transvaloração de todos os valores. Não se lê como tratado: lê-se de pé, como quem aprende a dançar sobre um abismo e a rir antes de cair.",
  "tags": ["Filosofia", "Nietzsche", "Existencialismo"],
  "progress": "9 Capítulos",
  "cover": "assets/assim-falou-zaratustra-cover.png",
  "overview_cards": [
    {"ic":"steps","t":"As Três Metamorfoses","b":"O espírito que se eleva muda três vezes de pele. Primeiro o <strong>camelo</strong>, que se ajoelha e pede mais carga: ajoelha-te, leva o 'Tu Deves', todo o peso dos milênios. Depois, no deserto mais solitário, faz-se <strong>leão</strong>, que ruge 'Eu Quero' e rasga o dragão das mil escamas douradas — cada escama um mandamento antigo: ganha a liberdade, mas só sabe destruir. Enfim a <strong>criança</strong> — inocência e esquecimento, uma roda que gira por si, um sagrado dizer-sim — e só ela cria mundos novos. Dizer não, o leão sabe; só a criança sabe dizer sim.","tip":"<strong>Diagnóstico:</strong> de que animal é a tua pele hoje — ainda dobras os joelhos sob o dever alheio, já rugiste o teu primeiro não, ou já giras uma roda que é só tua?","wide":True},
    {"ic":"mountain","t":"O Além-do-Homem","b":"O homem é uma corda atada entre o animal e o além-do-homem — uma corda sobre um abismo. O <strong>Übermensch</strong> não é raça, gênio nem tirano: ler assim é profanar o texto. É quem forja os próprios valores, jura fidelidade à Terra e ao corpo, e diz <strong>sim</strong> à vida inteira, sem descontar nada. Não é um santo a imitar — é um horizonte que só se conquista caminhando para ele.","tip":"<strong>Modelo mental:</strong> lê 'homem' como verbo, não como substantivo — algo a ser superado, nunca uma essência pronta a se defender com unhas."},
    {"ic":"spiral","t":"O Eterno Retorno","b":"E se um demônio se esgueirasse até ti na tua hora mais solitária e sussurrasse: esta vida, com cada dor, cada tédio e cada êxtase, voltará outra vez, e inúmeras, idêntica — até a aranha e o luar entre as árvores? Lançar-te-ias ao chão rangendo os dentes e o amaldiçoando — ou cairias de joelhos, chamando-o de deus? Não é astronomia, é <strong>o peso mais pesado</strong>: a balança secreta que mede quanto, de fato, amas a tua vida.","tip":"<strong>Como aplicar:</strong> usa-o como crivo do dia — 'eu quereria este exato instante de volta, sem mudar uma vírgula, para sempre?'. Se não, muda a vida — ou muda os olhos com que a vês."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-prologo-morte-de-deus",
    "sub": "CAPÍTULO 1: Prólogo — A Descida e a Morte de Deus",
    "intro": "Zaratustra desce da montanha como um sol que precisa de quem o veja brilhar, transbordando de sabedoria que lhe pesa. No mercado, vem ensinar o além-do-homem — e a multidão ri, à espera do equilibrista. Mas quando lhes pinta o último homem como o pior dos espantalhos, eles gritam de volta: 'Dá-nos esse último homem!'. Pediram justamente o veneno que ele veio nomear.",
    "cards": [
      {"ic":"triangle","t":"A Morte De Deus","emph":"Morte","b":"O anúncio não é cocar de ateu vitorioso — é o <strong>diagnóstico de uma febre que ninguém sente</strong>: os valores mais altos, que penduravam o mundo num gancho seguro, perderam o peso. O prego soltou-se do céu e o niilismo é o frio que entra pela fenda. Sem fiador lá em cima, resta uma só tarefa: forjar sentido novo com as próprias mãos, e na Terra.","tip":"<strong>Modelo mental:</strong> não tomes o vazio por festa de libertação. Toma-o pelo canteiro de obras mais perigoso da tua vida — onde se constrói um deus ou se cava uma cova."},
      {"ic":"steps","t":"Corda Sobre O Abismo","emph":"Corda","b":"Não és o ponto de chegada de coisa alguma; és uma corda atada entre o animal e o além-do-homem, estendida sobre o abismo. O que há de grande no homem é ser <strong>ponte, e não meta</strong> — uma travessia perigosa, um tremor a meio caminho. Amar-se é amar quem se atira para a outra margem, não quem se agarra a esta.","tip":"<strong>Pergunta-chave:</strong> o que te prende ainda à margem do bicho, e o que, do outro lado, te chama com força bastante para te fazer atravessar?"},
      {"ic":"mask","t":"O Último Homem","emph":"Último Homem","b":"O avesso do além-do-homem é a criatura mais desprezível, a que tudo torna pequeno: aboliu o risco, o grande desejo, a estrela dançante — e <strong>'inventou a felicidade', e pisca</strong>. Quer só calor, vizinhos e prazerzinhos prudentes. Zaratustra o descreve para horrorizar; a multidão aplaude e o reclama. O espelho deles era esse, e o acharam bonito.","tip":"<strong>Sinal de alerta:</strong> onde só se quer evitar a dor e garantir o conforto até sexta-feira, o último homem já não precisa vencer — já reina.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["A obra parte de um diagnóstico (o vazio de sentido), não de uma doutrina pronta a ser engolida.", "O homem vale como ponte sobre o abismo, jamais como ponto de chegada.", "O conforto absoluto — o último homem — é a ameaça mais provável, porque é também a mais desejada."],
  },
  {
    "slug": "ch02-alem-do-homem",
    "sub": "CAPÍTULO 2: O Além-do-Homem — o Sentido da Terra",
    "intro": "O além-do-homem não é raça nem gênio — é quem cria os próprios valores, jura lealdade à Terra e diz sim à vida. Não é figura a imitar: é horizonte a inventar com os pés no chão. Eis o brado que abre tudo: 'o além-do-homem é o sentido da Terra — que a vossa vontade diga: que ele seja o sentido da Terra!'.",
    "cards": [
      {"ic":"mountain","t":"O Sentido Imanente","emph":"Imanente","b":"Caídos os ideais do alto, o sentido não desce mais das nuvens — tem de ser forjado <strong>aqui, leal ao corpo e ao instante</strong>. O além-do-homem é o sentido da Terra. Suplico-te: fica fiel à Terra, e não creias nos que te falam de esperanças supraterrenas! São envenenadores, saibam-no eles ou não.","tip":"<strong>Prática:</strong> pesa cada valor teu numa só balança: isto me aproxima da vida que pulsa, ou é uma fuga de costas para ela, rumo a um paraíso prometido?"},
      {"ic":"spark","t":"Material De Obra","emph":"Material","b":"O homem não é estátua pronta no museu — é o <strong>bloco de pedra à espera do escultor</strong>, e dentro dele dorme uma imagem das imagens. Zaratustra não quer discípulos de joelhos; quer criadores impiedosos consigo mesmos. O além-do-homem não é um senhor específico: é o relâmpago que tu mesmo invocas ao golpear a tua própria pedra.","tip":"<strong>Regra:</strong> larga os modelos perfeitos para copiar. O teu valor não está em quem admiras — está na mão que cria os teus próprios valores."},
      {"ic":"leaf","t":"Fidelidade À Terra","emph":"Fidelidade","b":"Despreza os pregadores do cansaço, que cospem no corpo em nome de uma alma purificada — falam de outro mundo porque deste já desistiram. Amar a carne, o instinto e o peso bruto do instante é o <strong>primeiro passo da grande saúde</strong>. Não é licença para o vício: é afirmar a vida real como o único palco onde se cria.","tip":"<strong>Sinal de alerta:</strong> doutrina que exige ódio ao corpo e à matéria quase sempre é fraqueza vital fantasiada de pureza. Quem maldiz a Terra é, no fundo, quem nela fracassou.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["O além-do-homem é o sentido imanente que se cria depois que o céu esvazia.", "Ser humano é ser superável — pedra a esculpir, não estátua acabada.", "A fidelidade à Terra e ao corpo é o critério único: nada de além-mundos para fugir deste."],
  },
  {
    "slug": "ch03-tres-metamorfoses",
    "sub": "CAPÍTULO 3: As Três Metamorfoses do Espírito",
    "intro": "Camelo → Leão → Criança: eis o mapa de toda libertação que vale a pena. Três tempos do espírito — ajoelhar e carregar, erguer-se e recusar, esquecer e criar. O leão que destrói ainda não é o criador; e o cume da maturidade tem cara de infância. Te direi as três metamorfoses do espírito: como ele se faz camelo, o camelo leão, e o leão, por fim, criança.",
    "cards": [
      {"ic":"steps","t":"O Camelo Que Carrega","emph":"Camelo","b":"O espírito robusto ajoelha-se como o camelo que quer ser bem carregado, e pede: carrega-me bem! Toma sobre si o 'Tu Deves' — a tradição, a moral, o sacrifício — e parte para o seu deserto. Esse passo é <strong>indispensável</strong>: sem o peso, o espírito não cria músculo nem reverência. Mas é só obediência; estacar aqui é morrer como besta de carga, orgulhosa do próprio fardo.","tip":"<strong>Armadilha:</strong> gabar-se da carga que se aguenta e do quanto se sofre é a vaidade secreta do camelo — o último disfarce do escravo que se crê santo."},
      {"ic":"sword","t":"O Leão Que Conquista","emph":"Leão","b":"No mais solitário dos desertos, o camelo se faz leão: quer arrancar a liberdade e ser senhor do próprio deserto. Encara o dragão de mil escamas douradas — 'Tu Deves' — e ruge o seu <strong>sagrado 'Eu Quero'</strong>. Conquista assim o direito a novos valores. Mas atenta: o leão é majestoso a dizer não; criar, ele ainda não sabe.","tip":"<strong>Sinal de alerta:</strong> a rebeldia pura te livra das correntes, mas não te dá rumo. O 'eu quero' do leão é a liberdade PARA criar — nunca o fim em si.","warn":True},
      {"ic":"spark","t":"A Criança Que Cria","emph":"Criança","b":"O cume do espírito não é a fúria do leão, mas o recomeço sem culpa: a criança é inocência e esquecimento, um novo começo, um jogo, uma roda que gira por si, um primeiro movimento, um <strong>sagrado dizer-sim</strong>. Só ela, leve e sem ressentimento, conquista o próprio mundo e inventa valores que ninguém jurou antes.","tip":"<strong>Como aplicar:</strong> a maturidade mais funda não tem carranca de dever — tem a entrega absorta de quem brinca, esquecido de que algum dia foi camelo."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["Libertar-se tem três tempos: aguentar (camelo), recusar (leão), criar (criança).", "Quem só destrói (o leão) ainda não é quem cria (a criança).", "Forjar valores próprios exige esquecer o peso do 'tu deves' — e brincar como quem nunca o carregou."],
  },
  {
    "slug": "ch04-corpo-desprezadores",
    "sub": "CAPÍTULO 4: O Corpo e a Virtude Doadora",
    "intro": "Zaratustra vira o eixo de cabeça para baixo: o corpo não é cárcere da alma — é a grande razão, uma pluralidade com um só sentido. A virtude mais alta não é a abstinência que se proíbe, mas a que transborda e doa, como o sol. E o fim de todo ensino não é seguir o mestre: é tornar-se quem se é. 'Atrás dos teus pensamentos há um senhor mais poderoso: chama-se Si-mesmo. Mora no teu corpo; é o teu corpo.'",
    "cards": [
      {"ic":"person","t":"A Grande Razão","emph":"Grande Razão","b":"A consciência de que tanto te orgulhas é só um brinquedinho, uma pequena razão a serviço da grande. O <strong>Si-mesmo</strong> — que respira, digere, dorme e desperta — carrega uma sabedoria mais antiga que toda a tua filosofia. 'Corpo sou eu inteiro, e mais nada; alma é só palavra para algo no corpo.' Trata o intelecto como instrumento, jamais como rei.","tip":"<strong>Prática:</strong> antes de decidir só com a cabeça, cala-te e escuta o que dizem o teu peito e o teu ventre — falam a língua mais velha de todas."},
      {"ic":"spark","t":"A Virtude Doadora","emph":"Doadora","b":"A virtude alta não é a santidade anêmica de quem se proíbe de viver. É como o ouro, raro e inútil para o comércio, que <strong>reluz com brilho brando e dá a si mesmo</strong>. Nasce da plenitude de quem tem tanto de si que precisa transbordar — sem esperar aplauso nem troco. A virtude que se doa é o amor que quer ser presente, não preço.","tip":"<strong>Modelo mental:</strong> mede a tua bondade pela vida que ela acende ao redor, não pelo tanto que tiveste de reprimir em ti para parecer bom."},
      {"ic":"key","t":"Torna-te Quem Tu És","emph":"Quem Tu És","b":"O mestre verdadeiro te despede para que aprendas a andar sem ele: 'agora vos perco; encontrai-vos a vós mesmos'. Mal se paga a um professor permanecendo eterno aluno. <strong>Perde-te, para que te reencontres</strong> — e desconfia de Zaratustra, inclusive deste. Realizar a tua potência única é recusar ser a sombra de alguém, ainda que do melhor dos guias.","tip":"<strong>Regra:</strong> não procures ídolos para copiar. A força que admiras no outro é só fagulha — usa-a para cavar a tua própria, não para te ajoelhares diante da dele."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["O corpo é a grande razão — desprezá-lo é cuspir na própria vida.", "A virtude mais alta transborda e doa como o sol; não é abstinência que se gaba.", "O fim do ensino não é seguir o mestre: é tornar-se quem se é — e até dele desconfiar."],
  },
  {
    "slug": "ch05-vontade-de-potencia",
    "sub": "CAPÍTULO 5: A Vontade de Potência",
    "intro": "A vida é, na raiz, vontade de potência: não cata prazer nem se contenta em durar — é ímpeto de crescer, de superar, de dar forma. 'Onde encontrei o vivente, encontrei a vontade de potência.' E a sua forma mais alta não escraviza ninguém de fora: dobra-se sobre si mesma. A vida confessou-me o seu segredo: 'eis, sou aquilo que sempre tem de superar-se a si próprio'.",
    "cards": [
      {"ic":"mountain","t":"O Desejo De Expansão","emph":"Expansão","b":"A vida não quer apenas sobreviver nem caçar prazerzinhos inofensivos; quer antes de tudo <strong>crescer, mandar e impor forma ao caos</strong>. Onde pulsa vida, pulsa vontade de potência. Até o sábio que persegue a verdade está, no fundo, querendo dobrar o mundo ao molde do seu pensamento — pensar é uma forma de querer.","tip":"<strong>Modelo mental:</strong> observa o que ao redor se diz manso e generoso. Sob muita brandura calada dorme a velha fome de sentir-se senhor."},
      {"ic":"sword","t":"O Domínio De Si","emph":"Domínio De Si","b":"Quem não sabe mandar em si está condenado a obedecer — a alguém, a algo, ao próprio impulso. A forma mais alta e mais árdua da vontade de potência não é acorrentar os outros, mas <strong>vergar e superar a própria natureza</strong>. Vencer-se é a única vitória que não tira nada de ninguém — e a coroa do espírito forte.","tip":"<strong>Prática:</strong> mede a tua força não pelo número de quem te obedece, mas pelo número de fraquezas tuas que já domesticaste e puseste a teu serviço."},
      {"ic":"triangle","t":"O Preço Da Criação","emph":"Preço","b":"Não há criação sem dor. Para erguer valores novos, é preciso antes baixar o martelo sobre os velhos altares — e quem cria o bem e o mal tem de ser, primeiro, um <strong>destruidor que quebra as tábuas</strong>. A vida se renova devorando o que caducou. Quem foge do custo da ruptura nunca prova a grandeza de se superar.","tip":"<strong>Sinal de alerta:</strong> se o teu 'crescimento' só te traz paz e nenhuma ruptura que doa, provavelmente paraste de subir e apenas te acomodaste no caminho.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["A vida é, na raiz, vontade de potência — superação, e não mera conservação.", "A potência suprema exerce-se sobre si: autodomínio e autossuperação, não tirania alheia.", "Criar exige destruir as tábuas antigas; todo crescimento cobra o seu preço em dor."],
  },
  {
    "slug": "ch06-ressentimento-rebanho",
    "sub": "CAPÍTULO 6: Ressentimento e Transvaloração",
    "intro": "Boa parte da moral que herdaste não desceu do céu — subiu do porão do ressentimento: a impotência que, não podendo morder, batizou de 'bem' a própria mansidão e de 'mal' a força que a fere. Morto o velho fiador celeste, resta uma só tarefa, e ela é de marteleiro: transvalorar — quebrar cada tábua antiga e perguntar a cada valor se serve à vida ou a renega.",
    "cards": [
      {"ic":"lens","t":"A Genealogia Dos Valores","emph":"Genealogia","b":"Toda virtude tem um porão, e é lá que se acende a lanterna. Não perguntes se um valor é nobre — pergunta <strong>de que ventre nasceu e a quem socorre</strong>. Verás que muita humildade e muita doçura não brotaram de coração transbordante: brotaram do medo, da inveja calada e da fraqueza que, não ousando agir, fez da própria covardia um altar.","tip":"<strong>Pergunta-chave:</strong> esta tua bondade é o ouro que transborda de quem tem demais — ou a couraça de quem não teve coragem de querer?"},
      {"ic":"scale","t":"Senhores Contra Escravos","emph":"Senhores","b":"Há duas formas de valorar, e elas se odeiam. A nobre nasce do próprio peito: diz primeiro 'isto sou eu, e é bom', e só depois, de passagem, chama de comum o que lhe é estranho. A escrava nasce de costas para o forte: começa apontando o inimigo, grita 'tu és o mal' — e só então, por sobra, <strong>chama de 'bem' a própria impotência</strong>. Uma cria; a outra apenas reage.","tip":"<strong>Sinal de alerta:</strong> desconfia de toda justiça mais faminta de rebaixar quem está no alto do que de erguer quem está embaixo. O ressentimento adora vestir-se de virtude pública.","warn":True},
      {"ic":"spark","t":"A Transvaloração","emph":"Transvaloração","b":"A grande virada não é trocar de lugar o bem e o mal na mesma velha tabuada — é <strong>despedaçar a régua inteira</strong> e forjar outra com as próprias mãos. Não meças mais teus atos pelo peso dos milênios, mas por um único fio de prumo: isto faz a vida crescer ou a faz minguar? E sabe que o espírito de gravidade, esse anão que tudo torna pesado, não se mata com argumento — mata-se com riso.","tip":"<strong>Modelo mental:</strong> transvalorar é largar a balança do rebanho, onde 'bom' é igual a 'inofensivo', e pesar a vida na tua própria — onde 'bom' é o que te faz ascender."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["Boa parte da moral 'do bem' é fraqueza disfarçada de virtude — o ressentimento sagrado.", "Há duas lógicas morais: afirmar a partir de si (senhor) ou definir-se contra o inimigo (escravo).", "A tarefa depois da morte de Deus é transvalorar: jogar fora a régua herdada e medir tudo pela vida."],
  },
  {
    "slug": "ch07-eterno-retorno",
    "sub": "CAPÍTULO 7: O Eterno Retorno e o Convalescente",
    "intro": "Eis o pensamento mais abissal, o que Zaratustra mal ousa pronunciar: e se tudo — tudo — voltasse infinitas vezes, sem mudar uma vírgula? Não é astronomia, é provação. É a pedra que esmaga ou que liberta. Pensá-lo até o fim adoece o próprio profeta: ele cai, jaz como morto, e só depois — convalescente, mordido e curado — aprende a cantá-lo de novo.",
    "cards": [
      {"ic":"spiral","t":"O Teste Supremo","emph":"Teste","b":"Suponha que, na tua hora mais solitária, um demônio se esgueire e te sussurre: viverás esta exata vida outra vez, e inúmeras vezes mais — cada dor, cada tédio, cada êxtase, idênticos, até a aranha e o luar entre as árvores. Esse é o <strong>peso mais pesado já posto sobre ombros humanos</strong>. Rangerias os dentes amaldiçoando-o, ou cairias de joelhos chamando-o de deus?","tip":"<strong>Como aplicar:</strong> faz dele o crivo de cada dia — 'quereria este exato instante de volta, igual, para toda a eternidade?'. Se não, não maldigas o instante: muda a vida que o produz."},
      {"ic":"mask","t":"O Nojo Do Pequeno","emph":"Nojo","b":"O que sufoca Zaratustra não é o retorno da dor nem do horror — isso o herói aguenta. A náusea que o derruba é outra: também o homem pequeno, o morno, o covarde voltará eternamente, e voltará para sempre. <strong>Essa serpente do nojo enrosca-se na garganta</strong>; e só há uma cura — morder-lhe a cabeça e cuspi-la fora, para então poder dizer sim ao todo.","tip":"<strong>Armadilha:</strong> é barato amar a vida olhando só para os cumes. A prova é encarar a baixeza do mundo, a mediocridade que também há de retornar — e ainda assim não desviar o olhar.","warn":True},
      {"ic":"clock","t":"O Instante Carregado","emph":"Instante","b":"Estás de pé sob um pórtico, e seu nome é 'Instante'. Atrás de ti, uma rua eterna que já correu; à tua frente, outra eternidade por correr — e as duas se chocam aqui, neste agora. Tudo o que pode acontecer já deve ter acontecido; logo, o presente não é fagulha que se apaga: ele <strong>carrega em si o peso de todas as eras</strong> e a semente de tudo que voltará a ser.","tip":"<strong>Regra:</strong> não esperes redenção fora do tempo nem paraíso no fim da estrada. Este instante é a única eternidade que tua mão alguma vez tocará."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["O eterno retorno não é cosmologia: é a balança secreta que pesa quanto, de fato, amas a tua vida.", "O obstáculo decisivo não é a dor, mas o nojo — que até o pequeno retorne; vencê-lo é convalescer.", "O peso mais pesado, uma vez abraçado, inverte-se em leveza, dança e riso."],
  },
  {
    "slug": "ch08-amor-fati-sim",
    "sub": "CAPÍTULO 8: Amor Fati — o Sagrado 'Sim' e o Meio-Dia",
    "intro": "Eis o cume luminoso de toda a obra: quem suporta o eterno retorno chega ao amor fati. Não é o suspiro de quem aguenta o que veio — é o sim cantado de quem ama o seu destino inteiro, com as cicatrizes e tudo. E a alegria, quando é funda de verdade, não quer só este instante: a dor diz 'passa!', mas toda alegria quer eternidade — quer profunda, profunda eternidade.",
    "cards": [
      {"ic":"spark","t":"Amor Ao Destino","emph":"Amor","b":"Abraça o que te sucede não com o suspiro morno de quem se curva, mas com o <strong>sim feroz de quem escolhe</strong>. Amor fati é querer o teu destino tal como é, sem amputar dele um só capítulo sombrio — pois foi a noite que forjou a estrela, e foram as feridas que afiaram quem te tornaste. Quem quer cortar a dor do passado não ama: regateia.","tip":"<strong>Modelo mental:</strong> resignar-se é dizer 'não há jeito, aceito'. Amar o destino é dizer 'que seja exatamente assim — e mais um milhão de vezes'."},
      {"ic":"eye","t":"O Grande Meio-Dia","emph":"Meio-Dia","b":"Há uma hora no caminho em que as sombras se encolhem ao menor tamanho e o sol pousa a pino — o grande meio-dia, em que o animal e o além-do-homem se olham nos olhos. É o instante de luz mais alta, em que a dor e a alegria se fecham no mesmo anel, e te descobres <strong>capaz de querer a eternidade de todas as coisas</strong>, sem descontar nenhuma.","tip":"<strong>Prática:</strong> educa a tua vontade a parar de litigar com o que já foi. Quem amaldiçoa o passado fica preso a ele; quem o abençoa como necessário fica, enfim, livre."},
      {"ic":"triangle","t":"O Perigo Da Compaixão","emph":"Compaixão","b":"O derradeiro e mais astuto inimigo do criador não tem cara de monstro: tem cara de bondade. É a pena. Diante da dor dos homens superiores, Zaratustra é tentado a parar e consolá-los — e justo aí mora a cilada, pois a piedade mal dosada <strong>paralisa a obra e arrasta o mestre para o fundo junto</strong>. 'A compaixão foi a minha última tentação', confessa ele — e segue caminho.","tip":"<strong>Sinal de alerta:</strong> cuidado quando a pressa de salvar quem sofre ao teu redor virar a desculpa mais nobre que existe para abandonar a tua própria grande obra.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["O cume não é tolerar o destino, é amá-lo (amor fati) — querê-lo de volta, igual, para sempre.", "O sim verdadeiro é total: abraça a dor como elo do mesmo anel da alegria.", "A compaixão mal dosada é a última e mais nobre tentação do criador."],
  },
  {
    "slug": "ch09-estrutura-simbolos",
    "sub": "CAPÍTULO 9: Estrutura, Símbolos e 'Para Todos e Para Ninguém'",
    "intro": "Este não é livro que prova: é livro que canta. Filosofia encenada, não demonstrada — em parábolas, salmos virados do avesso, bichos que falam e um profeta que ri. Quem o lê caçando um sistema limpo erra a porta: aqui as imagens não enfeitam o argumento, elas são o argumento. Decifrar os símbolos é decifrar as teses.",
    "cards": [
      {"ic":"book","t":"O Evangelho Invertido","emph":"Evangelho","b":"O livro é um espelho zombeteiro: empresta a cadência dos salmos, a solenidade do sermão e o molde da parábola para <strong>dinamitar por dentro a casa que imita</strong>. Nietzsche não redige um tratado árido — ele canta um anti-evangelho, onde a própria forma sagrada vira a arma que profana o sagrado. A paródia é o martelo; a beleza, o estopim.","tip":"<strong>Regra de leitura:</strong> não exijas da obra um sistema sem contradição. Ela avança, recua e se desdiz porque o pensamento vivo não marcha em fila — dança."},
      {"ic":"constellation","t":"As Chaves Simbólicas","emph":"Simbólicas","b":"Lê os bichos e as paisagens como quem lê escritura. A <strong>águia e a serpente</strong>, companheiras de Zaratustra, casam o orgulho que voa alto à sabedoria que se enrola sobre si — e a serpente, enrodilhada, é também o anel do eterno retorno. A montanha é o ar rarefeito da criação solitária; o mercado, a anestesia morna do rebanho. O pensamento mais árduo só ganha carne nessas figuras.","tip":"<strong>Como aplicar:</strong> ao tropeçar numa passagem poética que parece hermética, detém-te e traduz: que conceito bruto sobre o homem esta imagem está guardando por baixo?"},
      {"ic":"person","t":"Para Todos E Ninguém","emph":"Ninguém","b":"O subtítulo é uma cilada exata: 'para todos' na ambição de curar a cultura inteira; 'para ninguém' porque <strong>quem tenta segui-lo como cartilha trai a sua única lição</strong>. Por isso Zaratustra enxota os próprios discípulos — só te encontrarás a ti depois de o perderes. A obra que mais pede leitores é a que mais despreza seguidores.","tip":"<strong>Modelo mental:</strong> se concordas com tudo que o profeta diz e te fazes seu fiel devoto, falhaste no teste supremo do livro. Ele te quer criador, não crente."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["A forma (parábola, salmo, paródia bíblica) não veste o conteúdo: é o conteúdo.", "Os símbolos — águia e serpente, a corda sobre o abismo, o meio-dia, a dança — carregam as teses centrais.", "É um livro 'para todos e para ninguém': universal na ambição, radicalmente solitário no destino — quem o segue, o perde."],
  },
]
