const fs = require('fs');
const path = require('path');
const basePath = "C:\\Users\\User\\.gemini\\config\\skills\\drdolabela";

const template = (c) => `# Chapter ${c.id}: ${c.title}

## Core Idea
${c.core}

## Frameworks Introduced
- **${c.framework.name}**: ${c.framework.def}
  - When to use: ${c.framework.when}
  - How: ${c.framework.how}

## Key Concepts
- **${c.concept1.name}**: ${c.concept1.def}
- **${c.concept2.name}**: ${c.concept2.def}

## Mental Models
- **${c.model1.name}**: ${c.model1.def}
- **${c.model2.name}**: ${c.model2.def}

## Anti-patterns
- **${c.anti.name}**: ${c.anti.def}

## Worked Example
${c.example}

## Key Takeaways
1. ${c.takeaway1}
2. ${c.takeaway2}
`;

const data = [
  {
    skill: "diodoro-library-of-history",
    chaps: [
      { id: "01", slug: "mythic-origins", title: "Mythic Origins", core: "Integrating mythology as early historical sociology.", framework: {name: "Euhemeristic Synthesis", def: "Decoding divine narratives as human achievements.", when: "Parsing cultural myths.", how: "Isolate myth -> Identify technology -> Map as milestone."}, concept1: {name: "Universalism", def: "Encompassing global history into one narrative."}, concept2: {name: "Cultural Diffusion", def: "Tracking idea transmission."}, model1: {name: "Myth-as-Archive", def: "Myth as encrypted memory."}, model2: {name: "Cyclical Decadence", def: "Societies rise and fall predictably."}, anti: {name: "Literalism", def: "Discarding myth due to supernatural elements."}, example: "Analyzing Osiris as the codification of agricultural discovery.", takeaway1: "Myths are blueprints for societal values.", takeaway2: "Universal history weaves local stories into global frameworks." },
      { id: "02", slug: "hellenistic-rise", title: "Hellenistic Rise", core: "Mapping geopolitical shifts to universal empires.", framework: {name: "Hegemonic Transition", def: "Tracking power consolidation.", when: "Studying empire integration.", how: "Identify vacuum -> Analyze military mechanism -> Evaluate culture."}, concept1: {name: "Syncretism", def: "Merging distinct cultural systems."}, concept2: {name: "Diadochi", def: "Successors shaping political architecture."}, model1: {name: "Imperial Overstretch", def: "Vulnerability of expanded empires."}, model2: {name: "Cosmopolitanism", def: "Citizen of the known world."}, anti: {name: "Hellenocentric Bias", def: "Assuming Greek culture replaced indigenous ones."}, example: "Ptolemaic Egypt mapping Greek administration onto pharaonic religion.", takeaway1: "Hegemony requires syncretism.", takeaway2: "Managing diversity is complex." },
      { id: "03", slug: "universal-framework", title: "Universal Framework", core: "Synthesizing parallel historical timelines.", framework: {name: "Synchronistic Chronology", def: "Aligning disparate timelines.", when: "Building comparative global understanding.", how: "Establish anchor -> Map regions -> Identify correlations."}, concept1: {name: "Historiographical Synthesis", def: "Compiling sources into encyclopedias."}, concept2: {name: "Moral Exemplarity", def: "History as didactic tool."}, model1: {name: "Historian as Curator", def: "Organizing existing knowledge."}, model2: {name: "Parallel Evolution", def: "Independent simultaneous developments."}, anti: {name: "Chronological Isolationism", def: "Ignoring contemporaneous events."}, example: "Comparing Roman republican rise and Greek decline.", takeaway1: "Requires rigorous timeline synchronization.", takeaway2: "Narratives serve didactic purposes." }
    ]
  },
  {
    skill: "diogenes-lives-of-eminent-philosophers",
    chaps: [
      { id: "01", slug: "ionian-italian", title: "Ionian and Italian Traditions", core: "Structuring early philosophy into physical and mathematical lineages.", framework: {name: "Doxographical Mapping", def: "Tracing evolution through successions.", when: "Analyzing idea genealogy.", how: "Identify founder -> Map disciples -> Track mutations."}, concept1: {name: "Ionian Naturalism", def: "Search for material arche."}, concept2: {name: "Italian Pythagoreanism", def: "Immaterial numerical principles."}, model1: {name: "The Arche", def: "Fundamental derived substance."}, model2: {name: "Matter vs Form", def: "Physical reality vs abstract structure."}, anti: {name: "Ahistorical Analysis", def: "Ignoring geographical context."}, example: "Contrasting Anaximander's apeiron with Pythagoras's harmony.", takeaway1: "Western thought splits between empiricism and idealism.", takeaway2: "Lineage is key to understanding." },
      { id: "02", slug: "socratics", title: "Socrates and the Socratics", core: "The ethical turn shifting focus to human life and virtue.", framework: {name: "Elenchus", def: "Dialectical inquiry via refutation.", when: "Challenging unexamined assumptions.", how: "Ask definition -> Expose contradiction -> Refine."}, concept1: {name: "Aporia", def: "Productive perplexity."}, concept2: {name: "Moral Intellectualism", def: "Vice is ignorance."}, model1: {name: "Examined Life", def: "Reflection is essential."}, model2: {name: "Intellectual Midwifery", def: "Helping others birth truth."}, anti: {name: "Sophistry", def: "Arguing for power, not truth."}, example: "Using Elenchus in modern corporate ethics to strip false premises.", takeaway1: "Wisdom begins with acknowledging ignorance.", takeaway2: "Philosophy is a practical ethical tool." },
      { id: "03", slug: "hellenistic-schools", title: "Hellenistic Schools", core: "Philosophy as a therapeutic tool for mental tranquility.", framework: {name: "Therapeutic Philosophy", def: "Using logic to cure the soul's distress.", when: "For personal resilience.", how: "Diagnose fear -> Apply doctrinal remedy -> Practice daily exercises."}, concept1: {name: "Ataraxia", def: "Tranquility of the soul."}, concept2: {name: "Hedonic Calculus", def: "Maximizing static pleasure."}, model1: {name: "Dichotomy of Control", def: "Separating what is in our power from what is not."}, model2: {name: "Amor Fati", def: "Loving one's fate."}, anti: {name: "Vulgar Hedonism", def: "Confusing philosophical pleasure with endless indulgence."}, example: "Using stoic principles to manage career setbacks.", takeaway1: "Philosophy must have practical impact.", takeaway2: "Freedom comes from managing desires." }
    ]
  },
  {
    skill: "diogenes-vidas-e-doutrinas",
    chaps: [
      { id: "01", slug: "tradicao-jonica", title: "Tradição Jônica e Itálica", core: "A filosofia nasce dividida entre investigação material e abstração matemática.", framework: {name: "Mapeamento Doxográfico", def: "Traçar a evolução de ideias via linhagens.", when: "Ao investigar a mutação de conceitos.", how: "Identificar originário -> Mapear discípulos -> Analisar desvios."}, concept1: {name: "Arché", def: "O princípio material ou estrutural."}, concept2: {name: "Physis", def: "Natureza como fluxo material."}, model1: {name: "Dualismo Metodológico", def: "Matéria vs. Forma lógica."}, model2: {name: "Harmonia", def: "Proporções matemáticas subjacentes."}, anti: {name: "Projeção Moderna", def: "Enquadrar antigos em categorias científicas modernas."}, example: "Contrapor Tales (água) com Pitágoras (números) em design de sistemas.", takeaway1: "O pensamento ocidental oscila entre empirismo e idealismo.", takeaway2: "A compreensão exige o estudo das linhagens de transmissão." },
      { id: "02", slug: "socrates", title: "Sócrates e as Escolas Socráticas", core: "Redirecionamento da filosofia para a ética e investigação humana.", framework: {name: "Elenchos", def: "Teste lógico para expor contradições.", when: "Para desconstruir dogmas.", how: "Solicitar definição -> Fazer perguntas -> Demonstrar contradições."}, concept1: {name: "Aporia", def: "Confusão produtiva necessária para aprender."}, concept2: {name: "Intelectualismo Moral", def: "O mal é fruto da ignorância."}, model1: {name: "A Vida Examinada", def: "Reflexão contínua para o florescimento."}, model2: {name: "Maiêutica", def: "Parto de ideias guiado por perguntas."}, anti: {name: "Sofística", def: "Focar na persuasão em vez da verdade."}, example: "Usar a maiêutica em mentoria para revelar falhas lógicas.", takeaway1: "Consciência da ignorância é o início do saber.", takeaway2: "Ética é investigação racional contínua." },
      { id: "03", slug: "helenisticas", title: "Escolas Helenísticas", core: "A filosofia como terapia para a angústia num mundo incerto.", framework: {name: "Terapia Filosófica", def: "Uso de dogmas como fármacos da alma.", when: "Gestão de crise e resiliência.", how: "Diagnosticar perturbação -> Aplicar correção lógica -> Exercitar."}, concept1: {name: "Ataraxia", def: "Ausência de perturbação."}, concept2: {name: "Aponia", def: "Ausência de dor física."}, model1: {name: "Dicotomia do Controle", def: "Foco no que se pode controlar."}, model2: {name: "Cálculo Hedonista", def: "Avaliação de desejos naturais e necessários."}, anti: {name: "Passividade Fatalista", def: "Inação diante do destino."}, example: "Gerenciar expectativas financeiras aplicando o cálculo epicurista.", takeaway1: "Filosofia deve curar a ansiedade.", takeaway2: "A liberdade vem da gestão dos juízos." }
    ]
  },
  {
    skill: "eliade-shamanism",
    chaps: [
      { id: "01", slug: "initiation", title: "Shamanic Initiation", core: "Vocation requires a crisis, symbolic death, and resurrection.", framework: {name: "Initiatory Sickness", def: "Breakdown preceding spiritual restructuring.", when: "Analyzing profound transformative crises.", how: "Recognize crisis -> Identify dismemberment -> Integrate self."}, concept1: {name: "Symbolic Dismemberment", def: "Visionary experience of being torn apart."}, concept2: {name: "Vocation", def: "A calling inflicted by spirits, not a choice."}, model1: {name: "Wounded Healer", def: "Navigating suffering to heal others."}, model2: {name: "Ontological Rupture", def: "Radical break from ordinary reality."}, anti: {name: "Pathologization", def: "Reducing crisis to mental illness."}, example: "Leader facing failure rebuilding identity with deeper empathy.", takeaway1: "Mastery requires traversing personal dissolution.", takeaway2: "Initiation transforms chaos into order." },
      { id: "02", slug: "techniques", title: "Techniques of Ecstasy", core: "Using techniques of ecstasy to alter consciousness.", framework: {name: "Ecstatic Trance Architecture", def: "Methodology to exit profane time.", when: "Designing deep work states.", how: "Utilize rhythmic driving -> Focus intent -> Achieve separation."}, concept1: {name: "Ecstasy", def: "Standing outside oneself."}, concept2: {name: "Magical Flight", def: "Traveling in spirit form."}, model1: {name: "Sonic Driver", def: "Rhythmic sound shifting baseline states."}, model2: {name: "State-Dependent Knowledge", def: "Info accessible only in specific states."}, anti: {name: "Escapism", def: "Seeking altered states to flee reality."}, example: "Using binaural beats for creative insight flow state.", takeaway1: "Altered states are engineered for information retrieval.", takeaway2: "The shaman controls the trance." },
      { id: "03", slug: "cosmology", title: "Shamanic Cosmology", core: "Operating within a mapped, tripartite universe connected by an axis.", framework: {name: "Axis Mundi Mapping", def: "Using a central pillar to navigate complexity.", when: "Structuring complex information systems.", how: "Establish Center -> Map hierarchical zones -> Define portals."}, concept1: {name: "Axis Mundi", def: "Cosmic pillar connecting all zones."}, concept2: {name: "Center of the World", def: "Sacred point of origin."}, model1: {name: "Tripartite Reality", def: "Subconscious, practical, and ideal levels."}, model2: {name: "Cosmic Topography", def: "Detailed mental map of abstract spaces."}, anti: {name: "Flatland Thinking", def: "Treating all variables on a single plane."}, example: "Mapping corporate culture into values, operations, and hidden dynamics.", takeaway1: "Complex navigation requires a multi-level map.", takeaway2: "Agency comes from moving between levels of reality." }
    ]
  },
  {
    skill: "eliade-yoga",
    chaps: [
      { id: "01", slug: "samkhya", title: "Yoga and Samkhya", core: "Techniques to achieve liberation via dualism between Spirit and matter.", framework: {name: "Dualistic Disentanglement", def: "Separating consciousness from mental fluctuations.", when: "Seeking extreme cognitive detachment.", how: "Identify mental states as matter -> Cultivate Observer -> Negate material."}, concept1: {name: "Purusha", def: "Pure, eternal consciousness."}, concept2: {name: "Prakriti", def: "Nature, mind, matter."}, model1: {name: "Mind as Matter", def: "Thoughts are subtle forms of matter."}, model2: {name: "Neti Neti", def: "Not this, not this (systematic negation)."}, anti: {name: "Enmeshment", def: "Believing observer and observed are one."}, example: "Applying dualism to anxiety by observing rather than identifying.", takeaway1: "Theory is useless without physical/mental practice.", takeaway2: "Freedom comes from realizing you are the observer." },
      { id: "02", slug: "autonomy", title: "Techniques of Autonomy", core: "A systematic technology for destroying illusions and achieving enstasis.", framework: {name: "Eight-Limbed Path", def: "Sequential protocol for mastering mind and body.", when: "Designing a protocol for supreme focus.", how: "Ethical baselines -> Physical stability -> Mental withdrawal -> Absorption."}, concept1: {name: "Citta Vritti Nirodha", def: "Cessation of mental fluctuations."}, concept2: {name: "Samadhi", def: "Enstasis, complete absorption."}, model1: {name: "Physiological Anchoring", def: "Physical stillness prerequisites mental stillness."}, model2: {name: "Step-Function Concentration", def: "Progressive states of absorption."}, anti: {name: "Skipping the Baseline", def: "Attempting meditation without moral/physical stability."}, example: "Removing distractions and focusing intensely until entering secular Samadhi.", takeaway1: "Mental autonomy is an engineered state.", takeaway2: "The goal is revealing pristine underlying consciousness." },
      { id: "03", slug: "tantrism", title: "Tantrism and Hatha Yoga", core: "Using physiological forces and profane experiences as vehicles for liberation.", framework: {name: "Transmutation of Energy", def: "Using base instincts as fuel for ascent.", when: "Leveraging strong emotions rather than suppressing them.", how: "Arouse energy -> Arrest outward flow -> Sublimate upward."}, concept1: {name: "Kundalini", def: "Latent cosmic energy to be awakened."}, concept2: {name: "Subtle Body", def: "Esoteric anatomy of channels and chakras."}, model1: {name: "Poison as Medicine", def: "Binding elements can liberate if used with precision."}, model2: {name: "Body as Microcosm", def: "Mastering the body is mastering the cosmos."}, anti: {name: "Ascetic Repression", def: "Starving the body of potent energies."}, example: "Transmuting adrenaline into laser-focused presence during a crisis.", takeaway1: "The physical body is an alchemical laboratory.", takeaway2: "Mastery involves redirecting biological drives." }
    ]
  },
  {
    skill: "epicuro-cartas-maximas",
    chaps: [
      { id: "01", slug: "fisica", title: "Física e Atomismo", core: "Uso do atomismo materialista para eliminar o medo dos deuses e da morte.", framework: {name: "Desconstrução do Medo", def: "Uso da física para libertar a psique.", when: "Quando ansiedades irracionais dominam a decisão.", how: "Analisar o fenômeno -> Reduzi-o a causas materiais -> Concluir ausência de intenção divina."}, concept1: {name: "Atomismo", def: "A realidade é apenas átomos e vazio."}, concept2: {name: "Mortalidade da Alma", def: "A morte não é nada para nós."}, model1: {name: "Materialismo Terapêutico", def: "A física reduz o terror existencial."}, model2: {name: "Cadeia Causal", def: "Fenômenos têm explicações mecânicas."}, anti: {name: "Superstição", def: "Atribuir a natureza à ira divina."}, example: "Desmistificar uma falha técnica como cadeia de causa e efeito, não destino.", takeaway1: "O conhecimento natural é essencial para a tranquilidade.", takeaway2: "O medo da morte é irracional." },
      { id: "02", slug: "epistemologia", title: "Epistemologia e Canônica", core: "As sensações são o critério absoluto da verdade e base do conhecimento.", framework: {name: "Critério Empírico", def: "Confiança estrita nas percepções diretas.", when: "Ao validar informações em ambientes incertos.", how: "Coletar dados -> Separar sensação do juízo -> Confirmar com repetição."}, concept1: {name: "Sensações", def: "Contato direto com os átomos."}, concept2: {name: "Antecipações", def: "Conceitos formados pela repetição."}, model1: {name: "Erro no Juízo", def: "A visão não mente, a mente interpreta mal."}, model2: {name: "Evidência Direta", def: "O real é o percebido."}, anti: {name: "Ceticismo Radical", def: "Duvidar dos próprios sentidos impossibilita a ação."}, example: "Auditar a fórmula que interpretou um dado analítico, não o dado bruto em si.", takeaway1: "As sensações fornecem contato não filtrado com a realidade.", takeaway2: "A falsidade vem da precipitação do raciocínio." },
      { id: "03", slug: "etica", title: "Ética e Ataraxia", core: "O propósito da vida é a obtenção de prazer, entendido como ausência de dor e perturbação.", framework: {name: "Cálculo dos Prazeres", def: "Avaliação de desejos para maximizar a tranquilidade.", when: "No design do estilo de vida e consumo.", how: "Classificar desejo -> Descartar fúteis -> Moderar os não necessários."}, concept1: {name: "Tetrapharmakon", def: "Os quatro remédios para a alma."}, concept2: {name: "Ataraxia", def: "Tranquilidade perfeita da alma."}, model1: {name: "Prazer Estático", def: "O estado de calma equilibrada é superior à excitação."}, model2: {name: "Desejos Naturais e Necessários", def: "A base biológica mínima para a paz."}, anti: {name: "Consumismo Hedônico", def: "Buscar estímulos novos constantemente."}, example: "Rejeitar promoção desgastante focando no prazer estático do tempo livre.", takeaway1: "O maior prazer é a simples ausência de dor.", takeaway2: "A riqueza é limitar desejos ao que é natural." }
    ]
  },
  {
    skill: "epiteto-complete-works",
    chaps: [
      { id: "01", slug: "dichotomy", title: "The Dichotomy of Control", core: "Dividing existence into things up to us and things not up to us.", framework: {name: "Agency Filter", def: "Triaging events based on personal control.", when: "Facing overwhelming external circumstances.", how: "Pause reaction -> Ask if within direct control -> Act rationally or accept."}, concept1: {name: "Prohairesis", def: "Moral character, our power of choice."}, concept2: {name: "Indifferents", def: "Everything outside our control."}, model1: {name: "Archer Analogy", def: "Success is in the aim, not the target."}, model2: {name: "Internal Locus of Control", def: "Self-worth disconnected from outcomes."}, anti: {name: "Emotional Enmeshment", def: "Tying worth to external forces."}, example: "Feeling no distress over a market crash, evaluating only personal strategy execution.", takeaway1: "Freedom comes from mastering volitions.", takeaway2: "Attempting to control the uncontrollable guarantees misery." },
      { id: "02", slug: "disciplines", title: "The Three Disciplines", core: "Operationalizing Stoicism into daily practice of Desire, Action, and Assent.", framework: {name: "Tripartite Practice", def: "Daily regimen for training the soul.", when: "Structuring personal development.", how: "Train desire to accept fate -> Train impulses for duty -> Train assent for logic."}, concept1: {name: "Amor Fati", def: "Loving one's fate."}, concept2: {name: "Assent", def: "Cognitive act of agreeing to an impression."}, model1: {name: "Guard at the Door", def: "Scrutinizing every mental impression."}, model2: {name: "Cognitive Distance", def: "Separating event from interpretation."}, anti: {name: "Impulsive Reactivity", def: "Automatically agreeing with emotional impressions."}, example: "Pausing when insulted to withhold assent from the impression of harm.", takeaway1: "Philosophy is rigorous daily training.", takeaway2: "We are disturbed by views, not events." },
      { id: "03", slug: "role-ethics", title: "Role Ethics", core: "Duties in life are determined by specific social and natural roles.", framework: {name: "Role-Based Duty Mapping", def: "Determining appropriate action based on persona.", when: "Facing ethical dilemmas or conflicts of interest.", how: "Identify roles -> Define inherent duties -> Act to fulfill highest role."}, concept1: {name: "Prosopon", def: "The character/role one plays in life."}, concept2: {name: "Cosmopolitanism", def: "Citizen of the universe."}, model1: {name: "Actor in a Play", def: "You do not choose the role, but must play it excellently."}, model2: {name: "Hierarchy of Roles", def: "Universal reason overrides social demands."}, anti: {name: "Role Confusion", def: "Neglecting core duties to fulfill peripheral desires."}, example: "A judge balancing the role of friend (leniency) with the role of judge (impartiality).", takeaway1: "Excellence is fulfilling specific role duties.", takeaway2: "Capacity for moral excellence is identical regardless of station." }
    ]
  },
  {
    skill: "estrabao-geography",
    chaps: [
      { id: "01", slug: "geography", title: "Geography as Philosophy", core: "Geography is an applied philosophy vital for statesmanship.", framework: {name: "Geopolitical Synthesis", def: "Integrating physical geography, culture, and politics.", when: "Evaluating strategic potential of a region.", how: "Assess terrain -> Map migrations -> Synthesize structural impact."}, concept1: {name: "Oikoumene", def: "The known, inhabited world."}, concept2: {name: "Environmental Determinism", def: "Geography shapes societal character."}, model1: {name: "Polymath's Lens", def: "Geography requires astronomy, history, and myth."}, model2: {name: "Spatial Strategy", def: "Space dictates political viability."}, anti: {name: "Topographical Myopia", def: "Treating maps purely as physical spaces without cultural data."}, example: "Analyzing the Mediterranean as an essential highway driving Roman naval supremacy.", takeaway1: "Geography is foundational for effective leadership.", takeaway2: "Space and culture are inextricably linked." },
      { id: "02", slug: "chorography", title: "Chorography and Empire", core: "Chorography as a tool for detailed regional imperial administration.", framework: {name: "Imperial Chorography", def: "Deep-dive regional analysis for governance.", when: "Deploying resources in new territories.", how: "Define borders -> Catalog resources/customs -> Identify chokepoints."}, concept1: {name: "Chorography", def: "Descriptive study of specific regions."}, concept2: {name: "Pax Romana", def: "Roman peace as civilizing force."}, model1: {name: "Knowledge as Power", def: "Mapping a territory is intellectual conquest."}, model2: {name: "Administrative Granularity", def: "Local details trump global theory."}, anti: {name: "Uniform Administration", def: "Applying the same governance model to disparate terrains."}, example: "Focusing on Iberian mineral wealth and tribal temperaments for effective extraction.", takeaway1: "Local knowledge is superior for practical administration.", takeaway2: "Organization of spatial knowledge is an act of control." },
      { id: "03", slug: "cultural-topography", title: "Cultural Topography", core: "Mythic and historical memory of a landscape is as important as physical features.", framework: {name: "Mythic Landscape Mapping", def: "Reading historical layers of physical terrain.", when: "Engaging in cultural diplomacy or brand building.", how: "Identify site -> Unearth foundational myths -> Use for legitimacy."}, concept1: {name: "Homeric Authority", def: "Using ancient texts to validate contemporary claims."}, concept2: {name: "Sacred Geography", def: "Spaces charged with religious significance."}, model1: {name: "Palimpsest Terrain", def: "Landscape as a document written over multiple times."}, model2: {name: "Cultural Coordinates", def: "Myths dictating local behavior."}, anti: {name: "Utilitarian Erasure", def: "Ignoring historical significance for pure economic utility."}, example: "Validating a ruined city's importance by its role in the Trojan War.", takeaway1: "Landscapes are charged with cultural memory.", takeaway2: "Ancient texts act as critical coordinates in navigating terrain." }
    ]
  },
  {
    skill: "euripides-as-bacantes",
    chaps: [
      { id: "01", slug: "dionisio", title: "O Retorno de Dionísio", core: "A força do irracional e do desejo retorna para exigir reconhecimento e punir a repressão.", framework: {name: "Gestão do Irracional", def: "O reconhecimento obrigatório das forças instintivas.", when: "Ao lidar com pressões psicológicas reprimidas em organizações.", how: "Identificar força irracional -> Fornecer canal estruturado -> Evitar repressão frontal."}, concept1: {name: "O Estrangeiro", def: "A força desestabilizadora da ordem."}, concept2: {name: "Entusiasmo", def: "Estar possuído pelo deus, perda de individuação."}, model1: {name: "Vingança do Reprimido", def: "O que não se integra, destrói."}, model2: {name: "Energia Primal", def: "Instintos básicos como força motriz."}, anti: {name: "Racionalismo Arrogante", def: "Achar que leis controlam emoções primais."}, example: "Liderança que proíbe manifestações informais sofre colapso de moral.", takeaway1: "A racionalidade tem limites que o êxtase exige ocupar.", takeaway2: "Negar a natureza primal garante a destruição." },
      { id: "02", slug: "razao", title: "Razão vs. Êxtase", core: "O conflito letal entre a ordem estrita (Penteu) e a libertação orgiástica (Bacantes).", framework: {name: "Análise de Tensão Dialética", def: "Mapear o ponto de ruptura entre controle e liberdade.", when: "Ao equilibrar processos de compliance com inovação caótica.", how: "Mapear demandas da Ordem -> Mapear pressões do Caos -> Negociar integração."}, concept1: {name: "Hubris", def: "Arrogância fatal ao desafiar forças maiores."}, concept2: {name: "Sparagmos", def: "Despedaçamento ritual da forma rígida."}, model1: {name: "Ilusão do Controle", def: "Crença de que prender o corpo aprisiona a ideia."}, model2: {name: "Atração pelo Proibido", def: "A curiosidade voyeurística pela transgressão."}, anti: {name: "Rigidez Estrutural", def: "Sistemas inflexíveis quebram sob pressões não mapeadas."}, example: "Reguladores excessivos desenvolvendo fascínio pelo que tentam controlar.", takeaway1: "Sistemas hiper-rígidos são frágeis diante do caos.", takeaway2: "A verdadeira liderança integra aspectos obscuros." },
      { id: "03", slug: "catarse", title: "Catarse Trágica", core: "A destruição produz terror e piedade, reafirmando que o absoluto está além da moralidade humana.", framework: {name: "Mecanismo da Catarse", def: "Purificação emocional através da tragédia.", when: "No design de narrativas e resolução de traumas coletivos.", how: "Construir tensão -> Executar a queda -> Provocar reconhecimento da verdade."}, concept1: {name: "Anagnórise", def: "O reconhecimento doloroso da verdade."}, concept2: {name: "Implacabilidade Divina", def: "Forças da natureza não são morais."}, model1: {name: "Despertar Pós-Êxtase", def: "O custo de retornar à realidade após cegueira coletiva."}, model2: {name: "Destruição do Ego", def: "O contato com o absoluto aniquila o eu."}, anti: {name: "Final Feliz Forçado", def: "Tentar resolver contradições profundas com otimismo vazio."}, example: "O colapso de uma startup embriagada por crescimento irracional gerando clareza letal.", takeaway1: "O contato direto com o absoluto destrói o ego.", takeaway2: "O reconhecimento costuma vir tarde demais para evitar a tragédia." }
    ]
  },
  {
    skill: "euripides-fragments",
    chaps: [
      { id: "01", slug: "lost-tragedies", title: "Lost Tragedies and Mythic Variations", core: "Fragments reveal Euripides' radical experimentation with established mythic narratives.", framework: {name: "Mythic Subversion", def: "Altering core narratives to highlight alternative perspectives.", when: "Reframing legacy systems or cultural norms.", how: "Identify core myth -> Change a critical variable -> Analyze the new ethical implications."}, concept1: {name: "Palimpsest Myth", def: "Rewriting over older traditions."}, concept2: {name: "Variant Narrative", def: "Alternative timelines of known stories."}, model1: {name: "Narrative Plasticity", def: "Stories can bend drastically without breaking."}, model2: {name: "Marginal Focus", def: "Centering the story on side characters."}, anti: {name: "Canon Worship", def: "Refusing to alter a story because of 'tradition'."}, example: "Reconstructing the lost 'Telephus' to show a beggar as a king, forcing empathy.", takeaway1: "Innovation often comes from subverting established narratives.", takeaway2: "Fragments can contain more radical ideas than complete texts." },
      { id: "02", slug: "sophistic-themes", title: "Philosophical and Sophistic Themes", core: "Euripides embeds cutting-edge sophistic debates into the mouths of mythological characters.", framework: {name: "Dialectical Dramatization", def: "Using narrative conflict to stage philosophical debates.", when: "Presenting complex arguments to a broad audience.", how: "Assign opposing views -> Stage a high-stakes conflict -> Let the audience judge."}, concept1: {name: "Agon", def: "Formal debate between two characters."}, concept2: {name: "Nomos vs Physis", def: "The debate between law/custom and nature."}, model1: {name: "Theatrical Sophistry", def: "The stage as a laboratory for ideas."}, model2: {name: "Rhetorical Relativism", def: "Every argument has a counter-argument."}, anti: {name: "Didactic Monologue", def: "Preaching a single truth without staging its counter-argument."}, example: "Using fragments of 'Bellerophon' to debate the existence of the gods in the face of injustice.", takeaway1: "Drama is a powerful vehicle for intellectual debate.", takeaway2: "Complex ideas are best tested in conflict." },
      { id: "03", slug: "women-society", title: "Women and Society in Fragments", core: "Fragments often contain Euripides' most piercing critiques of patriarchal Greek society.", framework: {name: "Subaltern Voicing", def: "Giving articulate voice to the marginalized.", when: "Critiquing systemic power structures.", how: "Identify the marginalized -> Grant them high rhetoric -> Expose systemic hypocrisy."}, concept1: {name: "Misogyny Critique", def: "Exposing the logical flaws in patriarchal norms."}, concept2: {name: "Domestic Tragedy", def: "Elevating household conflicts to epic status."}, model1: {name: "The Outsider's Clarity", def: "Those excluded from power see its flaws most clearly."}, model2: {name: "Voice as Agency", def: "Speaking truth to power as the ultimate act of defiance."}, anti: {name: "Heroic Chauvinism", def: "Focusing solely on aristocratic male exploits."}, example: "Analyzing fragments of 'Melanippe the Wise' where a woman philosophically dismantles male assumptions.", takeaway1: "True societal critique comes from its margins.", takeaway2: "Giving voice to the voiceless shifts the paradigm of power." }
    ]
  },
  {
    skill: "faivre-western-esotericism",
    chaps: [
      { id: "01", slug: "four-characteristics", title: "The Four Fundamental Characteristics", core: "Defining esoteric thought through correspondences, living nature, imagination, and transmutation.", framework: {name: "Esoteric Paradigm Mapping", def: "Identifying esoteric structures in texts or practices.", when: "Distinguishing esoteric from exoteric philosophy.", how: "Check for: 1. Correspondences. 2. Living Nature. 3. Imagination. 4. Transmutation."}, concept1: {name: "Correspondences", def: "As above, so below; symbolic links across reality."}, concept2: {name: "Living Nature", def: "The cosmos is alive, conscious, and interconnected."}, model1: {name: "Macrocosm/Microcosm", def: "The part contains the whole."}, model2: {name: "Sympathy/Antipathy", def: "Invisible forces attracting or repelling."}, anti: {name: "Mechanistic Reductionism", def: "Viewing nature merely as dead matter governed by blind laws."}, example: "Using astrological correspondences to diagnose psychological archetypes.", takeaway1: "Esotericism is a specific structural way of viewing the world.", takeaway2: "Everything is connected through invisible, symbolic links." },
      { id: "02", slug: "imagination-mediation", title: "Imagination and Mediations", core: "The imagination is a cognitive organ capable of accessing higher realities through symbols.", framework: {name: "Active Imagination", def: "Using symbols to mediate between the human and divine.", when: "Accessing intuition or solving non-linear problems.", how: "Focus on a symbol -> Allow subconscious to animate it -> Translate insights into conscious action."}, concept1: {name: "Mundus Imaginalis", def: "The intermediate world of images and spirits."}, concept2: {name: "Mediation", def: "Angels, spirits, or rituals acting as bridges."}, model1: {name: "Symbolic Resonance", def: "Symbols are not arbitrary; they vibrate with intrinsic truth."}, model2: {name: "The Cognitive Organ", def: "Imagination as a tool for discovery, not just fantasy."}, anti: {name: "Rational Exclusivity", def: "Dismissing non-logical insight as mere hallucination."}, example: "Using tarot or alchemical imagery as a heuristic tool for strategic brainstorming.", takeaway1: "Imagination is a valid epistemic tool.", takeaway2: "Mediation is necessary to bridge the gap to the absolute." },
      { id: "03", slug: "transmutation-praxis", title: "Transmutation and Praxis", core: "Esotericism requires the active inner transformation of the practitioner, not just intellectual assent.", framework: {name: "Alchemical Transmutation", def: "The process of refining the self alongside the work.", when: "Engaging in deep personal or organizational change.", how: "Identify base material (flaws) -> Apply pressure/heat (discipline) -> Extract the purified essence (virtue)."}, concept1: {name: "Transmutation", def: "Qualitative change of the soul (lead to gold)."}, concept2: {name: "Praxis", def: "The mandatory practical application of esoteric theory."}, model1: {name: "The Inner Laboratory", def: "The true work of alchemy happens within the alchemist."}, model2: {name: "Solve et Coagula", def: "Dissolve the old structure to synthesize the new."}, anti: {name: "Armchair Occultism", def: "Accumulating esoteric knowledge without attempting personal transformation."}, example: "Treating a difficult project not just as a task, but as an alchemical crucible for developing personal resilience.", takeaway1: "Knowledge without transformation is dead.", takeaway2: "The ultimate goal is the spiritual refinement of the individual." }
    ]
  },
  {
    skill: "faustino-filosofia-forma-de-vida-ensaios",
    chaps: [
      { id: "01", slug: "exercicios-espirituais", title: "A Filosofia como Exercício Espiritual", core: "A filosofia antiga não era teoria acadêmica, mas práticas para transformação radical do eu.", framework: {name: "Protocolos de Transformação", def: "Uso de exercícios espirituais para mudar a percepção.", when: "No design de rotinas de desenvolvimento pessoal.", how: "Identificar paixão a ser curada -> Escolher exercício (meditação, leitura) -> Praticar repetição."}, concept1: {name: "Exercício Espiritual", def: "Prática voluntária para realizar uma transformação de si."}, concept2: {name: "Therapeia", def: "Cura das doenças da alma."}, model1: {name: "Filosofia como Modo de Vida", def: "A vida vivida é o fim da filosofia."}, model2: {name: "Conversão (Epistrophê)", def: "Uma mudança total na forma de ver o mundo."}, anti: {name: "Academicismo Estéril", def: "Estudar conceitos sem aplicá-los na conduta."}, example: "Escrever um diário noturno para auditar as ações do dia.", takeaway1: "A teoria fundamenta a prática terapêutica.", takeaway2: "A transformação exige esforço repetitivo." },
      { id: "02", slug: "dialogos-hadot", title: "Diálogos com Pierre Hadot e Foucault", core: "A intersecção entre a redescoberta de Hadot e a estética da existência de Foucault.", framework: {name: "Análise Comparativa de Práticas", def: "Mapear a diferença entre universalismo e estilização pessoal.", when: "Ao escolher entre regras universais ou ética singular.", how: "Avaliar o modelo estoico vs. o modelo foucaultiano de autopoiese."}, concept1: {name: "Estética da Existência", def: "A vida como uma obra de arte autônoma."}, concept2: {name: "Subjetivação", def: "Tornar-se sujeito através de práticas ativas."}, model1: {name: "Eu Universal vs. Singular", def: "A tensão entre alinhar-se à Razão ou forjar identidade única."}, model2: {name: "Cuidado de Si", def: "Atenção voltada para o próprio desenvolvimento."}, anti: {name: "Narcisismo Vazio", def: "Confundir cuidado rigoroso com culto da individualidade."}, example: "Usar disciplina estoica para emoções, mas estética foucaultiana para carreira.", takeaway1: "Temos o poder de esculpir nossa subjetividade.", takeaway2: "O debate define os limites da ética contemporânea." },
      { id: "03", slug: "estetica-existencia", title: "Ética e Estética da Existência", core: "A união indivisível entre o agir ético (o bem) e a forma de vida (o belo).", framework: {name: "Design da Existência", def: "Estruturar a vida diária como uma obra de arte moral.", when: "Quando a vida entra no piloto automático.", how: "Definir valores estéticos -> Eliminar hábitos desalinhados -> Cultivar novas práticas com rigor."}, concept1: {name: "Autopoiese", def: "A auto-criação do indivíduo."}, concept2: {name: "Ascese", def: "O treinamento prático para dominar a si mesmo."}, model1: {name: "Coerência Discurso-Ação", def: "A beleza está na ausência de hipocrisia."}, model2: {name: "A Vida como Obra de Arte", def: "A biografia deve ter coerência e beleza."}, anti: {name: "Conformismo Moral", def: "Seguir regras cegamente sem forjar um estilo próprio."}, example: "Rejeitar práticas antiéticas porque tornam a 'obra' de sua vida feia.", takeaway1: "A ética é uma escolha estética.", takeaway2: "Você é o autor e o material da transformação." }
    ]
  },
  {
    skill: "faustino-late-foucault",
    chaps: [
      { id: "01", slug: "ethical-turn", title: "The Ethical Turn", core: "Foucault shifts from analyzing power subjection to how individuals constitute themselves ethically.", framework: {name: "Genealogy of Ethics", def: "Analyzing how the relationship to oneself is structured.", when: "Understanding paradigm shifts in personal morality.", how: "Identify moral substance -> Map mode of subjection -> Analyze self-forming activity."}, concept1: {name: "Subjectivation", def: "The active process of forming oneself."}, concept2: {name: "Ethopoiesis", def: "The making of ethos; crafting character."}, model1: {name: "Power vs. Freedom", def: "Ethics is freedom informed by reflection."}, model2: {name: "Care of the Self", def: "Attending to oneself before caring for others."}, anti: {name: "Passive Victimhood", def: "Assuming subjects are entirely determined by power."}, example: "A professional creating their own ethical code in a corrupt industry.", takeaway1: "Ethics is the practice of freedom.", takeaway2: "We craft ourselves through power." },
      { id: "02", slug: "parrhesia", title: "Parrhesia and Truth-Telling", core: "Fearless speech to power at personal risk links truth and subjectivity.", framework: {name: "Parrhesiastic Contract", def: "Agreement to speak truth regardless of consequence.", when: "Evaluating whistleblowing or critique.", how: "Assess risk -> Verify conviction -> Speak directly to superior power."}, concept1: {name: "Parrhesia", def: "Fearless, dangerous truth-telling."}, concept2: {name: "The Risk of Truth", def: "Truth without risk is not parrhesia."}, model1: {name: "Courage over Rhetoric", def: "Valuing stark truth over manipulation."}, model2: {name: "Socratic Gadfly", def: "Duty to sting society into awareness."}, anti: {name: "Flattery", def: "Telling the powerful what they want to hear."}, example: "Subordinate telling CEO the flagship product is flawed, risking their job.", takeaway1: "Truth-telling is tied to personal courage.", takeaway2: "Society requires institutional spaces for parrhesia." },
      { id: "03", slug: "subjectivity-power", title: "Subjectivity and Power", core: "Power is a productive matrix through which subjects navigate and resist.", framework: {name: "Strategic Resistance", def: "Using power mechanisms to forge new forms of life.", when: "Navigating oppressive environments.", how: "Map power relations -> Identify nodes of freedom -> Engage in ascetic practices."}, concept1: {name: "Biopower", def: "Power regulating the life of populations."}, concept2: {name: "Normalization", def: "Coercion to conform to societal standards."}, model1: {name: "Agonistic Struggle", def: "Dynamic tension between power and resistance."}, model2: {name: "Aesthetics of Existence", def: "Creating a uniquely crafted life to resist normalization."}, anti: {name: "Totalitarian Despair", def: "Believing resistance is impossible."}, example: "LGBTQ+ creating new kinship structures to resist biopower.", takeaway1: "Where there is power, there is resistance.", takeaway2: "The self is the ultimate battleground." }
    ]
  },
  {
    skill: "fiordalis-buddhist-spiritual-practices",
    chaps: [
      { id: "01", slug: "meditation-traditions", title: "Meditation and Mindfulness Traditions", core: "Meditation is a structured technology for cognitive restructuring and awakening.", framework: {name: "Samatha-Vipassana Matrix", def: "Combining calming and insight meditation.", when: "Cultivating focus and understanding of reality.", how: "Use Samatha to stabilize mind -> Use Vipassana to analyze phenomena."}, concept1: {name: "Samatha", def: "Tranquility and concentration."}, concept2: {name: "Vipassana", def: "Insight into true nature."}, model1: {name: "Monkey Mind", def: "Restless, untamed consciousness."}, model2: {name: "The Observer Effect", def: "Watching thoughts without identifying."}, anti: {name: "Meditation as Relaxation", def: "Reducing ancient awakening to stress-relief."}, example: "Using breath focus to calm anxiety, then Vipassana to realize it's transient.", takeaway1: "Concentration is prerequisite for liberating insight.", takeaway2: "Mindfulness is active investigation." },
      { id: "02", slug: "asceticism-discipline", title: "Asceticism and Monastic Discipline", core: "Monastic rules (Vinaya) form the ethical container necessary for spiritual progress.", framework: {name: "Vinaya Structuring", def: "Using strict external rules to generate internal freedom.", when: "Designing environments for habit reformation.", how: "Identify distractions -> Implement absolute prohibitions -> Rely on community."}, concept1: {name: "Vinaya", def: "Monastic code of discipline."}, concept2: {name: "Dhutanga", def: "Optional austere practices."}, model1: {name: "Constraint breeds Freedom", def: "Removing choices eliminates decision fatigue."}, model2: {name: "The Middle Way", def: "Balancing extreme asceticism with indulgence."}, anti: {name: "Self-Mortification", def: "Torturing the body pointlessly."}, example: "Implementing a 'digital monk' protocol with absolute prohibition of social media.", takeaway1: "External discipline creates scaffolding for internal liberation.", takeaway2: "Ethical conduct is the foundation." },
      { id: "03", slug: "wisdom-cultivation", title: "Wisdom and Ethical Cultivation", core: "Wisdom (Prajna) cuts through the ignorance that causes suffering.", framework: {name: "The Threefold Training", def: "Integrated path of ethics, meditation, and wisdom.", when: "Designing a holistic system for human flourishing.", how: "Establish Sila -> Cultivate Samadhi -> Develop Prajna to see emptiness."}, concept1: {name: "Prajna", def: "Direct, non-conceptual wisdom."}, concept2: {name: "Sunyata", def: "Emptiness; lack of inherent existence."}, model1: {name: "Interdependent Origination", def: "Everything exists only in relation to everything else."}, model2: {name: "Raft Analogy", def: "Teachings are tools to be discarded once across."}, anti: {name: "Dogmatic Attachment", def: "Clinging to teachings as absolute truths."}, example: "Realizing a business failure is 'empty' of inherent badness.", takeaway1: "Ignorance, not sin, is the root of suffering.", takeaway2: "Wisdom is the experiential realization of interconnectedness." }
    ]
  },
  {
    skill: "foucault-hermeneutica-do-sujeito",
    chaps: [
      { id: "01", slug: "cuidado-de-si", title: "Cuidado de Si vs. Conhecimento de Si", core: "O 'Cuidar de Si' precedia o 'Conhecer a Si Mesmo', relação que a modernidade inverteu.", framework: {name: "Primazia do Cuidado", def: "Transformação prática antes do autoconhecimento teórico.", when: "Ao tentar mudar hábitos em vez de análise interminável.", how: "Identificar objetivo -> Aplicar exercícios (ascese) -> Conhecimento emerge."}, concept1: {name: "Epimeleia Heautou", def: "Atenção e ocupação consigo mesmo."}, concept2: {name: "Gnôthi Seauton", def: "Conhece-te a ti mesmo."}, model1: {name: "Momento Cartesiano", def: "O erro de achar que a verdade não exige mudar o sujeito."}, model2: {name: "Sujeito da Verdade", def: "O sujeito deve ser modificado para ter direito à verdade."}, anti: {name: "Intelectualismo Estéril", def: "Acreditar que entender a causa do trauma o cura."}, example: "Praticar meditação e diário para forjar caráter, em vez de apenas ler livros.", takeaway1: "A verdade exige um custo: a transformação.", takeaway2: "A prática precede a teoria." },
      { id: "02", slug: "praticas-antigas", title: "Práticas e Técnicas de Si na Antiguidade", core: "O detalhamento dos 'tecnologias do eu' usadas para blindar a alma.", framework: {name: "Arsenal Ascético", def: "Técnicas para preparar o indivíduo para a adversidade.", when: "Preparação para crises e luto.", how: "Praticar meditatio mortis -> Exame de consciência -> Retiro para si."}, concept1: {name: "Praemeditatio Malorum", def: "Visualização dos piores cenários."}, concept2: {name: "Anachôrêsis", def: "O retiro espiritual para dentro da mente."}, model1: {name: "Atleta da Alma", def: "Treinamento moral exige repetição."}, model2: {name: "Memória como Recurso", def: "Armazenar dogmas prontos para a crise."}, anti: {name: "Reatividade Passiva", def: "Esperar a crise para gerenciar emoções."}, example: "Treinar a mente imaginando a falência de um projeto.", takeaway1: "Resiliência é habilidade treinável.", takeaway2: "A mente precisa de equipamentos prontos." },
      { id: "03", slug: "direcao-consciencia", title: "A Conversão a Si Mesmo", core: "O objetivo final é a conversão total a si próprio, alcançando a autossuficiência.", framework: {name: "Círculo da Conversão", def: "O movimento de voltar-se para a posse plena de si.", when: "Quando sofrendo de burnout ou dependência de aprovação.", how: "Desligar dependências -> Voltar olhar para interior -> Fixar residência em si."}, concept1: {name: "Conversio ad Se", def: "A mudança do olhar para o dentro."}, concept2: {name: "Stultitia", def: "A dispersão do tolo voltado para os outros."}, model1: {name: "Eu como Porto Seguro", def: "Fortaleza interior invulnerável."}, model2: {name: "Alegria (Gaudium)", def: "O prazer inabalável da posse de si mesmo."}, anti: {name: "Distração Crônica", def: "A fuga de si mesmo através de estímulos."}, example: "Cortar redes sociais para curar a Stultitia no silêncio.", takeaway1: "A salvação é a libertação da dependência do outro.", takeaway2: "A maior alegria é encontrar prazer na própria existência." }
    ]
  },
  {
    skill: "foucault-historia-da-sexualidade-2",
    chaps: [
      { id: "01", slug: "uso-dos-prazeres", title: "O Uso dos Prazeres e a Moralidade", core: "A moral grega era baseada na estilização do uso, não em proibições universais.", framework: {name: "Análise da Chresis", def: "Avaliar o comportamento pela quantidade e oportunidade.", when: "Ao desenhar sistemas de moderação de comportamento.", how: "Definir momento (kairos) -> Estabelecer proporção -> Avaliar status."}, concept1: {name: "Chresis Aphrodision", def: "O uso correto dos prazeres sexuais."}, concept2: {name: "Sophrosyne", def: "A moderação e autodomínio."}, model1: {name: "Moral do Estilo", def: "A diferença entre esculpir um caráter e obedecer a um código."}, model2: {name: "Risco da Passividade", def: "Ser escravizado pelos próprios desejos."}, anti: {name: "Puritanismo Legalista", def: "Aplicar códigos de proibição à ética da moderação."}, example: "Comer excesso de açúcar demonstra falta de Sophrosyne, não um 'pecado' legal.", takeaway1: "A ética clássica é uma arte do autodomínio.", takeaway2: "A verdadeira liberdade exige o domínio sobre os instintos." },
      { id: "02", slug: "dietetica", title: "A Dietética e o Corpo", core: "A dietética como gestão integral do regime de vida para manter o equilíbrio.", framework: {name: "Regime de Vida Integral", def: "Gestão holística da energia.", when: "No design de rotinas de alta performance.", how: "Monitorar clima -> Ajustar ingestão/exercício -> Regular atividade sexual."}, concept1: {name: "Diaita", def: "O conjunto do estilo de vida."}, concept2: {name: "Equilíbrio dos Humores", def: "A saúde como proporção perfeita."}, model1: {name: "O Corpo Poroso", def: "Corpo vulnerável em troca com o ambiente."}, model2: {name: "A Fadiga como Risco", def: "O desgaste excessivo como via para doença."}, anti: {name: "Medicalização Segmentada", def: "Tratar a doença ignorando o regime completo."}, example: "Ajustar treino e sono de acordo com estresse do trabalho.", takeaway1: "Saúde requer micro-gerenciamento do cotidiano.", takeaway2: "Atos físicos têm custo energético global." },
      { id: "03", slug: "erotica", title: "A Erótica e o Amor Pelos Rapazes", core: "A pederastia apresentava um problema ético complexo de honra, status e poder.", framework: {name: "Análise de Poder Relacional", def: "Mapear a tensão em relações de mentoria.", when: "Avaliando dinâmicas de poder hierárquicas.", how: "Identificar polo dominante -> Mapear polo passivo -> Garantir geração de virtude."}, concept1: {name: "Erastes e Eromenos", def: "Amante mais velho e jovem amado."}, concept2: {name: "Aporia Moral", def: "Paradoxo de resistir pela honra e ceder para aprender."}, model1: {name: "O Amor como Pedagogia", def: "Transmissão da excelência masculina."}, model2: {name: "Ameaça da Feminilização", def: "O medo de que o jovem se tornasse inapto para o poder."}, anti: {name: "Leitura Contemporânea Simplista", def: "Analisar apenas por conceitos modernos de abuso."}, example: "A complexa dança de corte onde ceder rápido era vergonhoso.", takeaway1: "Relações eróticas são codificadas por dinâmicas de poder.", takeaway2: "A pedagogia grega estava ligada à tensão erótica." }
    ]
  },
  {
    skill: "foucault-technologies-of-the-self",
    chaps: [
      { id: "01", slug: "technologies-production", title: "Technologies of Production, Sign, Power, and Self", core: "Human action categorizes into four technologies: production, sign, power, and self.", framework: {name: "Four Technologies Matrix", def: "Categorizing systems by operational modality.", when: "Analyzing institutions or cultural practices.", how: "Determine if it modifies nature -> Communicates meaning -> Controls behavior -> Enhances inner state."}, concept1: {name: "Technologies of Power", def: "Systems determining conduct of individuals."}, concept2: {name: "Technologies of the Self", def: "Operations allowing individuals to effect changes in themselves."}, model1: {name: "Interface of Power and Self", def: "Intersection where power dictates self-care."}, model2: {name: "Matrix of Action", def: "Every action blends these four technologies."}, anti: {name: "Technological Determinism", def: "Ignoring that humans actively use 'Self' technologies to resist."}, example: "A corporate wellness app uses Sign, Power, and Self technologies.", takeaway1: "Control requires analyzing power and self-discipline intersection.", takeaway2: "We are shaped by both external domination and internal fashioning." },
      { id: "02", slug: "self-examination", title: "Stoic vs. Christian Self-Examination", core: "The shift from Stoic memory of rules to Christian suspicion of hidden desires.", framework: {name: "Comparative Examination Protocol", def: "Contrasting methods of internal auditing.", when: "Designing feedback systems.", how: "Stoic: Review actions against rules. Christian: Interrogate inner thoughts for corruption."}, concept1: {name: "Stoic Audit", def: "Checking actions against the dichotomy of control."}, concept2: {name: "Christian Hermeneutics", def: "Deciphering the self to find hidden illusions."}, model1: {name: "Self as a Fortress", def: "Protecting inner citadel from impressions."}, model2: {name: "Self as a Text", def: "Endlessly interpreting the self's hidden depths."}, anti: {name: "Conflating Introspection", def: "Assuming ancient reflection is modern psychoanalysis."}, example: "A Stoic notes the error in impulse; a Christian searches for subconscious self-sabotage.", takeaway1: "How we examine ourselves dictates our subjectivity.", takeaway2: "Modern obsession with the 'hidden true self' is Christian asceticism." },
      { id: "03", slug: "confession", title: "Confession and Truth Games", core: "The obligation to confess to authority is a primary mechanism of subjectivation.", framework: {name: "Confessional Apparatus", def: "Analyzing systems that extract truth from subjects.", when: "Evaluating data surveillance or management.", how: "Identify authority -> Analyze pressure to disclose -> Observe how confession solidifies identity."}, concept1: {name: "Exagoreusis", def: "Continuous verbalization of thoughts to a master."}, concept2: {name: "Truth Games", def: "Specific rules distinguishing true and false in a society."}, model1: {name: "Price of Truth", def: "Confession requires renunciation of the self."}, model2: {name: "Talking Cure", def: "Modern belief that speaking hidden truth brings liberation."}, anti: {name: "Confession as Pure Liberation", def: "Failing to see that confessing subjects you to power."}, example: "Social media operates as a secular confessional technology to an algorithmic authority.", takeaway1: "Telling the truth binds one to the power structure receiving it.", takeaway2: "Confession is the engine of Western subjectivity." }
    ]
  },
  {
    skill: "franz-sonhos-estudo",
    chaps: [
      { id: "01", slug: "estrutura", title: "A Estrutura e Linguagem dos Sonhos", core: "Os sonhos são manifestações autônomas do inconsciente, muitas vezes estruturados como um drama em quatro atos.", framework: {name: "Análise Dramática do Sonho", def: "Mapear o sonho como uma peça de teatro.", when: "Ao tentar decodificar a mensagem central de um sonho longo.", how: "1. Exposição -> 2. Desenvolvimento da trama -> 3. Clímax/Crise -> 4. Lise (resultado)."}, concept1: {name: "Compensação", def: "O sonho equilibra atitudes conscientes unilaterais."}, concept2: {name: "Associação Dirigida", def: "Conectar símbolos ao contexto do sonhador sem perder o foco na imagem."}, model1: {name: "O Inconsciente Direto", def: "O sonho não esconde, ele mostra o que é através de símbolos."}, model2: {name: "Linguagem Analógica", def: "Sonhos usam metáforas visuais, não lógica linear."}, anti: {name: "Dicionário de Símbolos Fixo", def: "Acreditar que os símbolos têm um único significado universal."}, example: "Um executivo arrogante sonhando que está nu revela vulnerabilidade compensatória.", takeaway1: "O sonho é um corretivo natural da psique.", takeaway2: "A estrutura narrativa contém a chave para a resolução." },
      { id: "02", slug: "arquetipos", title: "Motivos Arquetípicos", core: "Os sonhos acessam o Inconsciente Coletivo, trazendo símbolos mitológicos universais.", framework: {name: "Amplificação Arquetípica", def: "Expandir o significado de um símbolo através do mito.", when: "Quando o sonho apresenta imagens grandiosas ou bizarras.", how: "Identificar símbolo estranho -> Buscar paralelos míticos -> Aplicar lição universal."}, concept1: {name: "Inconsciente Coletivo", def: "Camada profunda da psique comum à humanidade."}, concept2: {name: "Sombra", def: "Parte da personalidade reprimida."}, model1: {name: "Anima/Animus", def: "Contraparte feminina/masculina mediadora."}, model2: {name: "O Self", def: "Centro totalizador da psique."}, anti: {name: "Reducionismo Pessoal", def: "Tentar explicar sonhos grandiosos apenas através de traumas de infância."}, example: "Sonhar com um dragão protegendo tesouro simboliza enfrentar o medo para obter energia psíquica.", takeaway1: "Nossa mente contém a herança mitológica da humanidade.", takeaway2: "Símbolos arquetípicos trazem energia vitalizadora." },
      { id: "03", slug: "sonhos-morte", title: "Sonhos de Morte e Transformação", core: "Sonhos de morte simbolizam o fim de uma atitude ou fase para o renascimento psíquico.", framework: {name: "Interpretação Alquímica da Morte", def: "Ler a destruição como pré-requisito para transformação.", when: "Ao lidar com mudanças drásticas ou perdas.", how: "Identificar o que está morrendo -> Relacionar à atitude obsoleta -> Focar no símbolo de renascimento."}, concept1: {name: "Nigredo", def: "Fase alquímica de escurecimento e morte psíquica."}, concept2: {name: "Morte como Iniciação", def: "Sacrifício do ego para a emergência do Self."}, model1: {name: "Ciclo Vida/Morte/Vida", def: "Nada termina absolutamente, apenas muda de forma."}, model2: {name: "Casamento Místico", def: "União dos opostos após a dissolução."}, anti: {name: "Pânico Literal", def: "Interpretar o sonho de morte como premonição literal."}, example: "A casa desmoronando no sonho é o inconsciente destruindo uma antiga estrutura de crenças.", takeaway1: "A morte no sonho é uma metáfora psíquica de renovação.", takeaway2: "Resistir à destruição psíquica apenas prolonga o sofrimento." }
    ]
  }
];

data.forEach(skill => {
  const skillPath = path.join(basePath, skill.skill);
  const chaptersPath = path.join(skillPath, 'chapters');
  
  if (!fs.existsSync(skillPath)) fs.mkdirSync(skillPath, { recursive: true });
  if (!fs.existsSync(chaptersPath)) fs.mkdirSync(chaptersPath, { recursive: true });

  let indexLines = [];

  skill.chaps.forEach(chap => {
    const filePath = path.join(chaptersPath, `ch${chap.id}-${chap.slug}.md`);
    fs.writeFileSync(filePath, template(chap), 'utf8');
    indexLines.push(`- [${chap.title}](chapters/ch${chap.id}-${chap.slug}.md)`);
  });

  const skillMdPath = path.join(skillPath, 'SKILL.md');
  const indexText = `## Chapter Index\n\n` + indexLines.join('\n');
  
  if (fs.existsSync(skillMdPath)) {
    let skillMd = fs.readFileSync(skillMdPath, 'utf8');
    if (skillMd.includes('## Chapter Index')) {
      skillMd = skillMd.replace(/## Chapter Index[\s\S]*/, indexText);
    } else {
      skillMd += `\n\n${indexText}`;
    }
    fs.writeFileSync(skillMdPath, skillMd, 'utf8');
  } else {
    fs.writeFileSync(skillMdPath, `---\nname: ${skill.skill}\ndescription: Book to skill adaptation\n---\n\n${indexText}`, 'utf8');
  }
});
console.log("Geracao concluida com sucesso!");
