# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para a linguística textual de
Beaugrande & Dressler (Introduction to Text Linguistics) + os mecanismos de
coesão de Halliday & Hasan. Os 7 critérios de textualidade e as 5 coesões."""

BOOK = {
 "title": "Coesão e Coerência",
 "author": "Beaugrande, Dressler & Halliday",
 "header_light": "COESÃO E",
 "header_bold": "COERÊNCIA",
 "subtitle": "VISÃO GERAL · OS 7 CRITÉRIOS DA TEXTUALIDADE",
 "intro": "Quando é que palavras enfileiradas viram <em>texto</em>? Não é a gramática que decide. Beaugrande & Dressler mostram que o texto é uma <strong>tessitura</strong> — fios que se entrelaçam — e que essa trama só se mantém se cumprir sete critérios. Dois cuidam do tecido: a <strong>coesão</strong> amarra as palavras à vista; a <strong>coerência</strong> amarra os sentidos na cabeça de quem lê. Os outros cinco cuidam do uso: ninguém escreve no vácuo, escreve para alguém, numa situação, herdando outros textos. Some um critério e o pano desfia. Esta é a régua para apalpar exatamente <em>onde</em> o texto rasgou.",
 "description": "A linguística do texto de Beaugrande & Dressler — os 7 critérios que transformam frases soltas em tessitura — somada aos 5 fios de coesão de Halliday & Hasan. No tecido: coesão (a superfície amarrada) e coerência (o sentido contínuo). No uso: intencionalidade, aceitabilidade, informatividade, situacionalidade, intertextualidade. Um mapa para ler por que um texto se sustenta — ou se rompe.",
 "tags": ["Língua", "Texto", "Redação"],
 "progress": "9 Capítulos",
 "cover": "assets/coesao-coerencia-cover.png",
 "overview_cards": [
   {"ic":"layers","t":"Os 7 Critérios de Textualidade","b":"Textualidade é uma soma de condições, não um talento. Duas olham para o tecido — <strong>coesão</strong> e <strong>coerência</strong>; cinco olham para o uso — <strong>intencionalidade, aceitabilidade, informatividade, situacionalidade e intertextualidade</strong>. São sete travas: enquanto todas seguram, há texto; quando uma cede, há só palavras juntas.","tip":"<strong>Como aplicar:</strong> diante de algo que 'não soa como texto', não conserte tudo — descubra qual das sete travas cedeu.","wide":True},
   {"ic":"link","t":"Coesão é o tecido · Coerência é o sentido","b":"A <strong>coesão</strong> costura o que está à vista — pronomes, conectores, repetições. A <strong>coerência</strong> costura o que está na cabeça de quem lê — as ideias sem buraco nem contradição. Por isso existe o texto amarradíssimo e sem pé nem cabeça, e o texto frouxo que ainda assim faz todo sentido.","tip":"<strong>Chave:</strong> a gramática garante a costura; só a coerência garante o sentido. O veredito final é dela."},
   {"ic":"key","t":"Os 5 Fios da Coesão","b":"Cinco modos de amarrar sem repetir: <strong>referência</strong> (ele, este, aquilo aponta), <strong>substituição</strong> (uma forma curta no lugar), <strong>elipse</strong> (o silêncio que o leitor preenche), <strong>conjunção</strong> (mas, porque, então sinalizam a relação) e <strong>coesão lexical</strong> (sinônimo, campo semântico que se reconhecem). Quatro escrevem; um, a elipse, cala.","tip":"<strong>Modelo mental:</strong> todo fio só amarra se a outra ponta — o referente — for achável. O pronome sem dono é o nó solto nº 1."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-textualidade","sub":"CAPÍTULO 1: O Que É Um Texto — Os 7 Critérios",
  "intro":"Há frases impecáveis que não formam texto e bilhetes torcidos que formam. A diferença não está na gramática: está em sete travas. Texto não é o tamanho da frase nem a soma das orações — é uma ocorrência que comunica, e só conta como tal quando os sete critérios de textualidade seguram juntos.",
  "cards":[
      {"ic":"layers","t":"As Sete Travas","emph":"sete","b":"Duas miram o tecido — <strong>coesão</strong> (a superfície amarrada) e <strong>coerência</strong> (o sentido contínuo); cinco miram o uso — <strong>intencionalidade, aceitabilidade, informatividade, situacionalidade e intertextualidade</strong>. Não é uma escala de notas: é uma corrente, e ela tem a força do elo mais fraco.","tip":"<strong>Como aplicar:</strong> não se pergunta 'está bom?', e sim 'qual das sete cedeu?'. O diagnóstico precede o conserto.","wide":True},
      {"ic":"bubble","t":"O Texto É Evento","emph":"evento","b":"Texto não é coisa parada na página — <strong>acontece</strong>, entre alguém que diz e alguém que recebe, numa situação concreta. A pergunta certa não é 'está correto?', mas 'o que ele fez acontecer?'. Mede-se pela comunicação que realiza, não pela frase no vidro do laboratório.","tip":"<strong>Modelo mental:</strong> verbo, não substantivo. O texto se faz no momento em que é usado, e desfaz-se fora dele."},
      {"ic":"gap","t":"Correto Não É Coeso","emph":"Correto","b":"Frases certinhas e <strong>desligadas umas das outras</strong> não viram texto — viram lista. E examinar o texto longe da sua situação afere só metade da régua: a outra metade está no uso.","tip":"<strong>Cuidado:</strong> não persiga nota dez nos sete critérios. Eles se equilibram entre si; maximizar um custa os outros.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Texto é ocorrência que comunica — não frase grande nem fila de orações.","Sete critérios em corrente: coesão e coerência (o tecido) + cinco do uso. Vale o elo mais fraco.","Quando algo 'não soa como texto', não conserte tudo: descubra qual das sete travas cedeu."]},

 {"slug":"ch02-coesao-referencia","sub":"CAPÍTULO 2: Coesão I — Referência, Substituição, Elipse",
  "intro":"Repetir o nome inteiro a cada linha cansa e quebra o fio. Por isso a língua inventou três economias para retomar o que já está dito sem dizê-lo de novo: apontar, encurtar e calar. São os três primeiros fios da coesão — e todos vivem da mesma promessa: o leitor há de recuperar o que ficou de fora.",
  "cards":[
      {"ic":"link","t":"Referência: a Seta","emph":"Referência","b":"Em vez de renomear, uma forma <strong>aponta</strong> — pronome, demonstrativo, artigo: 'ele', 'este', 'o tal'. A seta vai para trás (<strong>anáfora</strong>, retoma o já dito) ou para a frente (<strong>catáfora</strong>, anuncia o que vem). É a cadeia que mantém o assunto vivo de frase em frase.","tip":"<strong>Como aplicar:</strong> todo pronome é uma dívida — promete um antecedente claro. Se o credor não acha o referente, a coesão calota.","wide":True},
      {"ic":"pivot","t":"Trocar e Calar","emph":"Calar","b":"A <strong>substituição</strong> põe uma forma curta no lugar do item ('quero a azul, não a <em>outra</em>'); a <strong>elipse</strong> não põe nada — omite o que se recupera ('Eu [quero]'). A elipse é a substituição pelo zero: amarra com silêncio, e às vezes o silêncio amarra melhor que a palavra.","tip":"<strong>Modelo mental:</strong> trocar e calar só funcionam se a reconstrução for grátis. Se obriga o leitor a voltar e garimpar, virou pedágio."},
      {"ic":"gap","t":"O Pronome Sem Dono","emph":"Sem Dono","b":"'João disse a Pedro que <strong>ele</strong> errou' — ele quem? A seta aponta para dois alvos e não acerta nenhum. A ambiguidade referencial é o defeito de coesão <strong>mais comum</strong> da prosa — e o mais fácil de não ver, porque o autor sabe quem é 'ele'.","tip":"<strong>Cuidado:</strong> referente longe demais também solta o fio. Entre o pronome e seu dono não cabe um parágrafo inteiro.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["Três economias para retomar: a referência aponta, a substituição encurta, a elipse cala.","A cadeia referencial mantém o assunto vivo — e o pronome sem dono é o nó solto nº 1.","Toda retomada é um empréstimo: só vale enquanto o leitor recupera o que ficou de fora, sem esforço."]},

 {"slug":"ch03-coesao-conjuncao-lexical","sub":"CAPÍTULO 3: Coesão II — Conjunção e Coesão Lexical",
  "intro":"Retomar não basta: o leitor também precisa saber como uma ideia se liga à outra. Os dois últimos fios cuidam disso por caminhos opostos — a conjunção amarra pela lógica explícita (mas, porque, então) e a coesão lexical amarra, em surdina, pela própria escolha das palavras.",
  "cards":[
      {"ic":"steps","t":"Conjunção: a Placa","emph":"Conjunção","b":"São as palavrinhas que <strong>declaram a relação</strong> entre as partes: aditiva ('e' — soma), adversativa ('mas' — vira), causal ('porque' — funda), temporal ('então' — ordena), conclusiva ('portanto' — fecha). O conectivo é a placa de trânsito do raciocínio: diz se a frase confirma, contradiz ou conclui a anterior.","tip":"<strong>Como aplicar:</strong> leia só os conectivos de um parágrafo. Se a sequência deles já conta a lógica do texto, a costura está firme.","wide":True},
      {"ic":"constellation","t":"Coesão Lexical: a Família","emph":"lexical","b":"Aqui a amarra é silenciosa, feita do próprio vocabulário — <strong>reiteração</strong> (repetir, trocar por sinônimo ou por palavra mais geral) e <strong>colocação</strong> (termos do mesmo <strong>campo semântico</strong> que andam juntos: 'médico', 'febre', 'remédio'). As palavras de um bom texto parecem se reconhecer.","tip":"<strong>Modelo mental:</strong> num texto coeso, as palavras são de uma mesma família. Quando uma estranha entra, o leitor sente o intruso antes de saber por quê."},
      {"ic":"gap","t":"A Placa Trocada","emph":"Trocada","b":"'Mas' onde a relação era causa, 'portanto' sem premissa que o sustente: a placa errada manda o leitor para a saída errada. E o oposto também trava — 'aí, então, daí, aí' em cada linha vira ruído, placa de mais escondendo a estrada.","tip":"<strong>Cuidado:</strong> mudar de campo semântico sem transição faz o texto 'pular de assunto' — o leitor cai no buraco entre dois parágrafos que não se cumprimentaram.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["A conjunção declara a relação: soma, vira, funda, ordena, fecha. É a placa do raciocínio.","A coesão lexical amarra em surdina, por reiteração e colocação — as palavras da mesma família se reconhecem.","Conectivo errado, ou em excesso, desorienta tanto quanto a falta dele: a placa trocada é pior que nenhuma."]},

 {"slug":"ch04-coerencia","sub":"CAPÍTULO 4: Coerência — A Continuidade de Sentidos",
  "intro":"A coesão amarra o que se vê; a coerência amarra o que se entende. É a continuidade dos sentidos — o que permite ao leitor levantar, frase a frase, um mundo textual que se sustenta de pé. E eis o segredo: boa parte desse mundo não está na página. Está sendo construída na cabeça de quem lê.",
  "cards":[
      {"ic":"constellation","t":"O Mundo Não Está Todo Escrito","emph":"inferência","b":"Coerência é a <strong>estabilidade</strong> do mundo que o texto acende na mente — conceitos que se encaixam, sem buraco nem contradição. E a maior parte dele chega por <strong>inferência</strong>: o leitor preenche o que o texto, de propósito, não disse. Quem escreve não entrega o mundo pronto; entrega pistas para que o outro o monte.","tip":"<strong>Como aplicar:</strong> a coerência mora na cabeça do leitor. O texto não a contém — apenas a provoca, ou a frustra.","wide":True},
      {"ic":"layers","t":"O Roteiro do Restaurante","emph":"frames","b":"A mente traz prateleiras de conhecimento prévio — <strong>frames</strong> e <strong>scripts</strong>: diga 'restaurante' e já vêm mesa, garçom, conta, sem ninguém explicar. O texto apenas <strong>aciona</strong> essas estruturas; o leitor faz o resto. É a economia do óbvio — escrever o que falta, não o que já se sabe.","tip":"<strong>Modelo mental:</strong> o sentido é uma rede, não uma fila. Cada palavra puxa um nó de tudo o que o leitor já sabe."},
      {"ic":"gap","t":"O Buraco e a Batida","emph":"buraco","b":"Dois modos de quebrar o mundo: <strong>pular uma etapa</strong> que o leitor não consegue inferir — abre-se um buraco no chão; ou <strong>afirmar o que bate de frente</strong> com o que já foi dito — o mundo treme e desaba. O leitor não vê o erro na frase: sente que parou de fazer sentido.","tip":"<strong>Cuidado:</strong> existe texto coeso e incoerente — todo amarrado, sem nada por dentro. A coerência é a prova final, acima da gramática.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["Coerência é a continuidade dos sentidos — a estabilidade do mundo textual de pé.","Ela é co-construída por inferência: o leitor preenche, com seus esquemas, o que o texto cala.","Coesão não garante coerência. Amarrar não é fazer sentido — e o sentido é a última palavra."]},

 {"slug":"ch05-intencionalidade-aceitabilidade","sub":"CAPÍTULO 5: Intencionalidade e Aceitabilidade",
  "intro":"Aqui o texto deixa de ser tecido e vira gente. Dois critérios olham para as duas pontas da comunicação: a vontade de quem produz e a boa vontade de quem recebe. Entre as duas há um pacto — e é o pacto, não as palavras, que faz a mensagem chegar.",
  "cards":[
      {"ic":"target","t":"Intencionalidade: a Vontade","emph":"Intencionalidade","b":"Antes da primeira palavra, alguém <strong>quer</strong> que aquilo seja texto — coeso, coerente, a serviço de um plano: informar, convencer, comover. O texto não cai do céu; é instrumento de um propósito humano. Onde não se enxerga a intenção, o leitor pressente abandono e larga.","tip":"<strong>Como aplicar:</strong> antes de escrever, declare a si mesmo o que este texto deve <em>fazer</em> com quem o ler. Sem alvo, não há acerto.","wide":True},
      {"ic":"bubble","t":"Aceitabilidade: a Boa Vontade","emph":"Aceitabilidade","b":"Do outro lado, o leitor se dispõe a <strong>colaborar</strong> — tapa lacunas, releva um tropeço, vai junto — desde que sinta ali relevância e proveito. Ler é um ato cooperativo: o sentido não é transmitido pronto, é negociado a cada frase. Sem essa boa vontade, nenhum texto se completa.","tip":"<strong>Modelo mental:</strong> comunicação não é transmissão, é cooperação. Você escreve metade; o leitor escreve a outra metade."},
      {"ic":"gap","t":"Escrever de Costas","emph":"costas","b":"Escrever para si mesmo, de costas para quem recebe, derruba a aceitabilidade — e abusar da paciência alheia (tropeço atrás de tropeço) faz o leitor <strong>desistir de cooperar</strong>. A boa vontade é um crédito que se gasta: queime-o e o resto, por mais correto, vai para o lixo sem ser lido.","tip":"<strong>Cuidado:</strong> a mesma mensagem muda de forma conforme quem a recebe. Escrever bem é escrever para alguém — nunca para ninguém.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Intencionalidade: alguém quer que aquilo seja texto, com um propósito. Sem alvo, não há acerto.","Aceitabilidade: o leitor coopera enquanto vê relevância — e o sentido se negocia, não se transmite.","Texto é pacto entre duas vontades. Calibre-o para quem vai aceitá-lo, ou escreva de costas para ninguém."]},

 {"slug":"ch06-informatividade","sub":"CAPÍTULO 6: Informatividade",
  "intro":"Todo texto caminha numa corda bamba entre o que o leitor já espera e o que ainda não imaginou. Cair para o lado do esperado é entediar; cair para o lado do inesperado é exigir esforço demais. Informatividade é a arte de não cair de nenhum dos dois.",
  "cards":[
      {"ic":"scale","t":"As Três Ordens","emph":"três ordens","b":"A novidade chega em graus. <strong>1ª ordem</strong>: o trivial, o que já se sabia — entedia e o olho pula. <strong>2ª ordem</strong>: o ponto certo, informa sem sufocar — é onde se quer estar. <strong>3ª ordem</strong>: o tão inesperado que custa caro decifrar — pode deslumbrar ou perder o leitor de vez.","tip":"<strong>Como aplicar:</strong> mire sempre a 2ª ordem. O tédio e o caos são os dois vizinhos do fracasso — um de cada lado da porta.","wide":True},
      {"ic":"spark","t":"Surpreenda, mas Dê a Chave","emph":"Chave","b":"A quebra de expectativa só vira ouro quando o leitor <strong>acha a razão dela</strong> — quando a novidade, depois do espanto, se encaixa e ilumina. Surpresa sem chave é só ruído; surpresa motivada é descoberta. Esperado garante a compreensão; novo garante o interesse: o bom texto entrega os dois.","tip":"<strong>Modelo mental:</strong> a surpresa boa faz o leitor pensar 'claro!' — não 'como assim?'. A chave vem logo atrás do susto."},
      {"ic":"gap","t":"Liso ou Empedrado","emph":"Empedrado","b":"Repetir o que o público já domina (1ª ordem) deixa o texto liso — o olho escorrega e some. Empilhar novidade sem âncora (3ª ordem sem chave) deixa-o empedrado — o leitor tropeça e <strong>se perde</strong>. Densidade plana, sem picos nem vales, também não prende ninguém.","tip":"<strong>Cuidado:</strong> não basta ser denso — é preciso ter relevo. Texto sem alto nem baixo é estrada reta de madrugada: dá sono.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Informatividade é a corda bamba entre o esperado e o novo — e o alvo é a 2ª ordem.","1ª ordem entedia e escorrega; 3ª ordem sem chave afasta. O fracasso espreita os dois extremos.","A surpresa funciona quando é motivada: o leitor acha a razão e a novidade vira descoberta."]},

 {"slug":"ch07-situacionalidade","sub":"CAPÍTULO 7: Situacionalidade",
  "intro":"Nenhum texto flutua no ar. Ele aterrissa numa situação — um lugar, uma hora, um canal, um público — e é essa situação que decide se ele é relevante ou supérfluo. A situacionalidade é o critério que cobra: você está dizendo a coisa certa, aqui, agora?",
  "cards":[
      {"ic":"pin","t":"O Contexto Já Diz Metade","emph":"metade","b":"São os fatores que tornam o texto <strong>relevante ao seu momento</strong>. O contexto carrega sentido que as palavras nem precisam repetir, e desenha a fronteira do que pode ficar subentendido. <strong>'Cuidado, degrau'</strong> é texto inteiro diante do degrau — e mero fragmento numa folha solta.","tip":"<strong>Como aplicar:</strong> antes de explicar, pergunte o que a situação já está dizendo. Repetir o óbvio do contexto é gastar fôlego à toa.","wide":True},
      {"ic":"pivot","t":"Espelho ou Alavanca","emph":"Alavanca","b":"Um texto pode apenas <strong>refletir</strong> a situação como ela é (monitorar — narrar, descrever, registrar) ou <strong>agir para mudá-la</strong> (gerenciar — ordenar, pedir, persuadir). Saber qual dos dois você quer ser muda cada escolha de palavra: o espelho informa; a alavanca move.","tip":"<strong>Modelo mental:</strong> texto certo no lugar errado é texto errado. Relevância é uma propriedade do encontro, não da frase."},
      {"ic":"gap","t":"Roupa Errada para a Ocasião","emph":"Errada","b":"Falar num story como quem redige tese, ou numa tese como quem manda áudio — é <strong>desajuste de situação</strong>, e o leitor estranha antes de discordar. E martelar o que o próprio contexto já grita só acrescenta ruído por cima do recado.","tip":"<strong>Cuidado:</strong> um texto irrelevante à situação fracassa mesmo coeso e coerente — perfeito, e fora de lugar.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["Situacionalidade é a relevância do texto para a hora, o lugar e o canal em que aterrissa.","O contexto já diz metade: ele carrega sentido e cobra a roupa certa para a ocasião.","Texto irrelevante à situação falha mesmo coeso e coerente — perfeito e fora de lugar."]},

 {"slug":"ch08-intertextualidade","sub":"CAPÍTULO 8: Intertextualidade",
  "intro":"Nenhum texto começa do zero. Cada um nasce cercado de outros textos já lidos — e é por já termos visto coisas parecidas que entendemos uma nova. Ler é, em boa parte, reconhecer. A intertextualidade é o fio que prende um texto a toda a biblioteca que veio antes dele.",
  "cards":[
      {"ic":"link","t":"Texto Se Apoia em Texto","emph":"apoia","b":"São os fatores que fazem o uso de um texto <strong>depender do conhecimento de outros</strong>. Nenhuma página nasce órfã: herda formas, fórmulas, expectativas. Quando você alude ao que o leitor já conhece, monta uma ponte de graça; quando alude ao que ele ignora, deixa-o na outra margem.","tip":"<strong>Como aplicar:</strong> referência só vira ponte se a outra margem é habitada. Cite o conhecido para economizar; cite o obscuro e perderá o leitor no rio.","wide":True},
      {"ic":"book","t":"O Gênero É um Contrato","emph":"contrato","b":"Reconhecer o gênero — notícia, receita, resumo, piada — <strong>aciona expectativas</strong> que orientam quem escreve e quem lê. É intertextualidade já institucionalizada: um acordo assinado antes da primeira palavra sobre o que vai vir, e como.","tip":"<strong>Modelo mental:</strong> o gênero entrega metade da compreensão antes da 1ª linha. Quem o reconhece já sabe como ler — e o que não esperar."},
      {"ic":"gap","t":"Clichê e Ponte Sem Margem","emph":"Clichê","b":"Repetir fórmulas no automático devolve previsibilidade (lá está a 1ª ordem de novo); aludir a um texto que o público não conhece é construir <strong>uma ponte com uma margem só</strong>. Subverter o gênero é faca de dois gumes: surpresa motivada encanta, expectativa traída sem razão frustra.","tip":"<strong>Cuidado:</strong> quebre o contrato do gênero de propósito e com chave — nunca por descuido. O leitor perdoa a ousadia; não perdoa o engano.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Intertextualidade: todo texto depende do conhecimento de outros textos — ler é reconhecer.","O gênero é intertextualidade institucionalizada — um contrato que aciona expectativas antes da 1ª palavra.","Aludir ao conhecido constrói a ponte; aludir ao obscuro deixa o leitor na outra margem."]},

 {"slug":"ch09-principios-regulativos","sub":"CAPÍTULO 9: Os Princípios Regulativos",
  "intro":"Os sete critérios dizem o que faz de um texto um texto. Faltava o último passo: como produzi-lo bem. Três princípios regulativos governam essa cozinha — um zela pelo esforço, outro pelo efeito, e o terceiro arbitra entre os dois. Saber os critérios é diagnosticar; dominar os princípios é escrever.",
  "cards":[
      {"ic":"scale","t":"Esforço, Efeito, Acerto","emph":"Acerto","b":"<strong>Eficiência</strong> = o máximo com o mínimo esforço — mas, sozinha, entedia. <strong>Efetividade</strong> = a impressão forte, o texto que marca — mas, sozinha, cansa. <strong>Adequação</strong> = o juiz que dosa as duas conforme a situação. Eficiência poupa, efetividade marca; só a adequação decide quanto de cada.","tip":"<strong>Como aplicar:</strong> não escolha entre poupar e marcar — calibre a mistura para este leitor, neste canal, agora.","wide":True},
      {"ic":"pivot","t":"Otimizar, Não Maximizar","emph":"Otimizar","b":"Não existe maximizar um critério: turbinar um sempre cobra de outro. O texto mais fluente perde força; o mais impactante perde fôlego. O alvo nunca é o extremo de um — é o <strong>ponto ótimo do conjunto</strong>, onde todos os sete seguram juntos sem que nenhum domine.","tip":"<strong>Modelo mental:</strong> escrever bem é regular sete mostradores ao mesmo tempo, não cravar um deles no máximo."},
      {"ic":"gap","t":"Liso ou Pesado Demais","emph":"Liso","b":"Cem por cento eficiente: fluente, sim, e <strong>esquecível</strong> — escorre e não deixa marca. Cem por cento efetivo: marcante, e <strong>exaustivo</strong> — cada frase pesa uma tonelada. Os dois extremos fracassam por motivos opostos, e o erro está em ter ido até a ponta.","tip":"<strong>Cuidado:</strong> o equilíbrio certo não é fixo — ele muda com o gênero, o canal e o público. A adequação é regulagem, não receita.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["Três princípios regulam a escrita: eficiência (esforço), efetividade (impacto), adequação (o juiz).","Fluência e impacto puxam para lados opostos; a adequação arbitra conforme a situação.","Otimize o conjunto, nunca maximize um só — turbinar um critério sempre cobra de outro."]},
]
