# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'Como Fazer Amigos e Influenciar
Pessoas' (Dale Carnegie — How to Win Friends and Influence People, 1936).
Frameworks canônicos: as 3 técnicas fundamentais (não critique/condene/reclame;
aprecie honesta e sinceramente; desperte um forte desejo no outro); as 6 maneiras
de fazer gostarem de você (interesse genuíno, sorriso, o nome, ouvir, falar dos
interesses do outro, fazer sentir-se importante); as 12 maneiras de convencer
(evitar discussão; nunca dizer 'você está errado'; admitir o erro; começar amigável;
o 'sim, sim'; deixar falar; deixar a ideia ser do outro; ver pelo ponto de vista dele;
mostrar simpatia; apelar a motivos nobres; dramatizar; lançar um desafio); as 9
maneiras de liderar sem ofender (elogiar; apontar o erro indiretamente; falar dos
próprios erros antes; perguntar em vez de ordenar; deixar salvar as aparências;
elogiar o progresso; dar uma reputação a zelar; tornar o erro fácil de corrigir;
fazer o outro feliz em colaborar). Base: frameworks amplamente documentados —
não reproduz o texto."""

BOOK = {
 "title": "Como Fazer Amigos e Influenciar Pessoas",
 "author": "Dale Carnegie",
 "header_light": "COMO FAZER AMIGOS",
 "header_bold": "E INFLUENCIAR PESSOAS",
 "subtitle": "VISÃO GERAL · A ARTE PERDIDA DE LIDAR COM GENTE",
 "intro": "Carnegie descobriu uma coisa simples que quase todo mundo esquece: ninguém faz nada pelo SEU bem, todos agem pelo próprio — e por uma fome quase infantil de se sentir importante. Daí nasce tudo. Pare de criticar, que não corrige ninguém; aprecie de verdade, que custa pouco e vale ouro; e, em vez de empurrar o que você quer, descubra o que o outro deseja e mostre o caminho. Quem larga a vontade de ter razão e abraça o ponto de vista alheio tem o mundo a seu favor — porque trata as pessoas não como elas são, mas como elas querem ser vistas.",
 "description": "Publicado em 1936 e jamais fora de moda, é o clássico fundador das relações humanas — não porque ensine truques, mas porque devolve algo antigo: o interesse sincero pelo próximo. Em quatro partes (3 técnicas fundamentais, 6 maneiras de cair nas graças, 12 maneiras de convencer, 9 maneiras de liderar sem ferir), Carnegie repete um só recado de cem formas: influência é atração, nunca imposição. Veja pelo olho do outro, reconheça seu valor com sinceridade, e o que parecia manobra vira amizade. O método só funciona de coração aberto — usado para manipular, ele desmorona.",
 "tags": ["Comunicação", "Relacionamentos", "Influência"],
 "progress": "11 Capítulos",
 "cover": "assets/como-fazer-amigos-cover.png",
 "overview_cards": [
   {"ic":"key","t":"A Fome de Ser Importante","b":"Depois de comer e dormir, o desejo mais teimoso do ser humano é o de <strong>sentir-se importante</strong> — e é raríssimo alguém saciá-lo no próximo. Quase tudo o que fazemos, do trabalho ao penteado, é súplica disfarçada por essa migalha de reconhecimento. Quem aprende a oferecê-la com <strong>sinceridade</strong>, e não com bajulação, vira figura rara — daquelas que a gente nunca esquece.","tip":"<strong>Modelo mental:</strong> a sensação de importância é o pão mais barato que você pode dar — e o que mais falta na mesa de todo mundo.","wide":True},
   {"ic":"fork","t":"Isque com o que o Peixe Quer","b":"Você adora morango com creme; o peixe, porém, prefere minhoca — então é minhoca que vai no anzol. Assim com as pessoas: a única forma de mover alguém é falar do que <strong>ELE</strong> quer e mostrar como conseguir. Ford resumiu o <strong>segredo do sucesso</strong> em saber ver pelo ângulo do outro tão bem quanto pelo seu.","tip":"<strong>Como aplicar:</strong> antes de pedir, troque 'eu preciso' por 'como faço esta pessoa QUERER?'. Influência se atrai, não se arranca.","wide":True},
   {"ic":"scale","t":"Apreciar Não é Bajular","b":"As duas dão tapinha nas costas, mas vêm de lugares opostos: apreciação brota do coração e é <strong>altruísta</strong>; bajulação sai dos dentes para fora e é <strong>egoísta</strong> — e a gente fareja a segunda a um quilômetro. Carnegie pede o contrário do nosso instinto: <strong>pródigo no elogio, parco na censura</strong>.","tip":"<strong>Teste decisivo:</strong> se há vantagem esperada por trás do elogio, já não é apreciação — é isca."},
   {"ic":"steps","t":"O Livro em Quatro Andares","b":"<strong>(1)</strong> 3 técnicas para lidar com gente; <strong>(2)</strong> 6 maneiras de fazer gostarem de você; <strong>(3)</strong> 12 maneiras de convencer; <strong>(4)</strong> 9 maneiras de corrigir sem ferir. Não é lista solta: cada andar repousa sobre o de baixo, e todos sobre o mesmo alicerce — pensar primeiro no outro.","tip":"<strong>Mapa:</strong> escolha o andar pelo que você precisa agora — laço, simpatia, persuasão ou correção."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-fundamentos","sub":"PARTE 1: As Três Técnicas Fundamentais para Lidar com Pessoas",
  "intro":"Antes de qualquer técnica, três verdades simples sobre gente: criticar não corrige ninguém, todos têm sede de reconhecimento, e só se move quem é o outro quer. Não critique, aprecie de verdade, desperte o desejo. Tudo o que vem depois no livro é desdobramento destas três — e nada se sustenta sem elas.",
  "cards":[
      {"ic":"key","t":"A Sede de Ser Importante","emph":"Importante","b":"Tire a fome e o sono e sobra um desejo que governa quase tudo: o de ser importante. É ele que faz a criança chorar por atenção e o adulto comprar carro caro. Freud chamou de desejo de grandeza; Dewey, de anseio de ser notável — e quase ninguém o sacia no próximo. <strong>Quem aprende a alimentar essa fome com sinceridade torna-se daquelas pessoas que não se esquecem.</strong>","tip":"<strong>Modelo mental:</strong> a sede de importância é o motor mais constante de todos. Alimente-a — jamais a explore."},
      {"ic":"fork","t":"Morango para Você, Minhoca para o Peixe","emph":"Ponto de Vista do Outro","b":"Toda pessoa age pelo que ELA quer — nunca pelo que você quer. Você gosta de morango com creme; mas, para pescar, é minhoca que se põe no anzol, porque é disso que o peixe gosta. <strong>Pare de falar da sua necessidade e descubra o desejo do outro</strong>; depois mostre como o seu pedido o realiza. Essa é a fronteira exata entre empurrar e atrair.","tip":"<strong>Como aplicar:</strong> antes de “eu preciso que…”, descubra “o que o OUTRO ganha com isto?”.","wide":True},
      {"ic":"steps","t":"O Alicerce em Três Pedras","emph":"Três Técnicas Fundamentais","b":"A Parte 1 inteira cabe em três regras: não critique, não condene, não reclame; aprecie honesta e sinceramente; desperte no outro um desejo ardente. <strong>Todo o resto do livro são notas de rodapé destas três.</strong> Troque o impulso de corrigir pelo de compreender, e ancore cada pedido no que o outro quer ver realizado.","tip":"<strong>Regra:</strong> domine estas três e metade dos atritos da sua vida se dissolve antes de nascer."},
    ],
  "lessons_title":"Lições-Chave da Parte 1",
  "lessons":["Cada um age pelo próprio desejo e pela sede de sentir-se importante — comece por aí.","Influência é atração — despertar vontade —, nunca imposição.","Não criticar + apreciar de verdade + despertar o desejo: o alicerce que segura todo o resto."]},

 {"slug":"ch02-nao-critique","sub":"PARTE 1: Não Critique, Não Condene, Não Reclame",
  "intro":"Criticar parece consertar, mas estraga: fere o orgulho, levanta a defesa e deixa um rancor que dura anos — e quase nunca muda o que se queria mudar. O atalho que ninguém toma é o mais curto: compreender em vez de condenar.",
  "cards":[
      {"ic":"sword","t":"A Crítica Volta como Bumerangue","emph":"Bumerangue","b":"Você atira a crítica para corrigir e ela volta para te acertar: o outro não se emenda — ele se defende, contra-ataca ou se fecha como bicho acuado. “Qualquer tolo sabe criticar; entender e perdoar é que exige caráter.” <strong>A crítica raramente conserta o erro, mas raramente é esquecida</strong> — o orgulho ferido cobra juros por décadas.","tip":"<strong>Cuidado:</strong> crítica no calor do momento é a que mais machuca. Conte até dez antes de abrir a boca.","warn":True},
      {"ic":"eye","t":"Ninguém se Acha o Vilão","emph":"Justificados","b":"Cercado pela polícia, o assassino “Two Gun” Crowley escreveu que tinha “um coração cansado, mas bom, que a ninguém faria mal”. Se nem ele se condenava, que esperança há de a sua bronca dobrar uma pessoa comum? <strong>Não lidamos com criaturas de lógica, e sim de emoção</strong> — feitas de orgulho, vaidade e do tal coração que sempre se acha justo.","tip":"<strong>Modelo mental:</strong> troque “que burrice ele fez” por “por que, do lugar dele, aquilo fez sentido?”.","wide":True},
      {"ic":"leaf","t":"Entender no Lugar de Julgar","emph":"Compreender","b":"O que muda alguém nunca é a sentença — é a compreensão. Lincoln, ferino na juventude, quase foi parar num duelo por uma carta cruel; daí em diante engaveta as críticas e adota um lema: “Não julgues, para não seres julgado.” <strong>Procurar por que a pessoa agiu assim abre exatamente o canal que a crítica tranca.</strong>","tip":"<strong>Como aplicar:</strong> no lugar de “você errou”, faça uma pergunta sincera sobre o que a levou àquilo."},
    ],
  "lessons_title":"Lições-Chave (Técnica 1)",
  "lessons":["A crítica fere o orgulho e semeia rancor — quase nunca colhe correção.","Todo mundo se acha justificado; condenar só endurece o outro.","No lugar de criticar, procure entender por que ele agiu como agiu."]},

 {"slug":"ch03-aprecie","sub":"PARTE 1: Aprecie Honesta e Sinceramente",
  "intro":"Todo mundo anda faminto de uma coisa que ninguém serve: o sentir-se importante. A apreciação sincera é esse alimento — e é tão escasso que quem o oferece de verdade vira presença inesquecível. Cuidado para não confundi-lo com sua imitação barata, a bajulação.",
  "cards":[
      {"ic":"scale","t":"Sincera ou dos Dentes para Fora","emph":"Bajulação","b":"Apreciação e bajulação parecem gêmeas, mas vêm de mundos opostos: uma nasce no coração e é altruísta; a outra sai dos dentes para fora e é egoísta — e a gente fareja a falsa na hora. Bajular é dizer ao outro exatamente o que ele pensa de si mesmo. <strong>O elogio calculado colhe desprezo, não cooperação</strong>; no instante em que você espera algo em troca, já cruzou a linha.","tip":"<strong>Teste decisivo:</strong> se há vantagem esperada por trás, não é apreciação — é bajulação disfarçada.","warn":True},
      {"ic":"spark","t":"Sol ou Sombra para a Pessoa","emph":"Pródigo no Elogio","b":"Charles Schwab, um dos primeiros homens a ganhar um milhão de dólares por ano, dizia que seu maior trunfo era despertar entusiasmo “pela apreciação e pelo encorajamento” — “sou pródigo no elogio e parco na censura”. <strong>As pessoas abrem-se ao reconhecimento e murcham sob a crítica</strong>, exatamente como a planta ao sol e à sombra.","tip":"<strong>Como aplicar:</strong> aponte algo concreto e verdadeiro, e vá embora sem cobrar nada por isso."},
      {"ic":"key","t":"Tire o Holofote de Você","emph":"Qualidades do Outro","b":"O elogio só vira verdadeiro — e perde o cheiro de bajulação — quando você para de remoer as próprias façanhas e começa a enxergar as do outro. <strong>Dê às pessoas a única coisa de que andam famintas: a sensação de importância.</strong> É a moeda mais barata da terra e, ao mesmo tempo, a que mais vale na mão de quem a recebe.","tip":"<strong>Modelo mental:</strong> vire o holofote do “eu” para o “ele” — e o elogio sai sozinho, sincero."},
    ],
  "lessons_title":"Lições-Chave (Técnica 2)",
  "lessons":["A apreciação sincera mata a fome humana mais antiga: a de se sentir importante.","Bajulação é falsa e egoísta; apreciação é sincera e altruísta — não troque uma pela outra.","Seja pródigo no elogio verdadeiro e parco na censura — como o sol é para a planta."]},

 {"slug":"ch04-desperte-desejo","sub":"PARTE 1: Desperte no Outro um Forte Desejo",
  "intro":"Você pode mandar, suplicar ou ameaçar — nada disso move ninguém de verdade. A única alavanca é o desejo do próprio outro. Acenda nele uma vontade ardente e ele caminha sozinho; fale só dos seus desejos e caminhará sozinho você.",
  "cards":[
      {"ic":"target","t":"Acenda uma Vontade Ardente","emph":"Ânsia Ardente","b":"“Primeiro, desperte no outro uma vontade ardente. Quem consegue isso tem o mundo inteiro consigo; quem não, segue por uma estrada solitária” (Overstreet). <strong>Nenhuma ação humana nasce de ordem — todas nascem de um querer.</strong> Entusiasmo não se decreta; ele só brota quando a pessoa deseja, por dentro, aquilo que você propõe.","tip":"<strong>Como aplicar:</strong> descubra o que o outro quer e mostre como o seu pedido entrega justamente isso."},
      {"ic":"lens","t":"Use os Dois Olhos","emph":"Ângulo do Outro","b":"“Se existe um segredo do sucesso, ele está em ver as coisas pelo seu ângulo E pelo do outro ao mesmo tempo” (Ford). Embrulhar todo pedido no benefício alheio é o que transforma uma cobrança em algo que a pessoa faz de bom grado. <strong>Quem enxerga com os dois olhos tem o mundo a favor; quem só vê o próprio lado anda sozinho.</strong>","tip":"<strong>Regra:</strong> antes de propor qualquer coisa, responda honestamente: “por que ELE iria querer isto?”."},
      {"ic":"leaf","t":"Puxar o Bezerro Pela Vontade Dele","emph":"Empurrar","b":"Emerson e o filho suavam para empurrar o bezerro ao estábulo — cada um pensando só no que ELE queria. A empregada irlandesa, calada, pôs o dedo na boca do animal: deu-lhe o que o bezerro queria, e o conduziu manso para dentro. <strong>Despertar o desejo é atrair; impor é empurrar — e empurrar só fabrica resistência.</strong>","tip":"<strong>Cuidado:</strong> Carnegie exige ganho mútuo — usar o desejo do outro só para tirar vantagem trai o método e fracassa.","warn":True},
    ],
  "lessons_title":"Lições-Chave (Técnica 3)",
  "lessons":["A única forma de mover alguém é falar do que ELE quer e mostrar como obtê-lo.","Ver pelo ângulo do outro, sem largar o seu, é o segredo do sucesso (Ford).","Despertar o desejo é atrair; impor é empurrar — e empurrar gera resistência."]},

 {"slug":"ch05-gostarem-de-voce-1","sub":"PARTE 2: Seis Maneiras de Fazer as Pessoas Gostarem de Você (I)",
  "intro":"Simpatia não se conquista falando de si — conquista-se virando a atenção, de coração, para o outro. As três primeiras maneiras são as mais despretensiosas e as mais esquecidas: interesse genuíno, um sorriso, e o nome da pessoa.",
  "cards":[
      {"ic":"leaf","t":"A Lição do Cachorro","emph":"Interesse-se de Verdade","b":"Você faz mais amigos em dois meses interessando-se pelos outros do que em dois anos tentando que se interessem por você. Quem ensina isso de graça é o cachorro: ele vive de afeto genuíno e não tem nada a vender — por isso o mundo o adora. <strong>Para ser interessante, basta ser interessado.</strong> Vire o holofote para o outro, e ele se aproxima sozinho.","tip":"<strong>Como aplicar:</strong> entre em cada conversa curioso pela pessoa, não ansioso para impressioná-la."},
      {"ic":"spark","t":"O Recado que Não Precisa de Palavras","emph":"Sorria","b":"O sorriso diz, sem uma sílaba, “gosto de você, você me faz bem” — e atravessa até a linha telefônica. Não custa nada e enriquece quem recebe. <strong>Aja alegre e você ficará alegre: o gesto puxa o sentimento</strong>, não o contrário. Já a cara fechada anuncia rejeição antes da primeira frase.","tip":"<strong>Modelo mental:</strong> é o gesto mais barato do mundo com o maior retorno em boa-vontade."},
      {"ic":"key","t":"O Som Mais Doce de Todos","emph":"Som Mais Doce","b":"Para cada pessoa, o próprio nome é a palavra mais importante de qualquer idioma. Lembrá-lo é um elogio silencioso; esquecê-lo, um desdém. <strong>Andrew Carnegie batizava suas usinas com o nome de quem queria como cliente — e fechava o contrato.</strong> O famoso “sou péssimo com nomes” é, no fundo, só falta de atenção na hora de ouvir.","tip":"<strong>Como aplicar:</strong> repita o nome assim que ouvi-lo e use-o na conversa; trate-o como coisa sagrada.","wide":True},
    ],
  "lessons_title":"Lições-Chave (Maneiras 1-3)",
  "lessons":["Interesse-se sinceramente pelo outro — é o que mais aproxima as pessoas.","Sorria: o gesto mais barato com o maior retorno em boa-vontade.","Lembre e use o nome — para o seu dono, é o som mais doce que existe."]},

 {"slug":"ch06-gostarem-de-voce-2","sub":"PARTE 2: Seis Maneiras de Fazer as Pessoas Gostarem de Você (II)",
  "intro":"As três maneiras finais têm um eixo só: tire o assunto de você e ponha no outro. Saiba ouvir, fale do que entusiasma a pessoa e faça-a sentir-se importante — sempre de coração. Quem faz isso de verdade não é esquecido.",
  "cards":[
      {"ic":"eye","t":"O Maior Elogio é a Atenção","emph":"Bom Ouvinte","b":"Convide o outro a falar de si, faça perguntas que ele adore responder e escute com o corpo inteiro. Numa festa, Carnegie ouviu um botânico por horas quase mudo — e saiu da noite com fama de “o conversador mais interessante” da sala. <strong>O melhor conversador é, na verdade, o melhor ouvinte:</strong> nada lisonjeia tanto quanto a atenção exclusiva.","tip":"<strong>Cuidado:</strong> interromper ou só esperar a sua vez de falar é o exato oposto de ouvir.","warn":True},
      {"ic":"bubble","t":"Fale na Língua do Outro","emph":"Interesses do Outro","b":"Descubra o que faz a pessoa brilhar os olhos e leve a conversa para lá — ninguém resiste ao próprio assunto predileto. <strong>É a estrada mais curta até o coração de qualquer um.</strong> Roosevelt varava a véspera estudando o tema favorito de cada visitante; falar a língua do outro abre portas que nenhum argumento abriria.","tip":"<strong>Como aplicar:</strong> antes do encontro, descubra o que importa para a pessoa — e comece exatamente por aí."},
      {"ic":"constellation","t":"O Coroamento de Tudo","emph":"Importante","b":"As seis maneiras desembocam aqui, na Regra de Ouro: trate cada um como ele gostaria de ser tratado. Toda pessoa é superior a você em alguma coisa — reconheça isso de coração e a porta se abre. <strong>A única palavra que separa este princípio da bajulação é “sinceridade”; sem ela, todo o resto rui.</strong>","tip":"<strong>Regra:</strong> reconheça o valor que o outro realmente tem, nunca um elogio inventado para agradar.","wide":True},
    ],
  "lessons_title":"Lições-Chave (Maneiras 4-6)",
  "lessons":["Ouvir de verdade e deixar o outro falar de si encanta como nenhuma frase brilhante.","Fale dos interesses do outro — é a estrada mais curta até o coração dele.","Faça-o sentir-se importante, com sinceridade (Regra de Ouro): o resumo de tudo."]},

 {"slug":"ch07-convencer-1","sub":"PARTE 3: Conquistar para o Seu Modo de Pensar (I)",
  "intro":"Ninguém nunca convenceu ninguém numa discussão — a lógica não derruba o orgulho, acende. As três primeiras armas da persuasão andam na contramão do instinto: fuja da briga, nunca diga 'você está errado' e, quando errar, seja o primeiro a confessar.",
  "cards":[
      {"ic":"sword","t":"A Discussão Só se Ganha Fugindo","emph":"Evitando","b":"Mesmo “ganhando” a discussão, você perde: o outro sai ferido e mais agarrado à própria opinião. <strong>“Um homem convencido contra a vontade conserva a mesma opinião.”</strong> A razão não dobra o orgulho — ela o inflama. Não existe vitória de verdade numa briga: existe só uma relação a menos e um inimigo a mais.","tip":"<strong>Cuidado:</strong> no instante em que você pensa em “ganhar a discussão”, a relação já está perdida.","warn":True},
      {"ic":"scale","t":"Nunca Diga “Você Está Errado”","emph":"“Você Está Errado”","b":"Essas três palavras são um soco no amor-próprio: a mente do outro se fecha antes do próximo argumento. Troque por “posso muito bem estar enganado — vamos olhar os fatos juntos”. <strong>As pessoas concordam com quem as respeita, jamais com quem as humilha.</strong> Abrir admitindo a própria falha desarma a defesa que a sentença levantaria.","tip":"<strong>Como aplicar:</strong> ao discordar, comece confessando a sua falibilidade, não a do outro.","wide":True},
      {"ic":"key","t":"Confesse Antes que o Outro Acuse","emph":"Rápido e com Força","b":"Errou? Antecipe-se e condene a si mesmo com mais vigor do que o outro condenaria. Pego com o cão sem focinheira no parque, Carnegie disse ao guarda “sou culpado, não tenho desculpa nenhuma” — e o guarda acabou defendendo-o. <strong>Admitir o erro é força; defender o indefensável só endurece quem está diante de você.</strong>","tip":"<strong>Regra:</strong> tire as armas da mão do outro confessando primeiro — a humildade desarma."},
    ],
  "lessons_title":"Lições-Chave (Maneiras 1-3 de convencer)",
  "lessons":["A única forma de vencer uma discussão é não entrar nela.","Nunca diga 'você está errado' — respeite a opinião e abra com 'posso estar enganado'.","Quando errar, confesse rápido e com força — isso desarma o outro de imediato."]},

 {"slug":"ch08-convencer-2","sub":"PARTE 3: Conquistar para o Seu Modo de Pensar (II)",
  "intro":"Persuadir bem é conduzir, nunca empurrar. Abra com cordialidade, leve o outro a dizer 'sim' desde a primeira pergunta, deixe-o falar — e, sobretudo, deixe a ideia nascer como sendo dele. Contra a própria ideia, ninguém luta.",
  "cards":[
      {"ic":"leaf","t":"Uma Gota de Mel","emph":"Amigável","b":"“Uma gota de mel apanha mais moscas que um galão de fel.” A brandura abre o portão; a hostilidade tranca tudo antes da primeira frase. <strong>O tom da abertura decide se a conversa começa ou já termina.</strong> Quem entra acusando ou exigindo garante a porta na cara — e perde o resto do tempo tentando reabri-la.","tip":"<strong>Como aplicar:</strong> abra com cordialidade verdadeira, jamais com cobrança ou acusação."},
      {"ic":"steps","t":"O Segredo Socrático do “Sim”","emph":"“Sim, Sim”","b":"Velho truque de Sócrates: comece pelo que os dois já concordam e encadeie perguntas cuja única resposta possível é “sim”. <strong>Um “não” inicial vira orgulho que exige coerência; cada “sim” deixa o próximo mais fácil.</strong> Você embala o outro numa inércia de concordância — e, quando chega o ponto espinhoso, ele já vem dizendo sim.","tip":"<strong>Regra:</strong> nunca arranque um “não” logo no começo; desenhe antes a escada de concordâncias.","wide":True},
      {"ic":"bulb","t":"Deixe a Ideia Ser Dele","emph":"Ideia Ser do Outro","b":"Deixe o outro falar a maior parte — quem fala vai se convencendo sozinho. E plante a semente para que a ideia floresça como iniciativa dele. Um vendedor chegou com esboços de propósito inacabados e perguntou: “como o senhor terminaria isto?” O cliente sentiu o desenho como seu — e fechou o pedido. <strong>Ninguém resiste à própria ideia.</strong>","tip":"<strong>Como aplicar:</strong> ofereça como pergunta ou rascunho e deixe o outro completar — ele a adotará como dele."},
    ],
  "lessons_title":"Lições-Chave (Maneiras 4-8 de convencer)",
  "lessons":["Comece amigável e leve o outro a dizer 'sim' desde a primeira pergunta.","Deixe-o falar e sentir que a ideia é dele — ninguém luta contra a própria ideia.","Veja honestamente pelo ângulo do outro antes de propor o que quer que seja."]},

 {"slug":"ch09-convencer-3","sub":"PARTE 3: Conquistar para o Seu Modo de Pensar (III)",
  "intro":"As últimas armas da persuasão miram o coração: acolha o que o outro sente, ofereça-lhe um motivo nobre para agir, torne a ideia vívida e, quando nada mais mover a pessoa, atire-lhe um desafio. Tudo aqui aposta na melhor imagem que cada um tem de si.",
  "cards":[
      {"ic":"wave","t":"“Eu Sentiria o Mesmo”","emph":"Simpatia","b":"“Eu compreendo perfeitamente como você se sente; no seu lugar, eu sentiria exatamente igual.” Acolher a emoção do outro acalma a hostilidade e reabre o canal que o argumento havia trancado. <strong>Ninguém ouve você antes de se sentir ouvido.</strong> Já o “não é para tanto” bate a porta na cara da conversa.","tip":"<strong>Como aplicar:</strong> valide o sentimento do outro ANTES de apresentar a sua proposta."},
      {"ic":"mountain","t":"O Motivo que Soa Bem","emph":"Mais Nobres","b":"Todo mundo tem duas razões para agir: a real e a que soa bonita. <strong>Apele à que soa bonita — honra, justiça, palavra dada — e a maioria se esforça para honrar a imagem elevada que tem de si.</strong> Dê ao outro um motivo digno de fazer o que você precisa, em vez de cutucar só o interesse mesquinho.","tip":"<strong>Modelo mental:</strong> ofereça uma razão honrosa e a pessoa tende a se erguer à altura dela.","wide":True},
      {"ic":"spark","t":"Mostre, Não Conte — e Desafie","emph":"Desafio","b":"Verdade enunciada não convence; verdade encenada, sim — mostre, não conte. E, quando nada mexe com a pessoa, lance um desafio. Schwab riscou no chão da usina, em giz, o número de fornadas do turno do dia — sem dizer palavra. À noite, os turnos já competiam e a produção disparou. <strong>O desejo de vencer e de se destacar é combustível dos fortes.</strong>","tip":"<strong>Cuidado:</strong> teatro demais soa falso, e desafio mal calibrado vira pressão hostil.","warn":True},
    ],
  "lessons_title":"Lições-Chave (Maneiras 9-12 de convencer)",
  "lessons":["Acolha os sentimentos e desejos do outro antes de propor qualquer coisa.","Apele aos motivos mais nobres — as pessoas querem se ver agindo com honra.","Dramatize a ideia e, se preciso, lance um desafio: a vontade de vencer move montanhas."]},

 {"slug":"ch10-liderar-1","sub":"PARTE 4: Ser Líder — Mudar Pessoas sem Ofender (I)",
  "intro":"O bom líder corrige sem ferir, porque sabe que orgulho ferido nunca colabora. As primeiras quatro maneiras: abra com um elogio sincero, aponte o erro de lado, confesse os seus deslizes antes — e prefira a pergunta à ordem.",
  "cards":[
      {"ic":"spark","t":"A Anestesia Antes do Dentista","emph":"Elogio Sincero","b":"Engole-se muito melhor uma crítica depois de um reconhecimento honesto — como o dentista aplica anestésico antes de furar. <strong>O elogio verdadeiro amolece o terreno e abre o outro para a correção</strong> que, vinda seca, ele só rejeitaria. Não invente méritos: ancore-se em algo que a pessoa realmente fez bem.","tip":"<strong>Como aplicar:</strong> abra com um acerto concreto dela antes de tratar do que precisa mudar."},
      {"ic":"pivot","t":"Troque o “mas” pelo “e”","emph":"“e”, Não com “mas”","b":"O “mas” apaga tudo que veio antes — “você melhorou muito, MAS…” faz o outro só ouvir o tranco final. Troque por “e”: “melhorou muito, E, se afiarmos a matemática, fica imbatível”. <strong>E fale dos seus próprios erros antes de apontar os dele</strong>, para que a correção soe a conselho de igual, e não a sermão de quem está por cima.","tip":"<strong>Regra:</strong> confesse que você também erra — assim corrige lado a lado, não de cima para baixo.","wide":True},
      {"ic":"bubble","t":"Pergunte, Não Ordene","emph":"Pergunte","b":"Ninguém gosta de receber ordens. “Será que isto funcionaria?”, “o que você acha de…?” — <strong>a pergunta poupa o orgulho, convida à cooperação e faz a pessoa agir como se a ideia fosse dela.</strong> Um chefe, em vez de mandar limpar a sala, perguntou o que se poderia fazer com ela; o funcionário propôs a solução e a executou de bom grado.","tip":"<strong>Como aplicar:</strong> transforme cada ordem numa pergunta que convide o outro a propor a saída."},
    ],
  "lessons_title":"Lições-Chave (Maneiras 1-4 de liderar)",
  "lessons":["Comece sempre com elogio sincero — é a anestesia antes da correção.","Aponte o erro de lado (use 'e', não 'mas') e confesse os seus deslizes primeiro.","Pergunte em vez de mandar — a pergunta poupa o orgulho e gera cooperação."]},

 {"slug":"ch11-liderar-2","sub":"PARTE 4: Ser Líder — Mudar Pessoas sem Ofender (II)",
  "intro":"O grande líder não rebaixa — ele eleva. Deixa o outro salvar a face, celebra cada passo à frente, empresta-lhe uma reputação a zelar, faz do conserto algo fácil e, no fim, deixa a pessoa feliz por fazer o que ele sugeriu.",
  "cards":[
      {"ic":"mask","t":"Deixe o Outro Salvar a Face","emph":"Salvar as Aparências","b":"Nunca rebaixe ninguém diante dos outros; preserve a dignidade alheia mesmo ao corrigir ou dispensar. Custa quase nada e poupa anos de mágoa. <strong>Humilhar alguém em público fabrica um inimigo para a vida inteira</strong> — e nenhuma razão que você tivesse sobrevive a essa ferida no amor-próprio.","tip":"<strong>Cuidado:</strong> corrigir em público é a maior das ofensas. Faça-o a sós e com tato.","warn":True},
      {"ic":"spark","t":"Aplauda o Menor dos Avanços","emph":"Cada Progresso","b":"Seja “caloroso na aprovação e pródigo no elogio”. Reconheça todo avanço, por mínimo que pareça — o elogio específico faz a habilidade florescer muito mais que a crítica. <strong>Calar os acertos para só apontar os erros desanima e trava a pessoa.</strong> Quem se sente visto no progresso quer continuar progredindo.","tip":"<strong>Como aplicar:</strong> nomeie o avanço concreto na hora em que ele acontece, não só lá no resultado final."},
      {"ic":"constellation","t":"Dê um Bom Nome a Honrar","emph":"Reputação a Zelar","b":"Empreste ao outro a virtude que você quer ver nele — “você sempre foi tão cuidadoso” — e ele se esforçará para fazer jus. Uma dona de casa chamou a empregada nova de excelente cozinheira antes de qualquer prova; e Nellie tornou-se, de fato, impecável. <strong>Dê ao cão um bom nome e ele lutará para honrá-lo.</strong>","tip":"<strong>Modelo mental:</strong> a virtude atribuída tende a virar virtude real — e faça também o erro parecer fácil de corrigir.","wide":True},
    ],
  "lessons_title":"Lições-Chave (Maneiras 5-9 de liderar)",
  "lessons":["Deixe o outro salvar a face e aplauda cada avanço, por menor que seja.","Empreste-lhe um bom nome a honrar e faça o conserto do erro parecer fácil.","Deixe a pessoa feliz em fazer o que você sugere — mostre-lhe o que ela ganha com isso."]},
]
