# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'A Coragem de Não Agradar'
(Ichiro Kishimi & Fumitake Koga — The Courage to Be Disliked), sobre a psicologia
individual de Alfred Adler. Diálogo Filósofo × Jovem em 5 noites.
Frameworks canônicos: teleologia vs. etiologia ('o trauma não existe'); todo
problema é interpessoal; sentimento × complexo de inferioridade/superioridade;
a separação de tarefas ('de quem é a tarefa?'); o desejo de reconhecimento como
armadilha; relações horizontais (encorajar, não elogiar); sentimento de comunidade
(Gemeinschaftsgefühl); a tríade autoaceitação + confiança + contribuição; o aqui
e agora; a coragem de ser desprezado. Base: frameworks amplamente documentados —
não reproduz o texto."""

BOOK = {
 "title": "A Coragem de Não Agradar",
 "author": "Ichiro Kishimi & Fumitake Koga",
 "header_light": "A CORAGEM DE",
 "header_bold": "NÃO AGRADAR",
 "subtitle": "VISÃO GERAL · A PSICOLOGIA DE ADLER EM DIÁLOGO",
 "intro": "Um diálogo socrático entre um Filósofo e um Jovem cético, ao longo de cinco noites. O Filósofo defende a psicologia de Alfred Adler — quase esquecida ao lado de Freud e Jung. A tese choca: o passado não nos determina, todo problema é de relações interpessoais, e a felicidade é uma escolha de coragem. A coragem de ser livre — e, portanto, de ser desprezado por alguém.",
 "description": "O fenômeno japonês de Kishimi e Koga que popularizou Alfred Adler pelo mundo. Em forma de diálogo, vira do avesso a ideia de que somos reféns do trauma: vivemos por objetivos, não por causas. Ensina a separação de tarefas, a sair da armadilha do reconhecimento e a sustentar a felicidade na tríade autoaceitação, confiança e contribuição — a verdadeira coragem de não agradar.",
 "tags": ["Psicologia", "Adler", "Autoconhecimento"],
 "progress": "9 Capítulos",
 "cover": "assets/coragem-de-nao-agradar-cover.png",
 "overview_cards": [
   {"ic":"fork","t":"Teleologia vs. Etiologia — \"o trauma não existe\"","b":"Freud explica pela <strong>causa</strong> passada ('você é assim por causa de…'); Adler, pelo <strong>objetivo</strong> presente ('você age assim para conseguir algo'). A experiência não determina — nós damos significado a ela. O 'trauma não existe' não nega a dor: nega que ela nos <strong>obrigue</strong> a um destino.","tip":"<strong>Modelo mental:</strong> pergunte 'para quê?', não 'por quê?'. A causa prende; o objetivo liberta.","wide":True},
   {"ic":"scale","t":"A Separação de Tarefas","b":"A chave de quase todo conflito é uma pergunta: <strong>'de quem é a tarefa?'</strong>. Critério: <strong>quem arca com as consequências</strong>. Cuide da sua, não invada a do outro — nem deixe invadirem a sua. O que os outros pensam de você é <strong>tarefa deles</strong>.","tip":"<strong>Como aplicar:</strong> antes de se meter num conflito, identifique o dono da tarefa pelas consequências.","wide":True},
   {"ic":"sword","t":"A Coragem de Ser Desprezado","b":"Viver para satisfazer expectativas alheias é viver a vida dos outros. O desejo de reconhecimento é uma armadilha. A liberdade tem preço: aceitar ser, eventualmente, <strong>malvisto por alguém</strong>. Não buscar ser desprezado — mas não temer sê-lo.","tip":"<strong>Regra:</strong> se ninguém nunca te desaprova, talvez você não esteja vivendo a sua vida."},
   {"ic":"constellation","t":"A Tríade da Felicidade","b":"A coragem se ergue sobre três pilares: <strong>autoaceitação</strong> (aceitar o que não dá), <strong>confiança nos outros</strong> (sem condições) e <strong>contribuição</strong> ('sou útil'). É sentir-se útil — não ser aprovado — que dá valor a si mesmo.","tip":"<strong>Modelo mental:</strong> aceitar-se → confiar → contribuir → sentir-se útil → aceitar-se mais."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-trauma-nao-existe","sub":"PRIMEIRA NOITE: O Trauma Não Existe",
  "intro":"O passado não nos determina. Adler explica a conduta pelo objetivo presente (teleologia), não pela causa passada (etiologia). Por isso o Filósofo provoca: o trauma não existe no sentido de uma causa que nos prende — somos nós que damos significado à experiência.",
  "cards":[
      {"ic":"fork","t":"“Por Quê?” Prende, “Para Quê?” Liberta","emph":"“Para Quê?”","b":"Freud explica pela causa de trás: “você é assim por causa do que te aconteceu” — e, dito isso, o futuro já está fechado. Adler inverte a seta: “você age assim para um fim de agora”. O passado deixa de ser sentença e vira matéria-prima. <strong>Não é o que te aconteceu que decide a tua vida — é o objetivo que persegues neste instante.</strong>","tip":"<strong>Como aplicar:</strong> ao se flagrar num “não posso por causa de X”, pergunte “qual objetivo esse ‘não posso’ está me servindo?”."},
      {"ic":"key","t":"Os Mesmos Tijolos, Casa ou Prisão","emph":"Casa ou Prisão","b":"A experiência crua não causa o destino: o que decide é o <strong>significado</strong> que você empresta a ela. Por isso duas pessoas com o mesmo passado de dor seguem rumos opostos — uma se fecha, a outra floresce. Os mesmos tijolos erguem uma cela ou um lar; quem assenta cada um é você, no presente, não a infância.","tip":"<strong>Modelo mental:</strong> o passado é material de construção, nunca a planta pronta — o sentido você assina agora."},
      {"ic":"eye","t":"“O Trauma Não Existe” — o Que Isso Não Diz","emph":"Não Existe","b":"Adler não nega que coisas terríveis aconteçam, nem zomba da dor de ninguém. Ele nega que a dor nos <strong>obrigue</strong> a um destino. O recluso não fica trancado por causa do medo: ele fabrica o medo para ter licença de não enfrentar o mundo e seguir cuidado. Por trás de cada “não posso” mora um objetivo que o “não posso” protege.","tip":"<strong>Cuidado:</strong> “não existe” não quer dizer “não importa” — quer dizer “não te prende a um único destino”.","warn":True},
    ],
  "lessons_title":"Lições-Chave da Primeira Noite (I)",
  "lessons":["Não é o que te aconteceu que decide, mas o sentido que você dá.","Por trás de todo 'não posso' há um objetivo que ele protege.","Aceitar a teleologia é assumir que a mudança é possível agora."]},

 {"slug":"ch02-objetivo-e-estilo-de-vida","sub":"PRIMEIRA NOITE: Objetivos, Emoções e Estilo de Vida",
  "intro":"As emoções não nos dominam — nós as fabricamos a serviço de um objetivo. E o que chamamos de 'personalidade' é um estilo de vida que escolhemos, e que por isso pode ser reescolhido. O que falta para mudar não é capacidade: é coragem.",
  "cards":[
      {"ic":"spark","t":"Você Não É Tomado pela Raiva — Você a Liga","emph":"Você a Liga","b":"A mãe berra com a filha; o telefone toca, é a escola, e ela atende com voz mansa — desliga e volta a gritar. A raiva não a dominou: ela a <strong>ligou e desligou</strong> conforme servia. Emoção não é onda que te arrasta de fora; é ferramenta que você ergue para impor a vontade. Ninguém é escravo do que sente — a gente usa o sentimento.","tip":"<strong>Como aplicar:</strong> ao se sentir “tomado”, pergunte “o que estou tentando conseguir gritando — ou me calando — agora?”."},
      {"ic":"pivot","t":"Você Não Tem um Temperamento, Você Usa um Estilo","emph":"Usa um Estilo","b":"“Estilo de vida” é o nome de Adler para a personalidade — escolhido por volta dos dez anos e, por ter sido escolhido, <strong>re-escolhível agora mesmo</strong>. A diferença é tudo: não é “eu sou tímido”, sentença sem saída; é “eu tenho usado a timidez para evitar a rejeição”. Trocar o verbo de “ser” para “usar” devolve a chave à sua mão.","tip":"<strong>Modelo mental:</strong> personalidade não é uma jaula de nascença — é uma lente que se pode trocar quando quiser."},
      {"ic":"sword","t":"Falta Coragem, Não Capacidade","emph":"Coragem","b":"As pessoas não mudam não por incapacidade, mas porque o estilo atual, mesmo reclamado, é <strong>conhecido e confortável</strong> — e o novo é puro escuro. Permanecer é escolha ativa, disfarçada de “é assim que eu sou”. Mudar é abrir mão do familiar e pagar o preço do desconhecido. O obstáculo nunca foi falta de jeito: é falta de coragem.","tip":"<strong>Cuidado:</strong> a inércia não é ausência de decisão — é uma decisão silenciosa de continuar onde dói menos.","warn":True},
    ],
  "lessons_title":"Lições-Chave da Primeira Noite (II)",
  "lessons":["Você fabrica a emoção para um fim; ela não te governa.","'Personalidade' é estilo de vida escolhido — e re-escolhível agora.","O que falta para mudar não é capacidade, é coragem."]},

 {"slug":"ch03-todo-problema-interpessoal","sub":"SEGUNDA NOITE: Todo Problema é Interpessoal",
  "intro":"Não existe sofrimento puramente individual: toda angústia humana — inclusive a inferioridade — nasce das relações com os outros. Sentir-se inferior é saudável; o que adoece é transformar isso em desculpa ou em fachada de superioridade.",
  "cards":[
      {"ic":"link","t":"Não Há Sofrimento numa Ilha Deserta","emph":"Ilha Deserta","b":"Solidão, vergonha, ansiedade, inferioridade — nenhum desses tormentos existiria num universo de uma só pessoa. Só ganham forma porque <strong>existem outros</strong> diante de quem nos medimos. Adler vai ao extremo: todo problema humano é, no fundo, de relação. E é boa notícia — pois a saída para a dor mora exatamente ali, nas relações.","tip":"<strong>Modelo mental:</strong> se a ferida nasce no entre-nós, é no entre-nós que ela se cura — não no isolamento."},
      {"ic":"layers","t":"Inferioridade é Gasolina — o Complexo é o Álibi","emph":"o Álibi","b":"Sentir-se aquém de um ideal é universal e <strong>saudável</strong>: é o combustível do crescimento. O complexo de inferioridade é outra coisa — pegar esse sentimento e torná-lo desculpa para não tentar: “se eu não fosse baixo, conseguiria amar”. Mas a altura é fato neutro; gente baixa casa feliz. O que trava não é o fato — é o uso que se faz dele.","tip":"<strong>Como aplicar:</strong> desconfie de toda frase no formato “A, então não posso B” — quase sempre é álibi, não causa.","wide":True},
      {"ic":"mask","t":"Quem Se Gaba Está Escondendo","emph":"Escondendo","b":"A inferioridade não enfrentada vira fachada: a pessoa se finge superior, exibe poder, conquistas, marcas. Há uma versão mais perversa — exibir as próprias <strong>desgraças</strong>, “ninguém sofre como eu”, usando a dor como cetro para mandar na relação. Vanglória e vitimismo são a mesma máscara: duas fugas do buraco que ninguém quis encarar.","tip":"<strong>Sinal de alerta:</strong> quanto mais alguém ostenta — sucesso ou sofrimento — mais insegurança costuma estar tapando.","warn":True},
      {"ic":"target","t":"A Única Régua Legítima É Você de Ontem","emph":"Você de Ontem","b":"A meta sadia não é superar os outros, é superar o <strong>eu de ontem</strong>. Medir-se contra os demais fabrica inimigos onde poderia haver companheiros, e converte cada conquista alheia numa ferida sua. Basta caminhar para frente, no seu passo. Quem corre olhando para o lado tropeça — e numa corrida que ninguém pediu para disputar.","tip":"<strong>Regra:</strong> a comparação só é fértil quando o adversário é a sua própria versão de ontem."},
    ],
  "lessons_title":"Lições-Chave da Segunda Noite (I)",
  "lessons":["Todo problema, no fundo, é de relação — não há angústia numa ilha deserta.","Sentir-se inferior é saudável; usá-lo como desculpa (complexo) é fuga.","Quem se gaba ou exibe a própria desgraça está escondendo inferioridade."]},

 {"slug":"ch04-competicao-e-poder","sub":"SEGUNDA NOITE: Competição e Lutas de Poder",
  "intro":"Quando a vida vira competição, o mundo vira campo de batalha e todos viram inimigos. Sair da competição — e recusar-se a entrar em lutas de poder — transforma os outros de rivais em companheiros.",
  "cards":[
      {"ic":"mountain","t":"Saia da Competição e o Mundo Muda de Cor","emph":"Competição","b":"Quem compete mede a própria vitória pela derrota alheia — e nunca descansa: cada conquista do outro vira ferida sua, cada sala vira ringue. Adler propõe caminhar para frente sem comparar-se com ninguém. <strong>Largue a competição e os rivais viram companheiros</strong>: o mesmo mundo que era campo de batalha se enche de gente que torce por você.","tip":"<strong>Modelo mental:</strong> a horizontal não tem pódio — quando ninguém precisa perder, todos cabem do mesmo lado."},
      {"ic":"sword","t":"A Provocação É um Convite Para o Ringue","emph":"o Ringue","b":"Quem te ataca ou te insulta não busca a verdade — busca arrastar você para uma <strong>luta de poder</strong> onde possa vencer. O erro não está em ter razão; está em entrar na briga. Mesmo que você “ganhe” humilhando o outro, a relação perde e a vingança já se arma no silêncio. A saída adleriana é simples e difícil: não pise no ringue.","tip":"<strong>Como aplicar:</strong> separe “ter razão” de “fazer o outro admitir que errou” — perseguir o segundo é declarar guerra.","warn":True},
      {"ic":"scale","t":"Admitir o Erro Não É Perder","emph":"Não É Perder","b":"Reconhecer um equívoco, pedir desculpas, sair de uma briga — nada disso é derrota, embora o orgulho jure que é. Quem precisa vencer toda discussão confunde recuar da briga com recuar da verdade. <strong>São coisas distintas: a verdade fica de pé mesmo quando você sai do ringue.</strong> A derrota real é virar refém do próprio orgulho.","tip":"<strong>Regra:</strong> admitir erro é força tranquila; o que aprisiona é a necessidade de provar que o outro está errado."},
    ],
  "lessons_title":"Lições-Chave da Segunda Noite (II)",
  "lessons":["Saia da competição: a régua é você de ontem, não o outro.","Diante da provocação, recuse a luta de poder — não entre no ringue.","Admitir erro ou desculpar-se é força, não derrota."]},

 {"slug":"ch05-separacao-de-tarefas","sub":"TERCEIRA NOITE: A Separação de Tarefas",
  "intro":"A chave prática para desembaraçar quase todo conflito interpessoal é uma pergunta só: 'de quem é a tarefa?'. Cuide da sua e não invada a do outro — nem deixe que invadam a sua.",
  "cards":[
      {"ic":"scale","t":"Uma Pergunta Desembaraça Quase Tudo","emph":"Uma Pergunta","b":"Antes de se meter em qualquer conflito, faça a única pergunta que importa: <strong>“de quem é esta tarefa?”</strong>. O critério é frio — quem arca, no fim, com as consequências? Esse é o dono. A conduta então é só uma: faça a sua parte, não invada a do outro, não deixe invadirem a sua. Quase toda dor interpessoal nasce de cruzar essa fronteira.","tip":"<strong>Como aplicar:</strong> rastreie a consequência até o seu dono — é ele, não você, quem deve carregar e decidir aquela tarefa.","wide":True},
      {"ic":"leaf","t":"Você Leva o Cavalo à Água — Não o Obriga a Beber","emph":"à Água","b":"Separar tarefas não é abandono. Você pode oferecer ajuda e deixar claro que está disponível — mas a decisão e a execução pertencem ao <strong>dono</strong>. O pai que vigia, cobra e briga porque o filho não estuda só estraga a relação e carrega um peso que não é seu. Respeitar a fronteira é o gesto mais amoroso: ajudar quando se pede.","tip":"<strong>Cuidado:</strong> não confunda separar tarefas com largar mão — é fincar o limite e seguir presente para quando chamarem.","warn":True},
      {"ic":"key","t":"O Que Pensam de Você É Tarefa Deles","emph":"Deles","b":"O juízo que os outros fazem de você não está sob seu controle — e, por não estar, <strong>não é seu para carregar</strong>. Aprovar ou reprovar é tarefa deles; viver com retidão é a sua. Esta é a dobradiça de toda a obra: solte o veredito alheio e abre-se a porta da liberdade — a coragem de, eventualmente, ser desprezado sem desabar.","tip":"<strong>Regra:</strong> faça a sua tarefa com integridade e devolva ao outro a tarefa dele — o que ele acha de você."},
    ],
  "lessons_title":"Lições-Chave da Terceira Noite (I)",
  "lessons":["Em todo conflito, pergunte primeiro: 'de quem é a tarefa?'.","O dono é quem arca com as consequências — faça a sua, não invada a alheia.","O que os outros pensam de você é tarefa deles; libere-se desse peso."]},

 {"slug":"ch06-liberdade-e-reconhecimento","sub":"TERCEIRA NOITE: Liberdade e a Coragem de Ser Desprezado",
  "intro":"Buscar reconhecimento é uma armadilha: quem vive para satisfazer expectativas alheias vive a vida dos outros. A liberdade tem um preço — e esse preço é a coragem de ser desprezado por alguém.",
  "cards":[
      {"ic":"gap","t":"O Desejo de Aprovação É uma Armadilha","emph":"Armadilha","b":"Querer ser reconhecido parece nobre, mas escraviza: você se molda às expectativas dos outros e abre mão da própria vida. E a armadilha tem dois dentes — quem vive para agradar acaba também <strong>exigindo</strong> que os outros correspondam às suas expectativas. Você não nasceu para satisfazer ninguém; nem ninguém para satisfazer você.","tip":"<strong>Sinal de alerta:</strong> quando a decisão sai de “o que vão achar?” em vez de “qual é a minha tarefa?”, a coleira já está no pescoço.","warn":True},
      {"ic":"sword","t":"Não Buscar Ser Desprezado — Mas Não Temer Sê-lo","emph":"Não Temer","b":"Ser livre é aceitar a possibilidade de ser malvisto por alguém. Não é provocar antipatia, nem viver <strong>contra</strong> as expectativas — isso ainda seria deixá-las governar você. É não temer a desaprovação a ponto de trair quem você é. Sem essa coragem não há liberdade, e sem liberdade não há felicidade. Daqui vem o título do livro.","tip":"<strong>Modelo mental:</strong> se ninguém nunca te desaprova, é bem provável que você esteja vivendo a vida que os outros escreveram."},
      {"ic":"lens","t":"A Regra das Dez Pessoas","emph":"Dez Pessoas","b":"Por mais íntegro que você seja, de cada dez pessoas <strong>uma</strong> vai te desprezar faça o que fizer, sete serão neutras, e uma ou duas viram amigas de verdade. Gastar a vida convertendo o único desaprovador é sacrificar o todo por uma fração — e ainda falhar, pois o juízo dele nunca foi seu. Viva para quem importa.","tip":"<strong>Como aplicar:</strong> a opinião do desaprovador é tarefa dele; não a gerencie — invista nos um ou dois que ficam."},
    ],
  "lessons_title":"Lições-Chave da Terceira Noite (II)",
  "lessons":["Viver para a aprovação alheia é viver a vida dos outros.","Liberdade tem preço: ser, eventualmente, desprezado — e seguir em frente.","O juízo do outro sobre você é tarefa dele; a sua é viver com retidão."]},

 {"slug":"ch07-relacoes-horizontais","sub":"QUARTA NOITE: Relações Horizontais — Encorajar, Não Elogiar",
  "intro":"Elogio e punição são manipulação vertical (de cima para baixo). Adler propõe relações horizontais — 'diferentes, mas iguais' — e, no lugar do elogio, o encorajamento.",
  "cards":[
      {"ic":"layers","t":"Diferentes, mas Iguais","emph":"Iguais","b":"A relação vertical é hierarquia de valor: alguém se coloca acima, julga, premia e pune — e gera dependência. Adler propõe a horizontal: <strong>“diferentes, mas iguais”</strong>. Pai e filho, chefe e equipe têm papéis distintos, mas nenhum vale mais que o outro. A virada não é tratar todos igual; é tratá-los como iguais em valor.","tip":"<strong>Como aplicar:</strong> colabore lado a lado em vez de comandar de cima — mesmo onde o papel te dá autoridade.","wide":True},
      {"ic":"bubble","t":"Diga “Obrigado”, Não “Muito Bem”","emph":"“Obrigado”","b":"O elogio — “que bom menino!” — soa generoso, mas é um veredito de cima para baixo: quem tem capacidade avaliando quem supostamente não tem. Ele alimenta a fome de aprovação que adoece. A alternativa horizontal é <strong>agradecer</strong>: “obrigado, isso me ajudou”. O foco sai do julgamento e pousa na contribuição entre iguais.","tip":"<strong>Regra:</strong> “muito bem” é vertical e cria dependência; “obrigado” é horizontal e devolve dignidade ao outro."},
      {"ic":"spark","t":"“Sou Útil” Constrói o Que o Elogio Corrói","emph":"“Sou Útil”","b":"A criança que põe a mesa e ouve “obrigado, você me ajudou” não aprende a caçar elogios — aprende que <strong>é útil</strong>. É esse senso de utilidade, não o aplauso, que ergue coragem e valor próprio por dentro. Encorajar é reconhecer contribuição real para o outro agir por si — não bajular: o elogio vazio prende; o agradecimento liberta.","tip":"<strong>Cuidado:</strong> encorajar não é bajular — reconheça a contribuição verdadeira, jamais lisonjeie para conduzir o outro.","warn":True},
    ],
  "lessons_title":"Lições-Chave da Quarta Noite (I)",
  "lessons":["Troque relações verticais (premiar/punir) por horizontais ('diferentes, mas iguais').","Em vez de elogiar, encoraje: agradeça e reconheça a contribuição.","O valor próprio nasce de 'sou útil', não de 'fui aprovado'."]},

 {"slug":"ch08-sentimento-de-comunidade","sub":"QUARTA NOITE: O Sentimento de Comunidade",
  "intro":"A bússola de Adler para boas relações é o sentimento de comunidade (Gemeinschaftsgefühl): deslocar o foco do apego a si mesmo para o interesse pelos outros, sentindo-se parte de algo maior.",
  "cards":[
      {"ic":"constellation","t":"A Cura da Relação Está na Relação","emph":"na Relação","b":"Se todo problema é interpessoal, é nas relações que mora a saída — e seu nome em Adler é <strong>sentimento de comunidade</strong> (Gemeinschaftsgefühl): sentir os outros como companheiros e a si como parte de um todo. Não é afeto que aparece sozinho; é a bússola final, o ponto onde a angústia nascida entre as pessoas se desfaz entre as pessoas.","tip":"<strong>Modelo mental:</strong> a ferida que veio do “entre-nós” só fecha no “entre-nós” — nunca no isolamento orgulhoso.","wide":True},
      {"ic":"pivot","t":"Saia do Centro do Mundo","emph":"do Centro","b":"Quem vive em “como me veem? o que eu ganho?” está preso no próprio eu e exige que tudo gire em torno de si. A virada é trocar a pergunta: de <strong>“o que esta pessoa faz por mim?”</strong> para “o que eu posso dar a esta comunidade?”. Você não é o centro do mundo — é um membro dele. E pertencer não se recebe; se conquista contribuindo.","tip":"<strong>Como aplicar:</strong> diante de cada vínculo, pergunte o que pode oferecer antes de medir o que vai receber."},
      {"ic":"steps","t":"Nenhum Grupo É o Universo Inteiro","emph":"o Universo Inteiro","b":"Quando o emprego, a escola ou o casamento parecem prisão sem saída, o sufoco vem de tratar uma comunidade pequena como o mundo. Mas há sempre uma <strong>comunidade maior</strong> — a sociedade, a humanidade, o futuro. Ouvir a voz dela devolve a liberdade de discordar, mudar ou sair. A cela só existe enquanto você crê que ela é o universo.","tip":"<strong>Cuidado:</strong> confundir um grupo imediato com o mundo inteiro é exatamente o que faz você se submeter a tudo.","warn":True},
    ],
  "lessons_title":"Lições-Chave da Quarta Noite (II)",
  "lessons":["A meta das relações é o sentimento de comunidade: sentir-se parte, ver os outros como companheiros.","Saia do apego a si (o centro) para o interesse pelos outros (a parte do todo).","Quando um grupo aprisiona, escute a comunidade maior — ela devolve a liberdade."]},

 {"slug":"ch09-aqui-e-agora","sub":"QUINTA NOITE: A Tríade e o Viver o Aqui e Agora",
  "intro":"A coragem de ser feliz se sustenta em três pilares — autoaceitação, confiança nos outros e contribuição — e se realiza vivendo intensamente o aqui e agora, não num futuro idealizado.",
  "cards":[
      {"ic":"constellation","t":"Os Três Pilares que Se Sustentam em Roda","emph":"Três Pilares","b":"A coragem de ser feliz repousa em três apoios que se alimentam em ciclo. <strong>Autoaceitação</strong>: aceitar o eu que não consegue (mudar o mutável, aceitar o imutável). <strong>Confiança incondicional</strong>: confiar sem garantias; trair é tarefa do outro. <strong>Contribuição</strong>: agir pelo bem de todos. Aceito-me, então confio; confio, então contribuo; sinto-me útil — e me aceito mais.","tip":"<strong>Como aplicar:</strong> não force os três de uma vez — acione um, e o ciclo puxa os outros sozinho.","wide":True},
      {"ic":"spark","t":"O Valor Vem de “Sou Útil”, Não de “Fui Aprovado”","emph":"“Sou Útil”","b":"É contribuir que dá o <strong>sentido de valor</strong> — “sou bom para alguém” — fonte real do valor próprio, não o aplauso. Repare na inversão: a aprovação vem de fora e te deixa refém; a utilidade nasce do seu gesto e ninguém tira. Por isso o foco muda de “o que eu tenho” para “como uso o que tenho” — a coragem mora no uso, não no estoque.","tip":"<strong>Regra:</strong> sentir-se útil sustenta a coragem por dentro; caçar aprovação a corrói por fora."},
      {"ic":"clock","t":"A Vida É Série de Instantes, Não uma Reta","emph":"Série de Instantes","b":"A vida não é uma linha que sobe rumo a um pico: é uma sucessão de <strong>agoras</strong>, pontos soltos como passos de uma dança. Quem trata o presente como “vida em preparação” — “serei feliz quando me formar, for promovido, casar” — nunca chega, pois adiar a felicidade é deixar de viver. Não há ensaio: o instante já é a apresentação inteira.","tip":"<strong>Cuidado:</strong> fixar-se no passado (trauma) ou no futuro (metas) apaga o único lugar onde se vive de fato — o aqui.","warn":True},
      {"ic":"constellation","t":"Aponte para a Estrela-Guia e Cada Passo Já É Pleno","emph":"Estrela-Guia","b":"Não há sentido universal entregue pronto: o sentido da vida é o que <strong>você dá a ela</strong>. Basta apontar para a estrela-guia da contribuição aos outros — enquanto se caminha em sua direção, qualquer instante já está completo, mesmo sem chegar a lugar nenhum. Dance a vida em vez de corrê-la: o valor está em cada passo, não na chegada.","tip":"<strong>Modelo mental:</strong> a estrela-guia não é um destino a alcançar — é a direção que torna pleno o agora."},
    ],
  "lessons_title":"Lições-Chave da Quinta Noite",
  "lessons":["A coragem se ergue sobre a tríade: aceitar-se, confiar nos outros, contribuir.","Contribuir (sentir-se útil) é a fonte real do valor próprio — não a aprovação.","A vida é série de instantes: viva o aqui e agora, com a contribuição por estrela-guia."]},
]
