# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'A Coragem de Não Agradar'
(Ichiro Kishimi & Fumitake Koga — The Courage to Be Disliked), sobre a psicologia
individual de Alfred Adler. Diálogo Filósofo × Jovem em 5 noites.
Frameworks canônicos: teleologia vs. etiologia ('o trauma não existe'); todo
problema é interpessoal; sentimento × complexo de inferioridade/superioridade;
a separação de tarefas ('de quem é a tarefa?'); o desejo de reconhecimento como
armadilha; relações horizontais (encorajar, não elogiar); sentimento de comunidade
(Gemeinschaftsgefühl); a tríade autoaceitação + confiança + contribuição; o aqui
e agora; a coragem de ser desprezado. Base: frameworks amplamente documentados —
não reproduz o texto."""

BOOK = {
 "title": "A Coragem de Não Agradar",
 "author": "Ichiro Kishimi & Fumitake Koga",
 "header_light": "A CORAGEM DE",
 "header_bold": "NÃO AGRADAR",
 "subtitle": "VISÃO GERAL · CINCO NOITES PARA DESAMARRAR UMA VIDA",
 "intro": "Cinco noites, dois homens e uma tese que soa a heresia. Um Jovem cético chega à casa do Filósofo para refutá-lo, e sai dela outro. O Filósofo não consola: ele desmonta. O passado não te governa, garante; ninguém é refém do que sofreu; e a felicidade não se conquista, se decide. Adler — o terceiro gigante da psicologia, eclipsado por Freud e Jung — volta pela porta de um diálogo socrático que machuca antes de libertar. <em>E se tudo o que você chama de destino fosse apenas uma desculpa bem ensaiada?</em>",
 "description": "O fenômeno de Kishimi e Koga que devolveu Alfred Adler ao mundo, em forma de embate socrático. Vira do avesso o evangelho do trauma: não somos empurrados pelo passado, somos puxados por um objetivo presente. Daí desdobra a separação de tarefas, a fuga da armadilha do reconhecimento e a tríade que sustenta a felicidade — autoaceitação, confiança, contribuição. No fim, uma só promessa, desconfortável e libertadora: a liberdade custa o preço de, às vezes, ser desprezado.",
 "tags": ["Psicologia", "Adler", "Autoconhecimento"],
 "progress": "9 Capítulos",
 "cover": "assets/coragem-de-nao-agradar-cover.png",
 "overview_cards": [
   {"ic":"fork","t":"Teleologia vs. Etiologia — \"o trauma não existe\"","b":"Freud aponta para trás, à <strong>causa</strong> ('você é assim por causa do que sofreu') — e, dito isso, tranca a porta. Adler aponta para o presente, ao <strong>objetivo</strong> ('você age assim para conseguir algo'). A experiência não te empurra; você é que lhe dá sentido. 'O trauma não existe' não zomba da dor: nega que ela te <strong>condene</strong> a um único destino.","tip":"<strong>Modelo mental:</strong> troque 'por quê?' por 'para quê?'. A causa é uma cela; o objetivo, uma chave.","wide":True},
   {"ic":"scale","t":"A Separação de Tarefas","b":"Quase todo nó interpessoal se desata com uma só pergunta: <strong>'de quem é esta tarefa?'</strong>. O critério é frio — <strong>quem arca com as consequências</strong>. Cuide da sua, não invada a do outro nem deixe invadirem a sua. O que pensam de você não está na sua mão: é <strong>tarefa deles</strong>.","tip":"<strong>Como aplicar:</strong> antes de entrar num conflito, siga a consequência até o dono — é ele que decide, não você.","wide":True},
   {"ic":"sword","t":"A Coragem de Ser Desprezado","b":"Viver para o aplauso alheio é viver a vida que os outros escreveram. O desejo de reconhecimento parece nobre e é uma coleira. A liberdade cobra um preço: aceitar ser, de vez em quando, <strong>malvisto por alguém</strong>. Não se trata de buscar a antipatia — e sim de não tremer diante dela.","tip":"<strong>Regra:</strong> se ninguém jamais te desaprova, desconfie — talvez a vida que você vive não seja a sua."},
   {"ic":"constellation","t":"A Tríade da Felicidade","b":"A coragem se firma em três apoios que giram em roda: <strong>autoaceitação</strong> (aceitar o eu que não consegue), <strong>confiança nos outros</strong> (sem exigir garantia) e <strong>contribuição</strong> ('sou útil a alguém'). O que dá valor a você não é ser aprovado de fora — é sentir-se útil por dentro.","tip":"<strong>Modelo mental:</strong> aceito-me, então confio; confio, então contribuo; sinto-me útil — e me aceito mais."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-trauma-nao-existe","sub":"PRIMEIRA NOITE: O Trauma Não Existe",
  "intro":"O Jovem chega armado de Freud: somos o que o passado fez de nós. O Filósofo desarma-o com uma frase intolerável — o trauma não existe. Não que a dor não tenha sido real; é que a dor não dá ordens. Adler explica a conduta pelo objetivo de agora (teleologia), não pela causa de trás (etiologia). Quem dá sentido à experiência somos nós — e o que se dá, pode-se redar.",
  "cards":[
      {"ic":"fork","t":"“Por Quê?” Prende, “Para Quê?” Liberta","emph":"“Para Quê?”","b":"Freud aponta para trás — “você é assim por causa do que te fizeram” — e, ao apontar, fecha o futuro a cadeado. Adler vira a seta para a frente: “você age assim para um fim de agora”. De um golpe, o passado deixa de ser sentença e vira matéria-prima. <strong>Não é o que te aconteceu que escreve a tua vida — é o objetivo que persegues neste instante.</strong>","tip":"<strong>Como aplicar:</strong> ao se flagrar num “não posso por causa de X”, pergunte “que objetivo esse ‘não posso’ anda me prestando?”."},
      {"ic":"key","t":"Os Mesmos Tijolos, Casa ou Prisão","emph":"Casa ou Prisão","b":"A experiência crua não fabrica destino: o que decide é o <strong>significado</strong> que você empresta a ela. Por isso dois irmãos do mesmo inferno tomam rumos opostos — um se tranca, o outro floresce. Os mesmos tijolos levantam uma cela ou um lar; quem assenta cada um é você, hoje, e não a criança que você foi.","tip":"<strong>Modelo mental:</strong> o passado é o material; a planta da casa, não. Quem assina o projeto é você, agora."},
      {"ic":"eye","t":"“O Trauma Não Existe” — o Que Isso Não Diz","emph":"Não Existe","b":"Adler não finge que horrores não acontecem, nem ri da ferida de ninguém. Ele nega que a ferida te <strong>obrigue</strong> a um único caminho. O recluso não se tranca porque tem medo: ele fabrica o medo para ter licença de não sair — e seguir sendo cuidado. Atrás de cada “não posso” há um propósito que o “não posso” serve calado.","tip":"<strong>Cuidado:</strong> “não existe” não significa “não importa”; significa “não te acorrenta a um só destino”.","warn":True},
    ],
  "lessons_title":"Lições-Chave da Primeira Noite (I)",
  "lessons":["O que decide a sua vida não é o que sofreu, mas o sentido que você dá ao que sofreu.","Todo 'não posso' costuma esconder um 'não quero' a serviço de algum objetivo.","Aceitar a teleologia é aceitar a sentença mais incômoda: a mudança é possível agora."]},

 {"slug":"ch02-objetivo-e-estilo-de-vida","sub":"PRIMEIRA NOITE: Objetivos, Emoções e Estilo de Vida",
  "intro":"Se o passado não manda, manda a emoção? O Filósofo nega de novo. Não somos tomados pela raiva — nós a acendemos a serviço de um fim. E o que chamamos de 'personalidade' é apenas um estilo de vida que escolhemos um dia e teimamos em repetir. A conclusão desconcerta o Jovem: o que falta para mudar nunca foi capacidade — é coragem.",
  "cards":[
      {"ic":"spark","t":"Você Não É Tomado pela Raiva — Você a Liga","emph":"Você a Liga","b":"A mãe esbraveja com a filha; o telefone toca, é a escola, e ela atende com voz de seda — desliga e volta a gritar. A raiva não a engoliu: ela a <strong>ligou e desligou</strong> conforme convinha. Emoção não é onda que vem de fora e te arrasta; é a ferramenta que você saca para impor a vontade. Ninguém é refém do que sente — a gente usa o que sente.","tip":"<strong>Como aplicar:</strong> ao se sentir “tomado”, pergunte “o que eu quero conseguir gritando — ou me calando — agora mesmo?”."},
      {"ic":"pivot","t":"Você Não Tem um Temperamento, Você Usa um Estilo","emph":"Usa um Estilo","b":"“Estilo de vida” é como Adler chama a personalidade — escolhida lá pelos dez anos e, por ter sido escolha, <strong>reescolhível agora mesmo</strong>. A diferença é tudo: “eu sou tímido” é cadeia perpétua; “eu venho usando a timidez para fugir da rejeição” é uma porta. Trocar o verbo de “ser” por “usar” devolve a chave à tua mão.","tip":"<strong>Modelo mental:</strong> personalidade não é jaula de nascença — é uma lente, e lente a gente troca quando enxerga torto."},
      {"ic":"sword","t":"Falta Coragem, Não Capacidade","emph":"Coragem","b":"Ninguém deixa de mudar por incapacidade. Não muda porque o estilo de hoje, por mais que reclame dele, é <strong>conhecido e confortável</strong> — e o amanhã é puro escuro. Ficar é uma decisão ativa, disfarçada de “eu sou assim”. Mudar é largar o familiar e pagar a conta do desconhecido. O obstáculo nunca foi jeito: é coragem.","tip":"<strong>Cuidado:</strong> inércia não é ausência de escolha — é a escolha silenciosa de continuar onde dói menos.","warn":True},
    ],
  "lessons_title":"Lições-Chave da Primeira Noite (II)",
  "lessons":["A emoção é ferramenta que você ergue para um fim — não dona que te governa.","'Personalidade' é estilo de vida escolhido um dia; logo, reescolhível neste.","Quem não muda não carece de capacidade — carece de coragem para o desconhecido."]},

 {"slug":"ch03-todo-problema-interpessoal","sub":"SEGUNDA NOITE: Todo Problema é Interpessoal",
  "intro":"O Filósofo desfere a tese mais larga da noite: não existe angústia puramente sua. Solidão, vergonha, inferioridade — toda dor humana só ganha forma porque há outros por perto. Sentir-se aquém é saudável, é gasolina para crescer. Adoecer é outra coisa: é transformar o sentimento em desculpa para não tentar, ou em fachada para parecer maior do que se é.",
  "cards":[
      {"ic":"link","t":"Não Há Sofrimento numa Ilha Deserta","emph":"Ilha Deserta","b":"Solidão, vergonha, ansiedade, inferioridade — nenhum desses tormentos sobreviveria num mundo de uma só pessoa. Eles só nascem porque <strong>há outros</strong> diante de quem nos medimos. Adler leva ao extremo: no fundo, todo problema é de relação. E isso é alívio, não condenação — pois a saída para a dor mora exatamente onde ela começou.","tip":"<strong>Modelo mental:</strong> ferida que nasce no entre-nós só fecha no entre-nós; o isolamento orgulhoso não cura, só anestesia."},
      {"ic":"layers","t":"Inferioridade é Gasolina — o Complexo é o Álibi","emph":"o Álibi","b":"Sentir-se aquém do ideal é universal e <strong>saudável</strong>: é o que faz a gente crescer. O complexo de inferioridade é o desvio — pegar esse sentimento e transformá-lo em atestado de impossibilidade: “se eu não fosse baixo, conseguiria amar”. Mas a altura é um fato neutro; gente baixa casa feliz. O que trava nunca é o fato — é o uso que você faz dele.","tip":"<strong>Como aplicar:</strong> desconfie de toda frase no molde “A, logo não posso B”; quase sempre é álibi vestido de causa.","wide":True},
      {"ic":"mask","t":"Quem Se Gaba Está Escondendo","emph":"Escondendo","b":"A inferioridade que ninguém encarou vira fachada: o sujeito banca o superior, exibe poder, títulos, marcas. Há uma versão mais torta — desfilar as próprias <strong>desgraças</strong>, “ninguém sofre como eu”, e empunhar a dor como cetro para mandar na relação. Vaidade e vitimismo são a mesma máscara: duas fugas do mesmo buraco não encarado.","tip":"<strong>Sinal de alerta:</strong> quanto mais alguém ostenta — sucesso ou sofrimento — mais costuma estar tapando um vazio por baixo.","warn":True},
      {"ic":"target","t":"A Única Régua Legítima É Você de Ontem","emph":"Você de Ontem","b":"A meta sadia não é passar os outros, é passar o <strong>você de ontem</strong>. Medir-se pelos demais fabrica inimigos onde caberiam companheiros e transforma cada vitória alheia em ferida sua. Basta caminhar para a frente, no seu passo. Quem corre olhando para o lado tropeça — e ainda numa corrida que ninguém pediu para disputar.","tip":"<strong>Regra:</strong> comparação só é fértil quando o adversário é a sua própria versão de ontem; o resto é veneno."},
    ],
  "lessons_title":"Lições-Chave da Segunda Noite (I)",
  "lessons":["No fundo, todo problema é de relação — não existe angústia numa ilha deserta.","Sentir-se inferior é combustível saudável; virá-lo desculpa (o complexo) é fuga disfarçada.","Quem se gaba — de sucesso ou de desgraça — está tapando a inferioridade que não quis encarar."]},

 {"slug":"ch04-competicao-e-poder","sub":"SEGUNDA NOITE: Competição e Lutas de Poder",
  "intro":"Faça da vida uma competição e o mundo inteiro vira campo de batalha — cada rosto, um rival; cada sala, um ringue. O Filósofo mostra a saída pela porta oposta: largar a disputa e recusar a luta de poder. No instante em que ninguém precisa perder para você ganhar, os adversários se descobrem companheiros e o mundo muda de cor.",
  "cards":[
      {"ic":"mountain","t":"Saia da Competição e o Mundo Muda de Cor","emph":"Competição","b":"Quem compete só mede a própria vitória pela derrota do outro — e nunca descansa: cada conquista alheia abre uma ferida, cada sala vira arena. Adler propõe caminhar para a frente sem se comparar a ninguém. <strong>Solte a competição e os rivais viram companheiros</strong>: o mesmo mundo que era trincheira se enche de gente torcendo por você.","tip":"<strong>Modelo mental:</strong> na relação horizontal não há pódio — quando ninguém precisa perder, todos cabem do mesmo lado."},
      {"ic":"sword","t":"A Provocação É um Convite Para o Ringue","emph":"o Ringue","b":"Quem te ataca não procura a verdade — procura te arrastar para uma <strong>luta de poder</strong> onde possa sair por cima. O erro não é ter razão; é subir no ringue. Mesmo que você “ganhe” humilhando o outro, a relação perde e a vingança já começa a se armar no silêncio. A saída adleriana é simples de dizer e dura de fazer: não pise na lona.","tip":"<strong>Como aplicar:</strong> separe “ter razão” de “fazer o outro confessar que errou” — caçar o segundo é declarar guerra.","warn":True},
      {"ic":"scale","t":"Admitir o Erro Não É Perder","emph":"Não É Perder","b":"Reconhecer um engano, pedir desculpas, sair de uma briga — nada disso é derrota, por mais que o orgulho jure o contrário. Quem precisa vencer toda discussão confunde recuar da briga com recuar da verdade. <strong>São coisas diferentes: a verdade segue de pé mesmo quando você desce do ringue.</strong> A derrota de verdade é virar refém do próprio orgulho.","tip":"<strong>Regra:</strong> admitir o erro é força serena; o que aprisiona é a fome de provar que o outro está errado."},
    ],
  "lessons_title":"Lições-Chave da Segunda Noite (II)",
  "lessons":["Saia da competição: a única régua legítima é o você de ontem, nunca o outro.","Diante da provocação, recuse a luta de poder — vencer um insulto é perder a relação.","Admitir o erro e pedir desculpas é força tranquila; o refém é quem precisa ter sempre razão."]},

 {"slug":"ch05-separacao-de-tarefas","sub":"TERCEIRA NOITE: A Separação de Tarefas",
  "intro":"Aqui o Filósofo entrega a ferramenta mais afiada da obra — e a mais simples. Diante de qualquer conflito, uma só pergunta desfaz o nó: 'de quem é esta tarefa?'. O critério é frio: quem arca com as consequências. Cuide da sua, não invada a do outro nem deixe invadirem a sua. Parece pouco; é quase tudo.",
  "cards":[
      {"ic":"scale","t":"Uma Pergunta Desembaraça Quase Tudo","emph":"Uma Pergunta","b":"Antes de entrar em qualquer conflito, faça a única pergunta que importa: <strong>“de quem é esta tarefa?”</strong>. O critério é gelado — quem, no fim, arca com as consequências? Esse é o dono. A conduta então é uma só: faça a sua parte, não invada a do outro, não deixe invadirem a sua. Quase toda dor interpessoal nasce de pisar essa fronteira.","tip":"<strong>Como aplicar:</strong> siga a consequência até o dono — é ele, não você, quem carrega e decide aquela tarefa.","wide":True},
      {"ic":"leaf","t":"Você Leva o Cavalo à Água — Não o Obriga a Beber","emph":"à Água","b":"Separar tarefas não é virar as costas. Você pode oferecer ajuda e deixar a porta aberta — mas a decisão e o esforço pertencem ao <strong>dono</strong>. O pai que vigia, cobra e briga porque o filho não estuda só azeda a relação e carrega um fardo que não é dele. Respeitar a fronteira é o gesto mais amoroso: estar por perto e ajudar quando, e se, pedirem.","tip":"<strong>Cuidado:</strong> não confunda separar tarefas com abandonar — é fincar o limite e seguir disponível para quando te chamarem.","warn":True},
      {"ic":"key","t":"O Que Pensam de Você É Tarefa Deles","emph":"Deles","b":"O juízo que os outros fazem de você foge ao seu controle — e, por escapar, <strong>não é seu para carregar</strong>. Aprovar ou reprovar é tarefa deles; viver com retidão é a sua. Esta é a dobradiça de todo o livro: solte o veredito alheio e a porta da liberdade se abre — a coragem de, às vezes, ser desprezado sem desabar.","tip":"<strong>Regra:</strong> faça a sua tarefa com integridade e devolva ao outro a dele — o que ele pensa de você não te pertence."},
    ],
  "lessons_title":"Lições-Chave da Terceira Noite (I)",
  "lessons":["Em todo conflito, pergunte antes de tudo: 'de quem é esta tarefa?'.","O dono é quem arca com as consequências — faça a sua e não invada a alheia.","O que os outros pensam de você é tarefa deles; soltar esse peso é o começo da liberdade."]},

 {"slug":"ch06-liberdade-e-reconhecimento","sub":"TERCEIRA NOITE: Liberdade e a Coragem de Ser Desprezado",
  "intro":"O Jovem pergunta o que custa ser livre, e o Filósofo dá a resposta que dá nome ao livro. Buscar reconhecimento parece virtude e é cativeiro: quem vive para satisfazer a expectativa alheia vive a vida dos outros. A liberdade tem um preço — e o preço é a coragem de ser desprezado por alguém. Não procurar a antipatia; apenas não tremer diante dela.",
  "cards":[
      {"ic":"gap","t":"O Desejo de Aprovação É uma Armadilha","emph":"Armadilha","b":"Querer ser reconhecido soa nobre e acorrenta: você se molda à expectativa dos outros e abre mão da própria vida. E a armadilha morde dos dois lados — quem vive para agradar acaba também <strong>exigindo</strong> que os outros lhe agradem em troca. Você não veio ao mundo para satisfazer ninguém; nem ninguém para satisfazer você.","tip":"<strong>Sinal de alerta:</strong> quando a decisão nasce de “o que vão achar?” no lugar de “qual é a minha tarefa?”, a coleira já está no pescoço.","warn":True},
      {"ic":"sword","t":"Não Buscar Ser Desprezado — Mas Não Temer Sê-lo","emph":"Não Temer","b":"Ser livre é aceitar que alguém vá te ver com maus olhos. Não é provocar antipatia, nem viver <strong>contra</strong> a expectativa — isso ainda seria deixá-la te governar pelo avesso. É não temer a desaprovação a ponto de trair quem você é. Sem essa coragem não há liberdade; sem liberdade não há felicidade. Daqui sai o título do livro.","tip":"<strong>Modelo mental:</strong> se ninguém jamais te desaprova, é quase certo que você esteja vivendo a vida que os outros escreveram."},
      {"ic":"lens","t":"A Regra das Dez Pessoas","emph":"Dez Pessoas","b":"Por mais íntegro que você seja, de cada dez pessoas <strong>uma</strong> vai te desprezar faça o que fizer, sete ficarão indiferentes, e uma ou duas serão amigas de verdade. Gastar a vida tentando converter o único desaprovador é sacrificar o todo por uma fração — e ainda fracassar, pois o juízo dele nunca foi seu. Viva para quem fica.","tip":"<strong>Como aplicar:</strong> a opinião do desaprovador é tarefa dele; pare de administrá-la e invista nos um ou dois que ficam."},
    ],
  "lessons_title":"Lições-Chave da Terceira Noite (II)",
  "lessons":["Viver para a aprovação alheia é viver, dia após dia, a vida dos outros.","A liberdade cobra um preço: ser, de vez em quando, desprezado — e seguir caminhando.","O juízo do outro sobre você é tarefa dele; a sua é uma só, viver com retidão."]},

 {"slug":"ch07-relacoes-horizontais","sub":"QUARTA NOITE: Relações Horizontais — Encorajar, Não Elogiar",
  "intro":"O Filósofo derruba um ídolo que ninguém esperava: o elogio. Elogiar e punir são a mesma manobra vertical, de cima para baixo — quem se julga capaz avaliando quem supõe incapaz. Adler propõe a horizontal: 'diferentes, mas iguais'. E, no lugar do “muito bem”, o encorajamento — um simples “obrigado” que devolve dignidade ao outro.",
  "cards":[
      {"ic":"layers","t":"Diferentes, mas Iguais","emph":"Iguais","b":"A relação vertical é hierarquia de valor: alguém se põe acima, julga, premia e pune — e gera dependência. Adler aponta para a horizontal: <strong>“diferentes, mas iguais”</strong>. Pai e filho, chefe e equipe têm papéis distintos, mas nenhum vale mais que o outro. A virada não é tratar todos do mesmo jeito; é tratá-los como iguais em valor.","tip":"<strong>Como aplicar:</strong> colabore lado a lado em vez de comandar de cima — sobretudo onde o papel já te dá autoridade.","wide":True},
      {"ic":"bubble","t":"Diga “Obrigado”, Não “Muito Bem”","emph":"“Obrigado”","b":"O elogio — “que bom menino!” — parece generoso, mas é veredito de cima para baixo: quem se julga capaz avaliando quem supõe incapaz. E alimenta a fome de aprovação que adoece. A alternativa horizontal é <strong>agradecer</strong>: “obrigado, isso me ajudou”. O foco sai do julgamento e pousa na contribuição entre iguais.","tip":"<strong>Regra:</strong> “muito bem” é vertical e cria dependência; “obrigado” é horizontal e devolve estatura ao outro."},
      {"ic":"spark","t":"“Sou Útil” Constrói o Que o Elogio Corrói","emph":"“Sou Útil”","b":"A criança que põe a mesa e ouve “obrigado, você me ajudou” não aprende a caçar aplauso — aprende que <strong>é útil</strong>. É esse senso de utilidade, e não a medalha, que levanta coragem e valor próprio por dentro. Encorajar é reconhecer a contribuição real para o outro agir por si; não é bajular. O elogio vazio prende; o agradecimento solta.","tip":"<strong>Cuidado:</strong> encorajar não é lisonjear — reconheça a contribuição verdadeira, jamais elogie para conduzir o outro.","warn":True},
    ],
  "lessons_title":"Lições-Chave da Quarta Noite (I)",
  "lessons":["Troque o vertical (premiar e punir) pelo horizontal: 'diferentes, mas iguais'.","No lugar do elogio, encoraje — agradeça e reconheça a contribuição entre iguais.","O valor próprio brota de 'sou útil', nunca de 'fui aprovado'."]},

 {"slug":"ch08-sentimento-de-comunidade","sub":"QUARTA NOITE: O Sentimento de Comunidade",
  "intro":"Se todo problema é de relação, é na relação que está a cura — e o Filósofo lhe dá um nome: sentimento de comunidade (Gemeinschaftsgefühl). É a bússola final de Adler: tirar o foco do apego a si mesmo e voltá-lo ao interesse pelos outros, sentindo-se parte de algo maior. Sair do centro do mundo, enfim, para descobrir que se pertence a ele.",
  "cards":[
      {"ic":"constellation","t":"A Cura da Relação Está na Relação","emph":"na Relação","b":"Se todo problema é interpessoal, é nas relações que mora a saída — e seu nome em Adler é <strong>sentimento de comunidade</strong> (Gemeinschaftsgefühl): sentir os outros como companheiros e a si mesmo como parte de um todo. Não é afeto que brota sozinho; é a bússola final, o ponto onde a angústia que nasceu entre as pessoas se desfaz entre as pessoas.","tip":"<strong>Modelo mental:</strong> ferida que veio do “entre-nós” só cicatriza no “entre-nós” — nunca no isolamento orgulhoso.","wide":True},
      {"ic":"pivot","t":"Saia do Centro do Mundo","emph":"do Centro","b":"Quem vive em “como me veem? o que eu levo?” está trancado no próprio eu e exige que tudo gire em torno de si. A virada é trocar a pergunta: de <strong>“o que esta pessoa faz por mim?”</strong> para “o que eu posso dar a esta comunidade?”. Você não é o centro do mundo — é um membro dele. E pertencer não se recebe de presente; conquista-se contribuindo.","tip":"<strong>Como aplicar:</strong> diante de cada vínculo, pergunte o que pode oferecer antes de calcular o que vai receber."},
      {"ic":"steps","t":"Nenhum Grupo É o Universo Inteiro","emph":"o Universo Inteiro","b":"Quando o emprego, a escola ou o casamento viram prisão sem saída, o sufoco vem de tratar uma comunidade pequena como se fosse o mundo. Mas há sempre uma <strong>comunidade maior</strong> — a sociedade, a humanidade, o futuro. Ouvir a voz dela devolve a liberdade de discordar, mudar ou sair. A cela só existe enquanto você acredita que ela é o universo.","tip":"<strong>Cuidado:</strong> tomar o grupo imediato pelo mundo inteiro é justamente o que faz você se submeter a qualquer coisa.","warn":True},
    ],
  "lessons_title":"Lições-Chave da Quarta Noite (II)",
  "lessons":["A meta das relações é o sentimento de comunidade: sentir-se parte e ver os outros como companheiros.","Saia do apego a si — o centro — para o interesse pelos outros: a parte que serve ao todo.","Quando um grupo aprisiona, escute a comunidade maior; é ela que devolve a liberdade de sair."]},

 {"slug":"ch09-aqui-e-agora","sub":"QUINTA NOITE: A Tríade e o Viver o Aqui e Agora",
  "intro":"Na última noite o Filósofo costura tudo. A coragem de ser feliz se firma em três pilares que giram em roda — autoaceitação, confiança nos outros, contribuição — e só se realiza num lugar: aqui e agora. A vida não é uma reta rumo a um pico futuro; é uma sucessão de instantes. E o Jovem, que chegou para refutar, sai disposto a viver.",
  "cards":[
      {"ic":"constellation","t":"Os Três Pilares que Se Sustentam em Roda","emph":"Três Pilares","b":"A coragem de ser feliz repousa em três apoios que se alimentam num ciclo. <strong>Autoaceitação</strong>: aceitar o eu que não consegue — mudar o mutável, aceitar o imutável. <strong>Confiança incondicional</strong>: confiar sem cobrar garantia; trair é tarefa do outro. <strong>Contribuição</strong>: agir pelo bem de todos. Aceito-me, então confio; confio, então contribuo; sinto-me útil — e me aceito mais.","tip":"<strong>Como aplicar:</strong> não force os três de uma vez — gire um deles, e a roda puxa os outros sozinha.","wide":True},
      {"ic":"spark","t":"O Valor Vem de “Sou Útil”, Não de “Fui Aprovado”","emph":"“Sou Útil”","b":"É contribuir que dá o <strong>sentido de valor</strong> — “sou bom para alguém” —, a fonte real do valor próprio, e não o aplauso. Repare na inversão: a aprovação vem de fora e te deixa refém; a utilidade nasce do teu gesto e ninguém tira. Por isso o foco muda de “o que eu tenho” para “como uso o que tenho” — a coragem mora no uso, não no estoque.","tip":"<strong>Regra:</strong> sentir-se útil sustenta a coragem por dentro; caçar aprovação a rói por fora."},
      {"ic":"clock","t":"A Vida É Série de Instantes, Não uma Reta","emph":"Série de Instantes","b":"A vida não é uma linha que sobe rumo a um cume: é uma sucessão de <strong>agoras</strong>, pontos soltos como passos de uma dança. Quem trata o presente como “vida em preparação” — “serei feliz quando me formar, for promovido, casar” — nunca chega, porque adiar a felicidade é deixar de viver. Não há ensaio: cada instante já é a apresentação inteira.","tip":"<strong>Cuidado:</strong> fixar-se no passado (o trauma) ou no futuro (a meta) apaga o único lugar onde se vive de fato — o aqui.","warn":True},
      {"ic":"constellation","t":"Aponte para a Estrela-Guia e Cada Passo Já É Pleno","emph":"Estrela-Guia","b":"Não há um sentido universal entregue pronto: o sentido da vida é aquele que <strong>você dá a ela</strong>. Basta apontar para a estrela-guia da contribuição aos outros — e, enquanto se caminha em sua direção, cada instante já está completo, mesmo sem chegar a parte alguma. Dance a vida em vez de corrê-la: o valor está em cada passo, não na chegada.","tip":"<strong>Modelo mental:</strong> a estrela-guia não é um destino a alcançar — é a direção que torna pleno o agora."},
    ],
  "lessons_title":"Lições-Chave da Quinta Noite",
  "lessons":["A coragem se ergue sobre a tríade que gira em roda: aceitar-se, confiar nos outros, contribuir.","Contribuir — sentir-se útil a alguém — é a fonte real do valor próprio, não a aprovação alheia.","A vida é série de instantes: viva o aqui e agora, com a contribuição por estrela-guia."]},
]
