# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Crime e Castigo' (Fiódor Dostoiévski)."""

BOOK = {
  "title": "Crime e Castigo",
  "author": "Fiódor Dostoiévski",
  "header_light": "CRIME E",
  "header_bold": "CASTIGO",
  "subtitle": "VISÃO GERAL · A CONSCIÊNCIA NÃO ESPERA O TRIBUNAL",
  "intro": "Um ex-estudante febril, fechado num quarto do tamanho de um caixão, conclui que a moral é gaiola para os fracos: ao homem grande tudo é permitido, inclusive o sangue. Ergue o machado para provar a tese — e descobre, com pavor, que tem uma alma onde jurava só haver lógica. O castigo do título não é a Sibéria; é o que começa no segundo golpe e não o solta mais. Dostoiévski não derruba o niilismo com um argumento mais esperto. Faz coisa pior: deixa um homem inteligentíssimo vivê-lo até o fundo do poço — e ali, no fundo, a vida toma a palavra que a razão já não tem.",
  "description": "Crime e Castigo (Dostoiévski, 1866): a teoria do 'homem extraordinário' que se julga acima da lei moral, o assassinato como experimento de filosofia que se trinca já no primeiro golpe, a culpa que condena antes de qualquer algema, Sônia e o sofrimento que ressuscita, o duelo de alma com Porfiry ('você precisa de ar'), Svidrigáilov — o duplo que viveu o 'tudo é permitido' até o tiro — e a ressurreição pelo amor no epílogo siberiano. Não um manual de ideias: um homem inteiro posto à prova de fogo.",
  "tags": ["Literatura Clássica", "Filosofia", "Psicologia"],
  "progress": "9 Capítulos",
  "cover": "assets/crime-e-castigo-cover.png",
  "overview_cards": [
    {"ic":"sword","t":"O Crime como Experimento","b":"Raskólnikov não ergue o machado por dinheiro — mal abre a bolsa que rouba. Ergue-o para arrancar uma resposta sobre si mesmo: sou um Napoleão, com direito de pisar a lei moral em nome de uma ideia grande, ou <strong>'um piolho como todos'</strong>? O assassinato é a pergunta. A consciência é o veredicto que ele não tinha previsto.","tip":"<strong>Modelo mental:</strong> quando uma teoria concede a um homem direito sobre a vida alheia, quem a refuta não é o debate — é a vida, e ela cobra a prova em sangue."},
    {"ic":"spiral","t":"A Consciência como Castigo","b":"A Sibéria chega no fim e quase não pesa. O castigo de verdade começa antes de qualquer prisão: a febre, o delírio, o pavor de ser tocado pela própria mãe, a náusea de si. A teoria prometia que ele mataria 'sem hesitar' — e <strong>a alma que jurava não ter o desmente com remorso</strong>. Descobrir-se humano dói mais que a cadeia.","tip":"<strong>Para o leitor:</strong> repare como o corpo adoece. É ele que pronuncia a sentença que a razão se recusava a dar — a febre é o tribunal da consciência em sessão."},
    {"ic":"leaf","t":"Sônia e o Sofrimento Redentor","b":"<strong>Sônia Marmeládova</strong> também transgrediu — vendeu o corpo —, mas para tirar os irmãos da fome. Onde ele pôs orgulho, ela pôs amor: a mesma queda, motivos no extremo oposto. Ao assassino ela não oferece um silogismo melhor — oferece 'aceite o sofrimento e renasça', e lhe lê a ressurreição de Lázaro. E o homem que já cheirava a morte volta a respirar.","tip":"<strong>Modelo mental:</strong> contra uma ideia que mata, nenhuma ideia mais bonita basta. Só uma vida inteira posta na mesa — a vida vence a dialética."},
    {"ic":"masks","t":"Os Duplos — Svidrigáilov e Lújin","b":"Para medir Raskólnikov, olhe seus espelhos. <strong>Svidrigáilov</strong> vive o 'tudo é permitido' sem um arrepio de culpa — é o que o herói seria se a consciência tivesse calado; acaba no tiro, porque o niilismo levado a sério não dá vida, dá o nada. <strong>Lújin</strong> é o egoísmo de fraque: o mesmo crime, só que dentro da lei e com recibo.","tip":"<strong>Como aplicar:</strong> um homem se mede pelos seus duplos. Eles mostram, sem dó, em que ele teria dado caso o resgate não chegasse."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-teoria-homem-extraordinario",
    "sub": "CAPÍTULO 1: A Teoria do 'Homem Extraordinário'",
    "intro": "Tudo nasce de uma ideia. Raskólnikov dividiu a humanidade em duas castas: os 'ordinários', que existem para obedecer, e os 'extraordinários', a quem é dado transgredir a lei moral em nome de algo maior. O crime não é ganância — é exame. Ele precisa saber de que lado está: é um Napoleão, ou 'um piolho como todos'? O machado é a prova de laboratório que ele aplica em si mesmo.",
    "cards": [
      {"ic":"triangle","t":"Ordinários Contra Extraordinários","emph":"Extraordinários","b":"A tese é simples e letal: os <strong>extraordinários</strong> — de Napoleão ao legislador — teriam direito natural de passar por cima do sangue para fundar o novo; os ordinários servem só para perpetuar a espécie. Por isso a morte da velha não é sobre o cofre dela. É o teste empírico da própria grandeza dele.","tip":"<strong>Modelo mental:</strong> encare a brutalidade não como crime de paixão, mas como o experimento de um homem que decidiu medir a si mesmo em outra pessoa."},
      {"ic":"spark","t":"A Refutação Pela Carne","emph":"Pela Carne","b":"Dostoiévski não vence a ideia no conforto da mesa de debate: deixa o herói <strong>executá-la na própria pele</strong>. A refutação chega como febre, delírio e uma solidão que sufoca. A matemática da grandeza quebra no instante em que esbarra na resposta imprevista do corpo, que se recusa a ser apenas teoria.","tip":"<strong>Sinal de alerta:</strong> quando uma teoria perfeita só se sustenta a preço de sangue e adoecimento, o erro está na teoria — nunca no mundo que reagiu a ela.","warn":True},
      {"ic":"mask","t":"A Dupla Justificativa","emph":"Dupla Justificativa","b":"Para o mesmo machado, Raskólnikov guarda duas defesas: a <strong>utilitária</strong> ('uma morte vil por mil boas ações') e a <strong>napoleônica</strong> ('a audácia do ser superior'). Quando um único ato atroz precisa de dois álibis brilhantes, é porque a razão verdadeira não é nobre — e se esconde atrás dos dois: ressentimento e vaidade.","tip":"<strong>Como aplicar:</strong> repare quando alguém empilha duas justificativas elevadas para o mesmo gesto. Costuma ser o orgulho procurando uma roupa apresentável."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["O grande crime do romance é intelectual antes de ser físico: uma ideia que outorga ao homem direito sobre a vida alheia.", "O racionalismo amoral não cai por um argumento melhor — cai pelas consequências que se vivem na carne.", "Quando há duas razões nobres para o mesmo ato sujo, a razão de verdade está escondida embaixo das duas."],
  },
  {
    "slug": "ch02-o-crime-petersburgo",
    "sub": "CAPÍTULO 2: O Crime — Aliona, Lizavieta, Petersburgo",
    "intro": "O crime acontece — e trinca a teoria no próprio gesto. Lizavieta, a irmã mansa da agiota, entra por acaso e cai pelo mesmo machado: justamente uma das humilhadas que a teoria prometia salvar. Não existe assassinato 'racional' que saia cirúrgico. E ao redor, Petersburgo — o calor que gruda, as escadas imundas, o quarto-armário — é a cidade que faz a ideia parecer razoável.",
    "cards": [
      {"ic":"eye","t":"O Erro Imprevisto","emph":"Imprevisto","b":"O segundo golpe, o <strong>não planejado</strong>, mata Lizavieta — a oprimida que a teoria jurava emancipar. Ali o cálculo perfeito implode. Toda incisão fria sobre a vida real deixa um rastro de vítimas que a mente do estrategista se recusa a contabilizar antes de agir. A teoria mata duas; previu uma.","tip":"<strong>Regra:</strong> o bisturi ideológico nunca corta limpo. Quem age sobre vidas humanas em nome de uma ideia sempre derrama mais sangue do que sua planilha admitia.","warn":True},
      {"ic":"mountain","t":"A Cidade Como Vício","emph":"Cidade Como Vício","b":"A Petersburgo fétida, de vielas abafadas, não é pano de fundo — é <strong>personagem que aperta</strong>. O suor que não seca, a escada encardida, o quarto do tamanho de um armário: esse é o caldeirão onde o niilismo ferve até parecer lógico. Dostoiévski descreve a sujeira porque é nela que a queda encontra desculpa.","tip":"<strong>Prática:</strong> observe como uma degradação física crônica vai corroendo, sem alarde, as defesas morais mais elementares de quem nela vive."},
      {"ic":"gap","t":"O Roubo Sem Propósito","emph":"Sem Propósito","b":"O suposto grande assassino <strong>mal olha o que roubou</strong>: enfia as joias debaixo de uma pedra e as esquece. A indiferença ao butim entrega o blefe — o crime nunca foi para financiar o bem maior. O sangue foi derramado para testar um ego, não para encher uma carteira que ele sequer abre.","tip":"<strong>Modelo mental:</strong> quando os gestos de alguém contradizem o 'motivo' que ele anuncia, a verdade está no que ele deixa de fazer, não no que diz."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["Nenhum crime 'racional' sai cirúrgico — Lizavieta já refuta a teoria no próprio ato.", "Petersburgo funciona como argumento: o ambiente é o que torna certas ideias sedutoras.", "Largar o butim sem olhar prova que o móvel era a teoria, não a fome."],
  },
  {
    "slug": "ch03-culpa-consciencia-castigo",
    "sub": "CAPÍTULO 3: A Culpa e a Consciência — O Verdadeiro Castigo",
    "intro": "O 'castigo' do título não é a Sibéria: é a consciência. Muito antes de qualquer pena legal, Raskólnikov é triturado por dentro — febre, delírio, isolamento, repulsa por si mesmo. A teoria prometia um Napoleão que mataria sem hesitar; o que ele encontra no espelho é um homem que adoece de remorso. Descobrir-se 'piolho' dói mais que todo o medo da prisão.",
    "cards": [
      {"ic":"spiral","t":"O Tribunal Interno","emph":"Tribunal Interno","b":"O remorso vem de modo <strong>orgânico, involuntário</strong>: a razão assinou a licença para matar, mas a consciência se recusou a fazer o papel de Napoleão. O terror que sufoca Raskólnikov não é o medo de apodrecer na cela — é o espanto de descobrir que, afinal, ele tinha moral, e que ela não pediu sua permissão.","tip":"<strong>Regra:</strong> a pena íntima é proferida no exato instante da culpa. O juiz de dentro acorda antes de a polícia bater à porta."},
      {"ic":"gap","t":"O Muro do Isolamento","emph":"Isolamento","b":"O sangue seco corta o fio que ligava o estudante ao resto dos homens. Ele sente repulsa e pavor ao toque da mãe e do melhor amigo. O crime não o condenou só perante a lei: fez dele um <strong>fantasma exilado entre os vivos</strong> — uma morte social bem pior que o cárcere, porque ninguém a decretou e ele não pode apelar.","tip":"<strong>Sinal de alerta:</strong> o isolamento que vem depois de uma ruptura moral costuma punir a alma com mais crueza do que qualquer tribunal de toga.","warn":True},
      {"ic":"bulb","t":"O Magnetismo da Confissão","emph":"Confissão","b":"O herói flerta com a confissão de forma quase doente: vagueia pelas vielas, provoca a polícia, beira o limite. Há nele uma <strong>atração pela queda</strong>, um chamado da beira do abismo. O segredo pesa mais que o medo das algemas — a alma corrompida pede, em surdina, alguém que lhe imponha um limite vindo de fora.","tip":"<strong>Como aplicar:</strong> o impulso humano de rasgar a máscara e assumir o erro vence, mais vezes do que se imagina, o mais frio dos cálculos da cabeça."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["O castigo é a consciência, e ela age antes da lei — o título é literal.", "A teoria foi vencida pela própria natureza de Raskólnikov, não por refutação de fora.", "Sofrer prova que ele não é extraordinário — e é exatamente esse fracasso que abre a porta da redenção."],
  },
  {
    "slug": "ch04-sonia-amor-sacrificio-fe",
    "sub": "CAPÍTULO 4: Sônia — Amor, Sacrifício e Fé",
    "intro": "Sônia Marmeládova, vendida à rua para alimentar a família, é a antítese viva da teoria: onde Raskólnikov colocou a razão, ela coloca a fé e o amor. Figura-Cristo, transgrediu por amor aos outros — o avesso exato do orgulho do herói. Sua resposta ao assassino não é um silogismo, é um chamado: 'aceite o sofrimento e renasça'. E ela lhe lê, em voz trêmula, a ressurreição de Lázaro.",
    "cards": [
      {"ic":"leaf","t":"A Transgressão Pelo Amor","emph":"Pelo Amor","b":"Sônia também vendeu o corpo e quebrou a moral de Petersburgo — mas se entregou <strong>para estancar a fome dos irmãos</strong>. O contraste despe a teoria: a mesma transgressão pode ter raízes opostas e levar a destinos opostos, separando quem caiu por amor de quem caiu por orgulho.","tip":"<strong>Modelo mental:</strong> o 'o quê' de um ato diz pouco; o 'por quê' diz tudo. É o motivo escondido que decide em quem você vai se transformar."},
      {"ic":"book","t":"A Promessa de Lázaro","emph":"Promessa","b":"A leitura ofegante do morto que volta do túmulo não é interlúdio: é o <strong>mapa do epílogo</strong>. Lázaro apodrecido na sepultura é o assassino trancado no próprio ego. Há retorno para quem já cheira à morte — mas o preço é entregar-se à luz que a teoria sempre tratou com desprezo.","tip":"<strong>Prática:</strong> em grandes romances, o núcleo simbólico costuma estar escondido no texto que um personagem escolhe — ou é levado — a ler em voz alta."},
      {"ic":"key","t":"A Fé Que Não Argumenta","emph":"Não Argumenta","b":"Sônia não enfrenta as defesas eruditas do estudante com silogismos mais finos — ela <strong>põe a própria vida na mesa</strong>. Sua fé não tem verniz filosófico; é sacrifício de carne e osso, e fica de pé exatamente quando o imenso intelecto dele desaba. A vida vivida é o argumento que a vida pensada não consegue derrubar.","tip":"<strong>Sinal de alerta:</strong> a força de uma ideia destrutiva não se desarma com outra ideia. Só com o choque de uma vida real que se recusa a entrar na lógica dela.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["O móvel da transgressão (amor vs. orgulho) define o destino — a mesma ação tem raízes e desfechos opostos.", "A leitura de Lázaro é o programa do romance: morte em vida → ressurreição pelo sofrimento aceito.", "A fé de Sônia não é argumento, é vida encarnada — a refutação mais forte ao racionalismo amoral."],
  },
  {
    "slug": "ch05-porfiry-duelo-psicologico",
    "sub": "CAPÍTULO 5: Porfiry — O Duelo Psicológico",
    "intro": "Porfiry Pietróvitch, juiz de instrução, não caça provas — caça a alma. Sem uma evidência sequer, ele conduz um jogo de gato e rato montado sobre a psicologia e sobre a própria teoria do suspeito, certo de que a culpa fará o trabalho de entregá-lo. No fim, soa quase profeta: 'você precisa de ar' — confesse, não para perder, mas para voltar a respirar.",
    "cards": [
      {"ic":"lens","t":"A Caça Pelas Ideias","emph":"Caça Pelas Ideias","b":"Porfiry trabalha sem impressão digital, sem testemunha, sem arma: usa o artigo brilhante do estudante como laço. Cada pergunta de aparência inocente esconde uma estocada. Ele escava a vaidade de Raskólnikov e o obriga a <strong>exibir o orgulho que pariu o crime</strong> — porque sabe que o orgulho não resiste a explicar a própria genialidade.","tip":"<strong>Modelo mental:</strong> o interrogador mais perigoso é o que entende que o orgulhoso, mais cedo ou mais tarde, vai querer provar como é superior."},
      {"ic":"wave","t":"A Angústia Como Álibi","emph":"Angústia","b":"O juiz percebe que não precisa torturar ninguém — a máquina do remorso já faz o serviço pesado. Seu plano é só um: <strong>não deixar a culpa anestesiar</strong>. O tempo que se arrasta e o desespero de partilhar o segredo viram a polícia invisível. Diante daquele quarto abafado, o degredo na Sibéria quase soa como alívio.","tip":"<strong>Prática:</strong> contra um inimigo que se devora por dentro, às vezes a tática é não atacar — é deixá-lo gastar a própria energia batendo nas paredes da mente."},
      {"ic":"fork","t":"O Oxigênio da Punição","emph":"Oxigênio","b":"Olhando nos olhos assombrados do criminoso, Porfiry decreta o resgate: 'Entregue-se — você <strong>está precisando de ar</strong>'. A punição deixa de soar como guilhotina e vira janela aberta. Cumprir a pena não será o fim da vida de Raskólnikov; será, paradoxalmente, o único caminho de volta a ela.","tip":"<strong>Regra:</strong> assumir a ferida sob o sol arde de imediato; esconder a podridão no escuro envenena devagar, e por inteiro.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["Porfiry usa a teoria do próprio suspeito como isca — o orgulho intelectual é a brecha.", "A culpa interior trabalha pelo investigador: o tormento da consciência é mais eficaz que a prisão.", "'Você precisa de ar': a confissão é respiro, não derrota."],
  },
  {
    "slug": "ch06-svidrigailov-o-duplo",
    "sub": "CAPÍTULO 6: Svidrigáilov — O Duplo Niilista",
    "intro": "Svidrigáilov é o espelho sombrio de Raskólnikov: vive o 'tudo é permitido' sem o menor resto de consciência. É o que o herói teria sido se a culpa tivesse calado. Sensualista, predador — e, no entanto, capaz de gestos generosos. Seu fim é o tiro: não punição cristã, mas tédio. O niilismo levado a sério até o fim não conduz à liberdade, conduz ao nada.",
    "cards": [
      {"ic":"masks","t":"O Espelho Sem Consciência","emph":"Sem Consciência","b":"Svidrigáilov é o espelho mais aterrador do romance: comete horrores em silêncio e <strong>não sente o peso de uma pena sequer</strong>. Vive a cartilha do 'tudo é permitido' sem febre, sem delírio, sem o tribunal de dentro. É o fantasma do que Raskólnikov quis e não conseguiu ser — e olhar para ele é olhar para o próprio abismo.","tip":"<strong>Sinal de alerta:</strong> encare o duplo frio como a imagem crua do que sobra de um homem quando se arranca dele a bússola moral e se mantém só o intelecto.","warn":True},
      {"ic":"gap","t":"O Fundo Falso do Nada","emph":"Fundo Falso","b":"O duplo tem lampejos de bondade — paga o enterro dos órfãos —, mas o gesto <strong>não o aquece nem o preenche</strong>. Sem chão moral, a caridade vira capricho de quem não sabe o que fazer com o dia. O niilismo coerente funciona como relógio e, ainda assim, não fabrica sentido: só administra o vazio.","tip":"<strong>Modelo mental:</strong> um ato bom desligado de qualquer compromisso profundo não cura a doença de fundo — a ausência de um porquê para viver."},
      {"ic":"mountain","t":"O Tédio Até a Bala","emph":"Tédio","b":"Ele não encosta a arma na têmpora por culpa cristã, mas por <strong>tédio insuportável</strong>. Sem o tormento moral e sem afeto que prenda à vida, os dias escorrem sem peso e sem urgência. O tiro na noite de chuva não é castigo: é o tédio existencial desligando a luz, porque não há motivo para acordar amanhã.","tip":"<strong>Prática:</strong> antes de abraçar qualquer filosofia de liberdade absoluta, repare longamente no fim de quem a viveu até a última página."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["O duplo revela aonde a ideia leva quando não há o freio da consciência.", "O niilismo coerente não produz sentido — as boas ações viram capricho arbitrário.", "O tiro de Svidrigáilov é o anti-epílogo: sem fé e sem consciência, o 'tudo é permitido' termina no nada."],
  },
  {
    "slug": "ch07-razumikhin-dunia-familia",
    "sub": "CAPÍTULO 7: Razumíkhin, Dúnia e a Família",
    "intro": "Os contrapontos saudáveis. Razumíkhin prova que a pobreza não obriga ninguém ao crime. Dúnia é o duplo positivo do herói — tão orgulhosa e forte quanto ele, mas com a fé que a segura à beira do abismo. E Lújin encarna o egoísmo 'respeitável': o mesmo cálculo gelado, só que dentro da lei e de gravata. Pelos que estão ao redor, mede-se o que se tornou o que está no centro.",
    "cards": [
      {"ic":"person","t":"O Oposto Em Dobro","emph":"Oposto","b":"Razumíkhin vive na mesma miséria aguda do herói, mas acorda cedo, trabalha e ri alto. Ele é a <strong>refutação viva de Dostoiévski</strong>: não foi a pobreza de Petersburgo que ergueu o machado. Foram a vaidade e a teoria, criadas no isolamento de um quarto fechado, que assinaram as duas mortes.","tip":"<strong>Como aplicar:</strong> não meça a verdade só pela dor de quem caiu. Olhe também os que andam pela mesma lama e não se sujam — eles dizem o que sobra de desculpa."},
      {"ic":"scale","t":"O Orgulho Com Freio","emph":"Orgulho","b":"Dúnia tem a mesma altivez inquebrável e o mesmo olhar duro do irmão, mas carrega a <strong>fé cravada nas entranhas</strong>. Quando saca o revólver contra Svidrigáilov no quarto trancado, mostra que orgulho com bússola não precisa derramar sangue para vencer. A força dela se firma na defesa, não no ataque a uma ideia.","tip":"<strong>Modelo mental:</strong> o orgulho não é, sozinho, o pecado. O desastre vem quando a altivez corta o fio que ligava o homem ao resto do mundo."},
      {"ic":"key","t":"O Mal Respeitável","emph":"Mal Respeitável","b":"Lújin é o avesso encerado da mesma moeda: tritura reputações e manobra viúvas pobres com a precisão de um advogado, sempre escorado em <strong>argumentos de mercado e boas maneiras</strong>. O romance o despreza para mostrar que a violência fria dos que andam dentro da lei também tem as mãos sujas.","tip":"<strong>Armadilha:</strong> o cálculo metódico e chancelado pelas regras costuma deixar um rastro de destruição que nenhum tribunal alcança.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["Razumíkhin prova que a miséria não determina o crime — o contraponto mede o herói.", "O mesmo orgulho salva em Dúnia (com fé) e destrói em Raskólnikov (sem fé).", "Lújin encarna o crime dentro da lei — o egoísmo respeitável é tão corrosivo quanto o niilismo declarado."],
  },
  {
    "slug": "ch08-petersburgo-miseria-simbolos",
    "sub": "CAPÍTULO 8: Petersburgo, Miséria e Símbolos",
    "intro": "A cidade é personagem. Calor que sufoca, ruas imundas, o quarto-caixão amarelo onde a ideia apodrece como um corpo. A miséria torna a teoria utilitarista sedutora — e o romance a denuncia sem jamais aceitá-la como desculpa. E os símbolos não enfeitam: carregam a tese pela obra inteira, do amarelo da doença ao machado, da água da morte à cruz da contrição.",
    "cards": [
      {"ic":"layers","t":"A Sujeira Como Bússola","emph":"Sujeira","b":"A poeira amarela do verão não decora o parágrafo: <strong>o calor que esmaga empurra o crime</strong>. Dostoiévski esfrega o ar rançoso na sua retina para que o delírio intelectual soe plausível — sem nunca validar a desculpa sociológica de que o assassino é só refém da vizinhança em que nasceu.","tip":"<strong>Modelo mental:</strong> leia a descrição do espaço não como fotografia, mas como termômetro do caldeirão psicológico que ferve dentro do personagem."},
      {"ic":"eye","t":"A Paleta do Desespero","emph":"Paleta","b":"O <strong>amarelo</strong> pinta rostos doentes e papéis de parede decrépitos. A <strong>água</strong> reflete o suicida e promete o batismo. A <strong>cruz</strong> encarna o choque do renascimento. E o <strong>machado</strong> é a guilhotina da teoria descendo sobre inocentes. Em Dostoiévski, o objeto não acompanha a tese — ele a narra.","tip":"<strong>Prática:</strong> procure a chave filosófica por trás dos móveis quebrados e das paredes rachadas. Na boa literatura, o cenário é discurso."},
      {"ic":"pin","t":"A Tumba de Três Passos","emph":"Tumba","b":"O cômodo apertado, de papel sujo, onde o assassino respira <strong>é o útero abafado do desastre</strong>. O orgulho inflamado e a imundície estrutural se alimentam um do outro. Quando Porfiry diz 'você precisa de ar', a frase aponta para dois lugares ao mesmo tempo: os pulmões encurralados e a alma engaiolada.","tip":"<strong>Armadilha:</strong> o teto baixo pressiona a mente. É quase impossível manter clareza de horizonte quando se vive atolado na clausura.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["A cidade-personagem é argumento: torna a teoria compreensível sem nunca justificá-la.", "Os símbolos (amarelo, machado, água, cruz) carregam a tese ao longo de toda a obra.", "O quarto-caixão externaliza a clausura mental — em Dostoiévski, o espaço físico é sempre psicológico."],
  },
  {
    "slug": "ch09-confissao-sofrimento-epilogo",
    "sub": "CAPÍTULO 9: Confissão, Sofrimento e Ressurreição",
    "intro": "Empurrado pela consciência, por Sônia e por Porfiry, Raskólnikov vai à encruzilhada, beija a terra e se entrega — mas ainda sem se arrepender da ideia. No epílogo, após nove meses na Sibéria (a gestação do homem novo), ele sonha com a 'peste' do niilismo, desaba aos pés de Sônia e renasce pelo amor. Como Lázaro, a 'vida toma o lugar da dialética' — e o que o argumento não conseguia fazer, o sofrimento aceito faz.",
    "cards": [
      {"ic":"mountain","t":"A Palavra Antes da Culpa","emph":"Culpa","b":"No pátio gelado da delegacia o estudante diz as palavras, mas os dentes cerrados confessam que a cabeça <strong>ainda ama a fórmula do crime</strong>. O arrependimento verdadeiro demora. Primeiro o corpo se ajoelha diante da lei; só depois, devagar, o ego racha diante da consciência. A confissão vem antes da contrição.","tip":"<strong>Como aplicar:</strong> aceite que consertar um erro às vezes começa pelo ato seco de se expor — não pela lágrima imediata, que pode nem ter chegado ainda."},
      {"ic":"spiral","t":"O Vírus Incurável do Ego","emph":"Vírus","b":"Varrendo o chão de uma Sibéria cinzenta, ele sonha com uma peste em que cada contaminado se proclama dono absoluto da verdade — uma <strong>epidemia de vaidade teórica</strong> que dissolve o mundo em guerra. Esse pesadelo é a denúncia mais clara de Dostoiévski contra o pensamento puro, fechado, isolado de qualquer amor.","tip":"<strong>Sinal de alerta:</strong> ideias intocáveis matam mais que exércitos. A doença do ego que se crê dono da razão não precisa de diagnóstico de médico.","warn":True},
      {"ic":"leaf","t":"A Dialética Desaba","emph":"Desaba","b":"À margem do rio siberiano, o herói se desfaz em pranto e abraça os joelhos de Sônia sem resistir. O castelo de silogismos evaporou diante do <strong>baque do amor encarnado</strong>. A carne que sangrou pelo orgulho descobre, enfim, que se enche de paz por uma única via: a aceitação do sofrimento partilhado.","tip":"<strong>Modelo mental:</strong> nenhuma muralha lógica resiste para sempre ao avanço silencioso de alguém disposto a sofrer ao seu lado."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["A confissão precede o arrependimento: o ato externo abre a porta da transformação interna.", "O sonho da peste diagnostica o niilismo racionalista como epidemia que destrói quem a carrega.", "'A vida toma o lugar da dialética': o amor e o sofrimento aceito fazem o que nenhum argumento faz."],
  },
]
