# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Crime e Castigo' (Fiódor Dostoiévski)."""

BOOK = {
  "title": "Crime e Castigo",
  "author": "Fiódor Dostoiévski",
  "header_light": "CRIME E",
  "header_bold": "CASTIGO",
  "subtitle": "VISÃO GERAL · A CONSCIÊNCIA NÃO ESPERA O TRIBUNAL",
  "intro": "Um ex-estudante de febre nos olhos, trancado num quarto do tamanho de um caixão, raciocinou até esta conclusão: a moral é gaiola dos fracos, e ao homem grande tudo é permitido, inclusive o sangue. Ergue o machado para verificar a tese em si mesmo — e descobre, no segundo golpe, que tem alma onde jurava haver só lógica. O castigo do título não é a Sibéria; é a coisa que começa ali e não o larga mais. Dostoiévski não refuta o niilismo com um argumento mais fino. Faz pior: deixa um homem inteligentíssimo descê-lo até o último degrau do poço — e é no fundo, onde a razão emudece, que a vida abre a boca e fala.",
  "description": "Crime e Castigo (Dostoiévski, 1866): a teoria do 'homem extraordinário' que se acredita acima da lei moral, o assassinato montado como experimento de filosofia e trincado no próprio gesto, a culpa que profere a sentença muito antes de qualquer algema, Sônia e o sofrimento que ressuscita, o duelo de alma com Porfiry ('você precisa de ar'), Svidrigáilov — o duplo que levou o 'tudo é permitido' até o cano da pistola — e o renascimento pelo amor no epílogo siberiano. Não um catálogo de ideias: um homem inteiro atirado à prova de fogo.",
  "tags": ["Literatura Clássica", "Filosofia", "Psicologia"],
  "progress": "9 Capítulos",
  "cover": "assets/crime-e-castigo-cover.png",
  "overview_cards": [
    {"ic":"sword","t":"O Crime como Experimento","b":"Raskólnikov não ergue o machado por dinheiro — mal abre a bolsa que rouba e enfia o butim debaixo de uma pedra. Ergue-o para arrancar de si uma resposta: sou um Napoleão, com direito de pisar a lei moral em nome de uma ideia grande, ou <strong>'um piolho como todos'</strong>? O assassinato é a pergunta. A consciência será o veredicto que ele não pôs na conta.","tip":"<strong>Modelo mental:</strong> quando uma teoria outorga a um homem direito sobre a vida alheia, quem a refuta não é o debate — é a vida, e ela cobra a prova em sangue."},
    {"ic":"spiral","t":"A Consciência como Castigo","b":"A Sibéria chega no fim e quase não pesa. O castigo de verdade começa antes de qualquer cela: a febre, o delírio, o pavor ao toque da própria mãe, a náusea de si. A teoria garantia um homem que mataria 'sem hesitar' — e <strong>a alma que ele jurava não ter o desmente com remorso</strong>. Descobrir-se humano dói mais que a corrente no tornozelo.","tip":"<strong>Para o leitor:</strong> repare como é o corpo que adoece. É ele quem pronuncia a sentença que a razão se recusava a dar — a febre é o tribunal da consciência em sessão."},
    {"ic":"leaf","t":"Sônia e o Sofrimento Redentor","b":"<strong>Sônia Marmeládova</strong> também caiu — vendeu o corpo —, mas para tirar os irmãos da fome. Onde ele pôs orgulho, ela pôs amor: a mesma queda, motivos no extremo oposto. Ao assassino ela não devolve um silogismo melhor; abre a Bíblia e lhe lê, com a voz tremendo, a ressurreição de Lázaro. E o homem que já cheirava a defunto torna a respirar.","tip":"<strong>Modelo mental:</strong> contra uma ideia que mata, nenhuma ideia mais bela basta. Só uma vida inteira posta sobre a mesa — a vida toma o lugar da dialética."},
    {"ic":"masks","t":"Os Duplos — Svidrigáilov e Lújin","b":"Para medir Raskólnikov, olhe seus espelhos. <strong>Svidrigáilov</strong> vive o 'tudo é permitido' sem um arrepio de culpa — é o que o herói seria se a consciência tivesse calado; termina no tiro, porque o niilismo levado a sério não dá vida, dá o nada. <strong>Lújin</strong> é o mesmo egoísmo de fraque e cartola: o mesmo crime, só que dentro da lei e com recibo passado.","tip":"<strong>Como aplicar:</strong> um homem se mede pelos próprios duplos. Eles mostram, sem dó, em que ele teria dado se o resgate não chegasse a tempo."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-teoria-homem-extraordinario",
    "sub": "CAPÍTULO 1: A Teoria do 'Homem Extraordinário'",
    "intro": "Tudo nasce de uma ideia — e é a ideia que mata primeiro. Raskólnikov partiu a humanidade em duas castas: os 'ordinários', material que existe para obedecer e se repetir, e os 'extraordinários', a quem é lícito transpor a lei moral em nome de algo maior. O crime não é cobiça — é exame de admissão. Ele precisa saber de que lado caiu: é um Napoleão, ou 'um piolho como todos'? O machado é a prova de laboratório que ele resolveu aplicar em carne viva.",
    "cards": [
      {"ic":"triangle","t":"Ordinários Contra Extraordinários","emph":"Extraordinários","b":"A tese é simples e letal: os <strong>extraordinários</strong> — de Napoleão ao legislador — teriam licença natural para passar por cima do sangue e fundar o novo; os ordinários servem apenas para perpetuar a espécie. Por isso a morte da velha agiota não é sobre o cofre dela. É o teste empírico da grandeza do próprio assassino.","tip":"<strong>Modelo mental:</strong> não leia a brutalidade como crime de paixão, mas como o experimento de um homem que decidiu medir a si mesmo dentro de outra pessoa."},
      {"ic":"spark","t":"A Refutação Pela Carne","emph":"Pela Carne","b":"Dostoiévski não vence a ideia na poltrona do debate: faz o herói <strong>executá-la na própria pele</strong>. A refutação não vem por escrito — vem como febre, delírio e uma solidão que aperta a garganta. A aritmética da grandeza racha no instante em que bate na resposta imprevista do corpo, que se nega a ser só teoria.","tip":"<strong>Sinal de alerta:</strong> quando uma teoria perfeita só fica de pé ao preço de sangue e doença, o defeito está na teoria — nunca no mundo que reagiu a ela.","warn":True},
      {"ic":"mask","t":"A Dupla Justificativa","emph":"Dupla Justificativa","b":"Para o mesmo machado, Raskólnikov mantém duas defesas a postos: a <strong>utilitária</strong> ('uma vida vil por mil boas ações') e a <strong>napoleônica</strong> ('a audácia do ser superior'). Quando um ato atroz precisa de dois álibis brilhantes, é sinal de que a razão de verdade não é nobre nenhuma — e se esconde por baixo das duas: ressentimento e vaidade.","tip":"<strong>Como aplicar:</strong> desconfie de quem empilha duas justificativas elevadas para o mesmo gesto. É quase sempre o orgulho procurando uma roupa apresentável."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["O grande crime do romance é intelectual antes de ser físico: uma ideia que outorga ao homem direito sobre a vida alheia.", "O racionalismo amoral não tomba por um argumento melhor — tomba pelas consequências que se vivem na carne.", "Quando há duas razões nobres para o mesmo ato sujo, a razão verdadeira está escondida debaixo de ambas."],
  },
  {
    "slug": "ch02-o-crime-petersburgo",
    "sub": "CAPÍTULO 2: O Crime — Aliona, Lizavieta, Petersburgo",
    "intro": "O crime acontece — e trinca a teoria no próprio gesto. Lizavieta, a irmã mansa da agiota, entra por acaso e tomba sob o mesmo machado: exatamente uma das humilhadas que a teoria prometia resgatar. Não há assassinato 'racional' que saia cirúrgico. E em volta, Petersburgo — o calor que cola na pele, as escadas imundas, o quarto-armário — é a cidade que se encarrega de tornar a ideia plausível.",
    "cards": [
      {"ic":"eye","t":"O Erro Imprevisto","emph":"Imprevisto","b":"O segundo golpe, o <strong>que não estava no plano</strong>, mata Lizavieta — a oprimida que a teoria jurava emancipar. Ali o cálculo perfeito implode. Toda incisão fria sobre a vida real deixa um rastro de vítimas que a mente do estrategista se recusa a somar antes de agir. A teoria previu uma morte; entregou duas.","tip":"<strong>Regra:</strong> o bisturi ideológico nunca corta limpo. Quem opera sobre gente em nome de uma ideia sempre derrama mais sangue do que admitia a sua conta.","warn":True},
      {"ic":"mountain","t":"A Cidade Como Vício","emph":"Cidade Como Vício","b":"A Petersburgo fétida, de vielas sem ar, não é cenário — é <strong>personagem que aperta o peito</strong>. O suor que não seca, a escada encardida, o cubículo do tamanho de um armário: eis o caldeirão onde o niilismo ferve até parecer lógico. Dostoiévski esfrega a sujeira na sua cara porque é nela que a queda arranja desculpa.","tip":"<strong>Prática:</strong> repare como uma degradação física crônica vai corroendo, sem barulho, as defesas morais mais elementares de quem mora dentro dela."},
      {"ic":"gap","t":"O Roubo Sem Propósito","emph":"Sem Propósito","b":"O suposto grande assassino <strong>mal confere o que roubou</strong>: enfia as joias debaixo de uma pedra e nem volta a abrir o embrulho. A indiferença ao butim entrega o blefe — o crime nunca foi para financiar bem maior nenhum. O sangue correu para testar um ego, não para encher uma carteira que ele sequer espia.","tip":"<strong>Modelo mental:</strong> quando os gestos de alguém desmentem o 'motivo' que ele proclama, a verdade está no que ele deixa de fazer, não no que diz."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["Nenhum crime 'racional' sai cirúrgico — Lizavieta já refuta a teoria no próprio ato.", "Petersburgo funciona como argumento: é o ambiente que torna certas ideias sedutoras.", "Largar o butim sem olhar prova que o móvel era a teoria, e não a fome."],
  },
  {
    "slug": "ch03-culpa-consciencia-castigo",
    "sub": "CAPÍTULO 3: A Culpa e a Consciência — O Verdadeiro Castigo",
    "intro": "O 'castigo' do título não é a Sibéria: é a consciência, e ela não espera o tribunal. Muito antes de qualquer pena legal, Raskólnikov é triturado por dentro — febre, delírio, isolamento, asco de si. A teoria garantia um Napoleão que mataria sem pestanejar; o que o espelho lhe devolve é um homem que adoece de remorso. Descobrir-se 'piolho' dói mais do que todo o medo da prisão somado.",
    "cards": [
      {"ic":"spiral","t":"O Tribunal Interno","emph":"Tribunal Interno","b":"O remorso sobe de modo <strong>orgânico, à revelia da vontade</strong>: a razão assinou a licença para matar, mas a consciência se recusou a desempenhar o papel de Napoleão. O terror que sufoca Raskólnikov não é o de apodrecer na cela — é o espanto de descobrir que, no fim, ele tinha moral, e que ela nunca lhe pediu autorização.","tip":"<strong>Regra:</strong> a pena íntima é decretada no mesmo instante da culpa. O juiz de dentro acorda antes de a polícia bater à porta."},
      {"ic":"gap","t":"O Muro do Isolamento","emph":"Isolamento","b":"O sangue seco corta o fio que prendia o estudante ao resto dos homens. Ele recua com repulsa e pavor ao toque da mãe e do melhor amigo. O crime não o condenou só perante a lei: fez dele um <strong>fantasma exilado entre os vivos</strong> — morte social pior que o cárcere, porque ninguém a decretou e não há para onde apelar.","tip":"<strong>Sinal de alerta:</strong> o isolamento que vem depois de uma ruptura moral costuma punir a alma com mais crueldade do que qualquer tribunal de toga.","warn":True},
      {"ic":"bulb","t":"O Magnetismo da Confissão","emph":"Confissão","b":"O herói ronda a confissão como quem ronda a borda de um penhasco: vagueia pelas vielas, cutuca a polícia, brinca de chegar perto. Há nele uma <strong>atração pela queda</strong>, um chamado vindo do abismo. O segredo pesa mais que o medo das algemas — a alma corrompida implora, em surdina, por alguém que lhe imponha um limite vindo de fora.","tip":"<strong>Como aplicar:</strong> o impulso humano de rasgar a máscara e assumir o erro vence, mais vezes do que se supõe, o mais gelado dos cálculos da cabeça."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["O castigo é a consciência, e ela age antes da lei — o título é literal.", "A teoria foi vencida pela própria natureza de Raskólnikov, não por refutação vinda de fora.", "Sofrer prova que ele não é extraordinário — e é justamente esse fracasso que abre a porta da redenção."],
  },
  {
    "slug": "ch04-sonia-amor-sacrificio-fe",
    "sub": "CAPÍTULO 4: Sônia — Amor, Sacrifício e Fé",
    "intro": "Sônia Marmeládova, atirada à rua para dar de comer à família, é a antítese viva da teoria: onde Raskólnikov pôs a razão, ela põe a fé e o amor. Figura de Cristo, transgrediu por amor aos outros — o avesso exato do orgulho do herói. A resposta dela ao assassino não é um silogismo, é um chamado: 'aceite o sofrimento e renasça'. E então, com a voz tremendo, ela lhe lê a ressurreição de Lázaro.",
    "cards": [
      {"ic":"leaf","t":"A Transgressão Pelo Amor","emph":"Pelo Amor","b":"Sônia também vendeu o corpo e rompeu a moral de Petersburgo — mas se entregou <strong>para estancar a fome dos irmãos</strong>. O contraste despe a teoria de Raskólnikov: a mesma queda pode brotar de raízes opostas e levar a destinos opostos, separando para sempre quem caiu por amor de quem caiu por orgulho.","tip":"<strong>Modelo mental:</strong> o 'o quê' de um ato diz pouco; o 'por quê' diz tudo. É o motivo escondido que decide em quem você vai se transformar."},
      {"ic":"book","t":"A Promessa de Lázaro","emph":"Promessa","b":"A leitura ofegante do morto que sai do túmulo não é interlúdio: é o <strong>mapa do epílogo</strong>. O Lázaro apodrecido na sepultura é o assassino lacrado dentro do próprio ego. Há retorno até para quem já cheira a defunto — mas o preço é render-se à luz que a teoria sempre tratou com desprezo.","tip":"<strong>Prática:</strong> em grandes romances, o coração simbólico costuma estar escondido no trecho que um personagem escolhe — ou é levado — a ler em voz alta."},
      {"ic":"key","t":"A Fé Que Não Argumenta","emph":"Não Argumenta","b":"Sônia não rebate as defesas eruditas do estudante com silogismos mais afiados — ela <strong>põe a própria vida sobre a mesa</strong>. Sua fé não tem verniz filosófico; é sacrifício de carne e osso, e fica de pé exatamente no ponto em que o imenso intelecto dele desaba. A vida vivida é o argumento que a vida pensada não consegue derrubar.","tip":"<strong>Sinal de alerta:</strong> a força de uma ideia destrutiva não se desarma com outra ideia, e sim com o choque de uma vida real que se nega a entrar na lógica dela.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["O móvel da transgressão (amor vs. orgulho) define o destino — a mesma ação tem raízes e desfechos opostos.", "A leitura de Lázaro é o programa do romance: morte em vida → ressurreição pelo sofrimento aceito.", "A fé de Sônia não é argumento, é vida encarnada — a refutação mais forte ao racionalismo amoral."],
  },
  {
    "slug": "ch05-porfiry-duelo-psicologico",
    "sub": "CAPÍTULO 5: Porfiry — O Duelo Psicológico",
    "intro": "Porfiry Pietróvitch, juiz de instrução, não caça provas — caça a alma. Sem uma evidência sequer, conduz um jogo de gato e rato armado sobre a psicologia e sobre a própria teoria do suspeito, certo de que a culpa fará o serviço de entregá-lo. Lá pelo fim, soa quase profeta: 'você precisa de ar' — confesse, não para perder, e sim para voltar a respirar.",
    "cards": [
      {"ic":"lens","t":"A Caça Pelas Ideias","emph":"Caça Pelas Ideias","b":"Porfiry trabalha sem digital, sem testemunha, sem arma: usa como laço o artigo brilhante que o próprio estudante publicou. Cada pergunta de cara inocente esconde uma estocada. Ele cutuca a vaidade de Raskólnikov e o obriga a <strong>exibir o orgulho que gerou o crime</strong> — porque sabe que orgulho nenhum resiste à tentação de explicar a própria genialidade.","tip":"<strong>Modelo mental:</strong> o interrogador mais perigoso é o que entendeu que o orgulhoso, mais cedo ou mais tarde, vai querer provar o quanto é superior."},
      {"ic":"wave","t":"A Angústia Como Álibi","emph":"Angústia","b":"O juiz percebe que não precisa torturar ninguém — a máquina do remorso já carrega o serviço pesado. Seu plano cabe numa linha: <strong>não deixar a culpa anestesiar</strong>. O tempo que se arrasta e o desespero de não poder dividir o segredo viram a polícia invisível. Diante daquele quarto sem ar, o degredo na Sibéria chega a soar como alívio.","tip":"<strong>Prática:</strong> contra um inimigo que se devora por dentro, às vezes a tática é não atacar — é deixá-lo gastar a própria força batendo nas paredes da mente."},
      {"ic":"fork","t":"O Oxigênio da Punição","emph":"Oxigênio","b":"Fitando os olhos assombrados do criminoso, Porfiry pronuncia o resgate disfarçado de sentença: 'Entregue-se — você <strong>está precisando de ar</strong>'. A punição deixa de soar como guilhotina e vira janela escancarada. Cumprir a pena não será o fim da vida de Raskólnikov; será, no paradoxo, o único caminho de volta a ela.","tip":"<strong>Regra:</strong> assumir a ferida sob o sol arde na hora; esconder a podridão no escuro envenena devagar, e por inteiro.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["Porfiry usa a teoria do próprio suspeito como isca — o orgulho intelectual é a brecha.", "A culpa interior trabalha em favor do investigador: o tormento da consciência é mais eficaz que a prisão.", "'Você precisa de ar': a confissão é respiro, não derrota."],
  },
  {
    "slug": "ch06-svidrigailov-o-duplo",
    "sub": "CAPÍTULO 6: Svidrigáilov — O Duplo Niilista",
    "intro": "Svidrigáilov é o espelho sombrio de Raskólnikov: vive o 'tudo é permitido' sem o menor resto de consciência. É o que o herói teria sido se a culpa tivesse calado a boca. Sensualista, predador — e, mesmo assim, capaz de gestos generosos. Seu fim é o tiro: não castigo cristão, mas tédio. O niilismo levado a sério até a última linha não desemboca na liberdade, desemboca no nada.",
    "cards": [
      {"ic":"masks","t":"O Espelho Sem Consciência","emph":"Sem Consciência","b":"Svidrigáilov é o espelho mais aterrador do livro: comete horrores em silêncio e <strong>não carrega o peso de uma só pena</strong>. Vive a cartilha do 'tudo é permitido' sem febre, sem delírio, sem o tribunal de dentro. É o fantasma do que Raskólnikov quis e não conseguiu ser — e encará-lo é encarar o próprio abismo de frente.","tip":"<strong>Sinal de alerta:</strong> veja no duplo frio a imagem crua do que sobra de um homem quando se lhe arranca a bússola moral e se conserva apenas o intelecto.","warn":True},
      {"ic":"gap","t":"O Fundo Falso do Nada","emph":"Fundo Falso","b":"O duplo tem lampejos de bondade — banca o enterro dos órfãos —, mas o gesto <strong>não o aquece nem o enche por dentro</strong>. Sem chão moral, a caridade vira capricho de quem não sabe o que fazer com o próprio dia. O niilismo coerente funciona certinho como relógio e, ainda assim, não fabrica sentido nenhum: só administra o vazio.","tip":"<strong>Modelo mental:</strong> um ato bom desligado de qualquer compromisso profundo não cura a doença de fundo — a falta de um porquê para acordar."},
      {"ic":"mountain","t":"O Tédio Até a Bala","emph":"Tédio","b":"Ele não encosta o cano na têmpora por culpa cristã, e sim por <strong>tédio insuportável</strong>. Sem tormento moral e sem um afeto que prenda à vida, os dias escorrem sem peso e sem urgência. O tiro na noite de chuva não é castigo: é o tédio existencial desligando a luz, porque já não há motivo para acordar amanhã.","tip":"<strong>Prática:</strong> antes de abraçar qualquer filosofia da liberdade absoluta, demore o olhar no fim de quem a viveu até a última página."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["O duplo revela aonde a ideia leva quando falta o freio da consciência.", "O niilismo coerente não produz sentido — as boas ações viram capricho arbitrário.", "O tiro de Svidrigáilov é o anti-epílogo: sem fé e sem consciência, o 'tudo é permitido' termina no nada."],
  },
  {
    "slug": "ch07-razumikhin-dunia-familia",
    "sub": "CAPÍTULO 7: Razumíkhin, Dúnia e a Família",
    "intro": "Os contrapontos saudáveis. Razumíkhin prova que a pobreza não empurra ninguém ao crime. Dúnia é o duplo positivo do herói — tão orgulhosa e forte quanto ele, mas com a fé que a segura à beira do abismo. E Lújin encarna o egoísmo 'respeitável': o mesmo cálculo gelado, só que dentro da lei e de gravata. É pelos que estão em volta que se mede o que veio a ser quem está no centro.",
    "cards": [
      {"ic":"person","t":"O Oposto Em Dobro","emph":"Oposto","b":"Razumíkhin afunda na mesma miséria aguda do herói, mas acorda cedo, trabalha duro e ri alto. Ele é a <strong>refutação viva que Dostoiévski deixa à mão</strong>: não foi a pobreza de Petersburgo que ergueu o machado. Foram a vaidade e a teoria, incubadas no isolamento de um quarto fechado, que assinaram as duas mortes.","tip":"<strong>Como aplicar:</strong> não meça a verdade só pela dor de quem caiu. Olhe também os que pisam a mesma lama e não se sujam — são eles que mostram o quanto sobra de desculpa."},
      {"ic":"scale","t":"O Orgulho Com Freio","emph":"Orgulho","b":"Dúnia tem a mesma altivez inquebrável e o mesmo olhar duro do irmão, mas carrega a <strong>fé cravada nas entranhas</strong>. Quando ergue o revólver contra Svidrigáilov no quarto trancado, prova que orgulho com bússola não precisa derramar sangue para vencer. A força dela se firma na defesa, jamais no ataque a uma ideia.","tip":"<strong>Modelo mental:</strong> o orgulho, sozinho, não é o pecado. O desastre começa quando a altivez corta o fio que ligava o homem ao resto do mundo."},
      {"ic":"key","t":"O Mal Respeitável","emph":"Mal Respeitável","b":"Lújin é o lado encerado da mesma moeda: tritura reputações e manobra viúvas pobres com a frieza de um bom advogado, sempre escorado em <strong>argumentos de mercado e boas maneiras</strong>. O romance o despreza de propósito, para lembrar que a violência calculada dos que andam dentro da lei também sai com as mãos sujas de sangue.","tip":"<strong>Armadilha:</strong> o cálculo metódico e chancelado pelas regras costuma deixar um rastro de destruição que nenhum tribunal alcança.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["Razumíkhin prova que a miséria não determina o crime — o contraponto serve de régua para o herói.", "O mesmo orgulho salva em Dúnia (com fé) e destrói em Raskólnikov (sem fé).", "Lújin encarna o crime dentro da lei — o egoísmo respeitável é tão corrosivo quanto o niilismo declarado."],
  },
  {
    "slug": "ch08-petersburgo-miseria-simbolos",
    "sub": "CAPÍTULO 8: Petersburgo, Miséria e Símbolos",
    "intro": "A cidade é personagem. Calor que sufoca, ruas imundas, o quarto-caixão amarelo onde a ideia apodrece como um corpo na gaveta. A miséria torna a teoria utilitarista sedutora — e o romance a denuncia sem nunca aceitá-la como desculpa. E os símbolos não enfeitam nada: carregam a tese pela obra inteira, do amarelo da doença ao machado, da água da morte à cruz da contrição.",
    "cards": [
      {"ic":"layers","t":"A Sujeira Como Bússola","emph":"Sujeira","b":"A poeira amarela do verão não decora o parágrafo: <strong>é o calor que esmaga que empurra o crime</strong>. Dostoiévski esfrega o ar rançoso na sua retina para que o delírio intelectual soe plausível — sem jamais validar a desculpa sociológica de que o assassino é mero refém da vizinhança onde nasceu.","tip":"<strong>Modelo mental:</strong> leia a descrição do espaço não como fotografia, mas como termômetro do caldeirão psicológico que ferve dentro do personagem."},
      {"ic":"eye","t":"A Paleta do Desespero","emph":"Paleta","b":"O <strong>amarelo</strong> mancha rostos doentes e papéis de parede em frangalhos. A <strong>água</strong> reflete o suicida e ao mesmo tempo promete o batismo. A <strong>cruz</strong> encarna o baque do renascimento. E o <strong>machado</strong> é a guilhotina da teoria descendo sobre inocentes. Em Dostoiévski, o objeto não acompanha a tese — ele a narra sozinho.","tip":"<strong>Prática:</strong> procure a chave filosófica por trás dos móveis quebrados e das paredes rachadas. Na boa literatura, o cenário também fala."},
      {"ic":"pin","t":"A Tumba de Três Passos","emph":"Tumba","b":"O cômodo apertado, de papel sujo, onde o assassino mal cabe <strong>é o útero sem ar do desastre</strong>. O orgulho inflamado e a imundície estrutural se alimentam um do outro até virar febre. Quando Porfiry diz 'você precisa de ar', a frase aponta para dois lugares de uma vez: os pulmões encurralados e a alma engaiolada.","tip":"<strong>Armadilha:</strong> o teto baixo comprime a mente. É quase impossível guardar clareza de horizonte quando se vive atolado na clausura.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["A cidade-personagem é argumento: torna a teoria compreensível sem nunca justificá-la.", "Os símbolos (amarelo, machado, água, cruz) carregam a tese ao longo de toda a obra.", "O quarto-caixão externaliza a clausura mental — em Dostoiévski, o espaço físico é sempre psicológico."],
  },
  {
    "slug": "ch09-confissao-sofrimento-epilogo",
    "sub": "CAPÍTULO 9: Confissão, Sofrimento e Ressurreição",
    "intro": "Empurrado pela consciência, por Sônia e por Porfiry, Raskólnikov vai à encruzilhada, beija a terra e se entrega — mas ainda sem se arrepender da ideia. No epílogo, depois de nove meses na Sibéria (a gestação do homem novo), sonha com a 'peste' do niilismo, desaba aos pés de Sônia e renasce pelo amor. Como Lázaro, a 'vida toma o lugar da dialética' — e o que o argumento nunca conseguiu, o sofrimento aceito faz.",
    "cards": [
      {"ic":"mountain","t":"A Palavra Antes da Culpa","emph":"Culpa","b":"No pátio gelado da delegacia o estudante pronuncia as palavras, mas os dentes cerrados confessam que a cabeça <strong>ainda ama a fórmula do crime</strong>. O arrependimento verdadeiro chega atrasado. Primeiro o corpo se ajoelha diante da lei; só depois, bem devagar, o ego racha diante da consciência. A confissão vem antes da contrição.","tip":"<strong>Como aplicar:</strong> aceite que consertar um erro às vezes começa pelo ato seco de se expor — não pela lágrima imediata, que pode nem ter chegado ainda."},
      {"ic":"spiral","t":"O Vírus Incurável do Ego","emph":"Vírus","b":"Varrendo o chão de uma Sibéria cinzenta, ele sonha com uma peste em que cada contaminado se proclama dono absoluto da verdade — uma <strong>epidemia de vaidade teórica</strong> que dissolve o mundo em guerra de todos contra todos. Esse pesadelo é a denúncia mais nítida de Dostoiévski contra o pensamento puro, fechado, lacrado contra qualquer amor.","tip":"<strong>Sinal de alerta:</strong> ideias que se julgam intocáveis matam mais que exércitos. A doença do ego que se crê dono da razão dispensa diagnóstico de médico.","warn":True},
      {"ic":"leaf","t":"A Dialética Desaba","emph":"Desaba","b":"À margem do rio siberiano, o herói se desfaz em pranto e se agarra aos joelhos de Sônia sem oferecer resistência. O castelo de silogismos evaporou diante do <strong>baque do amor encarnado</strong>. A carne que sangrou pelo orgulho descobre, enfim, que só se enche de paz por uma via: a aceitação do sofrimento partilhado.","tip":"<strong>Modelo mental:</strong> nenhuma muralha lógica resiste para sempre ao avanço silencioso de alguém disposto a sofrer ao seu lado."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["A confissão precede o arrependimento: o ato externo abre a porta da transformação interna.", "O sonho da peste diagnostica o niilismo racionalista como epidemia que destrói quem a carrega.", "'A vida toma o lugar da dialética': o amor e o sofrimento aceito fazem o que nenhum argumento faz."],
  },
]
