# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'O Design do Dia a Dia'
(Don Norman — The Design of Everyday Things). Frameworks canônicos: a culpa é
do design, não do usuário; os 5 princípios fundamentais (affordances /
significantes / mapeamento / feedback / restrições); mapeamento natural;
restrições físicas, culturais, semânticas e lógicas; modelo conceitual ×
modelo mental e a imagem do sistema; o Golfo da Execução e o da Avaliação +
os 7 estágios da ação; conhecimento na cabeça × no mundo; deslizes × enganos
e design à prova de erro; funções de força (poka-yoke, interlock, lock-in,
lock-out); HCD e o Duplo Diamante. Base: síntese dos frameworks amplamente
documentados — não reproduz o texto."""

BOOK = {
 "title": "O Design do Dia a Dia",
 "author": "Don Norman",
 "header_light": "O DESIGN",
 "header_bold": "DO DIA A DIA",
 "subtitle": "VISÃO GERAL · OS PRINCÍPIOS DO DESIGN CENTRADO NO HUMANO",
 "intro": "Você empurra a porta que era de puxar e sai dali achando que o tolo é você. Don Norman vira o veredito do avesso: a culpa é do design, não sua. Nesta obra fundadora da UX, ele mostra que um objeto bem feito explica a si mesmo — diz, sem manual, o que dá para fazer e o que cada coisa significa. E o melhor: depois de aprender a olhar assim, você nunca mais consegue desver o mau design escondido em tudo à sua volta.",
 "description": "O clássico que inventou o vocabulário do design centrado no humano. Don Norman destrincha os cinco princípios que fazem um objeto se explicar sozinho — affordances, significantes, mapeamento, feedback e restrições — e por que 'erro humano' é, quase sempre, erro de projeto disfarçado. Da psicologia da ação (os dois golfos, os sete estágios) ao design à prova de erro (deslizes × enganos, funções de força, poka-yoke), é o manual para fazer coisas que as pessoas usam sem precisar de manual.",
 "tags": ["Design", "UX", "Produtos Digitais"],
 "progress": "10 Capítulos",
 "cover": "assets/design-do-dia-a-dia-cover.png",
 "overview_cards": [
   {"ic":"key","t":"A Culpa é do Design, Não do Usuário","b":"O princípio-mãe da obra. Quando gente competente erra, se sente burra ou precisa de manual para o trivial, o defeito está <strong>no objeto, não nas pessoas</strong>. 'Erro humano' é, quase sempre, erro de projeto com um álibi. A pergunta certa não é 'por que fulano errou?', mas <strong>'o que no design o empurrou para o erro?'</strong>.","tip":"<strong>Como aplicar:</strong> diante de uma falha que se repete, conserte o objeto. 'Treinar o usuário a prestar atenção' é confessar que o design fracassou.","wide":True},
   {"ic":"layers","t":"Os 5 Princípios Fundamentais","b":"O checklist de todo bom design. <strong>Affordance</strong>: o que o objeto deixa você fazer. <strong>Significante</strong>: o sinal que diz onde e como agir. <strong>Mapeamento</strong>: a relação controle→efeito, que o arranjo natural torna óbvia. <strong>Feedback</strong>: a resposta imediata ao que você fez. <strong>Restrição</strong>: o limite que fecha o caminho errado.","tip":"<strong>Modelo mental:</strong> affordance é a possibilidade; significante é o aviso dela. O designer manda muito mais no aviso do que na possibilidade.","wide":True},
   {"ic":"gap","t":"Os Dois Golfos da Ação","b":"Entre você e o que quer fazer abrem-se dois abismos. O <strong>Golfo da Execução</strong> — 'como é que eu faço isto?' — você atravessa com significante, mapeamento e restrição. O <strong>Golfo da Avaliação</strong> — 'pronto, e agora, deu certo?' — você atravessa com feedback e um modelo claro. Projetar é jogar ponte sobre os dois.","tip":"<strong>Como aplicar:</strong> use os 7 estágios da ação como sonda para achar o ponto exato em que a interface deixa a pessoa na mão."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-psicopatologia","sub":"CAPÍTULO 1: A Psicopatologia das Coisas do Dia a Dia",
  "intro":"Quando um objeto é difícil de usar, a culpa é do design, não da pessoa. O bom objeto explica a si mesmo: você bate o olho e já sabe o que fazer. O ruim exige manual, provoca erro e ainda deixa você com a sensação de ser burro. É daqui que a obra inteira parte.",
  "cards":[
      {"ic":"key","t":"A Culpa é do Design, Não Sua","emph":"Design","b":"Você empurra a porta errada e o constrangimento é seu. Norman absolve o suspeito de sempre: se gente normal tropeça no mesmo objeto, o defeito não está nas pessoas. <strong>A pergunta deixa de ser 'quem errou?' e passa a ser 'o que neste objeto convidou ao erro?'.</strong>","tip":"<strong>Como aplicar:</strong> ao errar, suspeite do objeto antes de si mesmo. O erro é o sintoma; o design mal feito é a doença."},
      {"ic":"eye","t":"Descobrir e Compreender","emph":"Compreender","b":"Todo objeto responde a duas perguntas mudas. <strong>Descobribilidade:</strong> só de olhar, dá para ver o que se pode fazer e como? <strong>Compreensão:</strong> dá para entender o que está acontecendo e por quê? Um objeto bem feito responde às duas sem você ter de perguntar — nem abrir o manual.","tip":"<strong>Modelo mental:</strong> trate o produto como um guia silencioso. Se ele não toma você pela mão e mostra o caminho, ele falhou no básico."},
      {"ic":"gap","t":"A Maldição das Portas Norman","emph":"Portas Norman","b":"O símbolo do mau design é a porta com puxador grande que, no entanto, é de empurrar. A mão obedece ao puxador e dá com a cara na madeira. E se a operação mais boba já precisa de um adesivo 'EMPURRE', a porta perdeu a discussão. <strong>Placa, ali, é confissão de fracasso: estão consertando com fita o que devia se explicar sozinho.</strong>","tip":"<strong>Sinal de alerta:</strong> quando o conserto vira fita crepe e caneta no painel, pare de enfeitar — reprojete.","warn":True},
    ],
  "lessons_title":"Lições-Chave: A Psicopatologia",
  "lessons":["Dificuldade de uso fala mal do design, não da inteligência de quem usa.","Bom produto é descobrível (vê-se o que dá para fazer) e compreensível (entende-se o que está acontecendo).","Se o básico já exige manual, o objeto está mal projetado — e nenhum treinamento conserta isso."]},

 {"slug":"ch02-affordances-significantes-mapeamento","sub":"CAPÍTULO 2: Affordances, Significantes, Mapeamento e Feedback",
  "intro":"O design conversa com a gente por cinco princípios: affordance (o que dá para fazer), significante (onde e como agir), mapeamento (controle→efeito), feedback (o que aconteceu) e restrição (o que não fazer). Aqui ficam os quatro primeiros — o vocabulário básico de quem projeta para gente de verdade.",
  "cards":[
      {"ic":"target","t":"Affordance e Significante","emph":"Significante","b":"A cadeira oferece a affordance de sustentar seu peso — a possibilidade existe. Mas sem o significante — o assento à vista, o encosto que diz 'sente aqui' — você não sabe onde se acomodar. <strong>A affordance abre a porta; o significante é a placa que aponta para ela.</strong> O designer raramente cria a affordance; quase sempre, o que ele projeta é o aviso.","tip":"<strong>Como aplicar:</strong> na tela, não conte que vão adivinhar onde clicar. Faça o clicável parecer clicável — relevo, contorno, algo que peça o toque."},
      {"ic":"link","t":"O Mapeamento Natural","emph":"Mapeamento","b":"É quando o arranjo dos controles copia o arranjo das coisas. O botão da frente acende a boca da frente, o de trás a de trás: o painel vira um mapinha do fogão, e some a bula. <strong>Em vez de pedir que a pessoa decore qual botão é qual, deixe o espaço responder por você.</strong>","tip":"<strong>Regra:</strong> posicione o controle onde a ação acontece — em cima para subir, à direita para avançar. O lugar já é metade da instrução."},
      {"ic":"wave","t":"O Retorno Imediato","emph":"Retorno","b":"Sem feedback, a pessoa fica no escuro: apertou e nada, então aperta de novo — e dispara a ação duas vezes. Um clique, um bipe, uma luz que pisca já resolvem. <strong>Mas o oposto também afunda: resposta demais vira barulho, e a informação que importa se perde no meio do alarme.</strong>","tip":"<strong>Modelo mental:</strong> o feedback chega no instante da ação. Um atraso de fração de segundo já é suficiente para a pessoa duvidar se funcionou."},
    ],
  "lessons_title":"Lições-Chave: Os Princípios",
  "lessons":["Affordance diz o que é possível; significante diz onde e como — não dá para ter um sem o outro.","Mapeamento natural torna a relação controle→efeito tão óbvia que dispensa explicação.","Todo controle pede feedback imediato e informativo — nem mudo (gera insegurança), nem aos berros (vira ruído)."]},

 {"slug":"ch03-psicologia-das-acoes","sub":"CAPÍTULO 3: A Psicologia das Ações do Dia a Dia",
  "intro":"Entre o que você quer e o mundo lá fora há sempre uma travessia. Quando o design não ajuda nem a planejar a ação, nem a entender o resultado, dois abismos se abrem: o Golfo da Execução, na ida, e o Golfo da Avaliação, na volta.",
  "cards":[
      {"ic":"steps","t":"Os Sete Estágios da Ação","emph":"Estágios","b":"Agir parece instantâneo, mas tem etapas. Na ida: você forma o objetivo, decide o que fazer e faz. Na volta: percebe o que mudou, interpreta e compara com o que queria. <strong>Conheça os sete estágios e você consegue apontar com o dedo em qual deles a pessoa empacou.</strong>","tip":"<strong>Prática:</strong> percorra os 7 estágios como um roteiro de inspeção quando for caçar a fricção de qualquer produto."},
      {"ic":"gap","t":"A Travessia dos Dois Golfos","emph":"Golfos","b":"Na ida, o Golfo da Execução: não saber como fazer a coisa funcionar. Na volta, o Golfo da Avaliação: não saber se ela fez o que você pediu. <strong>Projetar bem é lançar ponte sobre os dois — mapeamento e significante claros na ida, feedback honesto na volta.</strong>","tip":"<strong>Como aplicar:</strong> faça ao projeto duas perguntas: 'como a pessoa descobre a primeira ação?' e 'como ela sabe que deu certo?'."},
      {"ic":"lens","t":"O Cérebro em Três Níveis","emph":"Três Níveis","b":"O produto fala com três camadas suas ao mesmo tempo. A <strong>visceral</strong> reage à aparência num átimo, antes de pensar. A <strong>comportamental</strong> sente prazer (ou raiva) no uso. A <strong>reflexiva</strong> pondera depois — o que aquilo diz sobre quem você é. Bom design não escolhe uma; agrada às três.","tip":"<strong>Modelo mental:</strong> a beleza convida a entrar, o uso decide se você fica, e o orgulho de ter aquilo é o que faz você voltar."},
    ],
  "lessons_title":"Lições-Chave: A Psicologia da Ação",
  "lessons":["Os 7 estágios são uma lupa: servem para localizar o ponto exato em que a interface falha.","Significante e mapeamento estreitam o golfo da execução; feedback estreita o da avaliação.","Projete para os três níveis ao mesmo tempo: visceral, comportamental e reflexivo."]},

 {"slug":"ch04-conhecimento-cabeca-mundo","sub":"CAPÍTULO 4: Conhecimento na Cabeça e no Mundo",
  "intro":"A gente não precisa carregar tudo na cabeça: o mundo também guarda informação. Distinguimos uma moeda da outra sem saber desenhá-las, porque a pista está no próprio objeto. Bom design entende isso e põe o conhecimento no mundo, em vez de exigir que você decore.",
  "cards":[
      {"ic":"book","t":"Na Cabeça ou no Mundo","emph":"no Mundo","b":"Tudo que depende da memória sobrecarrega a cabeça e desaba na hora do aperto. O truque do bom design é o oposto: <strong>espalhar a pista no próprio objeto — formato, tamanho, posição, rótulo — para que a coisa diga o que é.</strong> Aí você não decora; só olha.","tip":"<strong>Como aplicar:</strong> se a tela obriga a guardar códigos de cabeça, é sinal de falha. Traga as opções para a vista e deixe a escolha óbvia."},
      {"ic":"bulb","t":"Quando os Modelos Brigam","emph":"Brigam","b":"O designer tem na cabeça um modelo conceitual de como a coisa funciona. O usuário monta o seu próprio modelo mental a partir do que vê — um palpite sobre o que há por dentro. <strong>O erro nasce na hora exata em que esses dois palpites não batem.</strong>","tip":"<strong>Sinal de alerta:</strong> quando a pessoa aperta o botão dez vezes achando que apressa a impressora, foi o seu modelo conceitual que não chegou até ela."},
      {"ic":"eye","t":"A Imagem do Sistema Fala por Você","emph":"Imagem do Sistema","b":"O designer não está ali para explicar; ficou calado, em outro prédio, anos atrás. O único recado que chega ao usuário é o que o próprio aparelho mostra — a imagem do sistema. <strong>O que o projeto não disser pela tela, pela forma e pelos botões, não foi dito. O que está invisível, para quem usa, não existe.</strong>","tip":"<strong>Regra:</strong> não conte com o manual em letra miúda para tapar o que a interface deixou de explicar. Quase ninguém o lê."},
    ],
  "lessons_title":"Lições-Chave: O Conhecimento",
  "lessons":["Não exija memória: ponha no próprio objeto o conhecimento de que a ação precisa.","O designer só fala pela imagem do sistema — se ela não comunica o modelo conceitual, ele se perde.","O erro aparece quando o modelo mental de quem usa diverge do modelo conceitual real."]},

 {"slug":"ch05-restricoes-descoberta","sub":"CAPÍTULO 5: Restrições, Descobribilidade e Feedback",
  "intro":"Restrição é o limite que fecha portas erradas e deixa só a certa em aberto — guiando a pessoa sem que ela tenha de pensar. Quanto menos opções inúteis, menos coisa para aprender e menos chance de errar.",
  "cards":[
      {"ic":"scale","t":"As Quatro Restrições","emph":"Quatro","b":"São quatro tipos que trabalham juntos. A <strong>física</strong> impede o encaixe errado (a peça só entra de um jeito). A <strong>cultural</strong> e a <strong>semântica</strong> dizem, pelo costume e pelo sentido, qual é o caminho. A <strong>lógica</strong> elimina o resto por dedução. Somadas, deixam o acerto como a única saída natural.","tip":"<strong>Prática:</strong> projete o encaixe assimétrico — faça com que a peça só caiba pelo lado certo. Aí o erro nem chega a ser uma opção."},
      {"ic":"link","t":"Quando Não Há Natural, Padronize","emph":"Padronize","b":"Nem tudo tem um mapeamento natural à mão — e aí entra a padronização. Convenção até imperfeita, como o teclado QWERTY, vinga porque todo mundo já a conhece. <strong>Aprende-se uma vez e a vida inteira aproveita; mudar a toa só obrigaria todo mundo a reaprender.</strong>","tip":"<strong>Como aplicar:</strong> não reinvente a roda. Se uma cor, um símbolo ou uma posição já virou linguagem comum, respeite — a familiaridade vale mais que a sua ideia nova."},
      {"ic":"wave","t":"O Som Que Confirma","emph":"Som","b":"O estalo seco da tranca é uma resposta completa: você sabe que fechou sem testar a maçaneta. Sons assim confirmam e orientam ao mesmo tempo, de graça. <strong>Quem silencia o aparelho 'por causa do design' costuma apagar, junto, a única pista que dizia à pessoa que deu certo.</strong>","tip":"<strong>Sinal de alerta:</strong> cuidado ao 'limpar o produto' a ponto de remover o clique, o estalo, o bipe que davam a sensação de segurança."},
    ],
  "lessons_title":"Lições-Chave: As Restrições",
  "lessons":["Combine as quatro restrições — física, cultural, semântica e lógica — para deixar o caminho certo como o único óbvio.","Quanto mais a restrição guia, menos a pessoa precisa aprender e menos erro ela tem como cometer.","Faltando mapeamento natural, apoie-se na padronização e respeite a convenção já estabelecida."]},

 {"slug":"ch06-funcoes-de-forca","sub":"CAPÍTULO 6: Funções de Força — Tornar Difícil o Erro Grave",
  "intro":"Quando o erro pode sair caro ou perigoso, restrição leve não basta. Aí entra a função de força — uma trava firme que segura a próxima ação até o passo certo ser dado, ou que bloqueia de vez o acesso à ação arriscada.",
  "cards":[
      {"ic":"sword","t":"As Travas de Força","emph":"Travas","b":"A função de força não pede educação: ela impede. Obriga a sequência certa (<strong>interlock</strong>), proíbe encerrar antes da hora (<strong>lock-in</strong>) ou veda a zona perigosa (<strong>lock-out</strong>). Onde o erro é irreversível, não confie no bom senso de ninguém — confie na trava.","tip":"<strong>Modelo mental:</strong> se o erro custa dados perdidos ou gente machucada, levante uma barreira de verdade. Aviso gentil não segura ninguém."},
      {"ic":"constellation","t":"Tornar o Erro Impossível","emph":"Impossível","b":"O poka-yoke japonês não previne o deslize com uma cor de alerta; previne com a forma. Um pino fora de lugar, um conector que só encaixa de um jeito, um sensor que conta peças. <strong>O acidente não é desencorajado — ele simplesmente deixa de ser possível.</strong>","tip":"<strong>Prática:</strong> onde o erro sai caro, desenhe formatos e gabaritos únicos, que recusem fisicamente o encaixe errado."},
      {"ic":"bubble","t":"Aviso Não Substitui Trava","emph":"Aviso","b":"Confiar a operações graves apenas a pop-ups e adesivos berrantes é empurrar para o usuário um risco que era do projeto. Na rotina e no cansaço, o aviso vira paisagem e ninguém mais o lê. <strong>Para o erro irreparável, troque o papel pela barreira mecânica.</strong>","tip":"<strong>Armadilha:</strong> trava demais também é problema — quando incomoda, a equipe acaba desligando tudo, e a proteção desmorona inteira.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Funções de Força",
  "lessons":["Para o erro grave, não avise: use uma função de força e torne-o impossível.","Interlock impõe a ordem; lock-in impede sair cedo; lock-out veda a zona proibida — escolha pelo risco.","Poka-yoke: o melhor controle de erro é não deixar o erro ter como acontecer."]},

 {"slug":"ch07-erro-humano-mau-design","sub":"CAPÍTULO 7: Erro Humano? Não, Mau Design",
  "intro":"A maior parte do que chamamos de 'erro humano' é erro de design: o sistema permitiu, induziu ou não preveniu o tropeço. Há dois tipos bem diferentes de erro — o deslize e o engano — e cada um pede um remédio próprio.",
  "cards":[
      {"ic":"pivot","t":"Deslize Não É Engano","emph":"Deslize","b":"No deslize, o plano estava certo e a mão errou — você quis o botão verde e apertou o vermelho ao lado, no automático. No engano, o plano já estava errado desde o início: você fez direitinho a coisa errada. <strong>Saber qual dos dois aconteceu é o que decide o remédio.</strong>","tip":"<strong>Como aplicar:</strong> pergunte se o objetivo estava certo e a execução escorregou (deslize) — ou se a decisão já vinha torta (engano)."},
      {"ic":"target","t":"Cada Erro, Seu Remédio","emph":"Remédio","b":"Deslize se combate com feedback claro, restrição e, acima de tudo, Desfazer barato — a rede que apara a queda leve. Engano é outra história: pede melhor informação e um modelo conceitual mais claro, para a decisão nascer certa. <strong>Trocar os remédios não resolve nem um, nem outro.</strong>","tip":"<strong>Modelo mental:</strong> proteja a rotina com o Desfazer; quando houver engano, conserte o entendimento, não só a tela."},
      {"ic":"mask","t":"O Erro de Modo","emph":"Erro de Modo","b":"Um dos deslizes mais traiçoeiros vem do 'modo': a mesma tecla faz coisas diferentes conforme o estado em que o aparelho está — e esse estado não aparece. A pessoa age achando que está num modo, mas estava em outro. <strong>O culpado não é quem operou: é o sistema que escondeu em que pé estava.</strong>","tip":"<strong>Sinal de alerta:</strong> culpar quem errou e fechar o caso é a garantia de que o mesmo acidente vai se repetir, com outra pessoa."},
    ],
  "lessons_title":"Lições-Chave: Erro Humano",
  "lessons":["Classifique antes de consertar: deslize (objetivo certo, ação errada) ou engano (objetivo errado).","Deslize pede feedback, restrição e Desfazer; engano pede melhor modelo conceitual e informação.","Não culpe quem usou: pergunte por que o sistema deixou o erro acontecer — e conserte o design."]},

 {"slug":"ch08-design-a-prova-de-erro","sub":"CAPÍTULO 8: Design à Prova de Erro",
  "intro":"Como as pessoas vão errar de qualquer jeito, o design honesto conta com isso: dificulta o erro grave, deixa o engano à vista e torna o conserto fácil. Errar precisa ser barato e ter volta.",
  "cards":[
      {"ic":"steps","t":"As Quatro Camadas de Defesa","emph":"Camadas","b":"As defesas vêm em ordem. Primeiro, <strong>previna</strong> com restrições. Não deu? <strong>Torne o erro visível</strong>, para ser pego cedo. Depois, garanta a <strong>volta fácil</strong> — Desfazer barato. E só no fim, para o que não tem retorno, reserve a <strong>confirmação séria</strong>.","tip":"<strong>Como aplicar:</strong> faça o erro comum custar quase nada; guarde a confirmação pesada apenas para a beira do precipício, onde não há undo."},
      {"ic":"spark","t":"O Poder do Desfazer","emph":"Desfazer","b":"O 'Tem certeza?' é quase inútil: no piloto automático, todo mundo clica 'Sim' sem ler. O que de fato protege é um Desfazer discreto e sempre à mão. <strong>Dê à pessoa a liberdade de tropeçar e apagar o rastro depois — sem susto, sem cerimônia.</strong>","tip":"<strong>Regra:</strong> não faça assinar um termo para jogar algo no lixo. Ofereça uma corda de resgate — a lixeira que segura o arquivo por uns dias."},
      {"ic":"bubble","t":"A Mensagem de Erro Que Ajuda","emph":"Ajuda","b":"Uma tela que cospe um código indecifrável e nenhuma saída não é ajuda — é o produto lavando as mãos. <strong>Boa mensagem de erro fala a língua da pessoa, diz o que aconteceu sem culpá-la e já oferece o caminho para corrigir e seguir em frente.</strong>","tip":"<strong>Armadilha:</strong> jargão técnico no alerta esconde a falha de usabilidade por trás dele — e gasta o último resto de confiança de quem está ali travado."},
    ],
  "lessons_title":"Lições-Chave: À Prova de Erro",
  "lessons":["Conte com o erro: previna o grave, deixe o engano visível e dê sempre a volta por cima.","Reserve a confirmação pesada para o irreversível; no resto, ofereça Desfazer.","Mensagem de erro existe para explicar e ajudar a consertar — nunca apenas para acusar."]},

 {"slug":"ch09-design-centrado-no-humano","sub":"CAPÍTULO 9: Design Centrado no Humano e Design Thinking",
  "intro":"Bom design começa antes do desenho: começa em resolver o problema certo, partindo do que as pessoas de fato precisam. O Design Centrado no Humano (HCD) é o ciclo de observar, idealizar, prototipar e testar — de novo e de novo.",
  "cards":[
      {"ic":"leaf","t":"Centrado em Gente de Verdade","emph":"Gente de Verdade","b":"HCD vira a ordem do design de cabeça para baixo: em vez de partir da tecnologia, parte da pessoa. E não acerta de primeira — roda em ciclo: observar, idealizar, montar um protótipo tosco e levá-lo ao teste com gente real. <strong>O protótipo não é a obra; é a pergunta barata que ensina o que não construir.</strong>","tip":"<strong>Prática:</strong> nunca trate o primeiro protótipo como pronto. Ele existe para falhar cedo e barato, enquanto consertar ainda custa pouco."},
      {"ic":"mountain","t":"O Duplo Diamante","emph":"Duplo Diamante","b":"São quatro tempos. No primeiro, você abre o leque para entender o problema de verdade; no segundo, fecha e define qual é. Só então abre de novo, agora para soluções, e fecha na que resolve. <strong>Resolver brilhantemente o problema errado é o fracasso mais caro que existe.</strong>","tip":"<strong>Modelo mental:</strong> antes de correr para a solução, pare e pergunte se o problema que você atacou é mesmo o problema certo."},
      {"ic":"lens","t":"Não Pergunte, Observe","emph":"Observe","b":"Pesquisa e entrevista contam o que a pessoa acha que faz — uma versão arrumada. O que ela faz mesmo só aparece quando você a observa no dia a dia, onde estão as gambiarras que ninguém conta na sala de reunião. <strong>Quando a fala briga com o comportamento, acredite no comportamento.</strong>","tip":"<strong>Sinal de alerta:</strong> empilhar função em cima de função para tapar uma dor que você nunca foi ver de perto só piora o produto inteiro."},
    ],
  "lessons_title":"Lições-Chave: HCD",
  "lessons":["Ache o problema certo antes de caçar a solução certa — é para isso que serve o Duplo Diamante.","HCD é um ciclo, não uma linha reta: observar → idealizar → prototipar → testar, repetidamente.","Observe o que as pessoas fazem; o que elas dizem que fazem é só parte da verdade."]},

 {"slug":"ch10-design-no-mundo-dos-negocios","sub":"CAPÍTULO 10: Design no Mundo dos Negócios",
  "intro":"Na vida real, o design ideal esbarra em prazo, custo, concorrência e briga interna. Entender essas forças — e como a tecnologia evolui e se espalha — é o que separa o bom design no papel do produto que de fato chega à mão das pessoas.",
  "cards":[
      {"ic":"scale","t":"Design é Negociação","emph":"Negociação","b":"A tela perfeita topa com orçamento estourado, marketing pedindo mais uma função e o relógio da prateleira. O design real não vive no vácuo: <strong>é a arte de ceder no acessório sem entregar o essencial — o que fazia a coisa resolver o problema.</strong>","tip":"<strong>Modelo mental:</strong> trate a restrição dura do negócio não como muro, mas como o molde que dá forma à solução final."},
      {"ic":"spiral","t":"A Praga da Featuritis","emph":"Featuritis","b":"Versão após versão, vão se grudando funções que brilham no anúncio e atrapalham no uso diário. <strong>Menu inchado é produto cansativo: cada novo brilho cobra seu pedágio em clareza, e o todo fica mais difícil de usar do que era.</strong>","tip":"<strong>Cuidado:</strong> dizer 'não' a pedido fútil — inclusive ao da chefia — é exatamente onde se defende o valor limpo da solução."},
      {"ic":"clock","t":"O Peso dos Legados","emph":"Legados","b":"A maioria das mudanças que pegam é incremental — pequenos passos que o público absorve sem susto. A virada radical existe, mas cobra anos e a dor de gente reaprender o hábito. <strong>Seguimos com o teclado QWERTY e controles ilógicos no carro não porque sejam bons, mas porque todo mundo já os conhece — e largar o conhecido custa caro.</strong>","tip":"<strong>Regra:</strong> aposte nas pequenas melhorias seguras do dia a dia e trate a revolução radical como aposta de longo prazo, de retorno incerto."},
    ],
  "lessons_title":"Lições-Chave: O Mundo dos Negócios",
  "lessons":["Bom design é negociação constante com prazo, custo, marketing e concorrência.","Resista à featuritis: toda função extra cobra um preço em clareza e usabilidade.","Conte com inovação quase sempre incremental; a radical é aposta lenta e cara de longo prazo."]},
]
