# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Do Mil ao Milhão: Sem Cortar o Cafezinho' (Thiago Nigro)."""

BOOK = {
 "title": "Do Mil ao Milhão",
 "author": "Thiago Nigro (Primo Rico)",
 "header_light": "DO MIL AO",
 "header_bold": "MILHÃO",
 "subtitle": "VISÃO GERAL · SEM CORTAR O CAFEZINHO",
 "intro": "Te venderam uma mentira confortável: que você fica rico cortando o café de R$ 5. Não fica. Thiago Nigro vira a conta do avesso — corte de gasto tem fundo (zero, e ninguém vive com zero), mas renda não tem teto. Riqueza é trabalhar três alavancas ao mesmo tempo: gastar bem, investir melhor e ganhar mais. Quem só economiza migalha gasta a vida apertando o que não muda o jogo. Tome o café. Faz a conta grande.",
 "description": "O guia de finanças do Primo Rico para quem está começando do zero. A tese dos três pilares (gastar bem, investir melhor, ganhar mais), o mito do cafezinho, orçamento sem neura, os tipos de gasto, como matar as dívidas caras, renda fixa contra renda variável, juros compostos a seu favor, por que a poupança te empobrece em silêncio — e o caminho real do primeiro mil ao primeiro milhão.",
 "tags": ["Educação Financeira", "Investimentos", "Independência Financeira"],
 "progress": "9 Capítulos",
 "cover": "assets/do-mil-ao-milhao-cover.png",
 "overview_cards": [
   {"ic":"triangle","t":"Os 3 Pilares da Riqueza","b":"Não tem segredo, tem três frentes ao mesmo tempo: (1) <strong>Gastar Bem</strong> — gaste menos do que ganha; (2) <strong>Investir Melhor</strong> — faça a sobra render acima da inflação; (3) <strong>Ganhar Mais</strong> — a maior alavanca, porque renda não tem teto. Mexer num pilar só não te tira do lugar; o patamar muda quando os três giram juntos.","tip":"<strong>Como aplicar:</strong> descubra qual dos três é o seu mais fraco e ataque por ele. É onde você está deixando dinheiro na mesa.","wide":True},
   {"ic":"spiral","t":"A Conta da Riqueza","b":"Riqueza não é mágica, é uma conta: <strong>Patrimônio = (o que você ganha − o que você gasta), investido por tempo suficiente para os juros compostos trabalharem.</strong> Os três pilares mexem exatamente aí — derruba o gasto, sobe a renda, melhora a taxa e o prazo do investimento. O resto é detalhe.","tip":"<strong>Modelo mental:</strong> banco de três pernas. Faltou uma, você senta no chão."},
   {"ic":"leaf","t":"O Mito do Cafezinho","b":"Cortar R$ 5 por dia não faz ninguém milionário — faz uma pessoa amarga com o bolso igual. A energia que você queima caçando centavos rende muito mais aplicada em quitar dívida, investir cedo e, acima de tudo, <strong>ganhar mais</strong>. Tome o café e olhe pra cifra grande.","tip":"<strong>Sinal de alerta:</strong> se você só pensa em pequenos cortes e nunca em renda e investimento, caiu na armadilha que te mantém pobre."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-tres-pilares","sub":"CAPÍTULO 1: Os Três Pilares da Riqueza",
  "intro":"Esquece a fórmula mágica: ficar rico é mexer em três coisas ao mesmo tempo — Gastar Bem, Investir Melhor e Ganhar Mais. O erro de quase todo mundo é grudar no primeiro, viver apertando gasto, e ignorar os outros dois — principalmente o terceiro, que é a alavanca mais forte de todas.",
  "cards":[
      {"ic":"triangle","t":"Os Três Pilares","emph":"Três Pilares","b":"Riqueza não é um truque, é um tripé. Gastar Bem te salva o mês, Investir Melhor coloca o tempo do seu lado, e Ganhar Mais é o que te tira do teto que você acha que é o seu limite. <strong>Passar a vida só apertando gasto é dirigir com o freio de mão puxado: você anda, mas nunca chega</strong>.","tip":"<strong>Prática:</strong> tripé manco cai. Olhe pro seu pilar mais fraco hoje e comece a escorar ele — é ali que está o seu dinheiro parado."},
      {"ic":"spark","t":"O Mito do Cafezinho","emph":"Cafezinho","b":"'Corta o café que você enriquece' é a desculpa mais bem-vendida do Brasil. Gasto tem fundo — você não consegue gastar menos que zero. Renda não tem teto. <strong>Suar pra economizar R$ 150 no mês enquanto ignora como ganhar R$ 1.500 a mais é trocar o ouro por moeda de chocolate</strong>.","tip":"<strong>Modelo mental:</strong> quem só joga pra não perder nunca aprende a ganhar. E na vida real, ficar no zero a zero é derrota."},
      {"ic":"layers","t":"A Conta da Riqueza","emph":"Conta","b":"O milhão não cai do céu, ele é uma conta: o que sobra da sua renda menos seus gastos, jogado nos juros compostos por tempo suficiente. <strong>Mas se o seu bolso é um balde furado, nem salário de diretor chega vivo no fim do mês — o problema nunca foi o quanto entra, e sim o quanto vaza</strong>.","tip":"<strong>Sinal de alerta:</strong> achar que o próximo aumento vai resolver tudo é a ilusão favorita de quem nunca controlou o que já ganha.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Riqueza vem dos três pilares juntos — nenhum sozinho te leva longe.","O cafezinho é distração; a renda é a alavanca de verdade.","Acerte qual é o seu pilar mais fraco e comece o trabalho por ele."]},

 {"slug":"ch02-gastar-bem-orcamento","sub":"CAPÍTULO 2: Gastar Bem — Orçamento",
  "intro":"É daqui que tudo nasce: pra sobrar dinheiro pra investir, você precisa gastar menos do que ganha. Sem essa sobra, não existe ponto de partida — você só fica girando no lugar. E a ferramenta que garante a sobra é o orçamento.",
  "cards":[
      {"ic":"scale","t":"A Regra-Mãe","emph":"Regra-Mãe","b":"Toda a riqueza começa numa frase boba que quase ninguém respeita: gaste menos do que você ganha. A diferença entre o que entra e o que sai é a única matéria-prima que constrói patrimônio. <strong>Se você não defende a sua sobra todo mês como se fosse o seu salário, ela some — e com ela some o seu futuro</strong>.","tip":"<strong>Como aplicar:</strong> o número que importa não é o que cai na conta no dia 5. É o que ainda está lá no dia 30."},
      {"ic":"lens","t":"O Orçamento é o Seu Espelho","emph":"Espelho","b":"Quem não anota pra onde o dinheiro vai entrega o controle pro acaso. Orçamento não é regime de fome — é a radiografia que mostra exatamente por onde o seu dinheiro vaza. <strong>Recusar olhar pra própria planilha é dirigir de olhos fechados a 120 e ainda achar que está no controle</strong>.","tip":"<strong>Regra:</strong> não guarde o que sobrar — não vai sobrar. Tire o seu percentual no dia em que o dinheiro cai, e viva com o resto."},
      {"ic":"clock","t":"Padrão de Vida × Renda","emph":"Padrão de Vida","b":"O que mais quebra quem ganha bem não é falta de dinheiro, é a inflação do estilo de vida: cada aumento vira carro novo, apartamento maior, gasto maior. Você ganha mais e continua pobre — só que com boleto mais caro. <strong>Quando a renda sobe, segure o padrão. Deixa a diferença ir pra corretora, não pra concessionária</strong>.","tip":"<strong>Armadilha:</strong> a promoção que você torra inteira no novo padrão de vida não te liberta — só aperta a coleira com banho de loja.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["Gaste menos do que ganha — a sobra é o combustível de tudo.","Monte e revise o orçamento; é o painel de controle do seu dinheiro.","Quando a renda sobe, não deixe o padrão de vida subir junto."]},

 {"slug":"ch03-tipos-de-gasto","sub":"CAPÍTULO 3: Os Tipos de Gasto",
  "intro":"Nem todo gasto é igual. Quando você sabe pra onde o dinheiro vai, dá pra cortar o que não faz falta sem mexer no que importa. Gastar bem não é gastar pouco — é gastar com consciência.",
  "cards":[
      {"ic":"cards","t":"Classifique Antes de Cortar","emph":"Classifique","b":"Antes de sair cortando, você precisa enxergar onde está a gordura. Gasto é fixo, variável ou supérfluo — e cada um pede um tratamento diferente. <strong>Sair cortando no escuro e atingir justo aquilo que aumenta a sua renda é dar um tiro no próprio pé achando que está economizando</strong>.","tip":"<strong>Prática:</strong> separe a fatura por tipo hoje e mire primeiro no que não te dá nem saúde, nem prazer real, nem dinheiro lá na frente."},
      {"ic":"wrench","t":"Ataque os Fixos Primeiro","emph":"Fixos","b":"Cortar a sobremesa alivia a consciência; renegociar os fixos resolve o problema. O ganho de verdade está nas mensalidades, nas assinaturas que você esqueceu e nos juros do dia a dia. <strong>Derrubar um boleto fixo te devolve dinheiro todo santo mês — sem você precisar sofrer de novo</strong>.","tip":"<strong>Modelo mental:</strong> não é sobre cortar o que te dá vida. É sobre parar de pagar empresa que você nem lembra que assinou."},
      {"ic":"bulb","t":"Gasto Bom × Gasto Ruim","emph":"Gasto Bom","b":"A diferença entre gasto e investimento é uma só: o retorno lá na frente. Gasto ruim seca a fonte e não te devolve nada. Mas <strong>cancelar o curso, o livro ou a ferramenta que faz você ganhar mais, só pra economizar uns trocados, é comer a semente em vez de plantar</strong>.","tip":"<strong>Sinal de alerta:</strong> economizar em saúde e em formação não te deixa rico — só te deixa cansado e ultrapassado.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["Classifique todo gasto: fixo, variável, supérfluo ou investimento.","Comece pelos fixos mal contratados — corte que dói pouco e rende muito.","Nunca corte o gasto que aumenta a sua renda futura."]},

 {"slug":"ch04-sair-das-dividas","sub":"CAPÍTULO 4: Sair das Dívidas",
  "intro":"Antes de pensar em investir, mate as dívidas caras. O juro que a dívida cobra de você quase sempre é maior do que qualquer rendimento que você conseguiria. Por isso, quitar dívida de juro alto é o investimento mais garantido que existe.",
  "cards":[
      {"ic":"sword","t":"Juro da Dívida > Qualquer Rendimento","emph":"Juro","b":"Nenhum investimento seguro rende o que o cartão rotativo cobra de você — uns 300% ao ano. Quitar essa dívida não é 'pagar conta', é o melhor negócio da sua vida: é um rendimento de 300% garantido. <strong>Investir um real enquanto carrega rotativo é tapar um buraco enchendo outro maior</strong>.","tip":"<strong>Como aplicar:</strong> sem segredo. Liste as dívidas, ataque a de juro mais alto primeiro e pause qualquer outro investimento até ela morrer."},
      {"ic":"spiral","t":"Juros Compostos Contra Você","emph":"Contra Você","b":"Os juros compostos são uma força neutra: a mesma que constrói o patrimônio do rico cava o buraco do endividado. Quando você rola a fatura, a dívida cobra juro sobre o próprio juro e engorda sozinha. <strong>É a bola de neve, só que descendo a ladeira por cima de você</strong>.","tip":"<strong>Armadilha:</strong> o pagamento mínimo do cartão não te dá fôlego — ele só estica a corda devagarinho até apertar de vez.","warn":True},
      {"ic":"wrench","t":"Renegocie Sem Vergonha","emph":"Renegocie","b":"O banco prefere receber pouco e devagar a não receber nada. Por isso tem muito mais margem pra negociar do que ele deixa transparecer. <strong>Antes de pagar mais, troque a dívida cara por uma barata: pegue um crédito de juro menor pra liquidar o rotativo e respire</strong>.","tip":"<strong>Regra:</strong> não tenha dó de ligar e dizer que vai levar a dívida pra outro banco. Lealdade bancária só enche o cofre deles, nunca o seu."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["Quite as dívidas caras antes de começar a investir.","Ataque sempre a dívida de maior juro primeiro.","Renegocie: troque dívida cara por barata e derrube a taxa."]},

 {"slug":"ch05-investir-melhor-renda-fixa-variavel","sub":"CAPÍTULO 5: Renda Fixa × Renda Variável",
  "intro":"Investir melhor começa por entender as duas grandes famílias de investimento, descobrir o seu perfil e só então escolher onde colocar o dinheiro. O erro número um do brasileiro é deixar tudo parado na poupança e achar que está investindo.",
  "cards":[
      {"ic":"scale","t":"Renda Fixa × Variável","emph":"Renda Fixa","b":"Na renda fixa você empresta dinheiro e sabe mais ou menos quanto vai receber — risco menor, sono tranquilo. Na variável você vira sócio e aceita o sobe e desce em troca de ganhos maiores no longo prazo. <strong>Usar as duas é montar o seu colete salva-vidas e o seu foguete; saber qual é o seu estômago é o que separa investir de apostar</strong>.","tip":"<strong>Modelo mental:</strong> quanto mais tempo você tem pela frente, mais oscilação da bolsa o seu estômago aguenta."},
      {"ic":"lens","t":"Conheça o Seu Perfil","emph":"Perfil","b":"Seu perfil de risco não se descobre no dia de alta — todo mundo é corajoso quando está ganhando. Ele aparece no dia do tombo, quando a tela fica vermelha. <strong>Sem a reserva de emergência blindada, a sua coragem evapora no primeiro susto e você vende tudo no fundo do poço, justo a hora errada</strong>.","tip":"<strong>Prática:</strong> só leve pra renda variável o dinheiro que você não vai precisar tão cedo. O de curto prazo fica no seguro."},
      {"ic":"key","t":"Risco × Retorno","emph":"Risco","b":"Existe uma lei que não falha: retorno alto vem com risco alto, sempre. Quem te promete ganho gigante e garantido está te aplicando um golpe — não existe almoço grátis. <strong>Reserva de emergência líquida é o que te impede de vender no pânico e transformar uma queda passageira em prejuízo de verdade</strong>.","tip":"<strong>Sinal de alerta:</strong> entrar na bolsa sem reserva montada não é ser ousado, é apostar — e aposta a casa sempre ganha.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Renda fixa é base e previsibilidade; renda variável é crescimento e risco.","Seu perfil depende de duas coisas: tolerância ao risco E prazo do dinheiro.","Comece pela base segura; só vá pra variável com reserva e tempo de sobra."]},

 {"slug":"ch06-juros-compostos-comecar-cedo","sub":"CAPÍTULO 6: Juros Compostos e Começar Cedo",
  "intro":"O ingrediente mais poderoso da riqueza não é dinheiro, é tempo agindo sobre os juros compostos. Começar cedo com pouco vence começar tarde com muito — e tempo é a única coisa que você não consegue comprar depois.",
  "cards":[
      {"ic":"spiral","t":"Juro sobre Juro","emph":"Juro sobre Juro","b":"O segredo dos juros compostos é que o rendimento também rende. O dinheiro que você ganhou ano passado trabalha junto com o seu ano que vem. A curva fica chata por muito tempo e depois dispara; <strong>quem desiste no trecho chato, achando que não está funcionando, sai do jogo bem antes da parte boa começar</strong>.","tip":"<strong>Regra:</strong> não saque os rendimentos. Reinvestir os juros e os dividendos é o que faz a bola de neve crescer de verdade."},
      {"ic":"clock","t":"Tempo Vale Mais que Valor","emph":"Tempo","b":"Cada ano que você adia o primeiro aporte custa caro lá na frente. Começar com R$ 100 hoje rende mais do que começar com R$ 10.000 daqui a dez anos. <strong>O tempo é o único ativo que não dá pra recuperar — e é justamente o mais barato pra quem está começando agora</strong>.","tip":"<strong>Modelo mental:</strong> a bola de neve não precisa começar grande. Precisa de uma ladeira longa pra rolar — e a ladeira é o tempo."},
      {"ic":"steps","t":"Aporte Todo Mês","emph":"Aporte","b":"Largue a fantasia do 'momento certo' pra entrar. O hábito de investir um valor fixo todo mês, chova ou faça sol, ganha de qualquer gênio do timing. <strong>Esperar 'juntar uma graninha' pra começar é a desculpa mais cara do mundo — você perde justo os primeiros anos, que são os que mais valem</strong>.","tip":"<strong>Sinal de alerta:</strong> ficar checando o saldo e sacar no primeiro susto mata a curva bem na hora em que ela ia decolar.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Os juros compostos transformam tempo em patrimônio — de forma exponencial.","Comece agora; o tempo que você perde não volta mais.","Aporte recorrente e reinvestimento dos rendimentos são o motor de tudo."]},

 {"slug":"ch07-diversificacao-erro-da-poupanca","sub":"CAPÍTULO 7: Diversificação e o Erro da Poupança",
  "intro":"Dois pontos fecham o pilar Investir Melhor: diversificar pra reduzir o risco sem abrir mão de retorno, e tirar o dinheiro da poupança — que costuma render menos que a inflação e te empobrece sem você perceber.",
  "cards":[
      {"ic":"cards","t":"Não Ponha Tudo numa Coisa Só","emph":"Tudo numa Coisa Só","b":"Jogar todo o seu dinheiro num único investimento é apostar a vida numa carta. Espalhar entre coisas que não sobem e descem ao mesmo tempo protege você sem matar o seu ganho. <strong>Quem diversifica bem não tenta adivinhar a próxima crise — só monta uma carteira que não afunda inteira quando uma parte vai mal</strong>.","tip":"<strong>Prática:</strong> diversificar não é encher a carteira de coisa que você não entende. É distribuir entre bons ativos de tipos diferentes."},
      {"ic":"wave","t":"O Erro da Poupança","emph":"Erro","b":"A poupança parece segura, mas ela tem um vazamento silencioso: rende menos que a inflação. Mês a mês, o seu dinheiro lá dentro compra menos coisa. <strong>Existem aplicações tão tranquilas quanto a poupança, e até mais seguras, que rendem o dobro — deixar na caderneta é escolher perder por comodismo</strong>.","tip":"<strong>Modelo mental:</strong> dinheiro parado na poupança não está protegido, está derretendo devagar. Você só não vê porque o número não cai."},
      {"ic":"lens","t":"Ganho Real, Não o do Extrato","emph":"Ganho Real","b":"O número bonito do extrato pode estar mentindo pra você. Se o seu dinheiro rendeu 6% e a inflação foi 5%, você ganhou 1% de verdade — o resto foi só repor o que o tempo comeu. <strong>O único placar que importa é o ganho real: quanto a mais o seu dinheiro compra hoje do que comprava antes</strong>.","tip":"<strong>Sinal de alerta:</strong> comemorar o saldo crescer enquanto o mercado fica mais caro é se enganar com número de fachada.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["A poupança costuma perder pra inflação — não é destino de quem quer crescer.","Diversifique entre tipos, prazos e emissores pra diluir o risco.","O que conta é o ganho real (acima da inflação), não o número do extrato."]},

 {"slug":"ch08-ganhar-mais-investir-em-si","sub":"CAPÍTULO 8: Ganhar Mais — A Maior Alavanca",
  "intro":"O terceiro pilar é o mais forte de todos, e é justo o que quase ninguém trabalha. Gasto tem fundo: zero. Renda não tem teto. A maior alavanca da riqueza é aumentar quanto você ganha — e o melhor investimento pra isso é você mesmo.",
  "cards":[
      {"ic":"mountain","t":"Renda Não Tem Teto","emph":"Teto","b":"Economizar é bom, mas tem limite: por mais que você aperte, não dá pra gastar menos que zero. Já o quanto você pode ganhar não tem teto nenhum. <strong>Passar a vida só tapando furos no orçamento é jogar pequeno num jogo que aceita aposta grande — você se esgota e mal sai do lugar</strong>.","tip":"<strong>Modelo mental:</strong> quando você é novo, gastar dinheiro pra aprender e ficar melhor no que faz vale muito mais que juntar moeda no cofre."},
      {"ic":"bulb","t":"Invista em Você Mesmo","emph":"Você Mesmo","b":"O investimento que mais rende não é ação gringa nem cripto da moda — é você. Sua habilidade, seu conhecimento e a sua rede de contatos são a máquina que gera toda a sua renda. <strong>Cortar curso, livro e formação pra economizar uns trocados é serrar o galho onde você está sentado</strong>.","tip":"<strong>Como aplicar:</strong> reserve uma fatia fixa do seu orçamento pra investir em conhecimento e em quem pode te abrir portas."},
      {"ic":"spiral","t":"Renda Ativa Vira Renda Passiva","emph":"Renda Passiva","b":"Hoje você troca tempo por dinheiro — trabalha e recebe. A virada é pegar essa sobra e jogar nos investimentos, que passam a gerar dinheiro mesmo enquanto você dorme. <strong>O dia em que essa renda passiva paga as suas contas, você deixa de trabalhar por obrigação e passa a trabalhar por escolha</strong>.","tip":"<strong>Sinal de alerta:</strong> aumentar o salário só pra inflar o padrão de vida é correr na esteira: muito esforço, e o milhão nunca chega.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Ganhar mais é a alavanca mais poderosa — renda não tem teto.","Invista em você mesmo: o capital humano é o ativo de maior retorno.","Transforme renda ativa em ativos que geram renda passiva."]},

 {"slug":"ch09-primeiro-milhao-liberdade-financeira","sub":"CAPÍTULO 9: O Primeiro Milhão e a Liberdade Financeira",
  "intro":"Aqui os três pilares viram um número só. O primeiro milhão não é sorte, é meta com data e cálculo. E liberdade financeira não é ostentação — é o dia em que a renda dos seus investimentos paga as suas contas e trabalhar vira escolha, não obrigação.",
  "cards":[
      {"ic":"target","t":"O Milhão é uma Meta com Conta","emph":"Conta","b":"Sete dígitos não caem no colo de ninguém. O milhão é o resultado de uma conta simples repetida por anos: quanto você aporta, vezes a taxa de retorno, vezes o tempo. <strong>Coloque o número numa planilha, descubra quanto precisa guardar por mês pra chegar lá, e transforme um sonho vago em alvo com prazo</strong>.","tip":"<strong>Prática:</strong> calcule o aporte mensal que, na taxa média de retorno, te leva à sua meta. Revisite a conta uma vez por ano."},
      {"ic":"leaf","t":"Liberdade Financeira","emph":"Liberdade","b":"Liberdade financeira é bater o número em que a renda dos seus investimentos cobre o seu custo de vida pra sempre. E tem um atalho que ninguém conta: segurar o padrão de vida aproxima essa data tanto quanto ganhar mais. <strong>Liberdade não é ter um carro caro na garagem — é ter a manhã livre pra escolher o que fazer com ela</strong>.","tip":"<strong>Modelo mental:</strong> cada luxo supérfluo que você assume hoje empurra a sua liberdade pra mais longe. Conforto cobra juros no seu tempo."},
      {"ic":"clock","t":"Constância é o Motor","emph":"Constância","b":"Ninguém fica rico de verdade do dia pra noite e continua rico. Quem enriquece de repente, sem base, costuma quebrar do mesmo jeito. O milhão é construído na chatice: aporte após aporte, mês após mês. <strong>A constância vence o talento, vence a sorte e vence o golpe de gênio — porque ela aparece todo dia, e eles não</strong>.","tip":"<strong>Armadilha:</strong> torrar toda a renda do momento pra inflar o status hoje é rasgar o mapa que te levaria à liberdade amanhã.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["O primeiro milhão é meta com conta (aporte × tempo × retorno), não sorte.","Liberdade financeira = renda passiva cobrindo o seu custo de vida.","Os três pilares juntos, com tempo e constância, entregam o resultado."]},
]
