# -*- coding: utf-8 -*-
"""emph curado por card (trecho literal do título → itálico verde) p/ enriquecer.py.
Cada lista segue a ORDEM dos cards do capítulo no _data.py. '' = sem emph (título limpo)."""

EMPH = {
 "admiravel-mundo-novo": {
  "ch01-estado-mundial-divisa": ["Estabilidade", "Lema Invertido", "Avesso"],
  "ch02-fabricacao-castas": ["Fábrica", "Desejada", "Destino Sem Escolha"],
  "ch03-condicionamento-hipnopedia": ["Neopavloviano", "Slogan", "Implantada"],
  "ch04-soma-felicidade-quimica": ["Algema", "Anestesia", "Preço Político"],
  "ch05-consumismo-tabu-solidao": ["Dever Cívico", "Todo Mundo Pertence a Todo Mundo", "Interioridade"],
  "ch06-bernard-lenina-desajuste": ["Inadaptação", "Duas Rebeldias", "Produto Perfeito"],
  "ch07-reserva-selvagem-john": ["Olhar de Fora", "Contramotivo", "Paraíso"],
  "ch08-debate-mond-john-fim": ["Grande Troca", "Direito de Ser Infeliz", "Fim Trágico"],
 },
 "coesao-coerencia": {
  "ch01-textualidade": ["7 critérios", "Ocorrência", "textualidade"],
  "ch02-coesao-referencia": ["", "elipse", "ambíguo"],
  "ch03-coesao-conjuncao-lexical": ["Conjunção", "lexical", "errado ou demais"],
  "ch04-coerencia": ["inferência", "frames e scripts", "Salto lógico"],
  "ch05-intencionalidade-aceitabilidade": ["", "", "destinatário"],
  "ch06-informatividade": ["três ordens", "motivada", "denso demais"],
  "ch07-situacionalidade": ["metade do texto", "gerenciar", "suporte"],
  "ch08-intertextualidade": ["depende de textos", "contrato prévio", "alusão obscura"],
  "ch09-principios-regulativos": ["Adequação", "Otimizar", "fluência"],
 },
 "escute": {
  "ch01-habilidade-perdida": ["Músculo", "Hiperconexão", "Assimetria"],
  "ch02-paradoxo-da-familiaridade": ["Familiaridade", "Congelada", "Completar Frases"],
  "ch03-deslocamento-e-apoio": ["Deslocamento", "Apoio", "Egoísmo"],
  "ch04-compreender-nao-responder": ["Compreender", "Sim, e…", "a Emoção"],
  "ch05-ruido-e-tecnologia": ["Conversa Degradada", "", "Mito"],
  "ch06-curiosidade-genuina": ["Genuína", "Qual a Coisa Mais", "Capciosa"],
  "ch07-silencio-e-pausas": ["Ferramenta", "Horror", ""],
  "ch08-lacuna-fala-pensamento": ["Lacuna Fala-Pensamento", "Voz Interior", "Vilão"],
  "ch09-solidao-e-polarizacao": ["Déficit de Escuta", "Recusa de Escutar", "Discordante"],
 },
 "insustentavel-leveza-do-ser": {
  "ch01-leveza-peso-eterno-retorno": ["Peso Máximo", "Einmal ist Keinmal", "Paradoxo"],
  "ch02-parte1-leveza-e-peso": ["Seis Acasos", "Armadilha", "Es Muss Sein"],
  "ch03-parte2-alma-e-corpo": ["Dualismo", "Espelho e a Alma", "Vertigem"],
  "ch04-parte3-palavras-incompreendidas": ["Palavras Mal-Entendidas", "Traição", "Sentido Que Se Move"],
  "ch05-parte4-alma-e-corpo": ["Não É Transferível", "Sob Vigilância", "Igualdade Forçada"],
  "ch06-parte5-leveza-e-peso": ["Édipo", "Recusada", "Queda"],
  "ch07-parte6-a-grande-marcha": ["Segunda Lágrima", "Ditadura do Coração", "Universal"],
  "ch08-parte7-o-sorriso-de-karenin": ["Tempo Circular", "Habitável", "Sem Biombo"],
  "ch09-narrador-estrutura-simbolos": ["Que Pensa", "Polifonia", "Não-Resolução"],
 },
 "milionario-mora-ao-lado": {
  "ch01-conheca-o-milionario": ["Invisível", "Riqueza", "Riqueza Esperada", "7 Fatores"],
  "ch02-frugal-frugal-frugal": ["", "Defesa", "Orçar"],
  "ch03-tempo-energia-dinheiro": ["Eficiente", "Planejar", "Pague-se Primeiro"],
  "ch04-voce-nao-e-o-que-dirige": ["Teste do Carro", "Conspícuo", "Valor, Não Marca"],
  "ch05-assistencia-economica-externa": ["Econômica Externa", "Veneno do Subsídio", "Melhor Presente"],
  "ch06-acao-afirmativa-em-familia": ["Ação Afirmativa", "Autossuficientes", "Veneno"],
  "ch07-ache-seu-nicho": ["Nicho", "aos Ricos", "EOC do Mercado"],
  "ch08-empregos-milionarios-x-herdeiros": ["Autofeitos", "Autônomos", "Vocação Certa"],
 },
 "arte-da-seducao": {
  "ch01-seducao-como-poder": ["Atração", "Carência", "Naturalidade"],
  "ch02-tipos-sedutor-1": ["Sereia e Libertino", "Dândi", "Erro"],
  "ch03-tipos-sedutor-2": ["Coquete", "Carismático", "Tela de Projeção"],
  "ch04-anti-sedutor-vitimas": ["Anti-Sedutor", "Carência da Vítima", "Próprio Perfil"],
  "ch05-fase1-separar": ["Indireta", "Quente e Frio", "Carência"],
  "ch06-fase2-penetrar": ["Espelhe e Isole", "Insinuação", "Prazer e Dor"],
  "ch07-fase3-precipitar": ["Inesperado", "Estratégica", "Cronometrada"],
  "ch08-fase4-o-tombo": ["Regressão", "Golpe Final", "Anticlímax"],
  "ch09-lente-analitica": ["Dinâmica", "Marketing, Política e Liderança", "Ético"],
 },
 "conversas-cruciais": {
  "ch01-conversa-crucial": ["3 Condições", "3 Saídas", "Sequestro"],
  "ch02-pool-de-significado": ["Significado Comum", "Coração", "Escolha do Tolo"],
  "ch04-aprender-a-observar": ["Visão Dupla", "Silêncio × Violência", "sob Estresse"],
  "ch05-tornar-seguro": ["Respeito Mútuos", "Contraste", "CRIB"],
  "ch06-dominar-historias": ["Caminho para a Ação", "3 Histórias Espertas", "Questões Espertas"],
  "ch07-state": ["STATE", "Fatos Primeiro", "Humildade"],
  "ch08-ampp": ["AMPP", "ABC", "Genuína"],
  "ch09-passar-a-acao": ["4 Métodos de Decisão", "WWWF", "Diálogo"],
 },
 "futebol-brasileiro": {
  "ch01-origem-aristocratica": ["Casaca", "Amadorismo", "Várzea"],
  "ch02-barreira-racial": ["Pó de Arroz", "Duas Terras", "Costurado"],
  "ch03-ruptura-vasco": ["Cruzmaltino", "Letrada", "Recusa Histórica"],
  "ch04-friedenreich": ["Disparo e o Mar", "Silenciada", "Pêndulo"],
  "ch05-profissionalizacao": ["Luvas de Prata"],
  "ch06-futebol-arte": ["Ginga", "Beleza como Fim", "Mestiçagem"],
  "ch07-maracanazo": ["1950", "Vira-Lata", "Combustível"],
  "ch08-tri-pele": ["o Bi", "Time Perfeito", "País do Futebol"],
  "ch09-1982-tetra-penta": ["Beleza que Perdeu", "Tetra", "Penta"],
  "ch10-7x1-legado": ["Mineiraço", "Democracia Racial", "como Brasil"],
 },
 "habitos-atomicos": {
  "ch01-1porcento-sistemas": ["Juros Compostos", "Sistemas > Metas", "Potencial Latente"],
  "ch02-identidade": ["Três Níveis", "Voto", "Aprisiona"],
  "ch03-loop-do-habito": ["Quatro Estágios", "Não Deseja o Hábito", "Problema vs. Solução"],
  "ch04-lei1-obvio": ["Pontuação e Intenção", "Empilhamento", "Ambiente Vence a Vontade"],
  "ch05-lei2-atraente": ["Agrupamento de Tentação", "Normas do Grupo", "Reformule"],
  "ch06-lei3-facil": ["Menor Esforço", "2 Minutos", "Automação"],
  "ch07-lei4-satisfatorio": ["Imediata", "Rastreador", "Duas Vezes"],
  "ch08-avancado": ["Jogo Certo", "Lado Sombrio", "Revisão e Reflexão"],
 },
 "hora-da-estrela": {
  "ch01-rodrigo-metalinguagem": ["Culpada", "Máscara Masculina", "Em Ruínas"],
  "ch02-macabea-invisivel": ["Excluída", "Quebradas", "Sem Raiva"],
  "ch03-pobreza-alteridade": ["Abismo Suado", "Covarde", "No Esgoto"],
  "ch04-linguagem-silencio-instante": ["Ruído Da Rádio", "Sangue Do Agora", "Sintaxe Suada"],
  "ch05-olimpico-gloria-desejo": ["Irônicos", "Predação", "Glória"],
  "ch06-madame-carlota-epifania": ["Armadilha", "Ironia Trágica", "Charlatã ou Destino?"],
  "ch07-hora-da-estrela-morte": ["Protagonismo", "Existência × Essência", "Morre com Ela"],
  "ch08-estrutura-simbolos-recursos": ["Paratexto", "Brilho Letal", "Três ao Mesmo Tempo"],
 },
 "investidor-inteligente": {
  "ch01-investidor-vs-especulador": ["Tríplice", "Defensivo e o Empreendedor", "Limitada"],
  "ch02-inflacao": ["Retorno Real", "Escudo Furado", "Diversificada"],
  "ch03-historico-do-mercado": ["Preço Acima de Tudo", "Gravidade Impiedosa", "Medo e a Fome"],
  "ch04-investidor-defensivo": ["Engrenagens", "Gotejador Mecânico", "Catedrais Antigas"],
  "ch05-investidor-empreendedor": ["Pechinchas", "Net-Nets", "Esforço e Método"],
  "ch06-preco-vs-valor": ["Preço ≠ Valor", "Votar e Pesar", "Bússola Racional"],
  "ch07-sr-mercado": ["Servo, Não Oráculo", "Volatilidade Amiga", "Corrente Emocional"],
  "ch08-margem-de-seguranca": ["Colchão Antimorte", "Absolvição do Erro", "Escudo do Batalhão"],
  "ch09-temperamento-e-disciplina": ["Caráter Esmaga o QI", "Algemas Racionais", "Triunfo da Espera"],
  "ch10-analise-de-empresas": ["Filtro Contábil", "Teto de Múltiplos", "Muralha contra Juros"],
 },
 "mais-esperto-que-o-diabo": {
  "ch01-a-entrevista-alegorica": ["Alegoria", "Outro Eu", "98% × 2%"],
  "ch02-a-deriva": ["Barco sem Leme", "Não-Derivante", "Indecisão"],
  "ch03-as-armas-do-diabo": ["Seis Medos", "Corrente do Medo", "Esperar o Medo Passar"],
  "ch04-o-hipnotismo-ritmico": ["Lei Cósmica", "Ritmo Novo", "Negligente"],
  "ch05-definicao-de-proposito": ["Alvo Único", "Mente Fechada", "sem Agir"],
  "ch06-mente-dominante-autocontrole": ["Única Coisa Sua", "Reação vs. Resposta", "Curar o Ambiente"],
  "ch07-o-tempo-e-a-adversidade": ["Juros Compostos", "Semente de Benefício", "Sabedoria vs. Idade"],
  "ch08-sistemas-que-produzem-derivantes": ["Fábricas de Hábitos", "Educar vs. Condicionar", "sem Ser Configurado"],
  "ch09-os-sete-principios-da-libertacao": ["Sete Pinos", "Harmonia e Cautela", "Não Menu"],
 },
 "nao-me-faca-pensar": {
  "ch01-nao-me-faca-pensar": ["Regra Zero", "Desatento", "Metáfora"],
  "ch02-como-usamos-a-web": ["Escaneamos", "Satisficing", "Muddling Through"],
  "ch03-design-escaneabilidade": ["Billboard 101", "Convenções", "Ruído"],
  "ch04-omita-palavras": ["Corte pela Metade", "Happy Talk", "Sintoma"],
  "ch05-navegacao-persistente": ["Billboard de Navegação", "Você Está Aqui", "Logo"],
  "ch06-teste-do-tronco": ["Trunk Test", "Porta de Entrada", "Sem Título"],
  "ch07-pagina-inicial": ["Question", "Home Equilibra", "Home Perfeita"],
  "ch08-teste-de-usabilidade": ["Teste Barato", "Usuário Médio", "Achar, não para Provar"],
  "ch09-boa-vontade": ["Tanque Finito", "ESVAZIA", "REABASTECE"],
  "ch10-acessibilidade-mobile": ["Usabilidade Estendida", "Stress Test", "Aprendabilidade"],
 },
 "noites-brancas": {
  "ch01-noite-primeira-encontro": ["Cais das Ilusões", "Tempo Suspenso", "Pacto com a Dor"],
  "ch02-noite-segunda-o-sonhador": ["Submerso", "Preço da Imagem", "Revolta"],
  "ch03-noite-terceira-historia-nastienka": ["Espelho Trincado", "Moeda da Espera", "Egoísta"],
  "ch04-noite-quarta-virada": ["Peripécia", "Instante de Felicidade", "mas Verdade"],
  "ch05-a-manha-generosidade": ["Radical", "Frase-Síntese", "Circular"],
  "ch06-sonho-realidade-solidao": ["Eixo Filosófico", "Idealização", "Diagnóstico Social"],
  "ch07-estrutura-simbolos-recursos": ["4 + 1", "Oposição", "Sincero e Irônico"],
 },
 "o-idiota": {
  "ch01-chegada-michkin-sociedade": ["Candura", "Duplos", "o Recebe"],
  "ch02-noite-nastassia-o-fogo": ["Fogo dos 100 Mil", "Beleza Ferida × Beleza Viva", "Compra × Compaixão"],
  "ch03-rogojin-faca-holbein": ["Cristo de Holbein", "Os Duplos", "Prenúncio"],
  "ch04-epilepsia-extase": ["Instante Eterno", "Graça e Doença", "Diagnóstico Moral"],
  "ch05-beleza-salvara-mundo-compaixao": ["Ambiguidade", "A Revolta Diante da Morte", "Autodestruição"],
  "ch06-aglaia-nastassia-confronto": ["Escolha Impossível", "Orgulho Que Pode Viver", "Indecisão"],
  "ch07-casamento-assassinato-desfecho": ["Posse Levada ao Fim", "Vigília", "Circularidade"],
  "ch08-personagens-sistema": ["Quadrângulo", "Figuras Crísticas", "A Voz da Revolta"],
  "ch09-simbolos-estrutura-tese": ["A Tese em Imagens", "4 Partes", "Tese Aberta"],
 },
 "pequeno-principe": {
  "ch01-o-chapeu-e-as-pessoas-grandes": ["Chapéu ou a Jiboia?", "Pessoas Grandes", "Carneiro na Caixa"],
  "ch02-o-planeta-do-principe-e-a-rosa": ["Rosa", "Baobás", "Vulcões e Cuidado"],
  "ch03-os-seis-planetas-e-as-pessoas-grandes": ["Galeria dos Adultos", "Acendedor de Lampiões", "Para Quê?"],
  "ch04-a-terra-a-serpente-e-o-jardim-de-rosas": ["Serpente", "Cinco Mil Rosas", "em Meio à Multidão"],
  "ch05-a-raposa-e-o-segredo-de-cativar": ["Criar Laços", "Trigo Dourado", "Segredo"],
  "ch06-o-poco-e-o-essencial-invisivel": ["Água Como Presente", "Estrelas e a Flor", "Amizade Consolidada"],
  "ch07-a-partida-as-estrelas-que-riem": ["Responsável pela Rosa", "Estrelas que Riem", "História Aberta"],
 },
 "poder-do-habito": {
  "ch01-o-loop-do-habito": ["Piloto Automático", "Anatomia do Ciclo", "Deixa Oculta"],
  "ch02-o-cerebro-ansioso": ["Desejo Antecipado", "Fricção do Creme", "Ansiedade"],
  "ch03-a-regra-de-ouro": ["Trocar a Rotina", "Recompensa", "Crença e Comunidade"],
  "ch04-habitos-angulares": ["Alavanca Mestra", "Pequenas Vitórias", "Contamina"],
  "ch05-forca-de-vontade": ["Músculo", "Autonomia", "Ponto de Crise"],
  "ch06-habitos-das-organizacoes": ["Trégua", "Oportunidade", "Rhode Island"],
  "ch07-habitos-do-consumidor": ["Familiaridade", "Predição por Dados", "Mudança de Vida"],
  "ch08-habitos-da-sociedade": ["Laços Fortes", "Laços Fracos", "Fazem Durar"],
  "ch09-neurologia-do-livre-arbitrio": ["pós-Consciência", "Quase-Acerto", "4 Passos"],
 },
 "psicopolitica": {
  "ch01-crise-da-liberdade": ["Empreendedor de Si Mesmo", "Coação à Liberdade", "Sempre Incompleto"],
  "ch02-smart-power": ["Seduz, não Reprime", "Like", "Permissividade"],
  "ch03-emocionalizacao": ["Força Produtiva", "Autenticidade", "Emoção vs. Sentimento vs. Razão"],
  "ch04-dataismo": ["Saber sem Sentido", "Fim da Pessoa", "a Guinada"],
  "ch05-transparencia-panoptico": ["Transparência", "Voluntário", "Amável"],
  "ch06-idiotismo": ["Coragem do Não", "Potência do Não", "Enxame Digital"],
 },
 "quem-pensa-enriquece": {
  "ch01-desejo": ["6 Passos", "Ardente vs. Desejo Morno", "Queimar as Pontes"],
  "ch02-fe-autossugestao": ["Estado Induzido", "Dirigida", "Cultiva Medo"],
  "ch03-imaginacao-planejamento": ["Sintética vs. Criativa", "Não a Meta", "Consentimento"],
  "ch04-decisao-persistencia": ["Rápido, Mudar Devagar", "4 Bases", "Um Passo do Ouro"],
  "ch05-mastermind": ["Terceira Mente", "Duas Naturezas", "sem Harmonia"],
  "ch06-subconsciente-cerebro": ["Transmutação", "Sempre Ativo", "como Rádio"],
  "ch07-medos-sexto-sentido": ["6 Fantasmas", "Indecisão → Dúvida → Medo", "Gabinete Invisível"],
 },
 "realismo-capitalista": {
  "ch01-fim-do-mundo": ["Não Há Alternativa", "Esterilidade", "Subsunção Real"],
  "ch02-precorporacao": ["", "", "Gestual"],
  "ch03-os-tres-reais": ["Três Reais", "Privatização do Estresse", "Negação"],
  "ch04-impotencia-reflexiva": ["Cinismo Informado", "Interatividade", "Engrenagem Da Culpa"],
  "ch05-stalinismo-de-mercado": ["Pós-Fordismo", "Stalinismo de Mercado", "Ontologia Empresarial"],
  "ch06-dreamwork-central-de-trocas": ["Disavowal", "Distúrbio de Memória", "Central de Trocas"],
  "ch07-supernanny-marxista": ["Supernanny Marxista", "Não é Liberdade", "Reabrir o Horizonte"],
 },
 "revolucao-dos-bichos": {
  "ch01-sonho-do-major-animalismo": ["Sonho de Major", "Bichos da Inglaterra", "Inimigo"],
  "ch02-rebeliao-sete-mandamentos": ["Acaso", "Religião de Papel", "Balde Sumido"],
  "ch03-trabalho-leite-privilegio": ["Trabalharei Mais", "Leite e as Maçãs", "Retórica de Garganta"],
  "ch04-batalha-do-estabulo": ["Mito Fundador", "Bola-de-Neve", "Sansão"],
  "ch05-cisao-napoleao-bola-de-neve": ["Ideia × Força", "Nove Cães", "Roubo da Ideia"],
  "ch06-moinho-reescrita-mandamentos": ["Reescrita da Lei", "Contra a Evidência", "Comércio com o Inimigo"],
  "ch07-fome-expurgos-confissoes": ["Expurgos", "Bode Expiatório", "Sem Motivo"],
  "ch08-culto-batalha-do-moinho": ["Culto à Personalidade", "Derrota Vendida como Vitória", "Em Excesso"],
  "ch09-sansao-final-mais-iguais": ["Carroça do Açougueiro", "Mais Iguais que os Outros", "Porcos = Humanos"],
 },
 "sete-saberes": {
  "ch01-cegueiras-do-conhecimento": ["Estrutural", "Racionalidade × Racionalização", "Paradigma Invisível"],
  "ch02-conhecimento-pertinente": ["Saber Pertinente", "Inteligência Geral", "Disjunção e Redução"],
  "ch03-condicao-humana": ["Unitas Multiplex", "Tríade Recursiva", "Homo Complexus"],
  "ch04-identidade-terrena": ["Terra-Pátria", "Comunidade de Destino", "Face Dupla"],
  "ch05-enfrentar-as-incertezas": ["Ecologia da Ação", "Estratégia × Programa", "Aposta Consciente"],
  "ch06-ensinar-a-compreensao": ["Compreender × Explicar", "Obstáculos", "Ética da Compreensão"],
  "ch07-antropoetica": ["Tríade Ética", "Dialógica", "Cidadania Terrena"],
 },
 "startup-enxuta": {
  "ch01-comecar": ["uma Startup", "É Gestão", "Cinco Raízes"],
  "ch02-definir": ["Como Cargo", "Porto Seguro", "Portfólio"],
  "ch03-aprender": ["Validado", "Duas Perguntas", "IMVU"],
  "ch04-experimentar": ["Duas Hipóteses", "Experimento", "Zappos"],
  "ch05-saltar": ["Salto de Fé", "Genchi Gembutsu", "Analogias e Antílogos"],
  "ch06-testar": ["Mínimo Viável", "Dropbox", "Mágico de Oz"],
  "ch07-medir": ["Contabilidade da Inovação", "× de Vaidade", "Teste A/B"],
  "ch08-pivotar-ou-perseverar": ["Pivô", "Catálogo de Pivôs", "Nº de Pivôs"],
  "ch09-lotes": ["Lotes Pequenos", "Cordão Andon", "Não Empurrar"],
  "ch10-crescer": ["Recorrente", "Viral", "Pago"],
  "ch11-adaptar": ["5 Porquês", "Proporcional", "Não a Pessoa"],
  "ch12-inovar": ["Três Requisitos", "Sandbox", "Portfólio"],
  "ch13-epilogo-nao-desperdice": ["Desperdício", "Produtividade Real", "Honestidade Científica"],
  "ch14-juntar-se-ao-movimento": ["Como Cultura", "Não Receitas", "Longo Prazo"],
 },
 "trabalhe-4-horas": {
  "ch01-novos-ricos-eficacia": ["Novos Ricos", "O-Q-Q", "Relativa × Absoluta", "Eficácia"],
  "ch02-definicao-regras-do-jogo": ["Hipótese Adiada", "Cilada", "Tédio × Felicidade"],
  "ch03-definicao-medo-dreamlining": ["Fear-setting", "Custo da Inação", "", "Renda-Alvo"],
  "ch04-eliminacao-pareto-parkinson": ["Pareto", "Parkinson", "Baixa Informação", "Combinação Mágica"],
  "ch05-automacao-musa-terceirizacao": ["Musa", "Microteste", "Terceirização", "Não-Decidir"],
  "ch06-libertacao-remoto-mini-aposentadorias": ["Fuga do Escritório", "", "antes de Libertar"],
  "ch07-preencher-o-vacuo": ["Vácuo", "Dão Sentido", "Aprender & Servir", "Erros dos NR"],
 },
 "trabalho-focado": {
  "ch01-o-trabalho-profundo-e-valioso": ["2 Habilidades", "Forja", "Conta do Tempo", "Sobra na Mente"],
  "ch02-o-trabalho-profundo-e-raro": ["Peso Invisível", "Covarde", "Teatro Produtivo", "Culto da Ferramenta"],
  "ch03-o-trabalho-profundo-e-significativo": ["Pinta a Casa", "Dança do Ar"],
  "ch04-regra-1-trabalhe-profundamente": ["4 Ritmos", "Ritualizar", "4DX", "Fim de Expediente"],
  "ch05-regra-2-abrace-o-tedio": ["Agende a Internet", "sob Pressão", "Meditação Produtiva"],
  "ch06-regra-3-abandone-as-redes-sociais": ["Artesão", "Poucos Vitais", "30 Dias"],
  "ch07-regra-4-drene-o-raso": ["Cada Minuto", "Orçamento de Raso", "Agenda Fixa"],
 },
}
