# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'Essencialismo: A Disciplinada
Busca por Menos' (Greg McKeown — Essentialism: The Disciplined Pursuit of Less).
Frameworks canônicos: 'menos, porém melhor'; a essência (a escolha, discernir o
vital trivial, o trade-off — 'o que vou renunciar?'); Essencialista vs.
Não-essencialista; o método EXPLORAR (espaço/escapar, observar/ouvir o sinal,
brincar, dormir, critério 90% / seleção extrema) → ELIMINAR (clarear o propósito
essencial, o 'não' gracioso, descomprometer-se / sunk cost, editar, limites) →
EXECUTAR (buffer/folga, remover o gargalo, pequenas vitórias, rotina, foco no
agora/fluxo); a vida do essencialista. Base: síntese dos frameworks amplamente
documentados — não reproduz o texto."""

BOOK = {
 "title": "Essencialismo",
 "author": "Greg McKeown",
 "header_light": "ESSENCIA",
 "header_bold": "LISMO",
 "subtitle": "VISÃO GERAL · A DISCIPLINADA BUSCA POR MENOS",
 "intro": "Pare de perguntar 'como dou conta de tudo?'. A pergunta do Essencialista é outra, e mais difícil: 'o que é absolutamente essencial?'. McKeown não promete fazer mais em menos tempo — promete o contrário: fazer menos, mas com inteireza. É a disciplina de separar o vital de poucos do trivial de muitos, dizer 'não' ao resto sem culpa e blindar com folga o que importa. Quase tudo é ruído; o ofício é escolher o sinal. Menos, porém melhor.",
 "description": "Um manifesto contra a vida espalhada — a agenda lotada que avança em todas as direções e em nenhuma. O Não-essencialista diz sim por pressão e termina exausto e disperso; o Essencialista entende que cada 'sim' é um 'não' a outra coisa, e prefere escolher esse 'não' de propósito. McKeown destila a disciplina em três movimentos: EXPLORAR para discernir o que conta, ELIMINAR o que não conta e EXECUTAR sem esforço heroico. Recusar o bom é o preço do excelente — e desse corte nascem clareza, controle e a alegria de viver o que de fato importa.",
 "tags": ["Produtividade", "Foco", "Prioridades"],
 "progress": "12 Capítulos",
 "cover": "assets/essencialismo-cover.png",
 "overview_cards": [
   {"ic":"scale","t":"A Essência: Escolha · Discernir · Trade-off","b":"Três verdades sustentam todo o resto. <strong>A escolha</strong>: tiram suas opções, mas nunca o poder de escolher entre elas — 'não posso' quase sempre é 'eu escolho não'. <strong>O discernimento</strong>: quase tudo é ruído, pouquíssimo é sinal; passado certo ponto, mais esforço não vira mais resultado. <strong>O trade-off</strong>: não dá para fazer tudo, então a pergunta deixa de ser 'como faço as duas?' e vira <strong>'o que vou renunciar?'</strong>.","tip":"<strong>Modelo mental:</strong> antes de todo 'sim', nomeie o 'não' embutido nele. Fingir que não há custo só entrega a escolha ao acaso.","wide":True},
   {"ic":"steps","t":"O Método: Explorar → Eliminar → Executar","b":"<strong>EXPLORAR</strong> para discernir: crie espaço, observe o sinal, durma, brinque e aplique o <strong>critério 90%</strong>. <strong>ELIMINAR</strong> para cortar: clareie um propósito, ofereça o 'não' gracioso, descomprometa-se, edite a vida e ponha limites. <strong>EXECUTAR</strong> para facilitar: construa folga, remova o gargalo e avance por pequenas vitórias e rotina.","tip":"<strong>Como aplicar:</strong> explore muitas opções para escolher pouquíssimas; corte o resto sem dó; só então execute o que sobreviveu.","wide":True},
   {"ic":"target","t":"Critério 90% (Seleção Extrema)","b":"A régua que torna a disciplina prática: dê a cada opção uma nota de 0 a 100 no que mais importa. Se não chega a <strong>90</strong>, é <strong>0</strong> — descarte. Recusar um sólido '8' parece desperdício; é o aluguel que se paga para a vaga ficar livre quando o '10' aparecer.","tip":"<strong>Regra:</strong> se não é um claro SIM, é um NÃO. A própria hesitação já costuma ser a resposta — acabe com a zona do 'talvez'."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-essencia-escolha","sub":"A ESSÊNCIA: A Escolha",
  "intro":"Tudo começa por uma pequena recuperação: a do poder de escolher. Podem lhe tirar as opções — nunca a capacidade de escolher entre as que restam. Quem esquece isso entrega o leme: deixa que o mais urgente e o mais barulhento decidam por ele, e depois chama de destino o que foi, o tempo todo, omissão.",
  "cards":[
      {"ic":"fork","t":"“Não Posso” é Quase Sempre “Escolho Não”","emph":"Escolho Não","b":"Arrancam suas opções; a escolha entre elas, jamais. Por isso quase todo “tenho que” esconde um <strong>“eu escolho” que você se recusa a assinar</strong>. Diga “escolho isto porque valorizo aquilo” e a caneta da sua agenda volta para a sua mão. A vítima sofre o que lhe acontece; o agente decide o que faz com isso.","tip":"<strong>Como aplicar:</strong> ouviu-se dizer “sou obrigado”? Troque por “eu escolho [X] porque [Y]”. Sem o porquê, é provável que a resposta seja não."},
      {"ic":"gap","t":"A Impotência Aprendida","emph":"Impotência Aprendida","b":"Quem deixa de exercer a escolha passa a agir <strong>como se não a tivesse</strong>. Cede a decisão à “tirania do tudo é obrigatório” e trata cada pedido como inegociável. Isso não é humildade — é abdicação. E uma vida sem timoneiro acaba escrita pela mão de quem grita mais alto.","tip":"<strong>Sinal de alerta:</strong> se a sua pauta do dia é ditada pelo que gritou mais alto, você não está escolhendo — está apenas reagindo.","warn":True},
      {"ic":"spark","t":"A Escolha É um Músculo","emph":"Músculo","b":"Não é algo que se tem; é algo que se faz — e, como todo músculo, atrofia no desuso e enrija a cada “não”. Cada recusa tira você da plateia e o põe no palco da própria vida. Treine no leve para aguentar o peso: <strong>quem recusa um café hoje aprende a recusar o projeto errado amanhã</strong>.","tip":"<strong>Modelo mental:</strong> a coragem de dizer não não cai do céu — ela se constrói, repetição por repetição, nas decisões pequenas."},
    ],
  "lessons_title":"Lições-Chave: A Escolha",
  "lessons":["A escolha de como gastar tempo e energia é sempre sua — não a terceirize ao acaso.","Troque todo 'tenho que' por 'eu escolho', e diga em voz alta o porquê.","Exercite a escolha no pequeno; é assim que ela aguenta peso no grande."]},

 {"slug":"ch02-essencia-discernir","sub":"A ESSÊNCIA: Discernir o Vital Trivial",
  "intro":"Quase tudo é trivial; pouquíssimo é vital. O Não-essencialista trata todas as opções como iguais e se afoga nelas. O Essencialista gasta tempo, antes de agir, para separar o que faz a diferença do que apenas faz volume — porque, passado certo ponto, mais esforço já não rende mais resultado.",
  "cards":[
      {"ic":"layers","t":"O Vital de Poucos × o Trivial de Muitos","emph":"Vital de Poucos","b":"A maioria das opções contribui quase nada; uma minoria contribui quase tudo. Pela lei do poder, <strong>uns 20% do esforço respondem por uns 80% do resultado</strong> — e os melhores acertos valem ordens de grandeza mais que o resto somado. A meta não é fazer muitas coisas bem; é achar a poucas coisas que rendem desproporcionalmente.","tip":"<strong>Como aplicar:</strong> em qualquer lista, isole as duas ou três opções de retorno desproporcional, congele as demais e não olhe para trás.","wide":True},
      {"ic":"eye","t":"Sinal × Ruído","emph":"Ruído","b":"Sinal é o que faz a maior contribuição; ruído é o que só disputa a sua atenção. A armadilha é a inversão sonora: o ruído grita, o sinal sussurra. <strong>Quando tudo parece igualmente importante, desconfie</strong> — importância uniforme quase nunca é a realidade, é falta de discernimento vestida de zelo.","tip":"<strong>Sinal de alerta:</strong> meça contribuição, não esforço. Movimento não é progresso, e estar ocupado não é, nem de longe, produzir o que conta.","warn":True},
      {"ic":"lens","t":"O Garimpeiro Não Carrega Cascalho","emph":"Cascalho","b":"Esforço e resultado não andam de mãos dadas: depois de certo ponto, cada hora rende menos que a anterior. O Essencialista pensa como garimpeiro — <strong>peneira toneladas de cascalho para guardar a pepita</strong> e deixa o resto no rio. Pulverizar energia por igual sobre tudo o que aparece é confundir o cascalho com o ouro.","tip":"<strong>Modelo mental:</strong> pouca coisa vale ouro; o restante é peso morto que se disfarça de trabalho. Saiba o que pesar na palma e o que devolver à água."},
    ],
  "lessons_title":"Lições-Chave: Discernir",
  "lessons":["Quase tudo é trivial; pouquíssimo é vital — o ofício é separar o sinal do ruído.","Mais esforço nem sempre dá mais resultado; persiga o retorno desproporcional.","Se tudo parece importante, o que falta é discernimento, não tempo."]},

 {"slug":"ch03-essencia-tradeoff","sub":"A ESSÊNCIA: O Trade-off",
  "intro":"Não dá para ter tudo nem fazer tudo — e tentar negar isso é a doença do Não-essencialista. Sua pergunta é 'como faço as duas coisas?'; a do Essencialista é 'o que vou renunciar?'. Encarar o trade-off de propósito é o que transforma uma escolha qualquer em estratégia.",
  "cards":[
      {"ic":"fork","t":"A Pergunta Certa: “O Que Vou Renunciar?”","emph":"O Que Vou Renunciar?","b":"“Como faço as duas coisas?” é uma armadilha: finge que o tempo é infinito e empurra o custo para debaixo do tapete. <strong>“Do que estou abrindo mão?”</strong> é a pergunta que se pode responder. Todo “sim” é um “não” a tudo o mais que ocuparia aquela hora — e não nomear esse “não” não o apaga, só entrega a decisão ao acaso.","tip":"<strong>Como aplicar:</strong> antes de aceitar um compromisso, escreva por extenso o que ele apaga da sua semana. Se o preço choca, a resposta apareceu.","wide":True},
      {"ic":"scale","t":"Estratégia É o Que Você Decide NÃO Fazer","emph":"NÃO Fazer","b":"Quem escolhe <strong>deliberadamente o que recusa</strong> ganha foco; quem tenta abraçar tudo dilui-se numa mediocridade dispersa. Estratégia não é a lista do que você fará — é o conjunto do que você descartou de propósito. O trade-off assumido vira vantagem; o trade-off negado vira só cansaço.","tip":"<strong>Modelo mental:</strong> defina o que vai recusar antes de definir o que vai abraçar. O 'não' delibera o 'sim'."},
      {"ic":"mountain","t":"“Qual Problema Eu Prefiro Ter?”","emph":"Qual Problema Eu Prefiro Ter?","b":"Todo caminho cobra seu pedágio; a rota sem custo é miragem. Em vez de fugir de uma dor que não existe, escolha de olhos abertos <strong>a dor que vale a pena</strong>. Querer “encaixar tudo” na agenda é a negação pura do trade-off — e a origem direta das semanas lotadas que não levam a lugar nenhum.","tip":"<strong>Cuidado:</strong> “dá para tudo” é a crença mais cara do Não-essencialista: ela enche a agenda e esvazia o essencial.","warn":True},
    ],
  "lessons_title":"Lições-Chave: O Trade-off",
  "lessons":["Não dá para fazer tudo: a pergunta honesta é 'o que vou renunciar?'.","Estratégia é escolher de propósito o que você NÃO vai fazer.","Todo 'sim' carrega um custo de oportunidade — torne-o visível antes de assiná-lo."]},

 {"slug":"ch04-explorar-espaco","sub":"EXPLORAR: Espaço para Pensar e Escapar",
  "intro":"Eis o paradoxo: para discernir o vital, é preciso primeiro criar espaço — escapar da rotina e do ruído para conseguir pensar. Sem folga mental, ninguém escolhe; apenas reage. O recuo não é o oposto da ação — é o que torna a ação certeira.",
  "cards":[
      {"ic":"leaf","t":"Escapar É Parte do Trabalho","emph":"Escapar","b":"Reservar tempo para pensar não é fuga do trabalho — é a fundação das decisões que importam. Bloqueie um intervalo sem telas nem agenda, de duas horas a um retiro, levando só a pergunta essencial. <strong>O Não-essencialista está ocupado demais para pensar na vida; o Essencialista cria o vazio em que a vida finalmente cabe na cabeça.</strong>","tip":"<strong>Como aplicar:</strong> trate o tempo de pensar como a reunião mais importante da semana — hora marcada, porta fechada, ninguém entra.","wide":True},
      {"ic":"bubble","t":"A Folga Mental É o Estúdio da Mente","emph":"Folga Mental","b":"A banda livre da mente é o que deixa ver as conexões e prioridades que o excesso encobre. Ideia essencial não brota na correria: <strong>ela precisa de uma sala vazia para aparecer</strong>. Sem essa folga, o cérebro nunca separa o sinal do ruído — limita-se a apagar o incêndio mais próximo, para sempre.","tip":"<strong>Modelo mental:</strong> o espaço é o estúdio da mente. Ninguém esculpe numa sala entulhada — primeiro se abre o vazio, depois se cria."},
      {"ic":"clock","t":"O Paradoxo do Ocupado","emph":"Paradoxo do Ocupado","b":"Quem mais precisa parar para pensar é justamente quem se sente <strong>sem um minuto para isso</strong>. A disponibilidade de 100% do tempo mata a reflexão e fantasia ocupação de produtividade. Sentir-se “ocupado demais para parar” não é desculpa — é o próprio diagnóstico de que parar virou urgência.","tip":"<strong>Cuidado:</strong> confundir estar sempre disponível com ser produtivo é o caminho mais curto para nunca decidir o que de fato importa.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Espaço",
  "lessons":["Agende, de propósito, tempo só para pensar — e defenda-o como defende uma reunião.","Folga mental é a condição para separar o sinal do ruído.","Quando achar que não tem tempo de parar, é exatamente a hora de parar."]},

 {"slug":"ch05-explorar-observar","sub":"EXPLORAR: Observar e Ouvir o que Importa",
  "intro":"Explorar bem é saber observar e escutar o sinal dentro do dilúvio de informação. O Essencialista vira 'jornalista da própria vida': não anota cada detalhe — caça o lide, a manchete, a essência que dá sentido a todo o resto.",
  "cards":[
      {"ic":"lens","t":"Seja o Jornalista da Própria Vida","emph":"Jornalista da Própria Vida","b":"Olhe os fatos a alguma distância e procure a <strong>manchete</strong> — o que de fato decide aquele projeto, reunião ou tema. Pergunte “qual é a história aqui?” e descarte todo detalhe que não muda o título. O repórter fareja o que vira notícia; o estenógrafo registra tudo e sai sem entender nada.","tip":"<strong>Como aplicar:</strong> diante de qualquer enxurrada de informação, force a pergunta “qual é a manchete?” antes de anotar a primeira linha.","wide":True},
      {"ic":"eye","t":"O Sinal É Discreto; o Ruído Grita","emph":"Discreto","b":"Reagir ao mais alto ou ao mais recente é o jeito mais seguro de perder o essencial, porque o ruído berra e o sinal cochicha. Treine a <strong>escuta do não-óbvio</strong>: o que ninguém diz, o que destoa do padrão, a anomalia que passa em branco. É no canto silencioso, não no centro barulhento, que costuma morar a informação que decide.","tip":"<strong>Regra:</strong> dar peso igual a tudo é a garantia matemática de perder o que importa no meio do que só faz barulho."},
      {"ic":"link","t":"Conectar Pontos Vale Mais que Colecioná-los","emph":"Conectar Pontos","b":"O valor não está em juntar fragmentos, e sim em <strong>ligá-los numa imagem</strong>. A manchete é o ponto que explica todos os outros — e ela só aparece quando você para de empilhar dados e começa a perguntar como conversam entre si. Quem apenas coleciona acaba afogado no próprio acervo.","tip":"<strong>Modelo mental:</strong> prefira sempre ligar poucos pontos numa história a colecionar muitos pontos soltos que nunca se encontram."},
    ],
  "lessons_title":"Lições-Chave: Observar",
  "lessons":["Diante de qualquer fluxo de informação, pergunte primeiro 'qual é a manchete?'.","O sinal é discreto e o ruído grita — não confunda volume com importância.","Ligar poucos pontos numa imagem vale mais do que colecionar muitos dados soltos."]},

 {"slug":"ch06-explorar-brincar-dormir","sub":"EXPLORAR: Brincar e Dormir",
  "intro":"Brincar e dormir parecem as primeiras coisas a cortar quando a vida aperta — e são justamente as que mais sustentam tudo o que vem depois. Não são folga roubada ao essencial: são o que torna possível explorar, criar e discernir. Proteger o sono é proteger o seu único ativo insubstituível: você.",
  "cards":[
      {"ic":"spark","t":"Brincar É Ativo, Não Custo","emph":"Ativo","b":"Brincar — qualquer coisa feita pelo prazer de si mesma — paga três dividendos: <strong>amplia o leque de opções, dissolve o estresse e acorda as funções superiores</strong> que exploram e criam. Quando a lógica empaca e o esforço só fecha portas, é o lúdico que reabre o caminho. Cortá-lo primeiro é fechar a torneira das próprias ideias.","tip":"<strong>Como aplicar:</strong> agende lazer de verdade, sem meta de produtividade. Trate-o como matéria-prima da criatividade, não como luxo dispensável.","wide":True},
      {"ic":"leaf","t":"O Sono Protege o Ativo","emph":"Protege o Ativo","b":"Dormir bem afia o foco, a criatividade e a capacidade de priorizar; sacrificar o sono <strong>corrói exatamente o que torna você capaz</strong> de fazer o essencial. Sete ou oito horas não são pausa — são recarga inegociável. O ativo descansado decide e produz mais que o esgotado em hora extra.","tip":"<strong>Modelo mental:</strong> oito horas dormindo podem render mais que oito horas a mais de trabalho feito sob fadiga. A hora bem dormida volta multiplicada."},
      {"ic":"key","t":"Você É o Ativo","emph":"Você É o Ativo","b":"A nascente de toda contribuição é a sua mente e a sua energia — por isso <strong>gerir a si mesmo vem antes de gerir tarefas</strong>. A cultura do “quem dorme menos é mais herói” troca produtividade por encenação de sacrifício e queima o capital que sustenta tudo. Glorificar a privação é quebrar o instrumento só para parecer dedicado.","tip":"<strong>Cuidado:</strong> cortar primeiro o sono e o lazer é serrar o galho em que toda a sua capacidade está sentada.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Brincar e Dormir",
  "lessons":["Brincar amplia o leque de opções, dissolve o estresse e alimenta a criatividade.","O sono é a recarga do ativo — protegê-lo é pré-condição de todo o resto.","Você é o ativo: gerir a si mesmo vem antes de gerir as tarefas."]},

 {"slug":"ch07-explorar-criterio90","sub":"EXPLORAR: O Critério 90% (Seleção Extrema)",
  "intro":"Aqui mora o coração do método: a seleção extrema. Se uma opção não é um claro 'SIM', então é um claro 'NÃO'. A régra é severa de propósito — recusar o bom é o aluguel que se paga para que o excelente encontre lugar quando chegar.",
  "cards":[
      {"ic":"target","t":"O Critério 90%","emph":"90%","b":"Dê a cada opção uma nota de 0 a 100 no critério que mais importa. Se não chega a <strong>90, ela vale 0 — descarte</strong>, sem meio-termo. Aceitar “oitos” razoáveis ocupa a capacidade que o “dez” iria exigir; por isso recusar um sólido oito hoje é o que deixa a vaga livre amanhã. Guardar o lugar é a jogada inteira.","tip":"<strong>Como aplicar:</strong> defina o critério decisivo, atribua a nota e elimine tudo abaixo de 90 — sem abrir exceção para o caso “quase lá”.","wide":True},
      {"ic":"scale","t":"Um Mínimo + Dois ou Três Extremos","emph":"Dois ou Três Extremos","b":"Para cruzar a porta, a opção precisa passar por <strong>um critério mínimo</strong> (“isto é viável?”) E por <strong>dois ou três critérios ideais extremos</strong> (“é exatamente o que eu quero?”). Só entra quem satisfaz os dois lados. Decide-se por régua — não por culpa, emoção ou a pressão de quem pediu.","tip":"<strong>Modelo mental:</strong> pense num clube de porta estreita. Quanto mais seletivo o critério de entrada, melhor tudo o que está lá dentro."},
      {"ic":"gap","t":"A Hesitação Já É o “Não”","emph":"Hesitação","b":"Dizer sim por culpa, pressão ou medo de perder lota a vida de medíocres; e o “talvez” suspenso drena energia enquanto adia a renúncia. A regra encurta o tormento: <strong>se não é um claro SIM, é um NÃO</strong>. Quando você se pega pesando demais, a própria dúvida já respondeu por você.","tip":"<strong>Sinal de alerta:</strong> uma pilha de “talvez” em aberto é seleção fraca — cada um deles consome energia e nunca vira coisa alguma.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Critério 90%",
  "lessons":["Pontue de 0 a 100: abaixo de 90 vira 0 e se descarta.","Exija um critério mínimo mais dois ou três extremos para qualquer 'sim'.","Se não é um claro SIM, é um NÃO — extinga a zona do 'talvez'."]},

 {"slug":"ch08-eliminar-clarear-nao","sub":"ELIMINAR: Clarear o Propósito e o \"Não\" Gracioso",
  "intro":"Eliminar começa pela clareza: um único propósito essencial, ao mesmo tempo concreto e inspirador. Com ele no centro, dizer 'não' ao resto deixa de soar grosseiro e passa a ser apenas coerente — e o 'não' coerente pode, sim, ser dito com graça.",
  "cards":[
      {"ic":"target","t":"A Intenção Essencial: Bússola, Não Slogan","emph":"Intenção Essencial","b":"Escolha um propósito <strong>inspirador o bastante para puxar e concreto o bastante para decidir sozinho</strong>. Troque o vago (“ser o melhor”, “fazer a diferença”) por uma meta única e verificável que, uma vez cumprida, torna mil outras desnecessárias. Uma boa intenção essencial responde, por você, a uma fila inteira de pedidos.","tip":"<strong>Como aplicar:</strong> redija o propósito de forma que ele próprio diga: “isto ajuda? não? então não agora.”","wide":True},
      {"ic":"mask","t":"O “Não” Gracioso","emph":"“Não” Gracioso","b":"Recuse com firmeza e respeito, <strong>separando a decisão da pessoa</strong>: dá para negar o pedido sem rejeitar quem pede. Diga não devagar e sim depressa; aponte o trade-off (“se eu fizer isto, não faço o essencial”); ofereça consideração em vez de desculpas a perder de vista. O desconforto breve de hoje compra a paz de não acumular ressentimento amanhã.","tip":"<strong>Regra:</strong> diga não devagar e sim depressa — e não empilhe justificativas: cada desculpa é um convite à renegociação."},
      {"ic":"sword","t":"Clareza Acima da Aprovação","emph":"Aprovação","b":"Sem propósito claro, pessoas e equipes avançam em todas as direções e em nenhuma. Dizer sim só para ser querido troca o <strong>respeito de longo prazo pela aprovação de curto</strong> — e um norte frouxo como “liderar o mercado” é cúmplice do estrago, porque nele tudo “cabe” e nada se decide.","tip":"<strong>Cuidado:</strong> propósito vago não filtra nada. Se tudo se encaixa no seu norte, é porque você ainda não tem norte algum.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Clarear e Dizer Não",
  "lessons":["Defina uma intenção essencial concreta E inspiradora — e verificável.","Use o propósito como filtro: o que não o serve merece um 'não'.","Recuse com graça: aponte o trade-off e separe sempre a decisão da pessoa."]},

 {"slug":"ch09-eliminar-descomprometer-editar-limites","sub":"ELIMINAR: Descomprometer-se, Editar e Limites",
  "intro":"Eliminar não é só recusar o novo — é a coragem de largar o que já não serve, mesmo depois de tanto investido. Descomprometer-se do que não funciona, editar a vida como um editor poda o supérfluo, e levantar limites que protegem o essencial dos avanços alheios.",
  "cards":[
      {"ic":"pivot","t":"O Teste de Base Zero contra o Custo Afundado","emph":"Base Zero","b":"O que já se gastou não volta; mantê-lo como justificativa é jogar tempo bom atrás do tempo ruim. Quando o único motivo for “já investi tanto”, faça a pergunta que desarma a inércia: <strong>“se eu ainda não estivesse nisto, quanto investiria HOJE para entrar?”</strong>. Se a resposta é “quase nada”, saia — e devolva as horas ao que importa.","tip":"<strong>Como aplicar:</strong> decida olhando para a frente, não para o que já se foi. O futuro não deve pagar a conta do passado.","wide":True},
      {"ic":"scale","t":"Editar a Vida","emph":"Editar","b":"Faça com a agenda o que um editor faz com o texto: <strong>cortar, condensar, corrigir e conter</strong>. Tirar opções não enfraquece o todo — fortalece-o. Uma obra (e uma vida) melhora tanto pelo que se retira quanto pelo que fica. Acrescentar é fácil e instintivo; a coragem mora no gesto de apagar o que não serve mais.","tip":"<strong>Modelo mental:</strong> menos na página, mais força no que sobra. O supérfluo nunca acrescenta — só dilui o essencial."},
      {"ic":"key","t":"Limites São Liberdade","emph":"Liberdade","b":"Fronteiras são regras claras do que você não aceita, fixadas <strong>de antemão para dizerem “não” no seu lugar</strong>, sem renegociação no calor do pedido. Parecem grades, mas é o limite prévio que liberta: sem ele, o tempo alheio invade o seu por padrão — e aí você reclama de uma porta que nunca chegou a instalar.","tip":"<strong>Sinal de alerta:</strong> “já cheguei até aqui, não posso parar” é o custo afundado em estado puro. Não é compromisso — é teimosia disfarçada.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Descomprometer, Editar, Limites",
  "lessons":["Use o teste de base zero para sair do que se mantém só por inércia.","Edite a vida: cortar opções fortalece o todo que sobra.","Limites definidos de antemão dizem 'não' por você e blindam o essencial."]},

 {"slug":"ch10-executar-buffer-gargalo","sub":"EXECUTAR: Buffer (Folga) e o Gargalo",
  "intro":"Executar o essencial sem heroísmo exige preparar o terreno antes. Construa buffer — a folga que absorve o imprevisto — e remova o gargalo, a restrição que dita a velocidade de tudo o mais. Empurrar mais forte contra um cano entupido não acelera nada; só inunda.",
  "cards":[
      {"ic":"layers","t":"Buffer: a Regra dos 50%","emph":"50%","b":"Buffer é a margem deliberada entre o planejado e o real. Contra a <strong>falácia do planejamento</strong> — sempre subestimamos o tempo —, estime quanto algo vai levar e some 50%. Deixe ar entre os compromissos e prepare-se para o pior cenário razoável: assim o imprevisto deixa de ser crise e vira apenas uma sobra já reservada.","tip":"<strong>Como aplicar:</strong> trate a agenda como cano com folga, não cheio até a borda. Sem espaço, qualquer atraso transborda na fila inteira.","wide":True},
      {"ic":"pin","t":"Remover o Gargalo, Não Empurrar Mais Forte","emph":"Gargalo","b":"O gargalo é o elo mais lento da corrente — e o sistema todo só anda na velocidade dele. Espremer esforço ao redor não resolve: <strong>identifique e desentupa a restrição antes de jogar qualquer recurso novo</strong>. Primeiro clareie a meta; depois ache o que mais trava o resto; só então invista — exatamente ali.","tip":"<strong>Regra:</strong> antes de “trabalhar mais”, pergunte o que está realmente travando. Reforce o ponto preso, não os que já fluem."},
      {"ic":"shield","t":"Preparação Extrema","emph":"Preparação Extrema","b":"Antecipar o pior cenário razoável reduz o estresse e blinda o essencial. O buffer <strong>converte a surpresa em rotina</strong>, em vez de deixar cada tropeço virar crise em cascata que contamina os compromissos seguintes. Planejar só para o melhor cenário é assinar, com antecedência, a correria crônica.","tip":"<strong>Cuidado:</strong> planejar apenas para o melhor caso garante atrasos encadeados — um pequeno tropeço de manhã derruba a fila do dia inteiro.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Buffer e Gargalo",
  "lessons":["Some 50% às estimativas e deixe ar entre os compromissos.","Antes de somar esforço, ache e desentupa o gargalo que limita tudo.","Antecipe o cenário ruim razoável — o buffer transforma surpresa em sobra já reservada."]},

 {"slug":"ch11-executar-progresso-rotina-fluxo","sub":"EXECUTAR: Progresso, Rotina e Fluxo",
  "intro":"O essencial não chega por grandes saltos, e sim por pequenas vitórias que se somam, por rotinas que põem o que importa no piloto automático e pelo foco inteiro no agora. Menos, porém melhor, vale também para o ritmo: um passo certo de cada vez.",
  "cards":[
      {"ic":"steps","t":"Pequenas Vitórias","emph":"Pequenas Vitórias","b":"Nada move tanto quanto sentir que se avança no que importa — o progresso visível é o combustível. Para destravar a meta grande que paralisa, comece <strong>ridiculamente pequeno</strong> e entregue uma vitória mínima por dia. O ímpeto se acumula por composição: a menor vitória de hoje vence a maior intenção adiada para um amanhã que nunca chega.","tip":"<strong>Como aplicar:</strong> defina a menor unidade de progresso possível e entregue-a hoje — antes mesmo de planejar a próxima.","wide":True},
      {"ic":"clock","t":"Rotina Põe o Essencial no Automático","emph":"Rotina","b":"Ancore o comportamento essencial num <strong>gatilho ou horário fixo</strong>, para não gastar força de vontade a cada repetição. Desenhe a rotina de modo que o difícil vire padrão: quando a disciplina pontual falha — e ela falha —, é o hábito que carrega o essencial sem pedir uma decisão nova todo dia.","tip":"<strong>Modelo mental:</strong> gatilho → rotina. Um sinal disparador (o café da manhã, o relógio) aciona a ação essencial sem você precisar querer."},
      {"ic":"wave","t":"Foco no Agora (Fluxo)","emph":"Agora","b":"Concentre-se na <strong>única coisa que importa neste instante</strong>, em vez de se rasgar entre o passado e o futuro. A pergunta que devolve o foco é simples: “o que é mais importante agora?”. Esperar pelo grande lance paralisa, e a multitarefa estilhaça a mente — o fluxo só nasce de uma coisa de cada vez, feita por inteiro.","tip":"<strong>Cuidado:</strong> a multitarefa não acelera coisa nenhuma — fragmenta a atenção e mata o fluxo justamente no que mais importa.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Progresso, Rotina e Fluxo",
  "lessons":["Comece ridiculamente pequeno: uma vitória mínima por dia.","Ancore o essencial numa rotina com gatilho — automatize o que importa.","Pergunte 'o que é mais importante agora?' e fique inteiro no presente."]},

 {"slug":"ch12-a-vida-do-essencialista","sub":"A VIDA DO ESSENCIALISTA",
  "intro":"O essencialismo não é uma técnica para os dias difíceis — é uma identidade, um modo de ser. Quando deixa de ser o que você faz e passa a ser quem você é, devolve clareza, controle e alegria, e a sensação rara de que nenhuma hora foi desperdiçada.",
  "cards":[
      {"ic":"constellation","t":"De “Fazer” a “Ser” Essencialista","emph":"Ser","b":"Pare de “fazer essencialismo” às vezes e passe a <strong>“ser essencialista”</strong> sempre, de modo que cada decisão já chegue filtrada pela essência — por hábito, não por esforço. Quando o que você faz reflete o que você valoriza, dissolve-se a tensão de viver partido entre a agenda e a alma.","tip":"<strong>Como aplicar:</strong> deixe “o que é essencial?” ser a lente padrão de toda escolha — da menor à decisiva — até virar reflexo, não cálculo.","wide":True},
      {"ic":"spark","t":"Clareza · Controle · Alegria","emph":"Clareza · Controle · Alegria","b":"Viver assim rende três frutos: <strong>clareza</strong> (você sabe o que importa), <strong>controle</strong> (a vida é sua, não dos outros) e <strong>alegria</strong> (presença plena no que vale a pena). Priorizar o essencial é o melhor seguro contra o arrependimento — contra o “eu queria ter feito o que de fato importava”.","tip":"<strong>Modelo mental:</strong> a vida é uma obra editada. O que você corta a define tanto quanto o que você decide manter."},
      {"ic":"book","t":"Vida Ocupada × Vida que Conta","emph":"Vida que Conta","b":"No fim, a escolha é entre uma agenda lotada de tudo e <strong>um punhado de coisas que importaram, feitas bem</strong>. Usar o essencialismo só na crise e recair no caos é voltar a ser Não-essencialista — porque até o essencial pede trade-off, e “menos” continua sendo a régua mesmo quando tudo o que sobrou é bom.","tip":"<strong>Cuidado:</strong> querer fazer “mais coisas essenciais” é a recaída disfarçada. Menos, porém melhor, vale também para o que já é bom.","warn":True},
    ],
  "lessons_title":"Lições-Chave: A Vida do Essencialista",
  "lessons":["Transforme o método em identidade: seja essencialista, não apenas o pratique de vez em quando.","Meça a vida pela contribuição ao essencial, não pelo volume de atividades.","'O que é essencial?' é a pergunta-padrão de toda escolha — e o melhor seguro contra o arrependimento."]},
]
