# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'Essencialismo: A Disciplinada
Busca por Menos' (Greg McKeown — Essentialism: The Disciplined Pursuit of Less).
Frameworks canônicos: 'menos, porém melhor'; a essência (a escolha, discernir o
vital trivial, o trade-off — 'o que vou renunciar?'); Essencialista vs.
Não-essencialista; o método EXPLORAR (espaço/escapar, observar/ouvir o sinal,
brincar, dormir, critério 90% / seleção extrema) → ELIMINAR (clarear o propósito
essencial, o 'não' gracioso, descomprometer-se / sunk cost, editar, limites) →
EXECUTAR (buffer/folga, remover o gargalo, pequenas vitórias, rotina, foco no
agora/fluxo); a vida do essencialista. Base: síntese dos frameworks amplamente
documentados — não reproduz o texto."""

BOOK = {
 "title": "Essencialismo",
 "author": "Greg McKeown",
 "header_light": "ESSENCIA",
 "header_bold": "LISMO",
 "subtitle": "VISÃO GERAL · A DISCIPLINADA BUSCA POR MENOS",
 "intro": "E se você parasse de perguntar 'como faço tudo?' e passasse a perguntar 'o que é absolutamente essencial?'. Greg McKeown chama isso de Essencialismo: não é gestão de tempo nem fazer mais com menos esforço — é a disciplina sistemática de discernir o vital de poucos do trivial de muitos, eliminar o resto sem culpa e proteger com folga o que importa. O lema: menos, porém melhor.",
 "description": "O manifesto de Greg McKeown contra a vida espalhada e ocupada que não leva a lugar nenhum. Em vez de dizer sim a tudo por pressão, o Essencialista escolhe: assume que todo 'sim' custa um 'não', aplica o critério dos 90% para recusar até o que é bom, e dedica sua energia à única coisa que faz a maior contribuição. Um método em três fases — explorar, eliminar, executar — para reconquistar a clareza, o controle e a alegria do que realmente conta.",
 "tags": ["Produtividade", "Foco", "Prioridades"],
 "progress": "12 Capítulos",
 "cover": "assets/essencialismo-cover.png",
 "overview_cards": [
   {"ic":"scale","t":"A Essência: Escolha · Discernir · Trade-off","b":"Três verdades destravam tudo. <strong>A escolha</strong>: você sempre pode escolher como gastar tempo e energia ('não posso' → 'eu escolho não'). <strong>O discernimento</strong>: quase tudo é ruído, pouquíssimo é sinal — esforço não vira resultado proporcional. <strong>O trade-off</strong>: não dá para ter tudo, então a pergunta certa não é 'como faço as duas?', mas <strong>'o que vou renunciar?'</strong>.","tip":"<strong>Modelo mental:</strong> antes de cada 'sim', nomeie do que você está abrindo mão. Todo 'sim' é um 'não' a outra coisa.","wide":True},
   {"ic":"steps","t":"O Método: Explorar → Eliminar → Executar","b":"<strong>EXPLORAR</strong> (discernir): crie espaço, observe o sinal, durma, brinque e use o <strong>critério 90%</strong>. <strong>ELIMINAR</strong> (cortar): clareie um propósito, diga o 'não' gracioso, descomprometa-se, edite e ponha limites. <strong>EXECUTAR</strong> (facilitar): construa folga (buffer), remova o gargalo e avance por pequenas vitórias e rotina.","tip":"<strong>Como aplicar:</strong> explore mais opções para escolher menos e melhor; depois corte sem dó; só então execute o pouco que resta.","wide":True},
   {"ic":"target","t":"Critério 90% (Seleção Extrema)","b":"A régua que torna tudo prático: avalie cada opção de 0 a 100. Se não chega a <strong>90</strong>, marque <strong>0</strong> e descarte. <strong>'Se não é um claro SIM, é um NÃO.'</strong> Recusar um sólido '8' é o preço de ter espaço para o '10'.","tip":"<strong>Regra:</strong> hesitou? A própria hesitação já costuma ser o 'não'. Acabe com a zona do 'talvez'."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-essencia-escolha","sub":"A ESSÊNCIA: A Escolha",
  "intro":"A base de todo essencialismo é reconquistar o poder de escolher. As opções podem ser tiradas, mas a capacidade de escolher entre elas, não. Quem esquece isso vira reativo — e deixa que os outros e o mais urgente decidam por ele.",
  "cards":[
      {"ic":"fork","t":"“Não Posso” é Quase Sempre “Escolho Não”","emph":"Escolho Não","b":"As opções podem ser arrancadas de você; a capacidade de escolher entre elas, jamais. Por isso quase todo “tenho que” esconde um <strong>“eu escolho” que você se recusa a assumir</strong>. Reformule: “escolho isto porque valorizo aquilo” — e a frase devolve a caneta que assina a sua agenda à sua própria mão.","tip":"<strong>Como aplicar:</strong> ao se ouvir dizer “sou obrigado”, troque por “eu escolho [X] porque [Y]” — sem porquê, recuse."},
      {"ic":"gap","t":"A Armadilha da Impotência Aprendida","emph":"Impotência Aprendida","b":"Quem para de exercer a escolha passa a agir <strong>como se não a tivesse</strong>: terceiriza a decisão ao mais barulhento e à “tirania do tudo é obrigatório”. Tratar cada demanda como inegociável não é humildade — é abdicar do leme e deixar que a vida seja escrita por quem grita mais alto.","tip":"<strong>Sinal de alerta:</strong> quando a sua pauta é definida pelo que grita mais alto, você parou de escolher e começou a só reagir.","warn":True},
      {"ic":"spark","t":"A Escolha É um Músculo","emph":"Músculo","b":"Ela atrofia no desuso e fortalece a cada “não” dito. Dizer “eu escolho não” é o gesto que tira você da posição de vítima e o coloca na de agente — e como músculo, <strong>treina-se no pequeno para aguentar peso no grande</strong>. Recusar um café hoje prepara você para recusar o projeto errado amanhã.","tip":"<strong>Modelo mental:</strong> a escolha não é algo que você tem — é algo que você faz, e que enfraquece se nunca for exercido."},
    ],
  "lessons_title":"Lições-Chave: A Escolha",
  "lessons":["Você sempre pode escolher como gastar tempo e energia — não terceirize isso.","Troque todo 'tenho que' por 'eu escolho', e nomeie o porquê.","Trate a escolha como músculo: exercite-a no pequeno para usá-la no grande."]},

 {"slug":"ch02-essencia-discernir","sub":"A ESSÊNCIA: Discernir o Vital Trivial",
  "intro":"Quase tudo é ruído e pouquíssimo é sinal. O Essencialista investe tempo para distinguir o vital de poucos do trivial de muitos — porque mais esforço, passado certo ponto, não vira mais resultado.",
  "cards":[
      {"ic":"layers","t":"O Vital de Poucos × o Trivial de Muitos","emph":"Vital de Poucos","b":"A maioria das opções contribui quase nada; uma minoria contribui quase tudo. Pela lei do poder, <strong>~20% do esforço gera ~80% do resultado</strong> — e alguns poucos acertos rendem ordens de magnitude mais que o resto somado. A meta não é fazer mais coisas bem; é achar a coisa certa que rende desproporcionalmente.","tip":"<strong>Como aplicar:</strong> em qualquer lista, ache as 1–3 opções de retorno desproporcional, congele as outras e não olhe para trás.","wide":True},
      {"ic":"eye","t":"Sinal × Ruído","emph":"Ruído","b":"Sinal é o que faz a maior contribuição; ruído é tudo o que apenas disputa a sua atenção. O perigo é que o ruído costuma ser barulhento e o sinal, discreto. <strong>Quando tudo parece igualmente importante, suspeite</strong>: importância uniforme quase nunca é a realidade — é falta de discernimento disfarçada de zelo.","tip":"<strong>Sinal de alerta:</strong> não meça esforço, meça contribuição — movimento não é progresso, e estar ocupado não é produzir o que conta.","warn":True},
      {"ic":"lens","t":"O Garimpeiro Não Carrega Cascalho","emph":"Cascalho","b":"A relação entre esforço e resultado não é linear: passado certo ponto, mais horas rendem cada vez menos. O essencialista pensa como garimpeiro — <strong>peneira muito cascalho para extrair a pepita</strong> e descarta o resto sem pena, em vez de pulverizar energia uniformemente sobre tudo o que aparece.","tip":"<strong>Modelo mental:</strong> pense como editor ou garimpeiro — pouca coisa vale ouro; o restante é peso morto que disfarça de trabalho."},
    ],
  "lessons_title":"Lições-Chave: Discernir",
  "lessons":["Quase tudo é trivial; pouquíssimo é vital — separe o sinal do ruído.","Mais esforço nem sempre dá mais resultado; busque o retorno desproporcional.","Se tudo parece importante, falta discernimento — não falta tempo."]},

 {"slug":"ch03-essencia-tradeoff","sub":"A ESSÊNCIA: O Trade-off",
  "intro":"Não dá para ter tudo nem fazer tudo. A pergunta do Não-essencialista é 'como faço as duas coisas?'; a do Essencialista é 'o que vou renunciar?'. Assumir o trade-off de propósito é o que transforma escolha em estratégia.",
  "cards":[
      {"ic":"fork","t":"A Pergunta Certa: “O Que Vou Renunciar?”","emph":"O Que Vou Renunciar?","b":"O não-essencialista pergunta “como faço as duas coisas?” — uma armadilha que ignora o custo. O essencialista pergunta <strong>“do que estou abrindo mão?”</strong>, que é acionável. Todo “sim” é um “não” a tudo o que poderia ocupar aquele tempo; fingir que não há custo só transfere a escolha para o acaso.","tip":"<strong>Como aplicar:</strong> antes de aceitar qualquer compromisso, escreva por extenso o que ele exclui da sua semana.","wide":True},
      {"ic":"scale","t":"Estratégia É o Que Você Decide NÃO Fazer","emph":"NÃO Fazer","b":"Marcas e pessoas que escolhem <strong>deliberadamente o que recusam</strong> ganham foco e força. Estratégia não é a lista do que você fará — é o conjunto de coisas que você descartou de propósito. O trade-off consciente transforma a escolha em vantagem; negá-lo dilui tudo numa mediocridade dispersa.","tip":"<strong>Modelo mental:</strong> pense como estrategista — defina o que vai recusar antes de definir o que vai abraçar."},
      {"ic":"mountain","t":"“Qual Problema Eu Prefiro Ter?”","emph":"Qual Problema Eu Prefiro Ter?","b":"Todo caminho tem dores; a opção sem custo não existe. Em vez de perseguir a ausência ilusória de dor, escolha conscientemente <strong>a dor que vale a pena</strong>. Tentar “encaixar tudo” na agenda é a negação pura do trade-off — e a fonte direta das semanas lotadas que não levam a lugar nenhum.","tip":"<strong>Cuidado:</strong> “dá para tudo” é a crença mais cara do não-essencialista — ela enche a agenda e esvazia o essencial.","warn":True},
    ],
  "lessons_title":"Lições-Chave: O Trade-off",
  "lessons":["Não dá para fazer tudo: a pergunta certa é 'o que vou renunciar?'.","Estratégia é escolher de propósito o que você NÃO vai fazer.","Todo 'sim' tem um custo de oportunidade — torne-o explícito."]},

 {"slug":"ch04-explorar-espaco","sub":"EXPLORAR: Espaço para Pensar e Escapar",
  "intro":"Para discernir o vital trivial é preciso, paradoxalmente, criar espaço — escapar da rotina e do ruído para conseguir pensar. Sem folga mental, você só reage; não escolhe.",
  "cards":[
      {"ic":"leaf","t":"Escapar É Parte do Trabalho","emph":"Escapar","b":"Para discernir o vital, é preciso, paradoxalmente, criar espaço — sair da rotina e do ruído para conseguir pensar. Bloqueie um período sem telas nem agenda, de duas horas a um retiro, levando só a pergunta essencial. <strong>Agendar o “pensar” não é fuga do trabalho — é a infraestrutura das decisões que importam.</strong>","tip":"<strong>Como aplicar:</strong> trate o tempo de pensar como uma reunião inegociável — com hora marcada e porta fechada.","wide":True},
      {"ic":"bubble","t":"A Folga Mental É o Estúdio da Mente","emph":"Folga Mental","b":"A banda livre da mente é o que permite ver as conexões e prioridades que o excesso esconde. Ideias essenciais não brotam na correria: <strong>elas precisam de uma sala vazia para aparecer</strong>. Sem essa folga, o cérebro nunca consegue separar o sinal do ruído — só apaga o incêndio mais próximo.","tip":"<strong>Modelo mental:</strong> pense no espaço como o estúdio da mente — uma sala vazia onde o essencial finalmente cabe."},
      {"ic":"clock","t":"O Paradoxo do Ocupado","emph":"Paradoxo do Ocupado","b":"Quem mais precisa parar para pensar é justamente quem se sente <strong>sem tempo algum para isso</strong>. A hiperconexão e a disponibilidade de 100% do tempo matam a reflexão e disfarçam ocupação de produtividade. Sentir-se “ocupado demais para parar” não é desculpa — é o próprio diagnóstico de que você precisa parar.","tip":"<strong>Cuidado:</strong> confundir estar sempre disponível com ser produtivo é o atalho mais rápido para nunca decidir o que importa.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Espaço",
  "lessons":["Agende, de propósito, tempo só para pensar — e proteja-o.","Folga mental é a condição para separar o sinal do ruído.","Quando achar que não tem tempo para parar, é exatamente a hora de parar."]},

 {"slug":"ch05-explorar-observar","sub":"EXPLORAR: Observar e Ouvir o que Importa",
  "intro":"Explorar bem é saber observar e escutar o sinal dentro do excesso de informação. O Essencialista vira 'jornalista da própria vida': busca o lide, a essência — não cada detalhe.",
  "cards":[
      {"ic":"lens","t":"Seja o Jornalista da Própria Vida","emph":"Jornalista da Própria Vida","b":"Enxergue os fatos com distância e procure a <strong>manchete</strong> — o que de fato importa naquele projeto, reunião ou tema. Pergunte “qual é a história aqui? qual é o lide?” e ignore todo detalhe que não muda a manchete. O repórter discerne o que vira notícia; o estenógrafo só registra tudo e sai sem clareza.","tip":"<strong>Como aplicar:</strong> em qualquer fluxo de informação, force a pergunta “qual é a manchete?” antes de anotar qualquer coisa.","wide":True},
      {"ic":"eye","t":"O Sinal É Discreto; o Ruído Grita","emph":"Discreto","b":"Reagir ao mais alto ou ao mais recente é a forma mais segura de perder o essencial, porque o ruído costuma ser barulhento e o sinal, quieto. Treine a <strong>escuta ativa do não-óbvio</strong>: o que ninguém está dizendo, o que destoa do padrão, a anomalia que ninguém comenta. É ali, no canto, que mora a informação que decide.","tip":"<strong>Regra:</strong> tentar absorver tudo com peso igual garante que você perca o que importa no meio do que só faz barulho."},
      {"ic":"link","t":"Conectar Pontos Vale Mais que Colecioná-los","emph":"Conectar Pontos","b":"O valor não está em acumular fragmentos, e sim em <strong>ligá-los numa visão</strong>. A manchete é o 20% que explica os 80% de uma situação — e ela só aparece quando você para de empilhar dados e começa a perguntar como eles se relacionam entre si. Quem só coleciona morre afogado no próprio acervo.","tip":"<strong>Modelo mental:</strong> privilegie sempre ligar fragmentos numa história a colecionar fragmentos soltos que nunca se encontram."},
    ],
  "lessons_title":"Lições-Chave: Observar",
  "lessons":["Em qualquer fluxo de informação, pergunte 'qual é a manchete?'.","O sinal é discreto; o ruído, barulhento — não confunda volume com importância.","Conectar pontos vale mais do que colecionar dados."]},

 {"slug":"ch06-explorar-brincar-dormir","sub":"EXPLORAR: Brincar e Dormir",
  "intro":"Brincar e dormir não são desperdício de tempo essencial — são investimentos que ampliam a capacidade de explorar, criar e discernir. Proteger o sono é proteger o seu maior ativo: você.",
  "cards":[
      {"ic":"spark","t":"Brincar É Ativo, Não Custo","emph":"Ativo","b":"A brincadeira — qualquer coisa feita pelo prazer dela mesma — entrega três ganhos: <strong>amplia opções, reduz o estresse e desperta as funções cerebrais superiores</strong> que criam e exploram. Quando a lógica empaca e o esforço só fecha portas, é o lúdico que reabre o caminho. Cortá-lo primeiro é cortar a fonte das próprias ideias.","tip":"<strong>Como aplicar:</strong> agende lazer real sem objetivo de produtividade — trate-o como insumo de criatividade, não como luxo dispensável.","wide":True},
      {"ic":"leaf","t":"O Sono Protege o Ativo","emph":"Protege o Ativo","b":"Dormir bem aumenta foco, criatividade e capacidade de priorizar; sacrificar o sono <strong>corrói exatamente aquilo que torna você capaz</strong> de fazer o essencial. Trate sete a oito horas como recarga inegociável, não como pausa: o ativo recarregado decide e produz mais que o esgotado em horas extras.","tip":"<strong>Modelo mental:</strong> oito horas dormindo podem render mais que oito horas a mais de trabalho feito sob fadiga."},
      {"ic":"key","t":"Você É o Ativo","emph":"Você É o Ativo","b":"A fonte de toda contribuição é a sua mente e a sua energia — por isso <strong>gerir a si mesmo vem antes de gerir tarefas</strong>. A cultura do “quem dorme menos é mais herói” confunde sacrifício com produtividade e queima o capital que sustenta tudo. Glorificar a privação é destruir o instrumento para parecer dedicado.","tip":"<strong>Cuidado:</strong> cortar primeiro o sono e o lazer é serrar o galho em que toda a sua capacidade está sentada.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Brincar e Dormir",
  "lessons":["Brincar amplia opções, reduz estresse e alimenta a criatividade.","O sono é recarga do ativo — protegê-lo é pré-condição de tudo.","Você é o ativo: gerir a si mesmo vem antes de gerir tarefas."]},

 {"slug":"ch07-explorar-criterio90","sub":"EXPLORAR: O Critério 90% (Seleção Extrema)",
  "intro":"A seleção extrema é o coração do método: se uma opção não é um claro 'SIM', é um claro 'NÃO'. Rejeitar o bom é o preço de ter espaço para o excelente.",
  "cards":[
      {"ic":"target","t":"O Critério 90%","emph":"90%","b":"Avalie cada opção de 0 a 100 no critério que mais importa. Se não chega a <strong>90, registre como 0 e descarte</strong> — sem meio-termo. Aceitar “oitos” medianos ocupa a capacidade que o “dez” exigiria; recusar um sólido oito hoje é o preço de ainda ter espaço quando o dez aparecer. Guardar a vaga é a jogada.","tip":"<strong>Como aplicar:</strong> defina o critério decisivo, dê a nota e elimine tudo abaixo de 90 — não abra exceção para o caso “quase”.","wide":True},
      {"ic":"scale","t":"Um Mínimo + Dois ou Três Extremos","emph":"Dois ou Três Extremos","b":"Para passar pela porta, a opção precisa cumprir <strong>um critério mínimo</strong> (“isto é viável?”) E <strong>dois ou três critérios ideais extremos</strong> (“é exatamente o que eu busco?”). Só entra o que satisfaz os dois lados. É decisão por régua, não por emoção, culpa ou pressão de quem pediu.","tip":"<strong>Modelo mental:</strong> pense num clube de porta estreita — quanto mais seletivo o critério de entrada, melhor tudo o que entra."},
      {"ic":"gap","t":"A Hesitação Já É o “Não”","emph":"Hesitação","b":"Dizer sim por culpa, pressão ou medo de perder enche a vida de medianos, e o “talvez” indefinido consome energia enquanto adia a renúncia. Por isso a regra encurta o tormento: <strong>se não é um claro SIM, é um NÃO</strong>. Quando você se pega pesando demais, a própria dúvida já está respondendo por você.","tip":"<strong>Sinal de alerta:</strong> uma coleção de “talvez” pendentes é seleção fraca — cada um deles drena energia e nunca vira nada.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Critério 90%",
  "lessons":["Pontue de 0 a 100; abaixo de 90 vira 0 e se descarta.","Exija um critério mínimo + dois ou três extremos para qualquer 'sim'.","Se não é um claro SIM, é um NÃO — acabe com o 'talvez'."]},

 {"slug":"ch08-eliminar-clarear-nao","sub":"ELIMINAR: Clarear o Propósito e o \"Não\" Gracioso",
  "intro":"Eliminar começa por clareza: um único propósito essencial, concreto e inspirador. Com ele definido, dizer 'não' ao resto deixa de ser rude e passa a ser coerente — e pode ser feito com graça.",
  "cards":[
      {"ic":"target","t":"A Intenção Essencial: Bússola, Não Mapa","emph":"Intenção Essencial","b":"Defina um propósito ao mesmo tempo <strong>inspirador e concreto o bastante para decidir sozinho</strong>. Troque o vago (“ser o melhor”, “fazer a diferença”) por uma meta única e verificável que, alcançada, torna o resto desnecessário. Uma boa intenção essencial responde por você a mil pedidos paralelos.","tip":"<strong>Como aplicar:</strong> escreva o propósito de modo que ele próprio diga “isto ajuda? não? então não vamos fazer agora.”","wide":True},
      {"ic":"mask","t":"O “Não” Gracioso","emph":"“Não” Gracioso","b":"Recuse com firmeza e respeito, <strong>separando a decisão da relação</strong>: dá para negar o pedido sem rejeitar quem pede. Diga não devagar e sim depressa; foque no trade-off (“se eu fizer isto, não farei o essencial”); ofereça respeito em vez de desculpas intermináveis. O desconforto curto de agora evita o ressentimento longo depois.","tip":"<strong>Regra:</strong> diga não devagar e sim depressa — e nunca empilhe desculpas, porque elas convidam à renegociação."},
      {"ic":"sword","t":"Clareza Acima da Aprovação","emph":"Aprovação","b":"Pessoas e equipes sem propósito claro avançam em todas as direções e em nenhuma. Dizer sim só para ser querido troca o <strong>respeito de longo prazo pela aprovação de curto</strong> — e um propósito vago como “liderar o mercado” é cúmplice disso, porque nele tudo “cabe” e nada se decide.","tip":"<strong>Cuidado:</strong> propósito vago não filtra nada; se tudo se encaixa no seu norte, é porque você não tem norte algum.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Clarear e Dizer Não",
  "lessons":["Defina uma intenção essencial concreta E inspiradora (verificável).","Use o propósito como filtro: o que não o serve recebe um 'não'.","Recuse com graça: foque no trade-off e separe a decisão da pessoa."]},

 {"slug":"ch09-eliminar-descomprometer-editar-limites","sub":"ELIMINAR: Descomprometer-se, Editar e Limites",
  "intro":"Eliminar não é só recusar o novo: é largar o que já não serve (vencendo o custo afundado), editar a vida como um editor corta o supérfluo, e instalar limites que protegem o essencial dos avanços alheios.",
  "cards":[
      {"ic":"pivot","t":"O Teste Zero-Based contra o Custo Afundado","emph":"Zero-Based","b":"O que já se gastou é irrecuperável; mantê-lo como justificativa é jogar tempo bom atrás do ruim. Quando o único motivo for “já investi tanto”, faça a pergunta que desarma a inércia: <strong>“se eu já não estivesse nisto, quanto investiria HOJE para entrar?”</strong>. Se a resposta é “pouco” — saia, e redirecione as horas.","tip":"<strong>Como aplicar:</strong> separe a decisão do passado investido — o futuro não deve pagar a conta do que já se foi.","wide":True},
      {"ic":"scale","t":"Editar a Vida","emph":"Editar","b":"Faça com a sua agenda o que um editor faz com um texto: <strong>subtrair, condensar, corrigir e conter</strong>. Cortar opções não enfraquece o todo — fortalece. A obra (e a vida) melhora tanto pelo que se retira quanto pelo que se mantém. Adicionar é fácil e instintivo; a coragem está em apagar o que não serve mais.","tip":"<strong>Modelo mental:</strong> pense como editor — menos opções na página, todo mais forte; o supérfluo dilui o essencial."},
      {"ic":"key","t":"Limites São Liberdade","emph":"Liberdade","b":"Fronteiras são regras claras do que você não aceita, definidas <strong>de antemão para dizerem “não” por você</strong> — sem renegociação no calor do pedido. Parecem rígidas, mas é exatamente o limite prévio que liberta: sem ele, o tempo dos outros invade o seu por padrão, e você reclama de uma porta que nunca instalou.","tip":"<strong>Sinal de alerta:</strong> “já cheguei até aqui, não posso parar” é a falácia do custo afundado em estado puro — não é compromisso, é teimosia.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Descomprometer, Editar, Limites",
  "lessons":["Use o teste zero-based para sair do que se mantém só por inércia.","Edite a vida: cortar opções fortalece o todo.","Limites definidos de antemão dizem 'não' por você e protegem o essencial."]},

 {"slug":"ch10-executar-buffer-gargalo","sub":"EXECUTAR: Buffer (Folga) e o Gargalo",
  "intro":"Executar o essencial sem esforço heroico exige preparar o terreno: criar buffer (folga/margem) para absorver imprevistos e remover o gargalo (a restrição que limita todo o progresso).",
  "cards":[
      {"ic":"layers","t":"Buffer: a Regra dos 50%","emph":"50%","b":"Buffer é a reserva deliberada de tempo entre o planejado e o real. Contra a <strong>falácia do planejamento</strong> — sempre subestimamos prazos —, estime quanto algo vai levar e some 50%. Deixe espaço entre os compromissos e prepare-se para o pior cenário razoável, para que o imprevisto deixe de ser crise e vire rotina absorvida.","tip":"<strong>Como aplicar:</strong> pense na agenda como cano com folga, não cheio até a borda — sem espaço, qualquer atraso transborda.","wide":True},
      {"ic":"pin","t":"Remover o Gargalo, Não Empurrar Mais Forte","emph":"Gargalo","b":"O gargalo é a restrição mais lenta da corrente — e o sistema inteiro só anda na velocidade dela. Somar esforço em volta não adianta: <strong>ache e desafogue a restrição antes de adicionar qualquer recurso</strong>. Primeiro clareie a meta, depois identifique o obstáculo que mais trava o resto, e só então invista.","tip":"<strong>Regra:</strong> antes de “trabalhar mais”, pergunte o que está realmente travando — e ataque esse ponto, não os que já fluem."},
      {"ic":"shield","t":"Preparação Extrema","emph":"Preparação Extrema","b":"Prevenir-se para o pior cenário razoável reduz o estresse e blinda o essencial. O buffer <strong>transforma a surpresa em rotina</strong>, em vez de deixar cada imprevisto virar uma crise em cascata que contamina os próximos compromissos. Planejar só para o melhor cenário é assinar, de antemão, a correria crônica.","tip":"<strong>Cuidado:</strong> planejar para o melhor cenário garante atrasos encadeados — um pequeno tropeço derruba toda a fila do dia.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Buffer e Gargalo",
  "lessons":["Some 50% às estimativas e deixe folga entre compromissos.","Antes de somar esforço, ache e remova o gargalo que limita tudo.","Prepare-se para o cenário ruim razoável — o buffer transforma surpresa em rotina."]},

 {"slug":"ch11-executar-progresso-rotina-fluxo","sub":"EXECUTAR: Progresso, Rotina e Fluxo",
  "intro":"O essencial avança não por grandes saltos, mas por pequenas vitórias que compõem progresso, por rotinas que colocam o essencial no piloto automático e pelo foco no agora (fluxo).",
  "cards":[
      {"ic":"steps","t":"Pequenas Vitórias","emph":"Pequenas Vitórias","b":"Nada motiva mais do que sentir que se avança no que importa — o progresso visível é o combustível. Para destravar a meta grande que paralisa, comece <strong>ridiculamente pequeno</strong> e produza uma vitória mínima por dia. O ímpeto se acumula por composição: a menor vitória de hoje vence a maior intenção adiada para um dia que nunca chega.","tip":"<strong>Como aplicar:</strong> defina a menor unidade de progresso possível e entregue-a hoje — antes de planejar a próxima.","wide":True},
      {"ic":"clock","t":"Rotina Põe o Essencial no Automático","emph":"Rotina","b":"Transforme o comportamento essencial em hábito ancorado num <strong>gatilho ou horário fixo</strong>, para não gastar força de vontade a cada repetição. Desenhe a rotina de modo que o difícil vire padrão: quando a disciplina pontual falha — e ela falha —, é o hábito quem carrega o essencial sem exigir decisão nova todo dia.","tip":"<strong>Modelo mental:</strong> gatilho → rotina — um sinal disparador (o café, o relógio) aciona a ação essencial sozinho."},
      {"ic":"wave","t":"Foco no Agora (Fluxo)","emph":"Agora","b":"Concentre-se na <strong>única coisa importante do momento presente</strong>, em vez de se dispersar entre o passado e o futuro. A pergunta que devolve o foco é “qual é a coisa mais importante agora?”. Esperar o “grande lance” paralisa, e a multitarefa estilhaça a atenção — o fluxo só nasce de uma coisa de cada vez, inteira.","tip":"<strong>Cuidado:</strong> a multitarefa não acelera nada — ela fragmenta a atenção e mata o fluxo no que realmente importa.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Progresso, Rotina e Fluxo",
  "lessons":["Comece ridiculamente pequeno: uma vitória mínima por dia.","Ancore o essencial numa rotina com gatilho — automatize o que importa.","Pergunte 'o que é mais importante agora?' e fique no presente."]},

 {"slug":"ch12-a-vida-do-essencialista","sub":"A VIDA DO ESSENCIALISTA",
  "intro":"O essencialismo não é uma técnica de vez em quando: é uma identidade, um modo de ser. Quando vira essência da pessoa, devolve clareza, controle e alegria — e a sensação de que cada hora foi bem vivida.",
  "cards":[
      {"ic":"constellation","t":"De “Fazer” a “Ser” Essencialista","emph":"Ser","b":"O essencialismo não é uma técnica de vez em quando — é uma identidade. Pare de “fazer essencialismo” e passe a <strong>“ser essencialista”</strong>, de modo que cada decisão seja filtrada pela essência por hábito, não por esforço. Quando o que você faz reflete o que valoriza, dissolve-se o conflito de viver dividido entre agenda e alma.","tip":"<strong>Como aplicar:</strong> use “o que é essencial?” como a lente padrão de toda escolha — da pequena à decisiva — até virar reflexo.","wide":True},
      {"ic":"spark","t":"Clareza · Controle · Alegria","emph":"Clareza · Controle · Alegria","b":"Viver assim entrega três frutos: <strong>clareza</strong> (você sabe o que importa), <strong>controle</strong> (a vida é sua, não dos outros) e <strong>alegria</strong> (presença plena no que vale a pena). Priorizar o essencial é o melhor seguro contra o arrependimento — contra o “eu queria ter feito o que de fato importava”.","tip":"<strong>Modelo mental:</strong> pense na vida como obra editada — o que você corta a define tanto quanto o que você mantém."},
      {"ic":"book","t":"Vida Ocupada × Vida que Conta","emph":"Vida que Conta","b":"No fim, a diferença é entre uma agenda lotada de tudo e <strong>um punhado de coisas que importaram, feitas bem</strong>. Usar o essencialismo só na crise e recair no caos é voltar a ser não-essencialista — porque até o essencial precisa de trade-off, e “menos” continua sendo a régua mesmo quando tudo o que sobrou é bom.","tip":"<strong>Cuidado:</strong> querer fazer “mais coisas essenciais” é a recaída disfarçada — menos, porém melhor, vale também para o que é bom.","warn":True},
    ],
  "lessons_title":"Lições-Chave: A Vida do Essencialista",
  "lessons":["Transforme o método em identidade: seja essencialista, não apenas o pratique.","Meça a vida pela contribuição ao essencial, não pelo volume de atividades.","'O que é essencial?' é a pergunta-padrão de toda escolha — e o seguro contra o arrependimento."]},
]
