# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'A Experiência Psicodélica' (Leary, Metzner & Alpert)."""

BOOK = {
  "title": "A Experiência Psicodélica",
  "author": "Timothy Leary, Ralph Metzner & Richard Alpert",
  "header_light": "A EXPERIÊNCIA",
  "header_bold": "PSICODÉLICA",
  "subtitle": "VISÃO GERAL · UM MAPA DA MENTE LIDO NO LIVRO TIBETANO DOS MORTOS",
  "intro": "Em 1964, três psicólogos de Harvard pegaram o <em>Bardo Thödol</em> — o manual budista para guiar a alma entre a morte e o renascimento — e leram nele, ousadamente, um mapa para o que acontece quando o ego se dissolve em vida. A tese é serena e radical: a experiência não está na molécula. Está no <strong>set</strong> (o que a mente traz), no <strong>setting</strong> (o que o quarto oferece) e no roteiro dos três Bardos que se atravessa. Tudo o mais é resistência ou rendição. Como estudo da consciência — não como convite —, o livro pergunta o que sobra de você quando se solta o leme.",
  "description": "Manual de Leary, Metzner & Alpert (1964), aqui em cheat sheet e em chave histórica de estudo da consciência. Lê o Livro Tibetano dos Mortos como mapa da mente: set & setting decidem a viagem; a substância é só uma chave química neutra; quase tudo é jogo, e o sofrimento vem de confundir o jogo com o real; a morte do ego (ego-loss) não é morte nem loucura; os três Bardos — Clara Luz, visões, reentrada — são fases a reconhecer; tudo que se vê é projeção da própria mente; e a travessia inteira cabe em três verbos: Confiar–Desligar–Flutuar.",
  "tags": ["Consciência", "Misticismo", "Psicologia"],
  "progress": "9 Capítulos",
  "cover": "assets/experiencia-psicodelica-capa.png",
  "overview_cards": [
    {"ic":"layers","t":"A Experiência Não Está na Química","b":"A mesma dose dá o paraíso a um e o inferno a outro — prova de que a molécula não decide nada. Três coisas decidem: o <strong>set</strong> (a mente que entra: intenção, medo, preparo), o <strong>setting</strong> (o quarto, as pessoas, a segurança) e o <strong>manual</strong> (o roteiro dos três Bardos, que diz o que fazer). A substância apenas amplifica o que esses três já trouxeram — e amplificar não é criar.","tip":"<strong>Modelo mental:</strong> trate a substância como amplificador, nunca como instrumento. Ela toca alto a música que o quarto já estava tocando baixo.","wide":True},
    {"ic":"steps","t":"O Mapa dos Três Bardos","b":"Os autores releem o <em>Bardo Thödol</em> como três estações da mente. A <strong>Clara Luz</strong> — ego dissolvido, consciência nua. As <strong>visões</strong> — tudo o que aparece é projeção sua. A <strong>reentrada</strong> — o eu se recompõe e volta aos jogos do dia. Em cada estação vale a mesma lei: reconhecer liberta, resistir aprisiona. Saber em que Bardo se está já é metade da travessia.","tip":"<strong>Como aplicar:</strong> o medo do desconhecido encolhe quando há um nome para a fase. O mapa não evita o território — apenas tira dele o pavor do sem-nome."},
    {"ic":"wave","t":"Confiar — Desligar — Flutuar","b":"A travessia inteira cabe em três verbos. <strong>Confiar</strong> no processo e no setting. <strong>Desligar</strong> o controle e o \"eu\". <strong>Flutuar</strong> correnteza abaixo, sem remar contra. O sofrimento nasce de uma só coisa: a resistência. E a entrega a dissolve. A frase é menos uma teoria que um mantra — algo a repetir quando o chão some.","tip":"<strong>Regra:</strong> não nade contra a correnteza; vire o rosto para o céu e boie. A mesma onda que afoga quem luta sustenta quem solta o leme."},
    {"ic":"book","t":"Por Que Ler Isto Hoje","b":"Esta é uma obra de 1964 sobre o <strong>estudo da consciência</strong> — não um convite a usar substância alguma. O que ela ainda ensina é psicológico e contemplativo: como a mente encara a dissolução do ego, como confunde projeção com realidade, como retorna de um estado extremo. São perguntas que a meditação, o luto e a psicologia também fazem.","tip":"<strong>Pergunta-chave:</strong> o que este mapa revela não sobre a viagem, mas sobre a sua mente comum, desperta, agora mesmo?"},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-set-and-setting",
    "sub": "CAPÍTULO 1: Set & Setting — O Terreno Decide a Viagem",
    "intro": "Aqui está a tese que funda o livro inteiro e desmonta o senso comum: a experiência não é causada pela substância. É causada pelo estado de quem entra (set) e pelo lugar onde se entra (setting). A química apenas abre a porta — quem decide o que há do outro lado é a disposição interior e o contexto. Por isso a viagem começa muito antes da dose.",
    "cards": [
      {"ic":"leaf","t":"A Semente Plantada Antes","emph":"Set","b":"O set é tudo o que a mente carrega ao entrar: intenção, humor, expectativa, medo, o que se leu e se temeu. Não é detalhe de partida — é a própria semente do que vai florescer. <strong>Quem entra apavorado colhe inferno; quem entra sereno colhe claridade.</strong> O que se busca, e sobretudo o que se teme, tende a se cumprir como profecia.","tip":"<strong>Como aplicar:</strong> a preparação interior não é etapa anterior à viagem — já é a viagem. Defina a intenção e dissolva o medo antes de qualquer outra coisa."},
      {"ic":"shield","t":"O Quarto Também É um Personagem","emph":"Setting","b":"O setting é o lugar, as pessoas, os sons, a segurança, a ausência de interrupção. Um quarto calmo e amoroso permite render-se; um quarto hostil ou imprevisível arma o pânico. <strong>Um ambiente seguro não é luxo — é pré-condição para soltar sem terror.</strong> Nada de estranhos, de exigências, de relógios, de \"tarefas\" a cumprir.","tip":"<strong>Regra:</strong> set e setting precisam estar em paz ao mesmo tempo — a sala serena e quem nela entra sereno. Um sem o outro não basta."},
      {"ic":"spark","t":"A Molécula É Neutra","emph":"Amplifica","b":"A mesma dose, em terrenos diferentes, dá paz ou dá pavor: é a prova de que a substância não tem conteúdo próprio. Ela não impõe nada — apenas amplifica e revela o que já estava no terreno. <strong>É amplificador, não instrumento.</strong> Toca alto a melodia que o set e o setting já tocavam baixo, seja ela um cântico ou um grito.","tip":"<strong>Sinal de alerta:</strong> creditar tudo à \"força da droga\" é esquecer que o mesmo composto, noutro quarto e noutra mente, produz o oposto exato.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["Quem decide a experiência é o set e o setting, jamais a substância em si.", "A preparação interior — intenção, serenidade, estudo — é a semente do que florescerá.", "Ambiente seguro e amoroso é pré-condição para render-se sem que o medo vire terror."],
  },
  {
    "slug": "ch02-chave-quimica",
    "sub": "CAPÍTULO 2: A Droga como Chave Química",
    "intro": "Se o Capítulo 1 disse onde a experiência mora, este diz o que a substância de fato é: uma chave química, nada mais. Ela destranca a mente comum, mas não contém a experiência, não traz mensagem, não produz sabedoria sozinha. Tudo o que se faz com a porta aberta vem do preparo e do mapa — nunca do que se engoliu.",
    "cards": [
      {"ic":"key","t":"A Chave Não Atravessa por Você","emph":"Não Atravessa","b":"A substância suspende, por um tempo, os filtros e os jogos do ego, soltando estados que já dormiam em potencial. É meio, não fim — um abridor neutro, nem sagrado nem demoníaco em si. <strong>A chave abre a porta; ela não atravessa por você.</strong> O trabalho de se entregar e de reconhecer permanece, do começo ao fim, inteiramente seu.","tip":"<strong>Modelo mental:</strong> a molécula não \"ensina\" coisa alguma. O que ensina é o reconhecimento — e reconhecer é um ato seu, não do composto."},
      {"ic":"book","t":"Porta Aberta, sem Planta da Casa","emph":"Labirinto","b":"O manual extraído do <em>Bardo Thödol</em> é o software que organiza o que fazer com a abertura; a química só liga o sistema. Sem roteiro, a porta aberta é desorientação pura; com ele, é navegação. <strong>Abrir a porta sem saber o que vem do outro lado é um convite ao pânico.</strong> Por isso as instruções devem estar lidas de antemão e à mão, prontas para reancorar.","tip":"<strong>Como aplicar:</strong> estude o roteiro antes. Quem entra numa casa às escuras, sem planta, tropeça em cada móvel e toma cada sombra por monstro.","warn":True},
      {"ic":"clock","t":"Tudo Passa, o Eu Retorna","emph":"Reversível","b":"O efeito é temporário: o ego sempre volta. Esquecer isso é justamente o que converte a dissolução em pavor. O que pesa não é a molécula, e sim <strong>o que se reconhece no intervalo em que a porta fica aberta.</strong> O sentido nasce do set, do setting e do manual; a substância só destranca — e logo cede, devolvendo a chave.","tip":"<strong>Regra:</strong> grave que isto vai passar e o eu vai voltar. A reversibilidade é a âncora que tira o terror da dissolução: ninguém se afoga numa maré que recua."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["A substância é chave química neutra — destranca a porta, mas não conduz por ela.", "O conteúdo e o sentido vêm do set, do setting e do manual, nunca da molécula.", "O estado é temporário e reversível; o valor está no que se reconhece no intervalo."],
  },
  {
    "slug": "ch03-jogos-e-nao-jogos",
    "sub": "CAPÍTULO 3: Jogos × Não-Jogos",
    "intro": "Leary lança um conceito que reorganiza tudo: quase toda a vida — social e mental — é feita de <em>jogos</em>. Papéis, regras, metas, estratégias que aprendemos sem perceber. Jogo não é palavra de desprezo: jogar é humano. O sofrimento começa quando esquecemos que estamos jogando e tomamos o tabuleiro por mundo. A experiência é, antes de tudo, um vislumbre do que existe fora de qualquer jogo.",
    "cards": [
      {"ic":"masks","t":"Tudo o que Você Faz Tem Regras","emph":"Jogos","b":"Jogo é qualquer padrão cultural com papéis, regras, valores e linguagem própria — o jogo do dinheiro, do status, da identidade, de \"ser alguém\". Reconhece-se um pela tríade: quais são as regras, quem ganha, o que aconteceria se eu parasse? E aqui está o golpe: <strong>o \"eu\" é só o jogador somado de todos esses jogos — não a consciência em si.</strong>","tip":"<strong>Pergunta-chave:</strong> diante de qualquer aflição, pergunte \"isto é um jogo?\". Quase sempre é — e só de nomear, o aperto no peito afrouxa."},
      {"ic":"mask","t":"A Dor de Esquecer o Tabuleiro","emph":"Tabuleiro","b":"O sofrimento brota de tomar o jogo pela realidade última — de confundir o papel com o ser. Quem se define inteiro pelo cargo desmcorona quando o cargo some. <strong>A vida cotidiana é um tabuleiro, e a angústia nasce de esquecer que existe um tabuleiro</strong> — de achar que você é a peça, quando é o jogador que a move.","tip":"<strong>Sinal de alerta:</strong> levar os próprios papéis a sério demais, confundir o que se é com o que se faz, é a raiz silenciosa de boa parte do tormento.","warn":True},
      {"ic":"target","t":"Jogar Sabendo que É Jogo","emph":"como Jogo","b":"O não-jogo é a consciência pura, sem papel nem meta — o destino do Primeiro Bardo. Mas a liberdade não é demolir os jogos nem cair no niilismo de quem larga tudo. <strong>Libertar-se é deixar de ser escravo dos jogos sem abandoná-los</strong>: é voltar a jogar com leveza, podendo entrar e podendo sair quando quiser.","tip":"<strong>Como aplicar:</strong> depois, reassuma os papéis — só que agora como quem sabe que são papéis. A graça está em escolher como e quando jogar."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["Quase toda a vida mental e social é feita de jogos, com seus papéis, regras e metas.", "O sofrimento vem de uma confusão só: tomar o jogo pela realidade última.", "Libertar-se é ver o jogo como jogo — não destruí-lo, mas deixar de ser seu refém."],
  },
  {
    "slug": "ch04-morte-do-ego",
    "sub": "CAPÍTULO 4: A Morte do Ego (Ego-Loss)",
    "intro": "Chegamos ao coração da experiência: o <em>ego-loss</em>, a dissolução temporária do senso de \"eu\" separado e de todos os jogos de uma só vez. Não é morte literal nem loucura — é a suspensão do jogador que se julgava idêntico à consciência. E há um único instante que decide tudo: o medo dessa dissolução é o que a transforma em terror. Sem medo, ela é paz.",
    "cards": [
      {"ic":"wave","t":"O Eu É Onda, Não Oceano","emph":"Onda","b":"O ego-loss é a queda momentânea da estrutura \"eu sou X, quero Y, temo Z\" — todos os papéis desmontando ao mesmo tempo. E não é o seu fim: <strong>o \"eu\" é uma onda, não o oceano; quando a onda baixa, o oceano continua inteiro.</strong> O ego é hábito acumulado, não a essência da consciência. Ele se dissolve, e o que o sustentava permanece.","tip":"<strong>Modelo mental:</strong> a dissolução do eu não te apaga — ela descobre a consciência que estava ali embaixo o tempo todo, sob o jogador."},
      {"ic":"spiral","t":"Duas Leituras, Dois Destinos","emph":"Resistência","b":"Há um instante de bifurcação. Ou a pessoa lê \"estou morrendo, estou enlouquecendo\" e despenca num inferno de resistência; ou lê \"isto é o ego soltando, isto é seguro\" e se entrega. <strong>O sofrimento vem da resistência; a entrega converte a mesma dissolução em paz.</strong> O evento é idêntico — o que muda o destino é o reconhecimento, não a química.","tip":"<strong>Sinal de alerta:</strong> ler a dissolução como morte ou loucura é o set errado que transforma uma libertação em pesadelo. A interpretação é tudo.","warn":True},
      {"ic":"pivot","t":"Solte o Leme, Não o Barco","emph":"Leme","b":"O ego-loss não se conquista à força — vem do soltar, jamais do empurrar. Agarrar-se ao \"eu\" no exato momento em que ele começa a dissolver é a fonte mesma do pânico. <strong>Largar o controle não é se perder: é deixar a correnteza levar.</strong> Soltar o leme não afunda o barco — é o gesto que abre a dissolução como uma paz vasta, sem dono.","tip":"<strong>Regra:</strong> não persiga o ego-loss empurrando; ele vem do render-se. Quanto mais força você faz para alcançá-lo, mais ele recua."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["O ego-loss é a dissolução temporária e reversível do \"eu\" e de todos os jogos.", "O sofrimento vem da resistência; a entrega converte a mesma dissolução em paz.", "O ego é hábito acumulado, não a essência da consciência — a onda, não o oceano."],
  },
  {
    "slug": "ch05-primeiro-bardo",
    "sub": "CAPÍTULO 5: O Primeiro Bardo — Ego-Perda e a Clara Luz",
    "intro": "Agora o livro abre o mapa propriamente dito. Tomando emprestadas as três estações do <em>Bardo Thödol</em>, os autores mapeiam a experiência em três fases. O Primeiro Bardo (Chikhai) é o ápice: a ego-perda total que descobre a Clara Luz — consciência pura, vazia e luminosa, anterior a todo \"eu\". É o não-jogo do Capítulo 3 em estado absoluto. E, por ser o mais alto, é também o mais difícil de habitar.",
    "cards": [
      {"ic":"lens","t":"A Clara Luz É o Espelho","emph":"Espelho","b":"No ponto mais alto, todo conteúdo cessa. Sem imagens, sem \"eu\", apenas uma claridade silenciosa e imensa — consciência nua, sem objeto, pura presença. <strong>Ela é o espelho, não a imagem refletida.</strong> Não procure mensagens nela; reconheça a consciência que reflete tudo. É o não-jogo absoluto, anterior a qualquer papel que você um dia vestiu.","tip":"<strong>Modelo mental:</strong> não cace visões nem revelações. A Clara Luz é a tela vazia e luminosa — nunca o que nela se projeta."},
      {"ic":"key","t":"Reconhecer É Lembrar de Casa","emph":"Reconhecer","b":"A liberação inteira repousa em um reconhecimento: a Clara Luz é a sua própria mente, não algo externo nem divino. O manual instrui: \"isto é a sua consciência, vazia e radiante\". <strong>Reconhecê-la é lembrar de casa — perceber que essa luz sempre foi você.</strong> Tomá-la por \"outro\", por um deus do lado de fora, é justamente não reconhecê-la — e cair nos Bardos seguintes.","tip":"<strong>Como aplicar:</strong> repouse na frase \"isto é a minha própria mente\". Tratar a luz como visão externa já é o primeiro passo da queda ao Segundo Bardo."},
      {"ic":"gap","t":"A Janela Se Fecha ao Toque","emph":"Estreita","b":"O estado mais alto é o mais fugaz: some no instante exato em que a mente tenta agarrá-lo, nomeá-lo ou \"fazer algo\" com ele. Este Bardo não pede ação — pede ausência de esforço, repouso na própria natureza. <strong>Toda tentativa de entender turva a luz e a estilhaça em formas</strong>, e dali se escorrega para o Segundo Bardo, o das visões.","tip":"<strong>Sinal de alerta:</strong> temer o vazio o fecha. O vazio luminoso é plenitude, não aniquilação — e querer \"compreendê-lo\" é, paradoxalmente, perdê-lo.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["O Primeiro Bardo é a ego-perda total que descobre a Clara Luz — a consciência pura.", "A liberação está em reconhecer essa luz como a própria mente, sem esforço algum.", "É o estado mais alto e o mais fugaz: agarrá-lo ou temê-lo o faz desaparecer."],
  },
  {
    "slug": "ch06-segundo-bardo",
    "sub": "CAPÍTULO 6: O Segundo Bardo — Visões e os Jogos da Mente",
    "intro": "Quando a Clara Luz não é reconhecida, a consciência desce ao Segundo Bardo (Chönyid): o reino das visões — formas, imagens, divindades pacíficas e iradas que surgem uma após a outra. Aqui o livro entrega sua chave-mestra, e é uma só: tudo o que se vê é projeção da própria mente. Não há nada \"lá fora\". O céu e o inferno saem do mesmo projetor.",
    "cards": [
      {"ic":"play","t":"Você É o Projetor","emph":"Projetor","b":"As visões — sublimes ou pavorosas — não têm vida própria: são a mente se exibindo a si mesma, arquétipos lançados na tela da consciência. <strong>Você é o projetor, não a tela; as imagens vêm de dentro.</strong> Lembrar disso desarma o medo de raiz, porque o que assusta não está ameaçando do lado de fora — é material seu, criado por você, projetado para você.","tip":"<strong>Modelo mental:</strong> crer que as visões são reais e externas é o que vira o Segundo Bardo em pesadelo — ou, igualmente perdido, em delírio místico."},
      {"ic":"mask","t":"O Monstro É o Seu Reflexo","emph":"Reflexo","b":"Surge uma figura furiosa, ameaçadora — e o impulso é fugir. Mas fugir a faz crescer. A instrução é a contrária: encarar. <strong>O monstro é o seu reflexo. A visão irada é material psíquico não reconhecido; ao reconhecê-lo como sua mente, ele se acalma ou se dissolve.</strong> Fugir dá poder à projeção; reconhecê-la a esvazia. Terror e êxtase brotam da mesma fonte: você.","tip":"<strong>Sinal de alerta:</strong> lutar contra a imagem aterrorizante só a intensifica. Alimentar a luta é alimentar o monstro — ele come o seu medo.","warn":True},
      {"ic":"link","t":"Nem Fugir do Terror, nem Agarrar o Êxtase","emph":"Nem Agarrar","b":"O princípio vale também para as visões belas: agarrar o êxtase aprisiona tanto quanto temer o horror — é só mais um jogo, mais um laço. Navegar o Segundo Bardo é reconhecer cada forma como interna e <strong>nem fugir do terror, nem se prender ao prazer.</strong> Nos dois casos a saída é uma só: ver a projeção, e deixar a forma surgir e passar.","tip":"<strong>Como aplicar:</strong> trate a visão linda e a horrível com a mesma postura. Diga \"isto sou eu\" e deixe fluir — sem agarrar, sem repelir, sem nomear de bom ou mau."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["O Segundo Bardo é o reino das visões — e todas, sem exceção, são projeção da mente.", "Reconhecer cada forma como interna, irada ou pacífica, é libertar-se dela.", "Nem fugir do terror nem agarrar o êxtase: os dois são jogos da própria mente."],
  },
  {
    "slug": "ch07-terceiro-bardo",
    "sub": "CAPÍTULO 7: O Terceiro Bardo — A Reentrada",
    "intro": "O Terceiro Bardo (Sidpa) é a reentrada: o retorno gradual ao ego comum e aos jogos do dia a dia. No <em>Bardo Thödol</em> é o Bardo do \"renascimento\" — e o nome não é por acaso. A maneira como se volta molda quem se será depois. Pode-se reentrar livre, carregando a lembrança de que tudo é jogo; ou recair nos velhos papéis com o mesmo aperto de antes, como se nada tivesse acontecido.",
    "cards": [
      {"ic":"steps","t":"A Volta Também É a Viagem","emph":"Parte da Viagem","b":"À medida que os efeitos cedem, o \"eu\" se recompõe aos poucos e a realidade consensual retorna. A descida tem ritmo próprio: forçá-la ou cortá-la de chofre gera confusão e medo. <strong>A volta não é o fim da viagem — é parte dela, e como se reentra pesa tanto quanto o pico.</strong> Tratar a descida como \"já acabou\" é deixar a colheita apodrecer no pé.","tip":"<strong>Sinal de alerta:</strong> a pressa de \"voltar logo ao normal\" cria ansiedade e pode reabrir o pânico. Respeite o ritmo lento da maré que baixa.","warn":True},
      {"ic":"fork","t":"Renascer É Escolher os Jogos","emph":"Escolher","b":"A reentrada não é passiva — é a chance de reassumir os jogos como quem sabe que são jogos, e não de recair neles cego. <strong>Renascer é escolher: você volta ao tabuleiro agora podendo decidir como jogar.</strong> O risco é o piloto automático — retomar os papéis antigos com a velha rigidez e, em poucas horas, estar de novo preso às mesmas angústias de sempre.","tip":"<strong>Como aplicar:</strong> ao sentir o \"eu\" voltando, escolha de propósito quais papéis vai vestir. O que se reassume sem pensar reassume você."},
      {"ic":"bookmark","t":"A Colheita Está na Integração","emph":"Integração","b":"O valor da experiência se decide aqui — no que se traz de volta e se costura à vida comum. Carregar viva a lembrança de que os papéis são jogos é o que faz a travessia render fruto. <strong>A integração é o que transforma um pico passageiro em mudança que fica.</strong> Sem ela, o aprendizado se apaga em dias e tudo volta a ser exatamente como era.","tip":"<strong>Pergunta-chave:</strong> ao reentrar, pergunte \"o que vi que quero levar para a vida desperta?\". A resposta a essa pergunta é a colheita real."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["O Terceiro Bardo é a reentrada — o retorno ao ego e aos jogos do cotidiano.", "Como se reentra decide o que da experiência se integra de fato à vida.", "O ideal é reassumir os jogos sabendo que são jogos, jamais recair neles cego."],
  },
  {
    "slug": "ch08-confiar-desligar-flutuar",
    "sub": "CAPÍTULO 8: Confiar — Desligar — Flutuar",
    "intro": "Toda a navegação dos três Bardos cabe numa instrução tríplice — a frase mais conhecida do livro: Confiar, Desligar, Flutuar correnteza abaixo. É o set ideal condensado em três verbos que se pode acionar quando o chão some. Não é teoria a compreender: é mantra a repetir. O antídoto direto ao pânico, em palavras de bolso.",
    "cards": [
      {"ic":"shield","t":"Confiar Desarma o Medo","emph":"Confiar","b":"Confiar é apoiar-se na própria mente, no processo, no guia, na segurança do quarto — e lembrar que o estado é seguro e reversível. <strong>A confiança desarma o medo antes que ele tenha tempo de virar inferno.</strong> É o primeiro verbo porque prepara o terreno: sem ela, toda onda que sobe é lida como ameaça; com ela, a mesma onda é lida como travessia.","tip":"<strong>Regra:</strong> ancore-se na intenção que você definiu e na presença do guia. A confiança é exatamente o que impede o medo de escalar até o pânico."},
      {"ic":"pivot","t":"Desligar É Largar o Leme","emph":"Desligar","b":"Desligar é soltar o controle, o \"eu\", a vontade de dirigir a experiência — parar de tentar \"entender\" ou \"consertar\". É o gesto que permite o ego-loss sem sofrimento. <strong>O controle é justamente o que precisa cair; insistir nele é o que fabrica o pânico.</strong> Confiar prepara, desligar inicia — é um só movimento, soltar, escandido em três tempos.","tip":"<strong>Sinal de alerta:</strong> tentar controlar a viagem ou combater o medo só os alimenta. É a luta que afunda, nunca a onda.","warn":True},
      {"ic":"wave","t":"Flutuar Correnteza Abaixo","emph":"Flutuar","b":"Flutuar é deixar-se levar pelo fluxo sem remar contra — acompanhar o que vier, visões, vazio, emoções, sem agarrar nem empurrar. Não é apatia: é rendição atenta, passividade ativa. <strong>Não nade contra a correnteza; vire o rosto para o céu e boie.</strong> A mesma onda que afogaria quem luta sustenta, sem esforço, quem solta o leme.","tip":"<strong>Como aplicar:</strong> nos momentos críticos, repita os três verbos como uma âncora — \"confie, solte, flutue\" — até o medo achar de novo o chão."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Confiar–Desligar–Flutuar é o protocolo central para atravessar a experiência sem pânico.", "A resistência — medo, controle, luta contra o fluxo — é a única fonte real de sofrimento.", "A frase funciona como mantra de reancoragem nos instantes em que o chão some."],
  },
  {
    "slug": "ch09-o-guia-e-a-sessao",
    "sub": "CAPÍTULO 9: O Guia e a Sessão",
    "intro": "O manual fecha com a parte prática: como se prepara e conduz uma sessão, e o que faz um guia. Os autores o desenham como presença serena, experiente e sem agenda própria — um navegador em terra firme que segura o mapa enquanto o outro atravessa o mar. Tudo o que se disse antes — set, setting, os três Bardos, o protocolo — aqui vira ato.",
    "cards": [
      {"ic":"person","t":"O Guia Segura o Mapa","emph":"Segura o Mapa","b":"O papel do guia é estar presente sem interferir: tranquilizar sem dirigir, reler as instruções dos Bardos quando preciso, nunca impor a própria experiência. Fala pouco e baixo, não discute, não desafia, zela pela segurança física. <strong>O guia é o leito do rio, não o remador — dá forma segura ao fluxo sem empurrar a água.</strong> A presença sem agenda é tudo o que se pede dele.","tip":"<strong>Sinal de alerta:</strong> guia com agenda própria — que quer que o outro tenha \"a\" experiência mística ou terapêutica certa — contamina a viagem inteira.","warn":True},
      {"ic":"wrench","t":"A Sessão Se Engenheira","emph":"Engenheira","b":"A preparação é o set & setting posto em ato: quarto silencioso e familiar, telefones mudos, intenção combinada, escolha cuidadosa de quem está presente, o manual à mão. As instruções dos três Bardos podem ser lidas em voz alta durante a sessão, guiando o reconhecimento em cada fase. <strong>Sessão sem preparo entrega tudo ao acaso</strong> — é recair no erro exato do Capítulo 1.","tip":"<strong>Como aplicar:</strong> trate ambiente, intenção e leitura prévia como engenharia, não como detalhe de última hora. É sobre essa base que todo o resto se ergue."},
      {"ic":"bubble","t":"Menos É Mais","emph":"Menos é Mais","b":"A melhor intervenção quase sempre é silêncio confiante e uma frase certa na hora certa. Diante de uma visão que assusta, o guia diz apenas: \"Está tudo bem. Isso é a sua mente. Confie, solte, flutue.\" Não explica, não conserta, não toca sem permissão. <strong>Intervir demais quebra o fluxo e mina a confiança</strong> — e o guia é decisivo, sobretudo, em conduzir uma reentrada serena.","tip":"<strong>Regra:</strong> é a relação de confiança entre guia e navegante que permite soltar. Protegê-la vale mais do que qualquer palavra a mais que se queira dizer."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["O guia é presença serena e sem agenda — segura o mapa, jamais dirige a viagem.", "A sessão se prepara com ambiente, intenção e leitura prévia: set & setting em ato.", "A maior ferramenta do guia é reancorar com Confiar–Desligar–Flutuar e conduzir uma reentrada calma."],
  },
]
