# -*- coding: utf-8 -*-
"""Dados de conteudo dos 9 capitulos genericos de Maquiavel Pedagogo.
Fonte: skill maquiavel-pedagogo. Consumido por gerar_maquiavel_rico.py.
Padrao: 6 cards ricos por capitulo, card-tip com prefixo em negrito."""

CHAPTERS = {
    'ch00-introducao': {
        'title_page': 'Introdução: O Ministério da Reforma Psicológica',
        'subtitle': 'INTRODUÇÃO: O MINISTÉRIO DA REFORMA PSICOLÓGICA',
        'meta': 'A revolução pedagógica mundial coordenada por Unesco, OCDE e Conselho da Europa para modificar valores, atitudes e comportamentos.',
        'intro': 'Uma revolução pedagógica mundial, conduzida por especialistas que dominaram os departamentos de educação da <strong>Unesco, Conselho da Europa, Comissão de Bruxelas e OCDE</strong>, busca impor uma "ética voltada para a criação de uma nova sociedade" usando técnicas psicopedagógicas de modificação de valores, atitudes e comportamentos.',
        'cards': [
            {
                'icon': 'globe',
                'wide': True,
                'id': 'coordenacao',
                'title': 'Uma Reforma Coordenada Internacionalmente',
                'body': 'Não é um fenômeno nacional isolado: a reforma é orquestrada por <strong>Unesco, OCDE, Conselho da Europa e Comissão de Bruxelas</strong>. A tese de Bernardin é documental — ele cita os próprios textos oficiais dessas organizações, "publicados sem reserva".',
                'tip': '<strong>Modelo mental:</strong> a escola é o instrumento, não o fim — o alvo declarado é a sociedade inteira.',
            },
            {
                'icon': 'cycle',
                'id': 'sequencia',
                'title': 'Revolução Psicológica → Revolução Social',
                'body': 'A sequência estratégica do projeto: <strong>mudança de valores + modificação de atitudes/comportamentos + manipulação da cultura → revolução psicológica → revolução social</strong>. É uma reapresentação sofisticada da utopia comunista.',
                'tip': '<strong>Como aplicar:</strong> rastreie a cadeia — quando uma reforma mira "atitudes" e "valores", o destino final não é pedagógico, é político.',
            },
            {
                'icon': 'layers',
                'id': 'quatro-tracos',
                'title': 'Os 4 Traços da Revolução Mundial',
                'body': 'A revolução pedagógica global se reconhece por quatro marcas:',
                'list': [
                    'Testes psicológicos em grande escala (90% das crianças norte-americanas já fichadas).',
                    'Informatização mundial do ensino, com censo de toda a população escolar.',
                    'Asfixia ou subordinação do ensino livre.',
                    'Pretensão de anular a influência da família.',
                ],
                'tip': '<strong>Sinal de alerta:</strong> testes e fichamentos em massa não são feitos "por amor à ciência" — têm aplicação prática.',
            },
            {
                'icon': 'eye',
                'id': 'conjunto',
                'title': 'Avaliar o Conjunto, não a Peça',
                'body': 'A revolução é introduzida "discretamente, sem deixar ver sua arquitetura geral". Cada reforma isolada (ciclos, IUFMs, avaliação, descentralização) <strong>parece administrativa</strong> — o sentido só aparece na coerência do conjunto.',
                'tip': '<strong>Anti-padrão:</strong> analisar cada medida isoladamente é exatamente o erro que o desenho do projeto explora.',
            },
            {
                'icon': 'doc-seal',
                'id': 'ressalva',
                'title': 'A "Ressalva Editorial" como Tell',
                'body': 'Quando uma organização internacional publica um texto "de responsabilidade do autor", ela <strong>o julgou próximo o bastante de suas posições para financiá-lo</strong>. A influência opera pela escolha de quem fala.',
                'tip': '<strong>Tell:</strong> a isenção formal de responsabilidade é, ela mesma, o endosso.',
                'quote': '"É preciso estar disposto a todos os sacrifícios e, inclusive, empregar — em caso de necessidade — todos os estratagemas, ardis e processos ilegais, silenciar e ocultar a verdade." (Lênin)',
            },
            {
                'icon': 'lock',
                'warning': True,
                'id': 'ditadura',
                'title': 'A Ditadura Psicopedagógica',
                'body': 'O regime que se desenha quando a escola <strong>impõe sub-repticiamente valores</strong> por técnicas de manipulação. A queda do nível escolar não é falha: é consequência lógica de uma missão que deixou de ser a formação intelectual.',
                'tip': '<strong>Modelo mental:</strong> se a missão principal já não é instruir, o declínio acadêmico é esperado e aceito.',
            },
        ],
        'lessons': [
            'A reforma educacional é coordenada internacionalmente — não é fenômeno nacional isolado.',
            'O objetivo declarado nos próprios documentos é inculcar valores, atitudes e comportamentos definidos de antemão.',
            'Os IUFMs existem para ensinar essas técnicas de manipulação aos futuros professores.',
            'A resistência dos professores é neutralizada por descentralização e engajamento psicológico.',
            'A tese é documental: o autor cita os próprios textos oficiais das organizações.',
        ],
    },
    'ch01-tecnicas-manipulacao': {
        'title_page': 'Capítulo I: As Técnicas de Manipulação Psicológica',
        'subtitle': 'CAPÍTULO I: AS TÉCNICAS DE MANIPULAÇÃO PSICOLÓGICA',
        'meta': 'Milgram, Asch, dissonância cognitiva e o pé na porta: as técnicas que fundamentam os métodos pedagógicos ativos.',
        'intro': 'Existem técnicas simples, estudadas cientificamente há décadas, que <strong>modificam valores, atitudes e comportamentos de adultos normais</strong>. São essas técnicas, ensinadas de forma semivelada nos IUFMs, que fundamentam os "métodos pedagógicos ativos".',
        'cards': [
            {
                'icon': 'shock',
                'id': 'milgram',
                'title': 'Submissão à Autoridade (Milgram)',
                'body': 'Mais de <strong>60%</strong> dos sujeitos aplicam choques de 450V até o fim — e <strong>92%</strong> quando apenas leem a lista e outro aciona o choque. O fator é a autoridade do pesquisador, não o sadismo.',
                'tip': '<strong>Tell:</strong> se um único par desobedece, 90% seguem o exemplo — a contestação é socialmente contagiosa.',
                'quote': '"O comum dos mortais, realizando simplesmente seu trabalho, sem qualquer hostilidade particular, pode tornar-se o agente de um processo de destruição terrível."',
            },
            {
                'icon': 'group3',
                'id': 'asch',
                'title': 'Conformismo de Grupo (Asch)',
                'body': 'Diante de um grupo unânime no erro, cerca de <strong>3/4 dos sujeitos cedem ao menos uma vez</strong> (32% das respostas erradas, contra 8% sem pressão). Mas um único aliado dissidente liberta o sujeito.',
                'tip': '<strong>Como aplicar:</strong> controlar a unanimidade aparente é controlar o indivíduo — por isso a dissidência é o que mais incomoda.',
            },
            {
                'icon': 'door',
                'id': 'pe-na-porta',
                'title': 'Pé na Porta e Porta na Cara',
                'body': 'Um <strong>ato aliciador mínimo</strong> abre caminho para o ato custoso: aceitação salta de 16,7% para 76%. O pedido preparatório "nem precisa ter o mesmo tema". Combinados, formam a técnica da "bola de neve".',
                'tip': '<strong>Modelo mental:</strong> comprometimentos crescentes — cada passo dado torna o próximo mais difícil de recusar.',
            },
            {
                'icon': 'scale-tip',
                'wide': True,
                'id': 'dissonancia',
                'title': 'Dissonância Cognitiva (Festinger)',
                'body': 'A contradição entre ato e opinião força uma reorganização interna: <strong>nossos atos modificam nossas opiniões</strong>, não só o contrário. É a base teórica das técnicas de lavagem cerebral — e a justificação dos métodos ativos.',
                'tip': '<strong>Sinal de alerta:</strong> a condição crítica é o <em>sentimento de liberdade</em> — sob coação consciente não há engajamento; a participação "voluntária" é o ingrediente ativo.',
                'quote': '"Os métodos ativos, fundados sobre a participação, são particularmente aptos a garantir essa aquisição [de valores]." (Declaração Mundial sobre Educação para Todos, Jomtien, 1990)',
            },
            {
                'icon': 'drama',
                'id': 'clarificacao',
                'title': 'Clarificação de Valores e Dramatização',
                'body': 'A <strong>clarificação de valores</strong> provoca dissonâncias "sem qualquer aparência de coação"; a <strong>dramatização</strong> alicia o ator pela identificação ao papel — uma das psicopedagogias ativas mais poderosas, ensinada nos IUFMs.',
                'tip': '<strong>Como aplicar:</strong> da "redação de textos" à "escrita de confissões", a fronteira com as técnicas de lavagem cerebral é tênue.',
            },
            {
                'icon': 'alert',
                'warning': True,
                'id': 'pressao',
                'title': 'Pressão Mínima > Pressão Forte',
                'body': 'Contra a intuição: a <strong>pressão apenas suficiente</strong> para induzir o comportamento produz interiorização duradoura; a pressão forte obtém só obediência externa temporária. Pagar $1 muda a opinião; pagar $20 não.',
                'tip': '<strong>Anti-padrão:</strong> achar que "pressão maior = mudança maior" é exatamente o inverso do que a evidência mostra.',
            },
        ],
        'lessons': [
            'Atos modificam opiniões — quem controla os atos da criança em sala controla, estatisticamente, seus valores.',
            'O sentimento de liberdade é o ingrediente da manipulação eficaz: a participação "voluntária" é o que engaja.',
            'Pé na porta e porta na cara escalonam comprometimentos numa "bola de neve".',
            'O grupo unânime dobra o indivíduo; um único dissidente o liberta.',
            'A avaliação é instrumento de interiorização de normas, não apenas medida de saber.',
        ],
    },
    'ch02-psicologia-social-educacao': {
        'title_page': 'Capítulo II: A Aplicação da Psicologia Social na Educação',
        'subtitle': 'CAPÍTULO II: A APLICAÇÃO DA PSICOLOGIA SOCIAL NA EDUCAÇÃO',
        'meta': 'Como a literatura pedagógica francesa recomenda abertamente as técnicas de manipulação como ferramentas de ensino.',
        'intro': 'O livro "Educar e Formar" (Monteil, 1989), dirigido a docentes, demonstra que as técnicas de manipulação do Capítulo I são <strong>explicitamente recomendadas como ferramentas educativas</strong> na França — e confessa que as pedagogias "não diretivas" sempre foram "a aplicação camuflada de uma diretriz".',
        'cards': [
            {
                'icon': 'book',
                'wide': True,
                'id': 'educar-formar',
                'title': '"Educar e Formar" (Monteil, 1989)',
                'body': 'Um manual dirigido a docentes e formadores que aplica, sem disfarce, o arsenal experimental de Festinger, Asch, Sherif e Kiesler. <strong>Manuais de pedagogia escritos como manuais de influência</strong> — o vocabulário é o mesmo da psicologia social de manipulação.',
                'tip': '<strong>Como aplicar:</strong> leia "jogos de influência" e "mudança de disposições" pelo que são — termos técnicos de manipulação, não metáforas pedagógicas.',
            },
            {
                'icon': 'recycle',
                'id': 'inversao',
                'title': 'A Inversão Atitude → Conduta',
                'body': 'A problemática central inverte o senso comum: a atitude aparece como <strong>produto da conduta, não sua causa</strong>. "A mudança de atitude torna-se a consequência de uma submissão comportamental."',
                'tip': '<strong>Modelo mental:</strong> induzir o comportamento primeiro; a crença se reorganiza depois para justificá-lo.',
                'quote': '"Após ter obedecido, com a sensação de tê-lo feito livremente, os indivíduos adotam o conteúdo do ato."',
            },
            {
                'icon': 'magnet',
                'id': 'cinco-fatores',
                'title': 'Os 5 Fatores do Engajamento (Kiesler)',
                'body': 'O grau de engajamento num ato é manipulável por cinco variáveis:',
                'list': [
                    'O caráter <strong>explícito</strong> do ato.',
                    'A sua <strong>importância</strong>.',
                    'O grau de <strong>irrevogabilidade</strong>.',
                    'O <strong>número de repetições</strong>.',
                    'Sobretudo, o <strong>sentimento de liberdade</strong> na realização.',
                ],
                'tip': '<strong>Tell:</strong> quando um método enfatiza a escolha "livre" e ativa do aluno, é o fator de Kiesler sendo acionado.',
            },
            {
                'icon': 'mask',
                'id': 'nao-diretividade',
                'title': 'A Não-Diretividade Camuflada',
                'body': 'A confissão de Monteil é direta: as pedagogias não diretivas são <strong>diretividade disfarçada</strong>, por admissão dos próprios teóricos. Tomá-las pelo valor de face é cair na armadilha.',
                'tip': '<strong>Anti-padrão:</strong> a "liberdade" da sala não diretiva é o que torna a diretriz invisível e eficaz.',
                'quote': '"Os trabalhos as reconduzem ao que elas sem dúvida não deixaram jamais de ser: a aplicação camuflada de uma diretriz que, em certa época, tínhamos dificuldade para admitir abertamente." (Monteil)',
            },
            {
                'icon': 'brain',
                'id': 'engajamento-engaja',
                'title': 'O Engajamento nos Engaja (Joule)',
                'body': 'Um comportamento compromete a ponto de <strong>determinar novas condutas</strong>, não só de modificar atitudes: submissão + sentimento de liberdade → engajamento → novo ato para "recobrar o equilíbrio cognitivo".',
                'tip': '<strong>Sinal de alerta:</strong> quanto mais o comportamento diverge das convicções, maior a mudança de atitude que ele força.',
            },
        ],
        'lessons': [
            'A literatura pedagógica francesa recomenda abertamente técnicas de psicologia social para "modificar cognições" dos alunos.',
            'O alvo declarado é a atitude — modificá-la para obter nova conduta.',
            'O engajamento é manipulável por cinco fatores conhecidos; o sentimento de liberdade é o principal.',
            'A não-diretividade é diretividade camuflada, por admissão dos próprios teóricos.',
            'Os IUFMs institucionalizaram a formação psicopedagógica reclamada por Monteil.',
        ],
    },
    'ch05-revolucao-etica': {
        'title_page': 'Capítulo V: A Revolução Ética',
        'subtitle': 'CAPÍTULO V: A REVOLUÇÃO ÉTICA',
        'meta': 'A substituição deliberada dos valores tradicionais por uma "nova ética" controlada pelo Estado e organizações internacionais.',
        'intro': 'A revolução pedagógica substitui deliberadamente os valores morais tradicionais por uma <strong>"nova ética" pseudo-universal "elaborada cientificamente"</strong> — bloqueando a transmissão familiar de valores e usando a escola para impor uma moral controlada pelo Estado e pelas organizações internacionais.',
        'cards': [
            {
                'icon': 'recycle',
                'wide': True,
                'id': 'dialetica',
                'title': 'A Manobra Dialética (Tese-Antítese-Síntese)',
                'body': 'A subversão dos valores em três tempos: <strong>(1)</strong> impedir a transmissão dos valores tradicionais, sobretudo pela família; <strong>(2)</strong> diante do caos ético resultante, tornar "imperativo" o retorno a uma educação moral; <strong>(3)</strong> introduzir os novos valores, agora controlados pelo Estado.',
                'tip': '<strong>Modelo mental:</strong> quem destrói e depois reconstrói um sistema de valores controla o resultado — por isso "os revolucionários se fazem defensores da ordem moral".',
            },
            {
                'icon': 'family',
                'id': 'contra-familia',
                'title': 'A Escola contra a Família',
                'body': 'A educação familiar é desqualificada como "inconsciente, contraditória e presa a valores tradicionais". A escola deve "explicitar" os valores para <strong>"superar esse modo pouco seguro de transmissão"</strong>.',
                'tip': '<strong>Tell:</strong> quando a transmissão familiar é tratada como problema a corrigir, a escola foi posicionada como sua rival funcional.',
            },
            {
                'icon': 'globe',
                'id': 'cientifica',
                'title': 'A Ética "Elaborada Cientificamente"',
                'body': 'A nova ética pretende-se universal e científica — e, como tal, <strong>não tolera concorrentes</strong>. "Os valores religiosos, de todas as religiões, são os primeiros visados", pois sistemas morais autônomos escapam ao controle estatal.',
                'tip': '<strong>Como aplicar:</strong> a nova ética funciona como substituto da religião — universal, "científica" e exclusiva.',
                'quote': '"Toda adoção de valores morais e de crenças deve ser realizada cientificamente." (Unesco)',
            },
            {
                'icon': 'layers',
                'id': 'elementos',
                'title': 'Os Elementos da Nova Ética',
                'body': 'Sob rótulos inquestionáveis entram reivindicações coletivistas:',
                'list': [
                    'Direitos humanos estendidos a "direitos sociais" (habitação, trabalho).',
                    'Direitos da criança — "temível arma contra a família".',
                    'Educação para a paz, o desarmamento e o meio ambiente.',
                    '"Passagem da competição à cooperação" e sociedade multicultural.',
                ],
                'tip': '<strong>Anti-padrão:</strong> aceitar "direitos humanos" sem definição deixa passar a extensão indefinida a direitos socioeconômicos.',
            },
            {
                'icon': 'target',
                'id': 'direitos-crianca',
                'title': 'A "Educação para a Paz" Revolucionária',
                'body': 'A própria literatura confessa: a educação para a paz é <strong>"atividade revolucionária"</strong> (Adam Curle). A recomendação tática é substituir o rótulo por "educação para os direitos humanos".',
                'tip': '<strong>Sinal de alerta:</strong> quando paz, justiça e equidade viram sinônimos, "a educação não pode permanecer neutra" — e deixa de sê-lo.',
            },
            {
                'icon': 'alert',
                'warning': True,
                'id': 'decadencia',
                'title': 'A Decadência é Deliberada',
                'body': 'A ruína moral não é eclipse acidental: é <strong>"o tempo necessário ao perfeito controle da modificação dos valores"</strong> — consequência escolhida e conscientemente assumida de um projeto de subversão.',
                'tip': '<strong>Modelo mental:</strong> distinga "hesitação" de "indiferença" — a decadência é a janela em que os valores são trocados.',
                'quote': '"Seria conveniente distinguir entre o tempo necessário ao perfeito controle da modificação dos valores e um suposto eclipse da moralidade." (Unesco)',
            },
        ],
        'lessons': [
            'A revolução ética opera por substituição: destrói os valores tradicionais e oferece novos, controlados institucionalmente.',
            'Os valores religiosos são os primeiros alvos — sistemas morais autônomos escapam ao controle estatal.',
            'A escola é posicionada como adversária funcional da família.',
            'A retórica dos direitos humanos veicula reivindicações socioeconômicas coletivistas.',
            'A decadência moral é consequência deliberada e assumida do projeto — não efeito colateral.',
        ],
    },
    'ch06-revolucao-cultural-interculturalismo': {
        'title_page': 'Capítulo VI: A Revolução Cultural e Interculturalismo',
        'subtitle': 'CAPÍTULO VI: A REVOLUÇÃO CULTURAL — HOMENAGEM A GRAMSCI',
        'meta': 'O interculturalismo como fusão deliberada de culturas para formar uma identidade nova e dissolver o núcleo identitário.',
        'intro': 'O interculturalismo não é coexistência de culturas, mas a <strong>fusão deliberada das culturas para formar "uma identidade cultural nova"</strong> — uma revolução psicológica de alcance epistemológico que ataca "as formas de conhecimento e a hierarquia dos saberes", rumo a uma cultura e língua mundiais.',
        'cards': [
            {
                'icon': 'fusion',
                'wide': True,
                'id': 'escalada',
                'title': 'De Multicultural a Intercultural',
                'body': 'A escalada conceitual é o ponto-chave: <strong>multicultural</strong> = várias culturas coexistem; <strong>intercultural</strong> = fusão que dá nascimento a uma cultura nova, "não mais marcada pelo eurocentrismo ou por um vínculo cego a suas próprias crenças e valores".',
                'tip': '<strong>Anti-padrão:</strong> confundir os dois é o erro — o segundo é declaradamente um projeto de fusão e engenharia de identidade.',
                'quote': '"A abordagem intercultural visa à formação de uma identidade cultural nova, aberta, não mais marcada pelo eurocentrismo, ou por um vínculo cego a suas próprias crenças e valores." (OCDE)',
            },
            {
                'icon': 'layers',
                'id': 'tripla',
                'title': 'A Tripla Justificação (OCDE)',
                'body': 'A educação multicultural é justificada por três vias: <strong>ética</strong> (combater discriminações), <strong>jurídica</strong> (direitos humanos) e — a decisiva — <strong>epistemológica</strong>: diferenciar "as formas da inteligibilidade e a estrutura do saber".',
                'tip': '<strong>Tell:</strong> a justificação epistemológica transforma a relativização cultural em "ciência" aplicável aos programas escolares.',
            },
            {
                'icon': 'globe',
                'id': 'mundialista',
                'title': 'A Educação Mundialista',
                'body': 'Programas para "inculcar nos alunos uma <strong>atitude mundialista</strong>" (Jomtien), vinculando meio ambiente, paz, dívida internacional e pobreza a todos os conteúdos. O dispositivo é total: atinge cada peça da instituição escolar.',
                'tip': '<strong>Como aplicar:</strong> quando um tema "transversal" reaparece em toda disciplina, é doutrinação por saturação, não interdisciplinaridade.',
            },
            {
                'icon': 'speech',
                'id': 'lingua',
                'title': 'A Língua Internacional',
                'body': 'O horizonte declarado é "o desenvolvimento de uma <strong>língua internacional</strong> que reforce uma cultura internacional" (Unesco) — prelúdio da destruição das culturas locais, em paralelo direto com a novilíngua de Orwell.',
                'tip': '<strong>Modelo mental:</strong> "a Revolução estará completa quando a língua for perfeita" — restringir a língua é restringir o pensamento.',
            },
            {
                'icon': 'brain',
                'id': 'nucleo-duro',
                'title': 'O Alvo: o Núcleo Duro das Culturas',
                'body': 'A própria OCDE revela o alvo ao perguntar: "Que pode fazer a escola em face das <strong>crenças e do imaginário coletivos que nutrem as culturas e constituem seu núcleo duro?</strong>". É Gramsci aplicado — revolução cultural por dentro das instituições.',
                'tip': '<strong>Sinal de alerta:</strong> relativizar a cultura própria "no mesmo nível das mais distantes" não é abertura — é desenraizamento instrumental.',
            },
            {
                'icon': 'alert',
                'warning': True,
                'id': 'tolerancia',
                'title': 'Tolerância ≠ Neutralidade',
                'body': 'Ler "tolerância" como neutralidade é o engano: a justificação epistemológica mostra que <strong>o alvo é a estrutura do saber</strong>, não apenas as atitudes. A resistência já é antecipada e desqualificada como "grupos ultraconservadores".',
                'tip': '<strong>Anti-padrão:</strong> aceitar o rótulo "tolerância" sem ler a justificação epistemológica é não ver o projeto.',
            },
        ],
        'lessons': [
            'Interculturalismo = engenharia de identidade, não convivência de culturas.',
            'A justificação epistemológica transforma a relativização cultural em "ciência" aplicável aos programas.',
            'O dispositivo é total: atinge cada peça da instituição escolar, inclusive a formação docente.',
            'O horizonte declarado é mundialista: atitude mundial, cultura e língua internacionais.',
            'Toda revolução psicológica requer uma revolução cultural — Gramsci como precondição.',
        ],
    },
    'ch07-reescrever-historia': {
        'title_page': 'Capítulo VII: Reescrever a História',
        'subtitle': 'CAPÍTULO VII: REESCREVER A HISTÓRIA',
        'meta': 'Manuais supranacionais e a subordinação da verdade histórica à atitude que se deseja produzir no aluno.',
        'intro': 'A educação para a paz e o interculturalismo exigem a <strong>reescritura da história</strong> — manuais "de história universal" redigidos por comitês internacionais, eliminando conflitos e elementos contrários à ideologia oficial: um "projeto essencialmente totalitário" que amputa as raízes das gerações futuras.',
        'cards': [
            {
                'icon': 'book',
                'wide': True,
                'id': 'manuais',
                'title': 'Os Manuais Supranacionais',
                'body': 'Proposta formal da 4ª Conferência dos Ministros da Educação (Unesco, 1988): elaborar <strong>"um manual de história geral da Europa e um manual de história universal"</strong>, com revisão dos manuais nacionais para "definir orientações comuns".',
                'tip': '<strong>Anti-padrão:</strong> tratar a revisão de manuais como cooperação técnica esconde que é definição centralizada do que pode ser lembrado.',
            },
            {
                'icon': 'palimpsest',
                'id': 'palimpsesto',
                'title': 'O Palimpsesto Orwelliano',
                'body': 'O processo tem um modelo literário explícito: a história raspada e reescrita "tantas vezes quantas fossem necessárias". <strong>Controlar o passado é controlar o presente.</strong>',
                'tip': '<strong>Modelo mental:</strong> sem referência estável ao passado, o indivíduo fica manipulável à vontade.',
                'quote': '"Toda a história era um palimpsesto, raspado e reescrito tantas vezes quantas fossem necessárias." (1984, Orwell)',
            },
            {
                'icon': 'scale-tip',
                'id': 'objetividade',
                'title': 'Objetividade Subordinada à Atitude',
                'body': 'O critério do ensino de história deixa de ser a verdade e passa a ser <strong>a atitude produzida no aluno</strong>: "a simples apresentação objetiva dos fatos, sendo insuficiente para produzir a atitude desejada...".',
                'tip': '<strong>Tell:</strong> quando a história é avaliada pela "atitude" que gera, virou instrumento de modificação de atitudes — o mesmo dispositivo dos capítulos I–III.',
                'quote': '"A simples apresentação objetiva dos fatos, sendo, de resto, insuficiente para produzir a atitude desejada..." (Unesco)',
            },
            {
                'icon': 'cycle',
                'id': 'aprender',
                'title': 'O "Aprender a Aprender"',
                'body': 'Sob o elogio das "sociedades aprendizes" esconde-se a função real: criar <strong>"uma mentalidade privada de qualquer referência estável"</strong>, aberta à mudança e à moda, "de maneira que a mera noção de verdade seja algo estranho e facilmente manipulável".',
                'tip': '<strong>Como aplicar:</strong> o relativismo histórico não é efeito colateral — é a infraestrutura da manipulação.',
            },
            {
                'icon': 'alert',
                'warning': True,
                'id': 'mutilacao',
                'title': 'A Mutilação Psicológica',
                'body': 'Amputar as raízes históricas <strong>impossibilita "toda verdadeira compreensão política"</strong>. A fórmula "adversários de ontem, parceiros de hoje" justifica eliminar dos manuais tudo "o que possa haver de desconfiança".',
                'tip': '<strong>Sinal de alerta:</strong> a história "curada pela diplomacia" entrega gerações sem as ferramentas para entender o presente.',
            },
        ],
        'lessons': [
            'A reescritura da história é proposta formal de conferências ministeriais — não inferência do autor.',
            'O critério passa a ser a atitude produzida no aluno, não a verdade factual.',
            '"Aprender a aprender" fabrica mentalidades sem referência estável — matéria-prima da manipulação.',
            'O paralelo com Orwell é estrutural: controle do passado = controle do presente.',
        ],
    },
    'ch10-avaliacao-informatizacao': {
        'title_page': 'Capítulo X: A Avaliação e a Informatização do Sistema Educacional Mundial',
        'subtitle': 'CAPÍTULO X: A AVALIAÇÃO E A INFORMATIZAÇÃO',
        'meta': 'A avaliação que mede e molda atitudes, com fichamento psicológico informatizado em escala mundial.',
        'intro': 'A avaliação deixa de medir o saber e passa a <strong>medir e moldar atitudes, valores e comportamentos</strong> — com testes psicológicos em massa, fichamento informatizado individual e bancos de dados interconectáveis em escala mundial.',
        'cards': [
            {
                'icon': 'gauge',
                'wide': True,
                'id': 'leme',
                'title': 'A Avaliação como Leme do Sistema',
                'body': 'Quem controla a avaliação controla o que se ensina: "é de importância primordial que os dispositivos de avaliação <strong>reflitam plenamente as reformas que se deseja implementar</strong>" (OCDE). Mude o que se mede e todo o sistema se realinha sozinho.',
                'tip': '<strong>Modelo mental:</strong> a avaliação é o leme — professores e alunos remam atrás dela automaticamente.',
                'quote': '"Os professores ensinarão para responder às exigências do sistema de avaliação e os alunos, conformemente, aprenderão." (OCDE)',
            },
            {
                'icon': 'database',
                'id': 'modelo-americano',
                'title': 'O Modelo Americano: Fichamento',
                'body': 'Testes psicológicos em massa no primário determinam <strong>perfis e disposições</strong> — também dos pais, refletidas nos filhos. Alunos com resultados "errados" recebem cursos behavioristas para "desencorajar atitudes aprendidas com os pais". Tudo "sem que o povo fosse informado".',
                'tip': '<strong>Sinal de alerta:</strong> os dados concentrados numa base única já nasciam com a intenção de ligar-se a bases similares no mundo.',
            },
            {
                'icon': 'barcode',
                'id': 'casimir',
                'title': 'Número de Identificação por Aluno',
                'body': 'Na França (1991–1993): <strong>160 questões por aluno</strong> sobre atitudes e inserção social, "competências transversais" não cognitivas no livreto escolar, o programa CASIMIR para coleta informatizada e um número de identificação secreto como chave de rede.',
                'tip': '<strong>Tell:</strong> coletar duas vezes (escola + amostra nacional) é absurdo transitório — a unificação numa base única é a trajetória natural.',
            },
            {
                'icon': 'chart-down',
                'id': 'competencia-minima',
                'title': 'A "Competência Mínima"',
                'body': 'O nível desejado é o da competência mínima — e os iletrados nos EUA saltaram de <strong>18 para 25 milhões</strong> em poucos anos. "Desde então, o governo não mais forneceu estatísticas."',
                'tip': '<strong>Modelo mental:</strong> privar dos instrumentos intelectuais é o que torna a doutrinação precoce eficaz — a "coletivização dos espíritos".',
            },
            {
                'icon': 'eye',
                'id': 'professores',
                'title': 'Testes Psicológicos de Professores',
                'body': 'O método das configurações (Peretti/INRP) sonda "as partes mais ou menos inconscientes do eu", avalia as <strong>mudanças ao longo da formação docente</strong> e até "os efeitos de uma terapia a que esteja submetido o professor".',
                'tip': '<strong>Como aplicar:</strong> não é só o aluno — o "eu profissional" do professor também é sondado e modificado.',
            },
            {
                'icon': 'alert',
                'warning': True,
                'id': 'sem-base-legal',
                'title': 'Fichamento sem Base Legal',
                'body': 'A operação avançou <strong>sem informação ao público e, na França, sem base legal</strong>: a operação de Jack Lang ocorreu "sem base legal alguma", antes da homologação da CNIL, com reitores ameaçando subordinados.',
                'tip': '<strong>Anti-padrão:</strong> confiar em promessas de confidencialidade local — em um ano a França passou de dados só da escola a fornecimento nacional sistemático.',
                'quote': '"Os estudantes registrados em fichas." (Le Figaro, 7/10/1992)',
            },
        ],
        'lessons': [
            'A avaliação é o mecanismo de comando da reforma: define na prática o que a escola ensina.',
            'O fichamento psicológico informatizado de alunos, pais e professores já era realidade nos EUA e avançava na França.',
            'A "cultura de avaliação" permanente + autoavaliação = interiorização contínua de valores.',
            'A infraestrutura técnica (bancos de questões, redes, CASIMIR) precede e habilita o controle mundial.',
            'A operação avançou sem informação ao público e, na França, sem base legal.',
        ],
    },
    'ch11-europa': {
        'title_page': 'Capítulo XI: A Europa',
        'subtitle': 'CAPÍTULO XI: A EUROPA',
        'meta': 'Como a agenda psicopedagógica entra nas instituições europeias pela porta do "insucesso escolar".',
        'intro': 'Embora OCDE, Conselho da Europa e Unesco não tenham poder executivo, sua influência molda as instituições comunitárias: resoluções e programas <strong>reproduzem fielmente a agenda psicopedagógica</strong> — a integração europeia dos sistemas como "prelúdio de uma integração mundial".',
        'cards': [
            {
                'icon': 'trojan',
                'wide': True,
                'id': 'cavalo-troia',
                'title': 'O "Insucesso Escolar" como Cavalo de Troia',
                'body': 'Sob o rótulo nobre de combater o fracasso escolar (Resolução de 1989) entram <strong>todas as peças da reforma</strong>: dimensão multicultural, socialização precoce, ensino não cognitivo, pedagogia centrada no aluno, abertura da escola à comunidade e "formação das pessoas envolvidas, pertençam ou não ao sistema educacional".',
                'tip': '<strong>Como aplicar:</strong> leia todo programa de "luta contra o insucesso" item a item — cada remédio é uma peça da reforma psicopedagógica.',
            },
            {
                'icon': 'eu-stars',
                'id': 'quadro-comum',
                'title': 'O Quadro Comum Europeu',
                'body': 'As reformas nacionais devem evoluir "dentro de um <strong>quadro comum europeu</strong>" — harmonização que antecede a padronização mundial. A agenda viaja por capilaridade: resoluções, programas e financiamento, não decretos.',
                'tip': '<strong>Tell:</strong> acompanhe o vocabulário, não as competências formais — instituições "sem poder executivo" governam mesmo assim.',
                'quote': '"É crucial que essas reformas ocorram mediante articulação com outras partes da Comunidade, para contribuir na elaboração de um quadro comum europeu, no qual devem evoluir as políticas nacionais." (Comissão Europeia)',
            },
            {
                'icon': 'magnet',
                'id': 'implicar-pais',
                'title': '"Implicar os Pais"',
                'body': 'O Parlamento Europeu declara que os sistemas "devem essencialmente visar a <strong>implicar os pais</strong> na educação das crianças". A leitura de Bernardin: implicá-los é engajá-los — para reduzir sua "resistência à mudança".',
                'tip': '<strong>Anti-padrão:</strong> ler "interesse dos pais" como empoderamento — o objetivo declarado é implicá-los, não ouvi-los.',
            },
            {
                'icon': 'recycle',
                'id': 'inovacao',
                'title': 'A Inovação como Prioridade Política',
                'body': 'A "gestão e o estímulo à inovação" devem tornar-se "prioridade política de primeira ordem", via <strong>maior autonomia [descentralização]</strong>, sensibilização de diretores e "zonas de inovação educacional".',
                'tip': '<strong>Modelo mental:</strong> a formação contínua é redesenhada para produzir gestores de inovação, não especialistas em disciplinas.',
            },
            {
                'icon': 'eye',
                'id': 'pos-escolar',
                'title': 'O Acompanhamento Pós-Escolar',
                'body': 'Um dispositivo de "acompanhamento dos jovens" <strong>mesmo após a escolaridade obrigatória</strong> — nas palavras citadas, "um verdadeiro controle psicológico dos indivíduos" que não termina com a escola.',
                'tip': '<strong>Sinal de alerta:</strong> o controle se estende para além da escola e para dentro das famílias — não tem ponto final declarado.',
            },
            {
                'icon': 'handshake',
                'id': 'acordos',
                'title': 'Os Acordos Internacionais',
                'body': 'Desde 1990, a cooperação formal da Comunidade com <strong>Conselho da Europa, Unesco, OCDE e OIT</strong> fecha o circuito: a mesma agenda, agora com respaldo institucional comunitário.',
                'tip': '<strong>Como aplicar:</strong> documentos "não vinculantes" preparam a legislação — subestimá-los é perder o passo seguinte.',
            },
        ],
        'lessons': [
            'A agenda psicopedagógica entra na Europa comunitária pela porta do "insucesso escolar".',
            'A Comissão propõe explicitamente autonomia/descentralização como instrumento de mudança.',
            'A formação contínua é redesenhada para produzir gestores de inovação, não especialistas.',
            'O dispositivo se estende para além da escola (jovens) e para dentro das famílias (pais).',
            'A integração europeia dos sistemas é etapa intermediária da integração mundial.',
        ],
    },
    'ch12-revolucao-pedagogica-franca': {
        'title_page': 'Capítulo XII: A Revolução Pedagógica na França',
        'subtitle': 'CAPÍTULO XII: A REVOLUÇÃO PEDAGÓGICA NA FRANÇA',
        'meta': 'A "revolução silenciosa" que entra por via administrativa e sobrevive a todas as alternâncias de governo.',
        'intro': 'A "revolução silenciosa" — expressão da própria OCDE — aterrissa na França via módulos e ciclos. Todos os temas internacionais <strong>entram por via administrativa</strong>, em boletins oficiais, e sobrevivem às alternâncias de governo.',
        'cards': [
            {
                'icon': 'hierarchy',
                'wide': True,
                'id': 'legrand',
                'title': 'Os 3 Níveis de Legrand',
                'body': 'A doutrina é articulada em três níveis: <strong>ético</strong> ("que homens desejamos formar e para que sociedade?"), <strong>psicológico</strong> (necessidades dos alunos) e <strong>técnico</strong> (processos diferenciados) — com a meta confessa de "um princípio de unificação mental".',
                'tip': '<strong>Tell:</strong> uma "nova doutrina pedagógica" que busca "unificação mental" admitida consensualmente não é pedagogia — é projeto político.',
                'quote': '"Não há ensino possível sem um conteúdo de valores e de afetividade... [é indispensável] uma nova doutrina pedagógica... princípio de unificação mental." (Louis Legrand)',
            },
            {
                'icon': 'school',
                'id': 'modulos-ciclos',
                'title': 'Módulos e Ciclos',
                'body': 'São as formas concretas da pedagogia centrada no aluno: os <strong>módulos</strong> (liceus, 1992) trazem grupos afins, "projeto pessoal" e autoavaliação permanente; os <strong>ciclos</strong> mantêm o professor com os alunos por anos. Resultado relatado: "recuo dramático no ensino da cultura geral".',
                'tip': '<strong>Como aplicar:</strong> avalie estruturas (módulos, ciclos, IUFMs), não discursos — é nelas que a reforma persiste.',
            },
            {
                'icon': 'peers',
                'id': 'grupo-pares',
                'title': 'O Grupo de Pares como Instrumento',
                'body': 'A crescente influência dos pares sobre as crianças <strong>"não é espontânea"</strong>: é "resultado de uma política de socialização deliberada", para fazer do grupo de pares o grupo de referência — "mais receptivo às influências dominantes do que um indivíduo isolado".',
                'tip': '<strong>Sinal de alerta:</strong> quando a influência dos pares cresce e a transmissão familiar definha, procure a política deliberada — não o acaso.',
                'quote': '"O controle social efetua-se então pelo grupo de pares, mais receptivo às influências dominantes do que o seria um indivíduo isolado."',
            },
            {
                'icon': 'recycle',
                'id': 'acao',
                'title': 'Ação antes que Conhecimento',
                'body': 'Para Legrand, "a educação deve consistir <strong>primordialmente em ação</strong>, e somente de modo secundário em conhecimento" — e o mestre "deverá ele mesmo estar convencido desses valores". A formação docente vira "criação de novas atitudes mediante a ação".',
                'tip': '<strong>Modelo mental:</strong> é a inversão atitude→conduta do Capítulo II, agora como doutrina oficial de formação de professores.',
            },
            {
                'icon': 'handshake',
                'id': 'bayrou',
                'title': 'O Caso Bayrou: a Continuidade',
                'body': 'Um ministro cristão, conservador e anticomunista — e ainda assim seu "triângulo de ouro" reproduz três temas da revolução internacional. Manteve ciclos, módulos, IUFMs e informatização; <strong>Jack Lang declarou-se "de acordo sobre o essencial"</strong>.',
                'tip': '<strong>Tell:</strong> a reforma que sobrevive à alternância política está nas estruturas, não nos discursos ministeriais.',
            },
            {
                'icon': 'alert',
                'warning': True,
                'id': 'quadro-capturado',
                'title': 'Reformar no Quadro Capturado',
                'body': 'Boas intenções + instituições capturadas = resultados revolucionários. Descentralizar ou criar formação contínua <strong>sem desmontar os IUFMs</strong> apenas abre espaço que o ensino não cognitivo ocupará primeiro.',
                'tip': '<strong>Anti-padrão:</strong> "lançar-se às goelas do lobo" — endossar a "inovação pedagógica" ignorando quem controla o domínio pedagógico.',
            },
        ],
        'lessons': [
            'A revolução entra por boletins oficiais, não por debate público.',
            'Módulos e ciclos são as formas concretas da pedagogia centrada no aluno e do ensino não cognitivo.',
            'A influência do grupo de pares sobre as crianças é engenharia deliberada de controle social.',
            'A alternância de governo (Lang → Bayrou) não interrompeu nada: estruturas mantidas.',
            'Conservadores bem-intencionados tornam-se vetores quando ignoram a captura institucional.',
        ],
    },
}
