# -*- coding: utf-8 -*-
"""Conteudo de 'A Experiencia Psicodelica' (Leary, Metzner & Alpert).
Fonte: skill experiencia-psicodelica. Consumido por gerar_psicodelia.py."""

OVERVIEW = {
    'meta': 'A Experiência Psicodélica de Leary, Metzner e Alpert — um manual baseado no Livro Tibetano dos Mortos para navegar estados alterados de consciência.',
    'intro': 'Um guia prático para navegar estados alterados de consciência, baseado no <strong>Bardo Thodol</strong> tibetano. Mapeia três fases da expansão da consciência e oferece frameworks para reconhecer e atravessar cada uma. <em>A droga não produz a experiência — ela é apenas a chave química.</em>',
    'cards': [
        {
            'icon': 'key',
            'title': 'Set & Setting',
            'wide': True,
            'body': 'A natureza da viagem não depende da substância, mas de duas variáveis: <strong>Set</strong> (o arranjo interno — personalidade, humor, preparação) e <strong>Setting</strong> (o cenário externo — ambiente, pessoas, cultura, música).',
            'tip': '<strong>Reconheça:</strong> contexto &gt; conteúdo. A mesma chave abre céus ou infernos conforme o set e o setting.',
            'quote': '"A droga apenas age como uma chave química — ela abre a mente, liberta o sistema nervoso de seus padrões ordinários."',
        },
        {
            'icon': 'hand',
            'title': 'Confiar · Desligar · Flutuar',
            'body': 'O protocolo universal para o desconhecido: <strong>confie</strong> na inteligência do processo vital, <strong>desligue</strong> a mente conceitual e <strong>flutue</strong> rio abaixo, sem resistência.',
            'tip': '<strong>Em dúvida:</strong> "desligue sua mente, relaxe, vá boiando rio abaixo".',
        },
        {
            'icon': 'yinyang',
            'title': 'Jogos e Não-Jogos',
            'body': 'Um <strong>jogo</strong> é toda sequência de comportamento com papéis, regras, rituais, objetivos e valores. O <strong>não-jogo</strong> é o reflexo espontâneo, a consciência transcendente — o que sobra quando o ego solta o roteiro.',
            'tip': '<strong>Lembre-se:</strong> a ego-perda é a dissolução temporária de todos os jogos.',
        },
        {
            'icon': 'eye',
            'title': 'Tudo é Projeção',
            'body': 'O princípio que governa o manual inteiro: <strong>visões, medos e deidades vêm de dentro</strong>. Reconhecer o processo é libertar-se dele; tentar controlá-lo é cair.',
            'tip': '<strong>Reconheça:</strong> nomear a projeção como projeção já é a libertação.',
        },
    ],
}

CHAPTERS = {
    'ch1-introducao-geral': {
        'nav_title': '1 · Introdução Geral',
        'title_page': 'Introdução Geral',
        'subtitle': 'MOVIMENTO I · A PARTIDA',
        'meta': 'A jornada a novos reinos da consciência: Set & Setting, os Três Bardos e o protocolo Confiar-Desligar-Flutuar.',
        'intro': 'A experiência psicodélica é uma <strong>jornada a novos reinos da consciência</strong> — a transcendência dos conceitos verbais, das dimensões de espaço-tempo e do ego. Este capítulo apresenta o mapa: os Três Bardos e o protocolo para navegá-los.',
        'cards': [
            {
                'icon': 'key',
                'title': 'A Chave Química',
                'wide': True,
                'body': 'A droga <strong>não</strong> produz a experiência transcendental — ela apenas abre a mente. O que se revela depende do <strong>Set</strong> (preparação, personalidade, humor) e do <strong>Setting</strong> (físico, social e cultural).',
                'tip': '<strong>Reconheça:</strong> a substância é a porta; quem decide a paisagem são o set e o setting.',
                'quote': '"A droga apenas age como uma chave química — ela abre a mente, liberta o sistema nervoso de seus padrões e estruturas ordinários."',
            },
            {
                'icon': 'portal',
                'title': 'Os Três Bardos',
                'wide': True,
                'body': 'O manual divide a viagem em três fases, segundo o Bardo Thodol:',
                'list': [
                    '<strong>1º Bardo (Chikhai)</strong> — transcendência completa: além das palavras, do espaço-tempo e do self. Consciência pura.',
                    '<strong>2º Bardo (Chonyid)</strong> — o self reaparece como visões pacíficas e coléricas. Período estético-alucinatório.',
                    '<strong>3º Bardo (Sidpa)</strong> — a reentrada no jogo-realidade rotineiro e no ego.',
                ],
                'tip': '<strong>Lembre-se:</strong> saber em qual bardo você está é o primeiro passo para navegá-lo.',
            },
            {
                'icon': 'hand',
                'title': 'Confiar · Desligar · Flutuar',
                'body': 'O princípio operacional fundamental: <strong>confiar</strong> na inteligência do processo vital de bilhões de anos, <strong>desligar</strong> o ego racionalizador e <strong>flutuar</strong> sem controle.',
                'tip': '<strong>Em dúvida:</strong> "Confie em sua divindade, confie em seu cérebro, confie em seus companheiros."',
            },
            {
                'icon': 'star',
                'title': 'As Confianças Básicas',
                'body': 'Sustentam a viagem: aceitar a <strong>extensão ilimitada da consciência</strong>, lembrar que milhões fizeram essa travessia, e saber que todos os males são produtos da própria mente.',
                'tip': '<strong>Reconheça:</strong> a experiência é segura — o terror, quando surge, é fabricado por dentro.',
            },
            {
                'icon': 'yinyang',
                'title': 'Jogos e Não-Jogos',
                'body': 'Um <strong>jogo</strong> reúne nove fatores — papéis, regras, rituais, objetivos, estratégias, valores, linguagem, lugares e padrões de movimento. Tudo que não os tem é <strong>não-jogo</strong>: reflexo, espontaneidade, consciência transcendente.',
                'tip': '<strong>Lembre-se:</strong> a ego-perda dissolve todos os jogos — e revela o que existe antes deles.',
            },
        ],
        'lessons': [
            'A droga é a chave química; Set & Setting determinam a experiência.',
            'A viagem tem três fases — os Três Bardos — cada uma com sua navegação.',
            'Confiar-Desligar-Flutuar é o protocolo universal para o desconhecido.',
            'O ego é uma coleção de jogos; a transcendência começa quando eles se soltam.',
        ],
    },
    'ch2-tributos-e-contexto': {
        'nav_title': '2 · Tributos e Contexto',
        'title_page': 'Tributos e Contexto Histórico',
        'subtitle': 'MOVIMENTO II · AS RAÍZES',
        'meta': 'Evans-Wentz, Jung e Govinda: a ponte entre o misticismo tibetano e a psicologia ocidental.',
        'intro': 'O manual se apoia em três pontes entre Oriente e Ocidente — <strong>Evans-Wentz, Jung e Lama Govinda</strong> — e na decisão de romper uma tradição de segredo de séculos.',
        'cards': [
            {
                'icon': 'moon',
                'title': 'W. Y. Evans-Wentz',
                'body': 'O tradutor que sentou-se aos pés de um lama por anos, como "uma molécula de RNA ativando o Ocidente com a mensagem do Oriente". Sua tese: <strong>a Arte de Morrer é tão importante quanto a Arte de Viver</strong>.',
                'tip': '<strong>Reconheça:</strong> a morte pré-mortem (a ego-perda) confere o poder de atravessar conscientemente a dissolução e a regeneração.',
            },
            {
                'icon': 'mirror',
                'title': 'Carl Gustav Jung',
                'body': 'Para Jung, o Bardo Thodol foi um "companheiro constante". Seu insight decisivo: <strong>todas as deidades, pacíficas e coléricas, são projeções da psique</strong> — o mundo exterior reflete a consciência interior.',
                'tip': '<strong>Lembre-se:</strong> toda afirmação metafísica é, na verdade, uma afirmação da psique.',
            },
            {
                'icon': 'lotus',
                'title': 'Lama Anagarika Govinda',
                'body': 'Iniciado em uma ordem budista tibetana, Govinda insistia que o Bardo Thodol é <strong>"um livro para os vivos tanto quanto para os mortos"</strong> — a morte do ego, não só a do corpo.',
                'tip': '<strong>Reconheça:</strong> o yogi é o "médico do Dharma" que guia através das fases da consciência.',
            },
            {
                'icon': 'yinyang',
                'title': 'Convergência Oriente-Ocidente',
                'wide': True,
                'body': 'Duas psicologias que se encontram: a oriental observa o interior (meditação, ioga, guias práticos); a ocidental observa o comportamento (laboratório, estatística, manuais clínicos).',
                'list': [
                    '<strong>Dados</strong> — observação interior detalhada × behaviorismo experimental.',
                    '<strong>Método</strong> — meditação e retiro × laboratório e estatística.',
                    '<strong>Escopo</strong> — extensão da consciência × comportamento observável.',
                    '<strong>Representantes</strong> — mestres budistas × William James e Carl Jung.',
                ],
                'tip': '<strong>Lembre-se:</strong> o manual funde os dois olhares num único mapa operacional.',
            },
            {
                'icon': 'door',
                'title': 'A Tradição do Segredo',
                'body': 'Os ensinamentos esotéricos foram guardados por séculos. Publicá-los <strong>"rompe com a tradição de segredo"</strong> — justificado porque o texto não será entendido por quem nunca expandiu a consciência.',
                'tip': '<strong>Reconheça:</strong> o mapa só faz sentido para quem já pisou (ou pisará) no território.',
            },
        ],
        'lessons': [
            'A Arte de Morrer (ego-perda consciente) é tão vital quanto a Arte de Viver.',
            'Todas as deidades e visões são projeções da própria psique (Jung).',
            'O Bardo Thodol é um livro para os vivos — a morte do ego, não só do corpo.',
            'O manual funde a psicologia interior oriental com a experimental ocidental.',
        ],
    },
    'ch3-primeiro-bardo': {
        'nav_title': '3 · Primeiro Bardo — Ego-Perda',
        'title_page': 'Primeiro Bardo — O Período da Ego-Perda',
        'subtitle': 'CHIKHAI BARDO · A SERENA LUZ',
        'meta': 'A transcendência completa: a Serena Luz Primária, os sintomas da ego-perda e a energia Kundalini.',
        'intro': 'O Primeiro Bardo é a <strong>transcendência completa</strong> — ego-perda total e o êxtase dos não-jogos. É a experiência da Serena Luz Primária, a radiação do instante em que a identidade se dissolve.',
        'cards': [
            {
                'icon': 'sun',
                'title': 'A Serena Luz Primária',
                'wide': True,
                'body': 'No supremo instante da ego-perda, surge a luz: o sistema nervoso destituído de atividade mental-conceitual, em contato direto com o processo cósmico. <strong>Reconhecê-la e tornar-se uno com ela quebra todos os vínculos ilusórios dos jogos.</strong>',
                'tip': '<strong>Reconheça:</strong> a fé é o primeiro passo na "Trilha Secreta" — e a calma é a condição.',
                'quote': '"Se no supremo instante de perder o ego puder reconhecer o êxtase que o tomará, e tornar-se uno com ele, todos os vínculos ilusórios de jogos se quebrarão imediatamente."',
            },
            {
                'icon': 'flame',
                'title': 'A Energia Kundalini',
                'body': 'Uma energia extática sobe pela espinha, dos chakras até o cérebro, com um ardor no fundo do crânio. Para os <strong>preparados</strong>, é alegria e iluminação; para os despreparados, vira interpretação patológica.',
                'tip': '<strong>Reconheça:</strong> o que o medo lê como doença, a preparação lê como ascensão.',
            },
            {
                'icon': 'helix',
                'title': 'O Fluxo Vital Biológico',
                'body': 'A consciência mergulha nos processos bioquímicos: motores pulsando, geradores irradiando energia. O perigo é <strong>arrastar o ego para os processos moleculares</strong> e tentar controlá-los.',
                'tip': '<strong>Cuidado:</strong> os dois únicos perigos do fluxo são tentar controlar e tentar racionalizar.',
            },
            {
                'icon': 'droplet',
                'title': 'Os Sintomas da Ego-Perda',
                'wide': True,
                'body': 'Sensações físicas a serem lidas como <strong>sinais de transcendência, não de doença</strong>:',
                'list': [
                    'Pressão corporal — "terra se desfazendo em água".',
                    'Frio úmido virando calor febril — "água se desfazendo em fogo".',
                    'Dispersão em átomos — "fogo se desfazendo em ar".',
                    'Pressão na cabeça — "foguete sendo lançado ao espaço".',
                    'Formigamento, corpo derretendo como cera, tremor ascendente.',
                ],
                'tip': '<strong>Reconheça:</strong> sinta as vibrações como dança cósmica e concentre-se na respiração.',
            },
            {
                'icon': 'wave',
                'title': 'A Serena Luz Secundária',
                'body': 'A consciência oscila entre transcendência e ego, como uma <strong>bola quicando</strong> — cada retorno menos intenso que o anterior. Surge a lucidez conceitual: o êxtase intelectual de pairar em terreno transcendente.',
                'tip': '<strong>Lembre-se:</strong> "é melhor ser parte do açúcar ou provar do açúcar?" — experiência × consciência da experiência.',
            },
            {
                'icon': 'people',
                'title': 'Os Tipos de Viajante',
                'body': 'Cada um navega a luz à sua maneira: o <strong>introvertido místico</strong> mantém a transcendência; o <strong>extrovertido</strong> se distrai com cores e sons; o <strong>novato confuso</strong> pode entrar em pânico inicial.',
                'tip': '<strong>Instrução ao guia:</strong> deixe o místico em paz; foque o extrovertido no ideal contemplativo; sinalize confiança ao novato.',
            },
        ],
        'lessons': [
            'Reconhecer a Serena Luz e tornar-se uno com ela quebra todos os jogos ilusórios.',
            'Os sintomas físicos da ego-perda são sinais de transcendência, não de doença.',
            'Os dois perigos do fluxo são tentar controlar e tentar racionalizar.',
            'A consciência quica entre ego e transcendência — cada retorno é mais suave.',
        ],
    },
    'ch4-segundo-bardo-visoes-1-3': {
        'nav_title': '4 · Segundo Bardo — Visões 1 a 3',
        'title_page': 'Segundo Bardo — Visões Pacíficas 1 a 3',
        'subtitle': 'CHONYID BARDO · AS VISÕES INTERIORES',
        'meta': 'O período das alucinações: a inação como chave e as três primeiras visões interiores.',
        'intro': 'No Segundo Bardo, o self reaparece como <strong>alucinações cármicas</strong>. O princípio que tudo governa: o cérebro está produzindo as visões — elas não existem fora da consciência que as anima. A chave é a <strong>inação</strong>.',
        'cards': [
            {
                'icon': 'eye',
                'title': 'Tudo é Projeção',
                'wide': True,
                'body': 'O princípio fundamental do bardo: <strong>nada existe exceto da forma como sua consciência dá vida às coisas</strong>. Sons, luzes e visões vêm de dentro. Reconhecer isto é a libertação.',
                'tip': '<strong>Reconheça:</strong> a visão mais gloriosa e a mais aterradora têm a mesma origem — você.',
                'quote': '"Reconheça que seu cérebro está produzindo as visões. Elas não existem. Nada existe exceto da forma como sua consciência dá vida às coisas."',
            },
            {
                'icon': 'lotus',
                'title': 'A Chave: Inação',
                'body': 'Integração passiva com tudo que ocorre. Tentar <strong>impor a vontade ou racionalizar gera redemoinhos alucinatórios</strong>. O lema é simples: PAZ, ACEITAÇÃO.',
                'tip': '<strong>Cuidado:</strong> se não puder ficar inativo, busque contato físico e respiração compartilhada com outra pessoa.',
            },
            {
                'icon': 'sun',
                'title': 'Visão 1 · A Fonte',
                'body': 'A Luz Branca como Criador — o Sol Central, a Única Verdade, o Pai-Mãe irradiante (deidade Vairochana). A <strong>armadilha</strong> é a educação que separa a divindade "lá em cima" do eu "aqui embaixo", gerando medo da luz.',
                'tip': '<strong>Instrução:</strong> não fuja da glória nem se agarre à "sombria luz da estupidez" — a luz e você são a mesma coisa.',
            },
            {
                'icon': 'kaleidoscope',
                'title': 'Visão 2 · Processos Arquetípicos',
                'body': 'Um fluxo infindável de <strong>formas coloridas e imagens microbiológicas</strong> — acrobacias celulares, um Niágara de desenhos abstratos, com cliques e zumbidos interiores.',
                'tip': '<strong>Cuidado:</strong> rotular ou verbalizar cada forma interrompe o fluxo — flutue com a corrente, não a nomeie.',
            },
            {
                'icon': 'infinity',
                'title': 'Visão 3 · Unidade Interior',
                'body': 'Pulsantes sensações de amor e unidade — um <strong>oceano unitivo de eletricidade orgástica</strong> em que cada célula canta liberdade. Ao se aproximar a dissolução, o ego grita "PARE" e vem a separação dolorosa.',
                'tip': '<strong>Instrução:</strong> entregue-se ao fluxo; se o ego enrijecer, feche os olhos, amoleça o corpo e respire como marefluxo.',
            },
        ],
        'lessons': [
            'Nada existe exceto como sua consciência dá vida — todas as visões são internas.',
            'A inação é a chave: impor vontade ou racionalizar gera redemoinhos.',
            'A Luz Branca é a Fonte; o medo dela nasce da separação eu/divindade.',
            'Não rotule as formas nem resista à unidade — flutue, amoleça, respire.',
        ],
    },
    'ch5-segundo-bardo-visoes-4-7': {
        'nav_title': '5 · Segundo Bardo — Visões 4 a 7',
        'title_page': 'Segundo Bardo — Visões 4 a 7 e Coléricas',
        'subtitle': 'CHONYID BARDO · AS VISÕES EXTERIORES',
        'meta': 'O mundo como ondas de energia, a unidade exterior, o circo retinal, o teatro mágico e as visões coléricas.',
        'intro': 'De olhos abertos, o Segundo Bardo revela o <strong>mundo exterior como vibração</strong>. As visões 4 a 7 dissolvem a solidez das coisas — e as Visões Coléricas testam o reconhecimento de que tudo é projeção.',
        'cards': [
            {
                'icon': 'wave',
                'title': 'Visão 4 · Vibrações Externas',
                'body': 'Os objetos viram <strong>padrões de ondas luminosas</strong>; a música, ondas acústicas. O mundo se revela um "show televisivo cósmico", sinestésico — sons sentidos como cores, sem mais substância que imagens numa tela.',
                'tip': '<strong>Cuidado:</strong> não tente congelar os padrões — "é como fotografar a tela e gritar que tomou posse da verdade".',
            },
            {
                'icon': 'infinity',
                'title': 'Visão 5 · Unidade Exterior',
                'body': 'Uma <strong>única rede de energia</strong> no universo: "você", "eu" e "ele" desaparecem em comunhão telepática. Na versão negativa, surge o "boneco de plástico" — pessoas como manequins sem vida.',
                'tip': '<strong>Instrução:</strong> sentindo o "boneco de plástico", volte ao fluxo interior (Visão 3): feche os olhos, deite, busque contato corporal.',
            },
            {
                'icon': 'kaleidoscope',
                'title': 'Visão 6 · O Circo Retinal',
                'body': 'Um <strong>caleidoscópio fantástico</strong> de luz e cor — a retina como tela de projeção, um mosaico de bilhões de raios em mutação, como um tapete persa vivo.',
                'tip': '<strong>Instrução:</strong> não imponha ordem — ria das acrobacias da retina e aproveite o espetáculo.',
            },
            {
                'icon': 'theatre',
                'title': 'Visão 7 · O Teatro Mágico',
                'body': 'Dramatizações simbólicas: <strong>cenas inteiras encenadas como teatro interior</strong>, com personagens arquetípicos, memórias e mitos entrando e saindo de cena.',
                'tip': '<strong>Instrução:</strong> assista sem entrar nos dramas — "atrás de cada porta espera precisamente o que você procura".',
            },
            {
                'icon': 'skull',
                'warning': True,
                'title': 'As Visões Coléricas',
                'body': 'Formas <strong>monstruosas envoltas em chamas</strong>, adornadas de crânios e serpentes. Mas são as mesmas Deidades Pacíficas sob outro aspecto — projeções não reconhecidas, devolvidas como terror.',
                'tip': '<strong>Reconheça:</strong> "todas estas figuras são emanações da sua própria consciência e não têm realidade objetiva". Não fuja — encare com serenidade.',
            },
        ],
        'lessons': [
            'O mundo exterior se revela vibração — ondas de energia sem solidez.',
            'A unidade pode virar "boneco de plástico"; a saída é o fluxo interior.',
            'O circo retinal e o teatro mágico são espetáculos — assista sem participar.',
            'As deidades coléricas são as pacíficas não reconhecidas: pura projeção.',
        ],
    },
    'ch6-terceiro-bardo': {
        'nav_title': '6 · Terceiro Bardo — Reentrada',
        'title_page': 'Terceiro Bardo — O Período da Reentrada',
        'subtitle': 'SIDPA BARDO · O RETORNO',
        'meta': 'A reentrada: os 7 sinais, os 6 mundos, o julgamento e a escolha consciente da personalidade.',
        'intro': 'O Terceiro Bardo é a <strong>transição de volta à vida desperta</strong> — cerca de metade da experiência se passa aqui. Suas metas: evitar as armadilhas da reentrada e escolher conscientemente a personalidade pós-sessão.',
        'cards': [
            {
                'icon': 'compass',
                'title': 'A Lei da Reentrada',
                'body': 'Duas instruções-chave bastam: <strong>não faça nada</strong> — permaneça calmo, passivo, relaxado — e <strong>perceba onde você está</strong>, reconhecendo o Terceiro Bardo.',
                'tip': '<strong>Reconheça:</strong> ~50% da experiência se passa na reentrada; saber disso já desarma o pânico.',
            },
            {
                'icon': 'list',
                'title': 'Os 7 Sinais de Reconhecimento',
                'wide': True,
                'body': 'Indícios de que você está na reentrada:',
                'list': [
                    'Poderes sobrenormais — percepção aumentada, telepatia.',
                    'Pânico e perseguição — demônios, controle mental.',
                    'Vagar irrequieto — levado pelos "ventos do carma".',
                    'Sentimento de estupidez e culpa comparativa.',
                    'Sensação de estar morto, entre robôs sem vida.',
                    'Esmagamento — redes metálicas, gaiolas (reentrada prematura).',
                    'Luz cinza crepuscular — o brilho vibrante se apaga.',
                ],
                'tip': '<strong>Reconheça:</strong> nomear o sinal como sinal já o esvazia de poder.',
            },
            {
                'icon': 'star',
                'title': 'Os 6 Mundos de Reentrada',
                'wide': True,
                'body': 'Cada cor de luz conduz a um nível de personalidade — <strong>siga as luzes claras, evite as monótonas</strong>:',
                'list': [
                    '<strong>Devas</strong> (santos) — luz branca — seguir.',
                    '<strong>Asuras</strong> (heróis) — luz verde — seguir.',
                    '<strong>Humanos</strong> (normais) — luz amarela — neutro.',
                    '<strong>Animais</strong> — luz azul — evitar.',
                    '<strong>Pretas</strong> (neuróticos) — luz vermelha — evitar.',
                    '<strong>Inferno</strong> — cor de fumaça — evitar.',
                ],
                'tip': '<strong>Instrução:</strong> o apego material puxa para baixo; o amor sincero eleva a reentrada.',
            },
            {
                'icon': 'scales',
                'title': 'As Visões de Julgamento',
                'body': 'O Senhor da Morte é a <strong>própria consciência</strong>; o Espelho do Carma é a <strong>memória</strong>. Partes do ego oferecem desculpas e justificativas diante do juiz interno.',
                'tip': '<strong>Lembre-se:</strong> "sua personalidade é uma coleção de padrões de pensamento e vazio — não pode ser ferida".',
            },
            {
                'icon': 'lotus',
                'title': 'Os 4 Métodos de Prevenção',
                'body': 'Para não cair em reentrada inferior: <strong>meditar no Buda/guia</strong> (figura protetora), concentrar-se em <strong>bons jogos</strong>, meditar na <strong>ilusão</strong> (tudo é Maya) e no <strong>vazio</strong> (Dharma-Kaya).',
                'tip': '<strong>Instrução:</strong> escolha a meditação conforme a armadilha — proteção, intenção, desapego ou vazio.',
            },
            {
                'icon': 'mountain',
                'warning': True,
                'title': 'A Escolha Consciente',
                'body': 'A regra de ouro da reentrada: <strong>não volte fugindo dos atormentadores</strong>. Banir o medo primeiro, escolher com calma e imparcialidade, ir devagar — sem se agarrar aos antigos scripts.',
                'tip': '<strong>Reconheça:</strong> "não seja atraído ao seu antigo ego" — cada momento pode ser uma agradável descoberta.',
            },
        ],
        'lessons': [
            'Metade da viagem é reentrada: não faça nada e reconheça onde está.',
            'Os 7 sinais e os 6 mundos são mapas — siga as luzes claras, evite as monótonas.',
            'O juiz é a sua consciência e o espelho é a sua memória — não minta.',
            'Escolha a personalidade pós-sessão com calma, sem fugir e sem apego.',
        ],
    },
    'ch7-comentarios-tecnicos': {
        'nav_title': '7 · Comentários Técnicos',
        'title_page': 'Comentários Técnicos sobre Sessões',
        'subtitle': 'O OFÍCIO · PREPARAÇÃO E GUIA',
        'meta': 'Modos de uso do manual, os quatro objetivos, as substâncias e o papel do guia psicodélico.',
        'intro': 'A parte prática do manual: <strong>como planejar e conduzir uma sessão</strong>. Os modos de uso, os quatro objetivos clássicos, o papel das substâncias e — sobretudo — as qualidades do guia.',
        'cards': [
            {
                'icon': 'compass',
                'title': 'Três Modos de Uso',
                'body': 'O manual serve de três formas: como <strong>leitura preparatória</strong> (reconhecimento é a palavra-chave), como <strong>apoio durante a sessão</strong> e como roteiro de <strong>programação</strong> de visões com música e símbolos.',
                'tip': '<strong>Instrução:</strong> "como um mapa rodoviário, consulte-o apenas se perder-se" — se a viagem começa em paz, não precisa dele.',
            },
            {
                'icon': 'star',
                'title': 'Os 4 Objetivos da Sessão',
                'wide': True,
                'body': 'Defina a intenção antes de partir (os quatro fins do hinduísmo clássico):',
                'list': [
                    '<strong>Poder pessoal</strong> — entendimento, discernimento, crescimento.',
                    '<strong>Dever e posição</strong> — autoconhecimento, vencer jogos, melhorar relações.',
                    '<strong>Diversão e prazer</strong> — sensações, beleza estética, êxtase.',
                    '<strong>Libertação</strong> — a experiência mística de ego-perda e iluminação.',
                ],
                'tip': '<strong>Reconheça:</strong> guia e viajante devem concordar com o objetivo antes da sessão.',
            },
            {
                'icon': 'key',
                'title': 'A Droga é a Chave',
                'body': 'LSD (mais potente), psilocibina (mais curta), mescalina (menor potência), DMT (muito breve). Mas vale sempre o princípio: <strong>a substância é só a chave química — não produz a experiência</strong>.',
                'tip': '<strong>Lembre-se:</strong> escolher a chave é o detalhe; o set e o setting são a viagem.',
            },
            {
                'icon': 'meditate',
                'title': 'Preparação e Cenário',
                'body': 'Antes: <strong>resolver conflitos emocionais pendentes</strong>, jejum leve, roupas confortáveis, sem compromissos depois. O cenário: ambiente familiar, sem interrupções, natureza, música selecionada e objetos simbólicos.',
                'tip': '<strong>Instrução:</strong> tenha comida simples à mão para o retorno — a reentrada também é cuidada.',
            },
            {
                'icon': 'hand',
                'warning': True,
                'title': 'O Guia Psicodélico',
                'body': 'O bom guia tem experiência própria, <strong>calma, paciência ilimitada e ausência de jogos pessoais</strong>. O que NÃO fazer: ser simpático demais, "jogar o jogo de médico", impor ajuda ou verbalizar em excesso.',
                'tip': '<strong>Cuidado:</strong> patologizar a experiência a reprime — o silêncio é, muitas vezes, o melhor guia.',
            },
        ],
        'lessons': [
            'O manual é um mapa — consulte-o só quando se perder.',
            'Defina um dos quatro objetivos antes da sessão e combine-o com o guia.',
            'A substância é só a chave; preparação e cenário são a viagem.',
            'O bom guia é calmo e silencioso — nunca patologiza nem impõe jogos.',
        ],
    },
    'ch8-instrucoes-para-sessao': {
        'nav_title': '8 · Instruções para a Sessão',
        'title_page': 'Instruções para Uso Durante a Sessão',
        'subtitle': 'A VOZ DO GUIA · O ROTEIRO VIVO',
        'meta': 'As instruções faladas para cada bardo e cada visão — o roteiro prático da travessia.',
        'intro': 'O capítulo operacional: as <strong>instruções a serem ditas em voz alta</strong> em cada fase. São o roteiro vivo que conduz o viajante do primeiro bardo à reentrada consciente.',
        'cards': [
            {
                'icon': 'sun',
                'title': 'Instruções do 1º Bardo',
                'body': 'Quando a ego-perda começa, o guia sussurra e depois silencia no êxtase claro. A instrução central: <strong>não se apegue a nada, por mais glorioso — confie e deixe fluir</strong>.',
                'tip': '<strong>Instrução:</strong> gravações na voz do próprio viajante são especialmente eficazes.',
            },
            {
                'icon': 'eye',
                'title': 'Instruções do 2º Bardo',
                'body': 'A preliminar que abre todas as visões: <strong>"escute, não se deixe distrair — os sons, luzes e visões vêm de dentro de você"</strong>. O reconhecimento da projeção é a chave de cada visão.',
                'tip': '<strong>Reconheça:</strong> repetida com calma, esta frase desfaz a maioria dos pânicos.',
            },
            {
                'icon': 'list',
                'title': 'O Roteiro das 7 Visões',
                'wide': True,
                'body': 'Uma instrução para cada visão do Segundo Bardo:',
                'list': [
                    '<strong>1 · A Fonte</strong> — a luz e você são a mesma coisa.',
                    '<strong>2 · Arquétipos</strong> — não rotule; flutue com as formas.',
                    '<strong>3 · Unidade Interior</strong> — entregue-se; amoleça o corpo.',
                    '<strong>4 · Vibrações</strong> — não congele os padrões; tudo é Maya.',
                    '<strong>5 · Unidade Exterior</strong> — "todos somos um"; sem medo.',
                    '<strong>6 · Circo Retinal</strong> — ria; não imponha ordem.',
                    '<strong>7 · Teatro Mágico</strong> — assista; não entre nos dramas.',
                ],
                'tip': '<strong>Cuidado:</strong> diante das formas coléricas, lembre que são as mesmas deidades pacíficas.',
            },
            {
                'icon': 'compass',
                'title': 'Instruções do 3º Bardo',
                'body': 'Na reentrada: <strong>reconheça o período, não lute para voltar, flutue</strong>. Siga as luzes brilhantes e prazerosas; evite as monótonas e a escuridão; não entre no antigo ego por medo.',
                'tip': '<strong>Instrução:</strong> não exerça poderes sobrenormais por interesse próprio.',
            },
            {
                'icon': 'scales',
                'title': 'Julgamento e Visões Sexuais',
                'body': 'No julgamento, <strong>o juiz é sua consciência e o espelho é sua memória — não minta</strong>. Nas visões sexuais, aparte-se da ação e do apego, confiando na unidade da vida.',
                'tip': '<strong>Lembre-se:</strong> "sua personalidade não pode ser ferida" — encare a verdade sem identificar-se com os papéis.',
            },
            {
                'icon': 'moon',
                'title': 'A Escolha Pós-Sessão',
                'body': 'O fechamento da travessia: <strong>vá devagar, naturalmente, aproveitando cada segundo</strong>. Não corra, não se apegue aos antigos scripts — cada momento pode ser uma descoberta nova.',
                'tip': '<strong>Instrução:</strong> "vá na boa, devagar, naturalmente" — a reentrada bem feita é metade da sabedoria da viagem.',
            },
        ],
        'lessons': [
            'No 1º Bardo: não se apegue a nada, por mais glorioso — confie e flua.',
            'A frase-chave do 2º Bardo: tudo vem de dentro de você.',
            'Há uma instrução simples para cada uma das 7 visões.',
            'Na reentrada: flutue, siga a luz clara e escolha a personalidade com calma.',
        ],
    },
}
