# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'O Homem Mais Rico da Babilônia' (George S. Clason).
Frameworks: pague-se primeiro (10%), as Sete Curas para uma bolsa vazia, as Cinco Leis do Ouro,
a deusa da boa sorte (a sorte favorece quem age), proteger o tesouro, casa como investimento,
renda futura, aumentar a capacidade de ganhar, e o plano de Dabasir para sair das dívidas (70/20/10).
Base: síntese dos frameworks amplamente documentados — não reproduz o texto."""

BOOK = {
 "title": "O Homem Mais Rico da Babilônia",
 "author": "George S. Clason",
 "header_light": "O HOMEM MAIS RICO",
 "header_bold": "DA BABILÔNIA",
 "subtitle": "VISÃO GERAL · UMA PARTE DE TUDO QUE GANHAS É TUA PARA GUARDAR",
 "intro": "Sob o sol da antiga Babilônia, um carroceiro pergunta ao homem mais rico da cidade por que tanto trabalho rendeu tão pouco ouro. A resposta não exige nascer rico nem ganhar muito — cabe numa só sentença: <strong>\"uma parte de tudo que você ganha é sua para guardar\"</strong>. O que enche o cofre não é o tamanho do salário, mas o hábito teimoso de pagar a si mesmo primeiro, gastar menos do que se ganha e nunca arriscar o que não se pode perder. Clason não ensina em fórmulas; ensina em fábulas — e a fábula gruda onde a planilha escorrega.",
 "description": "Nas parábolas de Arkad, Bansir e Dabasir, as leis da prosperidade aparecem despidas de toda complicação moderna: guarde um décimo antes de tocar no resto, faça o ouro guardado gerar mais ouro, distinga o que você quer do que você precisa, proteja o principal acima do lucro, e saiba que a sorte só sorri a quem já estendeu a mão. Endividado, Dabasir mostra a saída — 70% para viver, 20% para os credores, 10% para si. A riqueza, conclui o livro, é filha de hábitos pequenos e repetidos, não de salário grande nem de golpe de sorte.",
 "tags": ["Finanças", "Poupança", "Riqueza"],
 "progress": "9 Capítulos",
 "cover": "assets/homem-mais-rico-babilonia-cover.png",
 "overview_cards": [
   {"ic":"key","t":"Pague a Si Mesmo Primeiro","b":"A regra que sustenta todas as outras cabe numa frase: <strong>\"uma parte de tudo que você ganha é sua para guardar\"</strong>. Você trabalha o mês inteiro para o senhorio, o açougueiro e o sandaleiro; antes de qualquer um deles, separe <strong>ao menos um décimo</strong> e trate-o como dívida sagrada consigo mesmo. O cofre não se enche do que sobra — enche-se do que você retém antes que o resto escorra.","tip":"<strong>Como aplicar:</strong> tire os 10% no instante em que o dinheiro entra, não no fim do mês. O que não se vê não faz falta.","wide":True},
   {"ic":"steps","t":"As Sete Curas para uma Bolsa Vazia","b":"Arkad não dá um conselho, dá uma escada de sete degraus: <strong>engordar a bolsa · domar o gasto · pôr o ouro a trabalhar · blindar o principal · fazer da casa um bem · garantir a renda da velhice · aumentar a própria capacidade de ganhar</strong>. Nenhum degrau se pula; cada um só firma o pé porque o de baixo aguenta.","tip":"<strong>Regra:</strong> poupar vem antes de investir, e proteger vem antes de render. Quem inverte a ordem cai."},
   {"ic":"spark","t":"A Sorte Sorri a Quem Age","b":"A deusa da boa sorte passa pela porta de todos, mas <strong>não espera o indeciso terminar de pensar</strong>. Ela não mora na mesa de jogo: mora na oportunidade que chega vestida de trabalho e é agarrada no ato. O que os homens chamam de azar costuma ser apenas a chance que ficou para amanhã.","tip":"<strong>Modelo mental:</strong> quando uma boa oportunidade aparecer e as contas fecharem, decida no mesmo dia. A demora é a forma educada de dizer não."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-homem-que-desejava-ouro","sub":"CAPÍTULO 1: O Homem que Desejava Ouro",
  "intro":"Bansir, o melhor carroceiro da Babilônia, senta-se à sombra do muro com a bolsa vazia. Ao lado, Kobbi, o músico, está igualmente liso. Os dois fabricaram a vida inteira para os outros — carroças e canções — e nada guardaram para si. Daí a pergunta que abre o livro e atravessa todas as páginas: por que homens que trabalham tanto possuem tão pouco, enquanto o ouro se acumula nas mãos de poucos? A resposta, eles descobrirão, não está no braço, está no que ninguém lhes ensinou.",
  "cards":[
      {"ic":"gap","t":"Trabalho Não É a Mesma Coisa que Riqueza","emph":"Riqueza","b":"Bansir construiu as melhores carroças da cidade e morre pobre do mesmo jeito. <strong>O suor enche o dia, mas não enche o cofre</strong> — porque quem trabalha sem guardar apenas passa o ouro adiante, das próprias mãos para as de quem soube retê-lo. A diferença entre o rico e o pobre raramente é o esforço; quase sempre é o que cada um faz com a moeda depois que ela chega.","tip":"<strong>Como aplicar:</strong> antes de buscar ganhar mais, aprenda a guardar parte do que já ganha. Salário maior sem hábito de poupar só engorda contas maiores."},
      {"ic":"bulb","t":"A Inquietação Vem Antes da Mudança","emph":"Inquietação","b":"Enquanto o pobre se conforma com a bolsa vazia, ela continuará vazia. <strong>O primeiro passo para fora da pobreza é recusar-se a aceitá-la como destino.</strong> Bansir e Kobbi só começam a mudar no instante em que param de lamentar a sorte e admitem, em voz alta, que algo no próprio modo de viver precisa mudar.","tip":"<strong>Modelo mental:</strong> não desperdice o desconforto. A insatisfação honesta é o sino que chama à ação; ignorá-lo é voltar a dormir."},
      {"ic":"target","t":"Procure Quem Já Tem o Que Você Quer","emph":"Quem Já Tem","b":"De que adianta perguntar o caminho da fartura a quem também passa fome? Os dois amigos param de comparar misérias entre si e vão bater à porta de Arkad, o mais rico de todos. <strong>Conselho de dinheiro só vale quando vem de quem provou saber lidar com ele.</strong>","tip":"<strong>Sinal de alerta:</strong> aceitar receita de riqueza de quem vive endividado é pedir o mapa a quem nunca chegou."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Trabalhar muito não enriquece ninguém: sem o hábito de guardar, o ouro só passa pelas mãos.","Admitir a própria pobreza, sem se conformar com ela, é o primeiro degrau para sair dela.","Busque conselho com quem já enriqueceu — não com quem apenas trabalha tanto quanto você."]},

 {"slug":"ch02-homem-mais-rico","sub":"CAPÍTULO 2: O Homem Mais Rico da Babilônia",
  "intro":"Arkad, o homem mais rico da Babilônia, recebe os velhos amigos de infância e lhes confessa que nasceu tão pobre quanto eles. A virada veio de uma frase ensinada pelo agiota Algamish — e de uma lição que Arkad aprendeu da pior maneira: perdeu o primeiro ouro seguindo o conselho do homem errado. A fortuna, descobriu ele, não premia o talento nem a sorte, premia o método.",
  "cards":[
      {"ic":"key","t":"Pague a Si Mesmo Primeiro","emph":"Pague a Si","b":"Não é privação, é justiça. Você trabalha o mês inteiro para todo mundo; antes de o ouro chegar ao açougueiro e ao senhorio, <strong>retenha um décimo dele como pagamento a quem mais merece — você</strong>. Viver com os outros nove décimos é tão possível quanto viver com o salário inteiro; a diferença é que, agora, uma parte fica.","tip":"<strong>Prática:</strong> separe a décima parte no dia do pagamento, não no fim do mês. O bolso se acostuma ao que sobra com a mesma facilidade com que se acostumaria ao todo."},
      {"ic":"leaf","t":"Ponha o Ouro a Trabalhar","emph":"Trabalhar","b":"Moeda parada no cofre é serva preguiçosa. <strong>Cada peça de ouro deve render outras, e os filhos dela devem render também</strong> — é assim que um décimo guardado vira, com paciência, um rebanho. A riqueza de Arkad não veio de poupar muito de uma vez, e sim de nunca gastar os juros que a poupança gerava.","tip":"<strong>Modelo mental:</strong> os rendimentos não são para torrar. Mande-os de volta ao trabalho, e o seu ouro contratará mais ouro sem que você levante a mão."},
      {"ic":"mask","t":"Conselho Só de Quem Entende do Ofício","emph":"Quem Entende","b":"Arkad confiou suas primeiras economias a um pedreiro que prometeu comprar joias — e o pedreiro voltou com cacos de vidro. <strong>Pedir conselho de dinheiro a quem nada entende de dinheiro é pedir receita de pão ao ferreiro.</strong> O ouro perdoa muita coisa, menos ser entregue a mãos que não sabem o que fazem.","tip":"<strong>Sinal de alerta:</strong> recuse a dica brilhante de quem nunca guardou ouro. A boa intenção do amigo não substitui a competência do entendido.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["Guarde no mínimo um décimo de tudo o que ganha, antes de gastar qualquer parte do resto.","Faça o ouro guardado render — e reinvista os juros, em vez de consumi-los.","Tome conselho de dinheiro apenas com quem é experiente naquilo que aconselha."]},

 {"slug":"ch03-sete-curas","sub":"CAPÍTULO 3: As Sete Curas para uma Bolsa Vazia",
  "intro":"O rei Sargon vê o ouro da Babilônia escorrer para as mãos de poucos e o povo empobrecer. Chama Arkad e pede que ensine a cidade inteira a prosperar. Nasce então o curso das Sete Curas — o programa mais completo do livro, que vai do simples hábito de guardar até a arte de aumentar a própria capacidade de ganhar.",
  "cards":[
      {"ic":"steps","t":"As Sete Curas, Uma a Uma","emph":"Sete Curas","b":"O caminho não tem mistério, tem ordem: <strong>engorde a bolsa, controle o gasto, ponha o ouro a render, proteja o principal, torne a casa um bem, garanta a renda da velhice e amplie a sua capacidade de ganhar</strong>. São sete remédios para o mesmo mal — a bolsa vazia —, e cada um prepara o terreno do seguinte.","tip":"<strong>Como aplicar:</strong> não pule degraus. Ninguém investe bem enquanto o gasto descontrolado ainda fura o fundo da bolsa."},
      {"ic":"fork","t":"Nem Todo Desejo É Necessidade","emph":"Desejo","b":"Quem trata cada vontade como urgência nunca terá o bastante, por mais que ganhe. <strong>Os gastos crescem para ocupar tudo o que entra, vestindo o supérfluo com a roupa do indispensável.</strong> A segunda cura é simples e dura: viver com noventa por cento, e cortar o resto sem dó.","tip":"<strong>Regra:</strong> antes de comprar, separe o que você precisa do que você apenas quer. Se um desejo ameaça o seu décimo guardado, ele espera."},
      {"ic":"scale","t":"Proteja o Principal Antes do Lucro","emph":"Principal","b":"A promessa de ganho rápido cega o poupador e o faz jogar na vala anos de economia. <strong>A primeira regra de quem investe não é multiplicar depressa, é não perder o que já tem.</strong> Juro alto nenhum repõe a paz de um cofre esvaziado de uma vez.","tip":"<strong>Sinal de alerta:</strong> toda promessa de lucro grande e fácil que arrisca o principal é, quase sempre, o anúncio antecipado de um prejuízo."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["As Sete Curas formam uma sequência: poupar, controlar, multiplicar, proteger, ter casa, garantir renda futura e ganhar mais.","Separe desejos de necessidades — o gasto incha até engolir toda a renda, se você deixar.","Proteja o principal: a segurança do que se tem vem antes da busca por retorno."]},

 {"slug":"ch04-deusa-da-boa-sorte","sub":"CAPÍTULO 4: Conheça a Deusa da Boa Sorte",
  "intro":"No Templo do Aprendizado, os homens da Babilônia discutem como atrair a deusa da boa sorte. Uns juram que ela mora nas mesas de aposta. Arkad ouve e discorda: a sorte que enriquece não cai do céu sobre o jogador — ela chega disfarçada de oportunidade, e quem mais a afugenta é o homem que adia.",
  "cards":[
      {"ic":"spark","t":"A Sorte Mora na Oportunidade, Não na Aposta","emph":"Oportunidade","b":"Quem busca a deusa na mesa de jogo está olhando para o lugar errado. <strong>A boa sorte chega vestida de oportunidade — um bom negócio, uma terra barata, um trabalho que poucos quiseram — e fica para quem age.</strong> Não há carruagem mágica; há a chance que passa, e a mão que se estende a tempo.","tip":"<strong>Como aplicar:</strong> quando as contas fecharem a seu favor, decida. A deusa não espera o indeciso terminar de ponderar."},
      {"ic":"clock","t":"O Espírito da Procrastinação","emph":"Procrastinação","b":"Há em todo homem uma voz que sussurra \"amanhã eu vejo\" — e essa voz já custou mais fortunas que o azar. <strong>Adiar a decisão diante de uma boa chance é entregá-la, de presente, a quem teve a coragem de decidir hoje.</strong> A oportunidade raramente bate duas vezes na mesma porta.","tip":"<strong>Cuidado:</strong> esperar a \"hora perfeita\" é, quase sempre, a maneira educada de dizer não a si mesmo."},
      {"ic":"target","t":"Sorte É Preparo Encontrando a Chance","emph":"Preparo","b":"O homem de sorte costuma ser, de perto, o homem preparado. <strong>De nada serve a oportunidade dourada se a bolsa está vazia e a cabeça, despreparada.</strong> A chance favorece quem já poupou, já estudou e já está pronto para agir no instante em que ela aparece.","tip":"<strong>Modelo mental:</strong> trate a poupança e o aprendizado como o portão que se abre quando a oportunidade bate. Sem eles, ela passa direto."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["A boa sorte favorece quem age sobre oportunidades reais — não quem espera o acaso na mesa de jogo.","O hábito de adiar decisões é o que mais afasta a boa sorte.","Sorte é oportunidade encontrando alguém preparado: poupado, informado e pronto a decidir."]},

 {"slug":"ch05-cinco-leis-do-ouro","sub":"CAPÍTULO 5: As Cinco Leis do Ouro",
  "intro":"Antes de morrer, Arkad entrega ao filho Nomasir um saco de ouro e uma tábua de argila com as Cinco Leis. O moço logo perde o ouro por inexperiência — mas guarda as leis, e com elas reconstrói tudo. A lição vale por toda a vida: conhecer as regras do ouro vale mais do que herdar o ouro.",
  "cards":[
      {"ic":"layers","t":"As Cinco Leis do Ouro","emph":"Cinco Leis","b":"São cinco e cabem na palma: o ouro <strong>vem</strong> a quem guarda um décimo; <strong>trabalha</strong> para quem o emprega com sabedoria; <strong>fica</strong> com quem o protege com conselho prudente; <strong>foge</strong> de quem o aplica no que não entende; e <strong>some de vez</strong> de quem corre atrás de ganhos impossíveis. Quem as respeita, o ouro serve; quem as despreza, o ouro abandona.","tip":"<strong>Como aplicar:</strong> antes de cada decisão com dinheiro, passe-a pelas cinco leis como por um crivo. A que falhar em qualquer uma, recuse."},
      {"ic":"scale","t":"O Ouro Foge de Quem Não o Respeita","emph":"Foge","b":"A moeda escorre das mãos do imprudente para as mãos serenas de quem entende a cadência lenta dos juros. <strong>Ouro aplicado sem conhecimento já está, na prática, perdido</strong> — só falta descobrir para quem. O mercado não pune a má sorte; pune a pressa e a ignorância.","tip":"<strong>Sinal de alerta:</strong> entusiasmo sem entendimento é o caminho mais curto para transferir o seu ouro a quem sabe mais do que você."},
      {"ic":"shield","t":"Ouça o Conselho de Quem Já Lida com Ouro","emph":"Conselho","b":"As leis do ouro não se dobram a vontades nem a esperanças. <strong>Tentar contrariá-las sem ouvir os experientes é colecionar prejuízos.</strong> O conselho de quem já guardou e multiplicou ouro protege a sua bolsa de delírios que custariam anos de trabalho.","tip":"<strong>Para refletir:</strong> não ponha suor e patrimônio num negócio cujas regras você ainda não domina. Pergunte primeiro a quem domina."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Conhecer as leis do ouro vale mais do que herdar ouro: as regras se levam para qualquer lugar.","Invista apenas no que você entende, e com o conselho de quem é competente no assunto.","Desconfie de lucros altos demais — a ganância é exatamente o que faz o ouro fugir."]},

 {"slug":"ch06-emprestador-de-ouro","sub":"CAPÍTULO 6: O Emprestador de Ouro da Babilônia",
  "intro":"Rodan, o fabricante de lanças, ganha do rei cinquenta moedas de ouro e não sabe guardá-las — a irmã já lhe pede o dinheiro para um negócio do cunhado. Procura Mathon, o emprestador, e aprende a regra mais antiga de quem confia ouro a outrem: antes de pensar no lucro, garanta a volta do principal.",
  "cards":[
      {"ic":"mask","t":"Empreste com Garantia, Não com o Coração","emph":"Garantia","b":"Emprestar por dó, sem pedir nada em troca, é afundar junto com quem não sabe pagar. <strong>Quem exige uma garantia concreta — uma joia, uma terra, um bem — poupa-se das noites de desculpas e promessas vazias.</strong> A penhora não ofende o amigo honesto; protege os dois da vergonha de uma dívida que não volta.","tip":"<strong>Regra:</strong> promessa bonita sem lastro vale fumaça. Peça garantia mesmo a quem você ama — sobretudo a quem você ama."},
      {"ic":"fork","t":"Ajudar Não É Carregar a Dívida do Outro","emph":"Ajudar","b":"Tirar o pão da própria mesa para tapar o buraco de quem foi imprudente é trocar a sua segurança pela ruína dele. <strong>Não assuma como sua a dívida irresponsável de ninguém, por mais nobre que pareça o gesto.</strong> O resgate mal pensado afunda dois barcos em vez de salvar um.","tip":"<strong>Modelo mental:</strong> ajude o próximo até onde o seu conforto permite — nunca além da base da sua própria segurança."},
      {"ic":"eye","t":"Olhe a Capacidade Real de Pagar","emph":"Capacidade","b":"Por trás de todo grande plano há um homem; pergunte se esse homem já provou que sabe entregar. <strong>Antes do entusiasmo do negócio, pese a capacidade concreta do devedor de devolver o que tomou.</strong> Sonho bonito sem competência por baixo é o caminho mais curto para perder o ouro emprestado.","tip":"<strong>Para refletir:</strong> peça histórico de feitos, não juras de futuro. O brilho exagerado nos olhos costuma esconder um plano oco."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Antes de mirar o lucro, assegure a segurança e o retorno do principal emprestado.","Emprestar a amigos sem garantia costuma custar duas coisas: o ouro e a amizade.","Avalie a capacidade real de quem pede — e ouça quem lida com dinheiro e risco de ofício."]},

 {"slug":"ch07-muralhas-da-babilonia","sub":"CAPÍTULO 7: As Muralhas da Babilônia",
  "intro":"O exército assírio cerca a Babilônia, mas a cidade resiste: suas muralhas são altas demais para serem tomadas. A parábola é curta e a moral, clara — assim como a cidade só dorme em paz porque ergueu seus muros antes do cerco, toda pessoa precisa de uma reserva pronta antes que a desgraça chegue.",
  "cards":[
      {"ic":"shield","t":"Toda Cidade Precisa de Muralha","emph":"Muralha","b":"A Babilônia comerciava em paz porque, lá fora, muros firmes seguravam o inimigo. <strong>Confiar que a bonança vai durar para sempre é viver de portões abertos.</strong> Guardar uma reserva contra o dia mau não é medo exagerado: é a precaução básica de quem sabe que o cerco, mais cedo ou mais tarde, chega.","tip":"<strong>Regra:</strong> monte um fundo de emergência intocável antes de qualquer luxo. A vida cobra pedágios sem aviso."},
      {"ic":"target","t":"Proteção Antes da Expansão","emph":"Proteção","b":"O objetivo do dinheiro não é só crescer depressa, é não ruir no primeiro abalo. <strong>Casa de lona voa no vendaval; só o que tem alicerce firme permanece de pé.</strong> Antes de sonhar com grandes ganhos, assente a base que aguenta os tropeços da vida e da economia.","tip":"<strong>Como aplicar:</strong> tenha metas ambiciosas, mas reserve sempre uma fatia segura e disponível para o dia em que tudo der errado."},
      {"ic":"key","t":"O Único Escudo Certo É o Seu","emph":"Escudo","b":"Quando a desgraça bate, as promessas de socorro dos outros costumam evaporar. <strong>Aplausos e solidariedade não pagam contas; o que pagará é o ouro que você guardou em silêncio enquanto havia tempo.</strong> A reserva discreta e constante é o verdadeiro muro entre você e a miséria.","tip":"<strong>Modelo mental:</strong> trate a sua reserva como a guarda que nunca dorme — ela vela por você justamente nas noites de tempestade."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["Toda pessoa precisa de proteção financeira erguida antes de o imprevisto chegar.","Reserva de emergência e seguro são as muralhas da vida — defesa antes de conforto.","O cerco (a crise) chega para todos; só permanece de pé quem se preparou a tempo."]},

 {"slug":"ch08-mercador-de-camelos","sub":"CAPÍTULO 8: O Mercador de Camelos da Babilônia",
  "intro":"Dabasir caiu tão fundo nas dívidas que virou escravo. Conta agora como se reergueu — e a parábola entrega o método mais prático do livro: o plano que tira um endividado da lama e o devolve livre e próspero. Tudo começa pela alma de um homem livre; o resto é um plano de números, simples e teimoso.",
  "cards":[
      {"ic":"steps","t":"Primeiro a Alma do Homem Livre","emph":"Alma","b":"Antes de qualquer cálculo, Dabasir teve de decidir, lá no fundo, que merecia ser livre de novo. <strong>Enquanto o devedor se vê como vítima, ele continua acorrentado por dentro, mesmo sem grilhões.</strong> A reviravolta não nasce do bolso, nasce da recusa em aceitar a própria ruína como sentença definitiva.","tip":"<strong>Como aplicar:</strong> pare de explicar a dívida com desculpas. Onde há a determinação de um homem livre, sempre há um caminho."},
      {"ic":"sword","t":"O Plano 70/20/10","emph":"70/20/10","b":"Decidida a alma, o método é claro e cabe em três fatias: <strong>setenta por cento para viver, vinte por cento para pagar os credores e dez por cento para guardar para si</strong>. As dívidas são rateadas entre todos, na proporção de cada uma, e pagas mês a mês sem falta. Você vive, quita o passado e ainda começa a construir o futuro — ao mesmo tempo.","tip":"<strong>Regra:</strong> não espere ficar livre das dívidas para começar a poupar. Os dez por cento entram desde o primeiro mês — é a semente que prova que a vida está virando."},
      {"ic":"mountain","t":"Encare Cada Credor de Frente","emph":"Encare","b":"Fugir do cobrador só amarra mais apertado o nó da vergonha. Dabasir fez o contrário: procurou cada credor, mostrou o plano e pagou, parcela por parcela, com a cara limpa. <strong>Honrar a dívida, devagar mas sem falhar, devolve ao devedor algo que vale mais que o ouro — o respeito por si mesmo.</strong>","tip":"<strong>Sinal de alerta:</strong> esconder-se dos credores não apaga a dívida; apenas adia o acerto e corrói por dentro quem se esconde.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Aplique o plano de Dabasir: 70% para viver, 20% para pagar dívidas, 10% para guardar.","A decisão de quitar — a alma de um homem livre — vem antes de qualquer método.","Encare e honre cada credor: fugir só agrava a dívida e a vergonha."]},

 {"slug":"ch09-tabuas-de-argila-e-trabalho","sub":"CAPÍTULO 9: As Tábuas de Argila e a Sorte Maior",
  "intro":"As tábuas de argila de Dabasir, desenterradas e traduzidas no presente, provam que o plano funciona ainda hoje: um arqueólogo endividado o segue e quita as próprias contas. E a história de Sharru Nada, que de escravo subiu a mercador, fecha o livro com a maior das lições — o trabalho é o melhor amigo que o homem pode ter.",
  "cards":[
      {"ic":"book","t":"Os Princípios Não Envelhecem","emph":"Não Envelhecem","b":"O mais espantoso nas tábuas antigas não é a idade delas, é que continuam certas. <strong>A mesma cartilha que tirou um homem da escravidão na Babilônia tira hoje um endividado do aperto, sob outro céu e outra moeda.</strong> As regras do ouro são velhas como o tempo — e justamente por isso, confiáveis.","tip":"<strong>Como aplicar:</strong> desconfie de atalhos que prometem driblar o básico. Guardar um décimo e quitar as dívidas não saiu de moda, e não vai sair."},
      {"ic":"scale","t":"O Trabalho É o Melhor Amigo do Homem","emph":"Trabalho","b":"Sharru Nada, vendido como escravo, não se entregou: trabalhou tão bem que conquistou a liberdade e, depois, a fortuna. <strong>O trabalho bem-feito não é castigo; é o aliado que abre portas, atrai bons amigos e sustenta toda riqueza que dura.</strong> Quem despreza o esforço acaba escravo de outra coisa qualquer.","tip":"<strong>Modelo mental:</strong> trate o trabalho como amigo, não como inimigo a evitar. Entregue sempre um pouco mais do que pediram — é assim que se sobe."},
      {"ic":"clock","t":"A Maior Renda Vem de Você Mesmo","emph":"De Você","b":"A sétima cura coroa todas: aumente a própria capacidade de ganhar. <strong>Aperfeiçoar o ofício, aprender mais e fazer melhor é a fonte de renda que ninguém pode tirar de você.</strong> Antes de buscar onde aplicar o ouro, vale investir em quem o ganha — pois é dele que tudo o mais começa.","tip":"<strong>Para refletir:</strong> a constância sem brilho é que constrói. Um pouco melhor a cada dia, sem pressa e sem parar, vence o golpe de sorte que nunca vem."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["O trabalho bem-feito é o melhor amigo do homem e a base de toda riqueza duradoura.","Os princípios da Babilônia valem tanto no passado quanto hoje: regras velhas, porque verdadeiras.","Aperfeiçoar o próprio ofício aumenta a capacidade de ganhar — a sétima e mais alta cura."]},
]
