# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'A Hora da Estrela' (Clarice Lispector)."""

BOOK = {
  "title": "A Hora da Estrela",
  "author": "Clarice Lispector",
  "header_light": "A HORA",
  "header_bold": "DA ESTRELA",
  "subtitle": "VISÃO GERAL · A QUEM NUNCA EXISTIU, A MORTE COMO ESTREIA",
  "intro": "Há uma moça que ninguém vê. Macabéa — datilógrafa de Alagoas perdida no Rio, magra, sem queixo e quase sem desejo — não sabe que existe, como o cão não sabe que é cão. Para contá-la, Clarice inventa um homem, Rodrigo S.M., que escreve aos solavancos, culpado de falar por uma pobre que não é ele. O <em>como</em> se conta é a história. E só quando a vida a atropela é que essa moça, enfim, brilha: a estrela acende no exato instante em que se apaga. Último livro de Clarice Lispector, 1977.",
  "description": "Leitura de 'A Hora da Estrela' (Clarice Lispector, 1977): a metalinguagem e o narrador-máscara Rodrigo S.M., a anti-heroína invisível Macabéa, a pobreza como morte em vida, os limites da palavra e o silêncio, o instante-já e a epifania que não consola, a falsa promessa de Madame Carlota e a morte como o único momento em que existir e ser coincidem.",
  "tags": ["Literatura Brasileira", "Clarice Lispector", "Análise Literária"],
  "progress": "8 Capítulos",
  "cover": "assets/hora-da-estrela-cover.png",
  "overview_cards": [
    {"ic":"layers","t":"Três Vozes, Uma Dentro da Outra","b":"<strong>Clarice imagina Rodrigo S.M.; Rodrigo imagina Macabéa.</strong> A autora veste uma máscara de homem para confessar o que a incomoda: que escrever sobre um pobre, de fora, é quase sempre traí-lo. Não junte as três numa só — a distância entre elas é o assunto do livro.","tip":"<strong>Como ler:</strong> cada vez que o narrador trava e diz que não sabe contar, ele não falhou — ele está contando. A hesitação é o conteúdo.","wide":True},
    {"ic":"spark","t":"A Forma é o Fundo","b":"Aqui não se pergunta primeiro <em>o que acontece</em>, e sim <em>quem conta e por que dói contar</em>. A frase que se interrompe, o '...sim' que abre o livro, os treze títulos, a dedicatória que se assina sozinha — nada é enfeite. A maneira de dizer <strong>é</strong> a coisa dita.","tip":"<strong>Modelo mental:</strong> trate a sintaxe truncada como respiração de quem está sem ar. A pontuação, em Clarice, pensa junto com o leitor."},
    {"ic":"eye","t":"Tudo Que Brilha Mata","b":"Estrela, ouro, cabelo loiro, o Mercedes amarelo: na obra, o que reluz não salva — anuncia a queda. E a esperança, sentimento que Macabéa tem uma única vez na vida, é justamente o gatilho que a leva ao chão. <strong>O brilho não é promessa: é aviso.</strong>","tip":"<strong>Sinal de alerta:</strong> sempre que algo luminoso prometer um futuro melhor, prepare-se para a ironia — em Clarice, a luz vem de frente, como um farol.","warn":True},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-rodrigo-metalinguagem",
    "sub": "CAPÍTULO 1: Rodrigo S.M. e a Metalinguagem",
    "intro": "Antes de existir Macabéa, existe a mão que vai escrevê-la. Clarice inventa Rodrigo S.M. — um escritor que se ouve duvidar, recomeça, pede desculpa e confessa que mente — para encenar a única pergunta honesta de quem escreve sobre a miséria: com que direito eu, que como todo dia, falo pela boca de quem tem fome? O ato de narrar deixa de ser meio e vira o próprio tema.",
    "cards": [
      {"ic":"bubble","t":"A Culpa de Quem Conta","emph":"Culpada","b":"Rodrigo escreve com remorso. Ele sabe que está confortável — sentado, alimentado, dono da pena — enquanto inventa uma criatura que passa fome de verdade. <strong>Toda a tortura do narrador nasce de uma suspeita que ele não consegue calar: contar a dor do outro pode ser, no fundo, um modo elegante de aproveitar-se dela.</strong>","tip":"<strong>Como ler:</strong> não pule as queixas do narrador como se fossem rodeio. Cada hesitação é uma confissão — a de que falar pelo pobre, sem ele, já é uma pequena violência.","warn":True},
      {"ic":"mask","t":"A Máscara de Homem","emph":"Máscara","b":"Clarice, mulher, escolhe um narrador homem. Não por capricho: o disfarce mede a distância. <strong>Rodrigo é a prova encarnada de que entre quem escreve e Macabéa há um abismo — de classe, de corpo, de mundo — que nenhuma boa intenção atravessa de graça.</strong> A máscara não esconde a autora; denuncia o quanto ela está longe da moça.","tip":"<strong>Modelo mental:</strong> desconfie da literatura que se comove com a pobreza de longe. A piedade limpa, vinda de mãos que nunca lavaram chão, costuma servir mais a quem sente do que a quem padece."},
      {"ic":"triangle","t":"O Narrador Que Se Desmancha","emph":"Narrador","b":"Rodrigo não posa de dono da verdade — faz o contrário: admite em voz alta que não dá conta, que talvez esteja errado, que sua frase trai a moça. <strong>Em vez de fingir autoridade, ele exibe a própria impotência, e é essa honestidade desarmada que torna a história possível.</strong> Só quem reconhece que não sabe contar tem o direito de tentar.","tip":"<strong>Sinal de alerta:</strong> o narrador seguro de si, que descreve o miserável com mão firme e bonita, mente. O verdadeiro respeito pela dor alheia treme — e, às vezes, prefere o silêncio à frase pronta."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["Em A Hora da Estrela, a forma é o fundo: o modo de contar é a própria coisa contada.", "O narrador-máscara encena o problema ético de escrever sobre a pobreza de fora dela.", "A metalinguagem não é exibição: é o coração pulsante da obra — o livro pensando sobre si."],
  },
  {
    "slug": "ch02-macabea-invisivel",
    "sub": "CAPÍTULO 2: Macabéa, a Anti-Heroína Invisível",
    "intro": "Macabéa é feita de faltas. Órfã, criada na dureza pela tia, alagoana à deriva no Rio, datilógrafa que mal escreve, magra e sem viço — e, o que mais espanta, sem nem desejar coisa diferente. Ela não sofre da própria miséria porque nunca soube que havia outra vida possível. É uma anti-heroína no sentido exato: definida pelo que não tem.",
    "cards": [
      {"ic":"person","t":"A Moça Que Não Sabe Que Existe","emph":"Excluída","b":"Macabéa atravessa o mundo sem deixar marca: pede desculpa por ocupar espaço, encolhe-se, some. <strong>Ela não sabe que existe — assim como um cão não sabe que é cão — e essa inconsciência é a sua pobreza mais funda, mais cruel que a fome: a miséria que rouba até a noção de estar viva.</strong> Não há nela revolta nem grandeza; há uma presença que mal se nota.","tip":"<strong>Regra:</strong> não procure nela coragem oculta nem fúria de heroína. Macabéa não tem fundo secreto a revelar — e é exatamente disso, da existência rasa de quem nunca foi ensinada a querer, que Clarice quer falar."},
      {"ic":"leaf","t":"As Migalhas de Alegria","emph":"Alegrias","b":"A felicidade de Macabéa cabe num cafezinho, num gole de Coca-Cola, nas horas certas anunciadas pela Rádio Relógio. <strong>São prazeres tão pequenos que envergonham o leitor — porque medem, sem querer, o tamanho do que ele próprio acha pouco.</strong> Onde alguém vê uma vida miserável, ela vive contentamentos inteiros.","tip":"<strong>Para refletir:</strong> rir da alegria miúda de Macabéa é mais fácil que encarar o que ela mostra: que talvez o seu vasto desejo não venha de necessidade, mas de excesso. A pobreza dela acusa a sua fartura."},
      {"ic":"gap","t":"A Pobreza Sem Revolta","emph":"Pobreza","b":"Macabéa não joga pedra, não grita, não amaldiçoa o mundo que a esmaga — e isso perturba mais do que qualquer grito. <strong>A miséria mais completa não é a que enfurece, e sim a que apaga até a capacidade de se indignar: tirou-lhe a fome de justiça antes de tirar o resto.</strong> Quem nada teve não sente falta — e por isso não se rebela.","tip":"<strong>Pergunta-chave:</strong> o que mais nos alivia, secretamente — que o pobre não nos cobre? Macabéa não bate à nossa porta porque nem sabe que a porta lhe foi negada. Repare em quanto desse alívio mora dentro de você."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["A protagonista é construída por subtração — e a falta nela é proposital, não descuido.", "A 'felicidade' miúda de Macabéa obriga o leitor a encarar a própria condescendência.", "Invisibilidade social não é metáfora aqui: é o modo concreto de existir de Macabéa."],
  },
  {
    "slug": "ch03-pobreza-alteridade",
    "sub": "CAPÍTULO 3: Pobreza, Alteridade e Invisibilidade Social",
    "intro": "Macabéa é o outro absoluto: a retirante pobre que a cidade grande olha sem ver. O livro pega a miséria social e a transforma numa pergunta sobre a própria escrita — como contar a vida de quem a sociedade trata como inexistente, sem rebaixá-la a número de estatística nem a objeto de pena?",
    "cards": [
      {"ic":"mountain","t":"O Abismo Entre os Dois Brasis","emph":"Abismo","b":"De um lado, o mundo que come bem, fala bonito e mora no alto; do outro, Macabéa, varrendo as sobras do dia. <strong>Entre eles não há ponte: é o país partido ao meio, onde uma metade nem desconfia que a outra existe.</strong> Não é distância de ruas — é distância de mundos, e a cidade foi construída para que um lado nunca esbarre no outro.","tip":"<strong>Modelo mental:</strong> repare como a pobreza, no livro, não grita nem sangra à vista. Ela apaga em silêncio, sem manchar a paisagem — e é justamente por não incomodar que ninguém precisa olhar."},
      {"ic":"constellation","t":"A Pena Que Também Fere","emph":"Culpa","b":"Clarice desconfia da própria arte. Ela sabe que chorar pelo pobre do alto de um apartamento confortável pode ser um gesto bonito e covarde ao mesmo tempo. <strong>Descer à lama só para fotografá-la e vender o retrato é um roubo disfarçado de compaixão — e a literatura comovida costuma ser a primeira a cometê-lo.</strong>","tip":"<strong>Sinal de alerta:</strong> o abraço enternecido da literatura de pena traz uma lâmina escondida na manga. Comover-se com a miséria, e parar aí, é consumi-la como espetáculo — e sair de consciência limpa."},
      {"ic":"link","t":"Sem Solidariedade no Fundo do Poço","emph":"Luta","b":"Onde falta tudo, falta também a ternura: Olímpico despreza Macabéa, os colegas a humilham, ninguém estende a mão. <strong>A miséria não une os miseráveis — ela os adestra para se ferirem entre si, fabricando algozes a partir das próprias vítimas.</strong> A escassez extrema corrói até o consolo de não estar só.","tip":"<strong>Para refletir:</strong> não acredite depressa na imagem comovente dos oprimidos abraçados, fortes na união. Onde falta o pão, costuma faltar também o colo — e a solidariedade é, ela mesma, um luxo que a fome não permite."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["A obra é uma meditação sobre como representar o pobre sem traí-lo no caminho.", "A invisibilidade social é uma forma de morte em vida — apaga sem precisar matar.", "A compaixão fácil é parte do problema, não da solução: comover-se de longe pode ser uma forma de consumo."],
  },
  {
    "slug": "ch04-linguagem-silencio-instante",
    "sub": "CAPÍTULO 4: Linguagem, Silêncio e o Instante",
    "intro": "Toda a obra esbarra no limite da palavra. Macabéa quase não tem linguagem — recolhe frases soltas do rádio sem entendê-las. Rodrigo tem palavras demais, e ainda assim falha. Entre os dois abre-se o silêncio, e é dentro dele que Clarice caça o que mais lhe importa: o 'instante', o agora cru, anterior a qualquer sentido.",
    "cards": [
      {"ic":"wave","t":"As Palavras Que Macabéa Não Tem","emph":"Ruído","b":"Macabéa colhe da Rádio Relógio palavras que não compreende — 'efeméride', 'mújique' — e as guarda como pedrinhas bonitas e inúteis. <strong>A linguagem que poderia nomear sua dor nunca chega até ela; sobra o ruído, e o ruído não consola nem explica.</strong> Quem não tem palavra para o que sente fica também sem o direito de pensar a própria vida.","tip":"<strong>Como ler:</strong> cale o saber pronto e os termos elegantes e escute o que existe debaixo deles — o grito mudo de quem padece sem ter como dizer. Há dores que nenhuma frase bonita alcança."},
      {"ic":"spark","t":"O Instante Antes do Sentido","emph":"Agora","b":"Clarice não persegue o enredo: persegue o agora puro, o segundo nu de existir, antes que o pensamento o explique e o estrague. <strong>Para chegar lá, é preciso arrancar do real toda a maquiagem — as palavras consoladoras, as morais de fim de história — e ficar com o instante seco, sem cor e sem desculpa.</strong> A vida verdadeira está no instante, não na frase que o resume.","tip":"<strong>Modelo mental:</strong> aceite o fato nu sem embrulhá-lo em legenda fofa. Qualquer explicação reconfortante já é uma pequena traição do que de fato aconteceu — a verdade do instante dói sem rótulo."},
      {"ic":"eye","t":"A Pontuação Que Respira","emph":"Sintaxe","b":"As frases que se quebram, as reticências, o '...sim' que abre o livro: nada disso é descuido. <strong>A sintaxe de Clarice tropeça de propósito, como quem está sem ar — a pontuação é a respiração ofegante de um pensamento que mal cabe em palavras.</strong> A forma não acompanha o sentido: a forma é o sentido.","tip":"<strong>Regra:</strong> não 'corrija' mentalmente as frases truncadas para deixá-las redondas. Esses pontos fora do lugar são fraturas vivas do texto — alisá-las é apagar exatamente onde a obra está pensando."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["A obra dramatiza o limite da linguagem diante do real — o que mais importa não cabe em palavra.", "O silêncio e o 'instante' são, em Clarice, o lugar onde mora a verdade.", "A forma — sintaxe, pontuação, frase quebrada — é tão significante quanto o enredo."],
  },
  {
    "slug": "ch05-olimpico-gloria-desejo",
    "sub": "CAPÍTULO 5: Olímpico, Glória e o Desejo",
    "intro": "O único 'romance' da obra é um romance às avessas. Macabéa encontra Olímpico — pobre como ela, mas movido a ambição e dureza — e o perde para Glória, a colega de carnes fartas e cor de banha. Aqui o amor não aproxima ninguém: é puro desencontro, dois corpos querendo coisas opostas no mesmo instante.",
    "cards": [
      {"ic":"sword","t":"Nomes Grandes, Vidas Pequenas","emph":"Irônicos","b":"<strong>Olímpico, Glória, 'de Jesus', Madame Carlota</strong>: grandeza nos nomes, miséria nas vidas. Clarice batiza seus pobres com sílabas de deuses e santos para que o abismo entre o nome e a pessoa fira aos olhos. <strong>O nome é a promessa que a vida não cumpre — e ninguém ali é à altura do que se chama.</strong>","tip":"<strong>Como ler:</strong> diante de um nome pomposo na obra, espere o contrário. Quanto mais alto o batismo, mais funda a queda da pessoa que o carrega."},
      {"ic":"pivot","t":"Querer o Outro Como Degrau","emph":"Predação","b":"Olímpico sonha 'ser deputado', 'ficar rico', subir custe o que custar — e Macabéa, que nada acrescenta à subida, vira estorvo. Ele a troca por Glória, que tem mais <strong>carne, comida e contatos</strong>. <strong>Entre os que nada têm, o desejo não acolhe: calcula, e descarta quem não serve de escada.</strong>","tip":"<strong>Modelo mental:</strong> Macabéa só quer existir; Olímpico e Glória querem chegar. Quem só deseja ser não tem como competir com quem deseja ter — e perde sempre."},
      {"ic":"triangle","t":"A Piedade Que Empurra Para o Abismo","emph":"Glória","b":"Glória fica com Olímpico, sente um aguilhão de culpa e, para se aliviar, presenteia Macabéa com a consulta à cartomante. <strong>Quem rouba o namorado é a mesma que, sem querer, gira a chave da tragédia — e o faz justamente ao tentar fazer o bem.</strong> O remorso de Glória é o primeiro empurrão rumo à morte.","tip":"<strong>Sinal de alerta:</strong> repare na ironia clariceana — o gesto de bondade é a sentença. Em A Hora da Estrela, o bem feito a Macabéa costuma ser, no fundo, o seu fim.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["O amor, na obra, é desencontro — e instrumento de ambição, não de afeto.", "Os nomes pomposos ironizam a pequenez das vidas que os carregam.", "Glória, por culpa, é quem aciona o movimento rumo ao desfecho — fazendo o 'bem'."],
  },
  {
    "slug": "ch06-madame-carlota-epifania",
    "sub": "CAPÍTULO 6: Madame Carlota e a Falsa Epifania",
    "intro": "Madame Carlota, a cartomante, é a dobradiça da obra. Pela primeira vez, alguém olha para Macabéa e lhe promete um futuro de luz. A moça sai dali transformada — pela única vez na vida, deseja o amanhã, acredita que tudo vai mudar. E é exatamente essa esperança recém-nascida que a empurra para debaixo das rodas.",
    "cards": [
      {"ic":"bulb","t":"A Esperança Como Veneno","emph":"Armadilha","b":"Madame Carlota anuncia dinheiro, sorte e um noivo estrangeiro e loiro. <strong>A única vez que Macabéa quer o futuro é a véspera de não ter mais nenhum</strong> — e a obra, que desconfia de toda promessa de salvação, faz da esperança o gatilho da queda. Antes, Macabéa estava a salvo dentro do nada; foi o sonho que a expôs.","tip":"<strong>Modelo mental:</strong> leia aqui a velha reviravolta trágica — a promessa que se cumpre ao contrário — encaixada dentro de uma anti-tragédia, onde a heroína nem herói chega a ser."},
      {"ic":"eye","t":"Nós Sabemos; Ela Sorri","emph":"Ironia Trágica","b":"O leitor pressente que a profecia é falsa; Macabéa, não. <strong>Enquanto ela sai radiante, certa de que a vida virou, nós já carregamos o peso do que vem — e essa diferença entre o que sabemos e o que ela ignora aperta a garganta.</strong> A obra nos faz cúmplices de um destino que não podemos avisar.","tip":"<strong>Como ler:</strong> isto é a falsa epifania — a revelação prometida que não chega, ou chega ao contrário. A 'boa nova' de Clarice quase nunca é boa."},
      {"ic":"mask","t":"Charlatã ou Mensageira do Destino?","emph":"Charlatã ou Destino?","b":"Ex-prostituta, devota de Jesus, grotesca e estranhamente generosa, Madame Carlota fica para sempre entre dois sentidos: <strong>vigarista que vende ilusão ou instrumento cego do destino?</strong> A obra não decide — e talvez o mais cruel seja isto: a promessa de 'virar gente' é a única ternura que Macabéa recebe na vida inteira.","tip":"<strong>Sinal de alerta:</strong> a boa nova é a sentença de morte. O único carinho que cabe a Macabéa vem embrulhado na mentira que vai matá-la.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["A esperança prometida é o gatilho da tragédia — Macabéa só corre risco quando passa a querer.", "A reviravolta trágica clássica opera dentro de uma anti-tragédia, sem heroísmo a salvar ninguém.", "Clarice desconfia, por princípio, de toda redenção fácil — e da consolação que a anuncia."],
  },
  {
    "slug": "ch07-hora-da-estrela-morte",
    "sub": "CAPÍTULO 7: A Hora da Estrela — a Morte como Ápice",
    "intro": "Macabéa sai da cartomante cheia de futuro e atravessa a rua olhando o alto, como quem já é outra. Então o futuro chega: um Mercedes amarelo dirigido por um estrangeiro loiro a derruba — a profecia cumprida ao contrário, o noivo prometido transformado em algoz ao volante. Caída no chão, agonizando, ela vive o seu único instante inteiro: a hora em que existir e morrer enfim coincidem.",
    "cards": [
      {"ic":"star","t":"A Estreia Que É Também o Fim","emph":"Protagonismo","b":"Só ao morrer Macabéa vira centro de alguma coisa. <strong>A 'hora da estrela' é o instante em que cada um, como ator, tem enfim a sua cena — e a dela só pôde acontecer na queda.</strong> A vida toda foi um ensaio mudo para esse único minuto em que alguém, por fim, repara que ela está ali.","tip":"<strong>Modelo mental:</strong> a morte aqui não castiga — coroa. É a estreia adiada de quem nunca teve permissão para existir em cena."},
      {"ic":"spark","t":"Existir e Ser, Enfim Juntos","emph":"Existência × Essência","b":"A moça que 'não sabia que existia' só é plenamente quando deixa de ser. <strong>No chão, no último instante, existência e essência tocam-se pela primeira e única vez — a obra concede na morte o que a vida lhe negou inteira.</strong> Ser, para Macabéa, foi um luxo de um segundo só.","tip":"<strong>Como ler:</strong> a 'hora da estrela' é o instante-já supremo de Clarice — a morte como a única epifania que não mente, porque é a única que não promete nada depois."},
      {"ic":"triangle","t":"O Narrador Morre Junto","emph":"Morre com Ela","b":"Rodrigo encerra confessando que ele também vai morrer — e arremata com um inesperado 'é morango', leveza absurda à beira do abismo. <strong>O livro se fecha sobre si mesmo: o narrador inventado para contar Macabéa não sobrevive a ela.</strong> Apagada a moça, apaga-se a mão que a escrevia.","tip":"<strong>Ironia do destino:</strong> o estrangeiro loiro e rico da profecia de fato aparece — só que como assassino ao volante, e não como o noivo que viria salvá-la."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["A morte é o único momento de protagonismo de Macabéa — sua estreia e seu fim na mesma cena.", "A profecia de Madame Carlota se cumpre, sim, mas de forma trágica e invertida.", "Existência e essência só se encontram, para ela, no derradeiro instante."],
  },
  {
    "slug": "ch08-estrutura-simbolos-recursos",
    "sub": "CAPÍTULO 8: Estrutura, Símbolos e Recursos",
    "intro": "A Hora da Estrela começa antes de começar, interrompe-se a cada passo e acaba no exato ponto em que a personagem acaba. A obra é toda feita de costuras à mostra. Entender sua arquitetura — o que vem antes da primeira frase, o que reluz dentro dela, e os três livros que ela é ao mesmo tempo — é ter a chave da casa.",
    "cards": [
      {"ic":"book","t":"O Livro Começa Antes da Página 1","emph":"Paratexto","b":"A dedicatória que se assina '(na verdade Clarice Lispector)', os <strong>treze títulos alternativos</strong> empilhados na abertura, o '...sim' que inaugura tudo no meio de uma frase: nada disso é antessala — é já a obra. <strong>Antes de contar a história, Clarice entrega as chaves dela ao leitor, escondidas à vista.</strong> Pular o começo é entrar sem chave.","tip":"<strong>Como ler:</strong> a própria lista de títulos — entre eles 'A Culpa É Minha' e 'Ela Que Se Arranje' — já resume o argumento e o tom da obra. Leia-a como sinopse cifrada.","wide":True},
      {"ic":"constellation","t":"A Constelação Que Anuncia a Morte","emph":"Brilho Letal","b":"<strong>Estrela</strong> (protagonismo que só vem na morte) · <strong>Mercedes amarelo</strong> (a riqueza que atropela) · <strong>loiro/ouro</strong> (a promessa falsa) · <strong>Rádio Relógio</strong> (o mundo reduzido a ruído) · <strong>capim</strong> (a vida rasteira e humilde). Toda a obra reluz — e cada reluzir é um aviso. <strong>Em Clarice, o brilho não ilumina o caminho: marca onde o fim espera.</strong>","tip":"<strong>Modelo mental:</strong> sempre que algo cintilar na página, antecipe a catástrofe, nunca a salvação. A luz, nesta obra, é a cor do perigo."},
      {"ic":"layers","t":"Três Livros num Só","emph":"Três ao Mesmo Tempo","b":"Romance social, metaficção e poema filosófico: A Hora da Estrela recusa caber numa só prateleira e é <strong>as três coisas ao mesmo tempo</strong>. E não por indecisão — a recusa é o argumento: <strong>nenhuma moldura única dá conta de Macabéa, assim como nenhum rótulo dá conta de uma pessoa.</strong>","tip":"<strong>Cuidado:</strong> espremer a obra num único gênero é repetir, na crítica, o gesto que ela denuncia — reduzir a um rótulo o que era inteiro e indizível.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Em Clarice, o paratexto e a forma não rodeiam o sentido: são parte essencial dele.", "Os símbolos do brilho — estrela, ouro, loiro, Mercedes — anunciam sempre a morte, nunca a salvação.", "A obra é, ao mesmo tempo, social, metaficcional e filosófica — e essa recusa de um só gênero é proposital."],
  },
]
