# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'A Insustentável Leveza do Ser' (Milan Kundera)."""

BOOK = {
 "title": "A Insustentável Leveza do Ser",
 "author": "Milan Kundera",
 "header_light": "INSUSTENTÁVEL",
 "header_bold": "LEVEZA DO SER",
 "subtitle": "VISÃO GERAL · O PESO QUE ESMAGA, A LEVEZA QUE ESVAZIA",
 "intro": "Vivemos uma vez só, e uma vez não conta: o que acontece só uma vez é como se nunca tivesse acontecido. Sem repetição, sem ensaio, sem o termo de comparação que daria às escolhas o seu peso, a vida vira um esboço que jamais virará quadro. E aí está o paradoxo que dá nome ao livro: caberia esperar que o leve fosse fácil de carregar — mas é a leveza, e não o peso, que se revela <em>insustentável</em>. Kundera arma essa balança e pendura nela quatro destinos, na Praga ocupada de 1968. Depois recua, irônico, e deixa a sentença em aberto: nem o peso nem a leveza salvam.",
 "description": "Romance filosófico de Milan Kundera onde a história só começa depois do ensaio. A balança fundadora — leveza × peso — herdada de Parmênides e medida pelo eterno retorno de Nietzsche; 'einmal ist keinmal' (uma vez é nenhuma vez); os seis acasos que viram destino na memória; 'es muss sein!' tomado a Beethoven; o corpo que trai a alma; o kitsch como biombo que esconde a morte e 'ditadura do coração'; a Grande Marcha e, no fim, o sorriso de Karenin. Tomáš, Tereza, Sabina e Franz — quatro hipóteses postas à prova.",
 "tags": ["Literatura", "Filosofia", "Existencialismo"],
 "progress": "9 Capítulos",
 "cover": "assets/insustentavel-leveza-do-ser-cover.png",
 "overview_cards": [
  {"ic":"scale","t":"A Balança Onde Tudo É Pesado","b":"Parmênides dividiu o mundo em pares e premiou um lado: leve, bom; pesado, mau. Kundera mantém a balança e suspende o veredicto. <strong>Tereza e Franz</strong> escolhem o peso — fidelidade, raízes, a gravidade que prende o eu à terra. <strong>Tomáš e Sabina</strong> perseguem a leveza — desprendimento, traição, a vida sem amarras. E a tese cabe num gesto: <strong>o peso esmaga, mas a leveza, levada até o fim, vira o mais insuportável dos vazios</strong>. Nenhum prato é o certo.","tip":"<strong>Para refletir:</strong> onde você busca leveza (compromisso nenhum) e onde aceita o peso (com a conta que vem junto)? O livro não decide por você — só lhe mostra o preço de cada lado.","wide":True},
  {"ic":"spark","t":"Einmal ist Keinmal","b":"'<strong>Uma vez é nenhuma vez.</strong>' O que acontece uma só vez é como se não tivesse acontecido. Não há segunda versão para comparar, nenhum rascunho a corrigir — vivemos o primeiro esboço já passado a limpo. Daí a angústia de Tomáš: ele jamais saberá se devia ter ficado com Tereza, porque <strong>só viverá uma das vidas, sem a outra ao lado para servir de medida</strong>.","tip":"<strong>Modelo mental:</strong> antídoto ao arrependimento. Você não escolheu mal — escolheu sem ensaio, com a informação de uma vida que só acontecia uma vez."},
  {"ic":"mask","t":"O Kitsch — O Biombo Que Esconde a Morte","b":"Kitsch é a recusa de tudo o que, na existência, é inaceitável: a morte, o ridículo, os excrementos, o acaso. Sua fórmula é a <strong>segunda lágrima</strong> — a primeira chora com as crianças na grama; a segunda se comove de estar chorando junto com toda a humanidade. É a 'ditadura do coração': exige consenso, expulsa a dúvida e o indivíduo. Por isso <strong>todo totalitarismo é kitsch</strong> — mas ninguém escapa por inteiro do seu.","tip":"<strong>Teste:</strong> da próxima vez que uma emoção grande o pegar em público, pergunte — está sentindo pelo objeto, ou está se comovendo com a própria comoção? A segunda lágrima é a fronteira do kitsch."},
 ],
}

CHAPTERS = [
 {
  "slug": "ch01-leveza-peso-eterno-retorno",
  "sub": "CAPÍTULO 1: Leveza, Peso e o Eterno Retorno",
  "intro": "As primeiras páginas não contam história nenhuma: são um ensaio. Antes de apresentar uma única pessoa, o narrador-filósofo monta a balança em que tudo, depois, será pesado — e nos avisa, sem disfarce, que pensa em voz alta. Quem entende esta abertura tem a chave de tudo o que vem: o romance não vai narrar um amor, vai pesá-lo.",
  "cards": [
      {"ic":"scale","t":"O Peso Máximo e a Leveza Real","emph":"Peso Máximo","b":"Imagine que cada gesto se repetisse infinitas vezes — o eterno retorno de Nietzsche. Então cada ato carregaria uma carga atroz de responsabilidade: o <strong>peso máximo</strong>. Mas não há retorno. A história humana é leve como uma pena, e <strong>o que só acontece uma vez já está perdoado de antemão</strong> — leve porque sem consequência que volte para cobrar.","tip":"<strong>Para refletir:</strong> Kundera não crê no eterno retorno. Usa-o como régua: o peso máximo, que é só hipótese, serve para medir, por contraste, o quanto a vida real é leve — e por que isso pode ser terrível.","wide":True},
      {"ic":"spark","t":"Einmal ist Keinmal","emph":"Einmal ist Keinmal","b":"'<strong>Uma vez é nenhuma vez.</strong>' O que acontece uma só vez bem poderia não ter acontecido. Vivemos o <strong>primeiro rascunho já passado a limpo</strong>, sem o luxo do ensaio, sem a vida não vivida ao lado para servir de prova. Toda a hesitação de Tomáš nasce daqui: não há como saber qual escolha era a certa quando só se vive uma.","tip":"<strong>Modelo mental:</strong> julgar a própria escolha 'em retrospecto' é trapaça — falta a outra metade da balança. A vida vivida nunca tem a não vivida para se comparar."},
      {"ic":"fork","t":"O Paradoxo do Título","emph":"Paradoxo","b":"O título é um oxímoro de propósito. O que é leve deveria ser fácil de suportar — e é justamente o que não se suporta. A leveza do ser é insuportável porque, <strong>sem peso, nada tem importância</strong>: tudo flutua, indiferente, igual. O peso esmaga; a leveza esvazia. E o romance recusa-se a escolher entre os dois — <strong>encarna a oposição em vez de resolvê-la</strong>.","tip":"<strong>Para refletir:</strong> quando uma decisão 'sem consequência nenhuma' pesou mais do que devia — não apesar de ser leve, mas exatamente por isso?"},
    ],
  "lessons_title": "Lições-Chave do Capítulo 1",
  "lessons": ["O eterno retorno é régua, não crença: serve para medir, por contraste, o quanto a vida real é leve.", "Einmal ist keinmal — o que acontece uma vez é como se nada fosse; não há ensaio para a vida.", "A leveza é insuportável porque, sem peso, nada importa; o livro não resolve a tensão — faz dela a sua matéria."],
 },
 {
  "slug": "ch02-parte1-leveza-e-peso",
  "sub": "CAPÍTULO 2: Parte 1 — Leveza e Peso (Tomáš e Tereza)",
  "intro": "Agora a balança ganha rosto. Tomáš, cirurgião de Praga e colecionador de amantes, vê Tereza entrar em sua vida — não pela porta do destino, mas por uma cadeia improvável de seis pequenos acasos. É o momento em que a filosofia desce do ensaio e vira gente: o homem da leveza encontra a mulher do peso, e a partir daí cada um arrasta o outro para o seu lado da balança.",
  "cards": [
      {"ic":"constellation","t":"Os Seis Acasos","emph":"Seis Acasos","b":"Tomáš e Tereza só se cruzam porque <strong>seis acasos</strong> se enfileiram — uma ciática que o manda a outra cidade, o restaurante onde ela serve, um número de quarto que coincide, Beethoven no rádio no instante exato. Frágeis como pássaros pousando nos ombros. O que ele depois chamaria de destino <strong>era pura contingência</strong>, e foi a beleza — o acaso que rima — que a converteu em amor.","tip":"<strong>Para refletir:</strong> o que você narra como 'destino' na sua história seria, como aqui, um punhado de coincidências que a memória, mais tarde, decidiu sacralizar?","wide":True},
      {"ic":"leaf","t":"A Compaixão Como Armadilha","emph":"Armadilha","b":"Tereza chega doente, com febre, e algo se fecha: Tomáš não consegue <em>não</em> sofrer o sofrimento dela. Compaixão, aqui, não é a piedade que olha de cima — é a <em>com-paixão</em> etimológica, sofrer junto, no mesmo plano. <strong>O que o prende não é o desejo, é a impossibilidade de ficar de fora da dor do outro.</strong> O peso que ele tanto temia entra pela porta mais mansa.","tip":"<strong>Modelo mental:</strong> o laço mais difícil de cortar não é o do prazer — é o da dor partilhada. Quem sente como seu o que dói no outro já não consegue ir embora leve."},
      {"ic":"fork","t":"Es Muss Sein?","emph":"Es Muss Sein","b":"Tomáš oscila entre dois pratos: assumir o peso de Tereza ou voltar à leveza dos casos sem laço. E descobre o pior — <strong>sem o eterno retorno, não há como saber qual escolha era a certa</strong>. 'Tem de ser?' é a pergunta que ele rouba a Beethoven e que o livro inteiro persegue, sabendo de antemão que não vai respondê-la.","tip":"<strong>Para refletir:</strong> numa decisão sem volta que você tomou, o que a fez parecer 'necessária' — e quanto disso era acaso que você, depois, promoveu a fado?"},
    ],
  "lessons_title": "Lições-Chave do Capítulo 2",
  "lessons": ["O que vivemos como necessidade ('não podia ser de outro jeito') é, quase sempre, contingência que a memória disfarça de destino.", "A compaixão — sofrer com o outro, não por ele — é o que dá peso ao amor de Tomáš e o impede de partir.", "A beleza é o acaso que rima: um motivo musical no rádio basta para converter coincidência em sentido amoroso."],
 },
 {
  "slug": "ch03-parte2-alma-e-corpo",
  "sub": "CAPÍTULO 3: Parte 2 — A Alma e o Corpo (Tereza por dentro)",
  "intro": "A mesma história, agora pelo avesso de Tereza. Kundera reexpõe a cena como um tema musical retomado por outra voz — e, ao trocar a alma que olha, troca a própria verdade. Aqui se descobre a nascente da fragilidade dela: uma infância sob uma mãe que zombava do pudor, e o medo de ser apenas um corpo entre tantos.",
  "cards": [
      {"ic":"person","t":"O Drama do Dualismo","emph":"Dualismo","b":"Tereza queria que o corpo fosse a expressão única e visível da alma — e teme que seja só mais um corpo entre milhões, <strong>perfeitamente intercambiável</strong>. As traições de Tomáš ferem exatamente esse ponto: se o sexo 'não tem alma', então o corpo é coisa banal, e <strong>se o corpo é banal, Tereza não é ninguém</strong>. O ciúme dela é uma questão de metafísica disfarçada de ciúme.","tip":"<strong>Para refletir:</strong> o que a tortura não é a infidelidade em si, é a substituibilidade. Em que vínculos você sente essa mesma ânsia — a de ser único, e não mais um?"},
      {"ic":"eye","t":"O Espelho e a Alma","emph":"Espelho e a Alma","b":"Tereza diante do espelho, procurando a alma atrás do rosto. Por um instante crê tê-la visto; no seguinte, só rosto, pele, ossos — <strong>um invólucro como outro qualquer</strong>. O pavor não é de ser feia. É de não ser ninguém. Contra o mundo da mãe, onde os corpos eram todos iguais e sem segredo, ela trava uma guerra silenciosa para existir como alguém.","tip":"<strong>Modelo mental:</strong> a câmera fotográfica será a arma de Tereza — fotografar a invasão soviética é seu modo de agir, de ser sujeito que vê em vez de objeto que é visto."},
      {"ic":"wave","t":"A Vertigem Kunderiana","emph":"Vertigem","b":"Vertigem não é o medo de cair — é o <strong>desejo de cair</strong>, a atração baixa pela própria fraqueza, a voz do abismo que chama. Tereza a sente diante da força de Tomáš e da própria submissão; é a forma íntima do amor por quem se sabe que vai machucá-la. <strong>Não fugimos só do que nos destrói: às vezes nos inclinamos para ele.</strong>","tip":"<strong>Para refletir:</strong> a própria forma do romance é tese — contar a mesma cena por duas almas mostra que a verdade muda conforme quem a vive. Não há um relato neutro."},
    ],
  "lessons_title": "Lições-Chave do Capítulo 3",
  "lessons": ["O ciúme de Tereza é metafísico: o que está em jogo não é a traição, é se a pessoa é única ou substituível.", "Repetir a mesma cena por outro ponto de vista é, em si, um argumento — a verdade depende da alma que olha.", "A vertigem — o desejo de cair — explica por que os personagens se entregam justamente ao que os arruína."],
 },
 {
  "slug": "ch04-parte3-palavras-incompreendidas",
  "sub": "CAPÍTULO 4: Parte 3 — Palavras Incompreendidas (Sabina × Franz)",
  "intro": "A balança vira para o segundo casal: a pintora Sabina e o professor Franz. Aqui o narrador faz uma das suas jogadas mais finas — intercala um 'Pequeno Dicionário de Palavras Incompreendidas', onde se vê que os dois usam o mesmo idioma e habitam mundos opostos. O amor não naufraga por falta de sentimento; naufraga porque cada um decifra as mesmas palavras de um jeito incompatível.",
  "cards": [
      {"ic":"bubble","t":"O Dicionário das Palavras Mal-Entendidas","emph":"Palavras Mal-Entendidas","b":"Para Franz, <strong>fidelidade</strong> é a maior das virtudes; para Sabina, a virtude é a <strong>traição</strong> — sair da fila, romper o que está posto. Para ele, a passeata é 'a vida verdadeira'; para ela, que marchou à força nos desfiles comunistas, é puro horror. <strong>As mesmas palavras, e por baixo delas dois mundos que não se tocam.</strong> Eles se amam em duas línguas que apenas parecem ser uma.","tip":"<strong>Como aplicar:</strong> num conflito — amoroso, de trabalho, de família — escreva as palavras-chave dos dois lados e pergunte: elas significam mesmo a mesma coisa para cada um? Quase nunca significam.","wide":True},
      {"ic":"triangle","t":"A Traição Como Valor de Sabina","emph":"Traição","b":"Sabina trai em cadeia — o pai, o marido, a pátria, todo kitsch — e a cada rompimento se sente mais leve. Até esbarrar no fundo: depois de trair tudo, <strong>não sobra nada para trair</strong>, e a leveza absoluta revela seu avesso, o vazio. É a prova viva da tese do livro: <strong>levada ao extremo, a leveza pesa como o mais insuportável dos fardos</strong>. O oposto do peso também não salva.","tip":"<strong>Para refletir:</strong> Sabina leva a filosofia da leveza mais longe que ninguém — e paga a conta sozinha. O que sobra de uma liberdade que não se compromete com absolutamente nada?"},
      {"ic":"mask","t":"O Chapéu-Coco — O Sentido Que Se Move","emph":"Sentido Que Se Move","b":"O chapéu preto do avô de Sabina muda de significado a cada vez que reaparece: primeiro é jogo erótico, depois marca de identidade, depois memória de um passado perdido. <strong>O mesmo objeto, sentidos que se invertem.</strong> O chapéu ensina a ler o livro inteiro — nada tem sentido fixo; tudo depende de quem olha, e de quando.","tip":"<strong>Modelo mental:</strong> como o chapéu-coco, os motivos voltam transformados ao longo da obra — como um tema musical num desenvolvimento de sonata. Siga cada retorno e veja o que mudou."},
    ],
  "lessons_title": "Lições-Chave do Capítulo 4",
  "lessons": ["Nem todo fracasso amoroso é falta de amor: pode ser a incomensurabilidade de dois mundos escondida sob palavras iguais.", "A traição, em Sabina, não é vício e sim princípio — e revela o limite da leveza: depois de tudo traído, o vazio.", "O sentido é móvel: depende de quem olha e de quando, como o chapéu-coco que muda a cada retorno."],
 },
 {
  "slug": "ch05-parte4-alma-e-corpo",
  "sub": "CAPÍTULO 5: Parte 4 — A Alma e o Corpo (Tereza, o Regime)",
  "intro": "Tereza decide provar em si a leveza que a tortura: se Tomáš entrega o corpo sem a alma e fica ileso, talvez ela consiga o mesmo e se cure do ciúme. O experimento fracassa — e o fracasso é a resposta. Para ela, corpo e alma não se desatam; e, no país ocupado, descobre-se que nem o ato mais íntimo escapa à sombra do Estado.",
  "cards": [
      {"ic":"person","t":"A Leveza Não É Transferível","emph":"Não É Transferível","b":"Tereza tenta o sexo 'leve', desligado de sentimento — e o que vem não é libertação, é náusea. <strong>O que solta um pode acorrentar o outro</strong>: corpo e alma se prendem de um jeito diferente em cada pessoa. A fenda entre ela e Tomáš não é moral, é existencial. Não é que um seja melhor; é que <strong>habitam estruturas opostas, e nenhuma se ensina à outra</strong>.","tip":"<strong>Para refletir:</strong> antes de cobrar de alguém a sua leveza — ou o seu peso —, lembre que talvez você esteja exigindo que o outro respire por pulmões que não são os dele."},
      {"ic":"eye","t":"Público × Privado Sob Vigilância","emph":"Sob Vigilância","b":"Em Praga, depois de 1968, a polícia secreta grava as conversas mais íntimas e as transmite para humilhar. <strong>A fronteira entre o quarto e o Estado se apaga</strong>: a intimidade vira prova, a vida privada vira espetáculo de controle. Sob o totalitarismo, <strong>a vida privada simplesmente não existe</strong> — é a versão macro do dualismo, com o corpo capturado pelo regime.","tip":"<strong>Modelo mental:</strong> o totalitarismo não ocupa só a praça — entra na cama. Aqui o 'pessoal é político' não é palavra de ordem; é uma ameaça com gravador ligado."},
      {"ic":"wave","t":"O Pesadelo da Igualdade Forçada","emph":"Igualdade Forçada","b":"Tereza sonha com mulheres nuas marchando uniformes em volta de uma piscina — todas idênticas, e ela ordenada a ser igual. É o terror de ser <strong>um corpo entre corpos iguais, sem alma própria</strong>. No sonho, o mundo da mãe e o mundo do regime se fundem num só símbolo: a ameaça existencial e a política têm, no fim, a mesma forma.","tip":"<strong>Para refletir:</strong> o regime não se contenta em proibir liberdades — quer dissolver a singularidade da alma. Os sonhos de Tereza são onde o íntimo e o político descobrem que sempre foram a mesma ferida."},
    ],
  "lessons_title": "Lições-Chave do Capítulo 5",
  "lessons": ["A leveza não é transferível: o que liberta um pode aprisionar o outro — a diferença é existencial, não moral.", "Sob o totalitarismo não há vida privada; o regime invade até a cama e transforma a intimidade em prova.", "O fracasso de Tereza fecha o diagnóstico do livro: nem o peso nem a leveza salvam — cada um sofre o seu polo."],
 },
 {
  "slug": "ch06-parte5-leveza-e-peso",
  "sub": "CAPÍTULO 6: Parte 5 — Leveza e Peso (Tomáš, Édipo, as Vidraças)",
  "intro": "Tomáš escreve um artigo que compara os comunistas que 'não sabiam' a Édipo — e por isso perde a cirurgia, sua paixão soberana, seu maior 'es muss sein'. Recusa-se a retratar-se e cai degrau a degrau, até virar limpador de vidraças. E descobre, surpreso, que a queda traz uma leveza ambígua: pode ser alívio, pode ser a antessala do vazio. Às vezes é difícil saber qual das duas.",
  "cards": [
      {"ic":"eye","t":"A Metáfora de Édipo","emph":"Édipo","b":"Édipo não quis matar o pai nem desposar a mãe — mas, ao saber que o fizera, não alegou inocência: <strong>arrancou os próprios olhos</strong>. É a pergunta que Tomáš atira aos que dizem 'não sabíamos dos crimes': a ignorância não absolve, e a culpa partilhada cobra o mesmo gesto de quem a reconhece. <strong>O regime, que não tolera espelhos, lê a metáfora literária como crime político.</strong>","tip":"<strong>Para refletir:</strong> 'não saber' basta para ficar limpo? Vale para tudo o que escolhemos não investigar — porque investigar nos obrigaria a agir."},
      {"ic":"spark","t":"A Retratação Recusada","emph":"Recusada","b":"Tomáš se nega a assinar a retratação — e não por heroísmo de bandeira. Simplesmente não suporta <strong>escrever, com a própria mão, o contrário do que pensa</strong>. Por essa recusa miúda perde a medicina e desce a limpador de vidraças. <strong>A fidelidade ao próprio eu pode custar tudo — e não é nem coragem nem covardia: é o mínimo de integridade sem o qual já não se é ninguém.</strong>","tip":"<strong>Modelo mental:</strong> o gesto de Tomáš não tem nada de político. Pergunta a você o mesmo: o que você se recusaria a assinar, ainda que isso custasse a carreira?"},
      {"ic":"leaf","t":"A Leveza da Queda","emph":"Queda","b":"De andaime em andaime, vidraça após vidraça, Tomáš se sente estranhamente <strong>livre</strong> — sem carreira a defender, sem peso a proteger, com as tardes e as amantes de volta. A perda de status vira leveza dúbia: alívio e dissolução ao mesmo tempo. E o 'es muss sein' que ele atribuía à medicina mostra-se <strong>tão acidental quanto os seis acasos que lhe trouxeram Tereza</strong> — necessidade que a memória inventou.","tip":"<strong>Para refletir:</strong> o que você jura ser 'a sua vocação, não podia ser outra coisa' — quanto disso é fado e quanto é acaso que você, com o tempo, decidiu chamar de destino?"},
    ],
  "lessons_title": "Lições-Chave do Capítulo 6",
  "lessons": ["O que chamamos de destino ou vocação costuma ser acaso que a memória, mais tarde, promove a necessidade.", "Recusar a humilhação pode custar tudo — e não é heroísmo nem covardia: é fidelidade mínima ao próprio eu.", "A queda pode trazer leveza; mas, em Kundera, leveza em excesso já beira o vazio."],
 },
 {
  "slug": "ch07-parte6-a-grande-marcha",
  "sub": "CAPÍTULO 7: Parte 6 — A Grande Marcha (O Kitsch)",
  "intro": "O coração filosófico do livro. O narrador larga o enredo e dá-se ao seu ensaio mais célebre — o do kitsch, essa recusa estética e moral de tudo o que, na existência, é inaceitável. E mostra a Grande Marcha, a fantasia da humanidade desfilando unida rumo à fraternidade, como o kitsch feito política: emoção coletiva sem objeto, o desfile como fim em si mesmo.",
  "cards": [
      {"ic":"mask","t":"O Kitsch e a Segunda Lágrima","emph":"Segunda Lágrima","b":"Kitsch é a recusa da morte, do ridículo, dos excrementos, do acaso — o biombo bonito que se põe diante da morte para não vê-la. Sua fórmula são <strong>duas lágrimas</strong>. A primeira diz: 'que comovente, as crianças correndo na grama!' — e é humana. A segunda diz: 'que comovente, comover-me junto com toda a humanidade!' — e <strong>essa, a comoção que se admira a si mesma, é o kitsch</strong>.","tip":"<strong>Teste:</strong> da próxima vez que uma emoção grande o tomar num desfile, numa causa, numa propaganda, pergunte — você sente pelo objeto, ou está se comovendo com a própria comoção? Só a segunda lágrima é kitsch.","wide":True},
      {"ic":"triangle","t":"A Ditadura do Coração","emph":"Ditadura do Coração","b":"O kitsch exige <strong>unanimidade de sentimento</strong> e bane a dúvida, a ironia, o indivíduo. No seu reino, as respostas já vêm dadas e qualquer pergunta soa traição. Por isso <strong>todo totalitarismo é kitsch</strong>: precisa que todos chorem a mesma lágrima na mesma hora, e elimina o que destoa do desfile. A ternura obrigatória é a face sorridente do terror.","tip":"<strong>Sinal de alerta:</strong> quando um grupo exige que você sinta o que 'todos' sentem, sob pena de exclusão, você está diante da ditadura do coração — comunista, democrática, religiosa ou de família, tanto faz.","warn":True},
      {"ic":"wave","t":"O Kitsch É Universal","emph":"Universal","b":"Há kitsch comunista, fascista, católico e democrático — ele é, diz o narrador, parte da condição humana, e ninguém escapa inteiro. Até Sabina, que faz da luta contra o kitsch a sua bandeira, guarda o seu: a janela acesa à noite, a casa quente, a família feliz lá dentro. <strong>Combatê-lo não tem fim — porque o kitsch mora também em quem o combate.</strong>","tip":"<strong>Para refletir:</strong> qual é o seu kitsch particular — a imagem de vida realizada que 'não pode faltar' e que você se recusa, justamente, a olhar de perto?"},
    ],
  "lessons_title": "Lições-Chave do Capítulo 7",
  "lessons": ["Kitsch é a mentira que nega a morte, o corpo e o acaso para jurar que tudo é belo e tem sentido — o biombo diante da morte.", "A segunda lágrima é o teste: emoção que se admira a si mesma e exige consenso já virou kitsch.", "Todo totalitarismo é kitsch — mas o kitsch é universal, mora até em quem o combate, e por isso combatê-lo não acaba nunca."],
 },
 {
  "slug": "ch08-parte7-o-sorriso-de-karenin",
  "sub": "CAPÍTULO 8: Parte 7 — O Sorriso de Karenin (O Idílio)",
  "intro": "O fecho é a parte mais serena do romance. Tomáš e Tereza vivem agora numa aldeia, ele sem amantes, longe de Praga e da História; o cão Karenin — batizado com nome de Anna Kariênina — adoece de câncer. Contra todo o peso filosófico das partes anteriores, este movimento propõe uma felicidade humilde, quase paradisíaca, encontrada exatamente onde ninguém pensaria procurá-la: na queda, na repetição, no fim.",
  "cards": [
      {"ic":"leaf","t":"O Amor Idílico e o Tempo Circular","emph":"Tempo Circular","b":"O único amor verdadeiramente idílico do livro é o amor por um animal — <strong>sem ciúme, sem futuro a conquistar, sem reciprocidade a cobrar</strong>. Karenin não quer mudar nada nem chegar a lugar nenhum: vive no tempo circular da repetição amada, o mesmo passeio, a mesma rosquinha, a mesma manhã. É o paraíso que os homens perderam quando trocaram o círculo pela linha reta do progresso e do desejo.","tip":"<strong>Para refletir:</strong> Kundera sugere que talvez seja o único amor em que o homem dá menos do que recebe — e nem por isso é perdoado. Quanto da sua vida cabe nesse tempo circular, e quanto você o despreza por ser 'só repetição'?"},
      {"ic":"scale","t":"A Leveza Finalmente Habitável","emph":"Habitável","b":"Despidos de tudo — carreira, pátria, juventude —, Tomáš e Tereza se reconciliam. E Tereza percebe o paradoxo: foi a queda, a perda de tudo, que os trouxe à única felicidade possível. <strong>O peso que ela carregou com culpa foi também o que os salvou.</strong> A balança não declara um vencedor; leveza e peso encontram, enfim, um repouso frágil — e o frágil, aqui, é a forma mais alta de verdade.","tip":"<strong>Modelo mental:</strong> este não é o vazio de Sabina. É a leveza redimida — a paz da repetição amada, a felicidade pequena fora da Grande Marcha, à beira do fim e justamente por isso preciosa.","wide":True},
      {"ic":"mountain","t":"A Morte Sem Biombo","emph":"Sem Biombo","b":"Karenin morre de câncer, e Tomáš, o médico, é quem decide poupá-lo. Encarar essa morte <strong>sem enfeite, sem segunda lágrima, com pura ternura e pura dor</strong> é o exato oposto do kitsch. O idílio só é verdadeiro porque não esconde o fim — porque deixa cair o biombo. <strong>Não há paraíso sem morte dentro dele; só há mentira sobre a morte.</strong>","tip":"<strong>Para refletir:</strong> o narrador conta a morte de Tomáš e Tereza antes do fim, de propósito — para que você olhe a qualidade do instante, não o suspense do desfecho. O que muda na vida quando você a lê sabendo, sem disfarce, que ela termina?"},
    ],
  "lessons_title": "Lições-Chave do Capítulo 8",
  "lessons": ["A felicidade possível não está na Grande Marcha nem no sentido grandioso, mas no idílio repetido do cotidiano amado.", "O amor a um animal é o modelo do amor puro: sem interesse, sem futuro, sem reciprocidade exigida.", "Encarar a morte sem o biombo do kitsch é o que torna o idílio verdadeiro — o paraíso inclui o fim, não o nega."],
 },
 {
  "slug": "ch09-narrador-estrutura-simbolos",
  "sub": "CAPÍTULO 9: O Narrador, a Estrutura e os Símbolos",
  "intro": "Importa tanto o que o romance diz quanto a forma com que é construído — porque, aqui, a forma é o argumento. Kundera escreve um romance que pensa: um narrador que comenta, cita filósofos e chega a confessar que inventou os personagens. Sete partes erguidas como sete movimentos de música, com a cronologia embaralhada de propósito. Quem entende a partitura entende a obra.",
  "cards": [
      {"ic":"book","t":"O Romance Que Pensa","emph":"Que Pensa","b":"O narrador-ensaísta não se esconde atrás da história: pensa alto, discute Nietzsche e Parmênides e <strong>admite que tudo é ficção</strong> — Tomáš, diz ele, nasceu da frase <em>einmal ist keinmal</em>. Longe de quebrar o encanto, isso é o convite: <strong>você não vem aqui para acreditar, mas para pensar junto</strong>. Cada personagem é uma hipótese existencial posta à prova.","tip":"<strong>Como ler:</strong> tome cada um como uma equação. Tomáš = leveza e 'es muss sein'. Tereza = peso e o dualismo corpo-alma. Sabina = traição e fuga do kitsch. Franz = fidelidade e a Grande Marcha."},
      {"ic":"wave","t":"Composição Musical / Polifonia","emph":"Polifonia","b":"Sete partes, sete movimentos — e os títulos voltam em espelho ('Leveza e Peso' nas partes 1 e 5; 'A Alma e o Corpo' nas 2 e 4). Os motivos reaparecem transformados, como temas numa sonata: o <em>es muss sein</em> de Beethoven, o chapéu-coco, a segunda lágrima, Karenin. <strong>O eterno retorno, que o livro nega como crença, ele realiza na própria estrutura.</strong> Leia como partitura, não como enredo.","tip":"<strong>Como aplicar:</strong> ao reler, persiga cada motivo recorrente — toda volta do chapéu-coco, do espelho ou de Beethoven carrega um sentido novo que a anterior não tinha.","wide":True},
      {"ic":"spiral","t":"A Não-Resolução Como Método","emph":"Não-Resolução","b":"Kundera não resolve a balança leveza × peso: encarna-a em destinos e a deixa aberta. Para ele, o romance é o território da <strong>pergunta e da ambiguidade, não da resposta</strong> — e por isso embaralha o tempo e revela cedo a morte dos protagonistas. O 'o que acontece' importa menos que o 'o que significa'. <strong>A obra que sabe responder já não é romance; é catecismo.</strong>","tip":"<strong>Para refletir:</strong> o que muda na leitura ao saber, desde cedo, que Tomáš e Tereza morrerão num acidente de caminhão? O autor queria seu olhar na qualidade do instante, e não no suspense do fim."},
    ],
  "lessons_title": "Lições-Chave do Capítulo 9",
  "lessons": ["Leia como música: siga os motivos que retornam (es muss sein, o chapéu-coco, Karenin), não apenas o enredo.", "O narrador que pensa alto e confessa a ficção não é defeito — é o método; cada personagem é uma hipótese à prova.", "A não-resolução é deliberada: o romance, para Kundera, é o reino da pergunta, não da resposta."],
 },
]
