# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'O Investidor Inteligente' (Benjamin Graham)."""

BOOK = {
 "title": "O Investidor Inteligente",
 "author": "Benjamin Graham",
 "header_light": "O INVESTIDOR",
 "header_bold": "INTELIGENTE",
 "subtitle": "VISÃO GERAL · A BÍBLIA DO VALUE INVESTING",
 "intro": "O 'investidor inteligente' não é o mais esperto — é o mais paciente e disciplinado. Graham mostra que o maior inimigo do investidor é ele mesmo, e que duas palavras resumem tudo: margem de segurança. A alegoria do Sr. Mercado, a distinção preço × valor e as regras para o defensivo e o empreendedor compõem o manual definitivo.",
 "description": "A bíblia do value investing de Benjamin Graham. Investidor vs. especulador, a alegoria do Sr. Mercado, a margem de segurança, o investidor defensivo (50/50 e dollar-cost averaging), o empreendedor e as net-nets, preço vs. valor, inflação, temperamento e os critérios quantitativos de seleção de ações.",
 "tags": ["Value Investing", "Finanças", "Bolsa de Valores"],
 "progress": "10 Capítulos",
 "cover": "assets/investidor-inteligente-cover.png",
 "overview_cards": [
   {"ic":"scale","t":"Margem de Segurança","b":"O conceito central de todo o livro. Compre sempre com <strong>desconto substancial sobre o valor intrínseco</strong>, deixando folga para você estar errado. Analogia clássica: construa a ponte para 30 toneladas e dirija o caminhão de 10.","tip":"<strong>Como aplicar:</strong> pense primeiro em não perder; o ganho vem como consequência da disciplina."},
   {"ic":"person","t":"O Sr. Mercado","b":"O mercado é um <strong>sócio maníaco-depressivo</strong> que bate à sua porta todo dia oferecendo um preço. Você nunca é obrigado a aceitar. Ele está lá para <strong>servir, não para guiar</strong> — use a volatilidade como oportunidade, não como sinal de alarme.","tip":"<strong>Regra:</strong> compre no pânico do Sr. Mercado; ignore ou venda na euforia.","wide":True},
   {"ic":"fork","t":"Defensivo × Empreendedor","b":"Dois perfis coerentes: o <strong>defensivo</strong> busca tranquilidade com carteira 50/50 a 75/25 e regras mecânicas; o <strong>empreendedor</strong> dedica tempo para caçar pechinchas e net-nets. O erro é o meio-termo sem disciplina.","tip":"<strong>Modelo mental:</strong> se não tiver tempo e método para ser ativo, seja definitivamente passivo."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-investidor-vs-especulador","sub":"CAPÍTULO 1: Investimento vs. Especulação",
  "intro":"Graham define investimento como uma operação que, após análise séria, promete segurança do principal e retorno adequado. Tudo que não atende a esses três pilares é especulação. Saber em qual jogo você está é a primeira decisão inteligente.",
  "cards":[
      {"ic":"scale","t":"A Definição Tríplice","emph":"Tríplice","b":"Investir não é um salto de fé, é uma matemática inquebrável: análise profunda do ativo, blindagem absoluta do principal e retorno racional. Omitir qualquer um desses três pilares <strong>transforma o seu capital numa aposta suicida no cassino</strong>. Chamar o bilhete de loteria de aplicação é o primeiro passo para o matadouro financeiro.","tip":"<strong>Regra:</strong> teste o seu ativo contra a trindade protetora — se o risco for mortal ou a base analítica for cega, você é um especulador."},
      {"ic":"fork","t":"O Defensivo e o Empreendedor","emph":"Defensivo e o Empreendedor","b":"O mercado recompensa quem conhece a própria marcha e tritura quem duvida. O perfil defensivo delega o esforço aos sistemas mecânicos e ganha paz; o ativo gasta suor para descolar da média. <strong>O abismo fatal se escancara para o amador que gasta pouco tempo tentando colher lucros agressivos</strong>.","tip":"<strong>Como aplicar:</strong> fixe a sua identidade na rocha e abandone as táticas anfíbias que não pertencem ao seu jogo."},
      {"ic":"gap","t":"Especulação Limitada","emph":"Limitada","b":"Especular possui o seu espaço escuro, desde que amarrado e confinado num cofre raso distante das suas economias de vida reais. Brincar com alavancas exige que o montante <strong>esteja rotulado como lixo radioativo dimensionado para evaporar</strong> sem sangrar o núcleo. O pecado capital repousa em misturar contas e atuar vendado.","tip":"<strong>Sinal de alerta:</strong> o investidor que especula achando estar protegendo o futuro assina o próprio atestado da falência crônica.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Defina seu jogo: investidor ou especulador — e seja coerente com ele.","Investir exige os três pilares; sem eles, admita que está especulando.","Se for especular, isole o capital e limite o tamanho."]},

 {"slug":"ch02-inflacao","sub":"CAPÍTULO 2: O Investidor e a Inflação",
  "intro":"O inimigo silencioso do investidor não é a queda do mercado, mas a inflação, que corrói o poder de compra do dinheiro parado. O retorno 'adequado' precisa ser medido em termos reais.",
  "cards":[
      {"ic":"wave","t":"O Retorno Real Amargo","emph":"Retorno Real","b":"A métrica final não é o montante brilhando na tela virtual verde da sua corretora, mas a quantia íntegra de pães subtraída pelo custo da rua real. Render seis por cento com inflação de oito <strong>é sofrer uma hemorragia lenta escondida numa fantasia de lucro cego nominal</strong>. O número que não domina a prateleira sangra o seu cofre.","tip":"<strong>Como aplicar:</strong> o cálculo absoluto expurga o charme vazio das moedas fáceis que evaporam antes da conta do mês fechar."},
      {"ic":"triangle","t":"O Escudo Furado das Ações","emph":"Escudo Furado","b":"As engrenagens acionárias possuem a elasticidade valiosa de transferir as altas de preços aos balcões, servindo de colete tático nas selvas de papel. Mas essa proteção parcial e manca <strong>nunca blinda a carteira inteira num mar turbulento das taxas esticadas</strong>. Na espiral pesada dos juros travados para combater os picos, a sua tela chorará.","tip":"<strong>Modelo mental:</strong> trate a inflação como uma bactéria resistente crônica; o combate se dá com sistemas inteiros, não com pílulas mágicas."},
      {"ic":"layers","t":"A Trincheira Diversificada","emph":"Diversificada","b":"Despejar as fichas pesadas na aparente tumba segura da renda fixa congela o sangue enquanto o valor desaparece no forno silencioso das emissões soltas desenfreadas. Sobreviver no tiroteio imprevisível demanda imperiosamente <strong>o uso mesclado simultâneo da âncora fixa conservadora junto às hastes da renda flexível do mercado</strong>.","tip":"<strong>Sinal de alerta:</strong> prender o oxigênio financeiro sob a laje grossa e fria das contas seguras garante a deflação invisível amarga gradual cruel e calada lenta.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["Meça todo retorno em termos reais, descontando a inflação.","Ações oferecem proteção parcial — útil, mas não garantida.","Equilibrar ações e renda fixa defende contra cenários opostos."]},

 {"slug":"ch03-historico-do-mercado","sub":"CAPÍTULO 3: Um Século de História do Mercado",
  "intro":"A história mostra que o mercado alterna euforia e pânico em ciclos, e que preços altos embutem retornos futuros baixos. Estudar o passado serve para calibrar expectativas, não para prever o próximo movimento.",
  "cards":[
      {"ic":"clock","t":"O Preço Acima de Tudo","emph":"Preço Acima de Tudo","b":"A febre alucinógena rasga as etiquetas das lojas puxando a conta para os céus distantes. Quando você paga na euforia longe do asfalto suado das planilhas frias de resultados sólidos e passados, <strong>as chances estáticas do amanhã despencam no buraco invisível escuro amargo do chão do vale</strong>. Múltiplos são relógios, não profecias.","tip":"<strong>Prática:</strong> rebaixe drasticamente as esperanças de ouro quando os gráficos estiverem flutuando felizes nos cumes de papel e névoa das emoções gulosas."},
      {"ic":"spiral","t":"A Gravidade Impiedosa","emph":"Gravidade Impiedosa","b":"A multidão insana decreta o fim das velhas perdas clamando paradigmas geniais inovadores novos brilhantes puros. A força ancestral, porém, suga as exceções pro eixo médio. <strong>Tudo o que flutua frouxo longe das bases de pedra contábil afunda no charco de forma brutal arrastando os apressados gananciosos ao fracasso sangrento mudo</strong>.","tip":"<strong>Modelo mental:</strong> o delírio cantado do 'desta vez não volta' desenhou o túmulo de cada febre burra suicida covarde e podre rica feia que sangrou investidores."},
      {"ic":"wave","t":"Pausar o Medo e a Fome","emph":"Medo e a Fome","b":"Manter a baliza do eixo girando sob regras severas impõe o reajuste nos dois lados da prancha furiosa gélida chuvosa. Atolar cotas de ações amparado pela sede cega irracional no topo caro dos festivais vazios cheios ruidosos quentes e longos escancara <strong>a derrota covarde da razão sendo enforcada cruel pelas manchetes mansas de ouro e pluma fina do abismo noturno escuro</strong>.","tip":"<strong>Armadilha:</strong> aumentar as marchas e atirar granadas douradas de fardos plenos de capital suado na corrida do boi gordo gordo morrendo sem saber e sorrindo e morrendo.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["O preço pago hoje determina, em grande parte, o retorno de amanhã.","Extremos de valuation revertem; humildade vence a euforia.","Ajuste a alocação ao ciclo, mas sempre dentro de limites disciplinados."]},

 {"slug":"ch04-investidor-defensivo","sub":"CAPÍTULO 4: A Carteira do Investidor Defensivo",
  "intro":"O investidor defensivo busca tranquilidade e ausência de erros graves, não desempenho máximo. A solução é uma carteira simples, equilibrada, com regras mecânicas que removem a emoção da decisão.",
  "cards":[
      {"ic":"scale","t":"A Guarda das Engrenagens","emph":"Engrenagens","b":"Entregar a batuta condutora na mão insensível de um rádio engessado afugenta as apostas da vaidade emocional. Respeitar tetos rústicos entre posições de moedas mortas tristes de poupança firme e folhas verdes oscilantes elétricas <strong>coage as mãos de ferro a atirarem vendas automáticas nos dias felizes alucinados febris e compras silenciosas fundas baratas secas</strong>.","tip":"<strong>Regra:</strong> os muros que limitam a flexibilidade atuam feito grilhões salvando o piloto amador do desfiladeiro sujo fundo negro do instinto puro."},
      {"ic":"clock","t":"O Gotejador Mecânico","emph":"Gotejador Mecânico","b":"Mergulhar frações cegas periódicas frias constantes e surdas varre para o esgoto escuro amargo imundo podre cego a pressão mental suicida de caçar tempestades adivinhando marés fáceis nobres mortas do relógio. Comprar menos pacotes finos no ápice alto limpo puro verde da ladeira e arrastar carrinhos gordos fartos plenos no assoalho feio molhado ralo sujo quebra a angústia noturna.","tip":"<strong>Como aplicar:</strong> engesse o relógio e assine cegamente as provisões imunes e sagradas do calendário ignorando a TV."},
      {"ic":"key","t":"As Catedrais Antigas","emph":"Catedrais Antigas","b":"Ignorar novidades de plástico piscante cintilante perfumada oca mentirosa falsa cara gorda mansa que encantam marujos nas águas doces rasas fáceis e trazem praga fome guerra sombra frio dor e focar os mísseis cegos tristes de ferro quente na muralha clássica de pedras da elite. <strong>Comprar o que paga moedas fartas polidas e sujas cravadas reais fortes cheias por muitos invernos</strong>.","tip":"<strong>Modelo mental:</strong> o conservador foca os olhos escuros opacos frios doídos doídos na base rígida de ferro forte puro cru grosso."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["Mantenha de 25% a 75% em ações, com 50/50 como neutro, e rebalanceie.","Use aportes regulares (dollar-cost averaging) para vencer o timing.","Escolha blue chips e prefira simplicidade a complexidade."]},

 {"slug":"ch05-investidor-empreendedor","sub":"CAPÍTULO 5: A Carteira do Investidor Empreendedor",
  "intro":"O investidor empreendedor está disposto a dedicar tempo e esforço para superar a média. Graham adverte: só vale a pena com disciplina real — esforço sem método destrói valor, e pode ser pior que a estratégia passiva.",
  "cards":[
      {"ic":"lens","t":"Caça às Pechinchas","emph":"Pechinchas","b":"O mercado pune temporariamente negócios saudáveis. O investidor ativo desce aos porões do pânico farejando valor. Adquirir ativos sólidos <strong>pela metade do patrimônio real</strong> garante uma margem de proteção contra o ceticismo das ruas.","tip":"<strong>Como aplicar:</strong> compre o ativo quando a impopularidade gerar um desconto irracional."},
      {"ic":"gap","t":"A Tática Net-Nets","emph":"Net-Nets","b":"Comprar cotas abaixo do capital de giro líquido entrega o negócio inteiro como brinde. Isoladas, essas pechinchas escondem armadilhas letais. Mas <strong>uma cesta robusta dessas sobras absorve os impactos negativos e pavimenta o caminho rumo ao lucro desproporcional</strong>.","tip":"<strong>Sinal de alerta:</strong> concentrar o dinheiro em apenas uma pechincha arruinada anula qualquer margem de segurança e multiplica o seu risco.","warn":True},
      {"ic":"target","t":"Esforço e Método","emph":"Esforço e Método","b":"Acelerar o giro de posições não atesta atividade inteligente, apenas impulsiona a falência por desgaste de taxas. O caçador letal constrói um método sólido e rigoroso. Sem método comprovado, <strong>o aventureiro ativo transforma-se num doador de dinheiro sustentando a estrutura das corretoras</strong>.","tip":"<strong>Regra:</strong> opere de forma ativa somente se tiver disciplina e método; caso contrário, abrace a posição defensiva."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Só seja ativo se tiver disciplina e método; senão, seja defensivo.","Busque pechinchas e net-nets, com ampla diversificação.","Esforço sem critério é pior que a estratégia passiva."]},

 {"slug":"ch06-preco-vs-valor","sub":"CAPÍTULO 6: Preço vs. Valor",
  "intro":"A distinção fundadora do value investing: preço é o que você paga; valor é o que você recebe. O mercado cota preços o tempo todo, mas o valor intrínseco de um negócio muda muito mais devagar. Investir bem é explorar a diferença entre os dois.",
  "cards":[
      {"ic":"scale","t":"Preço ≠ Valor","emph":"Preço ≠ Valor","b":"O preço na tela é a emoção coletiva batendo martelo. O valor real é o motor sólido que gera caixa no longo prazo. Fundir cotação momentânea com o valor intrínseco <strong>é o erro fatal que destrói o patrimônio do amador precipitado</strong>. Se o valor superar o preço folgadamente, efetue a compra.","tip":"<strong>Como aplicar:</strong> rejeite ativos sobreprecificados e abrace aqueles esquecidos com solidez de fundamento."},
      {"ic":"wave","t":"Máquina de Votar e Pesar","emph":"Votar e Pesar","b":"As sessões do pregão agem como um concurso barulhento de popularidade descartável. A marcha dos anos, no entanto, <strong>funciona como uma balança implacável que precifica o peso real do lucro e do caixa gerado</strong>. Aposte sempre no veredito lento e definitivo da balança.","tip":"<strong>Modelo mental:</strong> o ativo ofuscado, porém subprecificado, sempre vencerá o queridinho caro do mercado no longo prazo."},
      {"ic":"lens","t":"A Bússola Racional","emph":"Bússola Racional","b":"Mapear centavos exatos nos lucros distantes mascara a incerteza do futuro sob a capa da precisão inútil. O valor desponta através de um raio amplo de segurança, <strong>apoiado firmemente no patrimônio observável do balanço atual</strong>.","tip":"<strong>Regra:</strong> não confie em otimismo estatístico de longuíssimo prazo; proteja o dinheiro nos números robustos do hoje."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Preço e valor são coisas distintas; lucre com a divergência.","No curto prazo prevalece a emoção; no longo, o fundamento.","Estime valor por faixas amplas, não por números exatos ilusórios."]},

 {"slug":"ch07-sr-mercado","sub":"CAPÍTULO 7: A Alegoria do Sr. Mercado",
  "intro":"Graham personifica o mercado como o Sr. Mercado: um sócio maníaco-depressivo que aparece todo dia oferecendo um preço. Você nunca é obrigado a aceitar. A genialidade é usá-lo, não obedecê-lo.",
  "cards":[
      {"ic":"person","t":"Servo, Não Oráculo","emph":"Servo, Não Oráculo","b":"O mercado não é um guia iluminado; ele atua como um sócio maníaco batendo na sua porta com ofertas insanas diárias. <strong>A missão consiste em extorquir os surtos depressivos dele ou faturar nos dias de delírio otimista incontrolável</strong>. Ele dita os preços, não o seu veredito de valor.","tip":"<strong>Como aplicar:</strong> feche a porta para o mercado nos dias mornos e abra a carteira apenas nos pânicos irracionais de venda."},
      {"ic":"spark","t":"Volatilidade Amiga","emph":"Volatilidade Amiga","b":"As flutuações sangrentas ferem de morte a ovelha insegura que persegue as setas diárias de cotação. O investidor estoico acolhe as crises, <strong>enxergando os mergulhos afiados das bolsas como presentes valiosos que entregam desconto e fortuna</strong>.","tip":"<strong>Modelo mental:</strong> o salto de preço altera o bilhete, mas não aumenta nem diminui as fundações de concreto da fábrica real."},
      {"ic":"mask","t":"A Corrente Emocional","emph":"Corrente Emocional","b":"Atrelar a pressão arterial às setas do índice escancara a submissão do apostador fraco. Entrar em parafuso nas quedas <strong>ou esbanjar autoconfiança comprando freneticamente topos caros deforma a sua sanidade tática e exaure os cofres num piscar de olhos</strong>.","tip":"<strong>Sinal de alerta:</strong> o impulso cego de agir imediatamente frente a qualquer oscilação de tela evidencia o erro crônico de postura.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["O Sr. Mercado oferece preços, não verdades — você escolhe quando agir.","Use a volatilidade a seu favor: compre no pânico, ignore a euforia.","Sua riqueza real depende do negócio, não da cotação de hoje."]},

 {"slug":"ch08-margem-de-seguranca","sub":"CAPÍTULO 8: A Margem de Segurança",
  "intro":"Se Graham tivesse que resumir o investimento inteligente a duas palavras, seriam MARGEM DE SEGURANÇA: comprar com desconto suficiente sobre o valor intrínseco para que erros de estimativa ou imprevistos não levem à perda permanente.",
  "cards":[
      {"ic":"scale","t":"O Colchão Antimorte","emph":"Colchão Antimorte","b":"A margem constitui o pilar que diferencia a conta fria do jogo inconsequente. Uma grande distância entre o valor projetado e o preço cobrado no balcão <strong>blinda o seu caixa contra o amanhã imprevisto e contra as próprias premissas que falharam rudemente</strong>.","tip":"<strong>Como aplicar:</strong> se o valor for cem reais, jamais compre por noventa; aguarde sentindo o tédio até tocar os sessenta."},
      {"ic":"key","t":"A Absolvição do Erro","emph":"Absolvição do Erro","b":"A margem foi inventada justamente porque a razão humana é precária. Ela amortiza as quedas contábeis severas operando como ponte projetada para excesso de peso. <strong>Sobreviver livre da destruição irreparável prepara a trilha dourada para o retorno generoso subsequente</strong>.","tip":"<strong>Modelo mental:</strong> foque impiedosamente na blindagem contra o desastre total; o lucro aparecerá de forma orgânica e paciente."},
      {"ic":"layers","t":"O Escudo do Batalhão","emph":"Escudo do Batalhão","b":"Ancorar a esperança inteira nas costas isoladas de uma única tese estilhaça qualquer parede de proteção construída no desconto do preço. Diversificar espalha o peso do chumbo estatístico, <strong>garantindo que o fracasso individual de uma ação seja anulado pela vitória matemática da cesta inteira</strong>.","tip":"<strong>Armadilha:</strong> o desconto avassalador numa única cota não substitui o escudo vital espalhado pela diversificação do portfólio.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Nunca compre sem margem de segurança — é o filtro central de Graham.","A margem protege contra seus próprios erros, não contra a volatilidade.","Combine margem com diversificação: ambas absorvem o imprevisível."]},

 {"slug":"ch09-temperamento-e-disciplina","sub":"CAPÍTULO 9: Temperamento e Disciplina",
  "intro":"Para Graham, o sucesso no investimento depende muito mais do temperamento do que do intelecto. O maior inimigo do investidor é ele mesmo — e proteger-se das próprias reações emocionais vale mais que qualquer análise sofisticada.",
  "cards":[
      {"ic":"mountain","t":"Caráter Esmaga o QI","emph":"Caráter Esmaga o QI","b":"O pior rival drena os seus ativos olhando direto pelo espelho matinal. O cérebro acadêmico sucumbe na nevasca da quebra porque falta lastro de sangue-frio. O vitorioso trava as emoções na hora de dor aguda, <strong>cumprindo a regra engessada e triturando o medo primal herdado do rebanho</strong>.","tip":"<strong>Como aplicar:</strong> escreva o seu protocolo operacional na pedra durante a paz e nunca o leia durante o sombrio desespero."},
      {"ic":"clock","t":"As Algemas Racionais","emph":"Algemas Racionais","b":"Tentativas inúteis de vaticinar marés afundam apostadores espertos num lodo movediço de vaidade e erro repetido. Proteger o capital significa estruturar o jogo para funcionar automaticamente sem você. <strong>A máquina decisória surda substitui as apostas febris por disciplina rotineira imbatível</strong>.","tip":"<strong>Sinal de alerta:</strong> preencher os fins de semana rascunhando previsões indica que as âncoras metodológicas estão arrebentadas.","warn":True},
      {"ic":"key","t":"O Triunfo da Espera","emph":"Triunfo da Espera","b":"Ausência de pressa temporal consagra o investidor que recusa ceder posições sólidas na calada da noite do medo. Romper o acordo mecânico nas horas gélidas de caos destrói colheitas antigas erguidas pedra por pedra. <strong>A paciência imóvel atua como cimento duro forjando muralhas ricas de prosperidade passiva</strong>.","tip":"<strong>Modelo mental:</strong> a quietude não é ociosidade; ela é a tática pesada exigindo nervos duros e silêncio absoluto no tiroteio."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["Temperamento vence QI: o inimigo é o próprio comportamento.","Não tente prever o mercado; proteja-se das suas reações emocionais.","Regras escritas e paciência são as armas centrais do investidor inteligente."]},

 {"slug":"ch10-analise-de-empresas","sub":"CAPÍTULO 10: Análise e Seleção de Ações",
  "intro":"Para estimar o valor intrínseco e encontrar a margem de segurança, Graham propõe critérios quantitativos, conservadores e verificáveis. A análise busca solidez e desconto, não a empresa mais empolgante.",
  "cards":[
      {"ic":"lens","t":"O Filtro Contábil","emph":"Filtro Contábil","b":"O otimismo fofo apaga os olhos enquanto o balanço amargo ilumina a sala nua. A qualidade defensiva foca os olhos nos lucros incessantes antigos e na folga esmagadora do capital de giro de hoje. <strong>Comprar saúde contábil demonstrada varre do mapa a lenda vazia prometida pelos múltiplos absurdos</strong>.","tip":"<strong>Como aplicar:</strong> o tédio no caixa forte ganha feio da euforia endividada que prega promessas impossíveis no balcão corporativo."},
      {"ic":"scale","t":"Teto de Múltiplos","emph":"Teto de Múltiplos","b":"Impor uma barreira de preços cobrindo lucros e patrimônio ao mesmo tempo corta as asas frágeis de ações supervalorizadas prestes a despencar no tédio da próxima crise. <strong>Combinar pisos lógicos garante abrigo tático freando a especulação impetuosa nas cotações fora de órbita</strong>.","tip":"<strong>Regra:</strong> pague barato pelos números duros do caixa; a virtude não está nos cálculos complexos, mas na matemática do preço modesto."},
      {"ic":"key","t":"A Muralha contra Juros","emph":"Muralha contra Juros","b":"Ignorar alavancagens cegas pavimenta o túnel rumo ao calote brutal. Companhias sólidas geram montanhas generosas cobrindo o fardo dos empréstimos. Tratar a dívida corporativa com desdém <strong>acelera o colapso estrutural da firma exata no segundo crítico em que o crédito encurta e vira pó</strong>.","tip":"<strong>Sinal de alerta:</strong> lucros vistosos lastreados num palácio montado com tijolos podres de empréstimos cobram multas devastadoras e súbitas.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 10",
  "lessons":["Selecione por solidez financeira, histórico estável e múltiplos baixos.","Combine P/L e P/VPA moderados para limitar o sobrepreço.","Lucros que cobrem a dívida com folga sustentam a segurança do principal."]},
]
