# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'O Investidor Inteligente' (Benjamin Graham)."""

BOOK = {
 "title": "O Investidor Inteligente",
 "author": "Benjamin Graham",
 "header_light": "O INVESTIDOR",
 "header_bold": "INTELIGENTE",
 "subtitle": "VISÃO GERAL · PROTEGER-SE DA PRÓPRIA BURRICE",
 "intro": "O investidor inteligente não é o mais esperto da sala — é o mais paciente, e sabe disso. Graham vira o jogo do avesso: o adversário a vencer não é o mercado, é o homem no espelho, que entra em pânico no fundo e fica ganancioso no topo. Contra ele, duas palavras bastam: margem de segurança. O resto do livro são ferramentas para manter a cabeça fria quando o Sr. Mercado bate à porta, eufórico ou em desespero. Investir, dizia ele, é tanto mais inteligente quanto mais se parece com administrar um negócio.",
 "description": "A obra que Warren Buffett chama do melhor livro de investimentos já escrito — e que não promete bater o mercado, e sim sobreviver a ele. Graham separa o investidor do especulador (análise, segurança do principal, retorno adequado), apresenta o Sr. Mercado como sócio maníaco-depressivo a serviço de quem souber usá-lo, ergue a margem de segurança como pilar central, distingue preço de valor, e arma o defensivo (carteira equilibrada, blue chips, aportes regulares) e o empreendedor (pechinchas e net-nets). No fim, a tese que tudo sustenta: temperamento e disciplina valem mais que QI.",
 "tags": ["Value Investing", "Finanças", "Bolsa de Valores"],
 "progress": "10 Capítulos",
 "cover": "assets/investidor-inteligente-cover.png",
 "overview_cards": [
   {"ic":"scale","t":"Margem de Segurança","b":"O coração do livro inteiro, em três palavras. Compre com <strong>desconto largo sobre o valor intrínseco</strong>, para que sua estimativa possa estar errada e você ainda assim não se arruine. É engenharia, não otimismo: <strong>construa a ponte para 30 toneladas e só atravesse com o caminhão de 10</strong>. A folga não é desperdício — é a diferença entre errar e quebrar.","tip":"<strong>Como aplicar:</strong> pense primeiro em não perder. O ganho vem depois, como recompensa da disciplina — nunca como objetivo."},
   {"ic":"person","t":"O Sr. Mercado","b":"Imagine um <strong>sócio maníaco-depressivo</strong> que bate à sua porta todo santo dia e grita um preço — pela sua parte ou pela dele. Uns dias eufórico, outros em desespero. A boa notícia: você nunca é obrigado a responder. Ele existe para <strong>servi-lo, não para guiá-lo</strong>; a cotação dele informa, mas quem decide o valor é você.","tip":"<strong>Regra:</strong> aproveite o desespero dele para comprar, a euforia para vender — e nos dias mornos, simplesmente feche a porta.","wide":True},
   {"ic":"fork","t":"Defensivo × Empreendedor","b":"Dois caminhos honestos, um único pecado: o meio-termo. O <strong>defensivo</strong> quer paz — carteira equilibrada, blue chips, regras mecânicas que decidem por ele. O <strong>empreendedor</strong> aceita o trabalho de caçar pechinchas e net-nets. Ambos vencem; quem perde é o amador que gasta esforço sem método e se imagina ativo.","tip":"<strong>Modelo mental:</strong> se não tem tempo nem disciplina para ser ativo de verdade, seja passivo de verdade. O pior lugar é entre os dois."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-investidor-vs-especulador","sub":"CAPÍTULO 1: Investimento vs. Especulação",
  "intro":"Graham abre o livro traçando uma fronteira que quase todos cruzam sem perceber. Investir é uma operação que, após análise séria, promete segurança do principal e retorno adequado — falte qualquer um dos três, e o que sobra é especulação. Não há vergonha em especular; há ruína em especular achando que se está investindo. A primeira decisão inteligente é saber em qual jogo você entrou.",
  "cards":[
      {"ic":"scale","t":"A Definição Tríplice","emph":"Tríplice","b":"Para Graham, a palavra 'investimento' tem um sentido exato, não um elogio vago. Exige <strong>análise séria, segurança do principal e retorno adequado</strong> — os três juntos, sem desconto. Tire um, e a operação não fica pior: muda de natureza, vira especulação. Chamar de investimento o que não passa nesse exame é o engano que precede a perda.","tip":"<strong>Regra:</strong> antes de comprar, submeta a operação aos três pilares. Se a análise é frágil ou o principal corre risco real, admita: você está especulando."},
      {"ic":"fork","t":"O Defensivo e o Empreendedor","emph":"Defensivo e o Empreendedor","b":"Há dois modos coerentes de investir, e Graham respeita os dois. O <strong>defensivo</strong> quer evitar erros graves e dormir tranquilo; deixa que regras simples trabalhem por ele. O <strong>empreendedor</strong> dedica tempo e estudo para superar a média. O que não funciona é o esforço pela metade: <strong>o amador que se mexe muito e estuda pouco costuma ficar atrás dos dois</strong>.","tip":"<strong>Como aplicar:</strong> escolha um perfil de propósito e seja fiel a ele. A indecisão entre os dois é mais cara que qualquer dos dois caminhos."},
      {"ic":"gap","t":"Especulação Limitada","emph":"Limitada","b":"Graham não proíbe especular — pede apenas que se faça com os olhos abertos. Reserve para isso <strong>uma conta separada, pequena e que você pode perder inteira</strong> sem abalar o patrimônio sério. O perigo nunca está em arriscar pouco de propósito; está em arriscar muito por engano, misturando a aposta com a poupança da vida.","tip":"<strong>Sinal de alerta:</strong> quem especula convencido de estar se protegendo é o que mais se machuca — porque não dimensiona o risco que não admite estar correndo.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Defina o jogo antes de jogar: investidor ou especulador — e seja coerente.","Investir exige os três pilares juntos; faltando um, é especulação assumida.","Se for especular, faça-o à parte, em valor pequeno e consciente."]},

 {"slug":"ch02-inflacao","sub":"CAPÍTULO 2: O Investidor e a Inflação",
  "intro":"O inimigo do investidor nem sempre derruba a tela com estrondo; às vezes ele trabalha em silêncio. A inflação não faz manchete a cada dia, mas come o poder de compra do dinheiro parado, ano após ano. Por isso 'retorno adequado', para Graham, significa adequado depois de descontada a inflação — o ganho real, não o número nominal que apenas parece maior.",
  "cards":[
      {"ic":"wave","t":"O Retorno Real","emph":"Retorno Real","b":"O que importa não é quantos reais a mais você tem, e sim quanto a mais você consegue comprar com eles. <strong>Render 6% num ano de inflação de 8% é empobrecer com aparência de lucro</strong>. O número nominal engana porque sobe; o número real informa porque mede o que de fato sobrou no fim do mês.","tip":"<strong>Como aplicar:</strong> de todo ganho anunciado, subtraia a inflação antes de comemorar. O resto é ilusão de ótica contábil."},
      {"ic":"triangle","t":"A Proteção Parcial das Ações","emph":"Proteção Parcial","b":"As ações têm uma vantagem real contra a inflação: a empresa repassa preços, e o lucro tende a acompanhar a alta geral. Mas é um escudo imperfeito, não uma garantia. <strong>Em surtos fortes de inflação e juros altos, nem as melhores ações protegem a carteira inteira</strong> — ajudam, sem resolver sozinhas.","tip":"<strong>Modelo mental:</strong> trate ações como hedge parcial, não como vacina. Contar com elas para neutralizar toda a inflação é esperar demais."},
      {"ic":"layers","t":"O Equilíbrio Entre os Dois","emph":"Equilíbrio","b":"Apostar tudo na renda fixa parece prudente e não é: o título 'seguro' devolve o capital intacto em moeda corroída. Apostar tudo em ações expõe ao pânico. Graham prefere <strong>manter os dois lados ao mesmo tempo</strong> — a âncora da renda fixa e o motor das ações — porque cada um defende contra o cenário que arruína o outro.","tip":"<strong>Sinal de alerta:</strong> 'guardar tudo no que é seguro' é a forma mais discreta de perder devagar para a inflação, sem nunca ver a queda na tela.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["Meça todo retorno em termos reais — o nominal mente quando sobe.","Ações protegem contra a inflação em parte, nunca por completo.","Equilibrar ações e renda fixa defende contra cenários opostos."]},

 {"slug":"ch03-historico-do-mercado","sub":"CAPÍTULO 3: Um Século de História do Mercado",
  "intro":"Um século de cotações ensina sempre a mesma lição, e ela quase nunca é aprendida: o mercado oscila entre a euforia e o pânico em ciclos, e o preço que se paga no auge encolhe o retorno que se colhe depois. A história não é uma bola de cristal para adivinhar o próximo pregão — é uma régua para calibrar o que é razoável esperar.",
  "cards":[
      {"ic":"clock","t":"O Preço Determina o Retorno","emph":"O Preço Determina","b":"Na euforia, a multidão paga caro porque está convencida de que vai ficar mais caro ainda. Mas <strong>quanto maior o preço pago hoje, menor o retorno provável de amanhã</strong> — é aritmética, não pessimismo. Os múltiplos altos não anunciam um futuro brilhante; com mais frequência, anunciam um futuro medíocre já contratado no preço.","tip":"<strong>Prática:</strong> quando o mercado celebra recordes, corte expectativas em vez de elevá-las. O entusiasmo geral é o pior momento para esperar muito."},
      {"ic":"spiral","t":"A Reversão à Média","emph":"Reversão à Média","b":"Em toda bolha alguém jura que as velhas regras morreram e um novo paradigma começou. Quase sempre é a véspera da queda. <strong>O que sobe muito além do que os lucros justificam tende a voltar</strong> — não por castigo, mas por gravidade econômica. Os extremos de valuation revertem; quem chegou tarde e na ganância paga a conta.","tip":"<strong>Modelo mental:</strong> a frase 'desta vez é diferente' já antecedeu praticamente todas as grandes perdas da história. Desconfie dela como de um aviso."},
      {"ic":"wave","t":"Disciplina Acima do Ciclo","emph":"Acima do Ciclo","b":"Você pode ajustar a alocação ao termômetro do mercado, mas dentro de limites fixados de antemão. <strong>Aumentar a exposição a ações justamente quando todos compram, no topo eufórico, é entregar a razão à manada</strong>. A defesa não é prever o ciclo; é ter regras que impedem você de agir pior justamente quando a tentação é maior.","tip":"<strong>Armadilha:</strong> carregar mais ações no auge da alta, embalado pelas manchetes otimistas, é o erro clássico — e o mais caro de todos.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["O preço pago hoje determina, em boa medida, o retorno de amanhã.","Extremos de valuation revertem à média; a humildade vence a euforia.","Ajuste a alocação ao ciclo, mas sempre dentro de limites disciplinados."]},

 {"slug":"ch04-investidor-defensivo","sub":"CAPÍTULO 4: A Carteira do Investidor Defensivo",
  "intro":"O investidor defensivo não quer ganhar o máximo; quer não cometer erros graves e poder dormir. Para Graham, esse é um objetivo digno e perfeitamente alcançável — desde que se renuncie ao impulso. A receita é uma carteira simples e equilibrada, governada por regras mecânicas que tomam a decisão no lugar da emoção, exatamente quando a emoção mais quer mandar.",
  "cards":[
      {"ic":"scale","t":"A Carteira Equilibrada","emph":"Equilibrada","b":"O defensivo fixa uma proporção entre ações e renda fixa — Graham sugere algo entre 50/50 e os limites de 25% e 75% — e a respeita. Quando as ações sobem demais, o rebalanceamento as reduz; quando caem, as recompõe. <strong>A regra vende caro e compra barato sozinha, sem pedir coragem ao investidor</strong> no momento em que ele teria menos.","tip":"<strong>Regra:</strong> escreva a proporção-alvo antes da tempestade e obedeça-a durante. O limite que parece rígido é o que segura sua mão longe do precipício."},
      {"ic":"clock","t":"Aportes Regulares","emph":"Aportes Regulares","b":"Em vez de tentar adivinhar o melhor dia para entrar — o que ninguém faz bem — o defensivo aporta sempre o mesmo valor em intervalos fixos. <strong>Comprando à mesma quantia, ele leva menos cotas quando o preço está alto e mais quando está baixo</strong>, na média certa. O método (dollar-cost averaging) troca a aflição de cronometrar o mercado pela serenidade de um calendário.","tip":"<strong>Como aplicar:</strong> automatize o aporte e siga-o ignorando o noticiário. A constância vence o palpite quase sempre."},
      {"ic":"key","t":"Blue Chips e Simplicidade","emph":"Blue Chips","b":"O defensivo prefere as empresas grandes, sólidas e com longo histórico de lucros e dividendos ao fascínio das novidades que prometem o futuro. <strong>Comprar o que já provou pagar por muitos anos vale mais que apostar no que ainda só promete</strong>. Simplicidade aqui não é falta de sofisticação — é a sofisticação de quem sabe o que evitar.","tip":"<strong>Modelo mental:</strong> o conservador olha o histórico de resultados, não a história empolgante. O que cansa de ser repetido é justamente o que protege."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["Mantenha de 25% a 75% em ações, com 50/50 como ponto neutro, e rebalanceie.","Use aportes regulares (dollar-cost averaging) para não depender do timing.","Prefira blue chips sólidas e a simplicidade à complexidade."]},

 {"slug":"ch05-investidor-empreendedor","sub":"CAPÍTULO 5: A Carteira do Investidor Empreendedor",
  "intro":"O investidor empreendedor aceita um trato exigente: dedicar tempo e estudo de verdade para superar a média. Graham aprova — com uma ressalva severa. O esforço só compensa quando guiado por método; mal aplicado, ele destrói valor e fica atrás da carteira passiva que tanto trabalho buscava bater. Atividade não é o mesmo que competência.",
  "cards":[
      {"ic":"lens","t":"Caça às Pechinchas","emph":"Pechinchas","b":"De tempos em tempos o mercado abandona empresas sadias por puro desânimo. É aí que o investidor ativo trabalha: <strong>comprar um negócio sólido por bem menos do que ele vale</strong>. O desconto que vem do pessimismo alheio, e não de um defeito real do negócio, é a pechincha que Graham ensina a procurar — comprar o dólar por cinquenta centavos.","tip":"<strong>Como aplicar:</strong> aja quando a impopularidade derrubar o preço sem derrubar os fundamentos. É a divergência entre os dois que vale dinheiro."},
      {"ic":"gap","t":"As Net-Nets","emph":"Net-Nets","b":"O caso extremo da pechincha: comprar a ação por menos do que a empresa tem em capital de giro líquido — como levar o negócio operacional de brinde. Sozinha, cada uma esconde riscos. <strong>Mas uma cesta diversificada de net-nets dilui os fracassos individuais e deixa o conjunto trabalhar a favor</strong>.","tip":"<strong>Sinal de alerta:</strong> concentrar tudo numa única pechincha desfaz a própria margem de segurança. Net-net se compra aos punhados, nunca uma só.","warn":True},
      {"ic":"target","t":"Esforço com Método","emph":"Esforço com Método","b":"Girar a carteira o tempo todo não prova esperteza; prova apenas custos e impostos comendo o retorno. O bom investidor ativo segue um método rigoroso e o repete. <strong>Sem método comprovado, quanto mais o aventureiro se mexe, mais ele perde</strong> — e teria saído melhor parado, na posição defensiva que desprezou.","tip":"<strong>Regra:</strong> só seja ativo se tiver disciplina e um critério testável. Na dúvida, a posição defensiva é a escolha mais inteligente — e mais difícil de admitir."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Só seja ativo se tiver disciplina e método; do contrário, seja defensivo.","Busque pechinchas e net-nets, sempre com ampla diversificação.","Esforço sem critério rende menos que a estratégia passiva."]},

 {"slug":"ch06-preco-vs-valor","sub":"CAPÍTULO 6: Preço vs. Valor",
  "intro":"Aqui está a distinção que funda todo o value investing, simples de dizer e difícil de viver: preço é o que você paga; valor é o que você recebe. O mercado grita um preço novo a cada segundo, mas o valor de um bom negócio muda devagar, ao ritmo dos lucros. Investir bem é, no fundo, explorar o intervalo entre essas duas velocidades.",
  "cards":[
      {"ic":"scale","t":"Preço Não É Valor","emph":"Preço Não É Valor","b":"O preço na tela é o humor da multidão de hoje. O valor é a capacidade real do negócio de gerar caixa ao longo dos anos. <strong>Confundir os dois é o erro que arruína o investidor apressado</strong>, que compra caro porque está subindo e vende barato porque está caindo. Compre quando o valor supera o preço com folga — não antes.","tip":"<strong>Como aplicar:</strong> fuja do que está caro pela moda e procure o sólido que anda esquecido. O desconforto de comprar o impopular é o preço da pechincha."},
      {"ic":"wave","t":"Votação e Balança","emph":"Votação e Balança","b":"Graham resume o mercado numa imagem que ficou: <strong>no curto prazo ele é uma máquina de votação — pesa popularidade; no longo prazo, uma balança — pesa valor real</strong>. A cotação de hoje conta quantos votos a ação tem; os anos contam quanto ela vale. Aposte no veredito lento da balança, não no aplauso de uma sessão.","tip":"<strong>Modelo mental:</strong> a empresa boa e esquecida tende a vencer a queridinha cara — basta dar tempo à balança para trabalhar."},
      {"ic":"lens","t":"Valor em Faixa, Não em Ponto","emph":"Valor em Faixa","b":"Calcular o valor intrínseco até o último centavo é fingir precisão onde só há incerteza. O futuro não se mede a régua. <strong>Estime o valor por uma faixa ampla, ancorada nos números verificáveis do balanço de hoje</strong>, e exija que o preço caia bem abaixo dela antes de agir.","tip":"<strong>Regra:</strong> desconfie de projeções otimistas para um futuro distante; prefira o patrimônio sólido que você consegue contar agora."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Preço e valor são coisas distintas; o lucro mora na divergência.","No curto prazo manda a emoção; no longo, o fundamento.","Estime valor por faixas amplas, nunca por números exatos ilusórios."]},

 {"slug":"ch07-sr-mercado","sub":"CAPÍTULO 7: A Alegoria do Sr. Mercado",
  "intro":"Imagine ter um sócio chamado Sr. Mercado. Todo dia ele aparece e lhe oferece um preço — para comprar sua parte ou vender a dele. O problema é que ele é instável: hoje eufórico e pedindo uma fortuna, amanhã apavorado e quase implorando para você levar tudo. A genialidade de Graham não está em corrigir esse sócio, e sim em lembrar que você pode simplesmente não atender — e lucrar exatamente com a loucura dele.",
  "cards":[
      {"ic":"person","t":"Servo, Não Guia","emph":"Servo, Não Guia","b":"O Sr. Mercado existe para servir você, jamais para orientá-lo. <strong>Aproveite os dias de pânico dele para comprar barato e os de euforia para vender caro — nos demais, ignore-o</strong>. Ele tem o direito de gritar qualquer preço; você tem o direito, muito mais valioso, de não responder. A cotação é dele; o juízo de valor é seu.","tip":"<strong>Como aplicar:</strong> feche a porta nos dias mornos e só atenda quando o preço estiver claramente absurdo — para mais ou para menos."},
      {"ic":"spark","t":"A Volatilidade É Amiga","emph":"Volatilidade É Amiga","b":"Para quem persegue a cotação diária, a oscilação é tormento. Para o investidor disciplinado, é presente. <strong>Cada queda forte é o Sr. Mercado oferecendo bons negócios a preço de liquidação</strong>. A volatilidade só fere quem a obedece; para quem a usa, ela é a própria fonte das pechinchas.","tip":"<strong>Modelo mental:</strong> a queda muda o preço da ação, não o valor da empresa por trás dela. A fábrica continua a mesma — só a etiqueta mudou."},
      {"ic":"mask","t":"Não Contagie Sua Emoção","emph":"Sua Emoção","b":"O risco do Sr. Mercado não é o que ele faz — é o que ele provoca em você. <strong>Entrar em pânico junto na queda, ou comprar com avidez no topo só porque ele está animado, é deixar o sócio instável governar o seu juízo</strong>. Quando o humor dele vira o seu, ele venceu.","tip":"<strong>Sinal de alerta:</strong> a urgência de agir a cada oscilação da tela é o sintoma de quem entregou o leme. A boa resposta, quase sempre, é nenhuma.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["O Sr. Mercado oferece preços, não verdades — você decide quando agir.","Use a volatilidade a seu favor: compre no pânico, ignore a euforia.","Sua riqueza depende do negócio que você possui, não da cotação de hoje."]},

 {"slug":"ch08-margem-de-seguranca","sub":"CAPÍTULO 8: A Margem de Segurança",
  "intro":"Se toda a sabedoria do investimento tivesse de caber em três palavras, Graham escolheria: margem de segurança. Comprar com desconto suficiente sobre o valor intrínseco para que um erro de estimativa, um azar ou um imprevisto não se transformem em perda permanente. É o fio que separa o investimento da aposta — e a única ideia que ele pede para você jamais esquecer.",
  "cards":[
      {"ic":"scale","t":"A Folga É a Proteção","emph":"A Folga","b":"A margem é a distância deliberada entre o que algo vale e o que você paga. <strong>Quanto maior essa folga, mais espaço você tem para errar sem se arruinar</strong>. É a aplicação de uma regra de engenharia ao dinheiro: projeta-se a ponte para muito mais peso do que jamais vai cruzá-la, porque o desastre não avisa.","tip":"<strong>Como aplicar:</strong> se a empresa vale cem, não compre por noventa — espere, mesmo entediado, até o preço cair a sessenta ou setenta. O desconto é a margem."},
      {"ic":"key","t":"A Margem Absolve o Erro","emph":"Absolve o Erro","b":"A margem existe porque a razão humana falha — suas contas vão errar, e os imprevistos vão acontecer. <strong>Ela é o amortecedor que transforma um erro de julgamento num prejuízo suportável, em vez de uma perda irreparável</strong>. Sobreviver aos erros é a condição para colher os acertos depois.","tip":"<strong>Modelo mental:</strong> concentre-se em não ser destruído. O lucro tende a aparecer sozinho para quem garantiu primeiro a sobrevivência."},
      {"ic":"layers","t":"Margem e Diversificação","emph":"Margem e Diversificação","b":"Mesmo a compra mais barata pode dar errado por motivos que ninguém previu. Por isso o desconto sozinho não basta. <strong>Espalhar o capital por várias posições faz com que o fracasso de uma seja absorvido pelo acerto das demais</strong>. Margem e diversificação são as duas metades do mesmo escudo.","tip":"<strong>Armadilha:</strong> um desconto enorme numa única ação não substitui a diversificação. Apostar tudo numa só pechincha desfaz a própria margem que ela oferecia.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Nunca compre sem margem de segurança — é o filtro central de Graham.","A margem protege contra seus próprios erros, não contra a volatilidade.","Combine margem e diversificação: juntas, absorvem o imprevisível."]},

 {"slug":"ch09-temperamento-e-disciplina","sub":"CAPÍTULO 9: Temperamento e Disciplina",
  "intro":"Aqui Graham revela a tese que sustenta todas as outras: investir bem é, antes de tudo, uma questão de caráter, não de inteligência. O maior inimigo do investidor não é o mercado, nem a concorrência — é ele próprio, com seu medo e sua ganância. Por isso a meta não é prever o futuro, e sim proteger-se das próprias reações quando o futuro chegar.",
  "cards":[
      {"ic":"mountain","t":"Temperamento Vence o QI","emph":"Temperamento","b":"O investidor mais brilhante quebra se entrar em pânico na hora errada; o medíocre prospera se mantiver a cabeça fria. <strong>Não é o intelecto que decide o resultado, e sim o autocontrole no momento da dor</strong>. Vence quem consegue cumprir o próprio plano justamente quando o instinto do rebanho grita para abandoná-lo.","tip":"<strong>Como aplicar:</strong> escreva suas regras de investimento nos dias de calma — e siga-as, sem reabrir a discussão, nos dias de desespero."},
      {"ic":"clock","t":"Regras Acima de Previsões","emph":"Regras","b":"Tentar adivinhar o próximo movimento do mercado consome tempo e quase sempre erra. Graham propõe o contrário: <strong>montar um sistema de decisões que funcione sozinho, sem depender do seu palpite a cada virada</strong>. A regra escrita substitui a aposta nervosa pela disciplina que não precisa de coragem todo dia.","tip":"<strong>Sinal de alerta:</strong> se você passa os fins de semana traçando previsões, é sinal de que falta um método — e sobra ansiedade no lugar dele.","warn":True},
      {"ic":"key","t":"A Paciência É a Tática","emph":"A Paciência","b":"Boa parte do trabalho do investidor é não fazer nada. <strong>Recusar-se a vender posições sólidas no meio do pânico preserva o que levou anos para construir</strong>. Romper o plano na pior hora desfaz, num momento de medo, a colheita de muito tempo de disciplina. Esperar não é ociosidade — é a parte mais difícil da estratégia.","tip":"<strong>Modelo mental:</strong> quietude exige mais nervo do que ação. Ficar parado enquanto todos correm é a tática, não a falta dela."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["Temperamento vence QI: o inimigo a domar é o próprio comportamento.","Não tente prever o mercado; proteja-se das suas reações emocionais.","Regras escritas e paciência são as armas centrais do investidor inteligente."]},

 {"slug":"ch10-analise-de-empresas","sub":"CAPÍTULO 10: Análise e Seleção de Ações",
  "intro":"Para encontrar valor com margem de segurança, Graham não pede genialidade — pede critérios. Propõe filtros quantitativos, conservadores e verificáveis, que qualquer investidor disciplinado consegue aplicar. A análise não procura a empresa mais empolgante; procura a sólida, comprada por um preço modesto. O brilho fica para os outros.",
  "cards":[
      {"ic":"lens","t":"O Filtro dos Números","emph":"Filtro dos Números","b":"O bom defensivo confia no balanço, não na história contada pela diretoria. Olha o <strong>histórico longo de lucros e a folga do capital de giro</strong> — saúde já demonstrada, não promessa futura. Comprar fundamento comprovado dispensa as projeções deslumbrantes que sustentam os múltiplos absurdos.","tip":"<strong>Como aplicar:</strong> prefira a empresa entediante com caixa forte à empresa empolgante e endividada. O tédio costuma pagar melhor."},
      {"ic":"scale","t":"Teto para os Múltiplos","emph":"Teto","b":"Para não pagar caro, Graham impõe limites simultâneos: <strong>um teto para o preço sobre o lucro (P/L) e outro para o preço sobre o patrimônio (P/VPA)</strong>. As duas barreiras juntas barram a ação inflada que parece sólida só porque está subindo. A disciplina aqui não é cálculo difícil — é recusar o preço alto.","tip":"<strong>Regra:</strong> a virtude não está na fórmula complexa, e sim na matemática singela de pagar barato pelos números concretos."},
      {"ic":"key","t":"A Dívida Sob Controle","emph":"A Dívida","b":"A alavancagem é o que derruba a empresa boa na hora ruim. Companhias sólidas <strong>geram lucro que cobre os juros com folga larga</strong>; é essa folga que sustenta a segurança do principal. Ignorar o endividamento é admirar a fachada sem ver que ela se apoia em crédito que pode secar.","tip":"<strong>Sinal de alerta:</strong> lucro vistoso erguido sobre muita dívida cobra a conta de uma vez, justamente quando o crédito encurta.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 10",
  "lessons":["Selecione por solidez financeira, histórico estável e múltiplos baixos.","Combine P/L e P/VPA moderados para limitar o sobrepreço.","Lucros que cobrem a dívida com folga sustentam a segurança do principal."]},
]
