# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Os Jogos da Vida' (Eric Berne)."""

BOOK = {
  "title": "Os Jogos da Vida",
  "author": "Eric Berne",
  "header_light": "JOGOS",
  "header_bold": "DA VIDA",
  "subtitle": "VISÃO GERAL · AS TRANSAÇÕES QUE REPETEM A MESMA DOR",
  "intro": "Eric Berne, psiquiatra, fez à sua profissão uma pergunta constrangedora: por que pessoas inteligentes repetem, a vida toda, as mesmas brigas estúpidas? Sua resposta desmonta o romance que contamos sobre nós mesmos — boa parte do que chamamos de relacionamento é <em>jogo</em>: uma transação de duplo-fundo, com isca, vítima voluntária e um final já escrito. Cada um sai magoado, e era exatamente isso que se foi buscar. O sofrimento, descobre Berne, não é acidente: é a recompensa.",
  "description": "Os Jogos da Vida de Eric Berne em cheat sheet: os estados de ego Pai-Adulto-Criança, as transações complementares/cruzadas/ulteriores, as carícias e a fome de reconhecimento que faz preferir a briga ao silêncio, a Fórmula J (Isca+Fraqueza→Resposta→Virada→Confusão→Recompensa), os jogos clássicos ('Sim, mas', 'Se Não Fosse Por Você', 'Chuta-me', 'Tribunal') e a única saída honesta — a autonomia.",
  "tags": ["Psicologia", "Relacionamentos", "Autoconhecimento"],
  "progress": "9 Capítulos",
  "cover": "assets/jogos-da-vida-cover.png",
  "overview_cards": [
    {"ic":"triangle","t":"Quem Está Falando Agora?","b":"Você não é um, é três, e eles se revezam ao microfone. O <strong>Pai</strong> repete o que ouviu dos pais ('você deve, sempre, nunca'); o <strong>Adulto</strong> é o computador que mede o aqui-e-agora sem paixão; a <strong>Criança</strong> é a fita das emoções de quando você tinha cinco anos. A primeira pergunta da Análise Transacional não é 'o que você sente?', e sim <strong>'quem dentro de você está falando agora?'</strong>","tip":"<strong>Diagnóstico rápido:</strong> 'você nunca presta atenção!' = Pai. 'São 14h, falta 1 hora' = Adulto. 'Não é justo!' = Criança.","wide":True},
    {"ic":"spiral","t":"A Fórmula J","b":"Toda briga que se repete obedece à mesma equação: <strong>Isca + Fraqueza → Resposta → Virada → Confusão → Recompensa</strong>. O coração da coisa é a <strong>Virada</strong> — o instante em que os papéis trocam de lugar sem aviso e cada jogador recolhe, pontual, o sentimento ruim que veio buscar. O barraco não descarrilou: ele chegou exatamente onde ia chegar.","tip":"<strong>Regra diagnóstica:</strong> se a Fórmula J encaixa, é jogo; se não encaixa, não é. Use-a como bisturi sobre qualquer padrão que não para de voltar."},
    {"ic":"key","t":"A Saída: Autonomia","b":"O antídoto de Berne tem três nomes: <strong>consciência</strong> (enxergar o jogo enquanto ele rola), <strong>espontaneidade</strong> (escolher a resposta em vez de cuspir a automática) e <strong>intimidade</strong> (relação sem duplo-fundo). Sair de um jogo nunca é vencer o adversário — é recusar a isca e deixá-lo segurando a vara sozinho.","tip":"<strong>Como aplicar:</strong> nomeie o jogo, negue a fraqueza que ele explora e vá buscar reconhecimento na fonte limpa — intimidade real no lugar da recompensa envenenada."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-analise-estrutural",
    "sub": "CAPÍTULO 1: Análise Estrutural — Os Estados de Ego",
    "intro": "A personalidade não é uma peça inteiriça: a cada minuto falamos a partir de um entre três estados de ego, e a maioria das pessoas vive sem saber qual delas pegou o microfone. Aprender a flagrar quem está no comando é o abecedário da Análise Transacional — e quase todo o resto do livro é só a aplicação dele.",
    "cards": [
      {"ic":"triangle","t":"As Três Vozes Internas","emph":"Três Vozes","b":"O Pai dá ordens emprestadas dos seus pais. A Criança é a relíquia viva das emoções de quem você foi aos cinco anos — ora obediente, ora birrenta. E o Adulto é o computador que processa o agora sem febre. São três fitas tocando ao mesmo tempo dentro do crânio, mas só uma vai ao ar: <strong>você nunca fala 'em geral', você fala sempre por um deles</strong>.","tip":"<strong>Como aplicar:</strong> na sua próxima resposta acalorada, pare meio segundo e pergunte — quem está respondendo, a Criança magoada ou o Adulto que vê os fatos?"},
      {"ic":"lens","t":"O Filtro Que Mente","emph":"Filtro","b":"O problema não são os três estados — é a fita errada tocando na hora errada. Na <strong>contaminação</strong>, o medo da Criança invade o Adulto vestido de 'preocupação lógica', e você jura que está sendo racional quando está só com susto. Na <strong>exclusão</strong>, você tranca um estado no porão: quem sufocou a própria Criança esqueceu como se ri à toa.","tip":"<strong>Modelo mental:</strong> Adulto saudável não amputa o Pai nem a Criança — ele fica na mesa de som e decide o volume de cada um."},
      {"ic":"bubble","t":"O Raio-X Pelo Tom","emph":"Raio-X","b":"O corpo entrega a fonte antes de a frase terminar. O dedo em riste e o vocabulário de sentença denunciam o Pai Crítico; a voz que encolhe ou o choro que estoura acusam a Criança. Por isso o diagnóstico não mora no <em>que</em> se diz: mora <strong>no tom, na postura e na história de quem está dizendo</strong>.","tip":"<strong>Regra:</strong> antes de reagir ao conteúdo, adivinhe a assinatura. Quem assinou esta mensagem — Pai, Adulto ou Criança? A resposta muda a sua."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["A personalidade é P + A + C: os três são normais e necessários — o problema é quem fala fora de hora.", "Diagnostique pelo tom e pela palavra antes de adivinhar a intenção; a fonte importa mais que o conteúdo.", "O Adulto não elimina o Pai e a Criança — ele os administra. Contaminação e exclusão são onde o sofrimento começa."],
  },
  {
    "slug": "ch02-analise-transacional",
    "sub": "CAPÍTULO 2: Análise Transacional — Os Três Tipos",
    "intro": "Conversar é trocar estímulo por resposta, estado de ego por estado de ego — essa é a unidade do relacionamento. Há três tipos de troca, e o terceiro, a ulterior, é o terreno escuro de onde brota cada jogo deste livro.",
    "cards": [
      {"ic":"link","t":"As Linhas Cruzadas","emph":"Cruzadas","b":"Na transação complementar você joga a bola e ela volta na mesma altura: a conversa pode seguir para sempre. Na cruzada, alguém devolve de um estado que você não chamou — você pergunta a hora (Adulto) e leva um 'por que você sempre me cobra?' (Criança ferida). Repare: <strong>quase toda briga da sua vida é uma linha telefônica que se cruzou sem que ninguém notasse</strong>.","tip":"<strong>Como aplicar:</strong> quando o ataque descer de um Pai agressivo, não suba a Criança magoada para receber — devolva a ligação pelo Adulto, com a frieza de quem só constata."},
      {"ic":"eye","t":"A Armadilha Do Duplo-Fundo","emph":"Duplo-Fundo","b":"A transação ulterior dispara dois tiros de uma vez: um social, educado e na superfície, e um psicológico, escondido no porão — o sarcasmo, a sedução, a alfinetada. E aqui está a chave de toda a obra: <strong>o desfecho da conversa é sempre decidido no porão, nunca na vitrine das palavras</strong>. O que parece estar em jogo raramente é o que está em jogo.","tip":"<strong>Sinal de alerta:</strong> em negócios, flertes e discussões que se repetem, escute com o terceiro ouvido. A frase é a cortina de fumaça; o recado verdadeiro vem por baixo dela.","warn":True},
      {"ic":"triangle","t":"A Isca Da Venda","emph":"Isca","b":"O vendedor sorri: 'este é o melhor, mas talvez o senhor prefira o básico, para economizar'. A frase social é prudência; o recado psicológico mira em cheio o seu orgulho. E a sua Criança pula da cadeira — 'eu tenho dinheiro para o melhor!' — e assina o cheque. Você não foi convencido: <strong>você mordeu o anzol disfarçado de gentileza</strong>.","tip":"<strong>Prática:</strong> sempre que uma fala inocente acender em você a urgência de provar o seu valor, pare. A isca acaba de cair na água — não é hora de morder."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["Complementares fluem, cruzadas rompem — toda briga é uma linha que se cruzou sem ninguém perceber.", "A ulterior tem duplo-fundo: quem decide o resultado é o nível psicológico, não o social.", "Cruzar a linha de propósito, pelo Adulto, é a ferramenta para travar um padrão antes que ele te arraste."],
  },
  {
    "slug": "ch03-estruturacao-do-tempo",
    "sub": "CAPÍTULO 3: A Estruturação do Tempo e as Carícias",
    "intro": "Antes da fome de comida vem outra, mais antiga: a fome de ser notado. O bebê não acariciado definha; o adulto não reconhecido enlouquece. Para saciar essa fome — e tapar os buracos do tédio — passamos a vida estruturando o tempo de seis maneiras, da mais segura e morna à mais arriscada e viva.",
    "cards": [
      {"ic":"spark","t":"A Moeda Da Sobrevivência","emph":"Moeda","b":"A 'carícia' (stroke) é a unidade de reconhecimento: o ato de dizer ao outro 'eu vejo que você existe'. E aqui mora a lei mais dura da psicologia humana: <strong>uma carícia negativa vale mais que carícia nenhuma</strong>. Insulto, grito e briga são todos preferíveis ao silêncio do esquecimento. É por isso que se joga sujo — a briga garante, na hora, a prova de que o outro ainda está ali.","tip":"<strong>Como aplicar:</strong> da próxima vez que sentir vontade de provocar uma crise, pergunte que carícia torta você foi caçar. O alvo quase nunca é vencer — é ser notado."},
      {"ic":"steps","t":"A Escada Do Risco","emph":"Escada","b":"As seis formas são degraus, do seguro ao exposto: o <strong>retraimento</strong> não arrisca nada; os <strong>rituais</strong> ('tudo bem?') rendem trocados; passatempos e trabalho consomem as horas em segurança morna. Os <strong>jogos</strong> servem um banquete de emoção — mas a conta vem em sofrimento. No último degrau, sozinha, está a <strong>intimidade</strong>: o máximo de carinho real pelo preço de ficar sem escudo.","tip":"<strong>Modelo mental:</strong> divida a sua semana. Quantas horas você passa fugindo da dor nos degraus mornos — e quantas no terreno aberto onde se pode amar e se pode levar um tombo?"},
      {"ic":"gap","t":"A Sondagem Dos Queixosos","emph":"Sondagem","b":"As conversas frouxas sobre 'como o governo rouba' ou 'como os homens não prestam' não são desabafo inocente — são recrutamento. <strong>O passatempo do queixume é um sonar: você lança a rede para descobrir quem topa embarcar num jogo futuro</strong> de autopiedade e revolta que não muda nada. Quem reclama junto com você está se candidatando a parceiro de jogo.","tip":"<strong>Sinal de alerta:</strong> desconfie do grupo cuja única cola é chorar as mágoas em coro. A vitimização compartilhada é das drogas sociais mais viciantes que existem.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["Precisamos de carícias como de comida: a privação total de reconhecimento adoece o corpo e a mente.", "Carícia negativa vence ausência de carícia — e é daí que nascem os jogos dolorosos.", "As 6 formas vão do retraimento à intimidade; os passatempos são a peneira que seleciona parceiros de jogo."],
  },
  {
    "slug": "ch04-os-jogos",
    "sub": "CAPÍTULO 4: Os Jogos — Definição e Anatomia",
    "intro": "Cuidado com a palavra 'jogo': não há diversão nenhuma aqui. Jogo, para Berne, é uma série de transações de duplo-fundo com um trambique embutido e um final tão previsível quanto amargo. Neste capítulo ele dá a definição exata, monta a Fórmula J e entrega o bisturi para dissecar qualquer padrão que insista em voltar.",
    "cards": [
      {"ic":"spiral","t":"O Diagnóstico Do Jogo","emph":"Diagnóstico","b":"Todo jogo roda na mesma engrenagem. O iniciador lança a <strong>Isca</strong>, fisgada pela <strong>Fraqueza</strong> do outro; segue a troca de aparência inocente, até a rasteira súbita da <strong>Virada</strong> e o instante de <strong>Confusão</strong> em que ninguém entende o que aconteceu. E então o <strong>Payoff</strong>: cada um recolhe, em silêncio, aquele sentimento ruim de sempre — e vai dormir sabendo que tinha razão sobre a vida.","tip":"<strong>Regra:</strong> barraco que se repete não é azar, é maquinário de precisão. Se a cena encaixa nos 6 passos, você não está numa briga — está dentro de uma máquina. Desligue-a."},
      {"ic":"key","t":"O Tesouro Da Moeda Torta","emph":"Tesouro","b":"Os jogos arruínam casamentos, e mesmo assim ninguém os larga — porque pagam bem. Eles dão estrutura ao tempo, blindam contra o risco da intimidade e, sobretudo, <strong>confirmam a velha mentira que você conta sobre si mesmo</strong> ('ninguém me entende', 'eu sempre me ferro'). Colecionar mágoas é juntar cupons: no fim, com o talão cheio, você pode explodir e ainda se sentir com toda a razão.","tip":"<strong>Modelo mental:</strong> o sofrimento crônico costuma ter um lucro escondido. A pessoa não solta o jogo porque ele é a muralha contra um vazio que assusta muito mais."},
      {"ic":"target","t":"Desarmando A Bomba","emph":"Desarmando","b":"A saída se chama antítese, e ela é fria, não agressiva. <strong>Você simplesmente se recusa a dar o passo final que a peça do outro precisa</strong>: não morde a isca de controle, não dá o conselho que pediram para depois recusar. Atacar o jogador é só mais uma jogada dentro do jogo. Tirar a corrente da tomada, em silêncio, é o que mata o circuito.","tip":"<strong>Como aplicar:</strong> diante da isca de drama, o veneno certo é o silêncio lúcido do Adulto. Não revide — recuse a sua deixa, e o jogo morre por falta de elenco."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["Jogo = transações ulteriores + payoff previsível, jogado em boa parte fora da consciência.", "A Fórmula J disseca qualquer jogo em 6 peças — use-a como ferramenta de diagnóstico, não de acusação.", "A saída é a antítese: recuse a isca e o seu próprio papel; atacar o jogador é continuar jogando."],
  },
  {
    "slug": "ch05-jogos-da-vida",
    "sub": "CAPÍTULO 5: Jogos do Dia a Dia",
    "intro": "Os jogos mais comuns não acontecem em divã: acontecem na cozinha e no escritório, com uma destreza que ninguém admite ter. São os clássicos domésticos — os que terceirizam a culpa, blindam o ego e, no fundo, servem para fugir do risco de uma intimidade de verdade.",
    "cards": [
      {"ic":"fork","t":"O Álibi Da Culpa","emph":"Álibi","b":"Em 'Se Não Fosse Por Você', a pessoa escolhe a dedo um parceiro controlador — e depois passa a vida reclamando que ele a impede de viver. Mas a proibição do outro é justamente o presente que ela foi buscar: <strong>um álibi perfeito para nunca ter de encarar o abismo de decidir e se expor por conta própria</strong>. O carcereiro não é o vilão da história — é o cúmplice contratado.","tip":"<strong>Sinal de alerta:</strong> quem vive culpando os limites que os outros lhe impõem costuma esconder um pavor secreto de andar com as próprias pernas.","warn":True},
      {"ic":"masks","t":"A Cortina Das Interrupções","emph":"Cortina","b":"Em 'Olha o Que Você Me Fez Fazer', basta um errinho de concentração e a fatura da culpa voa para o colega que passou por perto. É o jogo de quem precisa do ego sem um arranhão — qualquer falha tem de ser obra de outro. O ganho é o perdão garantido; <strong>o preço, pago em silêncio, é um isolamento que vai apertando o cerco</strong>.","tip":"<strong>Como aplicar:</strong> não assine a culpa que tentam te transferir. O jogo só recruta quem aceita, calado, o papel de réu."},
      {"ic":"wave","t":"Fúria Para Não Sentir","emph":"Fúria","b":"No 'Esquentadinho', o casal sobe o tom até bater porta e dormir em quartos separados, de cara virada. A fúria é ensurdecedora — e é exatamente esse o serviço dela: <strong>uma trincheira erguida às pressas para impedir a aproximação e o sexo</strong>. O objetivo nunca foi a discussão; era a recusa. A briga apenas forneceu a desculpa respeitável.","tip":"<strong>Prática:</strong> nomear o jogo em silêncio no instante em que ele começa já tira o ator automático do palco — e devolve a direção da cena ao seu Adulto."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["'Se Não Fosse Por Você' converte a proibição do outro em álibi para a própria covardia.", "'Olha o Que Você Me Fez Fazer' salva o ego ao custo de afastar todos — não assine a culpa.", "'Esquentadinho' usa a briga para fugir da intimidade: o conflito é o meio, e a recusa é o fim."],
  },
  {
    "slug": "ch06-jogos-conjugais-sociais",
    "sub": "CAPÍTULO 6: Jogos Conjugais e Sociais",
    "intro": "Casamento e vida social são estufa de jogos. 'Tribunal' anda atrás de um juiz que dê razão; 'Sim, mas' fareja conselhos só para fuzilá-los; 'Defeito' rebaixa o outro para subir na própria estima. Reconhecer cada um — e recusar o papel que ele te oferece — já é metade da antítese.",
    "cards": [
      {"ic":"scale","t":"O Terceiro De Muleta","emph":"Muleta","b":"Quando a dor a dois vira disputa crônica, o casal arrasta o problema para o 'Tribunal' e recruta um árbitro: o pai, o filho, o terapeuta. Repare que ninguém ali quer mais resolver o racha — <strong>os dois querem é seduzir a plateia e ouvir quem está com a razão</strong>. E o árbitro perde no exato segundo em que comete o erro de bater o martelo.","tip":"<strong>Regra:</strong> não seja juiz da arena dos outros. A única postura que cura é devolver o abacaxi ao colo de quem o trouxe — e sair da quadra."},
      {"ic":"bubble","t":"Conselhos Na Fogueira","emph":"Conselhos","b":"Em 'Por Que Você Não — Sim, Mas', a pessoa abre um problema e fuzila, um a um, todos os conselhos que recebe, sempre com a lâmina do 'sim, mas...'. A meta secreta nunca foi resolver nada — foi <strong>esgotar quem tentou ajudar, para provar a velha tese de que 'nada funciona e ninguém me entende'</strong>. O troféu do jogo é o silêncio exausto da sala.","tip":"<strong>Como aplicar:</strong> o antídoto de ouro é fechar o balcão de conselhos. Depois do terceiro 'sim, mas', devolva a bola, sem calor: 'E o que você pretende fazer?'"},
      {"ic":"eye","t":"Beco Sem Saída","emph":"Beco","b":"Um parceiro estende um laço; você se aproxima — e ele aperta o nó, porque aproximar-se era a cilada. No 'Encurralado', cada opção do cardápio (agir ou ficar quieto) já vem com censura e desprezo embutidos. É um <strong>duplo vínculo que paralisa, armado por uma Criança interna furiosa</strong> que precisa que você erre faça o que fizer.","tip":"<strong>Sinal de alerta:</strong> se você é punido sem falta por qualquer atitude que escolha, não está num desentendimento — está pisando no asfalto quente de um manipulador.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["'Tribunal' caça um juiz que dê razão — recuse o papel de árbitro e o jogo perde o palco.", "'Sim, mas' não quer solução: a antítese é parar de aconselhar e devolver 'o que você pretende fazer?'.", "'Encurralado' é duplo vínculo — nomeá-lo em voz alta quebra o feitiço de 'errar faça o que fizer'."],
  },
  {
    "slug": "ch07-jogos-do-submundo",
    "sub": "CAPÍTULO 7: Jogos do Submundo — Os Graus Pesados",
    "intro": "Aqui os jogos endurecem. São os de quem cobra dívidas, coleciona raiva e se autopune — e os graus sobem: alguns terminam em ruína, outros no tribunal ou no hospital. Não é mais brincadeira de sala; reconhecê-los a tempo deixa de ser refinamento e vira urgência.",
    "cards": [
      {"ic":"triangle","t":"Colecionando Pancadas","emph":"Pancadas","b":"Há vidas inteiras jogadas no 'Chuta-me': a pessoa arma a cena, fura as regras que não deveria furar, provoca no limite — tudo para <strong>obrigar a autoridade ou o colega a humilhá-la</strong>. A pancada que vem não é fracasso: é confirmação. Prova que o mundo cruel nunca falha. E, por mais estranho que pareça, a punição certa conforta mais que a incerteza.","tip":"<strong>Sinal de alerta:</strong> quando alguém parece convidar o destino a surrá-lo, repare bem — e resista à tentação de fazer a vontade dele. Punir é entrar no jogo.","warn":True},
      {"ic":"sword","t":"A Fúria Engarrafada","emph":"Fúria","b":"O jogador de 'Agora Te Peguei, Desgraçado' guarda mágoas como quem guarda munição seca, esperando. Finge paciência até a vítima cometer um deslize burocrático mínimo — e então estoura, num exagero que não cabe na ofensa. <strong>A falhinha de nada vira a licença dourada para a vingança total e barulhenta</strong> que ele queria dar desde o começo.","tip":"<strong>Como aplicar:</strong> quem narra com gosto as suas vitórias rancorosas sobre os erros dos outros joga este jogo. Negue-lhe o tropeço fácil que ele está farejando."},
      {"ic":"mask","t":"O Trunfo Da Deficiência","emph":"Trunfo","b":"Na 'Pata-de-Pau', a pessoa ergue o próprio trauma — a infância dura, a neurose diagnosticada — como um escudo à prova de balas. 'O que se pode esperar de alguém com a minha história?' Assim ela congela o próprio crescimento e compra uma <strong>licença vitalícia de vítima insolvente</strong>, exigindo indulgência justo onde deveria exigir de si mesma uma mudança.","tip":"<strong>Modelo mental:</strong> acolher a dor de uma tragédia é dever; aceitar que a dor dispensa o sujeito de crescer é assinar a perpetuação da doença."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["'Chuta-me' busca a punição que confirma o roteiro — não morda a isca cedendo ao impulso de punir.", "'Agora Te Peguei' coleciona ofensas para justificar a fúria — não forneça o erro que ele espera.", "'Pata-de-Pau' troca crescimento por isenção — compadeça-se da dor, mas não conceda a licença vitalícia."],
  },
  {
    "slug": "ch08-alem-dos-jogos-autonomia",
    "sub": "CAPÍTULO 8: Além dos Jogos — Roteiros e Autonomia",
    "intro": "Os jogos não são acidentes avulsos: cada um serve a um roteiro de vida que foi rabiscado na primeira infância e que você passou a vida confirmando. Crescer, para Berne, é largar o roteiro e os jogos rumo à autonomia — viver com consciência, espontaneidade e intimidade, sem libreto.",
    "cards": [
      {"ic":"spiral","t":"O Final Já Escrito","emph":"Final","b":"Você acha que improvisa, mas a sua vida segue um <strong>libreto invisível escrito na primeira infância</strong> — os atos finais já estavam rascunhados antes de você saber ler. E os jogos que você repete sem cansar são os tijolos que seguram esse roteiro de pé. Por isso quebrar a inércia dos dias dói: é entrar em guerra com a própria fundação.","tip":"<strong>Prática:</strong> pergunte que final os seus fracassos repetidos estão tão caprichosamente garantindo. Depois, no instante em que o impulso de sempre falar, rasgue a página."},
      {"ic":"key","t":"Os Tronos Da Convicção","emph":"Tronos","b":"Sob cada roteiro há uma tese sobre o mundo, escolhida cedo e raramente revista. Muitos vivem ajoelhados diante de 'eu não presto e você presta', ou 'eu presto e você é que não'. Trocar de parceiro ou de emprego sem mexer nessa tese é só mudar os móveis da mesma cela. O único chão firme é o mais difícil de pisar: <strong>Eu OK – Você OK</strong>.","tip":"<strong>Modelo mental:</strong> o comportamento doente é só o sintoma. A raiz é a Posição de vida negativa que você aceitou — e que pode, com trabalho, recusar."},
      {"ic":"constellation","t":"O Prédio Da Autonomia","emph":"Autonomia","b":"O prêmio que quebra os ciclos e devolve as suas horas se ergue sobre três pilares. A <strong>consciência</strong>, que vê o aqui-e-agora sem véu; a <strong>espontaneidade</strong>, que escolhe a resposta em vez de cuspir a do medo; e a <strong>intimidade</strong>, a coragem de uma relação sem tramoia nem disfarce protetor. Não é um estado que se atinge — é uma capacidade que se exercita.","tip":"<strong>Regra:</strong> espontaneidade não é descontrole. É o domínio fino sobre qual voz interna assume o microfone na fração de segundo em que você decide."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Os jogos servem a um roteiro de vida inconsciente — mudar as cenas exige mudar o roteiro.", "O alvo é a Posição de vida ('Eu OK – Você OK'), não apenas corrigir o comportamento de fora.", "Autonomia = consciência + espontaneidade + intimidade. É para onde toda a Análise Transacional aponta."],
  },
  {
    "slug": "ch09-intimidade-saida",
    "sub": "CAPÍTULO 9: Intimidade — A Saída dos Jogos",
    "intro": "No topo da escada, sozinha, está a intimidade — a sexta e última forma de estruturar o tempo, e a mais rara de todas. É a relação espontânea, sem jogo nem exploração: o máximo de reconhecimento verdadeiro que dois humanos podem trocar. E é justamente isto que todos os jogos, no fundo, tentam imitar sem nunca alcançar.",
    "cards": [
      {"ic":"leaf","t":"O Abismo Necessário","emph":"Abismo","b":"A intimidade verdadeira não tem manual nem garantia. Ela entrega o volume máximo de carinho autêntico cobrando o pedágio mais caro que existe: ficar sem escudo. E é exatamente por isso que os jogos prosperam — <strong>eles te servem atenção na dose torta, segura, calculada para nunca te ferir de verdade</strong>. O jogo é o afeto sem o risco do afeto.","tip":"<strong>Modelo mental:</strong> sair dos jogos é tirar o vidro fumê do olhar, sabendo que a proximidade real pode doer — e doer de frente, sem amortecedor."},
      {"ic":"target","t":"As Vias De Fuga","emph":"Fuga","b":"Para matar um jogo na nascente, há quatro cortes certeiros: recusar o engate da <strong>Isca</strong>; receber o duplo sentido com a frieza do Adulto, sem se ferir; rejeitar o falso conforto da <strong>Recompensa</strong> negativa; e — o passo que a maioria pula — ir buscar conexão emocional pela porta limpa, em vez da torta. Os três primeiros tiram o veneno; o quarto preenche o vazio que ele deixava.","tip":"<strong>Como aplicar:</strong> ataque a raiz. No próximo ensaio do padrão de sempre, cale a sua Criança rebelde e corte a jogada antes do gancho psicológico — não depois."},
      {"ic":"person","t":"Ponto De Não-Retorno","emph":"Não-Retorno","b":"A convicção curativa do 'Eu OK – Você OK' não se instala com pensamento positivo nem com livro lido. Trocar a bússola que sustenta os seus fracassos <strong>exige atrito real, contato franco, uma longa fila de encontros sem tramoia até que eles soterrem os traumas antigos</strong> e o escudo simplesmente deixe de fazer falta.","tip":"<strong>Sinal de alerta:</strong> enquanto você colecionar jogos, a autonomia será só teoria morta no papel. O primeiro passo concreto da cura é o risco solitário de baixar a guarda.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["Intimidade é o máximo de carícias autênticas — e o maior risco; os jogos existem para imitá-la sem pagar o preço.", "Sair de um jogo tem 4 caminhos: não morder a isca, responder pelo Adulto, recusar a recompensa e buscar carinho pela via limpa.", "A posição 'Eu OK – Você OK' é a fundação — sem ela, troca-se de jogo, mas não se troca de roteiro."],
  },
]
