# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'A Jornada do Escritor'
(The Writer's Journey) de Christopher Vogler. Estrutura mítica para roteiro:
os 12 estágios da Jornada do Herói e os 8 arquétipos."""

BOOK = {
 "title": "A Jornada do Escritor",
 "author": "Christopher Vogler",
 "header_light": "A JORNADA DO",
 "header_bold": "ESCRITOR",
 "subtitle": "VISÃO GERAL · A ESTRUTURA MÍTICA PARA ROTEIRISTAS",
 "intro": "Christopher Vogler traduziu o monomito de Joseph Campbell para a linguagem do roteiro. Sob a infinita variedade das histórias, há um único padrão — a Jornada do Herói — porque ele descreve a forma da transformação humana. Vogler organiza esse padrão em 12 estágios e 8 arquétipos, ferramentas para escrever (e diagnosticar) qualquer narrativa, do mito épico ao drama doméstico.",
 "description": "A adaptação de Christopher Vogler do monomito de Campbell para roteiristas: os 12 estágios da Jornada do Herói e os 8 arquétipos como funções psicológicas — uma bússola flexível para a estrutura de qualquer história.",
 "tags": ["Roteiro", "Mito", "Ofício"],
 "progress": "10 Capítulos",
 "cover": "assets/jornada-do-escritor-cover.png",
 "overview_cards": [
   {"ic":"spiral","t":"A Jornada do Herói — 12 Estágios","b":"O padrão universal em três atos: <strong>Partida</strong> (Mundo Comum → Travessia do Limiar), <strong>Iniciação</strong> (Provas → Recompensa) e <strong>Retorno</strong> (Caminho de Volta → Elixir). É bússola flexível, não fórmula rígida.","tip":"<strong>Como aplicar:</strong> comprima, mova ou subverta estágios — o público reconhece o padrão no osso.","wide":True},
   {"ic":"layers","t":"Os 8 Arquétipos","b":"Funções psicológicas, não tipos fixos: <strong>Herói, Mentor, Guardião do Limiar, Arauto, Camaleão, Sombra, Pícaro, Aliado</strong>. Um mesmo personagem pode vestir várias máscaras.","tip":"<strong>Modelo mental:</strong> pergunte que função a cena precisa, não que personagem colocar."},
   {"ic":"key","t":"Morte, Renascimento e Elixir","b":"No centro, a <strong>Provação</strong> mata e ressuscita o herói; no clímax, a <strong>Ressurreição</strong> prova a mudança; no fim, ele volta com o <strong>Elixir</strong> que cura o mundo de onde partiu.","tip":"<strong>Chave:</strong> transformação que não volta para casa é incompleta."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-monomito-arquetipos","sub":"CAPÍTULO 1: O Monomito e os Arquétipos",
  "intro":"Campbell encontrou um único padrão sob todas as histórias; Vogler o traduziu para o roteiro. Junto vêm os arquétipos — funções psicológicas recorrentes.",
  "cards":[
      {"ic":"spiral","t":"A Força do Monomito","emph":"Monomito","b":"O herói é expulso do conforto, sangra perante os monstros e mergulha num abismo obscuro para resgatar o tesouro que salvará a sua aldeia. Sob o verniz da ficção exótica, existe um <strong>espelho escancarado da própria condição humana</strong>. O monomito é a espinha dorsal de toda transformação que o público já sofreu.","tip":"<strong>Modelo mental:</strong> os golpes e precipícios do mundo externo na história são a carne rasgada do próprio conflito moral do herói."},
      {"ic":"layers","t":"A Máscara do Arquétipo","emph":"Máscara","b":"Um arquétipo nunca é um crachá permanente: ele atua como uma roupa pesada e provisória que os personagens vestem para cumprir o que a trama grita. Um aliado dócil pode calçar os sapatos da Sombra por cruéis cinco páginas, e <strong>isso é o que injeta eletricidade nas veias da obra trancada</strong>.","tip":"<strong>Prática:</strong> troque as máscaras dos seus personagens e desestabilize o previsível; o sábio pode tentar derrubar o menino no abismo."},
      {"ic":"eye","t":"O Risco da Forma Rígida","emph":"Forma Rígida","b":"Tratar a viagem do herói como uma receita de bolo contendo miligramas exatos asfixia a voz autêntica. Subverta a ordem, arranque um degrau e exija que ele pule de ponta-cabeça. O método serve para <strong>mapear as curvas da estrada, não para engessar os joelhos de quem caminha sangrando</strong>.","tip":"<strong>Armadilha:</strong> encarnar arquétipos estereotipados e frouxos arranca a alma dos personagens em favor de um preenchimento matemático.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["O monomito é o mapa universal da transformação, não fórmula de gênero.","Arquétipos são funções; personagens são máscaras que as vestem.","Use a estrutura como bússola flexível."]},

 {"slug":"ch02-mundo-comum-chamado","sub":"CAPÍTULO 2: Mundo Comum e o Chamado à Aventura",
  "intro":"Toda jornada começa no Mundo Comum — o 'antes', que mostra o que falta ao herói. Então o Chamado rompe o equilíbrio.",
  "cards":[
      {"ic":"book","t":"O Chão do Mundo Comum","emph":"Mundo Comum","b":"A monotonia esmagadora da rotina, a falha ridícula e a fragilidade doentia: desenhe o buraco inicial para que a escalada seja mensurável. Sem o gosto enjoado do café de todo dia, não existe <strong>a urgência palpável pelo choque elétrico da aventura</strong>. Mostre quem é ele caindo aos pedaços em casa.","tip":"<strong>Como aplicar:</strong> exponha imediatamente a ferida purulenta do personagem antes de jogar a corda para ele tentar fugir."},
      {"ic":"wave","t":"O Bote na Jugular","emph":"Bote","b":"O chamado desponta como um abalo sísmico inadiável que queima a casa do herói. Não estamos lidando com um sussurro educado, mas com a <strong>inexorável implosão das estruturas daquela vida mansa</strong>. A porta dos fundos bate com estrondo, forçando o corpo a correr sem olhar para o incêndio nas costas.","tip":"<strong>Modelo mental:</strong> o abalo que pode ser negado sem qualquer arranhão não passa de uma sugestão anêmica; o chamado estilhaça o teto."},
      {"ic":"target","t":"A Faca do Arauto","emph":"Arauto","b":"A mensageira das exóticas notícias entrega o pacote e obriga que os olhos se voltem para a escuridão do abismo à frente. Seja pessoa ou reviravolta fatal, o que o Arauto carrega nos dentes é <strong>o aviso irrevogável de que a passividade acomodada já apodreceu</strong>.","tip":"<strong>Regra:</strong> alongar demais a apresentação das panelas da casa queima o interesse da sua audiência, enfie logo a bota do Arauto na porta."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["O Mundo Comum estabelece quem o herói é e o que lhe falta.","O Chamado rompe o equilíbrio e encerra o 'como sempre'.","O Arauto — pessoa, notícia ou evento — traz o Chamado."]},

 {"slug":"ch03-recusa-mentor","sub":"CAPÍTULO 3: Recusa do Chamado e o Encontro com o Mentor",
  "intro":"Entre o Chamado e a aventura há a Recusa — a hesitação que torna humana a coragem. E entra o Mentor, que arma o herói.",
  "cards":[
      {"ic":"clock","t":"A Recusa Visceral","emph":"Recusa","b":"O passo apavorado para trás, as mãos trêmulas e o pretexto acovardado testam imediatamente a veracidade do abismo. Não existe herói inquebrável diante da perspectiva de morte e ruína: o pavor injeta carne e credibilidade na tensão. Se a decisão <strong>não custar pânico letal, a travessia cheirará a mentira</strong>.","tip":"<strong>Prática:</strong> explore os recuos apavorados — a coragem imensa não anula o tremor nos joelhos; ela opera através dele.","warn":True},
      {"ic":"key","t":"O Dom do Mentor","emph":"Mentor","b":"A energia canalizada por conselhos ardentes, mapas manchados ou um artefato ancestral engatilha o protagonista para o primeiro passo. Mas essa injeção representa o eu superior do aprendiz apenas enquanto este se rasteja. Entregue o presente e faça o mestre <strong>sumir para não roubar a tela dramática inteira</strong>.","tip":"<strong>Modelo mental:</strong> o farol aponta o porto de longe, mas de forma alguma pilota a caravela em meio ao mar agitado."},
      {"ic":"eye","t":"A Praga do Mestre Onipotente","emph":"Onipotente","b":"O velho sábio que domina todas as magias estraga a cena, sugando completamente os holofotes. Se o cajado milagroso resolver o problema com pó divino, por que raios nós perderíamos tempo com o pupilo inútil? O artefato entregue pelo mentor é só um <strong>gás que vaza, não o isqueiro aceso</strong>.","tip":"<strong>Armadilha:</strong> o mestre que resolve os perigos mata o próprio protagonista com a sombra maciça do paternalismo raso."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["A Recusa expõe o medo e torna a coragem humana.","O Mentor arma o herói com dom, treino ou conselho — e se retira.","O dom é meio para a ação do herói, nunca substituto dela."]},

 {"slug":"ch04-travessia-limiar","sub":"CAPÍTULO 4: A Travessia do Primeiro Limiar",
  "intro":"O herói se compromete e cruza para o Mundo Especial. É o ponto sem retorno que abre o Ato 2.",
  "cards":[
      {"ic":"steps","t":"O Teste de Sangue","emph":"Teste de Sangue","b":"A ponta da bota enfiada no mundo hostil, o choque cortante das regras cruéis daquele novo ecossistema e a certeza de que retornar equivale à covardia morta. A fronteira violada demarca <strong>a adesão voluntária à guerra incerta</strong>, batendo o martelo final no ponto absoluto e sem remissão de volta.","tip":"<strong>Como aplicar:</strong> carimbar o passaporte não exige volta atrás. Imponha uma perda colossal caso a figura hesite ao atravessar."},
      {"ic":"gap","t":"O Monstro do Limiar","emph":"Limiar","b":"Ele não reina supremo e não carrega a chave do arco final; ele guarda friamente os portões das estradas sujas. O porteiro ataca quem se atreve a violar a redoma, testando <strong>o nível do desespero e da fúria do escolhido de carne frouxa</strong>. Seu objetivo principal não é matar, mas espantar os fracos de coração.","tip":"<strong>Modelo mental:</strong> os vigias das portas aceitam contorno, pagamento ou pancada veloz, mas eles jamais demandam o prato principal da ação."},
      {"ic":"eye","t":"O Salto Sem Fogo","emph":"Salto Sem Fogo","b":"Atravessar portas gigantescas sendo arremessado por mãos alheias reduz o personagem a uma carga transportada num trem fantasma. Limiares frios que não pedem taxa de sangue destroem completamente o impacto e cospem no compromisso interno. Quando a travessia é gratuita, o viajante segue <strong>morno e afogado na inércia profunda no ato seguinte</strong>.","tip":"<strong>Armadilha:</strong> heróis rebocados esvaziam totalmente o clímax emocional e rebaixam a aposta épica a um mero passeio turístico.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["A Travessia é o comprometimento que abre o Ato 2.","O Guardião testa o preparo; supere, contorne ou converta.","Idealmente o herói escolhe cruzar, firmando-se como agente."]},

 {"slug":"ch05-provas-aliados-inimigos","sub":"CAPÍTULO 5: Provas, Aliados e Inimigos",
  "intro":"No Mundo Especial, o herói aprende as novas regras, ganha aliados e identifica inimigos — a parte expansiva do Ato 2.",
  "cards":[
      {"ic":"target","t":"O Ferro das Provas","emph":"Provas","b":"Lutas de escada e tropeços nas armadilhas rasas, esses pequenos abalos lapidam a lâmina e sujam a bota de suor e lama. Cada teste eleva a fervura da panela, revela o caráter sob pressão e prepara <strong>a musculatura que não poderá engasgar na Provação Central</strong>. Não encha linguiça com ação fútil; adestre as dores internas.","tip":"<strong>Prática:</strong> considere o meio da trama como a aula dolorosa do dia; cada conflito exige uma nota rabiscada em vermelho."},
      {"ic":"layers","t":"A Trupe e o Espelho Escuro","emph":"Espelho Escuro","b":"A facção aliada cimenta a confiança enquanto o arqui-inimigo escurece o céu sob a marca densa da Sombra. E o vilão absoluto cumpre o papel magistral: ele grita as fraquezas latentes do próprio salvador no fundo da alma. O rival bem talhado atua como <strong>a visão corrompida de tudo que o protagonista poderia encarnar amanhã</strong>.","tip":"<strong>Modelo mental:</strong> a oposição impecável revela nitidamente o veneno embutido que o justiceiro luta amargamente para não provar."},
      {"ic":"eye","t":"Provas Sem Osso","emph":"Sem Osso","b":"Conflitos soltos e companheiros enfeitados matam cruelmente as páginas. O figurante desocupado cega o ritmo, e a ameaça sem enraizamento na culpa principal estilhaça e pulveriza o coração da tese narrativa da obra. As peças mecânicas precisam <strong>morder a carne e mastigar o espírito da plateia ao mesmo instante</strong>.","tip":"<strong>Armadilha:</strong> lutas plásticas que não alteram a pele e os ossos por dentro desperdiçam dinheiro da produção e tempo valioso do público.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Provas treinam o herói e elevam as estacas rumo à Provação.","Aliados e Inimigos definem o time e dão forma à Sombra.","A Sombra mais potente espelha o herói."]},

 {"slug":"ch06-aproximacao-provacao","sub":"CAPÍTULO 6: Aproximação e a Provação",
  "intro":"O herói chega à caverna mais profunda e enfrenta a Provação: a crise central, um confronto com a morte do qual renasce mudado.",
  "cards":[
      {"ic":"spiral","t":"O Ventre da Baleia","emph":"Ventre","b":"A noite brutal da trama esmaga o ar do herói com o calcanhar de chumbo. Mergulhado na cova úmida e rasgado perante o monstro primordial, o herói não cede as roupas, <strong>ele morre simbolicamente para renascer com as cicatrizes rudes do saber</strong>. O centro de gravidade emana da força incontrolável do abismo estilhaçado.","tip":"<strong>Regra:</strong> não há renascimento real sem a destruição dolorosa e prévia de um dos pilares imensos daquela figura central."},
      {"ic":"key","t":"A Poeira da Morte","emph":"Morte","b":"As engrenagens estalam sob o desespero de forma contundente, a velha casca finalmente se esvai no ralo quente de dor pura. A emergência gloriosa ocorre apenas e restritamente das cinzas pegajosas do campo de batalha. Quando o personagem prende a respiração nas trevas, <strong>a plateia sente a corda rasgar na própria garganta também</strong>.","tip":"<strong>Modelo mental:</strong> o ponto sem fundo dita com exatidão a gravidade de cada mísera fagulha jogada desde a abertura das cortinas."},
      {"ic":"eye","t":"A Morte em Banho-Maria","emph":"Banho-Maria","b":"Vitórias limpas que tombam sem arranhar uma unha sequer esvaziam o caldeirão de fogo por completo. Se nós nunca mordemos o lábio duvidando seriamente do retorno, o renascimento divino vira um teatrinho barato de domingo. A ação plástica sem nenhuma morte interna arrastada é <strong>apenas um truque oco de pirotecnia covarde e infantil</strong>.","tip":"<strong>Armadilha:</strong> o público não tolera o roteirista bundão: poupar a vida com manobras fáceis destrói a força do pacto firmado.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["A Provação é a crise central: morte simbólica e renascimento.","Precisa de risco real e 'cheiro de morte' para emocionar.","A mudança tem que ser interna, não só a vitória externa."]},

 {"slug":"ch07-recompensa","sub":"CAPÍTULO 7: A Recompensa (Apoderar-se da Espada)",
  "intro":"Sobrevivida a Provação, o herói toma a Recompensa. É respiro e celebração — mas também a falsa sensação de que tudo acabou.",
  "cards":[
      {"ic":"target","t":"A Espada Sangrenta","emph":"Espada Sangrenta","b":"A conquista ardente do artefato cintilante encharcado em sangue, o autoperdão, a lâmina que mata deuses. As mãos trêmulas seguram com unhas e dentes <strong>algo que a morte atroz validou com os próprios carimbos gelados</strong>. Esse baú da recompensa carrega incrustado o custo extorsivo e explícito do horror monumental que ficou nas costas do abismo cego.","tip":"<strong>Prática:</strong> o prêmio tem que exibir lascas na empunhadura; algo ganho num abraço não passa de ouro folheado da feira livre."},
      {"ic":"clock","t":"O Falso Respiro","emph":"Falso Respiro","b":"A anestesia temporária desponta no copo esvaziado: beijos salgados, espadas erguidas num engano reconfortante e <strong>a farsa doce de que acabou tudo aqui no meio do prado ensolarado</strong>. É o esticar elástico antes da pancada asfixiante que rasgará todo o fôlego da corrida final, o demônio inerte preparou o silêncio mais sujo e cruel de todo o ato de desfecho.","tip":"<strong>Modelo mental:</strong> o alívio exagerado esconde nas frestas da janela o tombo mais cruel e furioso de toda a espinha dorsal."},
      {"ic":"eye","t":"A Festa Que Não Acaba","emph":"Não Acaba","b":"Deixar o brinde prolongado na praça afoga a obra. Se o herói engorda rindo, a tribo faminta e esquecida <strong>morre amargurada no frio, longe do fogo que as mãos manchadas e feridas roubaram brilhantemente</strong>. A paralisação egocêntrica decepa rudemente a essência do que movimenta a energia mitológica da coroa estendida perante a tela rasgada do céu.","tip":"<strong>Armadilha:</strong> o herói que consome a vitória mastigando a torta solitário assassina rudemente toda a empatia injetada na veia humana."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["A Recompensa é o prêmio conquistado pela Provação.","A falsa paz dá respiro e prepara a virada — não é o fim.","A Recompensa deve revelar a transformação do herói."]},

 {"slug":"ch08-caminho-de-volta","sub":"CAPÍTULO 8: O Caminho de Volta",
  "intro":"Com a Recompensa em mãos, o herói precisa voltar — e o retorno não é tranquilo. A virada que abre o Ato 3.",
  "cards":[
      {"ic":"steps","t":"A Fuga Final","emph":"Fuga Final","b":"A escolha de engatar a terceira e partir alucinado fugindo das bestas esfoladoras que clamam fúria de resgate com ódio visceral puro nas retinas manchadas de prata. A fuga apavorante quebra a quietude da canção. <strong>O retrovisor acusa cinzas suadas e os dentes rasgam a poeira voando em direção direta à vingança que acendeu as tochas de asfalto fervente</strong>.","tip":"<strong>Como aplicar:</strong> o freio é rasgado com lâmina bruta; a retirada quase sempre clama desesperadamente pela alavanca de uma caçada esbaforida."},
      {"ic":"wave","t":"A Faca na Costela","emph":"Faca na Costela","b":"A reviravolta enfia com força a lâmina fria na escuridão fofa para injetar o fôlego asfixiante no clímax impiedoso. Se o caldeirão não engolir gasolina pura agora no escuro rasgado, <strong>ninguém ligará mais se as engrenagens finais contam o troféu ou sangram perdidas</strong>. As apostas batem violentamente do teto descascado e furam os tijolos do alicerce esfacelado da última porta erguida e derrubada no porão escuro.","tip":"<strong>Prática:</strong> a trégua é covardia que o mestre atira na lixeira do quarto, desperte os lobos ensanguentados que rasgarão o pescoço."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["O Caminho de Volta vira o Ato 3: consequências e perseguição.","O herói se recompromete com a missão, ciente do custo.","A escolha de voltar prova que a transformação se fixou."]},

 {"slug":"ch09-ressurreicao","sub":"CAPÍTULO 9: A Ressurreição",
  "intro":"O clímax: a prova final e mais severa, em que o herói enfrenta a morte uma última vez e demonstra, definitivamente, que mudou.",
  "cards":[
      {"ic":"spiral","t":"O Clímax Final","emph":"Clímax","b":"A colisão frontal arrasadora estraçalha os muros <strong>mil vezes mais cortante e aguda do que as chamas do abismo lá debaixo</strong>. Toda a aldeia, a carne humana, o cérebro rasgado pendem num estalar letal de pura tensão insuportável no ar enfumaçado. O ex-escravo levanta carbonizado para calcinar a covardia impiedosamente perante o mundo cego agora subjugado pela força do aprendizado calejado cravado fundo na espinha.","tip":"<strong>Prática:</strong> dobre estupidamente o risco perante os deuses, o abismo inicial atinge o nível de aquecimento na porta deste novo inferno destrancado."},
      {"ic":"target","t":"O Fogo da Transformação","emph":"Transformação","b":"Os clichês ocos apodrecem sumariamente, dando total reinado absoluto <strong>à decisão insana de provar sob o ferro fumegante, rasgo impiedoso e asfalto cru que o sangue não mentiu feio</strong>. Cada célula costurada do saber novo explode nos atos frenéticos das mãos, decretando em berros cegos de ação visceral e brutal a mudança interna do novo cérebro nojento e refeito no fogo sem perdão alheio das regras velhas de papel amassado e pisoteado duro e rude do antigo porto afundado agora há pouco tempo e sem chances das algemas prenderem de novo o coração quebrado do antigo morador de lá debaixo das águas congeladas dos velhos tempos passados que agora evaporaram no nada fumaçado cinzento","tip":"<strong>Regra:</strong> os votos bonitos morrem na garganta seca e vazia; exiba a mutação dilacerante nos dedos e punhos esmagando impiedosamente a ignorância fraca e acomodada no lixo"},
      {"ic":"sword","t":"O Interventor Barato","emph":"Interventor","b":"O relâmpago divino descendo mágico fritando todo o exército final arranca descaradamente das mãos encharcadas a merecida e calejada catarse da plateia farta. Quando a entidade milagreira do autor medroso corta a dor e entrega os sorrisos sem rasgar a camisa, <strong>a criatura ressuscitada perde vergonhosamente o prêmio; virou apenas estorvo da sorte que sobreviveu sem o próprio soco ensanguentado cravado e orgulhosamente deixado perante o caixão do oponente morto</strong>.","tip":"<strong>Armadilha:</strong> o raio abençoado que liquida vilões complexos e grandiosos mata junto cruelmente a honra do sangue cravado e empurra a bilheteria e as folhas para as lamas inférteis","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["A Ressurreição é o clímax: a prova final, maior que a Provação.","O herói demonstra em ato, sob pressão máxima, que mudou.","Deve ser o próprio herói a vencer — nunca um salvador externo."]},

 {"slug":"ch10-retorno-com-elixir","sub":"CAPÍTULO 10: O Retorno com o Elixir",
  "intro":"A jornada se completa quando o herói retorna ao Mundo Comum trazendo o Elixir — algo que beneficia o mundo de onde partiu.",
  "cards":[
      {"ic":"key","t":"A Cura Entregue","emph":"Cura","b":"A poeira tóxica acalma devagar e os pulsos calejados esvaziam o jarro divino diretamente no centro deprimido e rasgado da aldeia. A coroa ou abraço arrebatador sacia de imediato a sede amarga que estraçalhava as gargantas feridas das pessoas apagadas do poço morto. <strong>A catarse irrecusável e final atesta esplendidamente que sofrer o abismo consertou maravilhosamente a aldeia, justificando o ferro</strong>.","tip":"<strong>Modelo mental:</strong> o herói desgraçado e arranhado porta a coroa dourada estritamente e unicamente porque despejou sem pensar no pódio um oceano curativo sobre cabeças suadas do vilarejo vazio e escuro."},
      {"ic":"spiral","t":"O Círculo e o Chão Limpo","emph":"Círculo","b":"O rancho apodrecido desenhado nas aberturas reaparece esplendorosamente preenchido do vigor vibrante injetado nas tábuas finas — <strong>as espadas do retorno lavam ferozmente as misérias iniciais esfregadas no rosto cético do leitor que perdoou a rotina inicial lenta</strong>. O prado final enxuga esplendidamente as lágrimas da abertura poeirenta de outrora fechando magistralmente a rima gloriosa encravada no roteiro das canetas rasgadas e reescritas arduamente na escrivaninha das lágrimas fáceis do escritor doente de cafeína barata na cadeira velha","tip":"<strong>Prática:</strong> a última câmera do plano arranca a dor espinhosa e exalta as montanhas que a lama rasteira dos primeiros quadros esquecidos chorava de inveja crua"},
      {"ic":"eye","t":"O Tesouro Escondido","emph":"Tesouro","b":"Encerrar a corrida pálido abraçando os malotes repletos sozinho num egoísmo infantil escuro, apaga desastrosamente as marcas majestosas do aço. <strong>A epifania efervescente tomba rastejante asfixiada porque o palco não vislumbrou a cura das feridas em comunidade suada, anulando de forma asquerosa e patética o ato abismal da provação monumental impagável outrora sofrida na pele cortada e esticada cruelmente sob a cruz do sol escaldante</strong>.","tip":"<strong>Armadilha:</strong> findar secamente longe do impacto catártico coletivo encolhe estupidamente toda a grandiosidade mitológica e chuta grosseiramente a bandeja da cura para fora das retinas e estômagos esvaziados do povão sentado que acompanhou tudo chorando as mágoas frias nos encostos carcomidos","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 10",
  "lessons":["O herói retorna transformado e traz um Elixir que beneficia o mundo.","O Elixir compartilhado cura o Mundo Comum e fecha o círculo.","A Imagem Final espelha a inicial — a prova visível da mudança."]},
]
