# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'As Leis da Natureza Humana' (Robert Greene)."""

BOOK = {
  "title": "As Leis da Natureza Humana",
  "author": "Robert Greene",
  "header_light": "LEIS DA",
  "header_bold": "NATUREZA HUMANA",
  "subtitle": "VISÃO GERAL · AS FORÇAS QUE MOVEM AS PESSOAS POR DENTRO",
  "intro": "Imaginamos agir por escolha. Quase sempre, agimos por forças que nunca pedimos licença para entrar: a emoção que decide antes da razão, o ego que distorce o que vê, o desejo que cobiça o que foge. Greene cataloga dezoito dessas forças com a frieza de um naturalista diante de um animal — sem moralismo, sem ilusão. Cada lei tem duas faces: o traço, como a natureza humana de fato opera; e a virada, o que um homem lúcido faz com isso. <em>A única defesa contra ser movido é aprender a ver o que move.</em>",
  "description": "As leis da natureza humana de Robert Greene em cheat sheet, lidas em chave de autoconhecimento e leitura de pessoas — não de manipulação. Irracionalidade e o sequestro da razão pela emoção; o narcisismo e a virada para a empatia; a máscara social e o caráter que se repete; o desejo do que é escasso; a perspectiva do general; defensividade; a atitude que cria a própria sorte; A Sombra; inveja e grandiosidade; gênero, propósito e o efeito do tribunal; agressão velada, o espírito da geração e a finitude. Um espelho frio para ler o outro — e a si mesmo.",
  "tags": ["Psicologia", "Poder", "Autoconhecimento"],
  "progress": "11 Capítulos",
  "cover": "assets/leis-da-natureza-humana-cover.png",
  "overview_cards": [
    {"ic":"layers","t":"As Três Alavancas","b":"Dezoito leis, mas três sustentam o edifício inteiro:<br><strong>Empatia</strong> — sair de si e ler o outro por dentro (Ch. 2).<br><strong>Caráter</strong> — o que alguém faz sob pressão diz mais que tudo o que jura (Ch. 3).<br><strong>Perspectiva</strong> — subir acima do impulso e do ego para ver o terreno (Ch. 5).<br>Quem domina estas três decifra as outras quinze quase sozinho.","tip":"<strong>Modelo mental:</strong> não tente decorar dezoito táticas. Cultive três faculdades — empatia, leitura de caráter, perspectiva — e o resto vem por dedução.","wide":True},
    {"ic":"mask","t":"Todo Traço Tem uma Virada","b":"Greene não condena a natureza humana; ele a descreve. Cada lei traz um <strong>traço</strong> — a irracionalidade, a inveja, a agressão que existem em todos nós — e, ao lado, a <strong>virada</strong>: o que fazer quando se enxerga a força operando. O método nunca muda: reconhecer, nomear, e só então escolher. <em>O que se vê deixa de comandar às cegas.</em>","tip":"<strong>Regra de uso:</strong> diante de cada lei, pergunte 'isto opera em mim — ou estão usando isto contra mim?'. O fim legítimo é o autoconhecimento e a defesa; a manipulação fria o próprio autor desaconselha."},
    {"ic":"eye","t":"Um Espelho, Não uma Arma","b":"Estas leis servem ao diagnóstico e à defesa, não ao ataque. Reconhecer a inveja disfarçada de elogio, a agressão que se faz de vítima, o consenso que se passa por verdade — isso devolve a você a escolha que a cegueira havia tomado. <strong>Quem nomeia a dinâmica deixa de ser conduzido por ela.</strong>","tip":"<strong>Como aplicar:</strong> trate o acervo como radar, jamais como mira. A vantagem real está na lucidez sobre si mesmo — não no domínio sobre o outro."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-irracionalidade",
    "sub": "CAPÍTULO 1: Domine seu Lado Emocional",
    "intro": "Gostamos de nos chamar de animais racionais. É a nossa vaidade fundadora. Na verdade, a emoção decide primeiro e a razão é convocada depois, como advogado, para defender o veredito já dado. O homem verdadeiramente racional não é o que não sente — é o que admite o quanto sente, e por isso consegue olhar a própria emoção de fora antes de obedecê-la.",
    "cards": [
      {"ic":"wave","t":"A Emoção Chega Primeiro","emph":"Primeiro","b":"Você sente, e só então pensa — nunca a ordem inversa. A emoção dispara num instante; a razão chega atrás, ofegante, costurando motivos nobres para o que o corpo já resolveu. Racionalidade, então, não é a ausência do sentir: é o sentir <strong>visto de fora e mantido na coleira</strong>. E tudo começa por uma admissão humilhante — a de ser mais irracional do que imagina.","tip":"<strong>Modelo mental:</strong> trate a emoção como o tempo lá fora — informa o seu dia, mas não dá ordens. Quem confunde clima com destino se molha sempre."},
      {"ic":"eye","t":"O Veneno Lento Engana Mais","emph":"Veneno Lento","b":"A raiva que explode pelo menos se anuncia. O perigoso é o que não bate à porta: o ressentimento que se cronifica, a inveja morna, o tédio que vira pressa. Essas correntes frias corroem o juízo <strong>sem jamais disparar o alarme</strong> — e ainda se disfarçam de lógica. <em>Quanto mais sereno e definitivo o seu raciocínio parece, mais vale revistá-lo.</em>","tip":"<strong>Sinal de alerta:</strong> a certeza calma é a melhor máscara da emoção. Desconfie da clareza que chega cedo demais e não custa esforço algum.","warn":True},
      {"ic":"lens","t":"Os Vieses São Lentes Tingidas","emph":"Lentes Tingidas","b":"Não enxergamos o mundo; enxergamos a versão que adula o ego. A lente da confirmação só vê o que já cremos; a da convicção confunde gritar mais alto com ter mais razão; outras tingem tudo pela aparência, pelo grupo, pela culpa, pela superioridade. <strong>Não há como arrancar a lente — só conhecer a cor de cada uma e descontar a distorção</strong> antes de agir.","tip":"<strong>Como aplicar:</strong> antes de qualquer decisão importante, pergunte 'qual conclusão me favoreceria agora?' — e fique justamente alerta se for essa a que parece óbvia."},
      {"ic":"gap","t":"A Liberdade Mora na Fresta","emph":"Fresta","b":"Entre o que lhe acontece e o que você faz há um vão estreito. Toda a sua liberdade cabe ali — e em nenhum outro lugar. Uma pausa, o ato de batizar a emoção pelo nome, o exercício de se olhar como olharia um estranho: cada gesto <strong>alarga a fresta</strong> e tira o comando da reação para devolvê-lo a quem escolhe.","tip":"<strong>Regra:</strong> quando a intensidade subir, não decida no calor — durma sobre a questão. A pressa emocional quase nunca assina um bom contrato."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["Admitir-se mais irracional do que pensa não é fraqueza — é a primeira condição da racionalidade real.", "Abra um vão entre o estímulo e a resposta: a pausa, o nome da emoção, o olhar de terceiro.", "Conheça seus vieses pelo nome próprio — só se desconta a distorção que se consegue ver."],
  },
  {
    "slug": "ch02-narcisismo-empatia",
    "sub": "CAPÍTULO 2: Transforme Amor-Próprio em Empatia",
    "intro": "No fundo de cada um arde a mesma fome de ser visto e confirmado. É o núcleo narcísico, e ele não tem cura — só destino. Pode girar para dentro, num poço que nada enche, ou voltar-se para fora e virar a mais rara das habilidades: a empatia, a arte de sair de si para ler o que se passa dentro do outro.",
    "cards": [
      {"ic":"spiral","t":"O Poço Sem Fundo","emph":"Poço","b":"A fome de atenção habita todos nós. No narcisista saudável, ela repousa sobre um eu já firme, e por isso sobra energia para olhar o outro. No narcisista profundo, falta o próprio eu: ele vive do reflexo alheio, converte toda conversa em palco e <strong>devora atenção sem jamais se saciar</strong>. Encher esse poço é tarefa de Sísifo.","tip":"<strong>Sinal de alerta:</strong> o vazio do narcisista profundo não tem fundo. Não se proponha a preenchê-lo — reconheça o tipo cedo e mantenha distância de braço.","warn":True},
      {"ic":"bubble","t":"Sair de Si para Ler o Outro","emph":"Sair de Si","b":"Empatia não é doçura nem sentimentalismo: é a habilidade social suprema, e treina-se como um músculo. Sobe em camadas — <strong>querer compreender; captar o estado pelo corpo e pelo tom; estudar a história alheia quando o instinto falha; corrigir-se pela reação real</strong>. Tudo nasce de um único gesto difícil: calar a própria voz interior antes de responder à do outro.","tip":"<strong>Como aplicar:</strong> ouça para entender, não para preparar a réplica. A atitude precede a técnica — sem ela, nenhum método de escuta funciona."},
      {"ic":"eye","t":"O Espelho que Mente","emph":"Espelho","b":"O erro mortal da empatia é projetar: supor que o outro sente o que <strong>você</strong> sentiria no lugar dele. Aí você não escuta a pessoa — escuta a si mesmo vestido com a roupa dela. A virada é tratar cada um como enigma a decifrar, não como cópia a confirmar; colher os sinais que ele de fato emite, e não o eco do seu próprio palpite.","tip":"<strong>Modelo mental:</strong> empatia é uma espionagem benigna. Você recolhe pistas do outro para servi-lo melhor — não para encontrar nele a confirmação de si."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["Localize-se no espectro narcísico e firme a autoestima por dentro — só um eu estável tem energia de sobra para o outro.", "Treine a empatia em camadas: a visceral (corpo e tom) e, quando o instinto falha, a analítica (história e contexto).", "Identifique o narcisista profundo logo no início — e resista à tentação de tapar um vazio que não tem fundo."],
  },
  {
    "slug": "ch03-mascara-carater",
    "sub": "CAPÍTULO 3: Veja Máscaras e Leia o Caráter",
    "intro": "Toda pessoa que você encontra traz uma máscara — o rosto que ela quer que o mundo aceite. Por baixo, intocado, mora o caráter: um padrão forjado na infância que se repete a vida inteira. Quem aprende a ler a fenda entre os dois deixa de ser enganado pela promessa do momento e passa a confiar no que o histórico já provou.",
    "cards": [
      {"ic":"mask","t":"A Verdade Escapa pelo Corpo","emph":"Escapa","b":"Todos encenam um papel para serem aceitos — mas o corpo é um mau ator e entrega o que a fala esconde. A microexpressão que dura meio segundo, o tom que destoa da frase, a postura que contradiz a boca: a verdade <strong>vaza pelos sinais que a pessoa não governa</strong>. A leitura, porém, é em agrupamentos, jamais em gestos soltos — braços cruzados não são confissão de nada.","tip":"<strong>Como aplicar:</strong> antes de interpretar, fixe o baseline — o jeito normal daquela pessoa. Só percebe o desvio quem conhece a norma de que ele se afasta."},
      {"ic":"layers","t":"O Caráter é o que se Repete","emph":"Repete","b":"Caráter não é o que alguém jura ser; é o que faz de novo, e de novo, quando o poder sobe à cabeça e a adversidade aperta. A intenção sai barata e se renova todo dia; o padrão custa anos para mudar e quase nunca muda. <strong>O passado de uma pessoa prevê o futuro dela melhor que qualquer promessa do presente.</strong> Uma desculpa eloquente não apaga uma série de atos.","tip":"<strong>Regra:</strong> julgue pelo histórico sob estresse, não pela fala bonita em paz. Acredite no padrão — ele tem provas; a promessa tem apenas palavras."},
      {"ic":"triangle","t":"A Pressão Arranca a Máscara","emph":"Arranca","b":"Greene assinala os tipos de risco: o perfeccionista que precisa controlar tudo, o rebelde de causas fáceis, o sedutor que vive de conquistar, o salvador que cria dependentes. No começo, cada um é só charme — e o charme é o anestésico. A pressão é o reagente que revela o caráter. <strong>Quando a máscara ideal deixa de bater com o comportamento real, acredite sempre no comportamento.</strong>","tip":"<strong>Sinal de alerta:</strong> charme intenso na largada somado a um padrão compulsivo sob pressão é a fórmula do encrenqueiro. Recue cedo — não se entra em negociação com um padrão.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["Fixe o baseline antes de ler qualquer sinal não-verbal — o significado está no desvio, não no gesto isolado.", "Interprete agrupamentos de sinais, nunca um gesto solto: um gesto é ruído, um conjunto é mensagem.", "Avalie o caráter pelo padrão histórico sob estresse — e reconheça os tipos tóxicos enquanto ainda dá tempo de recuar."],
  },
  {
    "slug": "ch04-desejo-perspectiva",
    "sub": "CAPÍTULO 4: Desejo Evasivo e Elevação da Perspectiva",
    "intro": "Duas forças torcem o julgamento sem que se note. A primeira é o desejo, que se alimenta de distância: cobiçamos o que escapa e enjoamos do que possuímos. A segunda é o tempo: sob pressão, a mente encolhe para o tamanho do agora e perde o quadro inteiro. Contra ambas vale a mesma medida — recuar para ganhar altura.",
    "cards": [
      {"ic":"spark","t":"Queremos o que Foge","emph":"Foge","b":"O desejo vive da falta, não da posse. Cobiçamos o escasso, o distante, o proibido — e, no instante em que a coisa é nossa, ela perde o brilho que tinha de longe. Pior ainda: queremos sobretudo o que a multidão quer, e o valor incha por contágio. <strong>Quando, de repente, 'todo mundo quer', desconfie — é cobiça induzida e escassez fabricada, raramente valor real.</strong>","tip":"<strong>Cuidado:</strong> não persiga nada só porque o tornaram raro de propósito. O desejo dos outros é o gatilho mais fácil de puxar no seu.","warn":True},
      {"ic":"mountain","t":"A Mente Encolhe sob Pressão","emph":"Encolhe","b":"Sob tensão, o campo de visão se fecha: reagimos ao urgente, ao alarmante, à manchete do dia — e tomamos a árvore mais próxima pela floresta inteira. É a miopia, e ela confunde o barulho mais alto com o sinal mais importante. A cura é a visão do general: <strong>subir acima da batalha e ler o terreno inteiro</strong> antes de mover a primeira peça.","tip":"<strong>Como aplicar:</strong> trate todo alarme como um pedido de atenção, jamais como uma ordem de ação. A pergunta que devolve a escala é simples — 'e daqui a um ano, isto ainda importa?'."},
      {"ic":"clock","t":"O Evento é Sintoma, Não Causa","emph":"Sintoma","b":"A crise isolada quase nunca é a raiz — é o <strong>sintoma de um sistema que opera silenciosamente por baixo</strong>. Quem persegue cada incêndio do dia vence escaramuças e perde a guerra; ganhar a disputa pequena custa, com frequência, a grande. Maturidade é responder ao padrão e ao longo prazo, não à faísca da hora.","tip":"<strong>Regra:</strong> alargue o horizonte de tempo antes de decidir. No curto prazo quase tudo é ruído; o sinal só aparece quando se afasta a câmera."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["Cultive certo mistério e a ausência calculada — a presença total e o tudo-ao-alcance extinguem o desejo.", "Eleve a perspectiva antes de reagir; a pergunta 'e daqui a um ano?' recoloca o evento na sua escala real.", "Pense em sistemas, não em eventos — o fato isolado é quase sempre o sintoma, raramente a causa."],
  },
  {
    "slug": "ch05-defensividade-autossabotagem",
    "sub": "CAPÍTULO 5: Defensividade e Autossabotagem",
    "intro": "Duas leis sobre a parede que separa a pessoa do mundo. A primeira: ninguém abaixa a guarda diante de quem o faz sentir-se inferior ou controlado — empurrar só endurece a muralha. A segunda, mais inquietante: a atitude com que você olha o mundo é a tinta com que o pinta, e depois você age de modo a confirmar a própria tinta.",
    "cards": [
      {"ic":"bubble","t":"Não Empurre — Abra a Porta","emph":"Abra a Porta","b":"A resistência alheia raramente é teimosia: é o ego se protegendo de quem ameaça sua autonomia ou seu valor. Argumentar de frente apenas reforça a muralha. O persuasor hábil faz o oposto — primeiro concorda, espelha os valores do outro, valida o seu orgulho, e só então conduz, de modo que a conclusão <strong>chegue ao outro como descoberta própria</strong>, e não como rendição.","tip":"<strong>Como aplicar:</strong> baixe a guarda do outro antes de pedir qualquer coisa. Adote por um instante a perspectiva dele e deixe sempre claro: 'a decisão é sua' — porque, no fim, ela precisa ser."},
      {"ic":"spiral","t":"A Profecia que se Cumpre","emph":"se Cumpre","b":"Você não vê o mundo como ele é; vê-o como a sua atitude o pinta — e então age de um jeito que faz a tinta virar realidade. O hostil lê tudo como ataque, afasta aliados e acaba provando o próprio isolamento. O expansivo lê o revés como informação e acaba atraindo oportunidades. <strong>A mesma realidade, dois destinos opostos — separados apenas pelo filtro.</strong>","tip":"<strong>Modelo mental:</strong> a sua atitude é o programa; a realidade que você relata, no fim do dia, é o que esse programa imprimiu. Troque o código e a saída muda."},
      {"ic":"target","t":"Escolha o Filtro Expansivo","emph":"Expansivo","b":"Greene separa os filtros que envenenam — o hostil, o ansioso, o evitador, o ressentido — da atitude expansiva: curiosidade, abertura ao novo, tolerância à ambiguidade, resiliência diante do golpe. E a notícia decisiva é que isto não é dom de berço: é <strong>uma escolha renovada a cada manhã</strong>, a de tratar a adversidade como dado a usar, não como sentença a cumprir.","tip":"<strong>Sinal de alerta:</strong> quando o mesmo 'azar' se repete e os mesmos padrões ruins reaparecem, suspeite do filtro que carrega por dentro — não do mundo lá fora.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["Antes de persuadir, dissolva a defensividade: valide o ego e a autonomia do outro — só então a porta se abre.", "A atitude precede e molda a circunstância; para mudar o resultado, troque primeiro o filtro pelo qual você o lê.", "Cultive o filtro expansivo — curiosidade, abertura e resiliência — como uma escolha diária, não como um traço herdado."],
  },
  {
    "slug": "ch06-sombra",
    "sub": "CAPÍTULO 6: Confronte seu Lado Obscuro — A Sombra",
    "intro": "Há em cada um uma metade negada — os traços que julgamos vergonhosos demais para admitir e por isso trancamos no escuro. É a Sombra. Ela não morre por estar presa; apenas fermenta, e volta disfarçada de contradição, de projeção, de explosão súbita. Quem a encara e a reintegra recupera energia, profundidade e a sua própria inteireza.",
    "cards": [
      {"ic":"mask","t":"A Sombra Cresce no Escuro","emph":"no Escuro","b":"Aquilo que você nega em si não desaparece — torna-se Sombra e retorna pela porta dos fundos: o comportamento que contradiz o discurso, a negação enfática demais, o lapso 'sem querer', a virtude alardeada com excesso. Reprimir consome energia o tempo todo, e o que se tranca no porão <strong>só ganha força lá embaixo</strong>, até o dia em que arromba a porta.","tip":"<strong>Sinal de alerta:</strong> a reação desproporcional e a moral exibida em voz alta são denúncia. A fachada perfeita demais costuma guardar a Sombra mais densa.","warn":True},
      {"ic":"eye","t":"A Projeção é o seu Espelho","emph":"Espelho","b":"O que mais o irrita no outro é, com frequência, <strong>material seu, negado e arremessado nele</strong>. A aversão intensa quase nunca fala da pessoa à sua frente; revela o traço que você não admite carregar. Por isso os de moral mais ruidosa ruem justamente no vício que mais condenavam — é a Sombra cobrando, com juros, o preço da repressão.","tip":"<strong>Modelo mental:</strong> transforme a irritação forte em instrumento de diagnóstico. Diante dela, pergunte não 'o que há de errado nele?', mas 'o que isto revela de mim?'."},
      {"ic":"spark","t":"Reintegre, Não Reprima","emph":"Reintegre","b":"A saída não é soltar a Sombra sem rédea nem fingir que ela inexiste — é reconhecê-la e canalizá-la com consciência. O homem autêntico incorpora o próprio lado obscuro em vez de apostar numa imagem impecável que mais cedo ou mais tarde se rompe. <strong>Energia reprimida vira sintoma; a mesma energia, integrada, vira combustível.</strong>","tip":"<strong>Regra:</strong> observe, nomeie, reintegre. O traço sombrio carrega força bruta — dirigida de propósito, essa força se converte em ousadia e criação."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["Reconheça que você tem uma Sombra — é justamente a negação dela que a torna perigosa.", "Leia as suas projeções e reações desproporcionais como pistas fiéis do seu próprio lado obscuro.", "Reintegre a energia da Sombra de forma consciente: o que se rejeita vira sintoma, o que se assume vira força."],
  },
  {
    "slug": "ch07-inveja-grandiosidade",
    "sub": "CAPÍTULO 7: O Ego Frágil — Inveja e Grandiosidade",
    "intro": "O ego frágil distorce de dois modos opostos. Para baixo, vira inveja: a dor de ver o outro subir, dor tão inconfessável que se mascara de quase qualquer coisa. Para cima, vira grandiosidade: a autoimagem que incha além do real e corta o fio com o chão. Reconhecer as duas — primeiro em si, depois nos outros — é defesa essencial.",
    "cards": [
      {"ic":"eye","t":"A Inveja Vem de Máscara","emph":"de Máscara","b":"A inveja é universal e quase nunca mostra a cara — é vergonhosa demais para isso. Vem por baixo, justamente de quem mais se compara com você. Leia os sinais que escapam: a microexpressão de desprezo, o elogio com a farpa embutida, a frieza diante do seu sucesso, a alegria mal contida com o seu tropeço. <strong>O 'amigo' que se anima a cada queda sua é o primeiro suspeito.</strong>","tip":"<strong>Como aplicar:</strong> não acenda a comparação à toa — a discrição protege. E aprenda a sentir o elogio que dói: por baixo dele costuma morar quem não suporta vê-lo bem."},
      {"ic":"triangle","t":"A Grandiosidade Precede a Queda","emph":"a Queda","b":"O sucesso embriaga: incha a autoimagem e rompe o cabo que a prendia à realidade. A grandiosidade nega os limites; a confiança madura os usa como mapa. Greene desfila líderes que, intoxicados pelo próprio mito, deixaram de ouvir e despencaram do alto. <strong>O auge é, paradoxalmente, o instante mais perigoso para o ego.</strong>","tip":"<strong>Sinal de alerta:</strong> quanto maior a vitória, mais firme deve ser a âncora no feedback real — e não na fantasia que a própria vitória passa a alimentar.","warn":True},
      {"ic":"scale","t":"Ambição com os Pés no Chão","emph":"Pés no Chão","b":"A alternativa à grandiosidade não é a humildade que paralisa, mas <strong>a ambição alta amarrada ao trabalho e ao feedback constante</strong>. Conheça os seus limites de verdade — não para se acomodar com menos, e sim para saber onde aplicar o esforço e em que ponto vale empurrar a fronteira, de propósito e a tempo.","tip":"<strong>Modelo mental:</strong> a grandiosidade que funciona é uma equação simples — visão grande, somada a feedback real, multiplicada pelo limite honestamente conhecido."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["Aprenda a ler os sinais sutis da inveja antes que ela sabote: o elogio com farpa, a frieza diante do seu êxito.", "Não inflame a comparação desnecessária — a discrição é o melhor escudo contra a inveja alheia.", "Trate o sucesso como o momento mais perigoso para o ego, e mantenha a ambição ancorada na realidade."],
  },
  {
    "slug": "ch08-proposito-conformismo",
    "sub": "CAPÍTULO 8: Propósito, Gênero e o Efeito do Tribunal",
    "intro": "Três forças decidem quem você se torna. O papel de gênero rígido, que amputa metade do seu repertório. A falta de rumo, que entrega o leme à influência alheia. E a pressão do grupo, que dissolve no calor coletivo o juízo que você teria sozinho. As três têm a mesma cura: um centro próprio, firme o bastante para não ser arrastado.",
    "cards": [
      {"ic":"constellation","t":"Reaver a Metade Amputada","emph":"Metade","b":"Encenar um papel de gênero rígido sai caro: você mutila metade de si — o homem que proíbe em si a ternura, a mulher que abafa a própria firmeza. O traço que você decretou ser 'do outro lado' não desaparece; apenas seca dentro de você. <strong>A inteireza derrota a metade</strong>: reaver o polo reprimido alarga o repertório e destrava a criatividade que vinha trancada com ele.","tip":"<strong>Como aplicar:</strong> faça a lista do que você chama de 'coisa do outro gênero' e recupere um traço de cada vez — usando-o como recurso à mão, não como um novo papel a vestir."},
      {"ic":"target","t":"Sem Norte, Folha ao Vento","emph":"Norte","b":"Quem não cultiva voz interior nem rumo torna-se folha ao vento — e a folha ao vento é a presa preferida de toda influência. A tarefa de vida é a vocação que ordena as decisões e dá lastro para aguentar o ruído de fora. <strong>O propósito funciona como bússola: havendo norte por dentro, a pressão de fora perde a força.</strong> Não é um cargo — é a linha mestra que costura o esforço.","tip":"<strong>Modelo mental:</strong> propósito não é o emprego que você ocupa, é o fio que dá sentido ao trabalho — e, de quebra, o que mais imuniza contra a manipulação."},
      {"ic":"person","t":"O Efeito do Tribunal","emph":"Tribunal","b":"Dentro de um grupo coeso, o indivíduo regride: engole opiniões sem mastigar, perde o fio crítico, troca o próprio juízo por um pouco de aprovação. O grupo arrasta seus membros a chancelar o que, sozinhos, recusariam — e, no calor da roda, o consenso começa a passar por verdade. <strong>A aprovação coletiva nunca foi prova de acerto.</strong> O calor da panela é que apaga a dúvida.","tip":"<strong>Regra:</strong> dentro de qualquer grupo, observe a dinâmica de fora — como antropólogo, não como torcedor — e guarde, intacto, um núcleo de juízo que não se entregue ao calor da maioria.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Reintegre o polo de gênero que você reprimiu — a inteireza recupera repertório e criatividade que estavam trancados.", "Defina a sua tarefa de vida: o propósito é o centro interno que imuniza contra a deriva e contra quem quer manobrá-lo.", "Resista ao efeito do tribunal — preserve, dentro de todo grupo, um núcleo crítico que não confunda consenso com verdade."],
  },
  {
    "slug": "ch09-agressao-geracoes-morte",
    "sub": "CAPÍTULO 9: Agressão, Gerações e a Finitude",
    "intro": "As últimas leis tratam das forças que nos movem sem rosto. A agressão, que quase sempre se disfarça de gentileza. O espírito da geração, que nos forma sem pedir licença e que confundimos com pensamento próprio. E a morte, negada por hábito — mas que, encarada de frente, devolve à vida foco e medida.",
    "cards": [
      {"ic":"mask","t":"A Hostilidade de Luvas","emph":"Luvas","b":"A agressão habita todos nós e quase sempre sai fantasiada de cortesia. O passivo-agressivo fere pela omissão: atrasa de propósito, sabota de leve, banca a vítima para deixá-lo em dívida. <strong>Por trás da amabilidade que parece excessiva, procure a hostilidade que não pôde sair pela porta da frente.</strong> E não tome a explosão por força: quem explode não lidera — apenas transborda.","tip":"<strong>Como aplicar:</strong> responda à agressão passiva com limite firme e o nome direto da coisa — nunca com a mesma moeda, nunca com tolerância sem fim."},
      {"ic":"wave","t":"Sua Geração é uma Onda","emph":"Onda","b":"Cada geração nasce dentro de um espírito — valores, medos e oportunidades que a moldam à revelia. Você jura que pensa sozinho; pensa, em boa parte, com o clima mental do seu tempo. Ler o Zeitgeist da própria geração e das vizinhas devolve perspectiva sobre o que parecia natural. <strong>A sua geração não é o mundo inteiro — é uma onda específica</strong>, e surfá-la exige primeiro enxergar a maré.","tip":"<strong>Modelo mental:</strong> pense em gerações como ondas. Pode-se ir a favor ou contra a corrente — mas só depois de tê-la visto; antes disso, ela leva você sem que perceba."},
      {"ic":"leaf","t":"A Morte como Conselheira","emph":"Conselheira","b":"Negar a finitude empurra o essencial para um 'depois' que nunca chega — e a vida escorre no piloto automático do adiamento. Encarar a morte faz o oposto: <strong>diante do fim, o trivial se evapora</strong> e ficam o foco, a gratidão e o senso do que é grande. Não há nisso morbidez alguma; é o filtro mais honesto de prioridades que existe.","tip":"<strong>Regra:</strong> volte de tempos em tempos à pergunta — 'se me restasse pouco tempo, o que eu mudaria hoje?'. A resposta é o mapa, sempre atualizado, do que de fato importa."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["Reconheça a agressão escondida sob a fachada amável e responda a ela com limites firmes e nome direto.", "Decifre o espírito da sua geração — e o das vizinhas — para distinguir o que é seu do que é apenas o clima do seu tempo.", "Medite sobre a finitude: a consciência da morte não escurece a vida, ela acende o foco e revela o que importa."],
  },
  {
    "slug": "ch10-autonomia-razao",
    "sub": "CAPÍTULO 10: Integrando as 18 Leis — Razão e Autonomia",
    "intro": "Aqui Greene fecha o círculo. As dezoito leis não são truques avulsos guardados na manga — encaixadas, formam um mapa da natureza humana. Dominá-lo não serve a vencer o outro, mas a uma conquista mais difícil: deixar de ser movido às cegas por forças invisíveis e passar a agir com consciência. A isso ele dá o nome de autonomia.",
    "cards": [
      {"ic":"constellation","t":"Um Mapa, Não Dezoito Truques","emph":"Mapa","b":"As leis ganham sentido quando se encaixam num só mapa, que cobre três terrenos. O <strong>interior</strong> — emoção, ego, Sombra. O <strong>relacional</strong> — empatia, máscara, inveja. E o <strong>coletivo</strong> — conformismo, gerações, finitude. Cada lei é uma lente isolada; reunidas, devolvem o retrato inteiro de quem age diante de você, e do que age dentro de você.","tip":"<strong>Como aplicar:</strong> ao entrar numa situação difícil, rode o mapa como uma lista de checagem — 'que lei da natureza humana está operando aqui, no outro e, sobretudo, em mim?'."},
      {"ic":"key","t":"A Pergunta que Mantém Limpa a Lente","emph":"Pergunta","b":"Há uma só bússola ética para todo o acervo: <strong>'isto está operando em mim — ou estão usando isto contra mim?'</strong>. Reconhecer a inveja velada, a agressão de luvas, o efeito do tribunal é defesa, jamais arma — porque devolve a escolha a quem tinha sido cegado. Os fins legítimos são o autoconhecimento e a empatia; a manipulação fria, o próprio autor faz questão de desaconselhar.","tip":"<strong>Modelo mental:</strong> a lente é radar, não mira. A vantagem real está na lucidez sobre as forças que o movem — nunca no domínio sobre o outro."},
      {"ic":"spark","t":"A Autonomia é o Destino","emph":"Autonomia","b":"Tudo no mapa converge para um único ponto: deixar de ser empurrado por forças que não se vê. Autonomia é <strong>enxergar com clareza</strong>, sem o filtro do ego; <strong>agir com espontaneidade</strong>, sem ser programado pelo medo ou pela sede de aprovação; e <strong>vincular-se de verdade</strong>, sem jogo nem exploração. É o avesso exato da deriva — escolher o próprio rumo em vez de ser levado por ele.","tip":"<strong>Regra:</strong> autonomia não é ser independente de tudo — é decidir, com os olhos abertos, quais forças você aceita servir e quais recusa."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 10",
    "lessons": ["Use o mapa das dezoito leis como radar: 'que força da natureza humana está operando aqui — no outro e em mim?'.", "Guarde a regra ética que mantém a lente limpa: o fim é o autoconhecimento e a defesa, jamais a manipulação.", "Lembre que a autonomia é o destino de tudo: ver com clareza, agir com espontaneidade e vincular-se sem jogo."],
  },
  {
    "slug": "ch11-emocao-perspectiva-sintese",
    "sub": "CAPÍTULO 11: As Três Alavancas em Ação",
    "intro": "Das dezoito leis, três carregam o peso de todas as outras: empatia, caráter e perspectiva. São as três alavancas — ler o outro por dentro, julgar pelo padrão e não pela promessa, subir acima do impulso para ver o terreno. Quem as exercita em conjunto tem o que basta para atravessar quase qualquer situação social sem ser arrastado.",
    "cards": [
      {"ic":"bubble","t":"Empatia é Músculo, Não Sentimentalismo","emph":"Músculo","b":"Empatia não é doçura: é a leitura precisa do estado interno alheio, e talvez a vantagem social mais rara e duradoura que existe. Treina-se em camadas — <strong>querer entender, captar pelo corpo e pelo tom, estudar a história quando o instinto falha, corrigir-se pela reação real</strong>. Suspender o próprio ego para ler o outro é exatamente o que separa o influente do manipulador.","tip":"<strong>Como aplicar:</strong> antes de uma conversa difícil, pergunte 'que estado emocional esta pessoa traz consigo?' — e deixe a resposta, não o seu humor, governar o seu tom."},
      {"ic":"layers","t":"O Padrão Fala Mais que a Promessa","emph":"Padrão","b":"As pessoas declaram intenções; o caráter revela padrões. Avalie alguém pelo histórico sob pressão e adversidade, não pela frase que ele diz num dia calmo. <strong>Um padrão ruim raramente se quebra sem trabalho deliberado</strong> — não aposte no 'desta vez vai ser diferente' sem prova de mudança. Sob estresse, o passado de uma pessoa é o melhor profeta do seu futuro.","tip":"<strong>Regra:</strong> acredite no padrão, não na promessa — sobretudo no momento em que a pressão aperta e a máscara começa a escorregar do rosto."},
      {"ic":"mountain","t":"A Visão do General","emph":"General","b":"Perspectiva é subir acima da batalha e ler o terreno inteiro. Ela separa o sinal do ruído, o curto do longo prazo, o sintoma da causa — e distingue o reativo do estratégico. <strong>Velocidade sem altitude é apenas reatividade com pressa.</strong> É a alavanca que permite aplicar as outras dezessete leis com serenidade, sem ser arrastado por cada alarme que toca.","tip":"<strong>Modelo mental:</strong> quanto mais acelerado o instante, mais indispensável a pausa para ganhar altura. Suba primeiro; só então decida."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 11",
    "lessons": ["Trate a empatia como músculo a treinar: da atitude de querer entender ao corpo e ao tom, à história, e à correção pelo feedback real.", "Ponha o caráter acima da intenção declarada — sob estresse, o passado é o melhor previsor do que virá.", "Pratique a perspectiva: ganhe altitude antes de ganhar velocidade, e suba acima da batalha antes de decidir."],
  },
]
