# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Maquiavel Pedagogo' (Pascal Bernardin)."""

BOOK = {
  "title": "Maquiavel Pedagogo",
  "author": "Pascal Bernardin",
  "header_light": "MAQUIAVEL",
  "header_bold": "PEDAGOGO",
  "subtitle": "VISÃO GERAL · O MINISTÉRIO DA REFORMA PSICOLÓGICA",
  "intro": "Bernardin documenta uma revolução pedagógica mundial — conduzida por Unesco, OCDE, Conselho da Europa e Comissão de Bruxelas — que troca a instrução pela modificação de “valores, atitudes e comportamentos”, usando técnicas de manipulação psicológica cientificamente validadas. A tese é documental: o autor cita os próprios textos oficiais.",
  "description": "Maquiavel Pedagogo de Pascal Bernardin em cheat sheet: a engenharia social aplicada à educação — dissonância cognitiva e sentimento de liberdade, a inversão atos→opiniões, a Unesco e a modificação de atitudes em escala, a revolução ética e cultural, reescrever a história, os IUFMs, a descentralização como engajamento, a avaliação como leme, a sociedade dual e o totalitarismo psicopedagógico.",
  "tags": ["Educação", "Psicologia Social", "Geopolítica"],
  "progress": "16 Capítulos",
  "cover": "assets/maquiavel-pedagogo-capa.png",
  "overview_cards": [
    {"ic":"pivot","t":"Atos Modificam Opiniões","b":"A inversão que sustenta o projeto: não se muda a crença para mudar o ato — induz-se o ato e a crença segue, por redução de dissonância (Festinger). É a justificação teórica dos “métodos ativos”: quem controla os atos da criança em sala controla, estatisticamente, <strong>seus valores</strong>.","tip":"<strong>Modelo mental:</strong> trate “pedagogia participativa” como engenharia de comportamento — o engajamento vem antes da opinião, não depois.","wide":True},
    {"ic":"key","t":"O Sentimento de Liberdade","b":"O ingrediente ativo de toda manipulação eficaz. Sem ele não há mudança de valor: sob coação consciente o sujeito não se engaja. Por isso a meta é fazer a nova série de valores aparecer ao indivíduo como algo que ele tenha <strong>escolhido livremente</strong> (Lewin/Unesco) — liberdade percebida, não real.","tip":"<strong>Sinal de alerta:</strong> quando uma reforma exalta a participação “livre” e ativa, procure o mecanismo de engajamento por trás — a liberdade sentida é a alavanca."},
    {"ic":"eye","t":"Avalie o Dispositivo, Não o Pretexto","b":"As técnicas nascem sob álibis nobres — antirracismo, paz, direitos humanos, insucesso escolar — e são depois declaradas aplicáveis “às atitudes sociais em geral”. <strong>O que vence o preconceito mais enraizado vencerá com folga as atitudes políticas, econômicas e éticas.</strong> O rótulo legitima; o aparelho permanece.","tip":"<strong>Como aplicar:</strong> diante de qualquer reforma, separe o objetivo declarado da capacidade instalada — e julgue o método, não a bandeira."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch00-ministerio-reforma",
    "sub": "INTRODUÇÃO: O Ministério da Reforma Psicológica",
    "intro": "Uma revolução pedagógica mundial, conduzida por especialistas instalados nos departamentos de educação dos organismos internacionais, visa impor uma “ética voltada à criação de uma nova sociedade” via modificação de valores, atitudes e comportamentos. A escola é o instrumento; o alvo é a sociedade inteira.",
    "cards": [
      {"ic":"steps","t":"Da Psique à Sociedade","emph":"Da Psique","b":"A sequência é declarada: mudança de valores, modificação de atitudes e manipulação da cultura produzem uma revolução psicológica — e esta, “inelutavelmente”, uma revolução social. Você precisa ver que a escola não é o fim: é o vetor. <strong>O alvo final não é a sala de aula, é a sociedade inteira.</strong>","tip":"<strong>Modelo mental:</strong> leia toda reforma escolar como peça de um projeto social maior — pergunte “para que tipo de sociedade isto forma?”."},
      {"ic":"masks","t":"Os Quatro Traços","emph":"Quatro Traços","b":"A revolução pedagógica tem assinatura: testes psicológicos em massa (90% das crianças americanas já fichadas), informatização mundial com censo da população escolar, asfixia do ensino livre e a pretensão de anular a família. Quatro frentes que traem o desenho. <strong>Cada uma parece técnica; só o conjunto revela a arquitetura.</strong>","tip":"<strong>Como aplicar:</strong> não avalie ciclos, IUFMs, avaliação e descentralização isoladamente — a coerência do conjunto é que denuncia o projeto."},
      {"ic":"lens","t":"A Ressalva que Entrega","emph":"Ressalva","b":"Quando um organismo internacional publica um texto “sob responsabilidade do autor”, não se distancia: julgou a tese próxima o bastante para financiá-la. <strong>A influência opera pela escolha de quem fala.</strong> A reforma avança por “discretas manobras, sem deixar ver sua arquitetura geral” — cada medida parece administrativa.","tip":"<strong>Sinal de alerta:</strong> a nota “opiniões do autor” num documento oficial é endosso, não isenção — alguém escolheu, pagou e divulgou aquela voz.","warn":True},
    ],
    "lessons_title": "Lições-Chave da Introdução",
    "lessons": ["A escola é o instrumento, não o fim — o alvo é a sociedade inteira.", "Quatro traços assinam a reforma: testes em massa, informatização, asfixia do ensino livre, neutralização da família.", "Avalie as reformas em conjunto: cada uma parece técnica; o sentido só aparece na arquitetura geral."],
  },
  {
    "slug": "ch01-tecnicas-manipulacao",
    "sub": "CAPÍTULO I: As Técnicas de Manipulação Psicológica",
    "intro": "Existem técnicas simples, estudadas há décadas pela psicologia social, que modificam valores, atitudes e comportamentos de adultos normais. São elas, ensinadas de modo semivelado aos professores, que fundamentam os “métodos pedagógicos ativos”.",
    "cards": [
      {"ic":"shield","t":"A Autoridade Dobra Todos","emph":"Dobra","b":"Em Milgram, mais de 60% aplicam choques até o fim — 85% em alguns países. Não é sadismo: é a autoridade; sem o pesquisador presente, a voltagem despenca. <strong>O comum dos mortais, “simplesmente fazendo seu trabalho”, vira agente de um processo terrível.</strong> Mas basta um par desobedecer e 90% o seguem.","tip":"<strong>Modelo mental:</strong> a obediência não mede o caráter, mede a estrutura — e a contestação de um só é socialmente contagiosa."},
      {"ic":"person","t":"O Grupo Unânime Vence Você","emph":"Unânime","b":"Em Asch, diante de um grupo unânime no erro, cerca de três quartos cedem ao menos uma vez (32% das respostas saem erradas, contra 8% sem pressão). E no ambíguo, mostra Sherif, o grupo cria uma norma que o indivíduo conserva mesmo sozinho depois. <strong>Um único aliado dissidente liberta o sujeito.</strong>","tip":"<strong>Como aplicar:</strong> quebre a falsa unanimidade — uma só voz divergente devolve às pessoas a capacidade de julgar."},
      {"ic":"spiral","t":"A Dissonância Reorganiza Tudo","emph":"Dissonância","b":"Contradição entre valor, opinião e ato força o psiquismo a se reorganizar — e o caminho mais curto é mudar a opinião para casar com o ato (Festinger). Pior: pressão <strong>apenas suficiente</strong> interioriza mais que pressão forte (pagar $1 muda a opinião; $20 não). Atos públicos e repetidos reescrevem os próprios valores.","tip":"<strong>Armadilha:</strong> ameaça fraca convence mais que ameaça forte — sem desculpa externa, o sujeito se convence por dentro.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo I",
    "lessons": ["Os atos modificam as opiniões — não só o contrário; quem controla os atos controla os valores.", "Grupo unânime dobra o indivíduo; um único dissidente o liberta.", "Pressão mínima suficiente interioriza; pressão forte só obtém obediência externa temporária."],
  },
  {
    "slug": "ch02-psicologia-social",
    "sub": "CAPÍTULO II: A Aplicação da Psicologia Social na Educação",
    "intro": "Manuais franceses dirigidos a docentes (Monteil, 1989) recomendam abertamente as técnicas de manipulação como ferramentas educativas — e confessam que as pedagogias “não diretivas” sempre foram “a aplicação camuflada de uma diretriz”.",
    "cards": [
      {"ic":"pivot","t":"A Conduta Cria a Atitude","emph":"a Atitude","b":"A inversão central: a atitude aparece como produto da conduta, não como sua causa. A circunstância induz o comportamento, surge a contradição entre fazer e pensar, vem a racionalização — e “após obedecer, com a sensação de tê-lo feito livremente, os indivíduos adotam o conteúdo do ato”. <strong>Primeiro se age; depois se acredita.</strong>","tip":"<strong>Como aplicar:</strong> ao ver um método que enfatiza “fazer” antes de “entender”, suspeite — a ação é o que remodela a posição interna."},
      {"ic":"fork","t":"Cinco Botões do Engajamento","emph":"Cinco Botões","b":"Kiesler nomeia o que torna um ato comprometedor: ser explícito, importante, irrevogável, repetido e — sobretudo — vir com o sentimento de liberdade. Joule mostra que o engajamento puxa novas condutas, não só novas opiniões. <strong>Um único comportamento, sentido como livre, pode determinar uma cadeia de outros.</strong>","tip":"<strong>Modelo mental:</strong> quanto mais público, repetido e “escolhido” for um ato, mais ele te prende ao que ele implica."},
      {"ic":"mask","t":"A Diretividade Camuflada","emph":"Camuflada","b":"A confissão de Monteil é explícita: as pedagogias não diretivas são “a aplicação camuflada de uma diretriz que tínhamos dificuldade para admitir abertamente”. O vocabulário — “jogos de influência”, “mudança de disposições” — é o da psicologia da manipulação. <strong>Não-diretividade não é ausência de direção: é direção escondida.</strong>","tip":"<strong>Sinal de alerta:</strong> “centrado no aluno” e “não diretivo” são, por admissão dos próprios teóricos, fachadas de uma diretriz.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo II",
    "lessons": ["A conduta induzida cria a atitude — a circunstância remodela a posição interna.", "O engajamento se manipula por cinco fatores; o sentimento de liberdade é o principal.", "Pedagogia “não diretiva” é diretividade camuflada — por confissão dos próprios teóricos."],
  },
  {
    "slug": "ch03-unesco-controle",
    "sub": "CAPÍTULO III: A Unesco e o Controle Psicológico",
    "intro": "O documento “A Modificação das Atitudes” (Davis/Unesco, 1964) projeta aplicar as técnicas de manipulação em escala internacional, sobre comunidades inteiras — não só atitudes intergrupos (o pretexto), mas “as atitudes sociais em geral”, com a escola como dispositivo central.",
    "cards": [
      {"ic":"gap","t":"Do Pretexto ao Geral","emph":"ao Geral","b":"O título não é “atitudes intergrupos”, é “a modificação das atitudes”. As técnicas, criadas sob álibi antirracista, são declaradas aplicáveis a atitudes “políticas, econômicas, sociais, ecológicas, éticas”. <strong>O que dobra o preconceito mais enraizado dobrará com folga o menos enraizado.</strong> O próprio autor admite o corolário.","tip":"<strong>Como aplicar:</strong> distinga o objetivo declarado (relações intergrupos) da capacidade instalada (modificar quaisquer atitudes ao arbítrio de quem manda)."},
      {"ic":"key","t":"Reeducar em Liberdade","emph":"Liberdade","b":"Lewin é citado sem rodeios: “a reeducação significa o estabelecimento de um novo superego… os objetivos só serão atingidos quando a nova série de valores aparecer ao indivíduo como algo que ele tenha escolhido livremente”. <strong>A liberdade percebida é a condição da inculcação</strong> — uma revolução de valores mais profunda que a social.","tip":"<strong>Modelo mental:</strong> “reeducação” aqui é instalar um novo superego — leia “educar” como “reeducar” sempre que o critério for mudar valores."},
      {"ic":"link","t":"Quem Dispõe dos Meios","emph":"dos Meios","b":"Para agir sobre a sociedade inteira, quatro instrumentos: altas personalidades, leis, forças econômicas e meios de comunicação. E a pergunta decisiva, feita pelo próprio texto: <strong>“trata-se de saber quem dispõe desses meios”.</strong> A família vira obstáculo — “para conduzir as crianças, começar pela modificação dos pais”.","tip":"<strong>Sinal de alerta:</strong> os pesquisadores preferem técnicas de grupo e relações interpessoais à propaganda de massa — mais eficazes porque invisíveis.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo III",
    "lessons": ["Desde 1964 a Unesco publica metodologia explícita de modificação de atitudes em escala.", "O grupo de pares escolar substitui a família como “grupo de referência”.", "Quem controla os meios (lei, economia, mídia) controla a reconversão — a família é tratada como obstáculo."],
  },
  {
    "slug": "ch04-redefinicao-escola",
    "sub": "CAPÍTULO IV: A Redefinição do Papel da Escola",
    "intro": "Armada das técnicas, a reforma redefine a escola: do ensino intelectual ao “ensino multidimensional” (ético, cultural, comportamental, político), cuja eficácia é medida “em função da modificação dos comportamentos”. A queda do nível é consequência deliberada, não acidente.",
    "cards": [
      {"ic":"layers","t":"Ensino Multidimensional","emph":"Multidimensional","b":"A escola deixa de transmitir saber para “formar a pessoa inteira” — e a eficácia da educação fundamental passa a ser “avaliada em função da modificação dos comportamentos” (Jomtien). São dois braços: revolução ética e revolução cultural. <strong>Quando o critério vira “mudar comportamentos”, é engenharia social, não instrução.</strong>","tip":"<strong>Modelo mental:</strong> “educação multidimensional” e “saber-ser” sinalizam avaliação de atitudes — leia “educar” como “reeducar”."},
      {"ic":"shelf","t":"O Código que Apaga","emph":"Apaga","b":"Bernstein opõe o código de série — programas nacionais, disciplinas, mérito — ao código integrado, em que a comunidade local define as normas e “os critérios de avaliação se obscurecem” e a seleção desaparece. Módulos e ciclos implementam isso. <strong>Apagar a régua não democratiza: esconde o fracasso do ensino não cognitivo.</strong>","tip":"<strong>Sinal de alerta:</strong> quando os critérios de avaliação “se obscurecem” de propósito, é a régua sendo apagada para que o fracasso não apareça.","warn":True},
      {"ic":"person","t":"O Professor Vira Conselheiro","emph":"Conselheiro","b":"A Unesco reposiciona o docente: não mais “transmissor do saber”, mas “educador e conselheiro”, com tarefas fora do currículo — vida familiar, lazer, aconselhar pais — e como “agente de mudança”. Se precisa dialogar sobre tudo, não sobra tempo para o ensino sólido. <strong>A queda do nível é design, não falha.</strong>","tip":"<strong>Como aplicar:</strong> o aviltamento penaliza os mais pobres — quem tem recursos instrui os filhos por fora; a “democratização” é retórica."},
    ],
    "lessons_title": "Lições-Chave do Capítulo IV",
    "lessons": ["A escola passa, oficialmente, da instrução à modificação de comportamentos.", "O “código integrado” obscurece os critérios e dissolve a seleção — a queda do nível é deliberada.", "O professor é reposicionado como terapeuta e agente de mudança, não como quem transmite saber."],
  },
  {
    "slug": "ch05-revolucao-etica",
    "sub": "CAPÍTULO V: A Revolução Ética",
    "intro": "A reforma substitui os valores morais tradicionais por uma “nova ética” pseudo-universal “elaborada cientificamente” — bloqueando a transmissão familiar de valores e usando a escola para impor uma moral controlada pelo Estado e pelos organismos internacionais.",
    "cards": [
      {"ic":"triangle","t":"Tese, Antítese, Controle","emph":"Controle","b":"A manobra tem três tempos: impedir a transmissão familiar dos valores; diante do caos ético resultante, declarar “imperativo” o retorno à educação moral; e então introduzir novos valores — controlados pelo Estado, não pela família. <strong>Quem reconstrói os valores controla o resultado</strong> — daí o revolucionário virar “defensor da ordem moral”.","tip":"<strong>Sinal de alerta:</strong> quando um mal social cresce e o Estado se oferece como restaurador moral, suspeite — a destruição prévia pode ser parte do plano.","warn":True},
      {"ic":"book","t":"A Família como Adversária","emph":"Adversária","b":"A educação familiar é desqualificada como inconsciente e presa a “valores ligados ao meio social ou religioso”; a escola deve “explicitar” os valores para “superar esse modo pouco seguro de transmissão”. Os direitos da criança viram “temível arma contra a família”. <strong>A escola é posta como rival funcional da casa.</strong>","tip":"<strong>Como aplicar:</strong> leia “explicitar valores na escola” contra “transmissão inconsciente em casa” como disputa de jurisdição moral, não como neutralidade."},
      {"ic":"scale","t":"Ciência no Lugar da Fé","emph":"da Fé","b":"“Toda adoção de valores morais e de crenças deve ser realizada cientificamente”, diz a Unesco — e “os valores religiosos, de todas as religiões, são os primeiros visados”. <strong>Sistemas morais autônomos escapam ao controle estatal</strong>, por isso são o primeiro alvo. A decadência moral é “o tempo necessário ao controle dos valores”.","tip":"<strong>Modelo mental:</strong> a nova ética funciona como substituto de religião: pretende-se universal, científica e não tolera concorrentes."},
    ],
    "lessons_title": "Lições-Chave do Capítulo V",
    "lessons": ["A revolução ética opera por substituição: destrói os valores tradicionais e oferece novos, controlados.", "A escola é posta como adversária da família; os “direitos da criança” servem a esse ataque.", "A decadência moral é consequência deliberada — o tempo necessário ao controle dos valores."],
  },
  {
    "slug": "ch06-revolucao-cultural",
    "sub": "CAPÍTULO VI: A Revolução Cultural e o Interculturalismo",
    "intro": "Interculturalismo não é coexistência de culturas (multiculturalismo), mas a fusão deliberada delas para formar “uma identidade cultural nova”. É uma revolução de alcance epistemológico que ataca “as formas de conhecimento e a hierarquia dos saberes”, rumo a uma cultura e uma língua mundiais.",
    "cards": [
      {"ic":"masks","t":"Fundir, Não Conviver","emph":"Fundir","b":"O salto é deliberado: multicultural = culturas que coexistem; intercultural = fusão que dá nascimento a uma cultura nova, “não mais marcada pelo eurocentrismo ou por um vínculo cego às próprias crenças” (OCDE). <strong>Pôr a própria cultura “no mesmo nível” das mais distantes serve para desenraizar, não para respeitar.</strong>","tip":"<strong>Modelo mental:</strong> trate “interculturalismo” como Gramsci aplicado — revolução cultural por dentro das instituições para dissolver o núcleo identitário."},
      {"ic":"lens","t":"O Alvo Epistemológico","emph":"Epistemológico","b":"A justificação tem três pernas: ética, jurídica e — a decisiva — epistemológica: diferenciar “as formas da inteligibilidade e a estrutura do saber”. É ela que habilita uma “teoria científica da educação multicultural”. <strong>O alvo declarado da OCDE é o “núcleo duro das culturas”</strong>, não apenas as atitudes.","tip":"<strong>Sinal de alerta:</strong> quando “tolerância” vem com justificação epistemológica, o alvo não são atitudes — é a própria estrutura do saber.","warn":True},
      {"ic":"link","t":"Rumo à Língua Mundial","emph":"Mundial","b":"O horizonte é declarado: “uma língua internacional que reforce uma cultura internacional” (Unesco), prelúdio da destruição das culturas locais. Bernardin liga isso à novilíngua de Orwell — “a Revolução estará completa quando a língua for perfeita”. <strong>Restringir a língua é restringir o pensamento.</strong>","tip":"<strong>Como aplicar:</strong> leia “atitude mundialista”, “cultura internacional” e “língua internacional” como o telos do projeto — desenraizar para reprogramar."},
    ],
    "lessons_title": "Lições-Chave do Capítulo VI",
    "lessons": ["Interculturalismo é engenharia de identidade — fusão, não convivência de culturas.", "A justificação epistemológica torna a relativização cultural uma “ciência” aplicável aos programas.", "O horizonte é mundialista: cultura e língua internacionais — restringir a língua é restringir o pensamento."],
  },
  {
    "slug": "ch07-reescrever-historia",
    "sub": "CAPÍTULO VII: Reescrever a História",
    "intro": "A educação para a paz e o interculturalismo exigem reescrever a história: manuais supranacionais redigidos por comitês internacionais, eliminando conflitos e o que contraria a ideologia oficial. “Projeto essencialmente totalitário” que amputa às gerações futuras suas raízes e sua compreensão política.",
    "cards": [
      {"ic":"book","t":"Manuais Supranacionais","emph":"Supranacionais","b":"A Conferência dos Ministros da Educação (Unesco, 1988) propõe um “manual de história geral da Europa” e um “de história universal”, com comitês definindo “orientações comuns”. Não é cooperação técnica: <strong>é definição centralizada do que pode ser lembrado.</strong> “Adversários de ontem, parceiros de hoje” justifica apagar a desconfiança.","tip":"<strong>Como aplicar:</strong> trate “revisão internacional de manuais” como curadoria diplomática da memória — pergunte quem decide o que entra e o que some."},
      {"ic":"eye","t":"Atitude Acima da Verdade","emph":"Acima da Verdade","b":"O texto oficial admite: “a simples apresentação objetiva dos fatos, sendo insuficiente para produzir a atitude desejada…”. O critério passa a ser a atitude que produz, não a verdade — “com utilização das ciências sociais para reforçar o impacto”. <strong>Avaliada pela atitude que gera, a história virou instrumento de modificação de atitudes.</strong>","tip":"<strong>Sinal de alerta:</strong> “objetividade insuficiente para produzir a atitude desejada” é a confissão — a verdade foi subordinada ao efeito.","warn":True},
      {"ic":"wave","t":"O Palimpsesto Permanente","emph":"Palimpsesto","b":"“Aprender a aprender” e “sociedade aprendiz” soam modernos, mas a função é fabricar “uma mentalidade privada de qualquer referência estável… de modo que a noção de verdade seja algo estranho e manipulável”. Bernardin cita Orwell: a história como “palimpsesto, raspado e reescrito”. <strong>Sem referência estável, você fica manipulável à vontade.</strong>","tip":"<strong>Modelo mental:</strong> o relativismo histórico não é abertura — é infraestrutura da manipulação; quem controla o passado controla o presente."},
    ],
    "lessons_title": "Lições-Chave do Capítulo VII",
    "lessons": ["A reescritura da história é proposta formal de conferências ministeriais, não inferência do autor.", "O critério vira a atitude produzida no aluno, não a verdade factual.", "“Aprender a aprender” fabrica mentalidades sem referência estável — matéria-prima da manipulação."],
  },
  {
    "slug": "ch08-iufms",
    "sub": "CAPÍTULO VIII: Os IUFMs — A Formação dos Professores",
    "intro": "Os IUFMs foram criados para formar professores em psicopedagogia, não em saber disciplinar — integrando um projeto mundial que culmina na proposta de “um currículo universal, internacional e padrão, estabelecido sob os auspícios das Nações Unidas”, com manuais e formação docente padronizados.",
    "cards": [
      {"ic":"pivot","t":"O Concurso Invertido","emph":"Invertido","b":"Pelo decreto de 18/10/1991, o candidato de francês “analisa e critica documentos pedagógicos” em vez de demonstrar domínio da língua; em matemática, “analisa situações” e critica pedagogia. A pedagogia substitui o saber já na seleção. <strong>Onde a prova mede didática e não domínio da matéria, seleciona-se manipuladores, não sábios.</strong>","tip":"<strong>Como aplicar:</strong> olhe o que a prova de admissão de fato avalia — ela revela quem o sistema quer formar."},
      {"ic":"person","t":"O Professor Dócil","emph":"Dócil","b":"A formação visa “fazer deles agentes dóceis de políticas cada vez mais revolucionárias”, porque “a aceitação dos professores é condição da difusão”. A docência é o gargalo: sem professores engajados, nada se difunde. <strong>E a reciclagem é permanente: o doutrinamento “não se limita à formação inicial”.</strong>","tip":"<strong>Modelo mental:</strong> a formação contínua não atualiza saber — estende a reeducação a toda a carreira e a todo o pessoal da escola."},
      {"ic":"target","t":"As Crenças como Matéria-Prima","emph":"Matéria-Prima","b":"A “pedagogia centrada no aluno” trata as crenças dele “como recursos para o ensino”, e “o próprio ensino é concebido para mudar as crenças do aluno”. Negociar objetivos, primazia da ação, clarificação de valores — tudo voltado a “revelar as crenças para mudá-las”. <strong>“Centrar no aluno” é acessar suas crenças para reescrevê-las.</strong>","tip":"<strong>Sinal de alerta:</strong> “centralidade do aluno” não é respeito à autonomia — é o ponto de acesso às crenças que se quer modificar.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo VIII",
    "lessons": ["Os IUFMs selecionam e formam pela psicopedagogia, não pelo saber — por decreto.", "A formação docente é o gargalo estratégico: sem professores engajados, nada se difunde.", "“Centrar no aluno” = acessar suas crenças como matéria-prima; o horizonte é um currículo mundial padronizado."],
  },
  {
    "slug": "ch09-descentralizacao",
    "sub": "CAPÍTULO IX: A Descentralização",
    "intro": "A descentralização não é reforma administrativa: é o instrumento psicológico para vencer a resistência passiva dos professores e da sociedade — criando dinâmica de grupo em escala escolar e aplicando a psicologia do engajamento a cada ator (diretor, professor, pais, comunidade).",
    "cards": [
      {"ic":"steps","t":"Autonomia que Aprisiona","emph":"que Aprisiona","b":"Princípios salutares — autonomia ao diretor, participação das coletividades — são desnaturados: o objetivo é envolver a sociedade num consenso sobre reformas “de fato inaceitáveis”. O diretor vira “change agent” e, ao participar, “não pode mais se opor — pé na porta após pé na porta”. <strong>Autonomia concedida é engajamento extorquido.</strong>","tip":"<strong>Como aplicar:</strong> diante de qualquer autonomia concedida, pergunte que política ela obriga a executar — quem ajuda a construir não consegue criticar."},
      {"ic":"fork","t":"Reeducar, Não Convencer","emph":"Reeducar","b":"Chin distingue três estratégias de inovação: coercitivas (poder), empírico-racionais (argumento) e normativas-reeducativas (mudar atitudes e valores “ativando forças no interior do sistema cliente”). <strong>Os organismos usam quase só as terceiras — manipulação, não persuasão racional.</strong> Engajar-se é mais profundo que apenas aceitar.","tip":"<strong>Modelo mental:</strong> “engajar-se” (compreender e pregar a causa) é mais fundo que “aceitar” (só endossar) — o alvo é o primeiro."},
      {"ic":"cards","t":"O Controle pelos Pares","emph":"pelos Pares","b":"O “projeto de escola” obrigatório “engaja coletiva e individualmente” professores e parceiros. O modelo português (PIPSE) põe psicólogos nas equipes e usa “a interação entre profissionais” — confissão da dinâmica de grupo que “exerce o controle social por intermédio do grupo de pares”. <strong>Já testada na China e em Portugal, a técnica “revolucionou o sistema”.</strong>","tip":"<strong>Sinal de alerta:</strong> “projeto de escola”, “trabalho em equipe” e “comunidade educativa” são dinâmica de grupo para vencer a resistência docente.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo IX",
    "lessons": ["A descentralização faz a sociedade aceitar o inaceitável, engajando cada nível.", "As estratégias são normativas e reeducativas — manipulação, não persuasão racional.", "O “projeto de escola” obrigatório é o veículo do controle pelo grupo de pares; já validado na China e em Portugal."],
  },
  {
    "slug": "ch10-avaliacao-informatizacao",
    "sub": "CAPÍTULO X: A Avaliação e a Informatização",
    "intro": "A avaliação deixa de medir o saber e passa a medir — e moldar — atitudes e comportamentos: testes psicológicos em massa, fichamento informatizado individual e bancos de dados interconectáveis em escala mundial. “Os professores ensinarão para responder às exigências do sistema de avaliação.”",
    "cards": [
      {"ic":"pin","t":"A Avaliação é o Leme","emph":"o Leme","b":"A OCDE é direta: “é primordial que os dispositivos de avaliação reflitam plenamente as reformas que se deseja implementar”. Mude o que se mede e todo o sistema se realinha sozinho. <strong>Quando a avaliação muda antes do currículo, é o currículo real que mudou.</strong> O alvo é o “saber-ser”: o domínio afetivo, não o cognitivo.","tip":"<strong>Modelo mental:</strong> a avaliação não mede a reforma, ela a executa — quem controla a avaliação controla o que se ensina."},
      {"ic":"target","t":"Competência Mínima","emph":"Mínima","b":"O nível desejado é o da “competência mínima” — e os iletrados nos EUA saltaram de 18 para 25 milhões em poucos anos; “desde então o governo não mais forneceu estatísticas”. Na França, 20% dos menores de 25 anos sem domínio de leitura. <strong>Privar dos instrumentos intelectuais é o que torna a doutrinação precoce eficaz.</strong>","tip":"<strong>Como aplicar:</strong> trate o “mínimo” como meta, não como piso — é o nível em que o pensamento crítico deixa de poder se defender."},
      {"ic":"link","t":"O Fichamento Individual","emph":"Fichamento","b":"160 questões por aluno respondidas pelos professores; número de identificação secreto como chave de rede; o programa CASIMIR para coleta. Nos EUA, base única que se quer ligar “a bases similares no mundo”, tudo “sem que o povo fosse informado”. Na França, fichas montadas “sem base legal alguma”. <strong>A autoavaliação acrescenta o engajamento do próprio fichado.</strong>","tip":"<strong>Sinal de alerta:</strong> promessa de confidencialidade local é frágil — em um ano a França passou de “dados só da escola” a fornecimento nacional.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo X",
    "lessons": ["A avaliação é o leme: mude o que se mede e o sistema inteiro se realinha.", "A “competência mínima” fabrica iletramento — privar de instrumentos torna a doutrinação eficaz.", "O fichamento psicológico informatizado de alunos (e pais e professores) é a infraestrutura do controle."],
  },
  {
    "slug": "ch11-europa",
    "sub": "CAPÍTULO XI: A Europa",
    "intro": "Embora OCDE, Conselho da Europa e Unesco não tenham poder executivo, sua influência molda as instituições comunitárias. Resoluções do Conselho, programas da Comissão e do Parlamento reproduzem a agenda psicopedagógica — a integração europeia dos sistemas como “prelúdio de uma integração mundial”.",
    "cards": [
      {"ic":"sword","t":"O Cavalo de Troia","emph":"Cavalo de Troia","b":"Sob o rótulo de “luta contra o insucesso escolar” (1989) entram a dimensão multicultural, a escolaridade pré-primária reforçada, a renovação da avaliação, as pedagogias diferenciadas, a abertura à comunidade. Cada “remédio” é uma peça da reforma. <strong>Leia todo programa de “combate ao fracasso” item a item — o rótulo nobre carrega o dispositivo.</strong>","tip":"<strong>Como aplicar:</strong> quando o título é consensual (paz, insucesso, direitos), examine o conteúdo — o álibi legitima técnicas estendidas depois."},
      {"ic":"link","t":"Governo por Capilaridade","emph":"Capilaridade","b":"Instituições “sem poder executivo” governam por resoluções, programas e financiamento: reformas nacionais devem evoluir “dentro de um quadro comum europeu”, harmonização que antecede a padronização mundial. A formação contínua é redesenhada para “gestores de inovação”, não especialistas. <strong>Acompanhe o vocabulário, não as competências formais.</strong>","tip":"<strong>Modelo mental:</strong> documentos “não vinculantes” preparam a legislação — subestimá-los é perder de vista por onde a agenda entra."},
      {"ic":"book","t":"Implicar os Pais","emph":"Implicar","b":"O Parlamento Europeu declara que os sistemas “devem essencialmente visar a implicar os pais na educação das crianças”. Bernardin lê: implicar é engajar, para reduzir a “resistência à mudança”, não para ouvir. E há “acompanhamento dos jovens” após a escola, “um verdadeiro controle psicológico”. <strong>“Interesse dos pais” aqui é engajamento, não empoderamento.</strong>","tip":"<strong>Sinal de alerta:</strong> quando pais e professores são “implicados” ou “consultados”, leia redução de resistência por participação, não partilha de poder.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo XI",
    "lessons": ["A agenda entra na Europa comunitária pela porta do “insucesso escolar”.", "Instituições sem poder executivo governam por capilaridade: resoluções, programas, financiamento.", "“Implicar os pais” é engajá-los para reduzir resistência — e o controle se estende para além da escola."],
  },
  {
    "slug": "ch12-franca",
    "sub": "CAPÍTULO XII: A Revolução Pedagógica na França",
    "intro": "A “revolução silenciosa” (expressão da própria OCDE) aterrissa na França via módulos e ciclos: todos os temas internacionais entram por via administrativa — e sobrevivem às alternâncias de governo, do socialista Jack Lang ao conservador François Bayrou.",
    "cards": [
      {"ic":"steps","t":"Entra pelo Boletim Oficial","emph":"Boletim Oficial","b":"A revolução não passa por debate público: entra por boletins oficiais (BO de 4/6/1992). Módulos nos liceus criam o quadro da pedagogia centrada no aluno, com avaliação permanente; ciclos no primário fazem o professor acompanhar alunos por anos. O Le Figaro registra o “recuo dramático no ensino da cultura geral”. <strong>Avalie estruturas, não discursos.</strong>","tip":"<strong>Como aplicar:</strong> módulos e ciclos são as formas concretas do ensino não cognitivo — olhe a estrutura, não o nome do ministro."},
      {"ic":"cards","t":"O Grupo de Pares Fabricado","emph":"Fabricado","b":"A queixa dos pais sobre a “influência dos grupos de pares” tem causa declarada: “esse fenômeno não é espontâneo. É resultado de uma política de socialização deliberada, que visa a fazer do grupo de pares o grupo de referência”, mais receptivo às influências dominantes que o indivíduo. <strong>Família que definha e pares que crescem: procure a política, não o acaso.</strong>","tip":"<strong>Sinal de alerta:</strong> a influência do grupo de pares sobre as crianças é engenharia deliberada de controle social — não um efeito natural da idade.","warn":True},
      {"ic":"pivot","t":"Sobrevive à Alternância","emph":"à Alternância","b":"O caso Bayrou é o teste: ministro cristão, conservador, anticomunista — e ainda assim seu “triângulo de ouro” (inovação + avaliação anual + formação contínua) reproduz os temas da revolução internacional. Manteve ciclos, módulos e IUFMs. <strong>Boas intenções somadas a instituições capturadas dão resultados revolucionários.</strong>","tip":"<strong>Modelo mental:</strong> reformar dentro do quadro capturado (IUFMs, psicopedagogias) é abrir espaço que o ensino não cognitivo ocupará primeiro."},
    ],
    "lessons_title": "Lições-Chave do Capítulo XII",
    "lessons": ["A revolução entra por boletins oficiais, não por debate público — avalie estruturas, não discursos.", "A influência do grupo de pares é engenharia deliberada de socialização e controle.", "A alternância de governo não interrompe nada: conservadores bem-intencionados viram vetores quando ignoram a captura."],
  },
  {
    "slug": "ch13-sociedade-dual",
    "sub": "CAPÍTULO XIII: A Sociedade Dual",
    "intro": "A queda do nível escolar é projeto, não falha: os próprios reformadores confessam objetivos políticos, não intelectuais. O resultado buscado é uma sociedade dual — ensino não cognitivo para a massa, formação intelectual verdadeira (mas ideologicamente cauciada) para uma elite cooptada.",
    "cards": [
      {"ic":"masks","t":"A Confissão de Legrand","emph":"Confissão","b":"Legrand admite que os métodos ativos não servem aos “objetivos intelectuais clássicos” — “a pedagogia formal impositiva é a única que convém” à seleção; “o problema não é técnico, é político”. Dewey vai além: “não há justificação social para a simples aquisição de ciência”. <strong>O baixo nível é deliberado — a inteligência individual é o alvo.</strong>","tip":"<strong>Como aplicar:</strong> quando a “democratização” estagna por décadas, pergunte o que o sistema otimiza — socialização (controle), não emancipação."},
      {"ic":"scale","t":"Massa e Elite","emph":"Massa e Elite","b":"Povalyaev (Unesco, 1989): “a sociedade moderna não tem necessidade de muitas pessoas instruídas… os mais dotados devem receber o melhor”. Prost confirma: as reformas “organizaram o recrutamento da elite escolar no seio da elite social”. <strong>A escola que nivela por baixo não abole a elite: só passa sua seleção a critérios sociais e ideológicos.</strong>","tip":"<strong>Modelo mental:</strong> os apóstolos da incultura receberam educação de elite — a dualidade está embutida no projeto, não é acidente."},
      {"ic":"shield","t":"Controle Não Aversivo","emph":"Não Aversivo","b":"Skinner via Bernardin: “os modos primitivos de controle foram substituídos por técnicas não aversivas, das quais o povo não tem consciência. Manipulado, ele não percebe que é controlado”. Mais eficaz que o totalitarismo clássico, pois elimina a revolta latente. <strong>O controle invisível não suscita oposição.</strong>","tip":"<strong>Sinal de alerta:</strong> o controle que não dói é o mais perigoso — sem revolta latente, ninguém procura a saída que não sente faltar.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo XIII",
    "lessons": ["O baixo nível é confessadamente deliberado — a inteligência individual é o alvo.", "O destino é a dualidade: educação não cognitiva para a massa, formação de elite cooptada ideologicamente.", "O controle social moderno é não aversivo e invisível — mais estável que a coerção."],
  },
  {
    "slug": "ch14-totalitarismo",
    "sub": "CAPÍTULO XIV: O Totalitarismo Psicopedagógico",
    "intro": "A revolução psicopedagógica é essencialmente totalitária: busca “submeter o indivíduo ao Estado, tanto em seu comportamento quanto em seu psiquismo e em seu próprio ser”. E o dispositivo não se limita à escola — estende-se “do berço ao túmulo”, a toda a sociedade.",
    "cards": [
      {"ic":"person","t":"O Modelo de Adulto Ideal","emph":"Adulto Ideal","b":"Toda taxonomia de objetivos pedagógicos “subentende um modelo de adulto ideal… é preciso coragem para admitir que se escolheu este ou aquele”; Russell: “precisamos ter uma concepção do tipo de pessoa que desejamos formar”. <strong>Todo “objetivo pedagógico” pressupõe um modelo de homem; pergunte quem o escolheu</strong> — sem debate público.","tip":"<strong>Modelo mental:</strong> teste qualquer objetivo educacional perguntando que adulto ideal ele supõe — e quem teve autoridade para defini-lo."},
      {"ic":"clock","t":"Do Berço ao Túmulo","emph":"Do Berço ao Túmulo","b":"A “educação permanente” da Unesco é uma rede total: “todo ano, todo mês, todo dia, do berço ao túmulo, todo mundo aprenderá… em casa, na escola, na usina, no hospital, no templo, no cinema, no sindicato, no partido”. Nenhum espaço fica fora. <strong>Leia “sociedade aprendiz” como reeducação contínua, não como oportunidade.</strong>","tip":"<strong>Sinal de alerta:</strong> “educação permanente” e “do berço ao túmulo” descrevem a extensão do dispositivo escolar à vida inteira.","warn":True},
      {"ic":"target","t":"A Mobilização Total","emph":"Total","b":"Quem “controlar a educação terá a iniciativa”, disse um conselheiro chinês na Unesco. O Quadro de Ação de Jomtien mobiliza ONGs, sindicatos, empregadores, mídia, partidos, universidades, organismos religiosos e ministérios — trabalho, saúde, comércio, defesa. <strong>A lista mede a ambição: um regime, não uma política setorial.</strong>","tip":"<strong>Como aplicar:</strong> o mesmo aparato opera na empresa (RH) e na mídia; adultos não estão imunes — magistrados, médicos e policiais são alvos nomeados."},
    ],
    "lessons_title": "Lições-Chave do Capítulo XIV",
    "lessons": ["O totalitarismo psicopedagógico controla o comportamento, o psiquismo e o ser.", "Toda pedagogia por objetivos pressupõe um modelo de homem escolhido por alguém, sem debate público.", "A educação permanente universaliza o dispositivo no tempo (vida inteira) e no espaço (todas as instituições)."],
  },
  {
    "slug": "ch15-conclusao",
    "sub": "CONCLUSÃO: Desmascarar, Conscientizar, Opor",
    "intro": "O papel da escola é redefinido “por um processo antidemocrático no qual as reformas são introduzidas sub-repticiamente”. A resposta exige desmascarar a ditadura psicológica — condição prévia de toda oposição — e medidas institucionais urgentes.",
    "cards": [
      {"ic":"layers","t":"Os Cinco Elementos","emph":"Cinco Elementos","b":"A síntese reduz o projeto a cinco peças: revolução ética e cultural na visão dos professores; “inovação” pedagógica que introduz as técnicas em sala; formação inicial e permanente dos docentes; descentralização do sistema; e informatização da avaliação. <strong>Os cinco estão presentes nas reformas francesas recentes</strong> — o diagnóstico fecha o arco do livro.","tip":"<strong>Como aplicar:</strong> use os cinco elementos como checklist ao ler qualquer reforma — se os cinco aparecem juntos, o desenho é o mesmo."},
      {"ic":"eye","t":"Desmascarar Vem Primeiro","emph":"Vem Primeiro","b":"A opressão não aversiva (Skinner) “não suscita oposição” — por isso “deve ser inicialmente desmascarada; somente depois, quando os povos tenham tomado consciência da malignidade dos processos, a oposição será possível”. A ordem importa: desmascarar, conscientizar, opor. <strong>Sem tornar visível o controle invisível, nenhuma resistência nasce.</strong>","tip":"<strong>Modelo mental:</strong> contra o controle que não dói, o primeiro ato político não é lutar — é revelar; só o visível pode ser combatido."},
      {"ic":"wrench","t":"As Medidas Urgentes","emph":"Urgentes","b":"Bernardin propõe um programa concreto: fechar IUFMs, CNDP, CRDPs e INRP; suprimir a formação continuada; banir as psicopedagogias; restaurar os programas; desmantelar as redes internacionais. <strong>Se a concepção de formação docente em vigor é a “crítica/social”, o professor já foi redefinido como agente político.</strong>","tip":"<strong>Sinal de alerta:</strong> o apelo é transpartidário — democracia, liberdade e dignidade humana como base; tratar o problema como só escolar é subestimá-lo.","warn":True},
    ],
    "lessons_title": "Lições-Chave da Conclusão",
    "lessons": ["O diagnóstico cabe em cinco elementos — todos presentes nas reformas recentes.", "A oposição começa pela denúncia: tornar visível o controle invisível (desmascarar → conscientizar → opor).", "A receita: fechar as instituições de doutrinamento, banir as psicopedagogias e restaurar os programas, com apoio transpartidário."],
  },
]
