# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Memórias do Subsolo' (Fiódor Dostoiévski)."""

BOOK = {
  "title": "Memórias do Subsolo",
  "author": "Fiódor Dostoiévski",
  "header_light": "MEMÓRIAS DO",
  "header_bold": "SUBSOLO",
  "subtitle": "VISÃO GERAL · A LIBERDADE COMO DOENÇA E COMO DIGNIDADE",
  "intro": "Um funcionário aposentado, amargo e hiperconsciente, escreve do seu 'subsolo'. Na Parte 1 ataca o racionalismo e defende o livre-arbítrio (o '2+2=5'); na Parte 2 prova, em episódios humilhantes, ser incapaz de agir e de amar. A obra que abriu o caminho para o existencialismo.",
  "description": "Análise de Memórias do Subsolo de Dostoiévski: o anti-herói e o estado do subsolo, a hiperconsciência que paralisa, o ataque ao palácio de cristal e ao utilitarismo de Tchernichévski, o livre-arbítrio e o capricho contra o determinismo, o jantar humilhante com Zvérkov, Liza e a incapacidade de amar, o narrador não confiável e o legado existencialista.",
  "tags": ["Literatura Clássica", "Filosofia", "Existencialismo"],
  "progress": "8 Capítulos",
  "cover": "assets/memorias-do-subsolo-cover.png",
  "overview_cards": [
    {"ic":"gap","t":"O Homem do Subsolo","b":"O narrador sem nome é o <strong>anti-herói moderno</strong>: funcionário aposentado, amargo, ressentido, 'doente de tanta consciência'. O 'subsolo' (подполье) é menos um porão que um estado da alma — o isolamento de quem despreza os outros e não consegue deixar de precisar deles.","tip":"<strong>Para o leitor:</strong> o subsolo é diagnóstico, não modelo — Dostoiévski o descreve para ser reconhecido, não admirado."},
    {"ic":"triangle","t":"Anti-Racionalismo: 2+2=5","b":"Contra o utilitarismo de Tchernichévski e o 'palácio de cristal' (a utopia racional onde tudo é calculado), o subsolo reivindica o direito de dizer <strong>'2+2=5'</strong> — não porque seja verdade, mas porque a liberdade de discordar é mais humana que a verdade imposta.","tip":"<strong>Modelo mental:</strong> '2+2=5' não é matemática — é manifesto do livre-arbítrio contra qualquer sistema que trate o homem como engrenagem determinada."},
    {"ic":"spiral","t":"A Hiperconsciência que Paralisa","b":"Ser consciente demais é, para ele, uma <strong>doença</strong>: quem examina cada impulso o dissolve e não age. O homem 'espontâneo' (que o subsolo desdenha) age; o hiperconsciente observa, hesita, se corrói — e tira prazer doentio da própria humilhação.","tip":"<strong>Como aplicar:</strong> excesso de autoanálise pode ser fuga da ação — identifique quando o 'pensar melhor' é procrastinação disfarçada."},
    {"ic":"mask","t":"Incapacidade de Amar","b":"O clímax moral da obra: ao encontrar Liza (jovem prostituta), o narrador oferece salvação com um discurso comovente — e a destrói quando ela acredita. A <strong>incapacidade de amar</strong> é o subsolo em sua forma mais pura: o afeto o desarma, então ele o ataca.","tip":"<strong>Modelo mental:</strong> quem só sabe se relacionar por hierarquia (humilhar ou ser humilhado) não consegue o amor que exige igualdade."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-o-homem-do-subsolo",
    "sub": "CAPÍTULO 1: O Homem do Subsolo — O Anti-Herói",
    "intro": "'Sou um homem doente... Sou um homem mau.' A frase de abertura instala o tom de toda a novela. O narrador sem nome é funcionário aposentado de Petersburgo, ressentido e isolado. O 'subsolo' é menos um porão que um estado da alma: o isolamento de quem se recusa a viver entre os homens e os despreza por isso.",
    "cards": [
      {"ic":"gap","t":"O Subsolo como Estado da Alma","emph":"Estado da Alma","b":"O subsolo não é um porão de tijolos, é o <strong>isolamento arrogante e doentio da consciência hipertrofiada</strong>. O narrador se afasta dos homens porque os despreza profundamente, mas precisa desesperadamente da plateia deles para se sentir alguém. Sem os olhos alheios que ele tanto odeia, o monólogo ácido não faz o menor sentido.","tip":"<strong>Sinal de alerta:</strong> o isolamento crônico que se alimenta de desprezar o mundo é um veneno, não é sabedoria superior.","warn":True},
      {"ic":"mask","t":"O Anti-Herói sem Ação","emph":"Anti-Herói","b":"O herói dos livros age no mundo; o habitante do subsolo é <strong>definido precisamente pela sua impotência amarga</strong>. Sua 'grandeza' repousa unicamente no ressentimento elaborado e na engenharia de planos perversos que ele jamais tira do papel. Dostoiévski esfrega na nossa cara o primeiro anti-herói real da literatura ocidental.","tip":"<strong>Modelo mental:</strong> o ressentimento refinado é o prêmio de consolação daqueles que não têm a coragem prática de mudar as coisas."},
      {"ic":"spiral","t":"Prazer no Sofrimento","emph":"Prazer no Sofrimento","b":"O homem do subsolo arranca uma satisfação doentia e enraizada <strong>da própria humilhação arrastada</strong>. Para ele, ser esmagado conscientemente é prova de superioridade filosófica diante do gado que é feliz sem pensar. Sofrer com lucidez doentia torna-se muito mais sedutor do que consertar a própria vida arruinada.","tip":"<strong>Prática:</strong> cuidado quando a sua queixa virar o seu troféu preferido; o 'sofrimento consciente' disfarça muito bem o medo de agir."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["O subsolo é estado da alma: isolamento que se alimenta do que odeia e precisa de plateia para existir.", "O anti-herói é definido pela impotência — o ressentimento é a rebeldia de quem não age.", "Prazer no sofrimento consciente pode ser fuga da mudança real — 'sofrer bem' é confortável."],
  },
  {
    "slug": "ch02-hiperconsciencia-paralisia",
    "sub": "CAPÍTULO 2: A Hiperconsciência que Paralisa",
    "intro": "Ser consciente demais é, para o narrador, uma doença. Quem examina cada impulso o dissolve antes de agir. O homem 'espontâneo' — que o subsolo desdenha como burro — age; o hiperconsciente apenas observa, hesita e se corrói. A consciência excessiva é o veneno que aprisiona.",
    "cards": [
      {"ic":"spiral","t":"Consciência como Doença","emph":"Consciência","b":"A mente afiada não é o farol que ilumina o caminho, é a <strong>lupa maldita que dissolve a vontade</strong>. O homem que pensa em excesso examina cada impulso inofensivo até estraçalhar a energia necessária para dar o primeiro passo. Essa consciência que devora a si mesma não é inteligência madura; é a paralisia absoluta do corpo.","tip":"<strong>Modelo mental:</strong> o abismo da autoanálise infinita não entrega respostas reais, ele apenas serve para sabotar as ações urgentes do dia."},
      {"ic":"mountain","t":"O Homem 'Espontâneo' × O Hiperconsciente","emph":"Espontâneo","b":"O narrador destila veneno e desprezo contra o homem de ação direta que age sem questionar as engrenagens. Mas, no fundo escuro, ele morre de inveja porque <strong>o burro espontâneo ao menos consegue existir e realizar as coisas</strong>. Ser brilhante e ficar inerte num canto sombrio é mil vezes pior do que a ignorância que de fato vive e respira.","tip":"<strong>Sinal de alerta:</strong> usar a genialidade ácida para ridicularizar quem está fazendo o trabalho sujo é a defesa patética dos covardes estáticos.","warn":True},
      {"ic":"eye","t":"O Prazer Invertido da Dor","emph":"Prazer Invertido","b":"Analisar as próprias feridas com bisturi não é busca de cura, é um <strong>vício silencioso na dor exposta</strong>. 'Sofrer é vantagem!', berra o subsolo, porque a angústia elaborada parece nobre em comparação à alegria banal. Quando o tormento ganha o selo falso de genialidade, o homem agarra as correntes em vez de tentar arrebentá-las de vez.","tip":"<strong>Prática:</strong> toda vez que você sentar num canto confortável narrando os próprios problemas com orgulho intelectual, levante e faça o oposto."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["Hiperconsciência é doença: dissolve cada impulso antes que ele se realize em ação.", "O homem 'espontâneo' que age sem examinar demais é mais vivo que o hiperconsciente mais 'inteligente'.", "Quando a dor passa a ser identidade, resiste à cura — o sofrimento consciente pode ser confortavelmente aprisionante."],
  },
  {
    "slug": "ch03-palacio-de-cristal-2x2",
    "sub": "CAPÍTULO 3: O Palácio de Cristal e o 2+2=4",
    "intro": "O núcleo polêmico da Parte 1: o narrador ataca o racionalismo e o utilitarismo de Tchernichévski. O 'palácio de cristal' simboliza a utopia cientificista — ordem perfeita e transparente onde nada se pode mudar: uma prisão dourada. Contra a tirania do '2+2=4', o subsolo reivindica o direito de afirmar '2+2=5'.",
    "cards": [
      {"ic":"triangle","t":"O Palácio de Cristal — Prisão Dourada","emph":"Palácio de Cristal","b":"A utopia racionalista que promete calcular cada sorriso humano num projeto matemático perfeito é um ataque brutal à nossa essência rebelde. Num mundo onde a cartilha resolve a miséria e tabela a alegria universalmente, <strong>não sobra nenhum pedaço de chão sujo e irregular para a liberdade pisar</strong>. A perfeição absoluta vira um caixão incrustado de diamantes deslumbrantes e sem saída.","tip":"<strong>Modelo mental:</strong> desconfie ferozmente das doutrinas modernas que tentam apagar todos os riscos da vida; a gaiola é gaiola independentemente do luxo."},
      {"ic":"spark","t":"2+2=5 — Manifesto do Livre-Arbítrio","emph":"2+2=5","b":"Gritar contra a matemática exata não é falha de intelecto, é o <strong>grito rasgado da alma defendendo o direito inalienável de dizer não</strong>. Se a ciência prova que a tecla deve descer daquele jeito inquestionável, o humano escolhe propositalmente a rebeldia do erro que queima só para provar a sua independência absoluta da fórmula imposta.","tip":"<strong>Prática:</strong> compreenda o valor essencial da desobediência: submeter-se a uma cartilha inteira que suga a sua vontade destrói o núcleo de quem você é."},
      {"ic":"sword","t":"O Muro de Pedra","emph":"Muro de Pedra","b":"As leis frias da natureza representam o muro estúpido e cinzento. O racionalista encosta a testa reverente e aceita obedecer em paz; o homem do subsolo, entretanto, <strong>atira o próprio corpo contra os blocos fechados até sangrar</strong>. Ele não tem esperança ingênua de quebrar a pedra bruta; ele apenas atesta ali, com os ossos quebrados, que a submissão humilde é inaceitável.","tip":"<strong>Sinal de alerta:</strong> não se trata de tentar ignorar as leis inquebráveis do mundo físico, mas de se recusar violentamente a venerá-las como um fim.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["O palácio de cristal (utopia racional) é prisão dourada — a perfeição que elimina toda escolha é morte da liberdade.", "'2+2=5' é manifesto do livre-arbítrio: o direito de discordar da verdade imposta é mais humano que a obediência ao cálculo.", "O muro de pedra (leis da natureza) divide os que reverenciam a necessidade dos que recusam, pelo gesto, ser engrenagem."],
  },
  {
    "slug": "ch04-livre-arbitrio-capricho",
    "sub": "CAPÍTULO 4: O Livre-Arbítrio e o Capricho",
    "intro": "A tese central da novela: contra o utilitarismo que garante que o homem esclarecido sempre escolherá o que lhe convém, o subsolo responde que o bem supremo não é a felicidade — é a vontade livre. O homem é capaz de agir contra seu próprio interesse só para provar que não é 'tecla de piano'.",
    "cards": [
      {"ic":"key","t":"A Vontade — Acima do Interesse","emph":"Vontade","b":"O utilitarismo engravatado prega que o humano busca apenas e tão somente maximizar o bem-estar gordo na balança. O subsolo quebra a mesa inteira e aponta o dedo: o tesouro supremo e intangível de um homem <strong>nunca foi a felicidade matemática, foi a liberdade caprichosa de escolher querer o que dá na telha</strong>.","tip":"<strong>Modelo mental:</strong> nenhum sistema puramente prático consegue aprisionar a loucura humana; as pessoas detonarão coisas maravilhosas só para sentir que têm o comando."},
      {"ic":"person","t":"A Tecla de Piano — Contra o Determinismo","emph":"Tecla de Piano","b":"O modelo mecanicista transforma o sangue e os nervos em cordinhas apertadas que vibram sob comandos externos previsíveis e fáceis. Mas o humano recusa esse lugar minúsculo no tablado: ele arrasta as unhas no quadro negro e age <strong>visceralmente contra o próprio interesse cego</strong> só para mostrar à audiência fria que não é uma engrenagem escrava e programada.","tip":"<strong>Prática:</strong> perceba quando alguém destrói uma oportunidade incrível puramente porque se sentiu encaixotado ou obrigado a dizer sim."},
      {"ic":"fork","t":"Agir Contra Si — O Paradoxo","emph":"Agir Contra Si","b":"Prefiro engolir ácido e destruir meu palácio a permitir que controlem o botão que dita minha dor ou felicidade amanhã cedo. É o coração negro e complexo da nossa natureza: <strong>a autossabotagem brutal erguida como a última prova inegável e sangrenta da nossa autonomia no palco do mundo</strong>.","tip":"<strong>Sinal de alerta:</strong> muito cuidado com a linha tênue onde a defesa corajosa da liberdade resvala feio para um padrão doente e imbecil de destruição dos próprios caminhos.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["O bem supremo, para o subsolo, não é a felicidade — é a vontade livre. A raiz do existencialismo.", "A 'tecla de piano' é o homem como engrenagem determinada — a rebeldia do capricho é a prova de humanidade.", "A autossabotagem como afirmação de liberdade é diagnóstico, não modelo — é a liberdade sem outro campo de exercício."],
  },
  {
    "slug": "ch05-parte-2-jantar-humilhacao",
    "sub": "CAPÍTULO 5 (Parte 2): O Jantar e a Humilhação",
    "intro": "A Parte 2 encena a filosofia da Parte 1: a teoria vira biografia fracassada. O narrador se autoconvida ao jantar em honra de Zvérkov (oficial bonito e rico, que ele inveja e despreza), é humilhado, exige um duelo e ainda assim os persegue. Ele procura a humilhação: a dor o faz sentir-se vivo.",
    "cards": [
      {"ic":"wave","t":"A Teoria Vira Biografia","emph":"Biografia","b":"As elucubrações geniais que encostaram a razão moderna contra a parede na primeira parte <strong>espatifam-se no chão sujo e cru da vida mundana da segunda</strong>. O mesmo teórico sombrio que dissecou a liberdade cai trêmulo e minúsculo diante dos olhares fúteis num restaurante medíocre qualquer. A tese maravilhosa é aniquilada brutalmente pela incompetência emocional social do portador real e prático.","tip":"<strong>Modelo mental:</strong> nenhuma ideia espetacular de papel consegue cobrir ou justificar os buracos dolorosos que você não resolve na sua vida real."},
      {"ic":"mask","t":"Zvérkov — A Inveja Disfarçada","emph":"Inveja Disfarçada","b":"O narrador exibe os dentes rangendo num falso desprezo esnobe contra o militar rico e fútil do outro lado da mesa. Mas a máquina raio-x literária revela o núcleo nojento: o ar de altivez moral <strong>é o escudo podre erguido por uma inveja corrosiva inconfessável</strong>. Ele cospe na uva deliciosa de Zvérkov unicamente e raivosamente porque jamais conseguiria alcançá-la.","tip":"<strong>Prática:</strong> seja radicalmente honesto: qual repulsa ética fortíssima sua esconde apenas frustração e ressentimento por algo que te foi negado?"},
      {"ic":"gap","t":"Buscar a Humilhação","emph":"Humilhação","b":"O personagem patético avança na noite arrastando os sapatos no bordel obscuro e mendigando forçadamente um xingamento dolorido na roda dos conhecidos fúteis e vazios. <strong>A presença marcada pelo vexame patético é imensamente mais calorosa e desejada do que o tormento surdo e mudo de ser ignorado ou invisível</strong>.","tip":"<strong>Sinal de alerta:</strong> quem puxa briga escandalosa à toa em qualquer rodinha só está gritando esganiçado no megafone que morre de pavor de não fazer a menor falta.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["A Parte 2 encena e desmonta a Parte 1: o filósofo da liberdade fracassa quando tenta vivê-la.", "Desprezo por Zvérkov é desprezo que encobre inveja — o ressentimento é inveja disfarçada de superioridade moral.", "Buscar a humilhação é buscar existência — a dor dolorosa é preferível à invisibilidade para o homem do subsolo."],
  },
  {
    "slug": "ch06-liza-incapacidade-de-amar",
    "sub": "CAPÍTULO 6: Liza — A Redenção Oferecida e Negada",
    "intro": "Ferido pelo jantar, no bordel o narrador domina Liza (jovem prostituta) com um discurso comovente de salvação. Liza acredita e o procura. Quando ela chega, ele desmascara a farsa — confessa que falou por despeito, humilha-a e a paga. É o retrato definitivo da incapacidade de amar.",
    "cards": [
      {"ic":"mask","t":"O Discurso-Arma","emph":"Discurso-Arma","b":"Embalado num verniz brilhante de salvador ético iluminado com conselhos valiosos, o homem do subsolo destila uma pregação comovente à prostituta perdida. Porém o conteúdo exato das frases <strong>é movido estritamente pelo despeito violento e pelo prazer macabro de fazê-la chorar para dominá-la mentalmente</strong>.","tip":"<strong>Modelo mental:</strong> dizer coisas inegáveis não faz do emissor um santo; a verdade pura atirada de forma perversa é tão brutal quanto uma adaga bem afiada."},
      {"ic":"gap","t":"Incapacidade de Amar","emph":"Incapacidade","b":"Quando Liza atravessa o quarto humilde rasgando as barreiras com pena amorosa cristalina e afeto cru sem defesas reais da alma nua exposta limpa, o narrador <strong>a escorraça furiosamente atirando dinheiro para feri-la fundo</strong>. Ele detesta a compaixão e não suporta o amor nítido porque amar sem as máscaras bélicas exige a mesma igualdade que ele sempre recusou dar ou receber.","tip":"<strong>Sinal de alerta:</strong> afugentar quem estende uma mão leal no escuro prova uma incapacidade desesperadora covarde de sair do escudo de proteção hostil e sujo.","warn":True},
      {"ic":"leaf","t":"Liza — A Superior Moral","emph":"Liza","b":"Liza, a moça caída na noite, despida de recursos vazios fúteis doentios opacos e sem a casca teórica brilhante fria cínica mentirosa, exibe uma visão humanitária colossal gigante pura forte viva. Ao virar as costas para a humilhação covarde doentia cega suja do apartamento <strong>ela deixa o ouro sobre a mesa não como um tapa ressentido infantil raivoso do subsolo oco falso, mas como a majestade absoluta da verdadeira superioridade limpa imensurável nua viva e real do perdão</strong>.","tip":"<strong>Prática:</strong> o título, o currículo e a teoria não entregam estofo moral a ninguém; repare na força crua de quem está esmagado na roda."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["A sinceridade do conteúdo não garante a bondade da intenção — palavras verdadeiras podem dominar.", "A crueldade com Liza é defesa: o subsolo não suporta ser amado porque amar exige igualdade que ele nega.", "Liza é a superior moral da cena — a inversão do clichê romântico é a tese central de Dostoiévski."],
  },
  {
    "slug": "ch07-narrador-estrutura-duas-partes",
    "sub": "CAPÍTULO 7: O Narrador e a Estrutura em Duas Partes",
    "intro": "A forma é o argumento. Parte 1 (ideia) → Parte 2 (encarnação): leem-se uma contra a outra. A voz é um dos primeiros narradores não confiáveis da literatura — mente, se contradiz, interpela 'os senhores'. O final é uma antinarrativa: sem redenção, o narrador interrompe o relato.",
    "cards": [
      {"ic":"eye","t":"Narrador Não Confiável","emph":"Narrador Não Confiável","b":"Ele diz uma coisa ruidosa arrogante brilhante agressiva veloz irônica genial, volta atrás pateticamente infantil e depois vomita veneno sobre quem acreditou na farsa. A genialidade desse registro espasmódico falso vacilante instável doentio cru e genial de Dostoiévski <strong>é escancarar um narrador cuja alma treme instável incapaz de sustentar uma posição moral ou ética perante os outros e a si mesmo por mais de três parágrafos contínuos</strong>.","tip":"<strong>Modelo mental:</strong> na vida, como no livro escuro denso sujo, repare na costura das desculpas longas dadas: a contradição esconde a ferida latejante profunda verdadeira."},
      {"ic":"layers","t":"A Estrutura em Duas Partes","emph":"Estrutura","b":"O livro é um machado de dois gumes densos frios afiados implacáveis letais que não perdoam o leitor ingênuo: na parte teórica pesada ácida você se curva à filosofia; na biografia crua da segunda parte <strong>você presencia como as teses soberbas falham de forma avassaladora e dolorosa frente ao chão real sujo fútil frio escuro raso inútil torto do contato social humano mínimo básico diário</strong>.","tip":"<strong>Prática:</strong> recuse separar as duas faces da moeda cínica tola do personagem frágil gélido sujo falso louco fraco cínico torto. Não existe tese forte desvinculada das pernas nulas na praça."},
      {"ic":"gap","t":"A Antinarrativa","emph":"Antinarrativa","b":"Livre do arco triunfal hollywoodiano tolo fofo rosa doce irreal em que o herói enxerga o sol, aprende, melhora, cresce limpo fofo pacífico purificado puro no final ameno bonito calmo feliz e sereno da luz mágica final. O subsolo não perdoa as fábulas doentias infantis fáceis soltas e fecha as portas do escuro <strong>abandonando o narrador mergulhado irreversivelmente sujo na podridão cínica do abismo do ressentimento circular eterno que ele escolheu não largar nulo frio cego vazio suado raso vazio cego sujo cego mudo frio duro raso inútil torto de modo inabalável sujo pálido oco cego amargo cru</strong>.","tip":"<strong>Sinal de alerta:</strong> não force lições moralistas rasas finais fáceis redentoras num padrão estático fechado escuro cínico doentio podre que por essência não busca o ar limpo fofo para poder se curar.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["O narrador não confiável é pioneiro — as contradições são os dados mais importantes, não os erros.", "A estrutura em duas partes é o argumento: a teoria (Parte 1) se testa e colapsa na vida (Parte 2).", "A antinarrativa (sem redenção) é escolha estética intencional — o subsolo não cresce, fecha-se sobre si mesmo."],
  },
  {
    "slug": "ch08-legado-existencialismo-simbolos",
    "sub": "CAPÍTULO 8: Legado, Existencialismo e Símbolos",
    "intro": "'Memórias do Subsolo' abre a grande fase de Dostoiévski e é uma das raízes do existencialismo. Prefigura Raskólnikov, Ivan Karamázov e o Grande Inquisidor. Os símbolos condensam a tese em imagens que percorrem toda a obra.",
    "cards": [
      {"ic":"spark","t":"Raiz do Existencialismo","emph":"Raiz do Existencialismo","b":"Bem antes que a filosofia francesa colocasse gravatas formais nulas polidas no conceito pesado livre denso existencial nulo denso e criasse modas frias intelectuais nos cafés europeus limpos pálidos soltos fáceis o homem sujo enfiado na névoa opaca ruidosa triste de Petersburgo <strong>bateu as botas suadas na mesa afirmando furioso agressivo rebelde que nossa vontade caprichosa crua torta arrebenta qualquer essência moldada matemática exata pura nocauteando o gesso imposto</strong>.","tip":"<strong>Modelo mental:</strong> veja o subsolo não como um monólogo neurótico solto, mas como o martelo pioneiro furioso que racha a ciência exata determinista ocidental cega e fria."},
      {"ic":"link","t":"Ponte na Obra de Dostoiévski","emph":"Ponte","b":"Este panfleto denso raivoso veloz é a sala de testes febril e caótica onde a alma amargurada ganha facas: o ódio teórico frio letal antecipa Raskólnikov no machado gelado limpo ruidoso e o desprezo contra o paraíso imposto pavimenta as lajes do Grande Inquisidor majestoso amargo escuro cruel e frio cínico pesado. <strong>As grandes pedras monumentais densas clássicas do autor repousam inteiramente nesses rascunhos abissais sujos loucos fracos furiosos amargos e raivosos</strong>.","tip":"<strong>Prática:</strong> enxergue as grandes decisões ruins dos líderes como frutos podres diretos desastrados venenosos oriundos exatamente dessa teia doentia circular do ressentimento."},
      {"ic":"eye","t":"Os Símbolos — O Mapa","emph":"Símbolos","b":"Dostoiévski atira as munições não com frases mastigadas, mas esculpindo obeliscos conceituais inesquecíveis: o subsolo escuro inóspito cego ruidoso fraco é o espelho do distanciamento cínico, o muro impenetrável de rochas opacas brutas sólidas e fortes mortas dita os limites intransponíveis do mundo contra a força vital. <strong>A matemática do 2+2=5 ergue-se ensurdecedora rebelde suja louca forte altíssima cega como o escudo da nossa dignidade teimosa imprevisível e nua contra as prisões do conforto rasteiro mecânico matemático oco</strong>.","tip":"<strong>Como aplicar:</strong> na próxima vez em que o sistema apresentar um palácio blindado limpo exato frio impecável mudo, exija um pedacinho sujo fora da métrica para sentir-se vivo nulo fútil torto cego e humano real suado quente e denso."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Memórias do Subsolo é a raiz do existencialismo literário — liberdade antes da essência, vontade antes da razão.", "O homem do subsolo prefigura Raskólnikov, Ivan e o Grande Inquisidor — a novela é o laboratório dos personagens maiores.", "Os símbolos (palácio de cristal, tecla de piano, 2×2=5) são argumentos condensados em imagem — leia-os filosoficamente."],
  },
]
