# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Memórias do Subsolo' (Fiódor Dostoiévski)."""

BOOK = {
  "title": "Memórias do Subsolo",
  "author": "Fiódor Dostoiévski",
  "header_light": "MEMÓRIAS DO",
  "header_bold": "SUBSOLO",
  "subtitle": "VISÃO GERAL · 2+2=5, OU O DIREITO DE QUERER CONTRA MIM MESMO",
  "intro": "Sou um homem doente, um homem mau — e é deste meu buraco que falo com os senhores. Toda a minha sabedoria cabe numa insolência: prefiro dizer que <em>dois e dois são cinco</em>. Não porque seja verdade, mas porque a aritmética que me promete felicidade me reduz a tecla de piano, e eu quero ao menos o direito de tocar a nota errada. Depois confesso a prova: deram-me uma moça que me amava, e respondi-lhe com dinheiro na cara. Os senhores acham que estou me vangloriando? Talvez. Mas reparem — eu rio de mim antes que os senhores tenham tempo de rir.",
  "description": "Memórias do Subsolo (1864) é a confissão de um homem sem nome que escreve do porão da própria consciência. Na Parte 1 ele demole o 'palácio de cristal' de Tchernichévski: contra a utopia que calcula a felicidade humana como quem resolve uma equação, ergue o capricho, o livre-arbítrio e o escandaloso 2+2=5. Na Parte 2 a teoria desce à carne e se desmoraliza — o jantar humilhante com Zvérkov, e Liza, a quem ele oferece salvação só para arrancá-la de volta. Um narrador que mente, se contradiz e interpela 'os senhores'; um livro que se recusa a crescer, a aprender, a redimir-se — e, nessa recusa, inaugura o existencialismo.",
  "tags": ["Literatura Clássica", "Filosofia", "Existencialismo"],
  "progress": "8 Capítulos",
  "cover": "assets/memorias-do-subsolo-cover.png",
  "overview_cards": [
    {"ic":"gap","t":"O Homem do Subsolo","b":"Quem fala é um funcionário aposentado, sem nome, mau e <strong>'doente de tanta consciência'</strong>. O 'subsolo' (подполье) não é um porão de tijolos: é um estado da alma. É o canto de quem despreza os homens e, ao mesmo tempo, não vive sem a plateia deles — porque um veneno só faz efeito se há quem o veja borbulhar.","tip":"<strong>Para o leitor:</strong> o subsolo é diagnóstico, não modelo. Dostoiévski o pinta para que o reconheçamos em nós, não para que o admiremos nele."},
    {"ic":"triangle","t":"Anti-Racionalismo: 2+2=5","b":"Contra o 'palácio de cristal' de Tchernichévski — a utopia onde a ciência calcula a felicidade até a última casa decimal —, o subsolo crava o seu <strong>'2+2=5'</strong>. Não por ignorância da conta, mas por orgulho: o direito de discordar é mais humano que a verdade que me é enfiada goela abaixo.","tip":"<strong>Modelo mental:</strong> '2+2=5' não é matemática, é manifesto. É a recusa de ser engrenagem num sistema que confunde 'o que te convém' com 'o que vais querer'."},
    {"ic":"spiral","t":"A Hiperconsciência que Paralisa","b":"Pensar demais, aqui, é uma <strong>doença</strong>. Quem disseca cada impulso o mata antes de agir — e fica a olhar, hesitar e a apodrecer. O homem 'espontâneo', que o subsolo chama de burro e inveja em segredo, ao menos vive; o hiperconsciente troca a vida pela autópsia da vida.","tip":"<strong>Como aplicar:</strong> desconfie quando 'preciso pensar melhor' começa a soar igualzinho a 'tenho medo de agir'. A lucidez infinita é uma cadeira muito confortável."},
    {"ic":"mask","t":"Incapacidade de Amar","b":"O clímax moral: a Liza, prostituta, ele oferece salvação num discurso que faz chorar — e a despedaça no instante em que ela acredita. A <strong>incapacidade de amar</strong> é o subsolo em estado puro: o afeto o desarma, e tudo o que ele sabe fazer com quem o desarma é atacar.","tip":"<strong>Modelo mental:</strong> quem só conhece duas posições — humilhar ou ser humilhado — não cabe no amor, porque amar exige a igualdade que ele nunca aprendeu a suportar."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-o-homem-do-subsolo",
    "sub": "CAPÍTULO 1: O Homem do Subsolo — O Anti-Herói",
    "intro": "'Sou um homem doente... Sou um homem mau.' A primeira frase já é a sentença de tudo o que vem depois. Quem a profere é um funcionário aposentado de Petersburgo, sem nome, ressentido, encolhido no seu canto. O 'subsolo' não fica embaixo de casa nenhuma: é onde mora a alma que se recusa a viver entre os homens — e que, no mesmo gesto, os despreza para não admitir que precisa deles.",
    "cards": [
      {"ic":"gap","t":"O Subsolo como Estado da Alma","emph":"Estado da Alma","b":"O subsolo não tem tijolos: é o <strong>isolamento orgulhoso de uma consciência inchada demais</strong>. O narrador se tranca porque despreza os homens — e, no entanto, é só para esses mesmos homens que ele escreve. Tira o público que ele tanto odeia e o monólogo ácido fica falando para a parede.","tip":"<strong>Sinal de alerta:</strong> o desprezo pelo mundo, transformado em modo de vida, não é sabedoria superior — é um veneno que o solitário guarda para si mesmo.","warn":True},
      {"ic":"mask","t":"O Anti-Herói sem Ação","emph":"Anti-Herói","b":"O herói dos romances faz coisas; o homem do subsolo é definido <strong>justamente pelo que não faz</strong>. Toda a sua 'grandeza' cabe no ressentimento bem-arquitetado e em vinganças geniais que nunca saem do papel. Dostoiévski nos entrega aqui o primeiro anti-herói de verdade — feito não de feitos, mas de feridas.","tip":"<strong>Modelo mental:</strong> o ressentimento refinado é o prêmio de consolação de quem não teve a coragem prosaica de mudar a própria vida."},
      {"ic":"spiral","t":"Prazer no Sofrimento","emph":"Prazer no Sofrimento","b":"Ele extrai um gozo torto da <strong>própria humilhação</strong>. Ser esmagado, mas com consciência, lhe parece um título de nobreza diante do gado feliz que não pensa. Sofrer lucidamente acaba sendo mais sedutor do que a tarefa banal e ingrata de consertar a vida.","tip":"<strong>Prática:</strong> cuidado quando a queixa começa a virar troféu. O 'sofrimento consciente' é uma fantasia elegante que o medo de agir adora vestir."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["O subsolo é um estado da alma: um isolamento que se nutre do que odeia e precisa de plateia para existir.", "O anti-herói define-se pela impotência — o ressentimento é a rebeldia de quem nunca passa do plano à ação.", "O prazer no sofrimento consciente costuma ser fuga da mudança real: 'sofrer bem' é uma cadeira confortável demais."],
  },
  {
    "slug": "ch02-hiperconsciencia-paralisia",
    "sub": "CAPÍTULO 2: A Hiperconsciência que Paralisa",
    "intro": "Para o narrador, ter consciência demais é adoecer. Quem examina cada impulso o dissolve antes que ele vire gesto. O homem 'espontâneo' — que o subsolo chama de burro — age e pronto; o hiperconsciente fica a olhar, a hesitar, a se corroer. Aqui a inteligência não é farol: é a corda que prende o tornozelo.",
    "cards": [
      {"ic":"spiral","t":"Consciência como Doença","emph":"Consciência","b":"A mente afiada não ilumina o caminho — é a <strong>lupa que queima a vontade antes do primeiro passo</strong>. Quem pensa em excesso revira cada impulso inofensivo até não sobrar energia para nada. Essa consciência que se devora a si mesma não é maturidade; é uma paralisia com diploma.","tip":"<strong>Modelo mental:</strong> a autoanálise sem fim raramente entrega respostas. O que ela entrega, com pontualidade, é a desculpa para não agir hoje."},
      {"ic":"mountain","t":"O Homem 'Espontâneo' × O Hiperconsciente","emph":"Espontâneo","b":"O narrador cospe desprezo no homem de ação que não perde tempo questionando as engrenagens. Mas é desprezo com inveja por dentro: <strong>o tal burro, ao menos, existe e realiza</strong>. Ser brilhante e inerte num canto é pior que ser tolo e estar vivo no meio da rua.","tip":"<strong>Sinal de alerta:</strong> usar a inteligência só para ridicularizar quem faz o trabalho é a defesa preferida de quem não sai do lugar.","warn":True},
      {"ic":"eye","t":"O Prazer Invertido da Dor","emph":"Prazer Invertido","b":"Cutucar as próprias feridas, para ele, não é buscar cura — é um <strong>vício secreto na dor</strong>. 'Sofrer é uma vantagem!', proclama o subsolo, porque a angústia bem elaborada parece nobre ao lado da alegria rasa dos outros. Quando o tormento ganha ares de genialidade, o homem passa a abraçar as correntes em vez de arrebentá-las.","tip":"<strong>Prática:</strong> quando se pegar narrando os próprios problemas com certo orgulho intelectual, suspeite. Esse orgulho costuma ser a coleira disfarçada de medalha."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["A hiperconsciência é doença: dissolve cada impulso antes que ele tenha a chance de virar ato.", "O homem 'espontâneo', que age sem examinar tudo, está mais vivo que o hiperconsciente mais brilhante.", "Quando a dor vira identidade, ela resiste à cura — o sofrimento consciente é uma prisão de portas abertas que ninguém atravessa."],
  },
  {
    "slug": "ch03-palacio-de-cristal-2x2",
    "sub": "CAPÍTULO 3: O Palácio de Cristal e o 2+2=4",
    "intro": "Aqui está o coração polêmico da Parte 1, e a mira tem nome: Tchernichévski e a sua fé na razão que organiza tudo. O 'palácio de cristal' é a utopia cientificista — uma ordem perfeita, transparente, onde nada se pode mexer: uma prisão de vidro. Contra a tirania do '2+2=4', o subsolo levanta, teimoso, o seu '2+2=5'.",
    "cards": [
      {"ic":"triangle","t":"O Palácio de Cristal — Prisão Dourada","emph":"Palácio de Cristal","b":"A utopia que promete calcular cada sorriso humano num projeto impecável é, no fundo, um atentado contra o que temos de mais vivo. Onde a cartilha resolve a miséria e tabela a alegria, <strong>não sobra um palmo de chão torto para a liberdade pisar</strong>. A perfeição total tem o formato exato de um caixão — e não importa que seja de cristal.","tip":"<strong>Modelo mental:</strong> desconfie das doutrinas que prometem apagar todo risco da vida. Uma gaiola continua gaiola, por mais transparentes que sejam as grades."},
      {"ic":"spark","t":"2+2=5 — Manifesto do Livre-Arbítrio","emph":"2+2=5","b":"Gritar contra a conta certa não é burrice — é o <strong>direito de dizer 'não' levado às últimas consequências</strong>. Se a ciência prova que a tecla tem de descer assim, o homem escolhe de propósito a nota errada, só para lembrar ao mundo que ele não é o piano.","tip":"<strong>Prática:</strong> entenda o valor da desobediência. Render-se inteiro a uma fórmula que dispensa a sua vontade é entregar a chave do que faz de você alguém."},
      {"ic":"sword","t":"O Muro de Pedra","emph":"Muro de Pedra","b":"As leis da natureza são o muro: cinzento, surdo, inegociável. O racionalista encosta a testa, faz reverência e obedece em paz. O homem do subsolo, não — ele <strong>se atira contra a pedra até sangrar</strong>. Sabe que não vai derrubá-la; quer apenas deixar ali, com os próprios ossos, o protesto de quem se recusa a venerar o que o esmaga.","tip":"<strong>Sinal de alerta:</strong> não se trata de negar as leis do mundo físico, mas de não as adorar como destino. Obedecer é uma coisa; ajoelhar-se, outra.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["O palácio de cristal é uma prisão de cristal: a perfeição que elimina toda escolha é a morte da liberdade.", "'2+2=5' é manifesto do livre-arbítrio — discordar da verdade imposta é mais humano que obedecer ao cálculo certo.", "O muro de pedra separa dois homens: o que faz reverência à necessidade e o que, pelo gesto, recusa ser engrenagem."],
  },
  {
    "slug": "ch04-livre-arbitrio-capricho",
    "sub": "CAPÍTULO 4: O Livre-Arbítrio e o Capricho",
    "intro": "A tese central da novela: contra o utilitarismo que garante que o homem esclarecido sempre escolherá o que lhe convém, o subsolo responde que o bem supremo não é a felicidade — é a vontade livre. O homem é capaz de agir contra seu próprio interesse só para provar que não é 'tecla de piano'.",
    "cards": [
      {"ic":"key","t":"A Vontade — Acima do Interesse","emph":"Vontade","b":"O utilitarismo engravatado prega que o humano busca apenas e tão somente maximizar o bem-estar gordo na balança. O subsolo quebra a mesa inteira e aponta o dedo: o tesouro supremo e intangível de um homem <strong>nunca foi a felicidade matemática, foi a liberdade caprichosa de escolher querer o que dá na telha</strong>.","tip":"<strong>Modelo mental:</strong> nenhum sistema puramente prático consegue aprisionar a loucura humana; as pessoas detonarão coisas maravilhosas só para sentir que têm o comando."},
      {"ic":"person","t":"A Tecla de Piano — Contra o Determinismo","emph":"Tecla de Piano","b":"O modelo mecanicista transforma o sangue e os nervos em cordinhas apertadas que vibram sob comandos externos previsíveis e fáceis. Mas o humano recusa esse lugar minúsculo no tablado: ele arrasta as unhas no quadro negro e age <strong>visceralmente contra o próprio interesse cego</strong> só para mostrar à audiência fria que não é uma engrenagem escrava e programada.","tip":"<strong>Prática:</strong> perceba quando alguém destrói uma oportunidade incrível puramente porque se sentiu encaixotado ou obrigado a dizer sim."},
      {"ic":"fork","t":"Agir Contra Si — O Paradoxo","emph":"Agir Contra Si","b":"Prefiro engolir ácido e destruir meu palácio a permitir que controlem o botão que dita minha dor ou felicidade amanhã cedo. É o coração negro e complexo da nossa natureza: <strong>a autossabotagem brutal erguida como a última prova inegável e sangrenta da nossa autonomia no palco do mundo</strong>.","tip":"<strong>Sinal de alerta:</strong> muito cuidado com a linha tênue onde a defesa corajosa da liberdade resvala feio para um padrão doente e imbecil de destruição dos próprios caminhos.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["O bem supremo, para o subsolo, não é a felicidade — é a vontade livre. A raiz do existencialismo.", "A 'tecla de piano' é o homem como engrenagem determinada — a rebeldia do capricho é a prova de humanidade.", "A autossabotagem como afirmação de liberdade é diagnóstico, não modelo — é a liberdade sem outro campo de exercício."],
  },
  {
    "slug": "ch05-parte-2-jantar-humilhacao",
    "sub": "CAPÍTULO 5 (Parte 2): O Jantar e a Humilhação",
    "intro": "A Parte 2 encena a filosofia da Parte 1: a teoria vira biografia fracassada. O narrador se autoconvida ao jantar em honra de Zvérkov (oficial bonito e rico, que ele inveja e despreza), é humilhado, exige um duelo e ainda assim os persegue. Ele procura a humilhação: a dor o faz sentir-se vivo.",
    "cards": [
      {"ic":"wave","t":"A Teoria Vira Biografia","emph":"Biografia","b":"As elucubrações geniais que encostaram a razão moderna contra a parede na primeira parte <strong>espatifam-se no chão sujo e cru da vida mundana da segunda</strong>. O mesmo teórico sombrio que dissecou a liberdade cai trêmulo e minúsculo diante dos olhares fúteis num restaurante medíocre qualquer. A tese maravilhosa é aniquilada brutalmente pela incompetência emocional social do portador real e prático.","tip":"<strong>Modelo mental:</strong> nenhuma ideia espetacular de papel consegue cobrir ou justificar os buracos dolorosos que você não resolve na sua vida real."},
      {"ic":"mask","t":"Zvérkov — A Inveja Disfarçada","emph":"Inveja Disfarçada","b":"O narrador exibe os dentes rangendo num falso desprezo esnobe contra o militar rico e fútil do outro lado da mesa. Mas a máquina raio-x literária revela o núcleo nojento: o ar de altivez moral <strong>é o escudo podre erguido por uma inveja corrosiva inconfessável</strong>. Ele cospe na uva deliciosa de Zvérkov unicamente e raivosamente porque jamais conseguiria alcançá-la.","tip":"<strong>Prática:</strong> seja radicalmente honesto: qual repulsa ética fortíssima sua esconde apenas frustração e ressentimento por algo que te foi negado?"},
      {"ic":"gap","t":"Buscar a Humilhação","emph":"Humilhação","b":"O personagem patético avança na noite arrastando os sapatos no bordel obscuro e mendigando forçadamente um xingamento dolorido na roda dos conhecidos fúteis e vazios. <strong>A presença marcada pelo vexame patético é imensamente mais calorosa e desejada do que o tormento surdo e mudo de ser ignorado ou invisível</strong>.","tip":"<strong>Sinal de alerta:</strong> quem puxa briga escandalosa à toa em qualquer rodinha só está gritando esganiçado no megafone que morre de pavor de não fazer a menor falta.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["A Parte 2 encena e desmonta a Parte 1: o filósofo da liberdade fracassa quando tenta vivê-la.", "Desprezo por Zvérkov é desprezo que encobre inveja — o ressentimento é inveja disfarçada de superioridade moral.", "Buscar a humilhação é buscar existência — a dor dolorosa é preferível à invisibilidade para o homem do subsolo."],
  },
  {
    "slug": "ch06-liza-incapacidade-de-amar",
    "sub": "CAPÍTULO 6: Liza — A Redenção Oferecida e Negada",
    "intro": "Ferido pelo jantar, no bordel o narrador domina Liza (jovem prostituta) com um discurso comovente de salvação. Liza acredita e o procura. Quando ela chega, ele desmascara a farsa — confessa que falou por despeito, humilha-a e a paga. É o retrato definitivo da incapacidade de amar.",
    "cards": [
      {"ic":"mask","t":"O Discurso-Arma","emph":"Discurso-Arma","b":"Embalado num verniz brilhante de salvador ético iluminado com conselhos valiosos, o homem do subsolo destila uma pregação comovente à prostituta perdida. Porém o conteúdo exato das frases <strong>é movido estritamente pelo despeito violento e pelo prazer macabro de fazê-la chorar para dominá-la mentalmente</strong>.","tip":"<strong>Modelo mental:</strong> dizer coisas inegáveis não faz do emissor um santo; a verdade pura atirada de forma perversa é tão brutal quanto uma adaga bem afiada."},
      {"ic":"gap","t":"Incapacidade de Amar","emph":"Incapacidade","b":"Quando Liza atravessa o quarto humilde rasgando as barreiras com pena amorosa cristalina e afeto cru sem defesas reais da alma nua exposta limpa, o narrador <strong>a escorraça furiosamente atirando dinheiro para feri-la fundo</strong>. Ele detesta a compaixão e não suporta o amor nítido porque amar sem as máscaras bélicas exige a mesma igualdade que ele sempre recusou dar ou receber.","tip":"<strong>Sinal de alerta:</strong> afugentar quem estende uma mão leal no escuro prova uma incapacidade desesperadora covarde de sair do escudo de proteção hostil e sujo.","warn":True},
      {"ic":"leaf","t":"Liza — A Superior Moral","emph":"Liza","b":"Liza, a moça caída na noite, despida de recursos vazios fúteis doentios opacos e sem a casca teórica brilhante fria cínica mentirosa, exibe uma visão humanitária colossal gigante pura forte viva. Ao virar as costas para a humilhação covarde doentia cega suja do apartamento <strong>ela deixa o ouro sobre a mesa não como um tapa ressentido infantil raivoso do subsolo oco falso, mas como a majestade absoluta da verdadeira superioridade limpa imensurável nua viva e real do perdão</strong>.","tip":"<strong>Prática:</strong> o título, o currículo e a teoria não entregam estofo moral a ninguém; repare na força crua de quem está esmagado na roda."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["A sinceridade do conteúdo não garante a bondade da intenção — palavras verdadeiras podem dominar.", "A crueldade com Liza é defesa: o subsolo não suporta ser amado porque amar exige igualdade que ele nega.", "Liza é a superior moral da cena — a inversão do clichê romântico é a tese central de Dostoiévski."],
  },
  {
    "slug": "ch07-narrador-estrutura-duas-partes",
    "sub": "CAPÍTULO 7: O Narrador e a Estrutura em Duas Partes",
    "intro": "A forma é o argumento. Parte 1 (ideia) → Parte 2 (encarnação): leem-se uma contra a outra. A voz é um dos primeiros narradores não confiáveis da literatura — mente, se contradiz, interpela 'os senhores'. O final é uma antinarrativa: sem redenção, o narrador interrompe o relato.",
    "cards": [
      {"ic":"eye","t":"Narrador Não Confiável","emph":"Narrador Não Confiável","b":"Ele diz uma coisa ruidosa arrogante brilhante agressiva veloz irônica genial, volta atrás pateticamente infantil e depois vomita veneno sobre quem acreditou na farsa. A genialidade desse registro espasmódico falso vacilante instável doentio cru e genial de Dostoiévski <strong>é escancarar um narrador cuja alma treme instável incapaz de sustentar uma posição moral ou ética perante os outros e a si mesmo por mais de três parágrafos contínuos</strong>.","tip":"<strong>Modelo mental:</strong> na vida, como no livro escuro denso sujo, repare na costura das desculpas longas dadas: a contradição esconde a ferida latejante profunda verdadeira."},
      {"ic":"layers","t":"A Estrutura em Duas Partes","emph":"Estrutura","b":"O livro é um machado de dois gumes densos frios afiados implacáveis letais que não perdoam o leitor ingênuo: na parte teórica pesada ácida você se curva à filosofia; na biografia crua da segunda parte <strong>você presencia como as teses soberbas falham de forma avassaladora e dolorosa frente ao chão real sujo fútil frio escuro raso inútil torto do contato social humano mínimo básico diário</strong>.","tip":"<strong>Prática:</strong> recuse separar as duas faces da moeda cínica tola do personagem frágil gélido sujo falso louco fraco cínico torto. Não existe tese forte desvinculada das pernas nulas na praça."},
      {"ic":"gap","t":"A Antinarrativa","emph":"Antinarrativa","b":"Livre do arco triunfal hollywoodiano tolo fofo rosa doce irreal em que o herói enxerga o sol, aprende, melhora, cresce limpo fofo pacífico purificado puro no final ameno bonito calmo feliz e sereno da luz mágica final. O subsolo não perdoa as fábulas doentias infantis fáceis soltas e fecha as portas do escuro <strong>abandonando o narrador mergulhado irreversivelmente sujo na podridão cínica do abismo do ressentimento circular eterno que ele escolheu não largar nulo frio cego vazio suado raso vazio cego sujo cego mudo frio duro raso inútil torto de modo inabalável sujo pálido oco cego amargo cru</strong>.","tip":"<strong>Sinal de alerta:</strong> não force lições moralistas rasas finais fáceis redentoras num padrão estático fechado escuro cínico doentio podre que por essência não busca o ar limpo fofo para poder se curar.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["O narrador não confiável é pioneiro — as contradições são os dados mais importantes, não os erros.", "A estrutura em duas partes é o argumento: a teoria (Parte 1) se testa e colapsa na vida (Parte 2).", "A antinarrativa (sem redenção) é escolha estética intencional — o subsolo não cresce, fecha-se sobre si mesmo."],
  },
  {
    "slug": "ch08-legado-existencialismo-simbolos",
    "sub": "CAPÍTULO 8: Legado, Existencialismo e Símbolos",
    "intro": "'Memórias do Subsolo' abre a grande fase de Dostoiévski e é uma das raízes do existencialismo. Prefigura Raskólnikov, Ivan Karamázov e o Grande Inquisidor. Os símbolos condensam a tese em imagens que percorrem toda a obra.",
    "cards": [
      {"ic":"spark","t":"Raiz do Existencialismo","emph":"Raiz do Existencialismo","b":"Bem antes que a filosofia francesa colocasse gravatas formais nulas polidas no conceito pesado livre denso existencial nulo denso e criasse modas frias intelectuais nos cafés europeus limpos pálidos soltos fáceis o homem sujo enfiado na névoa opaca ruidosa triste de Petersburgo <strong>bateu as botas suadas na mesa afirmando furioso agressivo rebelde que nossa vontade caprichosa crua torta arrebenta qualquer essência moldada matemática exata pura nocauteando o gesso imposto</strong>.","tip":"<strong>Modelo mental:</strong> veja o subsolo não como um monólogo neurótico solto, mas como o martelo pioneiro furioso que racha a ciência exata determinista ocidental cega e fria."},
      {"ic":"link","t":"Ponte na Obra de Dostoiévski","emph":"Ponte","b":"Este panfleto denso raivoso veloz é a sala de testes febril e caótica onde a alma amargurada ganha facas: o ódio teórico frio letal antecipa Raskólnikov no machado gelado limpo ruidoso e o desprezo contra o paraíso imposto pavimenta as lajes do Grande Inquisidor majestoso amargo escuro cruel e frio cínico pesado. <strong>As grandes pedras monumentais densas clássicas do autor repousam inteiramente nesses rascunhos abissais sujos loucos fracos furiosos amargos e raivosos</strong>.","tip":"<strong>Prática:</strong> enxergue as grandes decisões ruins dos líderes como frutos podres diretos desastrados venenosos oriundos exatamente dessa teia doentia circular do ressentimento."},
      {"ic":"eye","t":"Os Símbolos — O Mapa","emph":"Símbolos","b":"Dostoiévski atira as munições não com frases mastigadas, mas esculpindo obeliscos conceituais inesquecíveis: o subsolo escuro inóspito cego ruidoso fraco é o espelho do distanciamento cínico, o muro impenetrável de rochas opacas brutas sólidas e fortes mortas dita os limites intransponíveis do mundo contra a força vital. <strong>A matemática do 2+2=5 ergue-se ensurdecedora rebelde suja louca forte altíssima cega como o escudo da nossa dignidade teimosa imprevisível e nua contra as prisões do conforto rasteiro mecânico matemático oco</strong>.","tip":"<strong>Como aplicar:</strong> na próxima vez em que o sistema apresentar um palácio blindado limpo exato frio impecável mudo, exija um pedacinho sujo fora da métrica para sentir-se vivo nulo fútil torto cego e humano real suado quente e denso."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Memórias do Subsolo é a raiz do existencialismo literário — liberdade antes da essência, vontade antes da razão.", "O homem do subsolo prefigura Raskólnikov, Ivan e o Grande Inquisidor — a novela é o laboratório dos personagens maiores.", "Os símbolos (palácio de cristal, tecla de piano, 2×2=5) são argumentos condensados em imagem — leia-os filosoficamente."],
  },
]
