# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Memórias do Subsolo' (Fiódor Dostoiévski)."""

BOOK = {
  "title": "Memórias do Subsolo",
  "author": "Fiódor Dostoiévski",
  "header_light": "MEMÓRIAS DO",
  "header_bold": "SUBSOLO",
  "subtitle": "VISÃO GERAL · 2+2=5, OU O DIREITO DE QUERER CONTRA MIM MESMO",
  "intro": "Sou um homem doente, um homem mau — e é deste meu buraco que falo com os senhores. Toda a minha sabedoria cabe numa insolência: prefiro dizer que <em>dois e dois são cinco</em>. Não porque eu não saiba a conta, mas porque a aritmética que me promete a felicidade me reduz a tecla de piano — e eu quero, ao menos, o direito de tocar a nota errada. Depois confesso a prova: deram-me uma moça que me amava, e respondi-lhe atirando-lhe dinheiro à cara. Os senhores supõem que me gabo disto? Talvez. Mas reparem bem — eu rio de mim antes que os senhores tenham tempo de rir.",
  "description": "Memórias do Subsolo (1864) é a confissão de um homem sem nome que escreve do porão da própria consciência. Na Parte 1 ele demole o 'palácio de cristal' de Tchernichévski: contra a utopia que calcula a felicidade humana como quem fecha uma equação, ergue o capricho, a vontade livre e o escandaloso 2+2=5. Na Parte 2 a teoria desce à carne e se desmoraliza — o jantar humilhante com Zvérkov e, sobretudo, Liza, a quem ele oferece a salvação só para a despedaçar quando ela acredita. Um narrador que mente, se contradiz e interpela 'os senhores'; um livro que se recusa a crescer, a aprender, a se redimir — e que, nessa recusa, inaugura o existencialismo.",
  "tags": ["Literatura Clássica", "Filosofia", "Existencialismo"],
  "progress": "8 Capítulos",
  "cover": "assets/memorias-do-subsolo-cover.png",
  "overview_cards": [
    {"ic":"gap","t":"O Homem do Subsolo","b":"Quem fala é um funcionário aposentado, sem nome, mau e <strong>'doente de tanta consciência'</strong>. O 'subsolo' (подполье) não é um porão de tijolos: é um estado da alma. É o canto de quem despreza os homens e, ao mesmo tempo, não vive sem a plateia deles — porque um veneno só faz efeito se há quem o veja borbulhar.","tip":"<strong>Para o leitor:</strong> o subsolo é diagnóstico, não modelo. Dostoiévski o pinta para que o reconheçamos em nós, não para que o admiremos nele."},
    {"ic":"triangle","t":"Anti-Racionalismo: 2+2=5","b":"Contra o 'palácio de cristal' de Tchernichévski — a utopia onde a ciência calcula a felicidade até a última casa decimal —, o subsolo crava o seu <strong>'2+2=5'</strong>. Não por ignorância da conta, mas por orgulho: o direito de discordar é mais humano que a verdade que me é enfiada goela abaixo.","tip":"<strong>Modelo mental:</strong> '2+2=5' não é matemática, é manifesto. É a recusa de ser engrenagem num sistema que confunde 'o que te convém' com 'o que vais querer'."},
    {"ic":"spiral","t":"A Hiperconsciência que Paralisa","b":"Pensar demais, aqui, é uma <strong>doença</strong>. Quem disseca cada impulso o mata antes de agir — e fica a olhar, hesitar e a apodrecer. O homem 'espontâneo', que o subsolo chama de burro e inveja em segredo, ao menos vive; o hiperconsciente troca a vida pela autópsia da vida.","tip":"<strong>Como aplicar:</strong> desconfie quando 'preciso pensar melhor' começa a soar igualzinho a 'tenho medo de agir'. A lucidez infinita é uma cadeira muito confortável."},
    {"ic":"mask","t":"Incapacidade de Amar","b":"O clímax moral: a Liza, prostituta, ele oferece salvação num discurso que faz chorar — e a despedaça no instante em que ela acredita. A <strong>incapacidade de amar</strong> é o subsolo em estado puro: o afeto o desarma, e tudo o que ele sabe fazer com quem o desarma é atacar.","tip":"<strong>Modelo mental:</strong> quem só conhece duas posições — humilhar ou ser humilhado — não cabe no amor, porque amar exige a igualdade que ele nunca aprendeu a suportar."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-o-homem-do-subsolo",
    "sub": "CAPÍTULO 1: O Homem do Subsolo — O Anti-Herói",
    "intro": "'Sou um homem doente... Sou um homem mau.' A primeira frase já é a sentença de tudo o que vem depois. Quem a profere é um funcionário aposentado de Petersburgo, sem nome, ressentido, encolhido no seu canto. O 'subsolo' não fica embaixo de casa nenhuma: é onde mora a alma que se recusa a viver entre os homens — e que, no mesmo gesto, os despreza para não admitir que precisa deles.",
    "cards": [
      {"ic":"gap","t":"O Subsolo como Estado da Alma","emph":"Estado da Alma","b":"O subsolo não tem tijolos: é o <strong>isolamento orgulhoso de uma consciência inchada demais</strong>. O narrador se tranca porque despreza os homens — e, no entanto, é só para esses mesmos homens que ele escreve. Tira o público que ele tanto odeia e o monólogo ácido fica falando para a parede.","tip":"<strong>Sinal de alerta:</strong> o desprezo pelo mundo, transformado em modo de vida, não é sabedoria superior — é um veneno que o solitário guarda para si mesmo.","warn":True},
      {"ic":"mask","t":"O Anti-Herói sem Ação","emph":"Anti-Herói","b":"O herói dos romances faz coisas; o homem do subsolo é definido <strong>justamente pelo que não faz</strong>. Toda a sua 'grandeza' cabe no ressentimento bem-arquitetado e em vinganças geniais que nunca saem do papel. Dostoiévski nos entrega aqui o primeiro anti-herói de verdade — feito não de feitos, mas de feridas.","tip":"<strong>Modelo mental:</strong> o ressentimento refinado é o prêmio de consolação de quem não teve a coragem prosaica de mudar a própria vida."},
      {"ic":"spiral","t":"Prazer no Sofrimento","emph":"Prazer no Sofrimento","b":"Ele extrai um gozo torto da <strong>própria humilhação</strong>. Ser esmagado, mas com consciência, lhe parece um título de nobreza diante do gado feliz que não pensa. Sofrer lucidamente acaba sendo mais sedutor do que a tarefa banal e ingrata de consertar a vida.","tip":"<strong>Prática:</strong> cuidado quando a queixa começa a virar troféu. O 'sofrimento consciente' é uma fantasia elegante que o medo de agir adora vestir."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["O subsolo é um estado da alma: um isolamento que se nutre do que odeia e precisa de plateia para existir.", "O anti-herói define-se pela impotência — o ressentimento é a rebeldia de quem nunca passa do plano à ação.", "O prazer no sofrimento consciente costuma ser fuga da mudança real: 'sofrer bem' é uma cadeira confortável demais."],
  },
  {
    "slug": "ch02-hiperconsciencia-paralisia",
    "sub": "CAPÍTULO 2: A Hiperconsciência que Paralisa",
    "intro": "Para o narrador, ter consciência demais é adoecer. Quem examina cada impulso o dissolve antes que ele vire gesto. O homem 'espontâneo' — que o subsolo chama de burro — age e pronto; o hiperconsciente fica a olhar, a hesitar, a se corroer. Aqui a inteligência não é farol: é a corda que prende o tornozelo.",
    "cards": [
      {"ic":"spiral","t":"Consciência como Doença","emph":"Consciência","b":"A mente afiada não ilumina o caminho — é a <strong>lupa que queima a vontade antes do primeiro passo</strong>. Quem pensa em excesso revira cada impulso inofensivo até não sobrar energia para nada. Essa consciência que se devora a si mesma não é maturidade; é uma paralisia com diploma.","tip":"<strong>Modelo mental:</strong> a autoanálise sem fim raramente entrega respostas. O que ela entrega, com pontualidade, é a desculpa para não agir hoje."},
      {"ic":"mountain","t":"O Homem 'Espontâneo' × O Hiperconsciente","emph":"Espontâneo","b":"O narrador cospe desprezo no homem de ação que não perde tempo questionando as engrenagens. Mas é desprezo com inveja por dentro: <strong>o tal burro, ao menos, existe e realiza</strong>. Ser brilhante e inerte num canto é pior que ser tolo e estar vivo no meio da rua.","tip":"<strong>Sinal de alerta:</strong> usar a inteligência só para ridicularizar quem faz o trabalho é a defesa preferida de quem não sai do lugar.","warn":True},
      {"ic":"eye","t":"O Prazer Invertido da Dor","emph":"Prazer Invertido","b":"Cutucar as próprias feridas, para ele, não é buscar cura — é um <strong>vício secreto na dor</strong>. 'Sofrer é uma vantagem!', proclama o subsolo, porque a angústia bem elaborada parece nobre ao lado da alegria rasa dos outros. Quando o tormento ganha ares de genialidade, o homem passa a abraçar as correntes em vez de arrebentá-las.","tip":"<strong>Prática:</strong> quando se pegar narrando os próprios problemas com certo orgulho intelectual, suspeite. Esse orgulho costuma ser a coleira disfarçada de medalha."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["A hiperconsciência é doença: dissolve cada impulso antes que ele tenha a chance de virar ato.", "O homem 'espontâneo', que age sem examinar tudo, está mais vivo que o hiperconsciente mais brilhante.", "Quando a dor vira identidade, ela resiste à cura — o sofrimento consciente é uma prisão de portas abertas que ninguém atravessa."],
  },
  {
    "slug": "ch03-palacio-de-cristal-2x2",
    "sub": "CAPÍTULO 3: O Palácio de Cristal e o 2+2=4",
    "intro": "Aqui está o coração polêmico da Parte 1, e a mira tem nome: Tchernichévski e a sua fé na razão que organiza tudo. O 'palácio de cristal' é a utopia cientificista — uma ordem perfeita, transparente, onde nada se pode mexer: uma prisão de vidro. Contra a tirania do '2+2=4', o subsolo levanta, teimoso, o seu '2+2=5'.",
    "cards": [
      {"ic":"triangle","t":"O Palácio de Cristal — Prisão Dourada","emph":"Palácio de Cristal","b":"A utopia que promete calcular cada sorriso humano num projeto impecável é, no fundo, um atentado contra o que temos de mais vivo. Onde a cartilha resolve a miséria e tabela a alegria, <strong>não sobra um palmo de chão torto para a liberdade pisar</strong>. A perfeição total tem o formato exato de um caixão — e não importa que seja de cristal.","tip":"<strong>Modelo mental:</strong> desconfie das doutrinas que prometem apagar todo risco da vida. Uma gaiola continua gaiola, por mais transparentes que sejam as grades."},
      {"ic":"spark","t":"2+2=5 — Manifesto do Livre-Arbítrio","emph":"2+2=5","b":"Gritar contra a conta certa não é burrice — é o <strong>direito de dizer 'não' levado às últimas consequências</strong>. Se a ciência prova que a tecla tem de descer assim, o homem escolhe de propósito a nota errada, só para lembrar ao mundo que ele não é o piano.","tip":"<strong>Prática:</strong> entenda o valor da desobediência. Render-se inteiro a uma fórmula que dispensa a sua vontade é entregar a chave do que faz de você alguém."},
      {"ic":"sword","t":"O Muro de Pedra","emph":"Muro de Pedra","b":"As leis da natureza são o muro: cinzento, surdo, inegociável. O racionalista encosta a testa, faz reverência e obedece em paz. O homem do subsolo, não — ele <strong>se atira contra a pedra até sangrar</strong>. Sabe que não vai derrubá-la; quer apenas deixar ali, com os próprios ossos, o protesto de quem se recusa a venerar o que o esmaga.","tip":"<strong>Sinal de alerta:</strong> não se trata de negar as leis do mundo físico, mas de não as adorar como destino. Obedecer é uma coisa; ajoelhar-se, outra.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["O palácio de cristal é uma prisão de cristal: a perfeição que elimina toda escolha é a morte da liberdade.", "'2+2=5' é manifesto do livre-arbítrio — discordar da verdade imposta é mais humano que obedecer ao cálculo certo.", "O muro de pedra separa dois homens: o que faz reverência à necessidade e o que, pelo gesto, recusa ser engrenagem."],
  },
  {
    "slug": "ch04-livre-arbitrio-capricho",
    "sub": "CAPÍTULO 4: O Livre-Arbítrio e o Capricho",
    "intro": "Aqui está a tese de tudo. Os senhores garantem que o homem esclarecido há de escolher sempre o que lhe convém — que basta mostrar-lhe a vantagem para que ele a tome. Pois respondo: o bem mais alto do homem nunca foi a felicidade, foi a vontade livre, a sua própria vontade, ainda que selvagem. E ele é capaz de agir contra o próprio interesse, de propósito, só para provar aos senhores que não é tecla de piano.",
    "cards": [
      {"ic":"key","t":"A Vontade — Acima do Interesse","emph":"Vontade","b":"Dizem que o homem só persegue o seu proveito, e que basta a tabela das vantagens para domá-lo. Mentira de gente que nunca se olhou por dentro: <strong>o que um homem mais preza não é a felicidade calculada, é a vontade própria, livre e indócil — querer porque quer</strong>. Tirem-lhe isso, e terão um relógio, não um homem.","tip":"<strong>Modelo mental:</strong> nenhum sistema racional prende a vontade humana inteira. Mostre a alguém a única escolha 'sensata' e veja com que prazer ele faz a outra."},
      {"ic":"person","t":"A Tecla de Piano — Contra o Determinismo","emph":"Tecla de Piano","b":"Querem reduzir o homem a uma tecla de piano: aperta-se aqui, soa ali; sangue e nervos obedecendo à lei como engrenagem. Mas justamente por isto, e <strong>só para não ser tecla de piano</strong>, ele há de agir contra a própria conveniência — feito uma criança que destrói o brinquedo para mostrar que a mão é dele, não do compasso.","tip":"<strong>Prática:</strong> repare em quem joga fora uma boa oportunidade no instante em que sente que 'tinha' de aceitá-la. Não é tolice — é a vontade gritando que existe."},
      {"ic":"fork","t":"Agir Contra Si — O Paradoxo","emph":"Agir Contra Si","b":"Prefiro arruinar-me a deixar que alguém comande o botão da minha dor e da minha alegria. É o ponto mais escuro da nossa natureza, e eu o digo sem corar: <strong>a ruína escolhida de propósito vira a última prova de que o homem ainda é dono de si</strong> — quando já não lhe resta nenhum outro modo de provar.","tip":"<strong>Sinal de alerta:</strong> repare onde a defesa da liberdade descamba em mania de destruir-se. O subsolo não receita isto — confessa-o como doença, e ri amargo de quem confunde os dois.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["O bem supremo, para o subsolo, não é a felicidade — é a vontade livre. Aqui está a raiz do existencialismo.", "A 'tecla de piano' é o homem reduzido a engrenagem determinada; o capricho indócil é a prova de que ele não cabe na fórmula.", "A autossabotagem como afirmação de liberdade é diagnóstico, não receita — é a vontade sem nenhum outro campo onde se exercer."],
  },
  {
    "slug": "ch05-parte-2-jantar-humilhacao",
    "sub": "CAPÍTULO 5 (Parte 2): O Jantar e a Humilhação",
    "intro": "Agora a teoria desce da cabeça para os sapatos — e tropeça. O mesmo homem que pôs a razão de joelhos na Parte 1 convida-se a um jantar em honra de Zvérkov, oficial bonito e rico que ele inveja e despreza na mesma respiração. É humilhado a noite inteira, exige um duelo que ninguém leva a sério, e ainda assim corre atrás deles pela neve molhada. Procura a humilhação como quem procura ar: ao menos doendo, ele sente que está vivo aos olhos de alguém.",
    "cards": [
      {"ic":"wave","t":"A Teoria Vira Biografia","emph":"Biografia","b":"As ideias que na Parte 1 encostaram a razão moderna contra o muro <strong>despedaçam-se, na Parte 2, no chão pegajoso de um jantar medíocre</strong>. O teórico altivo da liberdade encolhe diante de quatro olhares de colégio e não sabe sequer onde pôr as mãos. A tese era soberba; o homem que a carrega não dá conta de atravessar uma sala.","tip":"<strong>Modelo mental:</strong> nenhuma ideia brilhante no papel tapa o buraco que você não tem coragem de encarar na vida. A filosofia não te ensina a entrar numa sala."},
      {"ic":"mask","t":"Zvérkov — A Inveja Disfarçada","emph":"Inveja Disfarçada","b":"O narrador range os dentes num desprezo de nariz empinado contra o militar rico e fútil do outro lado da mesa. Mas eu não me deixo enganar nem por mim: aquele ar de superioridade moral <strong>é apenas a casca de uma inveja que ele não ousa confessar</strong>. Cospe em Zvérkov só porque jamais será Zvérkov.","tip":"<strong>Prática:</strong> seja cruel consigo, como eu sou comigo: que indignação muito nobre sua não passa de despeito por aquilo que lhe foi negado?"},
      {"ic":"gap","t":"Buscar a Humilhação","emph":"Humilhação","b":"Lá vai ele pela noite, arrastando-se atrás dos colegas até o bordel, quase implorando que o ofendam. <strong>Existir pelo vexame, ser notado por baixo, ainda vale mais para ele do que a tortura calada de não fazer falta a ninguém</strong>. Um insulto, ao menos, prova que ele estava na sala.","tip":"<strong>Sinal de alerta:</strong> quem arma escândalo por nada numa roda qualquer raramente busca briga. Busca a prova, à força, de que sua ausência seria sentida.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["A Parte 2 encena e desmente a Parte 1: o filósofo da liberdade fracassa no instante em que tenta vivê-la.", "O desprezo por Zvérkov encobre inveja — o ressentimento é a superioridade moral que o fraco veste para não se ver pequeno.", "Buscar a humilhação é buscar existência: para o homem do subsolo, doer aos olhos do outro é melhor que ser invisível."],
  },
  {
    "slug": "ch06-liza-incapacidade-de-amar",
    "sub": "CAPÍTULO 6: Liza — A Redenção Oferecida e Negada",
    "intro": "Ferido no jantar, ele descarrega a vingança no ser mais frágil que encontra. No bordel domina Liza, jovem prostituta, com um discurso comovente sobre o destino que a espera — e ela acredita, e vem procurá-lo. Quando ela bate à sua porta, ele desfaz a farsa: confessa que falava por despeito, humilha-a e atira-lhe dinheiro. É o retrato definitivo de um homem que sabe fazer chorar, mas não sabe amar.",
    "cards": [
      {"ic":"mask","t":"O Discurso-Arma","emph":"Discurso-Arma","b":"Vestido de salvador, ele prega à moça perdida um sermão tão belo que a faz chorar. Mas eu conheço o avesso de cada palavra minha: <strong>aquele sermão não nasceu de piedade, e sim do despeito e do gozo torto de a ver desabar</strong>. Dizia a verdade — e usava a verdade como faca.","tip":"<strong>Modelo mental:</strong> dizer coisas certas não faz de ninguém um homem bom. A verdade atirada para ferir é tão cruel quanto a mentira — só mais covarde."},
      {"ic":"gap","t":"Incapacidade de Amar","emph":"Incapacidade","b":"Quando Liza vem, e abre o peito, e o olha sem nenhuma defesa, ele <strong>a expulsa aos gritos e lhe enfia dinheiro na mão para a ferir</strong>. Não suporta a ternura: o afeto o desarma, e a um homem desarmado o subsolo só sabe responder com o ataque. Amar exigiria a igualdade que ele nunca aprendeu a dar nem a receber.","tip":"<strong>Sinal de alerta:</strong> quem morde a mão que se estende no escuro não é forte. É o mais assustado de todos — incapaz de baixar a guarda por um instante que seja.","warn":True},
      {"ic":"leaf","t":"Liza — A Superior Moral","emph":"Liza","b":"Liza não tem teoria, não tem palavra bonita, não tem cinismo — tem o que a ele falta: a capacidade simples de sentir o outro. Ao sair daquele quarto sem revidar, <strong>ela deixa o dinheiro sobre a mesa não como o tapa rancoroso que ele lhe daria, mas como o silêncio de quem perdoa</strong>. A caída foi, ali, a única pessoa inteira.","tip":"<strong>Prática:</strong> nem título, nem leitura, nem inteligência dão estofo moral a alguém. Repare na grandeza de quem, esmagado, ainda escolhe não esmagar de volta."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["Palavras verdadeiras não garantem boa intenção: a mesma verdade que salva pode ser usada para dominar e ferir.", "A crueldade com Liza é defesa — o subsolo não suporta ser amado, porque amar pediria a igualdade que ele recusa.", "Liza é a superior moral da cena: ao inverter o clichê da prostituta redimida, Dostoiévski faz do salvador o algoz e da caída a alma inteira."],
  },
  {
    "slug": "ch07-narrador-estrutura-duas-partes",
    "sub": "CAPÍTULO 7: O Narrador e a Estrutura em Duas Partes",
    "intro": "A forma é o próprio argumento. Parte 1 é a ideia; Parte 2, a sua encarnação — e uma se lê contra a outra. A voz é uma das primeiras narrações não confiáveis da literatura: mente, se contradiz, interpela 'os senhores' a cada página. E o fim não é fim — é uma antinarrativa, um relato que simplesmente se interrompe, sem redenção, porque o homem que o escreve recusa-se a aprender.",
    "cards": [
      {"ic":"eye","t":"Narrador Não Confiável","emph":"Narrador Não Confiável","b":"Ele afirma uma coisa com arrogância, recua envergonhado no parágrafo seguinte e ainda cospe veneno em quem acreditou. O gênio de Dostoiévski está aí: <strong>dar voz a um homem que não consegue sustentar uma só posição por três parágrafos seguidos</strong>. Eu minto aos senhores; mas, ao confessar que minto, não estarei mentindo também?","tip":"<strong>Modelo mental:</strong> não despreze a contradição de quem se confessa — leia-a. É justamente na emenda da frase, na desculpa que se desdiz, que a ferida verdadeira aparece."},
      {"ic":"layers","t":"A Estrutura em Duas Partes","emph":"Estrutura","b":"O livro é uma armadilha de duas faces. Na primeira você curva-se ao raciocínio do subsolo, brilhante e implacável; na segunda <strong>você o vê encolher diante de um jantar e de uma moça, e a tese soberba quebra-se no contato mais banal com outra alma</strong>. A ideia que não desce às pernas não passa de discurso.","tip":"<strong>Prática:</strong> não separe a tese da vida de quem a defende. Uma filosofia que não atravessa uma sala de jantar talvez seja só elegante — não verdadeira."},
      {"ic":"gap","t":"A Antinarrativa","emph":"Antinarrativa","b":"Não espere o arco em que o herói vê a luz, aprende e amanhece melhor. O subsolo nega essa consolação: <strong>o relato apenas se interrompe, deixando o homem onde sempre esteve — no fundo do mesmo ressentimento que ele escolheu não largar</strong>. Não há cura porque ele não quer cura; só quer continuar a falar.","tip":"<strong>Sinal de alerta:</strong> não force uma moral redentora num homem que recusa redenção. A honestidade da obra está em não lhe oferecer a saída fácil que a vida também lhe negaria.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["O narrador não confiável é pioneiro — suas contradições são o dado mais importante, não defeitos a corrigir na leitura.", "A estrutura em duas partes é o argumento: a tese da Parte 1 é posta à prova na Parte 2 e desmorona no contato humano.", "A antinarrativa, sem redenção, é escolha estética: o subsolo não cresce nem se cura — fecha-se sobre si mesmo."],
  },
  {
    "slug": "ch08-legado-existencialismo-simbolos",
    "sub": "CAPÍTULO 8: Legado, Existencialismo e Símbolos",
    "intro": "'Memórias do Subsolo' abre a grande fase de Dostoiévski e é uma das raízes do existencialismo. Décadas antes de a filosofia pôr nome no assunto, este homem amargo de Petersburgo já gritava que a vontade vem antes da essência. Daqui sairão Raskólnikov, Ivan Karamázov e o Grande Inquisidor — e três imagens (o palácio de cristal, a tecla de piano, o 2+2=5) condensam a tese inteira em figura.",
    "cards": [
      {"ic":"spark","t":"Raiz do Existencialismo","emph":"Raiz do Existencialismo","b":"Muito antes de a filosofia francesa elegantizar o assunto nos cafés, este homem da névoa de Petersburgo já tinha dito o essencial: <strong>a vontade livre e indócil rompe qualquer essência que a ciência pretenda impor ao homem</strong>. Primeiro o homem escolhe; depois, se quiser, inventa a razão. Eis o existencialismo nascendo de um ressentido.","tip":"<strong>Modelo mental:</strong> leia o subsolo não como o desabafo de um neurótico, mas como o primeiro martelo a rachar a fé cega na razão que organiza tudo."},
      {"ic":"link","t":"Ponte na Obra de Dostoiévski","emph":"Ponte","b":"Esta novela curta é o laboratório de tudo o que viria depois. <strong>O ódio raciocinado do subsolo prepara o machado de Raskólnikov; sua recusa do paraíso imposto pavimenta o discurso do Grande Inquisidor</strong>. Os grandes romances nascem aqui — neste rascunho febril de uma alma que escolheu o porão.","tip":"<strong>Prática:</strong> repare como decisões monstruosas raramente vêm da maldade pura. Vêm, quase sempre, dessa mesma roda fechada do ressentimento que se justifica a si mesma."},
      {"ic":"eye","t":"Os Símbolos — O Mapa","emph":"Símbolos","b":"Dostoiévski argumenta com imagens, não com tratados. O subsolo é o isolamento que despreza e precisa de plateia; o muro de pedra é a necessidade que o racionalista venera e o rebelde esmurra; <strong>o 2+2=5 é o escudo da dignidade teimosa contra o conforto que nos transforma em engrenagem</strong>. Cada figura carrega a tese inteira.","tip":"<strong>Como aplicar:</strong> da próxima vez que lhe oferecerem o palácio perfeito, sem um defeito sequer, exija ali um canto torto, fora da conta — para lembrar que você é gente, e não tecla de piano."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Memórias do Subsolo é uma raiz do existencialismo literário: a liberdade vem antes da essência, a vontade antes da razão.", "O homem do subsolo prefigura Raskólnikov, Ivan e o Grande Inquisidor — a novela é o laboratório dos personagens maiores.", "Os símbolos (palácio de cristal, tecla de piano, 2+2=5) são argumentos condensados em imagem — leia-os como filosofia, não como adorno."],
  },
]
