# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Mulheres que Correm com os Lobos' (Clarissa Pinkola Estés)."""

BOOK = {
  "title": "Mulheres que Correm com os Lobos",
  "author": "Clarissa Pinkola Estés",
  "header_light": "MULHERES QUE CORREM",
  "header_bold": "COM OS LOBOS",
  "subtitle": "VISÃO GERAL · A MULHER SELVAGEM E OS CONTOS COMO REMÉDIO DA ALMA",
  "intro": "Há uma mulher dentro da mulher — instintiva, sábia, sem coleira. A cultura a domesticou: cortou-lhe o faro, baixou-lhe a voz, ensinou-a a sorrir quando devia rosnar. Mas a Mulher Selvagem não morre; ela hiberna sob o asfalto da rotina, esperando ser cantada de volta. Clarissa Pinkola Estés — psicanalista junguiana e <em>cantadora</em> — abre os velhos contos de fada como quem abre um corpo: dentro de cada um há um osso da alma feminina, e a instrução para reanimá-lo. Não se lê este livro. Recolhe-se dele a própria ossada.",
  "description": "Os contos de fada como remédio da alma — psicanálise junguiana (arquétipo, Sombra, individuação) traduzida em mito e narrativa. La Loba que canta os ossos de volta à vida, Barba Azul e o predador que mora dentro, Vasalisa e a boneca que sabe o caminho, a Mulher Esqueleto e o ciclo Vida-Morte-Vida, o Patinho Feio exilado da própria espécie, os Sapatinhos Vermelhos que dançam até matar, Manawee e a alma de duas faces, a Donzela Manca que desce para renascer. Cada conto é, ao mesmo tempo, um diagnóstico e uma cura.",
  "tags": ["Psicologia", "Feminino", "Autoconhecimento"],
  "progress": "9 Capítulos",
  "cover": "assets/mulheres-que-correm-com-os-lobos-cover.png",
  "overview_cards": [
    {"ic":"leaf","t":"A Mulher Selvagem","b":"Não confunda: <strong>selvagem aqui quer dizer natural, não descontrolado</strong> — o lobo que sabe a hora de caçar e a hora de dormir, não a fera fora de si. É a natureza instintiva, criativa e antiga da psique feminina, aquela que a domesticação cultural ensinou a calar. Ela não foi morta. Foi enterrada viva, e respira devagar, à espera.","tip":"<strong>Modelo mental:</strong> a Mulher Selvagem é menos um eu a construir do que um sentido perdido a recuperar — pelo corpo, pelos sonhos e por aquela repulsa ou atração que vem antes do pensamento.","wide":True},
    {"ic":"spiral","t":"O Ciclo Vida-Morte-Vida","b":"Tudo que vive — um amor, uma obra, uma fase de si — gira na mesma roda: <strong>nasce, floresce, definha, morre um pedaço e renasce mudado</strong>. A cultura nos ensinou a temer só a primeira metade da curva e a fugir da segunda. Mas recusar a morte de uma estação é abortar a primavera seguinte. Há que deixar morrer o que terminou.","tip":"<strong>Como aplicar:</strong> diante do que esfria e acaba, não pergunte como salvar — pergunte o que precisa morrer aqui para que o novo tenha lugar de nascer."},
    {"ic":"key","t":"Juntar os Ossos","b":"Quando você se sentir em cacos, espalhada pelo chão, há uma pergunta de La Loba a fazer: <strong>o que em mim é indestrutível e só está esperando para ser reanimado?</strong> Recolha esses ossos. Cante sobre eles — crie, nomeie, dê voz — e a carne volta. Nada de essencial em você se perdeu de verdade; apenas se dispersou e aguarda o canto.","tip":"<strong>Como aplicar:</strong> o cansaço fundo e a aridez por dentro não são sentença — são ossos no deserto, esperando alguém que saiba a melodia."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-la-loba-mulher-selvagem",
    "sub": "CAPÍTULO 1: La Loba e a Mulher Selvagem",
    "intro": "No deserto vive La Loba, a velha que junta ossos. Ela rasteja por barrancos atrás de uma ossada inteira de loba, monta osso por osso, e quando o esqueleto está armado, ergue-se sobre ele e canta. Ao cantar, a carne brota, o pelo cobre os ossos, e a loba salta viva, correndo até virar mulher na linha do horizonte. É a primeira lição e a tese inteira: nada de essencial em você morreu — apenas se dispersou, e espera a sua voz.",
    "cards": [
      {"ic":"spark","t":"Juntar os Ossos","emph":"Ossos","b":"O trabalho da alma começa de joelhos: varrer o chão do deserto e recolher, um a um, os ossos que a domesticação espalhou — os pedaços de você que foram chamados de demais, de errados, de feios. Reunidos os ossos, vem o canto: <strong>é a criação que põe carne de volta no que estava calado no escuro</strong>. A velha não conserta a loba; ela a chama de volta a ser.","tip":"<strong>Como aplicar:</strong> procure onde a sua chama foi dada por extinta e comece a desenterrar — devagar — aquilo em você que não quebra."},
      {"ic":"leaf","t":"O Selvagem Não é Louco","emph":"Selvagem","b":"Há quem ouça <em>selvagem</em> e pense em descontrole. É o contrário. A loba não ataca à toa: ela fareja o perigo, lê o vento, sabe a hora. <strong>Selvagem é a intuição em estado puro, ainda não anestesiada</strong>. A domesticação não educa a fera — ela a entorpece, e chama de boa menina a mulher que aprendeu a não rosnar quando deveria.","tip":"<strong>Sinal de alerta:</strong> quando rotularem de exagero ou histeria o seu instinto que ladrou primeiro, desconfie de quem rotula — costuma ser quem se beneficia do seu silêncio."},
      {"ic":"wave","t":"O Rio Sob o Rio","emph":"Rio","b":"Por cima corre o rio da rotina, raso e às vezes seco. Mas debaixo dele há outro rio, fundo e cheio, que nunca para — a água viva da psique instintiva. Quando a superfície da vida murcha e endurece, não é o fim da fonte: <strong>o rio de baixo segue intacto, mandando recados em arrepios, em repulsas que vêm sem aviso, em sonhos nítidos demais para esquecer</strong>.","tip":"<strong>Modelo mental:</strong> o esgotamento de cada dia não anuncia a morte da nascente — avisa apenas que o alçapão para as águas de baixo emperrou e pede para ser reaberto."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["A natureza selvagem é herança, não defeito a corrigir.", "Nada de essencial se perde — só se dispersa e espera o canto.", "Criar é cantar sobre os ossos: a arte reanima o que a vida amorteceu."],
  },
  {
    "slug": "ch02-barba-azul-predador-interno",
    "sub": "CAPÍTULO 2: Barba Azul e o Predador da Psique",
    "intro": "Barba Azul, o nobre estranho de barba estranha, casa-se com a moça mais nova, entrega-lhe todas as chaves do castelo e proíbe uma só porta. Mora aí o conto: dentro de cada psique há um predador — uma voz que promete cuidar de você e, em troca, exige que não olhe. A salvação não vem da obediência. Vem da chave proibida, da porta aberta, do horror visto de frente e, por fim, nomeado.",
    "cards": [
      {"ic":"eye","t":"O Predador se Revela","emph":"Predador","b":"O tirano de dentro não chega de faca: chega de luvas, galante, oferecendo proteção. Você só o reconhece pelo que ele te manda <em>não</em> ver. A porta que não se pode abrir, a pergunta que não se pode fazer, o quarto que fica trancado — <strong>essa proibição é o seu rastro; é ali que ele guarda o que sabe que você não suportaria saber</strong>.","tip":"<strong>Como aplicar:</strong> quando o encanto vier embrulhado num cômodo escuro e interditado, é justamente ali que a chave deve girar."},
      {"ic":"spark","t":"A Chave que Sangra","emph":"Chave que Sangra","b":"A moça abre a porta proibida e encontra o açougue: as esposas anteriores, mortas. A ingenuidade romântica se estilhaça de uma vez — e a chavezinha começa a sangrar e não para mais. <strong>O sangue diz que o que foi visto não se desvê: a verdade, uma vez avistada, é irreversível</strong>. Esfregar a chave para esconder a mancha é só pedir lugar na fila das próximas vítimas.","tip":"<strong>Sinal de alerta:</strong> inventar desculpas ternas para as bandeiras vermelhas é exatamente o gesto de quem tenta limpar a chave que sangra."},
      {"ic":"person","t":"Nomear e Mobilizar","emph":"Nomear","b":"Ver o horror não basta: o susto paralisa, e a paralisia alimenta o predador. A moça não escapa rezando — ela grita pelos irmãos, que chegam a cavalo. Reagir exige de você o mesmo: <strong>dar nome exato à coisa que machuca e convocar, na hora, as defesas instintivas que cortam o laço</strong>. Saber é meio caminho; o outro meio é agir sobre o que se sabe.","tip":"<strong>Regra:</strong> depois do susto, não se negocia horário de visita com a fera — fecha-se a porta e corta-se o contato pela raiz."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["A curiosidade é função de sobrevivência da alma, não um defeito de moça.", "Reconhece-se o predador interno pelo que ele proíbe você de ver.", "Saber é irreversível e é o que salva — mas só salva quem age depois de ver."],
  },
  {
    "slug": "ch03-vasalisa-intuicao",
    "sub": "CAPÍTULO 3: Vasalisa e a Recuperação da Intuição",
    "intro": "Antes de morrer, a mãe de Vasalisa lhe dá uma bonequinha e uma só instrução: 'Quando não souberes o caminho, pergunta à boneca, e alimenta-a.' É a intuição herdada de mãe para filha — a voz que sabe antes de a razão entender. Enviada à temível Baba Yagá, Vasalisa sobrevive porque pergunta à boneca, escuta e obedece. Do outro lado da prova, traz para casa o fogo: a luz que agora é dela, e de mais ninguém.",
    "cards": [
      {"ic":"bulb","t":"A Boneca de Bolso","emph":"Boneca","b":"A intuição não fala a língua dos argumentos; ela fala pelo corpo — o aperto no estômago, o arrepio sem motivo, o suor frio diante de alguém sorridente. É a boneca no bolso, e ela só responde a quem a alimenta. <strong>Dar-lhe silêncio, sono e atenção mantém viva a voz que enxerga o que os olhos ainda não viram</strong>.","tip":"<strong>Como aplicar:</strong> antes de deixar a mente racional julgar, pare e sinta — como o corpo reage a esta pessoa, a este convite, a esta porta?"},
      {"ic":"mountain","t":"O Forno da Baba Yagá","emph":"Baba Yagá","b":"A Baba Yagá não assusta por crueldade — ela é a velha selvagem da floresta, severa porque é mestra. Suas tarefas impossíveis e seu fogo não punem: <strong>iniciam, separando o choro infantil de uma resiliência mais antiga, que a moça nem sabia carregar</strong>. Encarar o que apavora é, aqui, o próprio rito de passagem.","tip":"<strong>Modelo mental:</strong> fugir da mestra terrível é fugir da prova — e quem evita a prova fica sem a força que só a travessia entrega."},
      {"ic":"key","t":"O Fogo na Caveira","emph":"Fogo","b":"Vasalisa volta da floresta com uma caveira em brasa, e essa luz não queima tudo: incinera apenas a madrasta e as filhas falsas que a sugavam. Esse é o fogo da intuição madura — <strong>o discernimento que põe limites nítidos e deixa arder, sem culpa, o que vive de drenar a sua vida</strong>.","tip":"<strong>Sinal de alerta:</strong> terceirizar a própria luz, deixar que outro decida o que você deve ver, é apagar a única chama que de fato te protege."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["A intuição é instrumento de sobrevivência herdado — mas só funciona se for alimentada.", "Escute a resposta do corpo antes de ouvir a mente.", "As provas que apavoram são iniciações: a luz própria se conquista do outro lado."],
  },
  {
    "slug": "ch04-mulher-esqueleto-vida-morte-vida",
    "sub": "CAPÍTULO 4: A Mulher Esqueleto — Vida-Morte-Vida no Amor",
    "intro": "Um pescador fisga, sem saber, a Mulher Esqueleto — uma morta jogada ao mar, reduzida a ossos. Aterrorizado, foge remando, e ela vai sendo arrastada atrás dele, presa à linha. Em casa, à luz do fogo, ele desembaraça com cuidado os ossos emaranhados, e uma lágrima sua, no sono, a alimenta. O esqueleto se faz mulher viva. É o conto do amor adulto: para amar de verdade, é preciso deixar de remar em pânico e sentar-se a desembaraçar a morte que todo amor traz consigo.",
    "cards": [
      {"ic":"spiral","t":"Desembaraçar os Ossos","emph":"Desembaraçar","b":"O amor maduro não é o mar liso da paixão sem atrito — esse acaba na primeira tempestade. É o trabalho paciente de desemaranhar, fio por fio, os ossos do medo. <strong>Quem joga os remos na água e foge na primeira curva difícil impede que a relação crie raiz funda</strong>; só fica quem se senta, à luz do fogo, e desata os nós em vez de cortá-los.","tip":"<strong>Como aplicar:</strong> nas noites em que o medo manda remar para longe, fique — e desembarace um nó de cada vez, com a mão firme e a pressa nenhuma."},
      {"ic":"wave","t":"O Alimento da Lágrima","emph":"Lágrima","b":"Uma só lágrima do pescador adormecido devolve a água à morta e a faz viver. A imagem é exata: <strong>a intimidade não se nutre de armaduras, e sim da vulnerabilidade que se deixa ver</strong>. Oferecer a própria fragilidade — a lágrima verdadeira — é o que hidrata a medula seca de uma relação cansada.","tip":"<strong>Modelo mental:</strong> a parede que nada atravessa não prova coragem no amor; ela apenas asfixia, em silêncio, a ternura que tentava nascer."},
      {"ic":"masks","t":"A Parceira Vida-Morte","emph":"Vida-Morte","b":"Os fins, as crises, os trechos que morrem dentro de um amor não vêm para ceifar a história inteira. Eles enterram uma fase ingênua para que outra, mais funda e mais real, possa despertar. <strong>Recusar a Dama Vida-Morte em nome de uma felicidade que nunca muda é congelar o casal numa redoma de mentiras gentis</strong>.","tip":"<strong>Sinal de alerta:</strong> colecionar começos — pular do barco toda vez que a noite cai — é confissão de quem ainda não aprendeu a assentar amor maduro."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["Todo amor verdadeiro passa por mortes parciais — fugir delas aborta o ciclo.", "A vulnerabilidade, a lágrima que se mostra, é alimento — não fraqueza.", "A Dama Vida-Morte é parceira do amor maduro, não a sua ameaça."],
  },
  {
    "slug": "ch05-patinho-feio-exilio-pertencimento",
    "sub": "CAPÍTULO 5: O Patinho Feio — Exílio e Pertencimento",
    "intro": "O cisne nasceu no ninho errado — um ovo grande entre patinhos — e por isso foi bicado, expulso e chamado de feio. Não era feio; era de outra espécie, no lugar errado. Sua travessia solitária pelo inverno não é castigo: é viagem em busca dos seus. Quando enfim avista os cisnes e baixa a cabeça esperando o golpe, vê no reflexo da água que sempre foi um deles. Quem nasce diferente do bando de origem conhece esse exílio — e a bússola que ele esconde.",
    "cards": [
      {"ic":"gap","t":"A Falácia do Ninho Errado","emph":"Ninho Errado","b":"A rejeição crônica engana: ela faz você acreditar que o defeito é seu, quando o que houve foi cair num bando que não é o seu. Aquilo em você que o grupo chamou de demais, de estranho, de errado, <strong>costuma ser a marca da sua espécie verdadeira — não uma anomalia a ser corrigida nem curada</strong>.","tip":"<strong>Como aplicar:</strong> o veredicto do galinheiro não rebaixa a envergadura do cisne; pato algum tem autoridade para medir um voo que não cabe no quintal dele."},
      {"ic":"person","t":"A Bússola do Inverno","emph":"Inverno","b":"O frio do exílio social dói, mas não significa que o caminho se perdeu. Atravessar o inverno é justamente o que empurra os passos desajustados em direção à própria estirpe, escondida mais adiante. <strong>O prêmio só floresce do outro lado da nevasca, para quem aguenta a travessia sem se entregar</strong>.","tip":"<strong>Modelo mental:</strong> quem foge da dureza do exílio em troca de aceitação fácil aceita também a coleira — o calor morno do bando errado custa a alma inteira."},
      {"ic":"eye","t":"O Reflexo Correto","emph":"Reflexo","b":"O descanso verdadeiro vem do bando que devolve o seu rosto sem exigir que você se ampute para caber. A espécie certa reconhece, nos ossos do recém-chegado, os mesmos laços que carrega. <strong>Pertencer de verdade dissolve as acrobacias cansadas que você inventava para ser tolerado por quem nunca seria o seu povo</strong>.","tip":"<strong>Regra:</strong> os iguais reconhecem os iguais pelo tom inteiro e cru do hálito selvagem — não pela performance que você fazia para agradar estranhos."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["Sentir-se 'errada' costuma ser sinal de estar no ninho errado, não de ser defeituosa.", "O exílio é travessia com destino: a própria espécie.", "Pertencer de verdade é onde você se reconhece no reflexo, sem precisar se deformar."],
  },
  {
    "slug": "ch06-sapatinhos-vermelhos-vicio",
    "sub": "CAPÍTULO 6: Os Sapatinhos Vermelhos — A Alma Capturada",
    "intro": "A menina tinha uns sapatinhos vermelhos toscos, feitos por suas próprias mãos, e os amava. Queimaram-nos, e em troca lhe deram outros, polidos e da loja. Quando os calçou, os sapatos começaram a dançar — e não pararam mais, levando-a pelos campos até quase a morte, até que o carrasco lhe cortou os pés. Quando a vida criativa de verdade é incinerada, a fome de alma faz a mulher calçar qualquer substituto reluzente. É a anatomia exata do vício.",
    "cards": [
      {"ic":"spark","t":"Os Sapatinhos Originais","emph":"Originais","b":"Os primeiros sapatos eram torpes, costurados com retalhos — e carregavam o oxigênio da alma selvagem, porque eram dela. Trocar o que se cria com as próprias mãos pela versão lustrosa da vitrine abre um vazio mortal por dentro. <strong>Nenhum atalho de fábrica devolve a vida que pulsava no que você teceu no chão de terra</strong>.","tip":"<strong>Como aplicar:</strong> pergunte qual fazer-com-as-mãos você abandonou no exato dia em que aceitou a comodidade enfeitada que lhe ofereceram em troca."},
      {"ic":"mask","t":"A Dança que Escraviza","emph":"Escraviza","b":"O sapato da vitrine começa prometendo alívio — só um para a dor de viver. Mas a dança não para: a compulsão toma o corpo e <strong>cobra a liberdade inteira como imposto sobre um prazer que dura um instante</strong>. Foi assim que um desejo legítimo virou carcereiro, e a menina, refém dos próprios pés.","tip":"<strong>Sinal de alerta:</strong> repare quando um alívio passageiro se tornar a única coisa que torna os seus dias suportáveis — é o sapato já colado.","warn":True},
      {"ic":"leaf","t":"Restaurar a Fonte","emph":"Fonte","b":"Brigar com a superfície do vício não para a dança. A cura vem quando a mulher volta à floresta e reacende a sua própria fogueira criativa. <strong>Devolver à alma a alegria original sufoca a dependência por dentro — sem a guerra interminável da pura força de vontade</strong>.","tip":"<strong>Modelo mental:</strong> dar oxigênio à sua vocação verdadeira asfixia o vício pela raiz, em vez de você ter de enfrentá-lo de peito todo dia."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["O vício começa na perda de uma vida autêntica — não num 'defeito de caráter'.", "Os substitutos que prometem preencher o vazio terminam por possuir quem os calça.", "Curar é reacender a alegria selvagem original, não apenas reprimir a compulsão."],
  },
  {
    "slug": "ch07-manawee-cortejo-alma-dupla",
    "sub": "CAPÍTULO 7: Manawee e o Cortejo da Alma Dupla",
    "intro": "Manawee pede a mão das filhas gêmeas de um rei, e a condição é uma só: adivinhar os dois nomes secretos. Ele não consegue sozinho — quem descobre os nomes é o seu cãozinho, que vai e volta da aldeia, mas se deixa distrair pelas iscas do caminho e esquece o que ouviu. Só depois de muitas idas, fiel apesar das quedas, é que o cão traz os nomes intactos. Amar a fundo é isto: conhecer as duas faces do outro, e voltar pela trilha quantas vezes for preciso.",
    "cards": [
      {"ic":"link","t":"As Duas Faces","emph":"Duas Faces","b":"Toda pessoa tem uma face ao sol — a que o mundo vê — e outra guardada na caverna, a selvagem. Saber os dois nomes é a prova: <strong>o vínculo que dura exige conhecer e nutrir os dois terrenos, não só o visível</strong>. Amar apenas a fachada é firmar acordo com meio corpo, e estranhar depois o fantasma que sobra.","tip":"<strong>Como aplicar:</strong> persiga o nome interno de quem você ama — o crachá social não guarda o segredo de uma união que atravessa o tempo."},
      {"ic":"target","t":"As Iscas da Floresta","emph":"Iscas","b":"O cão sabe a missão, mas o caminho está semeado de ossos e comida que testam o seu foco. Cada vez que ele se desvia, esquece o nome que tanto custou ouvir. <strong>É só recusando a recompensa fácil do meio do caminho que o prêmio chega inteiro ao fim</strong> — assim também com o instinto, que sabe, mas se perde se ceder à distração.","tip":"<strong>Sinal de alerta:</strong> esquecer de repente o que você mais queria é o sinal de que a mente mordeu a isca da distração fácil.","warn":True},
      {"ic":"person","t":"Persistência Humilde","emph":"Persistência","b":"A conquista não vem do arranco de força bruta, que passa. Vem da humildade de refazer os passos depois de cada queda e cada confusão na mata. <strong>Amar fundo se parece com o trabalho calado do operário que ergue o templo pondo um tijolo após o outro</strong>, sem plateia e sem pressa.","tip":"<strong>Modelo mental:</strong> a teimosia paciente vence a investida barulhenta — refaça a trilha toda vez que o nevoeiro a cobrir."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["O amor profundo exige conhecer a dupla natureza do outro — as duas faces.", "O instinto sabe o caminho — mas só serve quando se mantém fiel à missão.", "Conquista-se pela constância humilde, refazendo a trilha — não pela força."],
  },
  {
    "slug": "ch08-donzela-manca-descida-renovacao",
    "sub": "CAPÍTULO 8: A Donzela Manca — Descida e Renovação",
    "intro": "Um pai, enganado pelo diabo, troca a própria filha por riqueza e acaba lhe cortando as mãos. Sem mãos, ela deixa a casa e parte sozinha pela floresta — anos de errância no escuro, vivendo do que o silêncio lhe ensina. E então, lentamente, as mãos voltam a crescer: mais sábias, mais suas. A individuação feminina passa por essa descida — perda, mutilação simbólica e travessia das trevas — e dela nascem mãos novas, que ninguém pode dar de presente.",
    "cards": [
      {"ic":"mountain","t":"O Caminho da Descida","emph":"Descida","b":"Perder a velha armadura não é um acidente trágico no caminho: é a porta obrigatória para a maturidade. A identidade afunda para que outra, mais funda, possa subir. <strong>Tentar escalar de volta antes de a noite terminar engessa o renascimento e aborta o novo ser que vinha vindo</strong>.","tip":"<strong>Como aplicar:</strong> deixe a queda seguir a gravidade até o fundo; a semente precisa da pressão da terra escura antes de ousar a primeira folha."},
      {"ic":"clock","t":"O Tempo da Incubação","emph":"Incubação","b":"A paisagem congelada da descida engana o olho: por baixo do vazio, as engrenagens da transformação giram sem parar. Semanas de aparente nada vão tecendo, célula por célula, a capacidade nova. <strong>A pressa por produtividade estraga o forno escuro que só trabalha no tempo lento da alma</strong>.","tip":"<strong>Sinal de alerta:</strong> chamar-se de fracassada por estar parada é aplicar a métrica do trânsito da cidade à quietude sagrada da floresta.","warn":True},
      {"ic":"leaf","t":"As Mãos que Renascem","emph":"Mãos","b":"As mãos novas só brotam depois da caminhada inteira pela dor de não tê-las. Essa regeneração recusa muletas e pede que a própria mulher cuide das próprias feridas. <strong>A vitalidade ganha na travessia vem calejada — incapaz da antiga ingenuidade, porque atravessou o que atravessou</strong>.","tip":"<strong>Modelo mental:</strong> a autonomia nasce do abandono de quem espera resgate; aguardar a mão que vem do céu atrofia a mão que estava crescendo em você."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["A individuação exige descida: perda e errância fazem parte do caminho.", "Tempos estéreis costumam ser incubação — a transformação acontece fora de vista.", "As mãos novas renascem da travessia — nunca de um resgate vindo de fora."],
  },
  {
    "slug": "ch09-lar-subterraneo-voz-propria",
    "sub": "CAPÍTULO 9: O Lar Subterrâneo e a Voz Própria",
    "intro": "Há a mulher-foca que, em terra, casa e cria um filho, mas ressecou — porque alguém escondeu a sua pele de foca, e sem ela ela não pode voltar ao mar de origem. Quando a pele aparece, ela mergulha, refaz-se nas águas fundas, e retorna. A alma precisa desses regressos regulares à solidão fértil, ou seca. E a criatividade — recuperar a voz, criar, dizer a verdade no próprio tom — é a respiração mesma da Mulher Selvagem.",
    "cards": [
      {"ic":"wave","t":"Pele Nova, Pele Seca","emph":"Pele Seca","b":"O cansaço fundo e a impaciência sem causa avisam: a pele ressecou, e você ficou tempo demais longe das águas de origem. Voltar ao fundo da própria consciência não é luxo — é <strong>a manutenção que impede o eu de se esfarelar antes que a rachadura vire ruína</strong>.","tip":"<strong>Como aplicar:</strong> não espere o desmaio da alma para mergulhar; o recolhimento preventivo é o que salva a embarcação inteira."},
      {"ic":"spiral","t":"O Ciclo Respiratório","emph":"Ciclo Respiratório","b":"O mergulho reabastece para que você possa enfrentar a terra de novo. Mas fazer do refúgio uma toca permanente, para nunca mais voltar à vida, é trair a própria missão. <strong>Ir e voltar — mergulhar e emergir — é a respiração perfeita da matriz criativa</strong>: nem se afogar lá embaixo, nem secar aqui em cima.","tip":"<strong>Sinal de alerta:</strong> usar a cura como esconderijo para nunca mais encarar o mundo é deixar o medo, e não a alma, no comando do leme.","warn":True},
      {"ic":"spark","t":"A Voz Sem Dono","emph":"Voz Sem Dono","b":"Falar a partir da própria convicção não pede o carimbo de autoridade nenhuma. Engolir o timbre primal na garganta corta a circulação do espírito. <strong>Dizer a verdade crua no próprio tom é o fôlego do animal livre correndo no campo</strong> — e cantar sobre os ossos, no fim, é exatamente isto: criar sem pedir licença.","tip":"<strong>Modelo mental:</strong> a mudez que você fabrica para não incomodar ninguém vai, devagar, matando o órgão mais vivo que existe em você."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["A alma precisa de regressos regulares à solidão fértil, ou resseca.", "O ciclo saudável é ir e voltar — mergulhar para recarregar, emergir para viver.", "A criatividade é função vital da alma: recuperar a voz própria reúne todos os aprendizados do livro."],
  },
]
