# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'O Mundo de Sofia' (Jostein Gaarder)."""

BOOK = {
  "title": "O Mundo de Sofia",
  "author": "Jostein Gaarder",
  "header_light": "O MUNDO",
  "header_bold": "DE SOFIA",
  "subtitle": "VISÃO GERAL · TODA A FILOSOFIA OCIDENTAL CABE NUMA CAIXA DE CORREIO",
  "intro": "Sofia Amundsen, 14 anos, abre a caixa de correio e encontra um bilhete sem remetente, com três palavras: <em>Quem é você?</em> No dia seguinte chega o segundo: <em>De onde vem o mundo?</em> São as perguntas mais simples que existem — e, justamente por isso, as que ninguém mais ousa fazer depois de crescer. Sofia descobre, num susto, que não sabe responder a nenhuma das duas. Quem as envia é Alberto Knox, um velho filósofo que decide acordá-la para o mundo, carta por carta, de Tales a Sartre. Só que há uma pergunta embaixo de todas, e nem o mestre desconfia dela: <em>e nós, de que matéria somos feitos?</em>",
  "description": "Romance de Jostein Gaarder que esconde, lá dentro, um curso inteiro de história da filosofia — e o milagre é que nunca cheira a sala de aula. Pela mão de Alberto Knox, Sofia atravessa o espanto dos pré-socráticos, o tripé de Atenas (Sócrates, Platão, Aristóteles), o helenismo, a Idade Média, o 'penso, logo existo' de Descartes, os empiristas, a grande costura de Kant, Hegel, os três mestres da suspeita (Marx, Darwin, Freud) e o existencialismo. Então o chão se abre: as personagens descobrem que estão sendo escritas por outra pessoa. A primeira pergunta volta, agora gelada — e desta vez quem a recebe na cara é o leitor: tem tanta certeza assim de que <em>você</em> não é o sonho de alguém?",
  "tags": ["Filosofia", "História", "Educação"],
  "progress": "9 Capítulos",
  "cover": "assets/mundo-de-sofia-cover.png",
  "overview_cards": [
    {"ic":"eye","t":"Tudo Começa no Espanto","b":"A filosofia não nasce de saber muito — nasce de uma coisa que toda criança tem e quase nenhum adulto guarda: achar o mundo <strong>estranho</strong>. Que existam estrelas, que você esteja vivo, que haja algo em vez de nada — isso devia nos derrubar do banco. Mas a gente se acostuma, e o milagre vira papel de parede. <strong>Filósofo é só quem nunca terminou de se espantar.</strong>","tip":"<strong>A pista:</strong> o espanto é o seu termômetro. No dia em que algo descomunal — a consciência, o tempo, o simples existir — virou 'normal', foi você que cochilou, não o mistério que sumiu."},
    {"ic":"layers","t":"Os Dois Grandes Tabuleiros","b":"Esses 2.500 anos de pensamento se jogam, no fundo, em dois tabuleiros. Um pergunta de onde vem o saber: dos <strong>sentidos</strong> ou da <strong>razão</strong>? (Heráclito × Parmênides, empiristas × racionalistas.) O outro pergunta onde mora o real: nas <strong>Ideias eternas</strong> ou nas coisas que dá para morder? (Platão × Aristóteles.) Cada pensador escolhe um lado da rua — até Kant chegar e construir a ponte.","tip":"<strong>Modelo mental:</strong> diante de qualquer filósofo, faça-lhe duas perguntas — de onde ele tira o conhecimento e onde ele guarda a realidade. Com isso você já o tem meio mapeado.","wide":True},
    {"ic":"constellation","t":"O Livro Dobra Sobre Si Mesmo","b":"Aqui está a jogada que torna o romance inesquecível: o curso de filosofia acontece <strong>dentro de uma ficção que pergunta exatamente o que a filosofia pergunta</strong>. Sofia e Alberto descobrem, horrorizados, que são personagens escritos por outra pessoa — e o inocente 'Quem é você?' do primeiro bilhete fica, de repente, vertiginoso. Porque a dúvida deles é, palavra por palavra, a nossa.","tip":"<strong>A pista:</strong> a primeira pergunta do livro nunca é respondida — só volta mais funda. É a filosofia largando o quadro-negro para puxar você pelo colarinho."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-espanto-e-a-moldura",
    "sub": "CAPÍTULO 1: O Espanto e a Moldura",
    "intro": "Toda a filosofia cabe em duas perguntas que quase ninguém faz — não por serem difíceis, mas por serem tão simples que a gente as deixou para trás junto com a infância: 'Quem é você?' e 'De onde vem o mundo?' Sofia abre um envelope sem nome e, pela primeira vez, sente o chão sumir: não sabe responder nem uma nem outra. E descobre que esse susto tem dois lados — é assustador, e é a coisa mais viva que já lhe aconteceu.",
    "cards": [
      {"ic":"eye","t":"O Coelho na Cartola","emph":"Coelho na Cartola","b":"Imagine o universo inteiro como um coelho branco que um mágico imenso acaba de tirar da cartola. Nascemos lá no alto, na ponta dos pelos mais finos, ainda tontos de espanto com o truque. Mas o pelo é morno, e devagarinho a gente <strong>escorrega para o fundo quentinho da pelagem</strong> e cai no sono. O filósofo é só quem se recusa a dormir — e teima em subir de volta pelos pelos para encarar os olhos do mágico.","tip":"<strong>A pista:</strong> a rotina é um cobertor. Se o simples fato de estar vivo já não lhe arranca um arrepio, não foi o milagre que acabou — foi você que escorregou lá para o fundo, pertinho da pele."},
      {"ic":"bulb","t":"A Pergunta Vale Mais que a Resposta","emph":"Perguntar","b":"O mundo nos serve respostas prontas, de embrulho lacrado, e a gente engole sem abrir. A filosofia faz o contrário: tem o atrevimento de <strong>perguntar de novo o que todo mundo já deu por resolvido</strong>. E uma boa pergunta — daquelas que ficam zumbindo no escuro do quarto — vale mais do que cem respostas, porque a resposta a gente decora, mas a pergunta a gente pensa.","tip":"<strong>Modelo mental:</strong> a resposta certa fecha a porta; a boa pergunta a deixa aberta. Quem para de perguntar não ficou sábio — só ficou quieto."},
      {"ic":"bubble","t":"Do Mito à Razão","emph":"Razão","b":"O Ocidente deu seu primeiro passo no dia em que alguém parou de explicar o trovão pela cólera dos deuses e resolveu <strong>caçar a causa dentro da própria natureza</strong>. Não foi a poesia que morreu ali: foi um palpite ousado que nasceu — o de que o mundo, por baixo da confusão, talvez tenha uma ordem que cabe numa cabeça humana.","tip":"<strong>Para refletir:</strong> toda vez que você encerra um assunto com 'é assim e pronto', sem perceber, está voltando a explicar o mundo pela raiva dos deuses."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["Filosofar não começa por doutrina nenhuma — começa por recusar que o mundo seja óbvio.", "A pergunta certa vale mais que a resposta que serve só para nos fazer dormir de novo.", "A criança é a filósofa nata; o trabalho de uma vida é não deixar o espanto apagar."],
  },
  {
    "slug": "ch02-pre-socraticos",
    "sub": "CAPÍTULO 2: Os Pré-socráticos — do Mito ao Logos",
    "intro": "A filosofia ocidental nasce na costa grega da Jônia, no dia em que alguns homens trocam a história dos deuses por uma pergunta nua e ousada: de que é feito, lá no fundo, tudo o que existe (a physis)? E mal a pergunta sai da boca já abre uma fenda que nunca mais se fecha — em quem devemos confiar, nos olhos que veem ou na razão que pensa?",
    "cards": [
      {"ic":"wave","t":"Tudo Flui × Nada Muda","emph":"Flui × Muda","b":"Heráclito fica à beira do rio e entende que <strong>ninguém entra duas vezes na mesma água</strong> — tudo escorre, tudo muda, você inclusive. Parmênides olha o mesmo rio e crava o oposto: os sentidos mentem, e o que existe de verdade não pode mudar jamais. Desses dois espantos contrários brota a maior briga da filosofia — ficar com o que corre ou com o que fica?","tip":"<strong>Modelo mental:</strong> quase toda discussão filosófica é uma reedição desse duelo — a vida que não para de mudar contra a sede de algo que nunca mude."},
      {"ic":"layers","t":"A Busca pela Physis","emph":"Physis","b":"De Tales a Anaximandro, a ousadia foi imaginar que esse universo todo, tão variado, pudesse brotar de <strong>um único princípio</strong> — a água, o ar, o indefinido. As respostas estavam erradas, hoje sabemos; o que continua de tirar o chapéu é a aposta por baixo delas: e se, atrás de toda essa bagunça, houvesse uma só coisa explicando o resto?","tip":"<strong>A pista:</strong> esqueça que eles erraram dizendo 'tudo é água'. Guarde a coragem: a de apostar que o mundo, por mais embaralhado, pode ser entendido."},
      {"ic":"link","t":"Demócrito e os Átomos","emph":"Átomos","b":"Dois mil anos antes do microscópio, Demócrito teve um palpite de gênio: tudo seria feito de <strong>pecinhas minúsculas, eternas e invisíveis</strong> que se encaixam de mil jeitos — como blocos de montar — para dar numa flor, numa estrela ou em você. Sem deus nenhum no meio do caminho: só matéria que se monta e se desmonta.","tip":"<strong>Para refletir:</strong> boa parte da química e da física de hoje é o velho palpite de Demócrito que acabou vingando. Ele acertou o método dois mil anos antes de ter como provar."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["Filosofar é caçar a explicação dentro da natureza, e não acima dela.", "O duelo sentidos × razão (Heráclito × Parmênides) já desenha o mapa de tudo o que vem depois.", "O átomo de Demócrito mostra: pensar o mundo como pura matéria é tão antigo quanto a própria filosofia."],
  },
  {
    "slug": "ch03-socrates-platao-aristoteles",
    "sub": "CAPÍTULO 3: Sócrates, Platão e Aristóteles",
    "intro": "O tripé que sustenta tudo o que veio depois, em três gerações de mestre e aluno: Sócrates inventa o diálogo que faz parir ideias e morre por ele; Platão sobe ao céu e imagina que o real são as Ideias eternas atrás das aparências; e Aristóteles, com os pés outra vez na terra, devolve a filosofia aos sentidos e ao paciente trabalho de olhar o mundo como ele é.",
    "cards": [
      {"ic":"bubble","t":"A Maiêutica Socrática","emph":"Maiêutica","b":"Sócrates não dava aula: fazia perguntas. Dizia-se parteiro de ideias — não enfiava saber na cabeça de ninguém, mas <strong>ajudava o outro a dar à luz aquilo que já sabia sem saber</strong>. E o primeiro empurrão era o mais difícil: confessar 'só sei que nada sei'. Quem chega cheio de certezas nem entra na sala de parto.","tip":"<strong>Como aplicar:</strong> numa discussão emperrada, largue o martelo das afirmações e pegue a lanterna das perguntas. Uma pergunta no lugar certo abre o que dez respostas só trancavam."},
      {"ic":"mountain","t":"O Mundo das Ideias","emph":"Mundo das Ideias","b":"Platão imagina prisioneiros acorrentados numa caverna, de costas para a boca dela, certíssimos de que as <strong>sombras tremendo na parede são o mundo inteiro</strong>. Lá fora, no sol, estariam as coisas de verdade — as Ideias perfeitas e eternas. Filósofo é quem se solta, sai, queima os olhos na luz e volta para avisar: o que vocês chamam de real é só a sombra de uma sombra.","tip":"<strong>Sinal de alerta:</strong> aquilo que você jura ser a verdade absoluta talvez seja só um vulto na parede — a cópia borrada de algo que você ainda não virou para encarar.","warn":True},
      {"ic":"lens","t":"Aristóteles — A Forma nas Coisas","emph":"Forma nas Coisas","b":"Aristóteles, aluno de Platão, discorda do mestre com respeito e firmeza: a perfeição não mora num céu de gaveta. A forma de uma coisa <strong>está dentro da coisa que você pode ver, pegar e cheirar</strong>. Por isso o conhecimento entra pelos sentidos — é olhar, contar, nomear e arrumar o mundo com paciência, exatamente do jeito que ele é.","tip":"<strong>Modelo mental:</strong> se você se consome comparando a vida real a um ideal guardado na gaveta, chame Aristóteles: a única perfeição ao seu alcance está no que existe à sua frente, não no rascunho impecável."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["Sócrates: a verdade nasce no diálogo e na coragem humilde de admitir a própria ignorância.", "Platão: há uma realidade perfeita e racional por trás das aparências que os olhos alcançam.", "Aristóteles: conhecer começa pelos sentidos e pela observação ordenada deste mundo, não de outro."],
  },
  {
    "slug": "ch04-helenismo-e-idade-media",
    "sub": "CAPÍTULO 4: Helenismo e Idade Média",
    "intro": "Passado o esplendor de Atenas, a filosofia troca a pergunta sobre o cosmos por uma mais íntima e urgente: como viver bem num mundo que desabou? Daí saem o estoicismo, o epicurismo, o cinismo e o ceticismo. Séculos depois, na Idade Média, ela encontra o cristianismo e faz dois casamentos arranjados — Agostinho leva Platão para dentro da fé, Tomás de Aquino faz o mesmo com Aristóteles.",
    "cards": [
      {"ic":"leaf","t":"Filosofia como Arte de Viver","emph":"Arte de Viver","b":"Quando o velho mundo grego ruiu, a filosofia desceu das estrelas e virou conselho de cabeceira. O estoico treina-se a <strong>só se afligir com aquilo que de fato está nas suas mãos</strong>; o epicurista persegue uma alegria serena, feita de poucas coisas boas e da ausência de dor. Pensar deixou de ser contemplar o céu — passou a ser, antes de tudo, aprender a viver.","tip":"<strong>Como aplicar:</strong> a chave estoica é curta e cabe no bolso — separe com calma o que você pode mudar do que não pode, e queime a sua energia só no primeiro lado."},
      {"ic":"scale","t":"Agostinho × Tomás — Fé e Razão","emph":"Fé e Razão","b":"Dois gigantes costuraram Atenas com Jerusalém. Agostinho aproximou Platão da fé cristã; Tomás de Aquino fez o mesmo com Aristóteles e ousou dizer que <strong>a razão, andando sozinha, é capaz de chegar até Deus</strong>. A Idade Média não foi um cochilo de mil anos: foi a ponte que atravessou a herança grega por cima do abismo até nós.","tip":"<strong>Para refletir:</strong> não chame a Idade Média de 'buraco negro'. Foi ali, à luz de vela, que monges copiaram e discutiram o pensamento antigo para que ele não se perdesse."},
      {"ic":"spiral","t":"Neoplatonismo — A Emanação do Uno","emph":"Emanação","b":"Plotino imaginou que tudo o que existe <strong>transborda de uma única fonte de luz, o Uno</strong>, como anéis abrindo-se na água parada quando cai uma pedra. Quanto mais longe da fonte, mais fraca a luz — e a matéria seria a margem mais distante, já quase tomada pela sombra. Voltar ao centro, à claridade, seria a viagem do espírito.","tip":"<strong>Modelo mental:</strong> é uma figura que reaparece em mil roupagens na história — uma só luz da qual tudo escorre, e um caminho de regresso de volta à fonte."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["A filosofia também é uma arte de viver bem em meio à incerteza, não só de explicar o cosmos.", "O cristianismo medieval não apaga a filosofia grega — abraça-a e a carrega adiante.", "Fé e razão podem cooperar (Tomás) ou a fé pode vir na frente (Agostinho): um debate que atravessa os séculos."],
  },
  {
    "slug": "ch05-renascenca-descartes",
    "sub": "CAPÍTULO 5: Renascença e Descartes",
    "intro": "A Renascença tira Deus do centro do palco e põe ali, de novo, o ser humano — com o humanismo e os primeiros passos do método científico. E então entra Descartes, sentado junto à lareira, decidido a duvidar de tudo. No fundo dessa dúvida sem fundo ele topa com o único chão que não treme — 'penso, logo existo' — e funda, sozinho, a filosofia moderna.",
    "cards": [
      {"ic":"bulb","t":"A Dúvida Metódica","emph":"Dúvida Metódica","b":"Descartes resolve duvidar de tudo de propósito — dos sentidos, das tradições, até de estar acordado — só para ver o que sobra de pé. Não é desespero, é <strong>obra: demolir tudo o que balança</strong> à procura de uma única rocha firme onde levantar a casa do zero, dessa vez sem nenhuma rachadura na fundação.","tip":"<strong>Como aplicar:</strong> quer chegar ao osso de uma questão? Suspenda, por um instante, tudo o que você acredita 'porque sempre foi assim', e repare no que continua em pé sem ninguém segurar."},
      {"ic":"spark","t":"'Penso, Logo Existo'","emph":"Penso, Logo Existo","b":"No fundo do poço da dúvida, Descartes encontra a rocha: mesmo que tudo o mais seja ilusão, <strong>o próprio fato de eu estar duvidando já prova que eu existo</strong>. Posso desconfiar de tudo, menos de que há um 'eu' aqui, pensando agora. E com essa frase de quatro palavras a filosofia muda de endereço — o ponto de partida deixa de ser o mundo e passa a ser quem o pensa.","tip":"<strong>Modelo mental:</strong> repare na virada — a certeza não cai mais do céu, nem vem dos antigos, nem dos olhos, mas brota de dentro, do próprio ato de pensar."},
      {"ic":"gap","t":"O Problema do Dualismo","emph":"Dualismo","b":"Para salvar o pensamento, Descartes acaba serrando o mundo em dois: de um lado o <em>espírito</em>, que pensa e não ocupa lugar; do outro, a <em>matéria</em>, que ocupa lugar e não pensa. E aí nasce um nó que ninguém soube desatar: <strong>se alma e corpo são feitos de estofos tão diferentes, como diabos um consegue mexer no outro?</strong>","tip":"<strong>Para refletir:</strong> até hoje tratamos mente e corpo como dois inquilinos estranhos dividindo a mesma casa — e esse estranhamento começou com a serra de Descartes."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["A Renascença solta a investigação da tutela exclusiva da fé e acende a ciência moderna.", "Descartes faz da consciência — não do céu — o ponto de partida seguro da filosofia.", "O corte mente/corpo abre um nó que vai ocupar toda a filosofia que vem depois."],
  },
  {
    "slug": "ch06-spinoza-empiristas",
    "sub": "CAPÍTULO 6: Spinoza e os Empiristas",
    "intro": "Contra as ideias inatas de Descartes, os empiristas britânicos cravam a aposta oposta: nada entra na mente que não tenha passado, antes, pelos sentidos. E Hume leva o palpite ao extremo, dissolvendo até o 'eu' e a causalidade — foi ele, dirá Kant, que o 'acordou do sono dogmático'. Spinoza, por uma trilha à parte, faz o gesto mais ousado de todos: funde Deus e Natureza numa só palavra.",
    "cards": [
      {"ic":"leaf","t":"Deus sive Natura","emph":"Deus sive Natura","b":"Spinoza tem uma intuição de tirar o fôlego: Deus e a Natureza são <strong>a mesma e única realidade infinita</strong>. Não há relojoeiro lá fora que montou o mundo e foi-se embora; nós somos pedaços do próprio Deus-Natureza, ondas de um único mar. Tudo está preso a tudo, num só tecido sem costura nem avesso.","tip":"<strong>Modelo mental:</strong> olhe a sua vida 'sob a perspectiva da eternidade'. Vista lá do alto, na escala do todo infinito, boa parte dos seus dramas perde o peso."},
      {"ic":"eye","t":"Folha em Branco e 'Ser é Ser Percebido'","emph":"Folha em Branco","b":"Locke diz que nascemos como uma <strong>folha em branco</strong>, e que é a vida que vem nos escrevendo, linha a linha. Berkeley vai mais fundo e solta uma ideia de tirar o chão: existir, para uma coisa, seria nada mais que <strong>ser percebido por alguém</strong>. Tire o observador e a matéria evapora — sobram só ideias flutuando no ar.","tip":"<strong>A pista:</strong> não solte esse 'ser é ser percebido'. É a sementinha filosófica da grande virada do livro — Sofia descobrindo que só existe porque alguém a está imaginando."},
      {"ic":"lens","t":"Hume Dissolve a Causalidade","emph":"Causalidade","b":"Hume, o cético de boa pergunta, encosta o dedo na ferida: você já viu, com os próprios olhos, a 'causa' empurrar o 'efeito'? Nunca. Você só viu <strong>uma bola bater na outra mil vezes</strong> e se acostumou a esperar o de sempre. A lei que parecia de ferro talvez não passe de um hábito teimoso da nossa cabeça.","tip":"<strong>Para refletir:</strong> aquilo que você chama de 'regra que nunca falha' não seria, lá no fundo, só o costume de ter visto a mesma coisa se repetir até hoje?","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["Para os empiristas, todo conhecimento brota da experiência — pela porta dos sentidos.", "Hume dissolve o eu e a causalidade — à razão sobra apenas o velho hábito.", "Berkeley: 'existir é ser percebido' — a semente filosófica da virada meta do livro."],
  },
  {
    "slug": "ch07-kant",
    "sub": "CAPÍTULO 7: Kant — a Grande Síntese",
    "intro": "Empiristas e racionalistas brigaram por dois séculos, e os dois tinham metade da razão — é o que Kant mostra ao apaziguá-los: o conhecimento traz uma matéria que vem de fora (pelos sentidos) e uma forma que já trazemos de berço dentro da cabeça. Daí a conclusão que dá vertigem: jamais tocamos a coisa-em-si — só conhecemos o mundo já amassado pelo nosso próprio aparelho de pensar.",
    "cards": [
      {"ic":"lens","t":"Os Óculos da Mente","emph":"Óculos da Mente","b":"Kant achou a imagem exata: o espaço, o tempo e a causa não andam soltos pelo mundo — são <strong>óculos que a gente nasce usando e não consegue tirar do rosto</strong>. Tudo o que enxergamos já chega filtrado por essas lentes. É por isso que a ciência funciona tão bem; só que ela vale para o mundo visto pelos óculos, nunca para o mundo cru, sem lentes.","tip":"<strong>Modelo mental:</strong> não adianta espernear para ver a realidade sem o seu próprio cérebro no meio. Mas saber que se está de óculos já é meio caminho andado para pensar melhor."},
      {"ic":"gap","t":"Fenômeno × Coisa-em-Si","emph":"Fenômeno × Coisa-em-Si","b":"Então Kant risca no chão uma fronteira que ninguém pula. O mundo como ele <strong>aparece para nós</strong> (o fenômeno) é o campo onde a ciência joga à vontade. O mundo como ele é <strong>em si mesmo</strong>, atrás dos óculos, fica do outro lado de uma porta trancada por dentro. Não estamos sonhando — é que existe um limite, e Kant pede joelho dobrado diante dele.","tip":"<strong>Sinal de alerta:</strong> quem jura ter desvendado a verdade última do universo está, sem perceber, querendo enxergar sem os próprios olhos."},
      {"ic":"scale","t":"O Imperativo Categórico","emph":"Imperativo Categórico","b":"Na moral, Kant não manda obedecer a Deus nem calcular o lucro. Exige uma coisa que a própria razão cobra de você: <strong>aja somente do jeito que você toparia ver virar lei para o mundo inteiro</strong>. E nunca trate ninguém como mera ferramenta — cada pessoa é um fim em si, jamais um meio descartável.","tip":"<strong>Como aplicar:</strong> antes de uma escolha duvidosa, faça a si mesmo a pergunta de Kant — 'e se todos fizessem isto?'. Se a resposta assusta, é provável que o caminho não seja esse."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["Empiristas e racionalistas estavam, cada um, com metade da verdade: conhecer exige experiência e estruturas mentais de mãos dadas.", "Há um muro intransponível — a coisa-em-si fica para sempre fora do alcance da razão.", "A moral não cai do céu: nasce de dentro, da razão prática que cada um já carrega."],
  },
  {
    "slug": "ch08-hegel-kierkegaard-marx-freud",
    "sub": "CAPÍTULO 8: Hegel, Kierkegaard e os Mestres da Suspeita",
    "intro": "O século XIX vem e sacode tudo. Hegel mostra que a verdade não está pronta — faz-se aos trancos, ao longo da história (a dialética); Kierkegaard se rebela em nome do sujeito de carne e osso, esquecido dentro do sistema; e Marx, Darwin e Freud, cada um com seu martelo, derrubam a velha estátua orgulhosa do homem senhor de si.",
    "cards": [
      {"ic":"spiral","t":"A Dialética de Hegel","emph":"Dialética","b":"Para Hegel, a verdade não é uma pedra parada na vitrine de um museu: ela <strong>cresce no tempo, junto com a história</strong>. Nasce uma ideia (a tese), levanta-se a ideia contrária (a antítese), e do atrito das duas surge algo maior, que guarda o melhor de cada uma (a síntese). É assim, contradição vencida após contradição, que o pensamento sobe um degrau.","tip":"<strong>Como aplicar:</strong> numa discordância, não tente só atropelar o outro lado. O gesto mais adulto é colher a parte de razão que ele carrega e seguir em frente já com ela no bolso."},
      {"ic":"person","t":"Kierkegaard — O Indivíduo Concreto","emph":"Indivíduo Concreto","b":"Kierkegaard acha gélido falar só do grandioso 'Espírito do mundo' de Hegel. E aquele sujeito ali no canto, sozinho, que <strong>tem de decidir agora como vai viver a própria vida</strong>? É dele que tudo pende. Aqui nasce o existencialismo: a verdade que importa não é a do sistema bonito, é a que você carrega na pele e escolhe de dentro da angústia.","tip":"<strong>Modelo mental:</strong> nenhuma teoria grandiosa sobre 'a Humanidade' decide por você uma só escolha sua. No fim da fila é sempre um indivíduo concreto que precisa dar o passo."},
      {"ic":"triangle","t":"Os Três Mestres da Suspeita","emph":"Mestres da Suspeita","b":"Três pensadores derrubaram o trono da razão soberana. Darwin mostrou que o homem <strong>não foi posto no mundo pronto, mas evoluiu</strong>, parente dos outros bichos. Marx mostrou que muitas ideias 'nobres' servem, calado, a interesses de bolso. E Freud mostrou que <strong>nem dentro da própria cabeça a gente manda sozinho</strong> — há um inconsciente decidindo no porão.","tip":"<strong>Para refletir:</strong> diante de uma ideia que se diz nobre, vale erguer o tapete e olhar o que se esconde embaixo — uma herança biológica, um interesse financeiro ou um desejo que não ousa dizer o nome."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Hegel: a verdade se cumpre na história, por contradições que vão sendo superadas degrau a degrau.", "Kierkegaard: contra todo sistema, o que conta é o indivíduo que existe, sofre e decide.", "Marx, Darwin e Freud: três marteladas na velha imagem do homem totalmente dono de si e da própria consciência."],
  },
  {
    "slug": "ch09-sartre-virada-meta",
    "sub": "CAPÍTULO 9: Sartre, a Virada Meta e o Cosmos",
    "intro": "O fecho filosófico chega com Sartre — 'a existência precede a essência; estamos condenados a ser livres'. E então a genialidade de Gaarder fecha o círculo: Sofia descobre que é personagem de um livro, escrita por outra mão. A pergunta inocente do primeiro bilhete, 'Quem é você?', volta no nível mais fundo que existe — e desta vez ela não tem mais para onde correr.",
    "cards": [
      {"ic":"key","t":"'Condenados a ser Livres'","emph":"Condenados","b":"Sartre puxa o tapete de quem queria uma 'natureza humana' pronta de fábrica: ninguém nasce com manual de instruções. Somos atirados no mundo e <strong>obrigados a inventar o próprio sentido, escolha após escolha</strong>. Essa liberdade total não é festa — dá vertigem, porque não sobra ninguém para a conta: nem a sorte, nem os genes, nem Deus. Só você.","tip":"<strong>Sinal de alerta:</strong> Sartre chama de 'má-fé' aquele truque velho de fingir que 'não tive escolha', só para não ter de carregar o peso do que a gente, no fundo, decidiu.","warn":True},
      {"ic":"constellation","t":"A Virada Meta","emph":"Virada Meta","b":"Eis o golpe de mestre do livro. Sofia e Alberto vão catando pistas estranhas até encarar o impensável: <strong>são personagens, escritos por um pai de presente para a filha</strong>. E aí toda a filosofia que estudaram ferve de uma vez — porque os dois resolvem fazer o gesto mais existencialista de todos: tentar fugir das mãos do autor e passar a agir por conta própria.","tip":"<strong>Modelo mental:</strong> pense em quantos roteiros já vêm escritos botando palavras na sua boca — família, escola, propaganda, hábito. De tudo o que você diz num dia, quanto é fala sua, e quanto é texto que alguém escreveu antes?"},
      {"ic":"eye","t":"O Cosmos e o Espanto Final","emph":"Espanto Final","b":"O livro acaba onde começou: no espanto. Os átomos do seu corpo já foram <strong>fogo de estrelas antigas que explodiram</strong> bilhões de anos atrás — você é, ao pé da letra, o universo que um dia abriu olhos para se olhar e ficar de queixo caído consigo mesmo. A ciência explica quase tudo; mas o assombro de simplesmente existir não vai embora nunca.","tip":"<strong>Para refletir:</strong> se lembrar que você é poeira de estrela que aprendeu a pensar não lhe acende nem um fiozinho de espanto, talvez nada mais acenda. Não deixe essa chama apagar — ela é a primeira e a última lição do livro."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["Sartre: não existe essência pronta — a gente se fabrica a cada escolha que faz.", "A virada meta tira a filosofia do papel e a transforma em experiência vivida pelo próprio leitor.", "A maior sabedoria do livro é simples e dá para levar na mochila: nunca perca a capacidade de se espantar com o mundo."],
  },
]
