# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'Nação Dopamina' de Anna
Lembke. A neurociência do prazer e do vício: a balança prazer-dor, o déficit
de dopamina, o jejum, o autovínculo, a busca pela dor e o equilíbrio."""

BOOK = {
 "title": "Nação Dopamina",
 "author": "Anna Lembke",
 "header_light": "NAÇÃO",
 "header_bold": "DOPAMINA",
 "subtitle": "VISÃO GERAL · A BALANÇA ENTRE O PRAZER E A DOR",
 "intro": "Anna Lembke é psiquiatra do vício — e começa o livro confessando o próprio: romances baratos, lidos compulsivamente de madrugada. Sua tese vem do consultório e da neurociência: prazer e dor são processados no mesmo lugar do cérebro, em lados opostos de uma balança que só quer ficar nivelada. Por isso todo prazer cobra a sua dor depois. Inunde a balança e o cérebro instala pesos do lado da dor para se defender — é assim que a busca da felicidade fabrica o sofrimento, e por que, no mundo mais farto da história, estamos tão infelizes.",
 "description": "A neurociência do prazer e do vício, por Anna Lembke. A balança prazer-dor e a homeostase; a dopamina como régua do potencial viciante; a tolerância, a anedonia e o déficit que nasce do excesso; o cérebro de escassez perdido na abundância; o jejum de dopamina (~30 dias, acrônimo DOPAMINE); o autovínculo contra a fissura; a busca deliberada da dor (hormese); a honestidade radical e a vergonha que reconecta. A receita não é abolir o prazer — é aprender a sentar-se no meio da balança.",
 "tags": ["Psicologia", "Neurociência", "Hábitos"],
 "progress": "9 Capítulos",
 "cover": "assets/nacao-dopamina-cover.png",
 "overview_cards": [
   {"ic":"scale","t":"A Balança Prazer-Dor","b":"Prazer e dor não têm cada um o seu botão: dividem o <strong>mesmo lugar do cérebro</strong>, em pratos opostos de uma balança que detesta ficar inclinada. Incline-a para o prazer e o cérebro a empurra de volta — com a mesma força, e ainda passa um pouco do ponto. <strong>O preço do prazer é a dor que vem depois</strong>.","tip":"<strong>Como aplicar:</strong> o tombo que se segue ao êxtase é física da balança, não falha de caráter.","wide":True},
   {"ic":"spiral","t":"O Déficit de Dopamina","b":"Repita o excesso e o cérebro instala pesos fixos no prato da dor (<strong>tolerância</strong>): a balança passa a viver torta para baixo. Precisa-se de mais só para sentir o normal, e a vida comum desbota (<strong>anedonia</strong>). Já não se usa para subir — usa-se para não afundar.","tip":"<strong>Chave:</strong> quando nada mais tem graça, desconfie do excesso de ontem, não do mundo de hoje."},
   {"ic":"key","t":"A Saída — Abstinência e Dor","b":"A cura começa por parar: o <strong>jejum de dopamina</strong> (cerca de 30 dias para renivelar a balança), amparado pelo <strong>autovínculo</strong> — muros entre você e o estímulo. Depois inverte-se a lógica: <strong>apertar de propósito o prato da dor</strong> (frio, exercício) faz a balança rebater ao prazer, e desta vez de graça.","tip":"<strong>Modelo mental:</strong> a dor escolhida é a porta dos fundos para o prazer que não cobra ressaca."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-balanca-prazer-dor","sub":"CAPÍTULO 1: A Balança Prazer-Dor",
  "intro":"Imagine uma balança dentro da cabeça, com prazer de um lado e dor do outro. Ela tem uma regra só: voltar ao nível. Tudo o que se segue no livro nasce daqui.",
  "cards":[
      {"ic":"scale","t":"A Mesma Balança","emph":"Balança","b":"O cérebro não guarda o prazer e a dor em salas separadas: eles ocupam os mesmos circuitos, em pratos opostos de uma só balança. E essa balança obedece a um único mandamento — <strong>nunca permanecer inclinada</strong>. Cada vez que ela pende para o prazer, mecanismos automáticos puxam o outro prato para baixo, até zerar a conta.","tip":"<strong>Como aplicar:</strong> não há prazer de graça. O que vem fácil e instantâneo é sempre um empréstimo — e o cérebro cobra na mesma moeda."},
      {"ic":"wave","t":"A Conta Vem Depois","emph":"Conta","b":"O baixo que se segue ao pico não é arrependimento moral: é a balança rebatendo, e por um instante <strong>ela passa do ponto e pende para a dor</strong>. Daí a fissura — vontade de repetir só para voltar à linha de base. Repita uma vez e o desconforto passa; repita muitas e ele vira o seu estado normal.","tip":"<strong>Modelo mental:</strong> matar o vazio do pós-festa com mais estímulo é pagar dívida com cartão de crédito: alivia hoje, encarece amanhã."},
      {"ic":"gap","t":"De Hábito a Vício","emph":"Vício","b":"O vício é o que acontece quando a balança não consegue mais subir. À força de só caçar picos, ela emperra inclinada para a dor: aquilo que antes alegrava agora mal levanta a pessoa do chão. <strong>Passa-se a usar não para sentir prazer, mas para escapar do sofrimento de não usar</strong> — o motivo já não é o alto, é fugir do baixo.","tip":"<strong>Sinal de alerta:</strong> quando você repõe a angústia com mais rolagem de tela ou mais um copo, não conserta a balança — só joga peso no lado errado.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Prazer e dor dividem o mesmo circuito, em pratos opostos de uma balança que só quer ficar nivelada.","Pela homeostase, todo prazer é compensado com dor — e o cérebro chega a passar do ponto.","O tombo depois do êxtase é física da balança, não fraqueza moral."]},

 {"slug":"ch02-dopamina-moeda","sub":"CAPÍTULO 2: Dopamina — A Moeda do Vício",
  "intro":"A dopamina não é a molécula do prazer, como se diz por aí. É a molécula da busca, do querer, do 'vamos atrás'. E os neurocientistas a usam como régua: quanto mais dopamina algo dispara, mais viciante ele é.",
  "cards":[
      {"ic":"target","t":"Querer Sem Gostar","emph":"Querer","b":"No laboratório, querer e gostar revelam-se duas coisas separadas — e a dopamina move o querer, não o gostar. É por isso que o vício é tão cruel: <strong>o desejo sobrevive depois que o prazer já morreu</strong>. A pessoa persegue com toda a força algo que nem desfruta mais, obedecendo a uma ordem interna de 'mais' que perdeu o sentido.","tip":"<strong>Prática:</strong> diante de um hábito compulsivo, faça a pergunta honesta — ainda estou gostando disto, ou só estou querendo?"},
      {"ic":"spark","t":"A Régua da Dopamina","emph":"Régua","b":"O risco de um prazer não está só no que ele é, mas em quanta dopamina ele libera e com que velocidade. Quanto mais alto e mais rápido o pico, mais forte a balança rebate — e mais perigoso o hábito. <strong>Um celular no bolso pode disparar a régua tão alto quanto uma droga</strong>: é potente, instantâneo e está sempre à mão.","tip":"<strong>Modelo mental:</strong> meça o risco pela facilidade. Se é rápido, indolor e a um toque de distância, trate com respeito."},
      {"ic":"gap","t":"A Caça Que Não Acaba","emph":"Caça","b":"Apostar a felicidade na busca direta de mais dopamina é entrar numa roda que gira sem chegar a lugar nenhum. Confundir o pico químico barato com bem-estar de verdade <strong>deixa a pessoa exausta e vazia no meio da fartura</strong> — rica em estímulos, falida de sentido.","tip":"<strong>Sinal de alerta:</strong> vício não é só cigarro e álcool. A tela que brilha na sua mão destila a mesma moeda — e a saca a qualquer hora.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["A dopamina é a moeda do querer e da busca — e a régua usada para medir o potencial viciante.","Querer e gostar são circuitos distintos; o vício é querer muito o que já não se gosta.","Quanto mais alto e mais rápido o pico de dopamina, mais perigoso o hábito."]},

 {"slug":"ch03-deficit-dopamina","sub":"CAPÍTULO 3: O Déficit de Dopamina",
  "intro":"Gosto de imaginar gremlins minúsculos pulando no prato da dor cada vez que provamos prazer — restaurando o nível. Repita o prazer demais e eles não vão embora: ficam morando ali, acampados no lado da dor.","cards":[
      {"ic":"spiral","t":"Os Gremlins Que Ficam","emph":"Gremlins","b":"A cada dose de prazer, o cérebro joga gremlins no prato da dor para reequilibrar a balança. Use uma vez e eles saem depois. Use sem parar e eles <strong>se instalam de vez no lado da dor</strong>. É a tolerância: a mesma dose já não levanta a balança, e o custo embaixo só cresce. Precisa-se de mais para sentir menos.","tip":"<strong>Regra:</strong> não enfrente a tolerância dobrando a dose. Nesse cassino a banca sempre ganha, porque a banca é a sua própria biologia."},
      {"ic":"eye","t":"O Mundo Sem Cor","emph":"Anedonia","b":"Com a balança travada para baixo, instala-se a anedonia: a vida perde a cor. Nada anima, e nem a própria droga predileta chega ao êxtase de antes. O sentido do uso se inverte — <strong>já não se usa para tocar o céu, mas para aliviar por uns minutos o peso de estar no fundo</strong>.","tip":"<strong>Como aplicar:</strong> aquele embotamento diante das alegrias simples talvez não seja idade nem tédio, e sim a ressaca de tanto estímulo artificial."},
      {"ic":"gap","t":"Cavar Para Sair Do Buraco","emph":"Buraco","b":"Tentar tapar o vazio com mais da mesma fonte que o abriu é cavar para tentar sair do buraco. A cada dose de alívio, <strong>mais gremlins se mudam para o prato da dor</strong>, e a balança afunda mais um pouco. O remédio aparente é, ele próprio, a doença que se agrava.","tip":"<strong>Sinal de alerta:</strong> aquele desânimo crônico de que 'nada presta' pode não ser a vida pedindo mais estímulo, e sim o cérebro pedindo a pausa da abstinência.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["O excesso repetido rebaixa a dopamina basal — surgem a tolerância e o déficit.","Os gremlins se acumulam no prato da dor; o estado neutro vira negativo (anedonia).","No vício maduro, a busca do prazer dá lugar à fuga da dor."]},

 {"slug":"ch04-era-da-indulgencia","sub":"CAPÍTULO 4: A Era da Indulgência",
  "intro":"Eis o descompasso central da nossa época: um cérebro afinado por milênios de escassez, agora largado num mundo de prazer ilimitado, barato e a um clique de distância. A balança não foi feita para isto.",
  "cards":[
      {"ic":"link","t":"Feito Para A Escassez","emph":"Escassez","b":"Por milhares de gerações o corpo aprendeu a economizar para recompensas raras: caçar, guardar, esperar. Esse mesmo corpo acordou num mundo de fartura. <strong>O maquinário não enguiçou — só foi atropelado por uma abundância para a qual ninguém o projetou</strong>.","tip":"<strong>Como aplicar:</strong> não é só 'pouca força de vontade'. É um instinto antigo, desarmado, diante de um mundo engenhado para fisgá-lo."},
      {"ic":"pin","t":"A Agulha No Bolso","emph":"Agulha","b":"O celular deixou de ser ferramenta para virar a seringa da nossa era. Ele reúne os dois ingredientes que mais viciam: <strong>a recompensa imprevisível da máquina caça-níqueis e o acesso a qualquer hora, no bolso, sem fricção</strong>. Nunca um vício esteve tão à mão.","tip":"<strong>Modelo mental:</strong> ninguém deixaria um caça-níqueis ligado na mesa de jantar. O celular faz exatamente isso, e nós o aplaudimos."},
      {"ic":"gap","t":"A Infelicidade Dos Fartos","emph":"Fartura","b":"A onda de ansiedade e vazio justo nos países mais ricos derruba a velha promessa de que mais conforto traria mais felicidade. A dor de viver cresce <strong>não pela falta, mas pelo excesso</strong> — pela balança permanentemente torta de tanto prazer fácil. Mais distração só funda a solidão.","tip":"<strong>Sinal de alerta:</strong> tentar curar a infelicidade despejando mais consumo e mais tela em cima dela é jogar gasolina para apagar fogo.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["Um cérebro moldado pela escassez foi solto num mundo de superabundância de dopamina.","O smartphone é a 'agulha' moderna; a recompensa imprevisível é o padrão mais viciante.","O mal-estar contemporâneo vem do excesso, não da falta."]},

 {"slug":"ch05-jejum-de-dopamina","sub":"CAPÍTULO 5: O Jejum de Dopamina",
  "intro":"A primeira coisa que peço aos meus pacientes é a mais difícil: parar. Quatro semanas de abstinência — tempo de a balança renivelar e o cérebro reaprender a sentir prazer nas coisas comuns.",
  "cards":[
      {"ic":"clock","t":"Vai Piorar Antes De Melhorar","emph":"Travessia","b":"Cerca de trinta dias longe do estímulo: é o que custa renivelar a balança. E os primeiros dias são os piores — a balança range no fundo da dor e a fissura grita para você desistir. <strong>É justamente aí que muita gente abandona, dias antes de a calmaria chegar</strong>, em geral na segunda quinzena.","tip":"<strong>Prática:</strong> o jejum não serve para mutilar a alegria, mas para devolver o paladar — voltar a sentir o gosto das coisas simples."},
      {"ic":"steps","t":"O Roteiro DOPAMINE","emph":"DOPAMINE","b":"Para não navegar às cegas, Lembke organiza o jejum num roteiro — o acrônimo DOPAMINE: levante os <strong>dados</strong> do próprio uso, nomeie os <strong>objetivos</strong> e os <strong>problemas</strong>, faça a <strong>abstinência</strong> com presença (mindfulness), colha o <strong>insight</strong>, planeje os próximos passos e teste a vida sem o estímulo. Não é força bruta: é método.","tip":"<strong>Modelo mental:</strong> trate a fissura como onda do mar — não bata de frente. Fique parado, respire, e espere a água recuar sozinha."},
      {"ic":"gap","t":"A Cilada Da Moderação","emph":"Moderação","b":"O erro clássico é largar no terceiro dia, convencido de que tanto sofrimento 'prova' que a moderação seria mais sensata. Mas <strong>num circuito já viciado, moderar antes da abstinência é quase impossível</strong> — a primeira dose só reacende a fissura inteira.","tip":"<strong>Sinal de alerta:</strong> desistir no auge da tempestade, achando que 'não valeu a pena', é confundir o pior momento do processo com o seu fim.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["A cura começa pela abstinência — cerca de 30 dias para renivelar a balança.","O acrônimo DOPAMINE dá o roteiro do jejum, do levantamento de dados ao experimento.","Piora antes de melhorar; o alvo é reaver a sensibilidade ao prazer simples."]},

 {"slug":"ch06-autovinculo","sub":"CAPÍTULO 6: O Autovínculo",
  "intro":"A força de vontade é um músculo que falha justo quando mais precisamos dele — no auge da fissura. O autovínculo (self-binding) resolve isso ao contrário: decide-se com a mente fria e ergue-se uma barreira, para que a hora quente não tenha o que decidir.",
  "cards":[
      {"ic":"key","t":"Três Tipos De Muro","emph":"Muros","b":"O autovínculo é levantar barreiras enquanto se tem juízo. O <strong>muro físico</strong> põe distância — a garrafa fora de casa, o app desinstalado. O <strong>cronológico</strong> define horários e limites sem negociação. O <strong>categórico</strong> é a regra de não-uso, simples e inegociável. Todos partem da mesma humildade: planejar para a fraqueza, não para a força.","tip":"<strong>Como aplicar:</strong> não conte com a sua coragem de dizer não na hora H. Conte com a porta trancada que tira o 'sim' da mesa."},
      {"ic":"link","t":"Ulisses E O Mastro","emph":"Mastro","b":"Ulisses sabia que não resistiria ao canto das sereias, então mandou amarrar-se ao mastro antes de chegar perto. O autovínculo é isso: <strong>deixar o seu eu sóbrio de hoje vencer, de antemão, o seu eu fissurado de amanhã</strong>. Prevenir não é fraqueza — é a forma esperta de coragem.","tip":"<strong>Regra:</strong> não fique testando a si mesmo todo dia para provar que aguenta. Quem brinca perto do fogo acaba queimado."},
      {"ic":"gap","t":"A Cerca De Mentira","emph":"Cerca","b":"Apagar o atalho do celular, mas deixar o login pronto no computador, é erguer cerca de papel. Quando a barreira pode ser pulada em três cliques preguiçosos, <strong>o que você está protegendo não é a abstinência — é a desculpa</strong>. No fundo, montou o teatro do esforço com a saída já aberta.","tip":"<strong>Sinal de alerta:</strong> se o muro tem uma brecha conveniente para a noite de recaída, ele não é muro: é convite.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["A força de vontade é frágil; o autovínculo cria barreiras que dispensam a luta na hora da fissura.","São três tipos: físico (distância), cronológico (tempo) e categórico (regra de não-uso).","Decida com a mente fria — erga o muro antes de a fissura chegar."]},

 {"slug":"ch07-busca-pela-dor","sub":"CAPÍTULO 7: A Busca pela Dor",
  "intro":"Eis a virada mais contraintuitiva do livro. Se buscar prazer traz dor, então buscar dor de propósito traz prazer. A balança funciona nos dois sentidos — e este é o melhor dos dois.",
  "cards":[
      {"ic":"pivot","t":"A Balança Ao Contrário","emph":"Inverter","b":"Apertar de propósito o prato da dor — um banho gelado, uma corrida puxada — inclina a balança para baixo. E o cérebro responde como sempre: empurra de volta para o prazer. Só que aqui <strong>o rebote é lento, demorado e de graça</strong>, sem a fissura que cobra o atalho químico.","tip":"<strong>Como aplicar:</strong> a dor escolhida é o único jeito de obter prazer do sistema sem ficar devendo a ele depois."},
      {"ic":"steps","t":"A Dose De Sofrimento","emph":"Dose","b":"Em vez de fugir do desconforto, convide-o em pequenas doses. O frio, o jejum, os pesos, a leitura difícil estressam o corpo na medida certa — e <strong>ele se recupera mais forte, com foco e humor que duram</strong>. É a hormese: o que não te quebra recalibra a balança a teu favor.","tip":"<strong>Modelo mental:</strong> trate cada ritual de esforço como uma vacina — uma dose controlada de mal que treina o corpo para o bem."},
      {"ic":"gap","t":"Quando A Dose Vira Veneno","emph":"Veneno","b":"A diferença entre remédio e veneno é a dose. Levado ao excesso, o sofrimento deixa de curar e passa a destruir — e aí vira só outro vício, agora disfarçado de disciplina. <strong>Buscar dor sem limite não recalibra a balança: arrebenta-a</strong>. O ganho mora na medida, não no martírio.","tip":"<strong>Sinal de alerta:</strong> masoquismo com etiqueta de 'alta performance' é a mente desregulada achando um novo jeito de afundar.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["Apertar de propósito o prato da dor faz a balança rebater ao prazer (hormese).","Frio, exercício e jejum rendem prazer duradouro e sem ressaca.","A dose certa é moderada; dor demais é dano, não remédio."]},

 {"slug":"ch08-honestidade-radical","sub":"CAPÍTULO 8: A Honestidade Radical",
  "intro":"Reparei nos meus pacientes em recuperação um traço comum: eles dizem a verdade, até a verdade que envergonha. Não é virtude de cartilha. É terapia — a honestidade regula a balança e reconstrói o que o vício isolou.",
  "cards":[
      {"ic":"eye","t":"A Verdade Que Cura","emph":"Verdade","b":"Tirar da sombra o que se esconde e contar a alguém mata a solidão na hora. Confessar expõe o fracasso, sim, mas constrói uma ponte de responsabilidade e de pertencimento — e <strong>ajuda o próprio cérebro a desarmar o medo e a vergonha que sustentam o uso</strong>. Dizer a verdade dói menos do que guardá-la.","tip":"<strong>Prática:</strong> a verdade tem gosto de fel na hora de sair, mas acalma o pulso como um remédio ao fim do dia."},
      {"ic":"link","t":"Assumir A Própria História","emph":"Autoria","b":"Dizer 'eu menti, eu fugi, a culpa foi minha', sem o discurso de coitado, desata nós de anos. Largar o papel de vítima das circunstâncias e <strong>reconhecer a própria assinatura em cada erro devolve à pessoa o leme da própria vida</strong>. Quem se diz só vítima entrega a direção a outra pessoa.","tip":"<strong>Como aplicar:</strong> a recuperação começa de fato quando você para de terceirizar a culpa e assume a autoria do que fez."},
      {"ic":"gap","t":"As Duas Mentiras Confortáveis","emph":"Mentiras","b":"Há dois jeitos de fugir da verdade. Um é o álibi: pôr tudo na conta do 'sistema' ou da 'criança ferida', e ficar passivo no mesmo buraco. O outro é a confissão-espetáculo — <strong>transformar a própria dor em show para arrancar pena ou aplauso</strong>, o que apenas realimenta a encenação. Verdade não é nem desculpa nem palco.","tip":"<strong>Sinal de alerta:</strong> o perdão que pula a sinceridade íntima derruba a ponte exatamente onde o outro ia te reencontrar.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["A honestidade radical regula a balança e reconstrói a conexão que o vício corrói.","A mentira alivia na hora e adoece depois; a verdade dói e cura.","Assumir a autoria dos próprios atos — em vez do papel de vítima — é o que recupera."]},

 {"slug":"ch09-vergonha-equilibrio","sub":"CAPÍTULO 9: Vergonha Prossocial e o Equilíbrio",
  "intro":"A vergonha tem duas caras: uma tranca a pessoa no poço, a outra a traz de volta ao grupo. E aqui o livro se fecha com a sua única promessa honesta — a meta não é abolir o prazer nem mergulhar na dor, é aprender a equilibrar a balança.",
  "cards":[
      {"ic":"pivot","t":"Vergonha Que Tranca, Vergonha Que Liga","emph":"Vergonha","b":"'Eu sou um lixo' tranca a porta do poço por dentro — a vergonha destrutiva isola, e o isolamento alimenta o uso. Já 'eu fiz algo errado e magoei os meus' abre os olhos, chora o erro e <strong>move a pessoa a reparar e voltar para o grupo</strong>. A primeira condena quem você é; a segunda corrige o que você fez.","tip":"<strong>Como aplicar:</strong> você não é uma pessoa estragada; é uma pessoa falha — e gente falha tem como refazer os próprios passos."},
      {"ic":"scale","t":"Sentar-se No Meio Da Balança","emph":"Equilíbrio","b":"A vitória não é virar um monge anestesiado, longe de toda alegria. É viver na faixa do meio: provar o prazer <strong>sabendo da conta que ele cobra amanhã, e suportar a dor confiando no quinhão de paz que vem depois</strong>. Não se trata de travar a balança — e sim de aprender, enfim, a sentar-se sereno bem no centro dela.","tip":"<strong>Modelo mental:</strong> o objetivo nunca foi parar de oscilar. Foi parar de ser arremessado pela oscilação."},
      {"ic":"gap","t":"A Vergonha Como Vício","emph":"Recaída","b":"Ruminar a vergonha inútil até o enjoo pede, no fim, a mesma anestesia que abriu o buraco. Ajoelhado no escuro, sem ninguém por perto para devolver a perspectiva, <strong>o juiz interno vira uma máquina de autodestruição que nunca desliga</strong> — e o remorso só serve de desculpa para a próxima dose.","tip":"<strong>Sinal de alerta:</strong> quando o arrependimento vira pretexto para afundar de novo na velha dor, a vergonha já é só mais um vício, agora bem disfarçado.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["A vergonha destrutiva isola e afunda; a prossocial reconecta e repara.","Regras claras somadas à comunidade convertem a vergonha em mudança real.","A meta é o equilíbrio da balança — sentar-se no meio, não caçar o pico."]},
]
