# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'Não Me Faça Pensar'
(Steve Krug — Don't Make Me Think: A Common Sense Approach to Web Usability).
Frameworks canônicos: a 1ª Lei de Krug ('não me faça pensar' / auto-evidência);
como realmente usamos a web (escanear, satisficing/satisfazer, muddling
through/se virar); design para escaneabilidade (billboard design 101 —
convenções, hierarquia visual, áreas claras, clicável óbvio, eliminar ruído);
'omita as palavras desnecessárias' (corte metade, depois metade do resto;
happy talk); navegação persistente (Site ID, seções, 'você está aqui', busca);
o teste do tronco (trunk test); a página inicial e o mito da home perfeita;
o mito do usuário médio e o teste de usabilidade barato (3 usuários, uma manhã
por mês, pensar em voz alta); a reserva de boa vontade (reservoir of goodwill);
acessibilidade e design para celular. Base: síntese dos frameworks amplamente
documentados — não reproduz o texto."""

BOOK = {
 "title": "Não Me Faça Pensar",
 "author": "Steve Krug",
 "header_light": "NÃO ME",
 "header_bold": "FAÇA PENSAR",
 "subtitle": "VISÃO GERAL · USABILIDADE E O BOM SENSO NA WEB",
 "intro": "Todo o livro cabe num resmungo do usuário: 'não me faça pensar'. Quando uma página exige que você pare e raciocine para descobrir onde clicar, ela já falhou — porque ninguém vai ao seu site para resolver enigmas. Krug não escreve um tratado; ele aponta o óbvio que os designers teimam em ignorar: as pessoas não leem, escaneiam; não buscam a melhor opção, pegam a primeira que serve; não entendem o sistema, se viram no improviso. Usabilidade não é um departamento de doutorado — é bom senso, e bom senso se prova com três pessoas e uma manhã de teste, não com três horas de reunião.",
 "description": "O livro de usabilidade mais lido do mundo, e de propósito o mais fino: Steve Krug parte do princípio de que ninguém tem tempo nem paciência para a sua interface. Daí as regras de bom senso — descarregue o cérebro do usuário, respeite as convenções que ele já conhece, deixe gritantemente óbvio o que é clicável, corte metade das palavras (e depois metade do resto) e ofereça uma navegação que responda sempre 'onde estou?' e 'como volto?'. Krug fura o mito do 'usuário médio' (ele não existe) e o da home que agrada a todos (ela não comunica nada), e mostra que o teste barato — três usuários, uma manhã por mês, pensando em voz alta — vale mais que semanas de opinião. Por baixo de tudo, a reserva de boa vontade: cada atrito esvazia, cada gentileza reabastece, e o usuário que seca vai embora sem reclamar.",
 "tags": ["Usabilidade", "UX", "Web"],
 "progress": "10 Capítulos",
 "cover": "assets/nao-me-faca-pensar-cover.png",
 "overview_cards": [
   {"ic":"bulb","t":"A 1ª Lei: \"Não Me Faça Pensar\"","b":"A regra que governa todas as outras: cada página tem de ser <strong>auto-evidente</strong> — entendida no ato, sem deliberar. Cada <strong>'ponto de interrogação' que brota na cabeça</strong> do usuário ('isto é clicável?', 'onde estou?', 'por onde começo?') é um pedágio cobrado da paciência dele. A escala é simples: auto-evidente (ideal) > autoexplicativo (passa) > confuso (proibido).","tip":"<strong>Como aplicar:</strong> olhe cada tela e pergunte 'o que aqui faz alguém hesitar?'. Toda hesitação é um defeito esperando conserto.","wide":True},
   {"ic":"eye","t":"Como REALMENTE Usamos a Web","b":"Você projeta para um leitor atento e paciente; ele não existe. O usuário de verdade <strong>escaneia</strong> (não lê), <strong>se satisfaz</strong> (clica na primeira opção razoável, não na melhor — <em>satisficing</em>) e <strong>se vira</strong> (usa sem nunca entender como aquilo funciona — <em>muddling through</em>).","tip":"<strong>Modelo mental:</strong> sua página não é um livro lido na poltrona — é um outdoor visto a 100 km/h. Faça a ação certa saltar e torne o resto à prova de tropeço.","wide":True},
   {"ic":"target","t":"Teste Barato, e a Boa Vontade","b":"O 'usuário médio' é uma desculpa para vencer discussões — ele não existe. Pare de adivinhar e teste: <strong>3 usuários, uma manhã por mês</strong>, pensando em voz alta. E nunca esqueça a <strong>reserva de boa vontade</strong>: o usuário chega com um tanque de paciência que cada atrito esvazia e cada cortesia reabastece.","tip":"<strong>Regra:</strong> uma manhã olhando alguém usar o site vale mais que um mês defendendo o que você acha que ele faria."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-nao-me-faca-pensar","sub":"CAPÍTULO 1: Não Me Faça Pensar (a 1ª Lei)",
  "intro":"A primeira — e mais importante — lei de Krug cabe num pedido cansado do usuário: 'não me faça pensar'. Página, botão, link: tudo deve ser óbvio a ponto de dispensar reflexão. No instante em que alguém para para descobrir como uma coisa funciona, você já cobrou um esforço que não devia, e já o perdeu um pouquinho. Multiplique esse pouquinho por cada tela e você perdeu o usuário inteiro.",
  "cards":[
      {"ic":"target","t":"A Regra Zero da Web","emph":"Regra Zero","b":"Ninguém abre o seu site para ter o prazer de decifrá-lo. Cada vez que você obriga o usuário a parar e calcular ('onde clico para ver o preço? isto leva aonde?'), você gastou um pouco da boa vontade dele em algo que não interessava a ninguém. <strong>Se a sua tela exige raciocínio para ser usada, ela falhou como design</strong> — por mais elegante que pareça na sua tela.","tip":"<strong>Modelo mental:</strong> todo segundo gasto entendendo a navegação é um segundo que o usuário não passou querendo o que você oferece."},
      {"ic":"eye","t":"O Olhar Desatento","emph":"Desatento","b":"Você acha que ele vai admirar a página; ele vai passar voando. Não lê seu texto de boas-vindas, não estuda o menu, não pondera as opções: <strong>bate o olho e clica no primeiro item que parece, mais ou menos, levar ao que ele quer</strong>. Projetar para o leitor cuidadoso é projetar para um fantasma — o usuário real está com pressa e meio distraído.","tip":"<strong>Prática:</strong> diga o essencial em alto e bom som — hierarquia visual forte, palavras que saltam — e poupe a prosa bonita para outro lugar."},
      {"ic":"gap","t":"O Risco da Metáfora","emph":"Metáfora","b":"Batizar o carrinho de 'Sua Cestinha Mágica' e o contato de 'Fale com a Tribo' rende risadas na reunião criativa e travadas na cabeça do visitante. Na web, o familiar é cortesia: o nome de sempre é entendido sem esforço. <strong>Trocar a convenção sólida por uma graça original é cobrar pedágio onde devia haver passagem livre</strong>.","tip":"<strong>Armadilha:</strong> diante de 'criativo mas confuso' ou 'óbvio mas batido', o usuário escolhe o óbvio toda vez. Reinvente o produto, não os rótulos.","warn":True},
    ],
  "lessons_title":"Lições-Chave: A 1ª Lei",
  "lessons":["Persiga o auto-evidente: todo ponto de interrogação na cabeça do usuário é um defeito a eliminar.","Prefira o rótulo banal que se entende de imediato ao nome esperto que precisa ser decifrado.","Tirar peso da cabeça do usuário é a meta nº 1 de toda interface — todo o resto vem depois."]},

 {"slug":"ch02-como-usamos-a-web","sub":"CAPÍTULO 2: Como Realmente Usamos a Web",
  "intro":"Você imagina um usuário atento, que lê a página de cima a baixo e pondera a melhor opção. Sinto informar: ele é o oposto disso. O usuário real escaneia em vez de ler, agarra a primeira opção que parece servir em vez da melhor, e usa o site sem nunca entender como ele funciona. Não dá para mudar isso — então o bom design começa por aceitar esses três fatos teimosos.",
  "cards":[
      {"ic":"eye","t":"Não Lemos — Escaneamos","emph":"Escaneamos","b":"O olho do usuário <strong>varre a página atrás de palavras-âncora</strong> que casem com o que ele quer, pulando todo o resto. Aquele texto caprichado que você escreveu? Ele nem viu. Desenhar para o leitor que lê tudo com calma é desenhar para alguém que fechou a aba há muito tempo.","tip":"<strong>Como aplicar:</strong> trabalhe a hierarquia visual e ponha as palavras-chave em destaque — projete para o relance, não para a leitura.","wide":True},
      {"ic":"fork","t":"Satisficing (Satisfazer)","emph":"Satisficing","b":"O usuário não procura a melhor opção; pega <strong>a primeira que parece dar conta</strong> e clica (Herbert Simon juntou <em>satisfy</em> + <em>suffice</em>). Por que se daria ao trabalho de otimizar? Caçar a opção ótima cansa, errar quase não custa (é só voltar) — e, convenhamos, chutar é meio divertido.","tip":"<strong>Regra:</strong> não esconda a opção certa esperando que ele a descubra. Faça-a a mais visível — porque ele vai no primeiro 'serve', não no melhor."},
      {"ic":"wave","t":"Muddling Through (Se Virar)","emph":"Muddling Through","b":"O usuário <strong>usa as coisas sem fazer ideia de como funcionam</strong>; se está funcionando 'mais ou menos', ele segue feliz e nunca procura o jeito 'certo'. Apostar que ele vai 'parar e aprender o sistema' é apostar contra a natureza humana — e perder.","tip":"<strong>Cuidado:</strong> uma interface que quebra quando o usuário improvisa pune justamente o comportamento que toda pessoa tem.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Como Usamos a Web",
  "lessons":["Projete para quem escaneia, se contenta e improvisa — não para o leitor ideal que mora só na sua cabeça.","Como ele clica na primeira opção razoável, faça a opção certa ser a que mais salta aos olhos.","Como ele vive de improviso, deixe tudo à prova de erro e fácil de desfazer."]},

 {"slug":"ch03-design-escaneabilidade","sub":"CAPÍTULO 3: Design para Escaneabilidade (Billboard 101)",
  "intro":"Já que o usuário escaneia, a página tem de ser feita para ser escaneada — é o que Krug chama, com humor, de billboard design 101: o curso básico de outdoor. São cinco movimentos: aproveitar as convenções que ele já conhece, montar uma hierarquia visual clara, dividir a página em áreas óbvias, deixar gritante o que é clicável e calar o ruído. Nada de gênio — só caprichar no óbvio.",
  "cards":[
      {"ic":"layers","t":"Os 5 Movimentos do Billboard 101","emph":"Billboard 101","b":"Desenhe a página como quem desenha um outdoor para ser lido a 100 km/h: <strong>1) aproveite as convenções</strong> (logo no canto superior esquerdo, carrinho à direita); <strong>2) monte a hierarquia visual</strong> (o importante grande e à frente, o que é parente fica junto); <strong>3) recorte áreas claras</strong>; <strong>4) deixe o clicável escandalosamente clicável</strong>; <strong>5) cale o ruído</strong>.","tip":"<strong>Como aplicar:</strong> faça a aparência espelhar a estrutura — o olho deve 'ler' a organização da página antes de ler uma só palavra.","wide":True},
      {"ic":"book","t":"Convenções > Inovação","emph":"Convenções","b":"As convenções são processadas <strong>sem gastar um grama de atenção</strong>, porque o usuário já as aprendeu em mil sites antes do seu. Reinventá-las é obrigá-lo a aprender de novo o que já sabia. Só vale inovar quando a sua ideia é claramente melhor e fica tão óbvia quanto o padrão que substituiu.","tip":"<strong>Modelo mental:</strong> convenções são vocabulário compartilhado — usá-las é falar a língua do usuário em vez de inventar um dialeto só seu."},
      {"ic":"spark","t":"Eliminar o Ruído (Noise)","emph":"Ruído","b":"Banner piscando, animação girando, cinco cores brigando por atenção: tudo isso <strong>afoga aquilo que o usuário veio buscar</strong>. O ruído tem três sabores — o barulho de fundo, a bagunça e a tagarelice visual — e cada enfeite a mais é um pedaço de atenção a menos para o que importa.","tip":"<strong>Cuidado:</strong> quando tudo tem o mesmo tamanho e o mesmo peso, nada se destaca — e o usuário fica parado, sem saber por onde começar.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Escaneabilidade",
  "lessons":["Fale a língua das convenções; só invente a sua quando a alternativa for nitidamente melhor e igualmente óbvia.","Faça a aparência contar a estrutura: o importante grande e à frente, o aparentado agrupado.","Deixe o clicável obviamente clicável — e corte o ruído visual sem dó nem saudade."]},

 {"slug":"ch04-omita-palavras","sub":"CAPÍTULO 4: Omita as Palavras Desnecessárias",
  "intro":"A terceira lei de Krug é a mais divertida de obedecer: 'omita as palavras desnecessárias'. E ele leva a sério — corte metade das palavras de cada página, depois corte metade do que sobrou. Soa cruel, mas funciona: texto enxuto baixa o ruído, destaca o que presta e encurta a página, de modo que o usuário pensa menos, rola menos e acha mais rápido.",
  "cards":[
      {"ic":"steps","t":"A 3ª Lei: Corte pela Metade, Duas Vezes","emph":"Corte pela Metade","b":"Krug pega a velha regra de Strunk & White e turbina: <strong>'jogue fora metade das palavras de cada página — e depois jogue fora metade do que restou'</strong>. Parece exagero até você tentar: quase toda página aguenta o corte perdendo só gordura, nunca conteúdo.","tip":"<strong>Como aplicar:</strong> vire um editor sem coração — cada palavra paga aluguel justificando a própria presença, ou rua com ela."},
      {"ic":"bubble","t":"Mate o Happy Talk","emph":"Happy Talk","b":"O <strong>'blá-blá feliz'</strong> — aquele 'Seja muito bem-vindo ao nosso site! É com enorme satisfação que...' — não informa nada e ainda ocupa o lugar mais nobre da página. É conversa de elevador impressa na vitrine. Não encolha: apague.","tip":"<strong>Regra:</strong> se um trecho não ajuda o usuário a fazer o que veio fazer, ele é forte candidato à lata do lixo."},
      {"ic":"gap","t":"Instruções São um Sintoma","emph":"Sintoma","b":"Quase ninguém lê instrução — o usuário pula direto para o botão. Então não explique: <strong>torne a coisa tão óbvia que a explicação fique sobrando</strong>. O pouco que ainda precisar dizer, diga no ponto exato em que ele age, no mínimo de palavras.","tip":"<strong>Cuidado:</strong> precisar escrever um manual ao lado de um campo é o design confessando que ainda não está óbvio o bastante.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Omitir Palavras",
  "lessons":["Corte metade das palavras — e depois metade do que sobrou.","Apague todo o happy talk e a quase totalidade das instruções.","Texto enxuto é menos ruído, mais foco no essencial e página que termina antes de cansar."]},

 {"slug":"ch05-navegacao-persistente","sub":"CAPÍTULO 5: Navegação Persistente",
  "intro":"Numa loja você sente onde está: vê a porta, as prateleiras, a saída. Na web não existe esse 'lugar' — e a navegação é a única coisa que o substitui, fazendo as vezes das paredes e das placas. Por isso ela tem de aparecer em toda página (daí 'persistente') e responder na hora às perguntas que o usuário nem chega a formular: onde estou? o que tem aqui? como busco? como volto ao começo?",
  "cards":[
      {"ic":"pin","t":"O \"Billboard de Navegação\"","emph":"Billboard de Navegação","b":"Existe um núcleo que precisa reaparecer, igualzinho, em toda página: <strong>Site ID</strong> (o logo no topo, clicável, que leva à home), <strong>Seções</strong> (a navegação principal), <strong>'você está aqui'</strong> (a seção atual em destaque), <strong>Busca</strong> (uma caixa simples, sempre no mesmo canto) e os atalhos de serviço. Sempre os mesmos, sempre onde o usuário já espera.","tip":"<strong>Como aplicar:</strong> repita esse núcleo idêntico e no mesmo lugar em cada página — surpresa, aqui, é defeito.","wide":True},
      {"ic":"pin","t":"Sempre Marque \"Você Está Aqui\"","emph":"Você Está Aqui","b":"O usuário quase nunca <strong>entra pela porta da frente</strong>: ele cai fundo no site, vindo de um link do Google. Logo, precisa conseguir se localizar de onde quer que tenha aterrissado. O 'você está aqui' (a seção do momento acesa) e o caminho de migalhas respondem, num relance, à pergunta 'afinal, onde foi que eu parei?'.","tip":"<strong>Modelo mental:</strong> pense no mapa do shopping com a bolinha vermelha de 'você está aqui' — sempre no mesmo ponto, sempre pronto a te situar."},
      {"ic":"link","t":"O Logo Leva à Home","emph":"Logo","b":"Convenção sagrada: clicar no <strong>logo volta ao início</strong> — é o botão de pânico do usuário perdido. Quebrá-la (ou trocar a navegação de página para página, ou esconder a busca atrás de filtros) é tirar o chão de quem já estava se virando no improviso.","tip":"<strong>Cuidado:</strong> navegação que muda de cara a cada página destrói a persistência — e, com ela, o usuário.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Navegação Persistente",
  "lessons":["Repita o núcleo da navegação em toda página: logo, seções, 'você está aqui', busca e atalho à home.","Marque sempre o 'você está aqui' — o usuário entra por qualquer porta, raramente pela da frente.","O logo no topo leva à home; a busca é simples e mora sempre no mesmo lugar."]},

 {"slug":"ch06-teste-do-tronco","sub":"CAPÍTULO 6: O Teste do Tronco (Trunk Test)",
  "intro":"O teste do tronco é o jeito mais barato e brutal de auditar sua navegação. Imagine que te vendaram, te jogaram no porta-malas (o 'tronco' do carro) e te largaram numa página interna qualquer, lá no fundo do site. Você abre os olhos sem saber como chegou ali. Pergunta: dá para se localizar em segundos, sem entrar em pânico? Se dá, a navegação passou. Se você fica girando, ela falhou.",
  "cards":[
      {"ic":"lens","t":"As 6 Perguntas do Trunk Test","emph":"Trunk Test","b":"Pegue uma página interna qualquer, arrancada do contexto, e responda na lata: <strong>1)</strong> que site é este? (o logo) <strong>2)</strong> em que página eu caí? (o título) <strong>3)</strong> quais são as seções principais? <strong>4)</strong> que opções tenho neste nível? <strong>5)</strong> onde estou na árvore? (o 'você está aqui') <strong>6)</strong> como faço uma busca? Seis perguntas, segundos para cada — e nenhuma desculpa.","tip":"<strong>Como aplicar:</strong> abra uma página funda fora de contexto e cronometre os 6 itens. É o veredito mais honesto e mais barato que o seu site vai receber.","wide":True},
      {"ic":"key","t":"Cada Página É uma Porta de Entrada","emph":"Porta de Entrada","b":"A maioria das pessoas <strong>nunca passou pela sua home</strong> — caiu direto numa página interna, vinda do Google ou de um link compartilhado. Conclusão incômoda: toda página precisa <strong>se sustentar sozinha</strong> e responder às perguntas-âncora sem contar com nada que veio antes dela.","tip":"<strong>Modelo mental:</strong> pare de desenhar 'a jornada a partir da home'. Desenhe cada página como se fosse a primeira que o usuário vê — porque, para muitos, é."},
      {"ic":"gap","t":"Páginas Internas Sem Título","emph":"Sem Título","b":"Sem um <strong>título claro e em destaque</strong> — que bata com o link que foi clicado e com o item aceso na navegação —, o usuário não sabe onde aterrissou nem como subir um andar. É a reprovação mais comum (e mais boba) no teste do tronco.","tip":"<strong>Cuidado:</strong> navegação que só faz sentido 'para quem veio da home' abandona justamente quem chega pelo meio — ou seja, quase todo mundo.","warn":True},
    ],
  "lessons_title":"Lições-Chave: O Teste do Tronco",
  "lessons":["Aplique o teste do tronco a páginas internas profundas, sempre fora de contexto.","Toda página deve responder sozinha: que site, que página, quais seções, quais opções, onde estou e como busco.","O usuário entra 'pelo meio' — trate cada página como uma porta de entrada que se vira por conta própria."]},

 {"slug":"ch07-pagina-inicial","sub":"CAPÍTULO 7: A Página Inicial (Home)",
  "intro":"A home é a página mais disputada e mais sofrida do site: todo departamento quer um pedaço dela, e ainda assim ela precisa dizer quem você é, qual a sua missão, mostrar a hierarquia inteira e oferecer atalhos e busca. O erro clássico é querer agradar a todos. A home tem uma só obrigação inegociável: em poucos segundos, deixar claro o que é o site e por que alguém deveria se importar.",
  "cards":[
      {"ic":"target","t":"Vença o \"Big Honkin' Question\"","emph":"Question","b":"Há uma pergunta enorme pairando sobre todo visitante novo: <strong>'afinal, que site é este?'</strong>. Nunca o deixe sem resposta. No espaço nobre, o que aparece antes de rolar, entregue uma <strong>frase de valor concreta</strong> — o que é isto e por que eu deveria me importar — e não mais um 'blá-blá feliz' genérico.","tip":"<strong>Como aplicar:</strong> troque o vago 'Inovação que transforma vidas' pelo claro 'Agenda online para clínicas — menos faltas, mais consultas'. Um diz tudo; o outro, nada.","wide":True},
      {"ic":"scale","t":"As Tarefas que a Home Equilibra","emph":"Home Equilibra","b":"A home faz malabarismo: ao mesmo tempo precisa entregar <strong>identidade e missão</strong>, <strong>a hierarquia do site</strong> (as seções), <strong>a busca</strong>, <strong>o conteúdo em destaque e os atalhos</strong> e ainda <strong>o registro/login</strong>. Como nem tudo cabe no espaço nobre, alguém vai ter de ceder — e priorizar é o seu trabalho, não o do usuário.","tip":"<strong>Modelo mental:</strong> a home é a fachada com a vitrine: num relance ela diz o que a loja vende e convida você a entrar."},
      {"ic":"mask","t":"O Mito da Home Perfeita","emph":"Home Perfeita","b":"Tentar acomodar <strong>a prioridade de cada chefe de cada setor</strong> transforma a home num mural de cartazes que, no fim, não diz o que o site é. A tal 'home perfeita' que contenta todo mundo é, na prática, uma home que não comunica nada a ninguém.","tip":"<strong>Cuidado:</strong> cada departamento pendurando o próprio banner é a receita mais rápida para uma home que vira ruído de cima a baixo.","warn":True},
    ],
  "lessons_title":"Lições-Chave: A Página Inicial",
  "lessons":["A home tem de responder, no espaço nobre, 'o que é isto e por que me importar?' — numa frase de valor concreta.","Largue o sonho da home perfeita que agrada a todos: escolha a missão central e assuma os trade-offs.","Troque o blá-blá feliz e o mural de banners por identidade, valor, seções e busca."]},

 {"slug":"ch08-teste-de-usabilidade","sub":"CAPÍTULO 8: Teste de Usabilidade Barato",
  "intro":"As discussões de equipe sobre design são eternas por um motivo simples: cada um projeta para si mesmo e, na hora do impasse, saca a carta do 'usuário médio' — uma figura que não existe e por isso dá razão a quem a invoca. Krug oferece a saída: pare de discutir e teste. Um teste de usabilidade barato, simples e feito com frequência troca opinião por evidência — e encerra o debate em uma manhã.",
  "cards":[
      {"ic":"target","t":"A Fórmula do Teste Barato","emph":"Teste Barato","b":"<strong>Quantos:</strong> uns 3 usuários por rodada já desentocam os piores problemas. <strong>Quando:</strong> comece cedo e repita — <strong>uma manhã por mês</strong> basta. <strong>Como:</strong> dê tarefas de verdade, peça que a pessoa <strong>pense em voz alta</strong> (<em>think aloud</em>) e fique calado, só observando — sem socorrer, sem cutucar, sem 'ajudar'.","tip":"<strong>Como aplicar:</strong> debata os achados no mesmo dia e conserte só os problemas mais graves primeiro. Resista à tentação de querer arrumar tudo de uma vez.","wide":True},
      {"ic":"gap","t":"O Mito do \"Usuário Médio\"","emph":"Usuário Médio","b":"O 'usuário médio' é uma lenda urbana das reuniões: todo usuário é único e o uso é, no fundo, imprevisível. Quando alguém o invoca, <strong>está apoiando o próprio palpite numa pessoa que nunca existiu</strong> — e o palpite do chefe costuma vencer só porque é do chefe.","tip":"<strong>Sinal de alerta:</strong> assim que ouvir 'o usuário médio vai entender', pare a discussão e marque um teste. Esse é o momento exato.","warn":True},
      {"ic":"lens","t":"Testar para Achar, não para Provar","emph":"Achar, não para Provar","b":"Esqueça rigor estatístico e amostra científica: o objetivo é <strong>achar problema para consertar</strong>, não publicar um paper. Teste qualitativo, caseiro, faça-você-mesmo — e lembre que <strong>pouco e frequente vence muito e raro</strong>. Cada rodada troca horas de achismo por minutos de prova.","tip":"<strong>Modelo mental:</strong> testar é acender a luz no quarto escuro — de repente você para de tropeçar nas coisas que não enxergava."},
    ],
  "lessons_title":"Lições-Chave: Teste de Usabilidade",
  "lessons":["O usuário médio não existe — não ganhe discussões invocando-o; ganhe testando.","Teste cedo e sempre: uns 3 usuários, uma manhã por mês, pensando em voz alta.","Observe calado, debata no mesmo dia e conserte primeiro só os problemas mais graves."]},

 {"slug":"ch09-boa-vontade","sub":"CAPÍTULO 9: A Reserva de Boa Vontade",
  "intro":"Todo visitante chega com um tanque de paciência — Krug chama de reserva de boa vontade. Não é infinito. Cada atrito, obstáculo ou pequena falta de respeito drena um pouco; cada gentileza e facilidade devolve um pouco. E há um detalhe cruel: o tanque pode secar no silêncio. Esvaziado, o usuário simplesmente vai embora — sem reclamar, sem avisar, e sem voltar — mesmo que, tecnicamente, o site 'funcione'.",
  "cards":[
      {"ic":"scale","t":"A Paciência É um Tanque Finito","emph":"Tanque Finito","b":"A boa vontade começa razoavelmente cheia e vaza a cada frustração. O perigo não é o problema grande e óbvio — é a <strong>soma de mil aborrecimentos pequenos</strong>, cada um 'insignificante demais para reclamar', pingando até o tanque secar e o usuário desistir <strong>sem dizer nada a ninguém</strong>.","tip":"<strong>Como aplicar:</strong> a cada coisa que você pede ao usuário, pergunte 'isto enche ou esvazia o tanque?'. Trate-o como convidado em casa, não como suspeito na portaria.","wide":True},
      {"ic":"sword","t":"O Que ESVAZIA o Reservatório","emph":"ESVAZIA","b":"O tanque vaza quando você: <strong>esconde o que o usuário foi buscar</strong> (preço, contato, suporte); <strong>o pune por não fazer 'do seu jeitinho'</strong> (recusar o telefone porque ele pôs parênteses); <strong>pede dados que não precisa</strong>; empurra para ele um trabalho que era seu; e ainda exibe um visual amador que cheira a desleixo.","tip":"<strong>Cuidado:</strong> esconder o preço para 'capturar o lead' não captura nada — esvazia o tanque na hora e manda o usuário para o concorrente.","warn":True},
      {"ic":"leaf","t":"O Que REABASTECE","emph":"REABASTECE","b":"O tanque enche quando você: <strong>diz com clareza o que ele quer saber</strong> (frete, prazo, disponibilidade); <strong>poupa passos</strong> e só pede o estritamente necessário; <strong>antecipa a dúvida</strong> colocando a ajuda no exato ponto de uso; e capricha nos detalhes e na cortesia, como quem recebe alguém em casa.","tip":"<strong>Modelo mental:</strong> hospitalidade enche o tanque, grosseria seca. Trate o usuário do jeito que você gostaria de ser tratado num site alheio."},
    ],
  "lessons_title":"Lições-Chave: A Boa Vontade",
  "lessons":["A paciência do usuário é um tanque finito: cada atrito drena, cada cortesia reabastece — e ele esvazia em silêncio.","Não esconda o que ele procura, não peça o que não precisa e não jogue nas costas dele o trabalho que era seu.","Antecipe dúvidas, poupe passos e capriche nos detalhes — é a soma das pequenas gentilezas que segura o usuário."]},

 {"slug":"ch10-acessibilidade-mobile","sub":"CAPÍTULO 10: Acessibilidade e Mobile",
  "intro":"Usabilidade vale para todo mundo e em todo contexto — não só para o usuário ideal num desktop tranquilo. Acessibilidade não é caridade nem mero cumprimento de lei: é fazer o site funcionar para quem tem alguma deficiência, e o melhor é que isso quase sempre melhora a vida de todos os outros junto. E no celular — tela minúscula, dedo grosso, atenção pela metade — a 1ª Lei não relaxa: ela aperta.",
  "cards":[
      {"ic":"key","t":"Acessibilidade É Usabilidade Estendida","emph":"Usabilidade Estendida","b":"Os consertos mais comuns são <strong>baratos e beneficiam todo mundo</strong> — a maré que sobe levanta todos os barcos: <strong>texto alternativo</strong> nas imagens que informam, <strong>rótulos</strong> nos campos do formulário, <strong>contraste e fonte</strong> legíveis, <strong>navegação por teclado</strong> e uma ordem semântica que faça sentido. Não é um favor a poucos; é qualidade para muitos.","tip":"<strong>Como aplicar:</strong> nunca passe informação só pela cor ('os campos em vermelho são obrigatórios') — para o daltônico, essa frase simplesmente não existe.","wide":True},
      {"ic":"wave","t":"Mobile É o Stress Test da 1ª Lei","emph":"Stress Test","b":"Celular <strong>não é desktop encolhido</strong>: é outro bicho — tela pequena, dedo impreciso, gente usando no ônibus, na fila, distraída. Corte para o essencial, use <strong>alvos de toque grandes e bem espaçados</strong> e exija ainda menos raciocínio. O que passa no mobile distraído passa em qualquer lugar.","tip":"<strong>Modelo mental:</strong> acessibilidade é a rampa da calçada — feita para a cadeira de rodas, mas que socorre o carrinho de bebê, a mala e a sua perna torcida também."},
      {"ic":"clock","t":"Usabilidade × Aprendabilidade (Learnability)","emph":"Aprendabilidade","b":"O mobile vive escondendo comandos atrás de gestos e ícones mudos. Tudo bem sacrificar um tiquinho de clareza imediata se o usuário <strong>aprende o truque rápido e nunca mais esquece</strong> — mas não vire fã do obscuro: um gesto importante sem nenhuma pista visível tem aprendizado zero, ou seja, ninguém descobre.","tip":"<strong>Cuidado:</strong> enterrar ações importantes sob ícones ambíguos é apostar que o usuário vai adivinhar — e ele não vai.","warn":True},
    ],
  "lessons_title":"Lições-Chave: Acessibilidade e Mobile",
  "lessons":["Acessibilidade é usabilidade para todos — comece pelo barato e de alto impacto: texto alternativo, rótulos, contraste e teclado.","Nunca confie a informação só à cor; garanta estrutura semântica e navegação por teclado.","Mobile não é desktop encolhido: corte para o essencial, use alvos de toque grandes e peça ainda menos pensamento."]},
]
