# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'O Idiota' (Fiódor Dostoiévski)."""

BOOK = {
  "title": "O Idiota",
  "author": "Fiódor Dostoiévski",
  "header_light": "O",
  "header_bold": "IDIOTA",
  "subtitle": "VISÃO GERAL · O HOMEM BOM DEMAIS PARA ESTE MUNDO",
  "intro": "E se um homem fosse <em>realmente</em> bom — sem máscara, sem cálculo, sem o pequeno egoísmo de todos nós? Dostoiévski tentou escrevê-lo: o príncipe Míchkin, epiléptico, manso, que perdoa antes de ser ofendido. E descobriu uma coisa terrível. Solto em Petersburgo, capital do dinheiro e da vaidade, esse santo não converte ninguém — é idolatrado, explorado e por fim destruído, arrastando para o abismo justamente quem mais quis salvar. 'A beleza salvará o mundo', diz ele. O romance inteiro é a pergunta cruel que não responde: <em>e se não salvar?</em>",
  "description": "O romance em que Dostoiévski apostou tudo num homem 'positivamente belo' — bondade pura jogada num mundo cínico. Míchkin como Cristo que não redime; Nastássia Filíppovna, a beleza ferida que se recusa a ser salva; Rogójin, a paixão que possui e mata; 'a beleza salvará o mundo' como tese sob ataque; o Cristo morto de Holbein, diante do qual se pode perder a fé; a epilepsia e o êxtase de um segundo que vale uma vida; compaixão × paixão; e a estrutura circular que devolve o santo ao manicômio de onde veio.",
  "tags": ["Literatura Clássica", "Filosofia", "Psicologia"],
  "progress": "9 Capítulos",
  "cover": "assets/o-idiota-cover.png",
  "overview_cards": [
    {"ic":"person","t":"O Idiota É o Mundo, Não Ele","b":"Míchkin chega de mãos limpas: não mente, não inveja, não cobra. E o salão inteiro decide que ele é <strong>um pobre idiota</strong> — porque candura sem cálculo, para gente que só calcula, soa a burrice. O título é a maior ironia do livro: <strong>quem o chama de idiota está confessando o próprio cinismo</strong>. A medida não é a inteligência do herói; é a podridão da plateia.","tip":"<strong>Para o leitor:</strong> repare no seu próprio incômodo com Míchkin. Esse desconforto não diz que ele é bobo — diz quanto de Petersburgo já mora em você."},
    {"ic":"spark","t":"'A Beleza Salvará o Mundo'","b":"A frase mais célebre é também a mais escorregadia: não fala de rosto bonito, fala de <strong>beleza moral</strong> — compaixão, humildade feita carne. Mas no mesmo livro pulsa a outra beleza, a de Nastássia: deslumbrante, ferida, que não salva ninguém — <strong>incendeia</strong>. Tese e contraprova dividem a mesma página. <strong>Beleza sem bondade é campo de batalha; com bondade, talvez salve</strong> — e Dostoiévski recusa-se a prometer.","tip":"<strong>Modelo mental:</strong> não leia a frase como slogan de fé. Leia como aposta arriscada — o romance inteiro é o teste, e o resultado fica em aberto."},
    {"ic":"wave","t":"Dois Homens, o Mesmo Amor","b":"Míchkin ama Nastássia de <strong>piedade</strong> (a mulher humilhada) e Agláia de <strong>amor</strong> (a vida ainda possível). Rogójin ama Nastássia de <strong>fome</strong> — quer tê-la inteira, e se não puder, prefere não vê-la de ninguém. Compaixão e posse não são opostos: são <strong>o mesmo desejo por duas portas</strong>, e Dostoiévski as faz convergir para a mesma faca.","tip":"<strong>Como aplicar:</strong> separe amar de salvar e de possuir. Quando esses três se confundem numa pessoa só, o que parece devoção já é tragédia em marcha."},
    {"ic":"gap","t":"A Bondade Que Não Sabe Magoar","b":"Míchkin não faz mal por maldade — faz por <strong>não conseguir ferir</strong>. Ama duas mulheres, não quer perder nenhuma, e adia. A indecisão de um santo precipita o desastre de todos. É a descoberta mais dura do livro: <strong>bondade sem coragem de cortar não é mais doce que a crueldade — é só mais lenta</strong>.","tip":"<strong>Modelo mental:</strong> não escolher para não magoar é uma escolha — e costuma magoar mais, porque distribui a dor por todos em vez de assumir uma."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-chegada-michkin-sociedade",
    "sub": "CAPÍTULO 1 (Parte I): A Chegada de Míchkin e a Sociedade",
    "intro": "Um homem chega de trem da Suíça com uma trouxa por toda a fortuna e um sorriso que ninguém entende. É o príncipe Míchkin, saído de um sanatório — sem dinheiro, sem máscara, sem a menor noção das regras do jogo que vai jogar. No mesmo vagão, vindo cobrar uma herança e uma mulher, viaja Rogójin, os olhos a arder de paixão por Nastássia Filíppovna. Em poucas horas de viagem está armado tudo: a bondade desarmada e a fome que possui, lado a lado, rumo à mesma cidade e à mesma ruína.",
    "cards": [
      {"ic":"person","t":"A Bondade Como Espelho","emph":"Espelho","b":"Míchkin não esconde nada — e por isso devolve a cada um o próprio rosto. Diante da mesma candura, uns se enternecem, outros zombam, outros já calculam como usá-lo. <strong>A reação a um homem bom é um raio-X de quem reage</strong>: o que você enxerga na bondade dele conta a sua história, não a dele.","tip":"<strong>Para o leitor:</strong> mais que perguntar 'quem é Míchkin?', repare em quem o despreza e quem o ama — é assim que Dostoiévski lhe apresenta o salão inteiro."},
      {"ic":"masks","t":"O Trem Que Já É o Fim","emph":"Trem","b":"Num banco de vagão, compaixão e posse se sentam frente a frente pela primeira vez. Não é encontro casual: é <strong>prólogo do destino</strong>. Míchkin e Rogójin são duplos desde o segundo zero — duas formas de querer a mesma mulher, dois caminhos para o mesmo abismo. <strong>Em Dostoiévski, a primeira página já guarda a última</strong>.","tip":"<strong>Modelo mental:</strong> termine o livro e volte a este trem. O que parecia início inocente era a tragédia inteira em miniatura."},
      {"ic":"key","t":"A Cidade Que Tem Preço Para Tudo","emph":"Preço","b":"Petersburgo funciona a dinheiro, dote e orgulho ferido. Nastássia foi sustentada por Tótski desde menina e agora é leiloada de novo; Gánia a aceitaria por setenta e cinco mil rublos, segurando o nariz. <strong>Míchkin é o único que não põe preço em ninguém</strong> — e num mundo assim, quem não calcula só pode ser idiota. Generosidade, ali, lê-se como incompetência.","tip":"<strong>Como aplicar:</strong> desconfie de qualquer ambiente em que ser bom passa por ser bobo, e ser frio passa por ser esperto. O defeito está no ar, não em quem ainda sente."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["A bondade de Míchkin funciona como espelho: a reação de cada personagem a ele revela quem cada um é por dentro.", "O encontro no trem com Rogójin é o destino já dado — compaixão e posse de partida rumo à mesma mulher.", "Petersburgo precifica gente; Míchkin é o único que não calcula, e por isso o chamam de idiota."],
  },
  {
    "slug": "ch02-noite-nastassia-o-fogo",
    "sub": "CAPÍTULO 2 (Parte I): A Noite de Nastássia e o Fogo",
    "intro": "A cena mais elétrica da obra. No salão de Nastássia Filíppovna, os pretendentes a leiloam com olhares; ela ouve, calada, e então faz o impensável: atira no fogo os cem mil rublos de Rogójin e desafia Gánia a tirá-los das chamas com as próprias mãos. Toda Petersburgo a tratou como mercadoria; agora a mercadoria pega fogo na frente de todos. É menos um gesto de loucura que de justiça — a vítima virando juíza por uma noite.",
    "cards": [
      {"ic":"spark","t":"O Maço no Fogo","emph":"Fogo","b":"Cem mil rublos ardendo na lareira, e a oferta envenenada: pegue, Gánia, se a sua dignidade couber dentro do dinheiro. <strong>A mulher que foi comprada a vida toda compra e queima diante dos compradores</strong> — e cada um, naquele clarão, mostra o tamanho da própria alma. Mas o fogo tem dois rostos: é tribunal da sociedade e, ao mesmo tempo, a beleza ferida ateando fogo a si mesma.","tip":"<strong>Para o leitor:</strong> não veja só revolta. Veja o começo da autodestruição — quem queima o próprio preço muitas vezes está queimando a si junto."},
      {"ic":"wave","t":"A Beleza Que Recusa o Resgate","emph":"Recusa","b":"Nastássia não é só vítima — é vítima que <strong>se castiga</strong>. Quando Míchkin lhe oferece amor e limpeza, ela foge: aceitar a mão dele seria admitir que merece dignidade, e o orgulho ferido não a deixa merecer nada. <strong>Há uma forma de sofrimento que tranca a porta por dentro</strong> — e atira a chave na lareira junto com o dinheiro.","tip":"<strong>Modelo mental:</strong> o orgulho que pune a si mesmo é dos mais cruéis: bloqueia justamente a saída que salvaria. Quem mais precisa de socorro é quem mais o repele."},
      {"ic":"gap","t":"Ser Amada Por Pena","emph":"Pena","b":"Todos põem cifra em Nastássia; só Míchkin a olha como gente. Mas eis o nó trágico: <strong>ser amada por compaixão pode pesar tanto quanto ser comprada</strong>. Quem foi tratada como objeto aprende a desconfiar de toda ternura — e a piedade, por mais limpa, ainda a coloca de joelhos. Míchkin a quer salvar; ela só ouve mais um homem decidindo o seu lugar.","tip":"<strong>Como aplicar:</strong> a quem foi muito instrumentalizado, até o afeto sincero soa a armadilha. Salvar alguém sem rebaixá-lo é a coisa mais difícil que existe."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["O maço de rublos no fogo é tribunal: a comprada vira juíza da sociedade que a precificou — e ateia fogo a si mesma.", "Nastássia recusa o resgate: o orgulho ferido tranca por dentro a porta que a salvaria.", "Ser amada por pena pode pesar tanto quanto ser comprada — Míchkin a vê como gente, mas a piedade ainda decide o lugar dela."],
  },
  {
    "slug": "ch03-rogojin-faca-holbein",
    "sub": "CAPÍTULO 2 (Parte II): Rogójin, a Faca e o Cristo de Holbein",
    "intro": "Na casa escura de Rogójin, pesada como um túmulo, pende uma cópia do 'Cristo morto' de Holbein — não o Cristo glorioso dos altares, mas um cadáver verdadeiro, a carne já começando a apodrecer, sem o menor sinal de que vá levantar-se. Míchkin para diante dela e diz: um homem pode perder a fé olhando isto. Ali, entre o quadro e a faca que Rogójin acaricia em silêncio, o romance enfrenta sua dúvida mais funda: e se a morte tiver mesmo a última palavra?",
    "cards": [
      {"ic":"eye","t":"O Cristo Que Não Ressuscita","emph":"Holbein","b":"Holbein pintou o impossível de engolir: Deus feito carne <strong>e a carne apodrecendo como qualquer outra</strong> — sem auréola, sem promessa, só morte. É a objeção em forma de tinta a 'a beleza salvará o mundo': <strong>e se a bondade for, no fim, apenas mais um cadáver?</strong> O quadro discute com o romance do começo ao fim.","tip":"<strong>Para o leitor:</strong> é o único personagem mudo da obra — e fala mais alto que quase todos. Diante dele, a fé de Míchkin deixa de ser ingenuidade e vira aposta heroica."},
      {"ic":"masks","t":"Irmãos de Sangue e de Faca","emph":"Irmãos","b":"Rogójin e Míchkin trocam crucifixos, juram fraternidade — e cobiçam a mesma mulher. <strong>Não são herói contra vilão: são o mesmo amor partido em dois</strong>, a compaixão e a posse, gêmeos que não sabem viver um sem o outro. Toda vez que se abraçam, o ar fica carregado: a ternura entre eles já cheira a tragédia.","tip":"<strong>Modelo mental:</strong> o duplo, em Dostoiévski, é um espelho que devolve o seu pior. Rogójin é o que Míchkin seria se a piedade virasse fome."},
      {"ic":"sword","t":"A Faca Já Está na Mesa","emph":"Faca","b":"A lâmina que mata no último capítulo já reluz aqui, manuseada como quem não quer nada. Dostoiévski não esconde o destino — <strong>ele o anuncia e nos faz esperar</strong>. A paixão que precisa possuir não tem outro fim possível: <strong>o amor que não suporta perder o outro acaba por matá-lo</strong>, para tê-lo ao menos morto.","tip":"<strong>Como aplicar:</strong> 'você é meu e de mais ninguém' não é o auge do amor — é o seu disfarce mais perigoso. A posse total carrega, dentro, a própria sentença."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["O Cristo de Holbein é a dúvida pintada: e se a bondade não ressuscitar, e a morte vencer de vez?", "Rogójin e Míchkin são o mesmo amor partido em dois — compaixão e posse, irmãos que pressagiam a tragédia.", "A faca anunciada é o destino da paixão possessiva: o amor que não aceita perder acaba por destruir o que ama."],
  },
  {
    "slug": "ch04-epilepsia-extase",
    "sub": "CAPÍTULO 4 (Parte II): A Epilepsia e o Êxtase",
    "intro": "A doença que faz dele 'idiota' é também a sua janela para o céu. Nos segundos que precedem a crise epiléptica, Míchkin atravessa um instante de harmonia e luz tão absoluto que diria valer uma vida inteira — e logo depois desaba, convulso, na lama da exposição pública. Dostoiévski, ele próprio epiléptico, sabia do que falava: a glória e a queda chegam de mãos dadas, no mesmo corpo, separadas por um piscar de olhos.",
    "cards": [
      {"ic":"spark","t":"O Segundo Que Vale Uma Vida","emph":"Instante","b":"Antes da convulsão vem um relâmpago de <strong>harmonia total</strong> — tudo se reconcilia, e por um instante Míchkin parece tocar o sentido de todas as coisas. Ele confessa: por aquele segundo, daria a vida inteira. <strong>A lucidez mais alta e a 'idiotice' mais funda moram no mesmo crânio</strong>, divididas por meio segundo de luz.","tip":"<strong>Para o leitor:</strong> não é metáfora de gabinete. Dostoiévski viveu essa aura na própria pele — o êxtase que descreve é testemunho, não invenção."},
      {"ic":"gap","t":"Não Há Graça de Graça","emph":"Preço","b":"O preço daquele paraíso é a queda imediata: o corpo se dobra, a boca espuma, a plateia recua com nojo. <strong>A mesma porta que dá para a luz dá para a humilhação</strong> — e Míchkin paga o êxtase com a vergonha. Sua graça e sua impotência não são duas coisas: são as duas faces de um único dom.","tip":"<strong>Modelo mental:</strong> os dons que mais elevam costumam carregar a fragilidade que mais expõe. Quem vê mais longe também tropeça mais feio."},
      {"ic":"eye","t":"A Crise Que Arranca a Máscara","emph":"Máscara","b":"O ataque sempre vem na hora mais constrangedora — no salão cheio, sob os olhos da família. E faz o que a delicadeza de Míchkin jamais faria: <strong>rasga a compostura social e força a verdade para fora</strong>. No segundo do escândalo, cada convidado mostra o que tinha guardado — pena, asco, cálculo. A doença é o reagente que revela a alma de todos.","tip":"<strong>Como aplicar:</strong> quer conhecer alguém de verdade? Veja-o na crise. A normalidade veste o caráter; o desastre o despe."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["A aura epiléptica é um segundo de harmonia total — Míchkin diria valer uma vida; a graça e a doença são o mesmo dom.", "Não há graça sem preço: a mesma porta dá para a luz e para a humilhação da queda.", "A crise rasga a máscara social e revela cada um — a doença faz a verdade que a delicadeza não ousa."],
  },
  {
    "slug": "ch05-beleza-salvara-mundo-compaixao",
    "sub": "CAPÍTULO 5 (Parte III): 'A Beleza Salvará o Mundo'",
    "intro": "Aqui ressoa a frase que atravessou um século e meio: 'a beleza salvará o mundo'. Mas Dostoiévski não a entrega como consolo — entrega como desafio, e no mesmo capítulo arma a sua refutação. Ippolit, um rapaz de dezoito anos comido pela tuberculose, lê em voz alta a sua confissão de moribundo e atira a pergunta na cara da fé de Míchkin: de que serve a sua bondade lenta para quem morre amanhã? A tese e o seu carrasco dividem a mesma sala.",
    "cards": [
      {"ic":"spark","t":"A Frase Que É Uma Pergunta","emph":"Beleza","b":"'A beleza salvará o mundo' não é slogan de cartaz — é enigma. Não fala de rosto bonito, mas de <strong>beleza moral: compaixão e humildade feitas carne</strong>. E ao lado dela o romance acende Nastássia, a beleza que só sabe queimar. A frase pergunta o que não responde: <strong>sob que condições a beleza salva, em vez de destruir?</strong>","tip":"<strong>Para o leitor:</strong> Dostoiévski testa a frase a vida inteira do livro — e a deixa sem prova. A ambiguidade não é defeito; é a própria tese."},
      {"ic":"wave","t":"Ippolit Contra o Tempo","emph":"Ippolit","b":"Tuberculoso, dezoito anos, semanas de vida: Ippolit é o Cristo de Holbein que fala. <strong>Sua revolta é a objeção da morte à compaixão</strong> — de que vale a bondade que demora, se a sentença é hoje? Ele não cabe na salvação lenta de Míchkin; e na sua urgência, qualquer resposta soa pequena demais.","tip":"<strong>Modelo mental:</strong> Ippolit é a pergunta que toda fé adia: e se não houver tempo? A finitude transforma o consolo num insulto educado."},
      {"ic":"leaf","t":"A Piedade Que Empurra Para o Abismo","emph":"Piedade","b":"Míchkin derrama compaixão sobre Nastássia sem nunca exigir nada — e é justamente isso que a afunda. <strong>Amor que tudo perdoa e nada cobra confirma à pessoa que ela não precisa se levantar</strong>. A piedade sem firmeza vira cúmplice da queda: ajuda-se de tal modo a quem se afoga que se segura junto a pedra que o puxa.","tip":"<strong>Como aplicar:</strong> às vezes salvar alguém é parar de 'salvar' o que ele já decidiu perder — e ter a coragem de fazê-lo encarar a própria escolha."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["'A beleza salvará o mundo' é enigma, não slogan: o romance testa a frase a vida toda e recusa-se a confirmá-la.", "Ippolit é a objeção da morte à compaixão: de que vale a bondade lenta para quem não tem tempo?", "Piedade sem firmeza vira cumplicidade da queda — amor que tudo perdoa confirma que o outro não precisa se levantar."],
  },
  {
    "slug": "ch06-aglaia-nastassia-confronto",
    "sub": "CAPÍTULO 6 (Parte IV): Agláia × Nastássia",
    "intro": "Frente a frente, enfim, as duas mulheres que dividem o coração de Míchkin: Agláia, a beleza que ainda pode ser feliz, e Nastássia, a beleza já marcada pelo fogo. Uma exige que ele escolha; a outra, com um grito, o reivindica. E Míchkin, posto entre as duas, faz a única coisa de que é incapaz de não fazer — hesita, para não magoar ninguém. Naquele segundo de piedade dividida, perde as duas de uma vez. É o instante em que a bondade comete o seu crime.",
    "cards": [
      {"ic":"scale","t":"A Hesitação Que Mata Duas","emph":"Hesitação","b":"Ele ama Nastássia de pena e Agláia de esperança, e não suporta ferir uma delas. Mas <strong>não escolher para poupar as duas é cravar a faca mais fundo nas duas</strong>. Quando Nastássia desmaia e ele corre para ampará-la, já escolheu — e perdeu Agláia sem nem perceber. A tragédia não nasce do mal; nasce de uma ternura sem coragem.","tip":"<strong>Modelo mental:</strong> não decidir não é ficar neutro — é decidir às cegas, e quase sempre pior. A escolha que você adia o outro faz por você."},
      {"ic":"mask","t":"Agláia, o Futuro Desperdiçado","emph":"Agláia","b":"Agláia é o avesso luminoso de Nastássia: orgulhosa também, mas com a vida toda pela frente. <strong>Seu amor por Míchkin é verdadeiro</strong> — e o que a destrói não é a rival, é vê-lo largar a mão dela para socorrer a outra. O orgulho que poderia ter florescido não resiste a ser preterido pela piedade do homem amado.","tip":"<strong>Para o leitor:</strong> esta cena dói porque mostra que até a 'boa saída' (Agláia, a vida possível) foi jogada fora. Míchkin não desperdiça só a si — desperdiça quem o amava de verdade."},
      {"ic":"gap","t":"O Pecado da Bondade Sem Coragem","emph":"Pecado","b":"A falha trágica de Míchkin não é fraqueza de caráter nem maldade escondida: é <strong>recusar-se a aceitar que todo amor verdadeiro custa alguma dor a alguém</strong>. Quem ama todos de pena e jura não ferir ninguém termina ferindo a todos. <strong>A compaixão que foge da escolha não cancela o sofrimento — só o reparte entre mais gente</strong>.","tip":"<strong>Como aplicar:</strong> a conta da indecisão nunca é perdoada — só transferida. Quem se cala para não doer empurra a dor para todos que esperavam uma resposta."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["Hesitar para não ferir nenhuma das duas é feri-las mais fundo — não decidir é decidir pior.", "Agláia é a vida ainda possível, desperdiçada: o que a destrói é ver Míchkin largar a mão dela pela piedade da outra.", "A falha trágica é a bondade sem coragem de escolher — quem foge do custo do amor reparte a dor entre todos."],
  },
  {
    "slug": "ch07-casamento-assassinato-desfecho",
    "sub": "CAPÍTULO 7 (Parte IV): O Casamento, o Assassinato e o Desfecho",
    "intro": "No dia do casamento, com o véu já posto, Nastássia olha Míchkin, olha Rogójin à porta da igreja — e foge com o segundo. Era a última fuga: Rogójin a leva para casa e a mata. Míchkin encontra os dois na escuridão — a mulher sob o lençol, a faca de lado, o assassino tremendo. E o que faz o homem bom? Deita-se junto a Rogójin para velar o corpo a noite inteira, afagando-lhe a cabeça como a um irmão doente. Ao amanhecer, a razão já se apagou: o idiota voltou a ser idiota, agora para sempre.",
    "cards": [
      {"ic":"sword","t":"Matar Para Ter Para Sempre","emph":"Matar","b":"Rogójin não suporta a ideia de perdê-la mais uma vez — então a perde de vez, por suas próprias mãos. <strong>A paixão que precisa possuir só conhece um final: destruir o amado para que ninguém mais o tenha</strong>. O amor que não tolera a liberdade do outro nunca foi amor: era cadeia, e a faca é só a tranca derradeira.","tip":"<strong>Modelo mental:</strong> 'se não for meu, não será de ninguém' é o controle vestido de devoção — e seu destino está escrito desde o primeiro juramento."},
      {"ic":"mountain","t":"Os Dois Velando a Morta","emph":"Vigília","b":"A imagem mais devastadora do livro: compaixão e posse, deitados lado a lado, velando juntos a mulher que destruíram juntos. <strong>Os duplos enfim se reúnem — não no amor, mas no cadáver que ambos cavaram</strong>. Míchkin acaricia o assassino sem o julgar, fiel à sua bondade até o fim; e essa bondade, ali, não salva nada — apenas acompanha o horror.","tip":"<strong>Para o leitor:</strong> nesta vigília os dois homens viram um só. Compaixão e fome eram, desde o trem, o mesmo amor caminhando para a mesma noite."},
      {"ic":"spiral","t":"De Volta ao Ponto Zero","emph":"Círculo","b":"Míchkin retorna ao sanatório suíço de onde partiu — apagado, perdido, idiota de novo, agora sem cura. <strong>A bondade não conquistou um palmo do mundo: foi engolida por ele</strong>. O círculo se fecha como uma sentença: <strong>o homem puro não cabe entre os homens — vem do hospício e ao hospício é devolvido</strong>.","tip":"<strong>Modelo mental:</strong> quando o herói volta exatamente ao ponto de partida, a estrutura está dizendo o que a trama não diz — a promessa do início não se cumpriu."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["Rogójin mata para ter para sempre: a paixão possessiva só conhece um fim, destruir o amado para que ninguém o tenha.", "A vigília dos dois homens junto à morta é o ápice da obra — compaixão e posse, enfim um só, sobre o cadáver que cavaram juntos.", "O círculo se fecha como sentença: o homem puro não cabe no mundo, volta do hospício ao hospício, perdido para sempre."],
  },
  {
    "slug": "ch08-personagens-sistema",
    "sub": "CAPÍTULO 8: Os Personagens como Sistema",
    "intro": "Os personagens de 'O Idiota' não são retratos soltos: são um sistema de espelhos onde cada um só ganha sentido ao lado do outro. Míchkin reflete-se em Rogójin; Nastássia, em Agláia; Ippolit, no próprio Míchkin. Dostoiévski não desenha indivíduos isolados — ele monta um campo de forças morais e nos convida a lê-lo aos pares, porque a verdade de cada alma está na que lhe faz frente.",
    "cards": [
      {"ic":"masks","t":"O Quadrângulo do Desastre","emph":"Quadrângulo","b":"<strong>Míchkin–Nastássia–Rogójin–Agláia</strong>: quatro pontas de um único nó. Compaixão e fome disputando a mesma mulher; a beleza ferida e a beleza ainda viva como dois destinos; o homem que não consegue escolher e o que só sabe possuir. <strong>Cada um é a resposta do outro — apague qualquer ponta e os outros três perdem o sentido.</strong>","tip":"<strong>Modelo mental:</strong> em Dostoiévski ninguém existe sozinho; existe em tensão. Pergunte sempre 'contra quem este personagem está sendo escrito?'."},
      {"ic":"eye","t":"Um Cristo Que Não Redime","emph":"Cristo","b":"Míchkin tem os traços de Cristo — perdoa, não julga, compadece-se do assassino e da prostituta. Mas é <strong>a imagem de Cristo lançada na história moderna, onde a bondade desarmada já não converte ninguém</strong>: é idolatrada, explorada e despedaçada pelo mesmo mundo que veio salvar. A santidade, aqui, não opera milagres — apenas sofre.","tip":"<strong>Para o leitor:</strong> a aposta de Dostoiévski era cruel consigo mesmo — pôr a bondade perfeita à prova num mundo real e ver, sem desviar o olhar, se ela aguenta."},
      {"ic":"gap","t":"Ippolit, a Inocência Que Grita","emph":"Ippolit","b":"O rapaz que morre aos dezoito atira a pergunta que nenhuma fé responde fácil: <strong>de que serve toda a bondade do mundo a quem o céu condenou sem motivo?</strong> É o Cristo de Holbein em carne e osso — a inocência que sofre sem redenção à vista. A mesma revolta de Ivan Karamázov, mas sem teoria: pessoal, urgente, com a morte na garganta.","tip":"<strong>Como aplicar:</strong> a pergunta de Ippolit é a do sofrimento do inocente, que atravessa toda a obra de Dostoiévski. Quem a responde rápido demais não a entendeu."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["O quadrângulo Míchkin–Nastássia–Rogójin–Agláia é um nó só: cada personagem é a resposta do outro, ninguém existe sozinho.", "Míchkin é um Cristo que não redime — a bondade desarmada, no mundo moderno, é idolatrada, explorada e despedaçada.", "Ippolit grita a pergunta do sofrimento do inocente — a mesma de Ivan Karamázov, mas com a morte na garganta."],
  },
  {
    "slug": "ch09-simbolos-estrutura-tese",
    "sub": "CAPÍTULO 9: Símbolos, Estrutura e a Tese da Bondade",
    "intro": "Em quatro partes, o livro desenha um círculo: Míchkin entra no mundo carregando a bondade e sai dele esvaziado de razão, devolvido ao ponto exato de onde partira. E ao longo do caminho, os grandes objetos da obra não são cenário — são argumento. O Cristo de Holbein, o fogo, a faca, a aura epiléptica: cada um sustenta a tese e a sua dúvida quando as palavras dos personagens já não bastam. Em Dostoiévski, as coisas pensam.",
    "cards": [
      {"ic":"spiral","t":"Quando os Objetos Discutem","emph":"Objetos","b":"<strong>Holbein</strong>: e se a bondade não ressuscitar? <strong>Fogo</strong>: o julgamento que também é autoincêndio. <strong>Faca</strong>: a paixão que só sabe possuir matando. <strong>Aura epiléptica</strong>: a graça grudada na doença. <strong>Sanatório suíço</strong>: o círculo que não perdoa. <strong>Cada símbolo é uma tese em imagem</strong> — Dostoiévski argumenta com coisas, não só com falas.","tip":"<strong>Para o leitor:</strong> leia os objetos com a mesma atenção dos diálogos. Quando as palavras se calam ou mentem, é o quadro na parede que diz a verdade."},
      {"ic":"layers","t":"Quatro Partes Rumo ao Abismo","emph":"Quatro","b":"A arquitetura é uma queda em escada: <strong>I</strong> a chegada e a esperança; <strong>II</strong> os prenúncios se acumulando; <strong>III</strong> a tese posta à prova; <strong>IV</strong> a ruína consumada. E então o círculo se fecha — Míchkin volta ao manicômio de onde veio. <strong>O mundo não foi transformado pela bondade; foi a bondade que ele desfez.</strong>","tip":"<strong>Modelo mental:</strong> herói que termina onde começou é tragédia confessada — a estrutura grita o que a história sussurra: a promessa do início não se cumpriu."},
      {"ic":"bulb","t":"A Pergunta Que Fica","emph":"Pergunta","b":"O romance não diz se a beleza salvará o mundo. Monta o teste, mostra Míchkin falhar — e <strong>devolve a pergunta intacta às mãos do leitor</strong>. A bondade não salva nunca, ou foi esta bondade, sem firmeza, que não bastou? Dostoiévski recusa as duas saídas fáceis. <strong>Deixar o enigma de pé é a sua forma de respeito por quem lê.</strong>","tip":"<strong>Como aplicar:</strong> as maiores obras não fecham a conta — entregam-na em aberto. Quem exige de 'O Idiota' uma moral pronta perde justamente o que ele tem de mais honesto."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["Os símbolos (Holbein, fogo, faca, aura, sanatório) são argumentos em imagem — em Dostoiévski, leia os objetos como se fossem falas.", "As quatro partes são uma queda em escada, e o círculo final confessa a tragédia: o herói volta ao ponto zero.", "A tese fica em aberto de propósito — Dostoiévski não resolve o insolúvel, e essa recusa é a sua honestidade com o leitor."],
  },
]
