# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'O Príncipe' (Nicolau Maquiavel)."""

BOOK = {
  "title": "O Príncipe",
  "author": "Nicolau Maquiavel",
  "header_light": "O",
  "header_bold": "PRÍNCIPE",
  "subtitle": "VISÃO GERAL · O PODER COMO ELE É, NÃO COMO DEVERIA SER",
  "intro": "Os outros escreveram repúblicas e principados que ninguém nunca viu. Maquiavel jogou fora o 'como se deveria viver' e foi direto à verdade efetiva das coisas: como os homens de fato agem — volúveis, ingratos, interesseiros — e como, em meio a eles, se toma e se conserva um Estado. Não pergunta se o poder é justo. Pergunta como ele se ganha, e por que tantos o perdem. Aqui não há moral consoladora: há a fria anatomia de quem manda. <em>Quem larga o que se faz pelo que se deveria fazer aprende antes a se arruinar.</em>",
  "description": "O Príncipe de Maquiavel, sem o verniz: a verdade efetiva contra o idealismo, virtù × fortuna, temido antes de amado mas jamais odiado, a raposa e o leão, a crueldade bem usada, armas próprias contra mercenários, como fugir do ódio e do desprezo, e a corte de lisonjeiros. A mecânica nua do poder — em chave analítica, não como apologia.",
  "tags": ["Poder", "Política", "Estratégia"],
  "progress": "9 Capítulos",
  "cover": "assets/o-principe-cover.png",
  "overview_cards": [
    {"ic":"target","t":"A Verdade Efetiva","b":"Maquiavel parte da <strong>verdade efetiva das coisas</strong>, não da imaginação dela. Quem governa pelo mundo que devia existir é devorado pelo que existe: entre os muitos que não são bons, ser bom em tudo é a forma mais rápida de se perder. O realismo não é cinismo — é a única ferramenta que não quebra no contato com os homens.","tip":"<strong>Modelo mental:</strong> trate os homens como são — ingratos, volúveis, ávidos do próprio ganho —, não como você gostaria que fossem. Toda doutrina que ignora isso já nasce traída."},
    {"ic":"scale","t":"Virtù × Fortuna","b":"A fortuna é árbitra de <strong>metade</strong> das nossas ações; a outra metade ela deixa ao nosso governo. Virtù é o que se faz com essa metade — energia, previsão, audácia. Sem ocasião, o talento apodrece na obscuridade; sem virtù, a ocasião de ouro escorre pelos dedos e não volta.","tip":"<strong>Regra:</strong> erga os diques no tempo seco. Quando o rio transbordar, ele não pergunta quem se preparou — só poupa quem já o fez.","wide":True},
    {"ic":"sword","t":"Armas Próprias × Alheias","b":"Os alicerces do Estado são boas leis e <strong>boas armas</strong> — e onde não há boas armas, não há boas leis. Mercenário luta pelo salário, que nunca basta para morrer; auxiliar vencedor escraviza quem o pediu. Só a arma própria é segura.","tip":"<strong>Como aplicar:</strong> nunca entregue o que define o seu poder a quem não divide o seu risco. Capacidade alugada cria dependência de quem a vende, não lealdade a quem a comprou."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-tipos-de-principados",
    "sub": "CAPÍTULO 1: Os Tipos de Principado",
    "intro": "Antes de mandar, o príncipe classifica. Diagnosticar o tipo de Estado não é teoria de gabinete — é o primeiro ato político, e o mais perigoso de pular. A mesma medida que firma um principado hereditário arruína um novo: aplica-se o remédio errado quem não soube primeiro nomear a doença.",
    "cards": [
      {"ic":"layers","t":"Hereditário × Novo × Misto","emph":"Hereditário","b":"No hereditário, basta não dilapidar o que se herdou: o povo já se afez ao sangue antigo e perdoa o medíocre. No novo, mora toda a dificuldade. <strong>Mas o misto é o mais traiçoeiro de todos</strong> — quem te abriu as portas se revolta primeiro, porque a esperança que o moveu nunca será saciada por inteiro, e você não pode contentá-lo sem ferir os outros.","tip":"<strong>Modelo mental:</strong> nomeie a origem do seu poder antes de agir. O que cura um principado mata o outro."},
      {"ic":"clock","t":"O Tempo como Aliado","emph":"Tempo","b":"A <strong>antiguidade do domínio</strong> apaga a memória das mudanças e as razões das revoltas: cada inovação deixa um degrau onde a seguinte se apoia, e a duração faz parecer natural o que um dia foi imposição. O príncipe que herda tem menos motivos para ofender — e por isso, sem esforço, é mais amado.","tip":"<strong>Regra:</strong> na ordem já firmada, o tempo trabalha por você. Não rompa o costume sem necessidade extrema — a mudança convoca todos os inimigos de uma vez."},
      {"ic":"mountain","t":"A Dificuldade do Novo","emph":"Dificuldade do Novo","b":"Não há empresa mais arriscada que instaurar uma nova ordem. <strong>Ela nasce cercada de inimigos certos</strong>: têm-na por adversária todos os que lucravam com a ordem velha, e a defendem com tibieza os que dela lucrariam — em parte por medo dos antigos donos, em parte porque o homem só crê de verdade no que já experimentou. O ódio dos que perdem é sempre mais firme que o entusiasmo dos que ganham.","tip":"<strong>Sinal de alerta:</strong> ao fundar o novo, conte com a fúria dos antigos beneficiários e o apoio morno dos futuros. Não confie no segundo grupo enquanto ele não tiver provado a vantagem na própria mão.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["Nomeie o tipo de Estado antes de agir: a terapia depende do diagnóstico, e o remédio errado mata.", "No hereditário, o tempo e o costume governam por você — não rompa a ordem sem necessidade extrema.", "Quem funda o novo herda inimigos prontos e aliados mornos — espere isso desde o primeiro dia."],
  },
  {
    "slug": "ch02-principados-mistos",
    "sub": "CAPÍTULO 2: Principados Mistos — Conservar o Conquistado",
    "intro": "Conservar o que se conquistou é a arte de ferir a desordem enquanto ela ainda é um broto. A decepção dos novos súditos não é acidente: você os libertou prometendo melhora, e nenhuma melhora os contenta. A pergunta não é se haverá revolta — é se você a verá antes ou depois de ela tomar a rua.",
    "cards": [
      {"ic":"eye","t":"Cure o Mal no Broto","emph":"Broto","b":"Os males do Estado são como a tísica do médico: no começo, fáceis de curar e difíceis de enxergar; no fim, fáceis de enxergar e <strong>impossíveis de curar</strong>. O custo de enfrentar a ameaça não cresce em linha reta — dispara. E não há como fugir da guerra: só adiá-la, sempre em favor de quem espera.","tip":"<strong>Como aplicar:</strong> golpeie cedo o sinal fraco, quando golpear ainda é barato e ainda parece exagero. O problema pequeno que se tolera é a crise grande que se herda.","warn":True},
      {"ic":"pin","t":"Resida no Conquistado","emph":"Resida","b":"Quem mora na terra que tomou <strong>vê o incêndio na faísca</strong> e o apaga antes que lavre. O governo de longe só fica sabendo da rebelião quando ela já não tem remédio. Colônias custam quase nada e só ofendem os poucos que perdem a terra — gente pobre e dispersa, sem força para reagir; guarnições devoram o caixa e ofendem a todos.","tip":"<strong>Modelo mental:</strong> a presença flagra a desordem nascendo; a distância a engorda em silêncio até o ponto sem volta. Ofenda poucos, e os poucos certos."},
      {"ic":"spark","t":"Concentre a Dor, Dilua o Prazer","emph":"Concentre a Dor","b":"As crueldades necessárias devem cair todas de uma vez — assim ferem menos e são logo esquecidas. Os benefícios, ao contrário, distribua aos poucos, gota a gota, para que durem na boca. <strong>O mal repetido dia após dia mantém a faca sempre à vista</strong>, e nenhum gesto bom resgata quem fere todo dia.","tip":"<strong>Regra:</strong> ao assumir o comando, execute toda a dureza num único golpe. A dor concentrada o homem esquece; a dor parcelada ele soma — e cobra."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["Cure o mal no broto: enquanto é difícil de ver, é fácil de curar — depois, é o inverso.", "Resida na terra conquistada ou plante colônias: a presença flagra a revolta antes que ela tome a rua.", "Faça toda a crueldade de uma vez e dilua os benefícios — a dor concentrada se esquece, a parcelada se soma."],
  },
  {
    "slug": "ch03-virtu-e-fortuna",
    "sub": "CAPÍTULO 3: Virtù × Fortuna — As Duas Vias para o Poder",
    "intro": "Sobe-se ao poder por dois caminhos: pelo próprio braço (virtù) ou pelo acaso e o favor alheio (fortuna). Quem sobe pela virtù penou para chegar e quase não pena para ficar; quem sobe pela fortuna chegou sem suor e paga o preço depois — sustentar o que se ganhou de graça é o trabalho mais caro que existe.",
    "cards": [
      {"ic":"mountain","t":"Virtù: A Metade que é Sua","emph":"Virtù","b":"Os maiores fundadores nada deveram à sorte além da <strong>ocasião</strong> — a matéria bruta esperando a forma. Sem essa ocasião, a virtù deles teria se apagado no escuro; sem a virtù, a ocasião teria passado em vão. Mas a parte gloriosa foi toda deles: ergueram do nada uma ordem que durou.","tip":"<strong>Como aplicar:</strong> separe a origem do seu sucesso. Se subiu pelo método, repita o método; se subiu por sorte, corra a construir o que a sorte não dá — fundações."},
      {"ic":"sword","t":"O Profeta Armado","emph":"Profeta Armado","b":"Todos os profetas armados venceram; os desarmados se arruinaram. A multidão é fácil de convencer e <strong>difícil de manter convencida</strong>: a fé é variável. Por isso é preciso estar pronto para que, quando ela deixar de crer, se possa fazê-la crer à força. A palavra desarmada conquista a praça e a perde na primeira chuva.","tip":"<strong>Modelo mental:</strong> quem implanta uma ordem nova precisa de espada para defendê-la no dia em que o encanto passar — e ele sempre passa.","warn":True},
      {"ic":"clock","t":"Fortuna Pede Raízes Rápidas","emph":"Raízes Rápidas","b":"Quem foi alçado ao topo pelo favor de outro ou por pura sorte tem tudo, menos uma coisa: <strong>raiz</strong>. E raiz não se ergue na tempestade — ergue-se antes dela. Trate de fundar agora a estrutura, as alianças e a tropa que não dependam de quem o elevou, porque o que se recebe sem esforço o primeiro vento contrário leva.","tip":"<strong>Prática:</strong> o favor de um poderoso é empréstimo, não patrimônio. Converta-o, depressa, em poder próprio e autônomo — antes que cobrem a dívida."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["A fortuna dá a ocasião; a virtù dá a forma — uma sem a outra não funda nada.", "Subiu pela sorte? Lance raiz antes da primeira tempestade, porque depois é tarde.", "Profeta armado vence, desarmado se arruína: a fé da multidão precisa de espada para durar."],
  },
  {
    "slug": "ch04-armas-proprias",
    "sub": "CAPÍTULO 4: Armas Próprias × Mercenárias e Auxiliares",
    "intro": "Os alicerces de todo Estado são boas leis e boas armas. Mas onde faltam boas armas faltam boas leis — e só a arma própria é segura. A guerra é o ofício do príncipe; quem a entrega a estranhos entrega, junto, a própria sobrevivência, e fica devendo a vitória a quem pode cobrá-la.",
    "cards": [
      {"ic":"sword","t":"Mercenárias: Infiéis e Covardes","emph":"Infiéis","b":"A tropa alugada luta pelo pagamento do mês — e nenhum pagamento basta para um homem querer morrer por você. São <strong>leões na paz, lebres na guerra</strong>: enchem-se de coragem entre amigos e somem quando o inimigo aparece. Devoram o caixa enquanto não há perigo e desertam no minuto exato em que ele chega.","tip":"<strong>Modelo mental:</strong> capacidade alugada cria dependência de quem vende, não fidelidade a quem compra. Ela serve ao salário, jamais à causa."},
      {"ic":"triangle","t":"Auxiliares: Ainda Piores","emph":"Auxiliares","b":"Pedir tropa emprestada a um forte é o pior negócio de todos. Pode até ser disciplinada e eficaz — e é justamente por isso que é <strong>mais perigosa que a mercenária</strong>: se perde, você afunda; se vence, a vitória é dela, e você passa a ser refém do dono. É armadura emprestada — ou pesa demais, ou sufoca, ou aperta na hora errada.","tip":"<strong>Sinal de alerta:</strong> vencer com a força de outro não é sua vitória — é o primeiro dia da sua sujeição a ele.","warn":True},
      {"ic":"key","t":"A Arma Própria é a Única Segura","emph":"Arma Própria","b":"Nenhum poder está firme sem <strong>tropa própria</strong>; sem ela, repousa-se inteiro na sorte e na boa vontade alheia — duas coisas que não se controlam. A defesa é o coração do Estado, e nenhum coração se aluga. Antes uma arma própria imperfeita que uma alheia impecável: a primeira é sua, a segunda é uma corda no seu pescoço.","tip":"<strong>Regra:</strong> domine por dentro aquilo de que depende a sua sobrevivência. O núcleo do poder não se delega a quem não morre por ele."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["Funde o poder em armas próprias: mercenário e auxiliar são risco, não recurso.", "Antes a arma própria imperfeita que a alheia perfeita — a vitória de outro é a sua sujeição.", "O ofício central do poder — a defesa — não se aluga a quem não divide o seu risco."],
  },
  {
    "slug": "ch05-temido-ou-amado",
    "sub": "CAPÍTULO 5: Temido × Amado — A Verdade Efetiva",
    "intro": "Aqui bate o coração frio da obra. Surge a pergunta de que todos fogem: vale mais ser amado ou temido? Os homens, diz Maquiavel sem pestanejar, são ingratos, fingidos, fugidios do perigo e ávidos de lucro. Governá-los pelo afeto é fundar a casa sobre a areia do humor alheio.",
    "cards": [
      {"ic":"scale","t":"Temor > Amor (mas jamais Ódio)","emph":"Temor","b":"Não cabendo ter as duas coisas, <strong>é mais seguro ser temido</strong>. O amor se prende por um laço de gratidão que homens vis rompem na primeira conveniência; o temor se prende pelo medo do castigo, que nunca te larga. Mas o temor tem uma fronteira de morte: que não vire ódio. E não vira, desde que não se toque nos bens nem nas mulheres dos súditos — o homem perdoa a morte do pai mais depressa que a perda do patrimônio.","tip":"<strong>Modelo mental:</strong> ancore o poder no que está em suas mãos — o temor — e não no que está nas mãos dos outros — o amor. O afeto é deles; o medo é seu."},
      {"ic":"leaf","t":"A Parcimônia Governa","emph":"Parcimônia","b":"Aceite, sem corar, a fama de <strong>avaro</strong>. O príncipe que quer parecer generoso seca o cofre, e cofre seco só se enche extorquindo — então a liberalidade que buscava aplauso termina cobrando imposto e colhendo ódio. A parcimônia governa sem espoliar. Generoso de verdade é quem não precisa tomar de ninguém.","tip":"<strong>Como aplicar:</strong> a generosidade ostensiva é veneno que se bebe a si mesma. Seja avaro com o que é seu e largo com o que toma do inimigo."},
      {"ic":"target","t":"A Crueldade Bem Usada","emph":"Crueldade Bem Usada","b":"O príncipe não deve recear a fama de cruel quando ela serve para manter os súditos unidos e leais. <strong>Poucos castigos exemplares</strong> são, no fim, mais clementes que a piedade que deixa correr soltos o saque, a desordem e o crime — males que ferem a todos. A crueldade bem usada se faz de uma vez, por necessidade, e não se repete; a mal usada começa pequena e só cresce.","tip":"<strong>Armadilha:</strong> a piedade que tolera o caos é a mais cruel de todas, porque pune o inocente junto. Um corte certeiro salva o corpo inteiro.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["Prefira ser temido a amado — mas jamais odiado: não toque nos bens nem na honra dos súditos.", "Aceite a fama de avaro: a parcimônia governa, a liberalidade ostensiva espolia e gera ódio.", "Poucas crueldades feitas de uma vez são mais clementes que a piedade que deixa o caos punir a todos."],
  },
  {
    "slug": "ch06-raposa-e-leao",
    "sub": "CAPÍTULO 6: A Raposa e o Leão",
    "intro": "O capítulo mais célebre e o mais escandaloso: como o príncipe deve manter a palavra. A resposta gela — os que fizeram grandes coisas foram os que menos se importaram com a fé jurada e souberam, com astúcia, embaralhar a cabeça dos homens. Há dois modos de combater: pelas leis, que é próprio do homem, e pela força, que é próprio da fera. E como o primeiro muitas vezes não basta, é preciso saber ser a fera.",
    "cards": [
      {"ic":"mask","t":"Dois Modos de Combater","emph":"Raposa e Leão","b":"O príncipe deve tomar de empréstimo duas naturezas: a do leão e a da raposa. <strong>Leão para espantar os lobos, raposa para conhecer as armadilhas</strong>. O leão sozinho não enxerga o laço e cai nele; a raposa sozinha não tem como afastar quem vem aberto, com os dentes à mostra. Quem aposta numa só natureza é devorado pela ameaça que essa natureza não vê.","tip":"<strong>Modelo mental:</strong> a astúcia fareja o golpe vindo de baixo; a força esmaga o golpe vindo de frente. Saiba, a cada hora, qual das duas a hora pede."},
      {"ic":"eye","t":"A Palavra Não É Sagrada","emph":"Palavra","b":"A palavra <strong>deixa de obrigar</strong> quando cumpri-la se volta contra você e quando já não existem as razões que a fizeram nascer. Se todos os homens fossem bons, este preceito seria torpe; mas, sendo eles maus e não guardando a palavra que te deram, você não tem por que guardar a sua. Um príncipe precisa saber colorir bem essa natureza, e ser grande fingidor e dissimulador.","tip":"<strong>Sinal de alerta:</strong> honrar uma promessa que te mata, num jogo onde o outro não honra nenhuma, não é virtude — é tolice fatal.","warn":True},
      {"ic":"person","t":"As Cinco Aparências","emph":"Aparências","b":"Convém parecer clemente, fiel, humano, íntegro e religioso — e até sê-lo. Mas a alma deve ficar disposta a <strong>virar para o oposto exato</strong> quando a necessidade mandar. O povo julga pelos olhos e pelas mãos, não pelo que poucos de fato tocam; e no julgamento das ações dos príncipes olha-se o fim. Vença e conserve o Estado, e os meios serão sempre tidos por honrosos, louvados por todos.","tip":"<strong>Regra:</strong> o palco exige a máscara da virtude inteira. O que sustenta o palco, porém, é a frieza de rasgá-la na hora certa."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["Seja raposa e leão: a astúcia vê o laço, a força afasta o lobo — uma só natureza é devorada.", "A palavra não obriga quando cumpri-la te arruína e a razão que a gerou já morreu.", "O povo julga pelos olhos e pelo fim: mantenha as cinco aparências e deixe o resultado calar os meios."],
  },
  {
    "slug": "ch07-evitar-odio-desprezo",
    "sub": "CAPÍTULO 7: Evitar o Ódio e o Desprezo",
    "intro": "O golpe mais mortal vem de dentro. Todo o resto — invasão, guerra, intriga — o príncipe enfrenta de espada na mão; a conspiração, não: ela age no escuro, e contra ela só há uma defesa. A obra a reduz a uma frase: quem não é odiado nem desprezado quase nunca é conspirado.",
    "cards": [
      {"ic":"gap","t":"As Duas Coisas a Evitar","emph":"Ódio e Desprezo","b":"Toda a sua segurança se resume a esquivar dois abismos: <strong>o ódio e o desprezo</strong>. O ódio se ganha tomando bens e honra; o desprezo, mostrando-se volúvel, leviano, efeminado, pusilânime, irresoluto. Quem foge dos dois enfrentará poucos conspiradores — porque o homem que tramaria precisa contar com o descontentamento do povo, e onde não há ódio não há cúmplice.","tip":"<strong>Regra:</strong> a linha da vida do poder é o respeito. Perdoa-se o erro; jamais a fraqueza escancarada ou a mão no patrimônio alheio.","warn":True},
      {"ic":"person","t":"O Povo é a Maior Fortaleza","emph":"Maior Fortaleza","b":"O conspirador trama sozinho e tremendo: tem contra si as leis, a pena e o medo. O príncipe tem o Estado, os amigos e as armas. E se tiver, além disso, <strong>o povo a seu lado</strong>, o conspirador hesita — porque, mesmo vencendo o golpe, fugir do povo inteiro não há como. <strong>A melhor fortaleza é não ser odiado pelo povo</strong>: nenhuma muralha de pedra salva quem ele detesta.","tip":"<strong>Modelo mental:</strong> o escudo mais firme de quem manda é o consentimento calado da maioria. Funde-se nele, não na pedra."},
      {"ic":"fork","t":"Delegue o Odioso","emph":"Delegue","b":"As graças, distribua com a própria mão; <strong>as durezas, ponha-as na mão de outro</strong>. Cesare Borgia entregou a pacificação da Romanha a Remirro de Orco, homem cruel e expedito; depois, quando o povo já o odiava, deixou-o uma manhã cortado em dois na praça, com um cepo e uma faca ensanguentada ao lado. O povo, escreve Maquiavel, ficou ao mesmo tempo satisfeito e estupefato — o ódio recaiu sobre o morto, o crédito da ordem ficou com o príncipe.","tip":"<strong>Como aplicar:</strong> centralize o crédito, terceirize a culpa. O mal necessário jamais deve trazer a sua assinatura."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["Fuja do ódio (não toque em bens nem honra) e do desprezo (mostre firmeza, nunca hesitação).", "A melhor fortaleza é o povo a seu lado — nenhuma muralha compensa o ódio popular.", "Faça a graça com o seu nome; ponha a dureza na mão de outro — e, se preciso, sacrifique a mão."],
  },
  {
    "slug": "ch08-reputacao-lisonjeiros",
    "sub": "CAPÍTULO 8: Reputação, Ministros e Lisonjeiros",
    "intro": "O poder também se sustenta pela reputação e pela qualidade de quem cerca o príncipe. O primeiro juízo que se faz da cabeça de um homem é olhar os homens que ele tem à volta — e o veneno mais comum da corte tem nome: o lisonjeiro.",
    "cards": [
      {"ic":"mountain","t":"Reputação por Grandes Feitos","emph":"Grandes Feitos","b":"Nada faz um príncipe estimado como as grandes empresas e os exemplos raros da própria pessoa. E o segredo é <strong>não ser nunca neutro</strong>: declarar-se sem rodeios amigo de um ou inimigo do outro rende sempre mais que a hesitação. O neutro não agrada ao vencedor, que o despreza por não ter arriscado nada, nem ao vencido, que o abandona por não tê-lo socorrido — e acaba presa dos dois.","tip":"<strong>Prática:</strong> tome lado nos conflitos que importam. Quem fica em cima do muro é a primeira coisa que os dois lados derrubam."},
      {"ic":"key","t":"Bons Ministros","emph":"Bons Ministros","b":"A escolha dos ministros é a primeira prova do juízo de um príncipe. O bom ministro é o que pensa <strong>mais no Estado que no próprio bolso</strong>; o que só pensa em si nunca é de confiar. Para prendê-lo, honre-o, enriqueça-o, divida com ele a glória e a carga — de modo que ele sinta que não pode existir sem você, e que tanta honra o faça temer toda mudança.","tip":"<strong>Modelo mental:</strong> o braço direito só é leal quando o sucesso dele depende, inteiro, do seu. Faça-o rico o bastante para não cobiçar mais, e dependente o bastante para não ousar."},
      {"ic":"bubble","t":"Blinde-se dos Lisonjeiros","emph":"Blinde-se","b":"As cortes fervem de aduladores, e os homens se contentam tanto consigo que dificilmente escapam dessa peste. A única defesa que não te torna desprezado é <strong>escolher poucos sábios e só a eles dar a liberdade de te dizer a verdade</strong> — mas apenas no que você perguntar, e em mais nada. Ouça-os com paciência, e depois decida sozinho, à sua maneira, em silêncio.","tip":"<strong>Sinal de alerta:</strong> quem escuta todos sobre tudo perde o respeito e vira catavento; quem não escuta ninguém vai cego para o precipício.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Faça reputação com grandes feitos e lados firmes: o neutro vira presa dos dois adversários.", "Escolha o ministro que pensa no Estado, não no bolso — e prenda-o pela honra e pela dependência.", "Contra a lisonja: dê a poucos sábios a liberdade da verdade, só quando perguntados — e decida sozinho."],
  },
  {
    "slug": "ch09-fortuna-e-virtu",
    "sub": "CAPÍTULO 9: 'A Fortuna é Mulher' — Virtù e Ocasião",
    "intro": "A pergunta filosófica que sustenta a obra inteira: quanto do que nos acontece é obra da fortuna, e quanto é nosso? Maquiavel recusa o fatalismo de quem cruza os braços e entrega tudo ao céu. A fortuna, diz, é árbitra de metade das nossas ações — mas a outra metade, ou quase, ela deixa ao nosso governo. Resignar-se é desperdiçar a parte que era sua.",
    "cards": [
      {"ic":"wave","t":"Rio e Diques","emph":"Rio e Diques","b":"A fortuna é como um desses rios bravios que, ao transbordar, alagam a planície, arrancam árvores e arrastam o que encontram. Todos fogem; ninguém resiste. E, no entanto, <strong>nada impede que, na bonança, se ergam diques e represas</strong> — de modo que, quando as águas voltarem, sigam por canal, ou ao menos não desabem com a mesma fúria. A fortuna mostra a força onde não há virtù preparada para contê-la.","tip":"<strong>Modelo mental:</strong> a cheia virá; isso não está em suas mãos. O que está é o muro erguido no tempo seco — é ele, não a tempestade, que decide quem sobrevive."},
      {"ic":"clock","t":"Adapte-se aos Tempos","emph":"Adapte-se aos Tempos","b":"É feliz o príncipe que <strong>acerta o seu modo de agir com a qualidade dos tempos</strong>, e infeliz o que se desencontra deles. O cauteloso prospera enquanto a época pede cautela e arruína-se quando ela vira; o impetuoso, o contrário. E aqui está a tragédia: ninguém consegue torcer a própria natureza, ainda mais aquela que sempre lhe deu vitória. Por não saber mudar quando os tempos mudam, o homem cai.","tip":"<strong>Sinal de alerta:</strong> o método que te fez vencer ontem é a âncora invisível que te afoga amanhã. Quem não dobra com a época, a época quebra.","warn":True},
      {"ic":"spark","t":"A Audácia Vence o Acaso","emph":"Audácia","b":"A fortuna é mulher, escreve Maquiavel na imagem mais célebre — e cede mais aos jovens, porque são <strong>menos cautelosos, mais ferozes e a comandam com mais ousadia</strong>. Na dúvida, é melhor ser impetuoso que cauteloso: o que se entrega ao cálculo eterno fica imóvel, e a ocasião não espera. A glória não é dada pelo céu; arranca-se com as próprias mãos, na metade que é nossa.","tip":"<strong>Regra:</strong> o excesso de cálculo paralisa. Em meio à névoa, a audácia governada é o melhor escudo — quem hesita por prudência costuma morrer prudente."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["A fortuna rege metade; a outra metade é sua — recusar essa parte é o verdadeiro fatalismo.", "Erga os diques na bonança: a previsão feita no tempo seco contém a cheia da crise.", "Acerte o método com os tempos; quando eles mudam e você não, caem ambos — e, na dúvida, a audácia vence a hesitação."],
  },
]
