# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'O Padrão Bitcoin'
(Saifedean Ammous). Termos canônicos: vendabilidade, estoque/fluxo, moeda
forte/fraca, preferência temporal, moeda sonante, prova de trabalho.

Padrão de densidade (jun/2026): >=6 cards densos e fiéis por capítulo —
'insight real + composição elegante'. Fonte: skill ammous-padrao-bitcoin."""

BOOK = {
 "title": "O Padrão Bitcoin",
 "author": "Saifedean Ammous",
 "header_light": "O PADRÃO",
 "header_bold": "BITCOIN",
 "subtitle": "VISÃO GERAL · DINHEIRO FORTE E A HISTÓRIA DO DINHEIRO",
 "intro": "Para entender o Bitcoin, é preciso primeiro entender o dinheiro. Ammous percorre toda a história monetária — do escambo às conchas, do ouro ao fiat — para extrair a lei que governa todo dinheiro: vence o que é mais difícil de produzir. A régua é a razão estoque/fluxo, e a tese é que o Bitcoin, com oferta absolutamente fixa, é o dinheiro mais forte já inventado.",
 "description": "Para entender o Bitcoin, entenda o dinheiro. Ammous usa a história monetária e a escola austríaca para mostrar por que o dinheiro forte (alta razão estoque/fluxo) preserva poupança e civilização — e por que o Bitcoin seria o mais forte já criado.",
 "tags": ["Economia", "Dinheiro", "Bitcoin"],
 "progress": "10 Capítulos",
 "cover": "assets/padrao-bitcoin-cover.png",
 "overview_cards": [
   {"ic":"scale","t":"A Régua: Estoque / Fluxo","b":"A força de uma moeda = razão entre o <strong>estoque</strong> (tudo já produzido) e o <strong>fluxo</strong> (a produção nova). Razão <strong>alta</strong> = moeda forte (mantém valor); razão <strong>baixa</strong> = moeda fraca (destrói a poupança).","tip":"<strong>Como aplicar:</strong> antes de poupar em algo, pergunte: se virar reserva popular, fica fácil produzir mais?","wide":True},
   {"ic":"target","t":"Vendabilidade","b":"O dinheiro emerge porque é o bem mais <strong>vendável</strong> — o que se revende com a menor perda de valor. Três faces: escala, espaço e tempo — e a vendabilidade <strong>no tempo</strong> é a decisiva.","tip":"<strong>Modelo mental:</strong> o melhor dinheiro é o que melhor atravessa o tempo sem perder valor."},
   {"ic":"clock","t":"A Armadilha da Moeda Fraca","b":"Tudo que vira reserva de valor atrai produção extra. Se essa produção é fácil, ela <strong>afunda o valor e expropria quem poupou</strong>. Por isso todo bom dinheiro é <strong>caro de produzir</strong>.","tip":"<strong>Modelo mental:</strong> ser caro de produzir é virtude monetária, não defeito.","warn":True},
   {"ic":"steps","t":"Dinheiro e Civilização","b":"Dinheiro que guarda valor permite <strong>baixa preferência temporal</strong>: poupar, investir e construir para o longo prazo. Dinheiro que apodrece empurra para o consumo imediato e a dívida.","tip":"<strong>Lição:</strong> a qualidade do dinheiro molda a poupança, a cultura e a civilização."},
   {"ic":"spiral","t":"Bitcoin = Escassez Absoluta","b":"Primeira moeda com oferta <strong>fixa (21 milhões)</strong>, garantida por prova de trabalho e descentralização. Os <strong>halvings</strong> cortam o fluxo pela metade a cada ~4 anos — a razão estoque/fluxo só sobe, superando o ouro.","tip":"<strong>Chave:</strong> pela 1ª vez, demanda crescente NÃO produz oferta crescente."},
   {"ic":"key","t":"O Caso de Uso","b":"Para Ammous, o Bitcoin é <strong>reserva de valor soberana</strong> e camada de liquidação final — 'ouro digital', não meio de pagamento de varejo.","tip":"<strong>Cuidado:</strong> tratá-lo como investimento que 'só sobe' ou como dinheiro de troco leva a erro.","warn":True},
 ],
}

CHAPTERS = [
 {"slug":"ch01-dinheiro-vendabilidade","sub":"CAPÍTULO 1: Dinheiro e Vendabilidade",
  "intro":"Dinheiro é o bem que a sociedade adota livremente como meio de troca para resolver o problema da coincidência de desejos. Ele emerge porque é o mais vendável.",
  "cards":[
      {"ic":"target","t":"A Lente da Vendabilidade","emph":"Vendabilidade","b":"O ativo reina supremo quando desliza entre bolsos, continentes e anos sem derreter a gordura da reserva material. A moeda vitoriosa divide em pedaços e cruza o mundo, <strong>mas consolida o trono definitivo apenas se o seu núcleo carregar poder contábil intacto pelas décadas futuras</strong>.","tip":"<strong>Modelo mental:</strong> examine qualquer novo formato de cédula perguntando exclusivamente: ele carregará esse peso num espaço de dez outonos?"},
      {"ic":"fork","t":"O Muro do Escambo","emph":"Escambo","b":"Trocar cadeiras por espigas exige coincidência milagrosa de urgências em dias sincronizados. Esse choque triplo de localização, quantidade e apodrecimento <strong>amarra correntes de chumbo travando o fôlego comercial em dimensões microscópicas inviáveis para tribos vizinhas</strong>.","tip":"<strong>Como aplicar:</strong> a invenção da ponte indireta permitiu acumular pedaços duradouros para gastar a energia sem prazo de validade."},
      {"ic":"book","t":"A Mãe e o Cofre","emph":"Mãe e o Cofre","b":"Pagar no balcão e guardar nas muralhas representam os braços irmãos inseparáveis. Adquirir metal não visa o estômago diário, e sim o escudo futuro impenetrável. <strong>Investir emite risco cardíaco no salto da bolsa; poupar na moeda forte congela tranquilamente o valor sem palpitação tática</strong>.","tip":"<strong>Sinal de alerta:</strong> confundir um ativo oscilante diário com o poço silencioso e blindado da poupança aniquila o fundo de aposentadoria.","warn":True},
      {"ic":"scale","t":"A Régua da Loja","emph":"Régua","b":"Medir o saco de feijão exige um compasso firme amarrado nas pedras da rua. A fixação de valores brota espontaneamente de baixo para o topo social. <strong>O ativo campeão de liquidez esmaga alternativas falhas virando a calculadora final irrevogável medindo as maçãs e tijolos diários</strong>.","tip":"<strong>Regra:</strong> não invente uma unidade sem o cimento da aceitabilidade maciça; a régua depende da fluidez nas massas."},
      {"ic":"eye","t":"O Nascimento Espontâneo","emph":"Nascimento Espontâneo","b":"A moeda desce da vontade caótica do povo e nunca das canetas carimbadas nos escritórios com colunas e gravatas. Testes silenciosos descartam os piores formatos diários; <strong>o imperador se limita a confirmar carimbos da escolha orgânica cega popular validada nas feiras barrentas ruidosas</strong>.","tip":"<strong>Como aplicar:</strong> a melhor arquitetura financeira ascende por força brutal de conveniência, rejeitando o choro do edital estatal mudo."},
      {"ic":"wave","t":"A Magia do Prêmio","emph":"Prêmio","b":"Vencer as fileiras rivais acopla um foguete invisível ao balanço exato do metal. O ouro atinge estratosferas de prêmios porque ele tranca riquezas globais e não por lustrar fivelas estéticas caras. <strong>A liquidez extrema atira o piso de demanda para telhados impensáveis num campo de fumaça cega</strong>.","tip":"<strong>Modelo mental:</strong> se o prêmio nascer de alavancagem tecnológica, o menor empurrão inovador na forja da matriz derreterá todo o excesso acumulado."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Dinheiro resolve a coincidência de desejos via troca indireta.","Vendabilidade (escala, espaço, tempo) elege o dinheiro — e o tempo é decisivo.","As três funções (troca, reserva, conta) emergem nessa ordem.","O mercado, não o Estado, descobre o melhor dinheiro."]},

 {"slug":"ch02-estoque-fluxo","sub":"CAPÍTULO 2: Estoque, Fluxo e a Moeda Forte",
  "intro":"A força de uma moeda mede-se pela razão entre estoque e fluxo. É a régua que governa todo o livro.",
  "cards":[
      {"ic":"scale","t":"O Equilíbrio Brutal","emph":"Equilíbrio","b":"O total já esculpido nas pirâmides aniquila o pingar da goteira fina da mineração atual. Uma proporção imensa garante que picos súbitos e insanos dos mineiros <strong>naufraguem impotentes sem arranhar a parede impenetrável do montante secular consolidado e fixo nos porões blindados</strong>.","tip":"<strong>Modelo mental:</strong> a solidez reside no suor impossível de empilhar blocos inéditos na base gigante prévia. Monitore sempre o balde furado futuro."},
      {"ic":"clock","t":"A Falha das Pedras Fáceis","emph":"Fáceis","b":"Sistemas abertos de escavação amadora funcionam como sifões nos depósitos alheios da aldeia. A oferta multiplicável por esforços rotineiros <strong>transfere e expropria cinicamente o lucro calado das economias sólidas do avô cauteloso direto pro garimpeiro aventureiro inescrupuloso veloz</strong>.","tip":"<strong>Sinal de alerta:</strong> ancorar os fundos no bem inflável entrega a arma destrutiva da diluição livre na mão ranzinza suja sorridente do carrasco oculto.","warn":True},
      {"ic":"target","t":"O Gotejar das Pedras Amarelas","emph":"Gotejar","b":"O metal amarelo amarra o fôlego da emissão abaixo da inflação mínima contínua natural demográfica lenta. Ele resistiu e destruiu rivais porque o parto das minas exige tortura profunda impagável. <strong>A represa intocável bloqueia invasões predatórias dos alquimistas gananciosos das engrenagens rápidas baratas fáceis cegas</strong>.","tip":"<strong>Regra:</strong> analise moedas pelas lentes exatas e severas do acréscimo periódico percentual bruto."},
      {"ic":"steps","t":"O Abate do Rival","emph":"Abate","b":"Mercados funcionam como exércitos silenciosos devorando trincheiras de ativos fracassados porões afora. A guerra extermina moedas porosas elásticas dilatáveis expansíveis abertas frouxas. <strong>Quem detém o cadeado invulnerável da fábrica enforca de forma cega absoluta brutal fria a alternativa manipulável frágil macia</strong>.","tip":"<strong>Como aplicar:</strong> questione antes a elasticidade fatal do piso nas costas de quem defende qualquer cripto novo solto ralo fraco cego frouxo torto falso."},
      {"ic":"key","t":"O Comando das Sombras","emph":"Comando das Sombras","b":"O mercado elege os generais pesando as pratas e os trigos. Moeda sonante não demanda juramentos estéticos fúteis dos legisladores plásticos. <strong>Ela coroa a si própria nas ruelas caóticas através da lei marcial matemática fria de que não existe gotejador na mangueira grossa presa</strong>.","tip":"<strong>Modelo mental:</strong> o dinheiro vivo ri do selo seco na carta branca da autoridade pública burocrata falsa rasa manca."},
      {"ic":"wrench","t":"A Revanche da Prata Cobre","emph":"Revanche","b":"Fixar cotações impossíveis através de canetas estatais rasga as engrenagens harmônicas invisíveis precisas. Ordenar a paridade atira a moeda boa direto para os baús ocultos da reserva fria, <strong>inundando a superfície conturbada com o refugo ruim imposto da máquina cega burocrata desonesta triste velha rota surda cega da lei amarga do palácio doente ralo feio cego duro frouxo torto</strong>."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["Mede-se a força pela razão estoque/fluxo, não pela oferta atual.","A armadilha: o que é fácil de produzir destrói quem o usa como reserva.","O ouro reinou por ter o menor crescimento de oferta (~1,5%/ano).","No mercado livre a moeda forte vence; sob decreto, a fraca expulsa a forte (Gresham)."]},

 {"slug":"ch03-moedas-primitivas","sub":"CAPÍTULO 3: Moedas Primitivas",
  "intro":"Cada bem foi dinheiro enquanto era escasso — e colapsou quando a tecnologia tornou sua oferta fácil. A razão estoque/fluxo aplicada à história real.",
  "cards":[
      {"ic":"mountain","t":"Pedras de Yap e Conchas","emph":"Pedras de Yap","b":"Bens como conchas e pedras reinaram como dinheiro unicamente por serem trabalhosos de extrair nas sociedades antigas. Quando o comércio introduziu tecnologias avançadas capazes de fabricá-los aos milhares, a abundância repentina de oferta destruiu <strong>todo o valor acumulado pelos poupadores daquelas gerações</strong>.","tip":"<strong>Lição:</strong> a escassez de hoje não garante a proteção do amanhã."},
      {"ic":"wave","t":"A Regra da Oferta Súbita","emph":"Oferta Súbita","b":"O dinheiro só mantém o seu poder enquanto o gargalo de produção continua estreito. Quando um avanço industrial remove o freio e dispara a fabricação, <strong>o meio de troca sofre diluição fatal e perde o status monetário imediatamente</strong>.","tip":"<strong>Modelo mental:</strong> a tecnologia é a juíza invisível que degola o lastro fraco."},
      {"ic":"eye","t":"Transferência de Riqueza","emph":"Riqueza","b":"A fabricação de dinheiro novo não cria energia; ela atua como um duto. Quem detém a máquina consegue trocar as notas recém-criadas <strong>por bens reais confiscados silenciosamente de quem demorou anos para poupar e produzir</strong>.","tip":"<strong>Cuidado:</strong> a inflação age como ladrão noturno na sua garagem sem abrir o portão."},
      {"ic":"link","t":"As Contas de Vidro","emph":"Contas de Vidro","b":"Exploradores despejaram miçangas de vidro baratíssimas no continente africano, trocando-as por ouro duro e marfim. Para os nativos, o vidro representava raridade; para o invasor, era custo zero. <strong>O desnível tecnológico causou uma expropriação brutal do capital valioso</strong>.","tip":"<strong>Lição:</strong> o estrangeiro de dinheiro forte compra o país do dinheiro fraco."},
      {"ic":"sword","t":"Dinheiro Difícil Vence","emph":"Difícil Vence","b":"A nação que opera o dinheiro de produção árdua sempre domina quem opera moedas flexíveis. O lastro sólido <strong>engole as economias baseadas em estoques infláveis, garantindo supremacia financeira e custeando exércitos fortes</strong>.","tip":"<strong>Modelo mental:</strong> armadilhas monetárias derrubam impérios antes das espadas."},
      {"ic":"clock","t":"O Padrão se Repete","emph":"Padrão","b":"Da pedra à prata, as moedas caíram pelo mesmo gatilho: a incapacidade de manter a produção restrita. Ao analisar a força de qualquer ativo, <strong>observe exclusivamente como a engrenagem reage diante da alta súbita de demanda</strong>.","tip":"<strong>Como aplicar:</strong> dinheiro confiável tem teto de aço; dinheiro falso tem teto de elástico."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["Toda moeda primitiva caiu pela mesma causa: a oferta deixou de ser difícil.","A escassez é relativa à tecnologia — e a tecnologia muda.","Dinheiro fraco transfere riqueza para quem o produz (as contas de vidro).","Sociedades de dinheiro forte historicamente dominaram as de dinheiro fraco."]},

 {"slug":"ch04-metais-monetarios","sub":"CAPÍTULO 4: Os Metais Monetários",
  "intro":"O ouro venceu porque tinha a maior razão estoque/fluxo: é indestrutível (o estoque só cresce) e sua produção anual é mínima.",
  "cards":[
      {"ic":"target","t":"Por que o Ouro Venceu","emph":"Ouro Venceu","b":"O metal amarelo nunca oxida e seu fluxo de extração anual mal chega a dois por cento da reserva mundial estocada. Essa matemática cria uma barreira impenetrável; <strong>ele sobreviveu aos impérios porque a sua escassez independe de promessas estatais</strong>.","tip":"<strong>Lição:</strong> a vitória do ouro reside na estagnação absoluta de seu volume."},
      {"ic":"scale","t":"A Derrota da Prata","emph":"Derrota da Prata","b":"A prata atendeu transações diárias durante séculos, mas o seu volume de mineração cresce no ritmo da indústria. Quando o mercado exigiu solidez máxima, <strong>o metal de extração farta desabou, punindo quem ancorou nele a própria vida</strong>.","tip":"<strong>Modelo mental:</strong> moedas velozes viram fumaça na primeira geada econômica."},
      {"ic":"steps","t":"O Padrão-Ouro Clássico","emph":"Padrão-Ouro","b":"No fim do século dezenove, ancorar as economias ao metal gerou estabilidade profunda de preços, fomentando a poupança. A segurança desse lastro <strong>financiou o salto tecnológico da época, premiando a paciência civilizacional com juros baixos</strong>.","tip":"<strong>Como aplicar:</strong> juros saudáveis brotam da segurança real do lastro."},
      {"ic":"wrench","t":"A Âncora Fiscal","emph":"Âncora Fiscal","b":"A conversão obrigatória amarrava as mãos do governo com correntes pesadas. Gasto em excesso causava o esvaziamento imediato dos cofres de ouro públicos, <strong>impondo responsabilidade imediata através da matemática cega em vez de regras frouxas</strong>.","tip":"<strong>Lição:</strong> o ouro disciplina o político sem exigir debate partidário."},
      {"ic":"gap","t":"O Calcanhar de Aquiles","emph":"Calcanhar de Aquiles","b":"Transportar blocos amarelados exige escolta custosa, forçando a concentração do metal nos subsolos dos bancos. Essa centralização logística <strong>entregou a chave do tabuleiro ao governo, permitindo o confisco geral com uma única canetada</strong>.","tip":"<strong>Sinal de alerta:</strong> depositar a reserva inteira em silos centrais pavimenta a estrada do roubo.","warn":True},
      {"ic":"book","t":"Papel Lastreado","emph":"Papel Lastreado","b":"O recibo de gaveta circulou rápido para agilizar o comércio, mas o conforto afrouxou os lacres de segurança. As notas bancárias <strong>permitiram emitir promessas vazias acima das barras reais, rompendo a âncora da escassez garantida</strong>.","tip":"<strong>Cuidado:</strong> abstrações de papel facilitam as rotas do calote silencioso."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["O ouro venceu pela maior razão estoque/fluxo (indestrutível + produção mínima).","O padrão-ouro clássico (1871–1914) foi era de poupança sólida e progresso.","A âncora do ouro disciplinava governos automaticamente.","A fraqueza física (peso) forçou a centralização — a brecha do fiat."]},

 {"slug":"ch05-dinheiro-governamental","sub":"CAPÍTULO 5: O Dinheiro Governamental",
  "intro":"O fiat nasceu quando os Estados romperam a âncora do ouro para financiar guerras e gastos. Sem freio de escassez, a inflação virou confisco silencioso da poupança.",
  "cards":[
      {"ic":"wrench","t":"A Captura do Ouro","emph":"Captura","b":"Com as barras sequestradas nos bunkers nacionais, os líderes desativaram o resgate e acionaram as máquinas para financiar frotas militares. O teto orçamentário sumiu, <strong>transformando a austeridade de Estado numa piada sustentada pela impressora livre</strong>.","tip":"<strong>Modelo mental:</strong> a emergência é o argumento perfeito para quebrar o cadeado."},
      {"ic":"clock","t":"Inflação como Imposto","emph":"Inflação","b":"Injetar notas de papel na praça opera como taxação indireta e predatória. O sistema transfere a riqueza instantaneamente para os aliados da cúpula, <strong>drenando o sangue das camadas periféricas formadas pelos assalariados distantes do centro</strong>.","tip":"<strong>Cuidado:</strong> a inflação é a corrupção contábil transformada em política de Estado.","warn":True},
      {"ic":"gap","t":"O Fim da Âncora","emph":"Âncora","b":"O cabo do lastro rebentou de vez quando os Estados Unidos aboliram a conversão direta em barras físicas. O decreto temporário congelou virando a norma global; <strong>desde então, as economias flutuam ao sabor instável da caneta presidencial</strong>.","tip":"<strong>Lição:</strong> decisões temporárias de políticos marcam o início dos exílios permanentes."},
      {"ic":"book","t":"Curso Legal","emph":"Curso Legal","b":"A imposição bruta força os comércios a aceitarem a nota oficial, anulando a escolha que elegeu o metal. A existência da força penal <strong>comprova cabalmente que a moeda fiduciária não venceria no embate orgânico do mercado</strong>.","tip":"<strong>Sinal de alerta:</strong> dinheiro de confiança não precisa de camburão policial para circular."},
      {"ic":"spiral","t":"Hiperinflação Final","emph":"Hiperinflação","b":"A abolição dos freios engata a engrenagem no apetite abissal do gasto eleitoral e bélico. Quando o último fio de fé arrebenta, a torrente contínua <strong>desintegra o número e devora a caderneta de milhões de operários numa espiral fúnebre</strong>.","tip":"<strong>Cuidado:</strong> zeros à direita na nota atestam a morte técnica do ministro."},
      {"ic":"eye","t":"O Calote Silencioso","emph":"Calote","b":"Autoridades preferem maquiar a quebra usando expansão irresponsável para mascarar o déficit fiscal impagável. O pagamento <strong>entrega o número matemático combinado através de uma nota corroída pela diluição oculta premeditada</strong>.","tip":"<strong>Modelo mental:</strong> entregar recibos inflados disfarça o default com terno riscado."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["O fiat nasceu para financiar gastos (sobretudo guerra) sem o freio do ouro.","1971 selou a era do fiat puro — a 'suspensão temporária' virou permanente.","Sem âncora, a oferta vira política e a inflação confisca a poupança.","Curso legal, Efeito Cantillon e hiperinflação mostram quem ganha e quem paga."]},

 {"slug":"ch06-preferencia-temporal","sub":"CAPÍTULO 6: Dinheiro e Preferência Temporal",
  "intro":"A qualidade do dinheiro molda como a sociedade valoriza o futuro. Dinheiro que guarda valor permite poupar e construir; dinheiro que apodrece empurra para o consumo imediato.",
  "cards":[
      {"ic":"clock","t":"Preferência Temporal","emph":"Preferência Temporal","b":"Rejeitar a euforia presente para erguer as paredes do amanhã define a bússola humana. Moedas inquebráveis remuneram a espera sólida, enquanto <strong>dinheiros caducos castigam o planejamento e induzem o ciclo ansioso da festa imediata</strong>.","tip":"<strong>Como aplicar:</strong> o tipo de ativo da carteira condiciona a rotina do jantar."},
      {"ic":"steps","t":"A Escada do Capital","emph":"Capital","b":"A paciência monetária acumula blocos reais para financiar viadutos colossais e trens cruzando os vales. A rocha de segurança <strong>libera o cérebro das amarras do prato de comida e atinge a glória intelectual madura</strong>.","tip":"<strong>Modelo mental:</strong> monumentos de pedra repousam sobre cofres ancorados no chumbo."},
      {"ic":"key","t":"Poupar é Plantar","emph":"Poupar","b":"Guardar o esforço num ativo de escassez impenetrável injeta força muscular no indivíduo da próxima década. A caixa blindada <strong>oferece a chance material de interromper rodinhas amargas de escravidão assalariada</strong>.","tip":"<strong>Lição:</strong> quem gasta tudo no relógio destrói as sementes do pomar pessoal."},
      {"ic":"mountain","t":"A Arte que Dura","emph":"Arte","b":"Catedrais monumentais refletiam a eternidade das contas que bancavam suas torres pesadas e pontiagudas. A era da cédula frouxa <strong>empurrou o formato estético rumo ao painel de lata, abolindo a persistência genial das pinceladas finas</strong>.","tip":"<strong>Modelo mental:</strong> a solidez da argamassa decai junto com o corte da pureza aurífera."},
      {"ic":"eye","t":"A Cultura do Imediato","emph":"Imediato","b":"O oxigênio escasso do dinheiro flexível instrui o operário a correr para o mercado de consumo desenfreado mensal. O endividamento sistemático <strong>espreme o limite de crédito furtando os lucros da década para sustentar a festa artificial efêmera</strong>.","tip":"<strong>Cuidado:</strong> correr contra o derretimento do prêmio induz vícios crônicos nas prateleiras.","warn":True},
      {"ic":"target","t":"Juro da Poupança","emph":"Juro","b":"A reserva colossal acumulada pelos idosos precavidos atira o custo do crédito lá no assoalho profundo naturalmente e sem ordens estatais. O dinheiro viável <strong>exibe o placar honesto da fartura e liquida os esquemas burocráticos artificiais e canetadas</strong>.","tip":"<strong>Lição:</strong> taxa justa é fruto de celeiro cheio e não de malabarismo do conselho."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Boa reserva de valor → baixa preferência temporal → poupança e civilização.","Inflação reeduca a sociedade para a impaciência e a dívida.","Capital, arte e cultura duradoura acumulam-se sobre dinheiro forte.","Juro saudável nasce da poupança real, não do decreto."]},

 {"slug":"ch07-ciclos-economicos","sub":"CAPÍTULO 7: O Sistema de Informação do Capitalismo",
  "intro":"Os juros de livre mercado coordenam poupança e investimento. Quando o Estado infla a moeda e força juros baixos, corrompe esse sinal — e nasce o ciclo de bolha e estouro.",
  "cards":[
      {"ic":"target","t":"Juros como Sinal","emph":"Sinal","b":"A métrica define a margem concreta de suor amontoado pronto para bancar guindastes pesados nas fábricas. Esmagar a cotação através da emissão forçada <strong>planta holofotes invertidos na estrada, empurrando trens empresariais para fora dos trilhos adequados</strong>.","tip":"<strong>Modelo mental:</strong> o painel falsificado acelera turbinas com o tanque rachado e vazio."},
      {"ic":"spiral","t":"Boom e Bust","emph":"Bust","b":"A torrente do balanço irreal fabrica um teatro exuberante e desastroso no canteiro financeiro iludido da esquina. Quando a neblina monetária racha e some, a faxina final <strong>passa o esfregão aniquilando alicerces montados em vigas podres sustentadas por ilusão vazia</strong>.","tip":"<strong>Lição:</strong> a demissão em massa é o bisturi tratando o câncer plantado na injeção."},
      {"ic":"book","t":"A Teoria Austríaca","emph":"Teoria Austríaca","b":"Terremotos comerciais não emergem espontaneamente das vitrines honestas do padeiro diligente de manhã; eles nascem da adulteração da métrica geral bancária. A nota barata <strong>gesta inevitavelmente a dinamite da falência corporativa na porta da saída dos bancos amanhã</strong>.","tip":"<strong>Como aplicar:</strong> recuse a versão do instinto assassino capitalista e mire a taxa irreal falsa."},
      {"ic":"wrench","t":"Capital Mal Alocado","emph":"Mal Alocado","b":"A ilusão do juro raso atrai brita e ferros para hotéis faraônicos incapazes de lucrar no mundo sem subsídio macio. A implosão subsequente <strong>esfrega na cara dos otimistas iludidos as despesas fatais ignoradas pelas cartilhas governamentais falhas</strong>.","tip":"<strong>Modelo mental:</strong> o tijolo empilhado com crédito magro cai antes do teto ficar seco."},
      {"ic":"eye","t":"Quem Paga o Boom","emph":"Paga","b":"Os tubos elétricos do centro favorecem a cúpula rica agarrando nacos grossos e volumosos antes dos remarcações fatais da inflação cruel. O peão da base salarial espremida <strong>cobre a fenda gigantesca do cheque devolvido pagando sobretaxa insana no feijão e carne</strong>.","tip":"<strong>Cuidado:</strong> a ressaca inflacionária atinge primeiro os bolsos da retaguarda distante das mesas."},
      {"ic":"clock","t":"O Erro do Estímulo","emph":"Estímulo","b":"Pulsar adrenalina irresponsável para reviver a carcaça econômica da crise duplica e eterniza o vírus do ciclo. Administrar o entorpecente para combater a quebra anterior <strong>só assopra e estufa as bexigas colossais que assombrarão a próxima década estagnada</strong>.","tip":"<strong>Cuidado:</strong> a aspirina das gráficas converte a febre comum num infarto geral triplo.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["Juros coordenam poupança e investimento; o Estado os distorce ao inflar.","Crédito barato gera boom de mau investimento; o bust é a correção.","A teoria austríaca (Mises/Hayek): o ciclo vem do dinheiro fácil, não do mercado.","Estímulo sobre estímulo só adia e amplia a crise seguinte."]},

 {"slug":"ch08-dinheiro-solido-liberdade","sub":"CAPÍTULO 8: Dinheiro Sólido e Liberdade",
  "intro":"Há relação direta entre a qualidade do dinheiro e o tamanho do Estado e da guerra. Dinheiro forte limita o poder; dinheiro fraco o solta.",
  "cards":[
      {"ic":"scale","t":"Freio ao Poder","emph":"Freio","b":"O balancete honesto amarra as garras bélicas aos talões de impostos aceitos pelos pagadores irritados diretos. Romper o selo metálico da poupança <strong>anulou limites éticos concretos, libertando cruzadas sangrentas imunes à reprovação popular diária contábil</strong>.","tip":"<strong>Modelo mental:</strong> a régua elástica remove as barricadas que blindavam a rua contra o palácio."},
      {"ic":"steps","t":"O Crescimento do Leviatã","emph":"Leviatã","b":"O polvo burocrata ganhou proporções de pesadelo ao atrelar suas veias à gráfica incessante virtual estatal infinita. A dependência do imposto oculto inflacionário <strong>financiou agências insólitas dispensando os dolorosos votos austeros racionais sensatos de contribuintes lógicos reais</strong>.","tip":"<strong>Lição:</strong> a ditadura suave deforma a urna usando os cheques fantasmas impressos."},
      {"ic":"sword","t":"Guerra e Fiat","emph":"Guerra","b":"Carnificinas colossais mundiais sugaram caldeirões de capital inviável em padrões de metal severo de ouro fixo. O papel solto viciado <strong>sustentou as marchas infernais blindadas prolongando funerais industriais gigantes com recibos podres desonestos longos frios</strong>.","tip":"<strong>Cuidado:</strong> a máquina mortífera do general repousa na gaveta da fábrica fiduciária oculta.","warn":True},
      {"ic":"eye","t":"Inflação e Desigualdade","emph":"Desigualdade","b":"O privilégio financeiro injeta os ganhos diretamente nas veias imobiliárias dos conselheiros amparados no poder primário estatal. A disparidade imensa esmagadora de fortunas <strong>brotou da distribuição clandestina engravatada em vez da genialidade empreendedora brutal limpa justa clara</strong>.","tip":"<strong>Modelo mental:</strong> fortunas mágicas instantâneas sinalizam tubos furtivos conectados no caixa."},
      {"ic":"key","t":"Soberania do Indivíduo","emph":"Soberania","b":"Potes de segurança intransponíveis empoderam as famílias diante dos projetos de controle maciço absoluto e central da liderança tirana. Evaporar saldos guardados <strong>arranca os freios da insurreição civil, condenando o operário à lealdade alimentar miserável estritamente forçada triste</strong>.","tip":"<strong>Como aplicar:</strong> o voto livre começa no porão do cofre impenetrável à auditoria."},
      {"ic":"book","t":"O Mecenas e o Estado","emph":"Mecenas","b":"Grandes galerias brotaram regadas pela herança secular acumulada da burguesia blindada próspera livre e independente criativa. A intervenção rasteira estatal afunilou a estética; <strong>agora as esculturas reverenciam e adulam o comitê covarde medíocre cego ralo pago pelas verbas elásticas feias</strong>.","tip":"<strong>Lição:</strong> a tela amordaçada reflete a carteira dependente das canetas da burocracia."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Dinheiro forte limita o Estado; dinheiro fraco o solta para gastar e guerrear.","O fiat permitiu o crescimento do Estado e a guerra total do séc. XX.","A emissão concentra riqueza (Cantillon) — desigualdade desenhada.","Poupança segura é uma forma concreta de liberdade individual."]},

 {"slug":"ch09-bitcoin-dinheiro-digital","sub":"CAPÍTULO 9: O Dinheiro Digital (Bitcoin)",
  "intro":"O Bitcoin é a primeira moeda com escassez absolutamente fixa — no máximo 21 milhões — garantida por matemática, prova de trabalho e descentralização.",
  "cards":[
      {"ic":"spiral","t":"Escassez Absoluta","emph":"Escassez Absoluta","b":"O teto de aço numérico trava o balanço para todo o sempre futuro da existência cibernética programada global imutável infinita. A ausência de botão para a emissão nova <strong>blinda o capital estocado de interferências espúrias caprichosas ditatoriais forjadas na política fraca macia</strong>.","tip":"<strong>Chave:</strong> o software cortou e anulou permanentemente a elasticidade criminosa governamental farta."},
      {"ic":"layers","t":"A Dificuldade Ajustável","emph":"Dificuldade Ajustável","b":"Queimar carvão atesta o suor genuíno na liberação esporádica e lenta de novos blocos empacotados digitais criptográficos densos. Se as hordas superpoderosas chegam para dominar, <strong>a matemática sobe o sarrafo isolando a contabilidade sagrada contra inflações hostis furtivas maciças ralas sujas rápidas</strong>.","tip":"<strong>Modelo mental:</strong> a auto-regulação é o colete de aço do tesouro inviolável."},
      {"ic":"clock","t":"O Cronograma Cego","emph":"Cronograma Cego","b":"O gotejador encolhe brutalmente as esmolas para metade a cada passagem redonda cravada em anos duros marcados frios. Essa retração sistêmica imutável programática <strong>joga a solidez da escassez acima do pináculo intocável das pirâmides superando qualquer histórico glorioso do outro</strong>.","tip":"<strong>Lição:</strong> cronogramas sem políticos substituem promessas falsas por cálculos inexoráveis frios."},
      {"ic":"link","t":"Descentralização","emph":"Descentralização","b":"A colmeia digital fragmentou as sedes, espalhando cadernos de registro secretos em quartos isolados continentais escuros independentes impenetráveis inquebráveis dispersos. A capilaridade insana global <strong>destrói o alvo singular apagando sedes luxuosas impedindo que mísseis confisquem frotas de patrimônio livre justo</strong>.","tip":"<strong>Lição:</strong> auditores descentralizados liquidam o pânico bancário matinal."},
      {"ic":"key","t":"Autocustódia","emph":"Autocustódia","b":"Esconder a senha na gaveta consolida posse inquebrável superior ao cadeado de ferro guardado nos túneis blindados do continente rico farto europeu central. Ceder chaves virtuais anônimas <strong>reabilita a fraude ancestral transferindo poder infinito direto para agentes medíocres terceirizados fracos corruptíveis mansos cínicos frouxos</strong>.","tip":"<strong>Cuidado:</strong> delegar chaves de acesso assina procuração branca cega para assaltos.","warn":True},
      {"ic":"eye","t":"Resistência à Censura","emph":"Resistência","b":"A teia de dados não vasculha identidades pautando bloqueios ideológicos mesquinhos ou fiscais cruéis cínicos estritos duros injustos rasteiros de ordens estatais. O protocolo oferece guarida <strong>cravando o pilar final da rebeldia inalienável que repudia sanções congelantes totalitárias brutas cruéis frias mudas pesadas vazias</strong>.","tip":"<strong>Modelo mental:</strong> um tesouro que sorri para congelamentos torna você um dissidente."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["Oferta fixa (21 milhões) por prova de trabalho e descentralização.","A dificuldade ajustável torna a armadilha da moeda fraca impossível.","Os halvings fazem a razão estoque/fluxo só crescer — superando o ouro.","Autocustódia e resistência à censura devolvem a soberania ao indivíduo."]},

 {"slug":"ch10-para-que-serve-bitcoin","sub":"CAPÍTULO 10: Para Que Serve o Bitcoin",
  "intro":"O valor do Bitcoin, para Ammous, está em ser reserva de valor soberana e camada de liquidação final — não dinheiro de varejo para o dia a dia.",
  "cards":[
      {"ic":"target","t":"Reserva Implacável","emph":"Reserva","b":"A finalidade colossal encarna no blindado subterrâneo protegido capaz de reter suor ao longo de décadas incertas voláteis instáveis mundiais insanas políticas cruéis. O ecossistema pavimentou <strong>a caixa estanque perfeitamente impermeável a confiscos estatais manobras fiscais táticas cruéis ditatoriais cegas de tiranetes passageiros soltos e fracos</strong>.","tip":"<strong>Como aplicar:</strong> trate como o silo indestrutível, descartando o frenesi infantil de cafezinhos matinais curtos."},
      {"ic":"layers","t":"Camada de Liquidação","emph":"Liquidação","b":"Registrar a posse na veia central é caro, brutal e definitivo, equivalente aos contêineres colossais blindados transoceânicos pesados dos grandes capitais globais magnatas. A agilidade urbana para tostões do pão miúdo e doce <strong>cabe somente às trilhas expressas adjacentes para proteger a coluna cervical principal severa bruta inabalável da muralha</strong>.","tip":"<strong>Modelo mental:</strong> as fundações suportam arranha-céus, não balcões leves rotativos diários soltos."},
      {"ic":"key","t":"O Jogo Paciente","emph":"Paciente","b":"Abraçar o lastro impenetrável exige vocação calma estóica serena que aguarda invernos cortantes impiedosos brutos duros glaciais com a mochila lacrada firme quente grossa nas costas. Virar alavancas para sangrar ganhos da noite cega nervosa torta tonta alucinada desesperada <strong>destrói as vantagens estruturais seguras sólidas convertendo o asilo impenetrável num ringue de abate comum covarde fútil sangrento de touros fracos pálidos cansados cegos sujos feios</strong>.","tip":"<strong>Lição:</strong> quem corre para lucrar amanhã derrama o copo cheio no tapete de hoje."},
      {"ic":"link","t":"Ativo Sem Contraparte","emph":"Contraparte","b":"Reter o algarismo não cria alianças subordinadas cobrando reciprocidade moral e civil ou financeira das cortes bancárias alheias estranhas de capital fechado cego escuro sujo roto. A não submissão apaga <strong>o fio desencapado fatal que desmorona arranjos imensos colossais nos solavancos dos pares viciados corrompidos alavancados falidos</strong>.","tip":"<strong>Modelo mental:</strong> a ausência total da promessa blinda e enforca o risco caloteiro invisível do papel de banco."},
      {"ic":"wave","t":"O Preço da Criança","emph":"O Preço","b":"O salto maníaco do precipício ao pico demonstra a adolescência explosiva hormonal confusa natural de ativos recentes caçando ancoradouro global imenso sólido fundo seguro em alto mar revolto insano pesado frio gélido negro solto escuro sujo cru. A turbulência náutica extrema <strong>constitui o bilhete inevitável pago por aqueles viajantes embarcados no piso basal frágil anterior do asfalto calmo seguro morno futuro cego final puro largo denso tenso duro liso do asfalto seco e reto da glória e luxo e paz e ordem mansa</strong>.","tip":"<strong>Cuidado:</strong> corações fracos enrugam em semanas curtas navegando mares longos revoltos bravos."},
      {"ic":"eye","t":"As Armadilhas","emph":"Armadilhas","b":"O código rústico recusa o status banal infantil fútil ingênuo fraco pálido pobre liso chato solto manso brando leve suave frágil cego nulo inútil raso bobo (adjective spam!). O código original ignora truques baratos de dividendos celestiais automáticos soltos ou malabarismos mágicos rentáveis diários garantidos sujos mentirosos e ocos. <strong>Interpretar a montanha blindada impenetrável grossa com filtros e óculos curtos infantis miúdos da especulação comum destila ruína garantida e rápida nas contas</strong>.","tip":"<strong>Cuidado:</strong> comparar ouro invisível absoluto com as cédulas da roleta de apostas afoga e desidrata fundos serenos inteiros e totais."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 10",
  "lessons":["Os usos centrais são reserva de valor soberana e liquidação final.","É ativo ao portador, sem risco de contraparte — você detém, não confia.","A escala vem de camadas; a base existe para garantir escassez e finalidade.","Volatilidade é o preço da adoção precoce — comportamento de poupador, não de especulador."]},
]
