# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'O Padrão Bitcoin'
(Saifedean Ammous). Termos canônicos: vendabilidade, estoque/fluxo, moeda
forte/fraca, preferência temporal, moeda sonante, prova de trabalho.

Padrão de densidade (jun/2026): >=6 cards densos e fiéis por capítulo —
'insight real + composição elegante'. Fonte: skill ammous-padrao-bitcoin."""

BOOK = {
 "title": "O Padrão Bitcoin",
 "author": "Saifedean Ammous",
 "header_light": "O PADRÃO",
 "header_bold": "BITCOIN",
 "subtitle": "VISÃO GERAL · A LEI DO DINHEIRO FORTE",
 "intro": "Antes de discutir o Bitcoin, Ammous obriga você a olhar para o dinheiro — algo que quase ninguém examina, porque o usa todos os dias sem pensar. E há uma única lei sob toda a história monetária, das conchas ao ouro, do ouro ao papel do governo: <strong>vence o dinheiro mais difícil de fabricar.</strong> A régua é a razão estoque/fluxo, e o veredicto é austero — o Bitcoin, de oferta absolutamente fixa, seria o dinheiro mais duro que a humanidade já teve nas mãos.",
 "description": "Saifedean Ammous escreve com a economia austríaca na ponta da língua e o fiat na mira. Sua tese: a qualidade do dinheiro decide se uma sociedade poupa ou queima, constrói catedrais ou estoura bolhas, valoriza o futuro ou o devora hoje. Dinheiro forte (alta razão estoque/fluxo) preserva a poupança e a civilização; dinheiro fácil expropria quem confia nele. O Bitcoin, argumenta, é o ponto final dessa história — escassez que nenhum decreto consegue diluir.",
 "hook": "Seu salário perde valor todo mês — e você chama isso de normal.",
 "story_promise": "DINHEIRO DURO PRESERVA QUEM POUPA",
 "story_lessons": [
   "Dinheiro difícil de produzir protege a poupança, não a lei.",
   "O dinheiro fraco ensina você a gastar — não é culpa sua.",
   "O Bitcoin tem 21 milhões fixos e ninguém pode criar mais.",
 ],
 "tags": ["Economia", "Dinheiro", "Bitcoin"],
 "progress": "10 Capítulos",
 "cover": "assets/padrao-bitcoin-cover.png",
 "overview_cards": [
   {"ic":"scale","t":"A Régua: Estoque / Fluxo","b":"Toda moeda se mede por uma única conta: o <strong>estoque</strong> (tudo já produzido) dividido pelo <strong>fluxo</strong> (o que se produz a mais por ano). Razão <strong>alta</strong> = forjar mais é caro = dinheiro forte que guarda valor. Razão <strong>baixa</strong> = a oferta incha à vontade = dinheiro que devora a poupança de quem confiou nele.","tip":"<strong>Como aplicar:</strong> antes de guardar valor em algo, pergunte: se todos correrem para cá, é fácil fabricar mais?","wide":True},
   {"ic":"target","t":"Vendabilidade","b":"O dinheiro não foi decretado: o mercado o elegeu por ser o bem mais <strong>vendável</strong> — o que se revende a qualquer hora com a menor perda. Tem três faces — escala, espaço e tempo —, e <strong>atravessar o tempo</strong> sem derreter é a que separa o dinheiro de tudo o mais.","tip":"<strong>Modelo mental:</strong> bom dinheiro é o que chega íntegro ao seu eu de daqui a vinte anos."},
   {"ic":"clock","t":"A Armadilha da Moeda Fraca","b":"Tudo que vira reserva de valor atrai quem queira produzir mais daquilo. Se produzir é fácil, a enxurrada <strong>afunda o preço e expropria quem poupou</strong> — em silêncio, sem assalto. Por isso todo dinheiro que durou foi <strong>caro de fazer</strong>: a dificuldade é o cofre.","tip":"<strong>Modelo mental:</strong> ser difícil de produzir não é defeito da moeda — é a única coisa que a defende.","warn":True},
   {"ic":"steps","t":"Dinheiro e Civilização","b":"Dinheiro que guarda valor liberta a <strong>baixa preferência temporal</strong>: dá para poupar, esperar, construir o que só frutifica em décadas. Dinheiro que apodrece na carteira ensina o contrário — gaste já, endivide-se, viva o presente. O caráter de um povo segue o caráter da sua moeda.","tip":"<strong>Lição:</strong> mude a dureza do dinheiro e você muda a poupança, a arte e o horizonte de uma civilização."},
   {"ic":"spiral","t":"Bitcoin = Escassez Absoluta","b":"Pela primeira vez, uma moeda tem teto <strong>fixo (21 milhões)</strong> — não por promessa de banqueiro, mas por prova de trabalho e descentralização. Os <strong>halvings</strong> cortam o fluxo pela metade a cada ~4 anos: a razão estoque/fluxo só sobe, deixando o próprio ouro para trás.","tip":"<strong>Chave:</strong> aqui, demanda em alta NÃO destrava oferta nova — a primeira moeda imune à própria popularidade."},
   {"ic":"key","t":"O Caso de Uso","b":"Ammous é categórico: o Bitcoin é <strong>reserva de valor soberana</strong> e camada de liquidação final — 'ouro digital', não a moedinha do cafezinho. A finalidade é guardar suor através de regimes e décadas, não comprar o pão.","tip":"<strong>Cuidado:</strong> esperar que 'só suba' ou usá-lo como troco de balcão é entender errado o que ele é.","warn":True},
 ],
}

CHAPTERS = [
 {"slug":"ch01-dinheiro-vendabilidade","sub":"CAPÍTULO 1: Dinheiro e Vendabilidade",
  "intro":"Para Ammous, dinheiro não é invenção de governo: é a solução que o mercado encontrou para um problema antiquíssimo — a coincidência de desejos. Você tem peixe e quer sandálias; o sapateiro não quer peixe. O dinheiro nasce quando um bem se torna tão fácil de revender que todos passam a aceitá-lo só para repassar adiante. É o mais vendável que vence.",
  "cards":[
      {"ic":"target","t":"A Lente da Vendabilidade","emph":"Vendabilidade","b":"Vendabilidade é a chance de revender um bem sem perder no preço. Tem três faces: dividir-se em pedaços (escala), viajar leve (espaço) e — a que decide tudo — <strong>chegar ao futuro com o valor intacto (tempo)</strong>. Um bem campeão nas duas primeiras e fraco na terceira nunca virou bom dinheiro.","tip":"<strong>Modelo mental:</strong> teste qualquer 'novo dinheiro' por uma só pergunta — daqui a dez anos, ainda valerá o que vale hoje?"},
      {"ic":"fork","t":"O Muro do Escambo","emph":"Escambo","b":"Trocar diretamente exige um milagre: que eu queira o que você tem, você queira o que eu tenho, nas quantidades certas, no mesmo dia. Esse encaixe triplo quase nunca ocorre — e por isso <strong>a economia do escambo morre pequena, presa à aldeia</strong>. O dinheiro é a ponte indireta que rompe esse muro.","tip":"<strong>Como aplicar:</strong> a riqueza só escala quando há um meio comum — não se constrói civilização escambando galinha por sandália."},
      {"ic":"book","t":"Meio de Troca e Reserva","emph":"Reserva","b":"O dinheiro tem dois ofícios que pedem qualidades diferentes. Como meio de troca, basta circular hoje. Como <strong>reserva de valor</strong>, precisa cruzar o tempo sem encolher — e é aqui que quase todo 'dinheiro' falha. Guardar suor num bem que pode ser fabricado à vontade é apostar contra si mesmo.","tip":"<strong>Sinal de alerta:</strong> confundir o que circula bem com o que guarda valor é como confundir a corredeira com o cofre.","warn":True},
      {"ic":"scale","t":"A Unidade de Conta","emph":"Unidade","b":"A terceira função vem por último e de graça: quando um bem já é o meio de troca de todos, vira também a régua com que se mede o preço de tudo. <strong>A unidade de conta não se decreta — ela se conquista depois que o mercado já elegeu o vencedor.</strong> Tabelar preços numa moeda que ninguém usa é desenhar régua no vento.","tip":"<strong>Regra:</strong> a régua segue o dinheiro real; o dinheiro real não segue a régua imposta de cima."},
      {"ic":"eye","t":"O Mercado, Não o Estado","emph":"Mercado","b":"O dinheiro brotou de baixo, da experiência de milhões de trocas, muito antes de qualquer rei. <strong>O soberano não inventou a moeda: chegou depois para carimbá-la — e, com frequência, para fraudá-la.</strong> A história mostra povos escolhendo o melhor dinheiro disponível, não obedecendo a um decreto monetário.","tip":"<strong>Como aplicar:</strong> desconfie sempre que 'oficial' for usado como sinônimo de 'bom'. O mercado descobre; o Estado, no máximo, confirma."},
      {"ic":"wave","t":"O Prêmio Monetário","emph":"Prêmio","b":"Quando um bem é adotado como dinheiro, ganha um valor extra sobre o seu uso prático — o prêmio monetário. O ouro vale muito mais do que serviria para joias e indústria <strong>porque o mundo o guarda como reserva</strong>. Mas todo prêmio que não se assenta em escassez real é convite ao colapso.","tip":"<strong>Modelo mental:</strong> se o prêmio de um ativo apoia-se em moda, e não em dureza de oferta, ele evapora no primeiro susto."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Dinheiro resolve a coincidência de desejos via troca indireta.","Vendabilidade (escala, espaço, tempo) elege o dinheiro — e o tempo é decisivo.","As três funções (troca, reserva, conta) emergem nessa ordem.","O mercado, não o Estado, descobre o melhor dinheiro."]},

 {"slug":"ch02-estoque-fluxo","sub":"CAPÍTULO 2: Estoque, Fluxo e a Moeda Forte",
  "intro":"Aqui está a régua que governa o livro inteiro: a razão estoque/fluxo. O estoque é tudo o que já existe de uma moeda; o fluxo é o quanto se produz a mais por ano. Quanto maior o estoque diante do fluxo, mais difícil é inflar a oferta — e mais forte é o dinheiro. É por essa conta, e não por simpatia, que o ouro reinou.",
  "cards":[
      {"ic":"scale","t":"O Que Estoque/Fluxo Significa","emph":"Estoque/Fluxo","b":"Imagine um lago alimentado por um fio d'água. Se o lago é imenso e o fio é fino, nenhuma chuva de produção nova move o nível. <strong>É essa desproporção — estoque gigante, fluxo minúsculo — que torna uma moeda imune a quem quer fabricá-la em massa.</strong> O ouro tem o maior dos lagos e um dos mais finos dos fios.","tip":"<strong>Modelo mental:</strong> não pergunte quanto existe de uma moeda; pergunte quão rápido conseguem produzir mais."},
      {"ic":"clock","t":"A Armadilha da Oferta Fácil","emph":"Oferta Fácil","b":"Eis a lei impiedosa de Ammous: tudo que é adotado como reserva de valor passa a ser produzido com fúria — e o que é fácil de produzir <strong>arruína quem o guardou.</strong> Cada nova unidade fabricada barato é riqueza transferida, em silêncio, de quem poupou para quem fabricou.","tip":"<strong>Sinal de alerta:</strong> guardar valor num bem de oferta elástica é entregar a chave da sua poupança a quem sabe fabricá-lo.","warn":True},
      {"ic":"target","t":"Por Que o Ouro Reinou","emph":"Ouro","b":"O ouro não enferruja, então o estoque só cresce; e a mineração anual mal acrescenta um e meio por cento ao que já existe. Esse crescimento ínfimo <strong>fez o ouro derrotar todos os rivais ao longo de milênios</strong>: por mais que o preço subisse, ninguém conseguia inundar o mercado e diluir os poupadores.","tip":"<strong>Regra:</strong> meça toda moeda pelo crescimento anual da sua oferta — é o número que separa o que dura do que evapora."},
      {"ic":"steps","t":"Forte Vence Fraco","emph":"Vence","b":"No mercado livre, entre duas moedas, a mais difícil de produzir tende a vencer: ela guarda valor, então é nela que as pessoas escolhem poupar. <strong>A dureza da oferta é a vantagem competitiva definitiva do dinheiro</strong> — não o decreto, não a beleza, não a tradição. Quem produz fácil sempre perde para quem produz com suor.","tip":"<strong>Como aplicar:</strong> diante de qualquer cripto ou ativo novo, a primeira pergunta é só uma — quão fácil é criar mais?"},
      {"ic":"key","t":"Moeda Sonante","emph":"Sonante","b":"Moeda sonante (sound money) é a que o mercado escolhe livremente, não a que o legislador impõe. Ela não precisa de lei de curso forçado para circular: <strong>impõe-se sozinha porque sua oferta não pode ser falsificada por canetada.</strong> O ouro 'soava' verdadeiro; o papel só vale enquanto a confiança aguenta.","tip":"<strong>Modelo mental:</strong> dinheiro que precisa de polícia para ser aceito está confessando que perderia no voto do mercado."},
      {"ic":"wrench","t":"A Lei de Gresham","emph":"Gresham","b":"Vale o oposto sob decreto. Quando o Estado força duas moedas a valerem o mesmo, a boa some — todos a guardam — e a ruim inunda o comércio. <strong>'A moeda má expulsa a boa' só funciona porque a lei proíbe o mercado de cobrar o preço verdadeiro de cada uma.</strong> Tire o decreto e a regra se inverte: a boa volta a vencer.","tip":"<strong>Lição:</strong> Gresham não é lei da natureza — é o que acontece quando o preço do dinheiro é tabelado à força."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["Mede-se a força pela razão estoque/fluxo, não pela oferta atual.","A armadilha: o que é fácil de produzir destrói quem o usa como reserva.","O ouro reinou por ter o menor crescimento de oferta (~1,5%/ano).","No mercado livre a moeda forte vence; sob decreto, a fraca expulsa a forte (Gresham)."]},

 {"slug":"ch03-moedas-primitivas","sub":"CAPÍTULO 3: Moedas Primitivas",
  "intro":"Cada bem foi dinheiro enquanto era escasso — e colapsou quando a tecnologia tornou sua oferta fácil. A razão estoque/fluxo aplicada à história real.",
  "cards":[
      {"ic":"mountain","t":"Pedras de Yap e Conchas","emph":"Pedras de Yap","b":"Conchas e pedras gigantes serviram de dinheiro durante séculos por um único motivo: eram trabalhosíssimas de obter. Bastou o europeu chegar com barco e ferramenta de ferro para fabricá-las aos montes — e a enxurrada de oferta <strong>pulverizou a poupança de gerações inteiras daqueles povos</strong>. A escassez deles era frágil; a tecnologia a quebrou.","tip":"<strong>Lição:</strong> escassez de hoje não é promessa de amanhã — só dura o que ninguém aprendeu a produzir barato."},
      {"ic":"wave","t":"A Regra da Oferta Súbita","emph":"Oferta Súbita","b":"O dinheiro só mantém o seu poder enquanto o gargalo de produção continua estreito. Quando um avanço industrial remove o freio e dispara a fabricação, <strong>o meio de troca sofre diluição fatal e perde o status monetário imediatamente</strong>.","tip":"<strong>Modelo mental:</strong> a tecnologia é a juíza invisível que degola o lastro fraco."},
      {"ic":"eye","t":"Transferência de Riqueza","emph":"Riqueza","b":"A fabricação de dinheiro novo não cria energia; ela atua como um duto. Quem detém a máquina consegue trocar as notas recém-criadas <strong>por bens reais confiscados silenciosamente de quem demorou anos para poupar e produzir</strong>.","tip":"<strong>Cuidado:</strong> a inflação age como ladrão noturno na sua garagem sem abrir o portão."},
      {"ic":"link","t":"As Contas de Vidro","emph":"Contas de Vidro","b":"Exploradores despejaram miçangas de vidro baratíssimas no continente africano, trocando-as por ouro duro e marfim. Para os nativos, o vidro representava raridade; para o invasor, era custo zero. <strong>O desnível tecnológico causou uma expropriação brutal do capital valioso</strong>.","tip":"<strong>Lição:</strong> o estrangeiro de dinheiro forte compra o país do dinheiro fraco."},
      {"ic":"sword","t":"Dinheiro Difícil Vence","emph":"Difícil Vence","b":"A nação que opera o dinheiro de produção árdua sempre domina quem opera moedas flexíveis. O lastro sólido <strong>engole as economias baseadas em estoques infláveis, garantindo supremacia financeira e custeando exércitos fortes</strong>.","tip":"<strong>Modelo mental:</strong> armadilhas monetárias derrubam impérios antes das espadas."},
      {"ic":"clock","t":"O Padrão se Repete","emph":"Padrão","b":"Da pedra à prata, as moedas caíram pelo mesmo gatilho: a incapacidade de manter a produção restrita. Ao analisar a força de qualquer ativo, <strong>observe exclusivamente como a engrenagem reage diante da alta súbita de demanda</strong>.","tip":"<strong>Como aplicar:</strong> dinheiro confiável tem teto de aço; dinheiro falso tem teto de elástico."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["Toda moeda primitiva caiu pela mesma causa: a oferta deixou de ser difícil.","A escassez é relativa à tecnologia — e a tecnologia muda.","Dinheiro fraco transfere riqueza para quem o produz (as contas de vidro).","Sociedades de dinheiro forte historicamente dominaram as de dinheiro fraco."]},

 {"slug":"ch04-metais-monetarios","sub":"CAPÍTULO 4: Os Metais Monetários",
  "intro":"O ouro venceu porque tinha a maior razão estoque/fluxo: é indestrutível (o estoque só cresce) e sua produção anual é mínima.",
  "cards":[
      {"ic":"target","t":"Por que o Ouro Venceu","emph":"Ouro Venceu","b":"O metal amarelo nunca oxida e seu fluxo de extração anual mal chega a dois por cento da reserva mundial estocada. Essa matemática cria uma barreira impenetrável; <strong>ele sobreviveu aos impérios porque a sua escassez independe de promessas estatais</strong>.","tip":"<strong>Lição:</strong> a vitória do ouro reside na estagnação absoluta de seu volume."},
      {"ic":"scale","t":"A Derrota da Prata","emph":"Derrota da Prata","b":"A prata atendeu transações diárias durante séculos, mas o seu volume de mineração cresce no ritmo da indústria. Quando o mercado exigiu solidez máxima, <strong>o metal de extração farta desabou, punindo quem ancorou nele a própria vida</strong>.","tip":"<strong>Modelo mental:</strong> moedas velozes viram fumaça na primeira geada econômica."},
      {"ic":"steps","t":"O Padrão-Ouro Clássico","emph":"Padrão-Ouro","b":"No fim do século dezenove, ancorar as economias ao metal gerou estabilidade profunda de preços, fomentando a poupança. A segurança desse lastro <strong>financiou o salto tecnológico da época, premiando a paciência civilizacional com juros baixos</strong>.","tip":"<strong>Como aplicar:</strong> juros saudáveis brotam da segurança real do lastro."},
      {"ic":"wrench","t":"A Âncora Fiscal","emph":"Âncora Fiscal","b":"A conversão obrigatória amarrava as mãos do governo com correntes pesadas. Gasto em excesso causava o esvaziamento imediato dos cofres de ouro públicos, <strong>impondo responsabilidade imediata através da matemática cega em vez de regras frouxas</strong>.","tip":"<strong>Lição:</strong> o ouro disciplina o político sem exigir debate partidário."},
      {"ic":"gap","t":"O Calcanhar de Aquiles","emph":"Calcanhar de Aquiles","b":"Transportar blocos amarelados exige escolta custosa, forçando a concentração do metal nos subsolos dos bancos. Essa centralização logística <strong>entregou a chave do tabuleiro ao governo, permitindo o confisco geral com uma única canetada</strong>.","tip":"<strong>Sinal de alerta:</strong> depositar a reserva inteira em silos centrais pavimenta a estrada do roubo.","warn":True},
      {"ic":"book","t":"Papel Lastreado","emph":"Papel Lastreado","b":"O recibo de gaveta circulou rápido para agilizar o comércio, mas o conforto afrouxou os lacres de segurança. As notas bancárias <strong>permitiram emitir promessas vazias acima das barras reais, rompendo a âncora da escassez garantida</strong>.","tip":"<strong>Cuidado:</strong> abstrações de papel facilitam as rotas do calote silencioso."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["O ouro venceu pela maior razão estoque/fluxo (indestrutível + produção mínima).","O padrão-ouro clássico (1871–1914) foi era de poupança sólida e progresso.","A âncora do ouro disciplinava governos automaticamente.","A fraqueza física (peso) forçou a centralização — a brecha do fiat."]},

 {"slug":"ch05-dinheiro-governamental","sub":"CAPÍTULO 5: O Dinheiro Governamental",
  "intro":"O fiat nasceu quando os Estados romperam a âncora do ouro para financiar guerras e gastos. Sem freio de escassez, a inflação virou confisco silencioso da poupança.",
  "cards":[
      {"ic":"wrench","t":"A Captura do Ouro","emph":"Captura","b":"Com as barras sequestradas nos bunkers nacionais, os líderes desativaram o resgate e acionaram as máquinas para financiar frotas militares. O teto orçamentário sumiu, <strong>transformando a austeridade de Estado numa piada sustentada pela impressora livre</strong>.","tip":"<strong>Modelo mental:</strong> a emergência é o argumento perfeito para quebrar o cadeado."},
      {"ic":"clock","t":"Inflação como Imposto","emph":"Inflação","b":"Injetar notas de papel na praça opera como taxação indireta e predatória. O sistema transfere a riqueza instantaneamente para os aliados da cúpula, <strong>drenando o sangue das camadas periféricas formadas pelos assalariados distantes do centro</strong>.","tip":"<strong>Cuidado:</strong> a inflação é a corrupção contábil transformada em política de Estado.","warn":True},
      {"ic":"gap","t":"O Fim da Âncora","emph":"Âncora","b":"O cabo do lastro rebentou de vez quando os Estados Unidos aboliram a conversão direta em barras físicas. O decreto temporário congelou virando a norma global; <strong>desde então, as economias flutuam ao sabor instável da caneta presidencial</strong>.","tip":"<strong>Lição:</strong> decisões temporárias de políticos marcam o início dos exílios permanentes."},
      {"ic":"book","t":"Curso Legal","emph":"Curso Legal","b":"A imposição bruta força os comércios a aceitarem a nota oficial, anulando a escolha que elegeu o metal. A existência da força penal <strong>comprova cabalmente que a moeda fiduciária não venceria no embate orgânico do mercado</strong>.","tip":"<strong>Sinal de alerta:</strong> dinheiro de confiança não precisa de camburão policial para circular."},
      {"ic":"spiral","t":"Hiperinflação Final","emph":"Hiperinflação","b":"A abolição dos freios engata a engrenagem no apetite abissal do gasto eleitoral e bélico. Quando o último fio de fé arrebenta, a torrente contínua <strong>desintegra o número e devora a caderneta de milhões de operários numa espiral fúnebre</strong>.","tip":"<strong>Cuidado:</strong> zeros à direita na nota atestam a morte técnica do ministro."},
      {"ic":"eye","t":"O Calote Silencioso","emph":"Calote","b":"Autoridades preferem maquiar a quebra usando expansão irresponsável para mascarar o déficit fiscal impagável. O pagamento <strong>entrega o número matemático combinado através de uma nota corroída pela diluição oculta premeditada</strong>.","tip":"<strong>Modelo mental:</strong> entregar recibos inflados disfarça o default com terno riscado."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["O fiat nasceu para financiar gastos (sobretudo guerra) sem o freio do ouro.","1971 selou a era do fiat puro — a 'suspensão temporária' virou permanente.","Sem âncora, a oferta vira política e a inflação confisca a poupança.","Curso legal, Efeito Cantillon e hiperinflação mostram quem ganha e quem paga."]},

 {"slug":"ch06-preferencia-temporal","sub":"CAPÍTULO 6: Dinheiro e Preferência Temporal",
  "intro":"A qualidade do dinheiro molda como a sociedade valoriza o futuro. Dinheiro que guarda valor permite poupar e construir; dinheiro que apodrece empurra para o consumo imediato.",
  "cards":[
      {"ic":"clock","t":"Preferência Temporal","emph":"Preferência Temporal","b":"Rejeitar a euforia presente para erguer as paredes do amanhã define a bússola humana. Moedas inquebráveis remuneram a espera sólida, enquanto <strong>dinheiros caducos castigam o planejamento e induzem o ciclo ansioso da festa imediata</strong>.","tip":"<strong>Como aplicar:</strong> o tipo de ativo da carteira condiciona a rotina do jantar."},
      {"ic":"steps","t":"A Escada do Capital","emph":"Capital","b":"A paciência monetária acumula blocos reais para financiar viadutos colossais e trens cruzando os vales. A rocha de segurança <strong>libera o cérebro das amarras do prato de comida e atinge a glória intelectual madura</strong>.","tip":"<strong>Modelo mental:</strong> monumentos de pedra repousam sobre cofres ancorados no chumbo."},
      {"ic":"key","t":"Poupar é Plantar","emph":"Poupar","b":"Guardar o esforço num ativo de escassez impenetrável injeta força muscular no indivíduo da próxima década. A caixa blindada <strong>oferece a chance material de interromper rodinhas amargas de escravidão assalariada</strong>.","tip":"<strong>Lição:</strong> quem gasta tudo no relógio destrói as sementes do pomar pessoal."},
      {"ic":"mountain","t":"A Arte que Dura","emph":"Arte","b":"Catedrais monumentais refletiam a eternidade das contas que bancavam suas torres pesadas e pontiagudas. A era da cédula frouxa <strong>empurrou o formato estético rumo ao painel de lata, abolindo a persistência genial das pinceladas finas</strong>.","tip":"<strong>Modelo mental:</strong> a solidez da argamassa decai junto com o corte da pureza aurífera."},
      {"ic":"eye","t":"A Cultura do Imediato","emph":"Imediato","b":"O oxigênio escasso do dinheiro flexível instrui o operário a correr para o mercado de consumo desenfreado mensal. O endividamento sistemático <strong>espreme o limite de crédito furtando os lucros da década para sustentar a festa artificial efêmera</strong>.","tip":"<strong>Cuidado:</strong> correr contra o derretimento do prêmio induz vícios crônicos nas prateleiras.","warn":True},
      {"ic":"target","t":"Juro da Poupança","emph":"Juro","b":"A reserva colossal acumulada pelos idosos precavidos atira o custo do crédito lá no assoalho profundo naturalmente e sem ordens estatais. O dinheiro viável <strong>exibe o placar honesto da fartura e liquida os esquemas burocráticos artificiais e canetadas</strong>.","tip":"<strong>Lição:</strong> taxa justa é fruto de celeiro cheio e não de malabarismo do conselho."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Boa reserva de valor → baixa preferência temporal → poupança e civilização.","Inflação reeduca a sociedade para a impaciência e a dívida.","Capital, arte e cultura duradoura acumulam-se sobre dinheiro forte.","Juro saudável nasce da poupança real, não do decreto."]},

 {"slug":"ch07-ciclos-economicos","sub":"CAPÍTULO 7: O Sistema de Informação do Capitalismo",
  "intro":"Os juros de livre mercado coordenam poupança e investimento. Quando o Estado infla a moeda e força juros baixos, corrompe esse sinal — e nasce o ciclo de bolha e estouro.",
  "cards":[
      {"ic":"target","t":"Juros como Sinal","emph":"Sinal","b":"O juro de mercado é uma mensagem honesta: diz quanta poupança real existe disponível para financiar projetos longos. <strong>Quando o banco central força o juro para baixo imprimindo dinheiro, ele falsifica esse sinal</strong> — e as empresas leem fartura onde há escassez, embarcando em obras que a poupança verdadeira não sustenta.","tip":"<strong>Modelo mental:</strong> juro tabelado é um velocímetro adulterado; a estrada não muda só porque o ponteiro mente."},
      {"ic":"spiral","t":"Boom e Bust","emph":"Bust","b":"O crédito barato infla um boom eufórico de projetos que só fecham as contas enquanto o dinheiro fácil dura. <strong>Quando a ilusão acaba, vem o bust: a correção que liquida tudo o que nunca deveria ter sido construído.</strong> A recessão não é a doença — é o remédio amargo que limpa os erros do boom anterior.","tip":"<strong>Lição:</strong> o estouro é a verdade voltando à tona; adiá-lo só faz a mentira custar mais caro depois."},
      {"ic":"book","t":"A Teoria Austríaca","emph":"Teoria Austríaca","b":"Para Mises e Hayek, o ciclo econômico não nasce de um suposto caos natural do mercado: <strong>nasce da manipulação do dinheiro e do juro pelo Estado.</strong> Sem expansão artificial do crédito, não haveria a onda sincronizada de erros empresariais que chamamos de crise. A culpa não é do capitalismo — é da intervenção na moeda.","tip":"<strong>Como aplicar:</strong> diante de uma crise, não pergunte 'que ganância causou isto?', mas 'quem barateou o crédito antes?'."},
      {"ic":"wrench","t":"Capital Mal Alocado","emph":"Mal Alocado","b":"O juro artificialmente baixo atrai investimento para projetos que só parecem lucrativos sob subsídio — torres, megaobras, empresas que jamais fechariam a conta a juro real. <strong>Quando a realidade volta, esse capital aparece como desperdício: prédios vazios e dívidas que ninguém honra.</strong> Recurso escasso foi enterrado onde não devia.","tip":"<strong>Modelo mental:</strong> o que se ergue sobre crédito falso desaba assim que o crédito verdadeiro cobra a conta."},
      {"ic":"eye","t":"Quem Paga o Boom","emph":"Paga","b":"O dinheiro novo entra pelo topo. Quem está perto dele — bancos, grandes empresas, Estado — compra antes de os preços subirem; <strong>quem está na base só sente a inflação quando ela já corroeu o salário.</strong> O boom enriquece o centro e a ressaca é cobrada da periferia, no preço do feijão e do aluguel.","tip":"<strong>Cuidado:</strong> a fatura da farra do crédito chega primeiro a quem está mais longe da torneira."},
      {"ic":"clock","t":"O Erro do Estímulo","emph":"Estímulo","b":"A reação padrão à crise é imprimir mais e baixar o juro de novo — exatamente o que causou o problema. <strong>Combater a ressaca com mais da mesma bebida só adia e amplia a próxima crise</strong>, empilhando bolha sobre bolha. O estímulo não cura o ciclo: alimenta-o.","tip":"<strong>Cuidado:</strong> a dose que mascara a dor de hoje é a mesma que prepara o colapso maior de amanhã.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["Juros coordenam poupança e investimento; o Estado os distorce ao inflar.","Crédito barato gera boom de mau investimento; o bust é a correção.","A teoria austríaca (Mises/Hayek): o ciclo vem do dinheiro fácil, não do mercado.","Estímulo sobre estímulo só adia e amplia a crise seguinte."]},

 {"slug":"ch08-dinheiro-solido-liberdade","sub":"CAPÍTULO 8: Dinheiro Sólido e Liberdade",
  "intro":"Ammous traça uma linha reta entre a dureza do dinheiro e o tamanho do Estado. Sob o ouro, todo gasto tinha de sair de imposto cobrado ou ouro guardado — e o povo via a conta. Com o fiat, o governo descobriu a fonte sem fundo: imprimir. Dinheiro forte amarra o poder; dinheiro fraco o solta para crescer e guerrear.",
  "cards":[
      {"ic":"scale","t":"O Dinheiro Como Freio","emph":"Freio","b":"Sob o padrão-ouro, cada aventura do governo tinha um preço visível: subir imposto ou esvaziar o cofre. <strong>O ouro obrigava o poder a pedir a conta diretamente ao bolso do contribuinte</strong> — e isso, sozinho, contém ambição. Romper essa âncora foi remover o único limite que o Estado não conseguia ignorar.","tip":"<strong>Modelo mental:</strong> o que limita o poder não é o discurso de moderação; é a impossibilidade de gastar o que não se tem."},
      {"ic":"steps","t":"O Crescimento do Leviatã","emph":"Leviatã","b":"Com a impressora à disposição, o Estado deixou de depender do voto do contribuinte para crescer. <strong>A inflação virou o imposto que ninguém aprova e quase ninguém percebe</strong> — e foi com ele que o aparato estatal inchou no século XX muito além do que qualquer eleitorado teria autorizado em dinheiro contado.","tip":"<strong>Lição:</strong> imposto que precisa ser votado tem teto; imposto que se imprime não tem."},
      {"ic":"sword","t":"Guerra e Fiat","emph":"Guerra","b":"Sob o ouro, guerras esbarravam no caixa: acabava o metal, acabava a campanha. <strong>O fiat removeu esse freio e ajudou a transformar conflitos locais nas guerras totais e prolongadas do século XX.</strong> Quando o custo é diluído em todo poupador, o governante luta mais tempo do que a nação jamais pagaria à vista.","tip":"<strong>Cuidado:</strong> por trás de toda guerra interminável costuma haver uma impressora trabalhando em silêncio.","warn":True},
      {"ic":"eye","t":"Inflação e Desigualdade","emph":"Desigualdade","b":"O dinheiro novo não chega a todos ao mesmo tempo. Quem está perto da torneira — bancos, Estado, aliados — gasta antes dos preços subirem; quem está longe recebe a moeda já corroída. <strong>É o Efeito Cantillon: a inflação enriquece o centro e empobrece a periferia,</strong> e boa parte da desigualdade moderna foi desenhada assim, não conquistada.","tip":"<strong>Modelo mental:</strong> fortunas que brotam coladas ao poder raramente vêm de mérito — vêm de proximidade com a torneira."},
      {"ic":"key","t":"Soberania do Indivíduo","emph":"Soberania","b":"Uma poupança que o governo não consegue diluir nem confiscar é uma forma concreta de liberdade. <strong>Quando o Estado pode evaporar o que você guardou, ele tem sobre você um poder mais profundo que qualquer lei.</strong> Dinheiro forte devolve ao indivíduo a base material para discordar, resistir e recomeçar.","tip":"<strong>Como aplicar:</strong> a liberdade política começa onde termina o alcance da impressora sobre a sua poupança."},
      {"ic":"book","t":"O Mecenas e o Estado","emph":"Mecenas","b":"As grandes obras do passado foram bancadas por fortunas que duravam gerações, porque o dinheiro durava. <strong>Quando a moeda apodrece, a riqueza não se acumula longa o bastante para sustentar o mecenas independente</strong> — e a arte passa a depender do orçamento público, que premia quem agrada ao comitê, não quem cria.","tip":"<strong>Lição:</strong> a arte livre precisa de patrono livre; e patrono livre precisa de dinheiro que não derreta."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Dinheiro forte limita o Estado; dinheiro fraco o solta para gastar e guerrear.","O fiat permitiu o crescimento do Estado e a guerra total do séc. XX.","A emissão concentra riqueza (Cantillon) — desigualdade desenhada.","Poupança segura é uma forma concreta de liberdade individual."]},

 {"slug":"ch09-bitcoin-dinheiro-digital","sub":"CAPÍTULO 9: O Dinheiro Digital (Bitcoin)",
  "intro":"Aqui Ammous apresenta o protagonista. O Bitcoin é, na sua leitura, a primeira moeda da história com escassez absolutamente fixa — no máximo 21 milhões — e essa fixidez não é promessa de ninguém: é imposta por matemática, prova de trabalho e descentralização. Pela primeira vez, demanda crescente não consegue arrancar oferta nova.",
  "cards":[
      {"ic":"spiral","t":"Escassez Absoluta","emph":"Escassez Absoluta","b":"Nenhum dinheiro anterior teve teto verdadeiro — sempre houve uma mina nova, uma mão no botão. O Bitcoin é o primeiro com limite fixo de 21 milhões, <strong>e não existe quem possa votar mais unidades para dentro do sistema.</strong> Pela primeira vez, a popularidade de uma moeda não destrava a sua própria diluição.","tip":"<strong>Chave:</strong> o que para o ouro é meta, para o Bitcoin é certeza — a oferta não responde ao preço."},
      {"ic":"layers","t":"A Dificuldade Ajustável","emph":"Dificuldade Ajustável","b":"Criar bitcoins novos exige gastar energia real em prova de trabalho. E aqui está o golpe de gênio: <strong>se mais gente entra para minerar, o protocolo aumenta a dificuldade e mantém o ritmo de emissão.</strong> A armadilha da moeda fraca — preço sobe, produção dispara — fica, pela primeira vez, impossível de acontecer.","tip":"<strong>Modelo mental:</strong> mais esforço de mineração não gera mais moeda, só torna cada moeda mais cara de fazer."},
      {"ic":"clock","t":"Os Halvings","emph":"Halvings","b":"A cada ~4 anos, a emissão de bitcoins novos cai pela metade — por código, sem reunião nem decreto. <strong>O fluxo só encolhe, então a razão estoque/fluxo só sobe</strong>, num cronograma que já ultrapassa o ouro e segue subindo. É escassez que aperta sozinha, no calendário, à prova de político.","tip":"<strong>Lição:</strong> regra inscrita em código não negocia, não cede a emergência e não muda na véspera da eleição."},
      {"ic":"link","t":"Descentralização","emph":"Descentralização","b":"Não há servidor central, sede nem cofre a tomar. A contabilidade vive em milhares de máquinas espalhadas pelo mundo, todas guardando a mesma cópia. <strong>Sem ponto único a atacar, não há canetada nem confisco que apague o registro</strong> — é o que torna a regra dos 21 milhões inviolável na prática, não só na teoria.","tip":"<strong>Lição:</strong> o que ninguém controla sozinho também é o que ninguém consegue inflar ou apreender sozinho."},
      {"ic":"key","t":"Autocustódia","emph":"Autocustódia","b":"Quem guarda a própria chave detém o próprio dinheiro — sem banco, sem permissão, sem intermediário que possa congelar ou quebrar. <strong>É posse real, não promessa de terceiro.</strong> Mas a outra face é dura: entregar a chave a uma exchange é reabrir a velha porta do risco de contraparte que o Bitcoin existe para fechar.","tip":"<strong>Cuidado:</strong> 'não são suas as chaves, não é seu o bitcoin' — delegar a guarda é abrir mão da soberania.","warn":True},
      {"ic":"eye","t":"Resistência à Censura","emph":"Resistência","b":"A rede não pergunta quem você é nem por que está transacionando. Não há porteiro que possa barrar um pagamento por motivo político ou ideológico. <strong>Para Ammous, é o pilar final: um dinheiro que ninguém pode confiscar nem bloquear devolve ao indivíduo um poder que o fiat lhe tirou.</strong>","tip":"<strong>Modelo mental:</strong> guardar valor fora do alcance de congelamentos é, em si, um ato de soberania."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["Oferta fixa (21 milhões) por prova de trabalho e descentralização.","A dificuldade ajustável torna a armadilha da moeda fraca impossível.","Os halvings fazem a razão estoque/fluxo só crescer — superando o ouro.","Autocustódia e resistência à censura devolvem a soberania ao indivíduo."]},

 {"slug":"ch10-para-que-serve-bitcoin","sub":"CAPÍTULO 10: Para Que Serve o Bitcoin",
  "intro":"No fecho, Ammous diz com todas as letras para que o Bitcoin serve — e para que não serve. Ele é reserva de valor soberana e camada de liquidação final, o cofre digital para guardar suor através de regimes e décadas. Não é o dinheiro do troco do dia a dia, e tratá-lo como aposta de cassino é não ter entendido nada do livro.",
  "cards":[
      {"ic":"target","t":"Reserva de Valor Soberana","emph":"Reserva","b":"O uso central é guardar valor por longo prazo, fora do alcance de qualquer governo. <strong>É um cofre que nenhum decreto abre e nenhum confisco esvazia</strong> — pensado para atravessar décadas incertas, não para ser sacado na próxima semana. Quem o usa assim é poupador; quem o vê como bilhete de loteria é outra coisa.","tip":"<strong>Como aplicar:</strong> trate-o como o silo onde se guarda a colheita, não como o trocado do café da manhã."},
      {"ic":"layers","t":"Camada de Liquidação","emph":"Liquidação","b":"Registrar uma transação direto na rede principal é caro, lento e definitivo — como mover um navio-cargueiro de valor. <strong>Por isso o varejo, o cafezinho e a gorjeta vão para camadas construídas em cima</strong> (como a Lightning), enquanto a base existe para garantir escassez e liquidação final. A muralha sustenta a cidade; não é o balcão da padaria.","tip":"<strong>Modelo mental:</strong> a fundação aguenta o arranha-céu inteiro justamente por não ser usada como porta giratória."},
      {"ic":"key","t":"O Jogo do Poupador","emph":"Poupador","b":"Abraçar dinheiro forte é exercício de baixa preferência temporal: comprar, guardar e esperar atravessar invernos sem vender no pânico. <strong>Quem alavanca e tenta arrancar lucro da volatilidade transforma o cofre num cassino</strong> — e troca a vantagem estrutural de longo prazo pelo abate de curto prazo. A virtude aqui é a paciência, não a esperteza.","tip":"<strong>Lição:</strong> quem corre atrás do lucro de amanhã costuma entornar o que já tinha hoje."},
      {"ic":"link","t":"Ativo Sem Contraparte","emph":"Contraparte","b":"Bitcoin em autocustódia não depende de ninguém honrar uma promessa: você detém, não confia. <strong>Não há banco que possa quebrar, congelar ou caloteá-lo no seu lugar.</strong> É o oposto do dinheiro de papel, que é sempre o passivo de outra pessoa — e que desmorona quando essa pessoa, alavancada, cai.","tip":"<strong>Modelo mental:</strong> ausência de promessa é ausência de risco de calote — você não tem um devedor, tem o bem."},
      {"ic":"wave","t":"O Preço da Adoção Precoce","emph":"Preço","b":"A volatilidade brutal não é defeito permanente: é o preço de assistir, ao vivo, um ativo novo procurar seu valor no mundo. <strong>Os solavancos são o pedágio pago pelos que chegam cedo, antes de a base de adoção se firmar.</strong> Quem precisa de estabilidade diária não deveria estar no início da curva.","tip":"<strong>Cuidado:</strong> as oscilações expulsam o coração fraco — e essa é, em parte, a intenção."},
      {"ic":"eye","t":"O Que Ele NÃO É","emph":"NÃO É","b":"Ammous é direto sobre os erros de leitura: o Bitcoin não rende dividendo, não promete ganho garantido e não é esquema de enriquecer rápido. <strong>Lê-lo com as lentes da especulação comum é o caminho mais curto para a ruína.</strong> Comparar a escassez absoluta com a roleta das apostas é confundir o cofre com a mesa do cassino.","tip":"<strong>Cuidado:</strong> esperar 'só subir' ou tratá-lo como ação que paga proventos é errar de objeto — e pagar caro pelo erro."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 10",
  "lessons":["Os usos centrais são reserva de valor soberana e liquidação final.","É ativo ao portador, sem risco de contraparte — você detém, não confia.","A escala vem de camadas; a base existe para garantir escassez e finalidade.","Volatilidade é o preço da adoção precoce — comportamento de poupador, não de especulador."]},
]
