# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Introdução ao Pensamento Complexo' (Edgar Morin)."""

BOOK = {
 "title": "Introdução ao Pensamento Complexo",
 "author": "Edgar Morin",
 "header_light": "PENSAMENTO",
 "header_bold": "COMPLEXO",
 "subtitle": "VISÃO GERAL · RELIGAR SEM MUTILAR",
 "intro": "Para entender o mundo, aprendemos a desmontá-lo: separar, reduzir, abstrair. O método funciona — e por isso ninguém percebe o que ele custa. Cada corte limpo apaga o fio que ligava as peças, e sobra uma <em>inteligência cega</em>: precisa em cada detalhe, perdida no conjunto. Edgar Morin não pede menos rigor; pede um rigor que não amputa. Complexo vem de <em>complexus</em>, 'o que é tecido junto' — e a tarefa do pensamento não é desfiar esse tecido, mas religá-lo: distinguir sem isolar, ligar sem fundir, e sustentar a contradição em vez de fugir dela.",
 "description": "Edgar Morin contra o reflexo mais antigo do saber: explicar é separar. Ele opõe dois paradigmas — o da simplificação, que disjunta, reduz e quantifica até cegar, e o da complexidade, que religa sem dissolver. No centro, três operadores para pensar o entrelaçado: o dialógico (antagonistas que se precisam), o recursivo (o produto que produz quem o produziu) e o hologramático (a parte no todo, o todo na parte). Não é uma chave que abre o mundo — é a recusa de mutilá-lo: conviver com a incerteza, a desordem e o inacabado como matéria do real, não como falha a corrigir.",
 "tags": ["Filosofia", "Epistemologia", "Pensamento Crítico"],
 "progress": "6 Capítulos",
 "cover": "assets/pensamento-complexo-cover.png",
 "overview_cards": [
  {"ic":"fork","t":"Os Dois Paradigmas","b":"O pensamento clássico governa por três gestos: <strong>disjuntar</strong> (separar o que está ligado), <strong>reduzir</strong> (explicar o todo pela menor peça) e <strong>abstrair</strong> (trocar o concreto pelo número). Ele ordena e clareia — e cega no mesmo lance. O paradigma da complexidade não rejeita a ordem; rejeita a mutilação: <strong>distinguir sem isolar, associar sem fundir</strong>.","tip":"<strong>Modelo mental:</strong> quando uma explicação parecer limpa demais, pergunte o que ela teve de cortar fora para ficar tão limpa.","wide":True},
  {"ic":"spiral","t":"Os Três Operadores","b":"Pensar a complexidade não é acumular dados — é manejar três operações. <strong>Dialógico:</strong> sustentar dois contrários que se precisam, sem dissolver um no outro. <strong>Recursivo:</strong> ver que o produto é produtor de quem o produz — a sociedade faz os indivíduos que fazem a sociedade. <strong>Hologramático:</strong> a parte está no todo, e o todo está na parte.","tip":"<strong>Como aplicar:</strong> não são verdades a decorar, são lentes a girar — encaixe cada uma num problema seu de muitas dimensões e veja o que ela revela."},
  {"ic":"triangle","t":"Complexus: o Tecido Junto","b":"Complexo vem de <em>complexus</em>: <strong>o que é tecido junto</strong>. E tecido não se entende cortando os fios. Daí a confusão a desfazer: o complicado se resolve em passos, um de cada vez; o complexo é <strong>irredutivelmente entrelaçado</strong> — desfie-o e o que importava some entre os dedos.","tip":"<strong>Para refletir:</strong> diante de variáveis que não param quietas, talvez você não esteja diante da própria incompetência em simplificar, e sim da complexidade real do que olha."},
 ],
}

CHAPTERS = [
 {
  "slug": "ch01-inteligencia-cega",
  "sub": "CAPÍTULO 1: A Inteligência Cega",
  "intro": "Há uma cegueira que não vem de ver de menos, mas de um certo modo de ver: o que separa, reduz e abstrai. Esse método deu à ciência seus maiores triunfos e, no mesmo gesto, treinou uma inteligência que acerta cada peça e perde o desenho. Morin a chama de inteligência cega — e o remédio que ele propõe não é apagar a luz da distinção, é parar de cortar os fios entre as coisas que ela ilumina.",
  "cards": [
      {"ic":"lens","t":"Os Três Cortes","emph":"Cortes","b":"O pensamento clássico opera com três lâminas: <strong>disjunta</strong> (separa o sujeito do objeto, a ciência da filosofia, uma disciplina da vizinha), <strong>reduz</strong> (explica o todo pela menor peça) e <strong>abstrai</strong> (esvazia o concreto no número). Cada corte aclara um pedaço — e, no mesmo movimento, torna invisível tudo o que ligava esse pedaço ao resto.","tip":"<strong>Modelo mental:</strong> a clareza tem um preço escondido. Toda explicação que separa ganha em foco o que perde em contexto — e quase nunca soma a fatura."},
      {"ic":"eye","t":"A Inteligência Cega","emph":"Cega","b":"Cegueira não é o oposto de inteligência: pode ser o seu produto. <strong>Quanto mais fundo o saber afia um só ponto, mais perde de vista o conjunto em que esse ponto vive.</strong> O especialista enxerga o átomo e não vê o universo a que ele pertence — uma lucidez parcial que, somada, dá um saber desmiolado.","tip":"<strong>Para refletir:</strong> o perigo maior não é a ignorância confessa, é a competência estreita que não desconfia do próprio campo de visão."},
      {"ic":"gap","t":"A Patologia Do Saber","emph":"Patologia","b":"O remédio virou parte da doença. A especialização, que nasceu para conhecer melhor, hiperespecializou-se até <strong>recortar o real em fatias que não conversam</strong> — e os grandes problemas, que são sempre de muitas dimensões ao mesmo tempo, escorrem por entre as gavetas. Nenhuma disciplina sozinha alcança o que vive entre todas elas.","tip":"<strong>Sinal de alerta:</strong> quando um problema 'não é da minha área' por todos os lados, desconfie: pode ser justamente um problema que só se vê religando as áreas.","warn":True},
    ],
  "lessons_title": "Lições-Chave do Capítulo 1",
  "lessons": ["A simplificação não é um erro de cálculo — é um paradigma invisível; o primeiro passo é tornar visível a régua que se usa sem ver.", "Disjuntar, reduzir e abstrair são úteis e perigosos ao mesmo tempo: o veneno está na exclusividade, não no uso.", "A inteligência cega não vê de menos por falta de luz, e sim por cortar os fios entre o que ilumina.", "Religar não é abrir mão de distinguir — é distinguir sem isolar, e contextualizar o que se distinguiu."],
 },
 {
  "slug": "ch02-desenho-intencao-complexos",
  "sub": "CAPÍTULO 2: O Desenho e a Intenção Complexos",
  "intro": "Se o real não é feito de tijolos soltos, mas de sistemas, então o método de desmontá-lo falha por princípio. A teoria sistêmica traz a primeira surpresa: o todo é mais que a soma das partes — algo nasce do arranjo que nenhuma peça continha. E traz a segunda, que quase ninguém diz: o todo é também menos, porque o conjunto cala qualidades que a peça teria solta. Some-se a isso o sistema aberto, que só vive em troca com o fora, e o velho expulso da ciência clássica que precisa voltar: o sujeito que observa.",
  "cards": [
      {"ic":"link","t":"Mais — e Também Menos","emph":"Mais e Menos","b":"A frase consagrada diz que o todo é mais que a soma das partes: do arranjo emergem qualidades que nenhuma peça sozinha tinha. Morin acrescenta o que a frase esconde — <strong>o todo é também menos, porque, ao se organizar, ele inibe propriedades que a parte exibiria livre.</strong> Guardar os dois lados é o que separa o pensamento complexo do holismo ingênuo.","tip":"<strong>Modelo mental:</strong> reduzir ao elemento e exaltar o todo são o mesmo erro de mão trocada. O conhecimento mora no vaivém entre a parte e o conjunto, nunca num só polo."},
      {"ic":"scale","t":"O Sistema Aberto","emph":"Aberto","b":"O ser vivo não se sustenta por dentro: ele queima, troca, se desfaz e se refaz em fluxo constante com o meio que o cerca. <strong>É aberto por necessidade — fechá-lo seria matá-lo.</strong> A estabilidade que vemos não é repouso; é um equilíbrio dinâmico que só existe porque há entrada e saída ininterruptas atravessando a fronteira.","tip":"<strong>Como aplicar:</strong> antes de estudar uma coisa 'em si', pergunte de que troca com o fora ela depende para continuar sendo o que é. Tire o meio e o objeto desmorona."},
      {"ic":"gap","t":"O Sujeito Que Voltou","emph":"Sujeito","b":"A ciência clássica fez questão de varrer o observador para fora do quadro, em nome da objetividade pura. Mas <strong>quem conhece faz parte do que é conhecido — o olho está dentro da cena que descreve.</strong> Reintroduzir o sujeito não é cair no 'cada um tem sua verdade'; é admitir que esconder o observador não o elimina, só o torna um ponto cego.","tip":"<strong>Sinal de alerta:</strong> a explicação que se diz totalmente neutra costuma ser a que esqueceu de contar onde estava de pé quem a escreveu.","warn":True},
    ],
  "lessons_title": "Lições-Chave do Capítulo 2",
  "lessons": ["O alicerce do pensamento complexo é sistêmico: o real é feito de sistemas abertos, não de peças isoladas que se somam.", "O todo é mais e também menos que a soma das partes — segurar os dois lados afasta tanto o reducionismo quanto o holismo.", "Sistema aberto: a autonomia de qualquer coisa viva se paga com dependência do meio — fechá-la é matá-la.", "Reintroduzir o sujeito não é subjetivismo; é reconhecer que o observador está dentro do que observa."],
 },
 {
  "slug": "ch03-paradigma-da-complexidade",
  "sub": "CAPÍTULO 3: O Paradigma da Complexidade",
  "intro": "Aqui o livro entrega suas ferramentas. Para pensar o entrelaçado sem cortá-lo, Morin oferece três operadores — não dogmas a crer, mas lentes a usar. O <strong>dialógico</strong> faz conviver os contrários; o <strong>recursivo</strong> dobra a causa sobre o efeito; o <strong>hologramático</strong> põe o todo dentro da parte. E sob os três, o tetragrama: a percepção de que ordem, desordem, interações e organização não se excluem — se geram em anel. O universo se organiza ao mesmo tempo em que se desfaz.",
  "cards": [
      {"ic":"mask","t":"O Princípio Dialógico","emph":"Dialógico","b":"Ordem e desordem são inimigas: uma sufoca a outra. E são parceiras: juntas produzem toda organização. <strong>O dialógico é segurar dois antagonistas que se precisam, sem dissolver um no outro nem forçá-los numa síntese que apague a tensão.</strong> Ao contrário da dialética, a contradição não se resolve — ela permanece, e é justamente aí que se torna fértil.","tip":"<strong>Modelo mental:</strong> quando descartar um dos polos empobrece o fenômeno, não escolha lado — segure os dois ao mesmo tempo. É desconfortável, e é esse o ponto."},
      {"ic":"spiral","t":"A Recursão Organizacional","emph":"Recursão","b":"A linha reta causa→efeito não dá conta do vivo. Os indivíduos produzem a sociedade, que por sua vez produz os indivíduos; a espécie gera os seres que geram a espécie. <strong>O produto é, ele mesmo, produtor daquilo que o produziu</strong> — um anel, não um círculo vicioso. A causa e o efeito trocam de lugar e voltam a se alimentar.","tip":"<strong>Como aplicar:</strong> diante de um sistema vivo ou social, troque a flecha pela alça. Pergunte não só 'o que isto causa?', mas 'como o resultado realimenta a sua própria origem?'."},
      {"ic":"layers","t":"O Princípio Hologramático","emph":"Hologramático","b":"No holograma, cada ponto guarda quase toda a imagem do objeto. Assim no vivo: a célula carrega o código do organismo inteiro; o indivíduo traz dentro de si a cultura que o cerca. <strong>Não só a parte está no todo — o todo está em cada parte.</strong> Transcende de uma vez o reducionismo (que só vê peças) e o holismo (que só vê o conjunto).","tip":"<strong>Para refletir:</strong> conhecer enriquece em mão dupla — a parte se explica pelo todo, e o todo se revela na parte, num vaivém que nunca se fecha.","warn":True},
    ],
  "lessons_title": "Lições-Chave do Capítulo 3",
  "lessons": ["Pensar a complexidade é manejar operadores — dialógico, recursivo, hologramático —, não empilhar informação.", "Dialógico: o antagonismo pode ser produtivo; conviver com a contradição rende mais que eliminá-la à força.", "Recursivo: no vivo e no social, produto e produtor coincidem — a causalidade se dobra em anel.", "Tetragrama: ordem, desordem, interações e organização se engendram em círculo — não há ordem pura nem acaso puro."],
 },
 {
  "slug": "ch04-complexidade-e-acao",
  "sub": "CAPÍTULO 4: A Complexidade e a Ação",
  "intro": "Pensar a complexidade não fica na cabeça: tem consequência no agir. Toda ação, mal lançada, entra num jogo de interações que já não obedece a quem a lançou — passa a seguir a lógica do meio, não a do autor. Por isso a complexidade troca o programa pela estratégia: o programa supõe um ambiente estável e quebra ao primeiro imprevisto; a estratégia conta com o acaso e se corrige no caminho. E aceita o que isso implica — agir, no fundo, é apostar.",
  "cards": [
      {"ic":"leaf","t":"A Ecologia Da Ação","emph":"Ecologia","b":"Você dispara a ação com uma intenção clara; ela cai no mundo e a intenção deixa de mandar. <strong>Uma vez lançada, a ação entra no jogo das interações e passa a obedecer à lógica do meio — pode se desviar, voltar-se contra você ou produzir o contrário do que se quis.</strong> O ato não é seu; só a largada é.","tip":"<strong>Modelo mental:</strong> não basta decidir bem na origem. Lançada a ação, é preciso acompanhá-la e relançá-la, porque o ambiente vai reescrevendo o seu sentido."},
      {"ic":"target","t":"Estratégia, Não Programa","emph":"Estratégia","b":"O programa é uma sequência rígida que só funciona se nada sair do roteiro — e algo sempre sai. <strong>A estratégia faz o oposto: parte de uma decisão, examina as incertezas e ajusta o curso conforme o acaso e a informação chegam.</strong> O programa teme o imprevisto; a estratégia se alimenta dele, integrando o que não estava previsto.","tip":"<strong>Como aplicar:</strong> em terreno instável, não escreva o roteiro até o fim. Defina o rumo e deixe abertas as casas que o imprevisto vai preencher por você."},
      {"ic":"gap","t":"Decidir É Apostar","emph":"Apostar","b":"Na complexidade não há fundamento certo nem lei que garanta o resultado. Toda decisão importante é tomada com informação incompleta sobre um futuro que não se deixa prever. <strong>Decidir, então, é apostar — e a lucidez não está em fingir certeza, mas em saber que se está apostando.</strong> A consciência da aposta é o que separa o estrategista do iludido.","tip":"<strong>Sinal de alerta:</strong> desconfie de quem promete certeza num campo incerto. Quem nega o risco da aposta não o eliminou — apenas deixou de vê-lo.","warn":True},
    ],
  "lessons_title": "Lições-Chave do Capítulo 4",
  "lessons": ["A ação escapa à intenção: assuma a ecologia da ação e acompanhe o que você pôs no mundo, porque ele a reescreve.", "Em ambiente incerto, estratégia vence programa — flexibilidade que integra o acaso em vez de quebrar com ele.", "Decidir é apostar; a lucidez está em saber que se aposta, não em fingir que se tem certeza.", "Pensar complexo tem efeito prático: muda o modo de agir, não só o de explicar."],
 },
 {
  "slug": "ch05-complexidade-e-empresa",
  "sub": "CAPÍTULO 5: A Complexidade e a Empresa",
  "intro": "Para que a complexidade não pareça filosofia no ar, Morin a aterrissa num caso de todos os dias: a empresa. Ela não é uma máquina a ser comandada de cima, é um sistema vivo que se auto-organiza — e que só se mantém vivo porque está aberto, dependendo a cada instante do mercado, da energia e da informação que vêm de fora. Daí a lição que incomoda o gestor: governar a complexidade não é varrer a desordem, é aprender a usá-la.",
  "cards": [
      {"ic":"wave","t":"Auto-Eco-Organização","emph":"Auto-Eco","b":"A empresa se organiza por dentro, com regras e autonomia próprias — mas paga essa autonomia com uma dependência funda do meio que a alimenta. <strong>Autonomia e dependência não se opõem: crescem uma da outra.</strong> Quanto mais complexo e independente o sistema, mais aberto ao ambiente ele precisa estar. É o princípio dialógico em pleno funcionamento.","tip":"<strong>Modelo mental:</strong> não confunda autonomia com isolamento. O que é mais livre é também o que troca mais com o fora — não o que se fecha em si."},
      {"ic":"spiral","t":"A Ordem Que Precisa Da Desordem","emph":"Desordem","b":"O gestor sonha com a ordem total: tudo previsto, nada fora do lugar. Seria a morte. <strong>Um sistema sem nenhuma desordem não se adapta — enrijece e quebra ao primeiro abalo; um sistema só desordem se dissolve.</strong> A vida da organização está na liga entre as duas: a regra que estabiliza e o ruído que abre brechas para o novo.","tip":"<strong>Como aplicar:</strong> não persiga a desordem até o zero. Uma margem de improviso, atrito e folga é o que permite à organização inventar saída quando o roteiro falha."},
      {"ic":"gap","t":"Gerir Não É Controlar","emph":"Controlar","b":"Querer prever e fixar cada detalhe não traz segurança — traz fragilidade, porque o real sempre escapa do plano. <strong>Gerir a complexidade é o contrário do controle total: é abrir-se ao meio, dosar a desordem e conviver com a incerteza como condição, não como falha a eliminar.</strong> A rigidez perfeita é tão letal quanto o caos puro.","tip":"<strong>Sinal de alerta:</strong> quando um plano não admite nenhum desvio, ele não é forte — é quebradiço. O que não dobra com o imprevisto, parte.","warn":True},
    ],
  "lessons_title": "Lições-Chave do Capítulo 5",
  "lessons": ["A empresa é sistema vivo auto-eco-organizado: autonomia e dependência do meio caminham juntas, não em oposição.", "Ordem e desordem são parceiras: a rigidez total é tão letal para a organização quanto o caos absoluto.", "Gerir a complexidade é abrir-se ao meio e dosar a desordem, não persegui-la até o zero.", "A complexidade não é só teoria: aplicada à gestão, troca o controle total pela adaptação contínua."],
 },
 {
  "slug": "ch06-epistemologia-da-complexidade",
  "sub": "CAPÍTULO 6: Epistemologia da Complexidade",
  "intro": "No fecho, o pensamento se vira sobre si mesmo. Não basta conhecer o mundo: é preciso conhecer o próprio conhecer — vigiar os erros e as ilusões da mente que conhece. A complexidade integra de vez aquilo que a ciência clássica queria expulsar: o sujeito que observa e a incerteza que não se dissolve. E faz a última recusa, a mais difícil de aceitar: ela não é uma resposta que entrega a chave do mundo. É um imperativo — pensar sem mutilar — que nunca termina em certeza.",
  "cards": [
      {"ic":"link","t":"O Conhecimento Do Conhecimento","emph":"Do Conhecimento","b":"Conhecer não é só olhar o objeto — é olhar também o olhar. <strong>A mente que conhece precisa se dobrar sobre si mesma para vigiar os próprios erros e ilusões, porque a primeira fonte de cegueira é não saber como se vê.</strong> É o conhecimento pertinente: aquele que não esquece de incluir, no quadro, quem está pintando o quadro.","tip":"<strong>Modelo mental:</strong> antes de confiar numa conclusão, examine o aparelho que a produziu. A mente que não desconfia de si é a mais fácil de enganar."},
      {"ic":"eye","t":"O Sujeito Reintegrado","emph":"Sujeito","b":"A ciência clássica expulsou o observador em nome da objetividade — e, ao escondê-lo, criou um ponto cego. <strong>O sujeito não é o inimigo do conhecimento verdadeiro; é parte inevitável dele.</strong> Ser sujeito é ser, ao mesmo tempo, autônomo e dependente, fechado num 'Eu' que só ele pode dizer e aberto ao mundo que o atravessa.","tip":"<strong>Para refletir:</strong> negar o sujeito não o elimina — só o disfarça. A objetividade honesta é a que sabe de onde está sendo vista."},
      {"ic":"gap","t":"O Imperativo Da Incerteza","emph":"Incerteza","b":"Não há fundamento último, lei absoluta nem ordem perfeita: a incerteza é irredutível, parte do real, não defeito a corrigir. <strong>Por isso a complexidade não é uma solução — é um imperativo: pensar ligando e contextualizando, convivendo com a contradição e o inacabado.</strong> Ela não promete o mundo resolvido; promete não mutilá-lo.","tip":"<strong>Sinal de alerta:</strong> quem oferece a chave que explica tudo está vendendo simplificação. A complexidade dá menos conforto e mais verdade: o pensamento que não se fecha.","warn":True},
    ],
  "lessons_title": "Lições-Chave do Capítulo 6",
  "lessons": ["Conhecer bem exige conhecer o próprio conhecer: vigiar os erros e as ilusões da mente que conhece.", "O sujeito não é inimigo da objetividade — escondê-lo é que produz o ponto cego.", "A incerteza é irredutível: não é falha a corrigir, é matéria do real a habitar.", "A complexidade é um imperativo, não uma solução: pensar sem mutilar é o objetivo, e não há certeza final no fim."],
 },
]
