# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'O Poder de Delegar'
(Donna M. Genett — If You Want It Done Right, You Don't Have to Do It Yourself!).
Framework canônico: parábola James/Jones, os SEIS PASSOS, os três níveis de
autoridade (Recomendar / Informar e iniciar / Agir), a regra dos 95%."""

BOOK = {
 "title": "O Poder de Delegar",
 "author": "Donna M. Genett",
 "header_light": "O PODER",
 "header_bold": "DE DELEGAR",
 "subtitle": "VISÃO GERAL · QUEM FAZ TUDO NÃO LIDERA NADA",
 "intro": "Dois primos idênticos, James e Jones: mesmas mães gêmeas, mesma inteligência, o mesmo cargo de chefia. E vidas opostas. Jones joga golfe, janta em casa e está com tudo sob controle; James pula o café, apaga incêndios e some debaixo da caixa de entrada. A única diferença entre eles não é dom — é um hábito que se aprende: <em>delegar</em>. Genett vira do avesso o velho ditado e prova que, se você quer bem feito, justamente <strong>não</strong> precisa fazer sozinho. O método cabe em seis passos, e quando ele falha a culpa é de quem delegou.",
 "description": "A parábola de gestão de Donna Genett. Pelos primos James e Jones — partida idêntica, finais opostos — ela mostra que delegar não é empurrar tarefa para baixo: é liderança e coaching disfarçados de tarefa. Os seis passos na ordem (preparar, discutir e repetir de volta, prazo, nível de autoridade, checkpoints, debriefing), os três níveis de autoridade (Recomendar / Informar e iniciar / Agir) e a meta provocadora de delegar 95% do que cruza a mesa. Pular um passo é a causa de quase todo fracasso — e quem se torna gargalo com o próprio nome.",
 "tags": ["Liderança", "Gestão", "Produtividade"],
 "progress": "8 Capítulos",
 "cover": "assets/poder-de-delegar-cover.png",
 "overview_cards": [
   {"ic":"steps","t":"Os Seis Passos da Delegação","b":"Delegar 'estilo Nike' — só sair fazendo — é o caminho mais curto para o fracasso. O método é deliberado e <strong>vale na ordem</strong>:","list":[
     "<strong>1. Preparar</strong> — resultado e propósito, antes de abrir a boca.",
     "<strong>2. Discutir</strong> — explicar e pedir para <strong>repetir de volta</strong>.",
     "<strong>3. Prazo</strong> — realista, com tempo de revisão embutido.",
     "<strong>4. Autoridade</strong> — dizer o nível e sair da frente.",
     "<strong>5. Checkpoints</strong> — pegar o desvio enquanto é barato.",
     "<strong>6. Debriefing</strong> — fechar o ciclo nos dois sentidos.",
   ],"tip":"<strong>Como aplicar:</strong> quando uma delegação dá errado, procure qual destes seis passos foi pulado. Quase sempre é um só.","wide":True},
   {"ic":"layers","t":"Os Três Níveis de Autoridade","b":"Delegar sem dizer quanto poder a pessoa tem produz micro-gerência ou abandono. Genett nomeia três graus, escolhidos por <strong>risco × experiência</strong>:","list":[
     "<strong>Recomendar</strong> — ela pesquisa e recomenda; você decide.",
     "<strong>Informar e iniciar</strong> — ela escolhe e avisa antes de agir.",
     "<strong>Agir</strong> — autonomia total.",
   ],"tip":"<strong>Regra:</strong> para só 'tirar da mesa', escolha quem já está em Agir; para desenvolver alguém, comece nos dois primeiros degraus.","wide":True},
   {"ic":"fork","t":"James vs. Jones","b":"Primos idênticos, finais opostos. <strong>Jones</strong> delega — e ainda sobra golfe, marcenaria e jantar em casa; <strong>James</strong> pula o café e vive afogado na caixa de entrada. Não trabalha mais que o primo: faz tudo sozinho. A meta da autora é radical — delegar <strong>~95%</strong> do que cruza a mesa.","tip":"<strong>Modelo mental:</strong> se a tarefa só anda quando você a toca, você não delegou — criou um gargalo com o seu nome estampado nele."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-parabola-james-jones","sub":"CAPÍTULO 1: A Parábola dos Primos",
  "intro":"Dois primos idênticos, a mesma largada e dois destinos opostos no trabalho. A única variável é uma habilidade que se aprende: delegar. Genett usa o contraste para virar do avesso o velho 'se quer bem feito, faça você mesmo' — e mostrar que ele é, na verdade, a receita do afogamento.",
  "cards":[
      {"ic":"fork","t":"Mesma Largada, Finais Opostos","emph":"Finais Opostos","b":"Mães gêmeas idênticas, pais melhores amigos, a mesma cabeça, o mesmo posto de chefia — e dois homens em vidas opostas. Jones delega; James faz tudo. Quando duas partidas idênticas terminam em lugares tão diferentes, a causa não pode ser talento: o talento era o mesmo. <strong>O que separa os primos é um hábito, não um dom.</strong>","tip":"<strong>Modelo mental:</strong> a distância entre afogar-se e liderar é, no fundo, o tamanho de uma técnica que um dos dois ainda não aprendeu."},
      {"ic":"clock","t":"James — o Anti-Modelo","emph":"Anti-Modelo","b":"James pula o café, e a hora de ir para casa depende de quantos incêndios apagou e de quão alta ficou a pilha na caixa de entrada. Ele não é preguiçoso nem incompetente — é o oposto: tão bom que não solta nada. E é esse, justamente, quem afunda primeiro. <strong>Quando tudo depende de você, tudo trava em você.</strong>","tip":"<strong>Sinal de alerta:</strong> viver ocupado não é o mesmo que estar no controle. Agenda refém do volume é sintoma, não medalha.","warn":True},
      {"ic":"leaf","t":"Jones — o Modelo","emph":"o Modelo","b":"Jones sai depois de um café sem pressa, volta para o jantar e ainda tem golfe, marcenaria e os filhos. Não trabalha menos que James nem é mais esperto — fez outra escolha com a mesma competência: <strong>transformou a própria capacidade na capacidade do time</strong>. Delegar não lhe tirou trabalho. Devolveu-lhe a vida.","tip":"<strong>Regra:</strong> delegar bem não é abrir mão do resultado — é recomprar tempo, foco e presença, que é o que James perdeu fazendo tudo."},
      {"ic":"key","t":"A Diferença se Aprende","emph":"se Aprende","b":"Jones ensina a James o seu método de seis passos, e a vida do primo muda — prova de que delegar não nasce com a pessoa, se aprende. Mas o livro carrega uma cláusula que incomoda todo chefe: <strong>quando a delegação fracassa, a falha é de quem delegou, não de quem recebeu.</strong> O dedo aponta para cima, não para baixo.","tip":"<strong>Modelo mental:</strong> delegar é liderança e coaching disfarçados de tarefa. Quem trata como 'empurrar serviço para baixo' já errou no primeiro gesto."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["A diferença entre afogar-se e liderar é método, não talento — e método se aprende.","Delegar bem não rouba trabalho de quem delega: devolve-lhe tempo, foco e vida.","Se a delegação deu errado, a conta é do delegador. Comece corrigindo o seu lado."]},

 {"slug":"ch02-passo1-preparar","sub":"CAPÍTULO 2: Passo 1 — Preparar",
  "intro":"Sair fazendo, sem pensar antes, é onde a maioria das delegações já nasce torta. Quanto melhor o preparo, melhor o resultado — e o preparo inteiro acontece em silêncio, antes de você chamar a pessoa para conversar.",
  "cards":[
      {"ic":"bulb","t":"Pense de Trás para Frente","emph":"de Trás para Frente","b":"Antes de chamar ninguém, Genett manda pensar a tarefa pelo fim. Três perguntas: a quem delegar, qual é o resultado exato e qual a probabilidade real de aquela pessoa entregá-lo. O passo parece dispensável justamente por ser invisível — ele acontece dentro da sua cabeça. <strong>Mas é aí que a delegação dá certo ou desanda, muito antes da primeira palavra.</strong>","tip":"<strong>Como aplicar:</strong> cinco minutos pensando o resultado poupam horas de retrabalho depois. A pressa não economiza tempo — ela o cobra com juros."},
      {"ic":"target","t":"Resultado e Propósito","emph":"Resultado e Propósito","b":"Duas frases governam tudo o que vem depois. O <strong>resultado</strong> é o que precisa existir ao final, sem brecha para interpretação; o <strong>propósito</strong> é por que você passa isto, a esta pessoa, agora. Trocar “quero o relatório pronto” por “quero formar a analista para assumir os relatórios” muda quem escolher, quanta autoridade dar e quantos checkpoints marcar.","tip":"<strong>Regra:</strong> sem resultado e propósito claros na sua cabeça, não abra a boca para delegar — você estaria terceirizando confusão, não tarefa."},
      {"ic":"pivot","t":"Coaching ou Produção?","emph":"Coaching ou Produção","b":"Existem duas razões muito diferentes para passar uma tarefa adiante: <strong>desenvolver a pessoa</strong> (coaching) ou simplesmente <strong>tirar trabalho da própria mesa</strong> (produção). Essa única decisão é o leme de todos os passos seguintes — ela define o encaixe pessoa × tarefa, o nível de autoridade e a frequência do acompanhamento.","tip":"<strong>Modelo mental:</strong> nomeie o propósito primeiro, sempre. É a pergunta-mãe que organiza, em cascata, todas as escolhas que vierem depois."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["Resultado e propósito vêm antes da conversa — e antes de escolher a quem delegar.","Escolha a pessoa pelo encaixe com a tarefa, não por quem está livre na hora.","Coaching ou produção: essa só decisão comanda autoridade, checkpoints e acompanhamento."]},

 {"slug":"ch03-passo2-discutir","sub":"CAPÍTULO 3: Passo 2 — Discutir / Repetir de Volta",
  "intro":"Uma conversa específica sobre a tarefa, encerrada com a pessoa repetindo de volta — com as palavras dela — o que entendeu. Só depois desse eco os dois estão, de fato, de acordo. Antes dele, cada um saiu da sala com uma tarefa diferente na cabeça.",
  "cards":[
      {"ic":"bubble","t":"Uma Conversa, Não uma Ordem","emph":"Conversa","b":"Delegar não é despachar instrução — é abrir uma conversa sobre a tarefa e o resultado. E há um detalhe que quase todo chefe esquece de dizer em voz alta: <strong>onde a pessoa tem liberdade criativa e onde não tem</strong>. Deixar essa fronteira no subentendido é apostar que ela vai adivinhar o seu gosto. Quase nunca adivinha — e o erro só aparece no fim.","tip":"<strong>Cuidado:</strong> ambiguidade não evapora sozinha. Ela só muda de endereço — vai morar no retrabalho, onde sai bem mais cara do que custaria esclarecer agora."},
      {"ic":"link","t":"O Poder do Repetir de Volta","emph":"Repetir de Volta","b":"Feche toda delegação pedindo que a pessoa diga, com as próprias palavras, o que vai entregar. Ouvir a reformulação faz as lacunas aparecerem <strong>antes</strong> de o trabalho começar — quando consertá-las custa trinta segundos, e não um relatório inteiro refeito. É o passo mais barato de todo o método. Também é o mais pulado.","tip":"<strong>Como aplicar:</strong> nunca pergunte “ficou claro?” — a resposta é sempre um “sim” automático. Peça antes “me conta, com as suas palavras, o que você vai fazer”."},
      {"ic":"lens","t":"As Quatro Perguntas de Preparo","emph":"Quatro Perguntas","b":"Para entrar na conversa pronto, responda quatro coisas antes: o que precisa ser feito de um jeito específico? onde ela tem liberdade? que resultados concretos eu espero? e qual a <strong>probabilidade real de ela entregar</strong>? Sem essas respostas, a conversa vira improviso — e o improviso é exatamente o terreno onde a ambiguidade cresce.","tip":"<strong>Regra:</strong> “entendi” não é prova de entendimento, é educação. A única prova é a pessoa reformular sozinha aquilo que acabou de ouvir."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["Feche toda delegação com o repetir de volta: o passo mais barato e o mais ignorado.","Diga em voz alta onde há liberdade criativa e onde não há — não deixe no subentendido.","A ambiguidade que você não esclarece agora volta, mais cara, em forma de retrabalho."]},

 {"slug":"ch04-passo3-prazo","sub":"CAPÍTULO 4: Passo 3 — Prazo",
  "intro":"De todos os passos, o prazo é o que mais parece óbvio — e é onde os chefes mais tropeçam. Ele precisa ser realista, alcançável e pensado dentro da carga real da pessoa, com tempo de revisão já embutido. Data jogada no ar não é prazo; é torcida.",
  "cards":[
      {"ic":"clock","t":"Realista e Alcançável","emph":"Alcançável","b":"O prazo tem de caber na carga real da pessoa — ainda mais se for um <strong>desafio que a estica</strong> ou algo que ela nunca fez antes. E quando a data é inflexível, a flexibilidade só pode vir de outro lugar: escolher alguém com a agenda mais leve, alguém já comprovadamente confiável, ou partir a tarefa em pedaços menores.","tip":"<strong>Regra:</strong> com prazo apertado, delegue conforme a folga de quem pode dar conta — não conforme quem está livre. Disponível não é sinônimo de adequado."},
      {"ic":"steps","t":"Tempo de Revisão Embutido","emph":"Tempo de Revisão","b":"O primeiro “pronto” quase nunca é o “pronto” de verdade. Se a pessoa talvez precise ajustar, <strong>reserve essa folga já no começo do prazo</strong>, e não no fim — senão você chega à entrega com o resultado torto e margem zero para consertar. A data deixa de ser um ponto único e vira um plano pequeno: rascunho, revisão, fechamento.","tip":"<strong>Modelo mental:</strong> prazo sem tempo de revisão embutido é prazo de mentira. Ele promete uma margem de manobra que, na hora do aperto, não vai existir."},
      {"ic":"scale","t":"Prioridade Relativa","emph":"Prioridade Relativa","b":"A tarefa nova nunca chega num colo vazio: entra numa fila que a pessoa já carrega. Diga, sem rodeio, onde ela se encaixa diante de tudo o que você já delegou. Isso vira crítico ao delegar <strong>entre departamentos</strong> — ali, dois chefes podem, cada um na sua, jurar que a SUA tarefa é a urgente.","tip":"<strong>Cuidado:</strong> conflito de prioridade que ninguém viu atrasa tudo sem soar alarme. Alinhe as filas antes que elas se choquem em silêncio.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["Embuta a revisão no início do prazo: o primeiro resultado raramente é o final.","Diga, sem deixar implícito, onde a nova tarefa entra na fila de prioridades da pessoa.","Prazo rígido muda quem deve receber a tarefa — não force a data, ajuste a escolha."]},

 {"slug":"ch05-passo4-autoridade","sub":"CAPÍTULO 5: Passo 4 — Nível de Autoridade",
  "intro":"Entregar a tarefa sem dizer quanto poder vem junto é receita de dois desastres: ou você micro-gerencia, sufocando a pessoa, ou some, abandonando-a. Genett resolve o impasse com três níveis nomeados — diga em voz alta qual é, e então saia da frente.",
  "cards":[
      {"ic":"layers","t":"Os Três Níveis de Autoridade","emph":"Três Níveis","b":"Genett dá nome a três graus de poder. <strong>Recomendar</strong>: a pessoa pesquisa e recomenda — quem decide é você. <strong>Informar e iniciar</strong>: ela escolhe e te avisa antes de agir. <strong>Agir</strong>: autonomia total, sem pedir licença. O nível precisa ser dito em voz alta no ato de delegar — nunca deixado no ar, para que cada um adivinhe o seu.","tip":"<strong>Como aplicar:</strong> autoridade é um botão com graus, não um interruptor de tudo-ou-nada. Escolha o ponto certo da escala — não viva nos extremos.","wide":True},
      {"ic":"scale","t":"Risco Cruzado com Experiência","emph":"Risco × Experiência","b":"Quem decide o nível não é a pressa nem a simpatia — é o cruzamento de duas variáveis: o <strong>risco</strong> da tarefa e a <strong>experiência</strong> da pessoa. Dar “Agir” a quem mal está pronto para “Recomendar” é convidar o desastre; tratar um veterano como novato o sufoca e o esvazia. A matriz aponta o grau certo antes que o seu instinto erre.","tip":"<strong>Regra:</strong> deixe risco × experiência escolher o nível — não o quanto você gosta da pessoa, nem o quanto está atrasado."},
      {"ic":"steps","t":"A Escada de Progressão","emph":"Escada","b":"Os três níveis não são castas fixas — são degraus de uma escada. A pessoa <strong>sobe de Recomendar para Informar e iniciar, e daí para Agir</strong>, à medida que prova competência. Isso também resolve a escolha de quem recebe: para só tirar da mesa, pegue quem já está em Agir; para formar alguém, comece nos dois primeiros degraus.","tip":"<strong>Modelo mental:</strong> cada delegação é também um plano de desenvolvimento. Uma tarefa bem entregue pode promover a pessoa um degrau na escada."},
      {"ic":"key","t":"Diga o Nível e Saia da Frente","emph":"Saia da Frente","b":"Nomear o nível só vale se você honrá-lo depois. Definido o grau, <strong>intervir abaixo dele é micro-gerência; ignorá-lo de vez é negligência</strong>. O nível de autoridade é um contrato silencioso que liberta os dois lados: a pessoa para agir sem bater na sua porta a cada passo, e você para tirar o olho do operacional e cuidar do que é seu.","tip":"<strong>Cuidado:</strong> respeite o nível nos dois sentidos. Não aperte mais do que combinou — nem solte mais do que prometeu."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Nomeie o nível em voz alta — Recomendar, Informar e iniciar ou Agir — no ato de delegar.","Escolha o grau por risco × experiência; deixe a pessoa subir a escada conforme prova.","Definido o nível, honre-o nos dois sentidos: nem micro-gerência, nem abandono."]},

 {"slug":"ch06-passo5-checkpoints","sub":"CAPÍTULO 6: Passo 5 — Checkpoints",
  "intro":"Checkpoints são reuniões de progresso marcadas no calendário desde o ato de delegar — próximas no começo, espaçando à medida que a pessoa domina a tarefa. Existem para pegar o desvio enquanto corrigi-lo ainda é barato, e não no prazo final, quando já virou refazer tudo.",
  "cards":[
      {"ic":"pivot","t":"Cadência Decrescente","emph":"Cadência Decrescente","b":"Checkpoints se agendam no ato de delegar, não “quando der” — porque “quando der” nunca dá. E a frequência segue um arco: <strong>juntos e frequentes no início, mais espaçados conforme a pessoa pega o jeito</strong>. Não é vigilância de capataz; é uma rede de segurança que se afrouxa sozinha à medida que a confiança cresce.","tip":"<strong>Modelo mental:</strong> aperte cedo, solte depois. O custo de consertar um erro sobe a cada dia de silêncio entre vocês."},
      {"ic":"eye","t":"O Roteiro do Checkpoint","emph":"Roteiro","b":"Cada checkpoint tem uma sequência: conferir o feito contra os <strong>critérios combinados no Passo 2</strong>, apontar ajustes com um novo repetir de volta das mudanças, perguntar por problemas de prazo e de autoridade, encorajar, dar coaching e marcar o próximo encontro. A régua é sempre o que foi acordado — nunca um padrão novo que apareceu na sua cabeça hoje.","tip":"<strong>Regra:</strong> meça contra o combinado no início, não contra a expectativa que brotou agora. Mudar a régua no meio do jogo é injusto — e a pessoa percebe."},
      {"ic":"link","t":"Mate a Delegação Reversa","emph":"Delegação Reversa","b":"Delegação reversa é a tarefa voltando ao colo do chefe: a pessoa trava, devolve o problema, e o gestor reassume — virando James de novo. A defesa não é pegar de volta, é <strong>fazer uma pergunta: “o que você já tentou e o que ainda falta?”</strong> Isso devolve a bola ao campo dela, agora com coaching, e mantém a delegação de pé.","tip":"<strong>Sinal de alerta:</strong> cada “deixa que eu resolvo” recoloca o operacional no colo do líder e desfaz, em segundos, o que a delegação levou semanas para construir.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Marque os checkpoints no ato de delegar — “quando der” é o checkpoint que nunca acontece.","Cadência decrescente: um erro pequeno pego cedo evita o desastre grande no prazo final.","No travamento, devolva uma pergunta — não reassuma a tarefa, ou você vira James de novo."]},

 {"slug":"ch07-passo6-debriefing","sub":"CAPÍTULO 7: Passo 6 — Debriefing",
  "intro":"Terminada a tarefa, vem uma conversa de mão dupla sobre como foi. É o passo que transforma uma entrega isolada em aprendizado que se acumula — e é, de longe, o passo mais pulado, porque parece dispensável justo quando 'deu tudo certo'.",
  "cards":[
      {"ic":"spiral","t":"Investigação Neutra","emph":"Investigação Neutra","b":"O passo mais pulado de todos: a conversa sobre como foi. E a ordem muda tudo. Pergunte <strong>primeiro</strong> como a própria pessoa acha que se saiu; só depois dê o seu retorno; então comparem as duas leituras. Curiosidade antes de veredito é o que converte o que seria um tribunal em aprendizado de verdade.","tip":"<strong>Como aplicar:</strong> abra pela autoavaliação dela, não pelo seu julgamento. Quem fala primeiro define se a conversa vai investigar ou condenar."},
      {"ic":"bubble","t":"A Inversão do Espelho","emph":"Inversão do Espelho","b":"O debriefing de Genett tem um movimento raro nas empresas: peça que a pessoa avalie <strong>você como delegador</strong>. Você dá a sua autoavaliação, comparam as duas. Quem delega também presta contas — e esse gesto simples desarma o de-cima-para-baixo, revela onde o seu pedido saiu confuso e conserta o sistema, não apenas a pessoa.","tip":"<strong>Regra:</strong> o ciclo só fecha quando os dois lados saem melhores para a próxima rodada. Feedback de mão única arruma só metade do problema — a metade mais fácil."},
      {"ic":"book","t":"As Cinco Funções","emph":"Cinco Funções","b":"Uma só conversa faz cinco trabalhos: <strong>reforçar o crescimento, apontar onde desenvolver, aplaudir o acerto, registrar problemas de desempenho e dar coaching de verdade</strong>. Quem pula o debriefing porque “deu certo” joga os cinco fora de uma vez — e garante que a próxima delegação repita exatamente os mesmos atritos.","tip":"<strong>Modelo mental:</strong> sem debriefing, o aprendizado evapora junto com a entrega. O que você registrar aqui vira a matéria-prima do próximo Passo 1."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["Comece pela autoavaliação da pessoa: curiosidade antes de veredito (investigação neutra).","Inverta o espelho — peça que ela avalie você como delegador; quem delega também presta contas.","Registre o que ficou: o debriefing de hoje é o insumo do preparo de amanhã."]},

 {"slug":"ch08-aplicacoes","sub":"CAPÍTULO 8: Aplicações & a Regra dos 95%",
  "intro":"Os seis passos não são burocracia de manual — são exatamente o que deixa um líder se multiplicar em vez de se afogar. E Genett leva a tese ao limite: um chefe deveria delegar cerca de 95% do que cruza a sua mesa, ficando só com o punhado que ninguém mais pode fazer no lugar dele.",
  "cards":[
      {"ic":"mountain","t":"A Regra dos 95%","emph":"95%","b":"A tese, levada ao extremo: um líder deveria delegar perto de <strong>95% do que cruza a sua mesa</strong>, guardando para si apenas o estratégico — o trabalho que só ele pode fazer. O número não é preguiça, é foco. Quase tudo que chega pode e deve sair das suas mãos, para que elas sobrem livres para os 5% em que você é insubstituível.","tip":"<strong>Modelo mental:</strong> o 95% é meta de foco, não de fuga. O 5% que resta não é o que você não quer largar — é o único lugar onde a sua presença é única.","wide":True},
      {"ic":"spark","t":"Multiplicar, Não Somar","emph":"Multiplicar","b":"Fazer você mesmo <strong>soma</strong> uma pessoa ao resultado; delegar bem <strong>multiplica</strong> a capacidade do time inteiro. E os ganhos se acumulam: mais entrega, menos esgotamento, carga mais leve, gente mais forte, moral e retenção em alta. O “é mais rápido eu fazer” é verdade hoje e cilada amanhã — porque ninguém, do seu lado, está aprendendo a fazer no seu lugar.","tip":"<strong>Regra:</strong> desconfie sempre do “mais rápido eu mesmo”. É o juro barato de hoje que, somado, vira o gargalo com o seu nome estampado nele."},
      {"ic":"target","t":"Delegar Como Sistema","emph":"Como Sistema","b":"Os seis passos não são um checklist de uso único — são um <strong>ciclo</strong>: o debriefing de uma tarefa vira o preparo da seguinte. Rodado de novo e de novo, ele forma pessoas enquanto entrega resultados, e desarma a delegação reversa juntando autoridade clara com checkpoints. James vira Jones não trabalhando mais — mas pondo essa engrenagem para girar.","tip":"<strong>Como aplicar:</strong> trate os seis passos como engrenagem que repete. Cada volta deixa a próxima delegação um pouco mais barata, mais rápida e mais segura."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Mire em delegar quase tudo — guarde para si só o que ninguém mais pode fazer.","Delegar multiplica a capacidade do time; fazer sozinho apenas soma — e vira gargalo.","Os seis passos são um ciclo: o debriefing de hoje alimenta o preparo de amanhã. James vira Jones rodando-o."]},
]
