# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'O Poder dos Quietos' (Susan Cain)."""

BOOK = {
 "title": "O Poder dos Quietos",
 "author": "Susan Cain",
 "header_light": "O PODER DOS",
 "header_bold": "QUIETOS",
 "subtitle": "VISÃO GERAL · A FORÇA QUE NÃO PRECISA DE PLATEIA",
 "intro": "Um terço da humanidade recarrega no silêncio — e vive sendo gentilmente convencida de que há algo a consertar nisso. Susan Cain devolve a esse terço a sua dignidade. Sob o <strong>Ideal da Extroversão</strong>, aprendemos a confundir falar muito com pensar bem e ousadia com competência. Mas a quietude tem um currículo próprio: foco, profundidade, escuta, persistência. Não se trata de virar barulhento. Trata-se de descobrir que a sua natureza nunca foi o defeito — era o instrumento.",
 "description": "O livro de Susan Cain que reabilitou os introvertidos. A ascensão histórica do Ideal da Extroversão e o que ele nos custa, a biologia da alta reatividade de Kagan, a teoria do elástico e dos traços livres ancorados em nichos restauradores, o mito do brainstorming e do escritório aberto, a liderança que vence calada e a arte de florescer sem fingir ser outra pessoa.",
 "tags": ["Introversão", "Autoconhecimento", "Liderança"],
 "progress": "9 Capítulos",
 "cover": "assets/poder-dos-quietos-cover.png",
 "overview_cards": [
   {"ic":"layers","t":"A Bateria é o Segredo","b":"A linha que separa introvertido de extrovertido não é a timidez nem a falta de jeito — é <strong>onde você se recarrega</strong>. O quieto repõe energia na quietude e a gasta no convívio; com o expansivo, é o contrário. É um espectro, não duas caixas: introversão não é timidez, e timidez não é antissociabilidade.","tip":"<strong>Como aplicar:</strong> trate a sua dose de silêncio como combustível, não como fuga. Intercale a vida social com recuperação planejada — sem pedir desculpas por ela."},
   {"ic":"spark","t":"Esticar Sem Se Trair","b":"Você pode, sim, agir como <strong>pseudo-extrovertido</strong> — mas só vale a pena pelas poucas causas que você ama de verdade, e só dá certo se houver <strong>nichos restauradores</strong> esperando do outro lado: refúgios que devolvem o seu eu verdadeiro. Atuar fora do traço por longo tempo, sem refúgio, adoece.","tip":"<strong>Modelo mental:</strong> escolha as raras batalhas que merecem o esforço — e combine, de antemão, a recompensa de quietude que paga a conta de cada uma."},
   {"ic":"eye","t":"O Ideal da Extroversão","b":"Em um século, a cultura trocou a <strong>Cultura do Caráter</strong> (quem você é quando ninguém vê) pela <strong>Cultura da Personalidade</strong> (como você se vende quando todos veem). Desde então, julgamos a competência pelo volume da voz — mas eloquência nunca foi sinônimo de acerto.","tip":"<strong>Sinal de alerta:</strong> quando a 'melhor ideia da sala' é sempre a de quem fala mais alto, não é a sala que está acertando — é o Ideal que está mandando.","wide":True},
 ],
}

CHAPTERS = [
 {"slug":"ch01-o-ideal-da-extroversao","sub":"CAPÍTULO 1: O Ideal da Extroversão",
  "intro":"Em algum momento, sem que ninguém anunciasse, o Ocidente elegeu um eu ideal: gregário, falante, à vontade sob os holofotes. Susan Cain reconstitui essa virada silenciosa — do caráter para a personalidade — e mostra o que perdemos ao tratar a metade quieta da humanidade como um rascunho a corrigir.",
  "cards":[
      {"ic":"eye","t":"O Ideal da Extroversão","emph":"Ideal","b":"A cultura moderna ergueu um altar discreto ao falante seguro de si, e quase ninguém percebeu a cerimônia. Aos poucos, passamos a tratar como competente apenas quem domina a reunião com carisma. <strong>Confundimos a confiança de quem fala bem com a capacidade de quem pensa bem — e raramente são a mesma pessoa.</strong>","tip":"<strong>Como aplicar:</strong> separe o estilo da substância. A melhor ideia quase nunca é a que chegou primeiro, nem a que veio mais alto."},
      {"ic":"pivot","t":"Do Caráter à Personalidade","emph":"Personalidade","b":"Houve um tempo em que se admirava o caráter: o que a pessoa era na intimidade, longe de plateia. Então as cidades incharam, a venda virou ofício, e o critério mudou. <strong>Passamos a premiar a personalidade magnética — quem sabe encantar estranhos — ainda quando por trás do brilho não há nada de novo.</strong> A quietude foi rebaixada a defeito.","tip":"<strong>Modelo mental:</strong> quem gasta toda a energia em agradar a plateia raramente sobra tempo para o trabalho lento de aprofundar o próprio pensamento."},
      {"ic":"mask","t":"O Preço do Palco","emph":"Preço","b":"Quando a cultura exige que todos sejam apresentadores radiantes, metade das pessoas vive num cansaço que não sabe nomear. <strong>Obrigar o introvertido a vestir o carisma o dia inteiro não só o esgota: priva a equipe inteira do foco analítico que só nasce em quem pensa em silêncio.</strong> A conta chega para os dois lados.","tip":"<strong>Sinal de alerta:</strong> antes de promover quem apresenta o projeto com mais sorriso, repare em quem o resolveu — muitas vezes é alguém que não pediu o microfone."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["O Ideal da Extroversão é invenção cultural recente, não lei da natureza — e o que se inventou pode ser revisto.","O Ocidente migrou do caráter (quem você é no privado) para a personalidade (como você se mostra em público).","Premiar um só temperamento cobra um preço real — de quem é quieto e de quem perde o que ele tinha a oferecer."]},

 {"slug":"ch02-introversao-extroversao-e-energia","sub":"CAPÍTULO 2: Introversão, Extroversão e Energia",
  "intro":"Antes de tudo, ser quieto ou expansivo é uma questão de onde você busca energia e de quanto estímulo o seu sistema suporta com prazer. Compreender essa raiz simples desfaz, de uma vez, quase todos os mal-entendidos que cercam os introvertidos.",
  "cards":[
      {"ic":"spark","t":"Onde Você Recarrega","emph":"Bateria","b":"O temperamento não se mede pela facilidade de conversar, e sim pela direção em que a energia corre. O convívio prolongado descarrega o introvertido, que precisa de recolhimento para voltar a si; o expansivo faz o caminho inverso, e murcha no isolamento. <strong>A mesma festa que ilumina um deixa o outro de reserva esgotada.</strong>","tip":"<strong>Como aplicar:</strong> sair mais cedo de um evento não é falha de educação. É manutenção. O seu sistema pede silêncio como o corpo pede ar."},
      {"ic":"wave","t":"A Dose Certa de Estímulo","emph":"Estímulo","b":"Cada cérebro tem o seu ponto ótimo. O quieto rende melhor com luz baixa e poucas interrupções; ruído demais o trava. O expansivo, esse, cochila no sossego e só desperta no movimento. <strong>A entrega despenca quando se obriga a própria biologia a trabalhar no ambiente do outro temperamento.</strong>","tip":"<strong>Modelo mental:</strong> defender o seu ambiente de trabalho não é frescura — é cuidar da única variável que você de fato controla na sua produtividade."},
      {"ic":"fork","t":"Timidez Não É Introversão","emph":"Timidez","b":"A timidez é medo do julgamento alheio; a introversão é só uma preferência pelos bastidores. São duas coisas distintas que vivem sendo confundidas. <strong>Dá para ser um introvertido perfeitamente à vontade, que fala em público sem tremer — e que depois precisa de dias de quietude para se recompor.</strong>","tip":"<strong>Cuidado:</strong> a sua necessidade de paz não é um complexo a ser curado. É um traço a ser respeitado — a começar por você."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["O que separa os temperamentos é a fonte de energia e a dose ideal de estímulo — não a habilidade social.","Introversão, timidez e antissociabilidade são três coisas diferentes; confundi-las é a origem de quase todo o preconceito.","É um espectro, não duas caixas: os ambivertidos existem e todos nós nos movemos conforme o contexto."]},

 {"slug":"ch03-temperamento-e-biologia","sub":"CAPÍTULO 3: Temperamento e Biologia",
  "intro":"A introversão começa antes da personalidade — começa no berço. Jerome Kagan acompanhou bebês 'altamente reativos' que se agitavam diante do novo e os viu crescer como adultos mais cautelosos e reflexivos. Reagir muito ao mundo nunca foi fragilidade: é um sistema nervoso de alta fidelidade, afinado para captar o que os outros não notam.",
  "cards":[
      {"ic":"leaf","t":"O Bebê Que Sente Demais","emph":"Reativo","b":"O bebê que se sobressalta com cada novidade não é frágil — é minucioso: o sistema nervoso dele registra cada detalhe do ambiente em alta definição. <strong>Essa alta reatividade é o berço biológico da introversão. A pessoa cautelosa não recua por medo; recua porque está captando tudo ao mesmo tempo.</strong>","tip":"<strong>Modelo mental:</strong> pense no cérebro introvertido como uma antena de altíssima sensibilidade. Ele faz uma pausa não por fraqueza, mas porque recebeu o sinal inteiro de uma vez."},
      {"ic":"mountain","t":"A Sensibilidade Fina","emph":"Sensibilidade","b":"A química importa mais do que se admite. O quieto cansa mais cedo com cafeína, ruído e conversas sobrepostas. <strong>O que o mundo às vezes lê como desinteresse é só um sistema pedindo uma pausa para digerir a enxurrada de informação do dia.</strong>","tip":"<strong>Como aplicar:</strong> mapeie os seus gatilhos de sobrecarga e proteja, sem culpa, as horas em que você ainda pensa com clareza — em geral, as primeiras."},
      {"ic":"triangle","t":"Orquídeas e Dentes-de-Leão","emph":"Orquídea","b":"Os mais sensíveis definham depressa em lares ásperos e escritórios hostis. Mas, no ambiente certo, esses mesmos definhantes desabrocham acima da média, deixando os colegas robustos para trás. <strong>A sensibilidade que o expõe ao estresse é a mesma que sustenta a sua empatia e o seu foco mais profundo.</strong>","tip":"<strong>Modelo mental:</strong> pare de se comparar com o capim que cresce em qualquer rachadura. Você é orquídea: dê-se o solo e a luz certos, e o que você entrega não tem comparação."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["A introversão tem raiz biológica e parcialmente herdada — a alta reatividade descrita por Kagan.","Em média, o introvertido é mais sensível ao estímulo e atinge a sobrecarga mais cedo: é fisiologia, não manha.","Alta sensibilidade tem dois lados: a orquídea sofre no ambiente errado e brilha no certo — o entorno decide."]},

 {"slug":"ch04-elastico-e-tracos-livres","sub":"CAPÍTULO 4: O Elástico e os Traços Livres",
  "intro":"O temperamento não é uma cela. A personalidade tem a elasticidade de um elástico: estica para fora do traço quando algo que importa pede — mas dentro de um limite, e sempre ao custo de energia. A teoria dos traços livres ensina a fazer isso a serviço do que amamos, sem se perder no caminho.",
  "cards":[
      {"ic":"spiral","t":"A Teoria do Elástico","emph":"Elástico","b":"A biologia desenha a sua faixa natural, mas a sua vontade pode esticá-la por um tempo: dá para ser sociável quando a ocasião exige. <strong>O perigo não está em esticar — está em esquecer que existe um limite. Viver esticado mês após mês não fortalece a corda; gasta-a.</strong>","tip":"<strong>Como aplicar:</strong> escolha as poucas ocasiões que merecem você no palco. Nas demais, deixe o elástico voltar ao repouso — é ali que você se renova."},
      {"ic":"target","t":"A Atuação Que Vale a Pena","emph":"Propósito","b":"Vestir a desenvoltura de um extrovertido só se sustenta quando a causa por trás vale o esforço. <strong>Conseguimos agir fora da nossa natureza sem nos ferir quando é para servir um projeto que é o sentido da nossa vida, ou alguém que amamos.</strong> Aí a atuação é autêntica, não disfarce.","tip":"<strong>Modelo mental:</strong> esticar para agradar a vaidade de um chefe esvazia; esticar para erguer o que é seu energiza. O mesmo gesto, motivos opostos."},
      {"ic":"leaf","t":"O Nicho Restaurador","emph":"Nicho","b":"O elástico cobra o seu preço, e o preço é o descanso. Para cada hora de extroversão forçada, você precisa de um nicho restaurador garantido depois. <strong>Fechar a porta, silenciar o telefone e ler um livro não é luxo de ermitão: é a recarga que devolve você a si mesmo e ao trabalho.</strong>","tip":"<strong>Sinal de alerta:</strong> lotar a agenda social de sexta a domingo, sem nenhuma brecha de quietude, é o caminho mais curto para o esgotamento de quem é quieto."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["Podemos agir fora do traço, mas dentro de limites e sempre pagando em energia — não é de graça.","Esticar vale a pena pelos projetos centrais da vida: aí a pseudo-extroversão é uma escolha autêntica, não uma máscara.","Sem nicho restaurador para repor o eu verdadeiro, atuar fora do traço acaba cobrando a conta na saúde."]},

 {"slug":"ch05-mito-da-colaboracao","sub":"CAPÍTULO 5: O Mito da Colaboração",
  "intro":"O Novo Pensamento de Grupo prega que toda boa ideia nasce do barulho da colaboração. Décadas de pesquisa dizem o contrário: o brainstorming em grupo e o escritório aberto costumam empobrecer a criatividade, não multiplicá-la. A solitude, tão fora de moda, segue sendo condição do trabalho que vai fundo.",
  "cards":[
      {"ic":"bubble","t":"O Mito do Brainstorming","emph":"Mito","b":"A fé de que as melhores ideias surgem de grupos animados ao redor de uma lousa não resiste aos dados. Em reunião, a originalidade encolhe: uns se acomodam no esforço dos outros, e o medo do julgamento cala quem pensa diferente. <strong>Quase sempre, pessoas pensando sozinhas e somando os resultados depois produzem mais e melhor que o comitê reunido.</strong>","tip":"<strong>Como aplicar:</strong> mande o problema antes, por escrito, para cada um pensar no seu canto. Reúna o grupo só depois — para escolher, não para gerar."},
      {"ic":"lens","t":"O Custo do Escritório Aberto","emph":"Custo","b":"Derrubaram as paredes para forçar a colaboração e, sem querer, derrubaram a concentração junto. Espaços sem qualquer abrigo elevam o estresse, fragmentam a atenção e cansam a equipe inteira. <strong>Perder o controle sobre quem interrompe o seu trabalho é um dos maiores ralos de produtividade do mundo moderno.</strong>","tip":"<strong>Modelo mental:</strong> num escritório barulhento, o fone de ouvido raramente é sobre música. É a única parede portátil que sobrou para quem precisa pensar."},
      {"ic":"mountain","t":"A Solitude da Maestria","emph":"Solitude","b":"A excelência se constrói na prática deliberada, e essa quase sempre pede recolhimento: é sozinho, sem plateia, que se ataca o ponto fraco e se aprofunda o domínio. <strong>A execução pode ser coletiva, mas o salto criativo costuma nascer de uma mente trabalhando a sós — não do consenso confortável de uma sala cheia.</strong>","tip":"<strong>Regra:</strong> não confunda espírito de equipe com a obrigação de pensar em bando. Colabore na hora certa; reserve a quietude para o trabalho que de fato exige profundidade."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["O brainstorming em grupo presencial costuma piorar a criatividade — pense sozinho primeiro, combine depois.","O escritório aberto cobra foco, calma e produtividade; proteger a privacidade e o silêncio é investir no trabalho.","A maestria pede solitude e prática deliberada, não convívio o tempo todo."]},

 {"slug":"ch06-poder-silencioso","sub":"CAPÍTULO 6: O Poder Silencioso",
  "intro":"A quietude é uma forma de poder — só que não se anuncia. Diante de equipes proativas, líderes introvertidos rendem mais que os expansivos; na negociação, na influência e na obstinação, os quietos vencem com armas que não fazem barulho e, por isso mesmo, raramente são vistas chegando.",
  "cards":[
      {"ic":"person","t":"O Líder Que Sabe Ouvir","emph":"Ouvir","b":"Equipes cheias de iniciativa florescem sob quem fala menos. O líder quieto não precisa ocupar o centro das atenções, e por isso não sufoca a ideia boa só para defender o próprio palco. <strong>Ele abre espaço — e o talento à sua volta, livre da vaidade do chefe, aplica as melhores soluções.</strong>","tip":"<strong>Como aplicar:</strong> se a equipe trava, assuma o leme; se ela voa sozinha, recolha-se, registre os acertos e a sua função vira só remover os obstáculos."},
      {"ic":"bubble","t":"O Poder do Silêncio na Mesa","emph":"Silêncio","b":"O negociador afobado entrega os próprios limites na pressa de fechar. O quieto faz outra coisa: investiga as brechas, escuta o que não foi dito e deixa o silêncio trabalhar por ele. <strong>Recusar-se a preencher o vazio com retórica fácil costuma levar o outro lado a se mexer e a abrir as cartas primeiro.</strong>","tip":"<strong>Modelo mental:</strong> numa negociação, quem suporta melhor a pausa desconfortável quase sempre conduz o acordo. O silêncio é um instrumento — aprenda a deixá-lo soar."},
      {"ic":"clock","t":"A Força Quieta da Persistência","emph":"Persistência","b":"O carisma abre a porta; é o foco paciente que constrói a casa. O quieto tem uma capacidade discreta e teimosa de encarar o problema longo e a tarefa monótona sem desistir. <strong>Ele não precisa de aplauso para continuar — segue cavando no escuro muito depois de o entusiasmo dos outros ter ido embora.</strong>","tip":"<strong>Regra:</strong> a empolgação inicial murcha no primeiro tropeço. Quem volta à cadeira e faz, dia após dia, é quem derruba as muralhas que importam."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Diante de equipes proativas, a liderança introvertida supera a extrovertida — porque cede espaço em vez de ocupá-lo.","Escuta, preparo, calma e silêncio são armas silenciosas que decidem negociações e influência.","Boa parte da realização vem da persistência solitária, não só do carisma."]},

 {"slug":"ch07-criar-filhos-quietos","sub":"CAPÍTULO 7: Criar Filhos Quietos",
  "intro":"A criança quieta não veio com um defeito de fábrica para os pais corrigirem. Veio com um temperamento que pede ser respeitado — e ajudado a esticar, devagar e em segurança. O papel da casa e da escola não é envergonhar a sensibilidade, é nutri-la até ela virar força.",
  "cards":[
      {"ic":"leaf","t":"O Cuidado com a Orquídea","emph":"Orquídea","b":"O filho altamente reativo precisa de um ninho previsível e acolhedor. Submetê-lo a sustos e humilhações para 'endurecê-lo' não o fortalece — abala a base sobre a qual ele se apoia. <strong>O acolhimento caloroso de casa é justamente o que dá a essa criança a coragem de enfrentar o barulho do mundo lá fora.</strong>","tip":"<strong>Como aplicar:</strong> baixe os alarmes, reconheça o receio dela como um instinto legítimo, e só então convide-a — com calma — para o passo corajoso."},
      {"ic":"steps","t":"O Empurrão Gradual","emph":"Gradual","b":"Nem o choque brusco de quem joga a criança na água fria, nem a superproteção que a aprisiona. O caminho do meio é a exposição paciente e fracionada ao novo. <strong>Fique ao lado dela, mostre o ambiente antes, apresente uma pessoa de cada vez; alargue o mundo dela em pequenos passos, não em saltos.</strong>","tip":"<strong>Modelo mental:</strong> trate a coragem social do seu filho como um músculo. Carga demais de uma vez machuca; é a repetição leve e constante que faz crescer."},
      {"ic":"bulb","t":"Dê Nome à Força","emph":"Nomeie","b":"Tratar a quietude do filho como falha de caráter deixa marcas que o acompanham na vida adulta. As palavras dos pais viram a voz interior da criança. <strong>Se você elogiar a capacidade dela de ouvir e a profundidade do foco que ela tem, a introversão deixa de ser um estigma e passa a ser, aos olhos dela mesma, um dom.</strong>","tip":"<strong>Cuidado:</strong> não humilhe a criança em público exigindo sorrisos forçados para os parentes. Essa simpatia obrigada ensina a ela que ser quem é tem algo de errado."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["A criança quieta floresce em ambiente nutritivo — o entorno, mais que o temperamento, decide o resultado.","Ajude-a a esticar por exposição gradual: nem superproteção, nem empurrão bruto.","Reformule a quietude como força; a linguagem dos pais vira a imagem que o filho faz de si."]},

 {"slug":"ch08-relacionamentos-introvertido-extrovertido","sub":"CAPÍTULO 8: Relacionamentos Opostos",
  "intro":"Casais de temperamentos opostos vivem o mesmo atrito previsível: a dose de convívio e de estímulo que faz bem a um é exatamente a que sobrecarrega o outro. Ler esse desencontro como diferença de necessidade — e não de amor — é o que permite negociar a dose e, no fim, se completar.",
  "cards":[
      {"ic":"gap","t":"O Desencontro das Baterias","emph":"Baterias","b":"Um precisa de recolhimento para não se esgotar; o outro precisa de gente por perto para não definhar. <strong>Enquanto o casal não entende que a raiz disso é biológica, e não falta de amor, cada um lê o gesto do outro como rejeição — e adoece o que havia de bom.</strong>","tip":"<strong>Como aplicar:</strong> tire o gesto do plano pessoal. Ele não se recolhe porque amou menos; recolhe-se porque a bateria dele simplesmente acabou no fim do domingo."},
      {"ic":"scale","t":"Dois Jeitos de Brigar","emph":"Conflito","b":"Para o expansivo, levantar a voz é uma forma de descarregar a tensão e voltar ao normal. Para o introvertido, recuar é a defesa instintiva contra um caos que o machuca de verdade. <strong>Quando um persegue e o outro foge, os dois saem feridos e a questão original continua intacta.</strong>","tip":"<strong>Modelo mental:</strong> combinem regras antes do calor: tudo bem fazer uma pausa de meia hora — desde que ela venha com a promessa de voltar à conversa."},
      {"ic":"link","t":"A Dupla Que Se Completa","emph":"Completa","b":"Quando o ego sai do caminho, opostos formam uma parceria difícil de bater. Um abre as portas e atrai as pessoas; o outro cuida dos detalhes e ancora a casa. <strong>A diferença de temperamento deixa de ser motivo de briga e vira a maior vantagem que os dois têm juntos.</strong>","tip":"<strong>Regra:</strong> pare de tentar converter o outro ao seu jeito de ser. Joguem do mesmo lado, cada um fazendo o que faz melhor — é assim que opostos viram time."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["O atrito comum é a dose de convívio e estímulo — leia o recuo como necessidade, nunca como rejeição.","Os estilos de conflito diferem (evitar × confrontar); reconheça a diferença e faça uma pausa em vez de perseguir.","Negociem as quantidades e os sinais; opostos bem ajustados se completam em vez de se desgastar."]},

 {"slug":"ch09-quando-agir-como-o-oposto","sub":"CAPÍTULO 9: Quando Agir como o Oposto",
  "intro":"A meta nunca foi virar extrovertido, nem se esconder como introvertido. É outra, mais sábia: saber quando esticar para fora do traço — a serviço do que de fato importa — e quando honrar a própria natureza. Os nichos restauradores são o que tornam esse vaivém sustentável a vida inteira.",
  "cards":[
      {"ic":"key","t":"O Pacto do Traço Livre","emph":"Pacto","b":"Combine com quem convive com você, de forma aberta, em quais momentos você vai vestir a desenvoltura da extroversão — e o que isso pede em troca. <strong>O acordo é gentil e claro: eu me exponho e brilho na apresentação de hoje, e em troca tenho a manhã de amanhã só para mim, sem interrupções.</strong>","tip":"<strong>Como aplicar:</strong> não distribua a sua energia social a esmo. Cada hora de palco merece, logo depois, uma hora de quietude já reservada na agenda."},
      {"ic":"target","t":"Escolher Onde Esticar","emph":"Escolher","b":"Vale a pena esticar quando o esforço sustenta um valor que é central na sua vida. Quando o palco serve só à vaidade alheia ou à pressão do 'tem que ir', a resposta legítima é um não tranquilo. <strong>Aja fora do traço por amor ou por uma causa sua — nunca por obediência cega à etiqueta dos outros.</strong>","tip":"<strong>Regra:</strong> guarde a sua reserva limitada de sociabilidade intensa para o que realmente conta: as metas que são suas e as pessoas que você ama."},
      {"ic":"leaf","t":"A Restauração Inegociável","emph":"Restauração","b":"A única forma de atravessar uma temporada agindo fora da sua natureza sem se esgotar é reservar, de antemão, blocos intocáveis de recolhimento. <strong>A conta sempre chega: o cansaço se acumula em silêncio se você não abrir os espaços de quietude profunda em que ninguém o alcança.</strong>","tip":"<strong>Sinal de alerta:</strong> sacrificar as férias calmas e os fins de semana desligados para emendar um esforço no outro é o jeito mais certo de adoecer quem sente o mundo com intensidade."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["Esticar vale a pena quando o projeto é central, o ganho é alto e há como se recompor depois.","Aja o seu traço por padrão; aja o oposto por decisão deliberada, jamais por pressão difusa.","Todo esticar precisa de um nicho restaurador — sem ele, a conta vai parar na sua saúde."]},
]
