# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'Political Ponerology' de
Andrzej Łobaczewski. A gênese psicológica do mal social — em chave DEFENSIVA
(reconhecer para resistir). Ponerogênese, spellbinders, pathocracia."""

BOOK = {
 "title": "Ponerologia Política",
 "author": "Andrzej Łobaczewski",
 "header_light": "PONEROLOGIA",
 "header_bold": "POLÍTICA",
 "subtitle": "VISÃO GERAL · A CIÊNCIA DA GÊNESE DO MAL",
 "intro": "Łobaczewski foi psiquiatra sob um regime que ele teve de estudar de dentro, como um médico que adoece da própria doença que disseca. Sua aposta é fria e perturbadora: o mal que devora nações não é mistério teológico nem azar histórico, mas um processo clínico — tem causa, curso e estágios, como uma infecção. Uma minoria sem freios morais captura grupos e Estados; a maioria saudável, que não consegue sequer imaginar uma mente assim, é tomada de surpresa. Este livro é uma autópsia feita em vida: descreve o mecanismo não para repeti-lo, mas para vacinar quem ainda pode reconhecê-lo a tempo. <em>O que tem patogênese, tem profilaxia.</em>",
 "description": "A ponerologia de Łobaczewski: o estudo clínico da gênese do mal social, escrito por um psiquiatra que o observou por dentro de um regime. Ponerogênese, psicopatia essencial, spellbinders, paramoralismos, a máscara ideológica, a pathocracia e o ciclo histeroidal — diagnosticados friamente, em chave defensiva: nomear a patologia é a primeira dose da vacina. Lente de imunização, jamais manual.",
 "tags": ["Psicologia", "Política", "Sociedade"],
 "progress": "10 Capítulos",
 "cover": "assets/ponerologia-cover.png",
 "overview_cards": [
   {"ic":"eye","t":"A Ciência do Mal (defensiva)","b":"Tirar o mal social do altar da teologia e pô-lo na maca da clínica: não 'quem é o vilão', mas <strong>como o tecido sadio adoeceu</strong>. O propósito é <strong>imunológico</strong> — entender o mecanismo para reconhecê-lo no escuro e resistir, nunca para empunhá-lo.","tip":"<strong>Como aplicar:</strong> troque a pergunta 'quem é o culpado?' pela pergunta do patologista: 'por onde a infecção entrou?'.","wide":True},
   {"ic":"spiral","t":"Ponerogênese","b":"O mal de escala nacional não cai do céu: é <strong>incubado passo a passo</strong> — fator patológico, falha moral e cegueira intelectual se trançam numa cadeia causal. Um grupo são adoece em silêncio, um degrau de cada vez, e cada degrau era uma chance perdida de travar a roda.","tip":"<strong>Chave:</strong> a seleção negativa expulsa os íntegros e promove os cínicos — quando os medíocres mandam, a doença passou da linha."},
   {"ic":"mask","t":"Spellbinders e a Máscara","b":"O enfeitiçador captura a massa com <strong>certeza total, um inimigo único e a dúvida proibida</strong>, e veste o crime com a roupa da virtude (o paramoralismo). Por cima de tudo, uma <strong>ideologia nobre</strong> que serve de máscara — recruta o idealista e blinda o predador.","tip":"<strong>Modelo mental:</strong> não meça o discurso; meça a distância entre a bandeira hasteada e os atos cometidos em seu nome."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-ciencia-do-mal","sub":"CAPÍTULO 1: A Ciência do Mal",
  "intro":"A premissa que funda tudo: o mal social é um fenômeno natural, com origem e curso, e portanto algo que se diagnostica e se previne — não um enigma moral a lamentar. O olhar é declaradamente defensivo, o de quem estuda a peste para não morrer dela.",
  "cards":[
      {"ic":"eye","t":"Ponerologia","emph":"Ponerologia","b":"O mal que esmaga povos inteiros não desaba como um raio do céu — é construído no chão, devagar, por mãos que ninguém vê. A ponerologia o retira do altar da teologia e o deita na maca da dissecação. <strong>O que se cataloga clinicamente, com causa e mecanismo, também se contém antes de alastrar.</strong>","tip":"<strong>Como aplicar:</strong> trate o mal social como um patógeno observável — aquilo que tem mecanismo tem ponto de bloqueio."},
      {"ic":"scale","t":"Clínico, Não Moralista","emph":"Clínico","b":"Bater no peito e gritar palavras de ordem contra o tirano é um alívio que cega. A indignação queima toda a energia e apaga a inteligência tática de que se precisa para enxergar o mecanismo. <strong>Só o olhar frio do patologista mapeia a estrutura da doença sem ser contaminado pela histeria que ela mesma fabrica.</strong>","tip":"<strong>Modelo mental:</strong> indignar-se é fácil e estéril; diagnosticar os nós do poder exige a disciplina gelada de quem segura o bisturi."},
      {"ic":"gap","t":"Usar a Lente para Atacar","emph":"Usar a Lente","b":"Carimbar de 'psicopata' todo político que se detesta é vandalizar um instrumento cirúrgico. A lente nasceu para a observação atenta e a defesa, não para a pedrada de esquina. <strong>Reduzir a catástrofe a um único vilão espalhafatoso é ignorar o ecossistema apodrecido que o ergueu ao trono.</strong>","tip":"<strong>Cuidado:</strong> transformar categorias clínicas em xingamento banaliza a única defesa intelectual que você tem."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Ponerologia é o estudo clínico da gênese do mal social — fenômeno com causa, não mistério moral.","O propósito é defensivo: compreender o mecanismo para reconhecê-lo e resistir.","Diagnosticar o processo vale mais que a condenação moral, que cega antes de proteger."]},

 {"slug":"ch02-psicopatia-essencial","sub":"CAPÍTULO 2: A Psicopatia Essencial",
  "intro":"No centro da engrenagem, uma minoria pequena mas decisiva: indivíduos que nascem sem os laços morais e afetivos que prendem o resto de nós. É o núcleo catalisador — a fagulha biológica em torno da qual o mal macrossocial se organiza.",
  "cards":[
      {"ic":"key","t":"O Núcleo Sem Freio Moral","emph":"Sem Freio Moral","b":"Imagine agir no mundo sem a trava da culpa nem o peso da empatia diante da dor alheia. Para o psicopata essencial, o sentimento do outro não é virtude a respeitar: é <strong>uma falha de sistema, pronta para ser explorada com frieza e proveito.</strong> Onde a maioria hesita por pudor, ele avança.","tip":"<strong>Como aplicar:</strong> onde o pudor faz os outros recuarem, ele segue em frente — e é nessa diferença de freios que ganha a primeira vantagem."},
      {"ic":"eye","t":"A Assimetria de Compreensão","emph":"Assimetria","b":"Você olha para ele e projeta remorsos que não existem, supondo que sofre como você sofreria. Ele, enquanto isso, estuda friamente as suas fraquezas reais. <strong>A sua presunção de que todo mundo tem um fundo bom é exatamente a brecha por onde o predador entra.</strong> Você o subestima porque não consegue imaginar uma mente assim.","tip":"<strong>Modelo mental:</strong> pare de projetar a sua decência num terreno onde o solo é oco — reconhecer a diferença é o primeiro anticorpo."},
      {"ic":"gap","t":"Diagnóstico Amador Como Arma","emph":"Diagnóstico Amador","b":"Folhear um manual e rotular o ex ou o chefe de 'sociopata' corrói a seriedade do alerta clínico. Há gente cruel, dura e insensível sem a biologia da patologia estrutural. <strong>O rótulo inflado vira cortina de fumaça — e é por trás dela que o predador verdadeiro, o invisível, circula impune.</strong>","tip":"<strong>Cuidado:</strong> não confunda a frieza de um caráter rude com a patologia profunda e silenciosa do psicopata essencial.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["A psicopatia essencial é o núcleo catalisador: ausência dos laços morais e afetivos normais.","A assimetria de compreensão é a vantagem inicial do mal — nós não imaginamos uma mente assim.","Reconhecer o padrão protege; o rótulo apressado, porém, não é arma política."]},

 {"slug":"ch03-caracteropatias","sub":"CAPÍTULO 3: Caracteropatias e Esquizoidia",
  "intro":"O mal não precisa só do núcleo hereditário. Há os desvios de caráter adquiridos — feridas no cérebro ou na biografia — que deformam quem os cerca, sobretudo quando seu portador ocupa uma cadeira de influência.",
  "cards":[
      {"ic":"steps","t":"A Transmissão do Dano","emph":"Transmissão","b":"O mal social não exige um exército de psicopatas de nascença. Basta uma mente com lesões invisíveis ou cicatrizes adquiridas sentada no trono da sala de aula ou da chefia. <strong>O adulto de caráter estilhaçado despeja a própria fratura, dia após dia, sobre crianças e subordinados — e contamina, calado, a geração seguinte.</strong>","tip":"<strong>Como aplicar:</strong> o desvio de um solitário não é nada; o mesmo desvio numa cadeira que forma valores é desastre sistêmico."},
      {"ic":"pivot","t":"A Posição Amplifica a Falha","emph":"Posição Amplifica","b":"Um homem irascível varrendo a calçada é apenas um detalhe triste do bairro. O mesmo homem numa mesa de ministério assina, num rompante, a miséria de milhares. <strong>O caracteropata no poder estende o tapete vermelho por onde a psicopatia silenciosa entra no palácio pelos fundos.</strong>","tip":"<strong>Modelo mental:</strong> o estrago de um defeito mental é proporcional ao número de pessoas que lhe prestam continência."},
      {"ic":"gap","t":"Doença Não é Maldade","emph":"Doença","b":"Espancar moralmente uma falha que vem de um trauma crônico é chutar o cego que tropeça. A lente analítica não existe para fabricar inquisições, mas para isolar a influência com higiene clínica. <strong>Conter o dano real e barrar a ascensão patológica não exige queimar ninguém na fogueira da vingança moral.</strong>","tip":"<strong>Cuidado:</strong> usar a ciência para destruir a dignidade de quem é vítima do próprio cérebro corrompe quem aplica a teoria.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["Caracteropatias são desvios de caráter adquiridos que deformam quem os cerca.","A posição amplifica o dano: o mesmo defeito vale milhares de vezes mais no poder.","Conter com humanidade — não confundir a doença com a maldade."]},

 {"slug":"ch04-spellbinders-paramoralismos","sub":"CAPÍTULO 4: Spellbinders e Paramoralismos",
  "intro":"O mal precisa de vetores que o levem à massa. O enfeitiçador captura mentes com uma visão totalizante; o paramoralismo desliga o senso moral, invertendo o certo e o errado com a gramática da própria virtude.",
  "cards":[
      {"ic":"mask","t":"O Spellbinder","emph":"Spellbinder","b":"Sobe ao palanque com o peito estufado e o dom de embalar a multidão num torpor. Não entrega fatos densos: entrega promessas fáceis e um inimigo perfeito para odiar. <strong>Cobra a adesão emocional e cega como pedágio da paz ilusória de pertencer à tribo que não se pode questionar.</strong>","tip":"<strong>Como aplicar:</strong> se quem segura o microfone exige lealdade imediata e proíbe a pergunta, saia da sala sem olhar para trás."},
      {"ic":"fork","t":"O Paramoralismo","emph":"Paramoralismo","b":"É o truque supremo do mal: forrar o ato mais imundo com a seda da defesa dos fracos. O fanático convence você de que o assassinato covarde é o ápice do sacrifício ético. <strong>Um argumento que rouba a gramática da justiça para justificar o sangue desliga, no ato, o instinto de repulsa do ingênuo.</strong>","tip":"<strong>Modelo mental:</strong> sinta asco imediato de toda virtude pregada justamente para cobrir o sacrifício de terceiros."},
      {"ic":"gap","t":"Carisma Não É Patologia","emph":"Carisma","b":"Um orador eletrizante que move montanhas não é um psicopata disfarçado só porque atrai multidões. O ímã do spellbinder tem outra cor: ele captura proibindo a pergunta difícil. <strong>O traço letal não é o aplauso que recebe — é a inversão moral silenciosa que ele planta sob as palmas da plateia.</strong>","tip":"<strong>Cuidado:</strong> encantar não é crime. O crime começa quando o encanto anestesia a inteligência de quem ouve.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["Spellbinders capturam com certeza total, um inimigo único e a dúvida proibida.","Paramoralismos invertem a moral: vestem o crime com a roupa da virtude.","O pensamento conversivo blinda o grupo — toda crítica vira traição."]},

 {"slug":"ch05-ponerogenese","sub":"CAPÍTULO 5: Ponerogênese",
  "intro":"O processo em si: a história natural pela qual um grupo normal é convertido, estágio a estágio, em veículo do mal. Não há salto súbito — há um encadeamento, e cada elo aberto era uma porta de saída ignorada.",
  "cards":[
      {"ic":"spiral","t":"A Cadeia Causal","emph":"Cadeia Causal","b":"A gangrena política não chega à amputação sem antes exibir os sinais. Começa com ideias inocentes manipuladas, exige a expulsão do cético, premia o fanático e termina com a cúpula nas mãos de agentes doentios. <strong>O mal de escala nacional obedece a um cronograma lento — e cada degrau descido foi uma chance perdida de travar a roda.</strong>","tip":"<strong>Como aplicar:</strong> quem enxerga o processo corroendo o grupo por dentro não se deixa surpreender no fim da linha."},
      {"ic":"pivot","t":"A Seleção Negativa","emph":"Seleção Negativa","b":"Observe o filtro: quem tem princípios arruma as gavetas, cala e some pelos corredores; quem não tem pudor escuta o cochicho, sorri largo e leva a promoção. <strong>Quando os medíocres e servis ocupam a mesa principal e os íntegros somem, a doença da instituição já cruzou a linha de retorno.</strong>","tip":"<strong>Modelo mental:</strong> uma sala onde o questionador não entra mais e o bajulador reina já é o subsolo do processo."},
      {"ic":"gap","t":"Normalizar o Pequeno Passo","emph":"Pequeno Passo","b":"O abatedouro de verdades não começa pedindo o fuzilamento dos críticos. Começa pedindo, com doçura, que você cale uma opinião menor só hoje, 'pela coesão do grupo'. <strong>Cada concessão sorridente pavimenta a escada irreversível — e acordar quando a liberdade já acabou no térreo é um pranto tarde demais.</strong>","tip":"<strong>Cuidado:</strong> aceitar a mordaça pequena e amigável é entregar o passe que normaliza a mordaça total de amanhã.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Ponerogênese é a conversão gradual de um grupo normal em veículo do mal.","A seleção negativa expulsa os íntegros e promove os cínicos — eis o sinal vital.","Cada estágio é uma chance de interromper; o custo de travar cresce a cada degrau."]},

 {"slug":"ch06-associacoes-ponerogenicas","sub":"CAPÍTULO 6: As Associações Ponerogênicas",
  "intro":"Quando a ponerogênese amadurece, nasce o grupo capturado: sua causa declarada vira fachada, e sua função real passa a ser servir ao núcleo patológico que o tomou por dentro.",
  "cards":[
      {"ic":"layers","t":"A Dupla Estrutura","emph":"Dupla Estrutura","b":"A fachada brilha para os jornais: estatuto rígido, diretrizes nobres, sorrisos alinhados sob a sigla limpa. Nos bastidores, as ordens verdadeiras correm fora das atas, e quem tem o poder real despreza o organograma assinado pelos tolos. <strong>Julgar a carroça pelos cavalos da vitrine é entregar as chaves a quem manda no porão.</strong>","tip":"<strong>Como aplicar:</strong> desligue o som das entrevistas oficiais e rastreie por onde — e por quem — o dinheiro de verdade muda de mão."},
      {"ic":"link","t":"Coesão por Medo","emph":"Coesão por Medo","b":"Esqueça a irmandade nobre no topo da pirâmide. A cola que os prende às cadeiras de couro não é lealdade a uma visão limpa: é <strong>o terror da cumplicidade. Assinaram juntos os mesmos atos imundos e cada um guarda o segredo que faria a forca cair sobre o outro se abrisse a boca.</strong>","tip":"<strong>Modelo mental:</strong> quem se cala porque está atado por subornos e segredos não marcha por fidelidade — marcha algemado pelo medo."},
      {"ic":"eye","t":"Os 'Úteis'","emph":"Úteis","b":"A tragédia silenciosa é a de quem carrega o cimento, suando ao sol, da obra que um dia o aprisionará. Membros de moral íntegra enchem as fileiras erguendo bandeiras legítimas, sem suspeitar que são blindagem humana do núcleo perverso. <strong>A devoção sincera da base saudável empresta toda a legitimidade de que os predadores do topo precisam.</strong>","tip":"<strong>Cuidado:</strong> se a pirâmide te usa como escudo emocional mas nunca te dá acesso ao comando, a sua inocência está financiando o estrago.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["A associação ponerogênica é o grupo capturado, com a causa convertida em máscara.","Dupla estrutura: fachada nobre por fora, núcleo patológico por dentro.","A coesão vem do medo e da cumplicidade — olhe sempre para quem de fato decide."]},

 {"slug":"ch07-mascara-ideologica","sub":"CAPÍTULO 7: A Máscara Ideológica",
  "intro":"O mal organizado quase nunca se apresenta como mal. Ele se cobre com uma ideologia nobre — que recruta o idealista, comove a opinião pública e protege, por baixo, o núcleo que não acredita em nada.",
  "cards":[
      {"ic":"mask","t":"A Ideologia como Máscara","emph":"Máscara","b":"O predador de terno nunca anuncia a crueldade ao microfone. Ele toma uma doutrina romântica das mãos dos jovens sonhadores e a esvazia por dentro, até secar-lhe o miolo ético. <strong>A ideia outrora nobre vira casca oca, exibida no peito apenas para anestesiar os escrúpulos de quem cumpre as ordens.</strong>","tip":"<strong>Como aplicar:</strong> não ataque a bandeira que ele agita; ataque a distância entre o que ele prega chorando e a terra arrasada que deixa."},
      {"ic":"scale","t":"A Divergência Crescente","emph":"Divergência","b":"Enquanto as celas enchem e a tortura vira rotina nas repartições, as faixas nos muros berram promessas cada vez mais puras de liberdade. <strong>Eis o sinal vital: quanto mais sangue pinga no tapete dos bastidores, mais alto e mais imaculado sobe o discurso oficial.</strong> A pureza do palanque mede a sujeira que esconde.","tip":"<strong>Modelo mental:</strong> um excesso de pureza poética no palanque quase sempre compensa o que não se pode confessar nos bastidores."},
      {"ic":"gap","t":"Defender pela Bandeira","emph":"Defender pela Bandeira","b":"Mirar a artilharia na ideologia dos inocentes apaixonados é comprar a guerra falsa que o líder doente encomendou. O núcleo cínico não tem fé alguma na bandeira que inflama os ingênuos. <strong>Gastar munição refutando a doutrina rasa só garante blindagem de graça a quem opera o manual frio do saque do poder.</strong>","tip":"<strong>Cuidado:</strong> atacar a crença sincera dos seguidores distrai você do alvo único — a face da máquina que oprime.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["O mal organizado se cobre com uma ideologia nobre que serve de máscara e recruta idealistas.","Quanto mais a prática contradiz a doutrina, mais o discurso oficial se endurece e se purifica.","Julgue sempre pela distância entre a bandeira hasteada e os atos cometidos em seu nome."]},

 {"slug":"ch08-pathocracia","sub":"CAPÍTULO 8: A Pathocracia",
  "intro":"O estágio terminal: a associação captura o Estado e passa a governar uma sociedade inteira contra a própria população. O aparelho que existia para servir a nação é virado contra ela.",
  "cards":[
      {"ic":"sword","t":"O Governo dos Patológicos","emph":"Patológicos","b":"Quando a cúpula deixa de ser feita de homens imperfeitos lutando com leis confusas e passa a ser uma minoria desviada, instalada na própria insensibilidade, nasce a pathocracia. <strong>O Estado é canibalizado: cessa de servir a nação e passa a moê-la para alimentar o núcleo no topo, incapaz de empatia.</strong>","tip":"<strong>Como aplicar:</strong> quando o horror frio do Estado desce até as raízes da vida diária comum, a patologia já tomou as chaves da cabine."},
      {"ic":"layers","t":"A Inversão Institucional","emph":"Inversão","b":"Os tribunais mantêm as colunas e os juízes ainda desfilam de toga. Mas, por trás do rito intacto, a justiça foi amputada por dentro. <strong>O palco segue em cartaz, idêntico ao de sempre — só que os laudos e as sentenças apenas carimbam o que preserva o delírio de quem manda.</strong> A instituição guarda o nome e perde a função.","tip":"<strong>Modelo mental:</strong> no governo capturado, as instituições viram fachadas perfeitas por fora e cascas apodrecidas por dentro."},
      {"ic":"gap","t":"Frágil por Dentro","emph":"Frágil","b":"A muralha de baionetas assusta quem olha de fora. Mas a pathocracia consome um esforço descomunal só para se manter de pé, porque o exército de cúmplices medíocres não gera talento real. <strong>A casca da opressão parece inquebrável, e por baixo a base de cumplicidade já não aguenta o próprio peso — corrói as vigas que a sustentam.</strong>","tip":"<strong>Cuidado:</strong> rotular qualquer presidente medíocre de chefe de pathocracia esvazia a bala da arma de alerta para quando ela for de fato necessária.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Pathocracia é o governo dos patológicos sobre uma sociedade inteira.","Uma minoria governa a maioria por terror, cooptação e paralisia da vontade.","As instituições mantêm o nome e invertem a função — a fachada sobrevive, o conteúdo morre."]},

 {"slug":"ch09-ciclo-histeroidal","sub":"CAPÍTULO 9: O Ciclo Histeroidal",
  "intro":"Por que sociedades inteiras baixam a guarda? Há uma oscilação histórica: os tempos fáceis corroem o senso crítico e apagam a memória do sofrimento — e é justamente aí, no conforto, que a próxima onda ponerogênica encontra o terreno aberto.",
  "cards":[
      {"ic":"clock","t":"A Guarda Cai no Conforto","emph":"Conforto","b":"Décadas de paz e fartura injetam uma letargia doce no sangue coletivo. As mãos largam o fuzil, o ceticismo é expulso da sala amena e o rigor moral adormece. <strong>A vulnerabilidade máxima não nasce no medo afiado da crise — nasce, lenta e sorrateira, no auge sedutor da bonança.</strong> O perigo dorme com a barriga cheia.","tip":"<strong>Como aplicar:</strong> o caminho liso e sem pedras é exatamente onde a próxima praga deposita os ovos, no escuro do veludo."},
      {"ic":"wave","t":"A Memória do Sofrimento","emph":"Memória","b":"Os pais marcados de cicatrizes contam os horrores que viveram, e os filhos, nascidos no conforto, escutam entediados as velhas lições de guerras que para eles são só páginas cinzentas. <strong>Como o osso não rasgou a própria perna, eles abrem com alegria irresponsável as portas que os pais selaram sangrando.</strong> O que não doeu na carne não vira anticorpo.","tip":"<strong>Modelo mental:</strong> a história contada em enciclopédia não injeta na veia o anticorpo que só a cicatriz vivida produz."},
      {"ic":"gap","t":"Silenciar o Alerta","emph":"Silenciar","b":"O que aponta com o dedo os perigos que ainda são invisíveis no céu limpo é banido da praça festiva como um agourento chato. <strong>Tratar quem grita 'fogo' como um pária louco é arrancar o detector de fumaça do teto na véspera do incêndio.</strong> Mata-se o alarme antes da faísca, e depois chama-se a faísca de fatalidade.","tip":"<strong>Cuidado:</strong> se a roda alegre não suporta o agourento no canto da sala, é a roda inteira que vai arder junta quando a fagulha chegar.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["O ciclo histeroidal alterna bons tempos (complacência) e tempos duros (realismo).","A guarda cai no conforto: premia-se o agradável e esquece-se a lição do sofrimento.","Memória viva e senso crítico encurtam o ciclo — e adiam a próxima onda."]},

 {"slug":"ch10-defesa-imunizacao","sub":"CAPÍTULO 10: A Defesa — Reconhecer e Resistir",
  "intro":"Tudo converge para a defesa. O conhecimento difundido é imunidade social: aquilo que a maioria já entende e sabe nomear, a minoria patológica não consegue mais manipular no escuro.",
  "cards":[
      {"ic":"bulb","t":"O Conhecimento como Imunidade","emph":"Conhecimento","b":"O feitiço que quebra a espinha de uma nação se alimenta, como parasita, da ignorância do povo. Entender o mecanismo do tirano, saber nomear o paramoralismo, ver a engrenagem do poder doente — isso é a dose direta da vacina. <strong>A luz da consciência sobre a máquina das trevas dissolve o encanto em segundos.</strong>","tip":"<strong>Como aplicar:</strong> o manipulador só opera onde o truque é desconhecido; decodificar a fala macia tira ao lobo, na hora, o disfarce."},
      {"ic":"constellation","t":"A Maioria Saudável","emph":"Maioria Saudável","b":"Os patológicos parecem colossos só porque agem coesos nos bastidores, enquanto a massa sã tropeça, perdida no autoengano. O peso esmagador das fileiras saudáveis vence não pelo sangue, mas curando-se do feitiço em bloco. <strong>A coragem aqui não pede guerrilha histérica: pede uma resistência coordenada e serenamente implacável, feita de recusa.</strong>","tip":"<strong>Modelo mental:</strong> a histeria reativa só engorda a fábrica do terror; a clareza serena e compartilhada quebra a espinha da tirania."},
      {"ic":"key","t":"Imunizar, Não Perseguir","emph":"Imunizar","b":"O passo em falso final é transformar a lente da ponerologia na foice de um tribunal revolucionário. Caçar inimigos com sede de vingança moral significa que o projeto perverso já venceu dentro da sua cabeça. <strong>Imunizar uma cultura exige não engolir o espelho do monstro: ser cruel com o tirano é virar a continuação da mesma linhagem doente.</strong>","tip":"<strong>Cuidado:</strong> quem incendeia o asilo para expulsar o demônio entrega, com as próprias mãos, exatamente as chamas que o mal queria.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 10",
  "lessons":["O conhecimento difundido é imunidade social — saber nomear a patologia já a desarma.","A maioria saudável vence pela consciência e pela coesão, nunca pela perseguição.","Defender é imunizar com lucidez e humanidade — caçar inimigos reproduz a própria doença."]},
]
