# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'A Psicologia Financeira' (Morgan Housel).
Frameworks: comportamento > matemática, sorte e risco, nunca o bastante, juros compostos,
sobreviver, cauda longa, liberdade, homem no carro, riqueza invisível, poupar/margem, pessimismo/mudança."""

BOOK = {
 "title": "A Psicologia Financeira",
 "author": "Morgan Housel",
 "header_light": "PSICOLOGIA",
 "header_bold": "FINANCEIRA",
 "subtitle": "VISÃO GERAL · DINHEIRO É COMPORTAMENTO, NÃO MATEMÁTICA",
 "intro": "Ninguém é doido com dinheiro: cada um age conforme as cicatrizes que a própria vida lhe deixou. Por isso o gênio das contas quebra e a faxineira que poupou em silêncio morre milionária — porque <em>como</em> você se comporta pesa mais do que <em>o que</em> você sabe. Morgan Housel não traz fórmulas; traz histórias. E a história que ele conta é simples e dura de viver: dinheiro não é uma ciência exata a ser dominada, é um traço de caráter a ser educado. Quem aprende a sobreviver, a esperar e a dizer 'tenho o bastante' já venceu a parte difícil — o resto é deixar o tempo trabalhar.",
 "description": "As lições atemporais de Morgan Housel sobre riqueza, ganância e felicidade — uma coleção de histórias, não de planilhas. A tese é desconcertante de tão simples: o sucesso financeiro é uma soft skill, e o melhor investidor não é o mais inteligente, é o que sobrevive por mais tempo. Sorte e risco como irmãos, o 'nunca o bastante', os juros compostos que o cérebro se recusa a imaginar, sobreviver para deixar o tempo compor, as caudas que decidem tudo, a liberdade como o maior dividendo do dinheiro, a riqueza que justamente por ser riqueza ninguém vê, e a margem de segurança para o dia em que o plano não der certo.",
 "tags": ["Finanças", "Comportamento", "Investimento"],
 "progress": "11 Capítulos",
 "cover": "assets/psicologia-financeira-cover.png",
 "overview_cards": [
   {"ic":"scale","t":"Comportamento > Matemática","b":"A planilha está sempre certa; é o operador que treme. Finanças são ensinadas como física — taxas, fórmulas — mas são vividas como psicologia: medo, ego, ganância, esperança. Por isso <strong>como você se comporta importa mais do que o que você sabe</strong>. Antes de buscar o ativo perfeito, conserte a atitude — quem não sabe esperar não tem retorno que o salve.","tip":"<strong>Como aplicar:</strong> trabalhe a atitude (poupar, sobreviver, ser humilde) antes de escolher ativos.","wide":True},
   {"ic":"clock","t":"Sobreviver + Deixar o Tempo Compor","b":"Ganhar dinheiro pede ousadia; mantê-lo pede o avesso — humildade e um pouco de medo. Há mil caminhos para enriquecer e um só para garantir o composto: <strong>não quebrar e ficar no jogo</strong>. A única vantagem que sempre paga é simplesmente continuar de pé tempo suficiente para os juros compostos agirem.","tip":"<strong>Regra:</strong> nunca se exponha à ruína; maximize o tempo no jogo, não o retorno do ano."},
   {"ic":"eye","t":"Riqueza é o que Você Não Vê","b":"<strong>Rico</strong> é a renda que entra agora; <strong>riqueza</strong> é a renda que você decidiu não gastar. Uma se exibe, a outra é invisível por natureza — feita dos carros não comprados e dos luxos recusados. E o maior dividendo que ela paga não vem em coisas: vem no <strong>controle do seu próprio tempo</strong>.","tip":"<strong>Modelo mental:</strong> meça-se pelo patrimônio guardado, não pelo consumo exibido."},
 ],
}

# Infografico de Instagram (Diretor de Design) — arquetipo NUMEROS (gerar_infografico.py)
NUMEROS = {
 "kicker": "O LIVRO EM NÚMEROS", "tag": "DADOS",
 "stats": [
   {"ic":"clock","pre":"US$","num":"84,2","unit":"bi","star":True,"lbl":"depois dos 50 anos",
    "ctx":"Dos <b>US$ 84,5 bi</b> de Buffett, quase tudo veio após os 50 — o segredo foi o tempo."},
   {"ic":"spiral","pre":"~","num":"75","unit":"anos","lbl":"no jogo, compondo",
    "ctx":"Buffett investe há <b>~75 anos</b>. Tempo &gt; retorno: maximize o horizonte, não a taxa."},
   {"ic":"wave","pre":"~","num":"1","unit":"%","lbl":"de acertos bastou",
    "ctx":"Berggruen errou quase tudo; <b>~1% das obras</b> fez a fortuna. As caudas vencem."},
 ],
 "viz": {"type":"bar","frac":0.0036,"left":"AT&Eacute; OS 50 ANOS","right":"DOS 50 EM DIANTE",
         "title":"De onde veio a fortuna de Buffett","note":"tempo no jogo &rarr; <b>99,6%</b>"},
 "foot": {"ic":"clock","text":"<strong>Sobreviva e fique no jogo.</strong> Não busque o retorno do ano "
          "— deixe os juros compostos trabalharem por décadas."},
}

CHAPTERS = [
 {"slug":"ch01-ninguem-e-doido","sub":"CAPÍTULO 1: Ninguém é Doido",
  "intro":"Aquilo que parece um disparate na sua planilha costuma fazer todo sentido na vida de quem o faz. Ninguém é doido com dinheiro: cada decisão financeira é a soma das experiências que aquela pessoa viveu — a geração, a inflação, a guerra, a sorte e o azar que coube a ela. Sucesso com dinheiro tem menos a ver com o que você aprendeu na escola e mais com o que a vida tatuou em você.",
  "cards":[
      {"ic":"scale","t":"Finanças São Comportamento, Não Física","emph":"Comportamento","b":"O dinheiro é ensinado como ciência exata — fórmulas, planilhas, taxas — mas é vivido como psicologia: medo, ganância, ego, esperança. Por isso o gênio das contas quebra e a faxineira que poupou por décadas morre milionária. <strong>Como você se comporta importa mais do que o que você sabe.</strong> A planilha está certa; é a mão que segura a caneta que treme.","tip":"<strong>Como aplicar:</strong> antes de buscar o ativo perfeito, conserte a atitude — poupar, esperar, não entrar em pânico."},
      {"ic":"lens","t":"Ninguém É Doido","emph":"Doido","b":"Quem atravessou a hiperinflação foge da bolsa; quem só conheceu o mercado em alta acha que o risco sai de graça. Cada um de nós testemunhou uma fração ínfima da história econômica e a confunde com o mundo inteiro. <strong>Decisões financeiras não nascem de fórmulas — nascem de cicatrizes.</strong> O outro não é irracional: ele só viveu uma vida diferente da sua.","tip":"<strong>Modelo mental:</strong> pergunte “que vivência o leva a agir assim?” antes de “que erro ele cometeu?”."},
      {"ic":"fork","t":"Cada Um Joga um Jogo Diferente","emph":"Jogo Diferente","b":"O especulador que compra na euforia não é tolo — ele joga uma partida de horas, não de décadas, e para o jogo dele o lance está certo. O perigo é assistir a esse lance e copiá-lo achando que jogam a mesma coisa. <strong>As bolhas nascem quando investidores de longo prazo começam a imitar especuladores de curto prazo.</strong> Saiba seu prazo antes de saber seu ativo.","tip":"<strong>Cuidado:</strong> defina seu jogo — prazo, risco, meta — e nunca importe a tática de quem joga outro.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Nas finanças, o comportamento bate a inteligência — e é ele que você pode treinar.","Antes de julgar o 'erro' alheio, reconstrua a vida que levou àquela decisão.","Descubra qual jogo você joga — prazo, risco, meta — e nunca copie quem joga outro."]},

 {"slug":"ch02-sorte-e-risco","sub":"CAPÍTULO 2: Sorte & Risco",
  "intro":"Sorte e risco são irmãos gêmeos: dois nomes para a mesma verdade — a de que todo resultado tem um peso de forças que o esforço não controla. Quando dá certo, chamamos de mérito; quando dá errado, de azar. Mas a linha que separa os dois é mais fina e mais cruel do que gostamos de admitir.",
  "cards":[
      {"ic":"fork","t":"Sorte e Risco São Gêmeos","emph":"Gêmeos","b":"A sorte nada mais é que o risco visto pelo lado de fora. Nenhum sucesso é só mérito, nenhum fracasso é só erro — e <strong>a mesma decisão pode enriquecer um e arruinar outro, sem que a diferença tenha sido a inteligência: foi o acaso.</strong> Julgar resultado sem descontar a sorte e o azar é ler metade da história e jurar que viu o todo.","tip":"<strong>Como aplicar:</strong> pergunte “quanto disso foi processo replicável e quanto foi puro acaso?”."},
      {"ic":"constellation","t":"Estude o Padrão, Não o Herói","emph":"Herói","b":"O bilionário que largou a faculdade é o pior professor do mundo: no caso extremo é onde a sorte e o azar mais distorcem a lição. Para cada Gates há mil que fizeram igual e sumiram sem palco — e ninguém os convida a palestrar. <strong>Os exemplos mais inspiradores costumam ser os mais inúteis para copiar.</strong> A sabedoria mora na regra larga, não na exceção que brilha.","tip":"<strong>Regra:</strong> não idolatre nem demonize indivíduos — extraia padrões largos de muitos casos."},
      {"ic":"mask","t":"Bill Gates e o Amigo que Não Voltou","emph":"Bill Gates","b":"Gates frequentou uma das pouquíssimas escolas do mundo com computador em 1968 — sorte de uma em um milhão. Kent Evans, seu colega igualmente brilhante, morreu numa escalada antes de se formar — azar de uma em um milhão. Mesmo talento, mesma sala, destinos opostos. <strong>O acaso escreve linhas da nossa vida que o esforço nunca chega a tocar.</strong>","tip":"<strong>Cuidado:</strong> seja humilde nos acertos e gentil consigo nos erros — nem tudo foi sua mão.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["Trate sorte e risco como as duas faces da mesma moeda — uma não existe sem a outra.","Não idolatre o herói nem condene o fracassado isolado: extraia padrões de muitos casos.","Humildade nos acertos, autocompaixão nos erros — em ambos houve mão do acaso."]},

 {"slug":"ch03-nunca-o-bastante","sub":"CAPÍTULO 3: Nunca o Bastante",
  "intro":"A habilidade financeira mais difícil não é ganhar mais — é fazer a meta parar de fugir. Sem um senso firme de 'o bastante', nenhuma cifra satisfaz, e a busca infinita acaba levando alguém que já tem tudo a arriscar o essencial por algo de que não precisava. Saber parar é a forma mais rara de riqueza.",
  "cards":[
      {"ic":"target","t":"A Trave que Sempre se Move","emph":"se Move","b":"Quando a ambição corre mais rápido que a satisfação, o número dos sonhos vira o piso no instante em que você o alcança. E a comparação social tem um teto que ninguém atinge: sempre haverá alguém mais rico, mais à frente, com um pouco mais. <strong>É uma corrida deliberadamente sem linha de chegada</strong> — quem não decide onde para, corre para sempre.","tip":"<strong>Como aplicar:</strong> escreva, antes de buscar mais, qual é o seu “o bastante” — e pare de comparar.","wide":True},
      {"ic":"sword","t":"O que Nunca Vale o Risco","emph":"Nunca Vale","b":"Arriscar o que você tem e de que precisa por algo de que não precisa é insanidade — e foi o que derrubou homens que já tinham tudo, como Rajat Gupta e Bernie Madoff. Há bens que não têm preço de recompra: reputação, liberdade, família, ser amado, a paz de espírito. <strong>Perdidos esses, não existe lucro no mundo capaz de trazê-los de volta.</strong>","tip":"<strong>Sinal de alerta:</strong> dívida e fraude para acelerar ganhos — quem já tem o bastante e ainda aposta o essencial.","warn":True},
      {"ic":"bulb","t":"“Eu Tenho o Bastante”","emph":"o Bastante","b":"Na festa de um bilionário, Kurt Vonnegut cutuca o amigo Joseph Heller: o anfitrião ganha num único dia mais do que o romance de Heller renderá em toda a vida. Heller responde com a frase que é a alma deste capítulo: <strong>“Mas eu tenho uma coisa que ele nunca terá — o bastante.”</strong> Reconhecer o suficiente é a única vitória que a comparação não consegue roubar.","tip":"<strong>Regra:</strong> defina o suficiente como destino, não como etapa — só assim o jogo termina a seu favor."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["Defina seu 'o bastante' antes que a trave comece a fugir sozinha.","Nunca arrisque o que você tem e de que precisa por algo de que não precisa.","Reputação, liberdade e amor não têm preço de recompra — não os ponha na mesa."]},

 {"slug":"ch04-juros-compostos","sub":"CAPÍTULO 4: A Confusão dos Juros Compostos",
  "intro":"O cérebro humano pensa em linha reta, mas os juros compostos andam em curva — e essa pequena traição da intuição esconde a maior força das finanças. O que constrói fortunas não é o retorno espetacular de um ano: é o retorno apenas bom, mantido sem interrupção por um tempo absurdamente longo. Tempo é a alavanca que ninguém vê.",
  "cards":[
      {"ic":"spiral","t":"A Oitava Maravilha","emph":"Maravilha","b":"Um retorno meramente bom, repetido por décadas, produz uma escala que a intuição se recusa a prever: cresce devagar, devagar, devagar — e então dispara. Por isso <strong>a maior parte de uma fortuna não vem do retorno brilhante, mas do retorno mediano que ninguém teve a impaciência de interromper.</strong> Nos juros compostos, o tédio é o motor; a paciência é o gênio.","tip":"<strong>Modelo mental:</strong> o composto é não-linear — comece cedo e, acima de tudo, fique muito tempo.","wide":True},
      {"ic":"clock","t":"Tempo Vence Retorno","emph":"Tempo","b":"Buffett não é só o melhor investidor — é o mais antigo. Dos seus cerca de US$ 84,5 bilhões, quase US$ 84,2 bilhões chegaram depois dos 50 anos. <strong>Tivesse ele começado aos 30 e parado aos 60 com os mesmos retornos, seria um desconhecido.</strong> O segredo nunca foi a taxa anual — foi atravessar uns 75 anos no jogo sem nunca descer do trem.","tip":"<strong>Regra:</strong> maximize o horizonte, não a taxa — alongar o prazo bate refinar o percentual."},
      {"ic":"pin","t":"Não Interrompa à Toa","emph":"Interrompa","b":"Cada saída antecipada não pausa o composto: reinicia a contagem do zero. O resultado vem do tempo dentro do mercado, não de adivinhar a hora certa de entrar e sair. Quem persegue o ano perfeito troca uma década de juros silenciosos por uma única aposta de timing. <strong>Sair “só desta vez” costuma custar metade do resultado de uma vida inteira.</strong>","tip":"<strong>Cuidado:</strong> buscar o melhor ano em vez de muitos anos medianos seguidos quebra a mágica do composto.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["O resultado vem do tempo no mercado, não do acerto do timing.","Um retorno bom e durável vence, no fim, um retorno alto e curto.","A paciência é a maior vantagem competitiva ao alcance de qualquer um."]},

 {"slug":"ch05-ficar-rico-continuar-rico","sub":"CAPÍTULO 5: Ficar Rico vs. Continuar Rico",
  "intro":"Conquistar dinheiro e mantê-lo são habilidades opostas, e quase ninguém domina as duas. Ganhar pede ousadia, otimismo e a coragem de se expor. Manter pede o exato contrário: humildade, frugalidade e um medo saudável de que a sorte vai virar. Entre as duas, só uma estratégia garante que o composto chegue ao fim — sobreviver.",
  "cards":[
      {"ic":"mountain","t":"Sobreviver Acima de Tudo","emph":"Sobreviver","b":"Existem mil formas de enriquecer, mas uma só de garantir o composto: não quebrar. Ficar no jogo por décadas vale mais que qualquer retorno excepcional, porque a ruína apaga tudo o que veio antes — e quem é forçado a vender no fundo do poço nunca volta para ver a recuperação. <strong>A única vantagem que sempre paga é simplesmente continuar de pé.</strong>","tip":"<strong>Como aplicar:</strong> seja financeiramente inquebrável — caixa, dívida baixa, folga para atravessar o pior.","wide":True},
      {"ic":"pivot","t":"Ganhar e Manter São Opostos","emph":"Opostos","b":"As duas metades da fortuna pedem talentos contrários. Conquistar exige apostar e se expor; manter exige o avesso — recuar, poupar, temer. <strong>A mesma coragem que enriqueceu você é exatamente o que pode arruiná-lo depois.</strong> Vencida a etapa de ganhar, o sábio troca de mentalidade no meio do caminho, em vez de insistir no que funcionou antes.","tip":"<strong>Modelo mental:</strong> otimista no longo prazo, paranoico no curto — a mentalidade haltere que sobrevive."},
      {"ic":"scale","t":"O Trader que Morreu Falido","emph":"Falido","b":"Jesse Livermore foi o maior especulador de sua era e fez fortuna apostando contra a quebra de 1929. Mas a audácia que o fez vencer não sabia parar: ele seguiu alavancando, perdeu tudo e morreu sem nada. <strong>Saber ganhar não é saber manter — e a alavancagem transforma uma queda passageira em ruína definitiva.</strong> Ele venceu o crash e foi derrotado por si mesmo.","tip":"<strong>Sinal de alerta:</strong> confiar que a ousadia que enriqueceu autoriza arriscar o patrimônio inteiro.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Acima de qualquer retorno, priorize a sobrevivência: nunca se exponha à ruína.","Depois de conquistar, troque a ousadia pela humildade — a etapa mudou.","Mantenha folga e caixa para nunca ser obrigado a vender no pior momento."]},

 {"slug":"ch06-cauda-longa","sub":"CAPÍTULO 6: Caudas Vencem",
  "intro":"Numa carteira, numa carreira, num negócio, uma minoria minúscula de eventos responde por quase todo o resultado. É a tirania das caudas — e a sua boa notícia escondida: você pode errar a maior parte do tempo e ainda assim vencer, desde que os poucos acertos sejam grandes o suficiente para pagar todo o resto.",
  "cards":[
      {"ic":"wave","t":"As Caudas Decidem Tudo","emph":"Caudas","b":"O índice inteiro sobe porque uma fração das empresas carrega nas costas o peso morto de todas as outras; o ganho de uma vida cabe em punhado de anos. Em quase tudo que importa, a exceção rara é que escreve o resultado. <strong>Você pode estar errado a maior parte do tempo e ainda vencer — desde que as poucas vezes em que acerta sejam enormes.</strong>","tip":"<strong>Como aplicar:</strong> julgue uma estratégia pelo resultado agregado, não pela frequência de acertos.","wide":True},
      {"ic":"layers","t":"Errar Muito e Ainda Ganhar","emph":"Errar Muito","b":"O marchand Heinz Berggruen comprou milhares de obras, e a maioria não valeu quase nada — mas um punhado, Picasso, Klee, Matisse, valorizou tanto que o fez um dos maiores negociantes do mundo. Acertou talvez 1% das compras, e foi o bastante. <strong>O preço de capturar as poucas caudas gigantes é tolerar uma multidão de pequenos fracassos.</strong>","tip":"<strong>Regra:</strong> trate cada erro barato como ingresso pago para estar presente no acerto que muda tudo."},
      {"ic":"target","t":"O que Mata Não É Errar","emph":"Mata","b":"Errar com frequência é normal e está no roteiro; o que de fato arruína é não sobreviver até a cauda chegar. Vender o vencedor cedo demais e segurar o perdedor por orgulho corta justamente o evento que pagaria toda a conta. <strong>Abandonar uma boa estratégia por uma sequência normal de perdas é o único erro que não se recupera.</strong>","tip":"<strong>Cuidado:</strong> não troque uma estratégia sólida por uma sequência de fracassos que já estava no roteiro.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Julgue uma estratégia pelo resultado agregado, nunca pela taxa de acerto.","Aceite muitos pequenos erros como o custo de bilhete das grandes caudas.","Sobreviva aos fracassos para estar presente nos poucos acertos que decidem tudo."]},

 {"slug":"ch07-liberdade","sub":"CAPÍTULO 7: Liberdade — O Maior Dividendo",
  "intro":"De tudo que o dinheiro pode comprar, o mais valioso não cabe numa vitrine: é o controle sobre o próprio tempo. Acordar e poder dizer 'faço o que quero, quando quero, com quem quero, pelo tempo que quiser' — esse é o dividendo mais alto que a riqueza paga, e o único que o dinheiro entrega de verdade.",
  "cards":[
      {"ic":"key","t":"Controle do Tempo É a Riqueza Máxima","emph":"Controle do Tempo","b":"O maior dividendo do dinheiro não vem em coisas — vem nas manhãs em que você decide o que fazer, quando, com quem e por quanto tempo. O psicólogo Angus Campbell descobriu que o senso de controle sobre a própria vida prevê a felicidade melhor que renda, saúde ou status. <strong>Poder dizer “a agenda é minha” é o luxo mais caro que existe — e o que mais barato se desperdiça.</strong>","tip":"<strong>Como aplicar:</strong> ao decidir, prefira a opção que amplia o controle do seu tempo, não só o saldo.","wide":True},
      {"ic":"leaf","t":"Compre Autonomia, Não Coisas","emph":"Autonomia","b":"O melhor uso do dinheiro é convertê-lo em independência: a reserva que deixa você recusar o trabalho ruim, esperar a oportunidade certa, sair de uma sala sem pedir licença. Cada real guardado é uma opção que você compra para o futuro. <strong>Poupar não é renunciar ao prazer — é comprar o direito de escolher.</strong> A liberdade tem preço, e ele se paga adiando o gasto.","tip":"<strong>Modelo mental:</strong> sua reserva mede quantos “nãos” você pode dizer antes de precisar de um “sim”."},
      {"ic":"sword","t":"Renda Alta com Coleira","emph":"Coleira","b":"Desde os anos 1950 a riqueza média se multiplicou, mas a felicidade ficou para trás — em parte porque muita gente ganhou mais bens e perdeu as próprias horas: jornadas sem fim, e-mail fora do expediente, disponibilidade total. <strong>Ganhar muito preso à mesa de outro é riqueza pela metade.</strong> Trocar autonomia por status é dos piores negócios que existem.","tip":"<strong>Sinal de alerta:</strong> empregos que maximizam a renda e minimizam o controle sobre o seu próprio tempo.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["O melhor uso do dinheiro é comprar controle sobre o próprio tempo.","O senso de autonomia prevê a felicidade melhor do que a renda absoluta.","Construa reserva para poder dizer 'não', esperar e escolher."]},

 {"slug":"ch08-homem-no-carro","sub":"CAPÍTULO 8: O Paradoxo do Homem no Carro",
  "intro":"Há um pequeno paradoxo cruel no fundo de quase toda compra cara: você adquire o carro de luxo para ser admirado, mas quem o vê não admira você — admira a si mesmo imaginando-se ao volante. Gastamos uma fortuna por um respeito que as coisas, justamente, não sabem entregar.",
  "cards":[
      {"ic":"mask","t":"O Paradoxo do Homem no Carro","emph":"Homem no Carro","b":"Como manobrista, Housel viu por anos a multidão cobiçar os carros de luxo que ele estacionava — e ninguém, jamais, olhava o motorista. Cada um se via dentro do carro, não admirando o dono. <strong>Quem compra o Ferrari para ser admirado desaparece atrás do próprio objeto de desejo.</strong> Você usa o bem como recado; o mundo lê só o bem, nunca quem o conduz.","tip":"<strong>Como aplicar:</strong> pergunte “compro isto pelo uso ou pelo olhar de uma plateia que nem está olhando?”.","wide":True},
      {"ic":"bubble","t":"Respeito Vem do Caráter","emph":"Caráter","b":"A admiração que se persegue com cavalos-vapor chega, na verdade, por humildade, gentileza e empatia. As pessoas se afeiçoam a quem as faz sentir bem, não a quem ostenta o relógio. <strong>O respeito que o dinheiro tenta comprar é exatamente o que o dinheiro não vende.</strong> Você não admira o dono do carro caro — por que esperaria que fizessem por você o contrário?","tip":"<strong>Regra:</strong> quer ser respeitado? Invista em caráter e atenção ao outro, não em cifrões visíveis."},
      {"ic":"eye","t":"Comprar para a Plateia","emph":"Plateia","b":"Gastar caro para conquistar respeito tem efeito quase nulo — e, pior, costuma colher inveja, que é fácil de confundir com admiração. A plateia que você imagina avaliando suas posses está, na verdade, ocupada com as próprias. <strong>O bem comprado para impressionar impressiona menos do que custou, e por muito menos tempo.</strong>","tip":"<strong>Sinal de alerta:</strong> não confunda a inveja alheia com admiração — uma corrói, a outra nem chega.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Bens caros quase nunca compram a admiração que prometem entregar.","Quer ser respeitado? Invista em humildade e gentileza, não em ostentação.","A plateia olha a coisa, e nunca o dono — o sinal não chega a quem você quer."]},

 {"slug":"ch09-riqueza-invisivel","sub":"CAPÍTULO 9: Riqueza é o que Você Não Vê",
  "intro":"Eis uma confusão que custa caro: rico é a renda alta que entra hoje; riqueza é a renda que você decidiu não gastar. E aqui está a armadilha — a riqueza, por definição, é invisível. Ela é feita exatamente dos carros não comprados e dos luxos recusados, das coisas que justamente por não estarem ali ninguém consegue ver.",
  "cards":[
      {"ic":"eye","t":"Rico É Renda; Riqueza É o que Sobra","emph":"o que Sobra","b":"Rico é a renda de agora — financia o carro novo, o relógio, a viagem. Riqueza é o que você escolheu não gastar, convertido em ativos guardados. Uma se vê; a outra, por natureza, não. <strong>A riqueza mora justamente nos carros que não foram comprados e nos luxos que foram recusados.</strong> Você enxerga o gasto do vizinho — nunca a conta bancária dele.","tip":"<strong>Como aplicar:</strong> meça prosperidade pela renda que você NÃO gastou, não pelo padrão que exibe.","wide":True},
      {"ic":"gap","t":"A Riqueza Não Se Copia pela Aparência","emph":"Aparência","b":"Como ela é invisível, não dá para aprendê-la imitando quem parece rico — porque o que parece, tantas vezes, não é. O homem que troca de carro todo ano pode esconder um patrimônio mínimo e uma dívida alta; o verdadeiramente rico costuma passar por gente comum. <strong>Tomar o ostentador como modelo é copiar a fatura, não a fortuna.</strong>","tip":"<strong>Cuidado:</strong> não use quem ostenta como prova de sucesso — a aparência de rico e a riqueza raramente moram juntas.","warn":True},
      {"ic":"steps","t":"O Teste É Resistir ao Gasto","emph":"Resistir","b":"Construir riqueza é, no fundo, um único gesto repetido até virar caráter: dizer não ao gasto que parecia merecido. Cada compra adiada vira patrimônio; cada esforço para “parecer” bem-sucedido destrói a chance de realmente sê-lo. <strong>A tentação visível é a prova; o que sobra invisível é a nota que você tirou.</strong> Riqueza é a soma dos prazeres que você optou por não exibir.","tip":"<strong>Regra:</strong> trate a renda não gasta como o placar real — o consumo é despesa, não troféu."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["Riqueza é renda não gasta — e invisível por sua própria natureza.","Não confunda gasto visível com prosperidade: o que parece rico raramente é.","Construir riqueza é, em essência, um exercício diário de recusar gastos."]},

 {"slug":"ch10-poupar-margem","sub":"CAPÍTULO 10: Poupar & Margem de Segurança",
  "intro":"De todas as variáveis das finanças, a taxa de poupança é a mais sua: você não manda na renda nem no retorno do mercado, mas manda no quanto guarda. E a maior surpresa é que poupar depende menos do salário do que do ego. Some a isso a margem de segurança — a folga que mantém você no jogo quando o plano não dá certo — e você tem o capítulo mais prático do livro.",
  "cards":[
      {"ic":"leaf","t":"Poupar Sem um Motivo","emph":"Sem um Motivo","b":"A poupança não precisa de uma meta para começar — esperar o objetivo “digno” é só a desculpa que adia tudo. Ela é a proteção contra o imprevisível, e o imprevisível é a única certeza da vida financeira. <strong>Poupar sem destino certo é construir a opção de lidar com o que você ainda nem consegue imaginar.</strong> Guarde um percentual fixo, haja plano ou não.","tip":"<strong>Como aplicar:</strong> poupe por hábito automático — antes de saber para quê, justamente porque não dá para saber.","wide":True},
      {"ic":"scale","t":"Margem de Segurança","emph":"Margem de Segurança","b":"Benjamin Graham comprava ativos bem abaixo do valor estimado: mesmo errando a conta, ainda saía ganhando. A ideia vale para a vida inteira — deixe folga entre o que pode acontecer e o que você precisa que aconteça. <strong>Planeje de modo que o plano não precise dar certo.</strong> É essa folga que transforma um erro de cálculo em mero incidente, em vez de ruína.","tip":"<strong>Regra:</strong> dimensione tudo para sobreviver ao cenário ruim, não só ao cenário esperado."},
      {"ic":"mask","t":"Poupança Depende do Ego","emph":"Ego","b":"Quanto você poupa depende menos da renda e mais do quanto sente que precisa provar aos outros. Gastar menos é, no fundo, desejar menos status — e quem se solta da plateia descobre uma capacidade de poupar que o salário nunca explicou. <strong>O abismo entre o que você ganha e o que gasta é cavado pelo ego, não pela renda.</strong>","tip":"<strong>Sinal de alerta:</strong> otimizar tanto o plano que não sobra folga — sem ego sob controle, qualquer desvio quebra.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 10",
  "lessons":["Poupe por hábito, sem precisar de meta — o imprevisto é a única certeza.","Quanto você poupa depende mais do ego (gastar menos) do que da renda.","Embuta sempre uma margem de segurança: planeje para o caso de o plano falhar."]},

 {"slug":"ch11-pessimismo-e-mudanca","sub":"CAPÍTULO 11: Pessimismo, Mudança & Coerência",
  "intro":"O pessimismo tem um charme injusto: soa sempre mais inteligente que a esperança e captura muito mais atenção. Mas a aposta racional de longo prazo é otimista — o mundo tende a melhorar apesar dos tropeços. E há uma última armadilha: como você vai mudar mais do que imagina, evite os planos extremos e irreversíveis que prendem o seu 'eu de hoje' à garganta do 'eu de amanhã'.",
  "cards":[
      {"ic":"wave","t":"A Sedução do Pessimismo","emph":"Pessimismo","b":"O alarme soa sempre mais sábio que a esperança, e há um motivo estrutural nisso: o progresso é lento e silencioso, ao passo que a ruína é súbita e barulhenta. Por isso o pessimista parece um analista lúcido, e o otimista, um vendedor ingênuo. <strong>Mas a aposta racional de longo prazo é otimista — o mundo, apesar dos reveses, tende a melhorar.</strong>","tip":"<strong>Como aplicar:</strong> desconfie do alarme que soa “esperto demais” e pese a tendência histórica de melhora.","wide":True},
      {"ic":"pivot","t":"Você Vai Mudar","emph":"Mudar","b":"É a falácia do fim da história: em cada idade a gente acredita ter chegado à versão definitiva de si mesmo. O jovem jura que nunca trocará de gosto, de ofício ou de estilo — e aos quarenta já trocou todos. <strong>Subestimamos sistematicamente o quanto nossas metas e prioridades vão se transformar.</strong> Amarrar a vida a uma meta extrema é apostar contra o estranho que você ainda vai ser.","tip":"<strong>Regra:</strong> evite metas extremas e irreversíveis — deixe espaço para o “eu futuro” revisar sem punição alta.","warn":True},
      {"ic":"spark","t":"Otimismo Racional","emph":"Racional","b":"As duas posturas convivem sem se contradizer: esperar reveses no curto prazo e crescimento no longo é a coerência que mantém alguém no jogo. O realismo de hoje evita a ruína; o otimismo de amanhã paga o composto. <strong>Otimista no longo prazo, cauteloso no curto — paciência casada com prudência.</strong>","tip":"<strong>Modelo mental:</strong> aposte no longo prazo melhorando, mas blinde o curto prazo contra o golpe que tira você do jogo."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 11",
  "lessons":["Desconfie do pessimismo que soa esperto; aposte na melhora de longo prazo.","Você vai mudar mais do que imagina — evite metas extremas e irreversíveis.","Seja otimista no longo prazo e cauteloso no curto: as duas posturas se completam."]},
]
