# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Psicopolítica' (Byung-Chul Han)."""

BOOK = {
  "title": "Psicopolítica",
  "author": "Byung-Chul Han",
  "header_light": "PSICO",
  "header_bold": "POLÍTICA",
  "subtitle": "VISÃO GERAL · O PODER QUE NÃO PROÍBE — SEDUZ",
  "intro": "O senhor saiu de cena, e o servo continuou trabalhando. O neoliberalismo descobriu que a coação é ineficiente: corrente provoca resistência, prazer não provoca nenhuma. Por isso não reprime mais — seduz. Faz de cada um o empreendedor de si que se chicoteia sorrindo, e batiza de liberdade a própria exploração. Byung-Chul Han segue o fio do biopoder de Foucault até a <em>psicopolítica</em> digital, onde o Big Data lê o desejo antes de você senti-lo. Contra um poder que se parece com a felicidade, ele opõe o gesto mais difícil de todos: o <strong>idiotismo</strong> — a coragem de calar, de subtrair-se, de dizer \"não\".",
  "description": "Byung-Chul Han mapeia a passagem do biopoder — que disciplinava corpos com proibição e vigilância — para a psicopolítica neoliberal, que coloniza a psique e o desejo sem nunca dizer \"você deve\". É a anatomia de um poder amável: o <em>smart power</em> que agrada em vez de mandar, a emoção convertida em força produtiva, o Big Data e o dataísmo que governam por correlação, a transparência erguida em controle. Sequência de <em>Sociedade do Cansaço</em>. A saída não é mais comunicação, mais ação, mais dado: é a potência do \"não\".",
  "tags": ["Filosofia", "Poder", "Crítica Digital"],
  "progress": "8 Capítulos",
  "cover": "assets/psicopolitica-cover.png",
  "overview_cards": [
    {"ic":"layers","t":"Do Corpo à Psique","b":"O biopoder de Foucault domava <strong>corpos</strong>: muros, horários, vigilância, proibição. A psicopolítica mira mais fundo — a <strong>psique</strong>, com sua emoção, seu desejo, sua atenção, sua liberdade. Já não disciplina de fora; <strong>coloniza por dentro</strong>. A grade virou aplicativo, e a obediência virou vontade própria.","tip":"<strong>Modelo mental:</strong> diante de qualquer poder, pergunte onde ele toca. Se aperta o corpo, é disciplina. Se acende o desejo, é psicopolítica."},
    {"ic":"mask","t":"A Liberdade Que Explora","b":"O neoliberalismo é gênio porque não combate a liberdade — <strong>vive dela</strong>. Transforma autonomia, iniciativa e automotivação no próprio combustível da exploração. <strong>Quanto mais livre você se sente, mais rende.</strong> O patrão sumiu, mas não por bondade: ele agora mora dentro de você, e não tira folga.","tip":"<strong>Sinal de alerta:</strong> quando \"seja você mesmo\" deixa de ser convite e vira ordem, a sua singularidade já está na folha de pagamento.","warn":True},
    {"ic":"pivot","t":"O Idiotismo — a Potência do \"Não\"","b":"O <em>idiotēs</em> grego era o que ficava à parte da pólis — não o tolo, mas o singular, o que não se dissolve no consenso. Han o resgata como gesto de liberdade. Num mundo que premia quem comunica, expõe e reage sem parar, <strong>o ato mais subversivo é o silêncio</strong>: não postar, não responder, não se mostrar.","tip":"<strong>Como aplicar:</strong> resistir aqui é subtrair, não somar. Desligar, calar, guardar um pensamento que ainda não virou dado nem opinião."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-crise-da-liberdade",
    "sub": "CAPÍTULO 1: A Crise da Liberdade",
    "intro": "A liberdade prometida como fim da opressão tornou-se a forma mais astuta dela. O sujeito se julga livre exatamente no instante em que se explora — e por isso não há contra quem se rebelar. O \"poder fazer\" sem fronteira não emancipa: produz uma servidão que se confunde com autorrealização e se chama, sem ironia, de sucesso.",
    "cards": [
      {"ic":"mask","t":"O Empreendedor de Si Mesmo","emph":"Empreendedor de Si","b":"O sujeito agora se administra como uma empresa: concorre consigo, otimiza-se, cobra-se metas. A exploração não veio de fora — ele a internalizou. <strong>Carrega o capataz dentro do peito</strong>, e nenhum capataz é tão implacável quanto o que se confunde com a própria vontade. Sem patrão a derrubar, <strong>não sobra revolução possível</strong> — só desabamento.","tip":"<strong>Exemplo atual:</strong> o criador \"dono do próprio tempo\" que posta de madrugada até desabar. Ninguém o obriga — e é justamente por isso que ele não consegue parar."},
      {"ic":"spiral","t":"Quando o \"Poder\" Vira Ordem","emph":"Tem-Que-Poder","b":"O \"você pode\" do neoliberalismo soa libertador, mas se converte num <strong>\"você tem que poder\"</strong> sem teto. E liberdade sem limite não solta: <strong>esgota</strong>. Sem opressor externo onde descarregar a revolta, a agressividade dobra-se contra quem a sente. O explorado e o explorador passam a ser a mesma pessoa.","tip":"<strong>Modelo mental:</strong> a depressão e o burnout não são falhas do sistema — são o seu produto. A implosão é o que substitui a greve quando não há mais patrão a quem culpar."},
      {"ic":"person","t":"O Eu Como Obra Inacabável","emph":"Projeto","b":"O sujeito de desempenho se concebe como <strong>projeto eternamente por concluir</strong> — e nisso fracassa todo dia, porque projeto que nunca termina é projeto que nunca chega. Não há linha de chegada, só otimização perpétua. A autoexploração é mais total que a antiga porque <strong>não tem rosto contra o qual erguer o punho</strong>.","tip":"<strong>Sinal de alerta:</strong> a sensação crônica de \"nunca ser suficiente\" não é sua fragilidade pessoal — é o motor do sujeito-projeto funcionando exatamente como deve.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["O neoliberalismo não reprime a liberdade — vive dela. Quanto mais livre você se sente, mais explorável você é.", "O sujeito virou empreendedor de si: explora a si mesmo achando que se realiza.", "Sem opressor externo não há revolução — só implosão. A greve cede lugar à depressão e ao burnout."],
  },
  {
    "slug": "ch02-smart-power",
    "sub": "CAPÍTULO 2: O Smart Power (Poder Gentil)",
    "intro": "O poder antigo era estúpido: gastava energia oprimindo e ainda criava mártires. O <em>smart power</em> aprendeu a lição. Não obriga pelo medo — convence pelo prazer e pela aprovação. E como ninguém luta contra aquilo de que gosta, ele se torna mais total que toda corrente: a obediência mais perfeita é a que se sente como vontade própria.",
    "cards": [
      {"ic":"spark","t":"O Poder Que Diz \"Curtir\"","emph":"Seduz, não Reprime","b":"O poder disciplinar mandava: \"você deve\". O <em>smart power</em> pergunta, com voz amável: \"<strong>do que você gosta?</strong>\" — e estende o \"curtir\". Não há barricada a erguer contra um poder que distribui prazer. <strong>Quem é seduzido colabora; quem colabora não se revolta.</strong> A coerção fazia inimigos; a sedução faz fãs.","tip":"<strong>Modelo mental:</strong> o controle mais firme é o de que você gosta. Desconfie sobretudo do dispositivo que te agrada a ponto de você defendê-lo.","wide":True},
      {"ic":"bubble","t":"A Curtida É o Verbo do Poder","emph":"Like","b":"Onde o panóptico vigiava, o feed corteja. O algoritmo que aprende seu gosto e te devolve mais do mesmo não é carcereiro — é pretendente. <strong>Cada \"curtir\" é, ao mesmo tempo, prazer para você e dado para ele.</strong> A interface nunca ordena: ela sugere, recomenda, pergunta de novo \"gostou?\". E você responde — voluntário, satisfeito, capturado.","tip":"<strong>Como aplicar:</strong> quando um app fica conveniente demais para largar, não é vício seu — é o <em>smart power</em> trabalhando exatamente como foi desenhado."},
      {"ic":"leaf","t":"A Permissividade Que Prende","emph":"Permissividade","b":"\"Seja você mesmo.\" \"Realize-se.\" Soa como concessão e é grilhão: a liberalidade não solta, <strong>vincula</strong>. Quem crê expressar sua singularidade está, sem suspeitar, reproduzindo o molde que o explora. <strong>A permissividade é a forma mais doce do conformismo</strong> — proíbe nada e, por isso mesmo, captura tudo.","tip":"<strong>Sinal de alerta:</strong> quando \"autenticidade\" vira imperativo de marca, a sua expressão de si já é matéria-prima entregue de graça ao mercado.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["O poder neoliberal seduz em vez de reprimir — é amável, inteligente, <em>smart</em>.", "Como agrada, não encontra resistência: a sedução é mais eficaz que toda coerção.", "O \"curtir\" é a célula desse poder — adesão voluntária, prazerosa e, no mesmo gesto, dado."],
  },
  {
    "slug": "ch03-emocionalizacao",
    "sub": "CAPÍTULO 3: A Emocionalização",
    "intro": "A razão é lenta, desconfiada, cara de convencer. A emoção é rápida, impulsiva, contagiosa — e o capitalismo, que não perdoa ineficiência, escolheu a emoção. Já não se vende o objeto, vende-se o sentimento que ele promete. E o imperativo de \"ser autêntico\", que se anuncia como liberdade, é o turno mais sutil do trabalho: produzir o próprio eu para o mercado.",
    "cards": [
      {"ic":"wave","t":"O Afeto Virou Mercadoria","emph":"Força Produtiva","b":"O capitalismo emocional não vende mais coisas — <strong>vende sentimentos, experiências, sentido</strong>. A emoção tem uma virtude que a razão nunca terá: <strong>chega antes do pensamento</strong>. Conduz o consumo no instante em que o sujeito ainda nem deliberou. Comover é mais barato e mais certeiro do que convencer.","tip":"<strong>Como aplicar:</strong> diante de uma campanha, não pergunte o que ela diz. Pergunte qual emoção ela acende e recolhe — é essa emoção, não o produto, a mercadoria de verdade."},
      {"ic":"mask","t":"A Autenticidade à Venda","emph":"Autenticidade","b":"\"Expresse-se.\" \"Seja você mesmo.\" Parece o fim das máscaras e é a máscara mais perfeita: <strong>a fabricação do eu para o mercado</strong>. A singularidade não escapa do comércio — vira produto. A diferença não te liberta — vira diferencial vendável. Você acredita estar se revelando; está, na verdade, se embalando.","tip":"<strong>Modelo mental:</strong> quando \"seja você mesmo\" desce como mandamento de plataforma, a sua autoexpressão já é mão de obra entregue de graça ao algoritmo."},
      {"ic":"target","t":"Por Que o Capital Prefere a Emoção","emph":"Emoção × Razão","b":"A razão pondera, freia, exige tempo — é difícil de instrumentalizar. A emoção é dinâmica, performática, <strong>mobilizável sob demanda</strong>. Por isso o capital a corteja: é o atalho que <strong>contorna o juízo crítico</strong> e arrasta a adesão antes que ela seja examinada. Pensar é resistência; sentir, sob este regime, é obedecer depressa.","tip":"<strong>Sinal de alerta:</strong> o feed que otimiza indignação e euforia não te informa nem te diverte — ele te ordenha. Engajamento vira dado, dado vira receita.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["O capital descobriu a emoção como força produtiva — o afeto virou recurso a ser extraído.", "A emoção chega antes da razão: decide o consumo no instante anterior ao pensamento.", "O mandamento da autenticidade é coação disfarçada — produzir o eu já é trabalhar para o mercado."],
  },
  {
    "slug": "ch04-dataismo",
    "sub": "CAPÍTULO 4–5: Dataísmo e a Guinada Psicopolítica",
    "intro": "O Big Data trouxe uma nova religião, o <em>dataísmo</em>: a fé de que o número dispensa o sentido, e a correlação aposenta a compreensão. Acoplado à psicopolítica, gera um poder que não vigia o que você fez — antecipa o que você fará, e modela o desejo antes que ele apareça. Nesse cálculo, o sujeito deixa de ser pessoa: vira perfil, probabilidade, cluster.",
    "cards": [
      {"ic":"lens","t":"O Dataísmo — Saber Sem Sentido","emph":"Saber sem Sentido","b":"Eis o novo credo: tudo é dado, e o dado basta. Correlação no lugar da causa, contagem no lugar da compreensão — \"<strong>o número é mais transparente que o espírito</strong>\". Mas saber <em>que</em> sem saber <em>por quê</em> não é conhecimento, é niilismo eficiente: <strong>uma máquina que acerta tudo e não entende nada</strong>.","tip":"<strong>Modelo mental:</strong> quando um sistema acerta sobre você sem jamais te compreender, você não está sendo conhecido — está sendo computado.","wide":True},
      {"ic":"eye","t":"O Fim do Indivíduo","emph":"Dividual","b":"Indivíduo quer dizer indivisível. O Big Data o estilhaça em <strong>dividual</strong> — fragmentos de dados que se recombinam à vontade. À máquina não interessa quem você é, só <strong>em que grupo você cai</strong>. E o que parecia o mais íntimo, a sua escolha futura, é capturado de antemão como probabilidade.","tip":"<strong>Como aplicar:</strong> a recomendação que adivinha o que você quer ver antes de você querer não te entende — te calcula. É a liberdade prevista virando produto."},
      {"ic":"layers","t":"A Guinada: do Corpo à Psique","emph":"a Guinada","b":"O biopoder de Foucault domava <strong>corpos</strong> com muro, proibição e olho vigilante. A psicopolítica trabalha a <strong>psique</strong>: motiva, gameifica, parabeniza, faz desejar. E só funciona porque o sujeito é livre — <strong>é precisamente dessa liberdade que ela se alimenta</strong>. Proíbe nada; programa tudo.","tip":"<strong>Modelo mental:</strong> o app de bem-estar que te incentiva, premia com medalhas e celebra suas metas é psicopolítica pura — não te prende, te conduz a querer o que ele quer."},
    ],
    "lessons_title": "Lições-Chave dos Capítulos 4–5",
    "lessons": ["O dataísmo é a fé de que o dado dispensa o sentido — é niilismo travestido de ciência, não saber.", "O Big Data conhece por correlação, não por compreensão. Não te entende — e mesmo assim te governa.", "O poder saiu do corpo (biopolítica) e migrou para a psique (psicopolítica): explora a liberdade, não a reprime."],
  },
  {
    "slug": "ch05-transparencia-panoptico",
    "sub": "CAPÍTULO 6–7: Transparência e Panóptico Digital",
    "intro": "Pregam a transparência como honestidade, e ela é controle. Bentham sonhou um cárcere onde o preso, sem saber se era observado, se vigiava sozinho. O panóptico digital superou o sonho: aqui não há coerção nenhuma, porque nos expomos por prazer. O Big Brother orwelliano metia medo; este é amável — e por isso ninguém pensa em derrubá-lo.",
    "cards": [
      {"ic":"eye","t":"A Transparência Que Controla","emph":"Transparência","b":"Tudo expor, tudo comunicar, nada de segredo. O imperativo da transparência expulsa a <strong>negatividade</strong> — o outro, o oculto, o singular, o atrito — e fabrica o igual. E onde tudo está exposto, <strong>a confiança vira supérflua</strong>: por que confiar, se posso verificar? Confiança precisa de não-saber; o transparente a substitui pelo controle.","tip":"<strong>Modelo mental:</strong> o que se torna visível torna-se governável. Desconfie do elogio à transparência total — ele não pede a sua honestidade, pede o seu rastro.","wide":True},
      {"ic":"constellation","t":"O Panóptico Que Habitamos de Bom Grado","emph":"Voluntário","b":"O panóptico de Bentham isolava e coagia. O digital faz o oposto: <strong>hipercomunicação e exposição espontânea</strong>. A vigilância já não desce de uma torre — corre de lado, <strong>cada um vigiando e expondo os outros e a si</strong>. Não somos prisioneiros do panóptico; somos seus moradores entusiasmados, postando a própria cela.","tip":"<strong>Como aplicar:</strong> você não é observado contra a vontade. A eficácia do sistema está em você <em>querer</em> postar, curtir, compartilhar. O carcereiro é o seu desejo de aparecer."},
      {"ic":"bubble","t":"O Big Brother Amável","emph":"Amável","b":"A vigilância de hoje não inspira terror — inspira <strong>conforto</strong>. Entregamos dados em troca de conveniência e gratificação, e achamos o negócio vantajoso. <strong>Não somos arrastados para dentro: corremos para dentro.</strong> A conveniência é a coleira mais confortável já inventada, e cada comodidade digital é, no mesmo instante, um ponto de coleta.","tip":"<strong>Sinal de alerta:</strong> o assistente que escuta \"para te ajudar\", o relógio que mede seu sono \"pelo seu bem\" — ninguém obriga, e todos aderem. O \"pelo seu bem\" é a senha do poder amável.","warn":True},
    ],
    "lessons_title": "Lições-Chave dos Capítulos 6–7",
    "lessons": ["A transparência total não emancipa — nivela e controla, expulsando a negatividade que faz o singular existir.", "Ela troca a confiança pelo controle: onde tudo se expõe, confiar deixa de ser preciso.", "O Big Brother digital vigia agradando — e por agradar é mais eficaz que o de Orwell, que precisava do medo."],
  },
  {
    "slug": "ch06-idiotismo",
    "sub": "CAPÍTULO 8: O Idiotismo — Resistência à Psicopolítica",
    "intro": "Contra um poder que se infiltra pelo desejo, de nada serve gritar mais alto — gritar é justamente o que ele pede. Han propõe o contrário: o idiotismo. Ser <em>idiotēs</em> não é ser tolo; é ser singular, à parte do consenso, desconectado do coro. Num mundo que exige comunicar, reagir e aparecer sem trégua, a forma suprema de liberdade é a recusa: poder não.",
    "cards": [
      {"ic":"pivot","t":"O Idiotismo — a Coragem de Calar","emph":"Coragem do Não","b":"Na Grécia, o <em>idiotēs</em> era o particular, o que ficava à parte da pólis e não se entregava ao consenso. Han o reabilita como figura de liberdade. <strong>Resistir, aqui, é subtrair — não somar.</strong> Desligar, calar, guardar um pensamento sem entregá-lo ao feed. Onde todos correm para dizer, o idiota tem a ousadia de ficar em silêncio.","tip":"<strong>Como aplicar:</strong> não como \"detox\" para depois render mais — isso seria a psicopolítica de novo. Mas como reconquista da singularidade que só existe fora do enxame.","wide":True},
      {"ic":"gap","t":"A Potência do \"Não\"","emph":"Potência do Não","b":"Contra a positividade compulsiva da rede — sempre mais conteúdo, mais reação, mais opinião —, Han opõe a <strong>potência negativa</strong>: o poder de <strong>não fazer, não reagir, não se expor, não comunicar</strong>. Não é fraqueza, é a força mais rara. Saber não é fácil; <strong>poder-não é o que quase ninguém ainda consegue</strong>.","tip":"<strong>Modelo mental:</strong> o silêncio não é vazio — é abrigo. Guarda o pensamento que nasce do não-saber, do que ainda não virou dado, opinião nem postagem."},
      {"ic":"leaf","t":"Sair do Enxame","emph":"Enxame Digital","b":"O <em>enxame</em> (Schwarm) é a multidão conectada sem corpo nem alma comuns: barulho sincronizado, indignação em rebanho, milhões que reagem juntos sem nunca formar um \"nós\". <strong>Tornar-se idiota é sair do enxame</strong> — recuperar a solidão, a distância, a singularidade que nenhum dado alcança porque ela se recusa a virar dado.","tip":"<strong>Sinal de alerta:</strong> dirão que é saída individualista, fuga sem programa. A resposta de Han: o gesto filosófico vem antes — sem o silêncio que devolve o sujeito a si, nenhum \"nós\" verdadeiro nasce.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["A resistência à psicopolítica é o idiotismo: ousar ser singular, à parte, desconectado do coro.", "Resistir é exercer a potência do \"não\" — não comunicar, não se expor, não reagir. Subtrair, não somar.", "O silêncio, o segredo e a saída do enxame guardam a única liberdade que o dado não consegue capturar."],
  },
]
