# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'Os Quatro Compromissos'
(Don Miguel Ruiz). Frameworks: a domesticação e o sonho do planeta; o Juiz, a
Vítima e o Livro da Lei; os quatro acordos (impecável com a palavra; não levar
para o lado pessoal; não tirar conclusões precipitadas; sempre fazer o melhor);
a quebra de acordos antigos (as 3 maestrias); a liberdade pessoal; e o 5º acordo
(seja cético, mas aprenda a ouvir). Síntese dos frameworks amplamente
documentados — não reproduz o texto. Atribuída ao autor."""

BOOK = {
 "title": "Os Quatro Compromissos",
 "author": "Don Miguel Ruiz",
 "header_light": "OS QUATRO",
 "header_bold": "COMPROMISSOS",
 "subtitle": "VISÃO GERAL · QUATRO ACORDOS PARA A LIBERDADE PESSOAL",
 "intro": "Você firmou milhares de acordos sem jamais ter sido consultado. Don Miguel Ruiz traz da tradição tolteca uma verdade serena e desconcertante: aquilo que você chama de 'eu' foi acordado por outros e instalado em você quando criança — a domesticação. Desde então um Juiz condena, uma Vítima padece, e um Livro da Lei herdado decide o que é certo. Não se trata de melhorar dentro dessas regras, mas de trocá-las. Os quatro acordos são quatro promessas novas, simples como água, que substituem o medo pelo amor e devolvem a liberdade que você teve quando criança.",
 "description": "O clássico de Don Miguel Ruiz, colhido na sabedoria tolteca. A vida como um sonho coletivo e a domesticação que nos faz sonhá-lo; o Juiz, a Vítima e o Livro da Lei que governam por dentro; os QUATRO acordos — seja impecável com a palavra, não leve nada para o lado pessoal, não tire conclusões precipitadas, sempre faça o melhor que puder. Conhecê-los é fácil; vivê-los é o trabalho de uma vida. No fim, a quebra dos acordos antigos abre caminho à liberdade pessoal — e o quinto acordo a sela: duvide das palavras, mas aprenda a ouvir.",
 "tags": ["Sabedoria", "Autoconhecimento", "Espiritualidade"],
 "progress": "8 Capítulos",
 "cover": "assets/quatro-compromissos-cover.png",
 "overview_cards": [
   {"ic":"key","t":"Os Quatro Acordos","b":"Quatro promessas simples, feitas consigo, que tomam o lugar dos acordos de medo:","list":[
     "<strong>Seja impecável com a palavra</strong> — ela cria ou destrói; ponha-a a serviço da verdade.",
     "<strong>Não leve nada para o lado pessoal</strong> — o que os outros fazem é o sonho deles, não o seu.",
     "<strong>Não tire conclusões precipitadas</strong> — onde você suporia, tenha a coragem de perguntar.",
     "<strong>Sempre faça o melhor que puder</strong> — e o seu melhor muda a cada dia; por isso, sem autojulgamento.",
   ],"tip":"<strong>Como aplicar:</strong> não são frases para concordar, são acordos para honrar. Mudam a vida quando praticados todo dia, não quando apenas entendidos.","wide":True},
   {"ic":"layers","t":"A Máquina do Sofrimento","b":"Antes dos acordos, é preciso enxergar com calma o que governa você por dentro:","list":[
     "<strong>Domesticação</strong> — por recompensa e castigo, aceitamos as crenças dos adultos como nossas.",
     "<strong>Livro da Lei</strong> — o conjunto de tudo o que você guarda como verdade inquestionável.",
     "<strong>O Juiz</strong> — a voz que condena cada desvio da regra herdada.",
     "<strong>A Vítima</strong> — a parte de você que recebe a culpa e carrega a dor.",
   ],"tip":"<strong>Modelo mental:</strong> esse trio é um parasita que se alimenta do seu veneno emocional. Negar-lhe o veneno é o que os quatro acordos fazem.","wide":True},
   {"ic":"leaf","t":"O Destino: Liberdade Pessoal","b":"A meta não é tornar-se uma pessoa melhor — é tornar-se uma pessoa <strong>livre</strong>. Reaver a leveza e a verdade da criança que você foi antes da domesticação, e viver à sua própria imagem, sem medo do que pensam e sem fome de aprovação.","tip":"<strong>Bússola:</strong> diante de qualquer escolha, pergunte 'isto nasce do medo ou do amor?'. O amor é sempre o caminho de volta para casa."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-domesticacao-sonho","sub":"CAPÍTULO 1: A Domesticação e o Sonho do Planeta",
  "intro":"Aquilo que você acredita ser 'você' chegou de fora para dentro. Antes de mudar de vida, é preciso ver, com serenidade, que a vida que você vive é um sonho — um acordo coletivo que você aprendeu cedo demais para escolher.",
  "cards":[
      {"ic":"book","t":"O Sonho do Planeta","emph":"Sonho","b":"O que você chama de 'realidade' é, na verdade, um imenso <strong>sonho coletivo</strong>. Leis, religiões, papéis e juízos de certo e errado foram sonhados pela cultura antes de você nascer, e depositados na sua mente. Você não vê o mundo como ele é; você vê o sonho que lhe ensinaram a ver.","tip":"<strong>Modelo mental:</strong> diante de qualquer regra que pareça evidente, pergunte com calma: 'isto é a realidade, ou apenas o sonho que combinaram para mim?'."},
      {"ic":"layers","t":"A Domesticação do Humano","emph":"Domesticação","b":"Assim como se adestra um animal por <strong>recompensa e castigo</strong>, a criança é domesticada a tomar como suas as crenças dos adultos. Por medo de perder o amor de quem ama, ela aceita o roteiro. Chega o dia em que ninguém mais precisa vigiá-la: ela aprendeu a se domesticar sozinha.","tip":"<strong>Sinal de alerta:</strong> a domesticação está completa quando você passa a punir a si mesmo por regras que outros escreveram.","warn":True},
      {"ic":"scale","t":"O Juiz, a Vítima e o Livro da Lei","emph":"Juiz, a Vítima e o Livro","b":"A máquina interna do sofrimento tem três peças, sempre em movimento: o código herdado que você não questiona; o julgamento que não cessa contra si; e <strong>a Vítima, que abaixa a cabeça e carrega a dor</strong>. Juntas, elas fazem girar a culpa e a vergonha, dia após dia, sem que você perceba.","tip":"<strong>Prática:</strong> repare na voz que o condena por dentro. Ela não é a 'voz da razão' — é apenas o Juiz repetindo uma lei que você nunca assinou."},
      {"ic":"eye","t":"O Acordo Que Tudo Sustenta","emph":"Acordo","b":"Toda crença que você ouviu, acolheu sem questionar e tomou por verdade se tornou um <strong>acordo</strong>. A sua vida inteira é a soma silenciosa dos acordos que firmou consigo mesmo. Quase nenhum foi escolhido com lucidez — e é aqui que mora a esperança: tudo o que foi acordado pode ser desfeito.","tip":"<strong>Pergunta-chave:</strong> ao sentir uma limitação por dentro, pare e pergunte: 'eu decidi acreditar nisto, ou apenas herdei este acordo?'."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["O que você chama de 'eu' é, em grande parte, acordos que aceitou antes de poder escolher.","Juiz, Vítima e Livro da Lei são a máquina interna do sofrimento — vê-la, sem se julgar, é o primeiro passo para a liberdade.","A domesticação que você mesmo faz é a mais difícil de soltar; os quatro acordos são os acordos novos que tomam o seu lugar."]},

 {"slug":"ch02-impecavel-palavra","sub":"CAPÍTULO 2: Acordo 1 — Seja Impecável com a Palavra",
  "intro":"De todas as ferramentas que você tem, a palavra é a mais poderosa: pode criar e pode destruir. Ser impecável é usá-la na direção da verdade e do amor — começando, sempre, pela palavra que você dirige a si mesmo.",
  "cards":[
      {"ic":"spark","t":"A Palavra como Magia","emph":"Magia","b":"A palavra não serve apenas para nomear as coisas — ela tem o <strong>poder de criar</strong>. É a força com que você expressa e dá forma a tudo o que vive. O que você diz de si e dos outros é uma semente plantada na mente: pode florescer em confiança e beleza, ou germinar em medo por anos. A palavra é magia, e toda magia se usa com cuidado.","tip":"<strong>Como aplicar:</strong> antes de falar, faça uma pequena pausa. Pergunte 'esta palavra cria ou destrói?' — e deixe a intenção, não o impulso, abrir a boca."},
      {"ic":"key","t":"Impecável — Sem Pecado Contra Si","emph":"Impecável","b":"A palavra impecável vem do latim <em>sine peccato</em>: <strong>sem pecado</strong>. E pecar, aqui, não tem nada a ver com castigo divino — é tudo o que você faz contra si mesmo. Ser impecável com a palavra é, antes de tudo, parar de usá-la como arma contra a própria pessoa, e voltá-la inteira a favor da verdade.","tip":"<strong>Regra:</strong> o 'como eu sou burro' ou o 'nunca dou certo', dito sem pensar, é a forma mais comum de magia voltada contra você. Repare nele primeiro."},
      {"ic":"wave","t":"A Fofoca como Veneno","emph":"Fofoca","b":"A fofoca é o uso mais corriqueiro e mais nocivo da palavra. Ela carrega <strong>veneno emocional</strong>: passa adiante, em segredo, o ressentimento de um, e contamina o modo como muitos passam a enxergar uma pessoa. Como um fio invisível, prende quem fala e quem ouve no mesmo medo. Falar bem é mais raro — e muito mais curador.","tip":"<strong>Armadilha:</strong> 'eu só te conto isto para o seu bem' costuma ser a roupa gentil que a fofoca veste para entrar. Repare quando ela bater à sua porta.","warn":True},
      {"ic":"leaf","t":"A Palavra é uma Semente","emph":"Semente","b":"Basta um adulto distraído dizer a uma criança que ela não tem talento, e a frase pode <strong>criar raiz e abafar</strong> aquele dom por décadas. A mente recebe o que ouve como terra recebe a semente — sem filtrar. Por isso, as palavras de quem amamos pesam tanto, e por isso o trabalho de uma vida pode ser arrancar, com paciência, o que plantaram cedo demais.","tip":"<strong>Modelo mental:</strong> cuide das palavras que semeia nos outros, e das que ainda crescem em você. Algumas pedem rega; outras, simplesmente, soltar."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["A palavra cria realidade; ser impecável é pô-la a favor da verdade e do amor, nunca contra si mesmo.","A fofoca é veneno emocional — não a produza nem a leve adiante; falar bem cura mais do que parece.","O autoabuso verbal é a magia mais comum de todas; mude o que você diz a si por dentro, e o sonho começa a mudar."]},

 {"slug":"ch03-lado-pessoal","sub":"CAPÍTULO 3: Acordo 2 — Não Leve Nada para o Lado Pessoal",
  "intro":"Nada do que os outros fazem é por sua causa. Cada um age a partir do próprio sonho — das suas crenças, das suas feridas, do seu medo. Quando você deixa de tomar o mundo para si, fica em paz com o que dizem e fazem.",
  "cards":[
      {"ic":"lens","t":"Tudo é Projeção do Outro","emph":"Projeção","b":"Eis a verdade que liberta: o que vem da boca alheia — a raiva ou o elogio — fala da pessoa que fala, não de você. Cada um vive no próprio sonho, e o que ela atira é a <strong>projeção dessa realidade que só ela habita</strong>. A ofensa não retrata o alvo; retrata, por inteiro, quem a lançou.","tip":"<strong>Modelo mental:</strong> ao receber um ataque, lembre-se com serenidade: 'isto é sobre o sonho dele, não sobre mim'. E a farpa passa sem ferir."},
      {"ic":"mask","t":"A Importância Pessoal","emph":"Importância Pessoal","b":"Tomar para si o que os outros dizem nasce de uma ilusão muito comum: a de que tudo gira em torno de você. A domesticação nos convenceu de que somos o centro. Mas quando você pousa, com humildade, essa <strong>importância pessoal</strong>, descobre que a maior parte das ofensas simplesmente deixa de alcançá-lo.","tip":"<strong>Sinal de alerta:</strong> se um xingamento de um estranho na rua dói de verdade, a dor não veio dele — veio da crença secreta de que você era o centro daquela cena.","warn":True},
      {"ic":"scale","t":"Imunidade nos Dois Sentidos","emph":"Dois Sentidos","b":"A mesma serenidade que protege da crítica protege do elogio: <strong>se o aplauso o enche, a censura o esvazia</strong>. Quem não leva nada para o lado pessoal não se quebra com a ofensa do tolo nem se infla com o louvor da multidão. A paz mora em saber quem você é, sem depender da opinião de quem mal o conhece.","tip":"<strong>Regra:</strong> quem precisa do aplauso para se sentir inteiro entrega aos outros o leme da própria vida. A liberdade começa quando você o retoma."},
      {"ic":"leaf","t":"Não Coma o Veneno","emph":"Veneno","b":"No instante em que você acolhe a acusação e a toma por verdade, o <strong>veneno emocional</strong> entra e adoece por dentro. Não levar para o lado pessoal não é virar de pedra — é deixar de comer o veneno que lhe oferecem. O ataque chega, encosta na pele e segue adiante, sem encontrar onde se fixar.","tip":"<strong>Atalho:</strong> quando alguém lhe estender o fel de uma opinião amarga, você não precisa recusar nem revidar. Basta não engolir."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["O que os outros fazem é por causa deles; até a ofensa é um autorretrato de quem ofende.","Levar para o lado pessoal é a importância pessoal disfarçada — a crença de que você é o centro de tudo.","A paz nasce de saber quem você é; então o elogio não infla e a crítica não derruba."]},

 {"slug":"ch04-conclusoes-precipitadas","sub":"CAPÍTULO 4: Acordo 3 — Não Tire Conclusões Precipitadas",
  "intro":"Supomos o tempo todo — e tratamos a suposição como se fosse verdade. Desse hábito nasce quase todo o sofrimento das relações. O antídoto é simples de dizer e corajoso de fazer: perguntar.",
  "cards":[
      {"ic":"gap","t":"A Suposição como Veneno","emph":"Suposição","b":"A mente não suporta o vazio da dúvida; então o preenche com histórias. Inventamos o que o outro pensou, sentiu e quis — e <strong>acreditamos na invenção como se fosse fato</strong>. A partir daí, sofremos, acusamos e nos defendemos de crimes que aconteceram apenas dentro da nossa cabeça.","tip":"<strong>Sinal de alerta:</strong> a frase 'eu já sei o que ele quis dizer com isso' é quase sempre o começo de um drama que ninguém viveu, exceto você.","warn":True},
      {"ic":"bubble","t":"A Coragem de Perguntar","emph":"Coragem de Perguntar","b":"Há um único remédio para a suposição: <strong>perguntar, com clareza e sem rodeios</strong>. Exige coragem, porque perguntar é admitir que não sabemos — e isso nos deixa expostos. Mas uma pergunta franca dissolve, em segundos, a névoa que a imaginação levaria meses construindo.","tip":"<strong>Regra:</strong> o pequeno desconforto de perguntar agora vale mais do que mil noites passadas remoendo o que você apenas supôs."},
      {"ic":"bulb","t":"Ninguém Lê a Mente","emph":"Ninguém Lê a Mente","b":"Há uma crença que adoece o amor: a de que quem nos ama deveria adivinhar o que precisamos, sem que digamos. E nos magoamos quando o outro não acerta o que nunca foi dito. A verdade é serena e simples: <strong>o que não é falado, para o outro, não existe.</strong>","tip":"<strong>Como aplicar:</strong> deixe de lado a expectativa silenciosa e diga, com gentileza, o que você quer. Pedir não é fraqueza — é clareza."},
      {"ic":"link","t":"A Pergunta Dissolve o Drama","emph":"Dissolve o Drama","b":"Alguém não responde ao seu bom-dia, e você já construiu uma história inteira de desprezo e abandono. Até que pergunta — e descobre que a pessoa apenas estava distraída, ou doente, ou perdida nos próprios pensamentos. <strong>Todo aquele sofrimento existiu só dentro de você.</strong> A pergunta fura, na hora, a bolha que a suposição inflou.","tip":"<strong>Prática:</strong> onde houver dúvida no ar, traga a luz simples de uma pergunta. É o jeito mais barato e mais limpo de evitar o drama."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["Quase todo conflito nas relações nasce de supor em vez de perguntar.","Tenha a coragem de perguntar e de pedir o que precisa — ninguém é obrigado a ler a sua mente.","A comunicação clara é a forma mais simples e mais barata de prevenir o sofrimento."]},

 {"slug":"ch05-melhor-que-puder","sub":"CAPÍTULO 5: Acordo 4 — Sempre Faça o Melhor que Puder",
  "intro":"Este é o acordo que dá vida aos outros três. Fazer sempre o seu melhor — sabendo que o seu melhor muda a cada momento — guarda você do autojulgamento, da culpa e do arrependimento.",
  "cards":[
      {"ic":"clock","t":"O Melhor é Variável","emph":"Melhor é Variável","b":"O seu melhor não é uma linha reta — ele <strong>muda de um dia para o outro</strong>, conforme o sono, o humor, a saúde. O que você consegue numa manhã cansada é diferente do que consegue descansado, e está tudo certo: cada um é o seu melhor possível naquelas condições. Faça o melhor que houver hoje, e não cobre dele o melhor de ontem.","tip":"<strong>Modelo mental:</strong> não exija de um dia exausto o desempenho de um dia inteiro. Calibre a expectativa ao que o momento, de verdade, pode dar."},
      {"ic":"target","t":"Sem Autojulgamento","emph":"Autojulgamento","b":"Este acordo é a chave que fecha a porta do sofrimento. Quando você dá o máximo que era possível naquele momento, <strong>tira do Juiz qualquer motivo para condená-lo</strong>. Não sobra espaço para a culpa nem para o arrependimento, porque você sabe, em paz, que não havia mais a oferecer.","tip":"<strong>Sinal de alerta:</strong> o perfeccionismo que se cobra mesmo na exaustão não é virtude — é o velho Juiz com uma roupa nova.","warn":True},
      {"ic":"spark","t":"Aja pela Ação, não pela Recompensa","emph":"Recompensa","b":"Quem trabalha só de olho na recompensa carrega a tarefa como um fardo. Mas quando o que move você é <strong>o gosto de fazer pelo simples fazer</strong>, a ação já se paga no próprio instante. O prêmio que vier depois deixa de ser o que o sustenta — vira apenas um presente bem-vindo.","tip":"<strong>Regra:</strong> o salário e o aplauso chegam atrasados. A alegria de fazer bem-feito chega agora, e é ela que sustenta o caminho."},
      {"ic":"steps","t":"Nem Mais, Nem Menos","emph":"Nem Mais, Nem Menos","b":"Querer fazer 'mais que o seu melhor' esgota você e azeda o amor pela tarefa. Fazer de menos, por preguiça, abre a porta para a velha Vítima voltar. O ponto justo e saudável está sempre no <strong>limite natural do dia</strong> — nem além dele, nem aquém.","tip":"<strong>Como aplicar:</strong> trate o seu limite como uma linha de chegada: alcance-a e celebre. Tentar rompê-la todo dia, na marra, é o que adoece."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["O seu melhor muda a cada momento; fazer o melhor possível agora é tudo o que se pode pedir de você.","Quem sempre faz o seu melhor não tem do que se arrepender nem por que se julgar.","Aja pela alegria de fazer, não pela recompensa — é assim que os outros três acordos viram hábito."]},

 {"slug":"ch06-quebrar-acordos","sub":"CAPÍTULO 6: A Quebra de Acordos Antigos — A Arte da Transformação",
  "intro":"Saber os quatro acordos não basta: a domesticação só se desfaz na prática. Transformar-se é o trabalho de um guerreiro — quebrar, um a um, os acordos antigos feitos de medo e pôr os novos em seu lugar.",
  "cards":[
      {"ic":"mountain","t":"As Três Maestrias Toltecas","emph":"Maestrias","b":"O caminho tolteca tem três degraus. Primeiro, a <strong>consciência</strong>: ver com clareza a domesticação e o sonho em que se vive. Depois, a <strong>transformação</strong>: trocar os acordos antigos pelos novos, no dia a dia. Por fim, o <strong>amor</strong>, ou intenção: viver sem esforço, porque o medo já não dá as cartas.","tip":"<strong>Mapa:</strong> entender a própria dor não solta as amarras. Só a prática, repetida com paciência, refaz o contrato que você tinha consigo."},
      {"ic":"sword","t":"O Guerreiro contra o Parasita","emph":"Guerreiro","b":"O trio interno — Juiz, Vítima e Livro da Lei — funciona como um parasita que se alimenta da sua dor. Curar-se pede a postura serena e firme de um <strong>guerreiro</strong>: uma guerra paciente, sem ódio, contra o próprio medo. E a vitória não vem pela força, vem por inanição — você deixa de alimentar os pensamentos que o sustentam.","tip":"<strong>Regra:</strong> os hábitos antigos foram fixados por repetição. É também por repetição, em sentido contrário, que eles se soltam."},
      {"ic":"pivot","t":"A Morte como Mestra","emph":"Consciência da Morte","b":"Quando a vida segue tranquila, nos perdemos em fofocas e ninharias. A tradição tolteca convida a manter perto a <strong>consciência de que cada momento pode ser o último</strong>. Lembrar da morte não entristece — clareia: diante dela, o medo do ridículo se dissolve, o essencial brilha e o resto, simplesmente, perde a importância.","tip":"<strong>Modelo mental:</strong> deixe a finitude ser a sua conselheira. Ela descarta na hora as brigas pequenas e devolve o que de fato merece o seu dia."},
      {"ic":"link","t":"Substituir, não só Remover","emph":"Substituir","b":"A mente não tolera o vazio. Se você apenas arranca uma crença antiga sem pôr nada em seu lugar, o espaço aberto será <strong>logo reocupado pelos velhos acordos</strong>. Por isso o trabalho não é só limpar — é plantar o novo no lugar do que saiu, todos os dias, até criar raiz.","tip":"<strong>Armadilha:</strong> fechar o livro entendendo a teoria não muda nada por si só. A transformação real acontece na prática paciente do dia seguinte.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["Conhecer os acordos é o começo; transformar-se pede a prática serena e diária de um guerreiro.","O caminho tem três maestrias — consciência, transformação e amor — e tem a morte como mestra.","Cada acordo antigo que se quebra precisa ser substituído por um novo, ou o medo volta a ocupar o vazio."]},

 {"slug":"ch07-liberdade-novo-sonho","sub":"CAPÍTULO 7: O Novo Sonho — A Liberdade Pessoal",
  "intro":"O destino dos quatro acordos é a liberdade pessoal: o direito de ser quem você realmente é, sem medo e sem julgamento. É o reencontro com a leveza que você tinha quando criança, antes da domesticação.",
  "cards":[
      {"ic":"leaf","t":"A Liberdade Pessoal","emph":"Liberdade Pessoal","b":"Liberdade é o fim do tribunal interno. Ela chega quando você deixa de implorar por aprovação e passa a viver <strong>fiel à própria verdade</strong>, e não à imagem que o mundo esperava de você. Não é fazer o que se quer a qualquer custo — é ser o que se é, em paz, sem precisar pedir licença.","tip":"<strong>Bússola:</strong> diante de qualquer escolha difícil, pergunte: 'faço isto por medo de ser rejeitado, ou porque está em acordo comigo?'."},
      {"ic":"spark","t":"Recuperar a Espontaneidade","emph":"Recuperar","b":"A criança pequena não calcula nem se envergonha: ela ri, chora, brinca e vive inteira no instante. O caminho tolteca não pede que você acumule doutrinas — pede que você <strong>recupere</strong> aquela espontaneidade que sempre foi sua, agora somada à sabedoria de um adulto que já não se deixa enganar.","tip":"<strong>Modelo mental:</strong> despertar não é acrescentar coisas à mente; é tirar delas o que não era seu, até sobrar a verdade que você sempre foi."},
      {"ic":"constellation","t":"Céu ou Inferno: os Dois Sonhos","emph":"Dois Sonhos","b":"Você vive, o tempo todo, dentro de um sonho. Se ele é feito de medo, o seu dia a dia se torna um pequeno inferno de cobrança e culpa. Se ele <strong>nasce da palavra impecável e do amor</strong>, a mesma vida se torna o céu. Céu e inferno não estão depois da morte — são dois jeitos de sonhar o agora.","tip":"<strong>Como aplicar:</strong> olhe para os pesos da sua semana. A maior parte deles não vem do mundo lá fora; vem do sonho que você está sonhando por dentro."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["O destino dos quatro acordos é a liberdade pessoal: ser quem você é, sem medo nem julgamento.","Liberdade é reaver a espontaneidade da criança, somada à consciência do adulto.","Você sempre vive num sonho — o medo o faz inferno, o amor o faz céu; os acordos escolhem qual."]},

 {"slug":"ch08-quinto-acordo","sub":"CAPÍTULO 8: O Quinto Acordo (obra posterior)",
  "intro":"Em obra posterior, Don Miguel Ruiz acrescenta um acordo que costura todos os outros: duvide, mas escute. Não está entre os quatro originais, mas os completa — mencionado aqui de leve.",
  "cards":[
      {"ic":"lens","t":"Seja Cético, mas Aprenda a Ouvir","emph":"Cético","b":"O quinto acordo nasce de duas atitudes que parecem opostas e se completam. O ceticismo protege você das mentiras — as dos outros e as suas. A escuta deixa você acolher a verdade que existe por trás das palavras. <strong>Duvidar da superfície e ouvir o fundo</strong> é a forma mais madura de se comunicar.","tip":"<strong>Prática:</strong> ouça em duas camadas. Não compre a explicação fácil de alguém, mas perceba, com cuidado, a dor que talvez a tenha gerado."},
      {"ic":"layers","t":"As Palavras são Símbolos","emph":"Palavras são Símbolos","b":"O ceticismo é necessário porque toda linguagem é apenas um <strong>símbolo, sempre imperfeito</strong>. As palavras são aproximações da realidade, nunca a própria coisa. Quando você deixa de tomar ao pé da letra o que dizem, se livra de muitas brigas por sentidos que ninguém quis dar. Olhe para o que move a pessoa, não só para o que sai da boca.","tip":"<strong>Sinal de alerta:</strong> até a sua voz interna, a que diz 'eu não mereço', é apenas a repetição de símbolos que lhe ensinaram. Duvide dela também.","warn":True},
      {"ic":"scale","t":"Ceticismo + Escuta = Discernimento","emph":"Discernimento","b":"Ceticismo sem escuta endurece em arrogância e isola. Escuta sem ceticismo amolece em ingenuidade e se deixa enganar. É a união dos dois — a dúvida que protege e a escuta que acolhe — que forma o <strong>discernimento</strong>, o fecho sereno de tudo o que os acordos ensinam.","tip":"<strong>Regra:</strong> em cada fala que receber, deixe de lado o que for veneno e guarde apenas o que for verdadeiro e útil para você."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["O quinto acordo une os quatro: duvide das palavras, mas escute a intenção por trás delas.","Ceticismo sem escuta é arrogância; escuta sem ceticismo é ingenuidade — o discernimento une os dois.","Aplique o ceticismo primeiro às suas próprias crenças: é a transformação que continua."]},
]
