# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'Rápido e Devagar: Duas Formas de Pensar'
(Daniel Kahneman). Frameworks: Sistema 1 vs. Sistema 2, atenção/esforço, WYSIATI, substituição e
heurísticas, ancoragem, disponibilidade/representatividade, falácia da conjunção (Linda)/regressão,
ilusão de validade, excesso de confiança/pré-mortem, teoria do prospecto, enquadramento/contabilidade
mental, os dois eus (pico-fim).
Base: síntese dos frameworks amplamente documentados — não reproduz o texto."""

BOOK = {
 "title": "Rápido e Devagar: Duas Formas de Pensar",
 "author": "Daniel Kahneman",
 "header_light": "RÁPIDO",
 "header_bold": "E DEVAGAR",
 "subtitle": "VISÃO GERAL · DUAS FORMAS DE PENSAR",
 "intro": "Você acha que pensa. Na maior parte do tempo, alguém pensa por você — e mora na sua cabeça. O Sistema 1 é rápido, automático, intuitivo: entrega a resposta pronta antes de você notar a pergunta. O Sistema 2 é lento, lógico, esforçado — e tão preguiçoso que costuma assinar embaixo do que o Sistema 1 sugere, sem reler. Daniel Kahneman, único psicólogo a ganhar o Nobel de Economia, escreveu este livro com uma humildade rara: nem ele, que estudou os vieses a vida inteira, ficou imune a eles. A intuição não é mágica — é reconhecimento. E quando o terreno é irregular, ela é só palpite vestido de certeza.",
 "description": "O mapa da mente humana traçado por Daniel Kahneman, Nobel de Economia. Dois sistemas em disputa surda — o rápido que intui, o lento que confere; o WYSIATI, segundo o qual a mente decide com o pouco que vê e ignora o que ignora; as heurísticas e os vieses que erram de forma previsível (ancoragem, disponibilidade, representatividade, a falácia de Linda, a taxa-base esquecida, a regressão à média); o excesso de confiança e a vacina do pré-mortem; a Teoria do Prospecto — onde perder dói o dobro de ganhar; e os dois eus, o que vive e o que lembra, em desacordo sobre a própria vida.",
 "tags": ["Psicologia", "Decisão", "Vieses Cognitivos"],
 "progress": "12 Capítulos",
 "cover": "assets/rapido-e-devagar-cover.png",
 "overview_cards": [
   {"ic":"fork","t":"Sistema 1 vs. Sistema 2","b":"Dois personagens dividem a sua cabeça. O <strong>Sistema 1</strong> é rápido, automático, intuitivo — fala primeiro e nunca cala. O <strong>Sistema 2</strong> é lento, lógico, esforçado — e <strong>preguiçoso a ponto de delegar quase tudo</strong>. Você se identifica com o segundo; quem decide, quase sempre, é o primeiro.","tip":"<strong>Como aplicar:</strong> antes de cravar, pergunte-se 'essa resposta veio sozinha (S1) ou eu de fato a calculei (S2)?'.","wide":True},
   {"ic":"eye","t":"WYSIATI — o que você vê é tudo que há","b":"O Sistema 1 monta a história mais redonda possível com o pouco que tem à mão — e a toma pelo mundo inteiro. Não pergunta o que ficou de fora. Por isso <strong>a confiança mede a coerência da história, não a qualidade da prova</strong>: quanto menos você sabe, mais fácil tudo se encaixa.","tip":"<strong>Modelo mental:</strong> a pergunta que desarma a ilusão é 'o que me falta saber — e isso mudaria minha conclusão?'."},
   {"ic":"scale","t":"Aversão à Perda","b":"Não julgamos o quanto temos, mas o quanto mudou a partir de onde estamos — e a dor e o prazer não pesam igual: <strong>perder dói cerca de duas vezes mais do que ganhar agrada</strong>. Essa assimetria, e não o cálculo frio, governa as nossas apostas. É o coração da Teoria do Prospecto.","tip":"<strong>Regra:</strong> não recuse uma aposta a seu favor só porque o medo de perder fala mais alto que a vontade de ganhar."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-os-dois-sistemas","sub":"CAPÍTULO 1: Os Dois Sistemas",
  "intro":"A mente trabalha em duas marchas. O Sistema 1 pensa rápido, automático, sem o menor esforço; o Sistema 2 pensa devagar, com suor e lógica. A divisão de trabalho é eficiente — mas é também a fonte de quase todos os nossos erros, porque a maioria das decisões sai pronta do Sistema 1, sem que o Sistema 2 chegue a ser consultado.",
  "cards":[
      {"ic":"spark","t":"O Piloto Automático Manda","emph":"Piloto Automático","b":"O Sistema 1 trabalha sem você pedir: lê o tom de uma frase, julga uma cara em meio segundo, completa “pão com…” antes da sua vontade. Não há esforço, nem sensação de comando — e ainda assim ele <strong>gera quase todas as impressões e impulsos que você terá hoje</strong>. Você jura que pilota; na maior parte do dia, apenas assiste de carona.","tip":"<strong>Modelo mental:</strong> trate a primeira resposta como um palpite do S1 — em geral excelente, às vezes uma cilada.","wide":True},
      {"ic":"clock","t":"O Sistema 2 Custa Caro","emph":"Custa Caro","b":"Multiplicar 17 por 24, comparar duas apólices, segurar a língua na hora certa: tudo isso convoca o Sistema 2, que aloca atenção, queima energia e <strong>cansa como um músculo que se exige demais</strong>. Caro como é, ele só comparece a contragosto — quando o S1 trava ou quando errar sai caro o bastante para valer o trabalho.","tip":"<strong>Regra:</strong> diante do complexo ou do irreversível, convoque o S2 de propósito — ele nunca aparece por iniciativa própria."},
      {"ic":"mask","t":"O Supervisor que Só Assina","emph":"Só Assina","b":"O Sistema 2 é o “eu” que você imagina ser: racional, no comando, dono das próprias conclusões. Na prática, faz o papel de <strong>supervisor sonolento que carimba sem reler o que o S1 lhe entrega</strong>. Você sente que pesou cada lado; a verdade é que a intuição chegou pronta e a razão apenas assinou embaixo.","tip":"<strong>Cuidado:</strong> a ilusão de ter “decidido racionalmente” quando o S1 já tinha a resposta e o S2 só deu o aval.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Quase tudo o que você pensa, sente e faz nasce no Sistema 1, à sua revelia.","O Sistema 2 é lento e econômico — e por economizar, deixa os erros do S1 passarem.","Decidir melhor começa por uma pergunta simples: em qual sistema eu estou agora?"]},

 {"slug":"ch02-atencao-esforco-piloto-automatico","sub":"CAPÍTULO 2: Atenção, Esforço e Piloto Automático",
  "intro":"O esforço mental é caro: pensar com cuidado consome um recurso de verdade escasso, fadiga como exercício físico e obedece à lei do menor esforço. Por isso a mente delega quase tudo ao Sistema 1 e só desperta o Sistema 2 quando é empurrada — e raramente o é a tempo.",
  "cards":[
      {"ic":"leaf","t":"A Lei do Menor Esforço","emph":"Menor Esforço","b":"Entre dois caminhos para o mesmo lugar, a mente escolhe sempre o <strong>que custa menos pensar</strong>. Conferir dá trabalho; então o padrão é pular a checagem e aceitar o palpite que já chegou. Não é vício de caráter — é economia de um recurso que de fato acaba: a atenção. A preguiça do pensamento é uma lei, não um defeito.","tip":"<strong>Como aplicar:</strong> não aposte na força de vontade o dia inteiro; desenhe o ambiente para precisar menos dela.","wide":True},
      {"ic":"scale","t":"O Mesmo Poço Esgotado","emph":"Mesmo Poço","b":"Autocontrole e raciocínio bebem do <strong>mesmo poço, e ele tem fundo</strong>: gastar num seca o outro. Quem resiste ao doce decide pior logo depois; quem decide o dia todo cede à tentação à noite. É o esgotamento do ego — e fome, sono e multitarefa devolvem em silêncio o volante ao Sistema 1.","tip":"<strong>Regra:</strong> nunca decida o que importa com fome, exausto ou fazendo três coisas ao mesmo tempo."},
      {"ic":"eye","t":"O Gorila que Ninguém Vê","emph":"Gorila","b":"No experimento famoso, ocupadas em contar passes de basquete, <strong>metade das pessoas não vê um sujeito fantasiado de gorila atravessar a tela</strong> e bater no peito. O foco acende um ponto e apaga toda a volta. Somos cegos ao óbvio — e, pior, cegos à própria cegueira: nem suspeitamos do que deixamos de ver.","tip":"<strong>Cuidado:</strong> supor que “estou prestando atenção” garante enxergar o que importa — todo foco cobra um pedaço da periferia.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["Pensar com esforço é caro, e a mente economiza por padrão — pula a conferência.","Cansaço, fome e multitarefa entregam o controle de volta ao Sistema 1.","Em vez de exigir força de vontade, projete o contexto para precisar de menos."]},

 {"slug":"ch03-wysiati-coerencia","sub":"CAPÍTULO 3: WYSIATI e a Máquina de Saltar a Conclusões",
  "intro":"O Sistema 1 é uma máquina de saltar a conclusões: com os fragmentos que tem, costura a história mais coerente que consegue e a toma por toda a verdade. WYSIATI — 'o que você vê é tudo que há'. O que não sabemos simplesmente não entra na conta; e o que não entra na conta não nos faz duvidar.",
  "cards":[
      {"ic":"eye","t":"O que Você Vê é Tudo que Há","emph":"Tudo que Há","b":"O Sistema 1 fecha a história mais redonda que os dados à mão permitem — e a confunde com o mundo. Jamais se pergunta o que ficou de fora. Daí o paradoxo central: a sua <strong>confiança mede a coerência da narrativa, não o peso da prova</strong>. Quanto menos você sabe, menos cabos soltos restam — e mais fácil tudo se encaixa.","tip":"<strong>Como aplicar:</strong> a pergunta que fura a bolha é “o que não estou vendo — e isso mudaria a conclusão?”.","wide":True},
      {"ic":"link","t":"O Halo que Contamina Tudo","emph":"Halo","b":"Uma boa primeira impressão tinge tudo o que vem depois. O rosto simpático, a resposta dada com firmeza — e de repente <strong>você atribui à pessoa virtudes que nunca chegou a observar</strong>. Quem começa parecendo competente recebe crédito adiantado em cada frase seguinte. A coerência é construída pela ordem em que os fatos chegaram, não pelo que valem.","tip":"<strong>Modelo mental:</strong> desconfie de quem você admirou cedo demais — o halo costuma chegar antes da prova."},
      {"ic":"bubble","t":"A Ilusão de Verdade por Repetição","emph":"Repetição","b":"O que escorre fácil pela mente — familiar, claro, repetido — passa por mais verdadeiro, melhor, mais seguro. A simples <strong>repetição fabrica a sensação de verdade</strong>, ainda que a frase seja falsa: dita três vezes, começa a soar certa. Propaganda e boato não precisam de argumento — basta-lhes a fluência.","tip":"<strong>Cuidado:</strong> confundir “soou claro e familiar” com “é verdade”. Facilidade não é evidência.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["Julgamos com o que está ativado na cabeça, não com o que seria de fato relevante.","Facilidade e repetição fabricam a sensação de verdade — sem um único argumento.","Quanto menos você sabe, mais fácil — e mais perigoso — é fechar uma história coerente."]},

 {"slug":"ch04-substituicao-heuristicas","sub":"CAPÍTULO 4: Substituição e o Mecanismo das Heurísticas",
  "intro":"Quando a pergunta é difícil e a resposta tarda, o Sistema 1 faz um truque que você nem percebe: troca a pergunta dura por uma parecida e mais fácil, responde a esta e entrega o resultado como se fosse o pedido. Heurísticas são esses atalhos — úteis na maior parte das vezes, e por isso mesmo perigosos: erram com método.",
  "cards":[
      {"ic":"pivot","t":"A Troca de Pergunta Silenciosa","emph":"Troca de Pergunta","b":"Pergunta difícil — “esse candidato será um bom gestor?”. O Sistema 1 não a enfrenta: <strong>troca-a por uma vizinha e mansa</strong> — “gosto da cara dele?” — e devolve essa resposta no lugar da outra. A substituição é invisível. Você jura ter respondido à pergunta verdadeira, e ainda por cima com pressa e confiança a mais.","tip":"<strong>Como aplicar:</strong> antes de fechar um juízo, isole a pergunta que você queria responder da pergunta fácil que de fato respondeu.","wide":True},
      {"ic":"wave","t":"O Afeto Decide e Depois Argumenta","emph":"Afeto","b":"O atalho mais comum de todos é deixar o gostar ou o temer responder pelo mundo. Simpatizo com certa tecnologia? Então <strong>vejo seus riscos como baixos e seus ganhos como altos</strong> — sem um dado novo sequer. A conclusão emocional vem na frente, e a razão corre atrás fabricando os motivos. A ordem é o oposto da que imaginamos.","tip":"<strong>Modelo mental:</strong> o sentimento entrega a resposta; a razão só passa a maquiagem depois."},
      {"ic":"target","t":"Gostar Não é o Mesmo que Verdadeiro","emph":"Verdadeiro","b":"No fundo da substituição há uma confusão de dois mundos: tomar “<strong>isso me agrada</strong>” por “<strong>isso é provavelmente verdadeiro</strong>”. Uma resposta que desliza fácil parece certa por mero efeito da fluência. Mas a facilidade de sentir não prova coisa alguma — é só o S1 servindo o que estava à mão, não o que era exato.","tip":"<strong>Cuidado:</strong> tomar a fluência da resposta como sinal de que você respondeu à pergunta certa.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["Diante de perguntas difíceis, respondemos a outras mais fáceis — e nem notamos a troca.","O afeto (gostar ou temer) é a heurística mais comum e a mais poderosa de todas.","Para auditar um julgamento, separe a pergunta-alvo daquela que você de fato respondeu."]},

 {"slug":"ch05-ancoragem","sub":"CAPÍTULO 5: Ancoragem",
  "intro":"Mostre um número a alguém antes de pedir uma estimativa — mesmo um número absurdo, sorteado na sua frente — e a resposta dela escorregará na direção dele. É a ancoragem: talvez o mais robusto e mensurável de todos os vieses, justamente porque opera à luz do dia e ainda assim ninguém se desvia.",
  "cards":[
      {"ic":"pin","t":"Toda Estimativa Gravita na Âncora","emph":"Gravita","b":"Antes de cravar um número, o último que você viu já puxa a sua resposta para perto de si. Kahneman mostrou que <strong>até dígitos sorteados numa roleta deslocam as estimativas das pessoas</strong> — sem nenhuma relação com a pergunta. Daí a regra de negociação: quem solta o primeiro número não faz só uma proposta; desenha o campo em que os dois vão jogar.","tip":"<strong>Como aplicar:</strong> em negociação, abra com a sua âncora — quem diz o primeiro número define o terreno.","wide":True},
      {"ic":"steps","t":"Os Dois Motores da Âncora","emph":"Dois Motores","b":"A âncora prende por dois mecanismos ao mesmo tempo. Um é o <strong>ajuste insuficiente</strong>: o S2 parte do número dado e cansa de afastar-se cedo demais. O outro é a <strong>ativação seletiva</strong>: o S1 sai buscando só as memórias que combinam com a âncora. Um é deliberado, o outro automático — e ambos remam para o mesmo lado.","tip":"<strong>Regra:</strong> ancore de propósito quando puder; desconfie de todo número que apareceu pouco antes de você estimar."},
      {"ic":"sword","t":"Saber é Pouco — Pense o Oposto","emph":"Pense o Oposto","b":"O mais inquietante é que a âncora age <strong>mesmo quando você sabe que o número é absurdo e irrelevante</strong>. Acreditar que “não se deixou influenciar” é cair nela com elegância. A única defesa que funciona não é desprezar a âncora — é gastar esforço de S2 listando, uma a uma, as razões pelas quais ela estaria errada.","tip":"<strong>Cuidado:</strong> deixar o outro lado abrir a negociação enquanto você ainda nem decidiu a sua própria âncora.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Qualquer número visto antes de uma estimativa a puxa em sua direção.","A âncora age mesmo quando você sabe, e declara, que ela é irrelevante.","A defesa não é ignorá-la — é argumentar ativamente o oposto dela."]},

 {"slug":"ch06-disponibilidade-representatividade","sub":"CAPÍTULO 6: Disponibilidade e Representatividade",
  "intro":"Para estimar quão provável é algo, a mente usa dois atalhos que parecem sensatos e não são. A disponibilidade conta probabilidade pelo que vem fácil à lembrança. A representatividade conta pela semelhança com o estereótipo. Os dois cometem o mesmo pecado: substituem a estatística por uma impressão — e nos deixam errar com convicção.",
  "cards":[
      {"ic":"wave","t":"O que Lembra Fácil Parece Comum","emph":"Lembra Fácil","b":"Medimos a frequência de algo pela <strong>facilidade com que um exemplo salta à memória</strong> — nunca pelos números. Um desastre aéreo recente, vívido, repetido no noticiário, faz o avião parecer mais perigoso que o carro, quando é exatamente o contrário. O que é fácil de imaginar toma, sem pedir licença, o lugar do que é estatisticamente provável.","tip":"<strong>Como aplicar:</strong> meça o risco pela frequência real, não pela última manchete que ficou grudada em você.","wide":True},
      {"ic":"constellation","t":"O Estereótipo no Lugar da Conta","emph":"Estereótipo","b":"A representatividade decide a que grupo algo pertence pela <strong>semelhança com o protótipo guardado na cabeça</strong>, ignorando quão comum aquele grupo de fato é. O sujeito tímido e metódico “tem cara” de bibliotecário — e esquecemos que existem muito mais agricultores que bibliotecários. O perfil grita; a taxa-base não tem voz.","tip":"<strong>Regra:</strong> antes de encaixar o caso, pergunte “quão comum isso é na população?” — e só então ajuste pela semelhança."},
      {"ic":"gap","t":"A Taxa-Base que Some","emph":"Taxa-Base","b":"Atrás dos dois atalhos mora o mesmo erro: <strong>ignorar a frequência de base ao julgar um caso isolado</strong>. “Tem cara de” não é “é provável que seja”. Sem partir de quão comum algo é na população, qualquer descrição convincente nos faz apostar contra a estatística — e perder com a maior das certezas.","tip":"<strong>Cuidado:</strong> deixar o estereótipo do caso individual gritar mais alto do que a estatística da população inteira.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["A frequência que sentimos segue a facilidade de lembrar, não os dados.","A semelhança com o estereótipo nos cega para a estatística de base.","Comece pela taxa-base e só depois ajuste pela evidência do caso."]},

 {"slug":"ch07-linda-regressao","sub":"CAPÍTULO 7: A Falácia da Conjunção (Linda) e a Regressão à Média",
  "intro":"A representatividade arma duas ciladas elegantes. Numa, achamos que um cenário cheio de detalhes é mais provável que um genérico — o caso de Linda. Noutra, vemos um extremo voltar à média por puro acaso e insistimos em inventar uma causa — a regressão. Em ambas, a boa história derrota a boa estatística.",
  "cards":[
      {"ic":"layers","t":"O Detalhe que Reduz a Chance","emph":"Detalhe","b":"Linda é descrita como brilhante, engajada, crítica. Quase todos a julgam mais provável como “caixa de banco e feminista” do que apenas “caixa de banco”. É impossível: <strong>cada detalhe somado só pode estreitar o conjunto, nunca alargá-lo</strong> — P(A e B) jamais supera P(A). A história mais rica nos convence exatamente porque é menos provável.","tip":"<strong>Como aplicar:</strong> entre o cenário detalhado e o simples, aposte no simples — ele sempre tem a chance maior.","wide":True},
      {"ic":"spiral","t":"O Extremo Volta Sozinho à Média","emph":"Volta Sozinho","b":"Depois de um extremo — um voo péssimo, uma prova brilhante — o resultado seguinte tende a se aproximar da média, por mero acaso. Mas a mente <strong>se recusa a aceitar o acaso e fabrica uma causa</strong>: “a bronca corrigiu o piloto”, “o elogio amoleceu o aluno”. Assim a punição parece funcionar e o elogio parece estragar — quando era só a estatística respirando.","tip":"<strong>Regra:</strong> antes de explicar uma melhora ou uma piora, pergunte “não seria apenas regressão à média?”."},
      {"ic":"mask","t":"Plausível Não é Provável","emph":"Plausível","b":"Uma cena rica em detalhes é fácil de imaginar e por isso parece mais provável — mas cada cláusula a mais a torna, na conta, menos provável. A <strong>coerência seduz e atropela a lógica</strong>: tomamos “consigo visualizar bem” por “tem grande chance de ser verdade”. O vívido vende; o vago acerta.","tip":"<strong>Cuidado:</strong> creditar a uma intervenção a melhora que foi, na verdade, só regressão à média.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["Cada detalhe plausível somado aumenta a credibilidade e diminui a probabilidade.","O extremo volta à média sozinho — resista à tentação de lhe inventar uma causa.","Desconfie da explicação causal sempre que o acaso bastar para explicar."]},

 {"slug":"ch08-ilusao-validade-intuicao","sub":"CAPÍTULO 8: A Ilusão de Validade e a Intuição de Especialistas",
  "intro":"A certeza que sentimos não mede o acerto do julgamento — mede o quanto a história nos parece coerente. São coisas diferentes, e nós as confundimos. Em terrenos irregulares, como a bolsa ou a política, a intuição do especialista vale tanto quanto o palpite, só que carregada de uma confiança que ela não merece.",
  "cards":[
      {"ic":"lens","t":"Sentir-se Certo Não é Estar Certo","emph":"Sentir-se Certo","b":"A confiança que você sente mede a coerência da sua história, jamais a precisão dela. É a ilusão de validade: a <strong>certeza subjetiva permanece intacta mesmo depois de os dados provarem que aquele julgamento não prevê nada</strong>. Analistas seguríssimos acertam a bolsa como acertaria o acaso — e seguem confiantes, porque a sensação não depende do resultado.","tip":"<strong>Como aplicar:</strong> em terreno imprevisível, trate confiança alta como alarme, não como garantia.","wide":True},
      {"ic":"key","t":"Quando a Intuição é Confiável","emph":"Intuição","b":"O palpite de especialista só merece crédito sob duas condições, e juntas: um <strong>ambiente regular o bastante para ter padrões</strong> e <strong>feedback rápido e claro para aprendê-los</strong>. O bombeiro que pressente o piso ceder e o enxadrista os têm; o previsor de mercado, não — ali a intuição é adivinhação vestida de experiência. A intuição válida é só reconhecimento de um padrão já visto mil vezes.","tip":"<strong>Regra:</strong> sem ambiente regular e bom feedback, não confie na intuição — nem na sua, nem na do expert."},
      {"ic":"scale","t":"A Fórmula Vence o Especialista","emph":"Fórmula","b":"Em ambiente ruidoso, uma <strong>fórmula simples e consistente bate o julgamento clínico do especialista</strong> na maioria dos casos. A causa é humana demais: a pessoa oscila, contradiz a si mesma de um dia para o outro e se deixa levar pela impressão geral. A regra é tosca, mas tem uma virtude que falta ao especialista — não muda de humor.","tip":"<strong>Cuidado:</strong> tomar a confiança de um especialista como prova de que a previsão dele vai se cumprir.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Confiança é a sensação de coerência da história, não a medida do acerto.","A intuição só é confiável em ambientes regulares e com bom feedback.","Em terreno ruidoso, a regra simples e estável vence o julgamento humano."]},

 {"slug":"ch09-excesso-confianca-pre-mortem","sub":"CAPÍTULO 9: Excesso de Confiança, Visão de Fora e o Pré-Mortem",
  "intro":"Subestimamos prazo, custo e risco com uma teimosia notável — e a culpa é da perspectiva. Planejamos olhando para dentro do projeto, encantados com os seus detalhes, em vez de olhar para fora, para a estatística dos projetos parecidos que já fracassaram. O excesso de confiança é, talvez, o mais caro de todos os vieses.",
  "cards":[
      {"ic":"lens","t":"Olhe de Fora, Não de Dentro","emph":"de Fora","b":"A falácia do planejamento nasce da visão de dentro: estimamos pelo melhor cenário deste projeto, ricos em detalhes animadores e cegos para os atrasos de praxe. A cura é a <strong>visão de fora — a taxa-base de empreitadas parecidas que já aconteceram</strong>. Elas estouraram prazo e orçamento; o seu, salvo prova em contrário, vai estourar também.","tip":"<strong>Como aplicar:</strong> antes de confiar na sua estimativa, pergunte “como terminaram os projetos parecidos com este?”.","wide":True},
      {"ic":"sword","t":"Convide o Fracasso para a Mesa","emph":"o Fracasso","b":"O pré-mortem inverte o roteiro: antes de bater o martelo, imagine que já se passou um ano e <strong>o projeto fracassou de forma estrondosa — e peça a cada um que escreva a história desse desastre</strong>. O exercício dá voz à dúvida que o entusiasmo coletivo calava e faz subir à tona os riscos que ninguém ousava dizer em voz alta.","tip":"<strong>Regra:</strong> imaginar o fracasso hoje sai barato; descobri-lo no post-mortem, depois de gasto o dinheiro, sai caríssimo."},
      {"ic":"mountain","t":"O Otimismo que Esquece o Rival","emph":"Esquece o Rival","b":"Superestimamos o nosso controle e a nossa competência, e <strong>esquecemos que os concorrentes estão fazendo exatamente a mesma conta otimista</strong>. O otimismo de grupo é contagioso e cega: numa sala animada, levantar a mão para duvidar soa como deslealdade. Por isso o atraso e o estouro de orçamento são a regra — não o azar.","tip":"<strong>Cuidado:</strong> engolir a própria dúvida só porque “a equipe está animada” e mais ninguém reclamou.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 9",
  "lessons":["Planejamos pelo melhor caso — e por isso estouramos prazo e custo quase sempre.","A visão de fora, a taxa-base de projetos parecidos, é o antídoto do otimismo.","Um pré-mortem barato hoje poupa um post-mortem caro amanhã."]},

 {"slug":"ch10-teoria-do-prospecto","sub":"CAPÍTULO 10: Teoria do Prospecto — Aversão à Perda e Ponto de Referência",
  "intro":"A economia clássica supõe que pesamos o resultado final, friamente. Não é o que fazemos. Avaliamos tudo como ganho ou perda em relação a um ponto de referência — e a balança é torta: perder dói cerca de duas vezes mais do que ganhar a mesma quantia agrada. Dessa única assimetria nasce metade das nossas decisões irracionais.",
  "cards":[
      {"ic":"scale","t":"Perder Dói o Dobro de Ganhar","emph":"o Dobro","b":"A curva da dor e a do prazer não são espelhos: <strong>perder R$ 100 machuca cerca de duas vezes mais do que ganhar R$ 100 agrada</strong>. Essa assimetria explica por que recusamos apostas que nos favorecem e por que seguramos ações que afundam — o medo de perder fala sempre mais alto que a vontade de ganhar, mesmo quando a conta diz o contrário.","tip":"<strong>Como aplicar:</strong> não recuse uma aposta a seu favor só porque a dor de perder grita mais que o ganho possível.","wide":True},
      {"ic":"pin","t":"Tudo se Mede a Partir de um Ponto","emph":"a Partir de um Ponto","b":"Não sentimos a riqueza em si — sentimos a <strong>mudança a partir de onde estamos agora</strong>, o ponto de referência. E com sensibilidade decrescente: de R$ 100 a R$ 200 vibramos; de R$ 1.100 a R$ 1.200, quase nada, embora a quantia seja idêntica. Mude o ponto de partida e o mesmíssimo fato vira festa ou luto.","tip":"<strong>Modelo mental:</strong> reposicione o ponto de referência e a mesma situação se transforma de alívio em derrota — ou o inverso."},
      {"ic":"key","t":"O que é Meu Vale Mais","emph":"é Meu","b":"Basta possuir algo para passar a cobrar por ele acima do preço de mercado — é o efeito posse, filho direto da aversão à perda: <strong>abrir mão dói como perder</strong>. Junte a isso o hábito de superpesar tanto o evento raríssimo quanto a certeza absoluta, e estão explicados de uma vez a loteria que compramos e o seguro caro que assinamos.","tip":"<strong>Cuidado:</strong> segurar um mau investimento só para não “realizar” a perda — e não ter de admiti-la a si mesmo.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 10",
  "lessons":["Avaliamos a mudança a partir de um ponto de referência, não a riqueza final.","A perda pesa cerca do dobro do ganho equivalente — e por isso nos paralisa.","Superpesamos a certeza e o evento raro, distorcendo o que pagamos em seguros e loterias."]},

 {"slug":"ch11-enquadramento-contabilidade-mental","sub":"CAPÍTULO 11: Enquadramento, Contabilidade Mental e Econs vs. Humanos",
  "intro":"O mesmo fato, descrito de duas formas, produz duas decisões opostas — porque o Sistema 1 reage à embalagem, não ao conteúdo. É a prova mais nua de que não somos os Econs frios da teoria econômica, e sim Humanos: previsivelmente irracionais, comandados pela palavra, pela conta mental e pela inércia.",
  "cards":[
      {"ic":"lens","t":"A Palavra Decide, Não o Fato","emph":"A Palavra Decide","b":"“Salva 200 de 600” e “deixa 400 morrerem” dizem exatamente a mesma coisa — e fazem as pessoas escolherem o oposto. “90% magro” vende; “10% de gordura” encalha. <strong>A forma de apresentar muda a escolha sem mexer num único fato</strong>, porque o Sistema 1 responde à roupa que veste a informação, jamais ao corpo por baixo dela.","tip":"<strong>Como aplicar:</strong> antes de fechar o que importa, reenquadre — “e se isto fosse descrito como perda, eu decidiria igual?”.","wide":True},
      {"ic":"layers","t":"As Contas Mentais Separadas","emph":"Contas Mentais","b":"Guardamos o dinheiro em “gavetas” mentais — salário, lazer, prêmio — como se R$ 100 valessem coisas diferentes conforme a etiqueta. Isso <strong>viola a fungibilidade do dinheiro</strong> e abre a porta a três erros: vender o que sobe cedo demais, segurar o que cai, e afundar no custo já gasto, insistindo num projeto ruim só porque ele custou caro.","tip":"<strong>Regra:</strong> decida pelo patrimônio inteiro e pelo objetivo final, nunca pela gaveta mental isolada."},
      {"ic":"book","t":"Somos Humanos, Não Econs","emph":"Humanos","b":"A economia imagina os Econs — agentes glaciais que sempre maximizam. As pessoas de carne e osso são <strong>Humanos: previsivelmente irracionais</strong>, levados por enquadramento, contas mentais e preguiça de recalcular. Daí o poder discreto dos bons defaults: como quase ninguém refaz a conta, a opção padrão escolhida por outro acaba decidindo por nós.","tip":"<strong>Cuidado:</strong> teimar num projeto perdido por causa do dinheiro já gasto — “depois de tudo o que investi…”.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 11",
  "lessons":["A forma de apresentar decide a escolha — reenquadre antes de bater o martelo.","Contas mentais e custo afundado nos levam a violar a própria lógica econômica.","Somos Humanos previsíveis: bons defaults e arquitetura de escolha mudam o resultado."]},

 {"slug":"ch12-os-dois-eus","sub":"CAPÍTULO 12: Os Dois Eus — Experiência vs. Memória",
  "intro":"Há dois 'eus' dentro de você, e eles não se entendem. O eu que experiencia vive cada momento enquanto ele dura; o eu que recorda guarda a história depois e julga o que valeu a pena. Decidimos sempre para agradar o segundo — e o segundo distorce, com método, aquilo que o primeiro de fato viveu.",
  "cards":[
      {"ic":"fork","t":"Quem Vive e Quem Lembra","emph":"Quem Lembra","b":"São dois “eus” dentro de você: o que experiencia vive cada minuto à medida que ele escorre; o que recorda <strong>fica com a história e é quem manda no futuro</strong>. O drama é que decidimos para agradar o eu que lembra — perseguimos a boa lembrança, e não a soma real de bem-estar que o eu que vive de fato somou.","tip":"<strong>Como aplicar:</strong> decida pensando no eu que vai lembrar, mas viva atento ao eu que está sentindo agora.","wide":True},
      {"ic":"clock","t":"O Pico e o Fim Escrevem Tudo","emph":"o Fim","b":"A memória de um episódio não é a média do que se passou: é a média entre o <strong>momento mais intenso e o momento final</strong> — e a duração quase não pesa, eis a negligência da duração. Um procedimento longo que termina suave fica como melhor lembrança que um curto e ruim no fim. O desfecho reescreve, para trás, a experiência inteira.","tip":"<strong>Regra:</strong> para deixar uma boa memória, capriche no pico e no final — quanto tempo durou mal entra na conta."},
      {"ic":"bulb","t":"Nada é Tão Importante Quanto Parece","emph":"Tão Importante","b":"“Nada na vida é tão importante quanto você pensa <strong>enquanto está pensando nisso</strong>.” É a ilusão do foco: ao fixar uma só coisa — o carro novo, a mudança de cidade — ela parece capaz de refazer a vida. Mas a atenção logo se dispersa, a novidade desbota, e o impacto real encolhe muito abaixo do que fora prometido.","tip":"<strong>Cuidado:</strong> escolher uma experiência pela “história que vou contar” em vez do bem-estar que ela de fato vai entregar.","warn":True},
    ],
  "lessons_title":"Lições-Chave do Capítulo 12",
  "lessons":["Decidimos pela memória, não pela vida vivida — e a memória nos mente.","Pico e final dominam a lembrança; a duração simplesmente desaparece.","A ilusão do foco inflama o peso de qualquer coisa em que você pare para pensar."]},
]
