# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Realismo Capitalista: Não Há Alternativa?' (Mark Fisher)."""

BOOK = {
  "title": "Realismo Capitalista",
  "author": "Mark Fisher",
  "header_light": "REALISMO",
  "header_bold": "CAPITALISTA",
  "subtitle": "VISÃO GERAL · NÃO HÁ ALTERNATIVA?",
  "intro": "É mais fácil imaginar o fim do mundo do que o fim do capitalismo. Repare na frase: não falta inteligência para criticar o sistema — falta imaginação para sair dele. O realismo capitalista é essa atmosfera invisível que faz qualquer alternativa parecer infantil antes de ser pensada. Mark Fisher não a combate com mais argumentos; ele aponta as três rachaduras por onde o Real escorre — a depressão epidêmica, a catástrofe ecológica, a burocracia que se multiplica — e mostra que o 'não há alternativa' nunca foi um fato. Foi uma decisão política que esqueceu ter sido decidida.",
  "description": "Mark Fisher diagnostica o realismo capitalista: a convicção pré-reflexiva de que não há mundo possível fora do capitalismo — vivida não como ideia, mas como clima. Precorporação (a rebeldia vendida de volta antes de nascer), os três Reais que furam a superfície, a privatização do estresse, a impotência reflexiva, o stalinismo de mercado da cultura da auditoria, a ideologia como sonho que reconcilia o incompatível, e a saída: reabrir a imaginação e provar que há alternativa.",
  "tags": ["Filosofia", "Crítica Social", "Política"],
  "progress": "9 Capítulos",
  "cover": "assets/realismo-capitalista-cover.png",
  "overview_cards": [
    {"ic":"gap","t":"O Realismo Capitalista","b":"Não é uma crença que se defende — é o ar da sala. A certeza pré-reflexiva de que <strong>não há alternativa</strong> ao capitalismo, sentida como fato da realidade e não como posição política. É <strong>atmosfera, não doutrina</strong>: quanto menos se percebe como ideologia, mais forte ela opera. Ninguém a sustenta porque ninguém a vê.","tip":"<strong>Teste:</strong> diante de cada 'necessidade econômica', pergunte — isto é lei da natureza, ou uma decisão política que se esqueceu de ter sido decidida?"},
    {"ic":"triangle","t":"Os Três Reais","b":"Três rachaduras por onde o Real escorre e desmente a superfície lisa do sistema: <strong>(1) a epidemia de sofrimento mental</strong> · <strong>(2) a catástrofe ecológica</strong> · <strong>(3) a burocracia que se multiplica</strong>. Cada uma é tratada como falha avulsa a remendar — nunca como o sintoma estrutural que de fato é.","tip":"<strong>Modelo mental:</strong> o Real não se argumenta, ele irrompe. A tarefa política é nomear a fratura — não repintar o reboco por cima da rachadura."},
    {"ic":"pivot","t":"A Saída — Supernanny Marxista","b":"O capitalismo tardio não governa pela proibição, mas pela ordem implícita de <strong>gozar sem parar</strong> — e o excesso adoece, não liberta. A proposta de Fisher não é restaurar a repressão, e sim reconstruir uma <strong>autoridade coletiva, racional e democrática</strong> que diga 'até aqui' onde o mercado só sabe atiçar o desejo.","tip":"<strong>Como aplicar:</strong> reabrir a imaginação é o golpe central contra o TINA. Não espere a revolução inteira — até o ato contra-hegemônico mais modesto racha o mito da inevitabilidade."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-fim-do-mundo",
    "sub": "CAPÍTULO 1: É Mais Fácil Imaginar o Fim do Mundo",
    "intro": "Não é que defendamos o capitalismo como o melhor dos sistemas — é que não conseguimos mais imaginar um diferente. O realismo capitalista é essa sensação difusa de que o capitalismo esgotou o campo do possível: não uma tese a respirar, mas o próprio ar que se respira. Um horizonte tão naturalizado que deixou de parecer um horizonte.",
    "cards": [
      {"ic":"gap","t":"TINA — Não Há Alternativa","emph":"Não Há Alternativa","b":"O slogan de Thatcher saiu da campanha e virou condição da própria realidade. O capitalismo deixou de ser uma escolha entre outras e passou a se confundir com o real — <strong>opera como pano de fundo, não como tese</strong>. Como toda boa ideologia, funciona melhor exatamente onde já ninguém a reconhece como ideologia.","tip":"<strong>Como aplicar:</strong> nomeá-lo como construção política, e não como destino, já é o primeiro golpe — porque o expõe à pergunta que ele finge não existir.","wide":True},
      {"ic":"eye","t":"A Esterilidade da Imaginação","emph":"Esterilidade","b":"Depois de 1989, a queda do bloco soviético levou junto o \"fora\" de onde a crítica costumava falar. Por isso o fim do mundo virou gênero popular — <em>Filhos da Esperança</em> — enquanto <strong>a imaginação do que viria depois do capitalismo simplesmente secou</strong>. A força do sistema não está em provar que é bom: está em fazer o resto parecer impossível.","tip":"<strong>Modelo mental:</strong> o realismo capitalista é o ar da sala, não um quadro na parede. Ninguém precisa defendê-lo, porque ninguém chega a vê-lo."},
      {"ic":"layers","t":"Subsunção Real da Cultura","emph":"Subsunção Real","b":"O capitalismo não se contenta com a economia: coloniza o inconsciente, o desejo, o sono e o que ainda ousamos sonhar acordados. Não sobra um lado de fora limpo de onde apontar o dedo. A própria cultura que deveria resistir <strong>já chega pré-capturada</strong>, embalada para venda.","tip":"<strong>Sinal de alerta:</strong> quando a rebeldia vem com etiqueta de preço e logo de patrocinador, o sistema já a digeriu — e a revende como atitude.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["O realismo capitalista é um clima, não um credo — combatê-lo começa por torná-lo visível como construção, não como destino.", "A esterilidade da imaginação política não é acaso nem preguiça: é o efeito principal do sistema, não um efeito colateral.", "A força do capitalismo não está em provar que é bom, e sim em fazer o pós-capitalismo parecer impensável."],
  },
  {
    "slug": "ch02-precorporacao",
    "sub": "CAPÍTULO 2: Precorporação e Anticapitalismo Gestual",
    "intro": "O anticapitalismo não assombra o capitalismo — ele faz parte do espetáculo. O sistema não espera a crítica chegar para absorvê-la: ele a fabrica de antemão e vende a própria rebeldia de volta, embalada. O resultado perverso é que o gesto de oposição costuma alimentar exatamente aquilo que jura combater.",
    "cards": [
      {"ic":"mask","t":"Precorporação","b":"A cultura capitalista formata desejos e revoltas <strong>antes que existam</strong> — a dissidência já nasce pré-empacotada. É mais fina que a velha cooptação, que abocanhava o movimento depois: aqui a máquina molda o protesto antes do primeiro grito. A camiseta do Che pendurada na vitrine, o 'capitalismo consciente'.","tip":"<strong>Como aplicar:</strong> diante do seu próprio gesto crítico, pergunte — isto está sendo vendido de volta para mim como identidade, estilo ou produto?","wide":True},
      {"ic":"bubble","t":"Interpassividade","b":"O filme protesta no seu lugar; você assiste à crítica e sai de lá <strong>quite com a consciência</strong>, livre para seguir consumindo. <em>WALL-E</em> escarnece da humanidade obesa e consumista, a plateia ri de si mesma — e compra os bonecos do filme na saída. <strong>Sentir-se crítico não é o mesmo que agir.</strong>","tip":"<strong>Modelo mental:</strong> a crítica pop ao capital funciona como válvula de pressão — libera o vapor da indignação justamente para que a caldeira não exploda."},
      {"ic":"triangle","t":"Anticapitalismo Gestual","emph":"Gestual","b":"A denúncia da \"corporação maligna\" circula dentro do capitalismo e o reabastece com a sensação reconfortante de que já estamos todos cientes do problema. <strong>Ela confirma que o vilão são algumas empresas más e isoladas — nunca a estrutura que as produz aos lotes.</strong>","tip":"<strong>Sinal de alerta:</strong> atacar a 'corporação maligna' é o anticapitalismo de que o capitalismo mais gosta — absolve a máquina e responsabiliza o operador.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["A oposição que o sistema permite é, em geral, a oposição que o sistema já digeriu.", "A precorporação é mais sutil que a cooptação: não absorve depois — formata antes de o protesto existir.", "Sentir-se crítico não é agir politicamente; a interpassividade troca uma coisa pela outra e cobra a diferença em imobilidade."],
  },
  {
    "slug": "ch03-os-tres-reais",
    "sub": "CAPÍTULO 3: Capitalismo e o Real",
    "intro": "A \"realidade\" que o capitalismo oferece como fato consumado depende de recalcar o Real — aquilo que ele não consegue simbolizar sem se desmentir. Três Reais furam essa superfície e voltam à tona por mais que se tente afundá-los: o adoecimento mental, o desastre ambiental e a burocracia. Diante deles, a tarefa política não é discutir — é nomear a fratura.",
    "cards": [
      {"ic":"triangle","t":"Os Três Reais","emph":"Três Reais","b":"<strong>(1) A epidemia de transtornos mentais</strong> · <strong>(2) A catástrofe ecológica</strong> · <strong>(3) A burocracia que prolifera</strong>. Cada uma é despachada pelo sistema como falha avulsa, a remediar caso a caso — jamais como o sintoma estrutural que de fato é. O Real não se deixa argumentar: ele irrompe.","tip":"<strong>Modelo mental:</strong> pense no Real como a rachadura sob o reboco. O sistema repinta a parede uma e outra vez, em vez de encarar a estrutura que está cedendo.","wide":True},
      {"ic":"person","t":"Privatização do Estresse","emph":"Privatização do Estresse","b":"O truque consiste em descarregar no indivíduo — em sua química cerebral, sua \"resiliência\", sua terapia, seu coaching — um sofrimento que tem causa social, e assim <strong>despolitizá-lo por inteiro</strong>. Onde o sistema sussurra \"é um problema seu\", há quase sempre um sintoma estrutural recalcado.","tip":"<strong>Como aplicar:</strong> repolitize a dor — troque \"o que há de errado comigo?\" por \"o que há de errado num sistema que adoece tanta gente ao mesmo tempo?\""},
      {"ic":"leaf","t":"Sustentabilidade Como Negação","emph":"Negação","b":"O capitalismo não consegue admitir que o problema é o próprio crescimento infinito num planeta finito — então rebaixa o desastre a <strong>nicho de mercado verde</strong>. A crise ecológica vira linha de produto, selo e campanha, tudo menos o que é: um chamado à mudança estrutural.","tip":"<strong>Sinal de alerta:</strong> quando a catástrofe ambiental é reduzida a 'escolha do consumidor', a responsabilidade escorrega da estrutura para o seu carrinho de compras.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["Onde o sistema diz \"é problema seu\", procure o sintoma estrutural que ele precisou recalcar.", "Repolitizar a saúde mental e o ambiente — devolvê-los à causa coletiva — é uma das jogadas centrais de Fisher.", "O Real não se argumenta, ele irrompe; cabe à política nomear a fratura, não repintar o reboco sobre ela."],
  },
  {
    "slug": "ch04-impotencia-reflexiva",
    "sub": "CAPÍTULO 4: Impotência Reflexiva e Hedonia Depressiva",
    "intro": "Os jovens sabem que as coisas vão mal — e sabem, com a mesma clareza, que nada parecem poder fazer. A lucidez, aqui, não desperta a ação: endurece em paralisia. Não é a depressão de quem não sente prazer, mas a de quem só sabe buscar prazer raso e ainda assim continua vazio. Saber tudo virou o álibi perfeito para não fazer nada.",
    "cards": [
      {"ic":"clock","t":"A Impotência Reflexiva","emph":"Impotência Reflexiva","b":"Não é ignorância — é o contrário. O sujeito conhece de cor a catástrofe ambiental e a hipocrisia das corporações, e segue em frente como se nada disso tocasse seu dia. <strong>A impotência reflexiva é entender toda a engrenagem da exploração e, exatamente por isso, encolher os ombros: 'sei como é, mas o que eu posso fazer?'</strong> — uma crença que se cumpre sozinha.","tip":"<strong>Modelo mental:</strong> saber não é poder quando o saber serve só para justificar a inércia. A lucidez solitária acorrenta; o que liberta é o coletivo."},
      {"ic":"steps","t":"A Hedonia Depressiva","emph":"Hedonia Depressiva","b":"O sujeito do realismo capitalista não foi proibido de gozar — foi condenado a gozar e nunca se saciar. Rolar o feed, caçar a próxima curtida, o próximo episódio, o próximo clique. <strong>É a incapacidade não de sentir prazer, mas de fazer outra coisa que não seja persegui-lo</strong> — e voltar sempre ao mesmo vazio.","tip":"<strong>Prática:</strong> repare quando a indignação online vira fim em si mesma. Mede-se o efeito político não pelos likes acumulados, mas pelo que de fato mudou fora da tela."},
      {"ic":"gap","t":"A Privatização da Culpa","emph":"Privatização da Culpa","b":"Falhas que são da estrutura foram, uma a uma, transferidas para os ombros do indivíduo. Não conseguiu a vaga? Faltou-lhe currículo e brilho. Adoeceu de ansiedade? Falta de resiliência. <strong>O sistema converte o desastre coletivo em fracasso pessoal — e cobra de cada um, em silêncio, uma conta que ele não fez</strong>.","tip":"<strong>Sinal de alerta:</strong> a cobrança mais eficaz de um sistema injusto é convencer você a assinar, como dívida sua, a desigualdade que ele produziu.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["Lucidez sem coletivo apodrece em cinismo e depressão — a saída para a impotência reflexiva é política, não terapêutica.", "O sujeito do realismo capitalista não é privado de prazer: é sentenciado a um prazer que nunca chega a saciar.", "Quando a falha estrutural vira culpa privada, suspeite: o deslocamento isenta o sistema e adoece o indivíduo."],
  },
  {
    "slug": "ch05-stalinismo-de-mercado",
    "sub": "CAPÍTULO 5–6: Pós-Fordismo e Stalinismo de Mercado",
    "intro": "A precariedade pós-fordista não é só uma estatística do mercado de trabalho: é a causa material da epidemia de adoecimento mental. E o neoliberalismo, que prometia enxugar a burocracia, fez o oposto — multiplicou-a, agora a serviço do mercado. O paradoxo central: nunca houve tanto papel, tanta meta e tanta auditoria, porque o que passou a importar não é o trabalho, e sim a representação do trabalho.",
    "cards": [
      {"ic":"clock","t":"\"Não Se Apegue a Nada\" — Pós-Fordismo","emph":"Pós-Fordismo","b":"O regime de emprego precário, multitarefa e em reconfiguração permanente é a <strong>causa material</strong> do adoecimento em massa — viver sem chão firme adoece. \"Flexibilidade\" e \"resiliência\" são apenas nomes elegantes para o ato de transferir ao indivíduo o custo de um sistema que se recusa a estabilizar.","tip":"<strong>Como aplicar:</strong> repolitize a saúde mental — troque \"o que há de errado comigo?\" por \"que tipo de sofrimento este regime de trabalho fabrica em série?\"","wide":True},
      {"ic":"wrench","t":"Stalinismo de Mercado","emph":"Stalinismo de Mercado","b":"O que conta não é produzir, é <strong>encenar a produção</strong>: relatórios, metas, PR, auditorias. Como no stalinismo valia mais a propaganda da safra do que a safra, aqui vale mais o painel de indicadores do que aquilo que ele finge medir. O neoliberalismo não dissolveu a burocracia soviética — privatizou-a.","tip":"<strong>Modelo mental:</strong> siga a energia da instituição. Onde ela se gasta para 'parecer que se trabalha' — branding interno, dossiês, reuniões sobre reuniões — está o sintoma."},
      {"ic":"mask","t":"Ontologia Empresarial","emph":"Ontologia Empresarial","b":"A pressuposição, já naturalizada, de que tudo — escola, hospital, arte — deve ser tocado como se fosse uma empresa. As métricas são encenadas para um <strong>grande Outro</strong> (Lacan): uma plateia imaginária em que ninguém de fato acredita, mas para a qual todos continuam produzindo número.","tip":"<strong>Sinal de alerta:</strong> mais métrica não é mais qualidade. Quando a medida vira o alvo, ela deixa de ser boa medida (lei de Goodhart) — o esforço migra da coisa para o seu símbolo.","warn":True},
    ],
    "lessons_title": "Lições-Chave dos Capítulos 5–6",
    "lessons": ["A precariedade não é apenas econômica: ela fabrica sofrimento psíquico em escala epidêmica.", "Sob o realismo capitalista, parecer produtivo vence ser produtivo — a métrica deixa de ser meio e vira fim.", "O neoliberalismo não enxuga a burocracia; ele a reorganiza em torno da auditoria, da meta e do PR."],
  },
  {
    "slug": "ch06-dreamwork-central-de-trocas",
    "sub": "CAPÍTULO 7–8: Trabalho de Sonho e a Estrutura Invisível",
    "intro": "O realismo capitalista trabalha como um sonho: reconcilia contradições escandalosas sem que o sonhador estranhe — porque no sonho 'X e não-X' convivem em paz. E quando algo desanda, a culpa nunca encontra o capitalismo no banco dos réus: ela é desviada para o indivíduo ou para uma burocracia sem rosto. O sistema não precisa ser coerente; precisa apenas que ninguém compare o discurso de hoje com o de ontem.",
    "cards": [
      {"ic":"spiral","t":"Trabalho de Sonho e Disavowal","emph":"Disavowal","b":"A ideologia capitalista <strong>concilia o inconciliável sem que ninguém acorde</strong>, como na lógica frouxa de um sonho. O disavowal é o cinismo funcional — \"eu sei muito bem, mas mesmo assim…\": a crença não mora na cabeça, mora nos atos. Por isso apontar a contradição não basta; ela não constrange quem nunca precisou ser coerente.","tip":"<strong>Exemplo histórico:</strong> 2008. Décadas pregando que 'o mercado se autorregula' e, na primeira crise séria, resgates bilionários pagos pelo Estado — sem que a doutrina sofresse um arranhão. Trabalho de sonho perfeito.","wide":True},
      {"ic":"clock","t":"Distúrbio de Memória","emph":"Distúrbio de Memória","b":"O sistema desliga a continuidade histórica para que você não consiga colar o discurso de agora ao de antes. Sem esse fio, a <strong>memória política se apaga</strong> e cada promessa quebrada vira novidade. Lembrar o que foi dito ontem deixa de ser trivial — e passa a ser um ato político.","tip":"<strong>Como aplicar:</strong> não confie no cinismo como blindagem. Dizer 'não acredito em nada disso' não protege da ideologia, porque ela age nos seus atos, não nas suas convicções."},
      {"ic":"gap","t":"Não Há Central de Trocas","emph":"Central de Trocas","b":"Quando algo dá errado, a culpa recai sobre o indivíduo ou sobre uma burocracia abstrata — porque o capitalismo não tem rosto, nem mesa, nem endereço onde se protocolar a reclamação. Sem responsável, é inimputável. <strong>Diante de cada narrativa, pergunte: a quem ela atribui a culpa — e a quem, calada, poupa?</strong>","tip":"<strong>Sinal de alerta:</strong> jogar o desastre ecológico nas costas do 'consumidor consciente' é o deslocamento exemplar — absolve a estrutura e fabrica culpa privada.","warn":True},
    ],
    "lessons_title": "Lições-Chave dos Capítulos 7–8",
    "lessons": ["A força do realismo capitalista não está em ser coerente, mas em absorver a própria incoerência sem pagar pedágio.", "Restaurar a memória histórica — lembrar o que foi prometido ontem — é, por si só, um ato político.", "Sempre que a culpa de um problema estrutural vira responsabilidade individual, desconfie: há um deslocamento em ação."],
  },
  {
    "slug": "ch07-supernanny-marxista",
    "sub": "CAPÍTULO 9: Supernanny Marxista — a Saída",
    "intro": "O capitalismo tardio não governa proibindo — governa mandando gozar, estimular o desejo sem trégua. Mas o excesso não liberta: adoece. A proposta de Fisher não é trazer de volta o velho pai repressor; é reconstruir uma autoridade coletiva e racional capaz de dizer 'até aqui' — e, com isso, reabrir o horizonte de alternativas que o 'não há alternativa' havia lacrado.",
    "cards": [
      {"ic":"scale","t":"A Supernanny Marxista","emph":"Supernanny Marxista","b":"A imagem-proposta: uma <strong>autoridade coletiva, racional e democrática</strong> que põe limite onde o mercado só sabe atiçar desejo. Como a Supernanny que entra no lar caótico — não pela bronca autoritária, mas por regras claras, justas e consistentes que devolvem o chão a quem se afoga na permissividade.","tip":"<strong>Como aplicar:</strong> aponte onde o 'deixa o desejo correr solto' do mercado já cobra um limite coletivo, decidido democraticamente — o racionamento racional de recursos diante do colapso ecológico, por exemplo.","wide":True},
      {"ic":"mountain","t":"Indulgência Não é Liberdade","emph":"Não é Liberdade","b":"O capitalismo tardio governa pela <strong>estimulação sem fim</strong>, não pela proibição — e a ausência de limites não produz sujeitos autônomos, produz consumidores ansiosos e dependentes. É o mercado no papel do pai ausente que tudo permite, justamente porque já desistiu de educar.","tip":"<strong>Modelo mental:</strong> a permissividade não é liberdade, é abandono. O limite coletivo é condição da liberdade real — não a sua negação."},
      {"ic":"spark","t":"Contra-Hegemonia — Reabrir o Horizonte","emph":"Reabrir o Horizonte","b":"A tarefa estratégica é <strong>tornar o impensável de novo pensável</strong>: mostrar que o 'não há alternativa' sempre foi uma escolha política disfarçada de fato consumado. A inevitabilidade é só aparência — e basta uma fissura para que ela comece a estalar.","tip":"<strong>Como aplicar:</strong> não espere a revolução inteira. Para Fisher, mesmo ações modestas e coordenadas já rancham o mito do TINA — e a primeira rachadura é a que importa."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": ["O capitalismo tardio governa pelo excesso permissivo — e o excesso adoece, não liberta.", "A saída é reconstruir o coletivo: uma autoridade racional e democrática capaz de impor limites onde o mercado só excita o desejo.", "Reabrir a imaginação — provar que 'há alternativa' — é o golpe central; e até os pequenos atos coordenados contam."],
  },
]
