# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Os Segredos da Mente Milionária' (T. Harv Eker)."""

BOOK = {
 "title": "Os Segredos da Mente Milionária",
 "author": "T. Harv Eker",
 "header_light": "MENTE",
 "header_bold": "MILIONÁRIA",
 "subtitle": "VISÃO GERAL · REPROGRAME SEU TERMOSTATO FINANCEIRO",
 "intro": "Dê a duas pessoas a mesma sorte e, em poucos anos, cada uma volta ao próprio saldo de sempre. Não é falta de dica nem de oportunidade: é o <strong>termostato financeiro</strong> — um nível interno gravado na infância para o qual a sua conta sempre retorna. T. Harv Eker é direto: o dinheiro é o último elo de uma corrente que começa na cabeça (Pensamento → Sentimento → Ação → Resultado). Mexer no saldo é ajustar a temperatura; o que muda a vida é trocar o termostato. Por isso o livro não ensina onde investir — reprograma <em>quem</em> investe, abrindo os 17 Arquivos de Riqueza onde ricos e pobres pensam ao contrário.",
 "description": "O método de T. Harv Eker para reprogramar a mente financeira antes da carteira. O modelo de dinheiro instalado na infância por três fontes — o que você ouviu, viu e viveu —, a cadeia P→S→A→R, os 4 passos da mudança, as declarações ditas em voz alta com o corpo, e os 17 Arquivos de Riqueza que separam o pensar de ricos e pobres: criar a própria vida, jogar para ganhar, pensar grande, focar em oportunidades, medir o patrimônio líquido, pôr o dinheiro a trabalhar, agir apesar do medo e crescer sempre.",
 "tags": ["Mentalidade Financeira", "Autodesenvolvimento", "Riqueza"],
 "progress": "9 Capítulos",
 "cover": "assets/segredos-da-mente-milionaria-cover.png",
 "overview_cards": [
   {"ic":"spiral","t":"O Termostato Financeiro","b":"Você não tem o saldo que merece — tem o saldo para o qual foi <strong>regulado na infância</strong>. Ganhe muito de repente e a mente trata o excesso como febre: gasta, perde, devolve, até a conta voltar ao ponto de sempre. <strong>Mude o termostato, não a temperatura</strong> — é a única correção que dura.","tip":"<strong>Modelo mental:</strong> antes de caçar o investimento mágico, pergunte qual número interno a sua cabeça está defendendo."},
   {"ic":"steps","t":"Os 17 Arquivos de Riqueza","b":"Ricos e pobres não divergem na conta — divergem na cabeça, e em cada eixo apostam ao contrário. O rico <strong>cria</strong> a própria vida, joga para ganhar, pensa grande, vê oportunidade onde o outro vê risco, admira quem venceu e mede patrimônio, não salário. <strong>O pobre faz o inverso em todos eles — e chama isso de azar.</strong>","tip":"<strong>Como aplicar:</strong> cada arquivo é uma crença velha a substituir; troque uma por vez, na declaração e na ação.","wide":True},
   {"ic":"layers","t":"A Cadeia P→S→A→R","b":"O dinheiro é o <strong>último</strong> elo, nunca o primeiro: Pensamento gera Sentimento, que gera Ação, que gera Resultado. Brigar com o extrato é socar a sombra. A alavanca está lá no começo — na crença — e quem só mexe no fim trabalha o dobro para ficar no mesmo lugar.","tip":"<strong>Como aplicar:</strong> diante do resultado ruim, suba a corrente ao contrário — que ação? que sentimento? que crença? — e reescreva a crença."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-modelo-de-dinheiro","sub":"CAPÍTULO 1: O Modelo de Dinheiro",
  "intro":"Antes de você saber somar, alguém já tinha ajustado o seu termostato financeiro. É o nível interno para onde a sua conta sempre volta — não importa quanto entre ou saia. Por isso a regra que abre o livro: mude o termostato, e a temperatura segue; mexa só na temperatura, e o frio retorna.",
  "cards":[
      {"ic":"spiral","t":"O Termostato Financeiro","emph":"Termostato","b":"O termostato não pergunta o que você quer ter; ele defende o que está acostumado a ter. Por isso o ganhador da loteria volta à pobreza e o falido refaz a fortuna: cada um corre de volta ao número de sempre. <strong>Tática esperta numa mente regulada para a escassez é casaco no calor — você sua e tira.</strong>","tip":"<strong>Modelo mental:</strong> pare de procurar a dica milagrosa; o dinheiro não fica em mãos ajustadas para soltá-lo."},
      {"ic":"layers","t":"As Três Fontes da Programação","emph":"Três Fontes","b":"O seu modelo de dinheiro foi gravado em três faixas, antes de você ter como recusar. <strong>O que você ouviu</strong> ('rico é ganancioso', 'dinheiro não dá em árvore'), <strong>o que você viu</strong> os pais fazerem com cada nota, e <strong>o que você viveu</strong> — a briga, o aperto, a vergonha colada ao tema. Isso não é o seu destino; é só uma gravação antiga que ainda toca sozinha.","tip":"<strong>Como aplicar:</strong> nomeie a frase sobre dinheiro que mais ouviu em casa — e decida se ela é sua ou apenas herdada."},
      {"ic":"leaf","t":"A Raiz e o Fruto","emph":"Raiz e Fruto","b":"O saldo no vermelho é fruto; e fruto podre não se conserta lustrando a casca. Ele só denuncia o que está acontecendo lá embaixo, na raiz invisível das crenças. <strong>Quem passa o dia inteiro chorando pelos frutos nunca chega a cavar onde o problema realmente mora.</strong> O visível é o efeito; o invisível é a causa.","tip":"<strong>Cuidado:</strong> apertar gastos sem tocar na crença é remendar o casco furado por dentro — a água volta a entrar.","warn":True},
    ],
  "lessons_title":"Onde o Resultado Realmente Nasce",
  "lessons":["O seu resultado financeiro obedece a um modelo interno gravado na infância, não à sorte do dia.","Esse modelo veio de três fontes: o que você ouviu, o que viu e o que viveu.","Para mudar o fruto, mexa na raiz — podar o saldo não reprograma a crença."]},

 {"slug":"ch02-processo-pensamento-resultado","sub":"CAPÍTULO 2: A Cadeia P→S→A→R",
  "intro":"O dinheiro na conta não cai do céu nem do mercado: é o ponto final de uma frase que você começou na própria cabeça. Pensamento puxa Sentimento, que puxa Ação, que puxa Resultado. Mexa no fim e cansa; mexa no começo — a crença — e a frase inteira se reescreve.",
  "cards":[
      {"ic":"steps","t":"A Corrente Inteira","emph":"Corrente","b":"Um pensamento acende uma emoção; a emoção move (ou trava) a ação; a ação imprime o resultado. <strong>Trocar de emprego ou de negócio sem trocar a crença é só carregar o mesmo termostato para uma sala nova</strong> — em pouco tempo o saldo de sempre te encontra de novo, no endereço novo.","tip":"<strong>Como aplicar:</strong> não comece pela ação. Suba a corrente até a crença que a comanda, e mude o elo de cima."},
      {"ic":"lens","t":"O Resultado é um Espelho","emph":"Espelho","b":"O extrato não te julga nem te odeia: ele apenas mostra. É um espelho honesto do que o seu modelo de dinheiro vem produzindo, sem cerimônia e sem desconto. <strong>Culpar a economia, o chefe ou o azar é segurar uma muleta enquanto o teto cai</strong> — alivia hoje e adia a única correção que importa.","tip":"<strong>Modelo mental:</strong> pare de discutir com o número e leia-o como feedback. O saldo não é a sua sentença; é a sua radiografia."},
      {"ic":"bulb","t":"A Montante, Não a Jusante","emph":"A Montante","b":"Você não represa um rio brigando com a foz; vai-se à nascente. Trabalhar mais horas com a mesma crença é remar contra a correnteza: cansa, e o teto não sobe. <strong>O esforço só rende quando a antena interna está sintonizada para receber — senão, todo o suor escorre pelo mesmo ralo de sempre.</strong>","tip":"<strong>Regra:</strong> não force o faturamento por fora se, por dentro, você ainda acha que aquele dinheiro 'não é para você'.","warn":True},
    ],
  "lessons_title":"O Dinheiro é o Último Elo",
  "lessons":["Resultado é o fim da corrente P→S→A→R: para mudar o fim, mude o começo.","A alavanca está a montante (na crença), nunca a jusante (no saldo).","Leia o seu resultado como feedback do modelo interno — não como um destino que te foi imposto."]},

 {"slug":"ch03-condicionamento-e-declaracoes","sub":"CAPÍTULO 3: Condicionamento e Declarações",
  "intro":"O modelo de dinheiro foi gravado — logo, pode ser regravado. A mudança não é mágica: tem quatro passos (consciência, compreensão, dissociação, recondicionamento) e uma ferramenta de fogo, a declaração — frase dita em voz alta, com a mão no peito e o corpo junto, porque o pensamento mudo grava pouco.",
  "cards":[
      {"ic":"steps","t":"Os 4 Passos da Mudança","emph":"4 Passos","b":"Reprogramar não é se forçar a 'pensar positivo'. Primeiro a <strong>consciência</strong>: enxergar a crença que rege você. Depois a <strong>compreensão</strong>: ver de onde ela veio, que ela é deles, não sua. Em seguida a <strong>dissociação</strong>: notar que aquilo é apenas um aprendizado antigo, não a verdade. Só então o <strong>recondicionamento</strong> assenta o trilho novo.","tip":"<strong>Como aplicar:</strong> não corra instalar mentalidade rica por cima da velha. Limpe a faixa antiga primeiro — depois grave a nova."},
      {"ic":"spark","t":"As Declarações de Poder","emph":"Declarações","b":"Pensar positivo de boca fechada quase não pega; a crença velha grita mais alto. Por isso a declaração se diz <strong>em voz alta, com emoção e a mão no coração</strong> — não é teatro, é gravar com o corpo o que a mente sozinha não fixa. Voz, gesto e sentimento juntos furam o ceticismo e cravam a faixa nova mais fundo que qualquer afirmação silenciosa.","tip":"<strong>Modelo mental:</strong> pare de sussurrar metas tímidas no espelho; declare-as firme, em voz alta, todos os dias."},
      {"ic":"key","t":"Você Não é Seus Pensamentos","emph":"Dissociação","b":"À noite, a mente entra em pânico e jura que o dinheiro vai acabar — e você quase obedece. Mas essa voz não é você: é uma gravação antiga tocando no automático. <strong>Você é quem ouve o pensamento, não o pensamento.</strong> E quem observa pode discordar, baixar o volume e escolher outra faixa.","tip":"<strong>Regra:</strong> ouviu a voz do medo recitar o velho roteiro? Responda 'obrigado por compartilhar' — e aja na direção oposta."},
    ],
  "lessons_title":"Como se Regrava um Modelo",
  "lessons":["A mudança tem método: Consciência → Compreensão → Dissociação → Recondicionamento.","Você não é seus pensamentos — pode observá-los de fora e escolher outros.","Declarações ditas em voz alta, com gesto e emoção, instalam crenças melhor que afirmações mudas."]},

 {"slug":"ch04-arquivos-protagonismo","sub":"CAPÍTULO 4: Arquivos — Protagonismo e Compromisso",
  "intro":"Os 17 arquivos abrem com os três que sustentam todos os outros: assumir 100% da própria vida, jogar para ganhar (não só para não perder) e se comprometer de verdade a enriquecer. Sem esta base, qualquer técnica desaba.",
  "cards":[
      {"ic":"target","t":"Arquivo 1 — Criar vs. Ser Vítima","emph":"Vítima","b":"O rico cria a própria vida; a vítima espera que a vida lhe aconteça e depois reclama do roteiro. E a vítima se denuncia por três sinais: <strong>culpar</strong> (o governo, o chefe, os pais), <strong>justificar</strong> ('dinheiro não é tão importante') e <strong>reclamar</strong> — que é pedir mais do que se odeia. <strong>Ninguém no banco do carona dirige a fortuna.</strong>","tip":"<strong>Como aplicar:</strong> flagre-se culpando, justificando ou reclamando — e troque a frase por 'o que eu faço com isto a partir de agora?'."},
      {"ic":"spark","t":"Arquivo 2 — Jogar para Ganhar","emph":"Ganhar","b":"Entrar no jogo do dinheiro só para não perder é assinar de véspera o atestado de mediocridade: você se contenta com o suficiente para sobreviver. O rico joga para <strong>ganhar</strong> — sua meta não é pagar as contas, é a abundância. <strong>Quem mira o teto baixo acerta o teto baixo; quem mira a fortuna ao menos sai do conforto que a impede.</strong>","tip":"<strong>Modelo mental:</strong> 'só quero ter o suficiente' é o lema garantido da escassez. Defina o objetivo grande — e mire nele."},
      {"ic":"mountain","t":"Arquivo 3 — Compromisso Total","emph":"Compromisso","b":"Querer ficar rico não basta — quase todo mundo quer. O que separa é o <strong>compromisso</strong>: a disposição de fazer o que for preciso (ético), por quanto tempo for preciso. Desejo é suspiro na cama; compromisso é assinatura embaixo. <strong>O universo não responde a um 'quem sabe um dia'; responde a um 'estou dentro, custe o que custar'.</strong>","tip":"<strong>Cuidado:</strong> se para o seu bolso você usa 'seja o que Deus quiser', você ainda não se comprometeu — só torceu.","warn":True},
    ],
  "lessons_title":"A Base de Todos os Arquivos",
  "lessons":["Ricos criam a vida; pobres acham que ela lhes acontece — assuma 100% da responsabilidade.","Largue as três marcas da vítima: culpar, justificar e reclamar.","Jogue para ganhar (abundância) e comprometa-se de verdade — querer não é o mesmo que decidir."]},

 {"slug":"ch05-arquivos-visao-oportunidade","sub":"CAPÍTULO 5: Arquivos — Visão Grande e Oportunidade",
  "intro":"Estes três arquivos definem o tamanho do que você enxerga — e, logo, do que constrói. O rico pensa grande, caça oportunidades onde o outro só vê risco e admira quem venceu em vez de roer de inveja. Atenção e ambição apontadas para cima.",
  "cards":[
      {"ic":"triangle","t":"Arquivo 4 — Pensar Grande","emph":"Pensar Grande","b":"A sua renda é a fatura exata do valor que você entrega e de quantas pessoas serve. Servir cafezinho a um de cada vez tem teto; resolver a dor de milhões não tem. <strong>Não é ganância pensar grande — é generosidade: o mundo paga na medida do problema que você se dispõe a carregar para os outros.</strong>","tip":"<strong>Como aplicar:</strong> troque a pergunta 'como ganho mais?' por 'como sirvo mais gente e resolvo dores maiores?'. A renda segue a resposta."},
      {"ic":"lens","t":"Arquivo 5 — Foco em Oportunidades","emph":"Oportunidades","b":"Diante da mesma cena, dois olhares: o da escassez varre tudo atrás do risco que justifica não agir; o da riqueza varre atrás da chance que vale tentar. <strong>O rico entra na oportunidade preparado, não 'pronto' — e corrige a rota no caminho, porque sabe que esperar a certeza é deixar o trem partir.</strong>","tip":"<strong>Modelo mental:</strong> quem espera todos os sinais ficarem verdes nunca sai da esquina. Aja com a informação que tem e ajuste andando."},
      {"ic":"bulb","t":"Arquivo 6 — Admirar vs. Ressentir","emph":"Ressentir","b":"Xingar os ricos é o esporte favorito de quem nunca vai ser um. E faz todo sentido para a mente: <strong>você não consegue se tornar aquilo que despreza.</strong> Cada 'rico é ganancioso' é um cadeado que você mesmo fecha — a inveja trava por dentro a porta que a ambição tenta abrir.","tip":"<strong>Sinal de alerta:</strong> flagrou-se com nojo de quem venceu? Troque por admiração e curiosidade — 'o que ele fez que eu posso aprender?'.","warn":True},
    ],
  "lessons_title":"O Tamanho do que Você Enxerga",
  "lessons":["Pense grande: sua renda acompanha o valor que entrega e o número de pessoas que serve.","Foque em oportunidades e aja apesar do risco — não congele diante dos obstáculos.","Admire ricos e bem-sucedidos; ninguém se torna aquilo que despreza."]},

 {"slug":"ch06-arquivos-relacoes-valor","sub":"CAPÍTULO 6: Arquivos — Companhias, Valor e Abundância",
  "intro":"O faturamento se destrava na soma de três coisas: com quem você anda, a coragem de promover o que entrega e a recusa de pensar em 'ou isto, ou aquilo'. Companhia, voz e mentalidade de abundância — combinadas.",
  "cards":[
      {"ic":"person","t":"Arquivo 7 — Círculo de Convívio","emph":"Convívio","b":"Você tende à média das cinco pessoas com quem mais convive — em renda, em hábito, em teto mental. Sentar todo dia na roda do lamento contamina seus projetos com o pessimismo dos outros. <strong>O rico se aproxima de quem já chegou onde ele quer ir, porque o nível do grupo puxa o seu para cima.</strong>","tip":"<strong>Como aplicar:</strong> olhe seu círculo mais próximo. Aumente o tempo com quem te inspira e reduza o tempo com quem só reclama."},
      {"ic":"spark","t":"Arquivo 8 — Promover o Próprio Valor","emph":"Promover","b":"Esconder o que você faz por 'modéstia' não é virtude: é deixar quem precisa de você sem encontrar você. <strong>Se você acredita de verdade no valor do que entrega, divulgá-lo deixa de ser egoísmo e vira serviço.</strong> O gênio anônimo morre pobre não por falta de talento, mas por recusa de aparecer.","tip":"<strong>Modelo mental:</strong> 'não gosto de me vender' costuma ser medo de rejeição vestido de moral. Ofereça com orgulho o que ajuda os outros."},
      {"ic":"scale","t":"Arquivo 11 — Pensar 'Tanto/Ambos'","emph":"Ambos","b":"A mente pobre adora a escolha falsa: dinheiro ou família, sucesso ou saúde, lucro ou ética. A mente rica recusa a tesoura e pergunta 'como ter os dois?'. <strong>Quase toda renúncia que parece nobre é só falta de criatividade disfarçada de virtude.</strong> Abundância começa quando você para de cortar a vida ao meio.","tip":"<strong>Prática:</strong> sempre que se pegar diante de um 'ou… ou…', reescreva como 'tanto… quanto…' e procure o caminho que junta os dois."},
    ],
  "lessons_title":"O Que Destrava o Faturamento",
  "lessons":["Você é a média do seu convívio — escolha gente positiva e bem-sucedida.","Promover o próprio valor é dever de quem acredita no que entrega; vender não é palavrão.","Pense 'tanto/ambos' — recuse a falsa escolha e busque as duas coisas."]},

 {"slug":"ch07-arquivos-autoestima-receber","sub":"CAPÍTULO 7: Arquivos — Autoestima, Receber e Resultado",
  "intro":"A riqueza pede uma autoestima do tamanho dela: ser maior que os problemas, saber receber sem culpa e preferir ganhar por resultado, não por hora. Três arquivos sobre o quanto você se permite valer.",
  "cards":[
      {"ic":"mountain","t":"Arquivo 9 — Maior que os Problemas","emph":"Maior","b":"O problema não tem tamanho fixo — o tamanho é o seu, comparado ao dele. Para um gigante, qualquer obstáculo vira degrau; para um anão, vira muro. <strong>A solução não é pedir uma vida com problemas menores, é crescer até que os atuais fiquem pequenos.</strong> Riqueza grande é simplesmente um problema grande que alguém aprendeu a carregar.","tip":"<strong>Regra:</strong> diante de um problema, não chore por ele. Pergunte 'que pessoa eu preciso me tornar para isto virar fácil?'."},
      {"ic":"key","t":"Arquivo 10 — Ótimo Recebedor","emph":"Receber","b":"Quem aprendeu que recusar elogio é humildade também aprendeu, sem perceber, a recusar dinheiro. <strong>Bloquear o que entra — um 'imagina, não precisava' — fecha o cano por onde a abundância também passaria.</strong> Receber bem não é ganância; é deixar o fluxo correr nos dois sentidos.","tip":"<strong>Como aplicar:</strong> da próxima vez que te elogiarem ou te oferecerem algo, só sorria e diga 'obrigado'. Treine receber como treina dar."},
      {"ic":"spark","t":"Arquivo 12 — Pago por Resultado","emph":"Resultado","b":"O salário por hora tem uma promessa boa e um teto cruel: você troca tempo por dinheiro, e tempo é a única coisa que não dá para fabricar. <strong>O rico prefere ser pago pelo valor que cria, não pelo relógio</strong> — porque resultado escala e hora, não. A segurança do salário é, muitas vezes, o nome bonito da gaiola.","tip":"<strong>Cuidado:</strong> a 'estabilidade' de ganhar por tempo é também o limite do quanto você pode ganhar. Busque parte da renda atrelada a resultado.","warn":True},
    ],
  "lessons_title":"A Autoestima do Tamanho da Riqueza",
  "lessons":["Torne-se maior que os problemas em vez de pedir problemas menores.","Aprenda a receber bem — elogios, presentes, dinheiro: isso destrava o fluxo.","Prefira ser pago por resultado e valor, não por tempo — o relógio tem teto."]},

 {"slug":"ch08-arquivos-gestao-patrimonio","sub":"CAPÍTULO 8: Arquivos — Patrimônio e Gestão",
  "intro":"Riqueza não se mede pelo quanto entra, e sim pelo quanto fica e cresce. Três arquivos sobre o que de fato conta: o patrimônio líquido, o hábito de gerir cada entrada em frascos e o dinheiro que trabalha enquanto você dorme.",
  "cards":[
      {"ic":"scale","t":"Arquivo 13 — Patrimônio Líquido","emph":"Patrimônio","b":"Salário alto impressiona no bar; patrimônio líquido é o que sobra quando ninguém está olhando. <strong>A régua verdadeira da riqueza não é o quanto você ganha, é o quanto você acumula — renda mais poupança mais investimento, menos o que escorre pelo ralo.</strong> Muita gente de salário gordo é pobre disfarçada de rica.","tip":"<strong>Como aplicar:</strong> pare de só olhar a água que entra na pia. Acompanhe a que fica — calcule e acompanhe o seu patrimônio líquido."},
      {"ic":"cards","t":"Arquivo 14 — Sistema dos Frascos","emph":"Frascos","b":"Quem não administra cem reais não vai administrar cem mil — só vai perder mais rápido. O hábito vem antes da quantia: divida cada entrada em potes com destino certo, mesmo que pequenos. <strong>Um deles, a conta da Liberdade Financeira, é sagrado: entra e nunca sai, só gera renda.</strong> A disciplina nos centavos é o músculo que aguenta os milhões.","tip":"<strong>Modelo mental:</strong> não espere ficar rico para se organizar; organize-se com o que tem hoje — é o treino que sustenta o amanhã."},
      {"ic":"leaf","t":"Arquivo 15 — Dinheiro Trabalhando","emph":"Dinheiro a Trabalhar","b":"Trocar a sua vida inteira por dinheiro tem fim — o seu. Por isso o rico contrata um trabalhador que nunca cansa nem dorme: o próprio dinheiro. <strong>A liberdade chega no dia em que a renda dos seus investimentos paga as suas contas sem você precisar levantar.</strong> Você trabalha pelo dinheiro até que o dinheiro passe a trabalhar por você.","tip":"<strong>Regra:</strong> não se trata de parar de trabalhar. Trata-se de pôr cada real para gerar mais reais — até a renda passiva sustentar você."},
    ],
  "lessons_title":"A Riqueza se Mede pela Gestão",
  "lessons":["A medida da riqueza é o patrimônio líquido, não a renda — acompanhe esse número.","Gerencie por percentuais (sistema dos frascos): o hábito vale mais que a quantia.","Ponha o dinheiro a trabalhar (renda passiva) em vez de só trabalhar pelo dinheiro."]},

 {"slug":"ch09-arquivos-coragem-crescimento","sub":"CAPÍTULO 9: Arquivos — Coragem e Crescimento",
  "intro":"Os 17 arquivos fecham com a postura que sustenta todas as outras: agir apesar do medo e nunca parar de aprender e crescer. Sem coragem e desenvolvimento contínuos, nenhum dos arquivos anteriores sai do papel.",
  "cards":[
      {"ic":"sword","t":"Arquivo 16 — Agir Apesar do Medo","emph":"Agir","b":"Quem espera o medo passar para agir morre esperando — o medo não vai embora, e o conforto também é arriscado, só que com risco invisível. <strong>Coragem não é ausência de medo; é avançar com ele a bordo.</strong> O rico sente o mesmo frio na barriga que o pobre — e dá o passo mesmo assim, enquanto o outro recua e chama isso de prudência.","tip":"<strong>Como aplicar:</strong> não trate o frio na barriga como sinal de pare. Trate-o como largada — e aja antes que a desculpa se arme."},
      {"ic":"bulb","t":"Arquivo 17 — Aprender e Crescer Sempre","emph":"Crescer","b":"O objetivo final não é ter dinheiro — é tornar-se a pessoa capaz de criar e manter dinheiro. <strong>Por isso a verdadeira riqueza é a que você carrega por dentro: se perder tudo amanhã, quem aprendeu a construir reconstrói.</strong> Quem só herdou ou teve sorte derrete a fortuna, porque não virou ainda quem a sustenta.","tip":"<strong>Modelo mental:</strong> invista primeiro em você. O patrimônio externo balança; o que você se tornou não some no próximo vendaval."},
      {"ic":"mountain","t":"Expanda a Zona de Conforto","emph":"Zona de Conforto","b":"A zona de conforto é confortável e por isso mesmo é uma prisão de paredes macias. <strong>A sua riqueza de amanhã mora exatamente do lado de fora dela — no terreno do que hoje te dá medo de tentar.</strong> Cada vez que você faz o que incomoda, a zona cresce; e a zona de conforto, esticada, vira a nova zona de riqueza.","tip":"<strong>Sinal de alerta:</strong> se está tudo confortável, você parou de crescer. Procure de propósito o desconforto que expande os seus limites.","warn":True},
    ],
  "lessons_title":"A Postura que Sustenta Tudo",
  "lessons":["Coragem é agir com o medo presente — não espere ele sumir nem você 'estar pronto'.","Sair da zona de conforto é o preço da zona de riqueza; expanda-a agindo.","Comprometa-se a aprender e crescer sempre — o objetivo é tornar-se, não apenas ter."]},
]
