# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Quando Digo Não, Me Sinto Culpado' (Manuel J. Smith).
Termos canônicos: Disco Riscado, Banco de Névoa, Asserção Negativa,
Interrogação Negativa, Informação Gratuita, Autorrevelação, Acordo Viável."""

BOOK = {
  "title": "Quando Digo Não, Me Sinto Culpado",
  "author": "Manuel J. Smith",
  "header_light": "QUANDO DIGO NÃO,",
  "header_bold": "ME SINTO CULPADO",
  "subtitle": "VISÃO GERAL · A ASSERTIVIDADE COMO HABILIDADE VERBAL",
  "intro": "Smith mostra que a não assertividade é aprendida — via ansiedade, ignorância e culpa — e por isso pode ser desaprendida. A partir de um direito primário (você é o seu próprio juiz), ensina um conjunto de técnicas verbais para enfrentar a manipulação com calma e preservar o autorrespeito.",
  "description": "O manual clássico de assertividade. Smith ensina um conjunto de habilidades verbais — disco riscado, banco de névoa, interrogação negativa — para lidar com a manipulação como seu próprio juiz, preservando o autorrespeito.",
  "tags": ["Assertividade", "Comunicação", "Psicologia"],
  "progress": "11 Capítulos",
  "cover": "assets/smith-assertividade-capa.png",
  "overview_cards": [
    {"ic":"target","t":"Você é o Seu Próprio Juiz","b":"Toda a assertividade nasce de um único direito primário: você é o juiz supremo do seu próprio comportamento, pensamentos e emoções. A manipulação funciona ao fazer você <strong>entregar essa autoridade de juiz</strong> a regras, “deverias” e estruturas que o outro controla — recuperá-la é o passo de partida.","tip":"<strong>Modelo mental:</strong> quando ouvir “você deveria”, traduza para “eu preferiria que você…” — um mero desejo, que você aceita ou recusa.","wide":True},
    {"ic":"sword","t":"As 3 Alavancas: Ansiedade, Ignorância, Culpa","b":"A não assertividade é treinada na infância por três alavancas emocionais: ansiedade (“se não fizer X, algo ruim acontece”), ignorância (“deixe a autoridade decidir”) e culpa (“se fizer X, você é mau”). Uma onda súbita de qualquer uma delas <strong>é a alavanca sendo puxada</strong>, não informação sobre a realidade.","tip":"<strong>Sinal de alerta:</strong> culpa, ansiedade ou autodúvida repentinas num conflito denunciam manipulação em curso."},
    {"ic":"wrench","t":"O Kit de Técnicas Verbais","b":"O livro entrega um repertório de ferramentas calmas e persistentes: Disco Riscado (repetir o desejo), Banco de Névoa (absorver a crítica), Asserção e Interrogação Negativas, Informação Gratuita e Autorrevelação. São <strong>habilidades amorais</strong> — como dirigir um carro, servem ao bem ou ao mal, e você responde pelo uso.","tip":"<strong>Como aplicar:</strong> escolha a técnica pela situação (conflito, crítica, conversa) e treine-a até virar reflexo calmo."},
    {"ic":"scale","t":"O Placar é o Autorrespeito","b":"O ganho da assertividade é interno: o autorrespeito, preservado mesmo quando você não alcança o objetivo material. Conseguir o que quer é um bônus frequente — <strong>não a medida do sucesso</strong>. Tentar nunca desagradar ninguém é o que garante a manipulação.","tip":"<strong>Regra:</strong> negocie à vontade os objetivos materiais; nunca o autorrespeito."},
  ],
}

CHAPTERS = [
 {
  "slug": "ch01-sobrevivencia",
  "sub": "CAPÍTULO I: Sobrevivência e as Raízes da Não Assertividade",
  "intro": "O conflito entre pessoas é inevitável. Nossas respostas herdadas são luta ou fuga — mas o ser humano tem uma terceira, superior: a assertividade verbal. A maioria de nós é não assertiva porque, na infância, foi treinada a obedecer por ansiedade, ignorância e culpa.",
  "cards": [
   {"ic":"fork","t":"Luta, Fuga ou Palavra","emph":"Palavra","b":"As três respostas ao conflito. Luta (agressão) e fuga (evitação) são reflexos primitivos de sobrevivência; a solução verbal é a alternativa humana e eficaz. Troque o reflexo de atacar ou se retirar por um <strong>enfrentamento calmo e persistente</strong>.","tip":"<strong>Modelo mental:</strong> luta e fuga são o réptil que sobrou; a assertividade é o córtex fazendo o que só o humano consegue."},
   {"ic":"sword","t":"As 3 Alavancas Emocionais","emph":"3 Alavancas","b":"Como a criança — e depois o adulto — fica manipulável: ansiedade (“se não fizer X, algo ruim acontece”), ignorância (“deixe a autoridade decidir”) e culpa (“se fizer X, você é mau”). O <strong>“me sinto culpado” do título</strong> é esta última, a alavanca mais usada de todas.","tip":"<strong>Sinal de alerta:</strong> uma onda súbita de culpa, ansiedade ou autodúvida num conflito é uma alavanca sendo puxada — não informação sobre a realidade.","warn":True},
   {"ic":"mask","t":"O que é Manipulação","emph":"Manipulação","b":"Qualquer tentativa indireta de controlar seu comportamento mexendo nas suas emoções, em vez de declarar um desejo às claras. Os pais podem impor limites sem gerar ansiedade, ignorância ou culpa — mas <strong>a maioria não o faz</strong>, criando adultos passivos e manipuláveis.","tip":"<strong>Como aplicar:</strong> a não assertividade é aprendida; logo, pode ser desaprendida."},
   {"ic":"scale","t":"O Placar é o Autorrespeito","emph":"Autorrespeito","b":"O ganho da assertividade é interno: o autorrespeito, preservado mesmo quando você não alcança o objetivo material. <strong>Conseguir o que quer é um bônus frequente, não a medida do sucesso</strong> — e tentar nunca desagradar ninguém é justamente o que garante a manipulação.","tip":"<strong>Regra:</strong> o conflito não se evita; só se escolhe a resposta."},
  ],
  "lessons_title":"Lições-Chave do Capítulo I",
  "lessons":[
   "Você não pode evitar o conflito; só pode escolher luta, fuga ou assertividade.",
   "A não assertividade é aprendida — via ansiedade, ignorância e culpa — e por isso pode ser desaprendida.",
   "O objetivo é o autorrespeito primeiro; vencer é bônus, não a régua.",
   "Agressão não é assertividade — a luta ainda é um reflexo de sobrevivência.",
  ],
 },
 {
  "slug": "ch02-direito-primario",
  "sub": "CAPÍTULO II: O Direito Primário e Como Somos Manipulados",
  "intro": "Toda assertividade deriva de um direito primário: você é o juiz supremo de si mesmo. A manipulação funciona ao fazer você entregar essa autoridade de juiz a regras, estruturas e “deverias” que o manipulador controla.",
  "cards": [
   {"ic":"target","t":"Você é o Seu Juiz (Direito I)","emph":"Seu Juiz","b":"“Você tem o direito de julgar seu próprio comportamento, pensamentos e emoções, e de assumir a responsabilidade por sua iniciativa e consequências.” Você pode ouvir os outros, mas <strong>o veredito sobre você é seu</strong>. Todos os demais direitos derivam deste.","tip":"<strong>Como aplicar:</strong> quando ouvir “você deveria”, traduza para “eu preferiria que você…” — devolvendo a frase a um mero desejo, que você aceita ou recusa.","wide":True},
   {"ic":"book","t":"A Estrutura Externa","emph":"Estrutura Externa","b":"A ferramenta básica do manipulador: invocar regras, normas, lógica ou “o jeito que as coisas se fazem” como se isso decidisse seu comportamento por você. <strong>Você não é obrigado a viver por estruturas que não aceitou</strong> — “todo mundo sabe que você deveria” é só pressão fantasiada.","tip":"<strong>Sinal de alerta:</strong> um argumento “lógico” sobre o que você deveria fazer ainda é só a preferência de outra pessoa fantasiada.","warn":True},
   {"ic":"fork","t":"Os 3 Tipos de Interação","emph":"3 Tipos de Interação","b":"Para saber quanto pode se impor: comercial (troca explícita, contratos prévios obrigam, menor margem); autoridade (poder legítimo só sobre uma área definida, não sobre você como pessoa); igual (sem estrutura externa, assertividade plena). <strong>A margem cresce de comercial → autoridade → igual.</strong>","tip":"<strong>Regra:</strong> classifique a interação antes de reagir — o quanto pode se impor muda em cada uma."},
   {"ic":"sword","t":"Ferramentas Amorais","emph":"Amorais","b":"As habilidades assertivas são amorais — como dirigir um carro, servem para o bem ou para o mal. Ser seu próprio juiz significa que <strong>você responde pelo uso que faz delas</strong>. E elas não derrubam um contrato prévio genuíno: tentar parece tolice.","tip":"<strong>Cuidado:</strong> a assertividade não desfaz o pneu já rodado — respeite o que foi combinado de antemão."},
  ],
  "lessons_title":"Lições-Chave do Capítulo II",
  "lessons":[
   "Você é o seu juiz supremo — é o direito sobre o qual todos os outros se apoiam.",
   "Manipulação = transferir a autoridade de juiz para a estrutura externa; assertividade = mantê-la.",
   "Classifique a interação (comercial / autoridade / igual) para saber o quanto pode se impor.",
   "As habilidades são amorais — você responde por como as usa.",
  ],
 },
 {
  "slug": "ch03-dez-direitos",
  "sub": "CAPÍTULO III: Os Dez Direitos Assertivos",
  "intro": "Nove direitos do cotidiano estendem o direito primário às manipulações do dia a dia. Cada direito tem uma crença manipulativa como imagem espelhada: conhecer o direito pelo nome permite recusar a crença na hora.",
  "cards": [
   {"ic":"book","t":"A Carta de Direitos Assertivos","emph":"Carta de Direitos","b":"Os dez direitos — cada um <strong>anula um “deveria” manipulativo</strong>:","list":[
     "<strong>I.</strong> Julgar o próprio comportamento, pensamentos e emoções, e responder por eles.",
     "<strong>II.</strong> Não dar razões nem desculpas para se justificar.",
     "<strong>III.</strong> Julgar se você é responsável por resolver os problemas dos outros.",
     "<strong>IV.</strong> Mudar de ideia.",
     "<strong>V.</strong> Cometer erros — e se responsabilizar por eles.",
     "<strong>VI.</strong> Dizer “não sei”.",
     "<strong>VII.</strong> Ser independente da boa vontade alheia antes de lidar com ela.",
     "<strong>VIII.</strong> Ser ilógico ao tomar decisões.",
     "<strong>IX.</strong> Dizer “não entendi”.",
     "<strong>X.</strong> Dizer “não me importo”.",
    ],"tip":"<strong>Como aplicar:</strong> sob pressão, pergunte em silêncio “qual direito está sendo negado aqui?”. Nomeá-lo vira posição clara.","wide":True},
   {"ic":"target","t":"Os Dois Mais Potentes","emph":"Dois Mais Potentes","b":"Direito II (nenhuma razão nem desculpa): toda razão que você dá vira um gancho para o outro discutir. Direito VII (independência da boa vontade): você não precisa que gostem de você antes de poder lidar com eles — <strong>pode ser querido de novo depois do não</strong>.","tip":"<strong>Regra:</strong> no instante em que você se justifica (viola o II), convida o manipulador a refutar suas razões e reabrir o conflito."},
   {"ic":"pivot","t":"O Direito de Ser Ilógico (VIII)","emph":"Ser Ilógico","b":"Desejos e sentimentos não precisam passar num teste de lógica; “porque eu quero” é uma razão completa para si mesmo. Você também pode mudar de ideia (IV) — <strong>ideias e circunstâncias mudam</strong>, e você não fica preso à decisão de ontem.","tip":"<strong>Sinal de alerta:</strong> trate “mas isso não é lógico / justo / legal” como uma alavanca, não um xeque-mate."},
   {"ic":"scale","t":"Direito ↔ Crença Manipulativa","emph":"Crença Manipulativa","b":"Todo direito tem uma sombra: III ↔ “você tem de me ajudar”; V ↔ “errar é vergonhoso”; VI–IX ↔ “um adulto competente sempre sabe/entende”; X ↔ “você tem de se importar com o que penso”. <strong>Recuse a crença afirmando o direito correspondente.</strong>","tip":"<strong>Como aplicar:</strong> adotar o problema do outro como seu (violando o III) costuma ser culpa, não dever."},
  ],
  "lessons_title":"Lições-Chave do Capítulo III",
  "lessons":[
   "Memorize os dez direitos — cada um é uma resposta pronta a uma manipulação comum.",
   "“Nenhuma razão nem desculpa” (II) e “independência da boa vontade” (VII) desarmam a maior parte da pressão.",
   "Todo direito tem uma crença manipulativa como sombra; recuse a crença afirmando o direito.",
   "Adotar o problema do outro como seu (violando o III) costuma ser culpa, não dever.",
  ],
 },
 {
  "slug": "ch04-disco-riscado",
  "sub": "CAPÍTULO IV: Persistência — Disco Riscado e Acordo Viável",
  "intro": "A primeira técnica verbal é a persistência: repetir com calma o que você quer até o outro lado esgotar os “nãos”. Você perde a maioria dos conflitos não por estar errado, mas por desistir depois da primeira recusa.",
  "cards": [
   {"ic":"spiral","t":"Disco Riscado (Broken Record)","emph":"Disco Riscado","b":"Repetição calma do seu desejo, sem ensaiar argumentos nem acumular raiva: decida o desejo em uma frase; reconheça brevemente cada objeção e <strong>repita sem mudar a essência</strong>; não responda a desvios nem “lógica irrelevante”; mantenha o tom no mesmo nível.","tip":"<strong>Por que funciona:</strong> a maioria tem poucos “nãos” no bolso. “Se ele tem três, você só precisa de quatro.”","wide":True,"det":"<blockquote>“É contra a política.” — “Vejo que é a política, e quero meu dinheiro de volta.” “Você usou.” — “É verdade, e quero meu dinheiro de volta.” Sem raiva, sem novos argumentos: só o sulco, até esgotarem os nãos.</blockquote>"},
   {"ic":"scale","t":"Os Dois Placares","emph":"Dois Placares","b":"Separe o objetivo material (negociável; ceda à vontade) do autorrespeito (inegociável; nunca ceda). <strong>Perder o objetivo material mantendo o autorrespeito é uma vitória</strong> — porque o placar que conta é sempre o interno.","tip":"<strong>Modelo mental:</strong> imagine um disco riscado de verdade — mesmo sulco, mesma frase, repetição sem emoção: entediante, inabalável, eficaz."},
   {"ic":"link","t":"Acordo Viável (Workable Compromise)","emph":"Acordo Viável","b":"Sempre que o autorrespeito não estiver em jogo, ofereça um acordo prático no objetivo material (“metade agora, metade na sexta”). <strong>Você sempre pode negociar coisas</strong> — mas, se o objetivo toca o autovalor, não há acordo a fazer.","tip":"<strong>Regra dura:</strong> se o objetivo toca o autovalor, não há acordo — cedê-lo é derrota disfarçada de vitória."},
   {"ic":"sword","t":"O Erro Nº 1: Desistir","emph":"Desistir","b":"Desistir depois do primeiro “não” é a razão mais comum pela qual a pessoa não assertiva perde. A persistência vence o argumento: <strong>você não precisa de uma lógica melhor, só de mais fôlego</strong>.","tip":"<strong>Sinal de alerta:</strong> ser puxado para o assunto paralelo que o manipulador levanta, em vez de repetir o seu desejo.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo IV",
  "lessons":[
   "Defina um desejo claro e repita-o com calma; ignore todo desvio.",
   "As pessoas têm “nãos” limitados — seja mais persistente sem discutir.",
   "Negocie à vontade os objetivos materiais; nunca o autorrespeito.",
   "Contra um contrato prévio genuíno você pode perder — e tudo bem, o autorrespeito era a vitória.",
  ],
 },
 {
  "slug": "ch05-conversa-assertiva",
  "sub": "CAPÍTULO V: Conversa Assertiva — Informação Gratuita e Autorrevelação",
  "intro": "A assertividade não serve só para o conflito; ela torna a conversa comum fácil e à prova de manipulação. Duas técnicas fazem o trabalho — perceber a informação que o outro oferece e revelar os próprios altos e baixos sem vergonha — amparadas por um contato visual firme.",
  "cards": [
   {"ic":"bubble","t":"Informação Gratuita (Free Information)","emph":"Informação Gratuita","b":"Reconhecer as pequenas deixas não solicitadas que a pessoa oferece sobre o que lhe importa — e desdobrá-las. <strong>Escute o detalhe oferecido (“…depois que voltei da viagem…”) e pergunte sobre aquilo</strong>, e a conversa anda sozinha.","tip":"<strong>Como aplicar:</strong> trate cada resposta como uma sacola de informação gratuita — puxe um fio e siga-o."},
   {"ic":"person","t":"Autorrevelação (Self-Disclosure)","emph":"Autorrevelação","b":"Falar livremente dos seus lados positivos e negativos — comportamento, estilo de vida, opiniões — para aprofundar a comunicação e matar a manipulação de fome. <strong>Ofereça você mesmo o que normalmente esconderia, sem pedir desculpa.</strong>","tip":"<strong>Modelo mental:</strong> o que você revela não pode ser usado como arma — não há o que “expor” se você já disse."},
   {"ic":"eye","t":"Congruência Não Verbal","emph":"Congruência","b":"As palavras dizem uma coisa, o corpo diz outra — e as pessoas acreditam no corpo. <strong>O sinal mais claro de ansiedade é a falta de contato olho a olho</strong>; o nervosismo visível faz os outros te tolerarem em vez de honrar seus combinados.","tip":"<strong>Sinal de alerta:</strong> dizer as palavras confiantes desviando o olhar — o que chega é o nervosismo.","warn":True},
   {"ic":"shield","t":"Revelação como Armadura","emph":"Armadura","b":"Segredos são munição; assumir abertamente seus defeitos remove a alavanca. <strong>Esconder os negativos preserva exatamente as ansiedades (ignorância, culpa) que tornam você manipulável</strong> — revelar primeiro tira a arma da mão do outro.","tip":"<strong>Cuidado:</strong> interrogatório não é conversa — siga a informação oferecida em vez de disparar perguntas prontas."},
  ],
  "lessons_title":"Lições-Chave do Capítulo V",
  "lessons":[
   "Siga a informação gratuita que as pessoas oferecem; isso tira a timidez e conduz a conversa.",
   "Revele seus positivos e negativos abertamente — o que você revela não vira arma.",
   "Mantenha o contato visual; a ansiedade não verbal anula qualquer palavra assertiva.",
   "A revelação desmonta as alavancas de ignorância e culpa aprendidas na infância.",
  ],
 },
 {
  "slug": "ch06-lidar-com-critica",
  "sub": "CAPÍTULO VI: Lidando com a Crítica — Banco de Névoa e Asserção Negativa",
  "intro": "A crítica é o grande manipulador. Duas técnicas a neutralizam tirando a briga: concorde com qualquer verdade ou possibilidade que ela contenha, continue seu próprio juiz e não dê ao crítico manipulativo nada em que se apoiar.",
  "cards": [
   {"ic":"layers","t":"Banco de Névoa (Fogging)","emph":"Banco de Névoa","b":"Reconhecer com calma a probabilidade de haver algo de verdade numa crítica, sem deixar de ser o juiz do que você faz. Três movimentos: concorde com a <strong>verdade, a probabilidade ou o princípio</strong> da crítica (“tem razão”, “você pode ter razão”, “se eu fizesse isso, você teria um ponto”).","tip":"<strong>Por que funciona:</strong> como a névoa, você não oferece parede sólida — as farpas atravessam, você fica imóvel e a crítica não recebe recompensa.","wide":True},
   {"ic":"person","t":"Asserção Negativa (Negative Assertion)","emph":"Asserção Negativa","b":"Quando você está de fato errado (mesmo 100%), concorde de forma firme e solidária com a crítica — <strong>sem pedir desculpas</strong>. “Você tem razão, isso foi um descuido meu.”","tip":"<strong>Regra:</strong> quando errou de verdade, concorde mais que o crítico (“foi burrice minha”) — encerra o ataque mais rápido que qualquer defesa."},
   {"ic":"scale","t":"Elogio = Crítica","emph":"Elogio","b":"Para o assertivo, elogio e crítica são a mesma coisa: apenas o julgamento alheio. Receba qualquer um com a mesma calma, continuando seu próprio juiz. <strong>A crítica é informação que você pode usar ou descartar, não um veredito sobre seu valor.</strong>","tip":"<strong>Como aplicar:</strong> estas técnicas deixam você olhar para os próprios negativos sem ansiedade e sem mentir sobre um erro real."},
   {"ic":"sword","t":"Não se Defenda, Não Negue","emph":"Não se Defenda","b":"Defender-se ou negar transforma uma única crítica num debate que o manipulador pode vencer. <strong>Pedir desculpa por ser humano (excesso de desculpas) também perde</strong> — entrega a você o papel de réu.","tip":"<strong>Sinal de alerta:</strong> tratar a crítica como veredito sobre seu valor, em vez de informação a usar ou descartar.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo VI",
  "lessons":[
   "Concorde com a verdade, a probabilidade ou o princípio — a névoa não dá ao crítico nada para empurrar.",
   "Quando errado, assuma com firmeza e sem desculpas (Asserção Negativa); isso desarma a raiva.",
   "Elogio e crítica são a mesma coisa quando você continua seu próprio juiz.",
   "Concordar com calma extingue o reforço da crítica manipulativa — ela se apaga.",
  ],
 },
 {
  "slug": "ch07-interrogacao-negativa",
  "sub": "CAPÍTULO VII: Estimulando o Outro — Interrogação Negativa",
  "intro": "A última técnica central inverte o medo da crítica: você a pede ativamente. A Interrogação Negativa puxa a crítica para garimpar o que houver de útil e esgotar o que for manipulativo — treinando o outro a abandonar os truques e falar com honestidade.",
  "cards": [
   {"ic":"lens","t":"Interrogação Negativa (Negative Inquiry)","emph":"Interrogação Negativa","b":"Provocar ativamente a crítica a si mesmo: pergunte, com calma e repetidamente, por mais — <strong>“o que tem no meu fazer X que te incomoda?”, “o que mais?”</strong> — até o problema real vir à tona ou a crítica fabricada secar.","tip":"<strong>Por que funciona:</strong> a crítica manipulativa depende de ficar vaga; exigir detalhes ou rende informação genuína ou esvazia a sacola.","wide":True,"det":"<blockquote>— “Tá, faz o que você quiser.” — “Vejo que você está chateado; o que tem no meu sair que te incomoda?” — “Nada.” — “Parece que tem algo; o que especificamente?” Pressionado com honestidade, surge o desejo real: “queria que a gente jantasse junto”.</blockquote>"},
   {"ic":"fork","t":"Use ou Esgote","emph":"Use ou Esgote","b":"Toda crítica é feedback útil (guarde) ou um truque (drene) — a investigação separa os dois. <strong>Ao investigar em vez de se defender, você dissolve o enquadramento de “você está errado”</strong> usado para te controlar.","tip":"<strong>Como aplicar:</strong> continue pedindo detalhes até a informação real aparecer; não pare na primeira reclamação vaga."},
   {"ic":"link","t":"Treina o Outro a Ser Direto","emph":"Ser Direto","b":"Perguntar repetidamente “o que você realmente quer?” ensina os íntimos a declarar desejos diretamente, em vez de manipular — <strong>substituindo o emburramento e a indireta por pedidos honestos que dá para negociar</strong>.","tip":"<strong>Cuidado:</strong> o tom precisa ser curiosidade genuína; com sarcasmo, vira uma nova briga."},
   {"ic":"target","t":"Corra para a Crítica","emph":"Corra para a Crítica","b":"Corra em direção à crítica como um aspirador, não para longe dela: <strong>“me conta mais o que está errado no que eu fiz”</strong> tira o poder de ferir e o uso como alavanca.","tip":"<strong>Modelo mental:</strong> é depurar a relação — continue perguntando até achar o bug real, em vez de remendar sintomas."},
  ],
  "lessons_title":"Lições-Chave do Capítulo VII",
  "lessons":[
   "Convide a crítica ativamente — use o que for útil, esgote o que for manipulativo.",
   "Continue pedindo detalhes até o desejo real aparecer.",
   "A investigação treina as pessoas próximas a serem diretas em vez de manipulativas.",
   "Tom de curiosidade genuína; com sarcasmo vira briga.",
  ],
 },
 {
  "slug": "ch08-situacoes-comerciais",
  "sub": "CAPÍTULO VIII: Situações Comerciais — Onde Há Dinheiro Envolvido",
  "intro": "Conflitos comerciais (reembolsos, consertos, vendedores, mau atendimento) são vencidos combinando as técnicas — sobretudo o Disco Riscado para persistir e o Banco de Névoa para absorver desvios — respeitando que contratos prévios genuínos não se desfazem de forma assertiva.",
  "cards": [
   {"ic":"wrench","t":"A Pilha de Enfrentamento","emph":"Pilha de Enfrentamento","b":"Combine: <strong>Disco Riscado + Banco de Névoa + Acordo Viável + escalar com calma</strong> até quem pode dizer sim — declare e repita o desejo, neutralize desvios de “política”/culpa e negocie só o dinheiro.","tip":"<strong>Como aplicar:</strong> trate “é a nossa política” como desvio gratuito, não uma parede — dê Banco de Névoa e repita o desejo.","wide":True},
   {"ic":"book","t":"Prévio × Renegociável","emph":"Prévio","b":"Um termo assinado ou afixado, combinado de antemão, em geral vale (o pneu já bem rodado). Já um defeito ou mau atendimento é justo de cobrar. <strong>Tentar se impor por cima de um contrato real parece tolice e perde.</strong>","tip":"<strong>Sinal de alerta:</strong> discutir o mérito em vez de repetir o desejo dá ao funcionário ângulos para recusar.","warn":True},
   {"ic":"steps","t":"Suba até Quem Pode Dizer Sim","emph":"Quem Pode Dizer Sim","b":"Pergunte “quem aqui pode de fato conceder o que quero?” e suba até essa pessoa com o Disco Riscado. <strong>Não aceite o primeiro “não” de alguém que de toda forma não tem autoridade para dizer sim.</strong>","tip":"<strong>Como aplicar:</strong> ceda só no dinheiro (Acordo Viável); nunca abra mão de um tratamento respeitoso."},
   {"ic":"bubble","t":"Vendedor: Sem Explicação","emph":"Sem Explicação","b":"Na venda de porta em porta ou por telefone, você não deve nenhuma razão (Direito II): “não tenho interesse”, repetido, basta. <strong>Como funcionário, dar Banco de Névoa num cliente raivoso reduz a tensão sem abrir mão das regras.</strong>","tip":"<strong>Regra:</strong> persista e dê Banco de Névoa nos desvios — sem argumentar o mérito."},
  ],
  "lessons_title":"Lições-Chave do Capítulo VIII",
  "lessons":[
   "Persista (Disco Riscado) e dê Banco de Névoa nos desvios; escale até quem pode conceder.",
   "Você não deve explicação a vendedor — “não tenho interesse”, repetido, encerra.",
   "Negocie dinheiro com o Acordo Viável; nunca abra mão de um tratamento respeitoso.",
   "Contra um contrato prévio real, a assertividade não vale — respeite os termos combinados.",
  ],
 },
 {
  "slug": "ch09-situacoes-autoridade",
  "sub": "CAPÍTULO IX: Situações de Autoridade — Supervisão e Especialização",
  "intro": "A autoridade é real, mas limitada: o chefe governa tarefas definidas, o especialista governa o seu domínio — nenhum governa você como pessoa. Imponha-se dentro do limite, separando a exigência legítima da manipulação que vem de carona.",
  "cards": [
   {"ic":"person","t":"Autoridade é Limitada","emph":"Limitada","b":"Pergunte: “a autoridade dela cobre mesmo isto?”. Cumpra a parte legítima; imponha-se contra o excesso. <strong>Dê Banco de Névoa à crítica válida ao seu trabalho e use o Disco Riscado no que está fora da função.</strong>","tip":"<strong>Modelo mental:</strong> desenhe uma linha em volta do cargo — dentro, coopere; fora (vida privada, seu valor), imponha-se.","wide":True},
   {"ic":"target","t":"Entrevista Assertiva","emph":"Entrevista Assertiva","b":"Antecipe o próprio nervosismo com Asserção Negativa + Interrogação Negativa: <strong>“eu sempre fico um pouco nervoso em entrevista — isso vai atrapalhar?”</strong>. Assumir a fraqueza a desarma e soa como confiança.","tip":"<strong>Sinal de alerta:</strong> transmitir dúvida sobre habilidades menores faz você parecer uma dor de cabeça futura."},
   {"ic":"link","t":"A Linha do Cargo","emph":"Linha do Cargo","b":"Você pode fazer o que o cargo exige e, ao mesmo tempo, recusar-se a ser diminuído como pessoa. <strong>Pais e professores também impõem limites e recebem reclamações com Banco de Névoa, em vez de batalhas de justificativa.</strong>","tip":"<strong>Exemplo:</strong> “você pode ter razão que é arriscado, e como passo minhas noites é decisão minha.”"},
   {"ic":"sword","t":"Não se Justifique ao Chefe","emph":"Não se Justifique","b":"Justificar-se à autoridade convida a mais supervisão. <strong>Esconder o nervosismo na entrevista só o amplifica</strong> — revele e siga em frente, em vez de gastar energia disfarçando.","tip":"<strong>Cuidado:</strong> deixar a autoridade do cargo vazar para o controle pessoal (um chefe ditando sua vida privada) sem questionar.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo IX",
  "lessons":[
   "A autoridade cobre só uma área definida — coopere ali, imponha-se além dela.",
   "Revele o nervosismo da entrevista logo de cara; assumir soa como força.",
   "Dê Banco de Névoa na crítica válida ao trabalho; use o Disco Riscado no que mira você pessoalmente.",
   "Justificar-se à autoridade convida a mais supervisão.",
  ],
 },
 {
  "slug": "ch10-situacoes-iguais",
  "sub": "CAPÍTULO X: Situações entre Iguais — Amigos, Vizinhos, Família",
  "intro": "Com pares não há estrutura externa para se esconder, então a manipulação roda quase toda na culpa e na obrigação (“depois de tudo que fiz…”, “um amigo de verdade faria…”). É aqui que os direitos mais importam — em especial o de dizer não e o de não dar razões.",
  "cards": [
   {"ic":"fork","t":"Dizer “Não” a um Par","emph":"Não","b":"Disco Riscado + Direito II (nenhuma razão). Quando insistirem, <strong>não dê razões (que convidam à réplica)</strong>: “entendo que você precise, e não”. Repita. Dê Banco de Névoa na culpa (“você pode achar isso egoísmo — e não”).","tip":"<strong>Regra:</strong> sem razões = sem ganchos — o “não” sem justificativa é irrespondível.","wide":True,"det":"<blockquote>— “Mas você nem vai usar o carro hoje!” — “É verdade, e ainda assim prefiro não.” — “Pensei que a gente fosse amigo.” — “Somos, e a resposta continua não.”</blockquote>"},
   {"ic":"sword","t":"A Alavanca da Culpa","emph":"Alavanca da Culpa","b":"A culpa é a ferramenta principal do manipulador-par: “eu faria por você”, “você mudou”, “um amigo de verdade faria”. <strong>Reconheça, dê Banco de Névoa no enquadramento moral e segure a linha</strong> — uma relação de verdade sobrevive a um não.","tip":"<strong>Sinal de alerta:</strong> comprar o enquadramento “um amigo de verdade faria…” — isso é a manipulação, não um fato sobre amizade.","warn":True},
   {"ic":"shield","t":"O Direito VII na Prática","emph":"Direito VII","b":"Você não precisa da aprovação deles antes de poder lidar com eles — <strong>dá para ser querido de novo depois de ter dito não</strong>. Pais intrometidos podem ser recusados com as mesmas técnicas, com gentileza mas firmeza.","tip":"<strong>Como aplicar:</strong> com pares, decida sua linha antes da conversa — espere a alavanca da culpa como padrão."},
   {"ic":"link","t":"Não Explique o seu “Não”","emph":"Não Explique","b":"Toda razão que você dá a um amigo é algo para ele rebater. <strong>Ceder para acabar com a culpa só ensina os pares de que a culpa funciona com você</strong> — recuse com um “não” simples.","tip":"<strong>Regra:</strong> o nome do jogo é não dar gancho."},
  ],
  "lessons_title":"Lições-Chave do Capítulo X",
  "lessons":[
   "Com pares, recuse com um “não” simples e não dê razões (Direito II).",
   "A culpa é a principal manipulação entre pares — nomeie, dê Banco de Névoa, segure a linha.",
   "Você não precisa de aprovação antes de agir (Direito VII); o afeto pode voltar depois.",
   "Ceder para acabar com a culpa ensina os pares de que a culpa funciona com você.",
  ],
 },
 {
  "slug": "ch11-desejos-sexuais",
  "sub": "CAPÍTULO XI: Afirmar os Desejos Sexuais — e a Questão Social",
  "intro": "Desejos sexuais são desejos diferentes, mas o comportamento assertivo é exatamente o mesmo: declarar o que quer, recusar o que não quer, negociar acordos viáveis e revelar-se com abertura. A não assertividade e a manipulação são grandes causas ocultas de dificuldade sexual.",
  "cards": [
   {"ic":"person","t":"Mesmas Técnicas, Terreno Carregado","emph":"Mesmas Técnicas","b":"Autorrevelação + Interrogação Negativa + Acordo Viável aplicados ao sexo: revele seus desejos e receios com clareza; investigue os do parceiro; <strong>negocie os atos (material), nunca o autorrespeito</strong>. Dizer não à sedução é o mesmo enfrentamento de qualquer manipulação.","tip":"<strong>Frase do livro:</strong> “primeiro a asserção, depois a inserção” — a assertividade é pré-requisito de uma relação sexual saudável.","wide":True},
   {"ic":"eye","t":"Agendas Ocultas de Ansiedade","emph":"Agendas Ocultas","b":"Medos não ditos sobre mudança se disfarçam de preferências; a revelação os traz à luz, onde podem ser negociados. <strong>Dar indiretas em vez de revelar um desejo — e depois se ressentir de o parceiro não ter adivinhado — é antipadrão.</strong>","tip":"<strong>Como aplicar:</strong> a Interrogação Negativa substitui o emburramento e a indireta por desejos ditos com honestidade."},
   {"ic":"scale","t":"Negocie os Atos, Não a Dignidade","emph":"Não a Dignidade","b":"Negocie livremente os atos sexuais; uma exigência que custa seu autovalor é inegociável. <strong>A manipulação no sexo (culpa, “mágoa”, acusação) é a mesma alavanca de qualquer lugar</strong> — reconheça e use o mesmo enfrentamento.","tip":"<strong>Sinal de alerta:</strong> passividade silenciosa ou manipulação no sexo é rota documentada para a disfunção."},
   {"ic":"constellation","t":"A Questão Social","emph":"Questão Social","b":"Perguntado sobre o que aconteceria com a sociedade se muitos virassem assertivos, Smith responde com honestidade: “Não sei.” Sua preocupação está nos dois extremos — o indivíduo e a espécie — e na menor unidade social: <strong>duas pessoas resolvendo disputas pelos temas reais, não por quem manipula melhor</strong>.","tip":"<strong>Fecho:</strong> o objetivo de toda a obra é resolver o conflito pelos fatos da disputa, não pela força relativa das personalidades."},
  ],
  "lessons_title":"Lições-Chave do Capítulo XI",
  "lessons":[
   "Desejos sexuais são diferentes, mas o comportamento assertivo (revelar, investigar, negociar os atos) é idêntico.",
   "A não assertividade e a manipulação movem boa parte da dificuldade sexual.",
   "Revele as ansiedades ocultas; provoque os desejos reais do parceiro com a Interrogação Negativa.",
   "Negocie os atos; preserve sempre a dignidade.",
  ],
 },
]
