# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Quando Digo Não, Me Sinto Culpado' (Manuel J. Smith).
Termos canônicos: Disco Riscado, Banco de Névoa, Asserção Negativa,
Interrogação Negativa, Informação Gratuita, Autorrevelação, Acordo Viável."""

BOOK = {
  "title": "Quando Digo Não, Me Sinto Culpado",
  "author": "Manuel J. Smith",
  "header_light": "QUANDO DIGO NÃO,",
  "header_bold": "ME SINTO CULPADO",
  "subtitle": "VISÃO GERAL · O DIREITO DE DIZER NÃO SEM PEDIR DESCULPA",
  "intro": "Aquela culpa que sobe quando você diz não a alguém não é a sua consciência falando — é uma alavanca que instalaram em você na infância, e que outra pessoa está puxando agora. Smith parte daí com uma calma quase fria: a passividade não é defeito de caráter, é hábito treinado, e tudo que se treina se destreina. Ele não te ensina a vencer discussões nem a ganhar o que quer; ensina a parar de entregar, no primeiro 'você deveria', a única coisa que ninguém pode te tomar sem a sua licença — o veredito sobre quem você é. O resto é um punhado de frases ditas com voz baixa e ombros firmes.",
  "description": "O manual fundador do treino de assertividade (1975). Manuel J. Smith — psicólogo comportamental — trata a manipulação como mecânica, não como moral: ela funciona por três botões aprendidos (ansiedade, ignorância, culpa) e se desarma com um repertório de habilidades verbais frias e repetíveis — Disco Riscado, Banco de Névoa, Asserção e Interrogação Negativas. Sob todas, um único direito primário: você é o juiz supremo de si mesmo. Conseguir o que quer é bônus; o placar que conta é o autorrespeito, e esse não entra em negociação.",
  "tags": ["Assertividade", "Comunicação", "Psicologia"],
  "progress": "11 Capítulos",
  "cover": "assets/smith-assertividade-capa.png",
  "overview_cards": [
    {"ic":"target","t":"Você é o Seu Próprio Juiz","b":"Existe um direito do qual todos os outros descem: você é o juiz supremo do que faz, pensa e sente. Manipular é só uma coisa — convencer você a <strong>entregar essa toga a outra pessoa</strong>, a uma regra, a um 'todo mundo sabe que'. Enquanto o veredito sobre você ficar na sua mão, não há alavanca que pegue.","tip":"<strong>Modelo mental:</strong> todo “você deveria” é, no fundo, um “eu preferiria que você…” fantasiado de lei. Traduza de volta — e então decida se atende ao desejo do outro.","wide":True},
    {"ic":"sword","t":"As 3 Alavancas: Ansiedade, Ignorância, Culpa","b":"Ninguém nasce manipulável; aprende. Crianças são adestradas por três botões emocionais: ansiedade (“se não fizer, algo terrível acontece”), ignorância (“cale-se, quem sabe é a autoridade”) e culpa (“se fizer, você é um mau filho”). A onda súbita que você sente num conflito <strong>é o botão sendo apertado</strong> — não é a verdade chegando, é a coleira sendo puxada.","tip":"<strong>Sinal de alerta:</strong> culpa, medo ou autodúvida que surgem do nada, na hora exata em que você ia se impor, são o flagrante da manipulação."},
    {"ic":"wrench","t":"Um Punhado de Frases Treináveis","b":"A saída não é coragem nem retórica: é um repertório pequeno de habilidades verbais que se repetem a frio — Disco Riscado, Banco de Névoa, Asserção e Interrogação Negativas, Informação Gratuita, Autorrevelação. São <strong>amorais como dirigir um carro</strong>: levam ao bem ou ao mal, e quem vai ao volante responde pelo trajeto.","tip":"<strong>Como aplicar:</strong> você não decora discursos — escolhe a técnica certa para a situação e a treina até ela sair sem raiva e sem ensaio."},
    {"ic":"scale","t":"O Placar é o Autorrespeito","b":"O prêmio não é levar a melhor: é sair de qualquer briga ainda inteiro por dentro. Ganhar o que você queria acontece com frequência — mas é <strong>bônus, não a régua</strong>. A régua é o autorrespeito, que se mantém até quando você perde o objeto da disputa. Quem só quer nunca desagradar já assinou, de véspera, a própria coleira.","tip":"<strong>Regra:</strong> o dinheiro, a hora, a tarefa — negocie tudo à larga. O autorrespeito não está na mesa de negociação."},
  ],
}

CHAPTERS = [
 {
  "slug": "ch01-sobrevivencia",
  "sub": "CAPÍTULO I: Sobrevivência e as Raízes da Não Assertividade",
  "intro": "Onde há duas vontades, mais cedo ou mais tarde há choque — o conflito não se evita, só se responde a ele. O bicho que sobrou em nós só sabe duas saídas: bater ou correr. Mas o ser humano tem uma terceira, e é a única que não deixa estrago: falar. Se você não usa essa terceira, não é porque nasceu fraco — é porque alguém, lá atrás, ensinou você a obedecer com medo, com obediência cega e com culpa.",
  "cards": [
   {"ic":"fork","t":"Bater, Correr ou Falar","emph":"Falar","b":"São as três respostas ao conflito. Bater (agressão) e correr (fuga) são o réptil ainda vivo dentro de você — reflexos que serviam na savana e atrapalham na mesa de jantar. <strong>A palavra firme e repetida é a saída que só o humano tem</strong>, e a única que resolve sem queimar a ponte.","tip":"<strong>Modelo mental:</strong> a raiva que ataca e o silêncio que se retira são primos — os dois admitem que você perdeu o controle. A assertividade é não perdê-lo."},
   {"ic":"sword","t":"As 3 Alavancas Emocionais","emph":"3 Alavancas","b":"É assim que a criança — e o adulto que ela vira — fica de coleira: ansiedade (“se não fizer, acontece algo horrível”), ignorância (“não discuta, quem sabe é a autoridade”) e culpa (“se fizer, você é mau”). O <strong>“me sinto culpado” do título</strong> é esta terceira, a alavanca de cabo mais comprido — a que o outro puxa sem nem precisar levantar a voz.","tip":"<strong>Sinal de alerta:</strong> o turbilhão que sobe de repente num conflito não é a sua consciência avisando — é a alavanca sendo acionada. Sinta, e não obedeça.","warn":True},
   {"ic":"mask","t":"O Que É Manipulação","emph":"Manipulação","b":"É controlar o seu comportamento pela porta dos fundos: mexer nas suas emoções em vez de declarar, às claras, um desejo que você poderia aceitar ou recusar. Um pai pode pôr limites sem instalar medo, culpa e ignorância — <strong>a maioria não soube, e fabricou adultos dóceis</strong> sem nunca ter querido o mal.","tip":"<strong>Como aplicar:</strong> se a passividade foi aprendida, ela pode ser desaprendida — não é o seu jeito de ser, é um hábito velho."},
   {"ic":"scale","t":"O Placar é o Autorrespeito","emph":"Autorrespeito","b":"O que você ganha é por dentro: o autorrespeito, que fica de pé mesmo quando o objeto da briga escapa. <strong>Levar a melhor é bônus frequente, não a medida do sucesso</strong>. Querer agradar a todos o tempo todo não é gentileza — é o convite escrito que a manipulação esperava receber.","tip":"<strong>Regra:</strong> você não escolhe se haverá conflito; escolhe só com qual das três respostas vai entrar nele."},
  ],
  "lessons_title":"Lições-Chave do Capítulo I",
  "lessons":[
   "O conflito é inevitável; o que você decide é entrar nele batendo, correndo ou falando.",
   "A passividade não é caráter — é treino de infância via ansiedade, ignorância e culpa. E o que se treina, se destreina.",
   "O alvo é o autorrespeito antes de tudo; vencer a disputa é bônus, não a régua.",
   "Agressão não é assertividade: quem ataca ainda está no reflexo do bicho, não no comando da palavra.",
  ],
 },
 {
  "slug": "ch02-direito-primario",
  "sub": "CAPÍTULO II: O Direito Primário e Como Somos Manipulados",
  "intro": "Há uma só raiz, e todo o resto cresce dela: você é o juiz supremo de si mesmo. A manipulação não tem outro truque além deste — fazer você passar a toga de juiz para a mão alheia, escondida atrás de uma regra, de uma lógica, de um “é assim que se faz”. Saber a quem pertence o martelo, em cada situação, é metade da batalha.",
  "cards": [
   {"ic":"target","t":"Você é o Seu Juiz (Direito I)","emph":"Seu Juiz","b":"O direito primário, do qual todos descem: julgar o próprio comportamento, pensamentos e emoções — e arcar com as consequências disso. Ouça quem quiser; peça conselho a quem confiar. Mas <strong>a última palavra sobre você não se delega</strong>. Quem a entrega fica à mercê de qualquer um que a pegue.","tip":"<strong>Como aplicar:</strong> todo “você deveria” é o desejo de alguém vestido de mandamento. Dispa a roupa — vire “ele preferiria que eu…” — e o mandamento volta a ser um pedido que você aceita ou recusa.","wide":True},
   {"ic":"book","t":"A Estrutura Externa","emph":"Estrutura Externa","b":"A ferramenta nº 1 do manipulador: invocar a regra, a norma, a lógica, “o jeito certo das coisas” como se elas decidissem por você. Mas <strong>nenhuma estrutura governa você sem a sua adesão</strong> — “todo mundo sabe que você deveria” não é um fato sobre o mundo, é pressão usando fantasia de fato.","tip":"<strong>Sinal de alerta:</strong> quanto mais “lógico” e “justo” soa o argumento sobre o que você tem de fazer, mais é a preferência do outro caprichosamente embalada.","warn":True},
   {"ic":"fork","t":"Os 3 Tipos de Interação","emph":"3 Tipos de Interação","b":"Antes de reagir, saiba onde você está: comercial (a troca é explícita, o que foi combinado obriga — margem curta); autoridade (o poder é real, mas só sobre a tarefa, nunca sobre você como pessoa); igual (sem estrutura nenhuma para se esconder — assertividade cheia). <strong>De comercial a igual, a sua margem só cresce.</strong>","tip":"<strong>Regra:</strong> classifique a cena primeiro — o quanto você pode se impor não é o mesmo no balcão da loja, na sala do chefe e na mesa do amigo."},
   {"ic":"sword","t":"Ferramentas Amorais","emph":"Amorais","b":"Estas habilidades não têm moral própria — como um carro, levam ao hospital ou ao desastre. Ser o seu próprio juiz cobra o preço: <strong>você responde pelo uso que faz delas</strong>. E elas têm um limite honesto — não desfazem um acordo legítimo que você firmou antes; tentar usá-las contra a própria palavra é só teimosia.","tip":"<strong>Cuidado:</strong> assertividade não apaga o que você combinou de véspera — o que está rodado, está rodado. Ela serve para o que ainda está em aberto."},
  ],
  "lessons_title":"Lições-Chave do Capítulo II",
  "lessons":[
   "Você é o juiz supremo de si mesmo — a viga que sustenta todos os outros direitos.",
   "Manipular é transferir a toga de juiz para a estrutura externa; ser assertivo é não soltá-la.",
   "Leia a cena — comercial, autoridade ou igual — antes de reagir; a margem de imposição muda em cada uma.",
   "As técnicas são amorais como um volante: a estrada que você escolhe é responsabilidade sua.",
  ],
 },
 {
  "slug": "ch03-dez-direitos",
  "sub": "CAPÍTULO III: Os Dez Direitos Assertivos",
  "intro": "Do direito primário brotam nove direitos do dia a dia, um para cada manipulação corriqueira. E cada um tem uma sombra: a crença manipulativa que ele desmente. Saber o nome do direito é ter, no bolso, a resposta pronta — porque o que pega você de surpresa é justamente o que você não soube nomear na hora.",
  "cards": [
   {"ic":"book","t":"A Carta de Direitos Assertivos","emph":"Carta de Direitos","b":"Dez direitos, e cada um <strong>derruba um “você deveria” específico</strong>:","list":[
     "<strong>I.</strong> Julgar o próprio comportamento, pensamentos e emoções, e responder por eles.",
     "<strong>II.</strong> Não dar razões nem desculpas para se justificar.",
     "<strong>III.</strong> Julgar se você é responsável por resolver os problemas dos outros.",
     "<strong>IV.</strong> Mudar de ideia.",
     "<strong>V.</strong> Cometer erros — e se responsabilizar por eles.",
     "<strong>VI.</strong> Dizer “não sei”.",
     "<strong>VII.</strong> Ser independente da boa vontade alheia antes de lidar com ela.",
     "<strong>VIII.</strong> Ser ilógico ao tomar decisões.",
     "<strong>IX.</strong> Dizer “não entendi”.",
     "<strong>X.</strong> Dizer “não me importo”.",
    ],"tip":"<strong>Como aplicar:</strong> no meio da pressão, faça em silêncio uma só pergunta — “qual direito estão tentando me negar agora?”. Nomeado, o direito vira chão firme sob os seus pés.","wide":True},
   {"ic":"target","t":"Os Dois Mais Potentes","emph":"Dois Mais Potentes","b":"Direito II — nenhuma razão, nenhuma desculpa: cada justificativa que você dá é uma corda que você joga para o outro puxar. Direito VII — independência da boa vontade: você não precisa que gostem de você para poder dizer não. <strong>Diga o não hoje; o afeto pode voltar amanhã</strong>, e em geral volta.","tip":"<strong>Regra:</strong> no segundo em que você explica por que (rompendo o II), você reabre o caso e convida o manipulador a recorrer da sua sentença."},
   {"ic":"pivot","t":"O Direito de Ser Ilógico (VIII)","emph":"Ser Ilógico","b":"Vontade e sentimento não prestam contas à lógica de ninguém; “porque eu quero” é razão inteira, e basta a você. E você pode mudar de ideia (IV): <strong>as circunstâncias mudam, e você não está algemado à decisão de ontem</strong>. Quem cobra coerência sua costuma estar cobrando obediência.","tip":"<strong>Sinal de alerta:</strong> “mas isso não é lógico / justo / coerente” não é xeque-mate — é mais uma alavanca, pintada de raciocínio."},
   {"ic":"scale","t":"Direito ↔ Crença Manipulativa","emph":"Crença Manipulativa","b":"Cada direito projeta uma sombra, e a sombra é a mentira: III ↔ “você tem a obrigação de me ajudar”; V ↔ “errar é vergonha”; VI–IX ↔ “gente competente nunca diz não sei, não entendi”; X ↔ “você é obrigado a se importar com o que eu acho”. <strong>Para apagar a sombra, acenda o direito que ela nega.</strong>","tip":"<strong>Como aplicar:</strong> abraçar o problema do outro como se fosse seu (atropelando o III) quase nunca é dever — é a culpa disfarçada de generosidade."},
  ],
  "lessons_title":"Lições-Chave do Capítulo III",
  "lessons":[
   "Decore os dez direitos: cada um é a réplica pronta para uma manipulação que você já vai encontrar.",
   "“Sem razões nem desculpas” (II) e “independo da sua aprovação” (VII) desarmam a maior parte da pressão sozinhos.",
   "Todo direito tem uma crença manipulativa por sombra — apague a sombra afirmando o direito.",
   "Carregar o problema alheio nas costas (violando o III) costuma ser culpa vestida de dever.",
  ],
 },
 {
  "slug": "ch04-disco-riscado",
  "sub": "CAPÍTULO IV: Persistência — Disco Riscado e Acordo Viável",
  "intro": "A primeira técnica é a mais simples e a mais subestimada: persistir. Repetir, com voz mansa, o que você quer, até o outro lado ficar sem “nãos” no bolso. Você não perde a maioria das suas brigas por estar errado — perde porque solta a corda no primeiro puxão. Quem não desiste vence sem precisar ter o melhor argumento.",
  "cards": [
   {"ic":"spiral","t":"Disco Riscado (Broken Record)","emph":"Disco Riscado","b":"Repita o seu desejo como uma agulha presa no sulco — sem novos argumentos, sem juntar raiva: resuma o que você quer numa frase; reconheça de relance cada objeção e <strong>volte à mesma frase, intacta</strong>; ignore desvios e “lógicas” que não vêm ao caso; mantenha o tom exatamente onde estava.","tip":"<strong>Por que funciona:</strong> quase ninguém tem muitos “nãos” guardados. Se o outro tem três, basta você ter quatro.","wide":True,"det":"<blockquote>— “É contra a nossa política.” — “Entendo que seja a política, e eu quero o meu dinheiro de volta.” — “Mas você já usou.” — “É verdade, e quero o meu dinheiro de volta.” Sem alterar a voz, sem inventar argumento novo: só o mesmo sulco, girando, até os nãos acabarem.</blockquote>"},
   {"ic":"scale","t":"Os Dois Placares","emph":"Dois Placares","b":"Toda disputa tem dois placares — não os confunda. O objetivo material (o dinheiro, a folga, o favor) é negociável: ceda à vontade. O autorrespeito é inegociável: não ceda nunca. <strong>Sair sem o objeto, mas inteiro por dentro, é vitória</strong> — porque o único placar que conta de verdade é o de dentro.","tip":"<strong>Modelo mental:</strong> seja, de propósito, um disco riscado — mesma frase, mesmo tom, repetição sem emoção. É entediante, é imbatível, e funciona justamente por isso."},
   {"ic":"link","t":"Acordo Viável (Workable Compromise)","emph":"Acordo Viável","b":"Quando o autorrespeito não está em jogo, ofereça um meio-termo prático no material — “metade agora, metade na sexta”. <strong>Coisas sempre se negociam.</strong> Mas, no instante em que o objetivo encosta no seu valor próprio, não há acordo a fechar: ali a régua some.","tip":"<strong>Regra dura:</strong> se a concessão arranha quem você é, não é concessão — é derrota com laço de presente."},
   {"ic":"sword","t":"O Erro Nº 1: Desistir","emph":"Desistir","b":"Largar a corda depois do primeiro “não” é, de longe, por que a pessoa passiva perde. A persistência vence o argumento: <strong>você não precisa de uma lógica melhor, só de mais fôlego que o outro</strong>. O manipulador conta exatamente com a sua pressa de encerrar.","tip":"<strong>Sinal de alerta:</strong> quando você se vê discutindo o assunto paralelo que o outro jogou na mesa, em vez de repetir o seu desejo — caiu no desvio.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo IV",
  "lessons":[
   "Resuma o desejo numa frase e repita-a com calma; deixe passar todo desvio.",
   "Os “nãos” do outro são contados — só seja mais persistente, sem entrar na discussão.",
   "Negocie o material à larga; o autorrespeito jamais.",
   "Contra um acordo legítimo que você firmou antes, você pode perder o objeto — e tudo bem: o autorrespeito já era a vitória.",
  ],
 },
 {
  "slug": "ch05-conversa-assertiva",
  "sub": "CAPÍTULO V: Conversa Assertiva — Informação Gratuita e Autorrevelação",
  "intro": "Assertividade não é arma só de briga; é o que torna a conversa banal leve e, de quebra, à prova de manipulação. Duas habilidades fazem o serviço: captar a deixa que o outro deixa cair sem querer, e expor os próprios altos e baixos sem corar. As duas se apoiam em uma coisa simples e implacável — olhar nos olhos.",
  "cards": [
   {"ic":"bubble","t":"Informação Gratuita (Free Information)","emph":"Informação Gratuita","b":"São as migalhas que a pessoa larga de graça sobre o que lhe importa — e que você só precisa apanhar. <strong>Pesque o detalhe oferecido (“…depois que voltei da viagem…”) e pergunte exatamente sobre ele</strong>: a conversa passa a andar sozinha, e o silêncio constrangido desaparece.","tip":"<strong>Como aplicar:</strong> trate cada resposta do outro como uma sacola aberta — puxe um fio que esteja para fora e siga por ele."},
   {"ic":"person","t":"Autorrevelação (Self-Disclosure)","emph":"Autorrevelação","b":"Falar à vontade do que você é — virtudes e defeitos, manias, opiniões — para a conversa ganhar fundo e a manipulação morrer de fome. <strong>Entregue você mesmo o que costumaria esconder, e sem pedir desculpa por nada disso.</strong>","tip":"<strong>Modelo mental:</strong> o que você já contou ninguém pode usar como ameaça — não há o que “expor” de quem já se mostrou."},
   {"ic":"eye","t":"Congruência Não Verbal","emph":"Congruência","b":"A boca diz uma coisa, o corpo diz outra — e é no corpo que as pessoas acreditam. <strong>O delator mais óbvio da ansiedade é o olhar que foge</strong>; e o nervosismo à mostra faz o outro te suportar, em vez de honrar o que combinou com você.","tip":"<strong>Sinal de alerta:</strong> frase confiante dita com o olho na parede — o que chega ao outro não é a frase, é o nervosismo."},
   {"ic":"shield","t":"Revelação como Armadura","emph":"Armadura","b":"Segredo é munição que você guarda na mão de quem vai atirar em você. Assumir um defeito de cara desliga a alavanca: <strong>esconder os próprios negativos é o que conserva, intactas, as culpas e os medos que fazem de você presa fácil</strong>. Quem se revela primeiro tira a arma da mão do outro.","tip":"<strong>Cuidado:</strong> conversa não é interrogatório — siga a informação oferecida, não dispare uma bateria de perguntas decoradas."},
  ],
  "lessons_title":"Lições-Chave do Capítulo V",
  "lessons":[
   "Apanhe a informação gratuita que o outro deixa cair: ela dissolve a timidez e conduz a conversa.",
   "Mostre virtudes e defeitos sem rodeio — o que você revela deixa de ser arma na mão alheia.",
   "Olhe nos olhos: a ansiedade no corpo cancela qualquer palavra assertiva da boca.",
   "Revelar-se desmonta as alavancas de ignorância e culpa que instalaram em você na infância.",
  ],
 },
 {
  "slug": "ch06-lidar-com-critica",
  "sub": "CAPÍTULO VI: Lidando com a Crítica — Banco de Névoa e Asserção Negativa",
  "intro": "A crítica é o cabo mais comprido de todas as alavancas — é com ela que mais te puxam. Duas técnicas a desarmam tirando a briga de cena: concorde com o que ela tiver de verdadeiro ou possível, siga sendo o juiz do que você faz, e não dê ao crítico manipulador uma única parede onde encostar.",
  "cards": [
   {"ic":"layers","t":"Banco de Névoa (Fogging)","emph":"Banco de Névoa","b":"Reconheça, em voz calma, que pode haver algum fundo de verdade na crítica — sem nunca largar a toga de juiz do seu comportamento. Três degraus: concorde com a <strong>verdade, com a probabilidade ou com o princípio</strong> dela (“tem razão”, “você pode ter razão”, “se eu fizesse isso, você teria um ponto”).","tip":"<strong>Por que funciona:</strong> a névoa não devolve parede nenhuma. As farpas atravessam, você não se move, e a crítica volta para o atirador sem nenhum prêmio — então ela cessa.","wide":True},
   {"ic":"person","t":"Asserção Negativa (Negative Assertion)","emph":"Asserção Negativa","b":"Quando você errou mesmo — ainda que cem por cento — concorde com firmeza e até com simpatia, <strong>e sem pedir desculpa</strong>: “tem toda a razão, isso foi descuido meu”. Assumir o erro de frente é o que o tira de cena; defender-se é o que o mantém vivo.","tip":"<strong>Regra:</strong> quando o erro é real, concorde mais que o próprio crítico (“foi burrice minha mesmo”). Nada encerra o ataque mais rápido do que ele não ter o que acrescentar."},
   {"ic":"scale","t":"Elogio = Crítica","emph":"Elogio","b":"Para quem é o próprio juiz, elogio e crítica são a mesma matéria: a opinião de outra pessoa. Receba os dois com a mesma calma, sem deixar nenhum decidir o seu valor. <strong>A crítica é informação para usar ou descartar — não um veredito sobre quem você é.</strong>","tip":"<strong>Como aplicar:</strong> estas técnicas deixam você encarar os próprios defeitos sem ansiedade — e sem precisar mentir sobre um erro que de fato cometeu."},
   {"ic":"sword","t":"Não se Defenda, Não Negue","emph":"Não se Defenda","b":"Defender-se ou negar converte uma frase solta num debate — e o debate o manipulador sabe vencer. <strong>Pedir desculpa por ser humano (a enxurrada de “desculpa, desculpa”) também perde</strong>: veste em você, de graça, a roupa de réu.","tip":"<strong>Sinal de alerta:</strong> no instante em que você sente a crítica como sentença sobre o seu valor — e não como informação a aproveitar ou jogar fora — já mordeu a isca.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo VI",
  "lessons":[
   "Concorde com a verdade, a probabilidade ou o princípio: a névoa não dá ao crítico nada para empurrar.",
   "Errou? Assuma com firmeza e sem desculpas (Asserção Negativa) — é o que esvazia a raiva do outro.",
   "Elogio e crítica viram a mesma coisa quando o veredito sobre você continua na sua mão.",
   "Concordar com calma corta o reforço da crítica manipuladora — sem prêmio, ela se apaga sozinha.",
  ],
 },
 {
  "slug": "ch07-interrogacao-negativa",
  "sub": "CAPÍTULO VII: Estimulando o Outro — Interrogação Negativa",
  "intro": "A última técnica central faz a coisa que ninguém espera: ela vai atrás da crítica de propósito. A Interrogação Negativa puxa a crítica para a luz — garimpa o que houver de útil e drena o que for truque. E, no caminho, ensina o outro a largar a indireta e dizer, afinal, o que de fato quer.",
  "cards": [
   {"ic":"lens","t":"Interrogação Negativa (Negative Inquiry)","emph":"Interrogação Negativa","b":"Convoque a crítica contra você mesmo, calmamente e mais de uma vez: <strong>“o que tem no meu fazer isso que te incomoda?”, “o que mais?”</strong> — até o problema verdadeiro aparecer ou a crítica de fachada ficar sem combustível.","tip":"<strong>Por que funciona:</strong> a crítica manipuladora sobrevive de ser vaga. Exigir detalhe ou faz brotar a informação real ou esvazia a sacola — não há terceira saída.","wide":True,"det":"<blockquote>— “Tá, faz o que você quiser.” — “Vejo que você ficou chateado; o que te incomoda no meu sair?” — “Nada.” — “Parece que tem algo, sim; o que, exatamente?” Pressionada com gentileza, a verdade aparece: “eu queria que a gente jantasse junto hoje”.</blockquote>"},
   {"ic":"fork","t":"Use ou Esgote","emph":"Use ou Esgote","b":"Toda crítica é uma de duas coisas: aviso útil (guarde) ou truque (drene). Perguntar separa as duas. <strong>Ao investigar em vez de se defender, você dissolve a moldura “você está errado”</strong> — exatamente a moldura com que tentavam te conduzir.","tip":"<strong>Como aplicar:</strong> não pare na primeira reclamação vaga — continue pedindo o detalhe até a informação real cair na mesa."},
   {"ic":"link","t":"Treina o Outro a Ser Direto","emph":"Ser Direto","b":"Repetir, sem agressão, “o que você quer de verdade?” educa os mais próximos a declarar o desejo em vez de manipular — <strong>troca o emburramento e a indireta por um pedido honesto, que dá para negociar de igual para igual</strong>.","tip":"<strong>Cuidado:</strong> o tom tem de ser curiosidade de verdade. Com uma pitada de sarcasmo, a pergunta deixa de investigar e vira faísca de briga."},
   {"ic":"target","t":"Corra para a Crítica","emph":"Corra para a Crítica","b":"Vá em direção à crítica como quem aspira, não como quem foge: <strong>“me conta mais o que ficou ruim no que eu fiz”</strong>. Quem corre para a crítica tira dela o poder de ferir e o serviço de alavanca — ela só machuca quem se encolhe.","tip":"<strong>Modelo mental:</strong> é depurar a relação — persiga o problema raiz até encontrá-lo, em vez de remendar o sintoma que apareceu primeiro."},
  ],
  "lessons_title":"Lições-Chave do Capítulo VII",
  "lessons":[
   "Chame a crítica em vez de fugir dela: aproveite o que for útil, esgote o que for truque.",
   "Insista no detalhe até o desejo verdadeiro do outro vir à tona.",
   "Perguntar treina quem está perto de você a ser direto, no lugar de manipular.",
   "Tom de curiosidade sincera; com sarcasmo, a investigação vira mais uma briga.",
  ],
 },
 {
  "slug": "ch08-situacoes-comerciais",
  "sub": "CAPÍTULO VIII: Situações Comerciais — Onde Há Dinheiro Envolvido",
  "intro": "Onde há dinheiro na mesa — reembolso, conserto, vendedor insistente, mau atendimento —, ganha quem empilha as técnicas. Disco Riscado para não soltar a corda, Banco de Névoa para absorver os desvios. Com uma fronteira honesta: o que você assinou ou aceitou de véspera, isso a assertividade não desfaz; ela serve para tudo o que ainda está em aberto.",
  "cards": [
   {"ic":"wrench","t":"A Pilha de Enfrentamento","emph":"Pilha de Enfrentamento","b":"Empilhe as ferramentas: <strong>Disco Riscado + Banco de Névoa + Acordo Viável + subir a escada com calma</strong> até alguém que possa dizer sim. Declare o desejo, repita-o, deixe escorrer os desvios de “política” e de culpa, e negocie só uma coisa — o dinheiro.","tip":"<strong>Como aplicar:</strong> “é a nossa política” não é uma parede, é um desvio gratuito. Dê Banco de Névoa nele (“entendo que seja a política”) e volte ao seu desejo.","wide":True},
   {"ic":"book","t":"Prévio × Renegociável","emph":"Prévio","b":"O que estava assinado ou afixado e foi aceito de antemão costuma valer — é o pneu já rodado. Mas defeito e mau atendimento são justos de cobrar. <strong>Tentar passar por cima de um acordo real parece teimosia, e perde.</strong> Saiba de que lado dessa linha você está antes de subir o tom.","tip":"<strong>Sinal de alerta:</strong> discutir o mérito (“mas é injusto que…”) em vez de repetir o desejo entrega ao funcionário todos os ângulos para te recusar.","warn":True},
   {"ic":"steps","t":"Suba até Quem Pode Dizer Sim","emph":"Quem Pode Dizer Sim","b":"Antes de gastar fôlego, pergunte: “quem aqui pode, de fato, me conceder isso?” — e leve o Disco Riscado até essa pessoa. <strong>Não aceite o “não” de quem nem teria autoridade para dizer sim:</strong> negar é a única coisa que esse alguém pode fazer.","tip":"<strong>Como aplicar:</strong> ceda no dinheiro com o Acordo Viável; o tratamento respeitoso, esse não entra na conta."},
   {"ic":"bubble","t":"Vendedor: Sem Explicação","emph":"Sem Explicação","b":"Ao vendedor de porta ou de telefone você não deve uma só razão (Direito II): “não tenho interesse”, repetido, encerra o assunto. <strong>E do outro lado do balcão, dar Banco de Névoa a um cliente furioso baixa a tensão sem você abrir mão das regras.</strong>","tip":"<strong>Regra:</strong> persista e enevoe os desvios — em nenhum momento entre no mérito da venda."},
  ],
  "lessons_title":"Lições-Chave do Capítulo VIII",
  "lessons":[
   "Persista (Disco Riscado), enevoe os desvios (Banco de Névoa) e suba até quem pode conceder.",
   "Vendedor não tem direito à sua explicação — “não tenho interesse”, repetido, basta.",
   "Negocie cifras com o Acordo Viável; o tratamento respeitoso fica fora da negociação.",
   "Contra um acordo real firmado antes, a assertividade não vale — honre os termos que você aceitou.",
  ],
 },
 {
  "slug": "ch09-situacoes-autoridade",
  "sub": "CAPÍTULO IX: Situações de Autoridade — Supervisão e Especialização",
  "intro": "A autoridade existe e é real — mas tem cerca. O chefe manda na tarefa; o especialista manda no domínio dele. Nenhum dos dois manda em você como pessoa. O jogo aqui é enxergar a cerca: cooperar lá dentro, impor-se lá fora, e não deixar passar a manipulação que sempre tenta entrar de carona na ordem legítima.",
  "cards": [
   {"ic":"person","t":"Autoridade é Limitada","emph":"Limitada","b":"Faça uma pergunta antes de obedecer ou reagir: “a autoridade dela cobre mesmo isto?”. Cumpra a parte legítima sem drama; imponha-se contra o excesso. <strong>Enevoe a crítica justa ao seu trabalho e use o Disco Riscado no que extrapola a função.</strong>","tip":"<strong>Modelo mental:</strong> desenhe um círculo em volta do cargo. Dentro dele, coopere. Fora (sua vida privada, o seu valor), o cargo não tem jurisdição — imponha-se.","wide":True},
   {"ic":"target","t":"Entrevista Assertiva","emph":"Entrevista Assertiva","b":"Antecipe o seu próprio nervoso com Asserção Negativa e Interrogação Negativa: <strong>“eu costumo ficar um pouco nervoso em entrevista — isso atrapalha?”</strong>. Confessar a fraqueza a desarma, e quem confessa sem medo soa, paradoxalmente, confiante.","tip":"<strong>Sinal de alerta:</strong> demonstrar dúvida sobre habilidades miúdas faz de você, aos olhos de quem contrata, uma dor de cabeça anunciada."},
   {"ic":"link","t":"A Linha do Cargo","emph":"Linha do Cargo","b":"Dá para entregar o que o cargo pede e, no mesmo gesto, recusar ser diminuído como pessoa — as duas coisas cabem juntas. <strong>Pai e professor também põem limites e recebem reclamação com Banco de Névoa, em vez de entrar na guerra das justificativas.</strong>","tip":"<strong>Exemplo:</strong> “você pode ter razão que é arriscado — e como eu passo as minhas noites é decisão minha.”"},
   {"ic":"sword","t":"Não se Justifique ao Chefe","emph":"Não se Justifique","b":"Justificar-se à autoridade é pedir mais supervisão de presente. <strong>E esconder o nervoso na entrevista só o aumenta</strong> — revele-o e siga, em vez de queimar energia disfarçando o que todos percebem mesmo.","tip":"<strong>Cuidado:</strong> o vazamento mais perigoso é o da autoridade do cargo escorrendo para a sua vida — um chefe ditando o seu particular, e você obedecendo sem questionar.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo IX",
  "lessons":[
   "A autoridade só cobre a área da função — coopere ali dentro, imponha-se para fora dela.",
   "Confesse o nervoso da entrevista logo de cara; assumir, sem medo, soa como força.",
   "Enevoe a crítica justa ao trabalho; use o Disco Riscado no que mira você como pessoa.",
   "Justificar-se à autoridade é convidar mais supervisão para a sua mesa.",
  ],
 },
 {
  "slug": "ch10-situacoes-iguais",
  "sub": "CAPÍTULO X: Situações entre Iguais — Amigos, Vizinhos, Família",
  "intro": "Entre iguais não há estrutura externa atrás da qual o outro se esconda — então a manipulação corre quase toda pela culpa e pela dívida moral: “depois de tudo que eu fiz por você…”, “um amigo de verdade faria isso”. É aqui que os direitos mais pesam, sobretudo dois: o de dizer não e o de não dever razão a ninguém.",
  "cards": [
   {"ic":"fork","t":"Dizer “Não” a um Par","emph":"Não","b":"Disco Riscado mais Direito II — sem razões. Quando insistirem, <strong>não justifique (toda razão é uma porta que você abre para a réplica)</strong>: “entendo que você precise, e não”. Repita. Enevoe a culpa: “você pode achar isso egoísmo — e a resposta continua não”.","tip":"<strong>Regra:</strong> sem razão não há gancho. O “não” pelado, sem explicação amarrada, é irrespondível.","wide":True,"det":"<blockquote>— “Mas você nem vai usar o carro hoje!” — “É verdade, e mesmo assim prefiro não.” — “Pensei que a gente fosse amigo.” — “Somos, e a resposta continua não.”</blockquote>"},
   {"ic":"sword","t":"A Alavanca da Culpa","emph":"Alavanca da Culpa","b":"Entre pares, a culpa é a ferramenta-mestra: “eu faria isso por você”, “você mudou”, “um amigo de verdade faria”. <strong>Reconheça o golpe, enevoe a moldura moral e não saia da linha</strong> — relação de verdade sobrevive a um não; a que desmorona com ele não era amizade, era contrato de obediência.","tip":"<strong>Sinal de alerta:</strong> no segundo em que você compra o “um amigo de verdade faria…”, já perdeu — isso é a manipulação falando, não um fato sobre amizade.","warn":True},
   {"ic":"shield","t":"O Direito VII na Prática","emph":"Direito VII","b":"Você não precisa da aprovação deles para poder lidar com eles — <strong>dá para voltar a ser querido depois de ter dito não</strong>, e quase sempre se volta. Pai intrometido se recusa com as mesmas técnicas: gentileza no tom, firmeza na linha.","tip":"<strong>Como aplicar:</strong> com gente próxima, decida a sua linha antes de a conversa começar — e espere a culpa entrar em cena, porque ela vem."},
   {"ic":"link","t":"Não Explique o seu “Não”","emph":"Não Explique","b":"Cada razão que você dá a um amigo é uma munição que você entrega para ele atirar de volta. <strong>E ceder só para a culpa parar ensina, a quem está perto, que a culpa funciona com você</strong> — e ele vai recarregar. Recuse com um “não” simples e seco.","tip":"<strong>Regra:</strong> o nome do jogo é um só — não dar gancho."},
  ],
  "lessons_title":"Lições-Chave do Capítulo X",
  "lessons":[
   "Com pares, recuse com um “não” simples e não dê razões (Direito II).",
   "A culpa é a manipulação-rainha entre iguais — nomeie-a, enevoe-a e segure a linha.",
   "Você não precisa de aprovação antes de agir (Direito VII); o afeto costuma voltar depois.",
   "Ceder para a culpa cessar só ensina os próximos de que a culpa, com você, dá certo.",
  ],
 },
 {
  "slug": "ch11-desejos-sexuais",
  "sub": "CAPÍTULO XI: Afirmar os Desejos Sexuais — e a Questão Social",
  "intro": "Desejo sexual é um desejo diferente — mas o comportamento assertivo é, palavra por palavra, o mesmo: dizer o que se quer, recusar o que não se quer, negociar um meio-termo viável, mostrar-se sem vergonha. Boa parte da dificuldade na cama não vem do corpo: vem da passividade e da manipulação que entram, caladas, debaixo dos lençóis.",
  "cards": [
   {"ic":"person","t":"Mesmas Técnicas, Terreno Carregado","emph":"Mesmas Técnicas","b":"Autorrevelação, Interrogação Negativa e Acordo Viável, agora aplicados ao sexo: diga seus desejos e seus receios sem rodeio; investigue os do outro; <strong>negocie os atos (material) à vontade, e o autorrespeito nunca</strong>. Dizer não a uma investida é o mesmíssimo enfrentamento de qualquer outra manipulação.","tip":"<strong>A ideia do livro:</strong> não há intimidade saudável sem assertividade — saber se afirmar vem antes de saber se entregar.","wide":True},
   {"ic":"eye","t":"Agendas Ocultas de Ansiedade","emph":"Agendas Ocultas","b":"Medos não ditos sobre mudar se travestem de preferência; revelá-los é o que os traz para a luz, onde dá para negociá-los. <strong>Dar indireta em vez de declarar o desejo — e depois guardar mágoa porque o outro não adivinhou — é o antipadrão clássico.</strong>","tip":"<strong>Como aplicar:</strong> a Interrogação Negativa troca o emburramento e a indireta por desejos finalmente ditos em voz alta."},
   {"ic":"scale","t":"Negocie os Atos, Não a Dignidade","emph":"Não a Dignidade","b":"Os atos sexuais se negociam à larga; uma exigência que cobra o seu valor próprio não se negocia jamais. <strong>A manipulação na cama — culpa, “mágoa”, acusação — é a mesma alavanca de qualquer outro lugar</strong>, só que num terreno mais delicado. Reconheça, e responda igual.","tip":"<strong>Sinal de alerta:</strong> ceder em silêncio, ou ceder à manipulação, é rota documentada para a própria disfunção que se temia."},
   {"ic":"constellation","t":"A Questão Social","emph":"Questão Social","b":"Quando perguntam a Smith o que seria do mundo se muitos virassem assertivos, ele responde com a honestidade do livro inteiro: não sei. Seu foco está nos dois extremos — o indivíduo e a espécie — e na menor célula social de todas: <strong>duas pessoas resolvendo a briga pelo tema da briga, e não por quem manipula melhor</strong>.","tip":"<strong>Fecho:</strong> a obra inteira mira uma só coisa — decidir o conflito pelos fatos da disputa, nunca pela força relativa de duas personalidades."},
  ],
  "lessons_title":"Lições-Chave do Capítulo XI",
  "lessons":[
   "O desejo sexual é outro, mas o comportamento assertivo — revelar, investigar, negociar os atos — é idêntico.",
   "Passividade e manipulação movem boa parte da dificuldade sexual, mais que o corpo.",
   "Revele as ansiedades escondidas e provoque os desejos reais do outro com a Interrogação Negativa.",
   "Negocie os atos à vontade; a dignidade, nunca.",
  ],
 },
]
