# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas do livro 'Quando Digo Não, Me Sinto Culpado'
(Manuel J. Smith) para a biblioteca. Termos canônicos: Disco Riscado,
Banco de Névoa, Asserção Negativa, Interrogação Negativa, Informação Gratuita,
Autorrevelação, Acordo Viável."""

CHAPTERS = [
 {
  "slug": "ch01-sobrevivencia",
  "sub": "CAPÍTULO I: Sobrevivência e as Raízes da Não Assertividade",
  "intro": "O conflito entre pessoas é inevitável. Nossas respostas herdadas são luta ou fuga — mas o ser humano tem uma terceira, superior: a assertividade verbal. A maioria de nós é não assertiva porque, na infância, foi treinada a obedecer por ansiedade, ignorância e culpa.",
  "cards": [
   {"ic":"fork","t":"Luta, Fuga ou Palavra","b":"As três respostas ao conflito. Luta (agressão) e fuga (evitação) são <strong>reflexos primitivos de sobrevivência</strong>; a solução verbal é a alternativa humana e eficaz. Troque o reflexo de atacar ou se retirar por um enfrentamento <strong>calmo e persistente</strong>.","tip":"<strong>Modelo mental:</strong> luta e fuga são o réptil que sobrou; a assertividade é o córtex fazendo o que só o humano consegue."},
   {"ic":"sword","t":"As 3 Alavancas Emocionais","b":"Como a criança — e depois o adulto — fica manipulável: <strong>Ansiedade</strong> (“se não fizer X, algo ruim acontece”), <strong>Ignorância</strong> (“você não sabe o bastante, deixe a autoridade decidir”) e <strong>Culpa</strong> (“se fizer X, você é mau”). O “me sinto culpado” do título é esta última.","tip":"<strong>Sinal de alerta:</strong> uma onda súbita de culpa, ansiedade ou autodúvida num conflito é uma alavanca sendo puxada — não informação sobre a realidade.","warn":True},
   {"ic":"mask","t":"O que é Manipulação","b":"Qualquer tentativa indireta de controlar seu comportamento <strong>mexendo nas suas emoções</strong>, em vez de declarar um desejo às claras. Os pais <em>podem</em> impor limites sem gerar ansiedade, ignorância ou culpa — a maioria não o faz, criando adultos passivos e manipuláveis.","tip":"<strong>Como aplicar:</strong> a não assertividade é aprendida; logo, pode ser desaprendida."},
   {"ic":"scale","t":"O Placar é o Autorrespeito","b":"O ganho da assertividade é interno: o <strong>autorrespeito</strong>, preservado mesmo quando você não alcança o objetivo material. Conseguir o que quer é um bônus frequente — <strong>não a medida do sucesso</strong>.","tip":"<strong>Regra:</strong> tentar nunca desagradar ninguém garante manipulação. O conflito não se evita; só se escolhe a resposta."},
  ],
  "lessons_title":"Lições-Chave do Capítulo I",
  "lessons":[
   "Você não pode evitar o conflito; só pode escolher luta, fuga ou assertividade.",
   "A não assertividade é aprendida — via ansiedade, ignorância e culpa — e por isso pode ser desaprendida.",
   "O objetivo é o autorrespeito primeiro; vencer é bônus, não a régua.",
   "Agressão não é assertividade — a luta ainda é um reflexo de sobrevivência.",
  ],
 },
 {
  "slug": "ch02-direito-primario",
  "sub": "CAPÍTULO II: O Direito Primário e Como Somos Manipulados",
  "intro": "Toda assertividade deriva de um direito primário: você é o juiz supremo de si mesmo. A manipulação funciona ao fazer você entregar essa autoridade de juiz a regras, estruturas e “deverias” que o manipulador controla.",
  "cards": [
   {"ic":"target","t":"Você é o Seu Juiz (Direito I)","b":"“Você tem o direito de julgar seu próprio comportamento, pensamentos e emoções, e de assumir a responsabilidade por sua iniciativa e consequências.” Você pode ouvir os outros, mas <strong>o veredito sobre você é seu</strong>. Todos os demais direitos derivam deste.","tip":"<strong>Como aplicar:</strong> quando ouvir “você deveria”, traduza para “<em>eu</em> preferiria que você…” — devolvendo a frase a um mero desejo, que você aceita ou recusa.","wide":True},
   {"ic":"book","t":"A Estrutura Externa","b":"A ferramenta básica do manipulador: invocar <strong>regras, normas, lógica</strong> ou “o jeito que as coisas se fazem” como se isso decidisse seu comportamento por você (“todo mundo sabe que você deveria…”). Você não é obrigado a viver por estruturas que não aceitou.","tip":"<strong>Sinal de alerta:</strong> um argumento “lógico” sobre o que você deveria fazer ainda é só a preferência de outra pessoa fantasiada.","warn":True},
   {"ic":"fork","t":"Os 3 Tipos de Interação","b":"Para saber quanto pode se impor: <strong>Comercial</strong> (troca explícita; contratos prévios obrigam; menor margem); <strong>Autoridade</strong> (poder legítimo só sobre uma área definida, não sobre você como pessoa); <strong>Igual</strong> (sem estrutura externa; assertividade plena).","tip":"<strong>Regra:</strong> classifique a interação antes de reagir — a margem cresce de comercial → autoridade → igual."},
   {"ic":"sword","t":"Ferramentas Amorais","b":"As habilidades assertivas são <strong>amorais</strong> — como dirigir um carro, servem para o bem ou para o mal. Ser seu próprio juiz significa que <strong>você responde pelo uso</strong> que faz delas.","tip":"<strong>Cuidado:</strong> a assertividade não derruba um contrato prévio genuíno (o pneu já rodado) — tentar parece tolice."},
  ],
  "lessons_title":"Lições-Chave do Capítulo II",
  "lessons":[
   "Você é o seu juiz supremo — é o direito sobre o qual todos os outros se apoiam.",
   "Manipulação = transferir a autoridade de juiz para a estrutura externa; assertividade = mantê-la.",
   "Classifique a interação (comercial / autoridade / igual) para saber o quanto pode se impor.",
   "As habilidades são amorais — você responde por como as usa.",
  ],
 },
 {
  "slug": "ch03-dez-direitos",
  "sub": "CAPÍTULO III: Os Dez Direitos Assertivos",
  "intro": "Nove direitos do cotidiano estendem o direito primário às manipulações do dia a dia. Cada direito tem uma crença manipulativa como imagem espelhada: conhecer o direito pelo nome permite recusar a crença na hora.",
  "cards": [
   {"ic":"book","t":"A Carta de Direitos Assertivos","b":"Os dez direitos — cada um anula um “deveria” manipulativo:","list":[
     "<strong>I.</strong> Julgar o próprio comportamento, pensamentos e emoções, e responder por eles.",
     "<strong>II.</strong> Não dar razões nem desculpas para se justificar.",
     "<strong>III.</strong> Julgar se você é responsável por resolver os problemas dos outros.",
     "<strong>IV.</strong> Mudar de ideia.",
     "<strong>V.</strong> Cometer erros — e se responsabilizar por eles.",
     "<strong>VI.</strong> Dizer “não sei”.",
     "<strong>VII.</strong> Ser independente da boa vontade alheia antes de lidar com ela.",
     "<strong>VIII.</strong> Ser ilógico ao tomar decisões.",
     "<strong>IX.</strong> Dizer “não entendi”.",
     "<strong>X.</strong> Dizer “não me importo”.",
    ],"tip":"<strong>Como aplicar:</strong> sob pressão, pergunte em silêncio “qual direito está sendo negado aqui?”. Nomeá-lo vira posição clara.","wide":True},
   {"ic":"target","t":"Os Dois Mais Potentes","b":"<strong>Direito II</strong> (nenhuma razão nem desculpa): toda razão que você dá vira um gancho para o outro discutir. <strong>Direito VII</strong> (independência da boa vontade): você não precisa que gostem de você <em>antes</em> de poder lidar com eles — pode ser querido de novo <em>depois</em> do não.","tip":"<strong>Regra:</strong> no instante em que você se justifica (viola o II), convida o manipulador a refutar suas razões e reabrir o conflito."},
   {"ic":"pivot","t":"O Direito de Ser Ilógico (VIII)","b":"Desejos e sentimentos <strong>não precisam passar num teste de lógica</strong>; “porque eu quero” é uma razão completa para si mesmo. Você também pode mudar de ideia (IV) — ideias e circunstâncias mudam.","tip":"<strong>Sinal de alerta:</strong> trate “mas isso não é lógico / justo / legal” como uma alavanca, não um xeque-mate."},
   {"ic":"scale","t":"Direito ↔ Crença Manipulativa","b":"Todo direito tem uma sombra: <strong>III</strong> ↔ “você tem de me ajudar”; <strong>V</strong> ↔ “errar é vergonhoso”; <strong>VI–IX</strong> ↔ “um adulto competente sempre sabe/entende”; <strong>X</strong> ↔ “você tem de se importar com o que penso”.","tip":"<strong>Como aplicar:</strong> recuse a crença afirmando o direito correspondente."},
  ],
  "lessons_title":"Lições-Chave do Capítulo III",
  "lessons":[
   "Memorize os dez direitos — cada um é uma resposta pronta a uma manipulação comum.",
   "“Nenhuma razão nem desculpa” (II) e “independência da boa vontade” (VII) desarmam a maior parte da pressão.",
   "Todo direito tem uma crença manipulativa como sombra; recuse a crença afirmando o direito.",
   "Adotar o problema do outro como seu (violando o III) costuma ser culpa, não dever.",
  ],
 },
 {
  "slug": "ch04-disco-riscado",
  "sub": "CAPÍTULO IV: Persistência — Disco Riscado e Acordo Viável",
  "intro": "A primeira técnica verbal é a persistência: repetir com calma o que você quer até o outro lado esgotar os “nãos”. Você perde a maioria dos conflitos não por estar errado, mas por desistir depois da primeira recusa.",
  "cards": [
   {"ic":"spiral","t":"Disco Riscado (Broken Record)","b":"Repetição calma do seu desejo, sem ensaiar argumentos nem acumular raiva. <strong>(1)</strong> decida o desejo em uma frase; <strong>(2)</strong> reconheça brevemente cada objeção e <strong>repita</strong> sem mudar a essência; <strong>(3)</strong> não responda a desvios nem “lógica irrelevante”; <strong>(4)</strong> tom no mesmo nível.","tip":"<strong>Por que funciona:</strong> a maioria tem poucos “nãos” no bolso. “Se ele tem três, você só precisa de quatro.”","wide":True,"det":"<blockquote>“É contra a política.” — “Vejo que é a política, e quero meu dinheiro de volta.” “Você usou.” — “É verdade, e quero meu dinheiro de volta.” Sem raiva, sem novos argumentos: só o sulco, até esgotarem os nãos.</blockquote>"},
   {"ic":"scale","t":"Os Dois Placares","b":"Separe o <strong>objetivo material</strong> (negociável; ceda à vontade) do <strong>autorrespeito</strong> (inegociável; nunca ceda). Perder o objetivo material mantendo o autorrespeito <strong>é uma vitória</strong>.","tip":"<strong>Modelo mental:</strong> imagine um disco riscado de verdade — mesmo sulco, mesma frase, repetição sem emoção: entediante, inabalável, eficaz."},
   {"ic":"link","t":"Acordo Viável (Workable Compromise)","b":"Sempre que o autorrespeito <strong>não</strong> estiver em jogo, ofereça um acordo prático no objetivo material (“metade agora, metade na sexta”). Você sempre pode negociar <em>coisas</em>.","tip":"<strong>Regra dura:</strong> se o objetivo toca o autovalor, <strong>não há acordo</strong> — cedê-lo é derrota disfarçada de vitória."},
   {"ic":"sword","t":"O Erro Nº 1: Desistir","b":"Desistir <strong>depois do primeiro “não”</strong> é a razão mais comum pela qual a pessoa não assertiva perde. A persistência vence o argumento: você não precisa de uma lógica melhor, só de mais fôlego.","tip":"<strong>Sinal de alerta:</strong> ser puxado para o assunto paralelo que o manipulador levanta, em vez de repetir o seu desejo.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo IV",
  "lessons":[
   "Defina um desejo claro e repita-o com calma; ignore todo desvio.",
   "As pessoas têm “nãos” limitados — seja mais persistente sem discutir.",
   "Negocie à vontade os objetivos materiais; nunca o autorrespeito.",
   "Contra um contrato prévio genuíno você pode perder — e tudo bem, o autorrespeito era a vitória.",
  ],
 },
 {
  "slug": "ch05-conversa-assertiva",
  "sub": "CAPÍTULO V: Conversa Assertiva — Informação Gratuita e Autorrevelação",
  "intro": "A assertividade não serve só para o conflito; ela torna a conversa comum fácil e à prova de manipulação. Duas técnicas fazem o trabalho — perceber a informação que o outro oferece e revelar os próprios altos e baixos sem vergonha — amparadas por um contato visual firme.",
  "cards": [
   {"ic":"bubble","t":"Informação Gratuita (Free Information)","b":"Reconhecer as pequenas <strong>deixas não solicitadas</strong> que a pessoa oferece sobre o que lhe importa — e desdobrá-las. Escute o detalhe oferecido (“…depois que voltei da viagem…”) e pergunte sobre <em>aquilo</em>.","tip":"<strong>Como aplicar:</strong> trate cada resposta como uma sacola de informação gratuita — puxe um fio e a conversa anda sozinha."},
   {"ic":"person","t":"Autorrevelação (Self-Disclosure)","b":"Falar livremente dos seus lados <strong>positivos e negativos</strong> — comportamento, estilo de vida, opiniões — para aprofundar a comunicação e <strong>matar a manipulação de fome</strong>. Ofereça você mesmo o que normalmente esconderia, sem pedir desculpa.","tip":"<strong>Modelo mental:</strong> o que você revela não pode ser usado como arma — não há o que “expor” se você já disse."},
   {"ic":"eye","t":"Congruência Não Verbal","b":"As palavras dizem uma coisa, o corpo diz outra — as pessoas acreditam no <strong>corpo</strong>. O sinal mais claro de ansiedade é a <strong>falta de contato olho a olho</strong>; o nervosismo visível faz os outros te tolerarem em vez de honrar seus combinados.","tip":"<strong>Sinal de alerta:</strong> dizer as palavras confiantes desviando o olhar — o que chega é o nervosismo.","warn":True},
   {"ic":"book","t":"Revelação como Armadura","b":"Segredos são <strong>munição</strong>; assumir abertamente seus defeitos remove a alavanca. Esconder os negativos preserva exatamente as ansiedades (ignorância, culpa) que tornam você manipulável.","tip":"<strong>Cuidado:</strong> interrogatório não é conversa — siga a informação oferecida em vez de disparar perguntas prontas."},
  ],
  "lessons_title":"Lições-Chave do Capítulo V",
  "lessons":[
   "Siga a informação gratuita que as pessoas oferecem; isso tira a timidez e conduz a conversa.",
   "Revele seus positivos e negativos abertamente — o que você revela não vira arma.",
   "Mantenha o contato visual; a ansiedade não verbal anula qualquer palavra assertiva.",
   "A revelação desmonta as alavancas de ignorância e culpa aprendidas na infância.",
  ],
 },
 {
  "slug": "ch06-lidar-com-critica",
  "sub": "CAPÍTULO VI: Lidando com a Crítica — Banco de Névoa e Asserção Negativa",
  "intro": "A crítica é o grande manipulador. Duas técnicas a neutralizam tirando a briga: concorde com qualquer verdade ou possibilidade que ela contenha, continue seu próprio juiz e não dê ao crítico manipulativo nada em que se apoiar.",
  "cards": [
   {"ic":"layers","t":"Banco de Névoa (Fogging)","b":"Reconhecer com calma a <strong>probabilidade</strong> de haver algo de verdade numa crítica, sem deixar de ser o juiz do que você faz. Três movimentos: concorde com a <strong>verdade</strong> (“tem razão, estou atrasado”), com a <strong>probabilidade</strong> (“você pode ter razão”) ou com o <strong>princípio</strong> (“se eu fizesse isso, você teria um ponto”).","tip":"<strong>Por que funciona:</strong> como a névoa, você não oferece parede sólida — as farpas atravessam, você fica imóvel e a crítica não recebe recompensa.","wide":True},
   {"ic":"person","t":"Asserção Negativa (Negative Assertion)","b":"Quando você está <strong>de fato errado</strong> (mesmo 100%), concorde de forma firme e solidária com a crítica — <strong>sem pedir desculpas</strong>. “Você tem razão, isso foi um descuido meu.”","tip":"<strong>Regra:</strong> quando errou de verdade, concorde mais que o crítico (“foi burrice minha”) — encerra o ataque mais rápido que qualquer defesa."},
   {"ic":"scale","t":"Elogio = Crítica","b":"Para o assertivo, elogio e crítica são <strong>a mesma coisa</strong>: apenas o julgamento alheio. Receba qualquer um com a mesma calma, continuando seu próprio juiz. A crítica é informação que você pode usar ou descartar — não um veredito sobre seu valor.","tip":"<strong>Como aplicar:</strong> estas técnicas deixam você olhar para os próprios negativos sem ansiedade e sem mentir sobre um erro real."},
   {"ic":"sword","t":"Não se Defenda, Não Negue","b":"Defender-se ou negar transforma <strong>uma única crítica num debate</strong> que o manipulador pode vencer. Pedir desculpa por ser humano (excesso de desculpas) também perde.","tip":"<strong>Sinal de alerta:</strong> tratar a crítica como veredito sobre seu valor, em vez de informação a usar ou descartar.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo VI",
  "lessons":[
   "Concorde com a verdade, a probabilidade ou o princípio — a névoa não dá ao crítico nada para empurrar.",
   "Quando errado, assuma com firmeza e sem desculpas (Asserção Negativa); isso desarma a raiva.",
   "Elogio e crítica são a mesma coisa quando você continua seu próprio juiz.",
   "Concordar com calma extingue o reforço da crítica manipulativa — ela se apaga.",
  ],
 },
 {
  "slug": "ch07-interrogacao-negativa",
  "sub": "CAPÍTULO VII: Estimulando o Outro — Interrogação Negativa",
  "intro": "A última técnica central inverte o medo da crítica: você a pede ativamente. A Interrogação Negativa puxa a crítica para garimpar o que houver de útil e esgotar o que for manipulativo — treinando o outro a abandonar os truques e falar com honestidade.",
  "cards": [
   {"ic":"lens","t":"Interrogação Negativa (Negative Inquiry)","b":"Provocar ativamente a crítica a si mesmo: pergunte, com calma e repetidamente, por mais — “o que tem no meu fazer X que te incomoda?”, “o que mais?” — até o problema real vir à tona ou a crítica fabricada secar.","tip":"<strong>Por que funciona:</strong> a crítica manipulativa depende de ficar vaga; exigir detalhes ou rende informação genuína ou esvazia a sacola.","wide":True,"det":"<blockquote>— “Tá, faz o que você quiser.” — “Vejo que você está chateado; o que tem no meu sair que te incomoda?” — “Nada.” — “Parece que tem algo; o que especificamente?” Pressionado com honestidade, surge o desejo real: “queria que a gente jantasse junto”.</blockquote>"},
   {"ic":"scale","t":"Use ou Esgote","b":"Toda crítica é <strong>feedback útil</strong> (guarde) ou <strong>um truque</strong> (drene) — a investigação separa os dois. Ao investigar em vez de se defender, você dissolve o enquadramento de “você está errado” usado para te controlar.","tip":"<strong>Como aplicar:</strong> continue pedindo detalhes até a informação real aparecer; não pare na primeira reclamação vaga."},
   {"ic":"link","t":"Treina o Outro a Ser Direto","b":"Perguntar repetidamente “o que você realmente quer?” <strong>ensina os íntimos</strong> a declarar desejos diretamente, em vez de manipular — substituindo o emburramento e a indireta por pedidos honestos que dá para negociar.","tip":"<strong>Cuidado:</strong> o tom precisa ser curiosidade genuína; com sarcasmo, vira uma nova briga."},
   {"ic":"target","t":"Corra para a Crítica","b":"Corra <em>em direção</em> à crítica como um <strong>aspirador</strong>, não para longe dela: “me conta mais o que está errado no que eu fiz” tira o poder de ferir e o uso como alavanca.","tip":"<strong>Modelo mental:</strong> é depurar a relação — continue perguntando até achar o bug real, em vez de remendar sintomas."},
  ],
  "lessons_title":"Lições-Chave do Capítulo VII",
  "lessons":[
   "Convide a crítica ativamente — use o que for útil, esgote o que for manipulativo.",
   "Continue pedindo detalhes até o desejo real aparecer.",
   "A investigação treina as pessoas próximas a serem diretas em vez de manipulativas.",
   "Tom de curiosidade genuína; com sarcasmo vira briga.",
  ],
 },
 {
  "slug": "ch08-situacoes-comerciais",
  "sub": "CAPÍTULO VIII: Situações Comerciais — Onde Há Dinheiro Envolvido",
  "intro": "Conflitos comerciais (reembolsos, consertos, vendedores, mau atendimento) são vencidos combinando as técnicas — sobretudo o Disco Riscado para persistir e o Banco de Névoa para absorver desvios — respeitando que contratos prévios genuínos não se desfazem de forma assertiva.",
  "cards": [
   {"ic":"wrench","t":"A Pilha de Enfrentamento","b":"Combine: <strong>Disco Riscado</strong> (declare e repita o desejo) + <strong>Banco de Névoa</strong> (neutralize desvios de “política”/culpa) + <strong>Acordo Viável</strong> (negocie o dinheiro) + escalar com calma até quem <strong>pode</strong> dizer sim.","tip":"<strong>Como aplicar:</strong> trate “é a nossa política” como desvio gratuito, não uma parede — dê Banco de Névoa e repita o desejo.","wide":True},
   {"ic":"book","t":"Prévio × Renegociável","b":"Um termo assinado ou afixado, combinado de antemão, em geral <strong>vale</strong> (o pneu já bem rodado). Já um <strong>defeito</strong> ou mau atendimento é justo de cobrar. Tentar se impor por cima de um contrato real parece tolice e perde.","tip":"<strong>Sinal de alerta:</strong> discutir o mérito em vez de repetir o desejo dá ao funcionário ângulos para recusar.","warn":True},
   {"ic":"steps","t":"Suba até Quem Pode Dizer Sim","b":"Pergunte <strong>“quem aqui pode de fato conceder o que quero?”</strong> e suba até essa pessoa com o Disco Riscado. Não aceite o primeiro “não” de alguém que de toda forma não tem autoridade para dizer sim.","tip":"<strong>Como aplicar:</strong> ceda só no dinheiro (Acordo Viável); nunca abra mão de um tratamento respeitoso."},
   {"ic":"bubble","t":"Vendedor: Sem Explicação","b":"Na venda de porta em porta ou por telefone, você não deve <strong>nenhuma razão</strong> (Direito II): “não tenho interesse”, repetido, basta. Como funcionário, dar Banco de Névoa num cliente raivoso (“o senhor pode ter razão de que está lento…”) reduz a tensão sem abrir mão das regras.","tip":"<strong>Regra:</strong> persista e dê Banco de Névoa nos desvios — sem argumentar o mérito."},
  ],
  "lessons_title":"Lições-Chave do Capítulo VIII",
  "lessons":[
   "Persista (Disco Riscado) e dê Banco de Névoa nos desvios; escale até quem pode conceder.",
   "Você não deve explicação a vendedor — “não tenho interesse”, repetido, encerra.",
   "Negocie dinheiro com o Acordo Viável; nunca abra mão de um tratamento respeitoso.",
   "Contra um contrato prévio real, a assertividade não vale — respeite os termos combinados.",
  ],
 },
 {
  "slug": "ch09-situacoes-autoridade",
  "sub": "CAPÍTULO IX: Situações de Autoridade — Supervisão e Especialização",
  "intro": "A autoridade é real, mas limitada: o chefe governa tarefas definidas, o especialista governa o seu domínio — nenhum governa você como pessoa. Imponha-se dentro do limite, separando a exigência legítima da manipulação que vem de carona.",
  "cards": [
   {"ic":"person","t":"Autoridade é Limitada","b":"Pergunte: <strong>“a autoridade dela cobre mesmo isto?”</strong>. Cumpra a parte legítima; imponha-se contra o excesso. Dê Banco de Névoa/Asserção Negativa à crítica válida ao seu <strong>trabalho</strong>; use o Disco Riscado no que está fora da função.","tip":"<strong>Modelo mental:</strong> desenhe uma linha em volta do cargo — dentro, coopere; fora (vida privada, seu valor), imponha-se.","wide":True},
   {"ic":"target","t":"Entrevista Assertiva","b":"Antecipe o próprio nervosismo com Asserção Negativa + Interrogação Negativa: <strong>“eu sempre fico um pouco nervoso em entrevista — isso vai atrapalhar?”</strong>. Assumir a fraqueza a desarma e soa como confiança.","tip":"<strong>Sinal de alerta:</strong> transmitir dúvida sobre habilidades menores faz você parecer uma dor de cabeça futura."},
   {"ic":"link","t":"A Linha do Cargo","b":"Você pode <strong>fazer o que o cargo exige</strong> e, ao mesmo tempo, <strong>recusar-se a ser diminuído</strong> como pessoa. Pais e professores também impõem limites e recebem reclamações com Banco de Névoa, em vez de batalhas de justificativa.","tip":"<strong>Exemplo:</strong> “você pode ter razão que é arriscado, e como passo minhas noites é decisão minha.”"},
   {"ic":"sword","t":"Não se Justifique ao Chefe","b":"Justificar-se à autoridade <strong>convida a mais supervisão</strong>. E esconder o nervosismo na entrevista só o amplifica — revele e siga em frente.","tip":"<strong>Cuidado:</strong> deixar a autoridade do cargo vazar para o controle pessoal (um chefe ditando sua vida privada) sem questionar.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo IX",
  "lessons":[
   "A autoridade cobre só uma área definida — coopere ali, imponha-se além dela.",
   "Revele o nervosismo da entrevista logo de cara; assumir soa como força.",
   "Dê Banco de Névoa na crítica válida ao trabalho; use o Disco Riscado no que mira você pessoalmente.",
   "Justificar-se à autoridade convida a mais supervisão.",
  ],
 },
 {
  "slug": "ch10-situacoes-iguais",
  "sub": "CAPÍTULO X: Situações entre Iguais — Amigos, Vizinhos, Família",
  "intro": "Com pares não há estrutura externa para se esconder, então a manipulação roda quase toda na culpa e na obrigação (“depois de tudo que fiz…”, “um amigo de verdade faria…”). É aqui que os direitos mais importam — em especial o de dizer não e o de não dar razões.",
  "cards": [
   {"ic":"fork","t":"Dizer “Não” a um Par","b":"Disco Riscado + Direito II (nenhuma razão). Quando insistirem, <strong>não dê razões</strong> (que convidam à réplica): “entendo que você precise, e não”. Repita. Dê Banco de Névoa na culpa (“você pode achar isso egoísmo — e não”).","tip":"<strong>Regra:</strong> sem razões = sem ganchos — o “não” sem justificativa é irrespondível.","wide":True,"det":"<blockquote>— “Mas você nem vai usar o carro hoje!” — “É verdade, e ainda assim prefiro não.” — “Pensei que a gente fosse amigo.” — “Somos, e a resposta continua não.”</blockquote>"},
   {"ic":"sword","t":"A Alavanca da Culpa","b":"A culpa é a <strong>ferramenta principal</strong> do manipulador-par: “eu faria por você”, “você mudou”, “um amigo de verdade faria”. Reconheça, dê Banco de Névoa no enquadramento moral e segure a linha — uma relação de verdade sobrevive a um não.","tip":"<strong>Sinal de alerta:</strong> comprar o enquadramento “um amigo de verdade faria…” — isso é a manipulação, não um fato sobre amizade.","warn":True},
   {"ic":"book","t":"O Direito VII na Prática","b":"Você <strong>não precisa da aprovação</strong> deles <em>antes</em> de poder lidar com eles — dá para ser querido de novo <em>depois</em> de ter dito não. Pais intrometidos podem ser recusados com as mesmas técnicas, com gentileza mas firmeza.","tip":"<strong>Como aplicar:</strong> com pares, decida sua linha antes da conversa — espere a alavanca da culpa como padrão."},
   {"ic":"link","t":"Não Explique o seu “Não”","b":"Toda razão que você dá a um amigo é <strong>algo para ele rebater</strong>. Ceder para acabar com a culpa só ensina os pares de que a culpa funciona com você.","tip":"<strong>Regra:</strong> recuse com um “não” simples; o nome do jogo é não dar gancho."},
  ],
  "lessons_title":"Lições-Chave do Capítulo X",
  "lessons":[
   "Com pares, recuse com um “não” simples e não dê razões (Direito II).",
   "A culpa é a principal manipulação entre pares — nomeie, dê Banco de Névoa, segure a linha.",
   "Você não precisa de aprovação antes de agir (Direito VII); o afeto pode voltar depois.",
   "Ceder para acabar com a culpa ensina os pares de que a culpa funciona com você.",
  ],
 },
 {
  "slug": "ch11-desejos-sexuais",
  "sub": "CAPÍTULO XI: Afirmar os Desejos Sexuais — e a Questão Social",
  "intro": "Desejos sexuais são desejos diferentes, mas o comportamento assertivo é exatamente o mesmo: declarar o que quer, recusar o que não quer, negociar acordos viáveis e revelar-se com abertura. A não assertividade e a manipulação são grandes causas ocultas de dificuldade sexual.",
  "cards": [
   {"ic":"person","t":"Mesmas Técnicas, Terreno Carregado","b":"Autorrevelação + Interrogação Negativa + Acordo Viável aplicados ao sexo: revele seus desejos e receios com clareza; investigue os do parceiro; negocie os <strong>atos</strong> (material), nunca o autorrespeito. Dizer não à sedução é o mesmo enfrentamento de qualquer manipulação.","tip":"<strong>Frase do livro:</strong> “primeiro a asserção, depois a inserção” — a assertividade é pré-requisito de uma relação sexual saudável.","wide":True},
   {"ic":"eye","t":"Agendas Ocultas de Ansiedade","b":"Medos não ditos sobre mudança se <strong>disfarçam de preferências</strong>; a revelação os traz à luz, onde podem ser negociados. Dar indiretas em vez de revelar um desejo — e depois se ressentir de o parceiro não ter adivinhado — é antipadrão.","tip":"<strong>Como aplicar:</strong> a Interrogação Negativa substitui o emburramento e a indireta por desejos ditos com honestidade."},
   {"ic":"scale","t":"Negocie os Atos, Não a Dignidade","b":"Negocie livremente os <strong>atos</strong> sexuais; uma exigência que custa seu <strong>autovalor</strong> é inegociável. A manipulação no sexo (culpa, “mágoa”, acusação) é a mesma alavanca de qualquer lugar — reconheça e use o mesmo enfrentamento.","tip":"<strong>Sinal de alerta:</strong> passividade silenciosa ou manipulação no sexo é rota documentada para a disfunção."},
   {"ic":"constellation","t":"A Questão Social","b":"Perguntado sobre o que aconteceria com a sociedade se muitos virassem assertivos, Smith responde com honestidade: <strong>“Não sei.”</strong> Sua preocupação está nos dois extremos — o <strong>indivíduo</strong> e a <strong>espécie</strong> — e na menor unidade social: duas pessoas resolvendo disputas pelos temas reais, não por quem manipula melhor.","tip":"<strong>Fecho:</strong> o objetivo de toda a obra é resolver o conflito pelos fatos da disputa, não pela força relativa das personalidades."},
  ],
  "lessons_title":"Lições-Chave do Capítulo XI",
  "lessons":[
   "Desejos sexuais são diferentes, mas o comportamento assertivo (revelar, investigar, negociar os atos) é idêntico.",
   "A não assertividade e a manipulação movem boa parte da dificuldade sexual.",
   "Revele as ansiedades ocultas; provoque os desejos reais do parceiro com a Interrogação Negativa.",
   "Negocie os atos; preserve sempre a dignidade.",
  ],
 },
]
