# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Sociedade do Cansaço' (Byung-Chul Han)."""

BOOK = {
  "title": "Sociedade do Cansaço",
  "author": "Byung-Chul Han",
  "header_light": "SOCIEDADE",
  "header_bold": "DO CANSAÇO",
  "subtitle": "VISÃO GERAL · O EXPLORADOR DE SI MESMO E A DOENÇA DO POSITIVO",
  "intro": "Não há mais senhor com chicote: o senhor agora mora dentro de você, e se chama 'você consegue'. A época abandonou o muro do 'é proibido' e ergueu, no lugar, o horizonte aberto do 'tudo é possível' — e foi aí que começou a sufocar. O sujeito de desempenho é livre e escravo na mesma pele: explora a si mesmo com a sensação de estar se realizando, e marcha sorrindo até implodir. Byung-Chul Han diagnostica a praga de uma era que adoeceu não do que lhe falta, mas do que tem em excesso. O burnout não é fracasso do sistema — é o sistema funcionando.",
  "description": "Ensaio filosófico de Byung-Chul Han sobre a virada da sociedade disciplinar (Foucault) para a sociedade do desempenho. A violência deixou de invadir de fora — vírus, inimigo, proibição — e passou a explodir de dentro, por excesso de positividade: burnout, depressão, TDAH, transtorno limítrofe. Han percorre a autoexploração que se confunde com liberdade, a multitarefa como regressão, a morte do tédio profundo e da atenção contemplativa, e aponta a única saída de uma doença feita de excesso: não mais desempenho, mas o cansaço fundamental de Handke, que em vez de isolar, reconcilia.",
  "tags": ["Filosofia", "Burnout", "Contemporâneo"],
  "progress": "8 Capítulos",
  "cover": "assets/sociedade-do-cansaco-cover.png",
  "overview_cards": [
    {"ic":"layers","t":"Do Dever ao Poder","b":"A sociedade <strong>disciplinar</strong> de Foucault governava pela proibição — o verbo era <strong>dever</strong>, e o muro do 'é proibido' marcava onde parar. A sociedade do <strong>desempenho</strong> governa pela permissão ilimitada — o verbo é <strong>poder</strong>, e o horizonte do 'tudo é possível' não tem onde parar. Tiramos o teto que pesava e descobrimos que o teto também protegia.","tip":"<strong>Modelo mental:</strong> o 'poder' não liberta menos que o 'dever' obrigava. A proibição punha um fim; a possibilidade infinita não deixa nunca de cobrar.","wide":True},
    {"ic":"person","t":"O Senhor e o Escravo na Mesma Pele","b":"Ninguém o açoita de fora — ele é <strong>empresário de si mesmo</strong> e produz mais que qualquer servo, porque trouxe o feitor para dentro. A luta deixou de ser contra o opressor e virou <strong>guerra contra si</strong>: quem explora e quem é explorado são a mesma pessoa, e por isso não há revolta possível — só implosão.","tip":"<strong>Como aplicar:</strong> quando não sobra nenhum chefe a quem culpar e mesmo assim você se cobra até o colapso, a coação já não vem de fora. Vem de você."},
    {"ic":"gap","t":"Os Dois Cansaços","b":"Há um cansaço que adoece e um cansaço que cura. O do desempenho <strong>separa, emudece e cega</strong> — esgotamento do eu que se fecha sozinho no próprio mutismo. O <strong>cansaço fundamental</strong> de Handke faz o contrário: afrouxa a tirania do ego, reabre os olhos para o mundo e <strong>reconcilia</strong>.","tip":"<strong>Sinal de alerta:</strong> aprenda a distinguir os dois pelo efeito. O cansaço que te isola e te cala é doença; o que te abre e te serena é convalescença."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-violencia-neuronal",
    "sub": "CAPÍTULO 1: A Violência Neuronal",
    "intro": "Cada época tem suas doenças, e a doença trai a verdade do tempo. O século XX foi imunológico: adoecíamos do Outro, do estranho que invadia — bactéria, vírus, inimigo. O século XXI é neuronal. Depressão, burnout, TDAH e transtorno limítrofe não são infecções; são enfartos. Não vêm de uma negatividade que ataca de fora, mas de um excesso de positividade que não cabe mais dentro.",
    "cards": [
      {"ic":"gap","t":"O Fim do Inimigo","emph":"Inimigo","b":"A defesa imunológica reage ao que é estranho — e por isso supõe sempre um Outro, uma fronteira, um inimigo a repelir. As doenças de hoje já não têm inimigo. <strong>Ninguém invadiu: o que adoece é o excesso do Mesmo, o Igual sem alteridade, que não provoca reação imune porque não vem de fora — apenas se acumula até saturar</strong>.","tip":"<strong>Modelo mental:</strong> pare de procurar o culpado que veio de fora. O esgotamento não é uma invasão a repelir; é uma sobrecarga do próprio, que nenhuma defesa identifica como ameaça."},
      {"ic":"bulb","t":"A Violência do Positivo","emph":"Positivo","b":"Estamos acostumados a pensar a violência como negatividade: alguém priva, proíbe, agride. Há, porém, uma violência que não nega nada. <strong>É a do positivo em excesso — informação demais, estímulo demais, desempenho demais —, que não fere a partir do estranho, mas adoece a partir do Igual, e por isso passa despercebida como mero efeito do progresso</strong>.","tip":"<strong>Prática:</strong> combater a exaustão com mais um aplicativo de produtividade é tratar a febre com brasa. O remédio do excesso nunca é mais do mesmo."},
      {"ic":"lens","t":"A Saturação do Mesmo","emph":"Saturação","b":"As fronteiras imunológicas que separavam dentro e fora caíram, e celebramos isso como abertura. Mas a abertura total tem um preço silencioso. <strong>Onde tudo passa e nada repele, o sistema perde a capacidade de dizer 'não' ao que o satura — e morre não de ataque, mas de incapacidade de recusar o demais</strong>.","tip":"<strong>Sinal de alerta:</strong> num mundo sem nenhuma barreira, a mente que não consegue mais dormir nem esquecer não está mais livre. Está exposta.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": ["A doença da época não vem da repressão, mas do excesso — não do Outro hostil, mas do Mesmo saturado.", "A violência neuronal (burnout, depressão) é positiva: não nega nem invade, sobrecarrega de dentro.", "Onde não há mais inimigo de fora, não há defesa imunológica possível — só implosão."],
  },
  {
    "slug": "ch02-alem-da-sociedade-disciplinar",
    "sub": "CAPÍTULO 2: Além da Sociedade Disciplinar",
    "intro": "Foucault descreveu uma sociedade de hospitais, prisões e fábricas, governada pelo dever e pela proibição — uma fábrica de loucos e delinquentes. Mas esse mundo já não é o nosso. A sociedade do desempenho aposentou as muralhas e os feitores; em seu lugar pôs academias, escritórios abertos e o imperativo de poder tudo. E passou a produzir uma população nova: depressivos e fracassados.",
    "cards": [
      {"ic":"sword","t":"A Promessa que Adoece","emph":"Promessa","b":"O dever da sociedade disciplinar tinha um limite: cumprida a ordem, encerrava-se a tarefa. O poder não conhece esse fim. <strong>O 'você consegue' parece libertar, mas é mais cruel que qualquer 'você deve' — porque ninguém termina nunca de poder mais, e cada teto alcançado revela apenas o próximo</strong>.","tip":"<strong>Para refletir:</strong> a proibição dava sossego ao cumpri-la. A possibilidade infinita não dá sossego nenhum — sempre houve algo a mais que você poderia ter feito."},
      {"ic":"person","t":"O Empresário de Si","emph":"Empresário","b":"O sujeito de desempenho dispensou o feitor porque o internalizou. <strong>Acredita-se livre justamente quando se explora, e explora-se com mais afinco do que qualquer patrão ousaria exigir, porque confunde a coação que se autoimpõe com autonomia</strong>. Trabalha contra si próprio convencido de que trabalha para si.","tip":"<strong>Armadilha:</strong> sentir-se patrão de si mesmo na madrugada de trabalho não é sinal de liberdade. É o disfarce mais perfeito da servidão."},
      {"ic":"spiral","t":"A Revolta Sem Inimigo","emph":"Revolta","b":"Onde há um opressor, há quem derrubar — e a dor pode virar revolta. O sujeito de desempenho não tem essa saída. <strong>Como é, ao mesmo tempo, algoz e vítima, a agressividade não encontra para onde ir senão para dentro: em vez de revolução, autodestruição; em vez de raiva contra o mundo, depressão</strong>.","tip":"<strong>Sinal de alerta:</strong> a culpa de descansar num domingo mostra que a cobrança já não vem de fora. Você a herdou — e agora a executa sozinho.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": ["A época trocou o dever da proibição pelo poder ilimitado — e o ilimitado esgota mais que o proibido.", "O sujeito de desempenho é senhor e escravo de si: explora-se acreditando que se realiza.", "Sem opressor externo não há revolta possível; a agressividade volta-se para dentro e vira depressão."],
  },
  {
    "slug": "ch03-tedio-profundo",
    "sub": "CAPÍTULO 3: O Tédio Profundo",
    "intro": "Costumamos vender a multitarefa como uma conquista da civilização, prova de que o humano evoluiu. É o contrário: o animal selvagem também divide a atenção em vários focos ao mesmo tempo — comer, vigiar predadores, guardar a cria. A multitarefa não nos eleva acima dos bichos; nos devolve ao estado de alerta da selva. E a cultura, que nasce do oposto — da atenção profunda e demorada —, definha junto com o tédio que a alimentava.",
    "cards": [
      {"ic":"eye","t":"O Retorno à Selva","emph":"Selva","b":"A atenção dispersa, repartida entre muitas tarefas, é a forma de atenção do animal que precisa vigiar o ambiente para sobreviver. <strong>A multitarefa que celebramos como avanço é, na verdade, uma regressão: o aguçamento, não da consciência cultural, mas da vigilância selvagem que nunca pode baixar a guarda</strong>.","tip":"<strong>Prática:</strong> a incapacidade de terminar uma leitura sem checar o telefone não é agilidade. É a atenção do animal cercado, que não consegue se demorar em nada."},
      {"ic":"clock","t":"O Pássaro do Tédio","emph":"Tédio","b":"Benjamin chamou o tédio profundo de 'pássaro de sonho que choca o ovo da experiência'. Não é vazio nem perda de tempo. <strong>É o estado contemplativo de quem suporta a quietude até que dela nasça algo — e uma cultura que extermina o tédio extermina também a calma criadora que só ele incuba</strong>.","tip":"<strong>Modelo mental:</strong> a pressa de preencher cada brecha com estímulo mata o ovo antes de chocar. O novo não nasce da agitação; nasce da paciência de não fazer nada."},
      {"ic":"lens","t":"A Atenção que Permanece","emph":"Atenção","b":"A hiperatenção salta de informação em informação e nunca se demora — troca profundidade por velocidade e fica incapaz de permanecer. <strong>Toda obra duradoura, todo pensamento que aprofunda, exige a atenção contemplativa que descansa longamente sobre uma só coisa, e essa é justamente a faculdade que a pressa está aniquilando</strong>.","tip":"<strong>Como aplicar:</strong> reserve um intervalo intocável para uma única tarefa, sem troca nem interrupção. A demora não é desperdício de foco — é a sua condição.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": ["A multitarefa não é progresso, é regressão: a atenção dispersa do animal vigilante.", "A cultura e o pensamento profundos nascem da atenção contemplativa, que se demora.", "Sem o tédio profundo não se incuba o novo — a hiperatividade o mata antes de nascer."],
  },
  {
    "slug": "ch04-vita-activa",
    "sub": "CAPÍTULO 4: Vita Activa",
    "intro": "Hannah Arendt apostou na vita activa contra a velha contemplação ociosa: o homem se realiza agindo. Han discorda. A era do desempenho levou a ação ao extremo e não produziu o agente livre — produziu o animal laborans, hiperativo e exausto, que confunde correr com viver. O problema nunca foi agir. Foi absolutizar a atividade até expulsar dela a pausa que lhe dava sentido.",
    "cards": [
      {"ic":"mountain","t":"A Hiperatividade Não é Força","emph":"Hiperatividade","b":"Vivemos como se a atividade incessante fosse soberania, e a quietude, fraqueza. É um engano. <strong>A hiperatividade é uma forma de extrema passividade: quem não consegue parar não age livremente — apenas reage, arrastado pelo movimento, tão preso quanto o animal preso ao seu instinto</strong>.","tip":"<strong>Para refletir:</strong> a agenda lotada que você exibe como prova de potência costuma ser o oposto. Quem não pode interromper não é dono do próprio tempo."},
      {"ic":"pivot","t":"A Potência do Não","emph":"Potência","b":"Há a potência positiva — a força de fazer algo — e há a potência negativa, a força de não fazer, de se deter, de não reagir. <strong>O animal laborans só conhece a primeira e por isso é escravo dela; a verdadeira soberania está na segunda, na capacidade de dizer não à corrente dos estímulos e dos afazeres</strong>.","tip":"<strong>Como aplicar:</strong> recusar uma tarefa, uma notificação, uma oportunidade não é fraqueza. É o único gesto que prova que a sua vida ainda é sua."},
      {"ic":"clock","t":"O Demorar-se","emph":"Demorar-se","b":"A pressa devora a contemplação, e a contemplação é onde o sentido se forma. <strong>Só quem se demora — quem suporta a lentidão sem preenchê-la — colhe da experiência aquilo que a velocidade tritura: a profundidade, a duração, o que vale a pena justamente por não passar depressa</strong>.","tip":"<strong>Sinal de alerta:</strong> a incapacidade de deixar uma ideia amadurecer no silêncio, sem desfecho imediato, afunda o que ela poderia ter sido. O fruto pede tempo.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": ["A era do desempenho gera o animal laborans exausto, não o agente livre de Arendt.", "A hiperatividade é uma forma de não-liberdade: reação compulsiva, não potência.", "A capacidade soberana é a potência negativa — o demorar-se, o poder parar e não reagir."],
  },
  {
    "slug": "ch05-pedagogia-do-ver",
    "sub": "CAPÍTULO 5: Pedagogia do Ver",
    "intro": "Contra a reatividade da época, Han recorre a Nietzsche, que dizia faltar à modernidade três coisas para a verdadeira cultura: aprender a ver, aprender a pensar, aprender a falar e a escrever. Aprender a ver é acostumar o olho à calma, à paciência, ao deixar as coisas se aproximarem — e, sobretudo, é poder não reagir. O homem livre não é o que responde a todo estímulo; é o que sabe suspender a resposta.",
    "cards": [
      {"ic":"eye","t":"Aprender a Ver","emph":"Ver","b":"Ver, para Nietzsche, não é registrar imagens; é educar o olho a esperar. <strong>É deixar o estímulo se aproximar sem ceder ao impulso de reagir na hora — habituar-se à demora, ao intervalo, em vez de responder a cada provocação como faz quem não tem domínio sobre si</strong>.","tip":"<strong>Prática:</strong> diante do que pede resposta imediata, atrase-a de propósito. A capacidade de não reagir no ato é o primeiro sinal de que você vê, e não apenas reage."},
      {"ic":"scale","t":"A Força de Não Reagir","emph":"Não Reagir","b":"Confundimos potência com a pressa de revidar. É o contrário. <strong>Quem responde a todo ataque, a toda mensagem, a todo estímulo, está possuído por eles — a verdadeira força é a soberania de quem pode deixar passar, de quem detém em si o gesto antes que ele se torne reflexo</strong>.","tip":"<strong>Modelo mental:</strong> reagir furioso ao primeiro estímulo é exibir fraqueza. Suspender o contra-ataque é o gesto de quem comanda, não de quem é comandado."},
      {"ic":"gap","t":"O Intervalo do Pensamento","emph":"Intervalo","b":"Entre o que acontece e a resposta que damos existe um intervalo — e é nele que mora o pensamento. <strong>A reatividade pura suprime esse vão: responde antes de pensar, e por isso não pensa; quem abole a hesitação abole também a faculdade de refletir, reduzindo-se ao puro reflexo</strong>.","tip":"<strong>Sinal de alerta:</strong> o impulso de responder no ato, de sentenciar antes de considerar, é a morte da reflexão. Sem hesitação não há juízo, só reação.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": ["A cultura começa por aprender a ver: calma, paciência e a demora do olhar.", "A liberdade soberana é a potência negativa — o poder de não reagir ao estímulo.", "A hesitação, o intervalo entre estímulo e resposta, é a condição do pensamento; a reatividade o aniquila."],
  },
  {
    "slug": "ch06-caso-bartleby",
    "sub": "CAPÍTULO 6: O Caso Bartleby",
    "intro": "Bartleby, o escrivão de Melville, recusa cada ordem com a fórmula célebre: 'preferiria não fazê-lo'. Muitos filósofos viram nele um herói da resistência, quase uma figura messiânica do puro 'não'. Han discorda: Bartleby pertence ao mundo disciplinar — ao escritório fechado, à negatividade, à proibição —, e a sua paralisia não tem nada da nossa exaustão. Ele é o sintoma de outra época, e justamente por isso ilumina a nossa por contraste.",
    "cards": [
      {"ic":"book","t":"Um Sintoma de Outra Era","emph":"Era","b":"Bartleby vive entre paredes, sob ordens, no escritório murado da sociedade disciplinar. <strong>A sua doença é a da negatividade — a apatia de quem é cercado pela proibição e pelo dever, não o esgotamento de quem se cobra a si mesmo no horizonte aberto do 'tudo é possível'</strong>. Adoece do muro, não da liberdade.","tip":"<strong>Como aplicar:</strong> não projete no escrivão a nossa dor. A síndrome dele nasce do confinamento; a nossa nasce da ausência de qualquer parede que nos contenha."},
      {"ic":"lens","t":"Contra o Mito Messiânico","emph":"Messiânico","b":"Há quem leia o 'preferiria não' como um gesto sublime de recusa, uma potência heroica do nada. <strong>Han desfaz o mito: o que há em Bartleby não é grandeza filosófica, é o esvaziamento de quem perdeu o sentido — uma apatia sem rumo, não uma resistência libertadora</strong>.","tip":"<strong>Modelo mental:</strong> cruzar os braços por exaustão não é a mesma coisa que recusar por soberania. Romantizar a paralisia confunde sintoma com cura."},
      {"ic":"triangle","t":"A Lógica Que Mudou","emph":"Lógica","b":"O valor do caso Bartleby está no contraste que ele revela. <strong>Entre a época dele e a nossa, a própria lógica da doença virou: saímos da paralisia imposta de fora, dentro do muro, para o esgotamento autoimposto, sem muro nenhum — e tratar uma com o remédio da outra é errar o diagnóstico</strong>.","tip":"<strong>Sinal de alerta:</strong> oferecer 'mais liberdade' e 'mais autonomia' a quem já adoece de excesso de possibilidade não cura. Aprofunda a mesma chaga.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": ["Bartleby é figura disciplinar e negativa — pertence à era do muro, não à do desempenho.", "Han rejeita a leitura messiânica do 'preferiria não': é apatia sem sentido, não resistência heroica.", "O capítulo mostra que a lógica da doença mudou entre as eras — e que tratá-las igual é erro de diagnóstico."],
  },
  {
    "slug": "ch07-sociedade-do-cansaco",
    "sub": "CAPÍTULO 7: A Sociedade do Cansaço",
    "intro": "Nem todo cansaço adoece. Há o cansaço do desempenho, que esgota, isola e emudece — o cansaço de quem não pode mais e ainda se cobra. E há, em Peter Handke, o cansaço fundamental: um cansaço eloquente e sereno, que em vez de fechar o eu sobre si, o reabre para o mundo e para o outro. A cura desta época não está em desempenhar mais. Está em aprender, enfim, a se cansar bem.",
    "cards": [
      {"ic":"gap","t":"O Cansaço que Separa","emph":"Separa","b":"O esgotamento do desempenho é solitário por natureza: cada um se cobra sozinho, exausto, e nessa exaustão perde até a fala. <strong>É um cansaço que isola, que torna o outro insuportável e mudo o convívio — quem assim se cansa só consegue ver a si mesmo e ao próprio fracasso, fechado num eu sem janelas</strong>.","tip":"<strong>Sinal de alerta:</strong> o cansaço que te deixa irritado com a presença alheia, incapaz de conversa e de pausa partilhada, não é descanso adiado. É a doença em ação."},
      {"ic":"wave","t":"O Cansaço que Reconcilia","emph":"Reconcilia","b":"Handke descreve outro cansaço, eloquente e generoso, que afrouxa a tirania do eu. <strong>Esse cansaço fundamental não fecha — abre: devolve o olhar ao mundo, restaura a confiança entre as pessoas e funda uma comunidade serena de quem, igualmente cansado, baixou as armas e pode finalmente estar junto sem cobrança</strong>.","tip":"<strong>Modelo mental:</strong> existe um cansaço que aproxima — o de quem, depois do esforço, se senta ao lado do outro em silêncio sereno. Esse cansaço cura o que o desempenho rompeu."},
      {"ic":"leaf","t":"A Saída Não é Fazer Mais","emph":"Saída","b":"A tentação é tratar o esgotamento com mais método, mais produtividade, mais autocontrole — mais do mesmo veneno. <strong>Mas a doença é de excesso, e o que cura o excesso é a subtração: não o próximo desempenho, e sim o demorar-se sereno, a contemplação, o tempo que não rende nada e por isso reconcilia</strong>.","tip":"<strong>Como aplicar:</strong> o antídoto não é uma agenda melhor. É reservar um tempo que não produz, não otimiza e não cobra — e suportar que ele seja, simplesmente, vazio e bom."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": ["Há dois cansaços opostos: o do desempenho, que separa e emudece, e o fundamental, que reconcilia.", "O cansaço fundamental de Handke afrouxa a tirania do eu e reabre a pessoa para o mundo e o outro.", "A saída não é desempenhar mais, mas o demorar-se sereno — a cura por subtração, não por acúmulo."],
  },
  {
    "slug": "ch08-burnout-senhor-e-escravo",
    "sub": "CAPÍTULO 8: Burnout — Senhor e Escravo de Si",
    "intro": "Depressão e burnout são as doenças que assinam o sujeito de desempenho. Não nascem do excesso de responsabilidade, mas do excesso de poder: quando o 'tudo é possível' colide com o limite real do corpo e da alma, o eu que se explora a si mesmo não desiste — incendeia-se por dentro. O burnout não é o sistema falhando. É o sujeito de desempenho levado às últimas consequências.",
    "cards": [
      {"ic":"triangle","t":"A Guerra Contra Si","emph":"Guerra","b":"No burnout não há agressor externo a apontar; a violência partiu de dentro. <strong>O sujeito de desempenho é, ao mesmo tempo, quem aperta o gatilho e quem cai: cobra-se uma meta sem fim, fracassa em alcançá-la — porque ela não tem fim — e dirige contra si próprio toda a agressividade que não encontra outro alvo</strong>.","tip":"<strong>Modelo mental:</strong> quando o esgotamento chega, a pergunta não é 'quem me fez isso?'. É 'por que continuei me fazendo isso?'. A cura começa em soltar o próprio gatilho."},
      {"ic":"spiral","t":"A Queda Sem Fundo","emph":"Queda","b":"A proibição tinha pelo menos uma virtude: marcava onde parar. O 'poder ilimitado' aboliu essa marca. <strong>Sem nenhum limite externo para conter a corrida, o desempenho não tem onde frear — e a queda livre da autoexploração não encontra fundo, porque foi exatamente o fundo que a época removeu</strong>.","tip":"<strong>Sinal de alerta:</strong> a ausência de toda barreira externa não é liberdade. É o que torna você o único responsável por não despencar — e ninguém aguenta segurar a si mesmo para sempre.","warn":True},
      {"ic":"leaf","t":"A Cura é Subtrair","emph":"Subtrair","b":"Contra uma doença de excesso, acrescentar não cura — só agrava. <strong>O remédio do burnout não é mais positividade, mais foco, mais método: é reaprender a negatividade que perdemos — o limite, a forma, a pausa, o 'não' que protege —, devolvendo ao eu a fronteira sem a qual ele se dissolve</strong>.","tip":"<strong>Como aplicar:</strong> reconstrua barreiras onde a época as derrubou. Recusar, interromper, deixar de fora — esses gestos negativos são o dique que impede a alma de transbordar e secar."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": ["Depressão e burnout são o fracasso do 'poder' ilimitado, não do 'dever' proibitivo.", "A autoexploração implode: sem opressor externo, a violência volta-se contra o próprio eu.", "A cura é subtração — limite, forma, pausa, o 'não' que protege — e nunca mais positividade."],
  },
]
