# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) das páginas da biblioteca para 'Sound Design' de David
Sonnenschein. O uso EXPRESSIVO do som: processo, criatividade, acústica,
psicoacústica, música, voz, efeitos e o mapa emocional."""

BOOK = {
 "title": "Sound Design",
 "author": "David Sonnenschein",
 "header_light": "SOUND",
 "header_bold": "DESIGN",
 "subtitle": "VISÃO GERAL · A METADE DO FILME QUE NINGUÉM VÊ",
 "intro": "Feche os olhos numa sala de cinema e você ainda saberá tudo: o medo, o lugar, a iminência. O som é a metade da obra que entra sem pedir licença — e que quase todo filme desperdiça. Sonnenschein, músico antes de mixador, faz uma promessa simples e radical: <strong>voz, música e efeito não ilustram a imagem; dizem ao espectador o que sentir</strong>, por baixo do consciente. Todo som percorre a mesma rota — vibração que vira sensação, que vira percepção, que vira emoção — e o ofício é desenhar essa rota inteira: traçar a curva do coração da plateia e pintá-la com tom, ritmo, peso, cor, espaço e, sobretudo, silêncio.",
 "description": "O manual expressivo do sound design por David Sonnenschein — o livro que ensina a ouvir o roteiro antes de filmá-lo. Do spotting à mixagem: como inventar sons que dizem mais que o real, como a física vira emoção (vibração → sensação → percepção → sentimento), e como orquestrar voz, música e efeitos sem que briguem. No fim, o mapa emocional: a curva do que a plateia sente, desenhada com peso, ritmo, silêncio — e a coragem de cortar tudo no instante certo.",
 "tags": ["Som", "Cinema", "Ofício"],
 "progress": "8 Capítulos",
 "cover": "assets/sound-design-cover.png",
 "overview_cards": [
   {"ic":"layers","t":"As 3 Famílias do Som","b":"Toda trilha é um trio que vive à beira da briga: a <strong>voz</strong>, que reina porque o cérebro a coloca acima de tudo; a <strong>música</strong>, que comenta a cena em vez de descrevê-la; e os <strong>efeitos</strong>, que erguem o mundo onde nada foi filmado. O ofício não é somá-los — é reger quem fala e quem se cala a cada segundo.","tip":"<strong>Como aplicar:</strong> em cada instante, escolha um dono do palco (quase sempre a voz) e mande os outros dois recuarem.","wide":True},
   {"ic":"spiral","t":"Da Vibração à Emoção","b":"Um som é uma viagem em quatro estações: <strong>vibração</strong> (o ar tremendo), <strong>sensação</strong> (o ouvido vibrando junto), <strong>percepção</strong> (o cérebro decidindo o que aquilo é) e <strong>emoção</strong> (o corpo respondendo antes do pensamento). Projetar som é conduzir essa viagem do começo ao fim.","tip":"<strong>Modelo mental:</strong> você não mixa para o medidor de decibéis — mixa para o sistema nervoso da plateia."},
   {"ic":"clock","t":"O Mapa Emocional","b":"Antes de tocar num fader, desenhe a curva do que a história quer que o público sinta — e faça o som <strong>persegui-la</strong>, usando peso, ritmo, volume, cor e vazio como tinta. O som nunca legenda a imagem: ele cochicha ao espectador como ele deve se sentir.","tip":"<strong>Chave:</strong> no auge da emoção, muitas vezes o gesto mais alto é cortar tudo — o clímax É o silêncio."},
 ],
}

CHAPTERS = [
 {"slug":"ch01-processo-sound-design","sub":"CAPÍTULO 1: O Processo do Sound Design",
  "intro":"Som de filme não se cola no fim, como quem passa verniz numa mesa pronta. Ele se planta na leitura do roteiro, antes da primeira diária. O som pensado cedo conta história; o som improvisado na última semana só tapa buraco — e dá para ouvir a diferença.",
  "cards":[
      {"ic":"eye","t":"Ler o Roteiro com os Ouvidos","emph":"Ler com os Ouvidos","b":"O <em>spotting</em> é ler o roteiro perguntando, página a página, 'o que isto soa?'. Onde a cena pede um relógio que não para, um silêncio que sufoca, uma cidade que respira do outro lado da janela. <strong>Cada cena guarda um som à espera de quem o escute antes de existir</strong> — e marcá-lo no papel já é começar a dirigir a emoção.","tip":"<strong>Como aplicar:</strong> passe o roteiro de novo só ouvindo; anote no fim de cada cena o som que ela está pedindo em silêncio."},
      {"ic":"target","t":"Todo Som Precisa de um Porquê","emph":"Intenção","b":"Som sem motivo não é riqueza, é entulho — e entulho rouba espaço de quem tem algo a dizer. Cada ruído que entra na trilha gasta a atenção da plateia, que é finita. <strong>O que não empurra a história deixa a mesa</strong>: a clareza não vem de somar camadas, vem de cortar as que não servem.","tip":"<strong>Modelo mental:</strong> antes de adicionar um som, pergunte o que ele faz pela cena. Se a resposta for 'nada', ele já tem destino: o lixo."},
      {"ic":"gap","t":"A Cilada de Deixar para a Pós","emph":"Deixar para a Pós","b":"É tentador adiar o som para a sala de mixagem, como se fosse só um acabamento técnico. Mas decisão sonora tomada no fim chega tarde e cara: o que se desenhava por dois reais no roteiro custa uma fortuna para remendar depois. <strong>A pós-produção conserta; ela não inventa o que ninguém imaginou a tempo</strong>.","tip":"<strong>Cuidado:</strong> 'a gente resolve na mix' é a frase que mata as melhores ideias de som — elas morrem por falta de planejamento, não de talento."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 1",
  "lessons":["Sound design começa no roteiro (o spotting), não na mixagem.","Defina a paleta antes de criar; cada som precisa de uma intenção clara.","Mixar é hierarquizar: decidir quem manda no palco a cada instante."]},

 {"slug":"ch02-criatividade-sons","sub":"CAPÍTULO 2: Criatividade e a Invenção de Sons",
  "intro":"O som mais forte de uma cena quase nunca é a gravação fiel do objeto. É o som inventado — aquele que larga a verdade do microfone para dizer a verdade da emoção. O ouvido não quer exatidão; quer sentido.",
  "cards":[
      {"ic":"spark","t":"A Metáfora Sonora","emph":"Metáfora","b":"Gravar a moto como ela soa de fato é jornalismo. Fazê-la rosnar como uma fera prestes a atacar é cinema. <strong>O som não precisa ser correto; precisa ser verdadeiro para o que a cena sente</strong>. Misturar um rugido de leão a um trovão para uma porta que se abre não engana a plateia — diz a ela, direto no instinto, que o perigo entrou.","tip":"<strong>Como aplicar:</strong> pergunte o que a cena sente, não o que ela é. Depois procure o som dessa emoção, mesmo que ele venha de outro objeto."},
      {"ic":"layers","t":"Sons Nascem de Camadas","emph":"Camadas","b":"Os sons inesquecíveis do cinema raramente saem de uma fonte só. O sabre de luz é zumbido de projetor casado com chiado de TV; o monstro é voz humana afundada e desacelerada sobre rosnados de bicho. <strong>O timbre que ninguém reconhece nasce do cruzamento de fontes que ninguém esperava</strong> — e vira a assinatura sonora do filme.","tip":"<strong>Modelo mental:</strong> empilhe e processe fontes improváveis até surgir uma textura nova. Quando você não souber mais de onde aquilo veio, está pronto."},
      {"ic":"gap","t":"A Preguiça da Biblioteca Pronta","emph":"Biblioteca Pronta","b":"O banco de efeitos genéricos é a saída fácil — e ouvida em mil outros filmes. A mesma porta, o mesmo trovão, o mesmo passo: o público já os escutou e seu ouvido escorrega por cima sem sentir nada. <strong>O som de prateleira não erra; ele apenas não diz nada que seja seu</strong>, e a obra perde a voz própria.","tip":"<strong>Cuidado:</strong> usar a biblioteca como atalho é aceitar soar igual a todo mundo. O efeito comum não estraga o filme — ele o apaga."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 2",
  "lessons":["Desenhe a sensação, não a fidelidade ao objeto — essa é a metáfora sonora.","Os sons mais fortes costumam ser camadas de fontes inesperadas.","Um som original e reconhecível vira a assinatura do filme."]},

 {"slug":"ch03-vibracao-sensacao","sub":"CAPÍTULO 3: Da Vibração à Sensação",
  "intro":"Antes de comover, o som é só física: ar em movimento. Mas cada propriedade dessa física — altura, volume, duração, ritmo, espaço — é uma alavanca que mexe direto no corpo de quem ouve. Conhecê-las é ter as mãos nos botões da emoção.",
  "cards":[
      {"ic":"scale","t":"A Física Vira Sentimento","emph":"Física","b":"O grave profundo você não escuta — você sente no peito, e o corpo o lê como peso, ameaça, algo grande se aproximando. O agudo cortante crispa os nervos como uma unha no quadro-negro. <strong>Cada faixa de frequência tem um efeito no corpo antes de ter um nome na cabeça</strong>: a altura do som é a primeira escolha emocional do designer.","tip":"<strong>Como aplicar:</strong> quer ameaça que sufoca? Desça ao grave. Quer alerta que arrepia? Suba ao agudo. O timbre escolhe o sentimento antes da imagem aparecer."},
      {"ic":"pivot","t":"A Lei do Contraste","emph":"Contraste","b":"Um som só é alto em relação a um som baixo; um estrondo só assusta depois de um silêncio. <strong>Nenhum som significa sozinho — o sentido nasce da diferença entre o que veio antes e o que vem depois</strong>. O grito que gela a plateia foi preparado pelos minutos de quietude que o antecederam; sem o vale, não há pico.","tip":"<strong>Modelo mental:</strong> para um som chocar, esvazie o que vem antes dele. O susto mora no contraste, não no volume."},
      {"ic":"gap","t":"O Muro de Volume","emph":"Muro de Volume","b":"Quando tudo está alto o tempo todo, nada se destaca — e o ouvido, exausto, se desliga. A trilha que grita do início ao fim acha que está empolgando e está apenas anestesiando: <strong>a plateia para de sentir um som que nunca cede</strong>. Sem respiro, o forte vira ruído de fundo e perde todo o poder de surpreender.","tip":"<strong>Cuidado:</strong> volume no talo o filme inteiro não emociona — fatiga. Guarde o máximo para o instante que merece, e dê ao ouvido o vazio que torna esse instante grande."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 3",
  "lessons":["Altura, intensidade, ritmo e espaço são as alavancas físicas da emoção.","Graves pesam, agudos tensionam — mas é o contraste que dá significado.","O grave profundo cria tensão no corpo que a plateia sente sem perceber."]},

 {"slug":"ch04-sensacao-percepcao","sub":"CAPÍTULO 4: Da Sensação à Percepção",
  "intro":"O ouvido capta vibração; é o cérebro que decide o que ela significa — e o que ele simplesmente descarta. A mente não ouve tudo: ela escolhe, filtra, ignora. Desenhar som é desenhar para esse filtro, não para o microfone.",
  "cards":[
      {"ic":"lens","t":"Figura e Fundo","emph":"Figura e Fundo","b":"A atenção é uma lanterna: aponta para um som e mergulha o resto na sombra. O cérebro elege uma <strong>figura</strong> (em geral a voz) e empurra o resto para o <strong>fundo</strong>. <strong>Tente fazê-lo seguir duas coisas importantes ao mesmo tempo e ele não acompanha nenhuma</strong> — vira ruído, e a cena se perde. A mixagem decide para onde a lanterna aponta.","tip":"<strong>Como aplicar:</strong> em cada instante, escolha a figura e proteja-a; tudo o mais é fundo, e fundo tem que ceder espaço."},
      {"ic":"wave","t":"O Mascaramento","emph":"Mascaramento","b":"Quando dois sons ocupam a mesma faixa de frequência, o mais forte apaga o mais fraco — o ouvido nem percebe que o segundo existiu. A guitarra densa engole o violino na mesma região; o estrondo cobre o sussurro. <strong>Som não soma: som disputa território</strong>. Quem ignora isso enche a trilha e perde, sem saber, metade dela.","tip":"<strong>Modelo mental:</strong> se um som importante some, ele não está baixo — está sendo mascarado. Abra espaço na frequência em vez de só subir o volume."},
      {"ic":"gap","t":"Quando a Trilha Atropela a Voz","emph":"Trilha sobre a Voz","b":"O erro mais caro do som é deixar a música épica devorar a fala. As consoantes desaparecem, a plateia perde a frase — e perde a cena inteira que dependia dela. <strong>Nenhuma orquestra vale a sílaba que o público precisava entender</strong>: o espectador não relê uma fala como relê uma linha, ela passa uma vez só.","tip":"<strong>Cuidado:</strong> quando o ator fala, a trilha se ajoelha. Abra um corte na frequência da voz e deixe a palavra respirar."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 4",
  "lessons":["O cérebro filtra o som: mascaramento, figura/fundo e atenção seletiva.","Um fluxo consciente por vez — proteja sempre a figura, que costuma ser a voz.","Metade da emoção mora abaixo do consciente: o grave e a ambiência."]},

 {"slug":"ch05-musica","sub":"CAPÍTULO 5: A Música",
  "intro":"A música é a estrada mais curta até a emoção — e por isso a mais perigosa. Bem usada, dirige o coração da plateia sem ela perceber; mal usada, vira muleta que carrega cenas que não se sustentam sozinhas. É uma língua, e tem gramática.",
  "cards":[
      {"ic":"spark","t":"As Alavancas da Música","emph":"Alavancas","b":"A música move o público por escolhas precisas, não por mágica. A harmonia menor entristece, a maior conforta; o tom dissonante incomoda de propósito; o andamento acelerado aperta o peito, o lento o solta. <strong>Cada parâmetro musical é um botão emocional que o compositor gira com intenção</strong> — e o espectador sente o resultado sem saber a causa.","tip":"<strong>Como aplicar:</strong> não escolha a música por ser 'bonita'; escolha-a pelo que ela faz com o pulso de quem assiste."},
      {"ic":"link","t":"O Leitmotiv","emph":"Leitmotiv","b":"Amarre uma melodia a um personagem ou ideia e, a cada retorno, ela carrega a bagagem de tudo o que já aconteceu. <strong>O tema repetido vira memória: quando volta — distorcido, em menor, partido — diz à plateia o que mudou sem uma única palavra</strong>. É como o som constrói significado ao longo do filme inteiro, e não só na cena.","tip":"<strong>Modelo mental:</strong> apresente o tema do herói inteiro e radiante; no fim, toque-o quebrado, e a plateia sentirá a perda antes de entendê-la."},
      {"ic":"gap","t":"A Música que Repete a Imagem","emph":"Redundância","b":"Pôr a música para imitar cada gesto da tela — o famoso 'mickey-mousing' — é dizer duas vezes a mesma coisa e tratar o público como tolo. <strong>Música que só sublinha o que já se vê não acrescenta nada; ela só ocupa o ar</strong>. E o ar ocupado o tempo todo rouba o silêncio que faria a próxima nota valer algo.","tip":"<strong>Cuidado:</strong> a música deve comentar a cena, não legendá-la. Se ela diz exatamente o que a imagem já disse, ela é dispensável — corte-a."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 5",
  "lessons":["Melodia, harmonia, ritmo e timbre são alavancas emocionais precisas.","O leitmotiv constrói significado por repetição e variação ao longo do filme.","Música comenta — não ilustra — e só impacta quando há silêncio para contrastar."]},

 {"slug":"ch06-voz-humana","sub":"CAPÍTULO 6: A Voz Humana",
  "intro":"De todos os sons do mundo, a voz humana é o que o cérebro persegue primeiro — herança de uma espécie que sobreviveu ouvindo a fala dos seus. Ela carrega duas coisas ao mesmo tempo: a palavra (o quê) e a melodia da palavra (o como). E o como pesa mais.",
  "cards":[
      {"ic":"key","t":"A Voz Diz Mais que a Palavra","emph":"A Voz","b":"A mesma frase — 'estou bem' — pode ser alívio, mentira ou súplica, e o que decide é a <em>prosódia</em>: o tom, o ritmo, a pausa, o tremor na garganta. <strong>As palavras carregam a informação; a maneira de dizê-las carrega a verdade</strong>. O ouvido humano lê essa melodia com uma precisão que nenhum dicionário alcança.","tip":"<strong>Como aplicar:</strong> antes de cuidar da clareza da frase, cuide da emoção da entrega — é nela que a plateia acredita ou não."},
      {"ic":"target","t":"O Vococentrismo","emph":"Vococentrismo","b":"Quando há uma voz, o resto do som se curva. O cérebro não consegue não ouvir a fala humana; ela puxa a atenção sobre qualquer música ou efeito. <strong>Por isso a inteligibilidade da voz é sagrada: perdida uma palavra-chave, perde-se a cena</strong>. A orquestra mais cara do filme recua quando o ator abre a boca.","tip":"<strong>Modelo mental:</strong> na dúvida entre a beleza da trilha e a clareza da fala, escolha sempre a fala. A plateia perdoa um som; não perdoa não entender."},
      {"ic":"gap","t":"Quando o Som Desmente o Rosto","emph":"Descompasso","b":"A imagem mostra dor de partir o peito, mas o áudio entrega uma fala morna, gravada de qualquer jeito numa cabine cansada — e algo na plateia se desliga sem saber por quê. <strong>O ouvido percebe a mentira da voz antes de a razão entender o que houve</strong>. Voz sem verdade afunda a cena que a imagem tentava salvar.","tip":"<strong>Cuidado:</strong> dublagem e regravação são onde a emoção morre ou renasce. Uma fala sem alma anula a melhor atuação diante da câmera."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 6",
  "lessons":["A voz é palavra + prosódia + grão — e a prosódia é quem define o sentido.","Vococentrismo: a inteligibilidade da voz se protege acima de tudo.","Pausa e entonação são direção de ator — é nelas que a emoção mora."]},

 {"slug":"ch07-efeitos-paisagem","sub":"CAPÍTULO 7: Efeitos e Paisagem Sonora",
  "intro":"Os efeitos são os que constroem o mundo: dizem onde estamos, a que horas, o que é sólido e o que ameaça. A paisagem sonora — o fundo que ninguém nota — é um personagem invisível que define o lugar inteiro antes de a câmera mostrá-lo.",
  "cards":[
      {"ic":"layers","t":"As Camadas que Erguem o Mundo","emph":"Camadas","b":"Um cenário ganha vida em camadas: o passo no assoalho (o <em>foley</em> da presença), a ventania na janela e o burburinho da cidade (a ambiência do lugar), o estrondo que sobressalta (os efeitos duros). <strong>Empilhadas, elas convencem o ouvido de que existe um mundo onde havia só um estúdio vazio</strong>. A textura é o que faz a tela parecer habitada.","tip":"<strong>Como aplicar:</strong> construa o ambiente em planos — perto, médio, distante. A profundidade do som é o que dá tamanho ao espaço."},
      {"ic":"lens","t":"A Lupa do Diretor","emph":"Lupa","b":"O som decide para onde a plateia olha. Suma com a cidade lá fora e amplie o tique-taque do relógio, e a sala inteira passa a girar em torno do tempo que se esgota. <strong>Apagar tudo menos um som é apontar a atenção como um dedo</strong>: o que se ouve sozinho vira o centro do mundo, mesmo que a imagem mostre outra coisa.","tip":"<strong>Modelo mental:</strong> o silêncio ao redor de um único som é um zoom para os ouvidos — use-o para dizer à plateia o que importa agora."},
      {"ic":"gap","t":"A Cilada do Realismo Total","emph":"Realismo Total","b":"Tentar reproduzir cada som que existiria de verdade na cena cria uma papa indistinta — fiel à vida e surda para a história. <strong>A realidade é barulhenta e desfocada; o cinema precisa escolher</strong>. Exagerar o que conta e apagar o resto não é mentir: é traduzir o caos do mundo numa frase que o ouvido entende.","tip":"<strong>Cuidado:</strong> o som fiel a tudo não emociona ninguém. Faça hiper-realismo seletivo: um detalhe enorme, o resto em silêncio."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 7",
  "lessons":["Foley (presença), efeitos duros, ambiência (o lugar) e o som inventado são as camadas.","A paisagem sonora é um personagem: define espaço, tempo e clima.","Hiper-realismo seletivo: exagere um som que conta e apague todo o resto."]},

 {"slug":"ch08-som-imagem-emocao","sub":"CAPÍTULO 8: Som, Imagem e o Mapa Emocional",
  "intro":"O som não acompanha a imagem como um cãozinho — funde-se a ela e muda o que ela significa. A mesma cena com duas trilhas conta duas histórias. O método que coroa o livro é simples de dizer e difícil de fazer: trace a curva emocional da obra e pinte-a com som.",
  "cards":[
      {"ic":"clock","t":"O Mapa Emocional","emph":"Mapa","b":"Antes da técnica, o desenho: marque, do início ao fim, o que a história quer que a plateia sinta — tensão que sobe, alívio, queda, êxtase. <strong>Esse traçado vira a partitura do filme inteiro, e o som apenas o obedece</strong>: peso e volume nos picos, silêncio e rarefação nos vales. Sem o mapa, o som vira plano e a viagem, monótona.","tip":"<strong>Como aplicar:</strong> rascunhe a curva de emoção da obra numa linha só; depois pergunte, ponto a ponto, qual som a empurra para cima ou para baixo."},
      {"ic":"pivot","t":"O Som Contra a Imagem","emph":"Contraponto","b":"O som não precisa concordar com a tela. Quando a trilha empática chora junto, ela confirma a cena; quando a trilha anempática segue alegre sobre a tragédia — uma valsinha leve sobre a violência —, o contraste cala fundo. <strong>A indiferença do som diante do horror é mais cruel que qualquer trilha de medo</strong>, porque diz que o mundo nem reparou.","tip":"<strong>Modelo mental:</strong> uma musiquinha doce sobre uma cena brutal não suaviza — ela gela. Use o som que contraria quando quiser o golpe mais frio."},
      {"ic":"key","t":"O Silêncio como Clímax","emph":"Silêncio","b":"O gesto mais ousado da trilha é tirá-la. Depois de construir camadas e camadas, cortar tudo de uma vez cria um vácuo que prende a respiração da sala inteira. <strong>O silêncio só existe se houver som antes para esvaziar — e, posto na hora certa, grita mais alto que qualquer orquestra</strong>. É a nota final que o livro inteiro vinha preparando.","tip":"<strong>Cuidado:</strong> o silêncio só funciona como pico depois do cheio. Construa a densidade primeiro; depois apague tudo, e deixe o vazio fazer o trabalho."},
    ],
  "lessons_title":"Lições-Chave do Capítulo 8",
  "lessons":["Trace a curva emocional e pinte-a com peso, ritmo, volume, densidade e silêncio.","O som empático acompanha; o anempático contraria — e a indiferença é a mais cruel.","O clímax muitas vezes é o silêncio: densidade e corte são dramaturgia."]},
]
