# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'A Startup Enxuta' (The Lean Startup) de Eric Ries."""

BOOK = {
  "title": "A Startup Enxuta",
  "author": "Eric Ries",
  "header_light": "A STARTUP",
  "header_bold": "ENXUTA",
  "subtitle": "VISÃO GERAL · CONSTRUIR, MEDIR, APRENDER — ANTES QUE O DINHEIRO ACABE",
  "intro": "Toda startup é uma fábrica de uma coisa só: aprendizado. O resto — código, escritório, plano de slides — é matéria-prima ou desperdício. Eric Ries pega o chão de fábrica da Toyota e o aponta para a névoa onde startups operam: trate cada ideia como hipótese, construa o mínimo para testá-la, meça o que clientes reais fazem (não o que juram em pesquisa) e aprenda rápido o bastante para decidir entre virar o leme e seguir reto. O inimigo não é o concorrente nem a falta de talento. É o pior desperdício do mundo: construir com esmero, à perfeição, algo que ninguém quer.",
  "description": "O manual que tirou o empreendedorismo do mito do gênio na garagem e o pôs sobre o método científico. No centro, o ciclo Construir-Medir-Aprender e sua única moeda de progresso: o aprendizado validado — prova, com dados de cliente real, não a sensação de 'evoluímos'. Em volta, as ferramentas: o MVP que existe para aprender e não para impressionar, as hipóteses de valor e de crescimento (os saltos de fé), pivotar ou perseverar guiado por números, a contabilidade da inovação contra as métricas de vaidade, os três motores de crescimento, os lotes pequenos da linha de montagem e os cinco porquês que descem do sintoma técnico à raiz humana. A pergunta que governa tudo: não 'podemos construir?', mas 'devemos — e há negócio aqui?'.",
  "tags": ["Empreendedorismo", "Gestão", "Inovação"],
  "progress": "14 Capítulos",
  "cover": "assets/startup-enxuta-cover.png",
  "overview_cards": [
    {"ic":"spiral","t":"Construir-Medir-Aprender","b":"O motor de tudo, e ele gira ao contrário do instinto. Você não começa construindo: começa decidindo <strong>o que precisa aprender</strong>, depois o que medir, e só então o mínimo a construir para descobrir. Ideia vira hipótese, hipótese vira experimento, experimento vira decisão. A meta não é girar bonito — é <strong>encurtar cada volta</strong> antes que o caixa seque.","tip":"<strong>Modelo mental:</strong> planeje o laço de trás para frente; execute-o de frente. Quem inverte só na execução constrói às cegas.","warn":True},
    {"ic":"target","t":"Aprendizado Validado","b":"Pergunte qual foi o progresso da semana e a startup média responde com linhas de código e horas de reunião. Errado. A única moeda de progresso é o <strong>aprendizado validado</strong>: prova, com dados de cliente real, de uma verdade sobre o negócio. 'Trabalhamos muito' não conta. 'Aprendemos com o fracasso' tampouco — isso costuma ser fracasso com legenda bonita.","tip":"<strong>O teste:</strong> de cada coisa que você fez, pergunte 'que aprendizado isto provou?'. Se a resposta é nenhum, foi desperdício, por melhor que tenha ficado."},
    {"ic":"fork","t":"Pivô × Perseverar","b":"A reunião mais temida da startup. <strong>Pivotar</strong> não é desistir: é uma virada de leme deliberada — muda a estratégia, mantém a visão. <strong>Perseverar</strong> é continuar afinando porque os números provam tração. E aqui Ries vira a chave do dinheiro: a pista (runway) não é quanto caixa sobra, é <strong>quantos pivôs ainda cabem</strong>. Ciclo mais curto = mais tentativas pelo mesmo dinheiro.","tip":"<strong>A regra:</strong> os números teimam em estagnar apesar de você afinar tudo? Pivote. Melhoram de verdade? Persevere. O resto é opinião."},
  ],
}

CHAPTERS = [
  {
    "slug": "ch01-comecar",
    "sub": "CAPÍTULO 1: Começar (Visão)",
    "intro": "Empreender virou romance: o gênio rebelde, a garagem, a fé no faro. Bonito — e perigoso, porque romance não se ensina nem se repete. Ries começa derrubando o mito: empreendedorismo é gestão. Não a gestão de planilha das empresas maduras, que pressupõe um futuro previsível, mas uma disciplina nova, feita para a névoa. A startup é um experimento contínuo, e o caos do 'só fazer' mata tão certo quanto a burocracia que asfixia.",
    "cards": [
      {"ic":"spark","t":"O Que É uma Startup","emph":"uma Startup","b":"Esqueça garagem, app e capital de risco. Uma startup é '<strong>uma instituição humana feita para criar um produto novo sob extrema incerteza</strong>'. Tire a incerteza e sobra uma empresa comum, por mais jovem que seja. Deixe a incerteza e você está numa startup — mesmo dentro de uma gigante de cem anos.","tip":"<strong>O teste:</strong> não sabe ao certo quem é o cliente nem o que ele chama de valor? Então não há plano a executar — há hipótese a testar."},
      {"ic":"wrench","t":"Empreendedorismo É Gestão","emph":"É Gestão","b":"A palavra 'gestão' soa a terno e relatório, e por isso o empreendedor a despreza — e cai no vácuo do 'apenas faça'. Mas o vazio de método mata tão rápido quanto o excesso. A startup precisa de uma gestão <strong>própria</strong>, calibrada para a incerteza: nem o piloto automático da empresa madura, nem a improvisação heroica.","tip":"<strong>Vire a chave:</strong> disciplina não estrangula a criatividade. Ela aponta a criatividade para a única saída — o aprendizado."},
      {"ic":"layers","t":"As Raízes do Método","emph":"Raízes","b":"Nada aqui é invenção do nada. O método enxerta na startup o <strong>chão de fábrica da Toyota</strong> (produção enxuta), o <em>design thinking</em>, o <strong>desenvolvimento de clientes</strong> de Steve Blank e o espírito ágil. A novidade não é a peça; é apontar a engenharia de processo para o território onde tudo é incerto.","tip":"<strong>O que isso libera:</strong> se sucesso de startup tem método, então pode ser ensinado, aprendido e repetido. Deixa de ser sorte de poucos."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 1",
    "lessons": [
      "Startup = instituição + produto novo + extrema incerteza. Tire a incerteza e não é mais startup.",
      "Sucesso empreendedor não é genialidade nem sorte: tem método, logo se aprende e se repete.",
      "Empreender é gestão — uma gestão própria da incerteza, não a execução das empresas maduras.",
      "O 'apenas faça' e o plano rígido fracassam pelo mesmo motivo: ambos fingem saber o que ninguém sabe ainda.",
    ],
  },
  {
    "slug": "ch02-definir",
    "sub": "CAPÍTULO 2: Definir (Visão)",
    "intro": "Se 'startup' é definida pela incerteza, então empreendedor não é tipo de gente — é cargo. Existe na garagem e existe no 18º andar da corporação, sempre que alguém cria algo cujo destino ninguém conhece. A grande empresa adora dizer que 'só garagem inova', e essa frase é uma desculpa cara: ela serve para nunca ter de criar, dentro de casa, o espaço onde a inovação respiraria.",
    "cards": [
      {"ic":"person","t":"Empreendedor Como Cargo","emph":"Como Cargo","b":"Não é um espírito raro nem um traço de personalidade — é uma função. <strong>Quem cria um produto novo sob extrema incerteza está empreendendo</strong>, tenha CNPJ na garagem ou crachá na multinacional. O intraempreendedor faz o mesmo trabalho do fundador, só que com mais corredores para atravessar.","tip":"<strong>Custo da desculpa:</strong> 'só garagens inovam' é o álibi que dispensa a empresa grande de construir seu próprio campo de experimentação. Sai caro."},
      {"ic":"mountain","t":"O Porto Seguro da Inovação","emph":"Porto Seguro","b":"Inovação interna não morre por falta de talento; morre esmagada pela máquina de execução ao lado. Para sobreviver, precisa de três coisas: <strong>recursos escassos mas garantidos</strong> (sem disputar verba todo trimestre), <strong>autoridade própria</strong> para decidir, e <strong>pele em jogo</strong> — alguém que ganhe ou perca com o resultado.","tip":"<strong>Como aplicar:</strong> dê à equipe um cercado protegido. Pouco recurso ensina foco; recurso instável só ensina medo."},
      {"ic":"layers","t":"Portfólio de Inovação","emph":"Portfólio","b":"A empresa madura faz duas coisas que se odeiam: <strong>executar</strong> o que já funciona e <strong>experimentar</strong> o que talvez funcione. O erro é cobrar das duas as mesmas métricas, prazos e processos. Trate-as como carteiras distintas, com réguas distintas — e blinde os experimentos da lógica do negócio que dá lucro hoje.","tip":"<strong>Vire a chave:</strong> inovação não é um projeto com data de entrega. É uma capacidade que a casa mantém ligada o tempo todo."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 2",
    "lessons": [
      "Empreendedor é cargo, não tipo de gente: existe em qualquer organização, da garagem à gigante.",
      "Inovar dentro de casa exige recursos seguros, autoridade própria e pele em jogo — os três juntos.",
      "As mesmas práticas enxutas valem para a garagem e para a multinacional; muda o número de corredores.",
      "Cobrar do experimento as métricas e prazos do negócio maduro é a forma mais comum de matá-lo.",
    ],
  },
  {
    "slug": "ch03-aprender",
    "sub": "CAPÍTULO 3: Aprender (Visão)",
    "intro": "Toda startup mede progresso de algum jeito — e quase todas medem o jeito errado: recursos lançados, prazos cumpridos, equipe ocupada. Ries oferece uma régua única e implacável: aprendizado validado. Não a sensação de ter aprendido, mas a prova, com dados de cliente de verdade, de que você descobriu algo real sobre o negócio. O que não passa nessa régua é desperdício — inclusive o trabalho mais brilhante.",
    "cards": [
      {"ic":"target","t":"Aprendizado Validado","emph":"Validado","b":"A palavra que importa é <em>validado</em>. Não é o que você acha, intui ou conclui na sala — é o que clientes reais <strong>provaram com o comportamento</strong>. 'Entregamos o recurso X' não é progresso; é movimento. Progresso é descobrir, com evidência, uma verdade sobre quem compra e por quê.","tip":"<strong>O filtro:</strong> de cada atividade, pergunte 'que verdade do negócio isto prova?'. Resposta vazia = desperdício, sem apelação."},
      {"ic":"key","t":"As Duas Perguntas","emph":"Duas Perguntas","b":"A engenharia heroica adora a pergunta '<strong>isto PODE ser construído?</strong>' — e quase sempre a resposta é sim, com esforço bastante. Mas ela é a pergunta errada. As certas vêm depois: '<strong>DEVEMOS construir?</strong>' e '<strong>há negócio sustentável aqui?</strong>'. Saber fazer não é razão para fazer.","tip":"<strong>Vire a chave:</strong> orgulho de engenharia responde 'podemos'. Sobrevivência da empresa exige responder 'devemos, e dá negócio?'."},
      {"ic":"lens","t":"O Caso IMVU","emph":"IMVU","b":"Ries passou meses costurando seu avatar aos mensageiros que as pessoas já usavam, certo de que ninguém adotaria sem os amigos de sempre por perto. Lançou. Os clientes <strong>não queriam os velhos amigos: queriam conhecer gente nova</strong>. Meses de código jogados fora — porque a suposição nunca tinha sido testada.","tip":"<strong>A lição amarga:</strong> 'mas aprendemos tanto' dito sem um dado de cliente é fracasso com roupa de domingo. Não é aprendizado validado."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 3",
    "lessons": [
      "Aprendizado validado é a régua única de progresso — e só conta apoiado em comportamento de cliente real.",
      "Esforço heroico no produto errado é desperdício, por mais impecável que seja a execução.",
      "A pergunta certa nunca é 'podemos construir?', mas 'devemos — e há negócio sustentável aqui?'.",
      "'Aprendemos muito' sem um dado de cliente é a racionalização do fracasso. Autoengano, não lição.",
    ],
  },
  {
    "slug": "ch04-experimentar",
    "sub": "CAPÍTULO 4: Experimentar (Visão)",
    "intro": "Um plano de negócios é um romance de ficção com planilhas: cada recurso, cada projeção, é uma suposição vestida de fato. Ries propõe despir a roupa. Cada item do plano vira uma hipótese, e a startup deixa de 'construir e rezar' para virar um laboratório — método científico apontado para o mercado. Pense grande na visão; comece pequeno no experimento.",
    "cards": [
      {"ic":"scale","t":"As Duas Hipóteses","emph":"Duas Hipóteses","b":"De todas as apostas escondidas num plano, duas decidem o jogo. A <strong>hipótese de valor</strong>: o produto entrega valor de verdade a quem o usa? E a <strong>hipótese de crescimento</strong>: como novos clientes o descobrem e o espalham? Errar qualquer uma derruba a casa, por mais perfeito que esteja o resto.","tip":"<strong>Como aplicar:</strong> liste as suposições, ordene-as por risco e ataque primeiro a que, se falsa, mata o negócio. Não a mais fácil de testar."},
      {"ic":"spark","t":"A Startup É um Experimento","emph":"Experimento","b":"'Quem é o cliente?' e 'o que ele chama de valor?' não se respondem na sala de reunião — se respondem <strong>no experimento</strong>. Trate o plano como hipótese a testar, não como roteiro a executar. E desconfie de pesquisa de opinião: <strong>vale o que o cliente faz, não o que ele jura que faria</strong>.","tip":"<strong>A armadilha:</strong> em pesquisa, todo mundo é gentil e visionário. No botão de comprar, todo mundo é honesto."},
      {"ic":"steps","t":"O Caso Zappos","emph":"Zappos","b":"Como saber se gente compraria sapato pela internet sem montar estoque, galpão e logística? Nick Swinmurn <strong>fotografou sapatos em lojas de verdade</strong> e os pôs à venda online. Comprou alguém? Ele ia à loja, pagava e despachava. Sem escala, sem lucro — mas a hipótese de valor foi testada com dinheiro de cliente real.","tip":"<strong>Vire a chave:</strong> o experimento já é o produto. Não é o ensaio antes do produto — rode-o cedo, barato e com gente que paga."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 4",
    "lessons": [
      "Todo plano repousa sobre saltos de fé escondidos: o trabalho é desencavá-los e testá-los primeiro.",
      "Duas hipóteses decidem o jogo — a de valor e a de crescimento. Errar uma derruba o resto.",
      "Um experimento já é um produto: rode-o cedo, barato e com clientes que pagam de verdade.",
      "Confie no que o cliente faz, não no que ele declara. O botão de comprar não mente.",
    ],
  },
  {
    "slug": "ch05-saltar",
    "sub": "CAPÍTULO 5: Saltar (Dirigir)",
    "intro": "Toda startup começa com um ato de fé — e tudo bem, desde que você saiba exatamente onde a fé está. As 'suposições de salto de fé' são as crenças tão fundamentais que, se erradas, levam o negócio inteiro junto. O trabalho do empreendedor é localizá-las cedo, nomeá-las sem disfarce e testá-las rápido, fincando a estratégia na observação direta do cliente em vez do conforto da planilha.",
    "cards": [
      {"ic":"scale","t":"Suposições de Salto de Fé","emph":"Salto de Fé","b":"São as crenças que sustentam todo o resto — e as duas decisivas você já conhece: a <strong>hipótese de valor</strong> e a <strong>hipótese de crescimento</strong>. Chamam-se 'salto de fé' porque, no começo, não há dado: você aposta. A questão não é evitar a aposta, é <strong>descobrir o quanto antes se ela se paga</strong>.","tip":"<strong>Como aplicar:</strong> empilhe as suposições e puxe para o topo a que, se falsa, encerra a empresa. É por ela que se começa."},
      {"ic":"eye","t":"Genchi Gembutsu","emph":"Genchi Gembutsu","b":"A Toyota tem um nome para isto: <em>genchi gembutsu</em> — '<strong>vá e veja com seus próprios olhos</strong>'. Nenhum relatório, painel ou resumo substitui ver um cliente real lutando com seu produto. Steve Blank traduz em ordem direta: <strong>saia do prédio</strong>.","tip":"<strong>A verdade incômoda:</strong> estratégia montada no gabinete, sem nunca olhar um cliente nos olhos, é fé disfarçada de plano."},
      {"ic":"link","t":"Analogias e Antílogos","emph":"Analogias e Antílogos","b":"Para sustentar uma aposta, dois apoios. A <strong>analogia</strong> é o que outra empresa já <strong>provou</strong> ('o iPod mostrou que pagam por música portátil'). O <strong>antílogo</strong> é o que ela de propósito <strong>não fez</strong> — e que sobra como a sua pergunta de fé ainda em aberto.","tip":"<strong>O erro:</strong> copiar o sucesso alheio sem isolar o que ele nunca testou é confundir a analogia com a prova que você ainda precisa fazer."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 5",
    "lessons": [
      "Localize as suposições de salto de fé antes de qualquer outra coisa: são elas que sustentam o resto.",
      "Vá e veja com seus próprios olhos — observação direta do cliente vence qualquer relatório.",
      "Analogias e antílogos cercam a verdadeira pergunta de fé: o que ainda ninguém testou por você.",
      "Comece pela suposição mais arriscada, não pela mais cômoda de medir.",
    ],
  },
  {
    "slug": "ch06-testar",
    "sub": "CAPÍTULO 6: Testar (Dirigir)",
    "intro": "Aqui mora o conceito mais malentendido do livro. MVP não é 'produto capenga' nem 'versão 0.1' — é a menor coisa que permite dar uma volta inteira no ciclo Construir-Medir-Aprender. Ele existe para aprender, não para encantar. O instinto do bom artesão grita por polimento; o MVP pede o oposto: corte tudo que não responde à pergunta de agora, mesmo que doa.",
    "cards": [
      {"ic":"spark","t":"Produto Mínimo Viável (MVP)","emph":"Mínimo Viável","b":"'A versão do produto que extrai o <strong>máximo de aprendizado validado</strong> com o <strong>menor esforço</strong>.' Repare na assimetria: maximize o aprendizado, minimize o trabalho. Cada recurso que não testa a hipótese de hoje é peso morto — por mais bem-feito que seja.","tip":"<strong>O choque:</strong> recurso lindo que o cliente ignora não é qualidade. É desperdício caprichado. Polir o que ninguém usa é o pior dos dois mundos."},
      {"ic":"eye","t":"MVP de Vídeo (Dropbox)","emph":"Dropbox","b":"Drew Houston não podia construir o Dropbox só para descobrir se as pessoas o queriam. Então gravou um <strong>vídeo de três minutos</strong> mostrando o produto funcionando como se já existisse. Da noite para o dia, a lista de espera pulou de <strong>5 mil para 75 mil</strong>. A hipótese de valor: provada, sem ter escrito o produto.","tip":"<strong>A sacada:</strong> o vídeo era o MVP. Testou o desejo com pixels, não com código — e só então valeu a pena construir."},
      {"ic":"person","t":"Conserje e Mágico de Oz","emph":"Mágico de Oz","b":"Duas formas de aprender antes de automatizar. No <strong>conserje</strong>, você entrega o serviço <strong>à mão, um cliente por vez</strong>, sem nenhum sistema por trás. No <strong>Mágico de Oz</strong>, o cliente acha que conversa com um software reluzente — mas há gente puxando as alavancas atrás da cortina.","tip":"<strong>De propósito:</strong> não escala, e essa é a graça. Você compra o máximo de aprendizado por cliente antes de gastar uma linha de código."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 6",
    "lessons": [
      "O MVP existe para iniciar o aprendizado, não para entregar o produto pronto.",
      "Corte todo recurso e todo esforço que não responda à pergunta que você precisa testar agora.",
      "Vídeo, conserje e Mágico de Oz testam hipóteses caras com quase nenhum código.",
      "O medo de lançar cedo — concorrente, marca, orgulho — quase sempre pesa menos do que parece.",
    ],
  },
  {
    "slug": "ch07-medir",
    "sub": "CAPÍTULO 7: Medir (Dirigir)",
    "intro": "Como saber se a startup progride quando o lucro ainda é zero e o produto muda toda semana? A contabilidade tradicional não responde — ela foi feita para empresas estáveis. Ries propõe outra: a contabilidade da inovação, um jeito rigoroso de provar que o aprendizado avança, mesmo sem receita. Sua matéria-prima são métricas acionáveis. Seu veneno são as métricas de vaidade — aquelas que existem só para fazer o fundador dormir bem.",
    "cards": [
      {"ic":"steps","t":"Contabilidade da Inovação","emph":"Contabilidade da Inovação","b":"Funciona em três tempos: (1) o MVP estabelece o <strong>baseline</strong> — onde você realmente está, não onde gostaria; (2) você <strong>afina o motor</strong> com experimentos, empurrando os números rumo ao plano; (3) ao bater na parede, decide <strong>pivotar ou perseverar</strong>. É a régua que diz se você anda ou só se mexe.","tip":"<strong>Como aplicar:</strong> defina a meta de melhoria ANTES do experimento. Se a afinação não move a agulha, não é o motor — é a estratégia que está furada."},
      {"ic":"eye","t":"Acionáveis × de Vaidade","emph":"× de Vaidade","b":"<strong>Vaidade:</strong> os números que só sobem e fazem cócegas no ego — total de usuários, downloads, hits. Sobem mesmo que o negócio esteja afundando, e não dizem o que fazer a seguir. <strong>Acionáveis:</strong> mostram causa e efeito limpos, ligando uma decisão a um resultado. Boa métrica passa nos <strong>3 As</strong>: Acionável, Acessível, Auditável.","tip":"<strong>Sinal de alerta:</strong> o gráfico que 'só sobe' é o anestésico predileto da startup. Costuma esconder, embaixo, uma estagnação que ninguém quis ver.","warn":True},
      {"ic":"layers","t":"Coorte e Teste A/B","emph":"Teste A/B","b":"Duas lupas contra a mentira dos totais. A <strong>análise de coorte</strong> acompanha cada turma que entrou no mesmo período ao longo da jornada (cadastrou → usou → voltou → pagou) — e revela se cada nova turma se sai melhor que a anterior. O <strong>teste A/B</strong> isola o efeito de uma única mudança, separando causa de coincidência.","tip":"<strong>Vire a chave:</strong> o número bruto diz que cresceu. A coorte diz se o produto ficou melhor. São perguntas diferentes — e só a segunda importa."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 7",
    "lessons": [
      "Sem contabilidade da inovação, 'estamos progredindo' é torcida, não constatação.",
      "Prefira métricas acionáveis, acessíveis e auditáveis (3 As); fuja das de vaidade que só fazem cócegas.",
      "Análise de coorte e teste A/B revelam a verdade que os números acumulados escondem.",
      "Fixe a meta de melhoria antes do experimento — senão o resultado se ajusta à narrativa, não o contrário.",
    ],
  },
  {
    "slug": "ch08-pivotar-ou-perseverar",
    "sub": "CAPÍTULO 8: Pivotar (ou Perseverar) (Dirigir)",
    "intro": "É a hora da verdade, e quase ninguém a enfrenta a tempo. Pivotar ou perseverar é a decisão que separa a startup que aprende da que apenas resiste. O problema é humano: pivotar parece admitir que se errou, então a equipe se agarra às métricas de vaidade e adia. Ries reenquadra: pivô não é fracasso, é manobra. Você gira o leme da estratégia sem largar o destino.",
    "cards": [
      {"ic":"fork","t":"O Pivô","emph":"Pivô","b":"'Uma <strong>correção estruturada de curso</strong> para testar uma nova hipótese fundamental sobre o produto, a estratégia ou o motor de crescimento.' A palavra-chave é estruturada: não é entrar em pânico e mudar tudo. Muda a <strong>estratégia</strong>, mantém a <strong>visão</strong>. O Flickr nasceu de um jogo; o Twitter, de uma plataforma de podcast. Não desistiram — pivotaram.","tip":"<strong>Como aplicar:</strong> marque reuniões fixas de pivotar-ou-perseverar e leve dados para elas. Sem ritmo marcado, a decisão é sempre empurrada 'para o próximo mês'."},
      {"ic":"cards","t":"O Catálogo de Pivôs","emph":"Catálogo de Pivôs","b":"Pivotar não é um gesto só — é um cardápio. <strong>Zoom-in</strong> (um recurso vira o produto inteiro), <strong>zoom-out</strong> (o produto vira recurso de algo maior), e ainda: segmento de cliente, necessidade, plataforma, arquitetura de negócio, <strong>captura de valor</strong> (como se cobra), motor de crescimento, canal, tecnologia.","tip":"<strong>Vire a chave:</strong> pivô bem-feito troca UMA hipótese, com clareza cirúrgica. Trocar tudo de uma vez não é pivô — é recomeçar no escuro."},
      {"ic":"pin","t":"A Pista É o Nº de Pivôs","emph":"Nº de Pivôs","b":"Pergunte a um fundador quanta pista (runway) lhe resta e ele diz os meses de caixa. Ries corrige: a pista real é o <strong>número de pivôs que ainda dá para fazer</strong>. Por isso o ciclo curto vale ouro — acelerar o laço compra mais tentativas sem levantar mais capital.","tip":"<strong>Sinal de alerta:</strong> cuidado com a <strong>terra dos mortos-vivos</strong> — crescer o bastante para não morrer, mas nunca o bastante para validar nem coragem de encerrar. É falta de pivô disfarçada de sobrevivência.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 8",
    "lessons": [
      "Pivô muda a estratégia mantendo a visão — é manobra, não fracasso, e os maiores produtos nasceram de um.",
      "Marque reuniões fixas de pivotar-ou-perseverar e decida por dados, não por amor à ideia original.",
      "Meça a pista em número de pivôs possíveis: ciclo curto compra mais tentativas pelo mesmo dinheiro.",
      "Não pivotar a tempo, abraçado às métricas de vaidade, leva à terra dos mortos-vivos.",
    ],
  },
  {
    "slug": "ch09-lotes",
    "sub": "CAPÍTULO 9: Lotes (Acelerar)",
    "intro": "Aqui o livro volta literalmente ao chão de fábrica da Toyota. A intuição manda juntar tudo e processar em lote grande — parece mais eficiente. É miragem. Lote pequeno entrega feedback mais cedo, expõe o defeito enquanto ele é barato e corta o desperdício pela raiz. O contraintuitivo, medido, vence o óbvio.",
    "cards": [
      {"ic":"steps","t":"Lotes Pequenos","emph":"Lotes Pequenos","b":"Mover <strong>uma peça de cada vez</strong> pelo fluxo inteiro (single-piece flow) parece mais lento que empilhar o trabalho — e é mais rápido onde importa: feedback imediato, defeito flagrado cedo, retrabalho mínimo. O segredo não é correr mais; é descobrir o erro antes de repeti-lo cem vezes.","tip":"<strong>Como aplicar:</strong> implantação contínua é o lote pequeno levado ao limite — mudanças minúsculas em produção, muitas vezes ao dia."},
      {"ic":"spark","t":"O Cordão Andon","emph":"Cordão Andon","b":"Na Toyota, qualquer operário pode <strong>puxar o cordão (andon) e parar a linha inteira</strong> ao ver um defeito. Soa um absurdo paralisar tudo por um parafuso torto — até você perceber a lógica: qualidade se <strong>constrói na fonte</strong>, não se inspeciona no fim, quando consertar custa o máximo.","tip":"<strong>Vire a chave:</strong> pare a linha cedo. O defeito barato de hoje é o recall caro de amanhã — e o cliente perdido depois."},
      {"ic":"wave","t":"Puxar, Não Empurrar","emph":"Não Empurrar","b":"A fábrica enxuta não <strong>empurra</strong> produção por um plano feito meses antes; ela <strong>puxa</strong> pela demanda e pelo aprendizado real. O experimento dos envelopes prova o ponto: dobrar e selar uma carta completa por vez termina antes de dobrar todas, depois selar todas — exatamente o contrário do que o instinto jura.","tip":"<strong>O que se perde no lote grande:</strong> o erro só aparece no fim, quando já há cem unidades para refazer. Lote pequeno descobre na primeira."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 9",
    "lessons": [
      "Lote pequeno parece mais lento, mas entrega aprendizado e produto mais rápido onde conta.",
      "Pare a linha ao ver o defeito (andon): qualidade se constrói na fonte, não se inspeciona no fim.",
      "Puxar pela demanda real vence empurrar por um plano feito antes de saber a verdade.",
      "Lote grande adia o feedback e multiplica o retrabalho quando o erro enfim aparece.",
    ],
  },
  {
    "slug": "ch10-crescer",
    "sub": "CAPÍTULO 10: Crescer (Acelerar)",
    "intro": "Crescer todo mundo quer; poucos sabem de onde vem o crescimento que dura. Ries dá a regra de ouro: crescimento sustentável nasce das ações dos clientes que você já tem, não de uma campanha que se paga uma vez. E aponta os três motores que produzem isso. O erro fatal é ligar os três ao mesmo tempo — aí nenhuma métrica diz mais nada. Escolha um. Conheça sua alavanca.",
    "cards": [
      {"ic":"spiral","t":"Motor Recorrente (Pegajoso)","emph":"Recorrente","b":"Cresce <strong>segurando quem entra</strong>. A conta é simples e cruel: se a taxa de aquisição supera a <strong>taxa de atrito (churn)</strong>, o produto incha; se o churn vence, ele esvazia — mesmo enquanto novos usuários chegam. A alavanca aqui não é trazer mais gente, é fazer a gente ficar.","tip":"<strong>Sinal de alerta:</strong> total de usuários subindo com churn maior que a aquisição é uma startup encolhendo em segredo, com cara de quem prospera.","warn":True},
      {"ic":"link","t":"Motor Viral","emph":"Viral","b":"Cresce porque <strong>usar o produto, por si só, o espalha</strong> — um convite, um link compartilhado, um arquivo enviado a quem ainda não usa. A métrica é o <strong>coeficiente viral</strong>: quantos novos usuários cada usuário traz. Acima de <strong>1,0</strong>, vira reação em cadeia.","tip":"<strong>Vire a chave:</strong> viralidade verdadeira mora no produto em uso, não no orçamento de marketing. Se precisa de campanha para se espalhar, não é viral — é pago disfarçado."},
      {"ic":"scale","t":"Motor Pago","emph":"Pago","b":"Cresce <strong>reinvestindo a própria receita</strong> em adquirir mais clientes. Vive de uma desigualdade só: o <strong>valor do cliente ao longo da vida (LTV)</strong> precisa superar o <strong>custo de adquiri-lo (CPA)</strong>. A margem entre os dois é o combustível; quando ela some, o motor morre, por mais dinheiro que você jogue dentro.","tip":"<strong>A regra de ferro:</strong> um motor por vez. Misturar alavancas embaralha as métricas e você perde a única coisa que tinha — saber o que está, de fato, puxando o crescimento."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 10",
    "lessons": [
      "Crescimento que dura vem das ações dos clientes antigos — escolha o motor que captura isso.",
      "Cada motor tem sua métrica: churn (pegajoso), coeficiente viral (viral), LTV × CPA (pago).",
      "Foque em um motor por vez e domine sua alavanca específica antes de tocar em outro.",
      "Crescimento de vaidade (total de usuários) mascara, com frequência, um motor já parado.",
    ],
  },
  {
    "slug": "ch11-adaptar",
    "sub": "CAPÍTULO 11: Adaptar (Acelerar)",
    "intro": "Velocidade sem disciplina vira caos; disciplina sem velocidade vira burocracia. A startup que sobrevive ao crescimento é a organização adaptativa: regula o próprio ritmo de processo conforme cresce, em vez de copiar o manual da empresa grande de uma vez. A ferramenta para isso é desconcertantemente simples — uma pergunta de criança, feita cinco vezes seguidas.",
    "cards": [
      {"ic":"spiral","t":"Os 5 Porquês","emph":"5 Porquês","b":"Diante de qualquer falha, pergunte '<strong>por quê?</strong>' cinco vezes. Cada resposta desce um andar: o primeiro porquê dá a causa técnica, e os últimos quase sempre revelam que <strong>a raiz era humana ou de processo</strong> o tempo todo. O bug nunca foi só um bug.","tip":"<strong>Como funciona:</strong> servidor caiu → código novo → não foi testado → o engenheiro era novo → ninguém o treinou → 'o chefe acha que não há tempo para treinar'. A raiz é a política de onboarding, não o coitado do plantão."},
      {"ic":"scale","t":"Investimento Proporcional","emph":"Proporcional","b":"A cura tem de ter o tamanho da doença. Problema pequeno, correção pequena; problema grande, correção grande. Essa proporção é o que evita os dois extremos: a <strong>burocracia</strong> que sufoca a cada espirro e a <strong>negligência</strong> que deixa o mesmo erro voltar amanhã.","tip":"<strong>Overdose de processo:</strong> responder a um tropeço miúdo com uma reforma monumental é tão nocivo quanto ignorá-lo. O remédio em excesso também adoece."},
      {"ic":"person","t":"Mire o Sistema, Não a Pessoa","emph":"Não a Pessoa","b":"Há um modo de transformar os 5 porquês em <strong>'5 culpados'</strong>: usá-los para achar quem errou. Aí o método se suicida. A regra de ouro de Ries: comece com tolerância, mire o processo. <strong>'Quem comete um erro e é humilhado aprende uma coisa só: a esconder erros.'</strong> E erro escondido não vira aprendizado — vira tempo-bomba.","tip":"<strong>Vire a chave:</strong> a organização adaptativa ajusta o quanto de processo precisa à medida que cresce — nem o caos da garagem, nem o cartório da multinacional."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 11",
    "lessons": [
      "Os 5 porquês descem do sintoma técnico à causa-raiz, quase sempre humana ou de processo.",
      "Invista em correção na medida da gravidade — nem o excesso da burocracia, nem a falta que repete o erro.",
      "Mire o sistema, não a pessoa; comece tolerante, ou os erros passam a se esconder.",
      "A organização adaptativa equilibra velocidade e disciplina, regulando o próprio ritmo conforme cresce.",
    ],
  },
  {
    "slug": "ch12-inovar",
    "sub": "CAPÍTULO 12: Inovar (Acelerar)",
    "intro": "Como fazer a startup respirar dentro de uma empresa que vive de não errar? Inovação verdadeira precisa de liberdade para falhar, e a máquina de execução existe justamente para eliminar a falha. A resposta de Ries é arquitetura, não heroísmo: construir um porto seguro — o sandbox — onde a equipe experimenta com clientes reais, protegida da máquina ao lado, mas com a conta do resultado no próprio nome.",
    "cards": [
      {"ic":"mountain","t":"Os Três Requisitos","emph":"Três Requisitos","b":"Sem estes três, a inovação interna definha. (1) <strong>Recursos escassos, mas garantidos</strong> — pouco dinheiro ensina foco; dinheiro instável só ensina medo. (2) <strong>Autoridade própria</strong> para decidir sem pedir licença a cada passo. (3) <strong>Pele em jogo</strong>: gente que colhe o crédito ou amarga o prejuízo do que construiu.","tip":"<strong>Como aplicar:</strong> uma equipe pequena, multifuncional e dedicada, dona do experimento de ponta a ponta — não um comitê que opina e some."},
      {"ic":"target","t":"O Sandbox de Experimentação","emph":"Sandbox","b":"Um cercado com <strong>regras claras</strong>: cada experimento toca um número limitado de clientes, tem prazo definido, mede um punhado fixo de métricas acionáveis — e a <strong>mesma equipe</strong> acompanha o resultado do começo ao fim. A liberdade vem das bordas bem marcadas, não da ausência delas.","tip":"<strong>Dupla proteção:</strong> o sandbox blinda a empresa do risco de um experimento dar errado e blinda a equipe da máquina de execução que esmagaria o experimento certo."},
      {"ic":"layers","t":"Gestão de Portfólio","emph":"Portfólio","b":"A empresa madura tem de fazer malabarismo: tocar a <strong>execução do negócio que paga as contas</strong> e a <strong>inovação disruptiva</strong> que talvez pague as de amanhã — com lideranças, métricas e prazos separados. Não dá para cobrar do experimento o que se cobra da operação.","tip":"<strong>Sinal de alerta:</strong> experimentar sem que alguém responda pelo aprendizado é inovação sem dono. Vira teatro de inovação — atividade, não resultado.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 12",
    "lessons": [
      "Inovação interna precisa dos três: recursos seguros, autoridade própria e pele em jogo.",
      "O sandbox protege a empresa do risco e a equipe da máquina, liberando experimentos reais com clientes.",
      "Organizações maduras gerem execução e inovação como carteiras distintas, com réguas distintas.",
      "Inovação é capacidade contínua e com dono, conduzida pela mesma equipe do início ao fim.",
    ],
  },
  {
    "slug": "ch13-epilogo-nao-desperdice",
    "sub": "CAPÍTULO 13: Epílogo — Não Desperdice (Acelerar)",
    "intro": "Vivemos a era mais produtiva da história — e desperdiçamos como nunca. Não desperdiçamos aço nem petróleo: desperdiçamos a coisa mais cara que existe, o talento humano, derramado mês após mês em produtos que ninguém pediu. Para Ries, eliminar esse desperdício é a grande oportunidade do nosso tempo, e a Startup Enxuta é menos um conjunto de táticas que um movimento para devolver sentido ao trabalho.",
    "cards": [
      {"ic":"leaf","t":"Eliminar o Desperdício","emph":"Desperdício","b":"Herança direta da Toyota: desperdício é tudo que <strong>não cria valor para o cliente</strong>. Mas o pior desperdício não é o material refugado — é a <strong>energia humana</strong> queimada no produto errado, o engenheiro brilhante construindo, com capricho, algo que não deveria existir. Cada esforço tem de passar no teste do aprendizado validado.","tip":"<strong>A frase de capa:</strong> ser excelente em construir o que não deveria existir é eficiência apontada para o abismo."},
      {"ic":"target","t":"Produtividade Real","emph":"Produtividade Real","b":"Numa fábrica, produtividade é quanto se produz. Numa startup, é o oposto perigoso de medir: vale <strong>quanto aprendizado validado</strong> se gera, não quantos recursos se entrega. E o gargalo nunca foi a falta de ideias — ideias sobram. Falta o filtro que separa as que merecem virar produto das que só roubam tempo.","tip":"<strong>Vire a chave:</strong> o método enxuto é esse filtro. Não serve para ter mais ideias; serve para não construir as erradas."},
      {"ic":"lens","t":"Honestidade Científica","emph":"Honestidade Científica","b":"O método só funciona com uma virtude difícil: honestidade para deixar o dado contrariar você. O pecado capital é o <strong>experimento desenhado para confirmar</strong> a decisão já tomada — ciência de fachada, em que o resultado já estava escrito antes da pergunta. A Startup Enxuta é movimento vivo, não ritual de autoengano.","tip":"<strong>Sinal de alerta:</strong> se você só festeja o dado que dá razão à sua aposta e descarta o que a desmente, não está testando — está se enganando com método.","warn":True},
    ],
    "lessons_title": "Lições-Chave do Capítulo 13",
    "lessons": [
      "O maior desperdício do nosso tempo é construir com excelência o produto errado — talento humano queimado.",
      "Produtividade real mede aprendizado validado por esforço, não volume de entrega.",
      "Aplique o método com honestidade científica: deixe o dado poder lhe dar errado.",
      "O gargalo nunca foi falta de ideias, mas o filtro que separa as que merecem ser construídas.",
    ],
  },
  {
    "slug": "ch14-juntar-se-ao-movimento",
    "sub": "CAPÍTULO 14: Junte-se ao Movimento (Acelerar)",
    "intro": "Ries fecha onde começou, mas mais alto: a Startup Enxuta nunca foi sobre startups. É um modo de pensar gestão sob incerteza — e incerteza, hoje, está em todo lugar. O convite final não é decorar as técnicas, é juntar-se a um movimento com uma ambição grande: uma economia que desperdice menos do talento humano que já temos. O motor de tudo continua o mesmo: Construir-Medir-Aprender.",
    "cards": [
      {"ic":"spiral","t":"O Ciclo Como Cultura","emph":"Como Cultura","b":"Rodar o ciclo uma vez é técnica; rodá-lo sempre é cultura. A meta é fazer de Construir-Medir-Aprender o <strong>sistema operacional</strong> da organização — o jeito padrão de pensar, não um workshop anual. E, dentro dele, encurtar sem trégua o tempo de cada volta completa.","tip":"<strong>Como aplicar:</strong> internalize o laço a ponto de toda decisão grande virar hipótese a testar, não aposta a defender com o ego."},
      {"ic":"book","t":"Princípios, Não Receitas","emph":"Não Receitas","b":"As ferramentas famosas — MVP de vídeo, conserje, 5 porquês — <strong>envelhecem</strong> e nem sempre cabem no seu caso. O que permanece são os <strong>princípios</strong>: aprendizado validado, experimentação honesta, contabilidade da inovação. Eles você adapta; não copia.","tip":"<strong>Sinal de alerta:</strong> aplicar a ferramenta fora de contexto, esquecendo o princípio que a justifica, é culto à técnica — o MVP virou cargo, não método.","warn":True},
      {"ic":"clock","t":"Gestão de Longo Prazo","emph":"Longo Prazo","b":"Quem pensa em <strong>décadas</strong> precisa de estruturas que premiem o <strong>aprendizado contínuo</strong>, não só o número do trimestre. É aqui que a obra mira mais longe que o produto: o alvo final é uma <strong>economia que desperdice menos talento humano</strong>.","tip":"<strong>Para fechar:</strong> medir só o trimestre asfixia a inovação que só rende em anos. O curto prazo, sozinho, é míope por construção."},
    ],
    "lessons_title": "Lições-Chave do Capítulo 14",
    "lessons": [
      "O alvo final transborda o produto: uma economia que desperdice menos talento humano.",
      "Internalize os princípios e adapte (nunca apenas copie) as técnicas ao seu contexto.",
      "Faça do ciclo Construir-Medir-Aprender o sistema operacional da organização, não um evento.",
      "Estruturas de longo prazo premiam o aprendizado sustentável acima do número do trimestre.",
    ],
  },
]
