# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Story: Os Princípios do Roteiro' (Robert McKee).
Termos canônicos da edição brasileira: Arquitrama, Minitrama, Antitrama,
Incidente Incitante, A Lacuna (The Gap), Ideia de Controle, Cena Obrigatória."""

BOOK = {
  "title": "Story: Os Princípios do Roteiro",
  "author": "Robert McKee",
  "header_light": "STORY",
  "header_bold": "OS PRINCÍPIOS DO ROTEIRO",
  "subtitle": "VISÃO GERAL · O OFÍCIO POR TRÁS DA HISTÓRIA BEM CONTADA",
  "intro": "Não há crise de talento — há crise de ofício. A história não é uma fuga da vida: é o equipamento para vivê-la, a vida abstraída até sobrar só o que tem sentido. McKee não dá receita de sucesso; dá os princípios eternos por baixo de toda história que já comoveu alguém. E o primeiro deles é duro: 75% do trabalho está em desenhar a história, não em escrever as palavras. Você não tem uma história enquanto não tem o Clímax — e tudo, da primeira cena ao Incidente Incitante, existe para forçar o protagonista a atravessar a Lacuna entre o que ele espera do mundo e o que o mundo lhe devolve.",
  "description": "A obra de referência de Robert McKee em cheat sheet — não fórmula, mas forma. O espectro estrutural (Arquitrama, Minitrama, Antitrama); o cenário que liberta ao limitar e o gênero cujas convenções a plateia domina antes de você; estrutura e personagem como uma só coisa vista de dois ângulos; a Ideia de Controle e a Lacuna; o Incidente Incitante que acende o pavio; o design de atos e de cena; Crise, Clímax e Resolução; o Princípio do Antagonismo — fortaleça a oposição, não enfraqueça o herói; a exposição que se dispara como munição; e o método de dentro para fora, das fichas ao diálogo deixado por último.",
  "tags": ["Roteiro", "Narrativa", "Escrita Criativa"],
  "progress": "19 Capítulos",
  "cover": "assets/story-mckee-capa.png",
  "overview_cards": [
    {"ic":"book","t":"Boa História, Bem Contada","b":"O imperativo é duplo e indivisível: uma substância verdadeira — uma visão de vida que ninguém mais teria — casada com uma forma de mestre. Diálogo afiado e descrição bonita não erguem uma história de fundação oca; só a maquiam. <strong>A estrutura é soberana, e vem sempre primeiro.</strong>","tip":"<strong>Regra:</strong> 75% do trabalho está em desenhar a história, não em escrever o texto. Estrutura podre não há diretor, astro ou efeito que salve.","wide":True},
    {"ic":"gap","t":"A Substância é A Lacuna","b":"Toda história nasce de um abismo. O protagonista age esperando uma coisa do mundo; o mundo lhe devolve outra. Esse vão entre expectativa e resultado é a Lacuna — e é ele que arranca do personagem a próxima ação, mais arriscada que a anterior. <strong>Nunca deixe uma ação dar exatamente certo</strong> — exceto na última cena.","tip":"<strong>Modelo mental:</strong> Ação → reação inesperada (a Lacuna) → ação nova e mais difícil. Feche o vão e você fechou a história."},
    {"ic":"sword","t":"O Princípio do Antagonismo","b":"O preceito mais importante e o menos compreendido do ofício: o herói só pode ser tão fascinante quanto as forças que o obrigam a ser. Um roteiro morto ressuscita não pelo protagonista — pelo seu lado negativo. <strong>Não encolha o herói para ele vencer; faça crescer a oposição até ele se erguer à altura dela.</strong>","tip":"<strong>Como aplicar:</strong> 'forças de antagonismo' não é um vilão — é a soma de tudo que se opõe ao desejo, do íntimo do herói às instituições e ao mundo. Construa o negativo primeiro."},
    {"ic":"target","t":"Significado Produz Emoção","b":"O Clímax é uma revolução de valores — uma virada absoluta e irreversível — e ele entrega não um final feliz, mas a única coisa que a plateia veio buscar: a emoção que a narração prometeu. <strong>Significado produz emoção. Não dinheiro, não sexo, não efeitos, não astros.</strong> E é na Crise, não na luta, que o personagem se revela por inteiro.","tip":"<strong>Regra:</strong> dê à plateia o que ela quer, mas nunca do jeito que ela espera. O grande final é, ao mesmo tempo, inevitável e inesperado."},
  ],
}

CHAPTERS = [
 {
  "slug": "ch01-o-problema-da-historia",
  "sub": "CAPÍTULO I: O Problema da História",
  "intro": "Não há excesso de talento no mundo, há escassez de ofício. A história não é fuga da vida — é o instrumento mais fino que temos para entendê-la, a vida destilada até sobrar só o que carrega sentido. O declínio do roteiro não vem da falta de gênios; vem de escritores que trocaram substância por espetáculo e se esqueceram de que existem princípios.",
  "cards": [
   {"ic":"book","t":"Boa História, Bem Contada","emph":"Bem Contada","b":"O imperativo é duplo e indivisível: uma substância verdadeira — sua visão única de vida — casada com uma forma de mestre. <strong>Bom diálogo e descrição bonita não erguem uma história de fundação oca</strong>, só a disfarçam. A estrutura vem sempre primeiro; o resto é acabamento.","tip":"<strong>Teste de viabilidade:</strong> se a estrutura é oca, nenhum diretor, ator ou efeito a salva. Eles agravam o desastre, com orçamento maior."},
   {"ic":"masks","t":"História vs. Vida","emph":"História","b":"A vida é um borrão de horas em fuga, sem forma e sem foco; a história a abstrai até revelar o padrão e o sentido por baixo do caos. <strong>Vamos ao cinema não para escapar da vida, mas para encontrá-la</strong> — para sentir, em segurança, o triunfo e a tragédia que tememos viver.","tip":"<strong>Modelo mental:</strong> a história é equipamento para viver — um ensaio emocional da existência, não um analgésico contra ela."},
   {"ic":"wrench","t":"A Perda do Ofício","emph":"Ofício","b":"Ver mil filmes não ensina a escrever um, como ouvir mil sinfonias não ensina a compô-las. A ilusão de que se absorve o ofício por osmose é a origem da mediocridade. <strong>O que forma o escritor é o autoconhecimento somado ao domínio consciente da forma</strong> — e é esse domínio que libera o subconsciente a entregar o que ele tem de mais original.","tip":"<strong>Regra:</strong> 75% do trabalho está no design da história, não na escrita do texto. A inspiração vem depois da disciplina, nunca antes."},
   {"ic":"target","t":"Substância sobre Espetáculo","emph":"Espetáculo","b":"Encher a tela de efeitos milionários, atuação histriônica e som avassalador para mascarar um vazio cheio de clichês é confissão de derrota. <strong>A plateia é geniosa</strong> — viveu mil histórias e antecipa cada movimento. É preciso todo o ofício para chegar ao próximo beat antes dela.","tip":"<strong>Sinal de alerta:</strong> a 'história pessoal' sem protagonista, sem desejo e sem conflito confunde minúcia realista com verdade dramática. Cópia da vida não é arte.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo I",
  "lessons":[
   "Boa história torna um grande filme possível; história ruim garante o desastre, por melhor que seja o elenco.",
   "Estrutura é soberana: 75% do trabalho está em desenhar a história, não em escrever o texto.",
   "A plateia é genial — use todo o ofício só para chegar ao próximo beat antes dela.",
   "Domínio consciente da forma é o que dá ao subconsciente a coragem de entregar o original.",
  ],
 },
 {
  "slug": "ch02-espectro-estrutural",
  "sub": "CAPÍTULO II: O Espectro Estrutural",
  "intro": "Design não é molde; é um espectro de possibilidades. Num vértice, a Arquitrama — o design clássico que move quase todo o cinema do planeta. Num segundo, a Minitrama, que reduz sem romper. No terceiro, a Antitrama, que inverte para afirmar o absurdo. Antes da primeira linha, decida onde sua história se senta nesse triângulo — porque essa escolha já contrata, em silêncio, o tamanho da sua plateia.",
  "cards": [
   {"ic":"triangle","t":"O Triângulo das Tramas","emph":"Triângulo","b":"No alto está a Arquitrama: protagonista ativo, conflito externo, tempo contínuo, realidade consistente, final fechado — e a vasta maioria do público mundial. <strong>Quanto mais você desce o triângulo, rumo à Minitrama e à Antitrama, menor a plateia</strong>, porque cada degrau o afasta um pouco da experiência humana universal.","tip":"<strong>Regra:</strong> nenhum vértice é superior — mas todo afastamento do clássico cobra um preço em público. Saiba o que está pagando.","wide":True},
   {"ic":"target","t":"Arquitrama (Design Clássico)","emph":"Arquitrama","b":"Um protagonista de vontade luta contra forças sobretudo externas, num tempo contínuo e num mundo de causas e efeitos coerentes, <strong>rumo a um final fechado de mudança absoluta e irreversível</strong>. É a forma mais antiga e mais resistente porque imita a forma como a mente humana lê a vida.","tip":"<strong>Quando usar:</strong> para o público mais amplo — narrativas épicas, heroicas, de ação e de grande arco emocional."},
   {"ic":"person","t":"Minitrama (Minimalismo)","emph":"Minimalismo","b":"Guarda do clássico o suficiente para satisfazer, mas poda seus traços: final aberto, conflito mais interno que externo, protagonista passivo ou um elenco de iguais. <strong>A mudança continua profunda — só que em escala íntima, num sussurro em vez de um trovão.</strong>","tip":"<strong>Quando usar:</strong> dramas de personagem. O final aberto resolve o conflito central e deixa, de propósito, uma pergunta secundária no ar."},
   {"ic":"spiral","t":"Antitrama (Anti-estrutura)","emph":"Anti-estrutura","b":"Inverte de propósito cada princípio clássico para afirmar que a vida é absurda: a coincidência reina, o tempo se fragmenta, a realidade não se sustenta. <strong>Só vive como zombaria deliberada do clássico</strong> — quem não conhece a regra não consegue subvertê-la com sentido.","tip":"<strong>Sinal de alerta:</strong> misturar Arquitrama e Antitrama sem razão temática não ousa — confunde, e perde os dois públicos no 'meio morno'.","warn":True},
   {"ic":"book","t":"Consistência, Não Realidade","emph":"Consistência","b":"O seu mundo não precisa ser o mundo real — precisa ser fiel a si mesmo. Estabelecida a regra (ainda que 'a gravidade falha às terças'), você fica preso a ela até a última cena. <strong>Violar a própria lógica é a marca da Antitrama</strong>; fazê-lo sem querer é amadorismo.","tip":"<strong>Como aplicar:</strong> defina as leis internas de probabilidade do seu mundo e jamais as rompa por conveniência — a plateia perdoa o impossível, nunca o incoerente."},
  ],
  "lessons_title":"Lições-Chave do Capítulo II",
  "lessons":[
   "Decida onde sua história se senta no espectro antes da primeira linha — a escolha já dimensiona o público.",
   "Cada degrau abaixo do design clássico encolhe a plateia; saiba o preço que está pagando.",
   "Só se subverte com sentido a regra que já se domina.",
   "Consistência vale mais que realismo: obedeça às leis que você mesmo criou.",
  ],
 },
 {
  "slug": "ch03-estrutura-e-cenario",
  "sub": "CAPÍTULO III: Estrutura e Cenário",
  "intro": "O cenário não é pano de fundo: é a moldura que decide o que pode e o que não pode acontecer. E essa limitação, longe de prender o escritor, é sua melhor arma contra o clichê. Quanto menor e mais a fundo conhecido o mundo, mais escolhas reais o escritor tem — e mais original a história fica. Quem escreve sobre tudo não conhece nada.",
  "cards": [
   {"ic":"pin","t":"As 4 Dimensões do Cenário","emph":"4 Dimensões","b":"Antes de inventar um único evento, finque as quatro estacas: <strong>Época (o lugar no tempo), Duração (quanto tempo a história abrange), Local (o lugar no espaço) e Nível de Conflito (interno, pessoal, institucional ou ambiental)</strong>. Fora delas, nenhum evento é possível — e é exatamente essa fronteira que torna sua história sua.","tip":"<strong>Como aplicar:</strong> o elenco e os níveis de conflito que ele carrega também são cenário — defina quem habita o mundo antes de definir o que nele acontece."},
   {"ic":"triangle","t":"O Princípio da Limitação Criativa","emph":"Limitação Criativa","b":"Mundo grande, conhecimento raso, poucas escolhas, muito clichê. <strong>Mundo pequeno, conhecimento total, escolhas infinitas.</strong> Uma história honesta tem um, e só um, endereço no tempo e no espaço onde se sente em casa. A restrição não estrangula a criatividade — a obriga a existir.","tip":"<strong>Regra:</strong> crie um mundo que você possa conhecer até o fundo. A limitação inspira; o vasto apenas dilui."},
   {"ic":"book","t":"As 3 Pesquisas","emph":"3 Pesquisas","b":"O bloqueio não é mística — é não ter o que dizer. Cure-o com pesquisa: <strong>Memória, escrevendo o que você viveu; Imaginação, vivendo a vida do personagem hora a hora até a invenção dar um déjà vu; e Fato, indo à biblioteca confirmar e expandir.</strong> A página em branco recua diante de quem sabe.","tip":"<strong>Cuidado:</strong> pesquisa alimenta a imaginação, nunca a substitui — e nunca vira desculpa. Ler sobre o tema não é a mesma coisa que escrever a cena."},
   {"ic":"masks","t":"Criatividade é Dez para Um","emph":"Dez para Um","b":"Para cada cena, invente dez, vinte versões — e fique só com a mais verdadeira ao personagem e ao mundo, aquela que a tela jamais viu. <strong>O gênio não está só em criar: está no gosto e na coragem de exterminar a própria banalidade.</strong>","tip":"<strong>Sinal de alerta:</strong> a primeira ideia que aparece quase sempre é um clichê emprestado de todo filme que você já viu. Não case com ela — durma sobre ela.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo III",
  "lessons":[
   "Finque as quatro dimensões do cenário antes de inventar qualquer evento.",
   "A limitação inspira: o mundo pequeno e conhecível vence o mundo vasto e raso.",
   "Esgote memória, imaginação e fato — depois crie dez versões de cada cena e queime nove.",
   "Fantasia é o gênero mais estrito: um único salto longe do real e, daí em diante, probabilidade de ferro.",
  ],
 },
 {
  "slug": "ch04-estrutura-e-genero",
  "sub": "CAPÍTULO IV: Estrutura e Gênero",
  "intro": "A plateia chega ao cinema já sendo especialista no seu gênero — passou a vida aprendendo o que esperar dele. O escritor não tem escolha: precisa conhecer as convenções mais a fundo do que ela, para cumprir a expectativa e, no mesmo gesto, ultrapassá-la. Não existe escritor 'acima' do gênero — somos todos escritores de gênero.",
  "cards": [
   {"ic":"masks","t":"Convenção, Não Clichê","emph":"Convenção","b":"Convenções são os cenários, papéis, eventos e valores obrigatórios de cada gênero — e ignorá-las não é ousadia, é deixar a plateia faminta. O ofício mora num só ponto: <strong>cumprir a convenção sem cair no clichê</strong>. Rapaz-conhece-moça é convenção; conhecerem-se do jeito que sempre se conhecem é o clichê.","tip":"<strong>Como aplicar:</strong> trate as convenções como velhas amigas que exigem muito. A luta para honrá-las de um jeito nunca visto é o que separa o ofício da preguiça.","wide":True},
   {"ic":"lens","t":"O Método de Estudo de Gênero","emph":"Estudo de Gênero","b":"(1) Liste tudo que se parece com a sua obra — os triunfos e os fracassos; (2) estude cada filme com o roteiro na mão, dissecando-o em cenário, papel, evento e valor; (3) empilhe as análises e olhe através delas: <strong>o que histórias do meu gênero fazem, sem exceção?</strong>","tip":"<strong>Regra:</strong> até você saber a resposta, a plateia sabe mais que você. Ter visto filmes não é conhecer o gênero, como ouvir Beethoven não ensina a compor uma sinfonia."},
   {"ic":"target","t":"Posicionar a Plateia","emph":"Posicionar","b":"Diga cedo que tipo de história é a sua, para que o público chegue aquecido, focado e com fome do que você vai servir. <strong>Shakespeare batizou a peça de A Tragédia de Hamlet para que o Globe entrasse já sabendo que ia chorar.</strong>","tip":"<strong>Sinal de alerta:</strong> prometer um gênero no título e no cartaz e entregar outro mata a obra pela boca da própria plateia traída.","warn":True},
   {"ic":"spiral","t":"Gêneros Evoluem","emph":"Evoluem","b":"Gêneros são janelas para a realidade; quando a realidade muda, ou eles se dobram para acompanhá-la ou petrificam em museu. <strong>Cruzar gêneros é inventar</strong> — com mais de vinte e cinco deles, cada combinação inédita abre um filme que o mundo ainda não viu.","tip":"<strong>Cuidado:</strong> esquecer uma convenção obrigatória — o herói à mercê total do vilão, na Ação — deixa o espectador com uma fome que nada mais sacia."},
   {"ic":"book","t":"Arte vs. 'Filme de Arte'","emph":"Arte","b":"Hitchcock trabalhou puro dentro da Arquitrama e da convenção, para o grande público — e está no panteão. <strong>Não há contradição obrigatória entre arte e sucesso popular</strong>, nem parentesco garantido entre arte e 'Filme de Arte'. A obscuridade não é prova de profundidade.","tip":"<strong>Modelo mental:</strong> a convenção é a rima do contador de histórias. Frost dizia que escrever em verso livre é jogar tênis com a rede abaixada."},
  ],
  "lessons_title":"Lições-Chave do Capítulo IV",
  "lessons":[
   "Conheça seu gênero mais a fundo que a plateia — só assim você antecipa as antecipações dela.",
   "Convenção inspira; clichê mata. Entregue o elemento esperado de um jeito jamais visto.",
   "Gêneros evoluem com a sociedade — escreva o seu como o mundo é agora, não como era.",
   "Não existe contradição obrigatória entre arte e público; a obscuridade não é selo de grandeza.",
  ],
 },
 {
  "slug": "ch05-estrutura-e-personagem",
  "sub": "CAPÍTULO V: Estrutura e Personagem",
  "intro": "Estrutura e personagem são a mesma coisa olhada de dois ângulos. A sucessão de eventos que chamamos de estrutura É a sucessão de escolhas que o personagem faz sob pressão. Por isso 'história movida a personagem' é pleonasmo: não existe trama sem alguém que decida, nem personagem profundo que não se revele decidindo. Toque num, e você tocou no outro.",
  "cards": [
   {"ic":"mask","t":"Personagem vs. Caracterização","emph":"Caracterização","b":"Caracterização é tudo que se observa por fora — idade, profissão, jeito de falar, maneirismos. Personagem verdadeiro é outra coisa, e mais funda: <strong>é o que se revela na escolha sob pressão</strong>. Quanto maior o aperto, mais verdadeira a revelação — e mais distante ela costuma estar da máscara da superfície.","tip":"<strong>Regra:</strong> escreva os papéis principais para que, no fundo, NÃO sejam o que parecem ser. A distância entre a máscara e a verdade é a própria matéria do drama."},
   {"ic":"steps","t":"O Arco de Personagem","emph":"Arco","b":"A grande escrita não só revela o personagem verdadeiro — ela o transforma. Em cinco passos: <strong>mostre a caracterização; revele a natureza por uma escolha; ponha o interior em choque com a máscara; aperte a pressão sem parar; e, no Clímax, deixe que a última escolha o mude por dentro, para sempre.</strong>","tip":"<strong>Como aplicar:</strong> a longevidade vive na contradição. Bond atravessa vinte filmes porque cada um re-revela o assassino frio sob o galã encantador."},
   {"ic":"gap","t":"O Travamento (Interlock)","emph":"Travamento","b":"Mude os eventos e você mudou o personagem; reinvente o personagem por dentro e terá de reinventar os eventos. <strong>Inverta uma só ação decisiva — de quem diz a verdade para quem mente — e, sem mexer numa vírgula da caracterização, você criou um ser inteiramente outro.</strong>","tip":"<strong>Modelo mental:</strong> um personagem mudado precisa viver A história que só ele viveria. Não há como ajustar um lado sem o outro."},
   {"ic":"clock","t":"Guarde o Melhor para o Fim","emph":"o Melhor para o Fim","b":"O cinema é primo da música, da dança e da poesia — uma arte do tempo. E a primeira lei das artes do tempo é uma só: guardarás o melhor para o fim. <strong>Setenta e cinco por cento do trabalho está no design; e setenta e cinco por cento desse está no Clímax do último ato.</strong>","tip":"<strong>Regra:</strong> um filme é, no fundo, os seus últimos vinte minutos. Enquanto você não tem o Clímax, você não tem história — tem material."},
   {"ic":"masks","t":"O Sacrifício de Aristóteles","emph":"Sacrifício","b":"Qualquer traço encantador de caracterização que torne incrível a ação final precisa ir para o lixo: trama acima de caracterização. <strong>No Clímax, o personagem tem de poder e querer fazer exatamente o que faz</strong> — sem 'mas' que a plateia não engula.","tip":"<strong>Sinal de alerta:</strong> proteger um maneirismo simpático às custas da credibilidade do Clímax não salva o personagem — derruba o filme inteiro.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo V",
  "lessons":[
   "Revele o personagem verdadeiro pela escolha sob pressão, em choque com a máscara — e depois faça-o arquear.",
   "A estrutura aperta; o personagem torna a escolha crível. Toque num, e você tocou nos dois.",
   "Gaste o esforço onde a história vive: o design dos eventos e, acima de tudo, o Clímax final.",
   "Cinema é arte do tempo — guarde o melhor para o fim.",
  ],
 },
 {
  "slug": "ch06-estrutura-e-significado",
  "sub": "CAPÍTULO VI: Estrutura e Significado",
  "intro": "A vida divorcia ideia de emoção; a história volta a casá-las. O escritor não prova sua visão de mundo explicando-a — prova-a dramatizando-a. Narrar é a demonstração viva de uma verdade: a ideia que vira ação, e que só convence porque a sentimos antes de entendê-la.",
  "cards": [
   {"ic":"bulb","t":"A Ideia de Controle","emph":"Ideia de Controle","b":"Esqueça a palavra vaga 'tema' e exija de si uma frase exata: Valor + Causa. O valor é a carga — positiva ou negativa — do valor crítico no Clímax final; a causa é a razão principal de ele terminar daquele jeito. <strong>Extraia a ideia da ação, nunca force a ação a servir a ideia.</strong>","tip":"<strong>Como aplicar:</strong> a história lhe revela o significado, não o contrário. Crie o Clímax primeiro; só depois pergunte que valor ele afirma e por qual causa.","wide":True},
   {"ic":"scale","t":"Ideia vs. Contra-Ideia","emph":"Contra-Ideia","b":"Cena a cena, a Ideia e sua Contra-Ideia discutem em voz alta — 'o crime compensa!' contra 'o crime não compensa!' — e a discussão sobe de tom até as duas colidirem na Crise. <strong>Quem vencer o Clímax final torna-se a Ideia de Controle da obra.</strong>","tip":"<strong>Regra:</strong> a progressão se constrói oscilando, com energia, entre as cargas positiva e negativa do valor em jogo — nunca numa linha reta."},
   {"ic":"masks","t":"As 3 Visões","emph":"3 Visões","b":"Idealista: final para cima, a vida como a desejamos. Pessimista: final para baixo, a vida como a tememos. Irônica: as duas ao mesmo tempo. <strong>A ironia — o amor que é prazer e dor na mesma respiração — é a vida no seu estado mais completo</strong>, e por isso a visão mais difícil e mais rica de escrever.","tip":"<strong>Modelo mental:</strong> decida a visão antes do Clímax. Ela é a carga final que vai disciplinar, em silêncio, cada corte da obra."},
   {"ic":"sword","t":"Arme a Oposição","emph":"Oposição","b":"Sua visão não se prova pela eloquência com que você afirma a Ideia de Controle, e sim pela vitória dela sobre as forças poderosíssimas que você arma contra si mesmo. <strong>Os filmes antiguerra de Kubrick funcionam porque admitem, sem pestanejar, que os homens amam a guerra.</strong>","tip":"<strong>Sinal de alerta:</strong> nunca explique — dramatize. Mestre nenhum explica. Didatismo é sermão de fantasia, e a plateia farta o cheira de longe.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo VI",
  "lessons":[
   "Cristalize o significado em uma frase — Valor + Causa — e deixe-a disciplinar cada corte.",
   "Construa da premissa à Ideia de Controle como uma discussão entre Ideia e Contra-Ideia, ambas no auge.",
   "Nunca explique; dramatize. A plateia não precisa só entender — precisa acreditar.",
   "Uma ideia clara gera muitos significados; muitas ideias se anulam em nenhum.",
  ],
 },
 {
  "slug": "ch07-substancia-da-historia",
  "sub": "CAPÍTULO VII: A Substância da História",
  "intro": "Toda história é feita do mesmo material: a Lacuna. É o abismo que se rasga entre o que o protagonista espera do mundo, quando age atrás do seu desejo, e o que o mundo lhe devolve. Não há fumaça, efeito ou reviravolta que dispense esse vão. Sem Lacuna, há atividade na tela — não história.",
  "cards": [
   {"ic":"gap","t":"A Lacuna (The Gap)","emph":"A Lacuna","b":"O protagonista age contando com um certo resultado. O mundo — dentro dele, entre ele e os íntimos, ou lá fora — responde de outro jeito, e abre o vão. <strong>Esse golpe o obriga a se recompor e a partir para uma ação nova e mais arriscada, agora à altura da realidade que ele subestimou.</strong>","tip":"<strong>Regra:</strong> nunca deixe uma ação dar exatamente certo, exceto na resolução final. Onde houver êxito limpo, não há história — abra a Lacuna.","wide":True},
   {"ic":"target","t":"O Protagonista","emph":"Protagonista","b":"Um ser de vontade, com um desejo consciente (e quase sempre um inconsciente que o contradiz), com capacidade convincente de persegui-lo e ao menos uma chance de vencer. <strong>Como um míssil travado no alvo: não para enquanto não atingir o objeto ou for destruído na tentativa.</strong>","tip":"<strong>Sinal de alerta:</strong> se o personagem pode largar o desejo a qualquer momento sem custo, ele não é protagonista — é figurante com mais falas.","warn":True},
   {"ic":"mask","t":"Desejo Consciente vs. Inconsciente","emph":"Inconsciente","b":"O desejo consciente é o que o personagem sabe que quer e declara: 'quero o dinheiro'. O inconsciente é uma necessidade mais funda e quase sempre contrária, que o move sem que ele perceba: 'quero ser punido'. <strong>É o choque entre os dois que produz o conflito interno mais devastador.</strong>","tip":"<strong>Como aplicar:</strong> o atrito entre o desejo declarado e a necessidade que o trai por dentro é o que dá ao personagem mais de uma dimensão."},
   {"ic":"person","t":"Empatia vs. Simpatia","emph":"Empatia","b":"Simpatia é ser querido — 'gosto dele'. Empatia é reconhecimento — 'eu o entendo, há algo dele em mim'. <strong>O protagonista precisa de empatia; de simpatia, não</strong>. Macbeth é um assassino, e ainda assim vivemos sua queda por dentro.","tip":"<strong>Regra:</strong> sem empatia a história morre na poltrona. A plateia tem de farejar, no protagonista, uma humanidade que também é a sua."},
  ],
  "lessons_title":"Lições-Chave do Capítulo VII",
  "lessons":[
   "A história nasce no vão entre o que o personagem espera e o que o mundo de fato lhe entrega.",
   "Sem empatia não há história — a plateia precisa reconhecer-se no protagonista, ainda que ele seja um Macbeth.",
   "O desejo tem de ser forte o bastante para empurrar o protagonista ao limite do humano.",
   "Jamais o deixe vencer de primeira: ação → reação inesperada (a Lacuna) → ação nova e mais difícil.",
  ],
 },
 {
  "slug": "ch08-incidente-incitante",
  "sub": "CAPÍTULO VIII: O Incidente Incitante",
  "intro": "O Incidente Incitante é a causa primeira de tudo que vem depois: o evento que arromba o equilíbrio da vida do protagonista e o atira na história, acendendo nele o desejo de reequilibrar o que foi rompido. Errado o Incidente, errada a história inteira — porque dele descem, em linha reta, todas as cenas até o Clímax.",
  "cards": [
   {"ic":"spark","t":"O Fósforo que Acende","emph":"Fósforo","b":"A vida do protagonista é uma pilha de lenha seca; o Incidente Incitante é a faísca que cai sobre ela. <strong>Uma vez aceso, o fogo da história não se apaga mais — só no Clímax.</strong> E tem de queimar diante dos olhos da plateia, sobre o próprio protagonista.","tip":"<strong>Regra:</strong> ocorra na tela, não no passado contado (backstory) — só assim a plateia sente, na pele, o tranco do desequilíbrio.","wide":True},
   {"ic":"fork","t":"Causal vs. Coincidente","emph":"Coincidente","b":"Causal: alguém escolhe, e a escolha vira a vida de ponta-cabeça — a esposa anuncia que vai embora. Coincidente: o acaso bate, sem causa nem aviso — um disco voador pousa no quintal. <strong>Os dois servem, desde que arranquem do protagonista um desejo e uma ação.</strong>","tip":"<strong>Como aplicar:</strong> calibre o Setup. Cedo demais, a plateia não dimensiona o golpe; tarde demais, ela já bocejou antes do golpe chegar."},
   {"ic":"target","t":"A Espinha (Through-line)","emph":"Espinha","b":"O desejo profundo de restaurar o equilíbrio fixa a espinha dorsal da obra. <strong>Toda ação do protagonista, do Incidente Incitante ao Clímax, tem de pendurar-se nessa única busca</strong> — tirada dela, qualquer cena é gordura.","tip":"<strong>Sinal de alerta:</strong> se o protagonista pode dar de ombros e seguir a vida, aquilo não é o Incidente Incitante — é um evento falso disfarçado de gatilho.","warn":True},
   {"ic":"key","t":"A Promessa da Cena Obrigatória","emph":"Promessa","b":"No instante em que estoura, o Incidente faz uma promessa muda à plateia: 'haverá um confronto final para acertar esta conta'. Esse confronto é a Cena Obrigatória, a Crise. <strong>Se o seu incidente não aponta, claríssimo, para um Clímax necessário, é o incidente errado.</strong>","tip":"<strong>Exemplo:</strong> em Tubarão, o tubarão devora um banhista (coincidente) → a praia deixou de ser segura → matar o bicho (a espinha) → enfrentá-lo no mar aberto (a promessa cumprida)."},
  ],
  "lessons_title":"Lições-Chave do Capítulo VIII",
  "lessons":[
   "É o evento mais importante da obra — se ele falha, tudo que vem atrás rui.",
   "Tem de explodir na tela, para a plateia viver o impacto da ruptura, não ouvir falar dele.",
   "Não basta acontecer: o protagonista precisa reagir — formar um desejo e agir.",
   "Não atrase a ruptura; chegue a ela o quanto antes, sem pular o Setup que a torna legível.",
  ],
 },
 {
  "slug": "ch09-design-de-atos",
  "sub": "CAPÍTULO IX: O Design de Atos",
  "intro": "Atos são a grande arquitetura: beats erguem cenas, cenas erguem sequências, sequências erguem atos. E três grandes reviravoltas são o mínimo para uma história chegar ao fim da linha da experiência humana — ao ponto além do qual nada mais resta a dizer.",
  "cards": [
   {"ic":"layers","t":"Complicação vs. Complexidade","emph":"Complexidade","b":"Complicação é conflito num só dos três níveis — só o externo vira Ação pura, só o pessoal vira novela. Complexidade é conflito nos três ao mesmo tempo: dentro do personagem, entre ele e os próximos, e contra o mundo. <strong>O conselho cabe numa frase: escreva histórias relativamente simples, porém complexas.</strong>","tip":"<strong>Como aplicar:</strong> não multiplique personagens nem locações para parecer rico. Gaste a disciplina em profundidade nos três níveis, não em largura barata."},
   {"ic":"steps","t":"O Pântano do Segundo Ato","emph":"Pântano","b":"O Ato Um leva uns 25%; o último é o mais curto, pura aceleração rumo ao Clímax. Sobra, no meio, um Ato Dois longo e traiçoeiro — o pântano onde tantos roteiros afundam. <strong>Há duas pontes: somar subtramas, cujas reviravoltas caem entre os clímaxes, ou somar atos, criando um clímax de meio.</strong>","tip":"<strong>Cuidado:</strong> cada ato a mais cobra outra cena de virar a cabeça da plateia — convite ao clichê — e ainda corta pela metade a força do Clímax final."},
   {"ic":"pivot","t":"O Ritmo dos Atos (Alternância)","emph":"Alternância","b":"Os dois últimos clímaxes são as cenas mais potentes da obra e ficam a dez ou quinze minutos um do outro — por isso não podem repetir a mesma carga. <strong>Ninguém empilha positivo sobre positivo: 'estava ótimo… e ficou ainda melhor!' não comove, entedia.</strong>","tip":"<strong>Regra:</strong> se o Clímax é irônico, repare para que lado a ironia pende — e faça o penúltimo clímax pender para o lado oposto."},
   {"ic":"link","t":"As 4 Relações de Subtrama","emph":"Subtrama","b":"Uma subtrama justifica sua existência de quatro modos: (1) contradiz a Ideia de Controle, gerando ironia; (2) a ecoa, em variações de tema; (3) prepara o terreno para uma trama central que só explode tarde; ou (4) complica a trama central. <strong>A quarta é a nobre: antagonismo extra empurrando o herói.</strong>","tip":"<strong>Sinal de alerta:</strong> subtrama que não contradiz, não ecoa, não prepara nem complica não enriquece nada — só racha a história ao meio.","warn":True},
   {"ic":"masks","t":"O Falso Final","emph":"Falso Final","b":"Uma cena tão completa que a plateia jura que o filme acabou — E.T. morto na mesa; o duplo arranque final de O Exterminador do Futuro. Arma poderosa, sobretudo na Ação. <strong>Na maioria das obras, porém, o penúltimo clímax deve apertar a Pergunta Dramática: 'e agora?'</strong>","tip":"<strong>Exemplo-modelo:</strong> Kramer vs. Kramer faz quatro reviravoltas memoráveis em três atos — complexidade plena, e nenhuma repetição de carga."},
  ],
  "lessons_title":"Lições-Chave do Capítulo IX",
  "lessons":[
   "Complexidade é conflito simultâneo no interno, no pessoal e no externo — dentro de um elenco e um mundo contidos.",
   "Drene o longo Ato Dois com subtramas ou um clímax de meio-ato; pese o custo de multiplicar atos.",
   "Alterne as cargas dos dois últimos clímaxes — repetir uma corta pela metade a força do filme.",
   "Três atos no mínimo: 'estava ruim, depois bom — fim' sempre soa incompleto.",
  ],
 },
 {
  "slug": "ch10-design-da-cena",
  "sub": "CAPÍTULO X: O Design da Cena",
  "intro": "Toda cena precisa virar. Uma Reviravolta é a mudança na carga de valor da vida do personagem, girando sobre o eixo da Lacuna entre o que ele esperava e o que recebeu. Quando vira de verdade, entrega quatro coisas no mesmo instante: surpresa, curiosidade, revelação e uma nova direção. Cena que não vira é cena que não acontece.",
  "cards": [
   {"ic":"pivot","t":"Plantar e Colher (Setup / Payoff)","emph":"Plantar e Colher","b":"Nenhuma revelação cai do céu: tudo que vira na cena foi plantado antes. O plantio entrega o fato com um sentido aparente; a colheita revela o segundo sentido, o verdadeiro. <strong>Plante firme o bastante para ser lembrado, sutil o bastante para não entregar o jogo.</strong>","tip":"<strong>Regra:</strong> a reviravolta falha quando se prepara demais o óbvio e de menos o inesperado. Cada colheita é o plantio da virada seguinte."},
   {"ic":"bulb","t":"Lógica Retroativa","emph":"Retroativa","b":"Na narrativa, a lógica corre para trás. Imagine primeiro o impensável; depois volte e plante os setups que o tornam inevitável. <strong>A imaginação vem primeiro, livre e sem freios; a razão vem depois, só para construir a ponte.</strong>","tip":"<strong>Como aplicar:</strong> nove de cada dez ideias loucas serão lixo — mas a décima põe borboletas no estômago. Pense o absurdo primeiro, justifique-o depois."},
   {"ic":"scale","t":"A Lei dos Retornos Decrescentes","emph":"Retornos Decrescentes","b":"Quanto mais se repete uma emoção, menos ela cala fundo. Três cenas trágicas em fila: lágrimas, fungada, depois riso nervoso. <strong>Alterne carga positiva e negativa, ou a plateia anestesia.</strong> Só repetir funciona quando o contraste dá ao primeiro golpe um matiz oposto.","tip":"<strong>Sinal de alerta:</strong> emoção de enfeite — a lágrima cintilante, a música furiosa — não substitui a experiência que a deveria provocar.","warn":True},
   {"ic":"fork","t":"Escolha Verdadeira = Dilema","emph":"Dilema","b":"Escolher entre o bem e o mal não é escolha: todo personagem escolhe o que ele lê como bem. A decisão de verdade está entre <strong>bens irreconciliáveis — quer os dois, só pode um — ou males equivalentes — não quer nenhum, tem de levar um.</strong>","tip":"<strong>Como aplicar:</strong> trabalhe em triângulo. Acrescente um terceiro vértice, e ficar com B passa a custar C — e é esse preço que fecha a história."},
   {"ic":"masks","t":"Emoção vs. Sentimento (Mood)","emph":"Sentimento","b":"Emoção é curta e explosiva — e há só duas, prazer e dor. Sentimento, no cinema o clima, é o fundo demorado que dá nome e cor à emoção. <strong>O arco da cena produz a emoção; o clima — luz, ritmo, elenco, trilha — decide de que tom ela será.</strong>","tip":"<strong>Modelo mental:</strong> dois amantes e uma arma, sob luz de verão, dão comédia; os mesmos beats em sombra noturna dão thriller. Os beats são iguais; o clima é tudo."},
  ],
  "lessons_title":"Lições-Chave do Capítulo X",
  "lessons":[
   "Desenhe cada cena para virar sobre um valor, no eixo da Lacuna entre expectativa e resultado.",
   "Alterne as cargas emocionais — a lei dos retornos decrescentes pune toda repetição.",
   "Construa a escolha como dilema em triângulo; decisão de bem-contra-mal não é decisão.",
   "Plante os setups que tornam cada virada, ao mesmo tempo, surpreendente e inevitável.",
  ],
 },
 {
  "slug": "ch11-analise-da-cena",
  "sub": "CAPÍTULO XI: A Análise da Cena",
  "intro": "Nada é o que parece. Toda cena vive em dois andares: o texto — o que se vê, ouve, diz e faz — e o subtexto, a vida verdadeira que pulsa por baixo do comportamento. Por isso, quando uma cena cai dura, o defeito nunca está na superfície do diálogo: está na ação que deveria correr por baixo dele e não corre.",
  "cards": [
   {"ic":"layers","t":"Texto vs. Subtexto","emph":"Subtexto","b":"Texto é a superfície sensorial — imagem, diálogo, ação. Subtexto é o que ferve por baixo — o pensamento e o sentimento que o comportamento esconde. <strong>A lei de Hollywood é cruel e exata: se a cena é só sobre aquilo que a cena diz ser, você está em apuros.</strong>","tip":"<strong>Regra:</strong> escrever 'na lata' joga o subtexto para dentro do texto e não sobra nada para o ator atuar — só recitar.","wide":True},
   {"ic":"lens","t":"A Análise em 5 Passos","emph":"5 Passos","b":"Rode-a em qualquer cena que não respira: (1) nomeie o conflito — o desejo no infinitivo — e o do antagonista; (2) marque o valor de abertura e sua carga; (3) quebre a cena em beats; (4) confira o valor de fechamento; (5) ache a Reviravolta. <strong>Carga igual na abertura e no fechamento = um não-evento.</strong>","tip":"<strong>Como aplicar:</strong> no não-evento até pode ter passado exposição, mas nada aconteceu. A cena precisa fechar com a carga trocada — ou ela não é cena."},
   {"ic":"pivot","t":"O Beat","emph":"Beat","b":"Um beat é uma troca de ação e reação. Batize a ação subtextual com um gerúndio que tenha emoção — 'Implorando a seus pés', 'Ignorando a súplica'. <strong>Um beat novo só nasce quando o comportamento muda de fato</strong>, não quando muda a fala.","tip":"<strong>Diagnóstico:</strong> alinhe os gerúndios da cena e ache o exato instante em que a grande Lacuna se abre — ali, e só ali, está a Reviravolta."},
   {"ic":"mask","t":"O Teste do Lunático","emph":"Lunático","b":"O ator cria a partir do subtexto, nunca do texto. E quem diz e faz exatamente o que pensa e sente não é honesto — é louco. <strong>A máscara pública é a própria condição humana, e dramatizá-la é o trabalho do escritor.</strong>","tip":"<strong>Sinal de alerta:</strong> escreva a cena de amor como uma troca de pneu — que o diálogo fale de macaco e chave de roda, e que o romance jogue todo por baixo.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo XI",
  "lessons":[
   "Cena morta se diagnostica separando texto de subtexto e lendo os beats — nunca lustrando as falas.",
   "Cada beat é um par ação/reação em gerúndios com emoção; a cena tem de fechar numa carga diferente da que abriu.",
   "Confie na leitura mental da plateia: dê ao comportamento uma vida verdadeira por baixo dele.",
   "Até a confissão mais apaixonada esconde, sob si, um andar mais fundo.",
  ],
 },
 {
  "slug": "ch12-composicao",
  "sub": "CAPÍTULO XII: Composição",
  "intro": "Compor é ordenar e amarrar cenas para que a narração suba — cada ciclo de ação cobrando do personagem (e do escritor) mais do que o ciclo anterior. A história avança em espirais que se alargam ou se aprofundam, nunca em linha reta, até o ponto em que não há mais para onde ir: o fim da linha.",
  "cards": [
   {"ic":"spiral","t":"As 4 Progressões","emph":"4 Progressões","b":"Social: alargue o efeito das ações para a sociedade inteira. Pessoal: cave fundo nos laços íntimos e na vida interior. Ascensão Simbólica: vá do particular ao universal. Ascensão Irônica: faça a progressão girar na ironia. <strong>Quando o palco não pode crescer para fora, faça-o crescer para dentro.</strong>","tip":"<strong>Como aplicar:</strong> esgotada a largura, mergulhe nos segredos que se escondem atrás da máscara pública — sempre há mais andar abaixo.","wide":True},
   {"ic":"link","t":"O Princípio da Transição","emph":"Transição","b":"Entre cada duas cenas, encontre o terceiro elemento — algo que as una ou as oponha: um traço, um gesto, um objeto, uma palavra, uma qualidade de luz, um som, uma ideia. <strong>É essa dobradiça invisível que mantém a plateia escorregando macia de um corte ao próximo.</strong>","tip":"<strong>Exemplo:</strong> criança fazendo birra → adulto infantilizado; estufa → bosque. A ponte carrega o espectador inteiro através do corte, sem solavanco."},
   {"ic":"mountain","t":"Ascensão Simbólica","emph":"Ascensão Simbólica","b":"Comece com cenários e papéis que representam apenas a si mesmos; deixe-os acumular carga arquetípica cena a cena. Em O Franco Atirador: o operário vira guerreiro, e o guerreiro vira 'O Caçador', com a Crise no alto da montanha. <strong>O símbolo só age enquanto ninguém o percebe.</strong>","tip":"<strong>Regra de ouro:</strong> aponte o símbolo com o dedo e ele morre na hora. Deixe-o trabalhar abaixo da linha da consciência."},
   {"ic":"pivot","t":"Largo E Profundo ao Mesmo Tempo","emph":"Largo E Profundo","b":"Chinatown se espalha como mancha de óleo — um divórcio → a prefeitura → Los Angeles inteira — e, no mesmo movimento, mergulha para dentro: espancamentos, assassinato, incesto, o passado trágico se repetindo. <strong>É a dupla progressão na sua forma mais elegante.</strong>","tip":"<strong>Sinal de alerta:</strong> repetição episódica — cenas que trocam de lugar mas não de essência — não é progressão. É turismo.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo XII",
  "lessons":[
   "A história tem de subir — alargar no social, aprofundar no pessoal, ascender no símbolo ou girar na ironia.",
   "Ligue cada par de cenas por um terceiro elemento, seja por semelhança, seja por contraste.",
   "Deixe símbolo e ironia agirem por baixo: a plateia deve senti-los, jamais flagrá-los.",
   "Progredir por geografia não é progredir — troque a essência da cena, não só o cenário.",
  ],
 },
 {
  "slug": "ch13-crise-climax-resolucao",
  "sub": "CAPÍTULO XIII: Crise, Clímax e Resolução",
  "intro": "A Crise é a decisão suprema; o Clímax é a ação que ela detona; a Resolução é o fôlego que sobra. Significado produz emoção — não dinheiro, não sexo, não efeitos, não astros. E são esses três movimentos finais que decidem, sem apelação, se tudo que veio antes foi uma história ou apenas datilografia.",
  "cards": [
   {"ic":"fork","t":"A Crise (Cena Obrigatória)","emph":"Crise","b":"O ideograma chinês de crise junta duas faces: perigo e oportunidade. Esgotadas todas as ações menos uma, o protagonista encara, de frente, as forças de antagonismo mais concentradas de toda a sua vida. <strong>Tem de ser dilema de verdade: bens irreconciliáveis, ou o mal menor.</strong>","tip":"<strong>Regra:</strong> a decisão da Crise é um momento de propósito estático — e jamais acontece fora de cena. Represe ali toda a energia para deixá-la explodir no Clímax.","wide":True},
   {"ic":"spark","t":"O Clímax","emph":"Clímax","b":"Uma revolução de valores — do positivo ao negativo ou o contrário, com ou sem ironia — uma virada de carga máxima, absoluta e sem volta. <strong>A ação tem de ser pura e autoevidente; uma única linha de diálogo explicativo a mata.</strong>","tip":"<strong>Como aplicar:</strong> escreva de trás para frente, do Clímax rumo à causa. Toda cena que se pode cortar sem ferir o final deve ser cortada."},
   {"ic":"target","t":"A Lei de Goldman","emph":"Goldman","b":"Dê à plateia o que ela quer — nunca do jeito que ela espera. E o que ela quer não é um final feliz: é satisfação emocional, a emoção que a narração lhe prometeu lá atrás. <strong>Aristóteles já sabia: o final deve ser, ao mesmo tempo, inevitável e inesperado.</strong>","tip":"<strong>Sinal de alerta:</strong> final feliz é dar tudo a todos; final triste é matar todos. Sem a revelação que você reteve até aqui, os dois são amadorismo.","warn":True},
   {"ic":"mountain","t":"A Imagem-Chave","emph":"Imagem-Chave","b":"Uma única imagem dentro da ação climática que concentra todo o significado e toda a emoção da obra — o que Truffaut chamava de Espetáculo e Verdade no mesmo plano. <strong>Decidir custa mais que agir; por isso a Crise, não a porrada, é onde o personagem se revela até o osso.</strong>","tip":"<strong>Modelo mental:</strong> ação banal, sentido devastador — o Clímax de Gente como a Gente é só uma mulher fechando uma mala."},
   {"ic":"book","t":"A Resolução","emph":"Resolução","b":"Serve a três fins: (1) dar clímax a uma subtrama que não coube fechar antes; (2) mostrar a onda de efeitos do Clímax se espalhando pelo elenco; e (3) sempre, a cortina lenta. <strong>São os segundos em que a plateia recobra o fôlego e deixa a sala com dignidade.</strong>","tip":"<strong>Cuidado:</strong> cortar da Crise para outra coisa antes do Clímax esvazia a energia represada. Emende Crise e Clímax num corte direto, sem respiro no meio."},
  ],
  "lessons_title":"Lições-Chave do Capítulo XIII",
  "lessons":[
   "Erga a Crise como o dilema mais duro da obra, mantenha-a estática e revele o personagem na escolha.",
   "Aponte toda cena anterior para o Clímax; reescreva de trás para frente, a partir dele.",
   "Entregue a emoção prometida por uma virada imprevista, coroada por uma Imagem-Chave — e então, a cortina lenta.",
   "Significado produz emoção — não dinheiro, não sexo, não efeitos, não astros.",
  ],
 },
 {
  "slug": "ch14-principio-do-antagonismo",
  "sub": "CAPÍTULO XIV: O Princípio do Antagonismo",
  "intro": "Aqui está o preceito mais importante e o mais mal compreendido de todo o ofício. Um protagonista só pode ser tão fascinante e comovente quanto as forças de antagonismo o obrigam a ser. Por isso, um roteiro morto quase nunca ressuscita pelo herói — ressuscita pelo seu lado negativo. Mostre-me a sua oposição e eu lhe digo o tamanho da sua história.",
  "cards": [
   {"ic":"sword","t":"Fortaleça o Vilão, Não Enfraqueça o Herói","emph":"Fortaleça o Vilão","b":"A natureza humana é poupadora: ninguém gasta mais força do que o estritamente necessário. Só uma oposição avassaladora arranca do personagem — e do escritor — a realização plena. <strong>O protagonista tem de ser um azarão com uma única chance.</strong>","tip":"<strong>Regra:</strong> não encolha o dragão para o herói passar; faça o herói crescer até a altura dele. 'Forças de antagonismo' não é um vilão — é a soma de tudo que se ergue contra o desejo.","wide":True},
   {"ic":"scale","t":"A Declinação Negativa em 4 Estágios","emph":"4 Estágios","b":"Mapeie quão fundo o valor central pode afundar: Positivo → Contrário → Contraditório → Negação da Negação. <strong>Justiça → injustiça branda → injustiça → tirania: o crime que veste a toga, onde quem escreve a lei tem poder sem limite.</strong>","tip":"<strong>Como aplicar:</strong> use a escala como gráfico de autocrítica. Parou no Contraditório? É sólido, mas ainda não é o limite. A grande história desce até a Negação da Negação."},
   {"ic":"layers","t":"Os Negativos Qualitativos","emph":"Qualitativos","b":"Dois negativos não se somam num positivo: na vida, as coisas pioram, pioram e pioram. <strong>E os piores negativos não são mais do mesmo — são de outra qualidade: a mentira escondida no amor, a tirania escondida na lei, o inimigo escondido dentro de si.</strong>","tip":"<strong>Exemplo:</strong> é o ódio disfarçado de amor que eleva Gente como a Gente — como é que uma criança se defende disso?"},
   {"ic":"target","t":"O Problema do Super-Herói","emph":"Super-Herói","b":"Como transformar um deus num azarão? O desenho de Puzo para o Superman: dois foguetes correndo para lados opostos; depois Lois morta; depois a lei do pai erguida contra a mulher que ele ama. <strong>Desenhar o antagonismo É desenhar o herói — não há um sem o outro.</strong>","tip":"<strong>Sinal de alerta:</strong> não confunda um vilão com o antagonismo. A soma das forças inclui a própria natureza do protagonista, seus íntimos, as instituições e o mundo físico.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo XIV",
  "lessons":[
   "A força da história é a força do seu lado negativo. Construa a oposição primeiro.",
   "Mapeie a declinação do valor central em quatro estágios e empurre a narração até o fim da linha.",
   "Os negativos mais fundos são de qualidade, não de grau: a mentira no amor, a tirania na lei, o inimigo em si mesmo.",
   "Nunca enfraqueça o antagonismo para o herói vencer — faça o herói se erguer à altura dele.",
  ],
 },
 {
  "slug": "ch15-exposicao",
  "sub": "CAPÍTULO XV: Exposição",
  "intro": "Exposição são os fatos — de cenário, de biografia, de caracterização — que a plateia precisa conhecer. E o ofício exige que sejam invisíveis: dramatizados dentro do conflito, dosados do menos importante ao mais importante, e jamais entregues à plateia de bandeja. 'Mostre, não conte' não é estilo; é respeito pela inteligência de quem assiste.",
  "cards": [
   {"ic":"sword","t":"Exposição como Munição","emph":"Munição","b":"Toda vez que um fato precisa chegar ao público, faça o personagem usá-lo como arma — para atacar, defender ou convencer outro personagem, nunca para informar o espectador. <strong>Se os dois já sabem do fato e não têm por que dispará-lo um contra o outro, a plateia simplesmente não escuta.</strong>","tip":"<strong>Como aplicar:</strong> esconda a exposição dentro de uma briga. A plateia só absorve fatos enquanto está emocionalmente presa no conflito que os carrega.","wide":True},
   {"ic":"clock","t":"A Regra do Ritmo","emph":"Ritmo","b":"Revele só o que a plateia precisa, e só no instante em que precisa — guardando a exposição mais pesada para o fim. <strong>Revelação tardia tem força de reviravolta: os fatos mais fundos da backstory viram viradas de terceiro ato.</strong>","tip":"<strong>Sinal de alerta:</strong> a cena de informação — dois personagens contando um ao outro o que ambos já sabem, só para o público ouvir — mata a cena no nascimento."},
   {"ic":"lens","t":"As 2 Regras do Flashback","emph":"Flashback","b":"(1) Dramatize o flashback: faça dele uma mini-história com arco próprio, não um despejo de dados. (2) <strong>Nunca volte no tempo antes de acender no espectador a fome de saber</strong> — Casablanca só nos leva a Paris depois que estamos morrendo de curiosidade por aquele passado.","tip":"<strong>Truque:</strong> abrir na descoberta do crime, e não no crime, dispara a curiosidade em duas direções ao mesmo tempo — para trás (como e por quê?) e para frente (quem?)."},
   {"ic":"bubble","t":"O Teste da Narração","emph":"Teste da Narração","b":"Faça a pergunta dura: 'tirando a narração em off, a história continua bem contada?' Se não, reescreva até continuar — e então corte a narração. <strong>Se sim, guarde-a só pela única boa razão de existir: o contraponto</strong>, a ironia e o humor que nenhuma cena entregaria.","tip":"<strong>Sinal de alerta:</strong> narração explicando o filme do começo ao fim transforma a obra num audiolivro milionário, apenas ilustrado.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo XV",
  "lessons":[
   "Converta cada fato necessário em munição disparada dentro do conflito de uma cena.",
   "Dose as revelações: só o necessário, o melhor por último; só volte no tempo depois de criar a fome de saber.",
   "Rode o teste da narração e só a mantenha como contraponto.",
   "Mostre, não conte: explicar a vida à plateia como se fossem crianças é puro desprezo disfarçado.",
  ],
 },
 {
  "slug": "ch16-problemas-e-solucoes",
  "sub": "CAPÍTULO XVI: Problemas e Soluções",
  "intro": "Este é o caixa de ferramentas de McKee para os apuros do ofício: interesse, surpresa, coincidência, comédia, ponto de vista, adaptação, melodrama e os furos de roteiro. Oito dores antigas de quem escreve — e, para cada uma, uma saída que não trai a história.",
  "cards": [
   {"ic":"target","t":"Interesse: Curiosidade + Compaixão","emph":"Curiosidade + Compaixão","b":"Curiosidade prende o intelecto: abra perguntas e faça a plateia aguentar a espera. Compaixão prende a emoção: o público procura o Centro do Bem — o foco positivo onde sua empatia pousa. <strong>E o 'bem' só brilha contra um fundo mais escuro.</strong>","tip":"<strong>Exemplo:</strong> a lealdade dos Corleone num mundo de clãs traiçoeiros; a inteligência fria e cortês de Lecter contra a brutalidade e a mentira ao redor."},
   {"ic":"eye","t":"As 3 Relações com a Plateia","emph":"3 Relações","b":"Mistério: a plateia sabe MENOS que os personagens — só curiosidade. Suspense: sabem o MESMO — curiosidade e compaixão juntas, e é onde vivem nove de cada dez filmes. <strong>Ironia Dramática: a plateia sabe MAIS — só compaixão, o pavor e a piedade de ver vir o que o personagem não vê.</strong>","tip":"<strong>Como aplicar:</strong> misturá-las enriquece. Casablanca conta o passado de Paris em ironia e depois empurra a Crise de Rick para o mistério, e o choque dói mais por isso."},
   {"ic":"spark","t":"Surpresa e Coincidência","emph":"Coincidência","b":"Surpresa de verdade é a Lacuna entre expectativa e resultado seguida de um jorro de revelação — não o susto barato que se esquece em três segundos. <strong>Coincidência: traga-a cedo, nunca depois do meio, e jamais para resolver o final</strong> — esse é o deus ex machina, a salvação que despenca do céu.","tip":"<strong>Regra:</strong> o deus ex machina é o maior pecado do escritor — perdoado só na Antitrama, onde a vida é absurda, e na Comédia, se o herói já sofreu o bastante para merecer a graça.","warn":True},
   {"ic":"masks","t":"Comédia e Melodrama","emph":"Melodrama","b":"O comediante é um idealista enfurecido atacando uma instituição — ache aquilo que de fato te tira do sério. Já o melodrama não nasce do excesso de expressão, e sim da falta de motivação. <strong>A força de um evento tem de igualar a soma das causas que o produzem.</strong>","tip":"<strong>Como aplicar:</strong> não encolha a cena gritada — engorde o desejo que a move. E o teste da comédia é cruel: conte a história inteira sem citar uma única piada e veja se ela ainda diverte."},
   {"ic":"wrench","t":"O Problema dos Furos","emph":"Furos","b":"Se tapar um furo de lógica exige uma cena que só serve para explicar, faça antes a pergunta: a plateia vai notar o furo? Se vai, <strong>exponha-o e negue-o</strong> — um personagem admite 'nem eu sei por que faço isto…', e o público joga a lógica no lixo, satisfeito.","tip":"<strong>Adaptação:</strong> cada meio reina num nível — o romance no interior, o teatro no pessoal, o cinema no externo. Quanto mais puro o romance, pior o filme que ele dá."},
  ],
  "lessons_title":"Lições-Chave do Capítulo XVI",
  "lessons":[
   "Fisgue o intelecto com perguntas e a emoção com um Centro do Bem; escolha Mistério, Suspense ou Ironia de propósito.",
   "Coincidência só na primeira metade; no desfecho, quem comanda são os personagens, nunca o acaso.",
   "Escreva tão grande quanto a motivação que você ergueu; exponha o furo inevitável com charme e sem pedir desculpa.",
   "Melodrama é falta de motivação, não excesso de drama — aumente o desejo, não o volume da cena.",
  ],
 },
 {
  "slug": "ch17-personagem",
  "sub": "CAPÍTULO XVII: Personagem",
  "intro": "Um personagem não é uma pessoa — é uma obra de arte, uma metáfora da natureza humana, mais nítida e mais conhecível do que qualquer um de nós jamais será. O escritor é aquele velho 'verme da mente' medieval: cava uma natureza até o fundo e inventa o único evento capaz de forçá-la a viver até o limite.",
  "cards": [
   {"ic":"target","t":"Personagem Verdadeiro pelo Desejo","emph":"Desejo","b":"O personagem verdadeiro só se expressa na escolha sob dilema — e a chave de tudo é o desejo. Pergunte sem dó: o que ele quer? agora? em breve? na vida toda? o que ele acha que quer, e o que quer sem saber? <strong>Respostas claras a essas perguntas são o domínio do papel.</strong>","tip":"<strong>Como aplicar:</strong> a pressão revela, a escolha define. Pense a fundo a motivação — e depois deixe um resto de mistério, espaço para a plateia completar.","wide":True},
   {"ic":"mask","t":"Dimensão = Contradição","emph":"Contradição","b":"Dimensão é contradição consistente — dentro do personagem profundo (Macbeth, ambição contra culpa) ou entre a máscara e o fundo (um ladrão de gestos finos). <strong>Traços não são dimensões</strong>: gênio das finanças + faixa-preta + saxofonista continua plano como uma mesa de jantar.","tip":"<strong>Sinal de alerta:</strong> o protagonista tem de ser a figura mais dimensional do elenco; do contrário o Centro do Bem desliza para outro — foi o que quase aconteceu em Blade Runner.","warn":True},
   {"ic":"constellation","t":"O Design do Elenco (Sistema Solar)","emph":"Sistema Solar","b":"O protagonista é o sol; os coadjuvantes, planetas; os figurantes, satélites. Todos existem em função da relação que travam com o centro. <strong>Cada um talhado para acender uma contradição diferente do herói: um provoca seu cinismo, outro sua esperança, outro sua coragem.</strong>","tip":"<strong>Cuidado:</strong> figurantes são planos de propósito — mas plano não é tedioso. Um traço bem observado basta, e nada mais."},
   {"ic":"masks","t":"O Personagem Cômico","emph":"Cômico","b":"Dê-lhe uma obsessão que ele é incapaz de enxergar em si — o Avarento de Molière, a certeza de Clouseau de que é um detetive perfeito. <strong>No exato segundo em que o personagem flagra a própria mania, a comédia acaba.</strong>","tip":"<strong>Modelo mental:</strong> ame todos os seus personagens, e os maus mais que os outros — se você não consegue amá-los, não os escreva. Vilão nenhum se acha vilão."},
  ],
  "lessons_title":"Lições-Chave do Capítulo XVII",
  "lessons":[
   "Encontre o desejo, depois a contradição; a pressão revela, a escolha define.",
   "Construa o elenco de dentro para fora, a partir das dimensões do protagonista — e mantenha-o a figura mais funda do tabuleiro.",
   "Para a comédia, dê uma cegueira; para o vilão, dê autojustiça; para todos, dê amor.",
   "Não prenda a motivação a uma causa única — isso diminui o personagem. Deixe sempre um pouco de mistério.",
  ],
 },
 {
  "slug": "ch18-o-texto",
  "sub": "CAPÍTULO XVIII: O Texto",
  "intro": "O texto — diálogo e descrição — são os últimos vinte e cinco por cento do trabalho, e existem para servir ao que corre por baixo. O diálogo espreme o subtexto nas palavras mais atuáveis que houver; a descrição conduz o olho interior do leitor como uma câmera; e um Sistema de Imagens costura, em silêncio, uma poesia que atravessa o filme inteiro sem nunca se anunciar.",
  "cards": [
   {"ic":"bubble","t":"Disciplina do Diálogo","emph":"Diálogo","b":"Diálogo não é conversa — é ação comprimida de propósito em palavras. Diga o máximo no mínimo; mantenha as falas curtas e com som de gente ('ninguém fala assim' é sentença de morte). <strong>Use a frase periódica: empurre para o fim da linha a palavra que carrega todo o sentido.</strong>","tip":"<strong>Regra:</strong> menos é mais. A atriz que estende a xícara não precisa dizer 'Você quer este café, querido?' — a xícara, o gesto e o olhar já disseram tudo."},
   {"ic":"eye","t":"Descrição: a Cena-Mestra","emph":"Cena-Mestra","b":"Escreva no presente vivo e só aquilo que a câmera pode filmar. Em vez de marcar ângulos, quebre a descrição em pequenos parágrafos separados por linhas em branco — cada bloco insinua, de leve, um plano. <strong>Ler o roteiro tem de ser como assistir ao filme.</strong>","tip":"<strong>Como aplicar:</strong> deixe ao diretor e ao ator o trabalho criativo deles. Geral, movimento, close e inserto se sugerem sozinhos pelo recorte do parágrafo."},
   {"ic":"spiral","t":"Sistemas de Imagens","emph":"Sistemas de Imagens","b":"Uma estratégia de motivos que se repetem em imagem e som, do início ao fim, com persistência e variação. <strong>A Imagem Externa importa um símbolo já pronto — bandeira igual a pátria — e é a marca do filme de estudante; a Imagem Interna dá a uma categoria comum um sentido que só existe neste filme.</strong>","tip":"<strong>Exemplo:</strong> As Diabólicas encharca tudo de água e inverte o seu símbolo, que de vida passa a morte e terror.","wide":True},
   {"ic":"book","t":"Mantenha o Símbolo Invisível","emph":"Símbolo Invisível","b":"No instante em que a consciência flagra um símbolo, ele vira curiosidade intelectual neutra, sem força e quase sem sentido. <strong>Tal como a trilha sonora, o símbolo só age abaixo da linha da cognição.</strong>","tip":"<strong>Sinal de alerta:</strong> rotular o símbolo o mata — o laço de Buñuel, na quinta repetição, fez a plateia gritar 'Símbolo!' e rir do filme.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo XVIII",
  "lessons":[
   "Comprima o diálogo em torno do subtexto; termine a fala na palavra que de fato pesa.",
   "Descreva em unidades filmáveis, no presente, que já insinuem o corte.",
   "Construa um ou mais Sistemas de Imagens internos — e os mantenha invisíveis.",
   "Poético não é bonito: é a expressividade do conteúdo levada ao máximo, seja ele qual for.",
  ],
 },
 {
  "slug": "ch19-metodo-do-escritor",
  "sub": "CAPÍTULO XIX: O Método do Escritor",
  "intro": "Entre o escritor que prospera e o que padece, a diferença não é talento: é método. De dentro para fora, ou de fora para dentro. O sábio adia o diálogo o quanto pode, porque escrevê-lo cedo demais estrangula a criatividade — você se apaixona pelas palavras e perde a coragem de derrubar a estrutura por baixo delas.",
  "cards": [
   {"ic":"cards","t":"De Dentro para Fora","emph":"De Dentro para Fora","b":"De seis meses de roteiro, gaste uns quatro antes de escrever a primeira cena de verdade. O caminho: Escaleta em fichas → Pitch → Tratamento (com subtexto, sem diálogo) → Roteiro. <strong>O diálogo escrito por último é, de longe, o melhor que você é capaz de escrever.</strong>","tip":"<strong>Regra:</strong> estrutura primeiro, palavras por último. Descubra o Clímax antes de escrever uma única linha de diálogo.","wide":True},
   {"ic":"cards","t":"A Escaleta (Step-Outline)","emph":"Escaleta","b":"A história inteira contada em passos, em fichas 3×5, uma pilha por ato. Em cada ficha, uma ou duas frases: o que acontece e como a cena vira; no verso, a função estrutural. <strong>Fique meses nas fichas justamente para poder destruir — noventa por cento de tudo que se escreve é, no melhor dos casos, medíocre.</strong>","tip":"<strong>Sinal de alerta:</strong> esboce cada cena de doze jeitos, jogue fora sequências e atos inteiros sem dó. Não se apegue: ache o Clímax e reescreva de trás para frente.","warn":True},
   {"ic":"bubble","t":"O Teste do Pitch","emph":"Pitch","b":"Nunca mostre a escaleta a ninguém — conte a história em dez minutos e observe-a acontecer no rosto de uma pessoa. <strong>Se ela não funciona em dez minutos, como funcionaria em cento e dez? História ruim não melhora por ficar maior.</strong>","tip":"<strong>Marca de aprovação:</strong> o ouvinte sussurra um 'uau' e fica em silêncio. Enquanto a maioria não reagir assim, não avance uma linha."},
   {"ic":"book","t":"O Tratamento e o Roteiro","emph":"Tratamento","b":"Abra cada passo num parágrafo no presente, momento a momento, com todo o subtexto e nenhum diálogo: 'ele quer que ela faça isto, mas ela recusa'. Um tratamento de verdade tem 60, 90 páginas ou mais. <strong>Só então o roteiro corre — uma alegria, a cinco, dez páginas por dia.</strong>","tip":"<strong>Modelo mental:</strong> lembre a fábula da centopeia — estude o ofício membro a membro até o instinto virar conhecimento; e aí, então, você dança. O resto é coragem."},
  ],
  "lessons_title":"Lições-Chave do Capítulo XIX",
  "lessons":[
   "Estrutura primeiro, palavras por último: fichas → pitch → tratamento com subtexto → roteiro.",
   "Crie dez vezes mais do que você vai guardar, e ache o Clímax antes da primeira linha de diálogo.",
   "Teste a história nua, em dez minutos, num rosto humano — e só depois escreva com ousadia.",
   "Escreva todo dia, linha por linha. Além de talento e técnica, o ofício pede coragem.",
  ],
 },
]
