# -*- coding: utf-8 -*-
"""Conteúdo (pt-BR) de 'Story: Os Princípios do Roteiro' (Robert McKee).
Termos canônicos da edição brasileira: Arquitrama, Minitrama, Antitrama,
Incidente Incitante, A Lacuna (The Gap), Ideia de Controle, Cena Obrigatória."""

BOOK = {
  "title": "Story: Os Princípios do Roteiro",
  "author": "Robert McKee",
  "header_light": "STORY",
  "header_bold": "OS PRINCÍPIOS DO ROTEIRO",
  "subtitle": "VISÃO GERAL · ESTRUTURA, PERSONAGEM E SIGNIFICADO",
  "intro": "McKee destila os princípios eternos da narrativa num sistema operável. Estrutura é soberana — 75% do trabalho está em desenhar a história, não em escrever o texto. Do Incidente Incitante e A Lacuna ao Princípio do Antagonismo e ao Clímax: boa história, bem contada.",
  "description": "A bíblia do roteiro de Robert McKee em cheat sheet: o espectro estrutural (Arquitrama, Minitrama, Antitrama), cenário e gênero, estrutura ⇄ personagem, a Ideia de Controle, A Lacuna, o Incidente Incitante, o design de atos e de cena, crise/clímax/resolução, o Princípio do Antagonismo, exposição invisível e o método de dentro para fora.",
  "tags": ["Roteiro", "Narrativa", "Escrita Criativa"],
  "progress": "19 Capítulos",
  "cover": "assets/story-mckee-capa.png",
  "overview_cards": [
    {"ic":"book","t":"Boa História, Bem Contada","b":"O imperativo é duplo: uma substância única e verdadeira (uma verdade sobre a vida) casada com uma forma habilmente construída. Talento literário — bom diálogo, descrição bonita — não salva uma obra estruturalmente falha. <strong>A estrutura é soberana, e vem sempre primeiro.</strong>","tip":"<strong>Regra:</strong> 75% do trabalho está em desenhar a história — não em escrever o texto. Se a estrutura é oca, nenhum diretor, ator ou efeito a salva.","wide":True},
    {"ic":"gap","t":"A Substância é A Lacuna","b":"O motor da história é o abismo entre a expectativa do protagonista e a reação real do mundo quando ele age. <strong>Nunca deixe uma ação ter o êxito exato planejado</strong> — exceto na resolução final. A lacuna o força a se recompor e a uma ação nova e mais difícil.","tip":"<strong>Modelo mental:</strong> Ação → Reação inesperada (A Lacuna) → Nova Ação. É nesse vão que toda história nasce."},
    {"ic":"sword","t":"O Princípio do Antagonismo","b":"O preceito mais importante e menos compreendido do design de história: o protagonista só pode ser tão fascinante quanto as forças que o obrigam a ser. <strong>Não enfraqueça o herói para ele vencer — fortaleça a oposição até ele crescer.</strong> Construa o lado negativo primeiro.","tip":"<strong>Como aplicar:</strong> 'forças de antagonismo' não é um vilão — é a soma de tudo que se opõe ao desejo, do íntimo ao ambiente."},
    {"ic":"target","t":"Significado Produz Emoção","b":"O clímax é uma revolução de valores — uma virada absoluta e irreversível — que entrega a satisfação emocional prometida, e não um final 'feliz'. <strong>Significado produz emoção: não dinheiro, não sexo, não efeitos especiais, não astros.</strong> A Crise, não a luta, revela o personagem mais fundo.","tip":"<strong>Regra:</strong> dê à plateia o que ela quer, mas não do jeito que ela espera — o final deve ser 'inevitável e inesperado'."},
  ],
}

CHAPTERS = [
 {
  "slug": "ch01-o-problema-da-historia",
  "sub": "CAPÍTULO I: O Problema da História",
  "intro": "A história não é fuga da realidade — é o mecanismo mais profundo de compreendê-la. O declínio do roteiro moderno vem da perda do ofício: trocar substância por espetáculo. Boa história, bem contada.",
  "cards": [
   {"ic":"book","t":"Boa História, Bem Contada","emph":"Bem Contada","b":"O imperativo é duplo: uma substância única e verdadeira (uma verdade sobre a vida) casada com uma forma habilmente construída. <strong>Talento literário — bom diálogo, descrição bonita — não salva uma história estruturalmente falha.</strong> A estrutura vem sempre primeiro.","tip":"<strong>Teste de viabilidade:</strong> se a estrutura é oca, nenhum diretor, ator ou efeito a salva."},
   {"ic":"masks","t":"História vs. Vida","emph":"História","b":"A vida é um borrão de horas em fuga; a história dá forma à vida, abstraindo-a para revelar seus padrões e significados. <strong>Vamos ao cinema não para fugir da vida, mas para encontrá-la</strong> — sentir com segurança triunfos e tragédias.","tip":"<strong>Modelo mental:</strong> pense na história como 'equipamento para viver' — um ensaio emocional da existência."},
   {"ic":"wrench","t":"A Perda do Ofício","emph":"Ofício","b":"A crença equivocada de que absorver filmes inconscientemente substitui o estudo rigoroso e formal dos princípios. Experiência é superestimada; <strong>o que forma o escritor é o autoconhecimento somado ao domínio consciente do ofício</strong> — e é ele que libera o subconsciente a entregar o material mais original.","tip":"<strong>Regra:</strong> 75% do trabalho do escritor está no design da história — não na escrita do texto."},
   {"ic":"target","t":"Substância sobre Espetáculo","emph":"Espetáculo","b":"Apoiar-se em efeitos milionários, atuação histriônica e som avassalador para mascarar uma narrativa oca e cheia de clichês. <strong>A plateia é extremamente inteligente</strong> — é preciso todo o ofício para ficar à frente de suas antecipações.","tip":"<strong>Sinal de alerta:</strong> a 'história pessoal' sem protagonista, conflito ou desejo confunde minúcia realista com verdade dramática.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo I",
  "lessons":[
   "Uma boa história torna um bom filme possível; uma história ruim garante o desastre, qualquer que seja o elenco.",
   "Estrutura é soberana: 75% do trabalho está em desenhar a história, não em escrever o texto.",
   "A plateia é genial — use todo o ofício para se antecipar a ela.",
   "Ofício consciente é o que dá segurança ao subconsciente para emergir com originalidade.",
  ],
 },
 {
  "slug": "ch02-espectro-estrutural",
  "sub": "CAPÍTULO II: O Espectro Estrutural",
  "intro": "Design de história não é um molde rígido, mas um espectro de possibilidades: a Arquitrama (design clássico) numa ponta, a Minitrama (minimalismo) na outra, e a Antitrama (anti-estrutura) no extremo. Saiba onde sua história fica antes de escrever.",
  "cards": [
   {"ic":"triangle","t":"O Triângulo das Tramas","emph":"Triângulo","b":"A Arquitrama é o ápice (a vasta maioria do cinema global): protagonista ativo, conflito externo, tempo contínuo, realidade consistente, final fechado. <strong>Descendo o triângulo rumo à Minitrama e à Antitrama, a plateia potencial encolhe</strong> — porque você se afasta da experiência humana universal.","tip":"<strong>Regra:</strong> quanto mais longe do design clássico, menor o público.","wide":True},
   {"ic":"target","t":"Arquitrama (Design Clássico)","emph":"Arquitrama","b":"Um protagonista ativo luta contra forças de antagonismo sobretudo externas, em tempo contínuo e realidade causalmente conectada, <strong>rumo a um final fechado de mudança absoluta e irreversível</strong>.","tip":"<strong>Quando usar:</strong> para o público mais amplo, em narrativas épicas, heroicas ou dinâmicas."},
   {"ic":"person","t":"Minitrama (Minimalismo)","emph":"Minimalismo","b":"Conserva o suficiente do clássico para satisfazer, mas reduz seus traços: final aberto, conflito interno, protagonista passivo ou múltiplos protagonistas. <strong>A mudança é profunda, mas em escala íntima.</strong>","tip":"<strong>Quando usar:</strong> dramas intimistas, centrados em personagem. O final aberto resolve o conflito primário e deixa uma pergunta secundária no ar."},
   {"ic":"spiral","t":"Antitrama (Anti-estrutura)","emph":"Anti-estrutura","b":"Inverte deliberadamente os princípios clássicos para afirmar o absurdo da vida: coincidência, tempo não-linear, realidades inconsistentes. <strong>Só funciona como subversão hábil e proposital do clássico.</strong>","tip":"<strong>Sinal de alerta:</strong> misturar Arquitrama e Antitrama sem razão temática aliena os dois públicos — o 'meio confuso'.","warn":True},
   {"ic":"book","t":"Consistência, Não Realidade","emph":"Consistência","b":"O mundo não precisa ser o mundo real, mas precisa ser uma realidade consistente. Estabelecidas as regras (mesmo 'a gravidade falha às terças'), você deve obedecê-las à risca. <strong>Quebrar as próprias regras é Antitrama.</strong>","tip":"<strong>Como aplicar:</strong> defina as leis internas de probabilidade do seu mundo e nunca as viole — a plateia se sente traída."},
  ],
  "lessons_title":"Lições-Chave do Capítulo II",
  "lessons":[
   "Saiba exatamente onde sua história fica no espectro antes de escrever a primeira linha.",
   "Quanto mais longe do design clássico, menor o público potencial.",
   "Você só pode quebrar as regras depois de dominá-las.",
   "Realidade consistente importa mais que realismo — obedeça às regras que você criou.",
  ],
 },
 {
  "slug": "ch03-estrutura-e-cenario",
  "sub": "CAPÍTULO III: Estrutura e Cenário",
  "intro": "O cenário define e confina as possibilidades de evento — e essa limitação não é camisa de força, é a principal arma contra o clichê. Quanto menor e mais profundamente conhecido o mundo, mais original a história.",
  "cards": [
   {"ic":"pin","t":"As 4 Dimensões do Cenário","emph":"4 Dimensões","b":"Especifique as quatro antes de inventar eventos: <strong>Época (lugar no tempo), Duração (extensão no tempo), Local (lugar no espaço) e Nível de Conflito (interno, pessoal, institucional, ambiental)</strong>.","tip":"<strong>Como aplicar:</strong> o elenco e seus níveis de conflito fazem parte do cenário — defina-os antes dos eventos."},
   {"ic":"triangle","t":"O Princípio da Limitação Criativa","emph":"Limitação Criativa","b":"Quanto maior o mundo, mais diluído o conhecimento do escritor, menos escolhas, mais clichê. <strong>Quanto menor o mundo, mais completo o conhecimento e maiores as escolhas criativas.</strong> Uma história honesta está em casa em um, e só um, lugar e tempo.","tip":"<strong>Regra:</strong> crie um mundo pequeno e conhecível. A limitação inspira — escreva dentro do que você domina."},
   {"ic":"book","t":"As 3 Pesquisas","emph":"3 Pesquisas","b":"Contra o bloqueio ('você travou porque não tem o que dizer'): <strong>Memória — escreva o que viveu; Imaginação — viva a vida do personagem hora a hora até dar déjà vu; Fato — vá à biblioteca, a pesquisa confirma e expande.</strong>","tip":"<strong>Cuidado:</strong> estudo é alimento da imaginação, nunca um fim. Pesquisa não é procrastinação."},
   {"ic":"masks","t":"Criatividade é Dez para Um","emph":"Dez para Um","b":"Invente dez ou vinte versões de cada cena, depois escolha a mais verdadeira ao personagem e ao mundo que nunca esteve assim na tela. <strong>O gênio não está só em criar, mas no gosto e na vontade de exterminar banalidades.</strong>","tip":"<strong>Sinal de alerta:</strong> a primeira ideia que vem à cabeça costuma ser um clichê emprestado de todo filme que você já viu. Durma sobre ela.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo III",
  "lessons":[
   "Defina as quatro dimensões do cenário antes de inventar qualquer evento.",
   "A limitação inspira: um mundo conhecível vence um mundo vasto.",
   "Pesquise memória, imaginação e fato até a saturação — então crie dez opções e queime nove.",
   "Fantasia é o gênero mais estrito: um grande salto da realidade, depois probabilidade rígida.",
  ],
 },
 {
  "slug": "ch04-estrutura-e-genero",
  "sub": "CAPÍTULO IV: Estrutura e Gênero",
  "intro": "A plateia já é especialista em gênero — chega ao cinema com antecipações aprendidas por toda a vida. O escritor precisa dominar as convenções mais a fundo que ela: cumprir a expectativa e, ainda assim, superá-la. 'Somos todos escritores de gênero.'",
  "cards": [
   {"ic":"masks","t":"Convenção, Não Clichê","emph":"Convenção","b":"Convenções são os cenários, papéis, eventos e valores que definem cada gênero. O desafio: <strong>manter a convenção, evitar o clichê</strong>. Rapaz-conhece-moça é convenção; conhecer-se do jeito que sempre se conhecem é o clichê.","tip":"<strong>Como aplicar:</strong> chame as convenções 'como velhas amigas' — a luta para cumpri-las de forma única é o que eleva a história.","wide":True},
   {"ic":"lens","t":"O Método de Estudo de Gênero","emph":"Estudo de Gênero","b":"(1) Liste obras como a sua — êxitos e fracassos; (2) estude os filmes com os roteiros, quebrando cada um em cenário, papel, evento e valor; (3) empilhe as análises e olhe através delas: <strong>o que histórias do meu gênero sempre fazem?</strong>","tip":"<strong>Regra:</strong> até descobrir as respostas, a plateia está à sua frente. Ter visto filmes não é conhecer o gênero, como ouvir Beethoven não ensina a compor sinfonias."},
   {"ic":"target","t":"Posicionar a Plateia","emph":"Posicionar","b":"Fixe o tipo de história na mente do público para que cheguem 'aquecidos e focados, com um apetite que pretendemos saciar'. <strong>Shakespeare titulou A Tragédia de Hamlet para o Globe saber que ia chorar.</strong>","tip":"<strong>Sinal de alerta:</strong> prometer um gênero no título/marketing e entregar outro mata a obra pelo boca a boca.","warn":True},
   {"ic":"spiral","t":"Gêneros Evoluem","emph":"Evoluem","b":"Gêneros são janelas para a realidade; quando a realidade muda, eles dobram ou petrificam. <strong>Misturar gêneros é invenção</strong> — com 25+ gêneros, o cruzamento cria filmes que o mundo nunca viu.","tip":"<strong>Cuidado:</strong> omitir uma convenção obrigatória (o herói à mercê do vilão, na Ação) deixa a plateia insatisfeita."},
   {"ic":"book","t":"Arte vs. 'Filme de Arte'","emph":"Arte","b":"Hitchcock trabalhou puramente dentro da Arquitrama e da convenção, para o grande público, e está no topo do panteão. <strong>Não há contradição necessária entre arte e sucesso popular</strong>, nem ligação necessária entre arte e 'Filme de Arte'.","tip":"<strong>Modelo mental:</strong> convenção é a rima do contador de histórias — Frost: verso livre é tênis com a rede abaixada."},
  ],
  "lessons_title":"Lições-Chave do Capítulo IV",
  "lessons":[
   "Identifique seu gênero e domine as convenções além da expertise da plateia — antecipe as antecipações dela.",
   "Convenções inspiram; clichês matam. Cumpra o elemento esperado de um jeito nunca visto.",
   "Gêneros evoluem com a sociedade — escreva o gênero como o mundo é agora.",
   "Não há contradição entre arte e sucesso popular.",
  ],
 },
 {
  "slug": "ch05-estrutura-e-personagem",
  "sub": "CAPÍTULO V: Estrutura e Personagem",
  "intro": "Estrutura e personagem são uma só coisa vista de dois pontos de vista. A estrutura de eventos É o conjunto de escolhas feitas sob pressão. 'História movida a personagem' é redundância — trama e personagem profundo são o mesmo fenômeno.",
  "cards": [
   {"ic":"mask","t":"Personagem vs. Caracterização","emph":"Caracterização","b":"Caracterização é a soma de todas as qualidades observáveis (idade, profissão, aparência, maneirismos). <strong>Personagem verdadeiro se revela nas escolhas sob pressão</strong> — quanto maior a pressão, mais verdadeira a revelação.","tip":"<strong>Regra:</strong> escreva os papéis principais para que NÃO sejam, no fundo, o que parecem na superfície."},
   {"ic":"steps","t":"O Arco de Personagem","emph":"Arco","b":"A melhor escrita não só revela o personagem verdadeiro — ela o transforma. Cinco passos: <strong>exiba a caracterização; revele a natureza por escolha; contraponha o interior à máscara; aplique pressão crescente; no clímax, as escolhas mudaram o personagem profundamente</strong>.","tip":"<strong>Como aplicar:</strong> a longevidade vive na contradição — Bond dura 20 filmes porque cada um re-revela o matador sob o galã."},
   {"ic":"gap","t":"O Travamento (Interlock)","emph":"Travamento","b":"Mude o design de eventos e você mudou o personagem; reinvente o personagem profundo e terá de reinventar a história. <strong>Inverta uma ação decisiva (de quem diz a verdade para quem mente) e, sem tocar na caracterização, você criou um personagem inteiramente novo.</strong>","tip":"<strong>Modelo mental:</strong> personagem mudado precisa viver A história dele. Toque um, e você toca os dois."},
   {"ic":"clock","t":"Guarde o Melhor para o Fim","emph":"o Melhor para o Fim","b":"O cinema é primo da música, da dança e da poesia — arte temporal. O primeiro mandamento: 'guardarás o melhor para o fim'. <strong>~75% do trabalho vai no design, e 75% disso no clímax do último ato.</strong>","tip":"<strong>Regra:</strong> filmes são sobre seus últimos vinte minutos. Até criar o clímax, você não tem uma história."},
   {"ic":"masks","t":"O Sacrifício de Aristóteles","emph":"Sacrifício","b":"Qualquer traço de caracterização que mine a credibilidade da ação final deve ser sacrificado: trama acima de caracterização. <strong>No clímax, o personagem precisa poder e querer fazer o que faz.</strong>","tip":"<strong>Sinal de alerta:</strong> proteger uma caracterização charmosa às custas da credibilidade do clímax destrói a história.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo V",
  "lessons":[
   "Revele o personagem verdadeiro pela escolha sob pressão, em contradição com a caracterização — depois faça-o arquear.",
   "A estrutura pressiona; o personagem torna as escolhas críveis. Toque um, toca os dois.",
   "Gaste o trabalho onde a história vive: o design de eventos e, acima de tudo, o clímax final.",
   "Cinema é arte temporal: guarde o melhor para o fim.",
  ],
 },
 {
  "slug": "ch06-estrutura-e-significado",
  "sub": "CAPÍTULO VI: Estrutura e Significado",
  "intro": "A história une o que a vida separa: ideia e emoção. O escritor prova sua visão de vida não explicando, mas dramatizando. Narrar é a demonstração criativa da verdade — a conversão da ideia em ação.",
  "cards": [
   {"ic":"bulb","t":"A Ideia de Controle","emph":"Ideia de Controle","b":"Substitui o vago 'tema'. Uma frase = Valor + Causa. O valor é a carga (positiva/negativa) do valor crítico no clímax final; a causa é a principal razão de ele chegar lá. <strong>Extraia a ideia da ação, nunca o contrário.</strong>","tip":"<strong>Como aplicar:</strong> a história te diz o significado — crie o clímax primeiro, depois pergunte que valor ele traz e qual sua causa.","wide":True},
   {"ic":"scale","t":"Ideia vs. Contra-Ideia","emph":"Contra-Ideia","b":"Sequência a sequência, a Ideia positiva e a Contra-Ideia negativa discutem ('o crime compensa!' / 'o crime não compensa!'), ganhando intensidade até colidirem na Crise. <strong>Quem vence o clímax final vira a Ideia de Controle.</strong>","tip":"<strong>Regra:</strong> progressões se constroem movendo-se dinamicamente entre as cargas positiva e negativa dos valores em jogo."},
   {"ic":"masks","t":"As 3 Visões","emph":"3 Visões","b":"Idealista — final para cima, a vida como desejamos; Pessimista — final para baixo, a vida como tememos; Irônica — para cima e para baixo ao mesmo tempo. <strong>A ironia (amor é prazer e dor) é a vida no seu estado mais completo</strong> — a visão mais difícil e mais rica.","tip":"<strong>Modelo mental:</strong> escolha a visão antes do clímax — ela é a carga final que disciplina cada corte da obra."},
   {"ic":"sword","t":"Arme a Oposição","emph":"Oposição","b":"A prova da sua visão não é o quão bem você afirma a Ideia de Controle, mas a vitória dela sobre as forças poderosíssimas que você reúne contra ela. <strong>Os filmes antiguerra de Kubrick funcionam porque admitem que os homens amam a guerra.</strong>","tip":"<strong>Sinal de alerta:</strong> nunca explique — dramatize. Mestres narradores não explicam. Didatismo é sermão disfarçado.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo VI",
  "lessons":[
   "Expresse o significado como Valor + Causa numa frase — e deixe-o disciplinar cada corte.",
   "Construa da Premissa à Ideia de Controle como uma discussão entre Ideia e Contra-Ideia, ambas no auge.",
   "Nunca explique; dramatize. A plateia não precisa só entender — precisa acreditar.",
   "Uma ideia clara gera muitos significados; muitas ideias implodem em nada.",
  ],
 },
 {
  "slug": "ch07-substancia-da-historia",
  "sub": "CAPÍTULO VII: A Substância da História",
  "intro": "A substância da história é A Lacuna — o abismo que se abre entre a expectativa do protagonista e a reação real do mundo quando ele age para perseguir seu desejo.",
  "cards": [
   {"ic":"gap","t":"A Lacuna (The Gap)","emph":"A Lacuna","b":"O protagonista age esperando um certo resultado. O mundo (interno, pessoal ou extrapessoal) reage diferente do esperado, abrindo uma lacuna. <strong>Isso o força a se recompor e tomar uma ação nova e mais difícil, atravessando a lacuna.</strong>","tip":"<strong>Regra:</strong> nunca deixe uma ação ter o êxito exato planejado — exceto na resolução final. Sempre abra uma lacuna.","wide":True},
   {"ic":"target","t":"O Protagonista","emph":"Protagonista","b":"Um personagem de vontade, com desejo consciente (e/ou inconsciente), capacidade de persegui-lo de forma convincente e ao menos uma chance de alcançá-lo. <strong>Como um míssil teleguiado: travado no objeto, não para até alcançá-lo ou ser destruído.</strong>","tip":"<strong>Sinal de alerta:</strong> se o personagem pode desistir facilmente, não é um protagonista de verdade.","warn":True},
   {"ic":"mask","t":"Desejo Consciente vs. Inconsciente","emph":"Inconsciente","b":"Consciente: o que o personagem sabe que quer e enuncia ('quero o dinheiro'). Inconsciente: uma necessidade mais profunda, muitas vezes contraditória, que o move sem que ele perceba ('quero ser punido'). <strong>O choque entre os dois cria o conflito interno mais forte.</strong>","tip":"<strong>Como aplicar:</strong> o atrito entre o desejo declarado e a necessidade oculta gera a personagem mais rica."},
   {"ic":"person","t":"Empatia vs. Simpatia","emph":"Empatia","b":"Simpatia é ser querido ('eu me importo com ele'). Empatia é identificação ('eu o compreendo; sou como ele'). <strong>O protagonista precisa ser empático, mas não precisa ser simpático</strong> — vide Macbeth.","tip":"<strong>Regra:</strong> um protagonista sem empatia mata a história. A plateia precisa ver uma humanidade compartilhada."},
  ],
  "lessons_title":"Lições-Chave do Capítulo VII",
  "lessons":[
   "A história nasce no espaço entre o que o personagem espera e o que de fato acontece.",
   "Um protagonista sem empatia mata a história — a plateia precisa reconhecer-se nele.",
   "O desejo deve ser forte o bastante para empurrar o protagonista ao limite humano.",
   "Não deixe o personagem vencer na primeira tentativa: Ação → Reação inesperada (A Lacuna) → Nova Ação.",
  ],
 },
 {
  "slug": "ch08-incidente-incitante",
  "sub": "CAPÍTULO VIII: O Incidente Incitante",
  "intro": "O Incidente Incitante é a causa primária de tudo o que se segue: o evento que desequilibra radicalmente a vida do protagonista e o lança na história, despertando o desejo de restaurar o equilíbrio.",
  "cards": [
   {"ic":"spark","t":"O Fósforo que Acende","emph":"Fósforo","b":"A vida do protagonista é uma pilha de lenha seca; o Incidente Incitante é a faísca. <strong>Uma vez aceso, o fogo (a história) não se apaga até o clímax.</strong> Deve acontecer na tela e atingir o protagonista.","tip":"<strong>Regra:</strong> tem de ocorrer na tela — não na história pregressa (backstory) — para a plateia sentir o impacto emocional do desequilíbrio.","wide":True},
   {"ic":"fork","t":"Causal vs. Coincidente","emph":"Coincidente","b":"Causal: uma escolha ativa de um personagem desequilibra a vida (a esposa decide partir). Coincidente: um evento aleatório e sem causa (um disco voador pousa no quintal). <strong>Ambos servem — desde que forcem o desejo.</strong>","tip":"<strong>Como aplicar:</strong> equilibre o Setup — cedo demais, a plateia não entende o impacto; tarde demais, ela se entedia."},
   {"ic":"target","t":"A Espinha (Through-line)","emph":"Espinha","b":"O desejo profundo de restaurar o equilíbrio cria a espinha da história. <strong>Toda ação do protagonista, do Incidente Incitante ao Clímax, deve ser unificada por essa única busca.</strong>","tip":"<strong>Sinal de alerta:</strong> se o protagonista pode ignorar o evento, não é o Incidente Incitante — é falso.","warn":True},
   {"ic":"key","t":"A Promessa da Cena Obrigatória","emph":"Promessa","b":"No instante em que ocorre, o Incidente faz uma promessa: 'haverá um confronto final para resolver isto'. Essa é a Cena Obrigatória (a Crise). <strong>Se o seu incidente não aponta claramente para um clímax necessário, é o incidente errado.</strong>","tip":"<strong>Exemplo:</strong> em Tubarão, o tubarão come um banhista (coincidente) → a cidade não está mais segura → matar o tubarão (a espinha) → enfrentá-lo no mar (a promessa)."},
  ],
  "lessons_title":"Lições-Chave do Capítulo VIII",
  "lessons":[
   "É o evento mais importante da história — se ele falha, o resto desaba.",
   "Tem de acontecer na tela, para a plateia viver o impacto emocional da ruptura.",
   "O protagonista precisa reagir: formar um desejo e agir.",
   "Não atrase: chegue à ruptura o quanto antes, sem sacrificar o setup necessário.",
  ],
 },
 {
  "slug": "ch09-design-de-atos",
  "sub": "CAPÍTULO IX: O Design de Atos",
  "intro": "Atos são a macroestrutura: beats constroem cenas, cenas constroem sequências, sequências constroem atos. Três grandes reviravoltas são o mínimo para uma obra atingir 'o fim da linha' da experiência humana.",
  "cards": [
   {"ic":"layers","t":"Complicação vs. Complexidade","emph":"Complexidade","b":"Complicação = conflito em apenas UM dos três níveis (só extrapessoal → Ação; só pessoal → novela). Complexidade = conflito nos três níveis ao mesmo tempo. <strong>Conselho: histórias 'relativamente simples, mas complexas'.</strong>","tip":"<strong>Como aplicar:</strong> não multiplique personagens nem locações — gaste a disciplina em complexidade rica."},
   {"ic":"steps","t":"O Pântano do Segundo Ato","emph":"Pântano","b":"Ato Um ≈ 25%; o último ato é o mais curto (aceleração ao clímax); sobra um Ato Dois longo — o 'pântano'. <strong>Duas curas: adicionar subtramas (suas reviravoltas caem entre os clímaxes) ou adicionar atos (clímax do meio).</strong>","tip":"<strong>Cuidado:</strong> cada ato extra exige outra cena brilhante (convida ao clichê) e divide pela metade o impacto do clímax."},
   {"ic":"pivot","t":"O Ritmo dos Atos (Alternância)","emph":"Alternância","b":"Os dois últimos clímaxes são as cenas mais fortes e ficam a 10–15 min um do outro — não podem repetir a mesma carga. <strong>Não se monta final positivo com positivo ('estava ótimo… e ficou ainda melhor!').</strong>","tip":"<strong>Regra:</strong> se o clímax é irônico, veja para que lado a ironia pende — e contradiga esse lado no clímax penúltimo."},
   {"ic":"link","t":"As 4 Relações de Subtrama","emph":"Subtrama","b":"A subtrama pode (1) contradizer a Ideia de Controle (gera ironia), (2) ressoá-la (variações de tema), (3) preparar uma trama central tardia, ou (4) complicar a trama central. <strong>A quarta é a mais importante: antagonismo adicional.</strong>","tip":"<strong>Sinal de alerta:</strong> subtrama que não contradiz, ressoa, prepara nem complica racha a história ao meio.","warn":True},
   {"ic":"masks","t":"O Falso Final","emph":"Falso Final","b":"Uma cena tão completa que a plateia pensa que o filme acabou (E.T. morto; o duplo falso final de O Exterminador do Futuro) — útil sobretudo na Ação. <strong>Na maioria, o penúltimo clímax deve intensificar a Pergunta Dramática: 'E agora?'</strong>","tip":"<strong>Exemplo-modelo:</strong> Kramer vs. Kramer — quatro reviravoltas memoráveis em três atos: dá complexidade e evita repetição."},
  ],
  "lessons_title":"Lições-Chave do Capítulo IX",
  "lessons":[
   "Complexidade = conflito simultâneo nos níveis interno, pessoal e extrapessoal — num elenco e mundo contidos.",
   "Resolva o longo Ato Dois com subtramas ou um clímax de meio-ato; respeite o custo de multiplicar atos.",
   "Alterne as cargas dos seus dois últimos clímaxes — repetição corta pela metade a força do filme.",
   "Três atos no mínimo: 'estava ruim, depois bom — fim' sempre parece incompleto.",
  ],
 },
 {
  "slug": "ch10-design-da-cena",
  "sub": "CAPÍTULO X: O Design da Cena",
  "intro": "Toda cena deve ser uma Reviravolta (Turning Point): uma mudança na carga de valor da vida do personagem, girando sobre a lacuna entre expectativa e resultado. A reviravolta entrega quatro coisas de uma vez: surpresa, curiosidade, revelação e nova direção.",
  "cards": [
   {"ic":"pivot","t":"Plantar e Colher (Setup / Payoff)","emph":"Plantar e Colher","b":"Toda revelação numa reviravolta deve ter sido plantada antes. O plantio insere o conhecimento com um sentido aparente; a colheita entrega seu segundo sentido, mais verdadeiro. <strong>Plante firme o bastante para ser lembrado, sutil o bastante para não entregar.</strong>","tip":"<strong>Regra:</strong> reviravoltas falham quando se prepara demais o óbvio e de menos o inusitado. Um payoff vira o setup da próxima virada."},
   {"ic":"bulb","t":"Lógica Retroativa","emph":"Retroativa","b":"'Na narrativa, a lógica é retroativa.' Pense o impensável primeiro; depois volte e plante os setups que o tornam racional. <strong>A imaginação é primária e pré-condicional; a razão é secundária e pós-criativa.</strong>","tip":"<strong>Como aplicar:</strong> nove em dez ideias loucas serão inúteis — mas uma pode pôr borboletas no estômago. Pense primeiro, justifique depois."},
   {"ic":"scale","t":"A Lei dos Retornos Decrescentes","emph":"Retornos Decrescentes","b":"Quanto mais repetimos uma emoção, menos efeito ela tem. Três cenas trágicas seguidas: lágrimas, fungadas, depois riso. <strong>Alterne cargas positivas e negativas.</strong> A exceção: repetir só funciona quando o contraste dá ao primeiro evento um matiz oposto.","tip":"<strong>Sinal de alerta:</strong> emoção por decoração (lágrimas brilhantes, música raivosa) não substitui a experiência que a causa.","warn":True},
   {"ic":"fork","t":"Escolha Verdadeira = Dilema","emph":"Dilema","b":"Escolher entre bem e mal não é escolha — todo personagem escolhe o 'bem' como ele o percebe. <strong>A escolha real está entre bens irreconciliáveis (quer os dois, só pode um) ou o mal menor (não quer nenhum, tem de levar um).</strong>","tip":"<strong>Como aplicar:</strong> use o design triangular — adicione um terceiro vértice e escolher B significa sacrificar C, e esse preço encerra a história."},
   {"ic":"masks","t":"Emoção vs. Sentimento (Mood)","emph":"Sentimento","b":"Emoção é curta e explode (só existem duas: prazer e dor); sentimento (no cinema, o clima) é o pano de fundo de longo prazo que torna a emoção específica. <strong>O arco da cena dá a emoção; o clima (luz, ritmo, elenco, trilha) a colore.</strong>","tip":"<strong>Modelo mental:</strong> a mesma cena de amantes e uma arma, em luz de verão, é comédia; nos mesmos beats em sombras noturnas, é thriller."},
  ],
  "lessons_title":"Lições-Chave do Capítulo X",
  "lessons":[
   "Desenhe cada cena para virar sobre um valor, via lacuna entre expectativa e resultado.",
   "Alterne as cargas emocionais — os retornos decrescentes punem a repetição.",
   "Construa escolhas como dilemas em triângulos; decisões de bem-contra-mal são triviais.",
   "Plante os setups que tornam cada virada surpreendente e inevitável.",
  ],
 },
 {
  "slug": "ch11-analise-da-cena",
  "sub": "CAPÍTULO XI: A Análise da Cena",
  "intro": "Nada é o que parece: cada cena vive em dois níveis — texto (o que se vê, ouve, diz, faz) e subtexto (a vida interior sob o comportamento). Quando uma cena fracassa, o defeito nunca está na superfície do diálogo, e sim na ação por baixo dela.",
  "cards": [
   {"ic":"layers","t":"Texto vs. Subtexto","emph":"Subtexto","b":"Texto é a superfície sensorial (imagens, diálogo, ação). Subtexto é a vida sob a superfície — pensamentos e sentimentos ocultos pelo comportamento. <strong>A lei de Hollywood: 'se a cena é sobre o que a cena é sobre, você está em apuros'.</strong>","tip":"<strong>Regra:</strong> escrever 'na cara' põe o subtexto no texto e não deixa nada para o ator atuar.","wide":True},
   {"ic":"lens","t":"A Análise em 5 Passos","emph":"5 Passos","b":"Rode-a em qualquer cena que 'cai dura': (1) defina o conflito (desejo no infinitivo) e o do antagonista; (2) anote o valor de abertura e sua carga; (3) quebre em beats; (4) compare o valor de fechamento; (5) ache a Reviravolta. <strong>Mesma carga na abertura e no fechamento = não-evento.</strong>","tip":"<strong>Como aplicar:</strong> num não-evento, pode ter passado exposição, mas nada aconteceu — a cena precisa virar de carga."},
   {"ic":"pivot","t":"O Beat","emph":"Beat","b":"Um beat é uma troca de ação/reação. Nomeie a ação subtextual com um gerúndio emotivo ('Implorando a seus pés' / 'Ignorando a súplica'). <strong>Um novo beat começa só quando o comportamento muda claramente.</strong>","tip":"<strong>Diagnóstico:</strong> trace os gerúndios e ache o instante exato em que a grande lacuna se abre — ali está a reviravolta."},
   {"ic":"mask","t":"O Teste do Lunático","emph":"Lunático","b":"Atores criam a partir do subtexto, não do texto. Pessoas que dizem e fazem exatamente o que pensam e sentem não são honestas — são insanas. <strong>A máscara pública é a condição humana que o escritor deve dramatizar.</strong>","tip":"<strong>Sinal de alerta:</strong> escreva a cena de amor como uma troca de pneu — que o diálogo seja macaco e chave de roda, e o romance jogue por baixo.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo XI",
  "lessons":[
   "Diagnostique cenas mortas separando texto de subtexto e analisando beats — nunca polindo falas.",
   "Cada beat é um par ação/reação em gerúndios emotivos; a cena deve fechar numa carga diferente da que abriu.",
   "Confie na leitura mental da plateia: dê ao comportamento uma vida verdadeira por baixo.",
   "Até a confissão mais apaixonada esconde um nível mais profundo.",
  ],
 },
 {
  "slug": "ch12-composicao",
  "sub": "CAPÍTULO XII: Composição",
  "intro": "Composição é a ordenação e a ligação de cenas para que a narração progrida — cada ciclo de ação exigindo mais dos personagens (e do escritor) que o anterior, em espirais que se alargam ou se aprofundam, até o fim da linha.",
  "cards": [
   {"ic":"spiral","t":"As 4 Progressões","emph":"4 Progressões","b":"Social — alargue o impacto das ações para a sociedade; Pessoal — aprofunde nos laços íntimos e na vida interior; Ascensão Simbólica — vá do particular ao universal; Ascensão Irônica — gire a progressão na ironia. <strong>Se o cenário não pode ir mais amplo, vá mais fundo.</strong>","tip":"<strong>Como aplicar:</strong> quando não dá para alargar o palco, mergulhe nos segredos por trás da máscara pública.","wide":True},
   {"ic":"link","t":"O Princípio da Transição","emph":"Transição","b":"Entre cada duas cenas, ache o terceiro elemento — algo em comum ou em contraponto: um traço, uma ação, um objeto, uma palavra, uma qualidade de luz, um som, uma ideia. <strong>A dobradiça mantém a plateia fluindo pelos cortes.</strong>","tip":"<strong>Exemplo:</strong> criança birrenta → adulto infantil; estufa → bosque. A ligação carrega o espectador através do corte."},
   {"ic":"mountain","t":"Ascensão Simbólica","emph":"Ascensão Simbólica","b":"Comece com cenários e papéis que representam só a si mesmos; deixe-os acumular carga arquetípica. Em O Franco Atirador: operário → guerreiro → 'O Caçador', com a crise no topo da montanha. <strong>O símbolo só funciona enquanto não é notado.</strong>","tip":"<strong>Regra de ouro:</strong> rotule o símbolo e ele morre — deixe-o agir abaixo da consciência."},
   {"ic":"pivot","t":"Largo E Profundo ao Mesmo Tempo","emph":"Largo E Profundo","b":"Chinatown se espalha como uma mancha de óleo (um divórcio → a prefeitura → toda Los Angeles) e, simultaneamente, mergulha para dentro (espancamentos, assassinato, incesto, o passado trágico se repetindo). <strong>A dupla progressão elegante.</strong>","tip":"<strong>Sinal de alerta:</strong> repetição episódica — cenas que mudam de local mas não de essência — não é progressão; é geografia.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo XII",
  "lessons":[
   "Uma história precisa progredir — alargar socialmente, aprofundar pessoalmente, ascender simbolicamente ou girar ironicamente.",
   "Ligue cada par de cenas com um terceiro elemento, por semelhança ou contraponto.",
   "Deixe símbolos e ironia agirem de forma subliminar; a plateia deve senti-los, nunca vê-los.",
   "Progressão por geografia não é progressão — mude a essência, não só o lugar.",
  ],
 },
 {
  "slug": "ch13-crise-climax-resolucao",
  "sub": "CAPÍTULO XIII: Crise, Clímax e Resolução",
  "intro": "Crise é a decisão suprema; Clímax é a ação que essa decisão desencadeia. 'Significado produz emoção. Não dinheiro; não sexo; não efeitos especiais; não astros.' Os três movimentos finais decidem se tudo que veio antes foi história ou datilografia.",
  "cards": [
   {"ic":"fork","t":"A Crise (Cena Obrigatória)","emph":"Crise","b":"O ideograma chinês: Perigo/Oportunidade. Esgotadas todas as ações menos uma, o protagonista encara as forças de antagonismo mais concentradas de sua vida. <strong>Deve ser dilema verdadeiro: bens irreconciliáveis ou mal menor.</strong>","tip":"<strong>Regra:</strong> a decisão da Crise é um momento deliberadamente estático — nunca fora de cena. Represe a energia e deixe explodir no Clímax.","wide":True},
   {"ic":"spark","t":"O Clímax","emph":"Clímax","b":"Uma revolução de valores — do positivo ao negativo ou vice-versa, com ou sem ironia — uma virada de carga máxima, absoluta e irreversível. <strong>A ação deve ser pura e autoevidente: nada de diálogo explicativo.</strong>","tip":"<strong>Como aplicar:</strong> escreva de trás para frente — do clímax à causa. Se uma cena pode ser cortada sem perturbar o final, ela deve ser cortada."},
   {"ic":"target","t":"A Lei de Goldman","emph":"Goldman","b":"Dê à plateia o que ela quer — mas não do jeito que ela espera. E o que ela quer não é um final feliz, e sim satisfação emocional: a emoção que a narração prometeu. <strong>Aristóteles: o final deve ser 'inevitável e inesperado'.</strong>","tip":"<strong>Sinal de alerta:</strong> final feliz = dar tudo a todos; final triste = matar todos. Sem a revelação retida, é amadorismo.","warn":True},
   {"ic":"mountain","t":"A Imagem-Chave","emph":"Imagem-Chave","b":"Uma imagem dentro da ação climática que concentra todo o significado e emoção (Truffaut: 'Espetáculo e Verdade'). <strong>Decisões custam mais que ações — por isso a Crise, não a luta, é onde o personagem se revela mais fundo.</strong>","tip":"<strong>Modelo mental:</strong> ação trivial, significado avassalador — o clímax de Gente como a Gente é uma mulher arrumando uma mala."},
   {"ic":"book","t":"A Resolução","emph":"Resolução","b":"Três usos: (1) dar clímax a uma subtrama que não pôde resolver antes; (2) mostrar o espalhamento dos efeitos do clímax pelo elenco; (3) sempre, a cortina lenta. <strong>Segundos para a plateia recobrar o fôlego e sair do cinema com dignidade.</strong>","tip":"<strong>Cuidado:</strong> cortar da Crise para outro material antes do Clímax drena a energia represada — emende Crise e Clímax num corte direto."},
  ],
  "lessons_title":"Lições-Chave do Capítulo XIII",
  "lessons":[
   "Construa a Crise como o dilema mais difícil da história, mantenha-o estático e revele o personagem na escolha.",
   "Aponte toda cena anterior para o Clímax; reescreva de trás para frente a partir dele.",
   "Entregue a emoção prometida por uma virada imprevista, coroada por uma Imagem-Chave — depois, a cortina lenta.",
   "Significado produz emoção — não dinheiro, sexo, efeitos ou astros.",
  ],
 },
 {
  "slug": "ch14-principio-do-antagonismo",
  "sub": "CAPÍTULO XIV: O Princípio do Antagonismo",
  "intro": "'O princípio do antagonismo é o preceito mais importante e menos compreendido do design de história.' Um protagonista só pode ser tão fascinante e comovente quanto as forças de antagonismo o obrigam a ser. Um roteiro morto ressuscita pelo seu lado negativo.",
  "cards": [
   {"ic":"sword","t":"Fortaleça o Vilão, Não Enfraqueça o Herói","emph":"Fortaleça o Vilão","b":"A natureza humana é conservadora: ninguém faz mais do que precisa. Só uma oposição avassaladora força o personagem (e o escritor) à realização plena. <strong>O protagonista deve ser um azarão com apenas uma chance.</strong>","tip":"<strong>Regra:</strong> não encolha o dragão; faça crescer o herói. 'Forças de antagonismo' não é um vilão — é a soma de tudo que se opõe ao desejo.","wide":True},
   {"ic":"scale","t":"A Declinação Negativa em 4 Estágios","emph":"4 Estágios","b":"Mapeie os graus de negatividade do valor central: Positivo → Contrário → Contraditório → Negação da Negação. <strong>Ex.: Justiça → injustiça branda → injustiça → tirania (o crime 'legal', onde quem faz a lei tem poder ilimitado).</strong>","tip":"<strong>Como aplicar:</strong> use a declinação como gráfico de autocrítica. Parou no Contraditório? É sólido, mas não no limite. Grandes histórias chegam à Negação da Negação."},
   {"ic":"layers","t":"Os Negativos Qualitativos","emph":"Qualitativos","b":"Dois negativos não viram um positivo: na vida, as coisas 'pioram, pioram e pioram'. <strong>Os negativos mais fundos são qualitativos: a mentira dentro do amor, a tirania dentro da lei, o inimigo dentro de si.</strong>","tip":"<strong>Exemplo:</strong> o ódio mascarado de amor é o que eleva Gente como a Gente — 'como uma criança se defende disso?'"},
   {"ic":"target","t":"O Problema do Super-Herói","emph":"Super-Herói","b":"Como fazer de um deus um azarão? O design de Puzo para o Superman: dois foguetes em direções opostas, depois Lois morta, depois a lei do pai contra a mulher que ama. <strong>Desenhar o antagonismo É desenhar o herói.</strong>","tip":"<strong>Sinal de alerta:</strong> confundir um vilão com o antagonismo — a soma das forças inclui a própria natureza do protagonista, seus íntimos, instituições e o ambiente.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo XIV",
  "lessons":[
   "Força da história = força do seu lado negativo. Construa a oposição primeiro.",
   "Mapeie a declinação em quatro estágios do valor central e empurre a narração ao fim da linha.",
   "Os negativos mais profundos são qualitativos: a mentira no amor, a tirania na lei, o eu no inimigo.",
   "Não enfraqueça o antagonismo para o herói vencer — faça o herói crescer.",
  ],
 },
 {
  "slug": "ch15-exposicao",
  "sub": "CAPÍTULO XV: Exposição",
  "intro": "Exposição — os fatos de cenário, biografia e caracterização que a plateia precisa — deve ser invisível: dramatizada dentro do conflito, dosada 'o menos importante primeiro, o mais importante por último', e nunca dita para a plateia. 'Mostre, não conte' é respeito à inteligência do público.",
  "cards": [
   {"ic":"sword","t":"Exposição como Munição","emph":"Munição","b":"Sempre que fatos precisarem chegar à plateia, os personagens usam o que sabem para atacar, defender, persuadir — nunca para informar o espectador. <strong>Se ambos já sabem e não precisam usar como arma, a plateia não ouve.</strong>","tip":"<strong>Como aplicar:</strong> esconda a exposição dentro de uma briga — a plateia absorve fatos só enquanto está emocionalmente engajada no conflito.","wide":True},
   {"ic":"clock","t":"A Regra do Ritmo","emph":"Ritmo","b":"Revele apenas o que a plateia precisa, quando precisa — e guarde a exposição mais importante para o fim. <strong>Revelações tardias carregam poder de reviravolta; os fatos mais profundos da backstory viram reviravoltas no terceiro ato.</strong>","tip":"<strong>Sinal de alerta:</strong> a 'cena de informação' — dois personagens contando um ao outro o que ambos já sabem — mata a cena."},
   {"ic":"lens","t":"As 2 Regras do Flashback","emph":"Flashback","b":"(1) Dramatize o flashback — faça dele uma mini-história com arco próprio, não um despejo de informação. (2) <strong>Nunca volte no tempo antes de criar a necessidade e o desejo de saber</strong> (Casablanca só nos leva a Paris depois de acender a curiosidade).","tip":"<strong>Truque:</strong> abrir na descoberta do crime (não no crime) dispara a curiosidade em duas direções — passado (como/por quê?) e futuro (quem?)."},
   {"ic":"bubble","t":"O Teste da Narração","emph":"Teste da Narração","b":"Pergunte: 'se eu tirar a narração, a história ainda é bem contada?' Se não — reescreva até ficar, e então corte. <strong>Se sim — guarde-a só pela única boa razão: contraponto</strong> (a ironia e o humor que nenhuma cena faria).","tip":"<strong>Sinal de alerta:</strong> narração explicativa o filme inteiro vira 'audiolivro milionário, ilustrado'.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo XV",
  "lessons":[
   "Converta cada fato necessário em munição disparada dentro do conflito de uma cena.",
   "Dose as revelações: só o necessário, o melhor por último; só volte no tempo depois de criar fome de saber.",
   "Rode o teste da narração; mantenha-a apenas como contraponto.",
   "Mostre, não conte: explicar a vida para a plateia como se fossem crianças é condescendência.",
  ],
 },
 {
  "slug": "ch16-problemas-e-solucoes",
  "sub": "CAPÍTULO XVI: Problemas e Soluções",
  "intro": "O manual de solução de problemas de McKee: interesse, surpresa, coincidência, comédia, ponto de vista, adaptação, melodrama e furos de roteiro. Oito dilemas duradouros do ofício, cada um com sua saída.",
  "cards": [
   {"ic":"target","t":"Interesse: Curiosidade + Compaixão","emph":"Curiosidade + Compaixão","b":"Curiosidade (intelecto): abra perguntas e faça a plateia esperar. Compaixão (emoção): a plateia procura o Centro do Bem — o foco positivo de empatia. <strong>O 'bem' é relativo a um fundo mais escuro.</strong>","tip":"<strong>Exemplo:</strong> a lealdade dos Corleone entre clãs traiçoeiros; a inteligência e a calma de Lecter contra um mundo brutal e mentiroso."},
   {"ic":"eye","t":"As 3 Relações com a Plateia","emph":"3 Relações","b":"Mistério: a plateia sabe MENOS que os personagens (só curiosidade). Suspense: sabem o MESMO (curiosidade + compaixão — ~90% dos filmes). <strong>Ironia Dramática: a plateia sabe MAIS (compaixão pura — pavor e dó).</strong>","tip":"<strong>Como aplicar:</strong> misturar enriquece — Casablanca joga o flashback de Paris em ironia, depois vira a Crise de Rick em mistério para o choque."},
   {"ic":"spark","t":"Surpresa e Coincidência","emph":"Coincidência","b":"Surpresa verdadeira = a lacuna entre expectativa e resultado seguida de um jorro de revelação (não o susto barato). <strong>Coincidência: traga-a cedo, nunca após o meio, e jamais para virar o final</strong> (o deus ex machina: a salvação improvável que cai do céu).","tip":"<strong>Regra:</strong> o deus ex machina é 'o maior pecado do escritor' — exceto na Antitrama ('a vida é absurda') e na Comédia (se o herói sofreu enormemente).","warn":True},
   {"ic":"masks","t":"Comédia e Melodrama","emph":"Melodrama","b":"O comediante é um idealista raivoso atacando uma instituição — ache o que te enfurece. Já o melodrama 'não vem do excesso de expressão, mas da submotivação'. <strong>O poder de um evento deve igualar a soma de suas causas.</strong>","tip":"<strong>Como aplicar:</strong> não encolha a cena — aumente o desejo que a move. O teste de comédia: conte a história sem citar uma única piada."},
   {"ic":"wrench","t":"O Problema dos Furos","emph":"Furos","b":"Se tapar a lógica exige uma cena que só serve para explicar, pergunte: a plateia vai notar? Se sim, <strong>exponha o furo e o negue</strong> — um personagem admite 'não sei por que faço isto…', e o mundo joga a lógica no lixo, feliz.","tip":"<strong>Adaptação:</strong> cada meio domina um nível — romance = interno, teatro = pessoal, cinema = extrapessoal. 'Quanto mais puro o romance, pior o filme.'"},
  ],
  "lessons_title":"Lições-Chave do Capítulo XVI",
  "lessons":[
   "Fisgue o intelecto com perguntas e a emoção com um Centro do Bem; escolha Mistério/Suspense/Ironia de propósito.",
   "Coincidência cedo, personagens no comando no fim, nunca no desfecho.",
   "Escreva tão grande quanto a motivação que você construiu; exponha furos inevitáveis com charme confiante.",
   "Melodrama é submotivação, não exagero — aumente o desejo, não a cena.",
  ],
 },
 {
  "slug": "ch17-personagem",
  "sub": "CAPÍTULO XVII: Personagem",
  "intro": "Um personagem não é um ser humano — é uma obra de arte, 'uma metáfora da natureza humana', mais clara e conhecível que qualquer pessoa real. O escritor é o 'Verme da Mente' medieval: cava uma natureza e desenha o único evento que a forçará a viver até o limite.",
  "cards": [
   {"ic":"target","t":"Personagem Verdadeiro pelo Desejo","emph":"Desejo","b":"'O personagem verdadeiro só se expressa pela escolha em dilema.' A chave é o desejo: pergunte o que ele quer? agora? em breve? no geral? consciente? inconscientemente? <strong>Com respostas claras vem o domínio do papel.</strong>","tip":"<strong>Como aplicar:</strong> pressão revela, escolha define. Pense o motivo a fundo — depois deixe mistério, espaço para a experiência da plateia.","wide":True},
   {"ic":"mask","t":"Dimensão = Contradição","emph":"Contradição","b":"Uma dimensão é uma contradição consistente — dentro do personagem profundo (Macbeth: ambição vs. culpa) ou entre caracterização e profundidade (um ladrão charmoso). <strong>Traços não são dimensões</strong> (perito em finanças + faixa-preta + saxofonista = 'plano como uma mesa').","tip":"<strong>Sinal de alerta:</strong> o protagonista deve ser o personagem mais dimensional do elenco — senão o Centro do Bem se desloca (Blade Runner).","warn":True},
   {"ic":"constellation","t":"O Design do Elenco (Sistema Solar)","emph":"Sistema Solar","b":"O protagonista é o sol; os coadjuvantes são planetas; os figurantes, satélites — todos existem pela relação que travam com o protagonista. <strong>Cada um desenhado para revelar uma contradição diferente (A provoca seu cinismo, B sua esperança, C sua coragem).</strong>","tip":"<strong>Cuidado:</strong> figurantes são deliberadamente planos, mas não enfadonhos — um traço bem observado, nada mais."},
   {"ic":"masks","t":"O Personagem Cômico","emph":"Cômico","b":"Atribua uma mania que o personagem não consegue ver (o Avarento de Molière; a ilusão de detetive perfeito de Clouseau). <strong>No instante em que ele enxerga a própria obsessão, a comédia acaba.</strong>","tip":"<strong>Modelo mental:</strong> ame todos os seus personagens, sobretudo os maus — 'se não consegue amá-los, não os escreva'. Vilões acham que são bons."},
  ],
  "lessons_title":"Lições-Chave do Capítulo XVII",
  "lessons":[
   "Ache o desejo, depois a contradição; a pressão revela, a escolha define.",
   "Construa o elenco para fora, a partir das dimensões do protagonista — mantenha-o a figura mais profunda do tabuleiro.",
   "Para comédia, dê uma cegueira; para vilania, dê autojustiça; para todos, dê amor.",
   "Não pregue a motivação a causas específicas — diminui o personagem; deixe mistério.",
  ],
 },
 {
  "slug": "ch18-o-texto",
  "sub": "CAPÍTULO XVIII: O Texto",
  "intro": "O texto — diálogo e descrição — é os últimos 25% do trabalho e deve servir ao que está por baixo: o diálogo comprime o subtexto nas palavras mais atuáveis possíveis; a descrição guia o olho interior do leitor como uma câmera; e um Sistema de Imagens costura poesia subliminar pelo filme inteiro.",
  "cards": [
   {"ic":"bubble","t":"Disciplina do Diálogo","emph":"Diálogo","b":"Diálogo NÃO é conversa — é ação comprimida e proposital em palavras. Diga o máximo nas mínimas; mantenha falas curtas e naturais ('ninguém fala assim' é fatal). <strong>Use a frase periódica: adie a palavra que carrega o sentido para o fim da linha.</strong>","tip":"<strong>Regra:</strong> menos é mais — a atriz que oferece a xícara não precisa de 'Você quer este café, querido?'. A xícara, o gesto e o sentimento já dizem tudo."},
   {"ic":"eye","t":"Descrição: a Cena-Mestra","emph":"Cena-Mestra","b":"Escreva no presente vívido, só o que é filmável. Em vez de marcar ângulos de câmera, quebre a descrição em miniparágrafos separados por espaço em branco — cada unidade sugere sutilmente um plano. <strong>Lê-se como assistir ao filme.</strong>","tip":"<strong>Como aplicar:</strong> deixe ao diretor e ao ator o trabalho criativo deles — geral / movimento / close / inserto se insinuam pelo recorte."},
   {"ic":"spiral","t":"Sistemas de Imagens","emph":"Sistemas de Imagens","b":"Uma estratégia de motivos que se repete em imagem e som do início ao fim, com persistência e variação. <strong>Imagem Externa importa um símbolo pronto (bandeira = pátria) — 'a marca do filme de estudante'; Imagem Interna dá a uma categoria um sentido único deste filme.</strong>","tip":"<strong>Exemplo:</strong> As Diabólicas satura tudo de água e inverte seu simbolismo de vida para morte e terror.","wide":True},
   {"ic":"book","t":"Mantenha o Símbolo Invisível","emph":"Símbolo Invisível","b":"'A consciência de um símbolo o transforma numa curiosidade intelectual neutra, impotente e quase sem sentido.' <strong>Como a trilha sonora, o simbolismo só funciona abaixo da cognição.</strong>","tip":"<strong>Sinal de alerta:</strong> rotular símbolos (o laço de Buñuel, que à quinta repetição fez a plateia gritar 'Símbolo!') os mata.","warn":True},
  ],
  "lessons_title":"Lições-Chave do Capítulo XVIII",
  "lessons":[
   "Comprima o diálogo em torno do subtexto; termine as falas na palavra que importa.",
   "Descreva em unidades filmáveis no presente que sugiram o corte.",
   "Construa um ou mais Sistemas de Imagens internos e mantenha-os invisíveis.",
   "Poético não é bonito — é expressividade ampliada do conteúdo, qualquer que ele seja.",
  ],
 },
 {
  "slug": "ch19-metodo-do-escritor",
  "sub": "CAPÍTULO XIX: O Método do Escritor",
  "intro": "A diferença entre quem prospera e quem sofre é o método: de dentro para fora vs. de fora para dentro. O escritor sábio adia o diálogo o máximo possível — 'escrever diálogo cedo demais sufoca a criatividade'.",
  "cards": [
   {"ic":"cards","t":"De Dentro para Fora","emph":"De Dentro para Fora","b":"De um roteiro de seis meses, gaste ~quatro meses antes do roteiro. O pipeline: Escaleta em fichas → Pitch → Tratamento (com subtexto, sem diálogo) → Roteiro. <strong>O diálogo escrito por último é o melhor que você fará.</strong>","tip":"<strong>Regra:</strong> estrutura primeiro, palavras por último. Descubra o Clímax antes de escrever uma linha de diálogo.","wide":True},
   {"ic":"cards","t":"A Escaleta (Step-Outline)","emph":"Escaleta","b":"A história contada em passos em fichas 3×5, uma pilha por ato. Cada ficha: uma ou duas frases do que acontece e como a cena vira; no verso, a função estrutural. <strong>Fique meses nas fichas para destruir: '90% de tudo que você escreve é medíocre na melhor das hipóteses'.</strong>","tip":"<strong>Sinal de alerta:</strong> esboce cada cena de doze jeitos, jogue fora sequências e atos inteiros; não se apegue — descubra o Clímax e reescreva de trás para frente.","warn":True},
   {"ic":"bubble","t":"O Teste do Pitch","emph":"Pitch","b":"Nunca mostre a escaleta — conte a história em dez minutos e veja-a acontecer numa pessoa. <strong>'Se a história não funciona em dez minutos, como funcionará em 110? Não melhora ao ficar maior.'</strong>","tip":"<strong>Marca de aprovação:</strong> os ouvintes sussurram 'Uau' e ficam em silêncio. Até a maioria reagir com esse entusiasmo, não avance."},
   {"ic":"book","t":"O Tratamento e o Roteiro","emph":"Tratamento","b":"Expanda cada passo a um parágrafo no presente, momento a momento, com subtexto completo e sem diálogo ('ele quer que ela faça isto, mas ela recusa'). Um tratamento real tem 60–90+ páginas. <strong>Só então o roteiro flui — 'uma alegria' a 5–10 páginas por dia.</strong>","tip":"<strong>Modelo mental:</strong> a Fábula da Lacraia — estude o ofício membro a membro até o instinto virar conhecimento; aí, então, você dança. O que o mundo pede é coragem."},
  ],
  "lessons_title":"Lições-Chave do Capítulo XIX",
  "lessons":[
   "Estrutura primeiro, palavras por último: fichas → pitch → tratamento-com-subtexto → roteiro.",
   "Crie dez vezes mais do que você guarda, e ache o Clímax antes de escrever uma linha de diálogo.",
   "Teste a história nua, em dez minutos, em rostos humanos — depois escreva com ousadia.",
   "Escreva todo dia, linha por linha. Além de talento e técnica, o ofício exige coragem.",
  ],
 },
]
