import json

out_file = r"C:\Users\User\.gemini\antigravity\scratch\biblioteca\_kit_preview\gemini_in\batch_9_out.md"

data5 = {
  "ch01-nao-me-faca-pensar": {
    "cards": [
      {"ic": "target", "t": "A Regra Zero da Web", "emph": "Regra Zero", "b": "A interface implora: não adicione carga cognitiva onde não existe necessidade. O usuário não clica num link para resolver um enigma ou decifrar metáforas brilhantes. Se ele precisar parar e calcular onde deve clicar para ver o preço, <strong>a sua genialidade falhou como design</strong>. A intuição não é beleza, é ausência de atrito.", "tip": "<strong>Modelo mental:</strong> cada segundo gasto entendendo como a navegação funciona é um segundo a menos desejando o que você vende."},
      {"ic": "eye", "t": "O Olhar Desatento", "emph": "Desatento", "b": "O designer projeta como se a tela fosse uma obra de arte que seria admirada; o usuário a trata como um outdoor lido a 100km/h na estrada. As pessoas não leem tutoriais e não desbravam menus inteiros: elas <strong>passam os olhos e clicam no primeiro botão que vagamente se parece</strong> com a solução do problema.", "tip": "<strong>Prática:</strong> formate o texto para o escaneamento cego — use fontes grotescas, negritos gigantes e pule a prosa poética."},
      {"ic": "gap", "t": "O Risco da Metáfora", "emph": "Metáfora", "b": "Chamar o carrinho de compras de “Bolsa de Magias” e a página de contato de “Sinal de Fumaça” soa poético na reunião criativa, mas cega o visitante. A familiaridade na web salva o tempo de todo mundo. Quando você arranca as convenções sólidas em nome de uma originalidade superficial, <strong>você cobra pedágio no lugar errado</strong>.", "tip": "<strong>Armadilha:</strong> inventar a roda nas interfaces destrói a convenção; o usuário sempre prefere a previsibilidade chata ao labirinto exótico.", "warn": True}
    ]
  },
  "ch02-como-usamos-web": {
    "cards": [
      {"ic": "leaf", "t": "O Falso Racional", "emph": "Falso Racional", "b": "Você acredita que o cliente avalia as opções, pesa a melhor rota e escolhe a ideal. Na verdade, a escolha final não é a ótima, mas a satisfatória: a estratégia se baseia na tática de <strong>agarrar o primeiro link plausível</strong> e tentar a sorte. O processo é instintivo e imperfeito, muito longe do julgamento analítico.", "tip": "<strong>Modelo mental:</strong> na web, os usuários operam com o instinto de sobrevivência e não com a lógica fria de um arquiteto."},
      {"ic": "clock", "t": "O Valor do Clique Certo", "emph": "Clique Certo", "b": "O número absoluto de cliques exigidos não define a fluidez, mas sim o esforço em cada parada. O usuário tolerará três saltos a mais <strong>desde que a escolha em cada um deles seja instintiva, sem atrito e óbvia como um soco</strong>. É muito melhor clicar quatro vezes no verde do que travar por trinta segundos decifrando dois caminhos.", "tip": "<strong>Regra:</strong> não conte e elimine as páginas; conte e elimine os engasgos confusos de interpretação do usuário."},
      {"ic": "gap", "t": "A Falta de Manuais", "emph": "Manuais", "b": "A interface que demanda uma introdução ou legendas para que o seu público navegue não nasceu de uma inovação, e sim de um erro grave de projeto. Se o painel grita por um bloco de instruções de uso colado em cima, <strong>o design não comunicou, ele escondeu</strong>. A ferramenta precisa revelar o seu propósito no bater de olhos.", "tip": "<strong>Armadilha:</strong> forçar que leiam tutoriais equivale a exigir senha no hall de um supermercado; espanta a fome.", "warn": True}
    ]
  },
  "ch03-arquitetura-informacao": {
    "cards": [
      {"ic": "book", "t": "A Bússola Subconsciente", "emph": "Bússola", "b": "A arquitetura sólida se enraíza nos pilares mais entediantes do mundo: a hierarquia inflexível e a categorização transparente. Você precisa projetar o mapa como se fosse destinado a quem acordou com amnésia: <strong>o nível em que o usuário está deve gritar em negrito brilhante</strong>.", "tip": "<strong>Prática:</strong> destaque visualmente o caminho completo: onde você está, de onde veio e as portas que levam embora."},
      {"ic": "target", "t": "O Teste do Porta-Malas", "emph": "Porta-Malas", "b": "Derrube o usuário com os olhos vendados no meio do seu site. Se ele destrancar a página agora mesmo e demorar mais do que três segundos cruciais para saber o nome do site, em qual página caiu e quais os grandes blocos de navegação, <strong>o seu sistema faliu miseravelmente</strong>.", "tip": "<strong>Como aplicar:</strong> simule o visitante que cai direto via link em páginas obscuras do site, pulando a maquiagem da home."},
      {"ic": "eye", "t": "O Abandono Silencioso", "emph": "Abandono", "b": "As placas da rodovia virtual perdoam os desvios, mas a tolerância à desorientação crônica tem um prazo microscópico de validade. No milissegundo exato em que o internauta não se achar, ele sequer vai xingar ou abrir um ticket para você; ele vai <strong>bater a porta fechando a aba em silêncio fúnebre</strong> e você perdeu o dinheiro.", "tip": "<strong>Sinal de alerta:</strong> o tráfego que bate na porta de trás e some acusa que a placa de indicação estava suja e encardida.", "warn": True}
    ]
  },
  "ch04-testes-usabilidade": {
    "cards": [
      {"ic": "layers", "t": "O Falso Espelho", "emph": "Espelho", "b": "O designer argumenta eternamente na sala fechada de reunião com a vaidade ferida. Mas você, o líder da equipe de dev ou o dono, <strong>não é o seu maldito usuário médio</strong>. As verdades definitivas escritas com caneta de ouro não sobrevivem aos primeiros cinco minutos vendo uma pessoa comum tentar preencher um mísero formulário de contato.", "tip": "<strong>Regra:</strong> as brigas sobre o que o usuário quer são irrelevantes — jogue o rato no labirinto e as estatísticas respondem na mesa."},
      {"ic": "steps", "t": "O Poder do Amador", "emph": "Amador", "b": "Mire nos testes de usabilidade toscos e rápidos. Três pessoas recrutadas no café esbarrando no seu fluxo valem cem vezes mais do que um relatório pedante, esterilizado e engravatado de consultoria acadêmica caríssima. A usabilidade bruta e real pulsa <strong>quando o atrito rústico revela as fraturas que ninguém queria ver</strong>.", "tip": "<strong>Modelo mental:</strong> teste com alguém que o projeto nunca almejou como alvo ideal; a estupidez aparente dele iluminará buracos enormes e sombrios."},
      {"ic": "pin", "t": "O Efeito Ilha", "emph": "Ilha", "b": "Largar a avaliação nas mãos restritas de quem moldou o esqueleto da interface atrai o viés da maldição do conhecimento pleno. Quem solda as placas já sabe decifrar os atalhos. Contrate o julgamento da secretária ignorante, não os olhos acostumados do gerente de produtos que sonhou aquilo.", "tip": "<strong>Armadilha:</strong> o criador que audita e julga a própria criação vai atestar falsamente que o monstro flui como o ballet aquático.", "warn": True}
    ]
  }
}

data6 = {
  "ch01-infancia-mundo-adulto": {
    "cards": [
      {"ic": "eye", "t": "A Cegueira dos Números", "emph": "Números", "b": "O mundo adulto julga pela calculadora: para conhecer um amigo, ele pergunta o preço da casa e o tamanho da conta. As cifras não descrevem o amor e não definem o assombro da alma. Essa obsessão pelo utilitário <strong>cristaliza os olhos e enterra toda a curiosidade viva</strong> que a infância enxergava de graça.", "tip": "<strong>Modelo mental:</strong> as planilhas entregam o peso dos tijolos, não o calor que a lareira da sala esconde."},
      {"ic": "gap", "t": "O Elefante na Cobra", "emph": "Elefante", "b": "Quando a obra grita “isso é um chapéu”, a resposta da manada revela a cegueira crônica dos crescidos: eles exigem o óbvio e censuram o imponderável. A pressão por utilidade apaga dolorosamente a lente original que detectava <strong>os mistérios que as embalagens lisas não confessam</strong>.", "tip": "<strong>Sinal de alerta:</strong> abandonar e descartar rapidamente o que não se enquadra na utilidade engessa o espírito criativo irremediavelmente.", "warn": True},
      {"ic": "spark", "t": "O Essencial Invisível", "emph": "Invisível", "b": "A casca não carrega a majestade do tesouro escondido. O que torna o deserto sublime não é a aridez incalculável de areia, mas sim <strong>o poço escuro e vivo de água que se esconde ali debaixo</strong>. Os sentidos biológicos detectam e descrevem a caixa, apenas a sensibilidade afiada do peito perfura o osso para avistar o significado real.", "tip": "<strong>Regra:</strong> não compre nem mensure pessoas pelo currículo e posses materiais, garimpe a lealdade enfiada no barro da existência."}
    ]
  },
  "ch02-viagem-planetas": {
    "cards": [
      {"ic": "spiral", "t": "Os Prisioneiros do Ego", "emph": "Ego", "b": "Do rei sem súditos clamando obediência cega ao vaidoso surdo debaixo do aplauso fingido, os adultos alienígenas encarnam os tumores ridículos do orgulho isolado. Eles dominam o topo de rochas miúdas <strong>afogados tristemente numa vaidade asquerosa que só exige, mas nunca abraça ninguém</strong>.", "tip": "<strong>Como aplicar:</strong> o palco da autoridade é a tumba mais vazia e abafada quando se governa estritamente focado no retrovisor das suas próprias posses."},
      {"ic": "clock", "t": "A Corrida Estéril", "emph": "Estéril", "b": "O homem de negócios crava milhões de estrelas mortas num papel sem fim, acumulando infinitos lucros abstratos num cofre estéril, enquanto não rega nenhuma delas para germinar. O vício na contabilização frenética afoga impiedosamente as horas cruciais que poderiam <strong>acender de sentido algum peito desamparado que precisava chorar perto</strong>.", "tip": "<strong>Armadilha:</strong> empilhar infinitamente bens esquecendo rudemente a própria manutenção dos laços corrói as fundações da vida.", "warn": True},
      {"ic": "layers", "t": "A Servidão das Regras", "emph": "Regras", "b": "O acendedor de lampiões cumpre a norma esdrúxula sob uma velocidade infernal esvaziada e enlouquecedora. Ele sequer para as mãos tremendo para escutar a melodia do nascer e morrer do dia. <strong>Seguir a burocracia desprovida de alma seca a coragem de repensar se a missão original ainda responde à fome vital dos dias atuais</strong>.", "tip": "<strong>Prática:</strong> o soldado que vigia um muro derrubado obedece focado na lei, mas falha absurdamente em salvar a vida que escorre no chão."}
    ]
  },
  "ch03-raposa-cativar": {
    "cards": [
      {"ic": "link", "t": "A Ciência de Cativar", "emph": "Cativar", "b": "O elo não se compra empacotado no armazém escuro com as moedas no bolso — ele se assa com os meses no sol do tempo desperdiçado sem cobrança. Cativar alguém é assinar em sangue e suor limpo: <strong>o universo gigantesco de repente aponta inteirinho as luzes para aquela cor viva que colore os cabelos amados</strong>.", "tip": "<strong>Prática:</strong> laços rasos somem quando o dinheiro bate; as âncoras brutais demandam que você escute as dores surdas do outro sem olhar o relógio."},
      {"ic": "target", "t": "A Rosa Única", "emph": "Rosa", "b": "Os cinco mil clones no jardim não apagam das veias e calafrios as minúcias insuportáveis e majestosas da flor que ele irrigou sob a noite fria. O suor e a proteção entregues aos espinhos criaram violentamente <strong>um cordão invisível e insubstituível que as matemáticas quantitativas do mundo frio não racham no meio</strong>.", "tip": "<strong>Regra:</strong> não é a estética do parceiro que arrasta os seus dias, são exatamente os pântanos doentes dos quais ambos saíram abraçados que vale o prêmio."},
      {"ic": "key", "t": "O Peso da Responsabilidade", "emph": "Responsabilidade", "b": "A domesticação das fúrias não perdoa: o afeto depositado sob a redoma quente de alguém encarcera nobremente o criador da relação. O pacto escancarou a gaiola cega, e <strong>quando você arranca sorrisos de alguém na dor, as lágrimas dele passam a ser um compromisso eterno sob as suas mãos fracas</strong>.", "tip": "<strong>Armadilha:</strong> recuar amedrontado perante o peso e o luto da conexão afoga o juramento solene e prova que as sementes que você atirou eram covardes.", "warn": True}
    ]
  },
  "ch04-despedida-significado": {
    "cards": [
      {"ic": "mountain", "t": "O Corpo Inútil", "emph": "Corpo Inútil", "b": "O veneno da cobra atua cruelmente apenas no maquinário orgânico que desaba frio e inútil na areia pesada. A essência estalando de amor voa para cima sem carregar fardos carnais rasos. <strong>O cadáver esparramado pesadamente no areal choca o olhar da despedida dolorosa, mas esconde as verdades absolutas ali nas estrelas brilhantes</strong>.", "tip": "<strong>Modelo mental:</strong> o encerramento trágico do esqueleto assinala tão-somente a quebra brutal da casca provisória inútil, jamais condenando o afeto puro do peito."},
      {"ic": "spiral", "t": "As Estrelas Que Riem", "emph": "Riem", "b": "A separação física despedaçadora espalha os sorrisos embutidos na eternidade pontilhada. O silêncio estelar amargurado vira barulho orquestrado quente para aquele piloto enlouquecido — porque <strong>o eco doce do garoto eterno lá de cima injetou-se profundamente em cada pontinho de luz estelar daquela noite sombria do deserto outrora esquecido</strong>.", "tip": "<strong>Prática:</strong> escute as verdades imensas da vida na voz vibrante de quem não está mais presente materialmente perto de você respirando os ventos secos."},
      {"ic": "eye", "t": "A Falha da Memória Útil", "emph": "Útil", "b": "A saudade violenta assaltando a alma engasga no choro quando os negócios rasos da vida adulta tentam impor as rédeas cegas. Tentar explicar a dor da ausência futilmente perante quem exige o saldo prático da choradeira <strong>apaga o sentido milenar que as conversas noturnas no escuro e os arrepios sem métricas trouxeram sob o teto daquele avião quebrado</strong>.", "tip": "<strong>Armadilha:</strong> asfixiar a lembrança majestosa de uma conexão pura usando a régua burocrática dos homens de terno afoga a sua sanidade milagrosa de vez.", "warn": True}
    ]
  }
}

with open(out_file, "a", encoding="utf-8") as f:
    f.write("=== nao-me-faca-pensar ===\n```json\n" + json.dumps(data5, ensure_ascii=False, indent=2) + "\n```\n\n")
    f.write("=== pequeno-principe ===\n```json\n" + json.dumps(data6, ensure_ascii=False, indent=2) + "\n```\n\n")

print("Part 3 done.")
