import json

out_file = r"C:\Users\User\.gemini\antigravity\scratch\biblioteca\_kit_preview\gemini_in\batch_9_out.md"

data1 = {
  "ch01-contrato-audiovisual": {
    "cards": [
      {"ic": "link", "t": "O Terceiro Sentido", "emph": "Terceiro", "b": "Você não vê e ouve em faixas isoladas — as duas percepções colidem e se transformam. A imagem altera o que os ouvidos captam, e o som redefine o que os olhos julgam enxergar. Cria-se um <strong>terceiro sentido autônomo</strong>, impossível de ser reduzido à simples soma de ver e ouvir.", "tip": "<strong>Como aplicar:</strong> troque a trilha de uma cena e observe como a expressão do ator parece mudar sem que se altere um pixel."},
      {"ic": "pivot", "t": "Um Contrato Consentido", "emph": "Contrato", "b": "A relação entre o áudio e o visual é uma <strong>convenção profunda que você aceita</strong> sem questionar. Não existe adição natural entre as pistas. Se você troca o ruído de cascalho por neve sob os pés do personagem, a mesma imagem instantaneamente vira outra realidade.", "tip": "<strong>Modelo mental:</strong> a cena não é um registro fiel da realidade, mas um acordo ilusório de percepção."},
      {"ic": "gap", "t": "A Ilusão do Acompanhamento", "emph": "Ilusão", "b": "Tratar a trilha como uma roupagem opcional de enfeite <strong>ignora que ela redesenha ativamente o que se vê</strong>. Quando você sobrepõe um áudio, a cena original deixa de existir. Analisar os sentidos de forma isolada destrói o coração do fenômeno.", "tip": "<strong>Armadilha:</strong> julgar a imagem muda e o som cego quebra a solda que dá sentido à obra.", "warn": True}
    ]
  },
  "ch02-valor-acrescentado": {
    "cards": [
      {"ic": "eye", "t": "A Mágica do Acréscimo", "emph": "Acréscimo", "b": "O fenômeno ocorre quando a informação do som <strong>enriquece a imagem</strong> a ponto de fundir-se a ela. Você sente como se aquele significado emanasse naturalmente dos pixels na tela. O áudio trabalha nos bastidores para que o vídeo colha os aplausos.", "tip": "<strong>Como aplicar:</strong> o som perfeito é invisível — sentido pelo público como propriedade da própria imagem."},
      {"ic": "target", "t": "O Som Estrutura o Olhar", "emph": "Estrutura", "b": "Um texto recitado ou uma trilha impõem para onde seus olhos devem correr. Eles <strong>orientam a atenção</strong> e determinam a leitura definitiva de cenas ambíguas. Mais do que isso, o ritmo sonoro injeta uma sensação cronológica em imagens paradas.", "tip": "<strong>Regra:</strong> o som é quem planta o sentido e a emoção; a imagem é quem leva o crédito."},
      {"ic": "gap", "t": "O Peso da Redundância", "emph": "Redundância", "b": "Fazer o áudio gritar exatamente aquilo que a tela já escancara <strong>não acrescenta valor algum</strong> à narrativa. Isso apenas satura os sentidos e rouba o espaço de outras camadas. O bom design sonoro dialoga com a cena em vez de repeti-la como um eco.", "tip": "<strong>Cuidado:</strong> mixar um projeto sem testá-lo no mudo esconde a verdadeira função que o som desempenha.", "warn": True}
    ]
  },
  "ch03-sincrese": {
    "cards": [
      {"ic": "target", "t": "A Solda da Síncrese", "emph": "Solda", "b": "A fusão entre um evento visual e um ruído simultâneo é <strong>involuntária, reflexa e inevitável</strong> no seu cérebro. Você não precisa aprender a juntar as duas coisas — o impacto as cola na hora. É por isso que um soco falso no cinema soa tão doloroso e real.", "tip": "<strong>Prática:</strong> você não precisa captar o barulho autêntico no set, mas sim acertar o som no tempo exato."},
      {"ic": "pin", "t": "A Força da Sincronia", "emph": "Sincronia", "b": "Os instantes em que áudio e vídeo colidem com impacto são como <strong>acentos rítmicos</strong> em uma frase falada. Eles pontuam a cena, puxam a atenção e entregam o peso dramático exato. A sincronia tem o poder de unir mundos dispersos numa única pancada.", "tip": "<strong>Modelo mental:</strong> a precisão do tempo é o que cola os elementos; a escolha de qual ruído usar fica livre."},
      {"ic": "gap", "t": "O Excesso Que Quebra a Magia", "emph": "Excesso", "b": "Marcar cada passo ou gesto com uma colisão sonora <strong>esgota o espectador e dilui o acento dramático</strong>. É o efeito de desenho animado que retira a gravidade da obra. Quando a sincronia é frouxa ou óbvia demais, a costura se rasga e revela o truque.", "tip": "<strong>Sinal de alerta:</strong> sublinhar todos os movimentos é o mesmo que não destacar nenhum.", "warn": True}
    ]
  },
  "ch04-modos-de-escuta": {
    "cards": [
      {"ic": "lens", "t": "As Três Lentes Auditivas", "emph": "Três Lentes", "b": "Você ouve de forma causal para identificar a fonte, escuta pela semântica para decodificar palavras, e usa a escuta reduzida para focar <strong>apenas na textura e altura</strong> do ruído. Cada uma dessas posturas altera a forma como o seu cérebro processa o mundo.", "tip": "<strong>Prática:</strong> mixe o seu material garantindo que o modo predominante esteja sempre nítido para quem ouve."},
      {"ic": "key", "t": "O Domínio da Escuta Reduzida", "emph": "Escuta Reduzida", "b": "O mestre do áudio não descreve o barulho de um carro, mas um <strong>zunido grave e áspero que cresce</strong>. Ao se desconectar da origem literal daquele som, você ganha a liberdade de moldá-lo como matéria-prima bruta para evocar novas sensações na tela.", "tip": "<strong>Modelo mental:</strong> o público reage pelo significado (causal); o profissional opera pela textura (reduzida)."},
      {"ic": "gap", "t": "O Risco do Ambiente Alto", "emph": "Ambiente Alto", "b": "Ignorar que o foco do público na fala é estritamente <strong>semântico e não de ambiente</strong> faz com que você soterre vozes cruciais sob efeitos sonoros. O ouvinte busca entender a mensagem, e qualquer ruído extra durante o diálogo vira apenas poluição inútil.", "tip": "<strong>Armadilha:</strong> deixar o ambiente engolir o texto sabota a única coisa que o espectador deseja ouvir.", "warn": True}
    ]
  },
  "ch05-acusmatico-acusmetre": {
    "cards": [
      {"ic": "mask", "t": "O Poder do Invisível", "emph": "Invisível", "b": "A voz de origem escondida — o narrador invisível ou o vilão oculto nas sombras — ganha uma aura <strong>onisciente, onipresente e ameaçadora</strong>. Como não está confinada a um rosto específico na tela, a mente assume que ela habita e controla o espaço inteiro.", "tip": "<strong>Como aplicar:</strong> preserve a ausência física da maior ameaça para multiplicar o peso psicológico do seu suspense."},
      {"ic": "eye", "t": "A Queda Para a Carne", "emph": "Queda", "b": "A des-acusmatização ocorre no segundo em que você mostra o rosto de quem fala. O corpo <strong>aprisiona aquela entidade</strong> no espaço e no tempo de um simples mortal. A figura perde instantaneamente os seus poderes mágicos e passa a ser apenas humana.", "tip": "<strong>Modelo mental:</strong> revelar a origem física do medo é a forma mais eficaz de quebrar o encanto e rebaixar a ameaça."},
      {"ic": "gap", "t": "A Revelação Precoce", "emph": "Revelação Precoce", "b": "Mostrar cedo demais o rosto daquela voz sombria <strong>destrói todo o suspense</strong> que a escuridão sustentava de graça. A expectativa da ameaça no invisível é quase sempre mais aterradora do que o impacto da criatura sob a luz, que termina soando comum.", "tip": "<strong>Armadilha:</strong> revelar a figura por ansiedade joga no lixo um dos maiores trunfos da tensão narrativa.", "warn": True}
    ]
  },
  "ch06-temporalizacao": {
    "cards": [
      {"ic": "clock", "t": "A Injeção do Tempo", "emph": "Injeção", "b": "O som impõe ao registro visual um <strong>fluxo cronológico palpável</strong> — um presente que não para de escorrer. Sem áudio, a imagem congelada paira na eternidade. Quando o ruído entra, a mesma cena ganha duração contínua, ritmo urgente e um sentido de vida.", "tip": "<strong>Regra:</strong> o vídeo entrega a noção de espaço; é o desenho do som que dita a velocidade da experiência."},
      {"ic": "pivot", "t": "A Flecha Para o Futuro", "emph": "Flecha", "b": "Um ruído contínuo ou crescente <strong>aponta a percepção para o que está por vir</strong>. Ele vetoriza o momento, criando uma expectativa incontrolável de clímax ou desfecho. É essa condução que imprime um “antes e depois” incontornável dentro da sua cabeça.", "tip": "<strong>Modelo mental:</strong> o áudio é a força propulsora que arrasta a linha do tempo narrativa em direção ao futuro."},
      {"ic": "gap", "t": "A Desconexão Letal", "emph": "Desconexão Letal", "b": "Combinar uma imagem lenta com ruídos que não progridem faz a cena <strong>morrer de inanição</strong>. O espectador sente que nada acontece e o tédio anestesia tudo. Cortar a trilha de forma seca a cada mudança de plano esmaga a ponte que mantém o tempo vivo.", "tip": "<strong>Armadilha:</strong> esquecer o progresso sonoro destrói a percepção de que a história está caminhando.", "warn": True}
    ]
  },
  "ch07-rendering": {
    "cards": [
      {"ic": "spark", "t": "A Construção do Rendering", "emph": "Rendering", "b": "Reproduzir a acústica exata do mundo real não funciona. O audiovisual exige o rendering: a tradução engenhosa de <strong>peso, violência e materialidade</strong> para os ouvidos. Você não grava a ação crua, você esculpe a emoção que aquela gravidade exige.", "tip": "<strong>Como aplicar:</strong> molde a camada sonora para replicar a sensação visceral de um impacto, e não a ciência física do barulho."},
      {"ic": "target", "t": "O Falso Mais Que Verdadeiro", "emph": "Falso", "b": "A realidade pura costuma soar <strong>frouxa, fina e insuficiente</strong> no gravador. O barulho de um soco que você acha perfeito foi na verdade construído e exagerado em estúdio. A gravação literal é um rascunho muito pobre diante da experiência que a arte exige.", "tip": "<strong>Modelo mental:</strong> o purismo do áudio original é inútil — o que fisga a audiência é o realismo hiperbólico."},
      {"ic": "gap", "t": "O Fetiche Pela Verdade", "emph": "Fetiche", "b": "Insistir na gravação autêntica por uma teimosia documental faz a cena <strong>desabar sem brilho e sem impacto</strong>. Um ruído original fraco parece um erro da produção. O som tímido quebra as promessas dramáticas que a qualidade da fotografia estava fazendo.", "tip": "<strong>Armadilha:</strong> confiar no barulho exato da captação garante a honestidade técnica, mas assassina a imersão.", "warn": True}
    ]
  },
  "ch08-espacos-vococentrismo": {
    "cards": [
      {"ic": "layers", "t": "Os Três Palcos do Som", "emph": "Palcos do Som", "b": "O áudio transita entre “In” (visto na tela), “Fora de Campo” (diegético na borda) e “Off” (narrador e trilha inalcançáveis). Mover o barulho de um plano invisível para o palco físico <strong>transforma a relação de espaço</strong> sem precisar mover um milímetro de câmera.", "tip": "<strong>Como aplicar:</strong> a localização e a reverberação de uma fala entregam tanto significado dramático quanto a palavra dita."},
      {"ic": "target", "t": "A Ditadura da Voz", "emph": "Voz", "b": "O ser humano é biologicamente programado para priorizar a fala <strong>acima de qualquer outra coisa</strong>. Sendo linguagem, os nossos ouvidos buscam obcecadamente o código e o sentido. A dicção humana opera como o sol na cena: todo o resto do ambiente orbita ao seu redor.", "tip": "<strong>Regra:</strong> num ecossistema acústico denso, as vozes exigem sempre e de forma absoluta o papel principal."},
      {"ic": "pivot", "t": "A Angústia da Indiferença", "emph": "Indiferença", "b": "Enquanto a trilha empática abraça a dor, a música anempática <strong>segue inabalável enquanto o mundo acaba</strong>. Uma melodia leve durante uma tragédia amplifica o horror silencioso — pois avisa ao espectador que a máquina do universo gira surda e alheia ao seu choro.", "tip": "<strong>Sinal de alerta:</strong> competir a fala principal com trilhas emocionais polui o centro das atenções, quebrando a regra de ouro.", "warn": True}
    ]
  }
}

data2 = {
  "ch01-teoria-homem-extraordinario": {
    "cards": [
      {"ic": "triangle", "t": "Ordinários Contra Extraordinários", "emph": "Extraordinários", "b": "A tese letal: indivíduos <strong>extraordinários</strong> — de Napoleão a legisladores — possuiriam o direito natural de transpor o sangue para fundar o novo. Os ordinários servem apenas para perpetuar a espécie. O assassinato não é sobre o dinheiro: é o teste empírico da própria grandeza.", "tip": "<strong>Modelo mental:</strong> encare a brutalidade não como um crime passional, mas como um experimento de laboratório que deu errado."},
      {"ic": "spark", "t": "A Refutação Pela Carne", "emph": "Pela Carne", "b": "Dostoiévski não derrota a ideologia no conforto da mesa de debates: ele permite que o herói <strong>a execute na vida real</strong>. A verdadeira refutação se materializa na febre, no delírio paranoico e na solidão asfixiante. A teoria matemática da grandeza quebra diante da resposta imprevisível da biologia.", "tip": "<strong>Sinal de alerta:</strong> quando uma matriz teórica perfeita custa sangue e dor física, a falha reside na teoria, nunca no mundo.", "warn": True},
      {"ic": "mask", "t": "A Dupla Justificativa", "emph": "Dupla Justificativa", "b": "Raskólnikov defende duas motivações para o mesmo machado: a <strong>utilitarista</strong> (“uma morte vil para mil boas ações”) e a <strong>napoleônica</strong> (“a audácia do ser superior”). Quando um único ato atroz exige duas justificativas brilhantes, a verdade suja se esconde atrás delas: ressentimento e vaidade.", "tip": "<strong>Como aplicar:</strong> identifique quando você empilha álibis racionais e nobres para maquiar uma ação que nasceu do próprio orgulho."}
    ]
  },
  "ch02-o-crime-petersburgo": {
    "cards": [
      {"ic": "eye", "t": "O Erro Imprevisto", "emph": "Imprevisto", "b": "O golpe <strong>acidental</strong> que mata Lizavieta — a irmã mansa da usurária, e justamente o tipo de oprimida que a teoria prometia emancipar — implodiu o cálculo perfeito. Qualquer incisão fria e justificada na realidade espalha um rastro de vítimas que a mente do estrategista se recusa a prever.", "tip": "<strong>Regra:</strong> o bisturi ideológico nunca é cirúrgico; a ação sobre a vida sempre gera consequências colaterais incontroláveis.", "warn": True},
      {"ic": "mountain", "t": "A Cidade Como Vício", "emph": "Cidade Como Vício", "b": "A fétida São Petersburgo de vielas abafadas não é mero cenário de fundo, mas um <strong>personagem obsessor</strong>. O suor constante, as escadas encardidas e o quarto do tamanho de um armário forjam o caldeirão onde o niilismo se justifica. Dostoiévski descreve o lixo para explicar a queda.", "tip": "<strong>Prática:</strong> perceba como um ambiente de degradação física crônica acelera a quebra das defesas morais mais básicas."},
      {"ic": "gap", "t": "O Roubo Sem Propósito", "emph": "Sem Propósito", "b": "O suposto grande assassino <strong>mal examina os bens roubados</strong>: esconde as joias debaixo de uma pedra e as apaga da memória. A indiferença ao saque escancara o blefe de que o crime visava financiar o bem maior. O sangue foi derramado para testar o ego, não a carteira.", "tip": "<strong>Modelo mental:</strong> quando as atitudes de alguém traem os seus “motivos declarados”, a verdade se encontra no que ele não faz."}
    ]
  },
  "ch03-culpa-consciencia-castigo": {
    "cards": [
      {"ic": "spiral", "t": "O Tribunal Interno", "emph": "Tribunal Interno", "b": "A fúria do remorso atropela de maneira <strong>orgânica e involuntária</strong>. Enquanto o raciocínio assinou a licença para matar, a consciência rejeitou o papel de Napoleão. O terror sufocante de Raskólnikov não é a ameaça de apodrecer na cadeia: é a decepção paralisante de descobrir que possui moral.", "tip": "<strong>Regra:</strong> a pena íntima é sempre proclamada no exato momento da infração; o juiz interior acorda antes das viaturas."},
      {"ic": "gap", "t": "O Muro do Isolamento", "emph": "Isolamento", "b": "O sangue seco corta brutalmente a ponte que ligava o estudante à humanidade. Ele sente repulsa e terror ao toque da mãe e do melhor amigo. O delito não apenas o condenou perante a lei, mas o transformou num <strong>fantasma exilado entre os vivos</strong>. Uma morte social muito pior que o cárcere.", "tip": "<strong>Sinal de alerta:</strong> o isolamento paranoico após uma ruptura ética costuma punir a mente com mais crueza do que a justiça dos tribunais.", "warn": True},
      {"ic": "bulb", "t": "O Magnetismo da Confissão", "emph": "Confissão", "b": "O herói flerta dolorosamente com a confissão, vagando pelas vielas e desafiando a polícia. Existe nele uma <strong>atração alucinada pela queda livre</strong>. O segredo impenetrável pesa infinitamente mais que o pavor das algemas: a mente corrompida clama por um observador que lhe imponha limites.", "tip": "<strong>Como aplicar:</strong> o ímpeto humano por rasgar a máscara e assumir o pecado frequentemente derrota o mais frio dos cálculos intelectuais."}
    ]
  },
  "ch04-sonia-amor-sacrificio-fe": {
    "cards": [
      {"ic": "leaf", "t": "A Transgressão Pelo Amor", "emph": "Pelo Amor", "b": "A jovem Sônia também vendeu o próprio corpo e transgrediu a moralidade de Petersburgo — porém, entregou-se <strong>para estancar a fome dos irmãos</strong>. O contraste desnuda a teoria: a mesma quebra da norma possui naturezas opostas e trilha caminhos cruzados, dividindo quem amou de quem apenas pensou.", "tip": "<strong>Modelo mental:</strong> o “o quê” da atitude revela menos do que o “por quê”. É o motor invisível da ação que define quem você se tornará."},
      {"ic": "book", "t": "A Promessa de Lázaro", "emph": "Promessa", "b": "A leitura ofegante da ressurreição do homem morto não é um simples interlúdio literário; é o <strong>mapa do epílogo</strong>. O corpo putrefato de Lázaro reflete o assassino trancado em seu ego. Há retorno à vida para quem já fede à morte, mas ele exige submissão completa à luz que a teoria sempre desprezou.", "tip": "<strong>Prática:</strong> o núcleo simbólico de grandes narrativas frequentemente é escondido no texto que um personagem decide ler."},
      {"ic": "key", "t": "A Fé Que Não Argumenta", "emph": "Não Argumenta", "b": "A garota esguia e humilhada não confronta as defesas acadêmicas do estudante com silogismos rebuscados — ela <strong>coloca a própria vida na mesa</strong>. A sua fé não carrega verniz filosófico, mas encarna o sacrifício tangível que permanece firme enquanto o imenso intelecto dele sofre um colapso completo.", "tip": "<strong>Sinal de alerta:</strong> a força brutal de uma ideia destrutiva nunca se desarma com outra ideia, apenas com o choque de uma vida real.", "warn": True}
    ]
  },
  "ch05-porfiry-duelo-psicologico": {
    "cards": [
      {"ic": "lens", "t": "A Caça Pelas Ideias", "emph": "Caça Pelas Ideias", "b": "Porfiry opera sem digitais, sem DNA e sem armas: ele manipula o artigo brilhante do estudante e o utiliza como laço sufocante. Cada curiosidade fofa mascara uma estocada implacável. O investigador escava a vaidade de Raskólnikov, obrigando-o a <strong>exibir o orgulho que pariu o sangue</strong>.", "tip": "<strong>Modelo mental:</strong> o interrogador letal sabe que o narcisismo obriga o pecador a explicar a própria genialidade aos quatro ventos."},
      {"ic": "wave", "t": "A Angústia Como Álibi", "emph": "Angústia", "b": "O juiz afiado entende que não precisa torturar o jovem — o maquinário cruel do remorso fará todo o serviço pesado. O plano é <strong>impedir a anestesia temporária</strong>. O tempo esticado e o desespero para partilhar o segredo convertem-se na polícia invisível. O exílio penal pareceria férias perto do quarto abafado.", "tip": "<strong>Prática:</strong> não declare a guerra; deixe que o inimigo sitiado esvazie as próprias energias correndo pelas paredes da sua mente."},
      {"ic": "fork", "t": "O Oxigênio da Punição", "emph": "Oxigênio", "b": "Ao mirar os olhos assombrados do criminoso, a autoridade decreta a redenção: “Entregue-se, meu jovem, você <strong>está precisando de ar</strong>”. O castigo deixa de soar como guilhotina e assume ares de resgate oxigenado. Cumprir a pena não será a ruína da vida de Raskólnikov, mas o único porto seguro.", "tip": "<strong>Regra:</strong> assumir a ferida sob o sol queima a pele instantaneamente, mas esconder a putrefação no escuro envenena a alma.", "warn": True}
    ]
  },
  "ch06-svidrigailov-o-duplo": {
    "cards": [
      {"ic": "masks", "t": "O Espelho Sem Consciência", "emph": "Sem Consciência", "b": "O aristocrata perverso Svidrigáilov representa o espelho mais aterrorizante: ele comete horrores silenciosos e <strong>não sente o peso de uma pluma sequer</strong>. Ele vive a cartilha irrestrita do “tudo é permitido” sem febres ou arrepios de pavor. É o fantasma do que Raskólnikov desejava e falhou em ser.", "tip": "<strong>Sinal de alerta:</strong> encare o anti-herói frio como a encarnação crua do futuro se você extirpar a bússola ética do intelecto.", "warn": True},
      {"ic": "gap", "t": "O Fundo Falso do Nada", "emph": "Fundo Falso", "b": "Esse duplo niilista tem arroubos pontuais de generosidade pagando orfanatos, mas o teatro da bondade <strong>não o preenche nem o aquece</strong>. Sem balizas ou chão sólido, a benesse vira apenas um tédio caprichoso. O niilismo que funciona como um relógio não sustenta significado: só alimenta o vazio do deserto interno.", "tip": "<strong>Modelo mental:</strong> um ato de caridade desgarrado de compromissos profundos não cura a doença da ausência de sentido."},
      {"ic": "mountain", "t": "O Tédio Até a Bala", "emph": "Tédio", "b": "O homem podre não encosta a arma na cabeça por causa da culpa cristã, mas pelo <strong>tédio insuportável e silencioso</strong>. Destituído do tormento moral e do afeto vital, a vida escorre pelas mãos sem peso. A bala na chuva não é punição: é o tédio existencial tirando a própria vida para não ter que acordar amanhã.", "tip": "<strong>Prática:</strong> antes de abraçar qualquer filosofia de liberdade total, olhe longamente para a sepultura de quem a praticou até o fim."}
    ]
  },
  "ch07-razumikhin-dunia-familia": {
    "cards": [
      {"ic": "person", "t": "O Oposto Em Dobro", "emph": "Oposto", "b": "O robusto e leal Razumíkhin chafurda na mesma pobreza aguda do herói, mas acorda trabalhando e sorrindo alto. Ele é a <strong>faca afiada do contra-argumento dostoievskiano</strong>: não foi a miséria de Petersburgo que gerou o machado. Foram o narcisismo e a teoria letal criados no isolamento que assinaram as mortes.", "tip": "<strong>Como aplicar:</strong> meça a verdade não apenas pelas dores da queda, mas pelos homens que caminham pela mesma lama sem se sujarem."},
      {"ic": "scale", "t": "O Orgulho Com Freio", "emph": "Orgulho", "b": "Dúnia herda a mesma empáfia inquebrável e os olhos duros de seu irmão, mas possui <strong>a fé cravada nas entranhas</strong>. Ao sacar o revólver contra o vilão no cômodo trancado, ela demonstra que o orgulho iluminado não precisa degolar para vencer. A sua força se estrutura na defesa ética, não no ataque teórico.", "tip": "<strong>Modelo mental:</strong> a altivez não é o pecado original; o desastre acontece quando a arrogância corta o fio que a liga ao mundo."},
      {"ic": "key", "t": "O Mal Respeitável", "emph": "Mal Respeitável", "b": "O polido burocrata Lújin encarna a faceta encerada e elegante da mesma moeda: ele mói reputações e manipula viúvas paupérrimas usando a precisão de um advogado, escorado em <strong>justificativas de mercado e etiqueta</strong>. O romance cospe nele para mostrar que a violência fria dos engravatados também suja as mãos.", "tip": "<strong>Armadilha:</strong> o cálculo metódico e chancelado pelas regras costuma deixar um saldo de destruição imune aos olhos da lei.", "warn": True}
    ]
  },
  "ch08-petersburgo-miseria-simbolos": {
    "cards": [
      {"ic": "layers", "t": "A Sujeira Como Bússola", "emph": "Sujeira", "b": "A poeira amarela e sufocante do verão não enfeita parágrafos; <strong>o calor esmagador atua como promotor do crime</strong>. Dostoiévski esfrega o calor rançoso nas retinas para que o delírio intelectual soe plausível, sem nunca validar a desculpa sociológica de que o criminoso é apenas refém da sua vizinhança.", "tip": "<strong>Modelo mental:</strong> entenda a descrição espacial não como fotografia literária, mas como termômetro brutal do caldeirão psicológico."},
      {"ic": "eye", "t": "A Paleta do Desespero", "emph": "Paleta", "b": "A tinta <strong>amarela</strong> pinta os rostos doentes e o delírio decrépito. A <strong>água</strong> espelha a decisão do suicida ou promete a limpeza catártica. A <strong>cruz</strong> encarna o choque doloroso do renascimento, e o próprio machado personifica a guilhotina teórica descendo sobre pescoços inocentes. O objeto narra a tese.", "tip": "<strong>Prática:</strong> enxergue as chaves filosóficas por trás dos móveis rotos e das paredes rachadas que a boa literatura pinta."},
      {"ic": "pin", "t": "A Tumba de Três Passos", "emph": "Tumba", "b": "O cômodo de proporções sufocantes e papel de parede sujo onde o assassino respira <strong>é o útero asfixiante do desastre</strong>. O orgulho inflamado e a imundície estrutural se retroalimentam no espaço. Quando a polícia declara “você precisa de ar”, ela aponta tanto para os pulmões encolhidos quanto para a alma engaiolada.", "tip": "<strong>Armadilha:</strong> o teto baixo pressiona a mente; é impossível nutrir clareza de horizonte enquanto se vive atolado na clausura.", "warn": True}
    ]
  },
  "ch09-confissao-sofrimento-epilogo": {
    "cards": [
      {"ic": "mountain", "t": "A Palavra Antes da Culpa", "emph": "Culpa", "b": "No pátio gélido da delegacia, o estudante joga as palavras ao vento, mas os dentes trincados gritam que o cérebro dele <strong>ainda ama a fórmula do crime</strong>. O lamento genuíno demora a chegar. Primeiro ajoelha-se o corpo perante o juiz; só depois, lentamente, o ego racha perante a força da consciência.", "tip": "<strong>Como aplicar:</strong> aceite que a correção do erro muitas vezes principia na ação seca de se expor, e não em lágrimas imediatas."},
      {"ic": "spiral", "t": "O Vírus Incurável do Ego", "emph": "Vírus", "b": "Já varrendo o chão de uma Sibéria sombria, ele sonha com uma poeira letal onde todos os contaminados se declaram detentores absolutos da luz, espalhando uma <strong>pandemia de vaidade teórica</strong>. Essa alucinação grotesca é a mais clara denúncia dostoievskiana contra o estrago do pensamento puro e isolado.", "tip": "<strong>Sinal de alerta:</strong> ideias inflamadas e intocáveis matam mais que exércitos; a doença do ego coletivo não precisa de diagnóstico clínico.", "warn": True},
      {"ic": "leaf", "t": "A Dialética Desaba", "emph": "Desaba", "b": "Sentado à margem do rio siberiano, o herói deforma o rosto em pranto e abraça os joelhos de Sônia sem resistir. O castelo de silogismos evaporou diante do <strong>solavanco inegável do amor encarnado</strong>. A carne que sangrou pelo narcisismo descobre o milagre de se encher de paz unicamente pelo solo da aceitação.", "tip": "<strong>Modelo mental:</strong> nenhuma muralha lógica resiste para sempre ao baque silencioso e avassalador de alguém disposto a sofrer com você."}
    ]
  }
}

with open(out_file, "a", encoding="utf-8") as f:
    f.write("=== audiovisao ===\n```json\n" + json.dumps(data1, ensure_ascii=False, indent=2) + "\n```\n\n")
    f.write("=== crime-e-castigo ===\n```json\n" + json.dumps(data2, ensure_ascii=False, indent=2) + "\n```\n\n")

print("Part 1 done.")
