import json

out_file = r"C:\Users\User\.gemini\antigravity\scratch\biblioteca\_kit_preview\gemini_in\batch_9_out.md"

data3 = {
  "ch01-onda-de-sofrimento": {
    "cards": [
      {"ic": "wave", "t": "A Grande Reconfiguração", "emph": "Reconfiguração", "b": "A tela não mudou o mundo aos poucos; ela operou um corte brusco na espinha dorsal do desenvolvimento. O smartphone com câmera frontal, as curtidas anestesiantes e a internet de bolso forjaram um ambiente <strong>viciante por design perfeito</strong>. A infância saltou da brincadeira na rua direto para o fosso digital.", "tip": "<strong>Modelo mental:</strong> fixe 2012 como o divisor definitivo — se o surto aconteceu depois desse ano, ele tem endereço certo."},
      {"ic": "triangle", "t": "A Curva do Hospício", "emph": "Curva do Hospício", "b": "Os números de automutilação entre pré-adolescentes femininas saltaram assustadoramente a partir de 2012 e 2013, pintando no gráfico uma inclinação abrupta e agressiva. É uma ascensão veloz, afiada e <strong>sincronizada internacionalmente ao mesmo tempo</strong>. A curva não é um palpite sociológico; é o rastro da doença.", "tip": "<strong>Sinal de alerta:</strong> quando indicadores do mundo inteiro colapsam num mesmo segundo histórico, a causa também é única e global.", "warn": True},
      {"ic": "gap", "t": "O Mito Dos Tempos Difíceis", "emph": "Mito", "b": "Culpar os estragos econômicos ou a tensão política não explica o motivo exato de os hospitais lotarem de pré-adolescentes subitamente na mesma data. Tratar isso como o tradicional pânico moral da velhice <strong>ignora estupidamente a escala geométrica do dano</strong>. Você não está olhando para uma frescura da época, mas para uma quebra real.", "tip": "<strong>Armadilha:</strong> dizer “o jovem sempre sofreu” é o disfarce mais eficaz para silenciar o alarme e não mudar nada."}
    ]
  },
  "ch02-o-que-criancas-precisam": {
    "cards": [
      {"ic": "leaf", "t": "O Currículo Oculto", "emph": "Currículo Oculto", "b": "A brincadeira arriscada não guiada por adultos é a engrenagem principal de toda autorregulação emocional. Quando duas crianças brigam para decidir a regra do pega-pega, elas <strong>negociam atritos e treinam limites sozinhas</strong>. Isso vale dez vezes mais do que um software pedagógico seguro. O risco forja a musculatura da alma.", "tip": "<strong>Prática:</strong> deixe a criança assumir os tombos não-fatais do parquinho — cada arranhão é uma lição biológica essencial."},
      {"ic": "bubble", "t": "Sintonia e Freio", "emph": "Sintonia", "b": "A valsa contínua de sorrisos, tons de voz e olhares trocados constrói o hardware do comportamento saudável. Enfiar a tela na mão de uma criança para “acalmar a birra” atua como veneno psíquico: você treina a mente dela a <strong>pedir distração em vez de regular a própria frustração</strong>.", "tip": "<strong>Armadilha:</strong> o ipad pacificante anestesia o sintoma do choro, mas estraçalha o aprendizado do autocontrole.", "warn": True},
      {"ic": "clock", "t": "A Argila da Puberdade", "emph": "Argila", "b": "A fase inicial da adolescência atua como um imã de referências. O cérebro da juventude consome qualquer cultura oferecida de forma brutal. Se você permite que o feed incessante seja o professor principal, <strong>é ele quem vai cimentar a identidade inteira</strong>. E o algoritmo nunca ensina paciência ou profundidade.", "tip": "<strong>Modelo mental:</strong> considere a puberdade como a argila mais mole e valiosa da vida — o que você carimba ali, endurece e não sai mais."}
    ]
  },
  "ch03-modo-descoberta": {
    "cards": [
      {"ic": "mountain", "t": "Descoberta Versus Defesa", "emph": "Descoberta Versus Defesa", "b": "A criança no “Modo Descoberta” se joga corajosamente no desconhecido para florescer, enquanto no “Defesa” ela se fecha, consumida pelo pavor de existir. Uma base segura na terra firma os passos; contudo, a superproteção histérica na rua <strong>arrasta o cérebro diretamente para o medo</strong> crônico.", "tip": "<strong>Pergunta-chave:</strong> ao aprovar qualquer rotina na vida do jovem, interrogue-se: “Isto atiça a coragem ou alimenta o pânico?”"},
      {"ic": "leaf", "t": "A Vacina do Risco", "emph": "Vacina", "b": "A juventude é naturalmente antifrágil: ela ganha densidade justamente nos confrontos, tombos e arranhões controlados. Eliminar a brincadeira arriscada <strong>esteriliza a infância de suas defesas imunológicas naturais</strong>. O quarto macio, limpo e à prova de choque garante segurança hoje e produz um adulto aterrorizado amanhã.", "tip": "<strong>Sinal de alerta:</strong> poupar o seu filho de todo e qualquer tombo é assinar a sentença de fraqueza existencial dele.", "warn": True},
      {"ic": "steps", "t": "A Inversão do Rito", "emph": "Inversão", "b": "As sociedades sempre balizaram o crescimento com marcos de suor e sangue. Nós extinguimos as fogueiras rituais e invertemos a régua: <strong>hiperprotegemos no asfalto e abandonamos o jovem sozinho na trincheira virtual</strong>. A bússola certa exige mais ralo de joelho na rua e portas blindadas no quarto digital.", "tip": "<strong>Regra:</strong> construa pequenos ritos práticos de independência gradativa — comprar pão sozinho vale mais que a mesada gorda."}
    ]
  },
  "ch04-quatro-danos": {
    "cards": [
      {"ic": "triangle", "t": "Os Quatro Danos Gêmeos", "emph": "Quatro Danos", "b": "O ataque é múltiplo: privação letal do sono, isolamento do contato humano, a faca invisível dividindo a atenção e <strong>o vício absoluto moldando mentes</strong>. Um aplicativo não rouba só tempo, ele tritura as peças fundamentais que mantêm um organismo inteiro saudável. Quando se agrava o quarto, os outros três desmoronam.", "tip": "<strong>Prática:</strong> submeta o hábito de uso à peneira: ele arranca sono, contato físico, foco ininterrupto ou exige compulsão?"},
      {"ic": "gap", "t": "O Custo do Que Morreu", "emph": "Morreu", "b": "O mal da tela muitas vezes se esconde atrás daquilo que ele soterrou silenciosamente. Não é apenas sobre o brilho azul desgastando a retina, mas sobre as gargalhadas corporais que nunca aconteceram, o sono que a mente não colheu e as amizades que <strong>morreram de inanição</strong> por falta de presença.", "tip": "<strong>Modelo mental:</strong> olhe fixamente para a hora logada e calcule o imposto brutal das experiências terrenas que foram esquecidas."},
      {"ic": "spiral", "t": "O Cassino no Bolso", "emph": "Cassino", "b": "A recompensa variável é a roleta enfiada no córtex infantil: o jovem roda a alavanca incessante do feed e aguarda a luz piscar no cérebro frágil. Como o freio frontal ainda sequer existe biologicamente para os adolescentes, <strong>eles cedem ao delírio sem controle</strong>. Rede social não cura solidão; ela agita a miséria do isolamento.", "tip": "<strong>Armadilha:</strong> justificar a tela infinita como “conexão social” é endossar um cassino sob o falso pretexto de terapia de grupo.", "warn": True}
    ]
  },
  "ch05-meninas-meninos": {
    "cards": [
      {"ic": "wave", "t": "O Veneno da Tela Feminina", "emph": "Veneno", "b": "O ecossistema digital encontra sua presa na sociabilidade das meninas: ele exacerba a epidemia sociogênica, transforma a comparação dolorosa em esporte oficial e <strong>eterniza as agressões minúsculas em humilhação com alcance global</strong>. A rede esmaga a fragilidade sob os holofotes, sem chance para a amnésia e para o perdão natural.", "tip": "<strong>Sinal de alerta:</strong> um tropeço adolescente que antes durava três dias de fofoca, na rede, crava as garras para toda a vida.", "warn": True},
      {"ic": "gap", "t": "Os Meninos Na Caverna", "emph": "Na Caverna", "b": "Os garotos perdem a batalha de outra forma: rastejam devagar e invisíveis em direção aos jogos e à pornografia infinita. Quando a agressividade esportiva e a aprovação na terra fracassam, o computador oferece a eles <strong>a sensação falsa de um progresso heroico contínuo</strong>. A fuga para o conforto isola antes de enfraquecer por inteiro.", "tip": "<strong>Como aplicar:</strong> para resgatar o rapaz da caverna iluminada, o asfalto real precisa voltar a prometer respeito, risco e conquista material."},
      {"ic": "scale", "t": "Danos Que Correm Frios", "emph": "Danos", "b": "Enquanto as garotas sangram ruidosamente a dor para dentro em quadros depressivos intensos, a apatia masculina caminha nas sombras com isolamento inaudível e impotência a longo prazo. Ignorar um deles porque o outro grita mais alto no hospital <strong>é sentenciar ambos ao mesmo enterro silencioso</strong>.", "tip": "<strong>Modelo mental:</strong> a radiação envenena a garota pelo holofote que incendeia, e destrói o garoto pela penumbra que o acomoda."}
    ]
  },
  "ch06-elevacao-espiritual": {
    "cards": [
      {"ic": "mountain", "t": "O Elevador da Alma", "emph": "Elevador da Alma", "b": "Para esmagar a degradação anestesiante do feed, é preciso abraçar práticas de chão e carne: silêncio absoluto, suor em conjunto, gratidão intencional e reverência diante da natureza. Não basta arrancar o fio da tomada, você precisa preencher o vazio deixado com <strong>energia que expanda a caixa do peito</strong>.", "tip": "<strong>Prática:</strong> o silêncio focado no vento, sem lente e sem filtro, já queima parte do lixo virtual ancorado no cérebro."},
      {"ic": "leaf", "t": "A Efervescência Coletiva", "emph": "Efervescência Coletiva", "b": "A temperatura alta gerada pelo atrito da presença física não tem equivalente eletrônico. Dividir suor em uma quadra ou cantar apertado em volta da mesa cria laços que a tela gelada não sustenta. Arrancar o celular e largar a criança sozinha no próprio quarto vazio <strong>é apenas assinar o convite para a recaída veloz</strong>.", "tip": "<strong>Regra:</strong> não extirpe o aparelho das mãos se você não possui a coragem para puxar a família inteira para o centro de uma fogueira verdadeira."},
      {"ic": "spark", "t": "A Fábrica de Indignação", "emph": "Fábrica de Indignação", "b": "O ambiente cibernético transforma o escândalo barato na virtude principal da comunidade: o julgamento raivoso viraliza de forma gloriosa porque preenche os bolsos de quem minera o caos. Sentir que você está brigando por justiça apertando um teclado <strong>é a suprema degradação espiritual mascarada de heroísmo civil</strong>.", "tip": "<strong>Sinal de alerta:</strong> se você confunde vomitar sentenças iradas na tela com o dever cívico de melhorar o mundo, o algoritmo já te consumiu.", "warn": True}
    ]
  },
  "ch07-acao-coletiva": {
    "cards": [
      {"ic": "link", "t": "O Dilema dos Pais", "emph": "Dilema", "b": "O bloqueio isolado e corajoso se torna a tortura cruel se ninguém apoiar. O isolamento do pai solitário não é falta de fibra, mas covardia da manada: a força está em puxar as algemas de forma uníssona. A guerra exige o <strong>pacto silencioso das dezenas de casas juntas</strong>, ou todos morrerão atirando sozinhos de seus quartéis.", "tip": "<strong>Prática:</strong> abandone a fantasia militar individual; você necessita de meia dúzia de pais aliados agindo no exato mesmo fim de semana."},
      {"ic": "steps", "t": "A Alavanca em Bloco", "emph": "Alavanca em Bloco", "b": "A mudança opera apenas tracionando cabos paralelos: acordo visceral entre famílias para atrasar a primeira tela, vergonha alheia coletiva ao expor que celular na mesa é nojento, e escolas fechando as bolsas de cadeado. Nenhuma medida destrói a besta <strong>sozinha e enfraquecida</strong>.", "tip": "<strong>Regra:</strong> você não quebra um pilar de concreto com um machado só; todas as frentes da comunidade batendo unidas são essenciais."},
      {"ic": "mountain", "t": "De Volta à Terra Firme", "emph": "Terra Firme", "b": "Qualquer regra rígida implementada em casa só possui valor se ela agarrar o seu filho e atirá-lo de volta para a terra solta, para os galhos quebrados e para os encontros na sala. A sabotagem foi fabricada por homens, e nós próprios deteremos a maré se escolhermos <strong>a lama quente ao invés do gelo digital inerte</strong>.", "tip": "<strong>Pergunta-chave:</strong> essa medida restritiva aproxima a criança da vida física ou apenas impõe tortura pelo vazio?"}
    ]
  }
}

data4 = {
  "ch01-monomito-arquetipos": {
    "cards": [
      {"ic": "spiral", "t": "A Força do Monomito", "emph": "Monomito", "b": "O herói é expulso do conforto, sangra perante os monstros e mergulha num abismo obscuro para resgatar o tesouro que salvará a sua aldeia. Sob o verniz da ficção exótica, existe um <strong>espelho escancarado da própria condição humana</strong>. O monomito é a espinha dorsal de toda transformação que o público já sofreu.", "tip": "<strong>Modelo mental:</strong> os golpes e precipícios do mundo externo na história são a carne rasgada do próprio conflito moral do herói."},
      {"ic": "layers", "t": "A Máscara do Arquétipo", "emph": "Máscara", "b": "Um arquétipo nunca é um crachá permanente: ele atua como uma roupa pesada e provisória que os personagens vestem para cumprir o que a trama grita. Um aliado dócil pode calçar os sapatos da Sombra por cruéis cinco páginas, e <strong>isso é o que injeta eletricidade nas veias da obra trancada</strong>.", "tip": "<strong>Prática:</strong> troque as máscaras dos seus personagens e desestabilize o previsível; o sábio pode tentar derrubar o menino no abismo."},
      {"ic": "eye", "t": "O Risco da Forma Rígida", "emph": "Forma Rígida", "b": "Tratar a viagem do herói como uma receita de bolo contendo miligramas exatos asfixia a voz autêntica. Subverta a ordem, arranque um degrau e exija que ele pule de ponta-cabeça. O método serve para <strong>mapear as curvas da estrada, não para engessar os joelhos de quem caminha sangrando</strong>.", "tip": "<strong>Armadilha:</strong> encarnar arquétipos estereotipados e frouxos arranca a alma dos personagens em favor de um preenchimento matemático.", "warn": True}
    ]
  },
  "ch02-mundo-comum-chamado": {
    "cards": [
      {"ic": "book", "t": "O Chão do Mundo Comum", "emph": "Mundo Comum", "b": "A monotonia esmagadora da rotina, a falha ridícula e a fragilidade doentia: desenhe o buraco inicial para que a escalada seja mensurável. Sem o gosto enjoado do café de todo dia, não existe <strong>a urgência palpável pelo choque elétrico da aventura</strong>. Mostre quem é ele caindo aos pedaços em casa.", "tip": "<strong>Como aplicar:</strong> exponha imediatamente a ferida purulenta do personagem antes de jogar a corda para ele tentar fugir."},
      {"ic": "wave", "t": "O Bote na Jugular", "emph": "Bote", "b": "O chamado desponta como um abalo sísmico inadiável que queima a casa do herói. Não estamos lidando com um sussurro educado, mas com a <strong>inexorável implosão das estruturas daquela vida mansa</strong>. A porta dos fundos bate com estrondo, forçando o corpo a correr sem olhar para o incêndio nas costas.", "tip": "<strong>Modelo mental:</strong> o abalo que pode ser negado sem qualquer arranhão não passa de uma sugestão anêmica; o chamado estilhaça o teto."},
      {"ic": "target", "t": "A Faca do Arauto", "emph": "Arauto", "b": "A mensageira das exóticas notícias entrega o pacote e obriga que os olhos se voltem para a escuridão do abismo à frente. Seja pessoa ou reviravolta fatal, o que o Arauto carrega nos dentes é <strong>o aviso irrevogável de que a passividade acomodada já apodreceu</strong>.", "tip": "<strong>Regra:</strong> alongar demais a apresentação das panelas da casa queima o interesse da sua audiência, enfie logo a bota do Arauto na porta."}
    ]
  },
  "ch03-recusa-mentor": {
    "cards": [
      {"ic": "clock", "t": "A Recusa Visceral", "emph": "Recusa", "b": "O passo apavorado para trás, as mãos trêmulas e o pretexto acovardado testam imediatamente a veracidade do abismo. Não existe herói inquebrável diante da perspectiva de morte e ruína: o pavor injeta carne e credibilidade na tensão. Se a decisão <strong>não custar pânico letal, a travessia cheirará a mentira</strong>.", "tip": "<strong>Prática:</strong> explore os recuos apavorados — a coragem imensa não anula o tremor nos joelhos; ela opera através dele.", "warn": True},
      {"ic": "key", "t": "O Dom do Mentor", "emph": "Mentor", "b": "A energia canalizada por conselhos ardentes, mapas manchados ou um artefato ancestral engatilha o protagonista para o primeiro passo. Mas essa injeção representa o eu superior do aprendiz apenas enquanto este se rasteja. Entregue o presente e faça o mestre <strong>sumir para não roubar a tela dramática inteira</strong>.", "tip": "<strong>Modelo mental:</strong> o farol aponta o porto de longe, mas de forma alguma pilota a caravela em meio ao mar agitado."},
      {"ic": "eye", "t": "A Praga do Mestre Onipotente", "emph": "Onipotente", "b": "O velho sábio que domina todas as magias estraga a cena, sugando completamente os holofotes. Se o cajado milagroso resolver o problema com pó divino, por que raios nós perderíamos tempo com o pupilo inútil? O artefato entregue pelo mentor é só um <strong>gás que vaza, não o isqueiro aceso</strong>.", "tip": "<strong>Armadilha:</strong> o mestre que resolve os perigos mata o próprio protagonista com a sombra maciça do paternalismo raso."}
    ]
  },
  "ch04-travessia-limiar": {
    "cards": [
      {"ic": "steps", "t": "O Teste de Sangue", "emph": "Teste de Sangue", "b": "A ponta da bota enfiada no mundo hostil, o choque cortante das regras cruéis daquele novo ecossistema e a certeza de que retornar equivale à covardia morta. A fronteira violada demarca <strong>a adesão voluntária à guerra incerta</strong>, batendo o martelo final no ponto absoluto e sem remissão de volta.", "tip": "<strong>Como aplicar:</strong> carimbar o passaporte não exige volta atrás. Imponha uma perda colossal caso a figura hesite ao atravessar."},
      {"ic": "gap", "t": "O Monstro do Limiar", "emph": "Limiar", "b": "Ele não reina supremo e não carrega a chave do arco final; ele guarda friamente os portões das estradas sujas. O porteiro ataca quem se atreve a violar a redoma, testando <strong>o nível do desespero e da fúria do escolhido de carne frouxa</strong>. Seu objetivo principal não é matar, mas espantar os fracos de coração.", "tip": "<strong>Modelo mental:</strong> os vigias das portas aceitam contorno, pagamento ou pancada veloz, mas eles jamais demandam o prato principal da ação."},
      {"ic": "eye", "t": "O Salto Sem Fogo", "emph": "Salto Sem Fogo", "b": "Atravessar portas gigantescas sendo arremessado por mãos alheias reduz o personagem a uma carga transportada num trem fantasma. Limiares frios que não pedem taxa de sangue destroem completamente o impacto e cospem no compromisso interno. Quando a travessia é gratuita, o viajante segue <strong>morno e afogado na inércia profunda no ato seguinte</strong>.", "tip": "<strong>Armadilha:</strong> heróis rebocados esvaziam totalmente o clímax emocional e rebaixam a aposta épica a um mero passeio turístico.", "warn": True}
    ]
  },
  "ch05-provas-aliados-inimigos": {
    "cards": [
      {"ic": "target", "t": "O Ferro das Provas", "emph": "Provas", "b": "Lutas de escada e tropeços nas armadilhas rasas, esses pequenos abalos lapidam a lâmina e sujam a bota de suor e lama. Cada teste eleva a fervura da panela, revela o caráter sob pressão e prepara <strong>a musculatura que não poderá engasgar na Provação Central</strong>. Não encha linguiça com ação fútil; adestre as dores internas.", "tip": "<strong>Prática:</strong> considere o meio da trama como a aula dolorosa do dia; cada conflito exige uma nota rabiscada em vermelho."},
      {"ic": "layers", "t": "A Trupe e o Espelho Escuro", "emph": "Espelho Escuro", "b": "A facção aliada cimenta a confiança enquanto o arqui-inimigo escurece o céu sob a marca densa da Sombra. E o vilão absoluto cumpre o papel magistral: ele grita as fraquezas latentes do próprio salvador no fundo da alma. O rival bem talhado atua como <strong>a visão corrompida de tudo que o protagonista poderia encarnar amanhã</strong>.", "tip": "<strong>Modelo mental:</strong> a oposição impecável revela nitidamente o veneno embutido que o justiceiro luta amargamente para não provar."},
      {"ic": "eye", "t": "Provas Sem Osso", "emph": "Sem Osso", "b": "Conflitos soltos e companheiros enfeitados matam cruelmente as páginas. O figurante desocupado cega o ritmo, e a ameaça sem enraizamento na culpa principal estilhaça e pulveriza o coração da tese narrativa da obra. As peças mecânicas precisam <strong>morder a carne e mastigar o espírito da plateia ao mesmo instante</strong>.", "tip": "<strong>Armadilha:</strong> lutas plásticas que não alteram a pele e os ossos por dentro desperdiçam dinheiro da produção e tempo valioso do público.", "warn": True}
    ]
  },
  "ch06-aproximacao-provacao": {
    "cards": [
      {"ic": "spiral", "t": "O Ventre da Baleia", "emph": "Ventre", "b": "A noite brutal da trama esmaga o ar do herói com o calcanhar de chumbo. Mergulhado na cova úmida e rasgado perante o monstro primordial, o herói não cede as roupas, <strong>ele morre simbolicamente para renascer com as cicatrizes rudes do saber</strong>. O centro de gravidade emana da força incontrolável do abismo estilhaçado.", "tip": "<strong>Regra:</strong> não há renascimento real sem a destruição dolorosa e prévia de um dos pilares imensos daquela figura central."},
      {"ic": "key", "t": "A Poeira da Morte", "emph": "Morte", "b": "As engrenagens estalam sob o desespero de forma contundente, a velha casca finalmente se esvai no ralo quente de dor pura. A emergência gloriosa ocorre apenas e restritamente das cinzas pegajosas do campo de batalha. Quando o personagem prende a respiração nas trevas, <strong>a plateia sente a corda rasgar na própria garganta também</strong>.", "tip": "<strong>Modelo mental:</strong> o ponto sem fundo dita com exatidão a gravidade de cada mísera fagulha jogada desde a abertura das cortinas."},
      {"ic": "eye", "t": "A Morte em Banho-Maria", "emph": "Banho-Maria", "b": "Vitórias limpas que tombam sem arranhar uma unha sequer esvaziam o caldeirão de fogo por completo. Se nós nunca mordemos o lábio duvidando seriamente do retorno, o renascimento divino vira um teatrinho barato de domingo. A ação plástica sem nenhuma morte interna arrastada é <strong>apenas um truque oco de pirotecnia covarde e infantil</strong>.", "tip": "<strong>Armadilha:</strong> o público não tolera o roteirista bundão: poupar a vida com manobras fáceis destrói a força do pacto firmado.", "warn": True}
    ]
  },
  "ch07-recompensa": {
    "cards": [
      {"ic": "target", "t": "A Espada Sangrenta", "emph": "Espada Sangrenta", "b": "A conquista ardente do artefato cintilante encharcado em sangue, o autoperdão, a lâmina que mata deuses. As mãos trêmulas seguram com unhas e dentes <strong>algo que a morte atroz validou com os próprios carimbos gelados</strong>. Esse baú da recompensa carrega incrustado o custo extorsivo e explícito do horror monumental que ficou nas costas do abismo cego.", "tip": "<strong>Prática:</strong> o prêmio tem que exibir lascas na empunhadura; algo ganho num abraço não passa de ouro folheado da feira livre."},
      {"ic": "clock", "t": "O Falso Respiro", "emph": "Falso Respiro", "b": "A anestesia temporária desponta no copo esvaziado: beijos salgados, espadas erguidas num engano reconfortante e <strong>a farsa doce de que acabou tudo aqui no meio do prado ensolarado</strong>. É o esticar elástico antes da pancada asfixiante que rasgará todo o fôlego da corrida final, o demônio inerte preparou o silêncio mais sujo e cruel de todo o ato de desfecho.", "tip": "<strong>Modelo mental:</strong> o alívio exagerado esconde nas frestas da janela o tombo mais cruel e furioso de toda a espinha dorsal."},
      {"ic": "eye", "t": "A Festa Que Não Acaba", "emph": "Não Acaba", "b": "Deixar o brinde prolongado na praça afoga a obra. Se o herói engorda rindo, a tribo faminta e esquecida <strong>morre amargurada no frio, longe do fogo que as mãos manchadas e feridas roubaram brilhantemente</strong>. A paralisação egocêntrica decepa rudemente a essência do que movimenta a energia mitológica da coroa estendida perante a tela rasgada do céu.", "tip": "<strong>Armadilha:</strong> o herói que consome a vitória mastigando a torta solitário assassina rudemente toda a empatia injetada na veia humana."}
    ]
  },
  "ch08-caminho-de-volta": {
    "cards": [
      {"ic": "steps", "t": "A Fuga Final", "emph": "Fuga Final", "b": "A escolha de engatar a terceira e partir alucinado fugindo das bestas esfoladoras que clamam fúria de resgate com ódio visceral puro nas retinas manchadas de prata. A fuga apavorante quebra a quietude da canção. <strong>O retrovisor acusa cinzas suadas e os dentes rasgam a poeira voando em direção direta à vingança que acendeu as tochas de asfalto fervente</strong>.", "tip": "<strong>Como aplicar:</strong> o freio é rasgado com lâmina bruta; a retirada quase sempre clama desesperadamente pela alavanca de uma caçada esbaforida."},
      {"ic": "wave", "t": "A Faca na Costela", "emph": "Faca na Costela", "b": "A reviravolta enfia com força a lâmina fria na escuridão fofa para injetar o fôlego asfixiante no clímax impiedoso. Se o caldeirão não engolir gasolina pura agora no escuro rasgado, <strong>ninguém ligará mais se as engrenagens finais contam o troféu ou sangram perdidas</strong>. As apostas batem violentamente do teto descascado e furam os tijolos do alicerce esfacelado da última porta erguida e derrubada no porão escuro.", "tip": "<strong>Prática:</strong> a trégua é covardia que o mestre atira na lixeira do quarto, desperte os lobos ensanguentados que rasgarão o pescoço."}
    ]
  },
  "ch09-ressurreicao": {
    "cards": [
      {"ic": "spiral", "t": "O Clímax Final", "emph": "Clímax", "b": "A colisão frontal arrasadora estraçalha os muros <strong>mil vezes mais cortante e aguda do que as chamas do abismo lá debaixo</strong>. Toda a aldeia, a carne humana, o cérebro rasgado pendem num estalar letal de pura tensão insuportável no ar enfumaçado. O ex-escravo levanta carbonizado para calcinar a covardia impiedosamente perante o mundo cego agora subjugado pela força do aprendizado calejado cravado fundo na espinha.", "tip": "<strong>Prática:</strong> dobre estupidamente o risco perante os deuses, o abismo inicial atinge o nível de aquecimento na porta deste novo inferno destrancado."},
      {"ic": "target", "t": "O Fogo da Transformação", "emph": "Transformação", "b": "Os clichês ocos apodrecem sumariamente, dando total reinado absoluto <strong>à decisão insana de provar sob o ferro fumegante, rasgo impiedoso e asfalto cru que o sangue não mentiu feio</strong>. Cada célula costurada do saber novo explode nos atos frenéticos das mãos, decretando em berros cegos de ação visceral e brutal a mudança interna do novo cérebro nojento e refeito no fogo sem perdão alheio das regras velhas de papel amassado e pisoteado duro e rude do antigo porto afundado agora há pouco tempo e sem chances das algemas prenderem de novo o coração quebrado do antigo morador de lá debaixo das águas congeladas dos velhos tempos passados que agora evaporaram no nada fumaçado cinzento", "tip": "<strong>Regra:</strong> os votos bonitos morrem na garganta seca e vazia; exiba a mutação dilacerante nos dedos e punhos esmagando impiedosamente a ignorância fraca e acomodada no lixo"},
      {"ic": "sword", "t": "O Interventor Barato", "emph": "Interventor", "b": "O relâmpago divino descendo mágico fritando todo o exército final arranca descaradamente das mãos encharcadas a merecida e calejada catarse da plateia farta. Quando a entidade milagreira do autor medroso corta a dor e entrega os sorrisos sem rasgar a camisa, <strong>a criatura ressuscitada perde vergonhosamente o prêmio; virou apenas estorvo da sorte que sobreviveu sem o próprio soco ensanguentado cravado e orgulhosamente deixado perante o caixão do oponente morto</strong>.", "tip": "<strong>Armadilha:</strong> o raio abençoado que liquida vilões complexos e grandiosos mata junto cruelmente a honra do sangue cravado e empurra a bilheteria e as folhas para as lamas inférteis", "warn": True}
    ]
  },
  "ch10-retorno-com-elixir": {
    "cards": [
      {"ic": "key", "t": "A Cura Entregue", "emph": "Cura", "b": "A poeira tóxica acalma devagar e os pulsos calejados esvaziam o jarro divino diretamente no centro deprimido e rasgado da aldeia. A coroa ou abraço arrebatador sacia de imediato a sede amarga que estraçalhava as gargantas feridas das pessoas apagadas do poço morto. <strong>A catarse irrecusável e final atesta esplendidamente que sofrer o abismo consertou maravilhosamente a aldeia, justificando o ferro</strong>.", "tip": "<strong>Modelo mental:</strong> o herói desgraçado e arranhado porta a coroa dourada estritamente e unicamente porque despejou sem pensar no pódio um oceano curativo sobre cabeças suadas do vilarejo vazio e escuro."},
      {"ic": "spiral", "t": "O Círculo e o Chão Limpo", "emph": "Círculo", "b": "O rancho apodrecido desenhado nas aberturas reaparece esplendorosamente preenchido do vigor vibrante injetado nas tábuas finas — <strong>as espadas do retorno lavam ferozmente as misérias iniciais esfregadas no rosto cético do leitor que perdoou a rotina inicial lenta</strong>. O prado final enxuga esplendidamente as lágrimas da abertura poeirenta de outrora fechando magistralmente a rima gloriosa encravada no roteiro das canetas rasgadas e reescritas arduamente na escrivaninha das lágrimas fáceis do escritor doente de cafeína barata na cadeira velha", "tip": "<strong>Prática:</strong> a última câmera do plano arranca a dor espinhosa e exalta as montanhas que a lama rasteira dos primeiros quadros esquecidos chorava de inveja crua"},
      {"ic": "eye", "t": "O Tesouro Escondido", "emph": "Tesouro", "b": "Encerrar a corrida pálido abraçando os malotes repletos sozinho num egoísmo infantil escuro, apaga desastrosamente as marcas majestosas do aço. <strong>A epifania efervescente tomba rastejante asfixiada porque o palco não vislumbrou a cura das feridas em comunidade suada, anulando de forma asquerosa e patética o ato abismal da provação monumental impagável outrora sofrida na pele cortada e esticada cruelmente sob a cruz do sol escaldante</strong>.", "tip": "<strong>Armadilha:</strong> findar secamente longe do impacto catártico coletivo encolhe estupidamente toda a grandiosidade mitológica e chuta grosseiramente a bandeja da cura para fora das retinas e estômagos esvaziados do povão sentado que acompanhou tudo chorando as mágoas frias nos encostos carcomidos", "warn": True}
    ]
  }
}

with open(out_file, "a", encoding="utf-8") as f:
    f.write("=== geracao-ansiosa ===\n```json\n" + json.dumps(data3, ensure_ascii=False, indent=2) + "\n```\n\n")
    f.write("=== jornada-do-escritor ===\n```json\n" + json.dumps(data4, ensure_ascii=False, indent=2) + "\n```\n\n")

print("Part 2 done.")
