# -*- coding: utf-8 -*-
"""Dados de conteudo dos 13 capitulos de A Arte da Guerra (padrao rico).
Fonte: skill sun-tzu-arte-da-guerra. Consumido por gerar_arte_rico.py."""

ORDER = [
    'ch01-estimativa', 'ch02-gerenciamento-da-guerra', 'ch03-estratagemas',
    'ch04-posicoes-taticas', 'ch05-vantagens', 'ch06-pontos-fortes-e-fracos',
    'ch07-manobras', 'ch08-contingencias', 'ch09-exercito-em-marcha',
    'ch10-o-terreno', 'ch11-as-nove-situacoes', 'ch12-ataque-pelo-fogo',
    'ch13-uso-de-espioes',
]

CHAPTERS = {
'ch01-estimativa': {
    'num_label': 'CAPÍTULO I: ESTIMATIVA',
    'num_label_title': 'Capítulo I: Estimativa',
    'meta': 'Os cinco fatores fundamentais para prever o resultado de qualquer conflito antes da batalha.',
    'intro': 'A guerra é o campo onde vida e morte são determinadas — não pode ser conduzida sem cálculo. Sun Tzu abre o tratado com a tese central: a vitória se decide <strong>antes</strong> da batalha, pela análise ponderada de cinco fatores fundamentais.',
    'cards': [
        {'icon': 'balance', 'wide': True, 'title': 'Os Cinco Fatores da Guerra',
         'body': 'Todo conflito é regido por cinco pilares: <strong>Caminho</strong> (alinhamento entre líder e povo), <strong>Clima</strong> (o momento), <strong>Terreno</strong> (a posição), <strong>Comando</strong> (as virtudes do general) e <strong>Doutrina</strong> (organização e logística).',
         'tip': 'Use os cinco fatores como checklist antes de qualquer decisão estratégica importante — quem domina mais fatores, vence.',
         'details': 'As cinco virtudes que compõem o fator Comando são inteligência, probidade, benevolência, coragem e severidade — e devem coexistir em equilíbrio. O Caminho (Tao) é o mais profundo: quando o povo compartilha o propósito do líder, enfrenta qualquer perigo sem temer pela vida.'},
        {'icon': 'checklist', 'title': 'As Sete Perguntas Estratégicas',
         'body': 'Um sistema de avaliação comparativa entre forças: qual lado tem o povo mais alinhado, o comandante mais hábil, vantagem de clima e terreno, disciplina mais efetiva, tropas mais treinadas e recompensas mais justas?',
         'tip': 'Funciona como due diligence competitiva: responda cada questão objetivamente e o lado com mais pontos vencerá.'},
        {'icon': 'mask', 'title': 'O Princípio da Dissimulação',
         'body': 'Toda operação tem na dissimulação sua qualidade básica: <strong>se capaz, finja incapacidade</strong>; se pronto, finja despreparo; se perto, pareça longe.',
         'tip': 'A aparência deve sempre contradizer a realidade — é um multiplicador de força que não custa nada.',
         'details': 'Da dissimulação derivam as táticas de provocação: o inimigo orgulhoso deve ser provocado; o descansado, desgastado; o unido, dividido. Cada fraqueza emocional tem uma exploração correspondente.'},
        {'icon': 'temple', 'title': 'Os Cálculos no Templo',
         'body': 'A guerra se decide na análise prévia, não no campo. "O lado que <strong>contar mais pontos</strong> vencerá; o que contar menos, perderá."',
         'tip': 'Antes de agir, faça a conta. Quem entra em conflito sem ponderar já decidiu o resultado.'},
        {'icon': 'alert', 'warning': True, 'title': 'Anti-padrão: Agir sem Calcular',
         'body': 'Entrar em conflito sem ponderar os cinco fatores é caminhar para a derrota. A transparência total também é fatal: <strong>revelar suas capacidades reais elimina a vantagem da surpresa</strong>.',
         'tip': 'Estratégias de guerras passadas não servem: cada situação exige análise nova.'},
    ],
    'lessons': [
        'A guerra se decide antes de começar — pelo cálculo prévio dos cinco fatores fundamentais.',
        'A dissimulação é a qualidade básica de toda operação: a aparência deve sempre contradizer a realidade.',
        'O poder relativo entre forças se mede por sete perguntas comparativas objetivas.',
        'Ofereça iscas ao inimigo e ataque onde ele está desprevenido, por caminhos inesperados.',
        'As cinco virtudes do comandante — inteligência, probidade, benevolência, coragem e severidade — devem coexistir em equilíbrio.',
    ],
},
'ch02-gerenciamento-da-guerra': {
    'num_label': 'CAPÍTULO II: GERENCIAMENTO DA GUERRA',
    'num_label_title': 'Capítulo II: Gerenciamento da Guerra',
    'meta': 'A vitória rápida como imperativo econômico — campanhas prolongadas destroem o Estado.',
    'intro': 'A guerra consome recursos massivos. A vitória rápida é imperativa: campanhas prolongadas drenam o Estado, desmoralizam as tropas e convidam ataques de vizinhos oportunistas. O comandante sábio alimenta seu exército com os recursos do inimigo.',
    'cards': [
        {'icon': 'bolt', 'title': 'O Princípio da Vitória Rápida',
         'body': 'Procure sempre a vitória rápida; <strong>nunca prolongue as hostilidades</strong>. Jamais houve exemplo de país que tenha se beneficiado de uma guerra prolongada.',
         'tip': 'Defina objetivos claros, concentre recursos e execute com velocidade — toda demora tem custo exponencial.'},
        {'icon': 'cascade', 'wide': True, 'title': 'A Cascata de Deterioração',
         'body': 'O prolongamento dispara uma reação em cadeia: <strong>armas desgastadas → provisões insuficientes → tropas desmoralizadas → forças esgotadas → ataque dos vizinhos</strong>.',
         'tip': 'Use isto para avaliar o risco de qualquer projeto que se estenda além do prazo: cada etapa alimenta a próxima.',
         'details': 'Os custos são concretos: campanhas longas podem consumir 70% da riqueza do povo e 60% da renda do Estado. Manter um exército distante empobrece tanto o tesouro quanto a população, que arca com transporte e provisões.'},
        {'icon': 'coins', 'title': 'As Provisões do Inimigo',
         'body': 'Consumir <strong>um zhong de comida do inimigo equivale a vinte da própria terra</strong>. O general sábio se abastece no território adversário.',
         'tip': 'Aproveitar a infraestrutura do concorrente é cerca de 20x mais eficiente do que sustentar tudo a partir da própria base.'},
        {'icon': 'trophy', 'title': 'Despojos e Moral',
         'body': 'Distribuir os bens capturados como recompensa mantém a moral alta, e tratar bem os prisioneiros <strong>converte inimigos em aliados</strong>.',
         'tip': 'Recompense quem contribui para a vitória — a moral é um recurso que se administra, não um acaso.'},
        {'icon': 'alert', 'warning': True, 'title': 'Anti-padrão: A Campanha Prolongada',
         'body': 'Convocar forças repetidamente e ignorar os custos reais (econômico, moral, político) demonstra planejamento falho. <strong>Nunca houve benefício no prolongamento.</strong>',
         'tip': 'Pense em cada dia de operação como "mil barras de ouro": o custo de oportunidade é real e crescente.'},
    ],
    'lessons': [
        'Vitória rápida é imperativa — toda demora tem custo exponencial.',
        'Alimente seu exército com os recursos do inimigo: 1 unidade dele vale 20 suas.',
        'Recompense quem contribui para a vitória para manter a moral elevada.',
        'Trate bem os capturados — eles podem se tornar seus aliados.',
    ],
},
'ch03-estratagemas': {
    'num_label': 'CAPÍTULO III: ESTRATAGEMAS',
    'num_label_title': 'Capítulo III: Estratagemas',
    'meta': 'Vencer sem lutar, a lei da proporção de forças e o framework do autoconhecimento.',
    'intro': 'A excelência máxima não é vencer cem batalhas, mas <strong>subjugar o inimigo sem lutar</strong>. Este capítulo estabelece a hierarquia da estratégia e a máxima mais famosa de Sun Tzu: conhecer a si mesmo e ao inimigo é a chave da invencibilidade.',
    'cards': [
        {'icon': 'hierarchy', 'wide': True, 'title': 'A Hierarquia da Excelência',
         'body': 'Quatro níveis de política militar, do melhor ao pior: <strong>atacar a estratégia</strong> do inimigo → atacar suas <strong>alianças</strong> → atacar seus <strong>soldados</strong> → sitiar suas <strong>cidades</strong> (último recurso).',
         'tip': 'Suba o nível da disputa: quanto mais alto na hierarquia você resolve, menor o custo e o risco.',
         'details': '"Obter cem vitórias em cem batalhas não é o máximo da excelência. A máxima excelência é subjugar o inimigo sem lutar." Atacar cidades fortificadas é a pior política — exige três meses de preparo e sacrifica um terço dos soldados.'},
        {'icon': 'ratio', 'wide': True, 'title': 'A Lei da Proporção de Forças',
         'body': 'A tática se ajusta à razão numérica entre as forças.',
         'list': [
             '<strong>10 para 1</strong> → cerque completamente.',
             '<strong>5 para 1</strong> → ataque diretamente.',
             '<strong>2 para 1</strong> → flanqueie pelos dois lados.',
             '<strong>1 para 1</strong> → divida as forças do inimigo.',
             '<strong>Inferior</strong> → defenda com habilidade.',
             '<strong>Muito inferior</strong> → retire-se estrategicamente.',
         ],
         'tip': 'Uma startup com 1/5 dos recursos do concorrente não ataca de frente: defende um nicho e recua quando pressionada.'},
        {'icon': 'brain', 'title': 'O Framework do Autoconhecimento',
         'body': 'A máxima fundamental: <strong>conhecer a si mesmo e ao inimigo</strong> garante vitória em todas as batalhas; conhecer só a si mesmo, metade das chances; não conhecer nenhum, derrota certa.',
         'tip': 'Antes de competir, mapeie com honestidade as duas forças — a ignorância sobre si é tão fatal quanto sobre o rival.'},
        {'icon': 'crown', 'title': 'A Interferência do Soberano',
         'body': 'O comandante é o equilíbrio da carruagem do Estado. O governante que dá ordens <strong>sem conhecer a situação operacional</strong> causa confusão e sabota o próprio exército.',
         'tip': 'Proteja quem executa da microgestão de quem não está no campo: autoridade sem contexto destrói.'},
    ],
    'lessons': [
        'A vitória suprema é vencer sem combater — ataque estratégias, não pessoas.',
        'Adapte a tática à proporção de forças: nunca ignore a matemática do confronto.',
        'Autoconhecimento + conhecimento do inimigo = invencibilidade.',
        'Proteja o comando da interferência política desinformada.',
    ],
},
'ch04-posicoes-taticas': {
    'num_label': 'CAPÍTULO IV: POSIÇÕES TÁTICAS',
    'num_label_title': 'Capítulo IV: Posições Táticas',
    'meta': 'A invencibilidade depende de você; a derrota do inimigo depende dos erros dele.',
    'intro': 'A invencibilidade depende de você; a derrota do inimigo depende dos erros dele. O perito torna-se <strong>invencível primeiro</strong> e só então espera a oportunidade de vencer. A vitória pode ser prevista, mas não forçada.',
    'cards': [
        {'icon': 'shield', 'wide': True, 'title': 'O Princípio da Invencibilidade',
         'body': 'Tornar-se invencível está sob <strong>seu controle</strong>; derrotar o inimigo depende dos erros <strong>dele</strong>. Construa uma posição inabalável antes de buscar vulnerabilidades no adversário.',
         'tip': 'Priorize sempre fortalecer-se antes de atacar: a base sólida é a única variável que você controla por inteiro.',
         'details': 'Por isso a vitória do perito "não excede o bom senso": ele vence quando a vitória já era facilmente previsível, porque preparou as condições. A pessoa pode predizer uma vitória, mas não pode forçá-la.'},
        {'icon': 'sword', 'title': 'Ataque vs. Defesa',
         'body': 'Quando <strong>não há</strong> chance de vitória, defenda; quando <strong>há</strong>, ataque. A defesa cobre o que falta; o ataque revela a superabundância de força.',
         'tip': 'Não inverta a ordem: defender é o estado padrão até as condições de ataque estarem garantidas.'},
        {'icon': 'checklist', 'title': 'As Cinco Regras Militares',
         'body': 'O planejamento segue uma sequência: <strong>análise do terreno → cálculo de recursos → capacidade logística → comparação de forças → previsão da vitória</strong>.',
         'tip': 'Cada etapa alimenta a seguinte — pular uma compromete toda a previsão.'},
        {'icon': 'mountain', 'title': 'As Águas Represadas',
         'body': 'O exército vitorioso pesa como <strong>cem quilos contra gramas</strong>. A vantagem decisiva é como água acumulada que se libera de uma altura de dez mil pés.',
         'tip': 'Acumule vantagens em silêncio e libere-as de uma só vez, no momento certo — não as gaste aos poucos.'},
    ],
    'lessons': [
        'Torne-se invencível primeiro, depois busque as oportunidades.',
        'A vitória não se força — ela surge da preparação das condições.',
        'Siga os cinco elementos em sequência: terreno → recursos → logística → comparação → previsão.',
        'Acumule vantagens como águas represadas e libere-as no momento exato.',
    ],
},
'ch05-vantagens': {
    'num_label': 'CAPÍTULO V: VANTAGENS',
    'num_label_title': 'Capítulo V: Vantagens',
    'meta': 'Combinar táticas frontais e de surpresa infinitamente, como cinco notas geram melodias sem fim.',
    'intro': 'A arte da guerra se resume a combinar <strong>táticas frontais e de surpresa</strong> infinitamente — como cinco notas musicais produzem melodias sem fim. O comandante habilidoso explora a vantagem da posição, não a bravura individual.',
    'cards': [
        {'icon': 'music', 'wide': True, 'title': 'Frontal + Surpresa',
         'body': 'Há apenas duas operações fundamentais, mas suas combinações são <strong>infinitas</strong>: use o frontal para fixar o inimigo e o surpresa para destruí-lo, alternando entre ambos continuamente.',
         'tip': 'Como cinco notas, cinco cores e cinco sabores geram combinações inesgotáveis, dois movimentos bastam — o segredo está na alternância.',
         'details': 'Tudo depende da organização: a desordem nasce da ordem, a covardia da coragem, a fraqueza da força. O que parece caos pode ser disciplina dissimulada para atrair o adversário.'},
        {'icon': 'target', 'title': 'O Princípio do Impulso',
         'body': 'Duas imagens definem a ação decisiva: a <strong>torrente</strong> que arrasta pedras (impulso) e o <strong>falcão</strong> que despedaça a presa num golpe (oportunidade e timing).',
         'tip': 'Acumule potencial como um arco esticado e libere no instante preciso — força sem timing se dissipa.'},
        {'icon': 'mountain', 'title': 'A Vantagem da Posição',
         'body': 'A energia vem da posição, não dos homens: uma <strong>pedra redonda rolando</strong> de uma montanha de dez mil pés é imparável por sua situação, não por seu esforço.',
         'tip': 'Coloque sua equipe numa posição favorável e o resultado virá da configuração — não da heroicidade individual.'},
        {'icon': 'people', 'title': 'Seleção e Situação',
         'body': 'O bom general <strong>seleciona os homens certos</strong> e os coloca em situações que exploram suas forças, em vez de exigir bravura de todos.',
         'tip': 'Ofereça iscas ao inimigo, mas espere-o armado e com toda a força concentrada.'},
    ],
    'lessons': [
        'Combine frontal e surpresa infinitamente — como notas musicais geram melodias sem fim.',
        'Acumule impulso e libere-o no momento preciso, como o falcão sobre a presa.',
        'Explore a vantagem da posição; não dependa da bravura individual.',
        'Ofereça iscas, mas mantenha a força concentrada e pronta.',
    ],
},
'ch06-pontos-fortes-e-fracos': {
    'num_label': 'CAPÍTULO VI: PONTOS FORTES E PONTOS FRACOS',
    'num_label_title': 'Capítulo VI: Pontos Fortes e Fracos',
    'meta': 'Mover o inimigo sem ser movido por ele; atacar os pontos fracos como água que flui para o terreno baixo.',
    'intro': 'O general competente <strong>move o inimigo e nunca é movido por ele</strong>. Chegue primeiro, seja sutil a ponto de não deixar rastros, e ataque os pontos fracos enquanto evita os fortes — como a água, que sempre flui para o terreno baixo.',
    'cards': [
        {'icon': 'flag', 'title': 'O Domínio da Iniciativa',
         'body': 'Quem <strong>chega primeiro</strong> ao campo de batalha descansa e aguarda; quem chega depois se exaure ao se apressar para o combate.',
         'tip': 'Vantagem de quem age primeiro: ocupe a posição (mercado, terreno) antes do adversário e force-o a reagir.'},
        {'icon': 'focus', 'wide': True, 'title': 'O Princípio da Concentração',
         'body': 'Concentre suas forças em <strong>um único ponto</strong> enquanto o inimigo as dispersa em dez — assim você será dez contra um no lugar que importa, mesmo sendo menor no total.',
         'tip': 'Crie superioridade local: num cenário de recursos limitados, foco vence dispersão.',
         'details': 'A sutileza extrema é a condição para isso: tão sutil que ninguém ache rastro, tão misterioso que ninguém ouça informação. Faça escaramuças para revelar onde o inimigo é forte e fraco antes de comprometer suas forças.'},
        {'icon': 'water', 'title': 'A Água Corrente',
         'body': 'As táticas devem ser como a água: <strong>evitam o terreno alto</strong> (as forças) e <strong>fluem para o baixo</strong> (as fraquezas). A forma se adapta sempre ao obstáculo.',
         'tip': 'Mantenha isto como modelo mental permanente: nunca empurre contra a força — contorne-a.'},
        {'icon': 'split', 'warning': True, 'title': 'Anti-padrão: Defender Tudo',
         'body': 'Quem toma <strong>precauções em todos os lugares</strong> será fraco em todos eles. Fortalecer cada ponto é dispersar a força até a irrelevância.',
         'tip': 'E nunca repita uma tática vitoriosa: o modo de lutar nunca permanece constante, pois cada circunstância é única.'},
    ],
    'lessons': [
        'Mova o inimigo — nunca seja movido por ele.',
        'Concentre suas forças exatamente onde o inimigo as dispersa.',
        'Seja água: flua para os pontos fracos e evite os fortes.',
        'Cada vitória é única — nunca repita a mesma tática.',
    ],
},
'ch07-manobras': {
    'num_label': 'CAPÍTULO VII: MANOBRAS',
    'num_label_title': 'Capítulo VII: Manobras',
    'meta': 'Transformar o caminho tortuoso em reto e administrar o moral como recurso decisivo.',
    'intro': 'A arte de manobrar está em <strong>transformar desvantagem em vantagem</strong> — caminhos tortuosos em retas. A manobra carrega tanto oportunidade quanto perigo: mover-se rápido demais sacrifica equipamentos, devagar demais perde a hora. O moral é o fator decisivo.',
    'cards': [
        {'icon': 'compass', 'title': 'O Caminho Tortuoso em Reto',
         'body': 'Engane o inimigo conduzindo-o por uma <strong>rota tortuosa</strong> enquanto você toma o atalho direto — partindo depois e chegando antes.',
         'tip': 'O caminho aparentemente mais longo, se desvia o adversário, pode ser o mais curto até a posição favorável.'},
        {'icon': 'flag', 'wide': True, 'title': 'A Regra do Moral',
         'body': 'O espírito do exército segue um ciclo: <strong>agudo no início</strong>, relaxado no meio, <strong>fraco no fim</strong>. O bom comandante evita o inimigo quando seu moral está afiado e o ataca quando esmorece.',
         'tip': 'Cronometre os engajamentos pelo estado psicológico do adversário, não apenas pela posição física.',
         'details': 'Para administrar exércitos grandes, gongos, tambores e bandeiras unificam os movimentos. Quando o exército age como um só, o corajoso não avança sozinho e o covarde não recua sozinho — a coesão neutraliza os extremos individuais.'},
        {'icon': 'wind', 'title': 'As Cinco Qualidades de Movimento',
         'body': 'Adapte a postura ao contexto: <strong>rápido como o vento</strong>, estável como a floresta, feroz como o fogo, firme como a montanha e inescrutável como as nuvens.',
         'tip': 'Cada situação pede uma dessas cinco posturas — a versatilidade é a marca do bom estrategista.'},
        {'icon': 'alert', 'warning': True, 'title': 'Anti-padrão: A Marcha Forçada',
         'body': 'Correr cem li sem parar para alcançar uma vantagem faz <strong>apenas um décimo das tropas chegar a tempo</strong> — e os generais são capturados.',
         'tip': 'Nunca ataque inimigo com moral elevado, em terreno alto ou com colinas o apoiando. E sempre deixe saída a um inimigo cercado.'},
    ],
    'lessons': [
        'Transforme a desvantagem em vantagem — o caminho tortuoso pode ser tornado reto.',
        'Administre o moral como recurso: ataque quando o do inimigo estiver baixo.',
        'Nunca lance ataque sobre inimigo em terreno alto ou apoiado por colinas.',
        'Deixe sempre uma rota de fuga ao inimigo cercado — o desespero o torna perigoso.',
    ],
},
'ch08-contingencias': {
    'num_label': 'CAPÍTULO VIII: CONTINGÊNCIAS',
    'num_label_title': 'Capítulo VIII: Contingências',
    'meta': 'As variáveis táticas, as cinco regras de exceção e as cinco fraquezas fatais do líder.',
    'intro': 'O general deve compreender as variáveis táticas e <strong>ponderar vantagens e desvantagens ao mesmo tempo</strong>. Nem toda oportunidade deve ser aproveitada — e há cinco fraquezas de caráter capazes de destruir qualquer líder.',
    'cards': [
        {'icon': 'map', 'title': 'As Cinco Regras de Exceção',
         'body': 'A sabedoria está em saber o que <strong>não</strong> fazer: há estradas que não se percorrem, inimigos que não se atacam, cidades que não se capturam, territórios que não se disputam e <strong>ordens do soberano que não se obedecem</strong>.',
         'tip': 'Nem toda batalha vencível vale a pena: avalie o que cada "vitória" custa antes de buscá-la.'},
        {'icon': 'people', 'wide': True, 'title': 'As Cinco Fraquezas Fatais',
         'body': 'Falhas de caráter que destroem generais.',
         'list': [
             '<strong>Valentia temerária</strong> → quem despreza a vida é morto facilmente.',
             '<strong>Covardia</strong> → quem hesita na véspera é capturado facilmente.',
             '<strong>Irascibilidade</strong> → o temperamento explosivo é provocado facilmente.',
             '<strong>Excesso de honra</strong> → o suscetível demais é envergonhado facilmente.',
             '<strong>Benevolência excessiva</strong> → quem preza demais as pessoas torna-se hesitante e passivo.',
         ],
         'tip': 'Use a lista para autoavaliação e para diagnosticar o adversário: toda virtude levada ao extremo vira vulnerabilidade.'},
        {'icon': 'balance', 'title': 'A Ponderação Dupla',
         'body': 'O general hábil pensa nos dois lados ao mesmo tempo: conhecer as <strong>vantagens</strong> garante sucesso nos planos; conhecer as <strong>desvantagens</strong> permite resolver as dificuldades antes que surjam.',
         'tip': 'A cada plano, force-se a listar também o que pode dar errado — o otimismo cego é uma fraqueza fatal.'},
        {'icon': 'shield', 'title': 'O Princípio da Prontidão',
         'body': 'Nunca conte com a <strong>probabilidade de o inimigo não vir</strong>; conte sempre com a sua própria preparação para recebê-lo.',
         'tip': 'A segurança não vem da inação do outro, e sim da sua prontidão constante.'},
    ],
    'lessons': [
        'Nem toda estrada deve ser seguida, nem toda batalha travada.',
        'Sempre pondere vantagens E desvantagens antes de agir.',
        'Nunca dependa da inação do inimigo — dependa da sua preparação.',
        'As cinco fraquezas fatais são os maiores riscos de qualquer líder.',
    ],
},
'ch09-exercito-em-marcha': {
    'num_label': 'CAPÍTULO IX: O EXÉRCITO EM MARCHA',
    'num_label_title': 'Capítulo IX: O Exército em Marcha',
    'meta': 'Posicionar-se corretamente em cada terreno e aprender a ler os sinais do inimigo.',
    'intro': 'O posicionamento certo em cada terreno é fundamental — mas o capítulo vai além: ensina o general a <strong>ler os sinais</strong> da natureza, das negociações e do comportamento das tropas para antecipar as intenções do inimigo.',
    'cards': [
        {'icon': 'mountain', 'title': 'As Quatro Leis de Posicionamento',
         'body': 'Para montanhas, rios, pântanos e planícies vale a mesma busca: <strong>terreno alto, ensolarado, com provisões e longe de perigos</strong>.',
         'tip': 'Em qualquer contexto, ocupe a posição que combina visão, recursos e segurança antes de avançar.'},
        {'icon': 'eye', 'wide': True, 'title': 'O Sistema de Sinais',
         'body': 'O comportamento revela a intenção. Árvores se movendo: o inimigo avança. Pássaros levantando voo: <strong>emboscada</strong>. Pássaros pousando no campo: acampamento abandonado. Soldados apoiados nas armas: famintos e fatigados.',
         'tip': 'Aprenda a ler indícios indiretos — eles dizem mais sobre o adversário do que as palavras dele.',
         'details': 'Nas negociações vale o mesmo: palavras moderadas acompanhadas de preparativos indicam que o inimigo vai avançar; palavras belicosas e avanços aparentes indicam que vai recuar. Recompensas excessivas revelam um general em apuros; castigos excessivos, angústia profunda na tropa.'},
        {'icon': 'crown', 'title': 'Civilidade e Disciplina',
         'body': 'Comande com <strong>humanidade para unir</strong> e com <strong>disciplina para manter na linha</strong>. Punir tropas antes de conquistar sua lealdade as torna rebeldes; não punir depois as torna inúteis.',
         'tip': 'Equilíbrio é tudo: afeto sem disciplina e disciplina sem afeto falham igualmente.'},
        {'icon': 'checklist', 'title': 'Planejar sem Menosprezar',
         'body': 'A vantagem não está no número puro: <strong>quem faz planos e não subestima o inimigo</strong> conquista o apoio dos seus homens e a vitória.',
         'tip': 'Excesso de confiança é cegueira — respeite o adversário mesmo quando estiver à frente.'},
    ],
    'lessons': [
        'Busque sempre terreno alto, ensolarado e com linhas de provisão livres.',
        'Aprenda a ler sinais — da natureza, do comportamento e das negociações.',
        'Comande com civilidade e disciplina em equilíbrio.',
        'Quem planeja e não menospreza o inimigo tem o apoio dos seus homens.',
    ],
},
'ch10-o-terreno': {
    'num_label': 'CAPÍTULO X: O TERRENO',
    'num_label_title': 'Capítulo X: O Terreno',
    'meta': 'Os seis tipos de terreno, as seis situações de derrota e a fórmula completa da vitória.',
    'intro': 'Existem <strong>seis tipos de terreno</strong> e seis situações que apontam para a derrota. O terreno é o maior aliado do comandante — e a este capítulo pertence a fórmula completa da vitória sem perigo.',
    'cards': [
        {'icon': 'map', 'wide': True, 'title': 'Os Seis Tipos de Terreno',
         'body': 'Cada terreno exige uma tática própria: <strong>acessível</strong>, <strong>traiçoeiro</strong> (fácil entrar, difícil sair), <strong>duvidoso</strong>, <strong>estreito</strong>, <strong>acidentado</strong> e <strong>distante</strong>.',
         'tip': 'Identifique o "terreno" da sua disputa antes de escolher a tática — o ambiente dita a abordagem.',
         'details': 'No terreno traiçoeiro, o perigo é a armadilha de onde não se sai. No duvidoso, a tática é fingir retirada e golpear quando o inimigo persegue. Ler o terreno é tão decisivo quanto avaliar as forças.'},
        {'icon': 'cascade', 'title': 'As Seis Situações de Derrota',
         'body': 'Fuga, negligência, deterioração, desmoronamento, desorganização e debandada — <strong>nenhuma é causada pela natureza</strong>. Todas resultam de falhas de comando.',
         'tip': 'Use a lista como diagnóstico organizacional: quando algo desmorona, procure a falha de liderança, não o azar.'},
        {'icon': 'brain', 'title': 'A Fórmula Completa da Vitória',
         'body': 'O autoconhecimento ganha um terceiro pilar: <strong>conhecer o inimigo + conhecer a si mesmo + conhecer o terreno</strong> = vitória sem perigo.',
         'tip': 'Conhecer só dois dos três deixa você com metade das chances — o terreno completa a equação.'},
        {'icon': 'people', 'title': 'Filhos Amados, não Mimados',
         'body': 'Trate os soldados como <strong>filhos amados</strong> e eles o seguirão até a morte — mas sem disciplina, viram crianças mimadas, inúteis para o combate.',
         'tip': 'Afeto e exigência andam juntos: o líder que só agrada perde a tropa quando ela mais importa.'},
    ],
    'lessons': [
        'Domine os seis tipos de terreno e suas táticas correspondentes.',
        'As seis situações de derrota são sempre culpa do comando, nunca da natureza.',
        'Conhecer inimigo + a si mesmo + o terreno = vitória sem perigo.',
        'Trate os soldados com amor E disciplina — nunca apenas um dos dois.',
    ],
},
'ch11-as-nove-situacoes': {
    'num_label': 'CAPÍTULO XI: AS NOVE SITUAÇÕES',
    'num_label_title': 'Capítulo XI: As Nove Situações',
    'meta': 'Os nove terrenos táticos, a psicologia do desespero e a coordenação da serpente Shuairan.',
    'intro': 'O terreno se classifica em <strong>nove situações táticas</strong>, cada uma exigindo uma conduta específica. A psicologia da tropa é moldada pela situação: em terreno sem saída, os soldados lutam até a morte sem precisar de ordens.',
    'cards': [
        {'icon': 'map', 'wide': True, 'title': 'Os Nove Terrenos Táticos',
         'body': 'Cada situação tem sua conduta correta.',
         'list': [
             '<strong>Dispersivo</strong> (território próprio) → unifique as tropas, não lute.',
             '<strong>Marginal</strong> (penetração rasa) → mantenha as tropas compactas.',
             '<strong>Contencioso</strong> (favorável a ambos) → não ataque; apresse a retaguarda.',
             '<strong>Aberto</strong> (acessível) → defenda o acampamento com cuidado.',
             '<strong>Convergente</strong> (cruzamento) → forme alianças com vizinhos.',
             '<strong>Crítico</strong> (penetração profunda) → assegure as provisões.',
             '<strong>Difícil</strong> (montanhas/pântanos) → atravesse rapidamente.',
             '<strong>Cercado</strong> (acesso estreito) → recorra a estratagemas.',
             '<strong>Desesperado</strong> (sem saída) → lute até o fim.',
         ],
         'tip': 'Classifique sua situação competitiva em uma das nove e siga a conduta correspondente.'},
        {'icon': 'snake', 'title': 'A Serpente de Monte Chang',
         'body': 'A Shuairan responde como um só corpo: <strong>golpeie a cabeça e o rabo ataca</strong>; golpeie o rabo e a cabeça ataca; golpeie o meio e ambos respondem.',
         'tip': 'Organize a equipe para coordenação instantânea: cada parte cobre a outra sem esperar ordem central.'},
        {'icon': 'bolt', 'title': 'A Essência das Operações',
         'body': 'Quatro elementos resumem a ação militar: <strong>velocidade</strong>, exploração de <strong>vulnerabilidades</strong>, caminhos <strong>inesperados</strong> e atacar onde o inimigo <strong>não está preparado</strong>.',
         'tip': 'Comece com a aparência inocente de uma donzela e ataque com a rapidez da lebre quando o portão se abrir.'},
        {'icon': 'lock', 'warning': True, 'title': 'O Princípio da Sem-Saída',
         'body': 'Lance soldados onde <strong>não há retirada</strong> e eles lutarão até a morte: sem escapatória, resistem; em perigo profundo, perdem o medo.',
         'tip': 'Use o comprometimento total com cuidado — é poderoso, mas o desespero é uma força que não se controla pela metade.'},
    ],
    'lessons': [
        'Classifique o terreno em uma das nove situações e siga a conduta correspondente.',
        'Soldados em terreno desesperado lutam como nunca — use isso estrategicamente.',
        'Velocidade + exploração de vulnerabilidades = essência da operação.',
        'Seja como a serpente Shuairan: coordenação instantânea entre todas as partes.',
    ],
},
'ch12-ataque-pelo-fogo': {
    'num_label': 'CAPÍTULO XII: O ATAQUE PELO FOGO',
    'num_label_title': 'Capítulo XII: O Ataque pelo Fogo',
    'meta': 'A arma do fogo, o timing das condições e a lição maior: nunca empreender guerra por ira.',
    'intro': 'O fogo é uma arma poderosa que exige timing preciso. Mas a lição mais profunda do capítulo é outra: <strong>nunca empreenda guerra por ira</strong>. Um Estado destruído não pode ser reavivado; um morto não pode ser ressuscitado. O soberano iluminado age com prudência.',
    'cards': [
        {'icon': 'fire', 'wide': True, 'title': 'Os Cinco Modos de Ataque pelo Fogo',
         'body': 'O fogo destrói a <strong>infraestrutura</strong>, não só a força: queimar tropas, provisões, equipamentos, arsenais e linhas de reabastecimento.',
         'tip': 'Ataque indireto: muitas vezes destruir o que sustenta o adversário vale mais que enfrentá-lo de frente.',
         'details': 'O fogo pode destruir, a água pode bloquear — mas a água não priva o inimigo de suas provisões. E vencer a batalha sem consolidar o ganho é puro desperdício: ganhar sem firmar o resultado dissipa tempo e recursos.'},
        {'icon': 'hourglass', 'title': 'O Momento Oportuno',
         'body': 'O ataque pelo fogo depende de <strong>condições externas</strong>: tempo seco, ventos fortes e o instante certo. Nunca ataque contra o vento.',
         'tip': 'Coordene ações de alto impacto com as condições do ambiente — o timing externo decide tanto quanto a força.'},
        {'icon': 'alert', 'warning': True, 'title': 'A Prudência Suprema',
         'body': 'A maior lição militar é um freio emocional: <strong>nunca aja por ira, nunca envie tropas por indignação</strong>. O homem enfurecido volta a ser feliz, mas um Estado destruído nunca revive.',
         'tip': 'Decisões tomadas na emoção são irreversíveis — separe sempre o impulso do plano.'},
    ],
    'lessons': [
        'Destrua a infraestrutura do inimigo, não apenas suas forças.',
        'Cronometre as ações com as condições externas favoráveis.',
        'Nunca aja por ira — decisões emocionais são irreversíveis.',
        'Consolide cada vitória antes de buscar a próxima.',
    ],
},
'ch13-uso-de-espioes': {
    'num_label': 'CAPÍTULO XIII: O USO DE ESPIÕES',
    'num_label_title': 'Capítulo XIII: O Uso de Espiões',
    'meta': 'Os cinco tipos de espiões, a centralidade do espião convertido e a inteligência como alicerce.',
    'intro': 'A espionagem é o <strong>alicerce de todas as operações militares</strong>. Investir em inteligência custa infinitamente menos que manter um exército em campanha — e o espião convertido é a peça central de toda a rede.',
    'cards': [
        {'icon': 'spy', 'wide': True, 'title': 'Os Cinco Tipos de Espiões',
         'body': 'Uma rede completa de inteligência.',
         'list': [
             '<strong>Nativos</strong> → moradores locais do território inimigo.',
             '<strong>Internos</strong> → funcionários do inimigo trazidos ao seu lado.',
             '<strong>Convertidos</strong> → espiões inimigos que passam a trabalhar para você.',
             '<strong>Descartáveis</strong> → seus agentes que levam informação falsa ao inimigo.',
             '<strong>Indispensáveis</strong> → agentes confiáveis que circulam entre os dois lados.',
         ],
         'tip': 'Estruture qualquer coleta de informação combinando os cinco tipos — cada um cobre um ângulo.'},
        {'icon': 'network', 'title': 'O Espião Convertido',
         'body': 'Toda a rede repousa sobre o convertido: por meio dele se recrutam nativos e internos e se enganam os descartáveis. Por isso <strong>deve ser o mais recompensado de todos</strong>.',
         'tip': 'Identifique a peça que destrava todas as outras e invista nela de forma desproporcional.'},
        {'icon': 'brain', 'title': 'As Três Qualidades do Spymaster',
         'body': 'Gerir inteligência exige <strong>astúcia</strong> para empregar os espiões, <strong>humanidade e justiça</strong> para retê-los e <strong>atenção sutil</strong> para extrair a verdade do que relatam.',
         'tip': 'Só quem é benevolente e sábio sabe usar espiões; só quem é delicado e sutil extrai deles a verdade.'},
        {'icon': 'lock', 'warning': True, 'title': 'Conhecimento Vem de Pessoas',
         'body': 'O conhecimento prévio <strong>não vem de presságios, astrologia ou analogias históricas</strong> — vem de pessoas que conhecem a situação do inimigo. E o segredo é vital: uma só fuga de informação mata toda a rede.',
         'tip': 'Economizar em inteligência para gastar anos às cegas é o maior dos desperdícios.'},
    ],
    'lessons': [
        'Espionagem é o alicerce de todo movimento militar — invista generosamente.',
        'O espião convertido é a peça central de toda a rede de inteligência.',
        'Informação vem de pessoas, não de adivinhação ou de analogias históricas.',
        'Segredo absoluto é vital: uma única falha mata toda a rede.',
    ],
},
}
